import "../quiz_question.dart";

const _subject = "Biology";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// WAEC/NECO Biology — Section 3: Ecology. Covers basic ecological concepts,
/// biomes, ecosystem functioning (food chains/webs, cycles), ecological
/// factors, population studies, and conservation of natural resources.
List<QuizQuestion> buildBiologyEcologyQuestions() {
  return [
    ..._basicConcepts,
    ..._biomes,
    ..._ecosystemFunctioning,
    ..._ecologicalFactors,
    ..._populationStudies,
    ..._conservation,
  ];
}

final _basicConcepts = [
  _q("The study of the interactions between living organisms and their environment is called:",
      ["Ecology", "Genetics", "Physiology", "Taxonomy"], "Ecology",
      "Ecology is the scientific study of interactions among organisms and between organisms and their physical environment."),
  _q("The part of the Earth (land, water, and atmosphere) where living organisms exist is called the:",
      ["Biosphere", "Habitat", "Ecosystem", "Biome"], "Biosphere",
      "The biosphere is the global sum of all ecosystems, encompassing every region of the planet that supports life."),
  _q("The specific place where an organism normally lives is called its:",
      ["Habitat", "Niche", "Population", "Community"], "Habitat",
      "A habitat is the physical location or environment where a particular organism naturally lives."),
  _q("The specific role and position an organism occupies within its environment, including its interactions with other organisms and resources, is called its:",
      ["Ecological niche", "Habitat", "Biome", "Population"], "Ecological niche",
      "An ecological niche describes an organism's specific functional role, including its diet, habitat use, and interactions within the ecosystem."),
  _q("All the individuals of the same species living in a particular area at the same time form a:",
      ["Population", "Community", "Ecosystem", "Biome"], "Population",
      "A population consists of all members of one species inhabiting a specific geographic area at a given time."),
  _q("All the different populations of various species living and interacting together in a particular area form a:",
      ["Community", "Population", "Habitat", "Niche"], "Community",
      "A community consists of all the interacting populations of different species that coexist within a defined area."),
  _q("A community of living organisms interacting with each other and with their non-living (physical) environment forms a(n):",
      ["Ecosystem", "Population", "Biosphere", "Niche"], "Ecosystem",
      "An ecosystem includes both the biotic community and the abiotic (non-living) factors of the environment, all interacting together."),
  _q("Which of the following best distinguishes a habitat from a niche?",
      ["A habitat is where an organism lives; a niche is its functional role within that habitat", "A habitat and a niche mean exactly the same thing", "A niche is always larger than a habitat", "A habitat only applies to plants"],
      "A habitat is where an organism lives; a niche is its functional role within that habitat",
      "A habitat is simply the physical location an organism occupies, while its niche describes its role, behaviour, and interactions within that location."),
  _q("Factors in the environment that are non-living, such as temperature, light, and water, are called:",
      ["Abiotic factors", "Biotic factors", "Ecological factors only", "Population factors"], "Abiotic factors",
      "Abiotic factors are the physical and chemical (non-living) components of an environment that influence organisms."),
  _q("Factors in the environment that arise from living organisms, such as predation and competition, are called:",
      ["Biotic factors", "Abiotic factors", "Physical factors", "Climatic factors"], "Biotic factors",
      "Biotic factors are the living components of an ecosystem that affect other organisms, including competition, predation, and disease."),
  _q("Two species of birds competing for the same limited food supply in a habitat is an example of:",
      ["Competition (a biotic factor)", "Predation", "Symbiosis", "Parasitism"], "Competition (a biotic factor)",
      "Competition occurs when two or more organisms require the same limited resource, such as food, and is a biotic interaction."),
  _q("A relationship in which one organism benefits while the other is harmed, such as a lion hunting a zebra, is called:",
      ["Predation", "Mutualism", "Commensalism", "Competition"], "Predation",
      "Predation is an interaction where a predator captures and consumes another organism (the prey) for food."),
  _q("A relationship in which both organisms benefit from their interaction, such as bees pollinating flowers, is called:",
      ["Mutualism", "Predation", "Parasitism", "Competition"], "Mutualism",
      "Mutualism is a symbiotic relationship in which both participating species derive benefit from their interaction."),
  _q("A relationship in which one organism benefits while the other is neither helped nor harmed is called:",
      ["Commensalism", "Mutualism", "Parasitism", "Predation"], "Commensalism",
      "Commensalism describes a relationship where one species benefits, and the other experiences neither significant harm nor benefit."),
  _q("A relationship in which one organism (the parasite) benefits at the expense of another (the host), which is harmed, is called:",
      ["Parasitism", "Mutualism", "Commensalism", "Predation only"], "Parasitism",
      "Parasitism is a relationship where the parasite lives on or in a host, gaining nutrients while typically harming the host."),
  _q("An organism that manufactures its own organic food from inorganic materials, usually through photosynthesis, is called a(n):",
      ["Producer (autotroph)", "Consumer (heterotroph)", "Decomposer", "Predator"], "Producer (autotroph)",
      "Producers, such as green plants, are autotrophs that synthesise their own food, forming the base of most food chains."),
  _q("An organism that cannot make its own food and must obtain organic nutrients by consuming other organisms is called a(n):",
      ["Consumer (heterotroph)", "Producer (autotroph)", "Decomposer only", "Autotroph"], "Consumer (heterotroph)",
      "Consumers are heterotrophic organisms that obtain energy and nutrients by feeding on other organisms."),
  _q("An organism that feeds directly on producers (plants) is classified as a:",
      ["Primary consumer (herbivore)", "Secondary consumer (carnivore)", "Tertiary consumer", "Decomposer"], "Primary consumer (herbivore)",
      "Primary consumers, or herbivores, feed directly on producers such as plants, occupying the second trophic level."),
  _q("An organism that feeds on primary consumers (herbivores) is classified as a:",
      ["Secondary consumer (carnivore)", "Primary consumer", "Producer", "Decomposer"], "Secondary consumer (carnivore)",
      "Secondary consumers are typically carnivores that feed on primary consumers (herbivores)."),
  _q("Organisms such as bacteria and fungi that break down dead organic matter, releasing nutrients back into the environment, are called:",
      ["Decomposers", "Producers", "Primary consumers", "Secondary consumers"], "Decomposers",
      "Decomposers break down dead plants, animals, and waste material, recycling nutrients back into the ecosystem."),
  _q("Which of the following best explains the ecological importance of decomposers?",
      ["They recycle nutrients from dead organisms back into the soil and environment for producers to reuse", "They produce food for the entire ecosystem", "They are the top predators in every food chain", "They compete directly with producers for sunlight"],
      "They recycle nutrients from dead organisms back into the soil and environment for producers to reuse",
      "Decomposers are essential because they break down organic matter, releasing nutrients that can then be reused by producers, completing nutrient cycles."),
  _q("An organism that feeds on dead and decaying organic matter, such as a vulture feeding on carcasses, is called a:",
      ["Scavenger", "Predator", "Parasite", "Producer"], "Scavenger",
      "A scavenger, like a vulture or hyena, feeds on the remains of dead organisms rather than hunting live prey."),
  _q("Which of the following best distinguishes a scavenger from a decomposer?",
      ["A scavenger consumes visible chunks of dead matter, while a decomposer breaks down organic matter chemically at a microscopic level", "Scavengers and decomposers mean exactly the same thing", "Decomposers only exist in aquatic ecosystems", "Scavengers never eat dead animals"],
      "A scavenger consumes visible chunks of dead matter, while a decomposer breaks down organic matter chemically at a microscopic level",
      "Scavengers, such as vultures, physically consume dead organic material, while decomposers, such as bacteria and fungi, chemically break it down at a microscopic level, completing the process of decay."),
  _q("Two species requiring the exact same ecological niche in the same habitat would most likely experience intense:",
      ["Competition", "Mutualism", "Commensalism", "Parasitism"], "Competition",
      "When two species have very similar niche requirements, they compete intensely for the same limited resources, which can lead to the exclusion of one species (competitive exclusion)."),
  _q("Lichen, formed from a mutualistic relationship between fungi and algae, illustrates the benefit that algae gain by:",
      ["Receiving protection and structural support from the fungus, while photosynthesising to provide food", "Receiving no benefit at all from the fungus", "Being parasitised by the fungus", "Consuming the fungus for food"], "Receiving protection and structural support from the fungus, while photosynthesising to provide food",
      "In the lichen relationship, algae provide food through photosynthesis, while the fungus provides structural support, moisture retention, and protection — benefiting both partners."),
  _q("Cattle egrets that follow grazing cattle to feed on insects disturbed by the cattle's movement, without harming or benefiting the cattle, exemplify:",
      ["Commensalism", "Mutualism", "Parasitism", "Predation"], "Commensalism",
      "The egrets benefit by gaining easier access to food (insects), while the cattle are essentially unaffected, making this a classic example of commensalism."),
  _q("Two predator species hunting the exact same prey within a shared habitat exemplifies which type of biotic interaction?",
      ["Interspecific competition", "Mutualism", "Parasitism", "Commensalism"], "Interspecific competition",
      "When two different species compete for the same limited resource, such as prey, this is termed interspecific competition, occurring between different species."),
  _q("Competition occurring between members of the same species for a limited resource, such as territory or mates, is called:",
      ["Intraspecific competition", "Interspecific competition", "Mutualism", "Predation"], "Intraspecific competition",
      "Intraspecific competition occurs between individuals of the same species competing for shared limited resources, such as food, mates, or territory."),
  _q("Which of the following best describes 'camouflage' as an adaptation in prey species?",
      ["Blending in with the surroundings to avoid detection by predators", "Producing loud warning sounds to scare off predators", "Growing extremely large in size", "Reproducing extremely rapidly"], "Blending in with the surroundings to avoid detection by predators",
      "Camouflage allows prey species to visually blend into their environment, reducing the likelihood of being detected and captured by predators."),
  _q("Which of the following best describes 'mimicry' as an anti-predator adaptation, such as a harmless insect resembling a wasp?",
      ["An organism evolving to resemble another species, often a dangerous one, to deter predators", "An organism physically merging with another species", "An organism changing its habitat entirely", "An organism losing all its natural predators permanently"],
      "An organism evolving to resemble another species, often a dangerous one, to deter predators",
      "Mimicry involves a harmless species evolving physical features resembling a dangerous or unpalatable species, deterring predators that have learned to avoid the model species."),
  _q("Which of the following is an example of a chemical defence mechanism used by some organisms against predators?",
      ["Producing toxic or bad-tasting compounds", "Growing brightly coloured feathers only for mating displays", "Living in large herds only", "Migrating to a new location"], "Producing toxic or bad-tasting compounds",
      "Some organisms produce toxins or unpleasant-tasting chemicals as a defence mechanism, discouraging predators from consuming them."),
  _q("Which of the following best describes 'commensalism' using the example of barnacles attached to a whale?",
      ["Barnacles benefit by gaining access to food-rich waters as the whale swims, while the whale is largely unaffected", "Both the barnacles and the whale benefit equally", "The whale benefits while the barnacles are harmed", "Both species are harmed by the interaction"],
      "Barnacles benefit by gaining access to food-rich waters as the whale swims, while the whale is largely unaffected",
      "Barnacles attached to a whale gain transportation to nutrient-rich waters, benefiting from the relationship, while the whale experiences little to no significant effect, making this a classic case of commensalism."),
  _q("Which of the following best describes an example of mutualism between a specific plant and its pollinator?",
      ["A flower providing nectar to a bee, while the bee simultaneously transfers pollen, aiding the plant's reproduction", "A flower being consumed entirely by an insect with no benefit to the plant", "An insect laying eggs inside a flower, harming the plant", "A plant absorbing nutrients from a dead insect"],
      "A flower providing nectar to a bee, while the bee simultaneously transfers pollen, aiding the plant's reproduction",
      "This mutualistic relationship benefits both species: the bee receives nectar as food, while the plant benefits from pollination, aiding its reproductive success."),
  _q("Which of the following best explains why a parasite generally does not kill its host quickly, unlike many predators that kill their prey?",
      ["A parasite typically depends on the host remaining alive to continue providing it with nutrients over time", "Parasites always kill their hosts immediately upon contact", "Parasites and predators use identical survival strategies", "Parasites do not require any nutrients from their host"],
      "A parasite typically depends on the host remaining alive to continue providing it with nutrients over time",
      "Since parasites often rely on their host for an extended period to obtain nutrients, it is generally advantageous for the parasite if the host survives, at least long enough to complete the parasite's life cycle."),
  _q("Which of the following best describes an 'ectoparasite', such as a tick or flea?",
      ["A parasite that lives on the outer surface of its host's body", "A parasite that lives entirely inside the host's internal organs", "An organism that provides mutual benefit to its host", "A parasite that only affects plants"], "A parasite that lives on the outer surface of its host's body",
      "Ectoparasites, like ticks and fleas, live on the external surface of their host, feeding on blood or skin without entering the body."),
  _q("Which of the following best describes an 'endoparasite', such as a tapeworm?",
      ["A parasite that lives inside the body of its host", "A parasite that lives only on the outer surface of its host", "An organism that benefits its host equally", "A parasite that cannot survive within any living organism"], "A parasite that lives inside the body of its host",
      "Endoparasites, like tapeworms, live inside the body of their host, often within the digestive system or other internal organs."),
];

final _biomes = [
  _q("A large-scale ecological community characterised by distinct climate, vegetation, and animal life, such as a desert or rainforest, is called a:",
      ["Biome", "Habitat", "Niche", "Population"], "Biome",
      "A biome is a large geographic region characterised by particular climate conditions and the plant and animal communities adapted to it."),
  _q("Which local biome is characterised by high rainfall, dense vegetation with multiple canopy layers, and very high biodiversity?",
      ["Tropical rainforest", "Savanna", "Desert", "Tundra"], "Tropical rainforest",
      "Tropical rainforests receive abundant rainfall and support extremely dense, layered vegetation and the highest biodiversity of any biome."),
  _q("Which local biome is characterised by grassland interspersed with scattered trees, distinct wet and dry seasons, and large herds of grazing animals?",
      ["Savanna", "Tropical rainforest", "Mangrove swamp", "Desert"], "Savanna",
      "Savannas feature open grassland with scattered trees, marked seasonal rainfall variation, and are home to large populations of grazing herbivores."),
  _q("Which local biome, found along tropical and subtropical coastlines, is characterised by salt-tolerant trees with specialised root systems?",
      ["Mangrove swamp", "Savanna", "Desert", "Tundra"], "Mangrove swamp",
      "Mangrove swamps occur along sheltered coastlines and feature salt-tolerant trees with specialised roots (like prop roots) that cope with waterlogged, saline soil."),
  _q("Which of the following adaptations helps mangrove trees survive in waterlogged, low-oxygen soil?",
      ["Specialised aerial roots (pneumatophores) that project above the mud to absorb oxygen", "Extremely long taproots that avoid water entirely", "Complete absence of any root system", "Roots that grow only in dry season"],
      "Specialised aerial roots (pneumatophores) that project above the mud to absorb oxygen",
      "Pneumatophores are specialised root structures that rise above the waterlogged mud, allowing mangroves to obtain oxygen for respiration."),
  _q("Which world biome is characterised by extremely cold temperatures, permanently frozen subsoil (permafrost), and low-growing vegetation like mosses and lichens?",
      ["Tundra", "Desert", "Tropical rainforest", "Savanna"], "Tundra",
      "The tundra biome has a harsh, cold climate with permafrost that limits plant growth to low, hardy vegetation such as mosses and lichens."),
  _q("Which world biome is characterised by very low rainfall, extreme temperature fluctuations, and organisms adapted to conserve water?",
      ["Desert", "Tundra", "Tropical rainforest", "Temperate forest"], "Desert",
      "Deserts receive minimal rainfall and experience large temperature swings, so organisms there have adaptations for water conservation."),
  _q("Which world biome is characterised by moderate rainfall, distinct seasons, and deciduous trees that shed their leaves in autumn?",
      ["Temperate forest", "Tropical rainforest", "Desert", "Tundra"], "Temperate forest",
      "Temperate forests experience four distinct seasons, with many trees being deciduous, shedding leaves to conserve resources during colder months."),
  _q("Which of the following adaptations is common among desert animals to help them survive extreme heat and limited water?",
      ["Nocturnal behaviour, active mainly at night to avoid daytime heat", "Thick, insulating fur worn during hot daytime hours only", "Requiring large amounts of water daily", "Living exclusively in ponds"],
      "Nocturnal behaviour, active mainly at night to avoid daytime heat",
      "Many desert animals are nocturnal, being active during the cooler night hours to avoid extreme daytime heat and reduce water loss."),
  _q("Which of the following adaptations is common among plants living in desert biomes?",
      ["Thick, waxy cuticles and reduced leaf surface area to minimise water loss", "Very large, thin leaves to maximise photosynthesis", "Shallow roots that never reach groundwater", "An absence of any water-storage tissue"],
      "Thick, waxy cuticles and reduced leaf surface area to minimise water loss",
      "Desert plants often have thick cuticles and small or modified leaves (like spines) to reduce water loss through transpiration."),
  _q("Which biome would you expect to have the lowest species diversity due to its extreme, harsh climate?",
      ["Tundra", "Tropical rainforest", "Savanna", "Mangrove swamp"], "Tundra",
      "The tundra's extremely cold climate and short growing season limit the variety of species that can survive there, giving it relatively low biodiversity."),
  _q("Fish adapted to life in mangrove swamps and estuaries often show tolerance to a wide range of which abiotic factor, due to the mixing of fresh and salt water?",
      ["Salinity", "Light intensity", "Wind speed", "Altitude"], "Salinity",
      "Organisms in mangrove and estuarine environments must tolerate fluctuating salinity levels caused by the mixing of freshwater and seawater."),
  _q("Which of the following best explains why tropical rainforests support the greatest biodiversity of any terrestrial biome?",
      ["Consistently warm temperatures and high rainfall throughout the year create ideal conditions for plant growth, supporting complex food webs", "They receive the least amount of sunlight of any biome", "They have very low and unpredictable rainfall", "Their extremely cold climate favours a wide range of species"],
      "Consistently warm temperatures and high rainfall throughout the year create ideal conditions for plant growth, supporting complex food webs",
      "The consistently warm, wet conditions in tropical rainforests support lush plant growth year-round, providing the foundation for an exceptionally complex and diverse food web."),
  _q("The distinct wet and dry seasons of the savanna biome most strongly influence which behaviour in large herbivores like wildebeest?",
      ["Seasonal migration in search of water and fresh grazing", "Permanent hibernation during the dry season", "Complete cessation of reproduction", "Living exclusively underground"], "Seasonal migration in search of water and fresh grazing",
      "Many savanna herbivores undertake large-scale seasonal migrations, following the rains to find adequate water and fresh grazing land."),
  _q("Which term describes the layering of vegetation at different heights within a tropical rainforest, from the forest floor to the emergent layer?",
      ["Stratification", "Zonation", "Succession", "Symbiosis"], "Stratification",
      "Stratification refers to the distinct vertical layers of vegetation (forest floor, understorey, canopy, emergent layer) found in a tropical rainforest."),
  _q("The gradual, sequential change in the species composition of a habitat over time, such as a bare rock surface eventually becoming a forest, is called:",
      ["Ecological succession", "Stratification", "Zonation", "Migration"], "Ecological succession",
      "Ecological succession describes the predictable, gradual process by which a community of organisms changes over time, often starting with pioneer species and eventually reaching a stable climax community."),
  _q("The first organisms to colonise a barren or newly formed habitat during ecological succession, such as lichens on bare rock, are called:",
      ["Pioneer species", "Climax species", "Keystone species", "Invasive species"], "Pioneer species",
      "Pioneer species are hardy organisms, like lichens and mosses, that are first to colonise an empty or disturbed habitat, gradually altering conditions to allow other species to establish."),
  _q("The relatively stable, long-lasting community of organisms that develops at the end of ecological succession is called the:",
      ["Climax community", "Pioneer community", "Transitional community", "Keystone community"], "Climax community",
      "A climax community represents the stable, mature end-point of ecological succession, remaining relatively unchanged until a major disturbance occurs."),
  _q("Which of the following best describes a 'keystone species' within an ecosystem?",
      ["A species whose presence has a disproportionately large effect on maintaining the structure of its community", "A species that is always the largest predator in an ecosystem", "A species found only at the very beginning of succession", "A species that has no effect on other organisms"],
      "A species whose presence has a disproportionately large effect on maintaining the structure of its community",
      "A keystone species plays a critical role in maintaining the structure of an ecosystem; its removal can cause dramatic changes or collapse of the community, disproportionate to its abundance."),
  _q("Which of the following best explains why the removal of a keystone predator, such as sea otters (which control sea urchin populations), can drastically alter an ecosystem?",
      ["Without the predator, prey populations can explode, leading to overgrazing and loss of other habitat-forming species", "Removing a keystone predator always has no effect on other species", "Prey populations always decline when predators are removed", "Ecosystems are unaffected by changes in predator populations"],
      "Without the predator, prey populations can explode, leading to overgrazing and loss of other habitat-forming species",
      "Without sea otters controlling sea urchin numbers, urchins can overgraze kelp forests, destroying vital habitat for many other marine species — illustrating the ecosystem-wide impact of a keystone species."),
  _q("Which of the following best describes an 'invasive species' introduced into a new ecosystem?",
      ["A non-native species that spreads aggressively and often disrupts the native ecosystem", "Any species that is naturally found within an ecosystem", "A species that always benefits the ecosystem it is introduced to", "A species that can only survive in its original habitat"],
      "A non-native species that spreads aggressively and often disrupts the native ecosystem",
      "Invasive species are typically introduced from elsewhere (often by human activity) and can spread rapidly, outcompeting native species and disrupting established ecological relationships."),
  _q("Which of the following is a common negative impact of invasive species on native ecosystems?",
      ["Outcompeting native species for resources, sometimes leading to their local extinction", "Always increasing overall biodiversity in a positive way", "Having no impact on native species populations", "Always improving the productivity of an ecosystem"],
      "Outcompeting native species for resources, sometimes leading to their local extinction",
      "Invasive species often outcompete native organisms for food, space, or other resources, sometimes driving native species toward local extinction and disrupting the ecological balance."),
];

final _ecosystemFunctioning = [
  _q("A sequence showing the transfer of energy and nutrients from one organism to another through feeding relationships is called a:",
      ["Food chain", "Food web", "Ecological pyramid", "Nutrient cycle"], "Food chain",
      "A food chain represents a simple, linear sequence of organisms, each feeding on the one before it, showing energy transfer."),
  _q("A complex network of interconnected food chains within an ecosystem is called a:",
      ["Food web", "Food chain", "Trophic level", "Ecological pyramid"], "Food web",
      "A food web illustrates the many interconnected feeding relationships among organisms within an ecosystem, showing that most consumers eat more than one type of food."),
  _q("Each feeding position within a food chain, such as producer or primary consumer, is called a:",
      ["Trophic level", "Food web", "Ecological niche", "Habitat"], "Trophic level",
      "A trophic level represents a specific position in a food chain, defined by an organism's feeding relationship (e.g., producer, primary consumer)."),
  _q("In a food chain: Grass → Grasshopper → Frog → Snake → Hawk, which organism occupies the position of a tertiary consumer?",
      ["Snake", "Grasshopper", "Frog", "Hawk"], "Snake",
      "The snake, which eats the frog (a secondary consumer), occupies the tertiary consumer position (the fourth trophic level)."),
  _q("In the food chain: Grass → Grasshopper → Frog → Snake → Hawk, which organism is the producer?",
      ["Grass", "Grasshopper", "Frog", "Snake"], "Grass",
      "Grass is the producer in this food chain, as it manufactures its own food through photosynthesis, forming the base of the chain."),
  _q("A diagram representing the number, biomass, or energy of organisms at each trophic level, usually narrowing towards the top, is called a(n):",
      ["Ecological pyramid", "Food web", "Nutrient cycle", "Population graph"], "Ecological pyramid",
      "An ecological pyramid visually represents the relative amount of individuals, biomass, or energy at each successive trophic level."),
  _q("Which type of ecological pyramid represents the total number of individual organisms present at each trophic level?",
      ["Pyramid of numbers", "Pyramid of biomass", "Pyramid of energy", "Pyramid of productivity"], "Pyramid of numbers",
      "A pyramid of numbers shows the actual count of individual organisms present at each trophic level in a food chain."),
  _q("Which type of ecological pyramid represents the total dry mass of living material present at each trophic level?",
      ["Pyramid of biomass", "Pyramid of numbers", "Pyramid of energy", "Pyramid of population"], "Pyramid of biomass",
      "A pyramid of biomass shows the total mass of organisms (usually measured as dry weight) at each trophic level."),
  _q("Which type of ecological pyramid represents the amount of energy available and transferred at each trophic level, and is always upright?",
      ["Pyramid of energy", "Pyramid of numbers", "Pyramid of biomass", "Pyramid of decomposers"], "Pyramid of energy",
      "A pyramid of energy is always upright because energy is progressively lost at each trophic level, unlike numbers or biomass pyramids, which can sometimes be inverted."),
  _q("According to the ten percent rule, approximately what percentage of energy is transferred from one trophic level to the next?",
      ["10%", "50%", "90%", "100%"], "10%",
      "On average, only about 10% of energy stored in one trophic level is transferred to the next; the rest is lost mainly as heat during respiration."),
  _q("What is the main reason why energy decreases progressively as it moves up through trophic levels in a food chain?",
      ["Much of the energy is lost as heat during respiration and other metabolic processes at each level", "Energy is destroyed completely and cannot be measured", "Consumers create new energy at each level", "Energy only exists in the bottom trophic level"],
      "Much of the energy is lost as heat during respiration and other metabolic processes at each level",
      "Energy is lost as heat during respiration, in undigested food (egestion), and through movement, meaning only a small fraction is passed to the next trophic level."),
  _q("The continuous flow of energy through an ecosystem is best described as:",
      ["Unidirectional, flowing from producers to consumers and eventually being lost as heat", "Cyclical, being reused repeatedly by the same organisms", "Constant at every trophic level", "Increasing at each successive trophic level"],
      "Unidirectional, flowing from producers to consumers and eventually being lost as heat",
      "Unlike nutrients, energy flows in one direction through an ecosystem — from the sun to producers to consumers — and is ultimately lost as heat, not recycled."),
  _q("The continuous movement of carbon atoms between the atmosphere, living organisms, and the environment is called the:",
      ["Carbon cycle", "Nitrogen cycle", "Water cycle", "Energy cycle"], "Carbon cycle",
      "The carbon cycle describes how carbon moves between the atmosphere (as CO₂), living organisms, and geological reservoirs."),
  _q("Which process removes carbon dioxide from the atmosphere and incorporates carbon into organic compounds in plants?",
      ["Photosynthesis", "Respiration", "Combustion", "Decomposition"], "Photosynthesis",
      "Photosynthesis removes atmospheric carbon dioxide, converting it into organic carbon compounds (glucose) within plants."),
  _q("Which processes return carbon dioxide to the atmosphere as part of the carbon cycle?",
      ["Respiration and combustion", "Photosynthesis only", "Nitrogen fixation", "Transpiration"], "Respiration and combustion",
      "Both respiration (by living organisms) and combustion (burning of fossil fuels or wood) release carbon dioxide back into the atmosphere."),
  _q("The continuous movement of nitrogen between the atmosphere, soil, and living organisms is called the:",
      ["Nitrogen cycle", "Carbon cycle", "Water cycle", "Oxygen cycle"], "Nitrogen cycle",
      "The nitrogen cycle describes the transformation and movement of nitrogen through the atmosphere, soil, and living organisms."),
  _q("The process by which atmospheric nitrogen gas is converted into a usable form (such as ammonia) by certain bacteria is called:",
      ["Nitrogen fixation", "Nitrification", "Denitrification", "Ammonification"], "Nitrogen fixation",
      "Nitrogen fixation is carried out by certain bacteria (free-living or in root nodules) that convert inert atmospheric nitrogen gas into ammonia, a usable form."),
  _q("Bacteria found in the root nodules of leguminous plants (like beans) that fix atmospheric nitrogen are commonly of the genus:",
      ["Rhizobium", "Nitrosomonas", "Nitrobacter", "Pseudomonas"], "Rhizobium",
      "Rhizobium bacteria live symbiotically within the root nodules of leguminous plants, fixing atmospheric nitrogen into a usable form."),
  _q("The process by which ammonia is converted into nitrites and then nitrates by soil bacteria is called:",
      ["Nitrification", "Nitrogen fixation", "Denitrification", "Ammonification"], "Nitrification",
      "Nitrification is the two-step conversion of ammonia to nitrites and then to nitrates, carried out by specific soil bacteria, making nitrogen available for plant uptake."),
  _q("The process by which certain bacteria convert nitrates back into atmospheric nitrogen gas, completing the nitrogen cycle, is called:",
      ["Denitrification", "Nitrification", "Nitrogen fixation", "Ammonification"], "Denitrification",
      "Denitrification is carried out by denitrifying bacteria, which convert soil nitrates back into nitrogen gas, releasing it into the atmosphere."),
  _q("The continuous movement of water between the atmosphere, land, and oceans, driven mainly by evaporation and precipitation, is called the:",
      ["Water cycle (hydrological cycle)", "Carbon cycle", "Nitrogen cycle", "Energy cycle"], "Water cycle (hydrological cycle)",
      "The water cycle describes the continuous movement of water through evaporation, condensation, precipitation, and collection."),
  _q("The process by which water vapour turns into liquid water, forming clouds, is called:",
      ["Condensation", "Evaporation", "Precipitation", "Transpiration"], "Condensation",
      "Condensation is the process by which water vapour cools and changes into liquid water droplets, forming clouds."),
  _q("The process by which water falls from clouds to the Earth's surface as rain, snow, or hail is called:",
      ["Precipitation", "Condensation", "Evaporation", "Transpiration"], "Precipitation",
      "Precipitation is the deposition of water from the atmosphere onto the Earth's surface, in forms such as rain, snow, or hail."),
  _q("In the food chain: Algae → Small fish → Big fish → Shark, which organism is the primary consumer?",
      ["Small fish", "Algae", "Big fish", "Shark"], "Small fish",
      "The small fish, which feeds directly on algae (the producer), occupies the primary consumer position."),
  _q("In the food chain: Algae → Small fish → Big fish → Shark, which organism occupies the highest trophic level?",
      ["Shark", "Algae", "Small fish", "Big fish"], "Shark",
      "The shark, at the end of the chain, occupies the highest trophic level as the top (tertiary) consumer."),
  _q("Which of the following best explains why food webs give a more realistic picture of feeding relationships than simple food chains?",
      ["Most organisms feed on more than one type of food, creating interconnected relationships not shown in a single chain", "Food webs only apply to aquatic ecosystems", "Food chains always contain more organisms than food webs", "Food webs never include producers"],
      "Most organisms feed on more than one type of food, creating interconnected relationships not shown in a single chain",
      "Since most consumers eat a variety of food sources and are eaten by multiple predators, food webs capture these complex, interconnected relationships better than a single linear food chain."),
  _q("What is the primary source of energy that enters most ecosystems and powers food chains?",
      ["The sun (solar energy)", "Geothermal heat from within the Earth", "Chemical energy stored in rocks", "Wind energy"], "The sun (solar energy)",
      "Solar energy is the primary energy source for almost all ecosystems, captured by producers through photosynthesis and passed along food chains."),
  _q("A pyramid of numbers can sometimes appear inverted (narrow at the base), such as when a single large tree supports many small insects. Which type of pyramid does NOT suffer from this issue and is always upright?",
      ["Pyramid of energy", "Pyramid of numbers", "Pyramid of biomass in all cases", "None of these pyramids are ever upright"],
      "Pyramid of energy",
      "Unlike pyramids of numbers or biomass, which can sometimes be inverted due to the size or turnover rate of organisms, a pyramid of energy is always upright because energy diminishes progressively at each trophic level."),
  _q("Which of the following organisms would typically be found at the base (first trophic level) of a marine food chain?",
      ["Phytoplankton (microscopic algae)", "Sharks", "Tuna", "Seals"], "Phytoplankton (microscopic algae)",
      "Phytoplankton are microscopic, photosynthetic organisms that form the base of most marine food chains as primary producers."),
  _q("A food chain generally has a limited number of trophic levels (rarely more than four or five). Which of the following best explains this limitation?",
      ["The large loss of energy at each trophic level means there is insufficient energy to support further levels", "There is no limit to the number of trophic levels possible", "Predators refuse to eat beyond the fourth level", "Producers always outnumber all consumers combined"],
      "The large loss of energy at each trophic level means there is insufficient energy to support further levels",
      "Because roughly 90% of energy is lost at each trophic transfer, there is eventually too little energy remaining to support additional trophic levels beyond four or five."),
  _q("Which of the following processes is part of the water cycle and involves water loss specifically from plant leaves?",
      ["Transpiration", "Condensation", "Precipitation only", "Infiltration only"], "Transpiration",
      "Transpiration, the evaporation of water from plant leaves, is a significant contributor to the water cycle, alongside evaporation from open water surfaces."),
  _q("Which of the following gases makes up the largest percentage of the Earth's atmosphere and is a key part of the nitrogen cycle?",
      ["Nitrogen gas (N₂)", "Oxygen gas (O₂)", "Carbon dioxide", "Argon"], "Nitrogen gas (N₂)",
      "Nitrogen gas makes up about 78% of the atmosphere, though it must be converted (fixed) into a usable form before most organisms can use it."),
  _q("Which of the following best explains why nitrogen fixation is essential for most living organisms, despite nitrogen gas being abundant in the atmosphere?",
      ["Most organisms cannot use atmospheric nitrogen gas directly; it must first be converted into a usable form like ammonia or nitrates", "Nitrogen gas is toxic to all living organisms", "There is very little nitrogen gas in the atmosphere", "All organisms can absorb nitrogen gas directly from the air"],
      "Most organisms cannot use atmospheric nitrogen gas directly; it must first be converted into a usable form like ammonia or nitrates",
      "Atmospheric nitrogen gas (N₂) is chemically unreactive and cannot be used directly by most organisms; nitrogen fixation converts it into forms like ammonia that plants can absorb and use to build proteins."),
  _q("Which of the following best explains why decomposers are sometimes classified as part of the 'detritus food chain' rather than the standard grazing food chain?",
      ["They feed specifically on dead organic matter (detritus), rather than living producers or consumers", "They only feed on living plants", "They are always the largest organisms in an ecosystem", "They never play a role in nutrient cycling"],
      "They feed specifically on dead organic matter (detritus), rather than living producers or consumers",
      "The detritus food chain begins with dead organic matter, which decomposers and detritivores break down, distinguishing it from the grazing food chain that begins with living producers."),
  _q("Which of the following organisms would typically be classified as a detritivore, feeding on dead organic matter?",
      ["Earthworm", "Lion", "Grasshopper", "Eagle"], "Earthworm",
      "Earthworms are detritivores, consuming dead plant material and organic debris in soil, contributing to decomposition and nutrient cycling."),
  _q("Which of the following best explains the concept of 'gross primary productivity' in an ecosystem?",
      ["The total amount of energy captured by producers through photosynthesis in a given time", "The energy lost by producers through respiration", "The energy consumed by top predators only", "The total number of producers in an ecosystem"],
      "The total amount of energy captured by producers through photosynthesis in a given time",
      "Gross primary productivity refers to the total rate at which producers convert solar energy into chemical energy (organic matter) through photosynthesis."),
  _q("Which of the following best describes 'net primary productivity'?",
      ["The energy remaining in producers after subtracting their own respiratory losses from gross primary productivity", "The total energy captured by producers before any losses", "The energy consumed by primary consumers only", "The energy lost as heat at every trophic level combined"],
      "The energy remaining in producers after subtracting their own respiratory losses from gross primary productivity",
      "Net primary productivity is the energy that remains available to consumers after producers have used some of the captured energy for their own respiration."),
  _q("In the food chain: Maize → Rat → Snake → Owl, which organism would be most severely affected if the rat population suddenly crashed?",
      ["Both maize (less grazing pressure) and snake (less food) would be affected", "Only the owl would be affected", "None of the other organisms would be affected", "Only maize would be affected"],
      "Both maize (less grazing pressure) and snake (less food) would be affected",
      "A crash in the rat population would reduce grazing pressure on maize while also reducing the primary food source for snakes, illustrating the interconnected nature of food chains."),
  _q("Which of the following best explains why removing a top predator from an ecosystem can trigger a 'trophic cascade'?",
      ["Changes in predator numbers affect prey populations, which in turn affect the populations and resources at lower trophic levels", "Top predators have no influence on any other trophic level", "Only producers are affected by changes to predator populations", "Removing a predator always increases biodiversity at every level"],
      "Changes in predator numbers affect prey populations, which in turn affect the populations and resources at lower trophic levels",
      "A trophic cascade occurs when a change at one trophic level (such as removing a predator) ripples down through the food chain, affecting populations and resources at every lower level."),
  _q("Which of the following best explains why the total energy entering an ecosystem is generally far greater than the energy that reaches the highest-level consumers?",
      ["Energy is progressively lost as heat at each trophic transfer, following the laws of thermodynamics", "Energy increases as it moves through the food chain", "There is no loss of energy anywhere within a food chain", "Only the top predator ever receives any energy"],
      "Energy is progressively lost as heat at each trophic transfer, following the laws of thermodynamics",
      "In line with the laws of thermodynamics, energy is inevitably lost as heat during metabolic processes at each trophic level, meaning only a fraction reaches higher consumers."),
  _q("Which of the following organisms would occupy multiple trophic levels within a complex food web, depending on what it is currently eating?",
      ["An omnivore, such as a human or a bear", "A strict herbivore, such as a cow", "A strict carnivore that only eats one prey species", "A producer, such as grass"], "An omnivore, such as a human or a bear",
      "Omnivores consume both plant and animal matter, meaning they can occupy the role of primary, secondary, or even tertiary consumer depending on what they are eating at a given time."),
  _q("Which of the following best explains the ecological concept of 'nutrient cycling'?",
      ["The continuous movement and reuse of essential elements, such as carbon and nitrogen, between living organisms and the physical environment", "The one-way flow of energy through an ecosystem", "The permanent loss of nutrients from an ecosystem over time", "A process that only occurs in aquatic ecosystems"],
      "The continuous movement and reuse of essential elements, such as carbon and nitrogen, between living organisms and the physical environment",
      "Unlike energy, which flows one way and is lost as heat, nutrients are continuously recycled between organisms and the environment through processes like decomposition and the carbon and nitrogen cycles."),
  _q("Which of the following best explains why decomposers are essential for nutrient cycling to continue?",
      ["Without decomposers, nutrients would remain locked within dead organic matter and unavailable to producers", "Decomposers destroy nutrients permanently", "Decomposers only recycle water, not other nutrients", "Nutrient cycling would occur just as effectively without decomposers"],
      "Without decomposers, nutrients would remain locked within dead organic matter and unavailable to producers",
      "Decomposers break down dead organic matter, releasing locked-up nutrients back into the soil or environment, where they become available again for uptake by producers."),
];

final _ecologicalFactors = [
  _q("Physical (abiotic) factors such as temperature, rainfall, humidity, and light intensity that influence organisms in their environment are called:",
      ["Ecological factors", "Biotic factors", "Trophic factors", "Community factors"], "Ecological factors",
      "Ecological factors, both abiotic and biotic, determine the distribution and abundance of organisms within a habitat."),
  _q("Which instrument is used to measure wind speed in a habitat study?",
      ["Anemometer", "Hygrometer", "Barometer", "Thermometer"], "Anemometer",
      "An anemometer measures wind speed, an important abiotic factor especially in terrestrial habitat studies."),
  _q("Which instrument is used to measure atmospheric humidity (relative humidity of the air)?",
      ["Hygrometer", "Anemometer", "Secchi disc", "Quadrat"], "Hygrometer",
      "A hygrometer measures the relative humidity of the air, an important abiotic factor affecting terrestrial organisms."),
  _q("Which instrument is used to measure atmospheric pressure?",
      ["Barometer", "Hygrometer", "Anemometer", "Thermometer"], "Barometer",
      "A barometer measures atmospheric pressure, which can influence weather patterns and organism behaviour."),
  _q("Which simple instrument is used to measure the turbidity (clarity) and light penetration of water in an aquatic habitat?",
      ["Secchi disc", "Hygrometer", "Anemometer", "Quadrat"], "Secchi disc",
      "A Secchi disc is lowered into water to determine the depth of light penetration, indicating the water's turbidity or clarity."),
  _q("Which instrument is used to measure the amount of rainfall in a given area over a period of time?",
      ["Rain gauge", "Anemometer", "Barometer", "Hygrometer"], "Rain gauge",
      "A rain gauge collects and measures the amount of precipitation (rainfall) that falls in a specific location over time."),
  _q("Which instrument is used to measure the temperature of soil, water, or air in a habitat study?",
      ["Thermometer", "Anemometer", "Hygrometer", "Secchi disc"], "Thermometer",
      "A thermometer measures temperature, a critical abiotic factor affecting metabolic rates and the distribution of organisms."),
  _q("Which instrument, such as a light meter, is used to measure the intensity of light in a habitat?",
      ["Light meter (photometer)", "Hygrometer", "Anemometer", "Barometer"], "Light meter (photometer)",
      "A light meter (photometer) measures light intensity, which is crucial for photosynthesis and influences plant and animal distribution."),
  _q("Which of the following is an example of a topographical (physical landscape) factor that can influence a habitat?",
      ["Altitude and slope of the land", "Rainfall amount", "Air temperature", "Wind speed"], "Altitude and slope of the land",
      "Topographical factors include physical landscape features like altitude, slope, and aspect, which affect climate and habitat conditions."),
  _q("Which of the following is a quadrat commonly used for in ecological studies?",
      ["Estimating the population size or percentage cover of plants/slow-moving organisms in a sample area", "Measuring wind speed", "Measuring water clarity", "Measuring atmospheric pressure"],
      "Estimating the population size or percentage cover of plants/slow-moving organisms in a sample area",
      "A quadrat is a square frame of known area used to sample and estimate the abundance or percentage cover of organisms, especially plants, within a habitat."),
  _q("Which sampling method involves laying out a line across a habitat and recording organisms that touch or fall near it, often used to study zonation?",
      ["Transect sampling", "Quadrat sampling only", "Capture-recapture method", "Random sampling only"], "Transect sampling",
      "Transect sampling involves placing a line across a habitat to study how species distribution changes along an environmental gradient, such as from a shoreline inland."),
  _q("Which of the following best explains why temperature is a critical abiotic factor affecting the distribution of organisms?",
      ["It affects the rate of enzyme activity and metabolism in organisms", "It has no effect on living organisms", "It only affects plants, not animals", "It only matters in aquatic habitats"],
      "It affects the rate of enzyme activity and metabolism in organisms",
      "Temperature directly influences enzyme activity and metabolic rate, meaning organisms are often restricted to environments within their tolerable temperature range."),
  _q("Which abiotic factor most directly determines whether a plant can survive in a desert versus a rainforest environment?",
      ["Rainfall (water availability)", "Wind speed", "Atmospheric pressure", "Soil colour"], "Rainfall (water availability)",
      "Rainfall and overall water availability are major determinants of plant survival, directly influencing which plant species can thrive in a given biome."),
  _q("Which of the following abiotic factors would most directly limit the depth to which photosynthetic organisms can survive in a lake or ocean?",
      ["Light penetration", "Wind speed", "Air pressure", "Rainfall"], "Light penetration",
      "Since photosynthesis requires light, the depth to which light can penetrate water directly limits how deep photosynthetic organisms, like algae, can survive."),
  _q("Which of the following best explains why soil pH is an important ecological factor for plant growth?",
      ["It affects the availability of certain nutrients for uptake by plant roots", "It has no effect on nutrient availability", "It only affects animals, not plants", "It determines the colour of all plant leaves"],
      "It affects the availability of certain nutrients for uptake by plant roots",
      "Soil pH influences the chemical forms and solubility of nutrients, affecting how readily plant roots can absorb them; extreme pH values can limit nutrient availability."),
  _q("Which of the following is an example of an ecological factor that would primarily affect organisms in an aquatic (rather than terrestrial) habitat?",
      ["Water salinity and dissolved oxygen content", "Wind speed", "Soil type", "Altitude"], "Water salinity and dissolved oxygen content",
      "Salinity and dissolved oxygen levels are key ecological factors specific to aquatic environments, significantly influencing which organisms can survive there."),
  _q("Which of the following best explains why altitude can act as an ecological factor affecting species distribution on a mountain?",
      ["Temperature, oxygen levels, and atmospheric pressure change significantly with increasing altitude", "Altitude has no effect on any biological factor", "All species can survive equally well at any altitude", "Altitude only affects the colour of the sky"],
      "Temperature, oxygen levels, and atmospheric pressure change significantly with increasing altitude",
      "As altitude increases, temperature and atmospheric oxygen levels typically decrease, creating distinct zones of vegetation and animal life adapted to these changing conditions."),
  _q("Which of the following best explains why studying abiotic factors alongside biotic factors gives a more complete picture of a habitat?",
      ["Both types of factors interact to determine which organisms can survive and thrive in a given environment", "Only abiotic factors matter; biotic factors are irrelevant", "Only biotic factors matter; abiotic factors are irrelevant", "Abiotic and biotic factors never interact with one another"],
      "Both types of factors interact to determine which organisms can survive and thrive in a given environment",
      "A complete understanding of a habitat requires studying both abiotic factors (like temperature and rainfall) and biotic factors (like competition and predation), since they interact to shape which species can survive there."),
  _q("Which of the following instruments would be most useful for measuring soil moisture content in an ecological field study?",
      ["A soil moisture meter", "An anemometer", "A barometer", "A light meter"], "A soil moisture meter",
      "A soil moisture meter directly measures the water content within soil, an important abiotic factor for plant growth and soil organism distribution."),
  _q("Which of the following best explains why wind speed is considered an important ecological factor in certain habitats?",
      ["It can affect transpiration rates in plants, seed dispersal, and the ability of some organisms to fly or move", "Wind speed has no measurable effect on any living organism", "Wind speed only matters in aquatic ecosystems", "Wind always decreases transpiration rates in all conditions"],
      "It can affect transpiration rates in plants, seed dispersal, and the ability of some organisms to fly or move",
      "Wind speed can influence transpiration rates in plants, aid or hinder seed and pollen dispersal, and affect the ability of flying organisms to move efficiently through their environment."),
  _q("Which of the following best explains why organisms living in the deep ocean, far below the reach of sunlight, cannot rely on photosynthetic producers as their primary energy source?",
      ["Without sunlight, photosynthesis cannot occur, so these ecosystems often depend on alternative energy sources like chemosynthesis", "Sunlight penetrates to all ocean depths equally", "Photosynthesis can occur without any light at all", "Deep ocean organisms have no need for any energy source"],
      "Without sunlight, photosynthesis cannot occur, so these ecosystems often depend on alternative energy sources like chemosynthesis",
      "Since light cannot penetrate to extreme ocean depths, deep-sea ecosystems often rely on chemosynthetic bacteria (using chemical energy from hydrothermal vents) rather than photosynthetic producers as the base of the food chain."),
];

final _populationStudies = [
  _q("The number of individuals of a species per unit area or volume of habitat is called:",
      ["Population density", "Population growth rate", "Natality", "Mortality"], "Population density",
      "Population density measures how many individuals of a species occupy a given unit of area or volume."),
  _q("The birth rate within a population, or the number of new individuals produced over a given time, is called:",
      ["Natality", "Mortality", "Immigration", "Emigration"], "Natality",
      "Natality refers to the birth rate of a population — the number of new individuals born within a specific period."),
  _q("The death rate within a population, or the number of individuals that die over a given time, is called:",
      ["Mortality", "Natality", "Immigration", "Emigration"], "Mortality",
      "Mortality refers to the death rate of a population — the number of individuals that die within a specific period."),
  _q("The movement of individuals INTO a population from another area, increasing population size, is called:",
      ["Immigration", "Emigration", "Natality", "Mortality"], "Immigration",
      "Immigration is the arrival of new individuals into a population from elsewhere, contributing to population growth."),
  _q("The movement of individuals OUT of a population to another area, decreasing population size, is called:",
      ["Emigration", "Immigration", "Natality", "Mortality"], "Emigration",
      "Emigration is the departure of individuals from a population to settle elsewhere, reducing the original population's size."),
  _q("Which of the following would cause an INCREASE in population size?",
      ["High natality and immigration", "High mortality and emigration", "Equal natality and mortality only", "Emigration exceeding immigration"], "High natality and immigration",
      "A population grows when births (natality) and arrivals (immigration) exceed deaths (mortality) and departures (emigration)."),
  _q("Which sampling method is commonly used to estimate the population size of mobile animals, involving marking, releasing, and later recapturing individuals?",
      ["Capture-recapture method", "Quadrat sampling", "Transect sampling", "Secchi disc method"], "Capture-recapture method",
      "The capture-recapture method estimates population size by marking a sample of individuals, releasing them, then later capturing a new sample to see what proportion is marked."),
  _q("In the capture-recapture (Lincoln index) method, if 50 animals are initially marked and released, and later 60 animals are captured with 10 of them marked, what is the estimated total population size?",
      ["300", "50", "60", "10"], "300",
      "Using the Lincoln index formula: (first catch × second catch) ÷ number marked in second catch = (50 × 60) ÷ 10 = 300."),
  _q("Which of the following assumptions is important for the capture-recapture method to give an accurate population estimate?",
      ["The marked individuals mix randomly back into the population and marking does not affect survival", "All individuals in the population must be captured on the first attempt", "The population must be completely stationary and never move", "Marked individuals must be a different species from the rest"],
      "The marked individuals mix randomly back into the population and marking does not affect survival",
      "For the method to be reliable, marked individuals must redistribute randomly among the population, and the marking process should not affect their behaviour or survival."),
  _q("Which sampling method would be most appropriate for estimating the percentage cover of grass species in a large field?",
      ["Quadrat sampling", "Capture-recapture method", "Pitfall trapping", "Sweep netting"], "Quadrat sampling",
      "Quadrat sampling is ideal for stationary or slow-moving organisms like plants, allowing researchers to estimate abundance or percentage cover within sample areas."),
  _q("A pitfall trap, commonly used in ecological sampling, is designed to capture:",
      ["Small, ground-dwelling invertebrates that fall into a buried container", "Flying insects", "Aquatic organisms", "Large mammals"], "Small, ground-dwelling invertebrates that fall into a buried container",
      "A pitfall trap is a container buried level with the ground surface, used to capture small crawling invertebrates that fall in while moving across the ground."),
  _q("If a population's natality and immigration rates equal its mortality and emigration rates, the population size will:",
      ["Remain stable (in equilibrium)", "Increase rapidly", "Decrease rapidly", "Double every generation"], "Remain stable (in equilibrium)",
      "When the factors that increase a population (births, immigration) are balanced by those that decrease it (deaths, emigration), the population size remains stable."),
  _q("Which of the following is a density-dependent factor that can limit population growth as population size increases?",
      ["Competition for food and resources", "A sudden volcanic eruption", "A random flood", "An earthquake"], "Competition for food and resources",
      "Density-dependent factors, like competition for food, become more intense as population density increases, helping regulate population size."),
  _q("Which of the following is a density-independent factor that can affect population size regardless of how crowded the population is?",
      ["A natural disaster, such as a flood or fire", "Competition for food", "Predation intensity increasing with prey density", "Disease spreading more easily in crowded populations"],
      "A natural disaster, such as a flood or fire",
      "Density-independent factors, such as natural disasters, affect a population's size regardless of how many individuals are present."),
  _q("A graph showing the growth of a population over time, which typically rises steeply before levelling off as it approaches the environment's carrying capacity, produces a curve shaped like the letter:",
      ["S (sigmoid/logistic growth curve)", "J (exponential growth curve continuing indefinitely)", "V", "U"], "S (sigmoid/logistic growth curve)",
      "The sigmoid (S-shaped) growth curve shows a population growing rapidly at first, then slowing as resources become limited, eventually levelling off near the carrying capacity."),
  _q("The maximum population size that a given environment can sustainably support, considering available resources, is called the environment's:",
      ["Carrying capacity", "Population density", "Natality rate", "Biotic potential"], "Carrying capacity",
      "Carrying capacity is the maximum population size an environment can support indefinitely, given its available resources such as food, water, and space."),
  _q("When a population significantly exceeds an environment's carrying capacity, which of the following is a likely consequence?",
      ["Increased competition, starvation, and a subsequent decline in population size", "Unlimited, permanent population growth", "An automatic increase in the environment's resources", "No effect on the population at all"],
      "Increased competition, starvation, and a subsequent decline in population size",
      "Exceeding carrying capacity typically leads to resource depletion, increased competition, and higher mortality, causing the population to decline back towards a sustainable level."),
  _q("A rapid, unrestricted population growth pattern that occurs when resources are unlimited, producing a curve shaped like the letter 'J', is called:",
      ["Exponential growth", "Logistic growth", "Zero growth", "Negative growth"], "Exponential growth",
      "Exponential (J-shaped) growth occurs when a population grows at an accelerating rate due to abundant resources and minimal limiting factors, though this pattern is rarely sustained long-term in nature."),
  _q("Which of the following best describes why accurate population estimates are important for wildlife management?",
      ["They help determine sustainable hunting quotas and identify species at risk of decline", "They have no practical use in conservation", "They are only useful for studying human populations", "They can only be used to increase hunting activity"],
      "They help determine sustainable hunting quotas and identify species at risk of decline",
      "Accurate population data allows wildlife managers to set sustainable harvest limits and identify when a species' population is declining and needs protective intervention."),
  _q("If a random sample of ten 1m² quadrats in a field shows an average of 4 daisy plants per quadrat, and the field measures 500m², what is the estimated total number of daisy plants in the field?",
      ["2000", "500", "40", "4"], "2000",
      "Estimated total population = mean density per unit area × total area = 4 plants/m² × 500m² = 2000 plants."),
  _q("Which of the following is a limitation of using quadrat sampling to estimate population size?",
      ["It may not be representative if quadrats are not placed randomly across the habitat", "It works equally well for fast-moving animals as for stationary plants", "It requires no calculations to estimate population size", "It can only be used in aquatic habitats"],
      "It may not be representative if quadrats are not placed randomly across the habitat",
      "If quadrats are not placed randomly, the sample may not accurately represent the overall distribution of organisms in the habitat, leading to biased population estimates."),
  _q("Which of the following best describes the relationship between population size and available resources in a stable ecosystem?",
      ["Population size tends to stabilise around the carrying capacity determined by available resources", "Population size always increases indefinitely regardless of resources", "Population size has no relationship with resource availability", "Resources always increase to match population size"],
      "Population size tends to stabilise around the carrying capacity determined by available resources",
      "In a stable ecosystem, population size tends to fluctuate around the carrying capacity, which is set by the availability of resources like food, water, and space."),
  _q("Which of the following best explains why predator and prey populations often show cyclical fluctuations over time, such as in the classic lynx-hare relationship?",
      ["An increase in prey leads to more food for predators, whose population then grows, which in turn reduces prey numbers, and the cycle repeats", "Predator and prey populations never influence one another", "Prey populations always increase indefinitely with no predator influence", "Predators immediately drive all prey species to extinction"],
      "An increase in prey leads to more food for predators, whose population then grows, which in turn reduces prey numbers, and the cycle repeats",
      "Predator and prey populations are interdependent: rising prey numbers support more predators, but the resulting increased predation reduces prey numbers, eventually causing predator numbers to decline too, creating a repeating cycle."),
  _q("Which of the following best describes an r-selected species, characterised by producing many offspring with little parental care?",
      ["A species like many insects or fish that reproduce rapidly, producing large numbers of offspring with a low individual survival rate", "A species that produces very few offspring but invests heavily in their care", "A species that never reproduces sexually", "A species found exclusively in stable, resource-limited environments"],
      "A species like many insects or fish that reproduce rapidly, producing large numbers of offspring with a low individual survival rate",
      "r-selected species, such as many insects and fish, prioritise rapid reproduction and large numbers of offspring, accepting a low individual survival rate as a reproductive strategy."),
  _q("Which of the following best describes a K-selected species, characterised by producing fewer offspring with significant parental investment?",
      ["A species like elephants or humans that produce few offspring but invest heavily in their survival and development", "A species that produces thousands of offspring with no parental care", "A species that reproduces only asexually", "A species with no limit on population growth"],
      "A species like elephants or humans that produce few offspring but invest heavily in their survival and development",
      "K-selected species, such as elephants and humans, typically produce few offspring but invest considerable time and resources into their care, increasing each individual's chances of survival."),
];

final _conservation = [
  _q("The wise and sustainable use, protection, and management of natural resources to prevent their depletion or destruction is called:",
      ["Conservation", "Exploitation", "Pollution", "Extinction"], "Conservation",
      "Conservation involves the responsible management and protection of natural resources to ensure their availability for future generations."),
  _q("Which of the following is a major reason for conserving forests?",
      ["Forests help regulate climate, prevent soil erosion, and provide habitats for wildlife", "Forests have no ecological importance", "Forests only provide timber for construction", "Forests increase desertification"],
      "Forests help regulate climate, prevent soil erosion, and provide habitats for wildlife",
      "Forests play a crucial role in climate regulation, preventing soil erosion, and providing essential habitats for countless species."),
  _q("Which human activity is a major cause of deforestation?",
      ["Clearing land for agriculture and logging", "Planting trees for reforestation", "Establishing wildlife reserves", "Practising crop rotation"], "Clearing land for agriculture and logging",
      "Deforestation is largely driven by clearing forested land for farming, logging for timber, and urban expansion."),
  _q("Which of the following is an important method of soil conservation to prevent erosion on sloped land?",
      ["Terracing and contour ploughing", "Removing all vegetation cover", "Overgrazing by livestock", "Continuous monocropping without rest"], "Terracing and contour ploughing",
      "Terracing and contour ploughing help slow water runoff on slopes, reducing soil erosion and conserving topsoil."),
  _q("Which farming practice, involving the planting of different crops in succession, helps maintain soil fertility?",
      ["Crop rotation", "Overgrazing", "Deforestation", "Monoculture"], "Crop rotation",
      "Crop rotation helps replenish soil nutrients (such as through planting nitrogen-fixing legumes) and reduces the build-up of pests and diseases."),
  _q("Which of the following is a major cause of water pollution in many developing countries?",
      ["Discharge of untreated sewage and industrial waste into rivers", "Planting trees along riverbanks", "Building water treatment plants", "Reducing industrial activity"], "Discharge of untreated sewage and industrial waste into rivers",
      "Untreated sewage and industrial waste discharged into water bodies is a leading cause of water pollution, harming aquatic ecosystems and human health."),
  _q("Which method of sewage disposal involves treating wastewater to remove contaminants before releasing it into the environment?",
      ["Sewage treatment (using treatment plants)", "Direct discharge into rivers without treatment", "Open dumping on land", "Burning sewage"], "Sewage treatment (using treatment plants)",
      "Sewage treatment plants process wastewater to remove harmful substances and pathogens before safely releasing the treated water into the environment."),
  _q("Which of the following is an environmentally sound method of refuse (solid waste) disposal that involves converting organic waste into useful fertiliser?",
      ["Composting", "Open dumping", "Burning in open air", "Discharging into rivers"], "Composting",
      "Composting is a method that decomposes organic waste into nutrient-rich material that can be used to improve soil fertility."),
  _q("Which method of solid waste disposal involves burying waste in a designated, engineered site to minimise environmental contamination?",
      ["Sanitary landfill", "Open dumping", "River discharge", "Open burning"], "Sanitary landfill",
      "A sanitary landfill is an engineered site designed to safely bury waste while minimising the risk of contaminating soil and groundwater."),
  _q("Which of the following is a negative effect of air pollution caused by burning fossil fuels?",
      ["Respiratory diseases and contribution to global warming", "Improved air quality", "Increased biodiversity", "Enhanced ozone layer protection"], "Respiratory diseases and contribution to global warming",
      "Air pollution from burning fossil fuels releases harmful gases that can cause respiratory illness and contribute to the greenhouse effect and global warming."),
  _q("Which gas, released from burning fossil fuels, is a major contributor to global warming through the greenhouse effect?",
      ["Carbon dioxide", "Oxygen", "Nitrogen", "Helium"], "Carbon dioxide",
      "Carbon dioxide is a major greenhouse gas that traps heat in the atmosphere, contributing significantly to global warming when released in excess."),
  _q("Which of the following best describes the term 'pollutant'?",
      ["Any substance that contaminates the environment and causes harm to living organisms", "Any naturally occurring mineral in soil", "Any substance used in photosynthesis", "Any gas found in the atmosphere in normal concentrations"],
      "Any substance that contaminates the environment and causes harm to living organisms",
      "A pollutant is a harmful substance introduced into the environment, causing adverse effects on ecosystems and living organisms."),
  _q("Overhunting and habitat destruction are major causes of a reduction in wildlife populations, potentially leading to:",
      ["Extinction of species", "Increased biodiversity", "Improved ecosystem stability", "Population booms"], "Extinction of species",
      "Overhunting and habitat destruction can drastically reduce species populations, potentially driving them to extinction if unchecked."),
  _q("Which conservation strategy involves setting aside protected areas of land specifically to preserve wildlife and their habitats?",
      ["Establishment of game reserves and national parks", "Increased deforestation", "Unrestricted hunting", "Urban expansion into wild areas"], "Establishment of game reserves and national parks",
      "Game reserves and national parks are protected areas established specifically to conserve wildlife populations and their natural habitats."),
  _q("Which of the following practices contributes to the conservation of water resources?",
      ["Reducing water wastage and preventing contamination of water bodies", "Discharging untreated waste into rivers", "Excessive and unregulated water extraction", "Deforestation of watershed areas"], "Reducing water wastage and preventing contamination of water bodies",
      "Conserving water resources involves reducing wastage and preventing pollution to ensure clean water remains available for both human use and ecosystems."),
  _q("Which of the following best explains why the conservation of biodiversity is important?",
      ["It maintains ecosystem stability, provides genetic resources, and supports essential ecological processes", "It has no real benefit to humans or the environment", "It only benefits a small number of species", "It increases pollution levels"],
      "It maintains ecosystem stability, provides genetic resources, and supports essential ecological processes",
      "Biodiversity conservation is crucial because diverse ecosystems are more resilient, provide genetic resources for medicine and agriculture, and support essential processes like pollination and nutrient cycling."),
  _q("Which of the following best distinguishes 'renewable' from 'non-renewable' natural resources?",
      ["Renewable resources can be replenished naturally within a human timescale, while non-renewable resources cannot", "Renewable resources are always more abundant than non-renewable ones", "Non-renewable resources never run out", "There is no real difference between the two"],
      "Renewable resources can be replenished naturally within a human timescale, while non-renewable resources cannot",
      "Renewable resources, like sunlight, wind, and forests (if managed sustainably), regenerate naturally, while non-renewable resources, like fossil fuels, form over geological timescales far too slow to replace what is consumed."),
  _q("Which of the following is an example of a renewable natural resource?",
      ["Solar energy", "Coal", "Crude oil", "Natural gas"], "Solar energy",
      "Solar energy is continuously available from the sun and does not deplete with use, making it a renewable resource."),
  _q("Which of the following is an example of a non-renewable natural resource?",
      ["Crude oil", "Sunlight", "Wind", "Forest timber (if sustainably managed)"], "Crude oil",
      "Crude oil takes millions of years to form geologically, so it is considered a non-renewable resource once extracted and used."),
  _q("Which human activity is a leading cause of desertification (the spread of desert-like conditions) in semi-arid regions?",
      ["Overgrazing and deforestation", "Afforestation (tree planting)", "Crop rotation", "Building wildlife reserves"], "Overgrazing and deforestation",
      "Overgrazing by livestock and clearing of vegetation for firewood or farming strip the land of plant cover, accelerating desertification in fragile, semi-arid ecosystems."),
  _q("The process of planting trees in an area that previously had no forest cover is called:",
      ["Afforestation", "Deforestation", "Reforestation", "Overgrazing"], "Afforestation",
      "Afforestation refers to establishing forest cover on land that was not previously forested, as distinct from reforestation, which restores forest to a previously deforested area."),
  _q("The process of replanting trees in an area where forest was previously cleared is called:",
      ["Reforestation", "Afforestation", "Desertification", "Eutrophication"], "Reforestation",
      "Reforestation is the deliberate replanting of trees in areas where forests were previously cut down, helping restore lost ecosystems."),
  _q("The excessive enrichment of a water body with nutrients (such as from fertiliser runoff), often leading to algal blooms and oxygen depletion, is called:",
      ["Eutrophication", "Desertification", "Afforestation", "Bioaccumulation"], "Eutrophication",
      "Eutrophication occurs when excess nutrients, often from agricultural runoff, cause rapid algal growth; the subsequent decomposition of algae depletes oxygen, harming aquatic life."),
  _q("Which of the following best explains why eutrophication can lead to the death of fish in a lake?",
      ["Decomposing algae consume large amounts of dissolved oxygen, leading to oxygen depletion", "Algae directly poison fish with toxins in all cases", "Excess nutrients increase oxygen levels too much", "Algae block sunlight only, with no other effects"],
      "Decomposing algae consume large amounts of dissolved oxygen, leading to oxygen depletion",
      "As algal blooms die off, decomposer bacteria multiply and consume dissolved oxygen during decomposition, often leading to hypoxic conditions that suffocate fish and other aquatic organisms."),
  _q("The gradual accumulation of harmful substances (such as pesticides) in the tissues of organisms, increasing in concentration at higher trophic levels, is called:",
      ["Bioaccumulation (biomagnification)", "Eutrophication", "Desertification", "Nitrification"], "Bioaccumulation (biomagnification)",
      "Bioaccumulation (or biomagnification) describes how persistent pollutants become increasingly concentrated as they move up the food chain from producers to top predators."),
  _q("Why are top predators often most severely affected by the bioaccumulation of pesticides like DDT?",
      ["They consume many prey organisms, each carrying accumulated toxins, resulting in the highest concentration at the top of the food chain", "They are naturally more sensitive to all chemicals", "Pesticides are only found in the water predators drink", "Top predators do not eat other organisms"],
      "They consume many prey organisms, each carrying accumulated toxins, resulting in the highest concentration at the top of the food chain",
      "Because top predators eat many prey animals that have each accumulated toxins, the concentration of harmful substances magnifies significantly at the top of the food chain."),
  _q("Which of the following is a key benefit of establishing marine protected areas for ocean conservation?",
      ["They allow fish populations and marine habitats to recover by restricting harmful activities like overfishing", "They have no effect on marine biodiversity", "They are established solely to promote tourism, with no conservation value", "They increase the rate of illegal fishing"],
      "They allow fish populations and marine habitats to recover by restricting harmful activities like overfishing",
      "Marine protected areas restrict damaging activities such as overfishing and habitat destruction, allowing depleted fish stocks and fragile habitats like coral reefs to recover."),
  _q("Which of the following human activities is a major contributor to coral reef degradation worldwide?",
      ["Ocean warming and acidification linked to climate change, along with pollution", "Establishing marine protected areas", "Reducing carbon emissions", "Banning destructive fishing practices"], "Ocean warming and acidification linked to climate change, along with pollution",
      "Rising ocean temperatures and acidification, both linked to climate change, along with pollution and sedimentation, are major drivers of coral bleaching and reef degradation."),
  _q("Which of the following best describes 'coral bleaching'?",
      ["The loss of symbiotic algae from coral tissue, often due to stress from warmer water, causing corals to turn white and become vulnerable", "The natural, healthy colouration process of young coral", "A beneficial process that strengthens coral resilience", "A process unrelated to environmental stress"],
      "The loss of symbiotic algae from coral tissue, often due to stress from warmer water, causing corals to turn white and become vulnerable",
      "Coral bleaching occurs when corals expel their symbiotic algae (zooxanthellae) under stress, often from elevated water temperatures, losing their colour and becoming more vulnerable to disease and death."),
  _q("Which of the following is a sustainable agricultural practice that helps maintain soil fertility while minimising environmental harm?",
      ["Agroforestry (integrating trees with crops or livestock)", "Continuous monocropping without rest", "Excessive use of chemical fertilisers without regard for soil health", "Clearing all natural vegetation from farmland"], "Agroforestry (integrating trees with crops or livestock)",
      "Agroforestry combines trees with crops or livestock, improving soil fertility, reducing erosion, and providing additional benefits like shade and biodiversity, making it a sustainable farming practice."),
  _q("Which of the following best explains the importance of wetlands as a natural resource requiring conservation?",
      ["Wetlands filter pollutants, provide flood control, and serve as critical habitats for many species", "Wetlands serve no ecological purpose and can be freely drained", "Wetlands only exist in polar regions", "Wetlands increase the risk of flooding in surrounding areas"],
      "Wetlands filter pollutants, provide flood control, and serve as critical habitats for many species",
      "Wetlands provide essential ecosystem services, including natural water filtration, flood control by absorbing excess water, and critical habitat for a wide range of species."),
  _q("Which of the following best explains why illegal logging poses a significant threat to biodiversity in tropical rainforests?",
      ["It destroys habitats and disrupts ecosystems that support a vast number of specialised species", "It has no effect on species living within the forest", "It always improves the growth conditions for remaining species", "It only affects a single tree species with no wider impact"],
      "It destroys habitats and disrupts ecosystems that support a vast number of specialised species",
      "Illegal logging destroys critical habitat within tropical rainforests, disrupting complex ecosystems and threatening the survival of the many specialised species that depend on them."),
  _q("Which of the following best describes the role of environmental impact assessments before major construction or industrial projects?",
      ["They evaluate the potential ecological consequences of a project before it proceeds, helping to minimise environmental harm", "They are conducted only after a project is completed", "They have no bearing on whether a project is approved", "They guarantee zero environmental impact from any project"],
      "They evaluate the potential ecological consequences of a project before it proceeds, helping to minimise environmental harm",
      "Environmental impact assessments are conducted before project approval to identify and address potential ecological harm, helping decision-makers balance development with environmental protection."),
  _q("Which of the following best describes 'sustainable development' as it relates to environmental conservation?",
      ["Meeting present human needs without compromising the ability of future generations to meet their own needs", "Maximising resource extraction with no regard for future consequences", "Prioritising economic growth exclusively, ignoring environmental effects", "Halting all forms of development and resource use permanently"],
      "Meeting present human needs without compromising the ability of future generations to meet their own needs",
      "Sustainable development seeks a balance between meeting current human needs and preserving natural resources so that future generations can meet their own needs as well."),
  _q("Which of the following is a key reason for establishing international agreements on environmental protection, such as those addressing climate change?",
      ["Many environmental problems, like climate change, cross national borders and require coordinated global action", "Environmental problems only affect a single country at a time", "International cooperation has no impact on environmental issues", "Only wealthy countries are affected by environmental degradation"],
      "Many environmental problems, like climate change, cross national borders and require coordinated global action",
      "Since environmental issues like climate change and ocean pollution do not respect national borders, international cooperation and agreements are essential for effective, coordinated action."),
  _q("Which of the following best explains why community-based conservation programmes, involving local people, are often more effective than purely top-down government regulations?",
      ["Local communities have direct stakes in and knowledge of their environment, improving compliance and long-term sustainability", "Local communities have no interest in environmental conservation", "Government regulations are always more effective without any local involvement", "Community involvement always increases environmental destruction"],
      "Local communities have direct stakes in and knowledge of their environment, improving compliance and long-term sustainability",
      "When local communities are actively involved in conservation efforts, their traditional knowledge and personal investment in the outcome often lead to more effective and sustainable long-term results than regulations imposed from outside."),
  _q("Which of the following best explains why environmental education is considered an important tool for long-term conservation success?",
      ["It raises awareness and understanding, encouraging more sustainable behaviours among individuals and communities", "It has no measurable impact on conservation outcomes", "It only benefits scientists, not the general public", "It discourages any form of environmental protection"],
      "It raises awareness and understanding, encouraging more sustainable behaviours among individuals and communities",
      "Environmental education helps people understand the consequences of their actions on ecosystems, fostering more sustainable behaviours and greater public support for conservation initiatives."),
  _q("Which of the following best explains why urbanisation (the growth of cities) can have significant negative effects on local biodiversity?",
      ["It destroys and fragments natural habitats, replacing them with buildings and infrastructure", "It always increases the amount of natural habitat available for wildlife", "Urban areas have no effect on surrounding ecosystems", "Urbanisation exclusively benefits all native species"],
      "It destroys and fragments natural habitats, replacing them with buildings and infrastructure",
      "As cities expand, natural habitats are often destroyed or fragmented to make way for buildings and infrastructure, reducing the space and resources available for native wildlife."),
  _q("Which of the following is a strategy used in urban planning to help preserve some biodiversity within growing cities?",
      ["Creating green spaces, parks, and wildlife corridors within urban areas", "Removing all vegetation from city environments", "Building exclusively on protected wetlands", "Eliminating all green spaces from city planning"], "Creating green spaces, parks, and wildlife corridors within urban areas",
      "Urban planners can help preserve biodiversity by incorporating green spaces, parks, and wildlife corridors that provide habitat and movement pathways for various species within cities."),
  _q("Which of the following best explains why a rapidly growing human population can place increased pressure on natural resources and ecosystems?",
      ["More people require more food, water, energy, and land, increasing demand on already limited natural resources", "A growing population has no effect on resource consumption", "Natural resources automatically increase to match population growth", "Population growth always leads to improved environmental conditions"],
      "More people require more food, water, energy, and land, increasing demand on already limited natural resources",
      "As the human population grows, the overall demand for food, water, energy, and land increases, often placing greater strain on already limited natural resources and ecosystems."),
  _q("Which of the following best describes the concept of an 'ecological footprint'?",
      ["A measure of the amount of natural resources and land required to support an individual's or population's lifestyle", "A measure of an individual's physical shoe size", "A measure unrelated to resource consumption", "A measure only applicable to industrial machinery"],
      "A measure of the amount of natural resources and land required to support an individual's or population's lifestyle",
      "An ecological footprint estimates the amount of biologically productive land and resources required to support a particular lifestyle or population, reflecting its overall environmental impact."),
  _q("Which of the following best explains why recycling materials like paper, plastic, and metal is beneficial for environmental conservation?",
      ["It reduces the demand for raw materials, conserves energy, and decreases the volume of waste sent to landfills", "Recycling has no effect on resource consumption or waste levels", "Recycling always increases the amount of raw materials needed", "Recycling only applies to organic waste, not paper, plastic, or metal"],
      "It reduces the demand for raw materials, conserves energy, and decreases the volume of waste sent to landfills",
      "Recycling reduces the need to extract and process new raw materials, saves energy, and helps reduce the amount of waste that accumulates in landfills, benefiting the environment."),
  _q("Which of the following best explains why afforestation projects are often promoted as a strategy to help mitigate climate change?",
      ["Growing trees absorb carbon dioxide from the atmosphere through photosynthesis, helping to reduce greenhouse gas levels", "Trees release large amounts of carbon dioxide with no absorption at all", "Afforestation has no measurable effect on atmospheric carbon dioxide levels", "Trees only affect local weather, never global climate"],
      "Growing trees absorb carbon dioxide from the atmosphere through photosynthesis, helping to reduce greenhouse gas levels",
      "As trees grow, they absorb and store carbon dioxide through photosynthesis, helping to offset greenhouse gas emissions and mitigate the effects of climate change."),
  _q("Which of the following best explains why maintaining genetic diversity within a crop species (rather than growing one uniform variety) is important for food security?",
      ["Greater genetic diversity increases the chance that some varieties will survive diseases, pests, or changing climate conditions", "Genetic diversity has no bearing on a crop's resilience to disease", "A single uniform crop variety is always more resilient than diverse varieties", "Food security is entirely unrelated to genetic diversity in crops"],
      "Greater genetic diversity increases the chance that some varieties will survive diseases, pests, or changing climate conditions",
      "Maintaining genetic diversity among crop varieties increases the likelihood that at least some varieties will possess resistance to a given disease, pest, or environmental stress, helping protect overall food security."),
  _q("Which of the following best explains why overfishing can cause long-term damage to marine ecosystems, beyond simply reducing fish numbers?",
      ["It disrupts food chains and can cause population imbalances among predator and prey species throughout the ecosystem", "Overfishing only affects the specific fish species targeted, with no wider ecosystem impact", "Fish populations always recover instantly regardless of fishing pressure", "Overfishing has no measurable effect on marine biodiversity"],
      "It disrupts food chains and can cause population imbalances among predator and prey species throughout the ecosystem",
      "Removing large numbers of fish from an ecosystem disrupts established food chains, potentially causing overpopulation of prey species or starvation of predators that depend on the harvested fish."),
  _q("Which of the following best explains why some governments and organisations implement fishing quotas and seasonal restrictions?",
      ["To prevent overfishing and allow fish populations time to reproduce and recover, ensuring long-term sustainability", "To maximise short-term profit with no regard for fish population sustainability", "Fishing quotas have no effect on fish population sizes", "Seasonal restrictions are implemented randomly with no scientific basis"],
      "To prevent overfishing and allow fish populations time to reproduce and recover, ensuring long-term sustainability",
      "Fishing quotas and seasonal restrictions are designed to prevent overexploitation, giving fish populations sufficient time to reproduce and maintain sustainable numbers for future generations."),
];
