import "../quiz_question.dart";

QuizQuestion _q(String subject, String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

const _englishSubject = "English Language";
const _mathsSubject = "Mathematics";
const _gkSubject = "General Knowledge";

QuizQuestion _eq(String text, List<String> options, String correct, String explanation) =>
    _q(_englishSubject, text, options, correct, explanation);

QuizQuestion _mq(String text, List<String> options, String correct, String explanation) =>
    _q(_mathsSubject, text, options, correct, explanation);

QuizQuestion _gq(String text, List<String> options, String correct, String explanation) =>
    _q(_gkSubject, text, options, correct, explanation);

/// Federal University of Technology, Akure (FUTA) Post-UTME practice bank —
/// 100+ questions covering the three areas most Nigerian Post-UTME screening
/// exams draw on: English Language, Mathematics, and General Knowledge
/// (including current affairs). This is a general-purpose practice set,
/// not an official FUTA past-question paper; always confirm the exact
/// format and syllabus on FUTA's own screening portal for the current
/// session.
List<QuizQuestion> buildFutaPostUtmeQuestions() {
  return [
    ..._englishLanguage,
    ..._mathematics,
    ..._generalKnowledge,
  ];
}

/// Individual-subject accessors used by the Post-UTME subject picker, which
/// lets a student choose specific subjects rather than sit the full mixed
/// bank above.
List<QuizQuestion> buildFutaEnglishLanguageQuestions() => List.of(_englishLanguage);
List<QuizQuestion> buildFutaMathematicsQuestions() => List.of(_mathematics);
List<QuizQuestion> buildFutaGeneralKnowledgeQuestions() => List.of(_generalKnowledge);

const _passage =
    "Online shopping has expanded rapidly across Nigerian cities over the past decade, driven by growing mobile "
    "internet access and a rising class of tech-savvy young shoppers. Platforms that once relied solely on "
    "face-to-face transactions now compete with e-commerce marketplaces offering doorstep delivery of everything "
    "from electronics to groceries. This growth has created a booming logistics industry, as delivery companies "
    "race to solve the notoriously difficult problem of navigating congested roads and poorly numbered addresses "
    "in cities like Lagos and Port Harcourt. Motorcycle and tricycle riders have become a familiar sight, weaving "
    "through traffic to fulfil same-day orders. Yet the sector still faces real obstacles: unreliable electricity "
    "forces many warehouses to run costly generators, and inconsistent internet coverage in smaller towns limits "
    "how far online retailers can profitably expand. Despite these challenges, investors continue to pour funding "
    "into logistics start-ups, betting that whoever solves the delivery puzzle first will capture a market of "
    "over two hundred million potential customers.";

QuizQuestion _ucq(String question, List<String> options, String correct, String explanation) =>
    _eq("$_passage\n\n$question", options, correct, explanation);

const _passage2 =
    "Across many rural communities in Nigeria, the absence of a stable connection to the national electricity grid "
    "has long limited economic activity after sunset. In recent years, however, falling prices for solar panels "
    "and battery storage have made small home solar systems increasingly affordable for households far from any "
    "grid line. Local entrepreneurs now install compact rooftop panels that charge batteries during the day, "
    "providing enough power in the evening to run lights, charge phones, and even power small refrigerators for "
    "shopkeepers. Micro-finance institutions have begun offering pay-as-you-go financing plans, allowing families "
    "to spread the cost of a solar kit over many months rather than paying the full price upfront. Critics note "
    "that solar systems alone cannot yet power the heavy machinery needed for large-scale manufacturing, and that "
    "batteries eventually wear out and must be replaced at a cost many rural households still find burdensome. "
    "Nonetheless, development experts argue that even modest solar access can transform daily life, extending "
    "study hours for children, improving safety at night, and enabling small businesses to operate later into "
    "the evening.";

QuizQuestion _ucq2(String question, List<String> options, String correct, String explanation) =>
    _eq("$_passage2\n\n$question", options, correct, explanation);

const _passage3 =
    "Effective study habits are often the difference between students who merely attempt an examination and those "
    "who pass it with confidence. Educational researchers frequently point out that cramming large volumes of "
    "material into a single night before an examination rarely leads to lasting understanding, since information "
    "absorbed under stress is quickly forgotten. Spaced repetition, by contrast, involves reviewing material in "
    "short sessions spread out over days or weeks, allowing the brain more opportunities to strengthen memory "
    "connections. Practising with past examination questions is equally valuable, not merely because it "
    "familiarises candidates with the likely format of a paper, but because it forces active recall, a process "
    "proven to embed information far more securely than passive re-reading of notes. Sleep, too, plays an "
    "underrated role: students who stay awake all night to revise often perform worse than those who rest "
    "adequately, since memory consolidation largely occurs during sleep. Taken together, these findings suggest "
    "that how a student studies matters just as much as how long they study.";

QuizQuestion _ucq3(String question, List<String> options, String correct, String explanation) =>
    _eq("$_passage3\n\n$question", options, correct, explanation);

final _englishLanguage = [
  _ucq("According to the passage, what has mainly driven the rapid expansion of online shopping in Nigerian cities?",
      ["Growing mobile internet access and tech-savvy young shoppers", "A total ban on face-to-face transactions", "A sudden decrease in the number of shoppers", "Government subsidies for warehouse construction"], "Growing mobile internet access and tech-savvy young shoppers",
      "The passage states the growth was 'driven by growing mobile internet access and a rising class of tech-savvy young shoppers.'"),
  _ucq("What industry does the passage say has boomed as a result of e-commerce growth?",
      ["The logistics industry", "The banking industry", "The oil and gas industry", "The textile industry"], "The logistics industry",
      "The passage states 'this growth has created a booming logistics industry' as delivery companies compete to fulfil orders."),
  _ucq("What specific challenge do delivery companies face in cities like Lagos and Port Harcourt, according to the passage?",
      ["Navigating congested roads and poorly numbered addresses", "A complete absence of roads", "A total lack of customer demand", "Strict government bans on motorcycles"], "Navigating congested roads and poorly numbered addresses",
      "The passage mentions the 'notoriously difficult problem of navigating congested roads and poorly numbered addresses' in major cities."),
  _ucq("Which two obstacles does the passage identify as still facing the e-commerce and logistics sector?",
      ["Unreliable electricity and inconsistent internet coverage", "Excess funding and overstaffed warehouses", "Falling demand and cheap fuel", "Too many roads and too much internet access"], "Unreliable electricity and inconsistent internet coverage",
      "The passage states the sector faces 'real obstacles: unreliable electricity...and inconsistent internet coverage in smaller towns.'"),
  _ucq("Why, according to the passage, do investors continue funding logistics start-ups despite the challenges?",
      ["They are betting on capturing a market of over two hundred million potential customers", "They are required to by law", "They expect the market to shrink permanently", "They want to stop all online shopping activity"], "They are betting on capturing a market of over two hundred million potential customers",
      "The passage concludes investors are 'betting that whoever solves the delivery puzzle first will capture a market of over two hundred million potential customers.'"),
  _ucq("What is the closest meaning of the word 'notoriously' as used in the passage?",
      ["Widely and unfavourably known", "Rarely noticed", "Pleasantly surprising", "Completely resolved"], "Widely and unfavourably known",
      "'Notoriously' describes something widely known, usually for a negative or difficult quality, fitting the description of the delivery problem."),
  _eq("Choose the option that best completes the sentence: 'Neither the lecturer nor the students ___ aware of the change in venue.'",
      ["were", "was", "is", "has been"], "were",
      "When 'neither...nor' joins a singular and a plural subject, the verb agrees with the nearer subject, here the plural 'students', requiring 'were'."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The engineer gave a very METICULOUS report on the bridge inspection.'",
      ["Extremely careful and thorough", "Careless and rushed", "Brief and vague", "Overly optimistic"], "Extremely careful and thorough",
      "'Meticulous' means showing great attention to detail, making 'extremely careful and thorough' the closest synonym."),
  _eq("Choose the option opposite in meaning to the underlined word: 'The old machine's performance was surprisingly ROBUST.'",
      ["Fragile", "Sturdy", "Reliable", "Durable"], "Fragile",
      "'Robust' means strong and sturdy; its opposite is 'fragile', meaning easily broken or weak."),
  _eq("Choose the correctly spelt word.",
      ["Occurrence", "Occurence", "Ocurrence", "Occurrance"], "Occurrence",
      "'Occurrence' is correctly spelt with double 'c' and double 'r'; the other options misspell the word."),
  _eq("Choose the option that best completes the sentence: 'If the generator ___ properly, the factory would not have lost power.'",
      ["had been maintained", "was maintained", "is maintained", "will be maintained"], "had been maintained",
      "This third conditional describes an unreal past situation, requiring the past perfect passive: 'if it had been maintained.'"),
  _eq("Choose the correct preposition to complete the sentence: 'The new software is compatible ___ most operating systems.'",
      ["with", "to", "for", "at"], "with",
      "'Compatible with' is the standard preposition pairing used in formal and technical English."),
  _eq("Identify the part of speech of the underlined word: 'The technician QUICKLY replaced the faulty circuit board.'",
      ["Adverb", "Adjective", "Noun", "Conjunction"], "Adverb",
      "'Quickly' modifies the verb 'replaced', describing how the action was performed, making it an adverb."),
  _eq("Choose the option that is the correct plural form of 'analysis'.",
      ["Analyses", "Analysises", "Analysis's", "Analysia"], "Analyses",
      "'Analysis', derived from Greek, forms its plural irregularly as 'analyses'."),
  _eq("Choose the option nearest in meaning to the idiom: 'The two departments finally decided to BURY THE HATCHET after months of disagreement.'",
      ["End their conflict and make peace", "Start a fresh argument", "Hide important evidence", "Cancel the entire project"], "End their conflict and make peace",
      "'Bury the hatchet' is an idiom meaning to end a quarrel and become friendly again."),
  _eq("Choose the option that correctly completes the sentence: 'Mathematics ___ considered a difficult subject by many students.'",
      ["is", "are", "were", "have been"], "is",
      "Although 'mathematics' ends in 's', it is treated as a singular subject when referring to the discipline, requiring the singular verb 'is'."),
  _eq("Choose the word that best completes the sentence: 'The manager's ___ approach to deadlines frustrated the whole team.'",
      ["lax", "lack", "lash", "latch"], "lax",
      "'Lax' means not strict or careful enough, fitting the context of a frustrating approach to deadlines."),
  _eq("Choose the correctly punctuated sentence.",
      ["The workshop covers three areas: welding, wiring, and coding.", "The workshop covers three areas welding, wiring, and coding.", "The workshop covers three areas; welding, wiring, and coding.", "The workshop covers three areas, welding, wiring and coding"], "The workshop covers three areas: welding, wiring, and coding.",
      "A colon is correctly used to introduce a list after a complete independent clause, and the sentence properly ends with a full stop."),
  _eq("Choose the option that best completes the sentence: 'The data ___ still being analysed by the research team.'",
      ["is", "are", "was", "were"], "is",
      "In modern usage, 'data' is frequently treated as a singular mass noun in general contexts, taking the singular verb 'is'."),
  _eq("Identify the figure of speech used: 'The old bridge groaned under the weight of the trucks.'",
      ["Personification", "Simile", "Onomatopoeia", "Hyperbole"], "Personification",
      "Giving the bridge a human quality ('groaned') is an example of personification, attributing human behaviour to a non-human object."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The project's timeline was described as UNTENABLE by the engineers.'",
      ["Impossible to maintain or defend", "Extremely comfortable", "Fully achievable", "Slightly generous"], "Impossible to maintain or defend",
      "'Untenable' describes a position or situation that cannot be defended or maintained, fitting a timeline judged unrealistic."),
  _eq("Choose the correct form of the verb: 'Each of the components ___ tested before assembly.'",
      ["is", "are", "were", "have been"], "is",
      "'Each' is grammatically singular, so it takes the singular verb 'is', regardless of the plural noun that follows."),
  _eq("Choose the option that best completes the sentence: 'This is the laboratory ___ equipment was recently upgraded.'",
      ["whose", "who's", "which is", "that is"], "whose",
      "'Whose' is the possessive relative pronoun correctly used to link 'the laboratory' to 'its equipment'."),
  _eq("Choose the word opposite in meaning to the underlined word: 'The new policy was met with UNANIMOUS approval.'",
      ["Divided", "Unified", "Complete", "Widespread"], "Divided",
      "'Unanimous' means agreed by everyone; its opposite is 'divided', meaning split in opinion."),
  _eq("Choose the correct option to complete the sentence: 'The system is not only faster ___ also more energy-efficient.'",
      ["but", "and", "so", "or"], "but",
      "The correlative pairing 'not only...but also' is the standard grammatical construction used to link two related points."),
  _eq("Identify the correctly spelt word.",
      ["Maintenance", "Maintainance", "Maintenence", "Maintanance"], "Maintenance",
      "'Maintenance' is correctly spelt with 'ten' rather than 'tain' or 'ten' variants in the middle; the other options are misspellings."),
  _eq("Choose the option that best completes the sentence: 'It was the technician who ___ responsible for the delay.'",
      ["was", "were", "is being", "have been"], "was",
      "The subject 'who' referring back to 'the technician' requires the singular past tense verb 'was'."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The auditor gave a very FORTHRIGHT assessment of the company's finances.'",
      ["Direct and honest", "Vague and evasive", "Overly flattering", "Deliberately misleading"], "Direct and honest",
      "'Forthright' means direct and outspoken, especially in expressing one's opinions honestly."),
  _eq("Choose the correct option: 'The award was presented to my colleague and ___.'",
      ["me", "I", "myself", "mine"], "me",
      "After a preposition ('to'), the objective case pronoun 'me' is correct, not the subjective 'I'."),
  _eq("Choose the option that correctly completes the sentence: 'A number of engineers ___ working on the new bridge design.'",
      ["are", "is", "was", "has been"], "are",
      "'A number of' (referring to several individuals) takes a plural verb, unlike 'the number of', which takes a singular verb."),
  _eq("Choose the option that best expresses the meaning of the sentence: 'The company decided to go back to the drawing board after the prototype failed.'",
      ["Start the planning process over from the beginning", "Literally draw a new picture", "Cancel the project permanently", "Ask for more funding immediately"], "Start the planning process over from the beginning",
      "'Go back to the drawing board' is an idiom meaning to restart a plan from scratch after a failure."),
  _eq("Choose the word that is nearest in meaning to the underlined word: 'The abandoned factory was left in a state of complete DISREPAIR.'",
      ["Poor condition due to neglect", "Excellent working order", "Modern renovation", "Full operation"], "Poor condition due to neglect",
      "'Disrepair' refers to a poor condition resulting from neglect or lack of maintenance."),
  _eq("Choose the correct sentence.",
      ["Each of the students has submitted his project.", "Each of the students have submitted their project.", "Each of the students has submitted they project.", "Each of the students have submitted his project."], "Each of the students has submitted his project.",
      "'Each' is grammatically singular, so it correctly takes the singular verb 'has' and singular possessive 'his' in traditional formal usage."),

  // --- Vocabulary: synonyms ---
  _eq("Choose the option nearest in meaning to the underlined word: 'Smartphones have become UBIQUITOUS in modern Nigerian society.'",
      ["Omnipresent", "Rare", "Expensive", "Fragile"], "Omnipresent",
      "'Ubiquitous' means present or found everywhere, making 'omnipresent' the closest synonym."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The interviewer appreciated the candidate's CANDID response to a difficult question.'",
      ["Frank and honest", "Evasive and vague", "Rehearsed and stiff", "Aggressive and rude"], "Frank and honest",
      "'Candid' means truthful and straightforward, matching 'frank and honest'."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The new intern was RETICENT during the team meeting, saying very little.'",
      ["Reserved and quiet", "Loud and talkative", "Angry and confrontational", "Confident and outspoken"], "Reserved and quiet",
      "'Reticent' describes someone unwilling to speak freely, fitting 'reserved and quiet'."),
  _eq("Choose the option nearest in meaning to the underlined word: 'It is PRUDENT to save part of your salary every month.'",
      ["Wise and cautious", "Reckless and careless", "Generous and wasteful", "Lazy and indifferent"], "Wise and cautious",
      "'Prudent' means acting with care and good judgement, matching 'wise and cautious'."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The engineer proposed an AUDACIOUS plan to redesign the entire bridge.'",
      ["Bold and daring", "Timid and hesitant", "Dull and ordinary", "Slow and careful"], "Bold and daring",
      "'Audacious' describes a willingness to take bold risks, matching 'bold and daring'."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The professor gave a LUCID explanation of the complicated theorem.'",
      ["Clear and easy to understand", "Confusing and vague", "Extremely lengthy", "Poorly organised"], "Clear and easy to understand",
      "'Lucid' means expressed clearly and understood easily."),
  _eq("Choose the option nearest in meaning to the underlined word: 'Despite repeated failures, the researcher remained TENACIOUS in pursuing a solution.'",
      ["Persistent and determined", "Easily discouraged", "Careless", "Indifferent"], "Persistent and determined",
      "'Tenacious' describes someone who holds firmly to a course of action, matching 'persistent and determined'."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The BENEVOLENT donor funded scholarships for indigent students.'",
      ["Kind and generous", "Selfish and greedy", "Strict and harsh", "Wealthy but stingy"], "Kind and generous",
      "'Benevolent' means well-meaning and generous, matching 'kind and generous'."),
  _eq("Choose the option nearest in meaning to the underlined word: 'Climbing the mountain proved to be an ARDUOUS task.'",
      ["Very difficult and tiring", "Simple and quick", "Pleasant and relaxing", "Free of charge"], "Very difficult and tiring",
      "'Arduous' describes a task requiring great effort, matching 'very difficult and tiring'."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The graduate delivered an ELOQUENT speech at the convocation.'",
      ["Fluent and persuasive", "Short and confusing", "Rude and offensive", "Written but not spoken"], "Fluent and persuasive",
      "'Eloquent' describes fluent and persuasive speaking or writing."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The manager took a PRAGMATIC approach to solving the budget crisis.'",
      ["Practical and realistic", "Idealistic and unrealistic", "Emotional and reckless", "Theoretical only"], "Practical and realistic",
      "'Pragmatic' means dealing with things sensibly and realistically, matching 'practical and realistic'."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The DILIGENT student completed all assignments ahead of schedule.'",
      ["Hardworking and careful", "Lazy and careless", "Intelligent but slow", "Talented but unmotivated"], "Hardworking and careful",
      "'Diligent' describes someone who works hard and carefully, matching 'hardworking and careful'."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The report was praised for being CONCISE and easy to follow.'",
      ["Brief and to the point", "Long and detailed", "Confusing and unclear", "Written in technical jargon"], "Brief and to the point",
      "'Concise' means giving information clearly in few words, matching 'brief and to the point'."),
  _eq("Choose the option nearest in meaning to the underlined word: 'Some believe musical talent is an INNATE ability rather than a learned skill.'",
      ["Natural and inborn", "Learned through practice", "Rare and expensive", "Temporary and fading"], "Natural and inborn",
      "'Innate' means existing from birth rather than acquired, matching 'natural and inborn'."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The suspect gave a PLAUSIBLE explanation for his absence.'",
      ["Believable and reasonable", "Obviously false", "Extremely detailed", "Written down"], "Believable and reasonable",
      "'Plausible' means seeming reasonable or probable, matching 'believable and reasonable'."),

  // --- Vocabulary: antonyms ---
  _eq("Choose the word opposite in meaning to the underlined word: 'The museum displayed several ANCIENT artefacts from the region.'",
      ["Modern", "Old", "Historic", "Traditional"], "Modern",
      "'Ancient' means very old; its opposite is 'modern', meaning belonging to the present time."),
  _eq("Choose the word opposite in meaning to the underlined word: 'Rainfall was ABUNDANT in the region this year.'",
      ["Scarce", "Plentiful", "Frequent", "Heavy"], "Scarce",
      "'Abundant' means existing in large quantities; its opposite is 'scarce', meaning insufficient or rare."),
  _eq("Choose the word opposite in meaning to the underlined word: 'The jeweller confirmed that the diamond was GENUINE.'",
      ["Fake", "Authentic", "Valuable", "Rare"], "Fake",
      "'Genuine' means real or authentic; its opposite is 'fake', meaning not real."),
  _eq("Choose the word opposite in meaning to the underlined word: 'Attendance at the extra class was strictly VOLUNTARY.'",
      ["Compulsory", "Optional", "Free", "Occasional"], "Compulsory",
      "'Voluntary' means done by choice; its opposite is 'compulsory', meaning required by rule or law."),
  _eq("Choose the word opposite in meaning to the underlined word: 'The company plans to EXPAND its operations next year.'",
      ["Contract", "Grow", "Increase", "Improve"], "Contract",
      "'Expand' means to become larger; its opposite is 'contract', meaning to become smaller."),
  _eq("Choose the word opposite in meaning to the underlined word: 'Despite the setbacks, the coach remained OPTIMISTIC about the team's chances.'",
      ["Pessimistic", "Hopeful", "Confident", "Determined"], "Pessimistic",
      "'Optimistic' means hopeful about the future; its opposite is 'pessimistic', meaning expecting the worst."),
  _eq("Choose the word opposite in meaning to the underlined word: 'The company offered him a PERMANENT position after his internship.'",
      ["Temporary", "Fixed", "Lasting", "Secure"], "Temporary",
      "'Permanent' means lasting indefinitely; its opposite is 'temporary', meaning lasting for a limited time."),
  _eq("Choose the word opposite in meaning to the underlined word: 'The GENEROUS businessman donated heavily to the flood victims.'",
      ["Stingy", "Kind", "Wealthy", "Charitable"], "Stingy",
      "'Generous' means willing to give freely; its opposite is 'stingy', meaning unwilling to spend or give."),
  _eq("Choose the word opposite in meaning to the underlined word: 'The instructions given by the supervisor were EXPLICIT.'",
      ["Vague", "Clear", "Detailed", "Direct"], "Vague",
      "'Explicit' means stated clearly and in detail; its opposite is 'vague', meaning unclear or imprecise."),
  _eq("Choose the word opposite in meaning to the underlined word: 'Despite his success, the engineer remained HUMBLE.'",
      ["Arrogant", "Modest", "Simple", "Quiet"], "Arrogant",
      "'Humble' means having a modest view of oneself; its opposite is 'arrogant', meaning having an exaggerated sense of importance."),
  _eq("Choose the word opposite in meaning to the underlined word: 'The witness tried to CONCEAL the truth from the police.'",
      ["Reveal", "Hide", "Bury", "Deny"], "Reveal",
      "'Conceal' means to hide from view; its opposite is 'reveal', meaning to make known."),
  _eq("Choose the word opposite in meaning to the underlined word: 'The new work schedule is quite FLEXIBLE.'",
      ["Rigid", "Adaptable", "Convenient", "Loose"], "Rigid",
      "'Flexible' means able to change easily; its opposite is 'rigid', meaning fixed and unable to change."),
  _eq("Choose the word opposite in meaning to the underlined word: 'Workers are expected to be PUNCTUAL every morning.'",
      ["Habitually late", "Prompt", "Reliable", "Careful"], "Habitually late",
      "'Punctual' means arriving on time; its opposite describes someone who is habitually late."),
  _eq("Choose the word opposite in meaning to the underlined word: 'The children played safely in the SHALLOW end of the pool.'",
      ["Deep", "Wide", "Narrow", "Clear"], "Deep",
      "'Shallow' means having little depth; its opposite is 'deep', meaning extending far down."),
  _eq("Choose the word opposite in meaning to the underlined word: 'He made a HASTY decision without consulting anyone.'",
      ["Careful and well-considered", "Quick", "Rash", "Sudden"], "Careful and well-considered",
      "'Hasty' means done too quickly, without enough thought; its opposite describes a careful, well-considered decision."),

  // --- Grammar and sentence completion ---
  _eq("Choose the option that best completes the sentence: 'By this time next year, she ___ from the university.'",
      ["will have graduated", "will graduate", "has graduated", "graduates"], "will have graduated",
      "The future perfect tense ('will have graduated') is used for an action that will be completed before a specified future time."),
  _eq("Choose the option that best completes the sentence: 'The committee ___ yet to decide on the matter.'",
      ["is", "are", "were", "have"], "is",
      "'Committee' is treated as a singular collective noun when acting as one unit, requiring the singular verb 'is'."),
  _eq("Choose the option that best completes the sentence: 'Scarcely ___ the meeting begun when the power went off.'",
      ["had", "did", "was", "has"], "had",
      "The correlative structure 'scarcely...when' requires the past perfect 'had' in the inverted clause."),
  _eq("Choose the option that best completes the sentence: 'He is one of the students who ___ always punctual.'",
      ["are", "is", "was", "has been"], "are",
      "'Who' refers back to 'students' (plural), so the verb must agree in the plural form 'are'."),
  _eq("Choose the option that best completes the sentence: 'She would rather ___ at home than attend the noisy party.'",
      ["stay", "stays", "stayed", "staying"], "stay",
      "After 'would rather', the bare infinitive (without 'to') is used, giving 'stay'."),
  _eq("Choose the option that best completes the sentence: 'The report, along with the appendices, ___ due tomorrow.'",
      ["is", "are", "were", "have been"], "is",
      "The phrase 'along with the appendices' does not change the number of the subject 'report', which remains singular."),
  _eq("Choose the option that best completes the sentence: '___ she studies hard, she will pass the exam.'",
      ["If", "Unless", "Although", "Because"], "If",
      "'If' introduces the conditional clause stating the condition under which she will pass the exam."),
  _eq("Choose the option that best completes the sentence: 'He denied ___ the equipment.'",
      ["damaging", "having damage", "damage", "to damage"], "damaging",
      "The verb 'deny' is correctly followed by a gerund ('damaging'), not an infinitive."),
  _eq("Choose the option that best completes the sentence: 'The teacher insisted that every student ___ present.'",
      ["be", "is", "was", "would be"], "be",
      "After verbs like 'insist that', the subjunctive mood uses the base form of the verb, giving 'be'."),
  _eq("Choose the option that best completes the sentence: 'Hardly had the technician arrived ___ the machine broke down.'",
      ["when", "than", "then", "before"], "when",
      "'Hardly...when' is the standard correlative pairing used to describe two closely following events."),
  _eq("Choose the option that best completes the sentence: 'The twins resemble each other ___ closely that people often confuse them.'",
      ["so", "such", "too", "very"], "so",
      "The construction 'so...that' is used to express a result, correctly completing the sentence."),
  _eq("Choose the option that best completes the sentence: 'She is too tired ___ continue working.'",
      ["to", "for", "that", "so"], "to",
      "The structure 'too + adjective + to + infinitive' correctly completes the sentence with 'to'."),
  _eq("Choose the option that best completes the sentence: 'Not only did he pass the exam, ___ he also topped the class.'",
      ["but", "and", "so", "yet"], "but",
      "The correlative pairing 'not only...but also' is the standard construction linking two related points."),
  _eq("Choose the option that best completes the sentence: 'The professor, as well as his assistants, ___ attending the seminar.'",
      ["is", "are", "were", "have"], "is",
      "The subject of the sentence is 'the professor'; the phrase 'as well as his assistants' does not make the subject plural."),
  _eq("Choose the option that best completes the sentence: 'I wish I ___ more time to prepare for the interview.'",
      ["had", "have", "will have", "having"], "had",
      "After 'wish' for a present unreal situation, the past subjunctive form 'had' is required."),
  _eq("Choose the option that best completes the sentence: 'The new bridge is ___ than the old one.'",
      ["sturdier", "more sturdy", "sturdiest", "most sturdy"], "sturdier",
      "For short adjectives like 'sturdy', the comparative is formed by adding '-er', giving 'sturdier'."),
  _eq("Choose the option that best completes the sentence: 'Few students, if ___ , understood the complex theorem.'",
      ["any", "some", "none", "many"], "any",
      "'Few, if any' is an idiomatic expression meaning 'few, if there were any at all'."),
  _eq("Choose the option that best completes the sentence: 'The manager asked the workers ___ finish the project on time.'",
      ["to", "that they", "for to", "they should"], "to",
      "'Ask someone to do something' is the standard infinitive structure used after 'ask'."),
  _eq("Choose the option that best completes the sentence: 'This is the same result ___ we obtained last year.'",
      ["as", "that", "which", "like"], "as",
      "'Same...as' is the standard comparative construction used to compare two things."),
  _eq("Choose the option that best completes the sentence: 'The children were so excited ___ they could not sleep.'",
      ["that", "so", "as", "which"], "that",
      "The construction 'so...that' expresses a result, correctly completing the sentence with 'that'."),

  // --- Figures of speech ---
  _eq("Identify the figure of speech used: 'The old clock on the wall complained loudly with each passing hour.'",
      ["Personification", "Simile", "Metaphor", "Onomatopoeia"], "Personification",
      "Giving the clock the human ability to 'complain' is personification, attributing human qualities to a non-human object."),
  _eq("Identify the figure of speech used: 'The task was as easy as pie.'",
      ["Simile", "Metaphor", "Hyperbole", "Personification"], "Simile",
      "The comparison uses 'as...as', making this a simile."),
  _eq("Identify the figure of speech used: 'Time is a thief that steals our youth.'",
      ["Metaphor", "Simile", "Onomatopoeia", "Alliteration"], "Metaphor",
      "Describing time directly as 'a thief' without using 'like' or 'as' is a metaphor."),
  _eq("Identify the figure of speech used: 'I have asked you a thousand times to submit the assignment.'",
      ["Hyperbole", "Understatement", "Metaphor", "Simile"], "Hyperbole",
      "'A thousand times' is a deliberate exaggeration for emphasis, which is hyperbole."),
  _eq("Identify the figure of speech used: 'The kettle hissed on the stove.'",
      ["Onomatopoeia", "Personification", "Simile", "Metaphor"], "Onomatopoeia",
      "'Hissed' imitates the actual sound produced, making it onomatopoeia."),
  _eq("Identify the figure of speech used: 'She sells sea shells by the seashore.'",
      ["Alliteration", "Assonance", "Rhyme", "Onomatopoeia"], "Alliteration",
      "The repetition of the initial 's' sound across neighbouring words is alliteration."),
  _eq("Identify the figure of speech used: 'The lecturer gave us a definite maybe about the exam date.'",
      ["Oxymoron", "Simile", "Metaphor", "Hyperbole"], "Oxymoron",
      "'Definite maybe' combines two contradictory terms, which is an oxymoron."),
  _eq("Identify the figure of speech used: 'The company had to let go of some staff during the recession.'",
      ["Euphemism", "Hyperbole", "Metaphor", "Simile"], "Euphemism",
      "'Let go of' softens the harsher reality of dismissing staff, which is a euphemism."),
  _eq("Identify the figure of speech used: 'The hurricane caused a bit of damage to the coastal town.'",
      ["Understatement", "Hyperbole", "Personification", "Simile"], "Understatement",
      "Describing a hurricane's damage as 'a bit' deliberately minimises a serious event, which is understatement."),
  _eq("Identify the figure of speech used: 'The classroom became a battlefield during the debate.'",
      ["Metaphor", "Simile", "Onomatopoeia", "Alliteration"], "Metaphor",
      "Describing the classroom directly as 'a battlefield' without 'like' or 'as' is a metaphor."),

  // --- Idioms and proverbs ---
  _eq("Choose the option nearest in meaning to the idiom: 'The politician finally decided to SPILL THE BEANS about the scandal.'",
      ["Reveal a secret", "Cook a meal", "Start an argument", "Remain completely silent"], "Reveal a secret",
      "'Spill the beans' is an idiom meaning to reveal secret information."),
  _eq("Choose the option nearest in meaning to the idiom: 'These days, he visits his hometown ONCE IN A BLUE MOON.'",
      ["Very rarely", "Every single day", "Once a month exactly", "Very frequently"], "Very rarely",
      "'Once in a blue moon' is an idiom meaning something happens very rarely."),
  _eq("Choose the option nearest in meaning to the idiom: 'The old man sadly KICKED THE BUCKET last week.'",
      ["Died", "Travelled abroad", "Became very angry", "Won a competition"], "Died",
      "'Kick the bucket' is an informal idiom meaning to die."),
  _eq("Choose the option nearest in meaning to the idiom: 'Her analysis of the problem really HIT THE NAIL ON THE HEAD.'",
      ["Was exactly right", "Was completely wrong", "Caused an injury", "Was left unfinished"], "Was exactly right",
      "'Hit the nail on the head' means to describe something exactly and accurately."),
  _eq("Choose the option nearest in meaning to the idiom: 'I won't be at work today; I'm feeling UNDER THE WEATHER.'",
      ["Slightly unwell", "Extremely happy", "Very busy", "On holiday"], "Slightly unwell",
      "'Under the weather' is an idiom meaning feeling mildly ill."),
  _eq("Choose the option that best explains the proverb: 'A STITCH IN TIME SAVES NINE.'",
      ["Dealing with a problem early prevents it from getting worse", "Sewing clothes quickly saves money", "It is better to work slowly than quickly", "Nine problems are worse than one"], "Dealing with a problem early prevents it from getting worse",
      "The proverb teaches that prompt action on a small problem prevents it from becoming a much bigger one."),
  _eq("Choose the option that best explains the proverb: 'HE WHO PAYS THE PIPER DICTATES THE TUNE.'",
      ["Whoever provides the funding controls how it is used", "Musicians should always be paid promptly", "Only pipers can choose their own songs", "Payment should be made after the performance"], "Whoever provides the funding controls how it is used",
      "The proverb means that whoever finances something has the power to decide how it is done."),
  _eq("Choose the option that best explains the proverb: 'LET SLEEPING DOGS LIE.'",
      ["Avoid reopening an old issue that could cause trouble", "Never trust an animal that appears calm", "Always wake up early to avoid trouble", "Dogs should be allowed to rest during the day"], "Avoid reopening an old issue that could cause trouble",
      "The proverb advises against disturbing a settled matter that could cause new problems if reopened."),
  _eq("Choose the option that best explains the proverb: 'THE EARLY BIRD CATCHES THE WORM.'",
      ["Those who act promptly gain an advantage over others", "Birds must wake up before sunrise to find food", "Worms are most active early in the morning", "It is unwise to start a task too early"], "Those who act promptly gain an advantage over others",
      "The proverb means that people who act early or promptly are more likely to succeed."),
  _eq("Choose the option nearest in meaning to the idiom: 'The contractor was accused of trying to CUT CORNERS on the building project.'",
      ["Doing something in the cheapest or easiest way, often sacrificing quality", "Measuring the exact angles of a building", "Finishing a project well ahead of schedule", "Spending more money than necessary on materials"], "Doing something in the cheapest or easiest way, often sacrificing quality",
      "'Cut corners' is an idiom meaning to do something the easiest or cheapest way, often at the expense of quality."),

  // --- Oral English: phonetics, stress, and rhyme ---
  _eq("Which of the following words has a vowel sound different from the other three: boat, coat, goat, foot?",
      ["foot", "boat", "coat", "goat"], "foot",
      "'Boat', 'coat', and 'goat' share the same vowel sound; 'foot' has a different, shorter vowel sound."),
  _eq("Which syllable is stressed in the word 'PHOTOGRAPH'?",
      ["The first syllable", "The second syllable", "The third syllable", "All syllables equally"], "The first syllable",
      "'Photograph' is stressed on the first syllable: PHO-to-graph."),
  _eq("Which word rhymes with 'though'?",
      ["know", "cough", "through", "tough"], "know",
      "'Though' and 'know' share the same final vowel sound, making them rhyme."),
  _eq("Which letter is silent in the word 'knife'?",
      ["k", "n", "i", "f"], "k",
      "In 'knife', the initial 'k' is silent; only the 'n' sound is pronounced at the start."),
  _eq("Which word contains the same consonant sound as 'sh' in 'shoe'?",
      ["mission", "missing", "kiss", "message"], "mission",
      "In 'mission', the letters 'ssi' produce the /sh/ sound, the same consonant sound found in 'shoe'."),
  _eq("In the word 'PRESENT' (meaning a gift), which syllable carries the stress?",
      ["The first syllable", "The second syllable", "Both syllables equally", "Neither syllable"], "The first syllable",
      "As a noun meaning 'a gift', 'PRESent' is stressed on the first syllable, unlike the verb 'preSENT', stressed on the second."),
  _eq("Which pair of words rhyme?",
      ["chair and hair", "bear and beer", "food and good", "love and move"], "chair and hair",
      "'Chair' and 'hair' end with the same sound, making them a rhyming pair; the other pairs do not rhyme."),
  _eq("How many syllables are in the word 'beautiful'?",
      ["Three", "Two", "Four", "One"], "Three",
      "'Beautiful' is divided into three syllables: beau-ti-ful."),
  _eq("Which letter is silent in the word 'island'?",
      ["s", "i", "l", "d"], "s",
      "In 'island', the 's' is silent; the word is pronounced without an /s/ sound."),
  _eq("Which word does NOT have the same vowel sound as the others: sheep, sleep, bread, cheese?",
      ["bread", "sheep", "sleep", "cheese"], "bread",
      "'Sheep', 'sleep', and 'cheese' share the long /ee/ vowel sound, while 'bread' has a different, shorter vowel sound."),

  // --- Spelling ---
  _eq("Which of the following is the correct spelling of the word meaning 'essential or required'?",
      ["Necessary", "Neccessary", "Necesary", "Neccesary"], "Necessary",
      "'Necessary' is correctly spelt with one 'c' followed by double 's'; the other options are misspellings."),
  _eq("Which of the following is the correct spelling of the word meaning 'to feel ashamed or awkward'?",
      ["Embarrass", "Embarass", "Embaras", "Emberrass"], "Embarrass",
      "'Embarrass' is correctly spelt with double 'r' and double 's'; the other options are misspellings."),
  _eq("Which of the following is the correct spelling of the word referring to 'the system that administers a country or state'?",
      ["Government", "Goverment", "Governmant", "Govermnet"], "Government",
      "'Government' is correctly spelt with an 'n' before the final 'ment'; the other options are misspellings."),
  _eq("Which of the following is the correct spelling of the word meaning 'without doubt'?",
      ["Definitely", "Definately", "Definitly", "Deffinitely"], "Definitely",
      "'Definitely' is correctly spelt with 'ite' in the middle, not 'ate'; the other options are misspellings."),
  _eq("Which of the following is the correct spelling of the word meaning 'to provide lodging or make room for'?",
      ["Accommodate", "Acommodate", "Accomodate", "Accommadate"], "Accommodate",
      "'Accommodate' is correctly spelt with double 'c' and double 'm'; the other options are misspellings."),

  // --- Punctuation ---
  _eq("Which of the following sentences uses commas correctly in a list?",
      ["The technician repaired the printer, the scanner, and the copier.", "The technician repaired the printer the scanner and the copier.", "The technician repaired the printer; the scanner, and the copier.", "The technician repaired, the printer the scanner and the copier."], "The technician repaired the printer, the scanner, and the copier.",
      "Items in a list should be separated by commas, with a comma before the concluding 'and' (the Oxford comma) as shown in the first option."),
  _eq("Which of the following sentences uses the apostrophe correctly?",
      ["The girls' hostel has a new gate.", "The girl's hostel have a new gate.", "The girls hostel has a new gate.", "The girls's hostel has a new gate."], "The girls' hostel has a new gate.",
      "For a plural noun ending in 's' ('girls'), the possessive apostrophe is placed after the 's', giving 'girls''."),
  _eq("Which of the following sentences ends with the correct punctuation mark?",
      ["Have you finished the assignment?", "Have you finished the assignment.", "Have you finished the assignment!", "Have you finished the assignment,"], "Have you finished the assignment?",
      "A direct question must end with a question mark, not a full stop, exclamation mark, or comma."),
  _eq("Which of the following sentences uses quotation marks correctly?",
      ["The lecturer said, \"The exam has been postponed.\"", "The lecturer said, The exam has been postponed.", "The lecturer said \"The exam has been postponed", "The lecturer said, \"The exam has been postponed."], "The lecturer said, \"The exam has been postponed.\"",
      "A direct quotation must be enclosed in a matching pair of quotation marks, with the closing punctuation placed inside the final quotation mark."),
  _eq("Which of the following sentences uses a semicolon correctly?",
      ["The rain stopped; the sun came out.", "The rain stopped, the sun came out.", "The rain stopped; the sun, came out.", "The rain, stopped the sun came out."], "The rain stopped; the sun came out.",
      "A semicolon correctly joins two closely related independent clauses without a conjunction."),

  // --- Reading comprehension: passage 2 ---
  _ucq2("According to the passage, what has made small home solar systems increasingly affordable for rural households?",
      ["Falling prices for solar panels and battery storage", "A government ban on the national grid", "A sudden drop in fuel prices", "Free installation by the national grid"], "Falling prices for solar panels and battery storage",
      "The passage states that 'falling prices for solar panels and battery storage have made small home solar systems increasingly affordable.'"),
  _ucq2("What financing option have micro-finance institutions introduced to help families afford solar kits?",
      ["Pay-as-you-go financing plans spread over many months", "Free solar kits with no repayment", "One-time cash payments only", "Loans repayable within twenty-four hours"], "Pay-as-you-go financing plans spread over many months",
      "The passage says micro-finance institutions offer 'pay-as-you-go financing plans, allowing families to spread the cost...over many months.'"),
  _ucq2("What limitation of solar systems do critics point out in the passage?",
      ["They cannot yet power the heavy machinery needed for large-scale manufacturing", "They are more expensive than grid electricity everywhere", "They cannot charge mobile phones", "They are illegal in most Nigerian states"], "They cannot yet power the heavy machinery needed for large-scale manufacturing",
      "The passage notes that critics say 'solar systems alone cannot yet power the heavy machinery needed for large-scale manufacturing.'"),
  _ucq2("According to development experts mentioned in the passage, what benefits can modest solar access bring?",
      ["Extending study hours, improving night safety, and enabling businesses to operate later", "Eliminating the need for micro-finance institutions", "Replacing all heavy manufacturing machinery", "Ending rural-to-urban migration completely"], "Extending study hours, improving night safety, and enabling businesses to operate later",
      "The passage states experts believe solar access can transform daily life by 'extending study hours for children, improving safety at night, and enabling small businesses to operate later.'"),
  _ucq2("What is the closest meaning of the word 'burdensome' as used in the passage?",
      ["Difficult to bear", "Extremely cheap", "Highly convenient", "Completely optional"], "Difficult to bear",
      "'Burdensome' describes something that is a heavy load to bear, fitting the cost that many households 'still find burdensome.'"),

  // --- Reading comprehension: passage 3 ---
  _ucq3("According to the passage, why does cramming the night before an examination rarely lead to lasting understanding?",
      ["Because information absorbed under stress is quickly forgotten", "Because examinations rarely test memorised material", "Because most students sleep through the night regardless", "Because lecturers change the syllabus at the last minute"], "Because information absorbed under stress is quickly forgotten",
      "The passage states that 'information absorbed under stress is quickly forgotten', which is why cramming rarely leads to lasting understanding."),
  _ucq3("What does spaced repetition involve, according to the passage?",
      ["Reviewing material in short sessions spread out over days or weeks", "Studying for twelve continuous hours without a break", "Reading a textbook only once before the examination", "Memorising answers from previous candidates"], "Reviewing material in short sessions spread out over days or weeks",
      "The passage defines spaced repetition as 'reviewing material in short sessions spread out over days or weeks.'"),
  _ucq3("Why is practising with past examination questions described as valuable in the passage?",
      ["It forces active recall, which embeds information more securely than passive re-reading", "It guarantees the exact same questions will reappear", "It replaces the need for reading textbooks entirely", "It is required by every examination body"], "It forces active recall, which embeds information more securely than passive re-reading",
      "The passage explains that practising past questions 'forces active recall, a process proven to embed information far more securely than passive re-reading of notes.'"),
  _ucq3("What role does sleep play in studying, according to the passage?",
      ["Memory consolidation largely occurs during sleep, so adequate rest improves performance", "Sleep has no effect on examination performance", "Sleeping less always improves recall of information", "Sleep only matters for physical, not academic, performance"], "Memory consolidation largely occurs during sleep, so adequate rest improves performance",
      "The passage states that 'memory consolidation largely occurs during sleep', so students who rest adequately tend to perform better."),
  _ucq3("What is the main idea suggested at the end of the passage?",
      ["How a student studies matters just as much as how long they study", "Only the total number of study hours matters", "Sleep is unnecessary for academic success", "Cramming is the most effective study method"], "How a student studies matters just as much as how long they study",
      "The passage concludes that 'how a student studies matters just as much as how long they study.'"),
];

final _mathematics = [
  _mq("Simplify: 4(2x + 3) - 2(x - 5)",
      ["6x + 22", "6x + 2", "10x + 22", "6x - 22"], "6x + 22",
      "4(2x+3) - 2(x-5) = 8x + 12 - 2x + 10 = 6x + 22."),
  _mq("Solve for x: 5x - 7 = 23",
      ["x = 6", "x = 30", "x = 3", "x = 4"], "x = 6",
      "5x - 7 = 23, so 5x = 30, giving x = 6."),
  _mq("What is the value of 3^4?",
      ["81", "12", "64", "34"], "81",
      "3^4 = 3x3x3x3 = 81."),
  _mq("Simplify: (2/3) + (1/6)",
      ["5/6", "3/9", "1/2", "3/6"], "5/6",
      "Using a common denominator of 6: (2/3 = 4/6) + (1/6) = 5/6."),
  _mq("Find x if 6x + 5 = 3x + 26",
      ["x = 7", "x = 3", "x = 21", "x = 31"], "x = 7",
      "6x + 5 = 3x + 26, so 3x = 21, giving x = 7."),
  _mq("What is 15% of 480?",
      ["72", "64", "48", "32"], "72",
      "15% of 480 = 0.15 x 480 = 72."),
  _mq("The average of 8 numbers is 12. What is their sum?",
      ["96", "12", "20", "84"], "96",
      "Sum = average x count = 12 x 8 = 96."),
  _mq("Solve: x^2 - 25 = 0",
      ["x = 5 or x = -5", "x = 25 or x = -25", "x = 5 only", "x = -25 only"], "x = 5 or x = -5",
      "x^2 = 25, so x = sqrt(25) = +-5, giving x = 5 or x = -5."),
  _mq("If the ratio of technical to non-technical staff in a workshop is 3:4 and there are 12 technical staff, how many non-technical staff are there?",
      ["16", "9", "20", "48"], "16",
      "3 parts = 12, so 1 part = 4. Non-technical staff = 4 parts = 4 x 4 = 16."),
  _mq("What is the perimeter of a square workshop floor with side length 12m?",
      ["48m", "144m", "24m", "36m"], "48m",
      "Perimeter of a square = 4 x side = 4 x 12 = 48m."),
  _mq("What is the area of a circular water tank base with radius 7m? (Use pi = 22/7)",
      ["154 m^2", "44 m^2", "22 m^2", "308 m^2"], "154 m^2",
      "Area = pi r^2 = (22/7) x 7 x 7 = 22 x 7 = 154 m^2."),
  _mq("Simplify: 2^3 x 2^4",
      ["2^7 = 128", "2^12", "4^7", "2^1 = 2"], "2^7 = 128",
      "When multiplying powers with the same base, add the exponents: 2^3 x 2^4 = 2^7 = 128."),
  _mq("What is the value of the square root of 196?",
      ["14", "13", "49", "98"], "14",
      "The square root of 196 is 14, since 14 x 14 = 196."),
  _mq("A vehicle travels 150km in 2.5 hours. What is its average speed?",
      ["60 km/h", "375 km/h", "75 km/h", "50 km/h"], "60 km/h",
      "Average speed = distance/time = 150/2.5 = 60 km/h."),
  _mq("Solve for x: (x/5) - 2 = 4",
      ["x = 30", "x = 6", "x = 20", "x = 1.2"], "x = 30",
      "(x/5) = 6, so x = 30."),
  _mq("What is the sum of the interior angles of a heptagon (7 sides)?",
      ["900 degrees", "720 degrees", "540 degrees", "1080 degrees"], "900 degrees",
      "The sum of interior angles of a polygon = (n-2) x 180, so for a heptagon (n=7): (7-2) x 180 = 900 degrees."),
  _mq("What is the sum of the interior angles of an octagon (8 sides)?",
      ["1080 degrees", "900 degrees", "720 degrees", "1260 degrees"], "1080 degrees",
      "Using (n-2) x 180 for an octagon (n=8): (8-2) x 180 = 1080 degrees."),
  _mq("Factorise: x^2 - 9x + 20",
      ["(x - 4)(x - 5)", "(x + 4)(x + 5)", "(x - 2)(x - 10)", "(x + 20)(x - 1)"], "(x - 4)(x - 5)",
      "We need two numbers that multiply to 20 and add to -9: -4 and -5. So x^2-9x+20 = (x-4)(x-5)."),
  _mq("What is 0.75 expressed as a fraction in its lowest terms?",
      ["3/4", "75/100", "7/10", "2/3"], "3/4",
      "0.75 = 75/100, which simplifies to 3/4 when divided by 25."),
  _mq("If a = 6 and b = -2, find the value of a^2 - b^2",
      ["32", "40", "8", "16"], "32",
      "a^2 - b^2 = 36 - 4 = 32."),
  _mq("What is the median of the data set: 3, 7, 9, 14, 22?",
      ["9", "7", "14", "11"], "9",
      "With 5 values arranged in order (3,7,9,14,22), the median is the middle value: 9."),
  _mq("What is the mode of the data set: 2, 4, 4, 7, 9, 4, 10?",
      ["4", "7", "9", "10"], "4",
      "The mode is the most frequently occurring value; 4 appears three times, more than any other value."),
  _mq("Convert 7/8 to a percentage.",
      ["87.5%", "78%", "7.8%", "80%"], "87.5%",
      "7/8 = 0.875, which as a percentage is 87.5%."),
  _mq("What is the LCM (Lowest Common Multiple) of 4 and 10?",
      ["20", "40", "14", "2"], "20",
      "Multiples of 4: 4,8,12,16,20...; multiples of 10: 10,20...; the smallest common multiple is 20."),
  _mq("What is the HCF (Highest Common Factor) of 24 and 36?",
      ["12", "6", "72", "4"], "12",
      "The factors of 24 are 1,2,3,4,6,8,12,24; factors of 36 are 1,2,3,4,6,9,12,18,36; the highest common factor is 12."),
  _mq("If 2x + 3y = 18 and x = 3, find the value of y.",
      ["4", "3", "6", "5"], "4",
      "Substituting x=3: 2(3) + 3y = 18, so 6 + 3y = 18, giving 3y = 12, so y = 4."),
  _mq("A trader sells a laptop for N78,000 after a 15% discount on the original price. What was the original price?",
      ["N91,764.71 (approx N91,765)", "N89,700", "N66,300", "N93,600"], "N91,764.71 (approx N91,765)",
      "If N78,000 represents 85% of the original price, then original price = 78,000/0.85 approx N91,764.71."),
  _mq("What is the next number in the sequence: 4, 12, 36, 108, ___?",
      ["324", "216", "432", "144"], "324",
      "Each term is multiplied by 3 to get the next term: 108 x 3 = 324."),
  _mq("Simplify: (3a^2b) x (3ab^2)",
      ["9a^3b^3", "6a^3b^3", "9a^2b^2", "6a^2b^2"], "9a^3b^3",
      "Multiplying coefficients: 3x3=9. Multiplying a terms: a^2 x a = a^3. Multiplying b terms: b x b^2 = b^3. Result: 9a^3b^3."),
  _mq("What is the value of x in the equation: 3(x - 2) = 2(x + 4)",
      ["x = 14", "x = 4", "x = 6", "x = 10"], "x = 14",
      "3x - 6 = 2x + 8, so 3x - 2x = 8 + 6, giving x = 14."),
  _mq("A rectangular workshop floor has an area of 200 square metres and a width of 8 metres. What is its length?",
      ["25 metres", "20 metres", "16 metres", "12 metres"], "25 metres",
      "Length = Area/Width = 200/8 = 25 metres."),
  _mq("What is the probability of picking a defective bolt from a box containing 5 defective and 15 good bolts?",
      ["1/4", "1/3", "5/15", "1/5"], "1/4",
      "Total bolts = 5 + 15 = 20. Probability of defective = 5/20 = 1/4."),
  _mq("Express 6.3 x 10^3 as an ordinary number.",
      ["6,300", "630", "63,000", "0.0063"], "6,300",
      "6.3 x 10^3 = 6.3 x 1,000 = 6,300."),

  // --- Indices, logarithms, and number bases ---
  _mq("Simplify: 2^5 x 2^-2",
      ["8", "32", "2", "16"], "8",
      "When multiplying powers with the same base, add the exponents: 2^5 x 2^-2 = 2^3 = 8."),
  _mq("Evaluate: (3^2)^3",
      ["729", "81", "54", "243"], "729",
      "When raising a power to a power, multiply the exponents: (3^2)^3 = 3^6 = 729."),
  _mq("Evaluate: 16^(1/2)",
      ["4", "8", "2", "16"], "4",
      "16^(1/2) means the square root of 16, which is 4, since 4 x 4 = 16."),
  _mq("Evaluate: 27^(1/3)",
      ["3", "9", "27", "1"], "3",
      "27^(1/3) means the cube root of 27, which is 3, since 3 x 3 x 3 = 27."),
  _mq("Simplify: x^5 / x^2",
      ["x^3", "x^7", "x^2.5", "x^10"], "x^3",
      "When dividing powers with the same base, subtract the exponents: x^5/x^2 = x^(5-2) = x^3."),
  _mq("Evaluate: 5^0",
      ["1", "0", "5", "Undefined"], "1",
      "Any non-zero number raised to the power of zero equals 1, so 5^0 = 1."),
  _mq("Simplify: 2^3 x 2^-5",
      ["1/4", "4", "1/8", "8"], "1/4",
      "2^3 x 2^-5 = 2^(3-5) = 2^-2 = 1/2^2 = 1/4."),
  _mq("Evaluate: log base 10 of 100",
      ["2", "10", "100", "1"], "2",
      "log10(100) asks '10 raised to what power gives 100?'; since 10^2 = 100, the answer is 2."),
  _mq("Evaluate: log base 2 of 8",
      ["3", "4", "2", "8"], "3",
      "log2(8) asks '2 raised to what power gives 8?'; since 2^3 = 8, the answer is 3."),
  _mq("If log10 2 = 0.3010, find log10 4",
      ["0.6020", "0.3010", "0.9030", "1.2040"], "0.6020",
      "log10(4) = log10(2^2) = 2 x log10(2) = 2 x 0.3010 = 0.6020."),
  _mq("Convert the binary number 101101 to base 10.",
      ["45", "43", "53", "46"], "45",
      "101101 in binary = (1x32)+(0x16)+(1x8)+(1x4)+(0x2)+(1x1) = 32+8+4+1 = 45."),
  _mq("Convert 37 (base 10) to base 2.",
      ["100101", "101001", "110010", "100110"], "100101",
      "37 = 32+4+1 = (1x32)+(0x16)+(0x8)+(1x4)+(0x2)+(1x1), which is 100101 in base 2."),
  _mq("Convert 2A (base 16) to base 10.",
      ["42", "40", "44", "52"], "42",
      "In base 16, 2A = (2x16)+(10x1) = 32+10 = 42, since A represents 10."),
  _mq("Simplify: (2^4 x 2^3) / 2^5",
      ["4", "2", "8", "16"], "4",
      "(2^4 x 2^3)/2^5 = 2^(4+3-5) = 2^2 = 4."),
  _mq("Solve for x: log base 2 of x = 5",
      ["x = 32", "x = 10", "x = 25", "x = 16"], "x = 32",
      "log2(x) = 5 means 2^5 = x, so x = 32."),

  // --- Algebra ---
  _mq("Solve for x: 2(x + 3) = 3(x - 1)",
      ["x = 9", "x = 3", "x = -9", "x = -3"], "x = 9",
      "2x + 6 = 3x - 3, so 6 + 3 = 3x - 2x, giving x = 9."),
  _mq("Expand: (x + 2)(x - 5)",
      ["x^2 - 3x - 10", "x^2 + 3x - 10", "x^2 - 3x + 10", "x^2 - 7x - 10"], "x^2 - 3x - 10",
      "(x+2)(x-5) = x^2 - 5x + 2x - 10 = x^2 - 3x - 10."),
  _mq("Factorise: x^2 - 16",
      ["(x - 4)(x + 4)", "(x - 8)(x + 2)", "(x - 16)(x + 1)", "(x - 2)(x + 8)"], "(x - 4)(x + 4)",
      "x^2 - 16 is a difference of two squares: x^2 - 4^2 = (x-4)(x+4)."),
  _mq("If 3x + 2y = 12 and x = 2, find the value of y.",
      ["3", "6", "4", "1"], "3",
      "Substituting x=2: 3(2) + 2y = 12, so 6 + 2y = 12, giving 2y = 6, so y = 3."),
  _mq("Simplify: 5x - (2x - 7)",
      ["3x + 7", "3x - 7", "7x + 7", "3x + 14"], "3x + 7",
      "5x - (2x - 7) = 5x - 2x + 7 = 3x + 7."),
  _mq("Solve: x^2 - 5x + 6 = 0",
      ["x = 2 or x = 3", "x = -2 or x = -3", "x = 1 or x = 6", "x = 6 only"], "x = 2 or x = 3",
      "We need two numbers that multiply to 6 and add to -5: -2 and -3. So (x-2)(x-3)=0, giving x = 2 or x = 3."),
  _mq("Simplify: (2x^3 y^2) / (4xy)",
      ["x^2y/2", "2x^2y", "x^2y", "x^3y^2/4"], "x^2y/2",
      "Dividing coefficients: 2/4 = 1/2. Dividing x terms: x^3/x = x^2. Dividing y terms: y^2/y = y. Result: x^2y/2."),
  _mq("Expand: (x - 3)^2",
      ["x^2 - 6x + 9", "x^2 + 6x + 9", "x^2 - 9", "x^2 - 6x - 9"], "x^2 - 6x + 9",
      "(x-3)^2 = (x-3)(x-3) = x^2 - 3x - 3x + 9 = x^2 - 6x + 9."),
  _mq("Solve for x: (x + 1)/3 = 4",
      ["x = 11", "x = 13", "x = 9", "x = 15"], "x = 11",
      "Multiplying both sides by 3: x + 1 = 12, so x = 11."),
  _mq("Simplify: 3(2x - 1) - 2(x + 4)",
      ["4x - 11", "4x + 11", "8x - 11", "4x - 5"], "4x - 11",
      "3(2x-1) - 2(x+4) = 6x - 3 - 2x - 8 = 4x - 11."),
  _mq("If f(x) = 2x^2 - 3x + 1, find f(2).",
      ["3", "9", "-3", "11"], "3",
      "f(2) = 2(2)^2 - 3(2) + 1 = 2(4) - 6 + 1 = 8 - 6 + 1 = 3."),
  _mq("Solve the simultaneous equations: x + y = 10, x - y = 2",
      ["x = 6, y = 4", "x = 4, y = 6", "x = 8, y = 2", "x = 5, y = 5"], "x = 6, y = 4",
      "Adding both equations: 2x = 12, so x = 6. Substituting into x+y=10 gives y = 4."),
  _mq("Factorise: 2x^2 + 7x + 3",
      ["(2x + 1)(x + 3)", "(2x + 3)(x + 1)", "(2x - 1)(x - 3)", "(x + 1)(2x + 3)"], "(2x + 1)(x + 3)",
      "We need factors of 2x^2+7x+3 whose cross terms sum to 7x: (2x+1)(x+3) = 2x^2+6x+x+3 = 2x^2+7x+3."),
  _mq("Solve: x^2 = 7x",
      ["x = 0 or x = 7", "x = 7 only", "x = 0 only", "x = -7 or x = 0"], "x = 0 or x = 7",
      "x^2 - 7x = 0, so x(x-7) = 0, giving x = 0 or x = 7."),
  _mq("Simplify: (a + b)^2 - (a - b)^2",
      ["4ab", "2ab", "a^2 + b^2", "0"], "4ab",
      "(a+b)^2 - (a-b)^2 = (a^2+2ab+b^2) - (a^2-2ab+b^2) = 4ab."),

  // --- Sequences and series ---
  _mq("Find the 10th term of the arithmetic progression: 3, 7, 11, ...",
      ["39", "43", "35", "42"], "39",
      "With a=3 and d=4, T10 = a + 9d = 3 + 9(4) = 3 + 36 = 39."),
  _mq("Find the sum of the first 20 terms of the arithmetic progression: 2, 5, 8, ...",
      ["610", "600", "620", "580"], "610",
      "With a=2, d=3, n=20: Sn = n/2 x [2a + (n-1)d] = 10 x [4 + 57] = 10 x 61 = 610."),
  _mq("Find the common ratio of the geometric progression: 2, 6, 18, 54, ...",
      ["3", "4", "2", "9"], "3",
      "The common ratio is found by dividing any term by the previous term: 6/2 = 3."),
  _mq("Find the 6th term of the geometric progression: 5, 10, 20, ...",
      ["160", "80", "320", "150"], "160",
      "With a=5, r=2: T6 = a x r^5 = 5 x 32 = 160."),
  _mq("Find the sum to infinity of the geometric progression: 8, 4, 2, ...",
      ["16", "12", "20", "8"], "16",
      "With a=8, r=1/2: S(infinity) = a/(1-r) = 8/(1-0.5) = 8/0.5 = 16."),
  _mq("Find the next number in the sequence: 1, 4, 9, 16, 25, ___?",
      ["36", "30", "49", "32"], "36",
      "The sequence is of perfect squares (1^2, 2^2, 3^2, ...); the next term is 6^2 = 36."),
  _mq("Find the next number in the sequence: 2, 3, 5, 8, 13, ___?",
      ["21", "20", "18", "26"], "21",
      "Each term is the sum of the two preceding terms (a Fibonacci-style sequence): 8 + 13 = 21."),
  _mq("Find the arithmetic mean between 12 and 28.",
      ["20", "18", "22", "24"], "20",
      "The arithmetic mean of two numbers is their sum divided by 2: (12+28)/2 = 40/2 = 20."),
  _mq("Find the sum of the first 15 natural numbers.",
      ["120", "105", "135", "110"], "120",
      "Sum = n(n+1)/2 = 15(16)/2 = 240/2 = 120."),
  _mq("Find the 12th term of the arithmetic progression: 5, 9, 13, ...",
      ["49", "45", "53", "48"], "49",
      "With a=5, d=4: T12 = a + 11d = 5 + 11(4) = 5 + 44 = 49."),

  // --- Mensuration ---
  _mq("Find the area of a rectangular plot measuring 15m by 8m.",
      ["120 m^2", "23 m^2", "60 m^2", "46 m^2"], "120 m^2",
      "Area of a rectangle = length x width = 15 x 8 = 120 m^2."),
  _mq("Find the volume of a cube with side length 4cm.",
      ["64 cm^3", "16 cm^3", "48 cm^3", "256 cm^3"], "64 cm^3",
      "Volume of a cube = side^3 = 4^3 = 64 cm^3."),
  _mq("Find the volume of a cuboid measuring 5cm by 4cm by 3cm.",
      ["60 cm^3", "12 cm^3", "120 cm^3", "47 cm^3"], "60 cm^3",
      "Volume of a cuboid = length x width x height = 5 x 4 x 3 = 60 cm^3."),
  _mq("Find the circumference of a circle with radius 14cm. (Use pi = 22/7)",
      ["88 cm", "44 cm", "308 cm", "176 cm"], "88 cm",
      "Circumference = 2 x pi x r = 2 x (22/7) x 14 = 88 cm."),
  _mq("Find the area of a triangle with base 10cm and height 6cm.",
      ["30 cm^2", "60 cm^2", "16 cm^2", "20 cm^2"], "30 cm^2",
      "Area of a triangle = (1/2) x base x height = (1/2) x 10 x 6 = 30 cm^2."),
  _mq("Find the volume of a cylinder with radius 7cm and height 10cm. (Use pi = 22/7)",
      ["1,540 cm^3", "770 cm^3", "308 cm^3", "3,080 cm^3"], "1,540 cm^3",
      "Volume = pi r^2 h = (22/7) x 49 x 10 = 22 x 7 x 10 = 1,540 cm^3."),
  _mq("Find the total surface area of a cube with side length 5cm.",
      ["150 cm^2", "25 cm^2", "125 cm^2", "100 cm^2"], "150 cm^2",
      "Total surface area of a cube = 6 x side^2 = 6 x 25 = 150 cm^2."),
  _mq("Find the area of a trapezium with parallel sides 8cm and 12cm, and height 5cm.",
      ["50 cm^2", "100 cm^2", "20 cm^2", "40 cm^2"], "50 cm^2",
      "Area of a trapezium = (1/2)(sum of parallel sides) x height = (1/2)(8+12) x 5 = 10 x 5 = 50 cm^2."),
  _mq("Find the perimeter of a rectangle with length 20cm and width 9cm.",
      ["58 cm", "29 cm", "180 cm", "49 cm"], "58 cm",
      "Perimeter of a rectangle = 2(length + width) = 2(20+9) = 2(29) = 58 cm."),
  _mq("Find the area of a parallelogram with base 9cm and height 4cm.",
      ["36 cm^2", "26 cm^2", "18 cm^2", "13 cm^2"], "36 cm^2",
      "Area of a parallelogram = base x height = 9 x 4 = 36 cm^2."),
  _mq("Find the volume of a sphere with radius 3cm. (Use pi = 22/7 and volume = (4/3) pi r^3)",
      ["113.14 cm^3 (approx)", "36 cm^3", "254.57 cm^3", "28.29 cm^3"], "113.14 cm^3 (approx)",
      "Volume = (4/3) x (22/7) x 3^3 = (4/3) x (22/7) x 27 = 2,376/21 = approximately 113.14 cm^3."),
  _mq("Find the total surface area of a cylinder with radius 7cm and height 10cm. (Use pi = 22/7)",
      ["748 cm^2", "440 cm^2", "1,540 cm^2", "374 cm^2"], "748 cm^2",
      "Total surface area = 2 pi r(h + r) = 2 x (22/7) x 7 x (10+7) = 2 x 22 x 17 = 748 cm^2."),
  _mq("Find the area of a circle with diameter 21cm. (Use pi = 22/7)",
      ["346.5 cm^2", "693 cm^2", "173.25 cm^2", "441 cm^2"], "346.5 cm^2",
      "Radius = 21/2 = 10.5cm. Area = pi r^2 = (22/7) x 10.5^2 = (22/7) x 110.25 = 346.5 cm^2."),
  _mq("Find the area of a square with diagonal 10cm.",
      ["50 cm^2", "100 cm^2", "25 cm^2", "70.7 cm^2"], "50 cm^2",
      "Area of a square from its diagonal = (diagonal^2)/2 = 100/2 = 50 cm^2."),
  _mq("Find the volume of a cone with radius 6cm and height 7cm. (Use pi = 22/7)",
      ["264 cm^3", "528 cm^3", "88 cm^3", "792 cm^3"], "264 cm^3",
      "Volume of a cone = (1/3) pi r^2 h = (1/3) x (22/7) x 36 x 7 = (1/3) x 22 x 36 = 264 cm^3."),

  // --- Geometry ---
  _mq("Find the sum of the interior angles of a pentagon (5 sides).",
      ["540 degrees", "360 degrees", "720 degrees", "450 degrees"], "540 degrees",
      "Sum of interior angles = (n-2) x 180. For a pentagon (n=5): (5-2) x 180 = 540 degrees."),
  _mq("Find the size of each interior angle of a regular hexagon (6 sides).",
      ["120 degrees", "108 degrees", "135 degrees", "140 degrees"], "120 degrees",
      "Sum of interior angles of a hexagon = (6-2) x 180 = 720 degrees. Each angle = 720/6 = 120 degrees."),
  _mq("Find the exterior angle of a regular polygon with 9 sides.",
      ["40 degrees", "45 degrees", "36 degrees", "60 degrees"], "40 degrees",
      "Exterior angle of a regular polygon = 360/n = 360/9 = 40 degrees."),
  _mq("Angles on a straight line always sum to how many degrees?",
      ["180 degrees", "90 degrees", "360 degrees", "270 degrees"], "180 degrees",
      "Angles on a straight line are supplementary and always sum to 180 degrees."),
  _mq("Angles at a point always sum to how many degrees?",
      ["360 degrees", "180 degrees", "270 degrees", "90 degrees"], "360 degrees",
      "Angles that meet at a single point always sum to 360 degrees."),
  _mq("In a right-angled triangle, one of the other two angles is 35 degrees. Find the third angle.",
      ["55 degrees", "65 degrees", "45 degrees", "50 degrees"], "55 degrees",
      "The angles of a triangle sum to 180 degrees. With a right angle (90) and 35 degrees, the third angle = 180 - 90 - 35 = 55 degrees."),
  _mq("Each interior angle of a regular polygon is 150 degrees. How many sides does the polygon have?",
      ["12", "10", "15", "9"], "12",
      "Exterior angle = 180 - 150 = 30 degrees. Number of sides = 360/30 = 12."),
  _mq("When two parallel lines are cut by a transversal, the corresponding angles formed are always:",
      ["Equal", "Supplementary", "Complementary", "Unrelated"], "Equal",
      "Corresponding angles formed when a transversal cuts two parallel lines are always equal."),
  _mq("The sum of the interior angles of any triangle is always:",
      ["180 degrees", "360 degrees", "90 degrees", "270 degrees"], "180 degrees",
      "The interior angles of any triangle always sum to 180 degrees."),
  _mq("A triangle with exactly two equal sides is called:",
      ["Isosceles", "Scalene", "Equilateral", "Right-angled"], "Isosceles",
      "A triangle with exactly two equal sides (and two equal base angles) is called an isosceles triangle."),

  // --- Trigonometry ---
  _mq("Evaluate: sin 30 degrees",
      ["1/2", "sqrt(3)/2", "1", "0"], "1/2",
      "sin 30 degrees is a standard trigonometric value equal to 1/2."),
  _mq("Evaluate: cos 60 degrees",
      ["1/2", "sqrt(3)/2", "1", "0"], "1/2",
      "cos 60 degrees is a standard trigonometric value equal to 1/2."),
  _mq("Evaluate: tan 45 degrees",
      ["1", "0", "sqrt(3)", "1/2"], "1",
      "tan 45 degrees is a standard trigonometric value equal to 1, since sin 45 = cos 45."),
  _mq("Simplify: sin^2 x + cos^2 x",
      ["1", "0", "2", "1/2"], "1",
      "By the Pythagorean identity, sin^2 x + cos^2 x = 1 for any angle x."),
  _mq("A right-angled triangle has legs of length 6cm and 8cm. Find the length of the hypotenuse.",
      ["10 cm", "14 cm", "48 cm", "100 cm"], "10 cm",
      "By Pythagoras' theorem: hypotenuse = sqrt(6^2 + 8^2) = sqrt(36+64) = sqrt(100) = 10 cm."),
  _mq("If sin x = 0.6 and x is acute, find cos x.",
      ["0.8", "0.6", "1", "0.4"], "0.8",
      "Using the 3-4-5 right triangle where sin x = 3/5 = 0.6, cos x = 4/5 = 0.8. Check: 0.6^2+0.8^2 = 0.36+0.64 = 1."),
  _mq("Evaluate: tan 30 degrees",
      ["1/sqrt(3)", "sqrt(3)", "1", "2"], "1/sqrt(3)",
      "tan 30 degrees is a standard trigonometric value equal to 1/sqrt(3) (approximately 0.577)."),
  _mq("Evaluate: cos 0 degrees",
      ["1", "0", "-1", "90"], "1",
      "cos 0 degrees is a standard trigonometric value equal to 1."),
  _mq("Evaluate: sin 90 degrees",
      ["1", "0", "-1", "0.5"], "1",
      "sin 90 degrees is a standard trigonometric value equal to 1."),
  _mq("A ladder 10m long leans against a wall, making an angle of 60 degrees with the ground. Find the height it reaches on the wall.",
      ["5 x sqrt(3) m (approx 8.66 m)", "10 m", "5 m", "6.66 m"], "5 x sqrt(3) m (approx 8.66 m)",
      "Height = 10 x sin 60 degrees = 10 x (sqrt(3)/2) = 5 x sqrt(3), which is approximately 8.66 m."),

  // --- Statistics and probability ---
  _mq("Find the mean of the data set: 4, 8, 6, 10, 12",
      ["8", "9", "10", "7"], "8",
      "Mean = sum of values / number of values = (4+8+6+10+12)/5 = 40/5 = 8."),
  _mq("Find the range of the data set: 5, 9, 3, 17, 8",
      ["14", "12", "17", "9"], "14",
      "Range = highest value - lowest value = 17 - 3 = 14."),
  _mq("What is the probability of rolling a 6 on a single fair six-sided die?",
      ["1/6", "1/3", "1/2", "1/12"], "1/6",
      "A fair die has 6 equally likely outcomes, so the probability of any single number is 1/6."),
  _mq("What is the probability of drawing a red card from a standard deck of 52 playing cards?",
      ["1/2", "1/4", "1/13", "1/26"], "1/2",
      "A standard deck has 26 red cards out of 52 total, so the probability is 26/52 = 1/2."),
  _mq("Find the mean of the first 10 natural numbers (1 to 10).",
      ["5.5", "5", "6", "10"], "5.5",
      "Sum of 1 to 10 = 55. Mean = 55/10 = 5.5."),
  _mq("Find the mode of the data set: 3, 5, 5, 7, 9, 5, 2",
      ["5", "3", "7", "9"], "5",
      "The mode is the most frequently occurring value; 5 appears three times, more than any other value."),
  _mq("Find the median of the data set: 12, 15, 11, 20, 18",
      ["15", "12", "18", "14"], "15",
      "Arranging in order: 11, 12, 15, 18, 20. With 5 values, the median is the middle value: 15."),
  _mq("Two fair coins are tossed. What is the probability that both show heads?",
      ["1/4", "1/2", "1/3", "3/4"], "1/4",
      "The probability of heads on one coin is 1/2. For two independent coins both showing heads: 1/2 x 1/2 = 1/4."),
  _mq("A bag contains 4 red balls and 6 blue balls. What is the probability of picking a blue ball at random?",
      ["3/5", "2/5", "1/2", "6/4"], "3/5",
      "Total balls = 4 + 6 = 10. Probability of blue = 6/10 = 3/5."),
  _mq("In a class of 30 students, 18 offer Physics. What is the probability that a randomly chosen student offers Physics?",
      ["3/5", "3/10", "9/15", "1/2"], "3/5",
      "Probability = number offering Physics / total students = 18/30 = 3/5."),
  _mq("Find the range of the data set: 22, 45, 12, 38, 9",
      ["36", "33", "45", "13"], "36",
      "Range = highest value - lowest value = 45 - 9 = 36."),
  _mq("Find the mean of the data set: 2, 4, 4, 6, 8, 8, 10",
      ["6", "5", "7", "4"], "6",
      "Mean = sum of values / number of values = (2+4+4+6+8+8+10)/7 = 42/7 = 6."),
  _mq("What is the probability of NOT rolling a 3 on a single fair six-sided die?",
      ["5/6", "1/6", "1/2", "2/3"], "5/6",
      "The probability of rolling a 3 is 1/6, so the probability of not rolling a 3 is 1 - 1/6 = 5/6."),
  _mq("In a survey of 200 people, 60 said they prefer tea. What percentage of the people surveyed prefer tea?",
      ["30%", "60%", "40%", "20%"], "30%",
      "Percentage = (60/200) x 100 = 30%."),
  _mq("Find the mean of the first 5 even numbers: 2, 4, 6, 8, 10",
      ["6", "5", "8", "7"], "6",
      "Sum of the first 5 even numbers = 2+4+6+8+10 = 30. Mean = 30/5 = 6."),

  // --- Word problems ---
  _mq("A man's age is 3 times his son's age. If the sum of their ages is 48 years, find the son's age.",
      ["12 years", "16 years", "36 years", "24 years"], "12 years",
      "Let the son's age be x; the man's age is 3x. Then x + 3x = 48, so 4x = 48, giving x = 12 years."),
  _mq("A car covers 240km using 20 litres of fuel. Find the car's fuel consumption rate in km per litre.",
      ["12 km/L", "10 km/L", "20 km/L", "24 km/L"], "12 km/L",
      "Fuel consumption rate = distance/fuel used = 240/20 = 12 km/L."),
  _mq("Two numbers differ by 5, and their sum is 23. Find the two numbers.",
      ["9 and 14", "8 and 13", "10 and 15", "7 and 12"], "9 and 14",
      "Let the numbers be x and x+5. Then x + (x+5) = 23, so 2x = 18, giving x = 9 and the other number 14."),
  _mq("A trader buys goods for N5,000 and sells them for N6,200. Find the percentage profit.",
      ["24%", "20%", "12%", "30%"], "24%",
      "Profit = 6,200 - 5,000 = N1,200. Percentage profit = (1,200/5,000) x 100 = 24%."),
  _mq("Find the simple interest on N20,000 at 5% per annum for 3 years.",
      ["N3,000", "N4,000", "N2,000", "N5,000"], "N3,000",
      "Simple Interest = (P x R x T)/100 = (20,000 x 5 x 3)/100 = 300,000/100 = N3,000."),
  _mq("A tank is filled by pipe A in 6 hours. What fraction of the tank does pipe A fill in one hour?",
      ["1/6", "1/5", "6", "1/12"], "1/6",
      "If the pipe fills the whole tank in 6 hours, it fills 1/6 of the tank in one hour."),
  _mq("The sum of three consecutive integers is 72. Find the three integers.",
      ["23, 24, 25", "24, 25, 26", "22, 24, 26", "20, 24, 28"], "23, 24, 25",
      "Let the integers be n-1, n, n+1. Then 3n = 72, so n = 24, giving the integers 23, 24, and 25."),
  _mq("A worker is paid N450 per hour. Find the worker's pay for 7.5 hours of work.",
      ["N3,375", "N3,150", "N3,500", "N3,600"], "N3,375",
      "Pay = rate x hours = 450 x 7.5 = N3,375."),
  _mq("If 8 workers can complete a job in 15 days, how many days will 12 workers take to complete the same job at the same rate?",
      ["10 days", "12 days", "8 days", "15 days"], "10 days",
      "Total work = 8 x 15 = 120 worker-days. With 12 workers: 120/12 = 10 days."),
  _mq("A shopkeeper marks up goods by 20% on the cost price, then gives a 10% discount on the marked price. Find the overall percentage change relative to the cost price.",
      ["8% increase", "10% increase", "2% increase", "No change"], "8% increase",
      "Taking cost price as 100: marked price = 100 x 1.20 = 120. After a 10% discount: 120 x 0.90 = 108, which is an 8% increase over the original cost price."),
];

final _generalKnowledge = [
  _gq("The Federal University of Technology, Akure (FUTA) is located in which state?",
      ["Ondo State", "Ekiti State", "Osun State", "Edo State"], "Ondo State",
      "FUTA is located in Akure, the capital city of Ondo State, in south-western Nigeria."),
  _gq("In what year was the Federal University of Technology, Akure (FUTA) established?",
      ["1981", "1975", "1990", "2001"], "1981",
      "FUTA was established in 1981 as one of the second generation of Nigerian federal universities dedicated specifically to technology education."),
  _gq("FUTA was established as part of a federal government initiative to create universities with a special focus on which area of study?",
      ["Science and technology", "Law and humanities", "Theology", "Performing arts"], "Science and technology",
      "FUTA was created as a specialist federal university of technology, focused on producing graduates in engineering, science, and technology-related fields."),
  _gq("Akure, the host city of FUTA, serves as the capital of which Nigerian state?",
      ["Ondo State", "Ekiti State", "Kwara State", "Osun State"], "Ondo State",
      "Akure is the capital and largest city of Ondo State."),
  _gq("Ondo State, where FUTA is situated, is particularly well known in Nigeria for the large-scale production of which cash crop?",
      ["Cocoa", "Groundnut", "Cotton", "Kola nut only"], "Cocoa",
      "Ondo State is one of Nigeria's leading cocoa-producing states, with cocoa long forming a major part of the state's agricultural economy."),
  _gq("Which of the following ethnic/sub-ethnic groups forms the majority of the indigenous population of Ondo State?",
      ["Yoruba", "Igbo", "Hausa", "Tiv"], "Yoruba",
      "Ondo State's indigenous population is predominantly Yoruba, including the Akoko, Ondo, Ikale, Ilaje, and Owo sub-groups."),
  _gq("Which of the following is a well-known indigenous festival celebrated among the Yoruba communities of Ondo State?",
      ["Ohori and Igogo festivals", "Argungu fishing festival", "Durbar festival", "Sharo festival"], "Ohori and Igogo festivals",
      "The Igogo festival, celebrated in Owo, is among the notable indigenous festivals of Ondo State's Yoruba communities."),
  _gq("Which body of water forms part of the southern boundary of Ondo State?",
      ["Atlantic Ocean", "Lake Chad", "River Niger only", "Lake Kainji"], "Atlantic Ocean",
      "Ondo State has a coastline along the Atlantic Ocean in its southern riverine areas, including areas near Ilaje."),
  _gq("Which regulatory body is responsible for accrediting academic programmes in Nigerian universities, including FUTA?",
      ["The National Universities Commission (NUC)", "The Joint Admissions and Matriculation Board (JAMB)", "The West African Examinations Council (WAEC)", "The Federal Ministry of Education alone, with no separate agency"], "The National Universities Commission (NUC)",
      "The NUC is the regulatory body responsible for approving and accrediting academic programmes offered by Nigerian universities, ensuring they meet minimum quality standards."),
  _gq("Which of the following best describes the primary role of a Vice-Chancellor in a Nigerian university, such as FUTA?",
      ["Serving as the chief executive and academic head of the university", "Serving as the elected student union president", "Managing only the university's sports facilities", "Serving as an external auditor of the university's accounts"], "Serving as the chief executive and academic head of the university",
      "A Vice-Chancellor is the chief executive and principal academic officer of a Nigerian university, responsible for its overall administration and academic direction."),
  _gq("Which arm of government in Nigeria is primarily responsible for interpreting laws and administering justice?",
      ["The Judiciary", "The Legislature", "The Executive", "The Civil Service"], "The Judiciary",
      "The Judiciary is the arm of government responsible for interpreting laws and adjudicating disputes, distinct from the law-making Legislature and law-enforcing Executive."),
  _gq("What is the term for the Nigerian legislative chamber that represents individual constituencies at the federal level, alongside the Senate?",
      ["House of Representatives", "House of Assembly", "Federal Council", "National Council"], "House of Representatives",
      "The House of Representatives, together with the Senate, forms Nigeria's bicameral National Assembly, with members representing federal constituencies."),
  _gq("Which of the following countries shares a land border with Nigeria?",
      ["Cameroon", "Ghana", "South Africa", "Kenya"], "Cameroon",
      "Nigeria shares land borders with Cameroon, Niger, Chad, and Benin Republic; Ghana, South Africa, and Kenya are not bordering countries."),
  _gq("What is the longest river in Africa?",
      ["River Nile", "River Niger", "River Congo", "River Benue"], "River Nile",
      "The River Nile, flowing through north-eastern Africa, is the longest river on the continent."),
  _gq("Which of the following best describes the primary function of the Independent National Electoral Commission (INEC)?",
      ["Organising and supervising elections in Nigeria", "Regulating the Nigerian banking sector", "Enforcing traffic laws nationwide", "Managing Nigeria's foreign embassies"], "Organising and supervising elections in Nigeria",
      "INEC is Nigeria's independent body responsible for organising, conducting, and supervising elections at the federal and state levels."),
  _gq("What is the chemical symbol for pure oxygen gas?",
      ["O2", "O", "Ox", "O3"], "O2",
      "Oxygen gas exists naturally as a diatomic molecule, represented by the chemical formula O2."),
  _gq("Which planet in our solar system is known as the 'Red Planet'?",
      ["Mars", "Venus", "Jupiter", "Mercury"], "Mars",
      "Mars is often called the 'Red Planet' because of the reddish appearance caused by iron oxide (rust) on its surface."),
  _gq("Which of the following is Cote d'Ivoire's national football team commonly nicknamed?",
      ["The Elephants", "The Black Stars", "The Super Eagles", "The Indomitable Lions"], "The Elephants",
      "Cote d'Ivoire's senior men's national football team is popularly known as the Elephants, distinct from Ghana's Black Stars and Nigeria's Super Eagles."),
  _gq("Which international body is primarily responsible for setting global standards and rules for international trade?",
      ["The World Trade Organization (WTO)", "The United Nations (UN)", "The World Health Organization (WHO)", "The International Monetary Fund (IMF)"], "The World Trade Organization (WTO)",
      "The WTO is the international organisation specifically responsible for establishing and enforcing global rules governing trade between nations."),
  _gq("What is the term for a system of government headed by a king or queen whose powers are limited by a constitution?",
      ["Constitutional monarchy", "Absolute monarchy", "Republic", "Theocracy"], "Constitutional monarchy",
      "A constitutional monarchy is a system in which a monarch serves as head of state, but their powers are limited and defined by a constitution, unlike an absolute monarchy."),
  _gq("Which of the following best describes the primary function of the Nigerian Police Force?",
      ["Maintaining law and order and enforcing criminal law", "Making laws for the federation", "Interpreting the Nigerian constitution", "Managing the country's monetary policy"], "Maintaining law and order and enforcing criminal law",
      "The Nigerian Police Force is the primary law enforcement agency responsible for maintaining public order and enforcing criminal law across the country."),
  _gq("Which of the following is an example of a non-communicable disease?",
      ["Diabetes", "Tuberculosis", "Cholera", "Measles"], "Diabetes",
      "Diabetes is a non-communicable (chronic) disease, unlike tuberculosis, cholera, and measles, which are infectious diseases."),
  _gq("What is the smallest country in the world by land area?",
      ["Vatican City", "Monaco", "San Marino", "Liechtenstein"], "Vatican City",
      "Vatican City, an independent city-state enclaved within Rome, Italy, is the smallest country in the world by land area."),
  _gq("Which of the following best describes the primary role of the executive arm of government?",
      ["Implementing and enforcing laws", "Making laws for the country", "Interpreting the constitution exclusively", "Auditing government accounts exclusively"], "Implementing and enforcing laws",
      "The executive arm, headed by a President or Governor, is primarily responsible for implementing and enforcing the laws made by the legislature."),
  _gq("Which vitamin deficiency is most commonly associated with the bone disease rickets?",
      ["Vitamin D", "Vitamin A", "Vitamin C", "Vitamin B12"], "Vitamin D",
      "Rickets is a disease resulting from a deficiency of Vitamin D, which is essential for calcium absorption and healthy bone development."),
  _gq("What is the term for the total value of all goods and services produced within a country's borders in a given period?",
      ["Gross Domestic Product (GDP)", "Gross National Product (GNP)", "Net National Income", "Balance of Trade"], "Gross Domestic Product (GDP)",
      "GDP specifically measures the value of goods and services produced within a country's borders, regardless of the nationality of the producers."),
  _gq("Which Nigerian author wrote the celebrated play 'Death and the King's Horseman'?",
      ["Wole Soyinka", "Chinua Achebe", "Chimamanda Ngozi Adichie", "Cyprian Ekwensi"], "Wole Soyinka",
      "Wole Soyinka, Nigeria's first Nobel laureate in Literature, wrote the celebrated play 'Death and the King's Horseman.'"),
  _gq("What does the abbreviation 'NAFDAC' stand for in the Nigerian context?",
      ["National Agency for Food and Drug Administration and Control", "National Association for Drug and Chemical Control", "Nigerian Agency for Food and Drug Coordination", "National Authority for Food, Drugs, and Cosmetics"], "National Agency for Food and Drug Administration and Control",
      "NAFDAC regulates and controls the manufacture, importation, and sale of food, drugs, and related products in Nigeria."),
  _gq("What is the term for a persistent, sustained rise in the general price level of goods and services in an economy?",
      ["Inflation", "Deflation", "Recession", "Devaluation"], "Inflation",
      "Inflation describes an ongoing, generalised increase in prices across an economy, the opposite of deflation."),
  _gq("Which of the following best describes the primary aim of the African Continental Free Trade Area (AfCFTA)?",
      ["Creating a single market for goods and services across African countries to boost intra-African trade", "Restricting all trade between African nations", "Regulating global internet governance", "Coordinating African military alliances exclusively"], "Creating a single market for goods and services across African countries to boost intra-African trade",
      "AfCFTA aims to create a single continental market for goods and services, boosting intra-African trade by reducing tariffs and other trade barriers among member states."),
  _gq("Which of the following is a key function of the Central Bank of Nigeria (CBN) relating to currency?",
      ["Issuing and regulating the country's currency (the Naira)", "Setting the retail price of consumer goods", "Managing Nigeria's road transport infrastructure", "Running the national postal service"], "Issuing and regulating the country's currency (the Naira)",
      "One of the CBN's core functions is the sole authority to issue and regulate Nigeria's legal tender currency, the Naira."),
  _gq("Which of the following best describes the primary purpose of the World Health Organization (WHO)?",
      ["Coordinating international public health and disease control efforts", "Regulating international trade tariffs", "Managing global currency exchange rates", "Overseeing international postal services"], "Coordinating international public health and disease control efforts",
      "The WHO is a United Nations agency specifically responsible for coordinating international public health matters, including disease prevention and control."),
  _gq("Which of the following is the largest producer of crude oil in Africa, based on long-established historical ranking?",
      ["Nigeria", "Ghana", "Kenya", "Egypt"], "Nigeria",
      "Nigeria has long been recognised as one of Africa's leading crude oil producers, historically ranking as the continent's largest producer for extended periods."),
  _gq("What is the term for the practice of a country restricting imports through tariffs or quotas to protect domestic industries?",
      ["Protectionism", "Free trade", "Globalisation", "Liberalisation"], "Protectionism",
      "Protectionism refers to government policies that restrict international trade, such as tariffs and quotas, to shield domestic industries from foreign competition."),
];
