import "../quiz_question.dart";

const _subject = "Physical and Health Education";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// JAMB Physical and Health Education (PHE) — 100 questions covering
/// Foundations of Physical Education & Sports, Human Anatomy & Exercise
/// Physiology, and Health Education & Community Health.
List<QuizQuestion> buildJambPheQuestions() {
  return [
    ..._principlesOfPhe,
    ..._athleticsTrackEvents,
    ..._athleticsFieldEvents,
    ..._ballGames,
    ..._gymnasticsAndDance,
    ..._skeletalAndMuscularSystems,
    ..._circulatoryAndRespiratorySystems,
    ..._firstAidAndSportsInjuries,
    ..._personalHealthAndNutrition,
    ..._communicableAndNonCommunicableDiseases,
    ..._drugAndSubstanceAbuse,
    ..._environmentalAndCommunityHealth,
  ];
}

final _principlesOfPhe = [
  _q("Physical Education is best defined as an educational process that primarily uses",
      ["physical activity as a means to develop the total fitness and well-being of an individual", "purely academic classroom instruction with no physical activity", "only competitive professional sports training", "only theoretical study of sports history with no practical activity"], "physical activity as a means to develop the total fitness and well-being of an individual",
      "Physical Education uses purposeful physical activity as an educational tool to develop the physical, mental, social, and emotional well-being of individuals."),
  _q("Which of the following is a recognised general aim of Physical Education?",
      ["Promoting physical fitness, health, and the development of motor skills", "Discouraging any form of physical activity", "Focusing exclusively on producing professional athletes", "Eliminating team sports from the curriculum"], "Promoting physical fitness, health, and the development of motor skills",
      "A core aim of Physical Education is to promote overall physical fitness, health, and the development of fundamental motor skills, benefiting all participants, not just aspiring professional athletes."),
  _q("Recreation, as it relates to Physical Education, refers to",
      ["activities pursued during leisure time for enjoyment, relaxation, and personal fulfilment", "mandatory competitive sports training with no leisure element", "purely academic study with no physical component", "medical treatment for sports injuries"], "activities pursued during leisure time for enjoyment, relaxation, and personal fulfilment",
      "Recreation encompasses activities people choose to engage in during their free time for enjoyment, relaxation, and personal satisfaction, often incorporating physical activity."),
  _q("Which of the following is a recognised career pathway within the field of Physical Education and sports?",
      ["Sports coaching", "Civil engineering", "Pharmacy", "Accounting"], "Sports coaching",
      "Sports coaching is a well-established career pathway within Physical Education, alongside other options such as sports administration, physiotherapy, and PE teaching."),
  _q("The history of organised Physical Education is often traced back significantly to the practices of",
      ["ancient Greece, particularly through the Olympic Games", "modern 21st-century fitness trends exclusively", "purely indoor academic study with no physical activity", "only 20th-century professional sports leagues"], "ancient Greece, particularly through the Olympic Games",
      "Ancient Greek civilisation, notably through the ancient Olympic Games, is widely regarded as a foundational historical influence on the development of organised physical education and competitive sport."),
  _q("Which of the following best describes an objective of Physical Education related to social development?",
      ["Fostering teamwork, cooperation, and fair play through group physical activities", "Encouraging students to avoid all interaction with peers", "Focusing exclusively on individual, solitary activities with no team component", "Discouraging sportsmanship and fair competition"], "Fostering teamwork, cooperation, and fair play through group physical activities",
      "A key social objective of Physical Education is to develop important interpersonal skills such as teamwork, cooperation, and fair play, often cultivated through group and team-based physical activities."),
];

final _athleticsTrackEvents = [
  _q("Sprint events in track athletics typically cover distances of",
      ["100m, 200m, and 400m", "800m, 1500m, and 5000m", "10km, half-marathon, and marathon distances", "only distances beyond 10,000m"], "100m, 200m, and 400m",
      "Sprint events are short-distance races, typically covering 100m, 200m, and 400m, requiring maximum speed over a relatively brief duration."),
  _q("Middle-distance events in track athletics typically include races such as",
      ["800m and 1500m", "100m and 200m sprints", "the marathon (42.195km)", "the long jump and high jump"], "800m and 1500m",
      "Middle-distance races, such as the 800m and 1500m, require a combination of speed and endurance, positioned between short sprints and longer distance events."),
  _q("Long-distance events in track athletics typically include races such as",
      ["5000m, 10,000m, and the marathon", "100m and 200m sprints", "the 400m hurdles", "the 4x100m relay"], "5000m, 10,000m, and the marathon",
      "Long-distance track and road events, such as the 5000m, 10,000m, and marathon, primarily test an athlete's aerobic endurance over extended distances."),
  _q("Hurdles, a track event in athletics, require athletes to",
      ["run a set distance while jumping over a series of fixed barriers", "throw a heavy metal ball as far as possible", "jump over a bar set at increasing heights", "pass a baton to teammates in sequence"], "run a set distance while jumping over a series of fixed barriers",
      "Hurdle races require athletes to sprint a specified distance while clearing a series of evenly spaced barriers (hurdles) without knocking them down."),
  _q("In relay races, an important element of track athletics, competitors must",
      ["pass a baton to the next teammate within a designated exchange zone", "complete the entire race individually with no baton exchange", "throw an implement rather than run", "jump over a series of hurdles individually"], "pass a baton to the next teammate within a designated exchange zone",
      "Relay races require team members to successfully pass a baton to the next runner within a specifically marked exchange zone, with the race disqualified if the exchange occurs outside this zone."),
  _q("The standard distance of the 4x100m relay refers to",
      ["four athletes each running 100m, for a total combined distance of 400m", "a single athlete running 400m alone", "four athletes running 100m simultaneously side by side with no baton exchange", "four separate races of 100m each scored independently"], "four athletes each running 100m, for a total combined distance of 400m",
      "The 4x100m relay involves a team of four athletes, each running a 100m leg and passing the baton to the next teammate, for a total combined race distance of 400m."),
  _q("A false start in a track race occurs when",
      ["a runner leaves the starting blocks before the starting signal is given", "a runner finishes the race in first place", "a runner successfully passes the baton in a relay", "a runner clears a hurdle successfully"], "a runner leaves the starting blocks before the starting signal is given",
      "A false start occurs when an athlete begins moving from the starting blocks before the official starting signal (gun or similar) is given, which can result in disqualification under current rules."),
  _q("Which official in track athletics is primarily responsible for determining the order in which runners finish a race?",
      ["The judge (or photo-finish official)", "The starter", "The timekeeper exclusively, with no role in determining placing", "The groundskeeper"], "The judge (or photo-finish official)",
      "Judges (often assisted by photo-finish technology) are responsible for determining the precise finishing order of competitors in a track race."),
];

final _athleticsFieldEvents = [
  _q("The long jump, a field event in athletics, requires athletes to",
      ["sprint down a runway and jump for maximum horizontal distance into a sand pit", "jump over a horizontal bar for maximum height", "throw a heavy implement for maximum distance", "run a fixed distance as quickly as possible"], "sprint down a runway and jump for maximum horizontal distance into a sand pit",
      "In the long jump, athletes sprint along a runway before jumping from a take-off board, aiming to achieve the maximum horizontal distance before landing in a sand pit."),
  _q("The high jump, a field event in athletics, requires athletes to",
      ["jump over a horizontal bar set at increasing heights without knocking it down", "jump for maximum horizontal distance", "throw an implement for maximum distance", "sprint a fixed distance"], "jump over a horizontal bar set at increasing heights without knocking it down",
      "In the high jump, athletes attempt to clear a horizontal bar set at progressively increasing heights, with the winner being the athlete who clears the greatest height without dislodging the bar."),
  _q("The triple jump, a field event in athletics, is characterised by a sequence of",
      ["a hop, a step, and a jump, performed in a single continuous motion", "three separate identical jumps with rest in between", "a single maximal jump only", "throwing an implement three times in succession"], "a hop, a step, and a jump, performed in a single continuous motion",
      "The triple jump requires athletes to perform a specific sequence of a hop, a step, and a final jump in one continuous, fluid motion, aiming for maximum combined horizontal distance."),
  _q("The shot put, a throwing field event in athletics, requires athletes to",
      ["push (rather than throw with a swinging motion) a heavy spherical metal ball for maximum distance", "throw a discus-shaped implement using a spinning technique", "throw a javelin using a running approach", "jump over a horizontal bar"], "push (rather than throw with a swinging motion) a heavy spherical metal ball for maximum distance",
      "The shot put requires athletes to 'put' (push) a heavy spherical metal ball from the shoulder, rather than throwing it with a swinging arm motion, aiming for maximum distance."),
  _q("The discus throw, a field event in athletics, involves athletes",
      ["spinning within a circle before releasing a flat, disc-shaped implement for maximum distance", "pushing a heavy spherical ball from the shoulder", "running with a javelin before releasing it", "jumping over a bar set at increasing heights"], "spinning within a circle before releasing a flat, disc-shaped implement for maximum distance",
      "The discus throw involves athletes performing a rotational spinning technique within a throwing circle before releasing the flat, disc-shaped implement for maximum distance."),
  _q("The javelin throw, a field event in athletics, involves athletes",
      ["running along an approach runway before throwing a spear-like implement for maximum distance", "spinning within a circle before releasing a discus", "pushing a heavy ball from the shoulder", "jumping into a sand pit for maximum distance"], "running along an approach runway before throwing a spear-like implement for maximum distance",
      "The javelin throw requires athletes to build speed along a running approach before releasing the spear-like javelin implement, aiming for maximum throwing distance."),
];

final _ballGames = [
  _q("In football (soccer), a standard match is officiated primarily by",
      ["a referee, assisted by assistant referees (linesmen)", "a single umpire with no assistants", "a panel of judges scoring style points", "a scorekeeper with no on-field authority"], "a referee, assisted by assistant referees (linesmen)",
      "Football matches are officiated by a central referee, who has ultimate authority over the game, assisted by assistant referees (linesmen) who help monitor the sidelines, offside calls, and other aspects of play."),
  _q("In football, an offside offence generally occurs when an attacking player is",
      ["nearer to the opponent's goal line than both the ball and the second-last defender when the ball is played to them", "positioned anywhere on their own half of the pitch", "in possession of the ball inside their own penalty area", "taking a corner kick"], "nearer to the opponent's goal line than both the ball and the second-last defender when the ball is played to them",
      "The offside rule in football penalises an attacking player who is nearer to the opponent's goal line than both the ball and the second-last defender at the moment the ball is played to them, subject to specific exceptions."),
  _q("In basketball, a standard game is typically divided into",
      ["four quarters", "two halves only, with no quarters", "three periods", "innings, similar to baseball"], "four quarters",
      "Standard basketball games (such as under FIBA or NBA rules) are typically divided into four quarters, though specific quarter lengths can vary between different competition levels and organisations."),
  _q("In basketball, a 'travelling' violation occurs when a player",
      ["takes an illegal number of steps while holding the ball without dribbling", "successfully makes a three-point shot", "commits a foul against an opposing player", "passes the ball to a teammate legally"], "takes an illegal number of steps while holding the ball without dribbling",
      "Travelling is a basketball violation that occurs when a player holding the ball takes an excessive number of steps without dribbling it, resulting in a turnover to the opposing team."),
  _q("In volleyball, a team is generally allowed a maximum of how many touches to return the ball across the net (not counting a block)?",
      ["Three touches", "One touch only", "Five touches", "Unlimited touches"], "Three touches",
      "In standard volleyball rules, a team is permitted a maximum of three touches (not including a block contact) to return the ball successfully over the net to the opposing side."),
  _q("In volleyball, which skill is primarily used to initiate play at the start of each rally?",
      ["The serve", "The block", "The dig", "The set"], "The serve",
      "The serve is the skill used to put the ball into play at the beginning of each rally in volleyball, typically performed from behind the back boundary line."),
  _q("In handball, players are generally permitted to hold the ball for a maximum of how many seconds before passing, dribbling, or shooting?",
      ["Three seconds", "Thirty seconds", "One minute", "There is no time limit at all"], "Three seconds",
      "Handball rules typically limit players to holding the ball for a maximum of three seconds without dribbling, passing, or shooting, encouraging fast-paced play."),
  _q("In hockey (field hockey), players use which part of the stick to legally play the ball?",
      ["Only the flat side of the stick", "Either side of the stick, flat or rounded", "Only the rounded (back) side of the stick", "Any part of the body other than the stick"], "Only the flat side of the stick",
      "Field hockey rules require players to play the ball using only the flat side of the stick; using the rounded back side to strike the ball is an infringement."),
  _q("In cricket, a standard team consists of how many players on the field at one time?",
      ["Eleven players", "Nine players", "Fifteen players", "Six players"], "Eleven players",
      "A standard cricket team fields eleven players at any given time, following the traditional format of the game."),
  _q("In cricket, a batsman is given 'out' via a 'bowled' dismissal when",
      ["the bowler's delivery hits and dislodges the bails from the batsman's wicket", "the batsman scores a boundary (four or six runs)", "the batsman successfully completes a run", "the fielding team appeals unsuccessfully"], "the bowler's delivery hits and dislodges the bails from the batsman's wicket",
      "A 'bowled' dismissal in cricket occurs when the bowler's delivery directly strikes the batsman's wicket and dislodges the bails, resulting in the batsman being given out."),
  _q("In tennis, a standard singles match is generally won by a player who wins",
      ["the majority of sets, typically best-of-three or best-of-five sets depending on the competition", "a single point only", "exactly one game with no further requirement", "the coin toss before the match begins"], "the majority of sets, typically best-of-three or best-of-five sets depending on the competition",
      "Tennis matches are generally decided by winning the majority of sets played, commonly in a best-of-three format for most competitions, or best-of-five in some major men's tournaments."),
  _q("In badminton, players use a racket to strike which type of projectile?",
      ["A shuttlecock", "A tennis ball", "A table tennis ball", "A hockey ball"], "A shuttlecock",
      "Badminton is played using a lightweight shuttlecock, struck with a racket, distinguishing it from tennis (ball) and other racket sports."),
  _q("In table tennis, players must allow the ball to bounce how many times on their side of the table before returning it, under normal rally conditions?",
      ["Exactly once", "Twice", "Not at all, it must be volleyed directly", "Three times"], "Exactly once",
      "Under standard table tennis rules, the ball must bounce exactly once on a player's side of the table before they legally return it to the opponent's side."),
  _q("In basketball, a successful shot made from beyond the designated arc is awarded how many points?",
      ["Three points", "One point", "Five points", "Two points, the same as any other shot"], "Three points",
      "A successful field goal made from beyond the three-point arc in basketball is awarded three points, compared to two points for shots made inside the arc."),
];

final _gymnasticsAndDance = [
  _q("Floor activities, a component of gymnastics, are typically performed",
      ["on a padded mat, involving a sequence of tumbling and balance movements without additional apparatus", "exclusively on a raised balance beam", "exclusively using a vaulting box", "exclusively on parallel bars"], "on a padded mat, involving a sequence of tumbling and balance movements without additional apparatus",
      "Floor exercises in gymnastics are performed on a padded mat, combining tumbling, balance, and flexibility movements without the use of additional apparatus."),
  _q("The vaulting box, a piece of gymnastics apparatus, is primarily used for",
      ["performing vaulting movements, where an athlete runs, springs off a board, and executes movements over the box", "balance beam routines exclusively", "floor tumbling exclusively", "rhythmic ribbon exercises exclusively"], "performing vaulting movements, where an athlete runs, springs off a board, and executes movements over the box",
      "The vaulting box (or vaulting horse/table) is used for vaulting exercises, in which an athlete sprints toward the apparatus, springs off a springboard, and performs specific movements while passing over it."),
  _q("Parallel bars, a piece of apparatus used in artistic gymnastics, primarily require athletes to",
      ["perform swinging, balancing, and strength movements while supporting themselves between two raised, parallel bars", "run and jump over a raised bar", "perform floor tumbling exclusively", "throw an implement for distance"], "perform swinging, balancing, and strength movements while supporting themselves between two raised, parallel bars",
      "Parallel bars require gymnasts to perform a sequence of swinging, balancing, and strength-based movements while supporting their body weight between two raised, parallel horizontal bars."),
  _q("Rhythmic gymnastics is particularly distinguished from artistic gymnastics by its incorporation of",
      ["handheld apparatus such as ribbons, hoops, and balls, combined with dance-like movements", "exclusive use of the vaulting box", "exclusive use of parallel bars", "the complete absence of any music accompaniment"], "handheld apparatus such as ribbons, hoops, and balls, combined with dance-like movements",
      "Rhythmic gymnastics distinctively incorporates handheld apparatus, such as ribbons, hoops, balls, and clubs, combined with expressive, dance-like movements, typically performed to music."),
  _q("Traditional folk dances, an important component of dance within Physical Education, are generally characterised by",
      ["movements and steps rooted in the cultural traditions and history of a particular community", "purely modern, internationally standardised dance steps with no cultural connection", "movements exclusively performed using gymnastics apparatus", "steps identical across all cultures worldwide with no local variation"], "movements and steps rooted in the cultural traditions and history of a particular community",
      "Traditional folk dances reflect and preserve the specific cultural heritage, customs, and history of the particular community or region from which they originate."),
  _q("Which of the following best describes a key physical benefit of participating in gymnastics and dance activities?",
      ["Improved flexibility, balance, coordination, and overall body control", "Decreased overall physical fitness", "No measurable physical benefit whatsoever", "Exclusive development of upper body strength with no other benefit"], "Improved flexibility, balance, coordination, and overall body control",
      "Regular participation in gymnastics and dance activities helps develop important physical attributes, including flexibility, balance, coordination, and overall body control."),
];

final _skeletalAndMuscularSystems = [
  _q("Long bones, a type of bone found in the human skeletal system, are typically found in locations such as the",
      ["arms and legs (e.g., the femur and humerus)", "skull", "wrist and ankle exclusively", "vertebrae exclusively"], "arms and legs (e.g., the femur and humerus)",
      "Long bones, characterised by their length exceeding their width, are typically found in the limbs, such as the femur (thigh bone) and humerus (upper arm bone)."),
  _q("Short bones, a type of bone found in the human skeletal system, are typically found in locations such as the",
      ["wrist (carpals) and ankle (tarsals)", "arms and legs", "skull", "ribs"], "wrist (carpals) and ankle (tarsals)",
      "Short bones are roughly cube-shaped and are typically found in areas requiring stability and limited movement, such as the carpal bones of the wrist and tarsal bones of the ankle."),
  _q("Flat bones, a type of bone found in the human skeletal system, are typically found in locations such as the",
      ["skull and ribs", "fingers and toes", "wrist and ankle", "upper arm and thigh"], "skull and ribs",
      "Flat bones, characterised by their thin, often curved shape, are typically found in areas requiring protection of internal organs, such as the skull (protecting the brain) and the ribs (protecting the chest cavity)."),
  _q("A ball-and-socket joint, a type of joint in the human body, permits movement",
      ["in almost all directions, as seen at the shoulder and hip", "in only one plane, like a door hinge", "with almost no movement at all", "only in a rotating motion around a single axis"], "in almost all directions, as seen at the shoulder and hip",
      "A ball-and-socket joint, where a rounded bone head fits into a cup-like socket, allows the widest range of movement of any joint type, as seen at the shoulder and hip."),
  _q("A hinge joint, a type of joint in the human body, permits movement",
      ["in one plane only, similar to a door hinge, as seen at the elbow and knee", "in all directions, as seen at the shoulder", "with no movement at all", "only a gliding motion between flat bone surfaces"], "in one plane only, similar to a door hinge, as seen at the elbow and knee",
      "A hinge joint allows movement (flexion and extension) in a single plane, similar to the mechanical action of a door hinge, as seen at the elbow and knee joints."),
  _q("Flexion, a type of joint movement, refers to",
      ["decreasing the angle between two body parts at a joint, such as bending the elbow", "increasing the angle between two body parts at a joint", "moving a limb away from the midline of the body", "rotating a limb around its own axis"], "decreasing the angle between two body parts at a joint, such as bending the elbow",
      "Flexion describes a joint movement that decreases the angle between connected body segments, such as bending the arm at the elbow."),
  _q("Extension, a type of joint movement, refers to",
      ["increasing the angle between two body parts at a joint, such as straightening the elbow", "decreasing the angle between two body parts at a joint", "moving a limb toward the midline of the body", "rotating a limb around its own axis"], "increasing the angle between two body parts at a joint, such as straightening the elbow",
      "Extension describes a joint movement that increases the angle between connected body segments, such as straightening a previously bent arm at the elbow, the opposite of flexion."),
  _q("Abduction, a type of joint movement, refers to",
      ["moving a limb or body part away from the midline of the body", "moving a limb or body part toward the midline of the body", "decreasing the angle at a joint", "rotating a limb around its own axis"], "moving a limb or body part away from the midline of the body",
      "Abduction describes a movement that takes a limb or body part away from the central midline of the body, such as raising an arm out to the side."),
  _q("Skeletal (voluntary) muscles, a type of muscle in the human body, are characterised by being",
      ["under conscious, voluntary control, and typically attached to bones to produce movement", "under entirely involuntary control, such as the heart muscle", "found exclusively within the walls of internal organs", "incapable of contracting or producing any movement"], "under conscious, voluntary control, and typically attached to bones to produce movement",
      "Skeletal muscles are voluntary muscles, meaning they can be consciously controlled, and are typically attached to bones via tendons, enabling deliberate body movement."),
  _q("Regular exercise generally affects skeletal muscle fibres by",
      ["increasing their size (hypertrophy) and improving their strength and endurance capacity", "causing them to permanently shrink and weaken", "having no measurable effect on muscle tissue whatsoever", "converting all muscle fibres into bone tissue"], "increasing their size (hypertrophy) and improving their strength and endurance capacity",
      "Consistent exercise, particularly resistance training, generally leads to muscle fibre hypertrophy (increased size) and improved overall strength and endurance capacity."),
  _q("Which of the following is an example of a joint movement classified as rotation?",
      ["Turning the head from side to side", "Bending the knee", "Straightening the elbow", "Raising the arm out to the side"], "Turning the head from side to side",
      "Rotation describes a joint movement in which a body part turns around its own longitudinal axis, such as turning the head from side to side at the neck."),
];

final _circulatoryAndRespiratorySystems = [
  _q("The human heart is best described as a",
      ["muscular pump responsible for circulating blood throughout the body", "purely passive storage organ for blood with no pumping function", "component of the digestive system", "structure responsible for filtering air in the lungs"], "muscular pump responsible for circulating blood throughout the body",
      "The heart is a powerful, muscular organ that rhythmically contracts to pump blood throughout the circulatory system, delivering oxygen and nutrients to body tissues."),
  _q("The human heart consists of how many main chambers?",
      ["Four (two atria and two ventricles)", "Two chambers only", "Three chambers only", "Six chambers"], "Four (two atria and two ventricles)",
      "The human heart has four chambers: two upper chambers (the left and right atria) and two lower chambers (the left and right ventricles)."),
  _q("Oxygenated blood, pumped from the left ventricle of the heart, is transported throughout the body primarily via the",
      ["aorta and systemic arteries", "pulmonary artery exclusively", "vena cava exclusively", "pulmonary veins exclusively"], "aorta and systemic arteries",
      "Oxygen-rich blood leaves the heart's left ventricle via the aorta, the body's largest artery, which branches into systemic arteries supplying oxygenated blood throughout the body."),
  _q("Deoxygenated blood returning from the body to the heart enters primarily through the",
      ["vena cava, into the right atrium", "aorta, into the left ventricle", "pulmonary veins, into the left atrium", "coronary arteries exclusively"], "vena cava, into the right atrium",
      "Deoxygenated blood returning from body tissues enters the heart's right atrium via the vena cava (the superior and inferior vena cava), before being pumped onward to the lungs for reoxygenation."),
  _q("Breathing (respiration mechanics) involves the coordinated action primarily of the",
      ["diaphragm and intercostal muscles", "heart muscle exclusively", "skeletal muscles of the arms exclusively", "digestive system muscles"], "diaphragm and intercostal muscles",
      "Breathing mechanics rely on the coordinated contraction and relaxation of the diaphragm (a large muscle beneath the lungs) and the intercostal muscles between the ribs, changing the volume of the chest cavity."),
  _q("During inhalation, the diaphragm generally",
      ["contracts and flattens, increasing the volume of the chest cavity to draw air into the lungs", "relaxes and domes upward, decreasing chest cavity volume", "stops moving entirely", "has no role in the breathing process"], "contracts and flattens, increasing the volume of the chest cavity to draw air into the lungs",
      "During inhalation, the diaphragm contracts and moves downward, flattening its dome shape and increasing the volume of the chest cavity, which draws air into the lungs."),
  _q("Oxygen debt, a physiological concept in exercise science, refers to",
      ["the additional oxygen the body requires after strenuous exercise to restore normal metabolic conditions", "a permanent, irreversible reduction in lung capacity", "the total amount of oxygen inhaled during a single breath", "the complete absence of any oxygen in the bloodstream"], "the additional oxygen the body requires after strenuous exercise to restore normal metabolic conditions",
      "Oxygen debt refers to the extra oxygen consumption needed after intense exercise to help the body recover, replenish energy stores, and clear metabolic by-products such as lactic acid."),
  _q("Aerobic exercise is characterised by activities that are",
      ["performed at a moderate intensity over a sustained period, primarily using oxygen to produce energy", "extremely short and intense, relying on energy production without oxygen", "performed without any cardiovascular involvement whatsoever", "purely stationary with no movement involved"], "performed at a moderate intensity over a sustained period, primarily using oxygen to produce energy",
      "Aerobic exercise involves sustained, moderate-intensity activity (such as jogging or swimming) in which the body primarily uses oxygen to generate the energy needed for continued effort."),
  _q("Anaerobic exercise is characterised by activities that are",
      ["short, intense bursts of effort, where energy is produced without sufficient oxygen supply", "long, sustained, moderate-intensity efforts using oxygen throughout", "purely passive with no muscular exertion", "always performed for durations exceeding one hour"], "short, intense bursts of effort, where energy is produced without sufficient oxygen supply",
      "Anaerobic exercise involves brief, high-intensity bursts of effort (such as sprinting or heavy weightlifting), during which the body's energy demands exceed the available oxygen supply, relying on alternative energy pathways."),
  _q("Which of the following best illustrates the difference between aerobic and anaerobic exercise?",
      ["Long-distance running is primarily aerobic, while a 100m sprint is primarily anaerobic", "Both long-distance running and 100m sprints are identical in their energy production", "Long-distance running is anaerobic, while sprinting is aerobic", "Neither activity involves any form of energy production"], "Long-distance running is primarily aerobic, while a 100m sprint is primarily anaerobic",
      "Long-distance running relies primarily on sustained aerobic (oxygen-based) energy production, while a short, maximal-effort 100m sprint relies primarily on rapid anaerobic energy pathways."),
  _q("Regular cardiovascular (aerobic) exercise generally has which effect on the heart over time?",
      ["It can strengthen the heart muscle, improving its efficiency in pumping blood", "It permanently weakens the heart muscle", "It has no effect whatsoever on cardiovascular function", "It stops the heart from beating regularly"], "It can strengthen the heart muscle, improving its efficiency in pumping blood",
      "Consistent aerobic exercise training generally strengthens the heart muscle over time, improving its pumping efficiency and overall cardiovascular fitness."),
];

final _firstAidAndSportsInjuries = [
  _q("A sprain, a common sports injury, refers to",
      ["an injury to a ligament, typically caused by overstretching or tearing", "a break in a bone", "an injury to a muscle or tendon", "a break in the skin causing bleeding"], "an injury to a ligament, typically caused by overstretching or tearing",
      "A sprain specifically involves damage to a ligament (the connective tissue linking bones at a joint), typically from overstretching or partial/complete tearing due to sudden twisting or impact."),
  _q("A strain, a common sports injury, refers to",
      ["an injury to a muscle or tendon, typically caused by overstretching or overexertion", "an injury to a ligament specifically", "a break in a bone", "a dislocation of a joint"], "an injury to a muscle or tendon, typically caused by overstretching or overexertion",
      "A strain involves damage to a muscle or tendon, often resulting from overstretching, overexertion, or sudden excessive force during physical activity."),
  _q("A dislocation, a sports injury affecting a joint, occurs when",
      ["the bones forming a joint are forced out of their normal alignment", "a muscle is torn or overstretched", "a ligament is overstretched without bone displacement", "the skin is cut, causing bleeding"], "the bones forming a joint are forced out of their normal alignment",
      "A dislocation occurs when the bones that form a joint are displaced from their normal anatomical position, often requiring prompt medical attention to safely realign them."),
  _q("A fracture, a serious injury affecting bone, refers to",
      ["a break or crack in a bone", "an injury limited to a ligament only", "an injury limited to a muscle only", "a minor bruise with no bone involvement"], "a break or crack in a bone",
      "A fracture specifically refers to a break, crack, or other structural disruption of a bone, ranging in severity from a hairline crack to a complete break."),
  _q("A muscle cramp, a common exercise-related condition, is best described as",
      ["a sudden, involuntary, and often painful muscle contraction", "a permanent loss of muscle function", "a break in the bone underlying the muscle", "a type of skin injury causing bleeding"], "a sudden, involuntary, and often painful muscle contraction",
      "A muscle cramp is a sudden, involuntary, and often painful contraction of a muscle, which can occur during or after physical exertion, sometimes related to fatigue, dehydration, or electrolyte imbalance."),
  _q("When managing external bleeding as a first aid measure, the initial recommended action is generally to",
      ["apply direct, firm pressure to the wound using a clean cloth or dressing", "immediately remove any embedded object from the wound", "vigorously massage the surrounding area", "submerge the wound in cold water for an extended period"], "apply direct, firm pressure to the wound using a clean cloth or dressing",
      "Applying direct, firm pressure to a bleeding wound with a clean cloth or dressing is a fundamental first aid technique to help control and reduce blood loss."),
  _q("Cardiopulmonary Resuscitation (CPR) is an emergency procedure primarily used when a person",
      ["is not breathing and has no detectable pulse, to help maintain blood circulation and oxygen delivery", "has a minor cut requiring a simple bandage", "has a mild muscle cramp", "has a common cold"], "is not breathing and has no detectable pulse, to help maintain blood circulation and oxygen delivery",
      "CPR is a critical emergency procedure performed when someone's breathing and heartbeat have stopped, using chest compressions (and often rescue breaths) to manually maintain blood circulation and oxygen delivery until further medical help arrives."),
  _q("The R.I.C.E. method (Rest, Ice, Compression, Elevation) is a common first aid approach primarily used for managing",
      ["soft tissue injuries such as sprains and strains", "severe open fractures requiring surgery", "cardiac arrest requiring CPR", "common respiratory infections"], "soft tissue injuries such as sprains and strains",
      "The R.I.C.E. method is a widely recommended initial first aid approach for managing soft tissue injuries like sprains and strains, helping to reduce pain, swelling, and further tissue damage."),
];

final _personalHealthAndNutrition = [
  _q("A balanced diet is best described as one that",
      ["provides all the essential nutrients in appropriate proportions needed for good health", "consists of only a single type of food eaten exclusively", "contains excessive amounts of sugar and fat with no other nutrients", "eliminates all forms of carbohydrates entirely"], "provides all the essential nutrients in appropriate proportions needed for good health",
      "A balanced diet supplies all essential nutrient classes (carbohydrates, proteins, fats, vitamins, minerals, water) in the correct proportions needed to maintain good health."),
  _q("Carbohydrates, a major class of food nutrients, primarily function to",
      ["provide the body's main and most readily available source of energy", "build and repair body tissues, as the primary function", "regulate body processes as the primary function, like a hormone", "provide essential fatty acids exclusively"], "provide the body's main and most readily available source of energy",
      "Carbohydrates serve as the body's primary and most readily accessible source of energy, fuelling everyday physical and mental activity."),
  _q("Proteins, a major class of food nutrients, primarily function to",
      ["build, repair, and maintain body tissues", "serve as the body's primary and most readily available energy source", "provide bulk (fibre) to aid digestion, as their primary function", "supply essential vitamins exclusively"], "build, repair, and maintain body tissues",
      "Proteins are essential for building, repairing, and maintaining body tissues, including muscles, and also play roles in enzyme and hormone production."),
  _q("Fats (lipids), a major class of food nutrients, primarily function to",
      ["provide a concentrated source of energy and support the absorption of fat-soluble vitamins", "provide the body's primary source of dietary fibre", "build muscle tissue as their primary function", "regulate blood sugar levels as their primary function"], "provide a concentrated source of energy and support the absorption of fat-soluble vitamins",
      "Fats provide a highly concentrated source of energy and are necessary for the absorption of fat-soluble vitamins (A, D, E, and K), among other important physiological functions."),
  _q("Vitamins, a class of essential nutrients required in small amounts, primarily function to",
      ["regulate various body processes and support overall metabolic function", "serve as the body's primary source of energy", "build significant amounts of muscle tissue", "provide the majority of the body's caloric intake"], "regulate various body processes and support overall metabolic function",
      "Vitamins are required in relatively small quantities but play essential roles in regulating numerous body processes and supporting overall metabolic health."),
  _q("Minerals, a class of essential nutrients, are important for functions such as",
      ["bone development (calcium) and oxygen transport in the blood (iron)", "serving as the body's primary source of energy", "providing the majority of the body's dietary fibre", "regulating body temperature exclusively"], "bone development (calcium) and oxygen transport in the blood (iron)",
      "Minerals serve various essential physiological roles, such as calcium supporting bone development and strength, and iron being essential for oxygen transport within red blood cells."),
  _q("Water, though not a traditional 'food' nutrient, is essential for the body mainly because it",
      ["regulates body temperature, transports nutrients, and supports numerous vital physiological processes", "provides significant caloric energy", "builds muscle tissue directly", "is only needed in very small, negligible amounts"], "regulates body temperature, transports nutrients, and supports numerous vital physiological processes",
      "Water is essential for regulating body temperature, transporting nutrients and waste products, and supporting virtually all vital physiological processes, despite providing no caloric energy itself."),
  _q("An eating disorder, a serious health condition related to nutrition, is best described as",
      ["a psychological condition characterised by abnormal or disturbed eating habits that negatively affect health", "simply a strong personal preference for a particular type of food", "a temporary, harmless change in appetite", "a condition that has no impact on physical health"], "a psychological condition characterised by abnormal or disturbed eating habits that negatively affect health",
      "Eating disorders are serious psychological conditions involving abnormal or disturbed eating patterns (such as anorexia nervosa or bulimia) that can significantly harm physical and mental health."),
  _q("Anorexia nervosa, an example of an eating disorder, is generally characterised by",
      ["severe restriction of food intake, often driven by an intense fear of gaining weight", "excessive, uncontrolled overeating with no associated distress", "a complete absence of any body image concerns", "a purely physical condition with no psychological component"], "severe restriction of food intake, often driven by an intense fear of gaining weight",
      "Anorexia nervosa is characterised by severely restricted food intake, often driven by an intense fear of weight gain and a distorted perception of body image."),
  _q("Which of the following best represents general dietary advice for maintaining good personal health?",
      ["Consuming a varied, balanced diet alongside adequate hydration and regular physical activity", "Eating only one type of food exclusively for extended periods", "Avoiding water intake as much as possible", "Completely eliminating all classes of nutrients from the diet"], "Consuming a varied, balanced diet alongside adequate hydration and regular physical activity",
      "Maintaining good personal health is generally best supported by a varied and balanced diet, adequate hydration, and regular physical activity, working together to support overall well-being."),
];

final _communicableAndNonCommunicableDiseases = [
  _q("Malaria, a communicable disease of significant concern in Nigeria, is primarily transmitted through",
      ["the bite of an infected female Anopheles mosquito", "direct person-to-person contact", "contaminated water sources exclusively", "airborne respiratory droplets"], "the bite of an infected female Anopheles mosquito",
      "Malaria is caused by Plasmodium parasites transmitted to humans through the bite of infected female Anopheles mosquitoes, making mosquito control a key prevention strategy."),
  _q("HIV/AIDS, a significant communicable disease, is primarily transmitted through",
      ["contact with infected bodily fluids, such as blood or through unprotected sexual contact", "casual social contact, such as shaking hands", "airborne respiratory droplets, similar to the common cold", "contaminated food alone"], "contact with infected bodily fluids, such as blood or through unprotected sexual contact",
      "HIV is primarily transmitted through contact with certain infected bodily fluids, notably through unprotected sexual contact, sharing contaminated needles, or from mother to child during childbirth or breastfeeding."),
  _q("Tuberculosis (TB), a significant communicable disease, primarily affects which part of the body?",
      ["The lungs, though it can also affect other organs", "Exclusively the skin", "Exclusively the digestive system", "Exclusively the bones"], "The lungs, though it can also affect other organs",
      "Tuberculosis is a bacterial infection that primarily affects the lungs, though it can also spread to and affect other organs in more severe cases."),
  _q("Tuberculosis is primarily transmitted between people through",
      ["airborne respiratory droplets, such as from coughing or sneezing", "contaminated water sources", "insect bites", "direct skin contact alone"], "airborne respiratory droplets, such as from coughing or sneezing",
      "Tuberculosis spreads primarily through airborne respiratory droplets released when an infected person coughs, sneezes, or speaks, making it a highly contagious airborne disease."),
  _q("Cholera, a significant communicable disease, is primarily transmitted through",
      ["consumption of water or food contaminated with the cholera bacterium", "airborne respiratory droplets", "insect bites", "direct skin-to-skin contact alone"], "consumption of water or food contaminated with the cholera bacterium",
      "Cholera is caused by ingesting water or food contaminated with the bacterium Vibrio cholerae, making safe water supply and sanitation crucial for prevention."),
  _q("COVID-19, a significant communicable disease, is primarily transmitted through",
      ["respiratory droplets and aerosols released when an infected person breathes, talks, coughs, or sneezes", "contaminated water sources exclusively", "insect bites exclusively", "genetic inheritance from parents"], "respiratory droplets and aerosols released when an infected person breathes, talks, coughs, or sneezes",
      "COVID-19, caused by the SARS-CoV-2 virus, spreads primarily through respiratory droplets and aerosols released when an infected person breathes, talks, coughs, or sneezes."),
  _q("Which of the following is a recommended general prevention measure against communicable respiratory diseases such as tuberculosis and COVID-19?",
      ["Practising good respiratory hygiene, such as covering coughs and sneezes", "Avoiding all forms of vaccination", "Deliberately sharing personal items with infected individuals", "Ignoring any recommended public health guidelines"], "Practising good respiratory hygiene, such as covering coughs and sneezes",
      "Good respiratory hygiene practices, such as covering coughs and sneezes and practising proper hand hygiene, are important general measures for reducing the spread of airborne communicable diseases."),
  _q("Hypertension (high blood pressure), a significant non-communicable disease, refers to a condition in which",
      ["the force of blood against artery walls is consistently too high", "blood sugar levels are consistently too low", "red blood cell shape becomes abnormally sickle-shaped", "abnormal cell growth forms a malignant tumour"], "the force of blood against artery walls is consistently too high",
      "Hypertension is a chronic condition characterised by persistently elevated blood pressure, which can increase the risk of serious complications such as heart disease and stroke if left unmanaged."),
  _q("Diabetes, a significant non-communicable disease, is primarily characterised by",
      ["the body's inability to properly regulate blood glucose (sugar) levels", "an abnormally low blood pressure", "an infection caused by a bacterium", "an infection caused by a virus"], "the body's inability to properly regulate blood glucose (sugar) levels",
      "Diabetes is a chronic metabolic condition in which the body cannot effectively regulate blood glucose levels, either due to insufficient insulin production or ineffective insulin use."),
  _q("Cancer, a significant non-communicable disease, is generally characterised by",
      ["the uncontrolled growth and spread of abnormal cells within the body", "a bacterial infection of the respiratory system", "a viral infection transmitted through mosquito bites", "a temporary and easily reversible imbalance in blood pressure"], "the uncontrolled growth and spread of abnormal cells within the body",
      "Cancer is fundamentally characterised by the uncontrolled growth and potential spread of abnormal cells, which can disrupt normal body function and, in some cases, spread to other parts of the body."),
  _q("Sickle Cell Anaemia, a significant genetically inherited non-communicable disease particularly prevalent in Nigeria, is characterised by",
      ["red blood cells taking on an abnormal, rigid, sickle (crescent) shape", "an infection caused by a mosquito-borne parasite", "a condition caused exclusively by poor diet", "a bacterial infection of the lungs"], "red blood cells taking on an abnormal, rigid, sickle (crescent) shape",
      "Sickle Cell Anaemia is a genetically inherited blood disorder in which red blood cells become abnormally rigid and sickle (crescent) shaped, impairing their ability to carry oxygen efficiently and causing various health complications."),
  _q("Which of the following best distinguishes a communicable disease from a non-communicable disease?",
      ["A communicable disease can be transmitted from person to person (or via a vector), while a non-communicable disease generally cannot", "A non-communicable disease can be transmitted from person to person, while a communicable disease cannot", "Both types of disease are always transmitted in exactly the same way", "There is no meaningful distinction between the two categories"], "A communicable disease can be transmitted from person to person (or via a vector), while a non-communicable disease generally cannot",
      "The fundamental distinction lies in transmissibility: communicable diseases can spread between individuals (directly, or via a vector like a mosquito), whereas non-communicable diseases (like hypertension or diabetes) generally arise from other factors, such as genetics or lifestyle, and cannot be 'caught' from another person."),
];

final _drugAndSubstanceAbuse = [
  _q("Alcohol abuse, a significant substance abuse concern, can lead to health effects including",
      ["liver damage and impaired cognitive and motor function", "improved liver function over time", "enhanced athletic performance with no negative effects", "no significant health risks whatsoever"], "liver damage and impaired cognitive and motor function",
      "Chronic alcohol abuse is associated with serious health consequences, including liver damage (such as cirrhosis) and impaired cognitive and motor functioning."),
  _q("Tobacco use, a significant substance abuse concern, is particularly associated with an increased risk of",
      ["lung cancer and various respiratory and cardiovascular diseases", "improved lung capacity and cardiovascular health", "enhanced athletic performance with no health risks", "no significant long-term health consequences"], "lung cancer and various respiratory and cardiovascular diseases",
      "Tobacco use is a well-established major risk factor for lung cancer and a range of other serious respiratory and cardiovascular diseases."),
  _q("Narcotics, a category of drugs subject to abuse, are generally characterised by their",
      ["potential to cause dependency and significantly impair physical and mental functioning", "complete safety with no risk of dependency or harm", "exclusive use as performance-enhancing supplements", "role as an essential daily nutrient"], "potential to cause dependency and significantly impair physical and mental functioning",
      "Narcotic drugs, when abused, carry a significant risk of dependency (addiction) and can severely impair both physical health and mental/cognitive functioning."),
  _q("Performance-enhancing drugs (doping), when used by athletes, are generally prohibited in competitive sport mainly because they",
      ["provide an unfair advantage and can pose serious risks to the athlete's health", "are completely safe and universally permitted in all competitions", "have no effect whatsoever on athletic performance", "are required by international sports regulations"], "provide an unfair advantage and can pose serious risks to the athlete's health",
      "Performance-enhancing drugs are banned in competitive sport primarily because they create an unfair competitive advantage and often carry significant risks to the athlete's long-term health."),
  _q("The use of performance-enhancing drugs (doping) in sport can result in which of the following consequences for an athlete's career?",
      ["Disqualification, suspension, or a permanent ban from competition if detected", "Automatic guaranteed victory with no possible penalty", "No consequences whatsoever, even if detected", "An automatic upgrade in competition ranking"], "Disqualification, suspension, or a permanent ban from competition if detected",
      "Athletes found to have used banned performance-enhancing substances typically face serious sporting sanctions, including disqualification from results, suspension, or even a permanent ban from competition."),
  _q("Which of the following best describes a general strategy for preventing drug and substance abuse, particularly among young people?",
      ["Education about the risks and harmful effects of drug and substance abuse", "Encouraging early and unrestricted exposure to addictive substances", "Providing no information at all about the risks involved", "Actively promoting the use of performance-enhancing drugs in youth sports"], "Education about the risks and harmful effects of drug and substance abuse",
      "Providing clear, accurate education about the risks and harmful effects of drug and substance abuse is a widely recognised and important preventive strategy, particularly for young people."),
];

final _environmentalAndCommunityHealth = [
  _q("A safe and reliable water supply is important for community health mainly because it helps",
      ["prevent waterborne diseases such as cholera and typhoid", "increase the spread of airborne respiratory diseases", "have no meaningful impact on public health", "cause an increase in non-communicable diseases exclusively"], "prevent waterborne diseases such as cholera and typhoid",
      "Access to safe, clean water is essential for preventing waterborne diseases like cholera and typhoid, which spread through contaminated water sources."),
  _q("Proper waste disposal systems are important for community health mainly because they help",
      ["prevent the spread of disease-causing organisms and reduce environmental contamination", "increase the breeding of disease-carrying pests and organisms", "have no impact on public health whatsoever", "are only relevant to industrial factories, not residential communities"], "prevent the spread of disease-causing organisms and reduce environmental contamination",
      "Effective waste disposal systems help prevent the accumulation of waste that can breed disease-carrying pests and contaminate the environment, protecting overall community health."),
  _q("Pollution control measures are important for community health mainly because they help",
      ["reduce harmful exposure to contaminated air, water, and soil", "increase the concentration of harmful pollutants in the environment", "have no relevance to human health outcomes", "exclusively benefit wildlife with no impact on human communities"], "reduce harmful exposure to contaminated air, water, and soil",
      "Pollution control measures aim to limit the release of harmful substances into the air, water, and soil, directly reducing human exposure to environmental health hazards."),
  _q("The World Health Organization (WHO), an important international health agency, is primarily responsible for",
      ["coordinating international public health efforts and providing global health guidance", "manufacturing pharmaceutical products for individual countries", "regulating the food and drug industries of a single specific country", "providing direct primary healthcare exclusively within Nigeria"], "coordinating international public health efforts and providing global health guidance",
      "The WHO is a specialised United Nations agency responsible for coordinating international public health initiatives and providing global guidance and leadership on health matters."),
];
