import "../quiz_question.dart";

const _subject = "Government";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// JAMB Government — 100 questions covering the core UTME topics:
/// Elements of Government, Types/Systems of Government, Organs of
/// Government, Citizenship and Rights, the Political Process, Public
/// Administration, Pre-Colonial and Colonial Political Systems in
/// Nigeria, Post-Independence Constitutions, Military Rule, Nigeria's
/// Foreign Policy, and International Organizations.
List<QuizQuestion> buildJambGovernmentQuestions() {
  return [
    ..._elementsOfGovernment,
    ..._typesAndSystemsOfGovernment,
    ..._organsOfGovernment,
    ..._citizenshipAndRights,
    ..._politicalProcess,
    ..._publicAdministration,
    ..._preColonialPoliticalSystems,
    ..._colonialAdministration,
    ..._postIndependenceConstitutions,
    ..._militaryRule,
    ..._foreignPolicy,
    ..._internationalOrganizations,
  ];
}

final _elementsOfGovernment = [
  _q("The State, as a political concept, is best defined as",
      ["a political community occupying a definite territory, organised under a sovereign government", "a group of people who share the same language and culture", "any organisation formed to trade for profit", "a religious institution with global membership"], "a political community occupying a definite territory, organised under a sovereign government",
      "A State possesses four key elements: a defined population, territory, government, and sovereignty, distinguishing it from other social or cultural groupings."),
  _q("Sovereignty refers to the",
      ["supreme and final authority of a State to govern itself without external interference", "total population living within a country", "geographical boundary separating two countries", "official currency used within a country"], "supreme and final authority of a State to govern itself without external interference",
      "Sovereignty is the highest, unchallenged authority a State exercises over its territory and people, both internally (supreme over its citizens) and externally (independent of other states)."),
  _q("A Nation differs from a State mainly in that a Nation is based primarily on",
      ["a shared sense of identity, culture, language, or history among a people", "a fixed and legally recognised territorial boundary", "a formally established government structure", "international diplomatic recognition"], "a shared sense of identity, culture, language, or history among a people",
      "A Nation is a socio-cultural concept based on shared identity and common bonds among a people, which may or may not align with the political/legal boundaries of a State."),
  _q("Political power refers to the",
      ["ability to influence or control the behaviour of others, especially in governance", "amount of wealth possessed by an individual", "physical strength of a country's military alone", "number of political parties in a country"], "ability to influence or control the behaviour of others, especially in governance",
      "Power in the political sense is the capacity to make others act (or refrain from acting) in a particular way, often to achieve political or governmental objectives."),
  _q("Political authority differs from mere power mainly in that authority is",
      ["power that is recognised as rightful and legitimate by those over whom it is exercised", "power obtained purely through military force", "power exercised without any form of recognition or consent", "unrelated to any legal or constitutional basis"], "power that is recognised as rightful and legitimate by those over whom it is exercised",
      "Authority is power accepted as legitimate and rightful, typically because it is derived from law, tradition, or the consent of the governed, unlike raw, unrecognised coercive power."),
  _q("Legitimacy in government refers to the",
      ["widespread acceptance by citizens that a government's authority to rule is rightful", "physical size of a country's territory", "amount of foreign aid a country receives", "number of years a leader has been in power"], "widespread acceptance by citizens that a government's authority to rule is rightful",
      "Legitimacy exists when the majority of citizens accept and recognise a government's right to exercise authority, often based on lawful processes such as free and fair elections."),
  _q("Democracy, as a political ideology, is best described as a system of government",
      ["by the people, in which citizens exercise power directly or through elected representatives", "controlled entirely by a single hereditary ruler", "in which one political party permanently holds all power by force", "run exclusively by unelected military officers"], "by the people, in which citizens exercise power directly or through elected representatives",
      "Democracy is founded on the principle of popular sovereignty, where political power ultimately derives from the people, exercised through free elections and representative institutions."),
  _q("Capitalism, as an economic and political ideology, is characterised mainly by",
      ["private ownership of the means of production and a free market economy", "state ownership and control of all means of production", "the complete abolition of private property", "central planning of all economic activities by the government"], "private ownership of the means of production and a free market economy",
      "Capitalism emphasises private enterprise and market-driven economic decisions, with limited government intervention, contrasting with socialism's emphasis on collective or state ownership."),
  _q("Socialism, as a political ideology, advocates for",
      ["collective or state ownership of the means of production to promote social equality", "unrestricted private ownership of all economic resources", "the complete absence of any government", "the concentration of power in a single hereditary monarch"], "collective or state ownership of the means of production to promote social equality",
      "Socialism seeks to reduce inequality by having the means of production owned or heavily regulated collectively or by the state, rather than left entirely to private individuals."),
  _q("Fascism, as a political ideology, is generally characterised by",
      ["extreme nationalism, dictatorial power, and suppression of political opposition", "the complete decentralisation of all governmental authority", "an emphasis on individual liberty above all state interests", "a strong commitment to multi-party democratic elections"], "extreme nationalism, dictatorial power, and suppression of political opposition",
      "Fascism is typically marked by authoritarian, one-party rule, intense nationalism, and the forcible suppression of dissent and opposing political viewpoints."),
];

final _typesAndSystemsOfGovernment = [
  _q("A monarchy is a system of government in which supreme power is held by",
      ["a single ruler, often inherited through a royal family line", "an assembly of elected representatives", "a council of wealthy citizens only", "the military high command"], "a single ruler, often inherited through a royal family line",
      "Monarchies are typically headed by a king, queen, or emperor whose position is usually hereditary, passed down within a royal family."),
  _q("An oligarchy is a system of government in which power is concentrated in the hands of",
      ["a small group of privileged individuals or families", "the entire adult population through direct voting", "a single absolute ruler", "an independent judiciary alone"], "a small group of privileged individuals or families",
      "Oligarchy describes rule by a small, often wealthy or powerful elite group, rather than by a single individual (autocracy) or the broader population (democracy)."),
  _q("An autocracy is a system of government in which",
      ["absolute power is concentrated in a single individual, unchecked by other institutions", "power is shared equally among several elected bodies", "power rests solely with a religious council", "citizens directly vote on every single law"], "absolute power is concentrated in a single individual, unchecked by other institutions",
      "In an autocracy, one person holds unrestricted power over the state, without meaningful checks from a legislature, judiciary, or electorate."),
  _q("An aristocracy is a system of government in which power is held by",
      ["a hereditary privileged class considered to be of superior social rank", "the majority of ordinary citizens", "a single elected president", "an appointed group of foreign advisors"], "a hereditary privileged class considered to be of superior social rank",
      "Aristocracy is rule by a hereditary nobility or privileged upper class, historically believed (by supporters) to be best suited to govern due to birth or social standing."),
  _q("A unitary system of government is one in which",
      ["governmental power is centralised in a single national government", "power is constitutionally divided between a central government and regional/state governments", "each region operates as a fully independent sovereign state", "there is no central government of any kind"], "governmental power is centralised in a single national government",
      "In a unitary system, ultimate authority rests with the central government, which may delegate some functions to local units, but retains the power to alter or revoke such delegation at will."),
  _q("A federal system of government is characterised by",
      ["a constitutional division of powers between a central government and constituent states/regions", "the total absence of a central government", "complete concentration of all power in local governments only", "the merging of several independent countries into one without any internal divisions"], "a constitutional division of powers between a central government and constituent states/regions",
      "Federalism divides governmental powers constitutionally between a central (federal) authority and regional (state) governments, each with its own defined areas of jurisdiction, as in Nigeria and the USA."),
  _q("A confederal system of government is best described as one in which",
      ["independent states unite loosely for specific common purposes, while retaining most of their sovereignty", "all power is completely centralised in a single national government", "regional governments have no independent powers whatsoever", "the military permanently controls all governmental functions"], "independent states unite loosely for specific common purposes, while retaining most of their sovereignty",
      "In a confederation, sovereign states voluntarily cooperate on limited shared matters (like defence or trade), while each member state retains a very high degree of independent authority."),
  _q("A presidential system of government is characterised mainly by",
      ["a clear separation of powers, with an executive president elected independently of the legislature", "the fusion of executive and legislative powers in a single body", "a monarch serving as both head of state and head of government", "the complete absence of a legislative body"], "a clear separation of powers, with an executive president elected independently of the legislature",
      "In a presidential system, the president (head of the executive) is elected separately from the legislature and serves a fixed term, with powers constitutionally separated from the legislative and judicial branches."),
  _q("A parliamentary system of government is characterised mainly by",
      ["a fusion of executive and legislative powers, with the executive (Prime Minister and Cabinet) drawn from and accountable to the legislature", "a strict separation of powers between all three arms of government", "an executive president elected directly by the people, separate from parliament", "an absolute monarch holding all governmental power"], "a fusion of executive and legislative powers, with the executive (Prime Minister and Cabinet) drawn from and accountable to the legislature",
      "In a parliamentary system, the executive branch (led by a Prime Minister) emerges from and remains accountable to the legislature (parliament), unlike the separated presidential model."),
];

final _organsOfGovernment = [
  _q("The Legislature, as an organ of government, is primarily responsible for",
      ["making laws for the country", "interpreting and applying the laws", "implementing and enforcing the laws", "commanding the armed forces"], "making laws for the country",
      "The legislative arm (e.g., the National Assembly in Nigeria) is constitutionally charged with the primary responsibility of enacting laws for the governance of the state."),
  _q("The Executive, as an organ of government, is primarily responsible for",
      ["implementing and enforcing the laws made by the Legislature", "making all the laws of the country", "interpreting the constitutionality of laws", "solely representing the interests of the judiciary"], "implementing and enforcing the laws made by the Legislature",
      "The executive arm (headed by the President or Prime Minister) is responsible for the day-to-day administration and enforcement of laws and government policy."),
  _q("The Judiciary, as an organ of government, is primarily responsible for",
      ["interpreting the laws and administering justice", "making new laws for the country", "enforcing laws through the police and military", "collecting taxes on behalf of government"], "interpreting the laws and administering justice",
      "The judicial arm interprets and applies the law to resolve disputes and administer justice, while also often reviewing the constitutionality of laws and executive actions."),
  _q("The doctrine of Separation of Powers advocates that",
      ["the three arms of government (Legislature, Executive, Judiciary) should be constitutionally distinct and independent of one another", "all governmental power should be concentrated in a single arm of government", "only the Executive should have any real power", "the Judiciary should be controlled entirely by the Legislature"], "the three arms of government (Legislature, Executive, Judiciary) should be constitutionally distinct and independent of one another",
      "This doctrine, associated with Montesquieu, holds that dividing governmental power among three separate branches prevents the excessive concentration of power and protects individual liberty."),
  _q("The system of Checks and Balances is designed to ensure that",
      ["each arm of government can monitor and limit the powers of the other arms, preventing abuse of power", "one arm of government has absolute and unchecked authority over the others", "the Legislature has no oversight function over the Executive", "the three arms of government never interact with one another"], "each arm of government can monitor and limit the powers of the other arms, preventing abuse of power",
      "Checks and balances complement separation of powers by giving each branch specific tools (e.g., veto, impeachment, judicial review) to restrain the others, preventing any single branch from becoming too powerful."),
  _q("A bicameral legislature is one that consists of",
      ["two chambers or houses, such as a Senate and a House of Representatives", "a single chamber or house only", "three separate chambers of equal power", "no formal chamber structure at all"], "two chambers or houses, such as a Senate and a House of Representatives",
      "Bicameral legislatures, like Nigeria's National Assembly (Senate and House of Representatives), are divided into two separate legislative chambers, often to provide additional checks on lawmaking."),
  _q("A unicameral legislature is one that consists of",
      ["a single legislative chamber or house", "two separate legislative chambers", "three or more legislative chambers", "no legislative body at all"], "a single legislative chamber or house",
      "A unicameral system has just one legislative house, unlike bicameral systems, which divide legislative functions between two chambers."),
  _q("Judicial independence refers to the principle that",
      ["the judiciary should be free from undue influence or control by the executive or legislature", "judges should always agree with the decisions of the executive branch", "the judiciary should have no power to interpret the constitution", "courts should be directly controlled by the ruling political party"], "the judiciary should be free from undue influence or control by the executive or legislature",
      "Judicial independence ensures that courts can make impartial decisions based on law and fact, free from political pressure or interference from the other arms of government."),
  _q("The power of judicial review allows the courts to",
      ["examine and declare the actions or laws of the executive or legislature unconstitutional if they violate the constitution", "create entirely new laws independent of the legislature", "directly appoint members of the executive cabinet", "control the day-to-day administration of government ministries"], "examine and declare the actions or laws of the executive or legislature unconstitutional if they violate the constitution",
      "Judicial review empowers courts to assess whether laws or governmental actions comply with the constitution, striking down those found to be unconstitutional, reinforcing checks and balances."),
];

final _citizenshipAndRights = [
  _q("Citizenship refers to the legal status of an individual as a",
      ["recognised member of a particular State, with accompanying rights and duties", "temporary visitor to a foreign country", "employee of a foreign government", "member of an international organisation only"], "recognised member of a particular State, with accompanying rights and duties",
      "Citizenship establishes a formal, legal bond between an individual and a State, granting the individual certain rights while also imposing corresponding civic duties."),
  _q("Citizenship can generally be acquired through which of the following means?",
      ["Birth, naturalisation, and registration", "Only by winning a national lottery", "Only through military conscription", "Only by paying a large sum of money to the government"], "Birth, naturalisation, and registration",
      "The most common recognised methods of acquiring citizenship are by birth (within a territory or to citizen parents), naturalisation (after meeting residency and legal requirements), and registration."),
  _q("Citizenship by birth typically applies to a person who is born",
      ["within the territory of a State, or to parents who are citizens of that State", "in any country, regardless of their parents' nationality", "only to individuals over the age of eighteen", "exclusively to children of foreign diplomats"], "within the territory of a State, or to parents who are citizens of that State",
      "Citizenship by birth is usually granted based on either being born within a country's territory (jus soli) or being born to citizen parents regardless of birthplace (jus sanguinis)."),
  _q("Which of the following is a duty typically expected of a citizen?",
      ["Obeying the laws of the country and paying taxes", "Receiving unconditional financial support from the government", "Holding public office without being elected", "Owning property in more than one country"], "Obeying the laws of the country and paying taxes",
      "In exchange for the rights citizenship confers, citizens are typically expected to fulfil civic duties such as obeying laws, paying taxes, and sometimes voting or serving on juries."),
  _q("Fundamental Human Rights refer to",
      ["basic rights and freedoms guaranteed to every individual, often enshrined in a country's constitution", "privileges granted only to elected government officials", "rights that can be freely revoked by any private business", "benefits available exclusively to citizens of wealthy nations"], "basic rights and freedoms guaranteed to every individual, often enshrined in a country's constitution",
      "Fundamental human rights (e.g., right to life, freedom of expression, freedom of association) are considered inherent and essential, typically protected explicitly under a nation's constitution."),
  _q("The right to freedom of expression allows citizens to",
      ["hold and express opinions and ideas without undue government interference", "say anything at all with absolutely no legal limitations whatsoever", "avoid ever being criticised by others", "control what other citizens are allowed to say"], "hold and express opinions and ideas without undue government interference",
      "Freedom of expression protects individuals' rights to voice opinions and ideas, though in practice it is often subject to reasonable legal limitations (e.g., against defamation or incitement to violence)."),
  _q("Fundamental human rights, though broadly guaranteed, are generally subject to certain limitations mainly to",
      ["protect public order, national security, and the rights of others", "allow the government unlimited power over its citizens", "eliminate the rights of specific ethnic groups", "prevent any citizen from ever voting"], "protect public order, national security, and the rights of others",
      "Most constitutions permit reasonable, legally justified restrictions on rights when necessary to protect public safety, national security, public order, or the rights and freedoms of others."),
];

final _politicalProcess = [
  _q("A political party is best defined as an organised group that",
      ["seeks to gain and exercise governmental power through winning elections", "exists solely to provide charitable services to the public", "represents only the interests of a single private business", "operates exclusively outside the electoral process"], "seeks to gain and exercise governmental power through winning elections",
      "Political parties are organisations formed with the primary goal of contesting elections to gain control of government and implement their policy agenda."),
  _q("A one-party system of government is characterised by",
      ["the existence of only a single legally recognised political party", "multiple political parties competing freely in elections", "the complete absence of any political party", "regular alternation of power between two dominant parties"], "the existence of only a single legally recognised political party",
      "In a one-party system, only one political party is permitted to exist or hold power legally, often restricting political competition and pluralism."),
  _q("A multi-party system of government is characterised by",
      ["the existence of three or more political parties competing for power", "only one political party being legally allowed to exist", "exactly two political parties dominating all elections", "the complete absence of elections"], "the existence of three or more political parties competing for power",
      "Multi-party systems allow several political parties to compete for power and represent diverse viewpoints, distinguishing them from one-party or strictly two-party systems."),
  _q("Universal adult suffrage refers to the",
      ["right of all adult citizens who meet basic legal requirements to vote in elections", "right to vote granted only to wealthy landowners", "right to vote granted only to men", "practice of appointing, rather than electing, government officials"], "right of all adult citizens who meet basic legal requirements to vote in elections",
      "Universal adult suffrage guarantees the right to vote to all adult citizens, regardless of gender, wealth, or social status, subject only to basic requirements like age and citizenship."),
  _q("The First-Past-The-Post electoral system determines a winner as the candidate who",
      ["receives the highest number of votes in a constituency, regardless of whether it is an absolute majority", "receives more than fifty percent of the total votes cast", "is selected directly by the incumbent government", "is chosen by a council of traditional rulers"], "receives the highest number of votes in a constituency, regardless of whether it is an absolute majority",
      "Under First-Past-The-Post, the candidate with the most votes (a simple plurality) in a constituency wins, even without securing an outright majority of all votes cast."),
  _q("Proportional representation is an electoral system in which",
      ["seats are allocated to parties in proportion to the total number of votes they receive", "only the candidate with the most votes nationwide wins a single seat", "seats are distributed equally regardless of votes received", "voting is restricted to members of the ruling party"], "seats are allocated to parties in proportion to the total number of votes they receive",
      "Proportional representation aims to more accurately reflect the overall voting pattern of the electorate by distributing legislative seats in line with each party's share of the total vote."),
  _q("An Electoral Commission is primarily responsible for",
      ["organising, conducting, and supervising elections in a country", "enacting the laws that govern the country", "commanding the country's armed forces", "administering the country's judicial system"], "organising, conducting, and supervising elections in a country",
      "Electoral commissions (such as INEC in Nigeria) are independent bodies tasked with managing the electoral process to ensure elections are conducted fairly and transparently."),
  _q("A pressure group differs from a political party mainly in that a pressure group",
      ["seeks to influence government policy without directly seeking to win elections or govern", "always seeks to contest and win elections", "is formally registered as a branch of government", "has no interest in influencing public policy at all"], "seeks to influence government policy without directly seeking to win elections or govern",
      "Pressure groups (e.g., trade unions, professional associations) aim to influence government decisions and policies on specific issues, without themselves seeking to hold governmental power through elections."),
  _q("Public opinion refers to the",
      ["collective views and attitudes of the general population on political and social issues", "official position of the ruling political party alone", "personal opinion of a single government minister", "views expressed exclusively by foreign governments"], "collective views and attitudes of the general population on political and social issues",
      "Public opinion represents the aggregate viewpoint of citizens on issues of public concern, which can significantly influence government policy and electoral outcomes."),
  _q("Which of the following best distinguishes a pressure group from public opinion as forces influencing government?",
      ["A pressure group is an organised body, while public opinion is a more general, often unorganised, sentiment among the people", "Public opinion is always more organised than any pressure group", "Pressure groups never attempt to influence government policy", "Public opinion can only be expressed through political parties"], "A pressure group is an organised body, while public opinion is a more general, often unorganised, sentiment among the people",
      "While both can shape government decisions, pressure groups are structured, organised bodies with specific goals, whereas public opinion is a broader, more diffuse expression of popular sentiment."),
];

final _publicAdministration = [
  _q("The Civil Service refers to the",
      ["body of permanent, non-political officials who implement government policies", "elected members of the legislature", "military and police personnel", "judges serving in the judiciary"], "body of permanent, non-political officials who implement government policies",
      "The Civil Service consists of professional, typically non-partisan administrators who provide continuity in government by implementing policy regardless of which political party is in power."),
  _q("A key characteristic of an ideal civil service is",
      ["political neutrality, allowing it to serve any government of the day impartially", "active membership in a specific political party", "complete independence from any form of government oversight", "the right to make laws independently of the legislature"], "political neutrality, allowing it to serve any government of the day impartially",
      "Civil servants are expected to remain politically neutral, faithfully implementing the policies of whichever government is in power, rather than favouring a particular political party."),
  _q("Which of the following is a common problem facing the civil service in many developing countries?",
      ["Bureaucratic bottlenecks, corruption, and inefficiency", "Excessive political neutrality that never causes any issues", "Too few civil servants relative to the population's needs everywhere", "Complete absence of any hierarchical structure"], "Bureaucratic bottlenecks, corruption, and inefficiency",
      "Civil services in many developing countries often struggle with slow, overly bureaucratic processes, corruption, and general inefficiency, undermining effective public service delivery."),
  _q("A public corporation is established mainly to",
      ["provide essential goods or services to the public, often in sectors considered too important for purely private control", "generate maximum profit for private shareholders", "serve as a branch of a specific political party", "replace the judiciary in resolving legal disputes"], "provide essential goods or services to the public, often in sectors considered too important for purely private control",
      "Public corporations are government-owned entities set up to deliver key public services (like electricity or transportation), often prioritising public welfare over pure profit maximisation."),
  _q("Local government, as the third tier of government in Nigeria, is primarily responsible for",
      ["administering affairs at the grassroots level closest to the people", "making laws for the entire federation", "commanding the national armed forces", "conducting the country's foreign relations"], "administering affairs at the grassroots level closest to the people",
      "Local government exists as the tier of administration closest to ordinary citizens, handling grassroots issues such as local infrastructure, markets, and primary healthcare."),
  _q("Which of the following is a common source of revenue for local governments in Nigeria?",
      ["Statutory allocation from the federation account", "Direct control over national customs duties", "Revenue from international trade agreements", "Direct taxation of foreign embassies"], "Statutory allocation from the federation account",
      "Local governments in Nigeria primarily rely on statutory allocations from the federation account, along with locally generated revenue such as rates and levies, to fund their operations."),
  _q("Which of the following is a common problem facing local government administration in Nigeria?",
      ["Inadequate funding and excessive control by state governments", "Complete financial and administrative independence from the states", "An overabundance of skilled administrative personnel", "Too much direct citizen participation in decision-making"], "Inadequate funding and excessive control by state governments",
      "Nigerian local governments often struggle with insufficient funding and significant interference or control from state governments, limiting their autonomy and effectiveness."),
];

final _preColonialPoliticalSystems = [
  _q("The pre-colonial Hausa-Fulani political system was primarily organised around",
      ["a centralised emirate system headed by an Emir, supported by appointed officials", "a decentralised system with no recognisable central authority", "a purely democratic system with universal adult suffrage", "rule by an assembly of age-grade groups only"], "a centralised emirate system headed by an Emir, supported by appointed officials",
      "The Hausa-Fulani political system was highly centralised, with an Emir at the apex, supported by a hierarchy of appointed officials (such as the Waziri and district heads) administering the emirate."),
  _q("In the pre-colonial Hausa-Fulani system, the Emir was assisted in administration by an official known as the",
      ["Waziri (Vizier)", "Oba", "Eze", "Obi"], "Waziri (Vizier)",
      "The Waziri served as a chief adviser and administrator to the Emir, playing a role somewhat similar to a modern-day prime minister within the emirate system."),
  _q("The pre-colonial Yoruba political system was traditionally headed by a",
      ["monarch known as the Oba, supported by chiefs and councils", "purely elected village council with no traditional ruler", "single military dictator with no legitimacy", "religious leader with no political authority"], "monarch known as the Oba, supported by chiefs and councils",
      "The traditional Yoruba political system was monarchical, headed by an Oba, but tempered by councils of chiefs (such as the Oyomesi in the Oyo Empire) who provided checks on his authority."),
  _q("In pre-colonial Yoruba political systems, the council of kingmakers and chiefs known as the Oyomesi served mainly to",
      ["check the power of the Alaafin and could, in extreme cases, demand his removal", "have no influence at all over the Alaafin's decisions", "act purely as a religious body with no political function", "replace the Alaafin as the sole ruler of the kingdom"], "check the power of the Alaafin and could, in extreme cases, demand his removal",
      "The Oyomesi acted as a check on the Alaafin of Oyo's power, and under extreme circumstances, could even present him with an empty calabash as a demand that he take his own life, effectively removing him from power."),
  _q("The pre-colonial Igbo political system is generally described as",
      ["a decentralised, republican system without a single centralised traditional ruler", "a highly centralised monarchy similar to the Hausa-Fulani emirate system", "a system ruled entirely by a single hereditary emperor", "identical in structure to the Yoruba Oba system"], "a decentralised, republican system without a single centralised traditional ruler",
      "Unlike the centralised Hausa-Fulani and Yoruba systems, the traditional Igbo political system was largely acephalous (without a single head), relying instead on councils of elders, age-grades, and title societies for governance."),
  _q("In the pre-colonial Igbo political system, decision-making was often carried out through",
      ["village assemblies, councils of elders, and age-grade associations", "a single all-powerful hereditary king", "an emir supported by appointed district heads", "a foreign-appointed colonial governor"], "village assemblies, councils of elders, and age-grade associations",
      "Igbo communities typically governed themselves through participatory structures such as village general assemblies, councils of elders, and age-grade groups, reflecting a more decentralised, consensus-driven approach to authority."),
  _q("Title societies, such as the Ozo title in Igbo land, functioned mainly to",
      ["confer social status and political influence upon those who attained the title", "serve as the sole military command structure", "replace the need for any council of elders", "represent a purely ceremonial role with no social significance"], "confer social status and political influence upon those who attained the title",
      "Title societies granted successful members enhanced social prestige and often a voice in community decision-making, forming an important part of the decentralised Igbo governance structure."),
  _q("A key difference between the pre-colonial Hausa-Fulani and Igbo political systems was that the Hausa-Fulani system was",
      ["centralised under an Emir, while the Igbo system was largely decentralised", "entirely without any traditional leadership structure, unlike the Igbo system", "based on universal adult suffrage, unlike the Igbo system", "controlled by colonial administrators from the outset"], "centralised under an Emir, while the Igbo system was largely decentralised",
      "This distinction is a classic feature of Nigerian pre-colonial political history: the Hausa-Fulani's strongly centralised emirate structure versus the Igbo's more decentralised, republican-style governance."),
];

final _colonialAdministration = [
  _q("The policy of Indirect Rule, adopted by the British in colonial Nigeria, involved",
      ["governing through existing traditional rulers and institutions, under overall British supervision", "the complete abolition of all traditional rulers and institutions", "direct rule by British officials with no involvement of traditional authorities", "immediate grant of full self-government to Nigerians"], "governing through existing traditional rulers and institutions, under overall British supervision",
      "Indirect Rule, associated with Lord Lugard, used existing traditional political structures (like Emirs) as intermediaries to administer colonial policy, reducing the number of British officials needed."),
  _q("Indirect Rule was most successfully implemented in colonial Nigeria in the",
      ["Northern Region, due to the existing centralised emirate system", "Eastern Region, due to its decentralised political structures", "entire country equally, with no regional variation in success", "Western Region only, due to a complete absence of traditional rulers"], "Northern Region, due to the existing centralised emirate system",
      "The North's centralised Hausa-Fulani emirate system, with clear hierarchical authority, was well suited to Indirect Rule, whereas the decentralised Igbo system in the East made it more difficult to implement effectively."),
  _q("A major challenge to implementing Indirect Rule in Eastern Nigeria was that the",
      ["decentralised Igbo political system lacked the centralised traditional rulers the policy relied upon", "Igbo people had no interest in trade with the British", "region had no population large enough to govern", "British had no colonial interest in the Eastern Region at all"], "decentralised Igbo political system lacked the centralised traditional rulers the policy relied upon",
      "Since Indirect Rule depended on existing centralised traditional authority, the British faced difficulties in the East, sometimes resorting to appointing 'Warrant Chiefs' who lacked genuine traditional legitimacy."),
  _q("The Clifford Constitution of 1922 is significant mainly for",
      ["introducing the elective principle, allowing a limited number of Nigerians to be elected into the Legislative Council", "granting Nigeria full independence from British rule", "abolishing all forms of legislative council in Nigeria", "establishing a fully federal system of government for Nigeria"], "introducing the elective principle, allowing a limited number of Nigerians to be elected into the Legislative Council",
      "The 1922 Clifford Constitution was notable for introducing limited elections, allowing a small number of Nigerians (in Lagos and Calabar) to be elected to the Legislative Council for the first time."),
  _q("The Richards Constitution of 1946 is significant mainly for",
      ["introducing regionalism by dividing Nigeria into three regions (North, East, West)", "granting Nigeria complete independence", "abolishing the position of Governor-General", "introducing universal adult suffrage across Nigeria"], "introducing regionalism by dividing Nigeria into three regions (North, East, West)",
      "The Richards Constitution laid the foundation for Nigerian federalism by dividing the country into three regions, each with its own regional legislative assembly."),
  _q("The Macpherson Constitution of 1951 is significant mainly for",
      ["introducing a greater degree of Nigerian participation in central government and expanding the elective principle", "granting Nigeria full independence from Britain", "establishing Nigeria's first military government", "abolishing the regional structure created by the Richards Constitution"], "introducing a greater degree of Nigerian participation in central government and expanding the elective principle",
      "The Macpherson Constitution expanded Nigerian involvement in governance at the centre and further developed representative institutions, though it also revealed growing regional tensions."),
  _q("The Lyttelton Constitution of 1954 is significant mainly for",
      ["formally establishing Nigeria as a federation with defined powers for the regions and the centre", "granting Nigeria immediate independence", "abolishing the office of Regional Premier", "establishing a unitary, rather than federal, system of government"], "formally establishing Nigeria as a federation with defined powers for the regions and the centre",
      "The 1954 Lyttelton Constitution firmly established Nigeria's federal structure, clearly defining the division of powers between the regional governments and the central government."),
  _q("Nationalist movements in colonial Nigeria emerged mainly in response to",
      ["dissatisfaction with colonial rule and a desire for self-governance and independence", "a request from the British government for Nigerians to seek independence", "a lack of any economic or political grievances under colonial rule", "the total absence of any educated Nigerian elite"], "dissatisfaction with colonial rule and a desire for self-governance and independence",
      "Nationalist movements, led by figures like Herbert Macaulay, Nnamdi Azikiwe, and Obafemi Awolowo, arose from growing Nigerian dissatisfaction with colonial domination and a push for self-rule."),
  _q("The National Council of Nigeria and the Cameroons (NCNC) was significant as an early Nigerian",
      ["nationalist political organisation advocating for self-government", "colonial administrative body established by the British", "purely religious organisation with no political goals", "military faction opposing civilian rule"], "nationalist political organisation advocating for self-government",
      "The NCNC, led notably by Herbert Macaulay and later Nnamdi Azikiwe, was one of Nigeria's earliest and most prominent nationalist political parties advocating for self-determination."),
  _q("Which of the following best describes the general impact of British colonial rule on Nigeria's political development?",
      ["It introduced Western political and administrative structures while altering pre-existing indigenous systems of governance", "It had no effect whatsoever on Nigeria's traditional political systems", "It immediately granted Nigeria a fully independent, self-sufficient government", "It completely eliminated regional and ethnic distinctions within Nigeria"], "It introduced Western political and administrative structures while altering pre-existing indigenous systems of governance",
      "Colonial rule fundamentally reshaped Nigeria's political landscape by introducing Western-style institutions and constitutional frameworks, while significantly altering (and in some cases undermining) existing indigenous governance systems."),
];

final _postIndependenceConstitutions = [
  _q("The 1960 Independence Constitution established Nigeria as a",
      ["federation with a parliamentary system of government under a constitutional monarch", "unitary state under an executive president", "one-party socialist state", "military-controlled federation"], "federation with a parliamentary system of government under a constitutional monarch",
      "At independence in 1960, Nigeria adopted a parliamentary system, retaining the British monarch as ceremonial Head of State, represented locally by a Governor-General."),
  _q("The 1963 Republican Constitution is significant mainly because it",
      ["made Nigeria a republic, replacing the British monarch with a Nigerian President as Head of State", "abolished the federal structure of Nigeria", "introduced military rule for the first time", "granted Nigeria independence from British rule"], "made Nigeria a republic, replacing the British monarch with a Nigerian President as Head of State",
      "The 1963 Constitution transformed Nigeria into a full republic, replacing the British monarch as Head of State with an indigenous Nigerian President, while retaining the parliamentary system."),
  _q("The 1979 Constitution introduced which significant change to Nigeria's system of government?",
      ["A presidential system of government, replacing the parliamentary system", "A return to colonial-style Indirect Rule", "The abolition of the federal structure", "A one-party socialist system of government"], "A presidential system of government, replacing the parliamentary system",
      "The 1979 Constitution marked Nigeria's shift from the parliamentary system inherited at independence to a presidential system modelled substantially on that of the United States."),
  _q("The 1999 Constitution, under which Nigeria currently operates, established a",
      ["presidential system of government with a federal structure", "parliamentary system of government under a ceremonial monarch", "purely unitary system of government", "one-party state with no multi-party competition"], "presidential system of government with a federal structure",
      "The 1999 Constitution (as amended) continues to govern Nigeria today, maintaining a federal, presidential system of government with three tiers: federal, state, and local government."),
  _q("Which of the following is a key feature common to Nigeria's post-independence constitutions (1963, 1979, 1999)?",
      ["A federal system of government dividing power between the centre and constituent units", "A single, unitary structure with no regional or state divisions", "The complete absence of a written constitution", "Rule exclusively by unelected traditional rulers"], "A federal system of government dividing power between the centre and constituent units",
      "Despite differences in the form of executive government (parliamentary vs. presidential), Nigeria's constitutions since independence have consistently maintained a federal structure."),
  _q("The transition from a parliamentary to a presidential system of government in Nigeria was formalised by the",
      ["1979 Constitution", "1960 Independence Constitution", "1963 Republican Constitution", "Richards Constitution of 1946"], "1979 Constitution",
      "While the 1960 and 1963 constitutions retained a parliamentary framework, it was the 1979 Constitution that introduced the presidential system Nigeria has retained (with interruptions) since."),
  _q("Under the 1999 Constitution, the President of Nigeria serves as both",
      ["Head of State and Head of Government", "only a ceremonial Head of State with no executive powers", "only Head of Government, with a separate ceremonial Head of State", "a purely symbolic figure with no constitutional role"], "Head of State and Head of Government",
      "Under Nigeria's presidential system, the President combines the roles of Head of State (ceremonial representative of the nation) and Head of Government (in charge of the executive branch), unlike the separated roles in a parliamentary system."),
  _q("Which post-independence Nigerian constitution first introduced the Federal Character Principle to ensure fair representation of Nigeria's diverse groups in government?",
      ["The 1979 Constitution", "The 1960 Independence Constitution", "The 1963 Republican Constitution", "The Lyttelton Constitution of 1954"], "The 1979 Constitution",
      "The Federal Character Principle, aimed at ensuring no particular ethnic or sectional group dominates public appointments, was formally introduced under the 1979 Constitution."),
];

final _militaryRule = [
  _q("A major cause of military intervention in Nigerian politics historically has been",
      ["widespread political instability, corruption, and electoral malpractice under civilian governments", "excessive stability and efficiency of civilian government", "a complete absence of any political parties", "unanimous public satisfaction with civilian rule"], "widespread political instability, corruption, and electoral malpractice under civilian governments",
      "Military coups in Nigeria's history were frequently justified by the military as necessary responses to perceived political instability, corruption, and failures of the preceding civilian administrations."),
  _q("Under military rule in Nigeria, governmental power was typically concentrated in a body known as the",
      ["Supreme Military Council (or similar ruling council)", "National Assembly", "Federal Executive Council elected by the people", "Council of State comprised only of civilians"], "Supreme Military Council (or similar ruling council)",
      "Military regimes in Nigeria generally centralised power in a small ruling council of top military officers (variously named, such as the Supreme Military Council or Provisional Ruling Council), which issued decrees with the force of law."),
  _q("During military rule, laws were typically enacted through",
      ["decrees issued by the ruling military council, rather than through a legislature", "debate and voting within an elected National Assembly", "referenda conducted among the general public", "decisions made solely by the judiciary"], "decrees issued by the ruling military council, rather than through a legislature",
      "Since military governments typically suspended or dissolved the legislature, laws were instead promulgated as decrees by the ruling military authority, bypassing normal legislative processes."),
  _q("One commonly cited achievement of military regimes in Nigeria has been",
      ["swift decision-making unburdened by lengthy legislative debate, particularly during national emergencies", "the strengthening of multi-party democratic institutions", "increased citizen participation in lawmaking", "the permanent elimination of political corruption"], "swift decision-making unburdened by lengthy legislative debate, particularly during national emergencies",
      "Supporters of military rule sometimes point to its capacity for rapid, centralised decision-making, useful during crises, though this often came at the cost of democratic checks and civil liberties."),
  _q("A commonly cited weakness of military rule in Nigeria has been",
      ["the suppression of fundamental human rights and lack of accountability to the electorate", "excessive checks and balances slowing down governance", "too much power vested in an elected legislature", "overly transparent and participatory decision-making processes"], "the suppression of fundamental human rights and lack of accountability to the electorate",
      "Military regimes were frequently criticised for curtailing civil liberties, operating without the accountability mechanisms of elections, and concentrating power without meaningful checks."),
  _q("The transition from military to civilian rule in Nigeria typically involved",
      ["drafting a new or amended constitution and conducting elections to usher in a democratically elected government", "the permanent retention of power by the military", "the immediate abolition of the federal system of government", "rule being handed directly to a foreign government"], "drafting a new or amended constitution and conducting elections to usher in a democratically elected government",
      "Transitions from military to civilian rule in Nigeria's history generally followed a process of constitutional reform and organised elections to restore a democratically elected government."),
];

final _foreignPolicy = [
  _q("Nigeria's foreign policy refers to the",
      ["strategies and principles guiding Nigeria's relations with other countries and international bodies", "internal policies governing Nigeria's domestic economy alone", "laws governing trade solely within Nigeria's borders", "policies exclusively concerning Nigeria's military structure at home"], "strategies and principles guiding Nigeria's relations with other countries and international bodies",
      "Foreign policy encompasses the principles and strategies a country adopts in conducting its relations, diplomacy, and interactions with other states and international organisations."),
  _q("Which of the following is a core principle guiding Nigeria's foreign policy since independence?",
      ["Africa as the centrepiece of Nigeria's foreign policy", "Complete isolation from all other African countries", "Exclusive alliance with a single foreign superpower", "Total avoidance of any international organisation membership"], "Africa as the centrepiece of Nigeria's foreign policy",
      "Nigeria has consistently emphasised the promotion of African unity, decolonisation, and development as the central focus (the 'centrepiece') of its foreign policy since gaining independence."),
  _q("Which of the following is a major determinant of a country's foreign policy?",
      ["The country's economic resources and strategic national interests", "The personal hobbies of individual government ministers", "The colour of the country's national flag", "The number of public holidays celebrated annually"], "The country's economic resources and strategic national interests",
      "Foreign policy decisions are typically shaped by tangible factors such as a nation's economic strength, security concerns, historical ties, and overall strategic national interests."),
  _q("Nigeria played a significant leadership role in supporting the independence and anti-apartheid struggles of which Southern African country?",
      ["South Africa", "Egypt", "Kenya", "Morocco"], "South Africa",
      "Nigeria was a vocal and active supporter of the anti-apartheid movement in South Africa, providing diplomatic, financial, and moral support to end apartheid rule."),
  _q("Nigeria's relations with world powers, such as the United States and the United Kingdom, are generally guided by considerations of",
      ["mutual economic benefit, diplomatic cooperation, and international security", "total isolation from any political or economic engagement", "unconditional agreement with all their foreign policy positions", "abandonment of any independent Nigerian foreign policy stance"], "mutual economic benefit, diplomatic cooperation, and international security",
      "Nigeria's relations with major world powers are typically shaped by pragmatic considerations of trade, investment, diplomatic partnership, and shared security interests, while still asserting independent policy positions."),
  _q("Nigeria's foreign policy towards other African states has generally emphasised",
      ["Pan-Africanism and support for regional cooperation and integration", "the annexation of neighbouring territories", "complete non-involvement in regional African affairs", "support only for countries that share Nigeria's exact system of government"], "Pan-Africanism and support for regional cooperation and integration",
      "Nigeria has generally championed Pan-African ideals, supporting regional cooperation, peacekeeping, and integration efforts across the African continent, consistent with its 'Africa as centrepiece' policy."),
];

final _internationalOrganizations = [
  _q("The United Nations Organization (UNO) was established mainly to",
      ["promote international peace, security, and cooperation among nations", "serve as a single world government replacing individual nations", "regulate the internal domestic policies of member states directly", "function exclusively as a global trading company"], "promote international peace, security, and cooperation among nations",
      "The UN was founded after World War II with the primary aim of maintaining international peace and security while fostering cooperation on economic, social, and humanitarian issues among member states."),
  _q("Which organ of the United Nations is primarily responsible for maintaining international peace and security?",
      ["The Security Council", "The General Assembly", "The International Court of Justice", "The Economic and Social Council"], "The Security Council",
      "The UN Security Council holds primary responsibility for addressing threats to international peace and security, including the authority to authorise peacekeeping missions and sanctions."),
  _q("The permanent members of the United Nations Security Council, each holding veto power, are",
      ["the United States, United Kingdom, France, Russia, and China", "Nigeria, South Africa, Egypt, Kenya, and Ghana", "Germany, Japan, India, Brazil, and Canada", "all 193 member states of the United Nations equally"], "the United States, United Kingdom, France, Russia, and China",
      "The UN Security Council has five permanent members with veto power (the US, UK, France, Russia, and China), alongside ten non-permanent members elected for two-year terms."),
  _q("The Commonwealth of Nations is an international organisation whose members are mainly",
      ["countries that were formerly part of the British Empire", "exclusively countries located in Europe", "countries that have never had any historical ties to Britain", "restricted only to countries in the Americas"], "countries that were formerly part of the British Empire",
      "The Commonwealth is a voluntary association of predominantly former British colonies and territories, including Nigeria, that cooperate on shared values like democracy and development."),
  _q("The African Union (AU) was established mainly to promote",
      ["unity, cooperation, and development among African states", "the political and economic isolation of African states from the rest of the world", "the re-establishment of colonial rule in Africa", "competition and conflict among African nations"], "unity, cooperation, and development among African states",
      "The AU (successor to the Organisation of African Unity) works to promote political and economic integration, peace, security, and development across the African continent."),
  _q("The Economic Community of West African States (ECOWAS) was established mainly to promote",
      ["economic integration and cooperation among West African countries", "military conflict among West African states", "the political isolation of Nigeria from its neighbours", "trade exclusively between West Africa and Europe"], "economic integration and cooperation among West African countries",
      "ECOWAS aims to foster economic cooperation, free movement of goods and people, and regional integration among its West African member states, including Nigeria."),
  _q("Nigeria has historically played a significant peacekeeping role within ECOWAS, notably through its leadership contributions to the ECOWAS Monitoring Group known as",
      ["ECOMOG", "AU Peace and Security Council", "UN Security Council", "NATO"], "ECOMOG",
      "ECOMOG (ECOWAS Monitoring Group) was a peacekeeping force established by ECOWAS, in which Nigeria played a leading and prominent role, notably during conflicts in Liberia and Sierra Leone."),
  _q("International organisations such as the UN, Commonwealth, AU, and ECOWAS generally benefit member countries mainly by",
      ["providing platforms for cooperation, conflict resolution, and collective action on shared challenges", "eliminating the sovereignty of all member states entirely", "forcing all member states to adopt an identical system of government", "guaranteeing unlimited financial wealth to every member state"], "providing platforms for cooperation, conflict resolution, and collective action on shared challenges",
      "These organisations create structured forums where member states can collaborate on common political, economic, security, and social challenges, while generally still respecting national sovereignty."),
  _q("Nigeria's membership in international organisations like the UN and AU reflects its foreign policy commitment to",
      ["multilateral cooperation and collective diplomacy on the world stage", "complete political isolation from other nations", "unilateral action without regard for international consensus", "withdrawal from all forms of international engagement"], "multilateral cooperation and collective diplomacy on the world stage",
      "Nigeria's active participation in these international bodies demonstrates its foreign policy preference for engaging diplomatically and cooperatively with the wider international community, rather than pursuing isolation."),
  _q("Which of the following best describes the role of the United Nations General Assembly?",
      ["A forum where all member states have equal representation to discuss and vote on a wide range of international issues", "A body with the exclusive power to authorise military action against any nation", "A court that settles legal disputes between individual citizens", "An organisation limited only to economic issues in Europe"], "A forum where all member states have equal representation to discuss and vote on a wide range of international issues",
      "The General Assembly is the main deliberative body of the UN, where every member state, regardless of size or power, has equal voting rights on a broad range of global issues."),
  _q("The International Court of Justice (ICJ), the principal judicial organ of the United Nations, is primarily responsible for",
      ["settling legal disputes between states and providing advisory opinions on international legal questions", "enforcing UN Security Council resolutions with military force", "managing the UN's annual budget and finances", "administering humanitarian aid directly to refugees"], "settling legal disputes between states and providing advisory opinions on international legal questions",
      "The ICJ, based in The Hague, adjudicates legal disputes submitted by states and offers advisory opinions on international legal matters referred to it by authorised UN bodies."),
];
