import "../quiz_question.dart";

const _subject = "Literature in English";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// JAMB Literature-in-English — 100 questions covering literary
/// appreciation/terminology, the prescribed Shakespearean drama (Antony
/// and Cleopatra), African and non-African drama, African and non-African
/// prose, and the prescribed African and non-African poems on the
/// harmonized 2026-2030 syllabus.
List<QuizQuestion> buildJambLiteratureQuestions() {
  return [
    ..._literaryAppreciation,
    ..._antonyAndCleopatra,
    ..._africanDrama,
    ..._nonAfricanDrama,
    ..._africanProse,
    ..._nonAfricanProse,
    ..._africanPoetry,
    ..._nonAfricanPoetry,
  ];
}

final _literaryAppreciation = [
  _q("A metaphor is a figure of speech that",
      ["describes one thing as being another, without using 'like' or 'as'", "compares two things using 'like' or 'as'", "gives human qualities to non-human things", "uses exaggeration for emphasis"], "describes one thing as being another, without using 'like' or 'as'",
      "A metaphor makes a direct, implicit comparison by stating one thing is another (e.g., 'the world is a stage'), unlike a simile, which uses 'like' or 'as'."),
  _q("A simile is a figure of speech that compares two unlike things using",
      ["'like' or 'as'", "personification", "hyperbole only", "onomatopoeia only"], "'like' or 'as'",
      "A simile makes an explicit comparison between two different things, signalled by the connecting words 'like' or 'as' (e.g., 'as brave as a lion')."),
  _q("Personification is a literary device in which",
      ["human qualities or actions are attributed to non-human things or abstract ideas", "two contrasting ideas are placed side by side", "a part is used to represent the whole", "an exaggerated statement is made for effect"], "human qualities or actions are attributed to non-human things or abstract ideas",
      "Personification gives human characteristics (thoughts, feelings, actions) to inanimate objects, animals, or abstract concepts, such as 'the wind whispered'."),
  _q("Hyperbole is a literary device that involves",
      ["deliberate exaggeration for emphasis or dramatic effect", "understatement for ironic effect", "the use of a word that imitates a sound", "a contradiction between two words placed together"], "deliberate exaggeration for emphasis or dramatic effect",
      "Hyperbole intentionally overstates something to create emphasis or a strong impression, not intended to be taken literally, e.g., 'I've told you a million times.'"),
  _q("Irony, as a literary device, refers to a situation in which",
      ["there is a contrast between what is expected and what actually happens or is meant", "a statement is deliberately made more extreme than reality", "human traits are given to non-human things", "a sound is imitated through word choice"], "there is a contrast between what is expected and what actually happens or is meant",
      "Irony highlights a gap between appearance and reality, expectation and outcome, or literal and intended meaning, often creating a sense of surprise or critique."),
  _q("Dramatic irony occurs when",
      ["the audience knows something important that a character in the story does not know", "a character says the exact opposite of what they mean", "two words with opposite meanings are placed side by side", "an event happens that is the opposite of what was expected by everyone, including the audience"], "the audience knows something important that a character in the story does not know",
      "Dramatic irony creates tension or humour because the audience possesses information a character lacks, making the character's words or actions carry additional meaning."),
  _q("A soliloquy, common in Shakespearean drama, is best described as",
      ["a speech in which a character, alone on stage, reveals their inner thoughts to the audience", "a conversation between two or more characters", "a song performed by a chorus", "a stage direction describing the setting"], "a speech in which a character, alone on stage, reveals their inner thoughts to the audience",
      "A soliloquy allows a character to express private thoughts and feelings directly to the audience, as though thinking aloud, typically while alone on stage."),
  _q("An aside, in drama, refers to",
      ["a brief remark made by a character directly to the audience, unheard by other characters on stage", "the main climax of a play", "a long speech delivered to all characters present", "a stage direction indicating the time period"], "a brief remark made by a character directly to the audience, unheard by other characters on stage",
      "An aside is a short comment a character makes that is understood to be heard by the audience but not by the other characters present in the scene."),
  _q("Tragedy, as a literary genre, typically involves",
      ["a protagonist whose downfall results from a fatal flaw or a combination of circumstances beyond their control", "a lighthearted plot that always ends happily", "a purely factual, non-fictional account of events", "a series of unconnected short poems"], "a protagonist whose downfall results from a fatal flaw or a combination of circumstances beyond their control",
      "Classical tragedy centres on a protagonist (often of high status) whose serious flaw or unfortunate circumstances lead to their downfall, evoking pity and fear in the audience."),
  _q("A tragic hero's downfall is often attributed to a personal flaw known as",
      ["hamartia", "catharsis", "anagnorisis", "hubris only, and never any other flaw"], "hamartia",
      "Hamartia refers to the tragic hero's inherent flaw or error in judgement that sets in motion the chain of events leading to their downfall."),
  _q("Catharsis, a concept from Aristotle's theory of tragedy, refers to the",
      ["emotional release or purification experienced by the audience after watching a tragedy", "moment a character recognises the truth about their situation", "resolution of the main conflict in a comedy", "final scene of any dramatic work"], "emotional release or purification experienced by the audience after watching a tragedy",
      "Catharsis describes the emotional cleansing or release of pity and fear that Aristotle believed audiences experience by witnessing the events of a tragedy."),
  _q("A protagonist in a literary work is best described as",
      ["the central character around whom the main action of the story revolves", "the character who opposes the main character", "a minor character with little influence on the plot", "the narrator of the story only"], "the central character around whom the main action of the story revolves",
      "The protagonist is the principal character whose goals, conflicts, and development typically drive the central plot of a literary work."),
  _q("An antagonist in a literary work is best described as",
      ["the character or force that opposes the protagonist", "the central character of the story", "a character who narrates the events of the story", "the setting in which the story takes place"], "the character or force that opposes the protagonist",
      "The antagonist creates conflict by opposing the protagonist's goals or desires, driving much of the tension in the plot."),
  _q("Setting, as an element of a literary work, refers to the",
      ["time and place in which the events of the story occur", "sequence of events in the plot", "central message or lesson of the story", "list of characters involved in the story"], "time and place in which the events of the story occur",
      "Setting establishes the historical period, geographical location, and social context within which a narrative's events unfold."),
  _q("Theme, in literature, refers to the",
      ["central idea, message, or underlying meaning explored in a literary work", "sequence of events that make up the plot", "physical location where the story is set", "list of characters appearing in the story"], "central idea, message, or underlying meaning explored in a literary work",
      "A theme is the deeper, often universal, idea or insight a literary work explores or comments on, distinct from the literal plot events."),
  _q("Plot, as an element of a literary work, refers to the",
      ["structured sequence of events that make up the story", "time and place in which the story occurs", "moral lesson conveyed by the story", "individual characters who appear in the story"], "structured sequence of events that make up the story",
      "Plot is the organised arrangement of events and actions in a narrative, typically involving exposition, rising action, climax, falling action, and resolution."),
  _q("Characterisation refers to the",
      ["methods a writer uses to develop and reveal a character's personality and traits", "physical setting of the literary work", "central theme explored by the author", "rhyme scheme used in a poem"], "methods a writer uses to develop and reveal a character's personality and traits",
      "Characterisation encompasses the techniques (dialogue, action, description, other characters' reactions) an author uses to construct and reveal a character to the reader."),
  _q("A flat character in a literary work is one who",
      ["is simple, one-dimensional, and does not undergo significant development", "changes and develops significantly throughout the story", "always serves as the story's protagonist", "narrates the events of the story"], "is simple, one-dimensional, and does not undergo significant development",
      "Flat characters are relatively simple, often defined by a single dominant trait, and typically do not undergo the depth of development seen in more complex, rounded characters."),
  _q("A round character in a literary work is one who",
      ["is complex, multi-dimensional, and often undergoes significant development", "is simple and unchanging throughout the story", "appears only briefly in a single scene", "exists purely to narrate the events of the plot"], "is complex, multi-dimensional, and often undergoes significant development",
      "Round characters possess complex, realistic personalities and often evolve meaningfully in response to the story's events, unlike simpler flat characters."),
  _q("In poetry, a stanza refers to a",
      ["group of lines forming a unit, similar to a paragraph in prose", "single word repeated at the end of consecutive lines", "specific type of rhyme scheme only", "type of dramatic monologue"], "group of lines forming a unit, similar to a paragraph in prose",
      "A stanza is a grouped set of lines within a poem, functioning structurally in a similar way to a paragraph in prose writing."),
  _q("Alliteration is a literary device involving the",
      ["repetition of the same initial consonant sound in nearby words", "repetition of an entire line at intervals throughout a poem", "use of a word that imitates the sound it describes", "direct comparison of two things using 'like' or 'as'"], "repetition of the same initial consonant sound in nearby words",
      "Alliteration repeats the same consonant sound at the beginning of neighbouring words (e.g., 'the wild wind whispered'), often used for rhythm and emphasis."),
  _q("Onomatopoeia is a literary device in which a word",
      ["imitates or suggests the natural sound it describes", "is repeated for emphasis at the end of a line", "compares two unlike things using 'like' or 'as'", "gives human traits to an inanimate object"], "imitates or suggests the natural sound it describes",
      "Onomatopoeic words (e.g., 'buzz', 'clang', 'hiss') mimic the actual sound associated with the thing they describe, adding sensory vividness to writing."),
  _q("A symbol, in literature, is an object, person, or event that",
      ["represents a deeper meaning beyond its literal sense", "has no significance beyond its literal, physical presence", "always refers exclusively to a religious concept", "only appears in poetry, never in prose or drama"], "represents a deeper meaning beyond its literal sense",
      "A symbol carries meaning beyond its literal identity, standing in for a broader idea, theme, or concept within a literary work, such as a dove symbolising peace."),
  _q("Foreshadowing, as a narrative technique, involves",
      ["giving hints or clues earlier in a story about events that will happen later", "revealing the full ending of a story at its very beginning", "describing a character's physical appearance in detail", "using dialogue exclusively to develop the plot"], "giving hints or clues earlier in a story about events that will happen later",
      "Foreshadowing plants subtle clues or hints about future plot developments, building anticipation or tension without fully revealing what is to come."),
  _q("A flashback, as a narrative technique, involves",
      ["interrupting the present action of a story to depict an earlier event", "predicting future events before they occur", "describing the setting of a story in great detail", "combining two separate stories into a single narrative"], "interrupting the present action of a story to depict an earlier event",
      "A flashback shifts the narrative back in time from the current point in the story, often providing background information or context relevant to present events."),
  _q("Comedy, as a literary genre, is typically characterised by",
      ["a light-hearted tone and a resolution that is generally happy or favourable for the main characters", "a serious tone ending in the protagonist's downfall or death", "a purely factual, non-fictional account of real events", "the complete absence of any conflict or tension"], "a light-hearted tone and a resolution that is generally happy or favourable for the main characters",
      "Comedy typically employs humour and wit, often involving misunderstandings or obstacles that are ultimately resolved happily, contrasting with the serious, often fatal, outcomes of tragedy."),
  _q("A narrator who tells a story using pronouns such as 'he', 'she', and 'they', without being a character in the story, is described as using",
      ["third-person narration", "first-person narration", "second-person narration", "dramatic narration"], "third-person narration",
      "Third-person narration recounts events from outside the story using external pronouns, unlike first-person narration, which uses 'I' and involves a narrator who is also a character."),
];

final _antonyAndCleopatra = [
  _q("Antony and Cleopatra, a play prescribed on the JAMB Literature syllabus, was written by",
      ["William Shakespeare", "Robert Bolt", "J.B. Priestley", "Efua Sutherland"], "William Shakespeare",
      "Antony and Cleopatra is a tragedy by William Shakespeare, based on the historical relationship between the Roman general Mark Antony and the Egyptian queen Cleopatra."),
  _q("In Antony and Cleopatra, Mark Antony is a Roman general who is romantically involved with",
      ["Cleopatra, the Queen of Egypt", "Octavia, sister of Octavius Caesar, exclusively", "Enobarbus's wife", "Charmian, Cleopatra's attendant"], "Cleopatra, the Queen of Egypt",
      "The central relationship of the play is the passionate romantic and political alliance between Antony and Cleopatra, which conflicts with Antony's duties as a Roman leader."),
  _q("In Antony and Cleopatra, Antony forms a political alliance with Rome (the Second Triumvirate) alongside Octavius Caesar and",
      ["Lepidus", "Enobarbus", "Pompey", "Agrippa"], "Lepidus",
      "The Second Triumvirate in the play consists of Mark Antony, Octavius Caesar, and Lepidus, ruling different parts of the Roman world."),
  _q("In Antony and Cleopatra, Antony marries Octavia mainly in an attempt to",
      ["strengthen and cement his political alliance with her brother, Octavius Caesar", "escape from Cleopatra's influence permanently", "gain the throne of Egypt through marriage", "please the citizens of Alexandria"], "strengthen and cement his political alliance with her brother, Octavius Caesar",
      "Antony's marriage to Octavia is primarily a political move intended to reconcile and solidify his fragile alliance with Octavius Caesar, though it ultimately fails when Antony returns to Cleopatra."),
  _q("Enobarbus, a key supporting character in Antony and Cleopatra, is best described as",
      ["a loyal friend and soldier to Antony who eventually deserts him", "Antony's chief political rival", "the ruler of Rome", "Cleopatra's brother"], "a loyal friend and soldier to Antony who eventually deserts him",
      "Enobarbus is Antony's loyal companion for much of the play, but he eventually abandons Antony for Octavius Caesar's side, later dying of grief over his betrayal."),
  _q("The famous description of Cleopatra's barge, describing her as an image where 'age cannot wither her, nor custom stale her infinite variety,' is delivered by",
      ["Enobarbus", "Octavius Caesar", "Antony", "Charmian"], "Enobarbus",
      "Enobarbus delivers this celebrated description of Cleopatra's magnetic and endlessly captivating charm to fellow Romans, capturing her legendary allure."),
  _q("In Antony and Cleopatra, the naval battle at Actium is significant because",
      ["Antony suffers a decisive defeat after following Cleopatra's fleet as it retreats", "it results in a decisive victory that secures Antony's control over Rome", "it is fought entirely on land rather than at sea", "it takes place after Antony's death"], "Antony suffers a decisive defeat after following Cleopatra's fleet as it retreats",
      "The Battle of Actium marks a critical turning point: Antony's forces are defeated after he follows Cleopatra's retreating ships, severely damaging his military and political standing."),
  _q("At the end of Antony and Cleopatra, Antony dies by",
      ["falling on his own sword after mistakenly believing Cleopatra is dead", "being executed by Octavius Caesar's soldiers", "drowning during the Battle of Actium", "being poisoned by Cleopatra"], "falling on his own sword after mistakenly believing Cleopatra is dead",
      "Antony, believing a false report that Cleopatra has died, attempts suicide by falling on his sword, dying shortly afterward in Cleopatra's monument."),
  _q("Cleopatra's death at the end of the play is caused by",
      ["the bite of an asp (venomous snake) that she deliberately allows to bite her", "poison administered by Octavius Caesar", "a fatal wound suffered in battle", "natural causes after a long illness"], "the bite of an asp (venomous snake) that she deliberately allows to bite her",
      "Cleopatra chooses to die with dignity by allowing an asp, smuggled to her in a basket of figs, to bite her, rather than be paraded as a captive in Octavius Caesar's triumph in Rome."),
  _q("A major theme explored in Antony and Cleopatra is the conflict between",
      ["romantic passion and political duty/responsibility", "science and religion", "urban and rural life", "youth and old age exclusively"], "romantic passion and political duty/responsibility",
      "The play's central tension arises from Antony being torn between his overwhelming love for Cleopatra and the political and military obligations of his role as a Roman leader."),
];

final _africanDrama = [
  _q("The Marriage of Anansewa, a play on the JAMB Literature syllabus, was written by",
      ["Efua Sutherland", "Wole Soyinka", "Bosede Ademilua-Afolayan", "Robert Bolt"], "Efua Sutherland",
      "The Marriage of Anansewa is a well-known play by the Ghanaian playwright Efua Sutherland, drawing on the Anansegoro (Ananse storytelling) tradition."),
  _q("In The Marriage of Anansewa, the central character Ananse is best described as a",
      ["cunning and resourceful father scheming to secure wealth through his daughter's marriage", "wealthy chief with no financial troubles", "foreign trader visiting the village", "young suitor seeking Anansewa's hand in marriage"], "cunning and resourceful father scheming to secure wealth through his daughter's marriage",
      "Ananse is a trickster figure, drawing on the traditional Ananse (spider) folklore character, who schemes to profit from arranging his daughter Anansewa's marriage to multiple wealthy suitors simultaneously."),
  _q("In The Marriage of Anansewa, Ananse's scheme involves",
      ["promising his daughter Anansewa in marriage to several wealthy chiefs at the same time to extract gifts from each", "refusing all suitors who ask for his daughter's hand", "arranging a marriage without asking for any dowry", "giving away his daughter for free to the poorest suitor"], "promising his daughter Anansewa in marriage to several wealthy chiefs at the same time to extract gifts from each",
      "Ananse's central trick is accepting proposals and gifts from multiple wealthy chiefs simultaneously, intending to eventually choose just one, exploiting the others for material gain."),
  _q("The character Anansewa, in The Marriage of Anansewa, is best described as",
      ["Ananse's daughter, whose marriage is used as a pawn in her father's scheme", "Ananse's wife, who supports his scheming", "a rival trickster figure to Ananse", "a foreign princess visiting Ananse's village"], "Ananse's daughter, whose marriage is used as a pawn in her father's scheme",
      "Anansewa is Ananse's daughter, whose feelings and wellbeing are largely subordinated to her father's elaborate financial scheme involving her marriage prospects."),
  _q("A major theme explored in The Marriage of Anansewa is",
      ["greed and the exploitation of family relationships for material gain", "the industrial revolution and its effects on rural life", "war between two rival nations", "the discovery of a hidden natural resource"], "greed and the exploitation of family relationships for material gain",
      "The play critiques Ananse's greedy manipulation of his own daughter's marriage prospects purely for personal financial benefit, exploring themes of deception and exploitation."),
  _q("The dramatic style of The Marriage of Anansewa draws heavily on the Ghanaian storytelling tradition known as",
      ["Anansegoro", "Kabuki", "Commedia dell'arte", "Greek tragedy"], "Anansegoro",
      "Anansegoro is a Ghanaian theatrical tradition derived from Ananse (spider) trickster folktales, and Efua Sutherland adapted this storytelling style into a formal dramatic structure in the play."),
  _q("Once Upon an Elephant, an alternative African drama text on the JAMB syllabus, was written by",
      ["Bosede Ademilua-Afolayan", "Efua Sutherland", "Wole Soyinka", "J.B. Priestley"], "Bosede Ademilua-Afolayan",
      "Once Upon an Elephant is a Nigerian play by Bosede Ademilua-Afolayan, offered as an alternative African drama text alongside The Marriage of Anansewa on the harmonized syllabus."),
  _q("Once Upon an Elephant, as an African drama text, generally engages with themes relating to",
      ["African cultural heritage, tradition, and societal values", "European industrial history", "Antarctic exploration", "space travel and futuristic technology"], "African cultural heritage, tradition, and societal values",
      "As with much African drama on the syllabus, the play engages with themes of cultural heritage and tradition, reflecting concerns central to African dramatic literature."),
];

final _nonAfricanDrama = [
  _q("A Man for All Seasons, a play on the JAMB Literature syllabus, was written by",
      ["Robert Bolt", "J.B. Priestley", "William Shakespeare", "Efua Sutherland"], "Robert Bolt",
      "A Man for All Seasons is a historical drama by the English playwright Robert Bolt, depicting the life and principled stand of Sir Thomas More."),
  _q("A Man for All Seasons centres on the life of",
      ["Sir Thomas More, who refuses to support King Henry VIII's divorce and remarriage", "King Henry VIII himself as the main protagonist", "a fictional English merchant with no historical basis", "Queen Elizabeth I of England"], "Sir Thomas More, who refuses to support King Henry VIII's divorce and remarriage",
      "The play dramatises the true story of Sir Thomas More, who was ultimately executed for refusing to endorse King Henry VIII's break from the Catholic Church to remarry."),
  _q("A central theme of A Man for All Seasons is",
      ["individual conscience and moral integrity in the face of political pressure", "the industrialisation of English society", "the exploration of unknown territories overseas", "romantic love overcoming social class barriers"], "individual conscience and moral integrity in the face of political pressure",
      "The play explores Thomas More's unwavering commitment to his personal and religious conscience, even at the cost of his life, when pressured by the King to compromise his principles."),
  _q("In A Man for All Seasons, the character called 'The Common Man' functions mainly as",
      ["a narrator and commentator who plays several minor roles throughout the play", "the play's chief antagonist", "King Henry VIII's most trusted advisor", "Thomas More's son"], "a narrator and commentator who plays several minor roles throughout the play",
      "The Common Man serves as a versatile narrator figure, addressing the audience directly and taking on multiple minor roles, providing commentary on the unfolding events."),
  _q("At the end of A Man for All Seasons, Sir Thomas More is",
      ["executed for treason after refusing to take the Oath of Supremacy", "pardoned and restored to his position as Chancellor", "exiled from England permanently", "reconciled with King Henry VIII"], "executed for treason after refusing to take the Oath of Supremacy",
      "More is ultimately convicted and executed for treason after steadfastly refusing to swear the Oath of Supremacy, which would have required him to recognise the King's authority over the Church."),
  _q("An Inspector Calls, a play on the JAMB Literature syllabus, was written by",
      ["J.B. Priestley", "Robert Bolt", "William Shakespeare", "Harper Lee"], "J.B. Priestley",
      "An Inspector Calls is a play by the English playwright J.B. Priestley, exploring themes of social responsibility through the mysterious investigation of a young woman's death."),
  _q("In An Inspector Calls, the character Inspector Goole visits the Birling family to investigate the",
      ["suicide of a young working-class woman named Eva Smith", "theft of valuable family jewellery", "disappearance of the Birlings' youngest son", "murder of a local business rival"], "suicide of a young working-class woman named Eva Smith",
      "Inspector Goole arrives to question the Birling family about their individual roles in the events leading to the suicide of Eva Smith, a young working-class woman."),
  _q("A central theme of An Inspector Calls is",
      ["collective social responsibility and the consequences of individual actions on others", "the benefits of unregulated capitalism", "the joys of family reconciliation", "the exploration of space and time travel"], "collective social responsibility and the consequences of individual actions on others",
      "Priestley uses the play to argue that individuals bear responsibility for the wellbeing of others in society, critiquing selfish, class-based indifference to the suffering of the less fortunate."),
  _q("At the end of An Inspector Calls, it is revealed that",
      ["Inspector Goole's true identity and the true sequence of events remain deliberately ambiguous, adding a supernatural or moral dimension to the play", "Inspector Goole was definitively proven to be a real police officer", "Eva Smith was found alive and unharmed", "the entire investigation was immediately dismissed as irrelevant by the family"], "Inspector Goole's true identity and the true sequence of events remain deliberately ambiguous, adding a supernatural or moral dimension to the play",
      "The play's ending leaves open questions about whether Inspector Goole was a real inspector, a moral device, or something supernatural, reinforcing its central message about responsibility regardless of the literal explanation."),
  _q("An Inspector Calls is notable for its use of dramatic structure that unfolds in",
      ["real time, largely within a single setting (the Birling family's dining room)", "multiple settings across several different countries", "a non-linear structure jumping between many decades", "an entirely wordless, mime-based performance style"], "real time, largely within a single setting (the Birling family's dining room)",
      "The play largely adheres to the classical unities, unfolding in continuous real time within essentially one setting, heightening the tension of the investigation."),
];

final _africanProse = [
  _q("So the Path Does Not Die, a novel on the JAMB Literature syllabus, was written by",
      ["Pede Hollist", "Elma Shaw", "Harper Lee", "Susanne Bellefeuille"], "Pede Hollist",
      "So the Path Does Not Die is a novel by the Sierra Leonean-American writer Pede Hollist."),
  _q("So the Path Does Not Die is primarily set in which West African country?",
      ["Sierra Leone", "Nigeria", "Ghana", "Senegal"], "Sierra Leone",
      "The novel is set primarily in Sierra Leone, drawing on the author's own Sierra Leonean background and cultural context."),
  _q("A central concern of So the Path Does Not Die relates to",
      ["the impact of a harmful traditional practice on the life of its central female character", "a war between two rival West African kingdoms", "the discovery of oil reserves in a coastal village", "a European colonial administrator's diary"], "the impact of a harmful traditional practice on the life of its central female character",
      "The novel engages with the lasting personal and psychological impact of a harmful traditional practice on its central female protagonist, exploring themes of tradition, trauma, and identity."),
  _q("A major theme in So the Path Does Not Die is the tension between",
      ["traditional cultural practices and individual autonomy or modern values", "urban development and environmental conservation", "monarchy and democracy in a fictional kingdom", "science fiction and futuristic technology"], "traditional cultural practices and individual autonomy or modern values",
      "The novel explores the conflict between deeply rooted traditional expectations and the protagonist's own sense of self and desire to define her own path in life."),
  _q("Redemption Road, a novel on the JAMB Literature syllabus, was written by",
      ["Elma Shaw", "Pede Hollist", "Harper Lee", "Robert Bolt"], "Elma Shaw",
      "Redemption Road is a novel by the Liberian writer Elma Shaw."),
  _q("Redemption Road is primarily set against the backdrop of",
      ["civil conflict and its aftermath in Liberia", "the industrial revolution in Britain", "ancient Egyptian civilisation", "modern-day Wall Street finance"], "civil conflict and its aftermath in Liberia",
      "The novel is set in Liberia and engages with the lasting effects of the Liberian civil conflict on individuals and communities."),
  _q("A central theme of Redemption Road is",
      ["healing, reconciliation, and rebuilding in the aftermath of conflict", "space exploration and scientific discovery", "the rivalry between two European royal families", "the history of transatlantic shipping routes"], "healing, reconciliation, and rebuilding in the aftermath of conflict",
      "As its title suggests, the novel centrally explores paths toward personal and communal healing and reconciliation following the trauma of civil conflict."),
  _q("Both So the Path Does Not Die and Redemption Road, as African prose texts on the JAMB syllabus, share a common concern with",
      ["exploring difficult social realities in West Africa and their impact on individual characters", "depicting purely fictional fantasy worlds unconnected to reality", "chronicling the history of European exploration of Africa", "describing life in wealthy, conflict-free societies"], "exploring difficult social realities in West Africa and their impact on individual characters",
      "Both novels engage seriously with real, difficult social and historical realities in West Africa (harmful traditional practices and civil conflict, respectively) and their profound effects on individual lives."),
  _q("Pede Hollist and Elma Shaw, the authors of the two prescribed African prose texts, are both writers connected to",
      ["West Africa, drawing on their personal or ancestral connections to the region in their fiction", "South America, with no connection to West Africa", "Southeast Asia exclusively", "Northern Europe with no African connection"], "West Africa, drawing on their personal or ancestral connections to the region in their fiction",
      "Both authors have personal ties to West Africa (Sierra Leone and Liberia respectively), and their prescribed novels draw significantly on the social and historical realities of that region."),
];

final _nonAfricanProse = [
  _q("To Kill a Mockingbird, one of the prescribed non-African prose texts, was written by",
      ["Harper Lee", "Susanne Bellefeuille", "Robert Bolt", "J.B. Priestley"], "Harper Lee",
      "To Kill a Mockingbird is a celebrated novel by the American author Harper Lee, first published in 1960."),
  _q("To Kill a Mockingbird is narrated from the perspective of",
      ["Scout Finch, a young girl reflecting on her childhood", "Atticus Finch, her father", "Tom Robinson, the falsely accused man", "Boo Radley, the reclusive neighbour"], "Scout Finch, a young girl reflecting on her childhood",
      "The novel is narrated by Jean Louise 'Scout' Finch, recalling and reflecting on events from her childhood in the fictional town of Maycomb, Alabama."),
  _q("In To Kill a Mockingbird, Atticus Finch is a lawyer who defends",
      ["Tom Robinson, a Black man falsely accused of raping a white woman", "his own daughter, Scout, against false charges", "Bob Ewell in a civil dispute", "the reclusive neighbour, Boo Radley, in an unrelated matter"], "Tom Robinson, a Black man falsely accused of raping a white woman",
      "Atticus Finch takes on the legally and socially difficult task of defending Tom Robinson, a Black man wrongly accused of a serious crime, in the racially prejudiced setting of the American South."),
  _q("A major theme explored in To Kill a Mockingbird is",
      ["racial injustice and moral growth in a prejudiced society", "the benefits of urban industrialisation", "space exploration and scientific advancement", "international diplomacy between rival nations"], "racial injustice and moral growth in a prejudiced society",
      "The novel powerfully explores themes of racial prejudice, injustice, and the moral development of children (Scout and Jem) as they witness these realities in their community."),
  _q("The title 'To Kill a Mockingbird' relates symbolically to the idea that",
      ["it is a sin to harm innocent, harmless beings who do no wrong, such as Tom Robinson and Boo Radley", "mockingbirds are dangerous pests that must be eliminated", "hunting birds is a celebrated tradition in Maycomb", "Atticus Finch is himself literally a bird hunter"], "it is a sin to harm innocent, harmless beings who do no wrong, such as Tom Robinson and Boo Radley",
      "The mockingbird symbolises innocent characters (notably Tom Robinson and Boo Radley) who are harmed despite doing nothing but good, reflecting the novel's central moral concern."),
  _q("Boo Radley, a significant character in To Kill a Mockingbird, is initially portrayed to the children as",
      ["a mysterious, reclusive neighbour who is the subject of local rumours and fear", "the town's respected mayor", "Atticus Finch's law partner", "Scout's teacher at school"], "a mysterious, reclusive neighbour who is the subject of local rumours and fear",
      "Boo Radley is initially depicted as a frightening, mysterious figure in local legend, though he is later revealed to be a gentle, protective presence in the children's lives."),
  _q("At the end of To Kill a Mockingbird, Tom Robinson is",
      ["convicted by the all-white jury despite clear evidence of his innocence, and is later killed while attempting to escape prison", "acquitted and freed by the jury", "never brought to trial at all", "found to have committed the crime after new evidence emerges"], "convicted by the all-white jury despite clear evidence of his innocence, and is later killed while attempting to escape prison",
      "Despite Atticus's compelling defence and clear evidence pointing to his innocence, Tom Robinson is convicted by the prejudiced jury, and is later shot and killed while attempting to escape custody."),
  _q("Path of Lucas: The Journey He Endured, an alternative non-African prose text on the JAMB syllabus, was written by",
      ["Susanne Bellefeuille", "Harper Lee", "Pede Hollist", "Elma Shaw"], "Susanne Bellefeuille",
      "Path of Lucas: The Journey He Endured is a novel by Susanne Bellefeuille, offered as an alternative non-African prose text alongside To Kill a Mockingbird on the harmonized syllabus."),
  _q("As suggested by its title, Path of Lucas: The Journey He Endured centrally concerns",
      ["the personal struggles and journey of endurance faced by its central character, Lucas", "a historical account of European colonisation", "a purely comedic tale with no serious themes", "an adventure story set entirely in outer space"], "the personal struggles and journey of endurance faced by its central character, Lucas",
      "As the title indicates, the novel follows the difficult personal journey and hardships endured by its central character, Lucas, a theme reflected directly in the book's title."),
  _q("Which of the following is a shared thematic concern between To Kill a Mockingbird and Path of Lucas, as non-African prose texts on the syllabus?",
      ["The endurance of hardship and the pursuit of moral growth or justice", "The celebration of unchecked wealth and material success", "A focus purely on light-hearted, comedic events with no deeper meaning", "The complete absence of any central conflict"], "The endurance of hardship and the pursuit of moral growth or justice",
      "Both novels, in their own settings, explore characters enduring significant hardship while grappling with questions of justice, resilience, and moral development."),
];

final _africanPoetry = [
  _q("The poem 'Once Upon a Time' on the JAMB Literature syllabus was written by",
      ["Gabriel Okara", "Wole Soyinka", "Niyi Osundare", "Syl Cheney-Coker"], "Gabriel Okara",
      "'Once Upon a Time' is a well-known poem by the Nigerian poet Gabriel Okara."),
  _q("A central theme of Gabriel Okara's 'Once Upon a Time' is",
      ["the loss of genuine human sincerity and warmth in modern, sophisticated society", "the celebration of technological progress", "a description of a beautiful natural landscape", "the joys of childhood without any deeper reflection"], "the loss of genuine human sincerity and warmth in modern, sophisticated society",
      "The poem laments how people have become insincere and superficial in their social interactions ('laugh with their eyes while their ice-block-cold eyes search behind my shadow'), contrasting this with a more genuine past."),
  _q("In 'Once Upon a Time', the speaker expresses a desire to",
      ["relearn how to laugh and be genuinely sincere, as he once was as a child", "become wealthier than his neighbours", "travel to a foreign country permanently", "forget his own children completely"], "relearn how to laugh and be genuinely sincere, as he once was as a child",
      "The poem's speaker, addressing his son, wishes to unlearn the artificial habits of adulthood and rediscover the genuine, unguarded sincerity he had as a child."),
  _q("The poem 'New Tongue' on the JAMB Literature syllabus was written by",
      ["Elizabeth L.A. Kamara", "Wole Soyinka", "Niyi Osundare", "S.O.H. Afriyie-Vidza"], "Elizabeth L.A. Kamara",
      "'New Tongue' is a poem by the Sierra Leonean poet Elizabeth L.A. Kamara, included on the harmonized JAMB Literature syllabus."),
  _q("The poem 'Night' on the JAMB Literature syllabus was written by",
      ["Wole Soyinka", "Gabriel Okara", "Niyi Osundare", "Syl Cheney-Coker"], "Wole Soyinka",
      "'Night' is a poem by the Nigerian Nobel laureate Wole Soyinka, exploring imagery and reflection associated with the night."),
  _q("The poem 'Not My Business' on the JAMB Literature syllabus was written by",
      ["Niyi Osundare", "Wole Soyinka", "Gabriel Okara", "Elizabeth L.A. Kamara"], "Niyi Osundare",
      "'Not My Business' is a well-known poem by the Nigerian poet Niyi Osundare."),
  _q("A central theme of Niyi Osundare's 'Not My Business' is",
      ["the danger of indifference to injustice suffered by others, since it may eventually affect oneself", "the beauty of a rural farming landscape", "a celebration of a wedding ceremony", "the joys of international travel"], "the danger of indifference to injustice suffered by others, since it may eventually affect oneself",
      "The poem uses a repeated refrain of persecuted neighbours to warn against complacent indifference to injustice, since the speaker ultimately becomes a victim themselves."),
  _q("The poem 'Hearty Garlands' on the JAMB Literature syllabus was written by",
      ["S.O.H. Afriyie-Vidza", "Wole Soyinka", "Gabriel Okara", "Syl Cheney-Coker"], "S.O.H. Afriyie-Vidza",
      "'Hearty Garlands' is a poem by S.O.H. Afriyie-Vidza, included among the prescribed African poems on the harmonized JAMB Literature syllabus."),
  _q("The poem 'The Breasts of the Sea' on the JAMB Literature syllabus was written by",
      ["Syl Cheney-Coker", "Wole Soyinka", "Niyi Osundare", "Gabriel Okara"], "Syl Cheney-Coker",
      "'The Breasts of the Sea' is a poem by the Sierra Leonean poet Syl Cheney-Coker, featured on the harmonized JAMB Literature syllabus."),
  _q("Which of the following poets on the JAMB African poetry list is a Nigerian Nobel Laureate in Literature?",
      ["Wole Soyinka", "Gabriel Okara", "Niyi Osundare", "Syl Cheney-Coker"], "Wole Soyinka",
      "Wole Soyinka, author of 'Night', won the Nobel Prize in Literature in 1986, becoming the first African laureate in the category."),
  _q("Gabriel Okara, the poet of 'Once Upon a Time', is notable in African literature for his",
      ["experimentation with translating Ijaw speech rhythms and thought patterns into English poetry and prose", "exclusive focus on writing in French", "career as primarily a playwright rather than a poet or novelist", "work being set entirely outside Africa"], "experimentation with translating Ijaw speech rhythms and thought patterns into English poetry and prose",
      "Okara, a Nigerian writer of Ijaw heritage, is well known for his stylistic innovation in rendering African linguistic patterns and thought structures into English literary form."),
  _q("Which theme is commonly shared across several of the prescribed African poems, such as 'Once Upon a Time' and 'Not My Business'?",
      ["Social critique of dishonesty, indifference, or moral decline in society", "The celebration of purely personal romantic love with no social commentary", "A detailed scientific description of natural phenomena", "An account of a historical military battle"], "Social critique of dishonesty, indifference, or moral decline in society",
      "Both poems, in different ways, critique aspects of social behaviour — insincerity in 'Once Upon a Time' and dangerous indifference in 'Not My Business' — reflecting a broader trend of social critique in African poetry."),
  _q("Elizabeth L.A. Kamara and Syl Cheney-Coker, two poets on the JAMB African poetry list, share a connection to which West African country?",
      ["Sierra Leone", "Nigeria", "Ghana", "Senegal"], "Sierra Leone",
      "Both Elizabeth L.A. Kamara and Syl Cheney-Coker are poets connected to Sierra Leone, reflecting the syllabus's inclusion of a range of West African literary voices."),
  _q("The recurring refrain technique, in which a phrase or line is repeated throughout a poem, is often used to",
      ["reinforce a central theme or emotional emphasis", "confuse the reader intentionally", "indicate the poem has no coherent structure", "replace the need for a title"], "reinforce a central theme or emotional emphasis",
      "Poets frequently use refrains (repeated lines or phrases) to reinforce key ideas, build rhythm, or intensify emotional impact, a technique seen in poems like 'Not My Business'."),
  _q("Poetic imagery, as used in the prescribed African poems, refers to the",
      ["use of vivid, descriptive language that appeals to the senses to create mental pictures", "strict rhyme scheme followed throughout a poem", "number of stanzas contained in the poem", "poet's biographical background"], "use of vivid, descriptive language that appeals to the senses to create mental pictures",
      "Imagery involves language that evokes sensory experiences (sight, sound, touch, etc.), helping readers visualise and emotionally connect with the ideas expressed in a poem."),
];

final _nonAfricanPoetry = [
  _q("The poem 'She Walks in Beauty' on the JAMB Literature syllabus was written by",
      ["Lord Byron", "Geoffrey Chaucer", "Wilfred Wilson Gibson", "Fleur Adcock"], "Lord Byron",
      "'She Walks in Beauty' is a celebrated poem by the English Romantic poet Lord Byron, admiring the beauty of a woman."),
  _q("A central theme of Lord Byron's 'She Walks in Beauty' is",
      ["the harmonious blend of physical beauty and inner goodness in the woman being described", "the horrors of war", "the celebration of scientific progress", "the poet's despair over unrequited love"], "the harmonious blend of physical beauty and inner goodness in the woman being described",
      "The poem praises a woman's beauty as a perfect balance of light and dark, external and internal, suggesting her physical loveliness reflects an inner peace and goodness."),
  _q("The poem 'The Stone' on the JAMB Literature syllabus was written by",
      ["Wilfred Wilson Gibson", "Lord Byron", "Geoffrey Chaucer", "Fleur Adcock"], "Wilfred Wilson Gibson",
      "'The Stone' is a poem by the English poet Wilfred Wilson Gibson, often noted for its poignant treatment of grief and loss, particularly associated with the impact of war."),
  _q("A central theme explored in Wilfred Wilson Gibson's 'The Stone' is",
      ["grief and the emotional impact of losing a loved one", "the beauty of a spring landscape", "the excitement of travelling to a new city", "a humorous depiction of everyday village life"], "grief and the emotional impact of losing a loved one",
      "The poem centres on a poignant, understated conversation revealing a father's grief upon learning of the death of his son, exploring themes of loss and mourning."),
  _q("'The Nun's Priest's Tale', a poem on the JAMB Literature syllabus, was written by",
      ["Geoffrey Chaucer", "Lord Byron", "Wilfred Wilson Gibson", "Fleur Adcock"], "Geoffrey Chaucer",
      "'The Nun's Priest's Tale' is one of the tales from Geoffrey Chaucer's 'The Canterbury Tales', a major work of medieval English literature."),
  _q("'The Nun's Priest's Tale' is notable for being told using which literary device, featuring a rooster and a fox as central characters?",
      ["A beast fable, using animal characters to convey a moral lesson", "A purely factual historical account", "A modern free-verse structure with no rhyme or metre", "A dramatic monologue delivered by a human king"], "A beast fable, using animal characters to convey a moral lesson",
      "The tale is structured as a beast fable, featuring the rooster Chanticleer and a cunning fox, using their interactions to deliver moral and satirical commentary, in the tradition of Aesop's fables."),
  _q("Geoffrey Chaucer, author of 'The Nun's Priest's Tale', is best known as a major figure in",
      ["medieval English literature, particularly through 'The Canterbury Tales'", "twentieth-century modernist poetry", "African oral storytelling traditions", "Romantic-era English poetry"], "medieval English literature, particularly through 'The Canterbury Tales'",
      "Chaucer, often called the 'father of English literature', is renowned for 'The Canterbury Tales', a collection of stories written in Middle English in the late 14th century."),
  _q("The poem 'The Telephone Call' on the JAMB Literature syllabus was written by",
      ["Fleur Adcock", "Lord Byron", "Geoffrey Chaucer", "Wilfred Wilson Gibson"], "Fleur Adcock",
      "'The Telephone Call' is a poem by the New Zealand-born poet Fleur Adcock."),
  _q("A central theme of Fleur Adcock's 'The Telephone Call' is",
      ["the excitement and subsequent disappointment or deception experienced by the speaker over unexpected news", "the joys of a long, happy marriage", "an account of a historical battle", "the celebration of a national holiday"], "the excitement and subsequent disappointment or deception experienced by the speaker over unexpected news",
      "The poem follows the speaker's rising excitement upon receiving apparently good news over the phone, only for this excitement to be undercut by disappointment, often interpreted as a satire on false promises like sweepstake scams."),
  _q("Which of the following best describes the difference in poetic tradition between Lord Byron's Romantic poetry and Geoffrey Chaucer's medieval poetry?",
      ["Byron's Romantic poetry emphasises individual emotion and idealised beauty, while Chaucer's medieval work often uses allegory and moral storytelling within a broader social frame", "Byron wrote exclusively in Middle English, while Chaucer wrote in modern English", "Chaucer's work has no relationship at all to storytelling or narrative", "Byron's poetry always uses animal characters, exactly like Chaucer's 'The Nun's Priest's Tale'"], "Byron's Romantic poetry emphasises individual emotion and idealised beauty, while Chaucer's medieval work often uses allegory and moral storytelling within a broader social frame",
      "Byron represents the Romantic era's focus on intense personal feeling and idealised beauty, while Chaucer's medieval storytelling often blends allegory, humour, and moral instruction within a wider narrative frame like 'The Canterbury Tales'."),
  _q("Unlike the other prescribed non-African poems, which are shorter lyric or narrative poems, 'The Nun's Priest's Tale' is distinct in that it",
      ["forms part of a larger, extended collection of interlinked tales", "is the shortest poem on the entire syllabus", "was written in the twenty-first century", "contains no characters of any kind"], "forms part of a larger, extended collection of interlinked tales",
      "Unlike the standalone shorter poems by Byron, Gibson, and Adcock, Chaucer's tale is one part of the much larger framed narrative collection, 'The Canterbury Tales'."),
];
