import "../quiz_question.dart";

const _subject = "Music";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// JAMB Music — 100 questions covering Rudiments and Theory of Music
/// (staff notation, rhythm/meter, scales/intervals, chords/harmony) and
/// History and Literature of Music (Western art music eras, African
/// traditional music, Nigerian art music/musicians, popular music).
List<QuizQuestion> buildJambMusicQuestions() {
  return [
    ..._staffNotation,
    ..._rhythmAndMeter,
    ..._scalesAndIntervals,
    ..._chordsAndHarmony,
    ..._westernArtMusicEras,
    ..._africanTraditionalMusic,
    ..._nigerianArtMusicAndMusicians,
    ..._popularMusic,
  ];
}

final _staffNotation = [
  _q("The treble clef, also known as the G clef, is primarily used for notating",
      ["higher-pitched instruments and voices, such as the violin or soprano voice", "lower-pitched instruments, such as the double bass or bass voice", "only percussion instruments", "only rhythm without specific pitch"], "higher-pitched instruments and voices, such as the violin or soprano voice",
      "The treble (G) clef is used for higher-range instruments and voices, with its curl centring on the second line of the staff, marking the pitch G above middle C."),
  _q("The bass clef, also known as the F clef, is primarily used for notating",
      ["lower-pitched instruments and voices, such as the cello or bass voice", "only the highest-pitched instruments", "only unpitched percussion", "only vocal soprano parts"], "lower-pitched instruments and voices, such as the cello or bass voice",
      "The bass (F) clef is used for lower-range instruments and voices, with its two dots surrounding the fourth line of the staff, marking the pitch F below middle C."),
  _q("The C clef, a movable clef used in music notation, centres middle C on",
      ["whichever line the clef symbol is positioned on, such as alto or tenor clef placement", "always the top line of the staff", "always the bottom line of the staff", "a line outside the staff entirely"], "whichever line the clef symbol is positioned on, such as alto or tenor clef placement",
      "Unlike the fixed treble and bass clefs, the C clef is movable, and wherever its centre point is placed on the staff indicates the position of middle C, as seen in alto and tenor clef usage."),
  _q("In the treble clef, the notes on the lines from bottom to top are commonly remembered using the mnemonic",
      ["Every Good Boy Does Fine (E, G, B, D, F)", "Face (F, A, C, E)", "Good Boys Do Fine Always", "All Cows Eat Grass"], "Every Good Boy Does Fine (E, G, B, D, F)",
      "The treble clef's five lines, from bottom to top, represent E, G, B, D, F, commonly remembered with the mnemonic 'Every Good Boy Does Fine'."),
  _q("In the treble clef, the notes in the spaces from bottom to top spell out the word",
      ["FACE (F, A, C, E)", "EGBDF", "GBDFA", "ACEG"], "FACE (F, A, C, E)",
      "The four spaces of the treble clef staff, from bottom to top, represent F, A, C, E, conveniently spelling the word 'FACE'."),
  _q("In the bass clef, the notes on the lines from bottom to top are commonly remembered using the mnemonic",
      ["Good Boys Do Fine Always (G, B, D, F, A)", "Every Good Boy Does Fine", "All Cows Eat Grass", "Face"], "Good Boys Do Fine Always (G, B, D, F, A)",
      "The bass clef's five lines, from bottom to top, represent G, B, D, F, A, commonly remembered with the mnemonic 'Good Boys Do Fine Always'."),
  _q("In the bass clef, the notes in the spaces from bottom to top spell out",
      ["All Cows Eat Grass (A, C, E, G)", "Face", "Every Good Boy Does Fine", "Good Boys Do Fine Always"], "All Cows Eat Grass (A, C, E, G)",
      "The four spaces of the bass clef staff, from bottom to top, represent A, C, E, G, commonly remembered with the mnemonic 'All Cows Eat Grass'."),
  _q("Middle C, an important reference pitch in music notation, is typically notated using",
      ["a ledger line, since it falls outside the five main lines of both the treble and bass staff", "the top line of the treble staff", "the bottom line of the bass staff", "a note that cannot be notated at all"], "a ledger line, since it falls outside the five main lines of both the treble and bass staff",
      "Middle C sits between the treble and bass staves, and is notated using a short ledger line either just below the treble staff or just above the bass staff."),
  _q("A ledger line in music notation is used to",
      ["extend the staff to notate pitches that fall above or below its five main lines", "indicate the tempo of a piece", "show the dynamics (loudness) of a passage", "indicate a change of key signature"], "extend the staff to notate pitches that fall above or below its five main lines",
      "Ledger lines are short additional lines added above or below the staff to accommodate notes whose pitch falls outside the standard five-line range."),
  _q("The grand staff, commonly used in piano music, combines which two clefs?",
      ["The treble clef and the bass clef", "Two treble clefs", "Two bass clefs", "The treble clef and a C clef only"], "The treble clef and the bass clef",
      "The grand staff joins the treble and bass clefs together (typically with a brace), allowing the wide pitch range of the piano to be notated clearly across both staves."),
];

final _rhythmAndMeter = [
  _q("A whole note (semibreve) typically receives how many beats in common time (4/4)?",
      ["Four beats", "Two beats", "One beat", "Half a beat"], "Four beats",
      "In common time (4/4), a whole note (semibreve) receives four full beats, the longest standard note duration in that context."),
  _q("A half note (minim) typically receives how many beats in common time (4/4)?",
      ["Two beats", "Four beats", "One beat", "Half a beat"], "Two beats",
      "A half note (minim) receives two beats in common time, half the duration of a whole note."),
  _q("A quarter note (crotchet) typically receives how many beats in common time (4/4)?",
      ["One beat", "Two beats", "Four beats", "Half a beat"], "One beat",
      "A quarter note (crotchet) receives one full beat in common time, often serving as the basic reference beat unit."),
  _q("An eighth note (quaver) typically receives how many beats in common time (4/4)?",
      ["Half a beat", "One beat", "Two beats", "A quarter of a beat"], "Half a beat",
      "An eighth note (quaver) receives half a beat in common time, with two eighth notes equalling one quarter note."),
  _q("A rest in music notation indicates",
      ["a specific duration of silence corresponding to a particular note value", "an increase in volume", "a change in key signature", "a change in tempo"], "a specific duration of silence corresponding to a particular note value",
      "Rests are symbols indicating silence for a specific, measured duration, directly corresponding to the note value durations (whole rest, half rest, quarter rest, etc.)."),
  _q("A time signature such as 4/4 indicates that",
      ["there are four beats per measure, with the quarter note receiving one beat", "there are four measures in the entire piece", "the piece must be played four times", "there are four different instruments required"], "there are four beats per measure, with the quarter note receiving one beat",
      "In a 4/4 time signature, the top number (4) indicates the number of beats per measure, and the bottom number (4) indicates that the quarter note represents one beat."),
  _q("A simple meter, such as 2/4, 3/4, or 4/4, is characterised by",
      ["each beat being divisible into two equal subdivisions", "each beat being divisible into three equal subdivisions", "having no regular beat pattern at all", "always having exactly five beats per measure"], "each beat being divisible into two equal subdivisions",
      "Simple meters (like 2/4, 3/4, 4/4) are defined by beats that naturally subdivide into two equal parts, distinguishing them from compound meters."),
  _q("A compound meter, such as 6/8, 9/8, or 12/8, is characterised by",
      ["each beat being divisible into three equal subdivisions", "each beat being divisible into two equal subdivisions", "having no time signature at all", "always being played very slowly"], "each beat being divisible into three equal subdivisions",
      "Compound meters (like 6/8, 9/8, 12/8) feature beats that naturally divide into three equal parts, unlike the two-part subdivision found in simple meters."),
  _q("Syncopation, a rhythmic device in music, refers to",
      ["placing emphasis or accent on normally weak or unexpected beats", "always accenting the first beat of every measure", "playing every note at exactly the same volume", "eliminating all rhythmic variation from a piece"], "placing emphasis or accent on normally weak or unexpected beats",
      "Syncopation creates rhythmic interest and tension by shifting emphasis away from the strong, expected beats onto weaker or off-beat positions."),
  _q("A triplet, a rhythmic device in music notation, refers to",
      ["a group of three notes played in the time normally taken by two notes of the same value", "a group of three separate measures", "three different time signatures used simultaneously", "three musicians playing the same note"], "a group of three notes played in the time normally taken by two notes of the same value",
      "A triplet compresses three notes into the rhythmic space that would normally accommodate only two notes of that value, indicated by a small '3' bracket over the notes."),
  _q("A dotted note in music notation indicates that the note's duration is",
      ["increased by half of its original value", "doubled entirely", "reduced by half", "unaffected, since the dot has no rhythmic meaning"], "increased by half of its original value",
      "A dot placed after a note extends its duration by half of the note's original value, e.g., a dotted half note equals a half note plus a quarter note (three beats total in common time)."),
  _q("A tie in music notation is used to",
      ["join two notes of the same pitch, combining their durations into one continuous sound", "indicate a rest between two notes", "raise the pitch of a note by a semitone", "indicate a change of instrument"], "join two notes of the same pitch, combining their durations into one continuous sound",
      "A tie is a curved line connecting two notes of identical pitch, indicating that they should be played as a single sustained sound with combined duration, without a new articulation."),
];

final _scalesAndIntervals = [
  _q("A major scale is characterised by a specific pattern of intervals, generally expressed as",
      ["whole, whole, half, whole, whole, whole, half", "whole, half, whole, whole, half, whole, whole", "half, whole, half, whole, half, whole, half", "whole, whole, whole, whole, whole, whole, whole"], "whole, whole, half, whole, whole, whole, half",
      "The major scale follows the specific interval pattern of whole-whole-half-whole-whole-whole-half steps, giving it its characteristic bright, stable sound."),
  _q("The natural minor scale is characterised by a specific pattern of intervals, generally expressed as",
      ["whole, half, whole, whole, half, whole, whole", "whole, whole, half, whole, whole, whole, half", "half, whole, whole, half, whole, whole, half", "whole, whole, whole, half, whole, whole, half"], "whole, half, whole, whole, half, whole, whole",
      "The natural minor scale follows the interval pattern whole-half-whole-whole-half-whole-whole, giving it its characteristic darker, more melancholic sound compared to the major scale."),
  _q("The harmonic minor scale differs from the natural minor scale mainly by",
      ["raising the seventh scale degree by a semitone", "lowering the third scale degree", "raising the second scale degree", "lowering the sixth scale degree only when descending"], "raising the seventh scale degree by a semitone",
      "The harmonic minor scale raises the seventh degree of the natural minor scale by a semitone, creating a stronger pull toward the tonic and a distinctive augmented second interval."),
  _q("The melodic minor scale is distinctive because it",
      ["raises both the sixth and seventh degrees when ascending, but reverts to the natural minor when descending", "is identical to the major scale in every respect", "lowers the second scale degree only", "has no distinguishing features from the harmonic minor scale"], "raises both the sixth and seventh degrees when ascending, but reverts to the natural minor when descending",
      "The melodic minor scale traditionally raises its sixth and seventh degrees when ascending (to smooth the melodic line toward the tonic) but uses the natural minor form when descending."),
  _q("A key signature with no sharps or flats corresponds to which major key?",
      ["C major", "G major", "F major", "D major"], "C major",
      "C major is the only major key with no sharps or flats in its key signature, using only the natural (white) piano keys."),
  _q("A key signature with one sharp corresponds to which major key?",
      ["G major", "C major", "D major", "F major"], "G major",
      "G major has one sharp (F#) in its key signature, following the standard order in which sharps are added progressively to key signatures."),
  _q("How many sharps are in the key signature of a major key with five sharps?",
      ["Five sharps, corresponding to B major", "Five sharps, corresponding to E major", "Four sharps, corresponding to E major", "Six sharps, corresponding to F# major"], "Five sharps, corresponding to B major",
      "A key signature with five sharps corresponds to B major, following the cycle of fifths progression of sharp key signatures (C, G, D, A, E, B)."),
  _q("How many flats are in the key signature of a major key with five flats?",
      ["Five flats, corresponding to Db major", "Five flats, corresponding to Gb major", "Four flats, corresponding to Ab major", "Six flats, corresponding to Gb major"], "Five flats, corresponding to Db major",
      "A key signature with five flats corresponds to Db major, following the cycle of fourths progression of flat key signatures (F, Bb, Eb, Ab, Db)."),
  _q("An interval in music refers to",
      ["the distance in pitch between two notes", "the duration of a note", "the volume of a note", "the timbre of an instrument"], "the distance in pitch between two notes",
      "An interval measures the pitch distance between two notes, described by both a numerical size (e.g., third, fifth) and a quality (e.g., major, minor, perfect)."),
  _q("The inversion of an interval is achieved by",
      ["moving the lower note up an octave, or the higher note down an octave", "playing both notes simultaneously instead of separately", "doubling the duration of both notes", "changing the key signature of the piece"], "moving the lower note up an octave, or the higher note down an octave",
      "Interval inversion is achieved by relocating one of the two notes by an octave, which systematically changes both the numerical size and quality of the resulting interval."),
  _q("When a major third is inverted, it becomes a",
      ["minor sixth", "major sixth", "minor third", "perfect fifth"], "minor sixth",
      "Inverting a major third produces a minor sixth; as a general rule, inverting an interval changes major to minor (and vice versa) while the interval numbers sum to nine (3 + 6 = 9)."),
  _q("When a perfect fifth is inverted, it becomes a",
      ["perfect fourth", "perfect fourth diminished", "major fourth", "minor fifth"], "perfect fourth",
      "Inverting a perfect fifth produces a perfect fourth; perfect intervals remain perfect when inverted, with the interval numbers summing to nine (5 + 4 = 9)."),
];

final _chordsAndHarmony = [
  _q("A triad in root position consists of",
      ["a root note, a third above it, and a fifth above the root, stacked in that order", "four notes stacked in thirds", "only two notes played together", "a root note repeated three times at different octaves"], "a root note, a third above it, and a fifth above the root, stacked in that order",
      "A triad in root position is built with the root note as the lowest note, followed by the third and fifth stacked above it in ascending order."),
  _q("A major triad is built using which combination of intervals from the root?",
      ["A major third followed by a minor third", "A minor third followed by a major third", "Two major thirds", "Two minor thirds"], "A major third followed by a minor third",
      "A major triad consists of a major third between the root and third, and a minor third between the third and fifth, giving it its characteristic bright sound."),
  _q("A minor triad is built using which combination of intervals from the root?",
      ["A minor third followed by a major third", "A major third followed by a minor third", "Two major thirds", "Two minor thirds"], "A minor third followed by a major third",
      "A minor triad consists of a minor third between the root and third, and a major third between the third and fifth, giving it its characteristic darker sound."),
  _q("A dominant seventh chord is built by adding which interval to a major triad?",
      ["A minor seventh above the root", "A major seventh above the root", "A perfect fifth above the root", "An octave above the root"], "A minor seventh above the root",
      "A dominant seventh chord adds a minor seventh interval above the root to a major triad, creating the characteristic tension associated with dominant harmony."),
  _q("A perfect cadence (authentic cadence) in music harmony typically involves the chord progression",
      ["V to I (dominant to tonic)", "IV to I (subdominant to tonic)", "I to V (tonic to dominant)", "ii to V (supertonic to dominant)"], "V to I (dominant to tonic)",
      "A perfect (authentic) cadence moves from the dominant (V) chord to the tonic (I) chord, creating a strong, conclusive sense of resolution."),
  _q("An imperfect cadence in music harmony typically ends on which chord?",
      ["The dominant (V) chord", "The tonic (I) chord", "The subdominant (IV) chord only", "The submediant (vi) chord only"], "The dominant (V) chord",
      "An imperfect cadence ends on the dominant (V) chord, creating a sense of being unresolved or 'left hanging', in contrast to the resolution of a perfect cadence."),
  _q("A plagal cadence in music harmony typically involves the chord progression",
      ["IV to I (subdominant to tonic)", "V to I (dominant to tonic)", "I to V (tonic to dominant)", "V to vi (dominant to submediant)"], "IV to I (subdominant to tonic)",
      "A plagal cadence moves from the subdominant (IV) chord to the tonic (I) chord, often referred to as the 'Amen cadence' due to its common use at the end of hymns."),
  _q("An interrupted cadence in music harmony typically involves the chord progression",
      ["V to vi (dominant to submediant), deceiving the expected resolution to the tonic", "V to I (dominant to tonic)", "IV to I (subdominant to tonic)", "I to IV (tonic to subdominant)"], "V to vi (dominant to submediant), deceiving the expected resolution to the tonic",
      "An interrupted (deceptive) cadence resolves the dominant (V) chord to the submediant (vi) instead of the expected tonic (I), creating a surprising, unresolved effect."),
  _q("Four-part harmony writing in Western music traditionally refers to arranging music for which four voice parts?",
      ["Soprano, Alto, Tenor, and Bass (SATB)", "Soprano, Mezzo-soprano, Tenor, and Baritone", "Alto, Tenor, Baritone, and Bass", "Soprano, Alto, Baritone, and Bass"], "Soprano, Alto, Tenor, and Bass (SATB)",
      "Four-part harmony, common in choral and hymn writing, is traditionally arranged for Soprano, Alto, Tenor, and Bass (SATB) voice parts."),
  _q("In four-part harmony writing, parallel fifths and parallel octaves between voices are generally",
      ["avoided, as they can weaken the independence of the individual voice parts", "required in every single chord progression", "the primary goal of harmonic writing", "irrelevant to voice leading considerations"], "avoided, as they can weaken the independence of the individual voice parts",
      "Traditional voice-leading rules in four-part harmony discourage parallel fifths and octaves between voices, as they can diminish the sense of independent melodic movement in each part."),
  _q("A dominant seventh chord is built on which scale degree of a key?",
      ["The fifth degree (dominant)", "The first degree (tonic)", "The fourth degree (subdominant)", "The sixth degree (submediant)"], "The fifth degree (dominant)",
      "The dominant seventh chord is constructed on the fifth scale degree of a key, combining the dominant triad with an added minor seventh, and typically resolves to the tonic."),
  _q("A cadence in music refers to",
      ["a harmonic progression that creates a sense of resolution or closure at the end of a musical phrase", "the tempo marking at the beginning of a piece", "the specific instrument used to perform a piece", "the dynamic level of a passage"], "a harmonic progression that creates a sense of resolution or closure at the end of a musical phrase",
      "A cadence is a chord progression that concludes a musical phrase or section, providing varying degrees of resolution or continuation depending on its type."),
  _q("Which of the following triads would be built on the tonic (I) of a major key?",
      ["A major triad", "A diminished triad", "An augmented triad exclusively", "A triad with no third"], "A major triad",
      "In a major key, the tonic (I) chord is naturally a major triad, built using the scale's own major third and perfect fifth above the tonic note."),
];

final _westernArtMusicEras = [
  _q("The Medieval period of Western art music history is generally associated with",
      ["early Christian liturgical music, including Gregorian chant", "the emergence of the symphony orchestra", "the invention of the piano", "the rise of jazz and blues"], "early Christian liturgical music, including Gregorian chant",
      "The Medieval period, the earliest era of Western art music history, is closely associated with monophonic sacred music, particularly Gregorian chant used in Christian liturgy."),
  _q("The Renaissance period of Western art music is generally characterised by",
      ["the increasing use of polyphony (multiple independent melodic lines) in both sacred and secular music", "the exclusive use of electronic instruments", "the invention of the modern symphony orchestra", "the dominance of atonal composition techniques"], "the increasing use of polyphony (multiple independent melodic lines) in both sacred and secular music",
      "The Renaissance era saw significant development of polyphonic textures, with multiple independent vocal or instrumental lines woven together in both sacred choral music and secular songs."),
  _q("Johann Sebastian Bach, a major composer of the Baroque period, is particularly renowned for his mastery of",
      ["complex counterpoint and fugue composition", "atonal twelve-tone composition", "electronic music production", "the invention of jazz improvisation"], "complex counterpoint and fugue composition",
      "Bach is celebrated as one of history's greatest masters of counterpoint, particularly in his fugues, which weave multiple independent melodic lines together with remarkable complexity and skill."),
  _q("George Frideric Handel, another major composer of the Baroque period, is particularly renowned for his",
      ["oratorios, including the famous work 'Messiah'", "invention of the modern piano", "compositions for electronic synthesizer", "development of twelve-tone technique"], "oratorios, including the famous work 'Messiah'",
      "Handel is especially celebrated for his oratorios, most famously 'Messiah', which remains one of the most frequently performed choral works in Western classical music."),
  _q("The Classical period of Western art music, following the Baroque era, is particularly associated with which composers?",
      ["Haydn, Mozart, and Beethoven (early works)", "Bach and Handel exclusively", "Chopin and Schubert exclusively", "Only 20th-century composers"], "Haydn, Mozart, and Beethoven (early works)",
      "The Classical period is closely associated with Joseph Haydn, Wolfgang Amadeus Mozart, and the early compositional output of Ludwig van Beethoven, emphasising clarity, balance, and formal structure."),
  _q("The Classical period of Western music, compared to the Baroque period, is generally characterised by",
      ["simpler, clearer melodic lines and more balanced formal structures", "much denser and more complex counterpoint than the Baroque", "the exclusive use of electronic instruments", "the complete absence of any melody"], "simpler, clearer melodic lines and more balanced formal structures",
      "The Classical era favoured clearer, more homophonic textures with balanced phrase structures, contrasting with the denser contrapuntal complexity often found in Baroque music."),
  _q("Franz Schubert, a prominent composer of the Romantic period, is particularly renowned for his contributions to the genre of",
      ["the art song (Lied)", "the twelve-tone technique", "electronic music", "traditional African drumming"], "the art song (Lied)",
      "Schubert is especially celebrated for his mastery of the German art song (Lied), setting poetry to expressive vocal melodies accompanied by piano."),
  _q("Frederic Chopin, another prominent composer of the Romantic period, is particularly renowned for his compositions for",
      ["solo piano", "full symphony orchestra exclusively", "unaccompanied choir exclusively", "electronic synthesizer"], "solo piano",
      "Chopin is celebrated almost exclusively for his substantial and influential body of solo piano works, including nocturnes, etudes, and mazurkas."),
  _q("The Romantic period of Western art music, compared to the Classical period, is generally characterised by",
      ["greater emotional expressiveness, expanded harmonic language, and larger orchestral forces", "simpler, more restrained emotional expression", "the complete rejection of melody", "exclusive use of a cappella vocal music"], "greater emotional expressiveness, expanded harmonic language, and larger orchestral forces",
      "The Romantic era emphasised heightened emotional expression, more adventurous harmony, and often larger orchestral ensembles compared to the more restrained Classical period."),
  _q("The Modern period of Western art music, generally spanning the 20th century onward, is characterised by",
      ["significant experimentation with new harmonic, rhythmic, and structural approaches, including atonality", "a strict return to only Medieval compositional techniques", "the complete absence of any musical innovation", "exclusive reliance on Baroque-era forms"], "significant experimentation with new harmonic, rhythmic, and structural approaches, including atonality",
      "The Modern period is marked by extensive musical experimentation, including atonality, new rhythmic structures, and innovative approaches that broke from traditional tonal harmony."),
  _q("Which of the following correctly orders the major Western art music eras chronologically, from earliest to most recent?",
      ["Medieval, Renaissance, Baroque, Classical, Romantic, Modern", "Baroque, Medieval, Classical, Renaissance, Modern, Romantic", "Modern, Romantic, Classical, Baroque, Renaissance, Medieval", "Classical, Baroque, Medieval, Renaissance, Romantic, Modern"], "Medieval, Renaissance, Baroque, Classical, Romantic, Modern",
      "The standard chronological sequence of major Western art music eras is Medieval, Renaissance, Baroque, Classical, Romantic, and Modern."),
  _q("The fugue, a significant compositional form of the Baroque period, is characterised by",
      ["a single melodic theme (subject) introduced and imitated across multiple independent voices", "a single unaccompanied melody with no imitation", "purely improvised music with no set structure", "music composed for electronic instruments only"], "a single melodic theme (subject) introduced and imitated across multiple independent voices",
      "A fugue develops a central musical theme (the subject) by introducing it successively in different voices, which imitate and interweave with one another in intricate counterpoint."),
  _q("The symphony, a major musical form especially prominent in the Classical and Romantic periods, is typically written for",
      ["a full orchestra, usually in multiple movements", "a solo unaccompanied instrument", "unaccompanied vocal choir only", "electronic synthesizer only"], "a full orchestra, usually in multiple movements",
      "A symphony is a substantial orchestral work typically composed in several movements, showcasing the combined forces and varied timbres of a full orchestra."),
  _q("Ludwig van Beethoven is historically significant partly because his compositional style is often seen as",
      ["bridging the Classical and Romantic periods", "belonging exclusively to the Baroque period", "belonging exclusively to the Modern period", "having no historical significance"], "bridging the Classical and Romantic periods",
      "Beethoven's early works reflect Classical-era conventions, while his later compositions display increasingly Romantic characteristics, making him a pivotal transitional figure between the two eras."),
  _q("Gregorian chant, a hallmark of Medieval sacred music, is characterised by",
      ["monophonic (single melodic line) vocal music, typically unaccompanied and used in Christian liturgy", "complex four-part harmony with orchestral accompaniment", "purely instrumental music with no vocal component", "electronic sound synthesis"], "monophonic (single melodic line) vocal music, typically unaccompanied and used in Christian liturgy",
      "Gregorian chant consists of a single, unaccompanied melodic line (monophony), traditionally sung in Latin as part of Christian liturgical worship during the Medieval period."),
  _q("Which of the following composers is most closely associated with the Classical period's development of the symphony and string quartet, earning him the nickname 'Father of the Symphony'?",
      ["Joseph Haydn", "Johann Sebastian Bach", "Frederic Chopin", "Franz Schubert"], "Joseph Haydn",
      "Joseph Haydn made such extensive and influential contributions to the development of the symphony and string quartet forms that he earned the honorific title 'Father of the Symphony'."),
];

final _africanTraditionalMusic = [
  _q("Idiophones, a category of traditional African musical instruments, are instruments that produce sound primarily by",
      ["the vibration of the instrument's own body, such as when struck, shaken, or scraped", "the vibration of a stretched membrane", "the vibration of a stretched string", "the vibration of air within a tube"], "the vibration of the instrument's own body, such as when struck, shaken, or scraped",
      "Idiophones generate sound through the vibration of the instrument's own solid material, as in instruments like bells, rattles, and xylophones, without needing strings, membranes, or air columns."),
  _q("Aerophones, another category of traditional African musical instruments, are instruments that produce sound primarily through",
      ["vibrating columns of air, as in flutes and horns", "the vibration of a stretched membrane", "the vibration of the instrument's own solid body", "the vibration of a stretched string"], "vibrating columns of air, as in flutes and horns",
      "Aerophones produce sound through the vibration of air, typically within a tube or chamber, as found in wind instruments such as flutes, horns, and whistles."),
  _q("Chordophones, another category of traditional African musical instruments, are instruments that produce sound primarily through",
      ["the vibration of stretched strings, as in the kora or musical bow", "the vibration of a stretched membrane", "the vibration of the instrument's own solid body", "vibrating columns of air"], "the vibration of stretched strings, as in the kora or musical bow",
      "Chordophones generate sound through the vibration of one or more stretched strings, as seen in traditional African instruments like the kora and various musical bows."),
  _q("Membranophones, another category of traditional African musical instruments, are instruments that produce sound primarily through",
      ["the vibration of a stretched membrane, as in drums", "the vibration of stretched strings", "vibrating columns of air", "the vibration of the instrument's own solid body"], "the vibration of a stretched membrane, as in drums",
      "Membranophones produce sound through the vibration of a stretched membrane (skin or similar material) typically stretched over a frame or shell, as in various types of drums."),
  _q("In traditional African society, music commonly serves functions beyond entertainment, including",
      ["communication, storytelling, religious/ritual practice, and marking important life events", "purely decorative purposes with no social function", "exclusively commercial entertainment for profit", "no function beyond simple background noise"], "communication, storytelling, religious/ritual practice, and marking important life events",
      "Traditional African music serves multiple important social functions, including communication (e.g., talking drums), storytelling, religious and ceremonial practices, and marking significant life events such as births, marriages, and funerals."),
  _q("Call-and-response, a common structural element in African traditional music, involves",
      ["a leader singing or playing a phrase, which is then answered by a group or chorus", "a single performer playing an entire piece with no interaction", "purely instrumental music with no vocal element at all", "simultaneous, unrelated performances by multiple unconnected groups"], "a leader singing or playing a phrase, which is then answered by a group or chorus",
      "Call-and-response is a foundational structural technique in African music, where a lead singer or instrumentalist presents a musical phrase that is answered or echoed by a group, creating an interactive musical dialogue."),
  _q("Polyrhythm, a significant structural element in African traditional music, refers to",
      ["the simultaneous combination of two or more contrasting rhythmic patterns", "the use of only a single, unchanging rhythm throughout a piece", "the complete absence of any rhythmic structure", "a rhythm played by only one instrument at a time"], "the simultaneous combination of two or more contrasting rhythmic patterns",
      "Polyrhythm involves layering multiple distinct rhythmic patterns simultaneously, creating rich, complex rhythmic textures characteristic of much traditional African music."),
  _q("The talking drum, a notable African membranophone, is particularly significant for its ability to",
      ["mimic the tonal patterns of spoken language, allowing it to convey messages", "produce only a single fixed pitch with no variation", "function exclusively as a stringed instrument", "produce sound without being struck or played"], "mimic the tonal patterns of spoken language, allowing it to convey messages",
      "The talking drum's pitch can be varied by squeezing the cords or strings attached to its membrane, allowing skilled players to imitate the tonal patterns of spoken language and communicate specific messages."),
  _q("The xylophone, a common idiophone found in various African musical traditions, produces different pitches by",
      ["using wooden bars of varying lengths, which are struck to produce different pitches", "stretching strings of varying tension", "blowing air through tubes of varying length", "stretching a membrane of varying tightness"], "using wooden bars of varying lengths, which are struck to produce different pitches",
      "Xylophones use a series of wooden bars of differing lengths (and often differing thicknesses), each producing a distinct pitch when struck, typically arranged in a scale."),
  _q("The kora, a notable West African chordophone, is best described as a",
      ["21-string harp-lute, traditionally played by griots (jelis) in West Africa", "type of drum found in East Africa", "wind instrument made from animal horn", "wooden xylophone with metal keys"], "21-string harp-lute, traditionally played by griots (jelis) in West Africa",
      "The kora is a distinctive 21-string instrument combining features of a harp and lute, traditionally played by West African griots (jelis) who serve as musician-historians and storytellers."),
  _q("Griots (jelis), found in various West African cultures, traditionally serve as",
      ["musician-historians who preserve and transmit oral history and genealogy through music", "purely instrument makers with no performance role", "religious leaders exclusively, with no musical role", "government tax collectors"], "musician-historians who preserve and transmit oral history and genealogy through music",
      "Griots hold a specialised hereditary role as musician-historians, using song and instrumental accompaniment (often the kora) to preserve and pass down oral history, genealogy, and cultural knowledge."),
  _q("Which of the following best describes the role of drumming ensembles in many traditional African communities?",
      ["Providing rhythmic accompaniment for dance, ritual, and communal social occasions", "Serving purely as background noise with no social significance", "Being restricted exclusively to private, solitary performance", "Functioning only as a form of punishment"], "Providing rhythmic accompaniment for dance, ritual, and communal social occasions",
      "Drumming ensembles play a central role in African communal life, providing essential rhythmic accompaniment for dances, rituals, celebrations, and various important social occasions."),
  _q("In African traditional music, the concept of 'community participation' is often reflected through",
      ["call-and-response structures that actively involve the audience or group in the performance", "music performed exclusively by a single isolated musician with no audience involvement", "recorded music with no live performance element", "music that discourages any form of audience interaction"], "call-and-response structures that actively involve the audience or group in the performance",
      "Many African musical traditions emphasise communal participation, with call-and-response structures actively drawing the audience or community into the musical performance rather than positioning them as passive listeners."),
  _q("Which classification best describes a set of tuned drums or a marimba-like instrument struck to produce different pitches?",
      ["Idiophone", "Aerophone", "Chordophone", "Membranophone"], "Idiophone",
      "Instruments like tuned drums, xylophones, and marimbas that produce sound through the vibration of their own solid material when struck are classified as idiophones."),
];

final _nigerianArtMusicAndMusicians = [
  _q("Fela Sowande, a pioneering figure in Nigerian art music, is particularly recognised for",
      ["combining Western classical compositional techniques with traditional Yoruba musical elements", "founding the Fuji music genre", "pioneering Nigerian reggae music", "inventing the talking drum"], "combining Western classical compositional techniques with traditional Yoruba musical elements",
      "Fela Sowande is celebrated as a pioneering Nigerian composer who skilfully blended Western classical music training with traditional Yoruba musical idioms, helping establish modern Nigerian art music."),
  _q("Harcourt Whyte, another pioneering figure in Nigerian art music, is particularly recognised for his contributions to",
      ["Nigerian choral music composition", "the development of Afrobeat", "the invention of the kora", "pioneering Nigerian Fuji music"], "Nigerian choral music composition",
      "Harcourt Whyte made significant contributions to Nigerian choral music, composing numerous choral works that have become important parts of the Nigerian art music repertoire."),
  _q("Akin Euba, another significant figure in Nigerian art music, is particularly known for developing the concept of",
      ["'African pianism', integrating African musical elements into piano composition", "Fuji music", "Afrobeat", "the talking drum tradition"], "'African pianism', integrating African musical elements into piano composition",
      "Akin Euba is recognised for pioneering the concept of 'African pianism', a compositional approach that incorporates traditional African musical characteristics, such as rhythmic complexity, into piano music."),
  _q("Laz Ekwueme, another notable figure in Nigerian art music, is particularly recognised as a",
      ["prominent composer, musicologist, and choral conductor", "pioneer of Nigerian Afrobeat music", "inventor of the Fuji music genre", "founder of Nigerian reggae"], "prominent composer, musicologist, and choral conductor",
      "Laz Ekwueme made substantial contributions to Nigerian art music as a composer, respected musicologist, and accomplished choral conductor."),
  _q("Nigerian art music, as pioneered by figures like Fela Sowande and Akin Euba, is generally characterised by",
      ["the fusion of Western classical compositional techniques with indigenous Nigerian musical elements", "the complete rejection of any Western musical influence", "an exclusive focus on unaccompanied vocal music", "the exclusive use of electronic instruments"], "the fusion of Western classical compositional techniques with indigenous Nigerian musical elements",
      "Nigerian art music is generally defined by its thoughtful integration of Western classical compositional methods with indigenous Nigerian melodic, rhythmic, and cultural elements."),
  _q("Which of the following best describes the significance of pioneers like Fela Sowande and Harcourt Whyte to Nigerian music history?",
      ["They helped establish and legitimise a distinctly Nigerian tradition of composed art music", "They had no lasting impact on Nigerian music", "They exclusively performed traditional folk music with no innovation", "They focused solely on popular dance music"], "They helped establish and legitimise a distinctly Nigerian tradition of composed art music",
      "These pioneering figures played a foundational role in establishing a respected tradition of Nigerian art music, demonstrating how indigenous musical elements could be thoughtfully combined with formal compositional techniques."),
  _q("Choral music has played a particularly significant role in Nigerian art music, notably advanced through the work of",
      ["Harcourt Whyte and Laz Ekwueme", "Fela Kuti exclusively", "King Sunny Ade exclusively", "Ebenezer Obey exclusively"], "Harcourt Whyte and Laz Ekwueme",
      "Choral composition has been a particularly significant strand of Nigerian art music, with figures like Harcourt Whyte and Laz Ekwueme making substantial contributions to this tradition."),
  _q("The concept of 'African pianism', associated with Akin Euba, specifically involves",
      ["adapting African rhythmic and melodic characteristics for solo piano composition", "abandoning the piano entirely in favour of traditional instruments", "composing exclusively for orchestra with no piano involvement", "using only Western classical piano techniques with no African influence"], "adapting African rhythmic and melodic characteristics for solo piano composition",
      "African pianism represents a deliberate compositional approach that translates distinctly African musical characteristics, such as complex rhythms and melodic patterns, into piano repertoire."),
  _q("Nigerian art music composers generally sought to demonstrate that",
      ["indigenous Nigerian musical traditions could be meaningfully expressed through formal, composed musical structures", "traditional Nigerian music had no artistic value", "only Western musical traditions were worth studying", "composed music was incompatible with African musical heritage"], "indigenous Nigerian musical traditions could be meaningfully expressed through formal, composed musical structures",
      "A central achievement of Nigerian art music pioneers was demonstrating that indigenous musical traditions and formal compositional techniques could be successfully and meaningfully combined."),
  _q("Which of the following musicians is most closely associated with pioneering choral compositions that incorporate traditional Igbo musical elements?",
      ["Harcourt Whyte", "Fela Sowande", "Akin Euba", "King Sunny Ade"], "Harcourt Whyte",
      "Harcourt Whyte, of Igbo heritage, is particularly noted for choral compositions that draw on traditional Igbo musical elements within a Western choral framework."),
  _q("The academic study and documentation of Nigerian music, advanced by figures such as Laz Ekwueme, is best described as",
      ["musicology, the scholarly study of music", "purely performance-based training with no scholarly component", "a field unrelated to music entirely", "exclusively focused on popular music charts"], "musicology, the scholarly study of music",
      "Musicology involves the scholarly, academic study of music, including its history, theory, and cultural context — a field to which figures like Laz Ekwueme made significant contributions in the Nigerian context."),
  _q("Which best describes the broader significance of studying Nigerian art music and its pioneers within the JAMB Music syllabus?",
      ["It helps students appreciate the historical development and richness of formally composed Nigerian music alongside Western and traditional African music", "It focuses exclusively on foreign musical traditions with no relevance to Nigeria", "It has no connection to the broader history of music", "It is limited only to popular music genres"], "It helps students appreciate the historical development and richness of formally composed Nigerian music alongside Western and traditional African music",
      "Studying Nigerian art music and its pioneering figures gives students a fuller appreciation of the rich, diverse musical heritage of Nigeria, situated alongside Western art music and traditional African music traditions."),
];

final _popularMusic = [
  _q("Highlife, a popular Nigerian and Ghanaian music genre, developed with significant influence from",
      ["Western dance band instrumentation blended with indigenous West African rhythms and melodies", "purely traditional Nigerian drumming with no Western influence", "American country music", "Indian classical music"], "Western dance band instrumentation blended with indigenous West African rhythms and melodies",
      "Highlife emerged in West Africa through the fusion of Western instruments and dance band formats (such as guitars and horns) with indigenous West African melodic and rhythmic sensibilities."),
  _q("Juju music, a popular Nigerian music genre, is particularly associated with the prominent use of",
      ["the talking drum and electric guitar, blended with Yoruba musical traditions", "electronic synthesizers exclusively, with no traditional instruments", "orchestral strings exclusively", "bagpipes and traditional Scottish instruments"], "the talking drum and electric guitar, blended with Yoruba musical traditions",
      "Juju music is characterised by its distinctive combination of the talking drum and electric guitar, rooted in Yoruba musical traditions, popularised by artists such as King Sunny Ade."),
  _q("Fuji music, a popular Nigerian music genre, evolved significantly from",
      ["Yoruba Muslim 'were' (wake-up call) music traditionally performed during Ramadan", "Western classical opera", "American jazz exclusively", "Nigerian art music composed by Fela Sowande"], "Yoruba Muslim 'were' (wake-up call) music traditionally performed during Ramadan",
      "Fuji music traces its roots to the traditional Yoruba Muslim 'were' music, historically performed to wake worshippers for pre-dawn meals during Ramadan, later evolving into a distinct popular genre."),
  _q("Afrobeat, a popular Nigerian music genre, was significantly pioneered by",
      ["Fela Anikulapo Kuti, combining highlife, jazz, funk, and traditional African rhythms with socio-political lyrics", "King Sunny Ade exclusively", "Bob Marley", "Harcourt Whyte"], "Fela Anikulapo Kuti, combining highlife, jazz, funk, and traditional African rhythms with socio-political lyrics",
      "Fela Anikulapo Kuti is widely credited as the pioneering figure of Afrobeat, blending highlife, jazz, funk, and traditional African rhythmic elements with strongly socio-politically charged lyrics."),
  _q("Reggae music, though originating in Jamaica rather than Nigeria, is characterised musically by",
      ["a distinctive offbeat rhythm guitar pattern (the 'skank') and a relaxed tempo", "a strict, fast-paced marching band rhythm", "purely orchestral instrumentation with no guitar or bass", "the complete absence of any rhythmic pulse"], "a distinctive offbeat rhythm guitar pattern (the 'skank') and a relaxed tempo",
      "Reggae is musically defined by its characteristic offbeat guitar/keyboard rhythm pattern (often called the 'skank') and typically relaxed, moderate tempo."),
  _q("Which of the following musicians is most closely associated with the popularisation of Juju music internationally?",
      ["King Sunny Ade", "Fela Kuti", "Bob Marley", "Ebenezer Obey (alongside Sunny Ade, but the most internationally recognised pioneer is Ade)"], "King Sunny Ade",
      "King Sunny Ade is widely recognised as one of the most internationally successful and influential pioneers in popularising Juju music beyond Nigeria."),
  _q("Which of the following best describes a defining lyrical characteristic of Fela Kuti's Afrobeat music?",
      ["Strong socio-political commentary, often criticising government corruption and social injustice", "Purely romantic love songs with no social commentary", "Lyrics focused exclusively on religious worship", "Instrumental music with no lyrics at all"], "Strong socio-political commentary, often criticising government corruption and social injustice",
      "Fela Kuti's Afrobeat is particularly renowned for its bold socio-political lyrical content, frequently criticising government corruption, social injustice, and other pressing societal issues."),
  _q("Highlife music, as a genre, is generally distinguished from Fuji music mainly by its",
      ["strong incorporation of Western dance band instruments, such as guitars, horns, and drum kits", "complete reliance on unaccompanied vocal chanting only", "origins specifically tied to Islamic religious practice", "use exclusively of electronic synthesizers"], "strong incorporation of Western dance band instruments, such as guitars, horns, and drum kits",
      "Unlike Fuji's roots in Yoruba Muslim wake-up call traditions and largely percussion-based instrumentation, highlife prominently incorporates Western dance band instruments like guitars, horns, and drum kits."),
  _q("Bob Marley, a pioneering figure of reggae music, played a significant role in",
      ["popularising reggae music internationally and infusing it with messages of social justice and Rastafarian spirituality", "founding the Nigerian Afrobeat genre", "pioneering Nigerian Fuji music", "composing Nigerian art music choral works"], "popularising reggae music internationally and infusing it with messages of social justice and Rastafarian spirituality",
      "Bob Marley was instrumental in bringing reggae music to a global audience, infusing his music with themes of social justice, resistance, and Rastafarian spiritual beliefs."),
  _q("The evolution of popular Nigerian music genres like Highlife, Juju, Fuji, and Afrobeat generally reflects",
      ["the creative blending of indigenous Nigerian musical traditions with various external musical influences over time", "a complete rejection of any traditional Nigerian musical elements", "an exclusive reliance on foreign musical styles with no indigenous input", "the total absence of any historical development or change"], "the creative blending of indigenous Nigerian musical traditions with various external musical influences over time",
      "The development of these popular Nigerian genres illustrates a recurring pattern of creatively fusing indigenous musical traditions with external influences (Western instrumentation, jazz, funk, etc.) to produce distinctive new styles."),
  _q("Which popular music genre is most closely linked historically to Yoruba Islamic religious practices during the fasting month of Ramadan?",
      ["Fuji", "Reggae", "Highlife", "Afrobeat"], "Fuji",
      "Fuji music has its historical roots specifically in the Yoruba Muslim 'were' tradition of waking worshippers for pre-dawn meals during Ramadan, distinguishing its origin from the other listed genres."),
  _q("Ebenezer Obey, alongside King Sunny Ade, is a significant figure closely associated with which popular Nigerian music genre?",
      ["Juju music", "Fuji music", "Afrobeat", "Reggae"], "Juju music",
      "Ebenezer Obey, together with King Sunny Ade, is widely recognised as one of the most influential and successful pioneers of Juju music in Nigeria."),
];
