import "../quiz_question.dart";

const _subject = "Biology";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// JAMB Biology — 100 questions covering the JAMB UTME breakdown: Living
/// Organisms, Form and Functions (the largest section, spanning nutrition,
/// transport, respiration, excretion, support/movement, and control),
/// Homeostasis, Reproduction, Genetics and Heredity, Ecology and
/// Environment, and Evolution. Built separately from the shared WAEC-based
/// Biology bank because it follows JAMB's own topic weighting (notably
/// Homeostasis and Evolution, which the WAEC bank does not emphasise).
List<QuizQuestion> buildJambBiologyQuestions() {
  return [
    ..._livingOrganisms,
    ..._formAndFunctions,
    ..._homeostasis,
    ..._reproduction,
    ..._geneticsHeredity,
    ..._ecologyEnvironment,
    ..._evolution,
  ];
}

final _livingOrganisms = [
  _q("Which of the following is NOT one of the seven characteristics of living things?",
      ["Crystallization", "Reproduction", "Irritability", "Excretion"], "Crystallization",
      "The recognised characteristics of life are nutrition, respiration, excretion, growth, reproduction, irritability, and movement; crystallization is a physical, non-living process."),
  _q("The basic structural and functional unit of all living organisms is the",
      ["cell", "tissue", "organ", "system"], "cell",
      "The cell theory establishes the cell as the smallest unit capable of carrying out all life processes independently."),
  _q("Which organelle is described as the 'powerhouse of the cell' because it is the site of aerobic respiration?",
      ["Mitochondrion", "Nucleus", "Ribosome", "Golgi apparatus"], "Mitochondrion",
      "Mitochondria contain the enzymes for the Krebs cycle and electron transport chain, generating most of a cell's ATP through aerobic respiration."),
  _q("Which structure is present in a plant cell but absent in an animal cell?",
      ["Cell wall", "Nucleus", "Cell membrane", "Mitochondrion"], "Cell wall",
      "Plant cells have a rigid cellulose cell wall external to the cell membrane, providing shape and support, which animal cells lack."),
  _q("The correct order of increasing complexity in the organization of living matter is",
      ["cell, tissue, organ, system", "tissue, cell, system, organ", "organ, tissue, cell, system", "system, organ, cell, tissue"], "cell, tissue, organ, system",
      "Cells group into tissues, tissues combine to form organs, and organs work together as systems, representing increasing levels of biological organization."),
  _q("Which kingdom includes organisms that are prokaryotic, unicellular, and lack a true nucleus?",
      ["Monera", "Fungi", "Protista", "Plantae"], "Monera",
      "Kingdom Monera comprises bacteria and cyanobacteria, whose cells are prokaryotic, lacking a membrane-bound nucleus and other organelles."),
  _q("Fungi differ from green plants mainly in that fungi",
      ["lack chlorophyll and cannot photosynthesise", "have cell walls made of cellulose", "are always unicellular", "carry out photosynthesis in chloroplasts"], "lack chlorophyll and cannot photosynthesise",
      "Fungi are heterotrophic, absorbing nutrients from organic matter, since they lack chlorophyll and the chloroplasts needed for photosynthesis."),
  _q("The chloroplast, found in green plant cells, is the site of",
      ["photosynthesis", "aerobic respiration", "protein synthesis", "waste excretion"], "photosynthesis",
      "Chloroplasts contain chlorophyll pigments that trap light energy, driving the photosynthetic conversion of carbon dioxide and water into glucose and oxygen."),
  _q("Which cell organelle controls the cell's activities and contains the hereditary material?",
      ["Nucleus", "Cytoplasm", "Vacuole", "Cell membrane"], "Nucleus",
      "The nucleus houses the chromosomes (DNA), directing protein synthesis and cellular activity, and is often called the control centre of the cell."),
  _q("Binomial nomenclature, the scientific naming system for organisms, was introduced by",
      ["Carl Linnaeus", "Charles Darwin", "Gregor Mendel", "Robert Hooke"], "Carl Linnaeus",
      "Carl Linnaeus developed the two-name (genus and species) system of naming organisms, still used in modern taxonomy."),
  _q("Which taxonomic rank groups together organisms of similar genera?",
      ["Family", "Species", "Kingdom", "Phylum"], "Family",
      "Taxonomic hierarchy from broadest to narrowest is Kingdom, Phylum, Class, Order, Family, Genus, Species; a family groups related genera."),
  _q("The cell membrane's main function is to",
      ["regulate the movement of substances into and out of the cell", "manufacture proteins", "store genetic material", "carry out photosynthesis"], "regulate the movement of substances into and out of the cell",
      "The selectively permeable cell membrane controls which substances enter or leave the cell, maintaining internal homeostasis."),
  _q("Which of the following best defines a tissue?",
      ["A group of similar cells performing a specific function", "A single cell performing all life functions", "A group of different organs working together", "The outer covering of an organism"], "A group of similar cells performing a specific function",
      "A tissue is an organized group of structurally similar cells that work together to carry out one or more specific functions, such as muscle tissue contracting."),
  _q("Ribosomes in a cell are mainly responsible for",
      ["protein synthesis", "energy production", "waste storage", "photosynthesis"], "protein synthesis",
      "Ribosomes translate messenger RNA into polypeptide chains, making them the site of protein synthesis in both prokaryotic and eukaryotic cells."),
];

final _formAndFunctions = [
  _q("In a dicotyledonous root, the region responsible for absorbing water and mineral salts is the",
      ["root hair zone", "region of elongation", "root cap", "meristematic zone"], "root hair zone",
      "Root hairs greatly increase the surface area of the epidermis in the root hair (piliferous) zone, maximising water and mineral ion absorption."),
  _q("The main function of the xylem tissue in a flowering plant is to",
      ["conduct water and dissolved mineral salts upward from the root", "conduct manufactured food from the leaves to other parts", "carry out photosynthesis", "store excess starch"], "conduct water and dissolved mineral salts upward from the root",
      "Xylem vessels are dead, lignified tubes that transport water and dissolved minerals from roots to the rest of the plant, and also provide structural support."),
  _q("Phloem tissue is primarily responsible for",
      ["translocation of manufactured food (mainly sucrose) from the leaves to other parts", "transport of water from roots to leaves", "gaseous exchange in the leaf", "absorption of water from the soil"], "translocation of manufactured food (mainly sucrose) from the leaves to other parts",
      "Phloem, composed of living sieve tubes and companion cells, translocates organic food substances made in the leaves to storage organs and growing regions."),
  _q("Which mammalian organ system is responsible for pumping blood around the body?",
      ["Circulatory system (heart)", "Respiratory system", "Digestive system", "Excretory system"], "Circulatory system (heart)",
      "The heart, the central pumping organ of the circulatory system, rhythmically contracts to propel blood through arteries, capillaries, and veins."),
  _q("Photosynthesis in green plants requires which combination of raw materials?",
      ["Carbon dioxide and water", "Oxygen and glucose", "Nitrogen and water", "Oxygen and carbon dioxide"], "Carbon dioxide and water",
      "The overall equation for photosynthesis is 6CO2 + 6H2O + light energy -> C6H12O6 + 6O2, requiring carbon dioxide and water as raw materials."),
  _q("Heterotrophic nutrition in which an organism lives in or on another living organism, deriving nutrients and causing it harm, is called",
      ["parasitic nutrition", "saprophytic nutrition", "holozoic nutrition", "autotrophic nutrition"], "parasitic nutrition",
      "Parasitic nutrition involves an organism (the parasite) obtaining nutrients from a living host, usually to the host's detriment, e.g., tapeworms in the human gut."),
  _q("Saprophytic nutrition involves an organism obtaining nutrients by",
      ["secreting enzymes onto dead organic matter and absorbing the digested products", "ingesting solid food and digesting it internally", "manufacturing its own food using light energy", "living inside a host and absorbing digested food directly"], "secreting enzymes onto dead organic matter and absorbing the digested products",
      "Saprophytes such as many fungi and bacteria carry out extracellular digestion, releasing enzymes onto dead matter and absorbing the soluble products."),
  _q("The mammalian tooth adapted for cutting and biting off food is the",
      ["incisor", "canine", "premolar", "molar"], "incisor",
      "Incisors are chisel-shaped teeth at the front of the jaw, adapted for cutting and biting food into manageable pieces."),
  _q("Canine teeth in carnivorous mammals are mainly adapted for",
      ["tearing and gripping flesh", "grinding and chewing plant material", "cutting food into pieces", "crushing bones only"], "tearing and gripping flesh",
      "Canines are pointed, conical teeth well adapted for piercing, gripping, and tearing flesh, especially prominent in carnivores."),
  _q("Which enzyme, present in saliva, begins the digestion of starch in the mouth?",
      ["Salivary amylase (ptyalin)", "Pepsin", "Lipase", "Trypsin"], "Salivary amylase (ptyalin)",
      "Salivary amylase hydrolyses starch into maltose, beginning carbohydrate digestion even before food reaches the stomach."),
  _q("Pepsin, a protein-digesting enzyme, is secreted in the",
      ["stomach", "mouth", "small intestine only", "large intestine"], "stomach",
      "Pepsin is secreted by gastric glands in the stomach and works optimally in the highly acidic environment created by hydrochloric acid."),
  _q("Which blood vessel carries oxygenated blood away from the heart to the rest of the body?",
      ["Aorta", "Vena cava", "Pulmonary artery", "Hepatic portal vein"], "Aorta",
      "The aorta is the largest artery, carrying oxygen-rich blood from the left ventricle of the heart to systemic circulation."),
  _q("Red blood cells (erythrocytes) are mainly responsible for",
      ["transporting oxygen bound to haemoglobin", "fighting infections", "clotting blood", "transporting digested food"], "transporting oxygen bound to haemoglobin",
      "Haemoglobin within red blood cells binds oxygen in the lungs and releases it to respiring tissues throughout the body."),
  _q("Which type of blood vessel has walls only one cell thick, allowing exchange of substances with tissues?",
      ["Capillary", "Artery", "Vein", "Aorta"], "Capillary",
      "Capillaries are the smallest blood vessels, with walls a single cell thick, permitting efficient diffusion of gases, nutrients, and wastes with surrounding tissues."),
  _q("Aerobic respiration differs from anaerobic respiration mainly in that aerobic respiration",
      ["requires oxygen and releases far more energy per glucose molecule", "does not require oxygen", "produces lactic acid as the main end-product in animals", "occurs only in plants"], "requires oxygen and releases far more energy per glucose molecule",
      "Aerobic respiration fully oxidises glucose using oxygen, yielding about 38 ATP molecules, far more than the 2 ATP from anaerobic respiration."),
  _q("In humans, anaerobic respiration in muscles during vigorous exercise produces",
      ["lactic acid", "ethanol and carbon dioxide", "large amounts of ATP", "oxygen"], "lactic acid",
      "When oxygen supply is insufficient during strenuous activity, muscle cells respire anaerobically, converting glucose to lactic acid and releasing a small amount of energy."),
  _q("The main respiratory organ in fish, adapted for extracting dissolved oxygen from water, is the",
      ["gill", "lung", "skin", "trachea"], "gill",
      "Fish gills have thin, highly vascularised filaments with a large surface area, adapted to extract dissolved oxygen efficiently from water."),
  _q("The main excretory product removed by the mammalian kidney is",
      ["urea", "glucose", "amino acids", "bile"], "urea",
      "The kidneys filter blood and excrete urea, the main nitrogenous waste product formed from the breakdown of excess amino acids in the liver."),
  _q("Which excretory structure is found in earthworms, functioning similarly to the vertebrate kidney?",
      ["Nephridium", "Malpighian tubule", "Kidney", "Contractile vacuole"], "Nephridium",
      "Nephridia are the excretory organs of earthworms and other annelids, filtering coelomic fluid and expelling nitrogenous waste."),
  _q("Malpighian tubules, the excretory organs of insects, empty their waste products into the",
      ["gut (alimentary canal)", "haemolymph directly", "trachea", "Malpighian body"], "gut (alimentary canal)",
      "Malpighian tubules extract nitrogenous waste from the haemolymph and discharge it into the gut, where it is eliminated with faeces."),
  _q("The skin contributes to excretion mainly by removing excess",
      ["water, salts, and urea in sweat", "carbon dioxide only", "glucose", "bile pigments"], "water, salts, and urea in sweat",
      "Sweat glands in the skin excrete water, dissolved salts, and small amounts of urea, also contributing to body temperature regulation."),
  _q("Which tissue provides mechanical support in the stems of herbaceous (non-woody) plants?",
      ["Collenchyma", "Xylem parenchyma only", "Phloem fibres only", "Epidermis"], "Collenchyma",
      "Collenchyma cells have unevenly thickened cellulose walls, providing flexible mechanical support especially in young, growing stems."),
  _q("An exoskeleton, as found in insects and crustaceans, is mainly composed of",
      ["chitin", "calcium phosphate", "cellulose", "keratin only"], "chitin",
      "The insect exoskeleton (cuticle) is composed mainly of chitin, a tough polysaccharide that provides protection and attachment points for muscles."),
  _q("Which type of joint permits movement in almost all directions, as found at the shoulder?",
      ["Ball-and-socket joint", "Hinge joint", "Fixed (immovable) joint", "Gliding joint"], "Ball-and-socket joint",
      "A ball-and-socket joint, where a rounded bone head fits into a cup-like socket, allows the widest range of movement, as at the shoulder and hip."),
  _q("A hinge joint, such as the elbow, permits movement",
      ["in one plane only, like a door hinge", "in all directions", "with no movement at all", "by rotation only"], "in one plane only, like a door hinge",
      "Hinge joints allow flexion and extension in a single plane, similar to the mechanical action of a door hinge, as seen at the elbow and knee."),
  _q("The basic functional unit of the nervous system, responsible for transmitting nerve impulses, is the",
      ["neuron", "nephron", "axon terminal only", "synapse only"], "neuron",
      "Neurons (nerve cells) are specialised to generate and conduct electrical impulses, forming the structural and functional basis of the nervous system."),
  _q("The part of the human eye that controls the amount of light entering the eye by adjusting the size of the pupil is the",
      ["iris", "retina", "cornea", "lens"], "iris",
      "The iris, a pigmented muscular diaphragm, contracts or relaxes to control pupil diameter and hence the amount of light reaching the retina."),
  _q("Light-sensitive cells that detect the image formed in the eye are located in the",
      ["retina", "cornea", "iris", "sclera"], "retina",
      "The retina contains photoreceptor cells (rods and cones) that convert light into nerve impulses sent to the brain via the optic nerve."),
  _q("Which part of the mammalian ear is primarily responsible for maintaining balance?",
      ["Semicircular canals", "Cochlea", "Eardrum (tympanic membrane)", "Pinna"], "Semicircular canals",
      "The three fluid-filled semicircular canals in the inner ear detect changes in the head's rotational movement, helping maintain balance."),
  _q("Which endocrine gland, often called the 'master gland', regulates the activity of most other endocrine glands?",
      ["Pituitary gland", "Thyroid gland", "Adrenal gland", "Pancreas"], "Pituitary gland",
      "The pituitary gland secretes hormones that control the activity of other endocrine glands, including the thyroid, adrenal glands, and gonads."),
];

final _homeostasis = [
  _q("Homeostasis is best defined as the",
      ["maintenance of a stable internal environment despite external changes", "process of excreting metabolic waste", "growth and development of an organism", "process of obtaining food from the environment"], "maintenance of a stable internal environment despite external changes",
      "Homeostasis refers to the regulatory mechanisms that keep internal conditions such as temperature, water balance, and blood glucose within narrow, stable limits."),
  _q("The hormone responsible for lowering blood glucose levels after a meal is",
      ["insulin", "glucagon", "adrenaline", "thyroxine"], "insulin",
      "Insulin, secreted by the beta cells of the pancreas, stimulates cells to absorb glucose and promotes glycogen storage, lowering blood glucose levels."),
  _q("A deficiency in insulin production leads to a condition known as",
      ["diabetes mellitus", "goitre", "anaemia", "rickets"], "diabetes mellitus",
      "Without adequate insulin, cells cannot efficiently take up glucose, leading to persistently high blood glucose levels characteristic of diabetes mellitus."),
  _q("The hormone glucagon, secreted by the pancreas, acts to",
      ["raise blood glucose levels by promoting the breakdown of glycogen to glucose", "lower blood glucose by promoting glycogen storage", "regulate water reabsorption in the kidney", "control body temperature"], "raise blood glucose levels by promoting the breakdown of glycogen to glucose",
      "Glucagon opposes insulin, stimulating the liver to convert stored glycogen back into glucose when blood sugar levels fall too low."),
  _q("Osmoregulation refers to the regulation of",
      ["water and salt balance in the body", "body temperature", "blood glucose concentration only", "heart rate"], "water and salt balance in the body",
      "Osmoregulation maintains the correct concentration of water and dissolved solutes in body fluids, primarily controlled by the kidneys."),
  _q("Which hormone increases water reabsorption in the kidney tubules, concentrating urine when the body is dehydrated?",
      ["Antidiuretic hormone (ADH)", "Insulin", "Adrenaline", "Thyroxine"], "Antidiuretic hormone (ADH)",
      "ADH, released by the pituitary gland, increases the permeability of the kidney's collecting ducts to water, reducing urine volume and conserving body water."),
  _q("Sweating helps regulate body temperature mainly by",
      ["evaporative cooling as sweat vaporises from the skin surface", "increasing blood flow to the skin only", "trapping a layer of warm air near the skin", "constricting blood vessels near the skin"], "evaporative cooling as sweat vaporises from the skin surface",
      "As sweat evaporates from the skin, it absorbs latent heat from the body, producing a cooling effect that helps lower body temperature."),
  _q("Vasodilation of blood vessels near the skin surface in hot conditions helps the body to",
      ["lose more heat to the surroundings by increased blood flow near the surface", "retain heat within the body", "increase blood pressure", "reduce sweat production"], "lose more heat to the surroundings by increased blood flow near the surface",
      "When skin blood vessels widen (vasodilate), more warm blood flows near the skin surface, increasing heat loss to the environment by radiation and convection."),
];

final _reproduction = [
  _q("Asexual reproduction in which a new individual develops as an outgrowth from the parent, as in Hydra, is called",
      ["budding", "binary fission", "vegetative propagation", "spore formation"], "budding",
      "In budding, a small outgrowth (bud) forms on the parent and eventually detaches to become an independent organism, common in Hydra and yeast."),
  _q("Binary fission, a form of asexual reproduction, is most typically seen in",
      ["bacteria and Amoeba", "flowering plants", "mammals", "insects"], "bacteria and Amoeba",
      "Binary fission involves a single-celled organism splitting into two genetically identical daughter cells, characteristic of bacteria and protozoans like Amoeba."),
  _q("Vegetative propagation using stem cuttings, runners, or tubers is a form of",
      ["asexual reproduction in plants", "sexual reproduction in plants", "spore formation", "external fertilisation"], "asexual reproduction in plants",
      "Vegetative propagation produces new plants from vegetative parts (stems, roots, leaves) without the fusion of gametes, making it asexual."),
  _q("In flowering plants, the male reproductive part of the flower is the",
      ["stamen", "carpel (pistil)", "sepal", "petal"], "stamen",
      "The stamen, consisting of the anther and filament, produces pollen grains containing the male gametes of a flowering plant."),
  _q("The transfer of pollen grains from the anther to the stigma of the same flower or a different flower of the same species is called",
      ["pollination", "fertilisation", "germination", "dispersal"], "pollination",
      "Pollination is the physical transfer of pollen to the stigma, a necessary precursor step before fertilisation (fusion of gametes) can occur."),
  _q("Fertilisation in flowering plants occurs when",
      ["the male gamete nucleus fuses with the egg nucleus in the ovule", "pollen lands on the stigma", "a seed germinates", "the fruit ripens"], "the male gamete nucleus fuses with the egg nucleus in the ovule",
      "After pollination, the pollen tube grows down to the ovule, delivering the male gamete nucleus, which fuses with the egg nucleus to form a zygote."),
  _q("In mammals, fertilisation normally takes place in the",
      ["oviduct (fallopian tube)", "uterus", "ovary", "vagina"], "oviduct (fallopian tube)",
      "The sperm typically meets and fertilises the egg in the oviduct, after which the resulting zygote travels to the uterus for implantation."),
  _q("The structure that connects the developing foetus to the uterine wall, allowing exchange of nutrients and waste, is the",
      ["placenta", "amnion", "chorion", "yolk sac"], "placenta",
      "The placenta is a specialised organ that facilitates the exchange of oxygen, nutrients, and waste products between the mother's blood and the foetus."),
  _q("Which of the following is an example of external fertilisation?",
      ["Fertilisation in most fish, where eggs and sperm are released into water", "Fertilisation in mammals", "Fertilisation in birds", "Fertilisation in flowering plants"], "Fertilisation in most fish, where eggs and sperm are released into water",
      "In external fertilisation, gametes fuse outside the body, typically in water, as seen in most fish and amphibians, unlike the internal fertilisation in mammals."),
  _q("The amnion, a membrane surrounding the developing embryo in reptiles, birds, and mammals, functions mainly to",
      ["produce amniotic fluid that cushions and protects the embryo", "supply the embryo with food reserves", "carry out gaseous exchange", "anchor the embryo to the uterine wall"], "produce amniotic fluid that cushions and protects the embryo",
      "The amnion secretes amniotic fluid, which cushions the embryo against mechanical shock and prevents desiccation, an adaptation for reproduction on land."),
];

final _geneticsHeredity = [
  _q("The hereditary material found in the nucleus of a cell, responsible for transmitting traits from parents to offspring, is",
      ["deoxyribonucleic acid (DNA)", "ribonucleic acid (RNA) only", "adenosine triphosphate (ATP)", "glycogen"], "deoxyribonucleic acid (DNA)",
      "DNA carries the genetic instructions encoded in genes, organized on chromosomes, and is passed from parents to offspring during reproduction."),
  _q("A gene is best defined as",
      ["a segment of DNA that codes for a particular trait or protein", "an entire chromosome", "a pair of alleles", "the physical appearance of an organism"], "a segment of DNA that codes for a particular trait or protein",
      "Genes are specific sequences of DNA located at particular positions (loci) on chromosomes, each typically coding for a specific protein or trait."),
  _q("Alternative forms of a gene occupying the same position on homologous chromosomes are called",
      ["alleles", "chromatids", "genotypes", "phenotypes"], "alleles",
      "Alleles are variant forms of the same gene (e.g., for flower colour) that occupy corresponding positions on a pair of homologous chromosomes."),
  _q("In Mendelian genetics, if a tall plant (Tt) is crossed with another tall plant (Tt), what proportion of the offspring is expected to be tall, assuming T is completely dominant over t?",
      ["3/4 (75%)", "1/2 (50%)", "1/4 (25%)", "All of the offspring"], "3/4 (75%)",
      "A Tt x Tt cross gives a genotype ratio of 1 TT : 2 Tt : 1 tt. Since T is dominant, TT and Tt are both tall, giving 3/4 tall offspring by phenotype."),
  _q("An organism with two identical alleles for a given gene (e.g., TT or tt) is described as",
      ["homozygous", "heterozygous", "hybrid", "diploid only for that gene"], "homozygous",
      "Homozygous describes an organism carrying two identical alleles for a particular gene, as opposed to heterozygous, which carries two different alleles."),
  _q("The observable physical or biochemical characteristics of an organism, resulting from its genotype and environment, is called its",
      ["phenotype", "genotype", "karyotype", "allele"], "phenotype",
      "Phenotype refers to the outwardly expressed traits (e.g., flower colour, height) resulting from the interaction between an organism's genes and its environment."),
  _q("In humans, red-green colour blindness is a sex-linked trait carried on the",
      ["X chromosome", "Y chromosome", "an autosome (non-sex chromosome)", "mitochondrial DNA"], "X chromosome",
      "The gene for red-green colour blindness is located on the X chromosome, which explains why the condition is far more common in males (XY) than females (XX)."),
  _q("A cross between a pure-breeding tall plant and a pure-breeding short plant, producing all tall offspring in the first generation, illustrates",
      ["the principle of dominance", "the law of independent assortment", "linkage", "incomplete dominance"], "the principle of dominance",
      "Mendel's principle of dominance states that in a heterozygote, one allele (the dominant one) masks the expression of the other (recessive) allele, giving uniform tall offspring."),
  _q("Continuous variation, such as human height, is characterised by",
      ["a gradual range of values with no distinct categories, usually influenced by many genes and the environment", "only a few sharply distinct categories, such as blood group", "control by a single gene only", "being entirely unaffected by environmental factors"], "a gradual range of values with no distinct categories, usually influenced by many genes and the environment",
      "Continuous variation, controlled by multiple genes (polygenic inheritance) and modified by environment, produces a smooth range of values rather than distinct classes."),
  _q("Discontinuous variation, such as human blood groups, is characterised by",
      ["distinct, separate categories with no intermediate forms", "a continuous range of values", "being influenced mainly by environmental factors", "gradual overlapping categories"], "distinct, separate categories with no intermediate forms",
      "Discontinuous variation produces clearly distinguishable categories (e.g., blood groups A, B, AB, O), typically controlled by one or a few genes with little environmental influence."),
  _q("The process by which chromosome number is halved during the formation of gametes is called",
      ["meiosis", "mitosis", "fertilisation", "binary fission"], "meiosis",
      "Meiosis is a reduction division producing haploid gametes from diploid cells, ensuring the chromosome number is restored to diploid upon fertilisation."),
  _q("Mitosis differs from meiosis in that mitosis produces",
      ["two genetically identical daughter cells with the same chromosome number as the parent", "four genetically different haploid cells", "gametes for sexual reproduction", "cells with half the chromosome number of the parent"], "two genetically identical daughter cells with the same chromosome number as the parent",
      "Mitosis is used for growth and repair, producing two diploid daughter cells identical to the parent cell, unlike meiosis, which halves the chromosome number."),
  _q("A test cross is used to determine",
      ["whether an organism showing a dominant trait is homozygous or heterozygous", "the exact phenotype of an organism", "the number of chromosomes in a cell", "the sex of an offspring"], "whether an organism showing a dominant trait is homozygous or heterozygous",
      "Crossing an organism of unknown genotype (showing the dominant phenotype) with a homozygous recessive individual reveals, from the offspring ratio, whether it is homozygous or heterozygous."),
  _q("Mutation is best described as",
      ["a sudden, random change in the genetic material (DNA) of an organism", "the normal process of gamete formation", "the blending of parental traits in offspring", "the transfer of pollen between flowers"], "a sudden, random change in the genetic material (DNA) of an organism",
      "Mutations are spontaneous or induced changes in DNA sequence that can alter genes or chromosomes, serving as an important source of new genetic variation."),
];

final _ecologyEnvironment = [
  _q("An ecosystem is best defined as",
      ["a community of living organisms interacting with each other and their non-living environment", "a group of organisms of the same species living together", "the non-living components of the environment only", "a single population of one species"], "a community of living organisms interacting with each other and their non-living environment",
      "An ecosystem encompasses both the biotic community (living organisms) and the abiotic (non-living) environment, together with the interactions between them."),
  _q("Organisms that manufacture their own organic food from inorganic substances, such as green plants, are called",
      ["producers", "primary consumers", "decomposers", "secondary consumers"], "producers",
      "Producers (autotrophs), mainly green plants and algae, form the base of most food chains by converting light energy into chemical energy via photosynthesis."),
  _q("Organisms that feed directly on producers are termed",
      ["primary consumers (herbivores)", "secondary consumers (carnivores)", "decomposers", "tertiary consumers"], "primary consumers (herbivores)",
      "Primary consumers, or herbivores, occupy the second trophic level, feeding directly on plant material produced by producers."),
  _q("Decomposers, such as bacteria and fungi, play a vital ecological role by",
      ["breaking down dead organic matter and releasing nutrients back into the environment", "manufacturing food using sunlight", "consuming living plants only", "converting nitrogen gas directly into protein"], "breaking down dead organic matter and releasing nutrients back into the environment",
      "Decomposers recycle nutrients locked in dead organisms and waste by breaking them down into simpler inorganic substances usable by producers again."),
  _q("A food web differs from a simple food chain in that a food web",
      ["shows the many interconnected feeding relationships within a community", "involves only one species", "has energy flowing in a single, unbranched line", "excludes decomposers entirely"], "shows the many interconnected feeding relationships within a community",
      "A food web is a more realistic representation than a single food chain, showing multiple interconnected feeding pathways among many different organisms in a community."),
  _q("The main process by which atmospheric nitrogen gas is converted into a usable form (nitrates) for plants, carried out by certain soil bacteria, is called",
      ["nitrogen fixation", "denitrification", "nitrification only", "decomposition"], "nitrogen fixation",
      "Nitrogen-fixing bacteria, such as Rhizobium in root nodules, convert inert atmospheric nitrogen gas into ammonia and nitrogenous compounds usable by plants."),
  _q("In the carbon cycle, carbon dioxide is returned to the atmosphere mainly through",
      ["respiration and combustion", "photosynthesis only", "nitrogen fixation", "decomposition of rocks"], "respiration and combustion",
      "Both the respiration of living organisms and the combustion of fuels (including fossil fuels) release carbon dioxide back into the atmosphere, balancing its removal by photosynthesis."),
  _q("A biome characterised by low rainfall, extreme temperature ranges, and sparse vegetation adapted to conserve water is the",
      ["desert", "tropical rainforest", "temperate grassland", "tundra"], "desert",
      "Deserts receive very little rainfall and experience large daily temperature swings, so their vegetation (e.g., cacti) shows strong adaptations for water conservation."),
  _q("The tropical rainforest biome is characterised mainly by",
      ["high rainfall, warm temperatures, and very high biodiversity", "low rainfall and sparse vegetation", "permanently frozen subsoil (permafrost)", "extreme cold with very short growing seasons"], "high rainfall, warm temperatures, and very high biodiversity",
      "Tropical rainforests receive abundant rainfall year-round and warm, stable temperatures, supporting some of the highest levels of biodiversity on Earth."),
  _q("Which of the following is an example of a density-dependent factor limiting population growth?",
      ["Competition for food among members of the population", "A sudden volcanic eruption", "An unusually cold winter affecting all individuals equally", "A flood destroying habitat regardless of population size"], "Competition for food among members of the population",
      "Density-dependent factors, like competition, disease spread, and predation, have effects that intensify as population density increases, unlike density-independent factors like natural disasters."),
  _q("Which human activity is a major contributor to environmental pollution through the release of excess carbon dioxide and other greenhouse gases?",
      ["Burning of fossil fuels", "Afforestation", "Crop rotation", "Organic composting"], "Burning of fossil fuels",
      "Burning coal, petroleum, and natural gas releases large quantities of carbon dioxide and other pollutants, driving climate change and air pollution."),
  _q("Overgrazing and deforestation commonly lead to which environmental problem?",
      ["Soil erosion and desertification", "Increased soil fertility", "Higher rainfall in the affected area", "Increased biodiversity"], "Soil erosion and desertification",
      "Removing vegetation cover through overgrazing or deforestation exposes soil to wind and water erosion, often leading to long-term land degradation and desertification."),
  _q("Which of the following best describes 'conservation' in an ecological context?",
      ["The careful management and sustainable use of natural resources to prevent their depletion", "The complete prohibition of any use of natural resources", "The process of converting forests into farmland", "The uncontrolled extraction of natural resources for economic gain"], "The careful management and sustainable use of natural resources to prevent their depletion",
      "Conservation involves the wise, sustainable management of resources such as forests, wildlife, and water to ensure their availability for future generations."),
  _q("A population, in ecological terms, refers to",
      ["all the individuals of the same species living in a particular area at a given time", "all the different species living in an area", "the physical habitat of an organism", "a single organism and its immediate offspring"], "all the individuals of the same species living in a particular area at a given time",
      "A population consists of interbreeding individuals of one species occupying a defined geographic area during a specific period."),
  _q("Which ecological factor is classified as a biotic (living) factor rather than an abiotic factor?",
      ["Predation by other organisms", "Temperature", "Rainfall", "Soil pH"], "Predation by other organisms",
      "Biotic factors involve interactions with other living organisms (predation, competition, disease), while abiotic factors are non-living physical/chemical conditions like temperature and rainfall."),
];

final _evolution = [
  _q("The theory of evolution proposes that",
      ["present-day species have descended, with gradual modification, from earlier, often simpler ancestral forms", "all species were created independently and remain unchanged", "organisms can acquire entirely new organs within a single generation by will", "species never change over geological time"], "present-day species have descended, with gradual modification, from earlier, often simpler ancestral forms",
      "Evolutionary theory holds that all life shares common ancestry, with species gradually changing over long time periods through processes such as natural selection."),
  _q("Lamarck's theory of evolution proposed that",
      ["acquired characteristics developed during an organism's lifetime could be inherited by its offspring", "natural selection acts on random genetic variation", "species arise only through special creation", "evolution occurs suddenly within a single generation"], "acquired characteristics developed during an organism's lifetime could be inherited by its offspring",
      "Lamarck's theory of 'inheritance of acquired characteristics' (e.g., a giraffe's neck lengthening from stretching, then being passed to offspring) is now considered incorrect by modern genetics."),
  _q("Charles Darwin's theory of evolution is primarily based on the mechanism of",
      ["natural selection acting on heritable variation", "inheritance of acquired characteristics", "special creation of each species", "spontaneous generation of life"], "natural selection acting on heritable variation",
      "Darwin proposed that individuals with heritable traits better suited to their environment survive and reproduce more successfully, gradually shifting a population's characteristics over generations."),
  _q("Which of the following is considered strong evidence for evolution from comparative anatomy?",
      ["Homologous structures, such as the similar bone arrangement in a bird's wing and a human arm", "Identical behaviour in unrelated species", "The presence of water in all living cells", "The universal use of the same language of instruction in biology"], "Homologous structures, such as the similar bone arrangement in a bird's wing and a human arm",
      "Homologous structures share a similar underlying skeletal arrangement despite different functions, suggesting descent from a common ancestor, a key evolutionary evidence."),
  _q("Fossils provide evidence for evolution mainly by",
      ["showing a chronological record of gradual changes in organisms over geological time", "proving that all species appeared at the same time", "showing that organisms never change", "demonstrating spontaneous generation of new species"], "showing a chronological record of gradual changes in organisms over geological time",
      "The fossil record, when arranged by the age of rock strata, often shows a progressive sequence of gradual anatomical change, supporting the concept of evolution over time."),
  _q("Vestigial structures, such as the human appendix, are considered evidence for evolution because they",
      ["are remnants of organs that were functional in ancestral species but have reduced or lost function today", "are essential for current survival", "appear only in the fossil record, never in living organisms", "prove that acquired characteristics are inherited"], "are remnants of organs that were functional in ancestral species but have reduced or lost function today",
      "Vestigial organs are reduced, seemingly non-functional structures inherited from ancestors in whom they served a clear purpose, suggesting evolutionary descent with modification."),
  _q("Natural selection acts on variation within a population mainly through differences in",
      ["survival and reproductive success among individuals with different heritable traits", "the total number of offspring produced regardless of trait", "the age at which individuals die of natural causes only", "random mutation rates that are identical for all individuals"], "survival and reproductive success among individuals with different heritable traits",
      "Individuals with traits better suited to their environment tend to survive longer and produce more offspring, passing those advantageous traits on more frequently."),
  _q("Adaptation, in the context of evolution, refers to",
      ["a heritable trait that improves an organism's chances of survival and reproduction in its environment", "any random change acquired during an organism's life", "the process of an individual organism changing its own body structure at will", "a trait that has no effect on survival"], "a heritable trait that improves an organism's chances of survival and reproduction in its environment",
      "Adaptations are inherited features shaped by natural selection over generations that enhance an organism's fitness for its specific environment."),
  _q("Which of the following is an example of camouflage as an adaptation for survival?",
      ["A chameleon changing colour to blend with its surroundings", "A cactus storing water in its stem", "A bird building a nest", "A fish having gills for respiration"], "A chameleon changing colour to blend with its surroundings",
      "Camouflage allows organisms to blend with their environment, reducing detection by predators or improving success as a predator, a classic survival adaptation."),
  _q("The concept of 'survival of the fittest' in evolutionary theory means that",
      ["organisms best suited to their environment are more likely to survive and reproduce", "only the physically strongest organisms in a population ever survive", "all organisms in a population have an equal chance of survival regardless of traits", "fitness refers only to physical strength and speed"], "organisms best suited to their environment are more likely to survive and reproduce",
      "'Fitness' in evolutionary biology means reproductive success relative to the environment, not just physical strength, so well-adapted individuals of any trait can be 'fittest'."),
];
