import "../quiz_question.dart";

const _subject = "Use of English";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// JAMB Use of English — 100 questions covering Comprehension & Cloze,
/// Lexis & Structure, and Oral Forms. The approved-novel section (typically
/// ~10 questions) is deliberately excluded since it requires verified,
/// year-specific plot/character details not fabricated from memory.
List<QuizQuestion> buildJambUseOfEnglishQuestions() {
  return [
    ..._comprehension,
    ..._cloze,
    ..._lexis,
    ..._structure,
    ..._oralForms,
  ];
}

const _passage1 =
    "The rise of ride-hailing applications has quietly transformed transportation in Nigerian cities over the past "
    "decade. Where commuters once haggled endlessly with bus conductors or waited indefinitely for danfo buses to "
    "fill up, many now summon a car with a few taps on a smartphone screen. The convenience is undeniable: fixed "
    "fares eliminate haggling, GPS tracking reassures anxious relatives, and cashless payment removes the need to "
    "carry loose change. Yet the revolution has not been without friction. Traditional taxi drivers have staged "
    "protests in several cities, arguing that app-based drivers operate with lower overheads and undercut "
    "established fares unfairly. Regulators, meanwhile, have struggled to keep pace, drafting rules for an industry "
    "that barely existed when most transport legislation was written. Whether ride-hailing ultimately complements "
    "or replaces traditional taxis remains an open question, but its effect on how urban Nigerians move has already "
    "proven permanent.";

final _comprehension = [
  _q("$_passage1\n\nAccording to the passage, what has been one major benefit of ride-hailing apps for commuters?",
      ["Fixed fares that eliminate the need to haggle", "Free rides for all passengers", "Guaranteed government subsidies", "The complete elimination of traffic"], "Fixed fares that eliminate the need to haggle",
      "The passage states that fixed fares eliminate haggling as one of the conveniences of ride-hailing apps."),
  _q("$_passage1\n\nWhy have traditional taxi drivers protested against ride-hailing apps, according to the passage?",
      ["They believe app-based drivers have lower overheads and undercut established fares", "They believe ride-hailing apps are entirely illegal", "They want to ban all smartphones", "They are protesting against GPS tracking specifically"], "They believe app-based drivers have lower overheads and undercut established fares",
      "The passage states taxi drivers argue that app-based drivers operate with lower overheads and unfairly undercut established fares."),
  _q("$_passage1\n\nWhat challenge do regulators face regarding ride-hailing apps, according to the passage?",
      ["Drafting rules for an industry that did not exist when most transport laws were written", "Banning all forms of private transportation", "Reducing the number of licensed drivers to zero", "Eliminating smartphone use entirely"], "Drafting rules for an industry that did not exist when most transport laws were written",
      "The passage states regulators have struggled to draft rules for an industry that barely existed when transport legislation was originally written."),
  _q("$_passage1\n\nWhich of the following best captures the overall tone of the passage towards ride-hailing apps?",
      ["Balanced, acknowledging both benefits and challenges", "Entirely negative and dismissive", "Entirely uncritical and celebratory", "Indifferent and disengaged"], "Balanced, acknowledging both benefits and challenges",
      "The passage presents both the conveniences of ride-hailing and the friction it has caused, reflecting a balanced tone."),
  _q("$_passage1\n\nIn the context of the passage, the word 'friction' is nearest in meaning to:",
      ["conflict or disagreement", "smooth cooperation", "financial profit", "technological advancement"], "conflict or disagreement",
      "'Friction' here refers to the tension and conflict caused by the rise of ride-hailing apps, particularly with traditional taxi drivers."),
  _q("$_passage1\n\nIn the context of the passage, the word 'undercut' is nearest in meaning to:",
      ["offer a lower price than a competitor", "support financially", "praise publicly", "regulate strictly"], "offer a lower price than a competitor",
      "'Undercut' means to offer a lower price than competitors, here referring to app-based drivers charging less than traditional taxis."),
  _q("$_passage1\n\nWhich of the following statements is an opinion, rather than a fact, expressed in the passage?",
      ["Whether ride-hailing ultimately complements or replaces traditional taxis remains an open question", "Ride-hailing apps use GPS tracking", "Ride-hailing apps allow cashless payment", "Traditional taxi drivers have staged protests"], "Whether ride-hailing ultimately complements or replaces traditional taxis remains an open question",
      "This statement expresses uncertainty about the future, a matter of interpretation rather than a verifiable fact like the others listed."),
];

const _passage2 =
    "Few household rituals carry as much quiet significance in many Nigerian homes as the Sunday afternoon meal, "
    "prepared slowly while extended family drifts in and out of the kitchen. Unlike the rushed breakfasts of a "
    "working week, this meal is treated as an occasion, often stretching for hours as pots simmer and conversation "
    "meanders from politics to gossip to plans for the week ahead. Grandmothers guard their recipes jealously, "
    "correcting younger relatives who add too much or too little of a given spice, while children underfoot learn, "
    "almost by osmosis, the techniques that will one day be theirs to pass on. In an era of fast food and delivery "
    "apps, this ritual persists stubbornly, a reminder that some traditions resist the pull of convenience because "
    "their true value was never about efficiency in the first place.";

final _cloze = [
  _q("$_passage2\n\nAccording to the passage, how does the Sunday meal differ from weekday breakfasts?",
      ["It is treated as an occasion and often stretches for hours", "It is eaten in complete silence", "It is always ordered from a delivery app", "It is prepared by professional chefs only"], "It is treated as an occasion and often stretches for hours",
      "The passage explicitly contrasts the rushed weekday breakfasts with the slow, hours-long Sunday meal treated as an occasion."),
  _q("$_passage2\n\nWhat role do grandmothers play in this household ritual, according to the passage?",
      ["They guard their recipes and correct younger relatives' cooking techniques", "They refuse to participate in cooking at all", "They only eat the meal without preparing it", "They order food from delivery apps for the family"], "They guard their recipes and correct younger relatives' cooking techniques",
      "The passage states grandmothers guard recipes jealously and correct younger relatives who use incorrect amounts of spice."),
  _q("$_passage2\n\nIn the context of the passage, the phrase 'almost by osmosis' suggests that children learn cooking techniques by:",
      ["Simply being present and absorbing knowledge gradually, without formal instruction", "Attending structured cooking classes", "Reading detailed recipe books", "Watching cooking videos online"], "Simply being present and absorbing knowledge gradually, without formal instruction",
      "'By osmosis' is a figurative expression meaning to absorb knowledge gradually and passively, simply through exposure."),
  _q("$_passage2\n\nWhat does the passage suggest is the 'true value' of this tradition, distinct from convenience?",
      ["The connection, conversation, and continuity between generations", "Saving the most amount of time possible", "Reducing the cost of food preparation", "Avoiding all forms of social interaction"], "The connection, conversation, and continuity between generations",
      "The passage emphasises family conversation, learning, and generational continuity as the tradition's real value, not efficiency."),
  _q("$_passage2\n\nWhich of the following best describes the writer's attitude towards fast food and delivery apps, as implied in the passage?",
      ["Fast food represents convenience that this particular tradition deliberately resists", "Fast food is portrayed as superior to home cooking", "The writer expresses no view on fast food at all", "Fast food is described as the primary subject of the passage"], "Fast food represents convenience that this particular tradition deliberately resists",
      "The passage frames fast food and delivery apps as symbols of modern convenience that this enduring tradition resists, not as its central topic."),
  _q("In this passage, choose the most suitable word to fill the gap: 'The company announced its quarterly results, which _____ analysts by exceeding all expectations.'",
      ["surprised", "surprising", "surprise", "surprises"], "surprised",
      "The past tense 'surprised' correctly agrees with the past tense verb 'announced' used earlier in the sentence."),
  _q("Choose the most suitable word to fill the gap: 'Despite the heavy rainfall, the football match _____ as scheduled.'",
      ["proceeded", "proceeding", "proceeds", "to proceed"], "proceeded",
      "'Proceeded' is the correct past tense form needed to match the context of an event that already happened despite the rain."),
  _q("Choose the most suitable word to fill the gap: 'Many students find it difficult to concentrate _____ noisy environments.'",
      ["in", "on", "at", "for"], "in",
      "'In' is the correct preposition to use when referring to being within a particular type of environment or setting."),
  _q("Choose the most suitable word to fill the gap: 'The committee is expected to reach a decision _____ the end of the week.'",
      ["by", "since", "from", "at"], "by",
      "'By' correctly indicates a deadline — the decision must be made no later than the end of the week."),
  _q("Choose the most suitable word to fill the gap: 'She has been working on the project _____ three months now.'",
      ["for", "since", "during", "within"], "for",
      "'For' is used with a duration of time (three months), while 'since' would require a specific starting point in time."),
  _q("Choose the most suitable word to fill the gap: 'The manager insisted that the report _____ submitted before noon.'",
      ["be", "is", "was", "being"], "be",
      "After verbs like 'insisted that' expressing a demand, the subjunctive base form 'be' is used, regardless of subject."),
  _q("Choose the most suitable word to fill the gap: 'Neither the teacher nor the students _____ aware of the sudden change in schedule.'",
      ["were", "was", "is", "has been"], "were",
      "With 'neither...nor', the verb agrees with the nearer subject, 'students', which is plural, requiring 'were'."),
  _q("Choose the most suitable word to fill the gap: 'It is important _____ every citizen to obey traffic laws.'",
      ["for", "to", "of", "with"], "for",
      "'It is important for someone to do something' is the standard construction indicating who the obligation applies to."),
  _q("Choose the most suitable word to fill the gap: 'The old bridge, _____ was built decades ago, is finally being renovated.'",
      ["which", "who", "whom", "whose"], "which",
      "'Which' is the correct relative pronoun to refer to a non-human antecedent, 'the old bridge', in a non-defining clause."),
];

final _lexis = [
  _q("Choose the word nearest in meaning to the underlined word: The manager's decision was completely ARBITRARY.",
      ["random and unreasoned", "carefully calculated", "publicly announced", "financially motivated"], "random and unreasoned",
      "'Arbitrary' describes a decision made without a clear reason or system, often seemingly random."),
  _q("Choose the word nearest in meaning to the underlined word: The old manuscript was extremely FRAGILE.",
      ["easily broken or damaged", "extremely valuable", "brightly coloured", "very heavy"], "easily broken or damaged",
      "'Fragile' means delicate and easily broken or damaged."),
  _q("Choose the word nearest in meaning to the underlined word: His ABRUPT departure surprised everyone at the meeting.",
      ["sudden", "gradual", "cheerful", "delayed"], "sudden",
      "'Abrupt' means sudden and unexpected, especially when describing an action or change."),
  _q("Choose the word nearest in meaning to the underlined word: The professor's lecture was rather TEDIOUS.",
      ["boring and long", "exciting and brief", "controversial", "poorly attended"], "boring and long",
      "'Tedious' describes something that is tiresomely long and dull."),
  _q("Choose the word nearest in meaning to the underlined word: The team showed remarkable RESILIENCE after their early defeat.",
      ["the ability to recover quickly from difficulty", "a tendency to give up easily", "an unfair advantage", "a lack of preparation"], "the ability to recover quickly from difficulty",
      "'Resilience' refers to the capacity to recover quickly from setbacks or difficulties."),
  _q("Choose the word OPPOSITE in meaning to the underlined word: The politician's speech was notably CANDID.",
      ["evasive", "honest", "lengthy", "persuasive"], "evasive",
      "'Candid' means open and honest; its opposite is 'evasive', meaning avoiding direct answers."),
  _q("Choose the word OPPOSITE in meaning to the underlined word: The old house looked absolutely PRISTINE after renovation.",
      ["dilapidated", "spotless", "modern", "expensive"], "dilapidated",
      "'Pristine' means in perfect, untouched condition; its opposite is 'dilapidated', meaning in a state of disrepair."),
  _q("Choose the word OPPOSITE in meaning to the underlined word: The negotiations were marked by a spirit of HOSTILITY.",
      ["friendliness", "aggression", "secrecy", "urgency"], "friendliness",
      "'Hostility' means unfriendliness or aggression; its opposite is 'friendliness'."),
  _q("Choose the word OPPOSITE in meaning to the underlined word: His argument, though clever, was fundamentally SUPERFICIAL.",
      ["profound", "shallow", "confusing", "brief"], "profound",
      "'Superficial' means lacking depth; its opposite is 'profound', meaning deep or thorough."),
  _q("Choose the correct homonym pair used appropriately: 'The _____ of the ship sailed smoothly, while the captain checked the _____ for the journey ahead.'",
      ["vessel...course", "vessel...coarse", "vassal...course", "vassal...coarse"], "vessel...course",
      "'Vessel' (a ship) and 'course' (a route) are the correctly spelled homonyms fitting the sentence's meaning, distinct from 'vassal' (a subordinate) and 'coarse' (rough)."),
  _q("Which pair of words are homophones (sound alike but differ in spelling and meaning)?",
      ["Meat and meet", "Meat and beat", "Meet and greet", "Beat and beet — not a homophone pair"], "Meat and meet",
      "'Meat' and 'meet' are pronounced identically but have different spellings and meanings, making them homophones."),
  _q("Which pair of words are homophones?",
      ["Sea and see", "Sea and tea", "See and seed", "Tea and ten"], "Sea and see",
      "'Sea' and 'see' sound identical but differ in spelling and meaning, making them homophones."),
  _q("Choose the idiom that best completes the sentence: After the long negotiation, both sides finally agreed to _____ and sign the contract.",
      ["bury the hatchet", "spill the beans", "hit the road", "burn the midnight oil"], "bury the hatchet",
      "'Bury the hatchet' means to make peace or end a disagreement, fitting the context of reaching an agreement."),
  _q("Choose the idiom that best completes the sentence: The new employee had to _____ quickly to keep up with the fast-paced office.",
      ["hit the ground running", "let the cat out of the bag", "beat around the bush", "throw in the towel"], "hit the ground running",
      "'Hit the ground running' means to start something with great energy and immediate success, fitting the context of adapting quickly."),
  _q("Choose the idiom that best completes the sentence: Despite the setback, the team decided not to _____ and kept working towards their goal.",
      ["throw in the towel", "spill the beans", "bury the hatchet", "hit the road"], "throw in the towel",
      "'Throw in the towel' means to give up; the sentence requires the negative form 'not to give up', fitting the context of persistence."),
  _q("Choose the correct formal idiomatic expression: 'The board members agreed, _____, that the merger should proceed.'",
      ["by and large", "once in a blue moon", "at the drop of a hat", "out of the blue"], "by and large",
      "'By and large' means 'generally speaking' or 'for the most part', an appropriate formal expression for general agreement."),
  _q("Choose the word nearest in meaning to the underlined word: The witness gave a very CREDIBLE account of the incident.",
      ["believable", "confusing", "brief", "aggressive"], "believable",
      "'Credible' means capable of being believed; convincing."),
  _q("Choose the word nearest in meaning to the underlined word: The company's profits showed a GRADUAL increase over the year.",
      ["happening slowly over time", "sudden and dramatic", "temporary and brief", "completely unpredictable"], "happening slowly over time",
      "'Gradual' describes a change that happens slowly and steadily over time."),
  _q("Choose the word OPPOSITE in meaning to the underlined word: The new policy was met with UNANIMOUS approval from the board.",
      ["divided", "unanimous", "quick", "written"], "divided",
      "'Unanimous' means everyone agrees; its opposite is 'divided', meaning split in opinion."),
  _q("Choose the word OPPOSITE in meaning to the underlined word: The athlete's performance was considered MEDIOCRE by the judges.",
      ["outstanding", "average", "consistent", "brief"], "outstanding",
      "'Mediocre' means of only average quality; its opposite is 'outstanding', meaning exceptionally good."),
  _q("Choose the idiom that best completes the sentence: The manager decided to _____ and give the new intern a chance to prove himself.",
      ["give the benefit of the doubt", "spill the beans", "cut corners", "jump on the bandwagon"], "give the benefit of the doubt",
      "'Give the benefit of the doubt' means to trust someone's claim or ability without full proof, fitting the context of giving a new intern a chance."),
];

final _structure = [
  _q("Identify the correctly formed sentence.",
      ["Neither the manager nor his assistants were available for comment.", "Neither the manager nor his assistants was available for comment.", "Neither the manager or his assistants were available for comment.", "Neither the manager nor his assistants is available for comment."],
      "Neither the manager nor his assistants were available for comment.",
      "With 'neither...nor', the verb agrees with the nearer subject 'assistants' (plural), requiring 'were', and the correct correlative pair is 'neither...nor'."),
  _q("Choose the sentence with correct subject-verb agreement.",
      ["The number of applicants has increased significantly.", "The number of applicants have increased significantly.", "A number of applicants has applied.", "The team is playing their best today, aren't they."],
      "The number of applicants has increased significantly.",
      "'The number of' takes a singular verb since 'number' is the subject; 'a number of' would take a plural verb instead."),
  _q("Choose the sentence written in the passive voice.",
      ["The bridge was built by skilled engineers over two years.", "Skilled engineers built the bridge over two years.", "The engineers are building a new bridge.", "The engineers will build a new bridge next year."],
      "The bridge was built by skilled engineers over two years.",
      "This sentence is in the passive voice because the subject 'the bridge' receives the action, rather than performing it."),
  _q("Change to indirect speech: She said, 'I will finish the report by tomorrow.'",
      ["She said that she would finish the report by the next day.", "She said that she will finish the report by tomorrow.", "She said I will finish the report by tomorrow.", "She said that she finishes the report tomorrow."],
      "She said that she would finish the report by the next day.",
      "In reported speech, 'will' shifts to 'would' and 'tomorrow' shifts to 'the next day' since the reference point has moved to the past."),
  _q("Identify the correctly punctuated sentence.",
      ["The conference, which lasted three days, attracted delegates from over twenty countries.", "The conference which lasted three days, attracted delegates from over twenty countries.", "The conference, which lasted three days attracted delegates from over twenty countries.", "The conference which, lasted three days, attracted delegates from over twenty countries."],
      "The conference, which lasted three days, attracted delegates from over twenty countries.",
      "Commas correctly enclose the non-defining relative clause 'which lasted three days', which adds extra information about the conference."),
  _q("Identify the sentence that correctly uses a semicolon.",
      ["The rain continued all night; the streets were flooded by morning.", "The rain continued all night, the streets were flooded by morning.", "The rain continued; all night the streets were flooded by morning.", "The rain continued all night the streets; were flooded by morning."],
      "The rain continued all night; the streets were flooded by morning.",
      "A semicolon correctly joins two closely related independent clauses without needing a coordinating conjunction."),
  _q("Choose the sentence that correctly uses an apostrophe to show plural possession.",
      ["The students' results were released this morning.", "The student's results were released this morning.", "The students results were released this morning.", "The students's results were released this morning."],
      "The students' results were released this morning.",
      "Since 'students' is already plural, the apostrophe is placed after the 's' to correctly show plural possession."),
  _q("Identify the sentence written as a complex sentence (containing an independent and a dependent clause).",
      ["Although the weather was cold, the athletes continued training.", "The weather was cold, and the athletes continued training.", "The weather was cold. The athletes continued training.", "The weather was cold; the athletes continued training."],
      "Although the weather was cold, the athletes continued training.",
      "This sentence contains a dependent clause ('Although the weather was cold') and an independent clause, forming a complex sentence."),
  _q("Which of the following is a compound sentence (containing two independent clauses joined by a coordinating conjunction)?",
      ["She studied hard, and she passed the examination with distinction.", "Because she studied hard, she passed the examination.", "She, having studied hard, passed the examination.", "Studying hard, she passed the examination."],
      "She studied hard, and she passed the examination with distinction.",
      "This sentence joins two independent clauses with the coordinating conjunction 'and', making it a compound sentence."),
  _q("Choose the correct form of the verb: 'By the time we arrived at the venue, the ceremony _____ already begun.'",
      ["had", "has", "have", "was"], "had",
      "The past perfect 'had begun' correctly shows that the ceremony started before another past action (arriving)."),
  _q("Choose the correct form of the verb: 'If I _____ the truth earlier, I would have acted differently.'",
      ["had known", "knew", "know", "have known"], "had known",
      "The third conditional requires the past perfect 'had known' in the if-clause to express an unreal past condition."),
  _q("Identify the correct sentence regarding concord.",
      ["Each of the members has submitted their report.", "Each of the members have submitted their report.", "Each of the member has submitted their report.", "Each of the members submit their report."],
      "Each of the members has submitted their report.",
      "'Each' is always singular, regardless of the plural noun that follows, requiring the singular verb 'has'."),
  _q("Choose the sentence with the correct use of the gerund.",
      ["Swimming every morning has improved her stamina significantly.", "To swim every morning have improved her stamina.", "Swim every morning improve her stamina.", "Swimming every morning have improved her stamina."],
      "Swimming every morning has improved her stamina significantly.",
      "'Swimming' functions as a gerund (verb acting as a noun) and, as a singular subject, correctly takes the singular verb 'has'."),
  _q("Choose the sentence that correctly demonstrates the use of a conditional clause.",
      ["If the government invests in infrastructure, the economy will improve.", "If the government invest in infrastructure, the economy will improve.", "If the government will invest in infrastructure, the economy improve.", "If the government invests in infrastructure, the economy improved."],
      "If the government invests in infrastructure, the economy will improve.",
      "This is a correctly structured first conditional: present simple in the if-clause, and 'will' plus base verb in the main clause."),
  _q("Choose the word class of the underlined word: 'She spoke SOFTLY to avoid waking the baby.'",
      ["Adverb", "Adjective", "Noun", "Preposition"], "Adverb",
      "'Softly' describes how the action 'spoke' was performed, making it an adverb of manner."),
  _q("Choose the word class of the underlined word: 'The COMMITTEE will meet on Thursday to finalise the budget.'",
      ["Noun", "Verb", "Adjective", "Adverb"], "Noun",
      "'Committee' names a group of people, functioning as a (collective) noun and the subject of the sentence."),
  _q("Choose the sentence that correctly uses the past perfect continuous tense.",
      ["She had been studying for three hours before the exam started.", "She has been studying for three hours before the exam started.", "She was study for three hours before the exam started.", "She studied for three hours before the exam start."],
      "She had been studying for three hours before the exam started.",
      "The past perfect continuous 'had been studying' correctly shows an ongoing action that continued up until another past event (the exam starting)."),
  _q("Choose the sentence with the correct use of a reflexive pronoun.",
      ["He blamed himself for the mistake.", "He blamed hisself for the mistake.", "He blamed him for the mistake, himself.", "He blamed itself for the mistake."],
      "He blamed himself for the mistake.",
      "'Himself' is the correct reflexive pronoun referring back to the subject 'He'."),
  _q("Identify the sentence that correctly demonstrates parallel structure.",
      ["She enjoys reading, writing, and travelling.", "She enjoys reading, writing, and to travel.", "She enjoys to read, writing, and travelling.", "She enjoys reading, to write, and travelling."],
      "She enjoys reading, writing, and travelling.",
      "Parallel structure requires that items in a list share the same grammatical form; here, all three items are gerunds."),
  _q("Choose the correctly punctuated sentence using a colon to introduce a list.",
      ["The recipe requires three ingredients: flour, sugar, and butter.", "The recipe requires three ingredients, flour, sugar, and butter.", "The recipe requires: three ingredients flour, sugar, and butter.", "The recipe requires three ingredients flour: sugar, and butter."],
      "The recipe requires three ingredients: flour, sugar, and butter.",
      "A colon correctly introduces the list of ingredients following a complete independent clause."),
  _q("Choose the sentence that correctly uses 'fewer' rather than 'less'.",
      ["There were fewer students in class today than yesterday.", "There were less students in class today than yesterday.", "There was fewer student in class today.", "There were less student in class today."],
      "There were fewer students in class today than yesterday.",
      "'Fewer' is used with countable nouns like 'students', while 'less' is used with uncountable nouns."),
  _q("Identify the sentence that correctly uses the present perfect tense to describe an experience without a specific time.",
      ["She has visited Paris twice.", "She visited Paris twice yesterday.", "She is visiting Paris twice.", "She will visit Paris twice."],
      "She has visited Paris twice.",
      "The present perfect 'has visited' is used to describe an experience at an unspecified time before now."),
  _q("Choose the sentence that correctly avoids a dangling modifier.",
      ["Walking to the market, she noticed the sky darken.", "Walking to the market, the sky darkened.", "The sky darkened, walking to the market.", "Walking, the market and the sky darkened."],
      "Walking to the market, she noticed the sky darken.",
      "The modifying phrase 'Walking to the market' correctly refers to 'she', the subject performing the action, avoiding ambiguity."),
  _q("Choose the correct word class of the underlined word: 'They arrived EARLY to secure good seats.'",
      ["Adverb", "Adjective", "Noun", "Verb"], "Adverb",
      "'Early' describes when the action 'arrived' took place, functioning as an adverb of time."),
  _q("Choose the correct word class of the underlined word: 'The BRAVE firefighter rescued the family from the burning building.'",
      ["Adjective", "Noun", "Adverb", "Verb"], "Adjective",
      "'Brave' describes the noun 'firefighter', making it an adjective."),
];

final _oralForms = [
  _q("Which word has the same vowel sound as the one in 'CHOICE'?",
      ["NOISE", "NICE", "NOSE", "NEWS"], "NOISE",
      "'CHOICE' and 'NOISE' both contain the diphthong /ɔɪ/."),
  _q("Which word has the same vowel sound as the one in 'PLEASE'?",
      ["PEACE", "PRESS", "PLACE", "PLUS"], "PEACE",
      "'PLEASE' and 'PEACE' both contain the long vowel /iː/."),
  _q("Which word has the same vowel sound as the one in 'HOUSE' (the noun)?",
      ["MOUSE", "MOSS", "MOOSE", "MUST"], "MOUSE",
      "'HOUSE' and 'MOUSE' both contain the diphthong /aʊ/."),
  _q("Which word has the same vowel sound as the one in 'BOARD'?",
      ["SWORD", "WORD", "BEARD", "BARD"], "SWORD",
      "'BOARD' and 'SWORD' both contain the long vowel /ɔː/."),
  _q("Which word has the same initial consonant sound as the one in 'PHASE'?",
      ["FAST", "PAST", "CHASE", "HASTE"], "FAST",
      "'Phase' begins with the consonant sound /f/, despite the 'ph' spelling, the same as in 'fast'."),
  _q("Which word has the same final consonant sound as the one in 'WASHED'?",
      ["LAUGHED", "LOVED", "LANDED", "PLAYED"], "LAUGHED",
      "'Washed' and 'laughed' both end with the voiceless consonant /t/, since the '-ed' is pronounced /t/ after voiceless sounds."),
  _q("Which word begins with the same consonant cluster as 'SCRATCH'?",
      ["SCREAM", "SPRAY", "STRAP", "SWEAT"], "SCREAM",
      "'Scratch' and 'scream' both begin with the consonant cluster /skr/."),
  _q("Which word rhymes with 'ENOUGH'?",
      ["TOUGH", "THOUGH", "THROUGH", "DOUGH"], "TOUGH",
      "'Enough' /ɪˈnʌf/ and 'tough' /tʌf/ share the identical ending sound, making them rhymes."),
  _q("Which word rhymes with 'HEIGHT'?",
      ["LIGHT", "HEAT", "HIT", "HATE"], "LIGHT",
      "'Height' and 'light' rhyme, sharing the ending sound /aɪt/."),
  _q("Which word rhymes with 'SOUL'?",
      ["ROLE", "SOIL", "SILL", "SULK"], "ROLE",
      "'Soul' /səʊl/ and 'role' /rəʊl/ share the identical ending sound, making them rhymes."),
  _q("In the word 'PHOTOGRAPHY', which syllable carries the primary stress?",
      ["Second", "First", "Third", "Fourth"], "Second",
      "'PHOTOGRAPHY' places its primary stress on the second syllable: pho-TOG-ra-phy."),
  _q("Which syllable is stressed in the noun 'PRODUCE' (as in farm produce)?",
      ["First", "Second", "Both equally", "Neither"], "First",
      "As a noun, 'produce' is stressed on the first syllable: PRO-duce."),
  _q("Which syllable is stressed in the verb 'PRODUCE' (to produce something)?",
      ["Second", "First", "Both equally", "Neither"], "Second",
      "As a verb, 'produce' is stressed on the second syllable: pro-DUCE."),
  _q("In the word 'DEMOCRATIC', which syllable carries the primary stress?",
      ["Third", "First", "Second", "Fourth"], "Third",
      "'DEMOCRATIC' places its primary stress on the third syllable: dem-o-CRAT-ic."),
  _q("In the sentence 'I NEVER said she stole the money', what does the emphatic stress on 'NEVER' suggest?",
      ["A strong denial that the speaker made such a statement", "A question about the money", "Agreement with the statement", "Uncertainty about the event"], "A strong denial that the speaker made such a statement",
      "Stressing 'NEVER' emphatically denies ever making the statement, contradicting a claim that the speaker did say it."),
  _q("In the sentence 'She wanted the RED dress, not the blue one', which word carries the emphatic stress and why?",
      ["RED, to highlight the specific colour in contrast to blue", "wanted, to show desire", "dress, to identify the clothing item", "blue, to identify the rejected item"], "RED, to highlight the specific colour in contrast to blue",
      "Stressing 'RED' contrasts the desired colour with the rejected alternative, 'blue'."),
  _q("Which of the following words contains a triphthong (a glide involving three vowel sounds)?",
      ["FIRE", "FEAR", "FUR", "FUN"], "FIRE",
      "'Fire' /faɪə/ contains a triphthong-like glide combining the diphthong /aɪ/ with the schwa /ə/, common in RP pronunciation of words like 'fire' and 'hour'."),
  _q("Which of the following best describes a 'diphthong' in English phonetics?",
      ["A glide from one vowel sound to another within the same syllable", "A single, pure vowel sound with no movement", "A consonant sound produced with two points of articulation", "A silent letter within a word"], "A glide from one vowel sound to another within the same syllable",
      "A diphthong is a vowel sound formed by the combination of two vowel qualities within a single syllable, such as the /eɪ/ in 'day'."),
  _q("Which word has the same vowel sound as the one in 'EARLY'?",
      ["BIRD", "BEARD", "BARD", "BREAD"], "BIRD",
      "'EARLY' and 'BIRD' both contain the long central vowel /ɜː/."),
  _q("Which word has the same vowel sound as the one in 'COULD'?",
      ["GOOD", "GOOSE", "GOAD", "GOD"], "GOOD",
      "'COULD' and 'GOOD' both contain the short vowel /ʊ/."),
  _q("Which word has the same initial consonant sound as the one in 'GENERAL'?",
      ["JELLY", "GATE", "GOAT", "GHOST"], "JELLY",
      "'General' begins with the consonant sound /dʒ/, the same as in 'jelly'."),
  _q("Which word has the same final consonant sound as the one in 'PLAYED'?",
      ["CLIMBED", "WALKED", "LAUGHED", "HOPED"], "CLIMBED",
      "'Played' and 'climbed' both end with the voiced consonant /d/, since the '-ed' is pronounced /d/ after most voiced sounds."),
  _q("Which word begins with the same consonant cluster as 'THROUGH'?",
      ["THREAT", "TROUT", "SHOUT", "THOUGHT"], "THREAT",
      "'Through' and 'threat' both begin with the consonant cluster /θr/."),
  _q("Which word rhymes with 'WEIGH'?",
      ["THEY", "WHY", "WEE", "WET"], "THEY",
      "'Weigh' /weɪ/ and 'they' /ðeɪ/ share the identical ending sound, making them rhymes."),
  _q("Which word rhymes with 'BREAK'?",
      ["STEAK", "BEAK", "BLACK", "BRICK"], "STEAK",
      "'Break' and 'steak' rhyme, sharing the ending sound /eɪk/, despite different spelling patterns."),
  _q("In the word 'ADVERTISEMENT', which syllable carries the primary stress?",
      ["Third", "First", "Second", "Fourth"], "Third",
      "'ADVERTISEMENT' places its primary stress on the third syllable: ad-ver-TISE-ment."),
  _q("Which syllable is stressed in the noun 'CONTRACT' (a written agreement)?",
      ["First", "Second", "Both equally", "Neither"], "First",
      "As a noun, 'contract' is stressed on the first syllable: CON-tract."),
  _q("Which syllable is stressed in the verb 'CONTRACT' (to shrink or agree formally)?",
      ["Second", "First", "Both equally", "Neither"], "Second",
      "As a verb, 'contract' is stressed on the second syllable: con-TRACT."),
  _q("Which word has the same vowel sound as the one in 'BLOOD'?",
      ["LOVE", "FOOD", "LOUD", "LOAD"], "LOVE",
      "'BLOOD' and 'LOVE' both contain the short vowel /ʌ/."),
  _q("Which word has the same initial consonant sound as the one in 'CHEMIST'?",
      ["KETTLE", "CHERRY", "SHELF", "CHURCH"], "KETTLE",
      "'Chemist' begins with the consonant sound /k/, the same as in 'kettle', despite the 'ch' spelling."),
  _q("Which word rhymes with 'COMB'?",
      ["HOME", "COMMA", "COME", "COMB"], "HOME",
      "'Comb' /kəʊm/ and 'home' /həʊm/ share the identical ending sound, making them rhymes."),
  _q("In the word 'CHARACTERISTIC', which syllable carries the primary stress?",
      ["Fourth", "First", "Second", "Third"], "Fourth",
      "'CHARACTERISTIC' places its primary stress on the fourth syllable: char-ac-ter-IS-tic."),
  _q("Which syllable is stressed in the noun 'RECORD' (a music recording)?",
      ["First", "Second", "Both equally", "Neither"], "First",
      "As a noun, 'record' is stressed on the first syllable: REC-ord."),
];
