import "../quiz_question.dart";

const _subject = "Economics";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// JAMB Economics — 100 questions covering the 12 core UTME topics: Basic
/// Economic Concepts, Economic Systems, Tools of Economic Analysis, Demand
/// & Supply, Consumer Behaviour, Production & Costs, Market Structures,
/// National Income, Money/Banking/Inflation, Public Finance,
/// International Trade & Economic Organizations, and the Nigerian Economy.
List<QuizQuestion> buildJambEconomicsQuestions() {
  return [
    ..._basicEconomicConcepts,
    ..._economicSystems,
    ..._toolsOfEconomicAnalysis,
    ..._demandAndSupply,
    ..._consumerBehaviour,
    ..._productionAndCosts,
    ..._marketStructures,
    ..._nationalIncome,
    ..._moneyBankingInflation,
    ..._publicFinance,
    ..._internationalTradeOrganizations,
    ..._nigerianEconomy,
  ];
}

final _basicEconomicConcepts = [
  _q("Economics is best defined as the study of how",
      ["scarce resources are allocated to satisfy unlimited human wants", "governments collect taxes from citizens", "businesses advertise their products", "countries maintain diplomatic relations"], "scarce resources are allocated to satisfy unlimited human wants",
      "Economics fundamentally studies the allocation of limited (scarce) resources among competing, virtually unlimited human wants and needs."),
  _q("Scarcity in economics refers to the situation where",
      ["available resources are insufficient to satisfy all human wants", "goods are deliberately withheld from the market", "there is an oversupply of goods and services", "prices of goods are fixed by the government"], "available resources are insufficient to satisfy all human wants",
      "Scarcity is the basic economic problem: resources (land, labour, capital) are limited relative to the unlimited wants of individuals and society."),
  _q("Because of scarcity, every economic decision necessarily involves making a",
      ["choice among competing alternatives", "guaranteed profit", "government intervention", "permanent solution to all wants"], "choice among competing alternatives",
      "Since resources cannot satisfy every want, individuals and societies must choose which wants to satisfy and which to forgo, a direct consequence of scarcity."),
  _q("Opportunity cost is best defined as the",
      ["value of the next best alternative forgone when a choice is made", "total cost of producing a good", "amount of money spent on a purchase", "profit earned from a business venture"], "value of the next best alternative forgone when a choice is made",
      "Opportunity cost measures what is sacrificed (the best alternative given up) when a particular choice is made among scarce resources."),
  _q("A scale of preference is a list that arranges an individual's",
      ["wants in order of importance, from the most pressing to the least pressing", "income sources from highest to lowest", "debts from largest to smallest", "possessions by monetary value"], "wants in order of importance, from the most pressing to the least pressing",
      "A scale of preference helps an individual rank their many wants by priority, guiding decisions on which wants to satisfy first given limited resources."),
  _q("Which of the following best illustrates the concept of opportunity cost?",
      ["A student chooses to study instead of watching a movie, giving up the enjoyment of the movie", "A company increases its total revenue", "A government prints more currency", "A farmer plants more than one crop"], "A student chooses to study instead of watching a movie, giving up the enjoyment of the movie",
      "By choosing to study, the student forgoes the next best alternative use of that time (watching the movie), which represents the opportunity cost of studying."),
  _q("Human wants are generally considered to be",
      ["unlimited, since satisfying one want often creates new ones", "limited and easily satisfied completely", "identical for every individual", "unaffected by income levels"], "unlimited, since satisfying one want often creates new ones",
      "A basic assumption in economics is that human wants are virtually insatiable; even after one want is satisfied, new wants tend to arise."),
  _q("The basic economic problems every society must solve include deciding",
      ["what to produce, how to produce, and for whom to produce", "only what price to charge for goods", "only how much tax to collect", "only how to spend government revenue"], "what to produce, how to produce, and for whom to produce",
      "Every economic system, regardless of type, must answer these three fundamental questions given the scarcity of resources relative to wants."),
];

final _economicSystems = [
  _q("In a capitalist (free market) economic system, economic decisions are primarily made by",
      ["individuals and private businesses responding to market forces", "the central government through central planning", "a council of religious leaders", "international organisations only"], "individuals and private businesses responding to market forces",
      "Capitalism relies on private ownership of resources and decisions driven by supply, demand, and price signals in free markets, with minimal government intervention."),
  _q("In a socialist (command) economic system, the basic economic problems are solved mainly by",
      ["central government planning and control of resources", "the free interaction of individual buyers and sellers", "a completely unregulated market", "religious institutions"], "central government planning and control of resources",
      "Socialist/command economies rely on centralized government planning to determine what, how, and for whom goods are produced, rather than market forces."),
  _q("A mixed economic system is characterised by",
      ["a combination of both private enterprise and government intervention in economic activities", "complete government ownership of all resources", "a total absence of any government regulation", "the total absence of private businesses"], "a combination of both private enterprise and government intervention in economic activities",
      "Mixed economies blend elements of both capitalism and socialism, allowing private enterprise to operate alongside government regulation and public sector involvement."),
  _q("One key feature of a capitalist economic system is",
      ["the right to private ownership of property and means of production", "state ownership of all major industries", "the absence of a price mechanism", "central planning of all production decisions"], "the right to private ownership of property and means of production",
      "Private property rights, allowing individuals and firms to own and control resources and businesses, are a defining feature of capitalism."),
  _q("The Nigerian economy is generally classified as a",
      ["mixed economy", "purely capitalist economy", "purely socialist (command) economy", "purely traditional economy"], "mixed economy",
      "Nigeria's economy combines private enterprise with significant government involvement and regulation in sectors such as oil, utilities, and infrastructure, making it a mixed economy."),
  _q("One disadvantage commonly associated with a purely socialist economic system is that it",
      ["may reduce individual initiative and efficiency due to lack of profit motive", "always leads to extreme income inequality", "relies entirely on the price mechanism", "guarantees the fastest possible economic growth"], "may reduce individual initiative and efficiency due to lack of profit motive",
      "Because production decisions are centrally planned rather than profit-driven, socialist economies are often criticised for potentially weaker incentives for efficiency and innovation."),
];

final _toolsOfEconomicAnalysis = [
  _q("In statistics, the arithmetic mean of a set of values is calculated as the",
      ["sum of all the values divided by the number of values", "middle value when data is arranged in order", "value that occurs most frequently", "difference between the highest and lowest values"], "sum of all the values divided by the number of values",
      "The mean (average) is found by adding all data values together and dividing by the total count of values."),
  _q("The median of a data set is defined as the",
      ["middle value when the data is arranged in ascending or descending order", "most frequently occurring value", "sum of all values divided by their count", "difference between the largest and smallest values"], "middle value when the data is arranged in ascending or descending order",
      "The median is the middle value of an ordered data set, dividing the data into two equal halves; for an even number of values, it is the average of the two middle values."),
  _q("The mode of a data set refers to the",
      ["value that occurs most frequently in the data set", "average of all the values", "middle value of an ordered data set", "range between the highest and lowest values"], "value that occurs most frequently in the data set",
      "The mode identifies the most commonly occurring value(s) in a data set, useful for categorical or frequently repeated numerical data."),
  _q("What is the mean of the following set of numbers: 4, 6, 8, 10, 12?",
      ["8", "10", "6", "40"], "8",
      "Sum = 4+6+8+10+12 = 40. Mean = 40/5 = 8."),
  _q("The range of a data set is calculated as the",
      ["difference between the highest and lowest values", "sum of all the values", "average of the highest and lowest values", "middle value of the data set"], "difference between the highest and lowest values",
      "Range = highest value - lowest value, providing a simple measure of the spread (dispersion) of a data set."),
  _q("Standard deviation is a statistical measure used to indicate the",
      ["degree of dispersion (spread) of data values around the mean", "central tendency of a data set", "total sum of all data values", "most frequently occurring value in a data set"], "degree of dispersion (spread) of data values around the mean",
      "Standard deviation quantifies how much individual data points typically deviate from the mean, with a larger value indicating greater spread/variability."),
  _q("A pie chart is most useful for representing data as",
      ["proportions of a whole, shown as slices of a circle", "trends changing continuously over time", "the relationship between two continuous variables", "raw, unprocessed numerical data only"], "proportions of a whole, shown as slices of a circle",
      "Pie charts visually represent how a total quantity is divided into categorical proportions, with each slice representing a percentage of the whole."),
  _q("A line graph is particularly useful in economics for showing",
      ["how a variable changes continuously over a period of time", "the frequency of a single categorical value", "the proportion of a total represented by different categories", "unordered qualitative data"], "how a variable changes continuously over a period of time",
      "Line graphs effectively illustrate trends and changes in a variable (e.g., price, GDP) over successive time periods, making patterns easy to observe."),
];

final _demandAndSupply = [
  _q("The law of demand states that, other things being equal, as the price of a good rises, the quantity demanded",
      ["falls", "rises", "remains constant", "becomes infinite"], "falls",
      "The law of demand describes an inverse relationship between price and quantity demanded: consumers buy less of a good as its price increases, ceteris paribus."),
  _q("The law of supply states that, other things being equal, as the price of a good rises, the quantity supplied",
      ["rises", "falls", "remains constant", "becomes zero"], "rises",
      "The law of supply describes a direct (positive) relationship between price and quantity supplied: producers are willing to supply more as price increases, ceteris paribus."),
  _q("Market equilibrium occurs at the price where",
      ["quantity demanded equals quantity supplied", "quantity demanded exceeds quantity supplied", "quantity supplied exceeds quantity demanded", "price is at its highest possible level"], "quantity demanded equals quantity supplied",
      "Equilibrium price is where the demand and supply curves intersect, at which the amount buyers wish to purchase exactly matches the amount sellers wish to sell."),
  _q("A rightward shift of the demand curve (an increase in demand) can be caused by",
      ["an increase in consumer income (for a normal good)", "an increase in the price of the good itself", "a decrease in consumer income (for a normal good)", "an increase in the number of sellers only"], "an increase in consumer income (for a normal good)",
      "For a normal good, rising consumer income increases the quantity demanded at every price level, shifting the entire demand curve to the right."),
  _q("A leftward shift of the supply curve (a decrease in supply) can be caused by",
      ["an increase in the cost of production inputs", "a decrease in the price of production inputs", "an increase in the number of firms in the market", "an improvement in production technology"], "an increase in the cost of production inputs",
      "Higher input costs make production less profitable at every price level, causing producers to supply less, shifting the supply curve to the left."),
  _q("If the price of a good is set above the equilibrium price, the immediate result will be",
      ["a surplus, as quantity supplied exceeds quantity demanded", "a shortage, as quantity demanded exceeds quantity supplied", "no change in the market", "an automatic decrease in supply to zero"], "a surplus, as quantity supplied exceeds quantity demanded",
      "At a price above equilibrium, producers are willing to supply more than consumers wish to buy, creating a surplus (excess supply) that tends to push the price back down."),
  _q("If the price of a good is set below the equilibrium price, the immediate result will be",
      ["a shortage, as quantity demanded exceeds quantity supplied", "a surplus, as quantity supplied exceeds quantity demanded", "no change in the market", "an automatic increase in supply to infinity"], "a shortage, as quantity demanded exceeds quantity supplied",
      "At a price below equilibrium, consumers want to buy more than producers are willing to supply at that price, creating a shortage (excess demand)."),
  _q("Price elasticity of demand measures the",
      ["responsiveness of quantity demanded to a change in price", "total revenue earned from selling a good", "absolute change in price of a good", "cost of producing an additional unit of a good"], "responsiveness of quantity demanded to a change in price",
      "Price elasticity of demand (percentage change in quantity demanded / percentage change in price) shows how sensitive consumer purchasing is to price changes."),
  _q("A good is said to have elastic demand when",
      ["a small percentage change in price causes a proportionately larger percentage change in quantity demanded", "quantity demanded does not change at all when price changes", "a large percentage change in price causes a smaller percentage change in quantity demanded", "the price of the good has no effect on any other good"], "a small percentage change in price causes a proportionately larger percentage change in quantity demanded",
      "Elastic demand (elasticity greater than 1) means consumers are highly responsive to price changes, so quantity demanded changes proportionately more than price."),
  _q("Necessities such as salt typically have _____ demand, since consumers must buy them regardless of price changes.",
      ["inelastic", "perfectly elastic", "highly elastic", "unitary elastic"], "inelastic",
      "Goods considered necessities tend to have inelastic demand (elasticity less than 1), since consumers continue purchasing similar quantities even when price rises."),
  _q("Complementary goods, such as bread and butter, are characterised by the fact that a rise in the price of one",
      ["leads to a fall in the demand for the other", "leads to a rise in the demand for the other", "has no effect whatsoever on the demand for the other", "always causes both goods to disappear from the market"], "leads to a fall in the demand for the other",
      "Complementary goods are used together, so a price rise in one (reducing its quantity demanded) also reduces demand for the other good typically consumed alongside it."),
  _q("Substitute goods, such as tea and coffee, are characterised by the fact that a rise in the price of one",
      ["leads to a rise in the demand for the other", "leads to a fall in the demand for the other", "has no effect on the demand for the other", "causes both goods to become complementary"], "leads to a rise in the demand for the other",
      "When the price of one substitute good rises, consumers tend to switch to the relatively cheaper alternative, increasing demand for the substitute good."),
];

final _consumerBehaviour = [
  _q("Total utility refers to the",
      ["overall satisfaction a consumer derives from consuming a given quantity of a good", "price paid for a unit of a good", "additional satisfaction from consuming one more unit of a good", "cost of producing a good"], "overall satisfaction a consumer derives from consuming a given quantity of a good",
      "Total utility measures the entire satisfaction gained from consuming a certain total amount of a good or service, accumulating as more units are consumed."),
  _q("Marginal utility is defined as the",
      ["additional satisfaction gained from consuming one more unit of a good", "total satisfaction from all units consumed", "average price of all units consumed", "cost of the last unit produced"], "additional satisfaction gained from consuming one more unit of a good",
      "Marginal utility is the extra utility (satisfaction) a consumer gains from consuming one additional unit of a good, beyond what was already consumed."),
  _q("The Law of Diminishing Marginal Utility states that as a consumer consumes more units of a good,",
      ["the additional satisfaction gained from each successive unit tends to decrease", "the additional satisfaction from each successive unit tends to increase", "total utility always decreases", "the price of the good automatically falls"], "the additional satisfaction gained from each successive unit tends to decrease",
      "This law explains that, beyond a certain point, each extra unit of a good consumed yields progressively less additional satisfaction than the unit before it."),
  _q("A rational consumer aims to maximise total utility by allocating income such that the",
      ["marginal utility per naira spent is equal across all goods purchased", "entire income is spent on a single good only", "cheapest good available is always purchased exclusively", "most expensive good available is always purchased exclusively"], "marginal utility per naira spent is equal across all goods purchased",
      "Utility-maximising behaviour occurs when a consumer allocates spending so that the marginal utility obtained per unit of currency is equalised across all goods bought."),
  _q("The point at which marginal utility becomes zero indicates that the consumer has reached",
      ["maximum total utility from consuming that good", "zero total utility from the good", "a state where the good is no longer needed at any price", "the minimum possible price for the good"], "maximum total utility from consuming that good",
      "Total utility is at its peak precisely when marginal utility (the addition to total utility) falls to zero; consuming further units beyond this point would begin to reduce total utility."),
  _q("Which of the following best illustrates the Law of Diminishing Marginal Utility?",
      ["The satisfaction gained from eating the fourth slice of bread is less than that from the first slice", "A consumer buying more of a good as its price falls", "A firm producing more output as its costs decrease", "A government increasing tax rates on luxury goods"], "The satisfaction gained from eating the fourth slice of bread is less than that from the first slice",
      "As successive units of the same good are consumed within a given period, each additional unit typically yields less extra satisfaction than the one before, exactly as the law describes."),
];

final _productionAndCosts = [
  _q("Fixed costs of production are costs that",
      ["do not change with the level of output in the short run", "vary directly and proportionately with output", "only occur when output is zero", "are always higher than variable costs"], "do not change with the level of output in the short run",
      "Fixed costs (e.g., rent, insurance) remain constant regardless of how much is produced in the short run, unlike variable costs, which change with output level."),
  _q("Variable costs of production are costs that",
      ["change directly with the level of output produced", "remain constant regardless of output level", "are incurred only once, at the start of production", "never change over the life of a business"], "change directly with the level of output produced",
      "Variable costs (e.g., raw materials, hourly wages) rise and fall with the quantity of output produced, unlike fixed costs."),
  _q("Total cost of production is calculated as the",
      ["sum of total fixed cost and total variable cost", "difference between total fixed and total variable cost", "total revenue minus total profit", "average cost multiplied by fixed cost"], "sum of total fixed cost and total variable cost",
      "Total Cost (TC) = Total Fixed Cost (TFC) + Total Variable Cost (TVC), combining both cost components at a given output level."),
  _q("Average cost of production is calculated by",
      ["dividing total cost by the quantity of output produced", "multiplying total cost by the quantity of output", "subtracting fixed cost from total cost", "dividing total revenue by total cost"], "dividing total cost by the quantity of output produced",
      "Average cost (AC = TC/Q) shows the cost incurred per unit of output produced, a key measure for assessing production efficiency."),
  _q("Marginal cost is defined as the",
      ["additional cost incurred from producing one more unit of output", "total cost of producing all units", "average cost of production at the maximum output level", "fixed cost divided by variable cost"], "additional cost incurred from producing one more unit of output",
      "Marginal cost (MC) measures the extra cost a firm incurs by producing one additional unit of output, crucial for output and pricing decisions."),
  _q("The Law of Diminishing Returns states that as more units of a variable factor are added to a fixed factor, eventually",
      ["the additional (marginal) output from each extra unit of the variable factor will decrease", "output will increase indefinitely at a constant rate", "total output will immediately fall to zero", "the fixed factor becomes variable"], "the additional (marginal) output from each extra unit of the variable factor will decrease",
      "This law describes short-run production: beyond an optimal point, adding more of a variable input (e.g., labour) to fixed factors (e.g., land) yields progressively smaller marginal output."),
  _q("Economies of scale refer to the",
      ["reduction in average cost of production as a firm increases its scale (size) of output", "increase in average cost as output rises", "fixed costs incurred regardless of firm size", "total cost of producing a single unit of output"], "reduction in average cost of production as a firm increases its scale (size) of output",
      "Economies of scale occur when a firm's average cost per unit falls as it expands production, often due to specialisation, bulk purchasing, or more efficient use of resources."),
  _q("Diseconomies of scale occur when a firm expands beyond an optimal size, resulting in",
      ["rising average costs due to inefficiencies such as poor coordination and communication", "continuously falling average costs", "constant average costs regardless of size", "an automatic increase in profit"], "rising average costs due to inefficiencies such as poor coordination and communication",
      "Beyond a certain size, further expansion can create management and coordination difficulties, causing average costs to rise rather than continue falling."),
  _q("Total revenue of a firm is calculated as",
      ["price per unit multiplied by the quantity of units sold", "total cost minus total profit", "average cost multiplied by fixed cost", "marginal cost multiplied by output"], "price per unit multiplied by the quantity of units sold",
      "Total Revenue (TR) = Price (P) x Quantity sold (Q), representing the total income a firm earns from selling its output."),
  _q("Profit is calculated as the",
      ["difference between total revenue and total cost", "sum of total revenue and total cost", "product of total revenue and total cost", "average of total revenue and total cost"], "difference between total revenue and total cost",
      "Profit = Total Revenue - Total Cost; a positive value indicates the firm earns more than it spends, while a negative value indicates a loss."),
];

final _marketStructures = [
  _q("Perfect competition is a market structure characterised by",
      ["many buyers and sellers, homogeneous products, and free entry and exit", "a single seller controlling the entire market", "a few large firms dominating the market", "product differentiation as the main basis of competition"], "many buyers and sellers, homogeneous products, and free entry and exit",
      "Perfect competition assumes numerous small firms selling identical products, with no barriers to entering or leaving the industry, and no single firm able to influence price."),
  _q("A monopoly market structure exists when",
      ["a single firm is the sole supplier of a good or service with no close substitutes", "many firms sell identical products", "a few large firms dominate the market", "firms compete mainly through product differentiation"], "a single firm is the sole supplier of a good or service with no close substitutes",
      "Monopoly describes a market dominated entirely by one seller, who therefore has significant control over price due to the absence of close substitute products."),
  _q("Monopolistic competition is a market structure in which",
      ["many firms sell similar but slightly differentiated products", "only one firm supplies the entire market", "a few large firms dominate through interdependent pricing decisions", "products are completely identical across all sellers"], "many firms sell similar but slightly differentiated products",
      "Monopolistic competition combines features of competition (many sellers) and monopoly (product differentiation), as firms sell similar goods marketed as distinct through branding."),
  _q("An oligopoly market structure is characterised by",
      ["a small number of large firms dominating the market, often with interdependent pricing decisions", "an unlimited number of small firms", "one firm controlling the entire supply", "completely homogeneous products with no branding at all"], "a small number of large firms dominating the market, often with interdependent pricing decisions",
      "In oligopoly, a few large firms dominate the industry, and each firm's decisions (especially on price) significantly affect and are affected by rivals' actions."),
  _q("Under perfect competition, an individual firm is considered a 'price taker' because it",
      ["has no power to influence the market price and must accept the prevailing price", "sets its own price independently of the market", "can charge different prices to different customers", "controls the total market supply"], "has no power to influence the market price and must accept the prevailing price",
      "Since each firm in perfect competition is small relative to the whole market and sells an identical product, it must sell at the market-determined price."),
  _q("A key barrier to entry that helps sustain a monopoly is",
      ["exclusive control over a key resource, patent, or government licence", "the presence of many competing firms", "perfectly homogeneous products across the industry", "zero fixed costs of production"], "exclusive control over a key resource, patent, or government licence",
      "Monopolies are often sustained by barriers to entry such as patents, exclusive licences, or sole control of an essential resource, preventing competitors from entering the market."),
  _q("Price discrimination, sometimes practised by a monopolist, involves",
      ["charging different prices to different groups of consumers for the same product", "charging the same price to all consumers regardless of circumstances", "always charging the lowest possible price to all consumers", "eliminating all price differences in a market"], "charging different prices to different groups of consumers for the same product",
      "Price discrimination allows a firm with market power to charge different consumer segments different prices for an identical good, maximising its revenue."),
  _q("Advertising and branding are commonly used as competitive tools mainly in which market structure?",
      ["Monopolistic competition", "Perfect competition", "Pure monopoly with no substitutes", "None of these market structures"], "Monopolistic competition",
      "Since firms in monopolistic competition sell similar products, they rely heavily on advertising and branding to differentiate their goods and attract customers."),
  _q("Which of the following market structures has the largest number of buyers and sellers, with no single participant able to affect price?",
      ["Perfect competition", "Monopoly", "Oligopoly", "Monopolistic competition"], "Perfect competition",
      "Perfect competition, by definition, involves the greatest number of small, price-taking buyers and sellers, none of whom can individually influence market price."),
  _q("A cartel, sometimes formed under an oligopoly, refers to an agreement among firms to",
      ["collude on price and output levels to reduce competition among themselves", "compete aggressively on price to gain market share", "merge into a single large monopoly firm", "eliminate all forms of advertising"], "collude on price and output levels to reduce competition among themselves",
      "A cartel is a formal or informal agreement among typically oligopolistic firms to coordinate pricing and output, effectively reducing competition and behaving somewhat like a monopoly."),
];

final _nationalIncome = [
  _q("Gross Domestic Product (GDP) is defined as the total value of",
      ["all final goods and services produced within a country's borders in a given period", "goods and services produced by a country's citizens abroad only", "raw materials extracted from a country", "government spending alone in a fiscal year"], "all final goods and services produced within a country's borders in a given period",
      "GDP measures the market value of all final goods and services produced domestically (within the country's borders) over a specific time period, usually a year."),
  _q("Gross National Product (GNP) differs from GDP mainly in that GNP includes",
      ["income earned by a country's citizens both domestically and abroad, but excludes income earned by foreigners within the country", "only domestic production within the country's borders", "only government expenditure", "only exports and excludes all imports"], "income earned by a country's citizens both domestically and abroad, but excludes income earned by foreigners within the country",
      "GNP measures output produced by a nation's citizens and businesses regardless of location, while GDP measures output produced within the country's borders regardless of nationality."),
  _q("Net National Product (NNP) is obtained by",
      ["subtracting depreciation (capital consumption) from Gross National Product", "adding depreciation to Gross National Product", "subtracting exports from Gross National Product", "adding government transfer payments to GDP"], "subtracting depreciation (capital consumption) from Gross National Product",
      "NNP = GNP - Depreciation, accounting for the wearing out of capital equipment during the production process over the period measured."),
  _q("Which of the following is a common method of measuring national income?",
      ["The income method, output method, and expenditure method", "Only the taxation method", "Only the import-export method", "Only the population census method"], "The income method, output method, and expenditure method",
      "National income can be estimated using three approaches: summing incomes earned, summing the value of output produced, or summing total expenditure, which should theoretically yield the same total."),
  _q("The circular flow of income model illustrates the",
      ["flow of income and expenditure between households and firms in an economy", "flow of exports and imports between two countries", "structure of a country's banking system alone", "process of setting the exchange rate"], "flow of income and expenditure between households and firms in an economy",
      "The circular flow model shows how households supply factors of production to firms in exchange for income, which they then spend on goods and services produced by those firms."),
  _q("Per capita income is calculated by",
      ["dividing a country's total national income by its total population", "multiplying national income by the population", "subtracting the population from national income", "dividing the government budget by national income"], "dividing a country's total national income by its total population",
      "Per capita income (national income / population) provides an average measure of income per person, often used as a rough indicator of living standards."),
  _q("Which of the following would be excluded when calculating a country's GDP to avoid double counting?",
      ["The value of intermediate goods used up in producing final goods", "The value of final consumer goods", "Government spending on public services", "Exports of finished manufactured goods"], "The value of intermediate goods used up in producing final goods",
      "Only final goods and services are counted in GDP; including the value of intermediate goods (already embedded in the price of final goods) would result in double counting."),
];

final _moneyBankingInflation = [
  _q("Money performs several key functions, including serving as a",
      ["medium of exchange, store of value, and unit of account", "physical raw material for industry", "type of tax levied by government", "form of agricultural produce"], "medium of exchange, store of value, and unit of account",
      "Money's core functions include facilitating trade (medium of exchange), preserving value over time (store of value), and providing a common measure of value (unit of account)."),
  _q("Before the introduction of money, trade was conducted mainly through",
      ["the barter system, involving direct exchange of goods for goods", "electronic bank transfers", "the use of cheques", "credit cards"], "the barter system, involving direct exchange of goods for goods",
      "Barter, the direct exchange of goods and services without money, was the primary trading method before money was introduced, but it suffered from the problem of the 'double coincidence of wants'."),
  _q("The Central Bank of a country is primarily responsible for",
      ["regulating the money supply and overseeing the banking system", "manufacturing consumer goods for export", "setting the retail prices of all goods", "collecting personal income tax directly from workers"], "regulating the money supply and overseeing the banking system",
      "A country's central bank (e.g., the Central Bank of Nigeria) controls monetary policy, regulates commercial banks, and manages the overall money supply and currency stability."),
  _q("Commercial banks primarily function to",
      ["accept deposits from customers and provide loans and other banking services", "print the national currency", "set national fiscal policy", "regulate international trade agreements"], "accept deposits from customers and provide loans and other banking services",
      "Commercial banks serve as intermediaries between savers and borrowers, taking deposits and extending credit (loans) to individuals and businesses, unlike the central bank, which regulates the whole system."),
  _q("Inflation is best defined as a",
      ["persistent and sustained rise in the general price level of goods and services", "one-time increase in the price of a single good", "fall in the general price level over time", "fixed exchange rate policy"], "persistent and sustained rise in the general price level of goods and services",
      "Inflation refers to an ongoing, generalised increase in prices across an economy over time, which reduces the purchasing power of money."),
  _q("Demand-pull inflation occurs mainly when",
      ["aggregate demand in the economy exceeds the available aggregate supply", "the cost of production inputs rises significantly", "the government reduces the money supply", "there is a sudden increase in unemployment"], "aggregate demand in the economy exceeds the available aggregate supply",
      "Demand-pull inflation arises when total spending in an economy outpaces the economy's capacity to produce goods and services, pushing prices upward."),
  _q("Cost-push inflation occurs mainly when",
      ["rising costs of production, such as wages or raw materials, push up the general price level", "aggregate demand falls sharply", "the government increases interest rates", "the exchange rate strengthens significantly"], "rising costs of production, such as wages or raw materials, push up the general price level",
      "Cost-push inflation results from increased costs of production (e.g., wage rises, raw material price increases), which firms pass on to consumers as higher prices."),
  _q("Which of the following is a common measure taken by a central bank to control inflation?",
      ["Raising interest rates to reduce borrowing and spending", "Lowering interest rates to encourage more borrowing", "Increasing government subsidies on all goods", "Removing all taxes on imported goods"], "Raising interest rates to reduce borrowing and spending",
      "Central banks often raise interest rates during inflationary periods to discourage borrowing and spending, cooling down aggregate demand and easing upward pressure on prices."),
  _q("Deflation refers to a sustained",
      ["fall in the general price level of goods and services", "rise in the general price level of goods and services", "increase in government expenditure", "increase in the exchange rate of a currency"], "fall in the general price level of goods and services",
      "Deflation is the opposite of inflation: a persistent decrease in the overall price level in an economy, which can also cause economic difficulties like reduced spending."),
  _q("The demand for money to carry out everyday transactions is known as the",
      ["transactionary motive for holding money", "speculative motive for holding money", "precautionary motive against inflation only", "investment motive for holding bonds"], "transactionary motive for holding money",
      "Keynes identified the transactionary motive as the need to hold money to cover routine, planned day-to-day purchases and expenses."),
];

final _publicFinance = [
  _q("Public finance is the branch of economics concerned with the",
      ["revenue, expenditure, and debt management of government", "profit-making activities of private firms", "personal savings decisions of households", "trade agreements between two private companies"], "revenue, expenditure, and debt management of government",
      "Public finance studies how governments raise revenue (mainly through taxation), spend it on public goods and services, and manage public debt."),
  _q("A major source of government revenue in most economies is",
      ["taxation", "personal loans from citizens", "foreign remittances from individuals", "private charitable donations"], "taxation",
      "Taxation, in its various forms (income tax, VAT, customs duties, etc.), is typically the largest and most reliable source of revenue for national governments."),
  _q("A balanced government budget occurs when",
      ["government revenue equals government expenditure", "government revenue exceeds government expenditure", "government expenditure exceeds government revenue", "the government has no revenue at all"], "government revenue equals government expenditure",
      "A balanced budget is achieved when total planned government spending exactly matches total planned government revenue over a fiscal period."),
  _q("A budget deficit occurs when",
      ["government expenditure exceeds government revenue", "government revenue exceeds government expenditure", "government revenue equals government expenditure", "the government eliminates all forms of spending"], "government expenditure exceeds government revenue",
      "A deficit budget arises when planned government spending is greater than the revenue collected, often requiring the government to borrow to cover the shortfall."),
  _q("A budget surplus occurs when",
      ["government revenue exceeds government expenditure", "government expenditure exceeds government revenue", "government revenue equals government expenditure", "the government has zero revenue"], "government revenue exceeds government expenditure",
      "A surplus budget occurs when the government collects more revenue than it spends within a given fiscal period."),
  _q("Public debt refers to the",
      ["total amount of money owed by a government to domestic and foreign creditors", "total taxes collected by a government in a year", "total value of goods exported by a country", "total income earned by government employees"], "total amount of money owed by a government to domestic and foreign creditors",
      "Public debt represents the accumulated borrowing a government has undertaken, often to finance budget deficits, owed to both local and international lenders."),
];

final _internationalTradeOrganizations = [
  _q("The theory of absolute advantage states that a country should specialise in producing goods it can produce",
      ["more efficiently (using fewer resources) than other countries", "at exactly the same efficiency as other countries", "only for its own domestic consumption", "using the most expensive available technology"], "more efficiently (using fewer resources) than other countries",
      "Adam Smith's theory of absolute advantage suggests countries benefit from trade by specialising in goods they can produce using fewer resources than their trading partners."),
  _q("The theory of comparative advantage suggests that a country should specialise in producing goods for which it has the",
      ["lowest opportunity cost compared to other countries, even without an absolute advantage", "highest opportunity cost among all its industries", "largest absolute advantage over all trading partners", "government subsidy support only"], "lowest opportunity cost compared to other countries, even without an absolute advantage",
      "David Ricardo's comparative advantage theory shows that countries gain from trade by specialising in goods where their opportunity cost is relatively lowest, even if they have no absolute advantage in anything."),
  _q("The balance of trade refers to the difference between a country's",
      ["total value of exports and total value of imports of goods", "government revenue and government expenditure", "total savings and total investment", "money supply and demand for money"], "total value of exports and total value of imports of goods",
      "The balance of trade specifically measures the difference between the value of a country's merchandise exports and imports over a period."),
  _q("A favourable balance of trade occurs when a country's",
      ["exports exceed its imports", "imports exceed its exports", "exports equal its imports exactly", "government budget is balanced"], "exports exceed its imports",
      "A trade surplus (favourable balance of trade) exists when the value of a country's exports is greater than the value of its imports."),
  _q("The balance of payments is a broader record than the balance of trade because it includes",
      ["all financial transactions between a country and the rest of the world, including trade, services, and capital flows", "only the trade in physical merchandise goods", "only government-to-government financial aid", "only stock market transactions"], "all financial transactions between a country and the rest of the world, including trade, services, and capital flows",
      "The balance of payments records all economic transactions with the rest of the world, encompassing the trade balance plus services, income flows, and capital/financial account movements."),
  _q("An exchange rate is best defined as the",
      ["price of one country's currency expressed in terms of another currency", "total value of a country's exports", "interest rate set by a country's central bank", "tax rate imposed on imported goods"], "price of one country's currency expressed in terms of another currency",
      "The exchange rate specifies how much of one currency must be given up to obtain a unit of another currency, essential for international trade and finance."),
  _q("ECOWAS (Economic Community of West African States) was established mainly to promote",
      ["economic cooperation and integration among West African countries", "military alliances among European nations", "trade exclusively between Nigeria and the United States", "the standardisation of global currencies"], "economic cooperation and integration among West African countries",
      "ECOWAS is a regional economic organisation aimed at fostering trade, economic integration, and cooperation among its member states in West Africa."),
  _q("The International Monetary Fund (IMF) primarily assists member countries by",
      ["providing financial assistance and policy advice to promote monetary cooperation and economic stability", "manufacturing goods for export on behalf of member states", "setting domestic tax rates for its member countries", "directly managing member countries' agricultural sectors"], "providing financial assistance and policy advice to promote monetary cooperation and economic stability",
      "The IMF works to foster global monetary cooperation, financial stability, and sustainable economic growth, often providing loans and policy guidance to countries facing balance of payments difficulties."),
  _q("The World Bank primarily focuses on providing",
      ["long-term loans and financial/technical assistance for development projects in member countries", "short-term currency stabilisation loans only", "military support to developing nations", "direct cash transfers to individual citizens"], "long-term loans and financial/technical assistance for development projects in member countries",
      "Unlike the IMF's focus on monetary stability, the World Bank primarily funds long-term development projects (infrastructure, education, health) in developing countries."),
];

final _nigerianEconomy = [
  _q("Historically, before the discovery of oil, the mainstay of the Nigerian economy was",
      ["agriculture", "petroleum", "manufacturing of automobiles", "information technology services"], "agriculture",
      "Prior to the oil boom, Nigeria's economy relied heavily on agricultural exports such as cocoa, groundnut, palm oil, and cotton for foreign exchange and employment."),
  _q("Which of the following is a major problem currently facing agriculture in Nigeria?",
      ["Reliance on outdated farming methods and inadequate infrastructure", "Excessive government funding for agricultural research", "Overproduction of food crops beyond domestic and export needs", "Too many young people going into farming"], "Reliance on outdated farming methods and inadequate infrastructure",
      "Nigerian agriculture continues to be hampered by traditional farming techniques, poor rural infrastructure (roads, storage), and limited access to modern inputs and credit."),
  _q("Industrialization refers to the process by which an economy transforms from being primarily",
      ["agrarian to one dominated by manufacturing and industrial activities", "industrial to primarily agricultural", "service-based to purely agricultural", "monetary to purely barter-based"], "agrarian to one dominated by manufacturing and industrial activities",
      "Industrialization describes the structural shift of an economy from reliance on agriculture toward greater manufacturing and industrial production."),
  _q("Which of the following is a significant challenge to industrialization in Nigeria?",
      ["Inadequate and unreliable power (electricity) supply", "Excess availability of skilled industrial labour", "Overregulation preventing any foreign investment whatsoever", "Complete absence of raw materials nationwide"], "Inadequate and unreliable power (electricity) supply",
      "Unreliable electricity supply significantly raises production costs and discourages both local and foreign investment in Nigerian manufacturing industries."),
  _q("Population growth in Nigeria presents an economic challenge mainly because it can lead to",
      ["pressure on limited resources, unemployment, and strain on social infrastructure", "an automatic and immediate rise in per capita income", "a permanent reduction in the labour force", "a decrease in the demand for goods and services"], "pressure on limited resources, unemployment, and strain on social infrastructure",
      "Rapid population growth, if not matched by corresponding economic growth, can strain available resources, increase unemployment, and overburden schools, hospitals, and other infrastructure."),
  _q("The labour market in Nigeria is often characterised by",
      ["a high rate of unemployment and underemployment, especially among youths", "a persistent shortage of available workers in all sectors", "guaranteed full employment for all job seekers", "an absence of any informal sector employment"], "a high rate of unemployment and underemployment, especially among youths",
      "Nigeria faces significant challenges of unemployment and underemployment, particularly affecting young graduates, due to a mismatch between labour supply and available formal jobs."),
  _q("Diversification of the Nigerian economy refers to efforts to",
      ["reduce dependence on oil revenue by developing other sectors such as agriculture and manufacturing", "increase the country's reliance solely on crude oil exports", "eliminate the agricultural sector entirely", "focus exclusively on the service sector"], "reduce dependence on oil revenue by developing other sectors such as agriculture and manufacturing",
      "Economic diversification aims to broaden Nigeria's revenue base beyond oil by strengthening other productive sectors, reducing vulnerability to oil price shocks."),
  _q("The informal sector of the Nigerian economy typically consists of",
      ["small-scale, often unregistered businesses and self-employed workers operating outside formal regulation", "large multinational corporations only", "government ministries and parastatals", "publicly listed companies on the stock exchange"], "small-scale, often unregistered businesses and self-employed workers operating outside formal regulation",
      "The informal sector includes small traders, artisans, and self-employed individuals who typically operate without formal registration, taxation, or regulatory oversight, but who provide significant employment."),
];
