import "../quiz_question.dart";

const _subject = "Physics";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// JAMB Physics — 100 questions covering the 13 core UTME topics:
/// Measurements & Units, Scalars & Vectors, Motion, Gravitational Field,
/// Equilibrium of Forces, Work/Energy/Power, Friction & Simple Machines,
/// Properties of Matter, Thermal Physics, Waves & Sound, Optics,
/// Electricity & Magnetism, and Modern Physics.
List<QuizQuestion> buildJambPhysicsQuestions() {
  return [
    ..._measurementsUnits,
    ..._scalarsVectors,
    ..._motion,
    ..._gravitationalField,
    ..._equilibriumForces,
    ..._workEnergyPower,
    ..._frictionSimpleMachines,
    ..._propertiesOfMatter,
    ..._thermalPhysics,
    ..._wavesSound,
    ..._optics,
    ..._electricityMagnetism,
    ..._modernPhysics,
  ];
}

final _measurementsUnits = [
  _q("The S.I. unit of electric current is the",
      ["ampere", "coulomb", "volt", "ohm"], "ampere",
      "The ampere (A) is one of the seven base S.I. units, defined as the base unit of electric current."),
  _q("Which instrument is used to measure the diameter of a thin wire to the nearest 0.01 mm?",
      ["Micrometer screw gauge", "Vernier calipers", "Metre rule", "Measuring tape"], "Micrometer screw gauge",
      "The micrometer screw gauge has a much finer scale (typically 0.01 mm precision) than Vernier calipers (0.01 cm), making it suited to very thin objects like wires."),
  _q("Vernier calipers are typically used to measure internal and external diameters to the nearest",
      ["0.01 cm", "0.01 mm", "1 cm", "0.1 m"], "0.01 cm",
      "Vernier calipers commonly have a precision of 0.01 cm (0.1 mm), useful for measuring lengths, diameters, and depths more precisely than a metre rule."),
  _q("The number 0.004530 expressed to 3 significant figures is",
      ["0.00453", "0.0045", "0.004", "0.00450"], "0.00453",
      "Counting significant figures from the first non-zero digit: 4, 5, 3 are the first three significant figures, giving 0.00453."),
  _q("Which of the following is a derived S.I. unit?",
      ["Newton (force)", "Metre (length)", "Kilogram (mass)", "Kelvin (temperature)"], "Newton (force)",
      "The newton is derived from the base units kg, m, and s (N = kg m/s2), unlike the metre, kilogram, and kelvin, which are base units."),
  _q("The dimension of density (mass/volume) is",
      ["ML-3", "MLT-2", "ML2T-2", "MLT-1"], "ML-3",
      "Density = mass/volume = M / L3 = ML-3, since volume has dimension L3 (length cubed)."),
];

final _scalarsVectors = [
  _q("A scalar quantity is one that has",
      ["magnitude only, with no direction", "both magnitude and direction", "direction only, with no magnitude", "neither magnitude nor direction"], "magnitude only, with no direction",
      "Scalars, such as mass, distance, and speed, are fully described by a magnitude alone, unlike vectors, which also require a direction."),
  _q("Which of the following is a vector quantity?",
      ["Displacement", "Mass", "Time", "Energy"], "Displacement",
      "Displacement has both magnitude and a specified direction from a starting point, making it a vector, unlike mass, time, and energy, which are scalars."),
  _q("Two forces of 3 N and 4 N act at right angles to each other on an object. What is the magnitude of the resultant force?",
      ["5 N", "7 N", "1 N", "12 N"], "5 N",
      "Using Pythagoras' theorem for perpendicular vectors: resultant = sqrt(3^2 + 4^2) = sqrt(9+16) = sqrt(25) = 5 N."),
  _q("The horizontal component of a force of 10 N acting at 30 degrees to the horizontal is",
      ["10 cos 30 degrees", "10 sin 30 degrees", "10 tan 30 degrees", "10 / cos 30 degrees"], "10 cos 30 degrees",
      "The horizontal component of a vector is found by multiplying its magnitude by the cosine of the angle it makes with the horizontal axis."),
  _q("A boat heads directly across a river with its own velocity, while the river current pushes it downstream. The boat's resultant velocity relative to the bank is found by",
      ["vector addition of the boat's velocity and the river's velocity", "simple arithmetic subtraction of the two speeds", "multiplying the two velocities together", "the boat's velocity alone, ignoring the current"], "vector addition of the boat's velocity and the river's velocity",
      "Relative velocity problems are solved by vector addition, combining the boat's velocity relative to water with the water's velocity relative to the bank."),
  _q("Which method can be used to find the resultant of two vectors acting at an angle to each other?",
      ["The parallelogram law of vector addition", "Simple scalar addition only", "Direct multiplication of magnitudes", "Averaging their magnitudes"], "The parallelogram law of vector addition",
      "The parallelogram law states that two vectors can be represented as adjacent sides of a parallelogram, with the resultant being the diagonal from their common point."),
];

final _motion = [
  _q("An object starts from rest and accelerates uniformly at 2 m/s2 for 5 seconds. What is its final velocity?",
      ["10 m/s", "2 m/s", "7 m/s", "25 m/s"], "10 m/s",
      "Using v = u + at: v = 0 + (2 x 5) = 10 m/s, since the object starts from rest (u = 0)."),
  _q("A car travels at a constant velocity of 20 m/s for 10 seconds. What distance does it cover?",
      ["200 m", "20 m", "100 m", "2 m"], "200 m",
      "Distance = velocity x time = 20 x 10 = 200 m, since the velocity is constant (zero acceleration)."),
  _q("A body moving with uniform acceleration covers a distance given by s = ut + 1/2 at^2. If u = 0, a = 4 m/s2, and t = 3 s, what is s?",
      ["18 m", "12 m", "24 m", "6 m"], "18 m",
      "s = 0(3) + 0.5(4)(3^2) = 0 + 0.5 x 4 x 9 = 18 m."),
  _q("Newton's First Law of Motion states that a body will remain at rest or in uniform motion in a straight line unless",
      ["acted upon by an external unbalanced force", "it loses mass over time", "it is in a vacuum", "its velocity is zero"], "acted upon by an external unbalanced force",
      "This is the law of inertia: an object's state of motion changes only when a net external force acts on it."),
  _q("Newton's Second Law of Motion is mathematically expressed as",
      ["F = ma", "F = mv", "F = m/a", "F = ma^2"], "F = ma",
      "Newton's Second Law states that force equals the rate of change of momentum, which for constant mass simplifies to F = ma (mass x acceleration)."),
  _q("A resultant force of 20 N acts on a mass of 4 kg. What acceleration does it produce?",
      ["5 m/s2", "80 m/s2", "0.2 m/s2", "16 m/s2"], "5 m/s2",
      "Using F = ma: a = F/m = 20/4 = 5 m/s2."),
  _q("Newton's Third Law of Motion states that",
      ["for every action, there is an equal and opposite reaction", "force equals mass times acceleration", "momentum is always conserved in a closed system", "an object at rest stays at rest unless acted upon"], "for every action, there is an equal and opposite reaction",
      "Newton's Third Law describes the mutual nature of forces: whenever one body exerts a force on another, the second exerts an equal and opposite force back on the first."),
  _q("The momentum of a body is defined as the product of its",
      ["mass and velocity", "mass and acceleration", "weight and velocity", "force and time"], "mass and velocity",
      "Momentum (p) = mass (m) x velocity (v), a vector quantity with the same direction as the velocity."),
  _q("A 2 kg object moving at 3 m/s collides and comes to rest in 0.5 s. What is the impulse delivered to it?",
      ["6 Ns", "1.5 Ns", "12 Ns", "3 Ns"], "6 Ns",
      "Impulse = change in momentum = m(v-u) = 2(0-3) in magnitude = 6 Ns, the momentum lost by the object during the collision."),
  _q("In Simple Harmonic Motion (SHM), the acceleration of the oscillating body is always",
      ["directly proportional to its displacement from equilibrium and directed towards it", "constant throughout the motion", "directly proportional to its velocity", "zero at the extreme positions"], "directly proportional to its displacement from equilibrium and directed towards it",
      "SHM is defined by acceleration a = -omega^2 x, proportional to displacement x but directed opposite to it, always pulling the body back to equilibrium."),
  _q("A body undergoing projectile motion (ignoring air resistance) experiences which acceleration in the horizontal direction?",
      ["Zero (constant horizontal velocity)", "Acceleration due to gravity, g", "Increasing acceleration over time", "Acceleration equal to the initial vertical velocity"], "Zero (constant horizontal velocity)",
      "In projectile motion, gravity acts only vertically, so the horizontal component of velocity remains constant throughout the flight (zero horizontal acceleration)."),
  _q("The time taken for a projectile to reach maximum height depends on its",
      ["initial vertical component of velocity and the acceleration due to gravity", "initial horizontal velocity only", "mass of the projectile", "angle of projection only, independent of speed"], "initial vertical component of velocity and the acceleration due to gravity",
      "Time to maximum height, t = u_vertical / g, depends on the vertical component of the initial velocity and the local gravitational acceleration."),
];

final _gravitationalField = [
  _q("Newton's Law of Universal Gravitation states that the gravitational force between two masses is",
      ["directly proportional to the product of their masses and inversely proportional to the square of the distance between them", "inversely proportional to the product of their masses", "directly proportional to the distance between them", "independent of the distance between them"], "directly proportional to the product of their masses and inversely proportional to the square of the distance between them",
      "F = Gm1m2/r^2, showing gravitational attraction increases with mass and decreases sharply (inverse square) with increasing separation."),
  _q("The acceleration due to gravity, g, on the Earth's surface is approximately",
      ["9.8 m/s2", "6.4 m/s2", "3.8 m/s2", "1.6 m/s2"], "9.8 m/s2",
      "The standard value for acceleration due to gravity near the Earth's surface is approximately 9.8 m/s2 (sometimes approximated as 10 m/s2)."),
  _q("The value of g decreases as one moves from the Earth's surface towards its centre mainly because",
      ["only the mass of Earth enclosed within that radius contributes to the gravitational pull", "the Earth's rotation increases with depth", "temperature decreases towards the centre", "air resistance increases underground"], "only the mass of Earth enclosed within that radius contributes to the gravitational pull",
      "Inside a uniform sphere, only the mass enclosed within the radius from the centre contributes net gravitational force, so g decreases towards the centre, reaching zero there."),
  _q("Escape velocity is defined as the minimum velocity needed for an object to",
      ["completely escape a planet's gravitational field without further propulsion", "orbit a planet at a constant altitude", "reach the speed of sound", "achieve a stable circular orbit close to the surface"], "completely escape a planet's gravitational field without further propulsion",
      "Escape velocity is the speed at which an object's kinetic energy equals the gravitational potential energy binding it, allowing it to escape to infinity."),
  _q("The weight of an object is best described as",
      ["the gravitational force acting on its mass", "the amount of matter it contains", "a measure independent of gravitational field strength", "the same everywhere in the universe"], "the gravitational force acting on its mass",
      "Weight (W = mg) is a force resulting from the gravitational pull on an object's mass, and therefore varies with the local gravitational field strength, unlike mass."),
  _q("A satellite in a stable circular orbit around the Earth experiences a centripetal force provided by",
      ["the Earth's gravitational attraction on the satellite", "the satellite's engines firing continuously", "atmospheric drag", "the satellite's own inertia alone"], "the Earth's gravitational attraction on the satellite",
      "For a satellite in circular orbit, gravity supplies exactly the centripetal force needed to keep it moving in its circular path around the Earth."),
];

final _equilibriumForces = [
  _q("The centre of gravity of an object is the point at which",
      ["the entire weight of the object may be considered to act", "all external forces cancel to zero", "the object's mass is exactly zero", "the object rotates fastest"], "the entire weight of the object may be considered to act",
      "The centre of gravity is the single point through which the resultant of all gravitational forces on the parts of a body can be considered to act."),
  _q("An object is in stable equilibrium if, when slightly displaced, it",
      ["returns to its original position", "moves further away from its original position", "remains in its new position permanently", "topples over immediately"], "returns to its original position",
      "Stable equilibrium is characterised by a restoring tendency: a small displacement raises the centre of gravity, and gravity pulls the object back to its lowest-energy position."),
  _q("A body with a low centre of gravity and a wide base is generally",
      ["more stable than one with a high centre of gravity and narrow base", "less stable than a tall, narrow object", "unaffected by the position of its centre of gravity", "always in unstable equilibrium"], "more stable than one with a high centre of gravity and narrow base",
      "A wide base and low centre of gravity require a greater tilt before the centre of gravity passes outside the base, making the object harder to topple, hence more stable."),
  _q("The Principle of Moments states that for a body in equilibrium under the action of several coplanar forces,",
      ["the sum of clockwise moments about any point equals the sum of anticlockwise moments about that point", "all forces must be equal in magnitude", "the net force must be greater than zero", "moments are only considered for forces acting at the centre of gravity"], "the sum of clockwise moments about any point equals the sum of anticlockwise moments about that point",
      "The Principle of Moments (law of the lever) requires that clockwise and anticlockwise turning effects about a pivot balance exactly for rotational equilibrium."),
  _q("A uniform metre rule is balanced at its 50 cm mark. A 2 N weight is hung at the 20 cm mark. Where must a 4 N weight be hung to balance it?",
      ["At the 65 cm mark", "At the 60 cm mark", "At the 70 cm mark", "At the 80 cm mark"], "At the 65 cm mark",
      "Clockwise moment of 4 N about 50 cm mark = anticlockwise moment of 2 N: 2 x 30 = 4 x d, so d = 15 cm from the pivot, placing it at 50 + 15 = 65 cm."),
  _q("Lami's Theorem applies to three coplanar, concurrent forces in equilibrium and states that each force is proportional to the",
      ["sine of the angle between the other two forces", "cosine of the angle between the other two forces", "tangent of the angle between the other two forces", "sum of the other two forces"], "sine of the angle between the other two forces",
      "Lami's Theorem: F1/sin(angle between F2,F3) = F2/sin(angle between F1,F3) = F3/sin(angle between F1,F2), useful for solving three-force equilibrium problems."),
];

final _workEnergyPower = [
  _q("Work done by a force is calculated as the product of the",
      ["force and the distance moved in the direction of the force", "force and time taken", "mass and velocity", "force and acceleration"], "force and the distance moved in the direction of the force",
      "Work (W = Fd cos theta) is done when a force causes displacement in its own direction; no work is done if there is no displacement or the force is perpendicular to it."),
  _q("A force of 10 N moves an object through a distance of 5 m in the direction of the force. How much work is done?",
      ["50 J", "2 J", "15 J", "5 J"], "50 J",
      "Work = Force x distance = 10 x 5 = 50 joules."),
  _q("Kinetic energy of a moving body is given by the formula",
      ["1/2 mv^2", "mgh", "mv", "1/2 mv"], "1/2 mv^2",
      "Kinetic energy, the energy of motion, is given by KE = 1/2 mv^2, where m is mass and v is velocity."),
  _q("A 2 kg object falls freely and reaches a velocity of 10 m/s. What is its kinetic energy at that instant?",
      ["100 J", "20 J", "200 J", "10 J"], "100 J",
      "KE = 1/2 mv^2 = 0.5 x 2 x 10^2 = 0.5 x 2 x 100 = 100 J."),
  _q("Gravitational potential energy is given by the formula",
      ["mgh", "1/2 mv^2", "mv", "Fd"], "mgh",
      "Gravitational potential energy depends on mass (m), the acceleration due to gravity (g), and height (h) above a reference level: PE = mgh."),
  _q("The Law of Conservation of Energy states that",
      ["energy cannot be created or destroyed, only transformed from one form to another", "energy is always lost as heat in any process", "total energy of a system always increases over time", "kinetic energy is always equal to potential energy"], "energy cannot be created or destroyed, only transformed from one form to another",
      "This fundamental physical law means the total energy in an isolated system remains constant, even as it changes form (e.g., potential to kinetic)."),
  _q("Power is defined as the",
      ["rate at which work is done", "total amount of work done", "force applied per unit area", "product of force and distance"], "rate at which work is done",
      "Power (P = W/t) measures how quickly work is performed or energy is transferred, measured in watts (joules per second)."),
  _q("A machine does 500 J of work in 10 seconds. What is its power output?",
      ["50 W", "5000 W", "5 W", "500 W"], "50 W",
      "Power = Work/time = 500/10 = 50 watts."),
];

final _frictionSimpleMachines = [
  _q("Friction is a force that always acts to",
      ["oppose relative motion or the tendency of motion between two surfaces", "increase the speed of a moving object", "act perpendicular to the surfaces in contact", "act only on stationary objects"], "oppose relative motion or the tendency of motion between two surfaces",
      "Friction is a resistive force arising from contact between surfaces, always acting opposite to the direction of relative motion or intended motion."),
  _q("Static friction differs from dynamic (kinetic) friction in that static friction",
      ["acts on objects that are not yet moving relative to each other", "is always smaller than dynamic friction", "occurs only in fluids", "does not depend on the normal force"], "acts on objects that are not yet moving relative to each other",
      "Static friction prevents relative motion from starting, and its maximum value is generally slightly greater than the kinetic (dynamic) friction that acts once motion begins."),
  _q("Viscosity refers to a fluid's internal resistance to",
      ["flow", "compression", "boiling", "freezing"], "flow",
      "Viscosity measures how strongly a fluid resists flowing or deforming; thick fluids like honey have high viscosity compared to water."),
  _q("Terminal velocity is reached by an object falling through a fluid when",
      ["the resistive (drag) force equals the object's weight, resulting in zero net acceleration", "the object stops moving completely", "the object's weight becomes zero", "air resistance becomes negligible"], "the resistive (drag) force equals the object's weight, resulting in zero net acceleration",
      "As speed increases, drag force increases until it balances gravity; at this point the object falls at a constant maximum speed, its terminal velocity."),
  _q("The mechanical advantage of a simple machine is defined as the ratio of",
      ["load to effort", "effort to load", "velocity ratio to efficiency", "distance moved by effort to distance moved by load"], "load to effort",
      "Mechanical advantage (MA) = load/effort, indicating how many times the machine multiplies the applied effort force."),
  _q("The velocity ratio of a simple machine is defined as the ratio of",
      ["distance moved by the effort to distance moved by the load", "load to effort", "effort to load", "output power to input power"], "distance moved by the effort to distance moved by the load",
      "Velocity ratio (VR) = distance moved by effort / distance moved by load, a purely geometric property of the machine, independent of friction."),
  _q("The efficiency of a machine is calculated as",
      ["(mechanical advantage / velocity ratio) x 100%", "(velocity ratio / mechanical advantage) x 100%", "load x effort", "distance moved by effort only"], "(mechanical advantage / velocity ratio) x 100%",
      "Efficiency = (MA/VR) x 100%, reflecting how much of the input work is usefully converted to output work, always less than 100% due to friction."),
  _q("A pulley system has a velocity ratio of 4 and requires an effort of 30 N to lift a load of 100 N. What is its efficiency?",
      ["about 83.3%", "100%", "75%", "120%"], "about 83.3%",
      "MA = load/effort = 100/30 = 3.33. Efficiency = (MA/VR) x 100 = (3.33/4) x 100 = about 83.3%."),
];

final _propertiesOfMatter = [
  _q("Hooke's Law states that within the elastic limit, the extension of a spring is",
      ["directly proportional to the applied force", "inversely proportional to the applied force", "independent of the applied force", "proportional to the square of the applied force"], "directly proportional to the applied force",
      "Hooke's Law: F = ke, where extension e is directly proportional to the applied force F, provided the elastic limit of the material is not exceeded."),
  _q("Young's modulus of a material is defined as the ratio of",
      ["stress to strain, within the elastic limit", "force to area", "extension to original length", "strain to stress"], "stress to strain, within the elastic limit",
      "Young's modulus (E = stress/strain) quantifies a material's stiffness, describing how much it deforms elastically under a given stress."),
  _q("Atmospheric pressure is caused mainly by",
      ["the weight of the column of air above a given point", "the rotation of the Earth", "temperature differences at ground level only", "the presence of water vapour alone"], "the weight of the column of air above a given point",
      "The atmosphere's weight, pressing down due to gravity, exerts a pressure on surfaces below it, which decreases with increasing altitude."),
  _q("Pascal's Principle states that pressure applied to an enclosed fluid is",
      ["transmitted equally in all directions throughout the fluid", "only transmitted in the direction of the applied force", "reduced as it moves through the fluid", "converted entirely into heat"], "transmitted equally in all directions throughout the fluid",
      "Pascal's Principle underlies hydraulic systems: pressure applied anywhere in a confined incompressible fluid is transmitted undiminished to all parts of the fluid."),
  _q("Archimedes' Principle states that the upthrust on a body partially or wholly immersed in a fluid equals the",
      ["weight of the fluid displaced by the body", "weight of the body itself", "volume of the body", "density of the fluid alone"], "weight of the fluid displaced by the body",
      "Archimedes' Principle explains buoyancy: the upward force (upthrust) on a submerged object equals the weight of the fluid it displaces."),
  _q("The pressure exerted by a liquid column depends on the",
      ["depth of the liquid, its density, and the acceleration due to gravity", "shape of the container only", "surface area of the container base only", "temperature of the liquid only"], "depth of the liquid, its density, and the acceleration due to gravity",
      "Liquid pressure is given by P = h(rho)g, depending on the height (depth) of the column, the liquid's density, and gravitational acceleration, but not on the container's shape."),
  _q("A body floats in a liquid when",
      ["the upthrust on it equals its weight", "the upthrust exceeds twice its weight", "its density is greater than that of the liquid", "there is no upthrust acting on it"], "the upthrust on it equals its weight",
      "For a floating object, the upward buoyant force (upthrust) exactly balances the downward weight, resulting in zero net force and equilibrium."),
  _q("A spring of natural length 20 cm extends to 25 cm under a load of 10 N. What is its spring constant?",
      ["2 N/cm", "0.5 N/cm", "5 N/cm", "10 N/cm"], "2 N/cm",
      "Extension e = 25 - 20 = 5 cm. Spring constant k = F/e = 10/5 = 2 N/cm."),
];

final _thermalPhysics = [
  _q("The Celsius and Kelvin temperature scales are related by the formula",
      ["K = degC + 273", "K = degC - 273", "K = degC x 273", "K = 273/degC"], "K = degC + 273",
      "To convert Celsius to Kelvin (the absolute temperature scale), add 273 (more precisely 273.15) to the Celsius value."),
  _q("When a solid is heated, it generally expands because",
      ["increased thermal energy causes particles to vibrate more and move slightly further apart", "the mass of the solid decreases", "particles lose kinetic energy", "the solid's density increases proportionally"], "increased thermal energy causes particles to vibrate more and move slightly further apart",
      "Thermal expansion occurs because heating increases the amplitude of particle vibrations, increasing the average spacing between them."),
  _q("According to Boyle's Law, at constant temperature, the pressure of a fixed mass of gas is",
      ["inversely proportional to its volume", "directly proportional to its volume", "directly proportional to its temperature", "independent of its volume"], "inversely proportional to its volume",
      "Boyle's Law: PV = constant at constant temperature, so pressure increases as volume decreases, and vice versa."),
  _q("According to Charles's Law, at constant pressure, the volume of a fixed mass of gas is",
      ["directly proportional to its absolute temperature", "inversely proportional to its absolute temperature", "independent of temperature", "directly proportional to its pressure"], "directly proportional to its absolute temperature",
      "Charles's Law: V/T = constant at constant pressure, meaning gas volume increases proportionally with absolute (Kelvin) temperature."),
  _q("The Pressure Law states that at constant volume, the pressure of a fixed mass of gas is",
      ["directly proportional to its absolute temperature", "inversely proportional to its absolute temperature", "independent of temperature", "inversely proportional to volume"], "directly proportional to its absolute temperature",
      "The Pressure (Gay-Lussac's) Law: P/T = constant at constant volume, so pressure rises proportionally with absolute temperature."),
  _q("Specific heat capacity of a substance is defined as the quantity of heat required to raise the temperature of",
      ["a unit mass of the substance by one degree (Celsius or Kelvin)", "the whole substance by any amount", "one mole of the substance to its boiling point", "a unit volume of the substance by ten degrees"], "a unit mass of the substance by one degree (Celsius or Kelvin)",
      "Specific heat capacity, c, is defined by Q = mcT-change, representing heat needed per unit mass per degree temperature rise."),
  _q("How much heat is needed to raise the temperature of 2 kg of water by 5 degC? (Specific heat capacity of water = 4200 J/kgK)",
      ["42000 J", "8400 J", "21000 J", "4200 J"], "42000 J",
      "Q = mcT-change = 2 x 4200 x 5 = 42000 J."),
  _q("Latent heat of fusion is the heat energy required to",
      ["change a substance from solid to liquid at constant temperature", "raise the temperature of a solid by one degree", "change a substance from liquid to gas", "cool a liquid to its freezing point"], "change a substance from solid to liquid at constant temperature",
      "Latent heat of fusion is absorbed during melting (solid to liquid) without any change in temperature, as the energy breaks intermolecular bonds rather than increasing kinetic energy."),
  _q("Heat transfer through a solid medium, without the bulk movement of the material itself, is called",
      ["conduction", "convection", "radiation", "evaporation"], "conduction",
      "Conduction transfers heat through direct particle-to-particle vibration and collision within a solid, without any overall movement of the medium."),
  _q("Convection as a mode of heat transfer occurs mainly in",
      ["liquids and gases, through the bulk movement of the fluid", "solids only", "a vacuum", "only in metals"], "liquids and gases, through the bulk movement of the fluid",
      "Convection relies on the physical movement of heated fluid (liquid or gas), which is less dense and rises, carrying thermal energy with it, a process not possible in rigid solids."),
];

final _wavesSound = [
  _q("The distance between two successive crests (or troughs) of a wave is called its",
      ["wavelength", "amplitude", "frequency", "period"], "wavelength",
      "Wavelength (usually denoted by the Greek letter lambda) is the spatial period of a wave, the distance over which the wave's shape repeats."),
  _q("The relationship between the velocity, frequency, and wavelength of a wave is given by",
      ["v = f x wavelength", "v = f / wavelength", "v = f + wavelength", "f = v x wavelength"], "v = f x wavelength",
      "The wave equation v = f(lambda) relates wave speed to the product of frequency and wavelength, valid for all types of waves."),
  _q("Sound waves are classified as",
      ["longitudinal waves", "transverse waves", "electromagnetic waves", "standing waves only"], "longitudinal waves",
      "In sound waves, particles of the medium vibrate parallel to the direction of wave propagation, characteristic of longitudinal waves, unlike transverse waves such as light."),
  _q("An echo is produced when sound waves",
      ["are reflected off a hard surface and return to the listener after a short delay", "are refracted through a different medium", "are absorbed completely by a surface", "travel through a vacuum"], "are reflected off a hard surface and return to the listener after a short delay",
      "Echoes result from sound reflecting off obstacles like walls or cliffs, reaching the listener again after enough delay to be perceived as a distinct repetition."),
  _q("Sound cannot travel through a vacuum because",
      ["it requires a material medium (solid, liquid, or gas) for particle-to-particle transmission", "sound waves are electromagnetic in nature", "a vacuum has infinite density", "sound waves travel faster in a vacuum"], "it requires a material medium (solid, liquid, or gas) for particle-to-particle transmission",
      "Unlike electromagnetic waves such as light, sound is a mechanical wave that needs particles of a medium to vibrate and transmit the disturbance."),
  _q("The pitch of a musical note is determined mainly by its",
      ["frequency", "amplitude", "wavelength in a vacuum", "speed of travel"], "frequency",
      "Higher frequency sound waves are perceived as higher pitch, while amplitude instead determines the loudness of the sound."),
  _q("The loudness of a sound is determined mainly by its",
      ["amplitude", "frequency", "wavelength", "speed"], "amplitude",
      "A sound wave with greater amplitude carries more energy, which is perceived by the ear as a louder sound."),
  _q("The Doppler effect explains why the pitch of a sound",
      ["appears to change when there is relative motion between the source and the observer", "is always constant regardless of motion", "depends only on the medium's temperature", "cannot be perceived by the human ear"], "appears to change when there is relative motion between the source and the observer",
      "The Doppler effect describes the apparent shift in frequency (and pitch) of a wave due to relative motion, e.g., a siren sounding higher-pitched as it approaches and lower as it recedes."),
];

final _optics = [
  _q("The law of reflection states that the angle of incidence is",
      ["equal to the angle of reflection", "always greater than the angle of reflection", "always 90 degrees", "unrelated to the angle of reflection"], "equal to the angle of reflection",
      "The law of reflection states that the angle between the incident ray and the normal equals the angle between the reflected ray and the normal."),
  _q("Refraction of light occurs when light",
      ["passes from one medium to another of different optical density, causing a change in speed and direction", "is completely absorbed by a surface", "travels through a vacuum without any medium", "reflects off a mirror at equal angles"], "passes from one medium to another of different optical density, causing a change in speed and direction",
      "Refraction is the bending of light as it crosses a boundary between media with different refractive indices, due to a change in wave speed."),
  _q("A concave mirror is also known as a",
      ["converging mirror", "diverging mirror", "plane mirror", "diffusing mirror"], "converging mirror",
      "Concave mirrors curve inward and reflect parallel rays to converge at a focal point, making them converging mirrors, used in torches and telescopes."),
  _q("A convex lens forms a real, inverted image when the object is placed",
      ["beyond the focal length of the lens", "exactly at the optical centre of the lens", "between the lens and its focal point", "at infinity, producing an image at the focal point only"], "beyond the focal length of the lens",
      "When an object is placed beyond the focal length of a convex lens, the lens converges the refracted rays to form a real, inverted image on the other side."),
  _q("A ray of white light passing through a glass prism separates into its component colours, a phenomenon known as",
      ["dispersion", "reflection", "diffraction only", "polarization"], "dispersion",
      "Dispersion occurs because different wavelengths (colours) of light are refracted by slightly different amounts, spreading white light into a spectrum."),
  _q("The image formed by a plane mirror is always",
      ["virtual, upright, and the same size as the object", "real and inverted", "magnified and real", "smaller than the object"], "virtual, upright, and the same size as the object",
      "A plane mirror always produces a virtual (cannot be projected on a screen), laterally inverted, upright image identical in size to the object."),
  _q("A simple microscope works on the principle of using a",
      ["single converging lens to produce a magnified, virtual image of a nearby object", "concave mirror to focus distant objects", "prism to disperse light into colours", "plane mirror to reflect an image"], "single converging lens to produce a magnified, virtual image of a nearby object",
      "A simple microscope (magnifying glass) uses one convex lens, with the object placed within its focal length to produce an enlarged, upright, virtual image."),
  _q("A refracting astronomical telescope typically uses",
      ["two converging lenses: an objective lens and an eyepiece lens", "a single concave lens only", "two plane mirrors", "one convex lens and one plane mirror"], "two converging lenses: an objective lens and an eyepiece lens",
      "A basic refracting telescope has an objective lens that forms a real image of a distant object, magnified further by the eyepiece lens acting as a simple magnifier."),
];

final _electricityMagnetism = [
  _q("Electrostatics is the study of",
      ["electric charges at rest", "electric charges in motion (current)", "magnetic fields only", "the flow of heat through conductors"], "electric charges at rest",
      "Electrostatics deals with stationary electric charges and the forces, fields, and potentials associated with them, as opposed to current electricity."),
  _q("Like electric charges (e.g., two positive charges) placed near each other will",
      ["repel each other", "attract each other", "have no effect on each other", "neutralise each other completely"], "repel each other",
      "Coulomb's Law describes how like charges repel while unlike charges attract, a fundamental behaviour of electrostatic forces."),
  _q("A capacitor is a device used mainly to",
      ["store electric charge (and energy) in an electric field", "generate electric current from mechanical motion", "convert AC to DC", "measure electric current directly"], "store electric charge (and energy) in an electric field",
      "A capacitor consists of two conducting plates separated by an insulator (dielectric), storing charge and energy when a potential difference is applied across it."),
  _q("Ohm's Law states that the current flowing through a conductor is directly proportional to the potential difference across it, provided that",
      ["temperature and other physical conditions remain constant", "the resistance is increasing", "the current is alternating", "the conductor is a semiconductor"], "temperature and other physical conditions remain constant",
      "Ohm's Law (V = IR) holds for ohmic conductors as long as physical conditions such as temperature remain unchanged during the measurement."),
  _q("A current of 2 A flows through a resistor of resistance 5 ohms. What is the potential difference across the resistor?",
      ["10 V", "2.5 V", "7 V", "0.4 V"], "10 V",
      "Using V = IR: V = 2 x 5 = 10 volts."),
  _q("When resistors are connected in series, the total resistance is",
      ["the sum of the individual resistances", "the reciprocal of the sum of reciprocals of individual resistances", "always less than the smallest individual resistance", "equal to the average of the individual resistances"], "the sum of the individual resistances",
      "In a series circuit, resistances simply add: Rtotal = R1 + R2 + R3 + ..., since the same current flows through each resistor in turn."),
  _q("When resistors are connected in parallel, the reciprocal of the total resistance equals the",
      ["sum of the reciprocals of the individual resistances", "sum of the individual resistances", "product of the individual resistances", "difference between the individual resistances"], "sum of the reciprocals of the individual resistances",
      "For parallel resistors: 1/Rtotal = 1/R1 + 1/R2 + ..., which always gives a total resistance smaller than the smallest individual resistor."),
  _q("A magnetic field is produced around a straight, current-carrying conductor in a pattern of",
      ["concentric circles around the wire", "straight lines parallel to the wire", "a uniform field identical to a bar magnet", "no field at all unless the current is very large"], "concentric circles around the wire",
      "Oersted's discovery showed that a current-carrying wire produces a magnetic field forming concentric circles around it, with direction given by the right-hand grip rule."),
  _q("Electromagnetic induction is the process by which",
      ["a changing magnetic field induces an electromotive force (e.m.f.) in a nearby conductor", "a magnet is created by passing current through a coil", "static charges build up on an insulator", "current flows through a conductor at absolute zero with no resistance"], "a changing magnetic field induces an electromotive force (e.m.f.) in a nearby conductor",
      "Faraday's Law of electromagnetic induction states that a changing magnetic flux through a circuit induces an e.m.f., the basis for generators and transformers."),
  _q("A transformer works on the principle of",
      ["mutual electromagnetic induction between two coils linked by a changing magnetic flux", "electrostatic attraction between charged plates", "chemical reactions in a battery", "resistive heating of a wire"], "mutual electromagnetic induction between two coils linked by a changing magnetic flux",
      "Transformers use a changing current in a primary coil to produce a varying magnetic flux, which induces a corresponding e.m.f. in a secondary coil, enabling voltage step-up or step-down."),
];

final _modernPhysics = [
  _q("In Bohr's model of the atom, electrons orbit the nucleus in",
      ["fixed, discrete energy levels (orbits) without radiating energy", "continuously variable orbits at any energy", "orbits that constantly radiate energy and spiral inward", "a single fixed orbit for all elements"], "fixed, discrete energy levels (orbits) without radiating energy",
      "Bohr proposed that electrons occupy specific quantised energy levels, and only emit or absorb energy when jumping between these fixed levels, not while orbiting."),
  _q("The photoelectric effect refers to the",
      ["emission of electrons from a metal surface when light of sufficient frequency shines on it", "emission of light when a metal is heated", "absorption of electrons by a metal surface in the dark", "reflection of light off a polished metal surface"], "emission of electrons from a metal surface when light of sufficient frequency shines on it",
      "The photoelectric effect occurs when incident photons with energy above a metal's threshold frequency eject electrons from its surface, evidence for the particle nature of light."),
  _q("X-rays are a form of",
      ["high-frequency electromagnetic radiation", "charged particles emitted from radioactive nuclei", "sound waves of very high pitch", "mechanical waves requiring a medium"], "high-frequency electromagnetic radiation",
      "X-rays are electromagnetic waves with very short wavelength and high frequency, produced when fast-moving electrons are suddenly decelerated, as in an X-ray tube."),
  _q("Radioactivity is the spontaneous process by which",
      ["unstable atomic nuclei emit particles or radiation to become more stable", "atoms absorb external radiation to become excited", "electrons are shared between two atoms", "molecules break apart due to heating alone"], "unstable atomic nuclei emit particles or radiation to become more stable",
      "Radioactive decay occurs when an unstable nucleus spontaneously emits alpha, beta, or gamma radiation, transforming into a more stable configuration."),
];
