import "../quiz_question.dart";

const _oauIslamicStudiesSubject = "Islamic Studies";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _oauIslamicStudiesSubject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// Obafemi Awolowo University (OAU) Post-UTME Islamic Studies practice bank
/// — 100 medium-to-hard questions covering Tarikh (Pre-Islamic Arabia, the
/// Makkan and Madinan periods of the Prophet's life, the Rightly Guided
/// Caliphs, and the spread of Islam in West Africa, including Uthman Dan
/// Fodio), Qur'an and Hadith (revelation, preservation, prescribed Surahs,
/// and Hadith compilation), and Fiqh/Tawhid (Tawhid and Shirk, Ibadah, and
/// Shariah/Mu'amalat). This is an independent practice set aligned to the
/// general Post-UTME/JAMB syllabus, not an official OAU past-question
/// paper.
List<QuizQuestion> buildOauIslamicStudiesQuestions() {
  return [
    ..._preIslamicArabia,
    ..._makkanPeriod,
    ..._madinanPeriod,
    ..._rightlyGuidedCaliphs,
    ..._islamInWestAfrica,
    ..._quranAndHadith,
    ..._fiqhAndTawhid,
  ];
}

final _preIslamicArabia = [
  _q("The Arabic term used to describe the state of pre-Islamic Arabian society, particularly its widespread idolatry and moral decadence, is",
      ["Jahiliyyah", "Sunnah", "Ijma", "Hijrah"], "Jahiliyyah",
      "Jahiliyyah, literally 'ignorance', denotes the pre-Islamic era in Arabia marked by idol worship, tribal feuds, and various social ills."),
  _q("Before the rise of Islam, the custodianship (Sadanah) of the Ka'bah and control of Makkah's affairs was held by the tribe of",
      ["Quraysh", "Aws", "Khazraj", "Thaqif"], "Quraysh",
      "The Quraysh were the dominant tribe of Makkah, and various clans within it held privileged offices connected with the Ka'bah, such as providing water and guarding the sanctuary."),
  _q("Among pre-Islamic Arabs, disputes between individuals or tribes were frequently settled through",
      ["retaliatory tribal warfare and the law of the strongest", "an established written civil code", "a central royal court", "compulsory arbitration by religious clergy"], "retaliatory tribal warfare and the law of the strongest",
      "In the absence of a central authority, pre-Islamic Arab tribes often resolved disputes through raids, feuds, and retaliation, with strength and tribal solidarity determining outcomes."),
  _q("The annual markets or fairs held in pre-Islamic Arabia, such as Ukaz, were mainly significant for",
      ["trade and the recitation and judging of poetry", "the collection of obligatory Zakat", "the appointment of tribal chiefs by ballot", "the settlement of religious doctrine"], "trade and the recitation and judging of poetry",
      "Fairs like Ukaz combined commerce with cultural activity, especially poetic contests where the finest verses were publicly honoured."),
  _q("The pre-Islamic Arab custom in which a man could inherit his deceased father's widow (other than his own mother) as a wife is an example of a practice that Islam later",
      ["abolished", "made compulsory", "left entirely unregulated", "extended to include daughters"], "abolished",
      "Islam reformed inheritance and marriage laws, explicitly prohibiting such customs to protect women's dignity and rights."),
  _q("Which pre-Islamic Arabian city was especially renowned as a centre of long-distance trade linking Yemen in the south to Syria in the north?",
      ["Makkah", "Ta'if", "Yathrib", "Najran"], "Makkah",
      "Makkah's position on the caravan route between Yemen and Syria made it a vital commercial centre, a role the Quraysh capitalised on."),
  _q("In pre-Islamic Arabian belief, idols such as al-Lat, al-Uzza, and Manat were regarded as",
      ["intermediaries believed to bring worshippers closer to Allah", "the sole and only deities, with no belief in a supreme God at all", "purely artistic sculptures without religious value", "representations of deceased Arab kings"], "intermediaries believed to bring worshippers closer to Allah",
      "Despite worshipping idols, many pre-Islamic Arabs still acknowledged Allah as a supreme creator, but treated idols as intercessors, a practice the Qur'an condemns as shirk."),
  _q("The pre-Islamic Arabian institution known as 'Hilf al-Fudul', which Prophet Muhammad praised even after prophethood, was primarily a",
      ["pact formed to defend the oppressed and ensure justice for victims of wrongdoing", "treaty establishing trade monopolies for the Quraysh", "council for electing tribal chiefs", "alliance for waging war against Persia"], "pact formed to defend the oppressed and ensure justice for victims of wrongdoing",
      "Hilf al-Fudul was a chivalrous alliance among some Makkan clans pledging to support the wronged and oppressed, a value the Prophet later affirmed he would still uphold under Islam."),
  _q("Which of these best describes the general religious landscape of Arabia just before Islam, beyond dominant idolatry?",
      ["Small communities of Jews and Christians also existed alongside pockets of Hanif monotheists", "The entire peninsula was uniformly Christian", "Buddhism was the second most practised faith", "There was no religious diversity of any kind"], "Small communities of Jews and Christians also existed alongside pockets of Hanif monotheists",
      "Alongside the polytheistic majority, Jewish communities (notably in Yathrib and Khaybar), some Christians (as in Najran), and Hanifs who rejected idolatry were present in pre-Islamic Arabia."),
  _q("The pre-Islamic practice of 'Wa'd al-Banat', condemned in the Qur'an, refers to",
      ["the burying alive of infant daughters", "the giving of dowry to a bride", "the seclusion of women after marriage", "the naming ceremony of a newborn"], "the burying alive of infant daughters",
      "Wa'd al-Banat describes the abhorrent practice of female infanticide among some pre-Islamic Arab tribes, which the Qur'an strongly denounces."),
];

final _makkanPeriod = [
  _q("Prophet Muhammad (S.A.W) belonged to which clan of the Quraysh tribe?",
      ["Banu Hashim", "Banu Umayyah", "Banu Makhzum", "Banu Zuhrah"], "Banu Hashim",
      "The Prophet was born into the Banu Hashim clan of the Quraysh, a respected clan associated with the custodianship of the Ka'bah's water supply."),
  _q("Before receiving prophethood, Muhammad (S.A.W) earned a reputation among the Makkans for his honesty, which led them to give him the title",
      ["Al-Amin (the Trustworthy)", "Al-Mustafa (the Chosen)", "Khatam an-Nabiyyin (Seal of the Prophets)", "As-Sadiq (the Truthful) alone"], "Al-Amin (the Trustworthy)",
      "Long before revelation began, Muhammad was widely known and trusted as 'Al-Amin' for his integrity in commerce and personal dealings."),
  _q("The angel who delivered the first revelation of the Qur'an to Prophet Muhammad in the Cave of Hira was",
      ["Jibril (Gabriel)", "Mikail (Michael)", "Israfil", "Malik"], "Jibril (Gabriel)",
      "Angel Jibril was the messenger appointed by Allah to convey divine revelation to Prophet Muhammad throughout his mission."),
  _q("The first person to accept Islam among the Prophet's household was his wife",
      ["Khadijah bint Khuwaylid", "Aishah bint Abu Bakr", "Hafsah bint Umar", "Zaynab bint Jahsh"], "Khadijah bint Khuwaylid",
      "Khadijah, the Prophet's first wife, was the very first person to believe in and support his prophetic message."),
  _q("Among men, the first person outside the Prophet's immediate household to accept Islam was",
      ["Abu Bakr As-Siddiq", "Umar ibn al-Khattab", "Uthman ibn Affan", "Ali ibn Abi Talib"], "Abu Bakr As-Siddiq",
      "Abu Bakr was among the earliest and most prominent converts, using his influence to bring several other notable Makkans into Islam."),
  _q("The early Muslims who suffered severe persecution in Makkah and were advised by the Prophet to seek refuge in Abyssinia found protection under a Christian ruler known as",
      ["the Negus (An-Najashi)", "Heraclius", "Kisra (Khosrow)", "the Muqawqis"], "the Negus (An-Najashi)",
      "The Negus of Abyssinia was known for his justice and granted asylum to the persecuted Muslim emigrants, refusing Quraysh demands to hand them over."),
  _q("The Prophet's journey to Ta'if in the tenth year of his mission was primarily undertaken to",
      ["seek support and protection for his message after the deaths of Khadijah and Abu Talib", "negotiate a trade agreement", "perform a pilgrimage", "meet with Jewish scholars"], "seek support and protection for his message after the deaths of Khadijah and Abu Talib",
      "Following the loss of his two strongest supporters, the Prophet travelled to Ta'if hoping for support, but was instead met with rejection and hostility."),
  _q("The night journey in which Prophet Muhammad was taken from Makkah to Jerusalem and then ascended through the heavens is known as",
      ["Isra and Mi'raj", "Hijrah", "Laylat al-Qadr", "Ghazwah"], "Isra and Mi'raj",
      "The Isra was the night journey to Jerusalem, and the Mi'raj was the subsequent ascension through the heavens, during which the five daily prayers were prescribed."),
  _q("The pledges made between the Prophet and a group of Yathrib pilgrims at Aqabah, which paved the way for the Hijrah, are known as",
      ["the Pledges of Aqabah", "the Treaty of Hudaybiyyah", "the Constitution of Madinah", "the Farewell Sermon"], "the Pledges of Aqabah",
      "The First and Second Pledges of Aqabah were agreements in which converts from Yathrib pledged support and protection to the Prophet, leading to the eventual migration."),
  _q("During the boycott imposed by the Quraysh on Banu Hashim and Banu Muttalib, the Prophet's clan was largely confined to a",
      ["mountain valley/quarter known as Shi'b Abi Talib", "fortress in Ta'if", "coastal settlement near the Red Sea", "walled district of Yathrib"], "mountain valley/quarter known as Shi'b Abi Talib",
      "For about three years, the Quraysh socially and economically boycotted the Prophet's clan, confining them to the quarter of Abu Talib until the ban was lifted."),
  _q("The main content of the Qur'anic revelations received during the Makkan period is generally characterised by an emphasis on",
      ["Tawhid, the Day of Judgement, and moral reform", "detailed rules of inheritance and criminal punishment", "the organisation of a full state administration", "treaties of international diplomacy"], "Tawhid, the Day of Judgement, and moral reform",
      "Makkan revelations largely focused on establishing belief in the Oneness of Allah, the reality of resurrection and judgement, and correcting moral conduct, since legal/administrative rulings mostly came later in Madinah."),
  _q("Which of the Prophet's early followers was famously tortured by his Makkan master for accepting Islam, repeating 'Ahad, Ahad' (One, One) under torment?",
      ["Bilal ibn Rabah", "Zayd ibn Harithah", "Ammar ibn Yasir", "Suhayb ar-Rumi"], "Bilal ibn Rabah",
      "Bilal, an Abyssinian slave, endured brutal torture for his faith yet steadfastly affirmed the Oneness of Allah, later becoming the first muezzin of Islam."),
];

final _madinanPeriod = [
  _q("The Hijrah of Prophet Muhammad from Makkah to Madinah took place in the Gregorian year",
      ["622 CE", "610 CE", "630 CE", "570 CE"], "622 CE",
      "The Hijrah occurred in 622 CE and was later adopted as the starting point of the Islamic (Hijri) lunar calendar."),
  _q("Immediately upon arriving in Madinah, one of the first major actions Prophet Muhammad undertook was to",
      ["establish a mosque and formalise brotherhood (Mu'akhat) between Muhajirun and Ansar", "declare war on the Quraysh of Makkah", "abolish all existing trade in the city", "appoint a hereditary monarchy"], "establish a mosque and formalise brotherhood (Mu'akhat) between Muhajirun and Ansar",
      "In Madinah, the Prophet built a mosque as a communal centre and paired emigrants (Muhajirun) with Madinan hosts (Ansar) in a bond of brotherhood to aid social and economic integration."),
  _q("The document drawn up by Prophet Muhammad to regulate relations among Muslims, Jews, and other groups in Madinah is known as",
      ["the Constitution (Charter) of Madinah", "the Treaty of Hudaybiyyah", "the Pledge of Ridwan", "the Covenant of Aqabah"], "the Constitution (Charter) of Madinah",
      "This charter established Madinah as a single political community, defining rights, duties, and mutual defence obligations among its diverse inhabitants."),
  _q("The first major battle fought between the Muslims of Madinah and the Quraysh of Makkah, resulting in a decisive Muslim victory, was the Battle of",
      ["Badr", "Uhud", "the Trench (Khandaq)", "Hunayn"], "Badr",
      "Fought in 624 CE (2 AH), the Battle of Badr was the first significant military confrontation, in which a smaller Muslim force achieved a decisive victory."),
  _q("At the Battle of Uhud, a major setback for the Muslims occurred largely because",
      ["a group of archers left their assigned post in pursuit of spoils", "the Muslims refused to fight", "the Quraysh used weapons unfamiliar to the Arabs", "the battle was fought without the Prophet's presence"], "a group of archers left their assigned post in pursuit of spoils",
      "Despite initial Muslim gains, archers stationed on a hill abandoned their post against the Prophet's instructions, allowing the Makkan cavalry to counterattack and turn the tide."),
  _q("The Battle of the Trench (Khandaq) is notable for the Muslims' defensive strategy of",
      ["digging a trench around exposed parts of Madinah on the suggestion of Salman al-Farisi", "constructing a naval fleet", "abandoning Madinah entirely", "forming a direct alliance with the Quraysh"], "digging a trench around exposed parts of Madinah on the suggestion of Salman al-Farisi",
      "Salman al-Farisi, a Persian companion, suggested digging a trench, an unfamiliar tactic in Arabia that successfully thwarted the confederate siege of Madinah."),
  _q("The 628 CE agreement between the Muslims and the Quraysh that, despite seemingly unfavourable terms, allowed Islam to spread more peacefully is known as",
      ["the Treaty of Hudaybiyyah", "the Constitution of Madinah", "the Pledge of Aqabah", "the Farewell Sermon"], "the Treaty of Hudaybiyyah",
      "Although its terms initially appeared to favour the Quraysh, the truce of Hudaybiyyah created a period of peace during which Islam spread rapidly across Arabia."),
  _q("Makkah came under Muslim control largely without bloodshed in the year",
      ["630 CE, known as the Conquest (Fath) of Makkah", "622 CE, alongside the Hijrah", "624 CE, following the Battle of Badr", "632 CE, the year of the Prophet's death"], "630 CE, known as the Conquest (Fath) of Makkah",
      "The Conquest of Makkah in 630 CE occurred with minimal resistance, after which the Prophet granted a general amnesty to the Makkans and destroyed the idols in the Ka'bah."),
  _q("In his Farewell Sermon (Khutbat al-Wada), delivered near Makkah shortly before his death, Prophet Muhammad emphasised themes including",
      ["the sanctity of life and property, equality of believers, and rights of women", "the establishment of a hereditary caliphate", "the annexation of Persian and Roman territories", "the abolition of the Hajj pilgrimage"], "the sanctity of life and property, equality of believers, and rights of women",
      "The Farewell Sermon summarised core Islamic ethical and social principles, including the sanctity of life, property, and honour, racial equality, and the rights of women."),
  _q("Prophet Muhammad (S.A.W) passed away in the year",
      ["632 CE (11 AH), in Madinah", "630 CE, in Makkah", "622 CE, in Madinah", "640 CE, in Jerusalem"], "632 CE (11 AH), in Madinah",
      "The Prophet died in Madinah in 632 CE, corresponding to the 11th year after the Hijrah."),
  _q("The Muhajirun, as referred to in early Islamic history, were",
      ["Muslims who emigrated from Makkah to Madinah", "the original inhabitants of Madinah who supported the Prophet", "non-Muslim allies of the Quraysh", "the Prophet's Companions who never left Makkah"], "Muslims who emigrated from Makkah to Madinah",
      "'Muhajirun' (emigrants) refers to Makkan Muslims who left their homes to migrate to Madinah, distinguishing them from the Ansar, the Madinan 'helpers'."),
  _q("The term 'Ansar' in early Islamic history designates",
      ["the Madinan Muslims who welcomed and supported the emigrants from Makkah", "the Quraysh leaders who opposed the Prophet", "foreign envoys sent to Madinah", "the Prophet's bodyguards during military campaigns"], "the Madinan Muslims who welcomed and supported the emigrants from Makkah",
      "The Ansar ('helpers') were the native Muslims of Madinah (from the Aws and Khazraj tribes) who hosted and supported the Muhajirun after the Hijrah."),
];

final _rightlyGuidedCaliphs = [
  _q("The four Rightly Guided Caliphs (Al-Khulafa Ar-Rashidun) are, in chronological order,",
      ["Abu Bakr, Umar, Uthman, and Ali", "Ali, Umar, Abu Bakr, and Uthman", "Umar, Uthman, Abu Bakr, and Ali", "Abu Bakr, Ali, Umar, and Uthman"], "Abu Bakr, Umar, Uthman, and Ali",
      "The Rashidun Caliphs succeeded one another in this order, each contributing distinctly to the consolidation and expansion of the early Muslim state."),
  _q("Immediately after the death of Prophet Muhammad, the first challenge that Caliph Abu Bakr had to address was",
      ["the Wars of Apostasy (Ridda Wars) against tribes that renounced Islam or refused Zakat", "an invasion by the Byzantine Empire", "a civil war between the Muhajirun and Ansar", "the loss of Madinah to the Quraysh"], "the Wars of Apostasy (Ridda Wars) against tribes that renounced Islam or refused Zakat",
      "Following the Prophet's death, several Arab tribes apostatised or refused to pay Zakat; Abu Bakr firmly suppressed these rebellions in the Ridda Wars."),
  _q("One of Caliph Abu Bakr's most significant and lasting achievements was",
      ["initiating the compilation of the Qur'an into a single written text", "conquering the entire Persian Empire", "founding the city of Baghdad", "establishing the Umayyad dynasty"], "initiating the compilation of the Qur'an into a single written text",
      "Concerned by the loss of Qur'an reciters in battle, Abu Bakr commissioned Zayd ibn Thabit to collect the scattered revelations into a single authoritative manuscript."),
  _q("Caliph Umar ibn al-Khattab is particularly remembered for introducing",
      ["the Hijri calendar and formal administrative institutions such as the Diwan", "the compilation of Hadith into written books", "the practice of congregational Friday prayer", "the pilgrimage to the Ka'bah"], "the Hijri calendar and formal administrative institutions such as the Diwan",
      "Umar's caliphate saw major administrative reforms, including adopting the Hijrah as the starting point of the Islamic calendar and creating registers (Diwan) for state affairs and stipends."),
  _q("Under Caliph Umar's rule, major territorial expansions brought which two empires' territories substantially under Muslim control?",
      ["The Byzantine and Sasanian (Persian) Empires", "The Roman and Chinese Empires", "The Mongol and Ottoman Empires", "The Ethiopian and Indian Empires"], "The Byzantine and Sasanian (Persian) Empires",
      "During Umar's reign, Muslim armies achieved major victories against both the Byzantines (in Syria and Egypt) and the Sasanian Persians (in Iraq and Persia)."),
  _q("Caliph Uthman ibn Affan's most significant contribution to the preservation of Islamic scripture was",
      ["standardising the Qur'anic text into one official version and distributing copies to major provinces", "translating the Qur'an into Persian and Greek", "banning the recitation of the Qur'an in public", "commissioning the first Hadith collection"], "standardising the Qur'anic text into one official version and distributing copies to major provinces",
      "To resolve growing variations in recitation across the expanding empire, Uthman standardised the Qur'anic text (the 'Uthmanic codex') and sent authoritative copies to key regions."),
  _q("The assassination of Caliph Uthman ibn Affan led directly to",
      ["the outbreak of the first civil strife (Fitnah) within the Muslim community", "the immediate collapse of the Islamic state", "a peaceful transfer of power without incident", "the conversion of the Byzantine Empire to Islam"], "the outbreak of the first civil strife (Fitnah) within the Muslim community",
      "Uthman's assassination created deep political divisions, sparking the first major civil conflict (Fitnah) among Muslims, notably the Battle of the Camel and the Battle of Siffin."),
  _q("Caliph Ali ibn Abi Talib's caliphate was largely dominated by internal conflict, most notably the",
      ["Battles of the Camel and Siffin", "wars against the Byzantine Empire alone", "conquest of Spain", "expansion into India"], "Battles of the Camel and Siffin",
      "Ali's reign was marked by internal Muslim conflicts, including the Battle of the Camel against Aishah, Talhah, and Zubayr, and the Battle of Siffin against Mu'awiyah."),
  _q("The arbitration crisis following the Battle of Siffin, which Caliph Ali reluctantly accepted, led to the emergence of a dissenting group known as the",
      ["Khawarij (Kharijites)", "Ansar", "Muhajirun", "Ash'arites"], "Khawarij (Kharijites)",
      "The Khawarij broke away from Ali's camp in protest against the arbitration, considering it a violation of divine judgement, and later became a militant opposition group."),
  _q("The period of the four Rightly Guided Caliphs is generally regarded by Sunni Muslims as significant chiefly because",
      ["these caliphs were closely guided by the Prophetic example (Sunnah) and elected/chosen through community consultation", "they were all direct blood descendants of the Prophet in an unbroken hereditary line", "they ruled for over a century as a single unbroken dynasty", "the caliphate became strictly hereditary from Abu Bakr onward"], "these caliphs were closely guided by the Prophetic example (Sunnah) and elected/chosen through community consultation",
      "Unlike later hereditary dynasties, the Rashidun caliphs came to power through differing forms of community consultation (Shura) or nomination, and are esteemed for closely following the Prophet's example."),
];

final _islamInWestAfrica = [
  _q("Islam is generally believed to have reached West Africa mainly through",
      ["trans-Saharan trade routes linking North Africa to West African kingdoms", "direct military conquest by Arabian armies", "European colonial missionaries", "sea routes from the Persian Gulf to the Guinea coast"], "trans-Saharan trade routes linking North Africa to West African kingdoms",
      "Muslim traders travelling the trans-Saharan trade routes gradually introduced Islam to West African societies, especially through contact with rulers and merchant communities."),
  _q("Among the early West African empires, Islam gained significant royal patronage relatively early in",
      ["ancient Ghana and later Mali", "the Oyo Empire", "the Benin Kingdom", "the Ashanti Kingdom"], "ancient Ghana and later Mali",
      "The empires of ancient Ghana and, more prominently, Mali were among the earliest West African states where rulers embraced Islam and it received royal support."),
  _q("The Mali Emperor famed for his extravagant pilgrimage to Makkah in 1324, which spread awareness of West African wealth across the Muslim world, was",
      ["Mansa Musa", "Sunni Ali", "Askia Muhammad", "Sultan Bello"], "Mansa Musa",
      "Mansa Musa's lavish Hajj journey, during which he famously distributed large quantities of gold, brought international attention to the wealth and Islamic character of the Mali Empire."),
  _q("The Songhai ruler who significantly strengthened Islamic governance, scholarship, and administration, notably supporting the scholarly centre of Timbuktu, was",
      ["Askia Muhammad (Askia the Great)", "Mansa Musa", "Uthman Dan Fodio", "Muhammad Bello"], "Askia Muhammad (Askia the Great)",
      "Askia Muhammad promoted Islamic learning and law within the Songhai Empire, and made his own pilgrimage to Makkah, further cementing Islam's role in the state."),
  _q("Timbuktu, in the Songhai Empire, became especially renowned in West African Islamic history as a",
      ["centre of Islamic scholarship, particularly around Sankore University/Mosque", "coastal slave-trading port", "capital of the Sokoto Caliphate", "site of the first mosque built in West Africa"], "centre of Islamic scholarship, particularly around Sankore University/Mosque",
      "Timbuktu, especially its Sankore institution, developed into a major hub of Islamic learning, attracting scholars and students from across the region."),
  _q("Uthman Dan Fodio led his famous jihad in the early nineteenth century primarily in the region now known as",
      ["Hausaland (present-day northern Nigeria)", "the Niger Delta", "the Gold Coast (present-day Ghana)", "Senegambia"], "Hausaland (present-day northern Nigeria)",
      "Uthman Dan Fodio's jihad (beginning 1804) was waged in Hausaland, aiming to reform what he saw as corrupt and syncretic religious practice among Hausa rulers."),
  _q("One of the central grievances that motivated Uthman Dan Fodio's jihad against the Hausa rulers was",
      ["the mixing of Islamic practice with un-Islamic customs and oppressive taxation of the populace", "the Hausa rulers' complete rejection of Islam", "a dispute over trade routes with Europeans", "a succession dispute within his own family"], "the mixing of Islamic practice with un-Islamic customs and oppressive taxation of the populace",
      "Dan Fodio criticised the syncretism, injustice, and heavy taxation practised by many Hausa rulers, calling for a purer application of Islamic law and governance."),
  _q("The Islamic state established as a result of Uthman Dan Fodio's jihad, with its capital eventually at Sokoto, is known as the",
      ["Sokoto Caliphate", "Kanem-Bornu Empire", "Mali Empire", "Oyo Empire"], "Sokoto Caliphate",
      "The Sokoto Caliphate emerged from Dan Fodio's jihad as a major Islamic state uniting much of Hausaland under centralised Islamic governance."),
  _q("After Uthman Dan Fodio, leadership of the Sokoto Caliphate's administration was notably carried on by his son",
      ["Muhammad Bello", "Ahmadu Bello", "Ali Dan Fodio", "Modibbo Adama"], "Muhammad Bello",
      "Muhammad Bello succeeded his father as leader in Sokoto, consolidating and administering the new caliphate and founding the town of Sokoto as its capital."),
  _q("The spread of Islam into the forest regions of what is now south-western Nigeria (Yorubaland) occurred mainly through",
      ["gradual trade contacts and later the influence of returning ex-slaves and itinerant clerics", "the direct jihad campaigns of Uthman Dan Fodio himself", "European colonial imposition", "invasion by Songhai armies"], "gradual trade contacts and later the influence of returning ex-slaves and itinerant clerics",
      "Islam reached Yorubaland gradually, largely via trade with the north and the activities of Muslim clerics, with further growth aided later by returning liberated Muslims such as the Saro."),
  _q("The Kanem-Bornu Empire, located around Lake Chad, is historically significant in West African Islamic history for",
      ["being one of the earliest and longest-surviving Islamic states in the region", "leading the Sokoto jihad", "founding the city of Timbuktu", "resisting all contact with Islam until colonial rule"], "being one of the earliest and longest-surviving Islamic states in the region",
      "Kanem-Bornu adopted Islam very early (from around the 11th century) and persisted as an Islamic polity for many centuries, making it one of West Africa's most enduring Muslim states."),
];

final _quranAndHadith = [
  _q("The Qur'an, as a source of Islamic law and guidance, is understood by Muslims to be",
      ["the literal, unaltered word of Allah revealed to Prophet Muhammad through Angel Jibril", "a historical record compiled entirely by early scholars", "a collection of the Prophet's personal sayings and reflections", "a translated version of earlier Jewish and Christian scriptures"], "the literal, unaltered word of Allah revealed to Prophet Muhammad through Angel Jibril",
      "Muslims believe the Qur'an is the direct, verbatim revelation from Allah, transmitted through Angel Jibril to Prophet Muhammad over approximately 23 years."),
  _q("The Qur'an was revealed to Prophet Muhammad over a period of approximately",
      ["23 years", "10 years", "40 years", "3 years"], "23 years",
      "Revelation of the Qur'an occurred gradually over roughly 23 years, spanning both the Makkan and Madinan periods of the Prophet's mission."),
  _q("The scribe most closely associated with recording revelation during the Prophet's lifetime and later leading the Qur'an's compilation under Abu Bakr was",
      ["Zayd ibn Thabit", "Bilal ibn Rabah", "Salman al-Farisi", "Khalid ibn al-Walid"], "Zayd ibn Thabit",
      "Zayd ibn Thabit served as one of the Prophet's principal scribes of revelation and was later entrusted with compiling the Qur'an into a single manuscript."),
  _q("The chapters of the Qur'an are called",
      ["Surahs", "Ayahs", "Juz", "Hizb"], "Surahs",
      "The Qur'an is divided into 114 chapters known as Surahs, each further composed of verses called Ayahs."),
  _q("For the purposes of recitation and memorisation, the Qur'an is commonly divided into how many equal parts (Juz)?",
      ["30", "7", "60", "114"], "30",
      "The Qur'an is traditionally divided into 30 sections (Juz/Ajza) to facilitate its recitation across the days of a month, particularly during Ramadan."),
  _q("Surah Al-Fatihah, recited in every unit (Rak'ah) of the five daily prayers, is notable for",
      ["opening the Qur'an and summarising its core themes of praise, guidance, and supplication", "containing the longest chapter of the Qur'an", "being revealed entirely in the Madinan period", "detailing the rules of inheritance"], "opening the Qur'an and summarising its core themes of praise, guidance, and supplication",
      "Surah Al-Fatihah, 'The Opening', is a concise chapter praising Allah and asking for guidance, and its recitation is an essential part of every unit of the ritual prayer."),
  _q("Surah Al-Ikhlas is particularly notable in Islamic teaching for",
      ["its concise and powerful declaration of the absolute Oneness of Allah (Tawhid)", "narrating the story of Prophet Yusuf", "detailing the laws of marriage and divorce", "describing the Battle of Badr"], "its concise and powerful declaration of the absolute Oneness of Allah (Tawhid)",
      "Surah Al-Ikhlas is a short but theologically central chapter that affirms Allah's absolute Oneness, uniqueness, and self-sufficiency, rejecting any partners or equals."),
  _q("Surah Yasin is often referred to in popular Muslim tradition as",
      ["the 'heart' of the Qur'an", "the shortest Surah in the Qur'an", "a purely legal chapter with no narrative content", "the first Surah revealed to the Prophet"], "the 'heart' of the Qur'an",
      "Surah Yasin is widely regarded in tradition as holding a central, weighty status among the Qur'an's chapters and is frequently recited for its spiritual significance."),
  _q("Surah Al-Baqarah, the longest chapter of the Qur'an, is significant for containing, among other things, guidance on",
      ["a wide range of legal, social, and moral rulings, including the Verse of the Throne (Ayat al-Kursi)", "only narratives of pre-Islamic Arabia", "exclusively the story of the Prophet's Night Journey", "the complete Farewell Sermon"], "a wide range of legal, social, and moral rulings, including the Verse of the Throne (Ayat al-Kursi)",
      "As the Qur'an's longest Surah, Al-Baqarah covers extensive legal and moral guidance and includes Ayat al-Kursi, one of the most revered verses in the Qur'an."),
  _q("A Hadith, in Islamic terminology, refers to",
      ["a reported saying, action, or approval attributed to Prophet Muhammad", "a verse directly revealed in the Qur'an", "a ruling issued solely by a caliph", "a pre-Islamic Arabian proverb"], "a reported saying, action, or approval attributed to Prophet Muhammad",
      "Hadith literature records the sayings, deeds, and tacit approvals of the Prophet, forming the second major source of Islamic guidance after the Qur'an."),
  _q("The chain of narrators through which a Hadith is transmitted back to the Prophet is called the",
      ["Isnad (Sanad)", "Matn", "Tafsir", "Fiqh"], "Isnad (Sanad)",
      "The Isnad is the chain of transmitters cited before the text of a Hadith, used by scholars to assess the reliability and authenticity of the report."),
  _q("The actual textual content of a Hadith report, as distinct from its chain of narrators, is known as the",
      ["Matn", "Isnad", "Sirah", "Qiyas"], "Matn",
      "The Matn is the wording or substance of the Hadith itself, evaluated alongside the Isnad (chain of narration) in determining a Hadith's authenticity."),
  _q("A Hadith classified as 'Sahih' is one that is considered by scholars to be",
      ["authentic, having met the strictest criteria for a sound chain and text", "weak and largely unreliable", "fabricated and rejected outright", "of uncertain or disputed status"], "authentic, having met the strictest criteria for a sound chain and text",
      "'Sahih' (sound/authentic) is the highest grade of Hadith authenticity, indicating an unbroken, trustworthy chain of narrators and a text free from contradiction or defect."),
  _q("Among the six canonical Hadith collections widely regarded as most authoritative by Sunni Muslims, the two considered most rigorously authenticated are commonly known as",
      ["Sahih al-Bukhari and Sahih Muslim", "Sunan Abu Dawud and Sunan an-Nasa'i", "Sunan at-Tirmidhi and Sunan Ibn Majah", "Muwatta Malik and Musnad Ahmad"], "Sahih al-Bukhari and Sahih Muslim",
      "Compiled respectively by Imam Bukhari and Imam Muslim, these two collections are traditionally regarded by Sunni scholars as the most rigorously verified of the Hadith compilations."),
  _q("Imam Muhammad ibn Ismail al-Bukhari, compiler of one of the most authoritative Hadith collections, is especially noted for his",
      ["extremely rigorous criteria in verifying the authenticity of each Hadith he included", "reliance mainly on unverified oral traditions without scrutiny", "role as a Rightly Guided Caliph", "compilation of the Qur'an under Caliph Uthman"], "extremely rigorous criteria in verifying the authenticity of each Hadith he included",
      "Al-Bukhari is renowned for his exceptionally strict methodology in authenticating Hadith, examining narrators' reliability and the continuity of transmission chains before inclusion."),
  _q("The preservation of the Qur'an, in addition to its being written down, was also significantly reinforced during the Prophet's lifetime and after through",
      ["extensive oral memorisation (Hifz) by numerous companions", "translation into multiple languages immediately after revelation", "storage exclusively in a single royal archive", "encoding using a secret cipher"], "extensive oral memorisation (Hifz) by numerous companions",
      "Alongside written records, many companions memorised the Qur'an in its entirety, providing a strong oral safeguard that complemented the written text in ensuring its preservation."),
  _q("The scholarly discipline concerned with the interpretation and explanation of Qur'anic verses is known as",
      ["Tafsir", "Fiqh", "Kalam", "Sirah"], "Tafsir",
      "Tafsir refers to the field of Qur'anic exegesis, in which scholars explain the meanings, context, and implications of Qur'anic verses."),
];

final _fiqhAndTawhid = [
  _q("Tawhid, the foundational concept of Islamic belief, refers to",
      ["the absolute Oneness and uniqueness of Allah", "the collection of the Prophet's sayings", "the pilgrimage rites performed in Makkah", "the body of Islamic civil law"], "the absolute Oneness and uniqueness of Allah",
      "Tawhid is the core Islamic doctrine affirming that Allah is one, without partner, equal, or division, in His essence, attributes, and right to worship."),
  _q("The opposite of Tawhid, namely associating partners with Allah in worship, is termed",
      ["Shirk", "Ijtihad", "Zakat", "Sunnah"], "Shirk",
      "Shirk is regarded in Islam as the gravest sin, involving the ascription of divinity, power, or worship-worthiness to anything besides Allah."),
  _q("Scholars commonly divide Tawhid into three interconnected categories: Tawhid ar-Rububiyyah, Tawhid al-Uluhiyyah, and",
      ["Tawhid al-Asma was-Sifat", "Tawhid al-Fiqh", "Tawhid al-Hadith", "Tawhid al-Ijma"], "Tawhid al-Asma was-Sifat",
      "The three categories are Tawhid ar-Rububiyyah (Oneness of Lordship), Tawhid al-Uluhiyyah (Oneness of Worship), and Tawhid al-Asma was-Sifat (Oneness of Allah's Names and Attributes)."),
  _q("Tawhid ar-Rububiyyah specifically concerns belief in Allah's",
      ["sole role as Creator, Sustainer, and Controller of the universe", "exclusive right to be worshipped", "unique names and attributes only", "role as lawgiver in matters of Fiqh"], "sole role as Creator, Sustainer, and Controller of the universe",
      "This category of Tawhid affirms that Allah alone creates, sustains, and governs all that exists, without partner in these functions."),
  _q("The category of Tawhid concerned specifically with directing all acts of worship exclusively to Allah alone is",
      ["Tawhid al-Uluhiyyah", "Tawhid ar-Rububiyyah", "Tawhid al-Asma was-Sifat", "Tawhid al-Iman"], "Tawhid al-Uluhiyyah",
      "Tawhid al-Uluhiyyah (also called Tawhid al-Ibadah) requires that prayer, supplication, and all forms of worship be directed to Allah alone, with no intermediary or partner."),
  _q("In Islamic terminology, acts of worship performed to draw closer to Allah, such as Salah, Sawm, and Hajj, are collectively termed",
      ["Ibadah", "Shirk", "Qiyas", "Muamalat"], "Ibadah",
      "Ibadah refers broadly to acts of devotion and worship prescribed by Islam, encompassing ritual acts such as prayer, fasting, almsgiving, and pilgrimage."),
  _q("The Five Pillars of Islam are the Shahadah, Salah, Zakat, Sawm, and",
      ["Hajj", "Jihad", "Ijma", "Qiyas"], "Hajj",
      "The Five Pillars form the foundational framework of Muslim practice: the declaration of faith, prayer, almsgiving, fasting, and pilgrimage to Makkah for those able."),
  _q("The declaration of faith that constitutes the first Pillar of Islam is known as the",
      ["Shahadah", "Takbir", "Tasbih", "Talbiyah"], "Shahadah",
      "The Shahadah is the testimony affirming there is no god but Allah and that Muhammad is His Messenger, forming the entry point into the Islamic faith."),
  _q("Zakat, the third Pillar of Islam, is best described as",
      ["an obligatory charitable levy on qualifying wealth, given to specified categories of recipients", "a purely voluntary act of charity with no fixed rate", "a tax paid only by non-Muslims living under Muslim rule", "an annual pilgrimage obligation"], "an obligatory charitable levy on qualifying wealth, given to specified categories of recipients",
      "Zakat is a compulsory, calculated portion of a Muslim's qualifying wealth, distributed to specific categories of beneficiaries such as the poor and needy, distinguishing it from voluntary charity (Sadaqah)."),
  _q("The fasting prescribed as obligatory during the month of Ramadan is referred to as",
      ["Sawm", "Salah", "I'tikaf", "Tahajjud"], "Sawm",
      "Sawm is the obligatory fast observed from dawn to sunset throughout the month of Ramadan, one of the Five Pillars of Islam."),
  _q("The pilgrimage to Makkah, obligatory once in a lifetime for financially and physically capable Muslims, is known as",
      ["Hajj", "Umrah", "Ziyarah", "I'tikaf"], "Hajj",
      "Hajj is the major pilgrimage performed during a specific period in the Islamic month of Dhul-Hijjah, and is obligatory once in a lifetime for those who are able."),
  _q("Unlike Hajj, the lesser pilgrimage that can be performed at any time of the year is called",
      ["Umrah", "Tawaf al-Ifadah", "Sa'i", "Wuquf"], "Umrah",
      "Umrah shares some rites with Hajj, such as Tawaf and Sa'i, but is shorter, not obligatory, and may be performed at any time outside the fixed Hajj season."),
  _q("The body of Islamic jurisprudence dealing with legal rulings derived from the Qur'an, Sunnah, and other recognised sources is known as",
      ["Fiqh", "Tafsir", "Sirah", "Kalam"], "Fiqh",
      "Fiqh refers to the human scholarly effort of deriving detailed legal rulings from the primary sources of Islamic law."),
  _q("The independent legal reasoning exercised by qualified jurists to derive rulings on matters not explicitly addressed in the Qur'an or Sunnah is called",
      ["Ijtihad", "Taqlid", "Ijma", "Bid'ah"], "Ijtihad",
      "Ijtihad is the process by which a qualified scholar (Mujtahid) applies rigorous reasoning to derive legal rulings on new or unaddressed issues."),
  _q("The consensus of qualified Muslim jurists on a particular point of Islamic law is termed",
      ["Ijma", "Qiyas", "Istihsan", "Urf"], "Ijma",
      "Ijma refers to the collective agreement of qualified scholars on a legal ruling, recognised as one of the secondary sources of Islamic law."),
  _q("The method of legal reasoning that extends an existing ruling to a new, similar case based on a shared underlying cause is known as",
      ["Qiyas (analogical reasoning)", "Ijma (consensus)", "Ijtihad in its general sense only", "Naskh (abrogation)"], "Qiyas (analogical reasoning)",
      "Qiyas involves deriving a ruling for a new situation by drawing an analogy with an existing ruling, based on a common underlying reason ('illah)."),
  _q("Within Fiqh, the branch of law that governs everyday social and commercial transactions, such as contracts, trade, and marriage, is known as",
      ["Mu'amalat", "Ibadat", "Aqidah", "Akhlaq"], "Mu'amalat",
      "Mu'amalat covers the sphere of interpersonal and commercial dealings, as distinct from Ibadat, which governs acts of worship."),
  _q("Under Islamic commercial law (Mu'amalat), the charging or paying of interest on loans, known as Riba, is",
      ["strictly prohibited", "permitted without restriction", "encouraged for economic growth", "allowed only between Muslims and non-Muslims"], "strictly prohibited",
      "Riba is explicitly and firmly prohibited in Islamic law, as it is considered exploitative and contrary to principles of justice in financial dealings."),
  _q("Which of the following acts is generally classified under Shariah as one of the major sins (Kaba'ir)?",
      ["Consuming intoxicants", "Performing the five daily prayers", "Giving voluntary charity", "Fasting outside Ramadan"], "Consuming intoxicants",
      "The consumption of intoxicants (Khamr) is explicitly prohibited in Islamic law and is classified among the major sins due to its harmful effects on the individual and society."),
  _q("In Islamic family law under Shariah, a marriage contract (Nikah) requires, among other conditions, that",
      ["there be mutual consent of the parties, a dowry (Mahr), and witnesses", "the marriage be conducted in complete secrecy without witnesses", "no dowry of any kind be given", "only the groom's consent is legally necessary"], "there be mutual consent of the parties, a dowry (Mahr), and witnesses",
      "A valid Islamic marriage contract requires the free consent of both parties, the specification of a dowry for the bride, and the presence of witnesses."),
  _q("What is the meaning of the term 'Sunnah' in Islamic scholarship?",
      ["The sayings, actions, and approvals attributed to Prophet Muhammad", "A chapter of the Qur'an", "A type of ritual prayer performed only on Fridays", "A tax paid by non-Muslims"], "The sayings, actions, and approvals attributed to Prophet Muhammad",
      "Sunnah refers to the recorded traditions of the Prophet Muhammad's words, deeds, and tacit approvals, forming a key source of Islamic guidance alongside the Qur'an."),
  _q("What is Zakat, one of the Five Pillars of Islam?",
      ["Obligatory almsgiving to those in need", "The declaration of faith", "The pilgrimage to Makkah", "The fast during Ramadan"], "Obligatory almsgiving to those in need",
      "Zakat is a compulsory form of almsgiving, calculated as a portion of a Muslim's wealth, given to specified categories of people in need."),
  _q("What is the Islamic term for the pilgrimage to Makkah that able Muslims are obliged to perform at least once in their lifetime?",
      ["Hajj", "Zakat", "Sawm", "Salat"], "Hajj",
      "Hajj is the annual Islamic pilgrimage to Makkah, obligatory once in a lifetime for Muslims who are physically and financially able."),
  _q("What is the significance of the Hijrah in Islamic history?",
      ["It marks the migration of Prophet Muhammad from Makkah to Madinah and the start of the Islamic calendar", "It refers to the first revelation of the Qur'an", "It refers to the conquest of Makkah", "It marks the death of the Prophet"], "It marks the migration of Prophet Muhammad from Makkah to Madinah and the start of the Islamic calendar",
      "The Hijrah (migration to Madinah in 622 CE) is a pivotal event in Islamic history and marks the beginning of the Islamic (Hijri) calendar."),
  _q("Who was the first Caliph (Khalifah) after the death of Prophet Muhammad?",
      ["Abu Bakr", "Umar ibn al-Khattab", "Uthman ibn Affan", "Ali ibn Abi Talib"], "Abu Bakr",
      "Abu Bakr was chosen as the first of the four Rightly Guided Caliphs following the death of the Prophet."),
  _q("What does the term 'Tawhid' refer to in Islamic theology?",
      ["The oneness and uniqueness of God", "The concept of predestination", "The Islamic legal system", "The practice of charity"], "The oneness and uniqueness of God",
      "Tawhid is the central Islamic doctrine affirming the absolute oneness and uniqueness of God (Allah)."),
  _q("What is the significance of the Battle of Badr in early Islamic history?",
      ["It was the first major military victory for the early Muslim community over the Makkan forces", "It marked the final defeat of the Muslims", "It was a peace treaty between Muslims and Makkans", "It was the site of the first Qur'anic revelation"], "It was the first major military victory for the early Muslim community over the Makkan forces",
      "The Battle of Badr (624 CE) was a decisive early victory for the Muslim community against a larger Makkan force, significant for morale and Islamic history."),
  _q("What is the meaning of 'Ummah' in Islamic thought?",
      ["The global community of Muslims", "A local mosque", "A specific prayer", "An Islamic school of law"], "The global community of Muslims",
      "'Ummah' refers to the worldwide community of Muslims, united by shared faith regardless of ethnicity or nationality."),
];
