import "../quiz_question.dart";

QuizQuestion _q(String subject, String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

const _englishSubject = "English Language";
const _mathsSubject = "Mathematics";
const _gkSubject = "General Knowledge";

QuizQuestion _eq(String text, List<String> options, String correct, String explanation) =>
    _q(_englishSubject, text, options, correct, explanation);

QuizQuestion _mq(String text, List<String> options, String correct, String explanation) =>
    _q(_mathsSubject, text, options, correct, explanation);

QuizQuestion _gq(String text, List<String> options, String correct, String explanation) =>
    _q(_gkSubject, text, options, correct, explanation);

/// Obafemi Awolowo University (OAU), Ile-Ife Post-UTME practice bank — 100+
/// questions covering the three areas most Nigerian Post-UTME screening
/// exams draw on: English Language, Mathematics, and General Knowledge
/// (including current affairs, and OAU/Osun State/Ile-Ife facts). This is a
/// general-purpose practice set, not an official OAU past-question paper;
/// always confirm the exact format and syllabus on OAU's own screening
/// portal for the current session.
List<QuizQuestion> buildOauPostUtmeQuestions() {
  return [
    ..._englishLanguage,
    ..._mathematics,
    ..._generalKnowledge,
  ];
}

/// Individual-subject accessors used by the Post-UTME subject picker, which
/// lets a student choose specific subjects rather than sit the full mixed
/// bank above.
List<QuizQuestion> buildOauEnglishLanguageQuestions() => List.of(_englishLanguage);
List<QuizQuestion> buildOauMathematicsQuestions() => List.of(_mathematics);
List<QuizQuestion> buildOauGeneralKnowledgeQuestions() => List.of(_generalKnowledge);

const _passage =
    "Across many small towns and rural communities, entrepreneurship has become one of the most reliable "
    "paths out of poverty, especially where formal employment is scarce. A young tailor who once served only "
    "her immediate neighbours can, with a smartphone and a modest data plan, now showcase her designs to "
    "customers hundreds of kilometres away. Microfinance institutions and cooperative societies have also "
    "made small loans more accessible, allowing traders and artisans to expand their businesses without "
    "depending on relatives or moneylenders. Even so, many entrepreneurs still struggle with unreliable "
    "electricity, poor road networks, and limited access to affordable credit, all of which raise the cost "
    "of doing business. Governments and development agencies increasingly recognise that supporting small "
    "and medium enterprises is not merely a charitable gesture but a sound strategy for building resilient, "
    "self-sustaining local economies.";

QuizQuestion _ucq(String question, List<String> options, String correct, String explanation) =>
    _eq("$_passage\n\n$question", options, correct, explanation);

final _englishLanguage = [
  _ucq("According to the passage, what has enabled a small-town tailor to reach distant customers?",
      ["A smartphone and a modest data plan", "A large factory built with foreign investment", "A government-issued export licence", "A partnership with a multinational retailer"], "A smartphone and a modest data plan",
      "The passage states that with 'a smartphone and a modest data plan', the tailor can showcase her designs to customers far away."),
  _ucq("What role have microfinance institutions and cooperative societies played, according to the passage?",
      ["Making small loans more accessible to traders and artisans", "Eliminating the need for any form of credit", "Replacing all formal banks in rural areas", "Providing free equipment to every entrepreneur"], "Making small loans more accessible to traders and artisans",
      "The passage notes these institutions 'have also made small loans more accessible', reducing reliance on relatives or moneylenders."),
  _ucq("What challenges do many entrepreneurs still face, as described in the passage?",
      ["Unreliable electricity, poor roads, and limited access to affordable credit", "Excessive government interference in daily operations", "A complete lack of customers", "Overregulation of internet access"], "Unreliable electricity, poor roads, and limited access to affordable credit",
      "The passage lists these three challenges as ones that 'raise the cost of doing business.'"),
  _ucq("According to the passage, how do governments and development agencies increasingly view support for small and medium enterprises?",
      ["As a sound strategy for building resilient, self-sustaining economies", "As an unnecessary expense with no economic benefit", "As a purely charitable gesture with no strategic value", "As a temporary measure to be phased out soon"], "As a sound strategy for building resilient, self-sustaining economies",
      "The passage concludes that such support is 'not merely a charitable gesture but a sound strategy' for building resilient local economies."),
  _ucq("What was the tailor's situation before gaining wider reach, according to the passage?",
      ["She served only her immediate neighbours", "She exported goods internationally", "She worked exclusively for a large company", "She had no customers at all"], "She served only her immediate neighbours",
      "The passage says she 'once served only her immediate neighbours' before expanding her reach."),
  _ucq("What is the closest meaning of the word 'resilient' as used in the passage?",
      ["Able to recover from difficulties and remain strong", "Extremely fragile and prone to failure", "Entirely dependent on foreign aid", "Temporary and short-lived"], "Able to recover from difficulties and remain strong",
      "'Resilient' describes something able to withstand or recover quickly from difficulties, fitting the context of a strong local economy."),
  _eq("Choose the option that best completes the sentence: 'Neither the manager nor the staff ___ aware of the change.'",
      ["was", "were", "have been", "are being"], "was",
      "With 'neither...nor', the verb agrees with the subject nearer to it ('the staff' is closer, but in strict traditional grammar with a singular first noun and this construction pattern, 'was' agrees with the nearer singular sense expected here); standard practice: the verb agrees with the nearest subject, 'staff' functioning as a collective singular unit in this context, giving 'was'."),
  _eq("Choose the option nearest in meaning to the underlined word: 'Her ARDUOUS journey to the village took three days.'",
      ["Difficult and tiring", "Short and easy", "Pleasant and relaxing", "Free of charge"], "Difficult and tiring",
      "'Arduous' means involving strenuous effort or difficulty, making 'difficult and tiring' the closest synonym."),
  _eq("Choose the option opposite in meaning to the underlined word: 'The new regulations were met with UNANIMOUS approval.'",
      ["Divided", "Complete", "Universal", "Enthusiastic"], "Divided",
      "'Unanimous' means everyone in agreement; its opposite is 'divided', meaning split in opinion."),
  _eq("Choose the correctly spelt word.",
      ["Accommodate", "Accomodate", "Acommodate", "Accommadate"], "Accommodate",
      "'Accommodate' is correctly spelt with double 'c' and double 'm'; the other options misspell the word."),
  _eq("Choose the option that best completes the sentence: 'If I ___ you, I would apologise immediately.'",
      ["were", "was", "am", "will be"], "were",
      "This is a second conditional expressing a hypothetical situation, requiring the subjunctive 'were' regardless of subject."),
  _eq("Choose the correct preposition to complete the sentence: 'The book is quite similar ___ the one I read last year.'",
      ["to", "with", "from", "for"], "to",
      "'Similar to' is the standard and correct preposition pairing in English usage."),
  _eq("Identify the part of speech of the underlined word: 'The SUDDENLY loud noise startled everyone.'",
      ["Adverb", "Adjective", "Noun", "Conjunction"], "Adverb",
      "'Suddenly' modifies the adjective 'loud', describing the manner of the noise becoming loud, making it an adverb."),
  _eq("Choose the option that is the correct plural form of 'crisis'.",
      ["Crises", "Crisises", "Crisis's", "Crisi"], "Crises",
      "'Crisis', derived from Greek, forms its plural irregularly as 'crises'."),
  _eq("Choose the option nearest in meaning to the idiom: 'The manager decided to TURN A BLIND EYE to the minor infraction.'",
      ["Deliberately ignore something", "Report the matter immediately", "Investigate thoroughly", "Punish severely"], "Deliberately ignore something",
      "'Turn a blind eye' is an idiom meaning to deliberately ignore or pretend not to notice something."),
  _eq("Choose the option that correctly completes the sentence: 'Mathematics ___ a compulsory subject in secondary school.'",
      ["is", "are", "were", "have been"], "is",
      "Although 'mathematics' ends in 's', it is treated as a singular subject when referring to the academic discipline, requiring 'is'."),
  _eq("Choose the word that best completes the sentence: 'The ___ evidence convinced the jury of his guilt.'",
      ["conclusive", "conclusion", "concluding", "conclude"], "conclusive",
      "'Conclusive' is the adjective form needed to describe the evidence as decisive and final."),
  _eq("Choose the correctly punctuated sentence.",
      ["Please bring the following: a pen, a notebook, and a calculator.", "Please bring the following a pen, a notebook, and a calculator.", "Please bring the following, a pen a notebook and a calculator.", "Please bring the following; a pen, a notebook, and a calculator."], "Please bring the following: a pen, a notebook, and a calculator.",
      "A colon correctly introduces the list following the complete independent clause 'Please bring the following.'"),
  _eq("Choose the option that best completes the sentence: 'The information he provided ___ inaccurate.'",
      ["was", "were", "have been", "having been"], "was",
      "'Information' is an uncountable noun that takes a singular verb, so 'was inaccurate' is correct."),
  _eq("Identify the figure of speech used: 'The wind whispered through the trees.'",
      ["Personification", "Simile", "Hyperbole", "Onomatopoeia"], "Personification",
      "Giving the wind the human ability to 'whisper' attributes a human action to a non-human thing, making this personification."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The company's growth has been remarkably RAPID.'",
      ["Very fast", "Very slow", "Uncertain", "Negligible"], "Very fast",
      "'Rapid' means happening at a fast pace, making 'very fast' the closest synonym."),
  _eq("Choose the correct form of the verb: 'Each of the students ___ expected to submit an assignment.'",
      ["is", "are", "were", "have"], "is",
      "'Each' is grammatically singular, so it takes the singular verb 'is', regardless of the plural noun that follows."),
  _eq("Choose the option that best completes the sentence: 'This is the town ___ history dates back centuries.'",
      ["whose", "who's", "which is", "that is"], "whose",
      "'Whose' is the possessive relative pronoun correctly used to link 'the town' to 'its history.'"),
  _eq("Choose the word opposite in meaning to the underlined word: 'The results of the experiment were CONCLUSIVE.'",
      ["Inconclusive", "Definite", "Certain", "Clear"], "Inconclusive",
      "'Conclusive' means decisive or definite; its direct opposite is 'inconclusive', meaning not leading to a firm conclusion."),
  _eq("Choose the correct option to complete the sentence: 'He is not only intelligent ___ also hardworking.'",
      ["but", "and", "so", "or"], "but",
      "The correlative pairing 'not only...but also' is the standard grammatical construction linking two related qualities."),
  _eq("Identify the correctly spelt word.",
      ["Necessary", "Neccessary", "Necesary", "Neccesary"], "Necessary",
      "'Necessary' is correctly spelt with one 'c' and double 's'; the other options are misspellings."),
  _eq("Choose the option that best completes the sentence: 'It was they who ___ blamed for the delay.'",
      ["were", "was", "is being", "have been"], "were",
      "The subject 'they' requires the plural past tense verb 'were' for grammatical agreement."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The professor's argument was remarkably COGENT.'",
      ["Clear and convincing", "Vague and unclear", "Overly long", "Full of contradictions"], "Clear and convincing",
      "'Cogent' means clear, logical, and convincing, especially of an argument."),
  _eq("Choose the correct option: 'This decision affects both you and ___.'",
      ["me", "I", "myself", "mine"], "me",
      "After the conjunction 'and' within a prepositional object position, the objective case pronoun 'me' is correct."),
  _eq("Choose the option that correctly completes the sentence: 'The majority of the residents ___ opposed to the new tax.'",
      ["are", "is", "was", "has been"], "are",
      "'The majority of' followed by a plural noun ('residents') takes a plural verb."),
  _eq("Choose the option that best expresses the meaning of the sentence: 'She decided to bite the bullet and accept the challenging assignment.'",
      ["She chose to face a difficult situation bravely", "She literally bit down on a bullet", "She refused to accept the assignment", "She postponed her decision indefinitely"], "She chose to face a difficult situation bravely",
      "'Bite the bullet' is an idiom meaning to face a difficult or unpleasant situation with courage."),
  _eq("Choose the word that is nearest in meaning to the underlined word: 'The old building was in a state of complete DECREPITUDE.'",
      ["Being worn out and in poor condition", "Excellent preservation", "Modern renovation", "Complete restoration"], "Being worn out and in poor condition",
      "'Decrepitude' refers to a state of being worn out or in poor condition due to age or neglect."),
  _eq("Choose the correct sentence.",
      ["Everybody has to bring his or her own textbook.", "Everybody have to bring their own textbook.", "Everybody has to bring they own textbook.", "Everybody have to bring his own textbook."], "Everybody has to bring his or her own textbook.",
      "'Everybody' is grammatically singular, so it takes the singular verb 'has' and a singular possessive form in formal usage."),
];

final _mathematics = [
  _mq("Simplify: 6(x + 3) - 4(x - 2)",
      ["2x + 26", "2x + 10", "10x + 10", "2x - 10"], "2x + 26",
      "6(x+3) - 4(x-2) = 6x + 18 - 4x + 8 = 2x + 26."),
  _mq("Solve for x: 5x - 7 = 23",
      ["x = 6", "x = 30", "x = 4", "x = 3"], "x = 6",
      "5x - 7 = 23, so 5x = 30, giving x = 6."),
  _mq("What is the value of 3^4?",
      ["81", "12", "64", "27"], "81",
      "3^4 = 3x3x3x3 = 81."),
  _mq("Simplify: (2/3) + (1/6)",
      ["5/6", "3/9", "1/2", "3/6"], "5/6",
      "Using a common denominator of 6: (2/3 = 4/6) + (1/6) = 5/6."),
  _mq("Find x if 9x + 4 = 6x + 25",
      ["x = 7", "x = 3", "x = 21", "x = 29"], "x = 7",
      "9x + 4 = 6x + 25, so 3x = 21, giving x = 7."),
  _mq("What is 15% of 480?",
      ["72", "64", "48", "80"], "72",
      "15% of 480 = 0.15 x 480 = 72."),
  _mq("The average of 8 numbers is 12. What is their sum?",
      ["96", "12", "20", "84"], "96",
      "Sum = average x count = 12 x 8 = 96."),
  _mq("Solve: x^2 - 49 = 0",
      ["x = 7 or x = -7", "x = 49 or x = -49", "x = 7 only", "x = -49 only"], "x = 7 or x = -7",
      "x^2 = 49, so x = sqrt(49) = +-7, giving x = 7 or x = -7."),
  _mq("If the ratio of boys to girls in a class is 3:4 and there are 12 boys, how many girls are there?",
      ["16", "9", "15", "20"], "16",
      "3 parts = 12, so 1 part = 4. Girls = 4 parts = 4 x 4 = 16."),
  _mq("What is the perimeter of a rectangle with length 12cm and width 7cm?",
      ["38cm", "84cm", "19cm", "42cm"], "38cm",
      "Perimeter of a rectangle = 2(length + width) = 2(12+7) = 2 x 19 = 38cm."),
  _mq("What is the area of a circle with radius 7cm? (Use pi = 22/7)",
      ["154 cm^2", "44 cm^2", "22 cm^2", "308 cm^2"], "154 cm^2",
      "Area = pi r^2 = (22/7) x 7 x 7 = 22 x 7 = 154 cm^2."),
  _mq("Simplify: 2^3 x 2^4",
      ["2^7 = 128", "2^12", "4^7", "2^1 = 2"], "2^7 = 128",
      "When multiplying powers with the same base, add the exponents: 2^3 x 2^4 = 2^7 = 128."),
  _mq("What is the value of the square root of 169?",
      ["13", "14", "84.5", "26"], "13",
      "The square root of 169 is 13, since 13 x 13 = 169."),
  _mq("A motorist travels 150km in 2.5 hours. What is their average speed?",
      ["60 km/h", "375 km/h", "75 km/h", "50 km/h"], "60 km/h",
      "Average speed = distance/time = 150/2.5 = 60 km/h."),
  _mq("Solve for x: (x/5) + 4 = 9",
      ["x = 25", "x = 5", "x = 45", "x = 1"], "x = 25",
      "(x/5) = 5, so x = 25."),
  _mq("What is the sum of the interior angles of a heptagon (7 sides)?",
      ["900 degrees", "720 degrees", "540 degrees", "1080 degrees"], "900 degrees",
      "The sum of interior angles of a polygon = (n-2) x 180, so for a heptagon (n=7): (7-2) x 180 = 900 degrees."),
  _mq("What is the sum of the interior angles of an octagon (8 sides)?",
      ["1080 degrees", "900 degrees", "720 degrees", "1260 degrees"], "1080 degrees",
      "Using (n-2) x 180 for an octagon (n=8): (8-2) x 180 = 1080 degrees."),
  _mq("Factorise: x^2 - 5x + 6",
      ["(x - 2)(x - 3)", "(x + 2)(x + 3)", "(x - 1)(x - 6)", "(x + 6)(x - 1)"], "(x - 2)(x - 3)",
      "We need two numbers that multiply to 6 and add to -5: -2 and -3. So x^2-5x+6 = (x-2)(x-3)."),
  _mq("What is 0.75 expressed as a fraction in its lowest terms?",
      ["3/4", "75/100", "7/10", "2/3"], "3/4",
      "0.75 = 75/100, which simplifies to 3/4 when divided by 25."),
  _mq("If a = 6 and b = -2, find the value of a^2 - b^2",
      ["32", "40", "4", "16"], "32",
      "a^2 - b^2 = 36 - 4 = 32."),
  _mq("What is the median of the data set: 5, 7, 9, 12, 18?",
      ["9", "7", "12", "10.2"], "9",
      "With 5 values arranged in order (5,7,9,12,18), the median is the middle value: 9."),
  _mq("What is the mode of the data set: 2, 4, 4, 6, 7, 4, 9?",
      ["4", "6", "7", "9"], "4",
      "The mode is the most frequently occurring value; 4 appears three times, more than any other value."),
  _mq("Convert 7/8 to a percentage.",
      ["87.5%", "78%", "7.8%", "70%"], "87.5%",
      "7/8 = 0.875, which as a percentage is 87.5%."),
  _mq("What is the LCM (Lowest Common Multiple) of 4 and 10?",
      ["20", "40", "14", "2"], "20",
      "Multiples of 4: 4,8,12,16,20...; multiples of 10: 10,20...; the smallest common multiple is 20."),
  _mq("What is the HCF (Highest Common Factor) of 24 and 36?",
      ["12", "6", "72", "4"], "12",
      "The factors of 24 are 1,2,3,4,6,8,12,24; factors of 36 are 1,2,3,4,6,9,12,18,36; the highest common factor is 12."),
  _mq("If 2x + 3y = 18 and x = 3, find the value of y.",
      ["4", "6", "8", "2"], "4",
      "Substituting x=3: 2(3) + 3y = 18, so 6 + 3y = 18, giving 3y = 12, so y = 4."),
  _mq("A trader sells an item for N9,600 after a 20% discount on the original price. What was the original price?",
      ["N12,000", "N11,520", "N7,680", "N10,000"], "N12,000",
      "If N9,600 represents 80% of the original price, then original price = 9,600/0.8 = N12,000."),
  _mq("What is the next number in the sequence: 2, 6, 18, 54, ___?",
      ["162", "108", "216", "72"], "162",
      "Each term is multiplied by 3 to get the next term: 54 x 3 = 162."),
  _mq("Simplify: (3a^2b) x (5ab^2)",
      ["15a^3b^3", "8a^3b^3", "15a^2b^2", "8a^2b^2"], "15a^3b^3",
      "Multiplying coefficients: 3x5=15. Multiplying a terms: a^2 x a = a^3. Multiplying b terms: b x b^2 = b^3. Result: 15a^3b^3."),
  _mq("What is the value of x in the equation: 3(x - 2) = 2(x + 4)",
      ["x = 14", "x = 4", "x = 6", "x = 10"], "x = 14",
      "3x - 6 = 2x + 8, so 3x - 2x = 8 + 6, giving x = 14."),
  _mq("A rectangular plot has an area of 200 square metres and a width of 8 metres. What is its length?",
      ["25 metres", "10 metres", "20 metres", "16 metres"], "25 metres",
      "Length = Area/Width = 200/8 = 25 metres."),
  _mq("What is the probability of picking a blue ball from a bag containing 5 red and 3 blue balls?",
      ["3/8", "1/3", "5/8", "1/5"], "3/8",
      "Total balls = 5 + 3 = 8. Probability of blue = 3/8."),
  _mq("Express 6.5 x 10^3 as an ordinary number.",
      ["6,500", "650", "65,000", "0.65"], "6,500",
      "6.5 x 10^3 = 6.5 x 1000 = 6,500."),
  _mq("Simplify: 4^2 - 2^3",
      ["8", "0", "24", "16"], "8",
      "4^2 = 16 and 2^3 = 8, so 16 - 8 = 8."),
];

final _generalKnowledge = [
  _gq("Obafemi Awolowo University (OAU) is located in which town in Osun State?",
      ["Ile-Ife", "Osogbo", "Ede", "Ikire"], "Ile-Ife",
      "OAU is located in Ile-Ife, a historic town in Osun State, south-western Nigeria."),
  _gq("What was Obafemi Awolowo University originally named when it was founded in 1962?",
      ["University of Ife", "University of Osun", "Ife Federal University", "Yoruba National University"], "University of Ife",
      "The institution was established in 1962 as the University of Ife before being renamed in 1987."),
  _gq("In what year was the University of Ife officially renamed Obafemi Awolowo University?",
      ["1987", "1962", "1999", "1975"], "1987",
      "The university was renamed Obafemi Awolowo University in 1987 in honour of Chief Obafemi Awolowo, a prominent Nigerian statesman."),
  _gq("After whom is Obafemi Awolowo University named?",
      ["Chief Obafemi Awolowo", "Nnamdi Azikiwe", "Ahmadu Bello", "Herbert Macaulay"], "Chief Obafemi Awolowo",
      "The university is named after Chief Obafemi Awolowo, a Nigerian nationalist and the first Premier of the Western Region."),
  _gq("Ile-Ife, home to OAU, is traditionally regarded by the Yoruba people as what?",
      ["The cradle of Yoruba civilization", "The site of the first Nigerian parliament", "The capital of the old Northern Region", "The location of Nigeria's first seaport"], "The cradle of Yoruba civilization",
      "Ile-Ife holds deep cultural and historical significance as the traditional cradle of Yoruba civilization, according to Yoruba oral history and tradition."),
  _gq("Which traditional ruler is the recognised paramount monarch based in Ile-Ife?",
      ["The Ooni of Ife", "The Alaafin of Oyo", "The Oba of Benin", "The Emir of Kano"], "The Ooni of Ife",
      "The Ooni of Ife is the traditional monarch of Ile-Ife and one of the most revered traditional rulers among the Yoruba people."),
  _gq("OAU's main campus is widely noted for which distinctive architectural feature?",
      ["Modernist campus architecture and design", "Colonial Gothic-style buildings", "Entirely underground lecture halls", "A campus built solely of mud brick huts"], "Modernist campus architecture and design",
      "OAU is well known for its distinctive modernist campus architecture, designed in the 1960s and often cited as a landmark of Nigerian architectural design."),
  _gq("Which UNESCO World Heritage Site, associated with Yoruba religion and culture, is located in Osun State?",
      ["Osun-Osogbo Sacred Grove", "Sukur Cultural Landscape", "Sungbo's Eredo", "Nok Terracotta Site"], "Osun-Osogbo Sacred Grove",
      "The Osun-Osogbo Sacred Grove, located along the banks of the Osun River in Osogbo, was inscribed as a UNESCO World Heritage Site in 2005."),
  _gq("Which river is closely associated with the Osun-Osogbo Sacred Grove and its annual festival?",
      ["Osun River", "Niger River", "Benue River", "Ogun River"], "Osun River",
      "The Osun-Osogbo Sacred Grove sits along the Osun River, and the annual Osun-Osogbo Festival celebrates the river goddess Osun."),
  _gq("What is the capital city of Osun State?",
      ["Osogbo", "Ile-Ife", "Ede", "Ilesa"], "Osogbo",
      "Osogbo is the capital of Osun State, while Ile-Ife remains historically and culturally significant as the seat of the Ooni."),
  _gq("Osun State was carved out of which larger state in 1991?",
      ["Oyo State", "Ondo State", "Ogun State", "Kwara State"], "Oyo State",
      "Osun State was created in August 1991 out of the former Oyo State during Nigeria's state creation exercise under General Ibrahim Babangida."),
  _gq("Which ethnic group forms the predominant population of Osun State and Ile-Ife?",
      ["Yoruba", "Igbo", "Hausa", "Ijaw"], "Yoruba",
      "Osun State, including Ile-Ife, is predominantly inhabited by the Yoruba ethnic group."),
  _gq("Which regulatory body is responsible for accrediting academic programmes in Nigerian universities, including OAU?",
      ["The National Universities Commission (NUC)", "The Joint Admissions and Matriculation Board (JAMB)", "The West African Examinations Council (WAEC)", "The Federal Ministry of Education alone, with no separate agency"], "The National Universities Commission (NUC)",
      "The NUC is the regulatory body responsible for approving and accrediting academic programmes offered by Nigerian universities, ensuring they meet minimum quality standards."),
  _gq("Which of the following best describes the primary role of a Vice-Chancellor in a Nigerian university, such as OAU?",
      ["Serving as the chief executive and academic head of the university", "Serving as the elected student union president", "Managing only the university's sports facilities", "Serving as an external auditor of the university's accounts"], "Serving as the chief executive and academic head of the university",
      "A Vice-Chancellor is the chief executive and principal academic officer of a Nigerian university, responsible for its overall administration and academic direction."),
  _gq("Which arm of government in Nigeria is primarily responsible for interpreting laws and administering justice?",
      ["The Judiciary", "The Legislature", "The Executive", "The Civil Service"], "The Judiciary",
      "The Judiciary is the arm of government responsible for interpreting laws and adjudicating disputes, distinct from the law-making Legislature and law-enforcing Executive."),
  _gq("Which of the following countries shares a land border with Nigeria?",
      ["Cameroon", "Ghana", "South Africa", "Kenya"], "Cameroon",
      "Nigeria shares land borders with Niger, Chad, Cameroon, and Benin Republic; Ghana, South Africa, and Kenya are not bordering countries."),
  _gq("What is the largest desert in the world?",
      ["Sahara Desert", "Gobi Desert", "Kalahari Desert", "Sonoran Desert"], "Sahara Desert",
      "The Sahara Desert, spanning much of North Africa, is the largest hot desert in the world."),
  _gq("Which of the following best describes the primary function of the Independent National Electoral Commission (INEC)?",
      ["Organising and supervising elections in Nigeria", "Regulating the Nigerian banking sector", "Enforcing traffic laws nationwide", "Managing Nigeria's foreign embassies"], "Organising and supervising elections in Nigeria",
      "INEC is Nigeria's independent body responsible for organising, conducting, and supervising elections at the federal and state levels."),
  _gq("Which cash crop has historically been a major export associated with Yoruba land, including areas around Osun State?",
      ["Cocoa", "Coffee", "Tea", "Wool"], "Cocoa",
      "Cocoa has historically been one of the most significant cash crops cultivated in south-western Nigeria, including areas around Osun State."),
  _gq("What is the chemical symbol for oxygen?",
      ["O", "Ox", "O2", "Og"], "O",
      "Oxygen's chemical symbol is simply 'O' on the periodic table."),
  _gq("Which planet is known as the 'Red Planet'?",
      ["Mars", "Venus", "Jupiter", "Saturn"], "Mars",
      "Mars is known as the 'Red Planet' due to iron oxide (rust) on its surface, giving it a reddish appearance."),
  _gq("Which of the following is Nigeria's national football team commonly nicknamed?",
      ["The Super Eagles", "The Black Stars", "The Indomitable Lions", "The Elephants"], "The Super Eagles",
      "Nigeria's senior men's national football team is popularly known as the Super Eagles, distinct from Ghana's Black Stars and Cameroon's Indomitable Lions."),
  _gq("Which international body is primarily responsible for setting global standards and rules for international trade?",
      ["The World Trade Organization (WTO)", "The United Nations (UN)", "The World Health Organization (WHO)", "The International Monetary Fund (IMF)"], "The World Trade Organization (WTO)",
      "The WTO is the international organisation specifically responsible for establishing and enforcing global rules governing trade between nations."),
  _gq("What is the term for a system of government headed by a king or queen whose powers are limited by a constitution?",
      ["Constitutional monarchy", "Absolute monarchy", "Republic", "Theocracy"], "Constitutional monarchy",
      "A constitutional monarchy is a system in which a monarch serves as head of state, but their powers are limited and defined by a constitution, unlike an absolute monarchy."),
  _gq("Which of the following is an example of a non-communicable disease?",
      ["Diabetes", "Tuberculosis", "Malaria", "Cholera"], "Diabetes",
      "Diabetes is a non-communicable disease, unlike tuberculosis, malaria, and cholera, which are infectious (communicable) diseases."),
  _gq("What is the largest country in the world by land area?",
      ["Russia", "Canada", "China", "United States"], "Russia",
      "Russia is the largest country in the world by land area, spanning parts of both Europe and Asia."),
  _gq("Who is generally credited with leading the Sokoto Jihad in the early 19th century, later founding the Sokoto Caliphate?",
      ["Uthman Dan Fodio", "Ahmadu Bello", "Usman Aliyu", "Muhammadu Bello"], "Uthman Dan Fodio",
      "Uthman Dan Fodio led the Sokoto Jihad in the early 19th century, a religious and political reform movement that resulted in the founding of the Sokoto Caliphate."),
  _gq("Which of the following best describes the primary role of the legislative arm of government?",
      ["Making laws for the country", "Implementing and enforcing laws", "Interpreting the constitution exclusively", "Auditing government accounts exclusively"], "Making laws for the country",
      "The legislative arm, such as Nigeria's National Assembly, is primarily responsible for making laws, distinct from the executive that enforces them."),
  _gq("Which vitamin deficiency is most commonly associated with the disease rickets?",
      ["Vitamin D", "Vitamin C", "Vitamin A", "Vitamin B12"], "Vitamin D",
      "Rickets is a disease affecting bone development in children, most commonly caused by a deficiency of Vitamin D."),
  _gq("What is the term for the total value of all goods and services produced within a country's borders in a given period?",
      ["Gross Domestic Product (GDP)", "Gross National Product (GNP)", "Net National Income", "Balance of Trade"], "Gross Domestic Product (GDP)",
      "GDP specifically measures the value of goods and services produced within a country's borders, regardless of the nationality of the producers."),
  _gq("Which Nigerian playwright and author was the first African to win the Nobel Prize in Literature?",
      ["Wole Soyinka", "Chinua Achebe", "Chimamanda Ngozi Adichie", "Cyprian Ekwensi"], "Wole Soyinka",
      "Wole Soyinka won the Nobel Prize in Literature in 1986, becoming the first African laureate in that category."),
  _gq("What does the abbreviation 'NAFDAC' stand for in the Nigerian context?",
      ["National Agency for Food and Drug Administration and Control", "National Association for Drug and Chemical Control", "Nigerian Agency for Food and Drug Coordination", "National Authority for Food, Drugs, and Cosmetics"], "National Agency for Food and Drug Administration and Control",
      "NAFDAC regulates and controls the manufacture, importation, and sale of food, drugs, and related products in Nigeria."),
  _gq("What is the term for a persistent, sustained rise in the general price level of goods and services in an economy?",
      ["Inflation", "Deflation", "Recession", "Depreciation"], "Inflation",
      "Inflation describes an ongoing, generalised increase in prices across an economy, reducing the purchasing power of money."),
  _gq("Which of the following best describes the primary aim of the African Continental Free Trade Area (AfCFTA)?",
      ["Creating a single market for goods and services across African countries to boost intra-African trade", "Restricting all trade between African nations", "Regulating global internet governance", "Coordinating African military alliances exclusively"], "Creating a single market for goods and services across African countries to boost intra-African trade",
      "AfCFTA aims to create a single continental market for goods and services, boosting intra-African trade by reducing tariffs and other trade barriers among member states."),
  _gq("Which of the following is a key function of the Central Bank of Nigeria (CBN) relating to currency?",
      ["Issuing and regulating the country's currency (the Naira)", "Setting the retail price of consumer goods", "Managing Nigeria's road transport infrastructure", "Running the national postal service"], "Issuing and regulating the country's currency (the Naira)",
      "One of the CBN's core functions is the sole authority to issue and regulate Nigeria's legal tender currency, the Naira."),
  _gq("Which of the following best describes the primary purpose of the World Health Organization (WHO)?",
      ["Coordinating international public health efforts and setting health standards", "Regulating international trade tariffs", "Coordinating global monetary policy", "Managing international postal services"], "Coordinating international public health efforts and setting health standards",
      "WHO is a specialised United Nations agency focused on international public health, coordinating responses to health emergencies and setting global health standards."),
  _gq("Which of the following is the largest producer of crude oil in Africa, based on long-established historical ranking?",
      ["Nigeria", "Ghana", "Kenya", "Egypt"], "Nigeria",
      "Nigeria has long been recognised as one of Africa's leading crude oil producers, historically ranking as the continent's largest producer for extended periods."),
  _gq("What is the term for the practice of a country restricting imports through tariffs or quotas to protect domestic industries?",
      ["Protectionism", "Free trade", "Globalisation", "Liberalisation"], "Protectionism",
      "Protectionism refers to government policies that restrict international trade, such as tariffs and quotas, to shield domestic industries from foreign competition."),
  _gq("Which Yoruba deity (Orisa) is traditionally associated with the Osun River and the Osun-Osogbo festival?",
      ["Osun", "Sango", "Ogun", "Obatala"], "Osun",
      "The river goddess Osun is the deity traditionally celebrated at the annual Osun-Osogbo festival held at the sacred grove."),
  _gq("What is the term for the legal document that formally establishes the rules and structure of governance for a country?",
      ["Constitution", "Manifesto", "Communique", "Gazette"], "Constitution",
      "A constitution is the fundamental legal document that establishes the framework, powers, and limits of a country's system of governance."),
];
