import "../quiz_question.dart";

const _subject = "History";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// Obafemi Awolowo University (OAU) Post-UTME History practice bank — 100
/// medium-to-hard questions spanning the Nigeria Area up to 1800, Nigeria
/// Since 1800, British Colonialism & Resistance, Nationalism and
/// Independence, Post-Independence Nigeria, African History, and World
/// History themes. This is a general practice set aligned to the typical
/// JAMB/Post-UTME History syllabus, not an official OAU past-question paper.
List<QuizQuestion> buildOauHistoryQuestions() {
  return [
    ..._nigeriaUpTo1800,
    ..._nigeriaSince1800,
    ..._britishColonialismAndResistance,
    ..._nationalismAndIndependence,
    ..._postIndependenceNigeria,
    ..._africanHistory,
    ..._worldHistory,
  ];
}

final _nigeriaUpTo1800 = [
  _q("The theory that the Yoruba originated from a migration led by Oduduwa from the east is commonly known as the",
      ["Oduduwa migration theory of Yoruba origin", "autochthonous (indigenous) theory of Yoruba origin", "Bayajidda legend", "Hamitic hypothesis"], "Oduduwa migration theory of Yoruba origin",
      "One major tradition of Yoruba origin holds that Oduduwa led a migration from the east and settled at Ile-Ife, from where his descendants founded the various Yoruba kingdoms."),
  _q("The Bayajidda legend is a foundation myth most closely associated with the origin of the",
      ["Hausa states", "Yoruba kingdoms", "Benin Kingdom", "Kanem-Bornu Empire"], "Hausa states",
      "The Bayajidda legend, involving a heroic stranger who slays a snake in a well at Daura, is the traditional account explaining the founding of the seven true Hausa states (Hausa Bakwai)."),
  _q("In traditional Benin political history, the transition from the Ogiso dynasty to the Oba dynasty is closely linked to the invitation extended to a prince from",
      ["Ile-Ife", "Old Oyo", "Kano", "Sokoto"], "Ile-Ife",
      "Benin oral tradition holds that after the Ogiso dynasty ended, Benin chiefs invited a prince (Oranmiyan) from Ile-Ife, whose son Eweka I became the first Oba, beginning the present dynasty."),
  _q("Which of these describes the general system of land tenure practised in most pre-colonial Nigerian societies before 1800?",
      ["Land was generally held communally by families, lineages, or the community, rather than owned by individuals", "Land was bought and sold freely on an open individual market", "All land belonged exclusively to foreign trading companies", "Land ownership was determined solely by written colonial title deeds"], "Land was generally held communally by families, lineages, or the community, rather than owned by individuals",
      "Across most pre-colonial Nigerian societies, land was typically held in trust by families, lineages, or communities under customary law, rather than being individually owned property."),
  _q("The nine-mile-long defensive earthwork known as the Sungbo's Eredo is associated with which pre-colonial Nigerian kingdom?",
      ["The Ijebu Kingdom", "The Benin Kingdom", "The Kano Emirate", "The Kwararafa Kingdom"], "The Ijebu Kingdom",
      "Sungbo's Eredo is a massive system of walls and ditches associated with the Ijebu Kingdom, believed to have been constructed for defensive and boundary purposes."),
  _q("The extensive system of earthworks and moats surrounding Benin City, among the largest man-made structures in pre-colonial Africa, primarily served the purpose of",
      ["defending the kingdom and demarcating its boundaries", "storing surplus agricultural produce", "channelling water for large-scale irrigation farming", "housing the kingdom's bronze-casting guilds"], "defending the kingdom and demarcating its boundaries",
      "The Benin Walls and moats were built over centuries chiefly for defence against invasion and to mark out the boundaries of the expanding kingdom and its subordinate settlements."),
  _q("Among the Igbo, the title-taking system such as Ozo was significant mainly because it",
      ["conferred status and authority on individuals based on achievement rather than inherited kingship", "was reserved exclusively for hereditary monarchs", "was introduced by British colonial administrators", "replaced all forms of village council government"], "conferred status and authority on individuals based on achievement rather than inherited kingship",
      "In the largely decentralised Igbo political system, title systems like Ozo allowed individuals to earn social prestige and influence through personal achievement, wealth, and initiation, rather than through inherited kingship."),
  _q("The Nupe Kingdom, located in the Niger-Benue confluence area, was historically ruled by a monarch bearing the title of",
      ["Etsu Nupe", "Attah of Igala", "Obi of Onitsha", "Amanyanabo"], "Etsu Nupe",
      "The Nupe Kingdom's traditional ruler held the title Etsu Nupe, governing from centres such as Bida in the pre-colonial and later emirate period."),
  _q("In the pre-1800 Niger Delta city-states, the office of the 'Amanyanabo' referred to the",
      ["head or king of a Delta trading state such as Bonny or Kalabari", "senior priest responsible for oracle consultations", "leader of a Benin-appointed provincial administration", "commander of an Oyo cavalry regiment"], "head or king of a Delta trading state such as Bonny or Kalabari",
      "'Amanyanabo', meaning 'owner of the land', was the title used for the ruling head of several Niger Delta city-states engaged in coastal and overseas trade."),
  _q("A key economic factor that encouraged the rise of centralised states such as Old Oyo and Benin in the forest belt was",
      ["control of long-distance trade routes linking the coast, the forest, and the savanna", "the total absence of any trade with neighbouring peoples", "reliance on a single crop with no trading surplus", "an economy based purely on nomadic pastoralism"], "control of long-distance trade routes linking the coast, the forest, and the savanna",
      "States like Old Oyo and Benin grew powerful partly by controlling and taxing trade routes connecting northern savanna markets, forest producers, and the Atlantic coast."),
  _q("Islam was introduced into Hausaland mainly through the influence of",
      ["Wangarawa (Mande-speaking) traders and clerics from the western Sudan", "direct British colonial missionary activity", "Portuguese explorers along the coast", "the trans-Atlantic slave trade"], "Wangarawa (Mande-speaking) traders and clerics from the western Sudan",
      "Islam spread into Hausaland from around the 14th century largely through Wangarawa traders and Muslim clerics travelling from the western Sudanic empires, well before any European contact."),
  _q("Before the 19th-century Jihad, Hausa society was already marked by a degree of religious tension mainly between",
      ["Islamic practice among the ruling and merchant classes and persistent traditional (Maguzawa) religious practices among much of the peasantry", "Roman Catholic and Protestant Christian communities", "Sunni and Shia populations of equal size", "Buddhist and Hindu trading communities"], "Islamic practice among the ruling and merchant classes and persistent traditional (Maguzawa) religious practices among much of the peasantry",
      "Although Islam had taken root among Hausa rulers and traders, many rural Hausa (the Maguzawa) retained traditional religious practices, a tension Uthman Dan Fodio later cited as justification for reform."),
  _q("The trans-Saharan trade that flourished across the Nigeria area before 1800 principally exchanged North African goods such as salt and cloth for southern products including",
      ["gold, kola nuts, leather, and slaves", "cocoa and rubber", "crude oil and timber", "maize and cassava"], "gold, kola nuts, leather, and slaves",
      "Trans-Saharan caravans typically carried salt, cloth, and horses southward, returning north with gold, kola nuts, leather goods, and enslaved people obtained from the savanna and forest zones."),
  _q("Which of the following best explains why many Igbo communities in the pre-1800 period lacked centralised kingship, unlike Benin or Oyo?",
      ["Their political system emphasised village democracy through councils of elders, age grades, and title societies", "They had no contact whatsoever with neighbouring centralised states", "British colonial policy had already abolished Igbo kingship by that period", "They were entirely nomadic and therefore could not sustain fixed institutions"], "Their political system emphasised village democracy through councils of elders, age grades, and title societies",
      "Most pre-colonial Igbo communities practised a form of village-based, republican governance relying on councils of elders, age grades, and title societies rather than a single centralised monarch."),
];

final _nigeriaSince1800 = [
  _q("Uthman Dan Fodio's Jihad formally began in 1804 at",
      ["Gudu, where he made the hijra (withdrawal) and was declared Amir al-Mu'minin", "Sokoto, already established as the caliphate's capital", "Kano, the largest Hausa city", "Ilorin, a Yoruba frontier town"], "Gudu, where he made the hijra (withdrawal) and was declared Amir al-Mu'minin",
      "In 1804, Dan Fodio withdrew (hijra) to Gudu with his followers, where he was proclaimed Amir al-Mu'minin (Commander of the Faithful), marking the formal start of the Jihad."),
  _q("Within the Sokoto Caliphate's administrative structure, overall spiritual and political leadership was vested in the",
      ["Sultan of Sokoto", "Shehu of Bornu", "Alaafin of Oyo", "Emir of Zaria alone, independent of Sokoto"], "Sultan of Sokoto",
      "The Sultan of Sokoto stood at the apex of the Caliphate, exercising ultimate spiritual and political authority over the various emirates, which retained a degree of local autonomy under their Emirs."),
  _q("Muhammed Bello, a key successor to Uthman Dan Fodio, is particularly remembered for",
      ["consolidating and administering the Sokoto Caliphate after the Jihad, and founding Sokoto as its capital", "leading the original 1804 Jihad from its start", "founding the city-state of Ibadan", "signing the earliest treaty with British colonial officials"], "consolidating and administering the Sokoto Caliphate after the Jihad, and founding Sokoto as its capital",
      "Muhammed Bello, Dan Fodio's son, succeeded him as Caliph, founded Sokoto as the new capital, and played a central role in consolidating and administering the vast Caliphate."),
  _q("Unlike Hausaland, the Kanem-Bornu Empire successfully resisted absorption into the Sokoto Caliphate largely due to the leadership of",
      ["Muhammad al-Kanemi, who reorganised Bornu's defences and religious authority", "Uthman Dan Fodio himself, who chose to spare Bornu", "the Alaafin of Oyo, who allied with Bornu against Sokoto", "British colonial forces who intervened to protect Bornu"], "Muhammad al-Kanemi, who reorganised Bornu's defences and religious authority",
      "Muhammad al-Kanemi rallied Bornu's forces and religious scholarship to repel Fulani Jihadist advances, preserving Bornu's independence and eventually founding a new ruling dynasty there."),
  _q("The Fulani Jihadists' establishment of the Ilorin Emirate in Yorubaland is closely linked to the actions of",
      ["Afonja, the Are-Ona-Kakanfo, who invited Fulani support against the Alaafin", "Muhammed Bello, acting entirely without local Yoruba involvement", "the Oyomesi council, seeking to strengthen the Alaafin's authority", "British colonial officers seeking a buffer state"], "Afonja, the Are-Ona-Kakanfo, who invited Fulani support against the Alaafin",
      "Afonja, the Oyo military commander at Ilorin, rebelled against the Alaafin and enlisted Fulani and Hausa support; this alliance eventually resulted in Ilorin becoming a Fulani-ruled emirate."),
  _q("The founding of Ibadan as a major 19th-century Yoruba power is best explained by its origins as a",
      ["war camp that grew into a powerful city-state through military success in the Yoruba civil wars", "trading post established directly by European merchants", "colonial administrative headquarters created by the British", "religious centre founded by Fulani clerics"], "war camp that grew into a powerful city-state through military success in the Yoruba civil wars",
      "Ibadan began as a war camp of refugees and warriors from various Yoruba towns and rose to prominence through military strength during the chaotic period of the Yoruba civil wars."),
  _q("The Kiriji War (Ekiti-Parapo War) of the late 19th century was fought mainly between",
      ["Ibadan and an alliance of Ekiti, Ijesa, and other Yoruba groups", "the Sokoto Caliphate and Bornu", "Benin and the Itsekiri", "British forces and the Ijebu"], "Ibadan and an alliance of Ekiti, Ijesa, and other Yoruba groups",
      "The prolonged Kiriji War pitted Ibadan against the Ekitiparapo alliance (Ekiti, Ijesa, and others), representing one of the longest and most destructive conflicts of the Yoruba civil war era."),
  _q("The Kiriji War was eventually brought to an end largely through",
      ["British mediation, which led to a peace treaty in 1886", "Ibadan's total military conquest of all opposing forces", "direct intervention by the Sokoto Caliphate", "a decision of the Oyomesi council of Old Oyo"], "British mediation, which led to a peace treaty in 1886",
      "British officials, keen to secure stability for trade, mediated between the warring Yoruba factions, contributing to the peace agreement that ended the Kiriji War in 1886."),
  _q("Following the collapse of Old Oyo, the Alaafin's court and remaining Oyo authority relocated southward and was eventually re-established at",
      ["New Oyo (Ago-Oja)", "Ibadan", "Ijebu-Ode", "Abeokuta"], "New Oyo (Ago-Oja)",
      "After the destruction of the old capital, the Oyo court moved and was eventually resettled at Ago-Oja, which became known as New Oyo, though with much reduced power compared to the old empire."),
  _q("The founding of Abeokuta in the 1830s is best explained as a",
      ["refuge settlement created by Egba groups displaced by the Yoruba civil wars", "colonial town created directly by British administrators", "new capital deliberately established by the Sokoto Caliphate", "trading post founded solely by Portuguese merchants"], "refuge settlement created by Egba groups displaced by the Yoruba civil wars",
      "Abeokuta was founded as a fortified refuge ('under the rock') by Egba communities fleeing the instability and warfare that followed the collapse of Old Oyo."),
  _q("The 19th-century Nupe Kingdom came under Fulani rule largely as a result of",
      ["a Jihadist takeover led by Mallam Dendo and his successors", "direct British colonial conquest", "a peaceful dynastic marriage alliance", "the intervention of the Alaafin of Oyo"], "a Jihadist takeover led by Mallam Dendo and his successors",
      "Mallam Dendo, a Fulani cleric, exploited a succession dispute in the Nupe Kingdom to establish Fulani political dominance, eventually founding a new emirate dynasty at Bida."),
  _q("A major long-term political consequence of the 19th-century upheavals (the Sokoto Jihad and the Yoruba civil wars) was that",
      ["Nigeria's pre-colonial political landscape was significantly reshaped just before the onset of British colonial rule", "the region achieved complete and lasting political unity", "the trans-Atlantic slave trade was permanently ended within the region", "European contact with the interior ceased entirely"], "Nigeria's pre-colonial political landscape was significantly reshaped just before the onset of British colonial rule",
      "The dramatic 19th-century transformations — the rise of the Sokoto Caliphate and the fragmentation of Yorubaland — reshaped the political map of the Nigeria area on the very eve of British colonisation."),
  _q("The 19th-century Jihad and subsequent wars in the Nigeria area contributed to an increase in the internal (domestic) slave trade mainly because",
      ["large numbers of war captives were enslaved and put to use within African societies, including on plantations", "slavery had been completely unknown before this period", "the British actively encouraged internal enslavement during this period", "all captives were immediately freed under Islamic law"], "large numbers of war captives were enslaved and put to use within African societies, including on plantations",
      "The extensive warfare of the Jihad and the Yoruba civil wars generated large numbers of captives, many of whom were enslaved and used domestically, including on the plantations that emerged around this period."),
  _q("Which of the following Yoruba towns is most closely associated with serving as a key middleman trading centre between the interior and European traders on the coast during the 19th century?",
      ["Ijebu-Ode", "Sokoto", "Kano", "Bornu"], "Ijebu-Ode",
      "Ijebu-Ode occupied a strategic position between the Yoruba interior and the coast, and the Ijebu long controlled and profited from trade passing through their territory to European merchants."),
];

final _britishColonialismAndResistance = [
  _q("Lagos was formally annexed by the British in",
      ["1861", "1914", "1900", "1885"], "1861",
      "Lagos was annexed as a British colony in 1861, decades before the wider amalgamation of Nigeria, largely to suppress the slave trade and secure British commercial interests."),
  _q("The Royal Niger Company, chartered in 1886, was primarily significant for",
      ["administering and controlling trade in the Niger area under a British royal charter before direct colonial rule was established", "granting Nigeria's independence", "organising the Berlin Conference", "leading the Sokoto Jihad"], "administering and controlling trade in the Niger area under a British royal charter before direct colonial rule was established",
      "Under Sir George Goldie, the Royal Niger Company held a royal charter to trade and administer territory along the Niger, effectively laying groundwork for later formal British colonial control."),
  _q("The British Protectorate of Southern Nigeria and the Protectorate of Northern Nigeria were formally proclaimed in",
      ["1900", "1861", "1914", "1922"], "1900",
      "In 1900, the British Crown took over administration from the Royal Niger Company, formally establishing the Protectorates of Northern and Southern Nigeria ahead of the 1914 amalgamation."),
  _q("The British conquest of the Sokoto Caliphate was effectively completed with the fall of the city of",
      ["Sokoto itself in 1903", "Kano in 1914", "Ilorin in 1897", "Zaria in 1908"], "Sokoto itself in 1903",
      "British forces under Frederick Lugard captured Sokoto in 1903, marking the effective end of the Caliphate's independent political and military authority."),
  _q("The British conquest of the Benin Kingdom in 1897 was triggered directly by",
      ["the killing of members of a British trade delegation, prompting a punitive expedition", "a formal declaration of war by the Oba against Britain", "an uprising among Benin's own chiefs against the Oba", "a boundary dispute between Benin and Lagos"], "the killing of members of a British trade delegation, prompting a punitive expedition",
      "After a British-led delegation was attacked and several members killed near Benin, Britain launched a large punitive expedition in 1897 that captured and looted Benin City."),
  _q("A major consequence of the 1897 Punitive Expedition against Benin was",
      ["the exile of Oba Ovonramwen and the seizure of thousands of Benin artworks, including the Benin Bronzes", "the immediate granting of self-rule to Benin", "the peaceful integration of Benin as an equal partner in colonial government", "the establishment of Benin as the colonial capital of Southern Nigeria"], "the exile of Oba Ovonramwen and the seizure of thousands of Benin artworks, including the Benin Bronzes",
      "Following the expedition, Oba Ovonramwen was deposed and exiled, and British forces looted a vast quantity of Benin's royal art, much of which remains in foreign museums today."),
  _q("Indirect Rule faced its greatest practical difficulty in Eastern Nigeria mainly because",
      ["many Igbo communities lacked the centralised, hereditary chieftaincy structures the system assumed", "the Igbo had no contact whatsoever with the colonial government", "Eastern Nigeria had already gained self-government before 1900", "the region had no economic resources of interest to Britain"], "many Igbo communities lacked the centralised, hereditary chieftaincy structures the system assumed",
      "Because Indirect Rule was modelled on the emirate system, its imposition on the largely decentralised Igbo areas required artificial 'warrant chiefs', which lacked genuine traditional legitimacy."),
  _q("Colonial 'pacification' campaigns in the Nigeria area referred to",
      ["military expeditions used by the British to subdue resistant communities and extend colonial control", "peaceful diplomatic negotiations that avoided all use of force", "programmes to end domestic conflicts between rival Nigerian ethnic groups after independence", "campaigns run by missionaries with no military involvement"], "military expeditions used by the British to subdue resistant communities and extend colonial control",
      "'Pacification' was the term colonial authorities used for military campaigns aimed at forcibly subduing resistant communities and consolidating British administrative control over new territories."),
  _q("The Anglo-Aro War (1901-1902) was fought by the British mainly to break the power of",
      ["the Aro Confederacy and its Long Juju oracle network in the Igbo hinterland", "the Sokoto Caliphate", "the Benin Kingdom", "the Ijebu Kingdom"], "the Aro Confederacy and its Long Juju oracle network in the Igbo hinterland",
      "The Aro Confederacy exercised extensive religious and commercial influence, notably through the Ibinukpabi (Long Juju) oracle; the British campaign aimed to dismantle this network and extend colonial control."),
  _q("The British defeat of the Ijebu Kingdom in 1892 was significant chiefly because it",
      ["opened up the Yoruba interior to more direct British commercial and political penetration", "marked the final British military campaign in Nigeria", "led immediately to full Nigerian independence", "occurred without any resistance from Ijebu forces"], "opened up the Yoruba interior to more direct British commercial and political penetration",
      "The Ijebu had long acted as middlemen restricting British access to the interior; their defeat in 1892 removed this barrier and accelerated British commercial and political expansion into Yorubaland."),
  _q("The Nana Olomu of Itsekiri resistance against British commercial encroachment in the late 19th century was fundamentally a dispute over",
      ["control of the palm oil trade and middleman trading privileges in the Niger Delta", "religious differences between Christianity and traditional beliefs", "control of the Sokoto Caliphate's northern trade routes", "the right to appoint the Oba of Benin"], "control of the palm oil trade and middleman trading privileges in the Niger Delta",
      "Nana Olomu, a powerful Itsekiri trading chief, resisted British efforts to bypass African middlemen and trade directly in the interior, particularly over lucrative palm oil trade."),
  _q("King Jaja of Opobo's resistance to British trading interests in the 1880s ultimately resulted in his",
      ["arrest and exile by the British", "formal recognition as a British colonial governor", "successful expulsion of all British traders from the Niger Delta", "alliance with the Sokoto Caliphate against Britain"], "arrest and exile by the British",
      "King Jaja of Opobo, who sought to control his own trade with Europe rather than accept British middlemen restrictions, was lured aboard a British ship, arrested, and exiled to the West Indies."),
  _q("Colonial direct taxation, a recurring trigger of resistance movements such as the Adubi War and the Aba Women's Riot, was resented largely because it",
      ["was seen as an unprecedented imposition that undermined existing customary obligations and economic autonomy", "was welcomed unanimously by all Nigerian communities", "had already existed in identical form under pre-colonial rulers", "applied exclusively to European residents in Nigeria"], "was seen as an unprecedented imposition that undermined existing customary obligations and economic autonomy",
      "In many areas, direct colonial taxation represented a novel and unwelcome imposition that clashed with existing customary economic arrangements, generating widespread resentment and, at times, open resistance."),
  _q("The colonial policy of using warrant chiefs in Igboland is best described as an attempt to",
      ["create artificial local authorities where none of the required kind previously existed, to serve Indirect Rule", "restore the exact powers of pre-existing Igbo kings", "abolish all forms of local government entirely", "replace Islamic emirate rulers in the North"], "create artificial local authorities where none of the required kind previously existed, to serve Indirect Rule",
      "Since Indirect Rule required identifiable local rulers, the British appointed warrant chiefs in many Igbo communities that traditionally had no single hereditary ruler, often provoking resentment due to their lack of legitimacy."),
  _q("Which of the following best captures the overall economic relationship established between colonial Nigeria and Britain?",
      ["Nigeria mainly supplied raw materials and cash crops while importing British manufactured goods", "Nigeria and Britain traded as economic equals with balanced industrial exchange", "Britain provided Nigeria with the majority of its food imports", "Nigeria's economy was entirely self-contained and had no trade links with Britain"], "Nigeria mainly supplied raw materials and cash crops while importing British manufactured goods",
      "Colonial economic policy structured Nigeria's economy around the export of raw materials and cash crops to Britain, in exchange for imported British manufactured goods, a classic colonial trade pattern."),
];

final _nationalismAndIndependence = [
  _q("The West African Students' Union (WASU), founded in London in 1925, played an important role in Nigerian nationalism mainly by",
      ["fostering pan-African political consciousness among Nigerian and other West African students studying abroad", "organising Nigeria's first general election", "negotiating the Berlin Conference agreements", "administering the Sokoto Caliphate"], "fostering pan-African political consciousness among Nigerian and other West African students studying abroad",
      "WASU brought together West African students in Britain, exposing many future Nigerian nationalist leaders to pan-African ideas and political organisation that shaped later independence movements."),
  _q("The Nigerian Youth Movement (NYM), formed in the 1930s, is significant as one of the first Nigerian nationalist organisations to",
      ["attract broad-based, cross-regional membership demanding greater Nigerian self-government", "restrict its membership exclusively to Northern Nigeria", "openly reject any form of Nigerian self-government", "be founded directly by the British colonial government"], "attract broad-based, cross-regional membership demanding greater Nigerian self-government",
      "The NYM drew members from various regions and backgrounds, marking an important step toward broader nationalist mobilisation beyond earlier, more localised political associations."),
  _q("Obafemi Awolowo's early political career included founding the pan-Yoruba cultural and political organisation known as",
      ["Egbe Omo Oduduwa", "the Sokoto Council", "the Nigerian Youth Movement", "the Northern People's Congress"], "Egbe Omo Oduduwa",
      "Awolowo founded Egbe Omo Oduduwa in 1948 as a pan-Yoruba cultural organisation, which later provided much of the political base for the Action Group."),
  _q("The Northern Elements Progressive Union (NEPU), led by figures such as Aminu Kano, distinguished itself from the NPC mainly by",
      ["advocating radical social reform and challenging the traditional emirate ruling establishment in the North", "supporting the continuation of British colonial rule indefinitely", "restricting its activities to Southern Nigeria", "opposing any form of Nigerian independence"], "advocating radical social reform and challenging the traditional emirate ruling establishment in the North",
      "NEPU, associated with Aminu Kano, took a more radical, reformist stance than the NPC, criticising the conservative emirate establishment and calling for greater social and political change in the North."),
  _q("The 1953 Kano Riots were significantly triggered by",
      ["political and ethnic tensions arising from a heated debate over the timing of Nigerian self-government", "a dispute over colonial taxation policy", "the outcome of Nigeria's independence referendum", "disagreements over the location of Nigeria's new capital"], "political and ethnic tensions arising from a heated debate over the timing of Nigerian self-government",
      "The 1953 Kano riots followed sharp regional and ethnic tensions after Southern-based politicians pushed for an early date for Nigerian self-government, a proposal Northern leaders resisted."),
  _q("The 1957 and 1958 Constitutional Conferences held in London were mainly concerned with",
      ["resolving outstanding constitutional issues, including minority concerns, ahead of Nigerian independence", "declaring Nigeria's independence immediately", "abolishing the regional system of government", "establishing the Nigerian Civil War peace terms"], "resolving outstanding constitutional issues, including minority concerns, ahead of Nigerian independence",
      "These London conferences addressed key unresolved issues, including the fears of ethnic minorities within the regions, as part of the process of finalising arrangements for Nigerian independence."),
  _q("The Willink Commission of 1957-1958 was established mainly to investigate",
      ["the fears of ethnic minorities and consider possible safeguards, including the question of separate states", "the causes of the Nigerian Civil War", "the terms of the Berlin Conference", "the effectiveness of Indirect Rule in Northern Nigeria"], "the fears of ethnic minorities and consider possible safeguards, including the question of separate states",
      "The Willink Commission was set up by the British government to examine the concerns of minority ethnic groups within Nigeria's three regions and recommend safeguards ahead of independence."),
  _q("At the 1960 independence, Nnamdi Azikiwe assumed the position of",
      ["Governor-General, and later the first President when Nigeria became a republic in 1963", "first Prime Minister of Nigeria", "Premier of the Northern Region", "Premier of the Western Region"], "Governor-General, and later the first President when Nigeria became a republic in 1963",
      "Azikiwe became Nigeria's first indigenous Governor-General at independence in 1960, and subsequently the first President when Nigeria adopted a republican constitution in 1963."),
  _q("Abubakar Tafawa Balewa's role at the time of Nigeria's 1960 independence was that of",
      ["Prime Minister, heading the federal government", "Governor-General", "Premier of the Eastern Region", "President of the Senate"], "Prime Minister, heading the federal government",
      "Tafawa Balewa served as Nigeria's first Prime Minister, leading the federal government under the parliamentary system established at independence in 1960."),
  _q("A key demand shared broadly by Nigerian nationalist movements across regions in the years before independence was",
      ["an accelerated timetable for full self-government and eventual independence from British rule", "the permanent retention of British colonial administration", "abolition of the regional system rather than any form of self-rule", "closer political union with other British West African colonies as a single country"], "an accelerated timetable for full self-government and eventual independence from British rule",
      "Despite regional and ideological differences, Nigerian nationalist parties broadly agreed on pressing for a faster path to self-government and full independence from Britain."),
  _q("The 1959 Federal Election, held ahead of independence, is significant mainly because it",
      ["determined which coalition of parties would form Nigeria's first independent government", "was Nigeria's first ever election of any kind", "led directly to Nigeria becoming a republic", "was cancelled due to widespread unrest"], "determined which coalition of parties would form Nigeria's first independent government",
      "The 1959 federal election results led to a coalition government between the NPC and NCNC, which formed Nigeria's government at the point of independence in October 1960."),
  _q("Compared to the NCNC and Action Group, the Northern People's Congress (NPC) in the pre-independence period is generally described as",
      ["more cautious about rapid self-government, prioritising Northern regional interests and gradual change", "the most radical party demanding immediate independence", "a party founded and led primarily by Southern politicians", "opposed in principle to any Nigerian self-government"], "more cautious about rapid self-government, prioritising Northern regional interests and gradual change",
      "The NPC, closely tied to the Northern emirate establishment, generally favoured a more gradual approach to self-government, wary that rapid change might disadvantage the North relative to the more educationally advanced South."),
  _q("The transformation of Nigeria's colonial constitutional structure from unitary control toward federalism was primarily driven by",
      ["the need to accommodate Nigeria's ethnic, regional, and cultural diversity", "a direct instruction from the League of Nations", "the outcome of the Nigerian Civil War", "pressure from other independent African states"], "the need to accommodate Nigeria's ethnic, regional, and cultural diversity",
      "Nigeria's shift toward a federal structure, beginning with the Richards Constitution, reflected the practical need to manage the country's considerable ethnic, cultural, and regional diversity."),
  _q("The role of the press, such as Azikiwe's West African Pilot, in the Nigerian independence movement was mainly to",
      ["mobilise public opinion and criticise colonial policies in support of nationalist goals", "serve as an official mouthpiece of the colonial government", "focus exclusively on sports and entertainment news", "avoid any discussion of political matters"], "mobilise public opinion and criticise colonial policies in support of nationalist goals",
      "Nationalist-owned newspapers such as the West African Pilot played an active role in shaping public opinion, criticising colonial policy, and rallying support for self-government."),
  _q("Which of the following best explains the choice of a federal, rather than unitary, system of government for independent Nigeria in 1960?",
      ["It offered a practical means of balancing regional autonomy with national unity across a diverse country", "It was a system copied directly from the government of ancient Songhai", "It eliminated the need for any central government institutions", "It was imposed without consultation by the United Nations"], "It offered a practical means of balancing regional autonomy with national unity across a diverse country",
      "Federalism was adopted as a pragmatic compromise, allowing regions considerable autonomy over local affairs while preserving a unified central government for a country with wide ethnic and regional diversity."),
];

final _postIndependenceNigeria = [
  _q("The controversial national population census of 1962/1963 contributed to post-independence tension mainly because",
      ["its results were disputed and seen as tied to regional political and resource-allocation advantage", "it was Nigeria's first ever census under any government", "it revealed there was no ethnic diversity in Nigeria", "it was conducted entirely by foreign observers with no local input"], "its results were disputed and seen as tied to regional political and resource-allocation advantage",
      "Because population figures affected regional representation and revenue allocation, the disputed 1962/1963 census results heightened regional and political rivalries in the early 1960s."),
  _q("The Western Region crisis of 1962, involving a split within the Action Group, most directly resulted in",
      ["a state of emergency being declared in the Western Region", "the outbreak of the Nigerian Civil War", "the creation of the Mid-Western Region", "Nigeria's first military coup"], "a state of emergency being declared in the Western Region",
      "Political conflict between Awolowo and Akintola factions within the Action Group led to serious unrest in the Western Region, prompting the federal government to declare a state of emergency there in 1962."),
  _q("The Mid-Western Region was created in 1963, becoming Nigeria's",
      ["fourth region, carved mainly out of the former Western Region", "first region created after independence", "only region created through a military decree", "final region before the Civil War, carved from the North"], "fourth region, carved mainly out of the former Western Region",
      "The Mid-Western Region was created in 1963 out of parts of the Western Region, becoming the fourth of Nigeria's regions and addressing some minority demands in the area."),
  _q("The 'Operation Wetie' unrest that followed the disputed Western Region election of 1965 significantly contributed to",
      ["a breakdown of public order that helped precipitate the January 1966 military coup", "the peaceful resolution of Nigeria's regional political disputes", "the immediate return of Nigeria to a unitary system of government", "the end of the Nigerian Civil War"], "a breakdown of public order that helped precipitate the January 1966 military coup",
      "Widespread violence and arson ('Operation Wetie') following the contested 1965 Western Region election deepened the political crisis that set the stage for the military takeover in January 1966."),
  _q("General Yakubu Gowon's decision to create 12 states out of the four regions in 1967 was announced",
      ["shortly before the outbreak of the Nigerian Civil War, partly to undercut support for Biafran secession", "immediately after the end of the Nigerian Civil War", "at the moment of Nigeria's 1960 independence", "during the Second Republic under President Shagari"], "shortly before the outbreak of the Nigerian Civil War, partly to undercut support for Biafran secession",
      "Gowon's 12-state creation in May 1967 was announced just before the Civil War began, aiming partly to weaken support for Eastern Region secession by addressing minority grievances within the region."),
  _q("The Nigerian Civil War is generally understood to have been fuelled in part by economic considerations related to control of",
      ["newly discovered oil reserves located mainly within the Eastern Region", "gold deposits in Northern Nigeria", "cocoa plantations in the West", "salt mines in the Sahara-facing north"], "newly discovered oil reserves located mainly within the Eastern Region",
      "The prospect of substantial oil revenue located largely within Eastern Nigeria was a significant economic factor underlying both the region's confidence in seceding and the federal government's determination to prevent it."),
  _q("General Murtala Mohammed, who came to power in a 1975 coup, is particularly remembered for",
      ["launching a vigorous programme to purge the civil service and prepare a transition to civilian rule", "leading Nigeria into the Civil War", "declaring Nigeria's independence in 1960", "founding the Action Group political party"], "launching a vigorous programme to purge the civil service and prepare a transition to civilian rule",
      "Murtala Mohammed's short but energetic regime pursued reforms including a major civil service purge and set in motion a transition programme toward civilian rule, continued after his assassination by Olusegun Obasanjo."),
  _q("The 1979 Constitution, which ushered in Nigeria's Second Republic, marked a significant departure from the First Republic mainly by introducing a",
      ["presidential system of government modelled partly on that of the United States", "return to a purely unitary system of government", "continuation of the British parliamentary monarchy", "one-party socialist state structure"], "presidential system of government modelled partly on that of the United States",
      "Unlike the parliamentary First Republic, the 1979 Constitution introduced a presidential system with an executive President, drawing significant inspiration from the American model."),
  _q("General Ibrahim Babangida's regime (1985-1993) is particularly remembered for its prolonged and ultimately incomplete transition programme, culminating in the annulment of the",
      ["12 June 1993 presidential election, widely believed to have been won by MKO Abiola", "1979 general election", "1959 federal election", "1999 presidential election"], "12 June 1993 presidential election, widely believed to have been won by MKO Abiola",
      "Babangida's annulment of the June 12, 1993 election, generally regarded as Nigeria's freest and fairest at the time, triggered a severe political crisis and is widely seen as one of the darkest moments of Nigerian democratic history."),
  _q("General Sani Abacha's rule in the 1990s is widely associated with",
      ["intense authoritarian repression, including the execution of Ken Saro-Wiwa and other Ogoni activists", "a smooth and rapid transition to democratic government", "the peaceful resolution of the June 12 crisis", "Nigeria's return to civilian rule in 1993"], "intense authoritarian repression, including the execution of Ken Saro-Wiwa and other Ogoni activists",
      "Abacha's regime was marked by severe political repression, including the 1995 execution of environmental activist Ken Saro-Wiwa and eight other Ogoni leaders, drawing widespread international condemnation."),
  _q("Nigeria's Fourth Republic, beginning in 1999, is historically notable for representing",
      ["the longest continuous period of civilian democratic governance in Nigeria's post-independence history", "Nigeria's first ever attempt at civilian rule", "a return to the parliamentary system used in the First Republic", "the final period before Nigeria's independence"], "the longest continuous period of civilian democratic governance in Nigeria's post-independence history",
      "Since 1999, Nigeria has sustained an unbroken period of civilian democratic government, marking its longest such stretch since independence, despite the political challenges it has faced."),
  _q("Revenue allocation has remained a persistent and contentious issue in post-independence Nigerian history mainly because of",
      ["disagreements between the federal government and the states/regions over how to share national income, especially oil revenue", "a complete lack of any natural resources within the country", "the absence of any federal government structure", "unanimous agreement among all regions on a fixed permanent formula since 1960"], "disagreements between the federal government and the states/regions over how to share national income, especially oil revenue",
      "Since independence, the distribution of national revenue, particularly oil wealth, between the federal government and the constituent states has remained a recurring and often contentious political issue."),
  _q("The creation of additional states beyond Gowon's original 12, continuing through subsequent military regimes, generally reflected ongoing",
      ["demands from various ethnic and local groups for greater self-administration and access to resources", "instructions from the United Nations Security Council", "attempts to abolish the federal system entirely", "agreements reached at the Berlin Conference"], "demands from various ethnic and local groups for greater self-administration and access to resources",
      "Successive rounds of state creation in Nigeria have generally responded to persistent local and ethnic demands for greater administrative autonomy and more direct access to resources and representation."),
  _q("The transition from military to civilian rule in 1999 was significantly shaped by the sudden death of which military Head of State in mid-1998, which accelerated the transition process?",
      ["General Sani Abacha", "General Yakubu Gowon", "General Murtala Mohammed", "General Ibrahim Babangida"], "General Sani Abacha",
      "Abacha's sudden death in June 1998 led to General Abdulsalami Abubakar taking over and swiftly implementing a transition programme that culminated in the 1999 elections and the start of the Fourth Republic."),
];

final _africanHistory = [
  _q("The West African empire of Ghana is generally believed to have declined significantly following invasions and pressure from the",
      ["Almoravids, a North African Berber Islamic movement", "Ottoman Empire", "Portuguese colonisers", "Mongol Empire"], "Almoravids, a North African Berber Islamic movement",
      "Historians commonly link the decline of ancient Ghana partly to military and religious pressure from the Almoravid movement in the 11th century, alongside internal weaknesses and the drying up of trade routes."),
  _q("Following Mansa Musa's famous pilgrimage to Makkah, the Mali Empire's international reputation was significantly enhanced due to his",
      ["extravagant distribution of gold along the route, which drew wide attention to Mali's wealth", "military conquest of Egypt", "conversion of the entire Islamic world to traditional African religion", "abolition of trade throughout West Africa"], "extravagant distribution of gold along the route, which drew wide attention to Mali's wealth",
      "Mansa Musa's lavish spending and gift-giving of gold during his pilgrimage caused a temporary devaluation of gold in some regions and dramatically raised international awareness of Mali's wealth."),
  _q("The decline of the Mali Empire from the 15th century onward was significantly influenced by",
      ["internal succession disputes and the rising power of the Songhai Empire", "a sudden and total loss of all gold resources", "direct conquest by the Ottoman Empire", "British colonial intervention"], "internal succession disputes and the rising power of the Songhai Empire",
      "Mali's decline resulted from a combination of internal political instability over succession and the growing military and political strength of the emerging Songhai Empire, which eventually eclipsed it."),
  _q("The city of Jenne (Djenne), closely associated with the Mali and Songhai empires, was particularly renowned as a centre of",
      ["trade and Islamic scholarship, alongside Timbuktu", "iron smelting technology unique to Southern Africa", "the trans-Atlantic slave trade", "Portuguese colonial administration"], "trade and Islamic scholarship, alongside Timbuktu",
      "Jenne, like Timbuktu, developed into a major centre of trade and Islamic learning in the Western Sudan, contributing significantly to the intellectual and commercial life of the Mali and Songhai empires."),
  _q("The historic Kanem-Bornu Empire maintained diplomatic and religious contacts across the Sahara reaching as far as",
      ["the Ottoman Empire and North Africa", "the Kingdom of Portugal exclusively", "the Kingdom of Great Zimbabwe", "Western Europe directly, bypassing North Africa"], "the Ottoman Empire and North Africa",
      "Kanem-Bornu maintained active trans-Saharan diplomatic, religious, and commercial relations with North African states and, at times, the Ottoman Empire, reflecting its long-standing regional importance."),
  _q("The prosperity of Great Zimbabwe, a major Southern African civilization, was built substantially on control of trade in",
      ["gold and ivory with the East African (Swahili) coast", "salt with North African caravans", "kola nuts with the Guinea forest region", "cocoa with European trading companies"], "gold and ivory with the East African (Swahili) coast",
      "Great Zimbabwe's wealth derived largely from its role in regional and long-distance trade, particularly the exchange of gold and ivory with Swahili coastal trading cities linked to the wider Indian Ocean trade."),
  _q("The abolition of the trans-Atlantic slave trade by Britain in 1807 primarily affected West Africa by",
      ["gradually shifting British commercial interest toward 'legitimate' trade in goods such as palm oil", "immediately ending all forms of slavery within Africa", "causing an instant and total collapse of West African economies", "leading directly to Nigeria's independence"], "gradually shifting British commercial interest toward 'legitimate' trade in goods such as palm oil",
      "Following abolition, British commercial policy in West Africa gradually pivoted toward promoting 'legitimate' commerce, especially in commodities like palm oil, as a substitute for the slave trade."),
  _q("Which of the following was a significant long-term social effect of the trans-Atlantic slave trade on West African societies?",
      ["Increased warfare and slave-raiding as some states sought captives to trade for European goods", "The immediate and complete disappearance of all indigenous political systems", "Universal population growth across every affected region", "The elimination of all forms of internal African trade"], "Increased warfare and slave-raiding as some states sought captives to trade for European goods",
      "The demand for enslaved people to trade with Europeans encouraged increased warfare, raiding, and the militarisation of some African states seeking captives to exchange for firearms and other goods."),
  _q("The European colonial power most associated with the policy of assimilation, distinct from the British approach of Indirect Rule, was",
      ["France", "Germany", "Portugal", "Belgium"], "France",
      "French colonial policy, especially in West Africa, generally emphasised assimilation, aiming to culturally integrate colonial subjects into French civilisation, in contrast with the British preference for Indirect Rule."),
  _q("At the Berlin Conference of 1884-1885, the principle used to justify a European power's claim to a given African territory generally required that power to demonstrate",
      ["effective occupation of the territory it claimed", "prior ownership recognised by African rulers", "a unanimous vote of all African leaders", "religious conversion of the entire local population"], "effective occupation of the territory it claimed",
      "The Berlin Conference established the principle of 'effective occupation', requiring a European power to show genuine administrative or military presence to have its claim over African territory recognised by other powers."),
  _q("Ethiopia's successful resistance to Italian colonisation at the Battle of Adwa in 1896 is historically significant because it",
      ["allowed Ethiopia to remain one of the very few African states to preserve its independence during the Scramble for Africa", "marked the beginning of the Scramble for Africa", "led to the complete colonisation of the entire Horn of Africa by Italy", "was the first ever conflict between an African and a European power"], "allowed Ethiopia to remain one of the very few African states to preserve its independence during the Scramble for Africa",
      "Ethiopia's decisive victory over Italy at Adwa in 1896 preserved its independence, making it (along with Liberia) one of the few African states to avoid European colonial rule during this period."),
  _q("The 'legitimate trade' era in 19th-century West Africa refers to the period when European commerce shifted its focus mainly toward",
      ["agricultural and natural produce such as palm oil, groundnuts, and rubber, rather than enslaved people", "the exclusive trade of gold and diamonds", "arms trading with African military states", "manufactured European textiles exclusively"], "agricultural and natural produce such as palm oil, groundnuts, and rubber, rather than enslaved people",
      "Following the decline of the slave trade, 'legitimate trade' centred on the export of agricultural and natural commodities like palm oil, groundnuts, and rubber to European markets."),
  _q("Pan-Africanism, as an ideological and political movement, is best described as one that primarily promoted",
      ["solidarity, unity, and the liberation of African peoples and those of African descent worldwide", "European control over African colonies in perpetuity", "the division of Africa into smaller, competing ethnic states", "exclusive economic ties between Africa and a single foreign power"], "solidarity, unity, and the liberation of African peoples and those of African descent worldwide",
      "Pan-Africanism emerged as a movement advocating unity, solidarity, and eventual liberation for African peoples and the African diaspora, influencing independence movements across the continent, including in Nigeria."),
  _q("Kwame Nkrumah of Ghana is particularly significant in African history as",
      ["the leader of the first Sub-Saharan African colony to achieve independence, in 1957", "the founder of the ancient Mali Empire", "a key leader of the Sokoto Jihad", "the ruler who built Great Zimbabwe"], "the leader of the first Sub-Saharan African colony to achieve independence, in 1957",
      "Kwame Nkrumah led Ghana (the former Gold Coast) to independence in 1957, making it the first Sub-Saharan African colony to gain independence, and inspiring subsequent African independence movements including Nigeria's."),
  _q("The Organisation of African Unity (OAU), founded in 1963, was primarily established to promote",
      ["African unity, solidarity, and the eradication of colonialism across the continent", "European economic interests in Africa", "the reinstatement of colonial rule in newly independent states", "military alliances exclusively directed against Cold War superpowers"], "African unity, solidarity, and the eradication of colonialism across the continent",
      "The OAU was founded in Addis Ababa in 1963 by newly independent African states to foster continental unity, coordinate cooperation, and support the ongoing struggle against colonialism across Africa."),
];

final _worldHistory = [
_q("The system of interlocking alliances before World War I, dividing much of Europe into two major camps, is best exemplified by the",
      ["Triple Alliance and the Triple Entente", "United Nations Charter", "Warsaw Pact and NATO", "Berlin Conference agreements"], "Triple Alliance and the Triple Entente",
      "Before World War I, Europe was divided broadly between the Triple Alliance (Germany, Austria-Hungary, Italy) and the Triple Entente (France, Russia, Britain), a rigid alliance system that helped turn a regional crisis into a general war."),
_q("The concept of 'total war', closely associated with both World War I and World War II, refers to a conflict in which",
      ["entire national economies and civilian populations are mobilised in support of the war effort", "fighting is restricted strictly to professional soldiers on clearly defined battlefields", "no modern weapons or technology are used", "combat is limited exclusively to naval engagements"], "entire national economies and civilian populations are mobilised in support of the war effort",
      "'Total war' describes conflicts, like the two World Wars, in which whole societies — industry, civilians, and resources — were mobilised in support of the military effort, blurring the line between combatants and civilians."),
_q("The Treaty of Versailles imposed on Germany after World War I included a clause, widely resented by Germans, that",
      ["assigned Germany full responsibility ('war guilt') for causing the war", "granted Germany additional overseas colonies", "allowed Germany to keep its full pre-war military strength", "immediately readmitted Germany to full membership of the League of Nations"], "assigned Germany full responsibility ('war guilt') for causing the war",
      "The 'War Guilt Clause' of the Treaty of Versailles placed sole responsibility for the war on Germany, justifying heavy reparations and territorial losses, and fuelling deep German resentment."),
_q("The rise of Adolf Hitler and the Nazi Party in Germany during the 1930s was significantly aided by",
      ["severe economic hardship, including hyperinflation and the Great Depression, combined with resentment over Versailles", "widespread economic prosperity across interwar Germany", "strong and effective enforcement mechanisms within the League of Nations", "a lack of any nationalist sentiment in Germany"], "severe economic hardship, including hyperinflation and the Great Depression, combined with resentment over Versailles",
      "Germany's severe economic crises of the 1920s-30s, combined with lingering resentment over the harsh Versailles terms, created fertile conditions that the Nazi Party exploited to gain mass support."),
_q("The policy pursued by Britain and France toward Nazi Germany's early territorial expansion in the late 1930s is commonly known as",
      ["appeasement", "containment", "isolationism", "détente"], "appeasement",
      "Appeasement describes the policy by which Britain and France made concessions to Hitler's territorial demands, such as at the Munich Agreement of 1938, hoping to avoid another major war."),
_q("The Munich Agreement of 1938, a notable example of the appeasement policy, permitted Nazi Germany to annex the",
      ["Sudetenland region of Czechoslovakia", "entire territory of Poland", "Rhineland region of Germany itself", "Alsace-Lorraine region of France"], "Sudetenland region of Czechoslovakia",
      "At the Munich Conference, Britain and France agreed to allow Germany to annex the Sudetenland, a German-speaking region of Czechoslovakia, in a failed attempt to satisfy Hitler's territorial ambitions and avoid war."),
_q("The wartime conference at which Roosevelt, Churchill, and Stalin discussed the post-war reorganisation of Europe, including the division of Germany, was held at",
      ["Yalta", "Versailles", "Berlin (1884-1885)", "San Francisco"], "Yalta",
      "The 1945 Yalta Conference brought together the leaders of the United States, Britain, and the Soviet Union to plan the post-war order in Europe, including arrangements for occupied Germany."),
_q("The founding charter of the United Nations was formally adopted at a conference held in",
      ["San Francisco in 1945", "Versailles in 1919", "Berlin in 1885", "Geneva in 1920"], "San Francisco in 1945",
      "Representatives of fifty nations adopted the United Nations Charter at the San Francisco Conference in 1945, formally establishing the organisation shortly after the end of World War II."),
_q("The Korean War (1950-1953) is generally regarded as a significant early example of a",
      ["Cold War proxy conflict between forces backed by the capitalist and communist blocs", "direct large-scale war between the United States and the Soviet Union", "conflict entirely unrelated to Cold War rivalries", "war fought exclusively using nuclear weapons"], "Cold War proxy conflict between forces backed by the capitalist and communist blocs",
      "The Korean War, pitting a US-led UN coalition against North Korean and Chinese forces, exemplified the pattern of Cold War 'proxy wars' in which the superpowers avoided direct confrontation while backing opposing sides."),
_q("The Cuban Missile Crisis of 1962 is widely regarded as one of the tensest moments of the Cold War because it",
      ["brought the United States and the Soviet Union close to direct nuclear confrontation", "marked the formal end of the Cold War", "resulted in the immediate reunification of Germany", "led directly to the founding of the United Nations"], "brought the United States and the Soviet Union close to direct nuclear confrontation",
      "The discovery of Soviet nuclear missiles in Cuba triggered a tense standoff between the United States and the Soviet Union, widely seen as the moment the world came closest to nuclear war during the Cold War."),
_q("The dissolution of the Soviet Union in 1991 is generally regarded as marking",
      ["the definitive end of the Cold War era", "the beginning of the Cold War", "the start of World War II", "the founding of the League of Nations"], "the definitive end of the Cold War era",
      "The formal collapse of the Soviet Union in December 1991 is widely seen as the conclusive end of the decades-long Cold War rivalry between the Eastern and Western blocs."),
_q("The permanent members of the United Nations Security Council, each holding veto power, originally comprised the United States, the Soviet Union (later Russia), Britain, France, and",
      ["China", "Germany", "Japan", "India"], "China",
      "The five permanent, veto-wielding members of the UN Security Council are the United States, Russia (as Soviet successor), Britain, France, and China, reflecting the major Allied powers of World War II."),
_q("The Non-Aligned Movement, which many newly independent African and Asian states (including Nigeria) associated with, emerged as a response to",
      ["a wish to avoid formal alignment with either the Western capitalist bloc or the Soviet-led communist bloc during the Cold War", "a decision to join the Warsaw Pact exclusively", "a formal military alliance directed against the United Nations", "an agreement to support only the League of Nations"], "a wish to avoid formal alignment with either the Western capitalist bloc or the Soviet-led communist bloc during the Cold War",
      "The Non-Aligned Movement, formed in the early 1960s, allowed newly independent states to pursue independent foreign policies without formally aligning with either Cold War superpower bloc."),
];
