import "../quiz_question.dart";

const _subject = "Hausa";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// Obafemi Awolowo University (OAU), Ile-Ife Post-UTME Hausa practice bank —
/// 100 medium-to-hard questions covering Ka'idojin Rubutu (orthography),
/// Auna Fahimta (comprehension), Tsarin Sauti (phonology), Ƙirar Kalma
/// (morphology), Gidajen Kalmomi (syntax), Adabin Baka (oral literature —
/// weighted higher, especially proverbs and culture), Rubutaccen Adabi
/// (written literature, covered only at a general/author level rather than
/// through detailed prescribed-text plot questions), and Al'ada (culture).
/// This is an original practice set modelled on typical OAU Post-UTME/JAMB
/// Hausa screening style, not a reproduction of any official past question
/// paper; always confirm the exact syllabus and format on OAU's own
/// screening portal for the current session.
List<QuizQuestion> buildOauHausaQuestions() {
  return [
    ..._kaidojinRubutu,
    ..._aunaFahimta,
    ..._tsarinSauti,
    ..._kirarKalma,
    ..._gidajenKalmomi,
    ..._adabinBaka,
    ..._rubutaccenAdabi,
    ..._alada,
  ];
}

final _kaidojinRubutu = [
  _q("Wanne daga cikin wadannan haruffa ne baya cikin haruffan Hausa na boko?",
      ["Q", "K", "Ƙ", "R"], "Q",
      "Standard Hausa boko orthography excludes the Latin letters Q, X, and V; it uses K, Ƙ, and R among its consonants."),
  _q("Menene daidai matsayin harafin 'Ɓ' idan aka kwatanta da 'B' a rubutun Hausa?",
      ["Ɓ baƙi ne mai shaƙuwa (implosive) daban da B", "Ɓ da B daya ne kawai a rubuce ba tare da bambanci ba", "Ɓ ba a amfani da shi a Hausa", "Ɓ wasali ne"], "Ɓ baƙi ne mai shaƙuwa (implosive) daban da B",
      "Ɓ represents a distinct implosive consonant sound in Hausa, phonemically different from the plain plosive B."),
  _q("A ka'idar rubutun Hausa, yaushe ake amfani da babban harafi (capital letter)?",
      ["A farkon jimla da kuma sunayen musamman", "A karshen kowace kalma", "A tsakiyar kalma kawai", "Ba a taba amfani da babban harafi a Hausa"], "A farkon jimla da kuma sunayen musamman",
      "As in standard orthographic convention, Hausa capitalises the first word of a sentence and proper nouns such as personal names and place names."),
  _q("Wanne misali ne daidai wajen amfani da alamar sirara (apostrophe) a Hausa?",
      ["'Yan mata", "Yan' mata", "Y'an mata", "Yanmata'"], "'Yan mata",
      "The apostrophe correctly precedes 'yan' in 'yan mata' (girls), marking the elided initial sound, as commonly standardised in Hausa orthography."),
  _q("Menene kuskure a wannan jimlar: 'ya tafi kasuwa jiya'?",
      ["Rashin amfani da babban harafi a farkon jimla", "Rashin waƙafi", "Rashin alamar tambaya", "Rashin amfani da baƙar dawa"], "Rashin amfani da babban harafi a farkon jimla",
      "The sentence should begin with a capital letter: 'Ya tafi kasuwa jiya', since it starts a new sentence."),
  _q("A rubutun Hausa, menene aikin 'waƙafi' (comma)?",
      ["Yana nuna gajeren tsayawa a cikin jimla domin raba sassa", "Yana nuna karshen jimla gaba daya", "Yana nuna tambaya", "Yana nuna mamaki kawai"], "Yana nuna gajeren tsayawa a cikin jimla domin raba sassa",
      "The comma (waƙafi) marks a brief pause, typically separating items in a list or clauses within a sentence, without ending the sentence."),
  _q("Wanne daga cikin jimlolin nan biyu ne daidai a fannin rabon kalmomi: 'ba komai' ko 'bakomai'?",
      ["ba komai", "bakomai", "Dukansu daidai ne", "Babu wanda ke daidai"], "ba komai",
      "'Ba komai' (nothing/it's alright) is correctly written as two separate words in standard Hausa orthography, not merged."),
  _q("Menene ake kira alamar da ake amfani da ita don nuna cewa magana ce ta wani mutum a rubuce, kalma-kalma?",
      ["Alamar magana (quotation marks)", "Aya", "Waƙafi", "Alamar tambaya"], "Alamar magana (quotation marks)",
      "Quotation marks are used to enclose direct speech or a quoted statement exactly as spoken or written by someone else."),
  _q("A rubutaccen Hausa, wace hanya ce daidai ta nuna adadi 'talatin da biyar' a matsayin lamba?",
      ["35", "53", "305", "350"], "35",
      "'Talatin da biyar' translates directly to thirty-five, written numerically as 35."),
  _q("Me ya sa ake bukatar sanin ka'idojin rubutu sosai kafin rubuta rahoto ko wasika a Hausa?",
      ["Domin gujewa kuskuren da zai iya canza ma'ana ko rikita mai karatu", "Domin karin lokacin da za a dauka wajen rubutu", "Domin baiwa marubuci lambar yabo", "Domin babu wata fa'ida"], "Domin gujewa kuskuren da zai iya canza ma'ana ko rikita mai karatu",
      "Careful adherence to orthographic rules prevents ambiguity or unintended changes in meaning, ensuring the writing is clearly understood."),
  _q("Wace kalma ce aka rubuta daidai bisa ka'idar rubutun Hausa?",
      ["Malami", "Mallami", "Malaami", "Mallam'i"], "Malami",
      "'Malami' (teacher) is the standard, correctly spelt form in Hausa orthography."),
  _q("A rubutun Hausa, menene bambanci tsakanin 'ƙirƙira' da 'kirkira'?",
      ["Ƙirƙira daidai ne saboda amfani da hooked ƙ, kirkira kuskure ne", "Kirkira daidai ne, ƙirƙira kuskure ne", "Dukansu daidai ne gaba daya", "Ba su da wata ma'ana"], "Ƙirƙira daidai ne saboda amfani da hooked ƙ, kirkira kuskure ne",
      "'Ƙirƙira' (to invent/create) requires the hooked Ƙ, which is phonemically distinct from plain K; spelling it with plain 'k' is an orthographic error."),
];

final _aunaFahimta = [
  _q("A tambayoyin auna fahimta, idan aka nemi 'babban ra'ayi' na labari, mai karatu zai fara da",
      ["Neman babban sako da marubuci yake son isarwa", "Kirga yawan jimlolin da ke cikin labarin", "Neman sunan mai buga littafin", "Duba tsawon lokacin da aka dauka wajen rubuta labarin"], "Neman babban sako da marubuci yake son isarwa",
      "Identifying the main idea means locating the central message the writer intends to communicate, not incidental production details."),
  _q("Idan wata tambaya ta ce 'menene take/take na dacewa da labarin?', menene ake bukata daga dalibi?",
      ["Ya zabi taken da ya fi dacewa da abin da labarin ya kunsa gaba daya", "Ya zabi taken mafi tsayi", "Ya zabi kalma ta farko a cikin labarin", "Ya zabi kalma ta karshe a cikin labarin"], "Ya zabi taken da ya fi dacewa da abin da labarin ya kunsa gaba daya",
      "A suitable title question requires selecting the option that best captures the overall content and theme of the passage, not superficial features."),
  _q("A wani labari, an ce 'Audu ya yi murna matuka domin ya samu tallafin karatu.' Menene dalilin murnar Audu?",
      ["Ya samu tallafin karatu", "Ya samu sabon mota", "Ya samu aiki", "Ya samu aure"], "Ya samu tallafin karatu",
      "The sentence directly states Audu's joy was because he obtained a scholarship, a straightforward direct-extraction comprehension question."),
  _q("Yaya za a iya bambance tsakanin 'gaskiya' (fact) da 'ra'ayi' (opinion) a cikin wani rubutu?",
      ["Gaskiya za a iya tabbatar da ita, ra'ayi kuwa fahimtar mutum ne game da wani abu", "Babu wani bambanci a tsakaninsu", "Ra'ayi koda yaushe gaskiya ne", "Gaskiya ba za a iya tabbatar da ita ba"], "Gaskiya za a iya tabbatar da ita, ra'ayi kuwa fahimtar mutum ne game da wani abu",
      "A fact can be verified as objectively true, while an opinion reflects a personal judgement or belief that may vary between individuals."),
  _q("Idan tambaya ta bukaci dalibi ya yi hasashen abin da zai faru gaba a labari, wace fasaha ake amfani da ita?",
      ["Yin hasashe (prediction/inference)", "Taƙaita labari kawai", "Fitar da bayani kai tsaye", "Rabon kalmomi"], "Yin hasashe (prediction/inference)",
      "Predicting or inferring future events in a passage requires reasoning beyond what is explicitly stated, using contextual clues already given."),
  _q("A cikin jumlar 'Ko da yake ruwa yana sauka, Bala ya ci gaba da tafiya kasuwa', menene ma'anar 'ko da yake'?",
      ["Duk da cewa (despite the fact that)", "Domin (because)", "Idan (if)", "Kafin (before)"], "Duk da cewa (despite the fact that)",
      "'Ko da yake' functions as a concessive connective meaning 'even though/despite the fact that', signalling contrast between two clauses."),
  _q("Idan a cikin labari aka ce 'ta yi fatali da shawarar mahaifiyarta', menene ma'anar 'yi fatali da'?",
      ["Ki ko yi watsi da wani abu", "Yarda da wani abu", "Yaba wa wani abu", "Yi kokarin fahimtar wani abu"], "Ki ko yi watsi da wani abu",
      "The idiomatic expression 'yi fatali da' means to reject or disregard something, here referring to dismissing the mother's advice."),
  _q("Wace dabara ce ta fi taimakawa wajen gano amsar tambaya cikin sauri a jarabawar fahimta?",
      ["Duba kalmomin da ke cikin tambayar sannan a nemo su a sakin layin da suka dace", "Karanta amsoshin kadai ba tare da karanta tambayar ba", "Zabi amsa mafi tsayi koyaushe", "Zabi amsa ta farko koyaushe ba tare da tunani ba"], "Duba kalmomin da ke cikin tambayar sannan a nemo su a sakin layin da suka dace",
      "An efficient comprehension strategy is scanning for key words from the question within the relevant paragraph to quickly locate supporting evidence."),
  _q("Menene ake nufi idan aka ce wani rubutu 'na ba da labari' (narrative) ne?",
      ["Rubutun da ke ba da labarin abubuwan da suka faru, na gaskiya ko na kagaggu", "Rubutun da ke koyar da yadda ake yin wani abu kawai", "Rubutun da ke bayyana ra'ayin marubuci kawai", "Rubutun da ba shi da wani tsari"], "Rubutun da ke ba da labarin abubuwan da suka faru, na gaskiya ko na kagaggu",
      "A narrative text tells a story of events, whether real or fictional, typically with characters, setting, and a sequence of happenings."),
  _q("A cikin labarin da ke cewa 'Talakawa da yawa suna fama da matsalar rashin ruwa mai tsafta', menene babban abin damuwa?",
      ["Rashin ruwa mai tsafta ga talakawa", "Yawan mutane a birni", "Rashin makarantu", "Rashin ababen more rayuwa gaba daya"], "Rashin ruwa mai tsafta ga talakawa",
      "The sentence explicitly identifies lack of access to clean water among the poor as the central concern being discussed."),
];

final _tsarinSauti = [
  _q("Wadanne sautuka ne 'a, e, i, o, u' a Hausa?",
      ["Wasula (vowels)", "Baƙaƙe (consonants)", "Kirari", "Karin sauti"], "Wasula (vowels)",
      "The five basic vowel qualities a, e, i, o, u form the vowel inventory of Hausa, produced without significant airflow obstruction."),
  _q("Menene ake kira baƙaƙen da ake furta su ta hanyar hade wurin fitar iska da baki, kamar 'ts' a Hausa?",
      ["Baƙaƙe masu haɗi (affricates)", "Wasula dogaye", "Karin sauti mai fadowa", "Sila a bude"], "Baƙaƙe masu haɗi (affricates)",
      "Affricate consonants like 'ts' involve a stop closure immediately released into a fricative, a recognised consonant class in Hausa phonology."),
  _q("A Hausa, dogon wasali (long vowel) kamar wanda ke cikin 'baabaa' yana da mahimmancin",
      ["Iya canza ma'anar kalma daga gajeren wasali", "Babu wani muhimmanci", "Kawai kyautata sauti ba tare da canza ma'ana ba", "Iya canza harshe gaba daya"], "Iya canza ma'anar kalma daga gajeren wasali",
      "Vowel length is phonemically contrastive in Hausa — long versus short vowels can distinguish word meaning entirely, not just add stylistic effect."),
  _q("Karin sauti mai sauka (low tone) idan aka canza shi zuwa sama a wata kalma, menene zai iya faruwa?",
      ["Ma'anar kalmar na iya canzawa gaba daya", "Babu wani tasiri kwata-kwata", "Kalmar za ta zama wasali kadai", "Kalmar za ta bata sauti gaba daya"], "Ma'anar kalmar na iya canzawa gaba daya",
      "Since Hausa is a tonal language, changing the tone pattern on an otherwise identical word can completely change its meaning."),
  _q("Menene ake kira aikin da ake yi na hada baƙi biyu domin su zama sauti daya kacal a furuci, misali 'nb' ya zama 'mb'?",
      ["Daidaitawa (assimilation)", "Rage kalma (deletion)", "Kirar kalma", "Sila a rufe"], "Daidaitawa (assimilation)",
      "This is a classic example of assimilation, where a nasal consonant changes its place of articulation to match a following consonant."),
  _q("A Hausa, wace irin sila ce 'kar' a cikin 'karfe'?",
      ["Sila a rufe (closed syllable)", "Sila a bude (open syllable)", "Wasali dogo kadai", "Baƙi mara amfani"], "Sila a rufe (closed syllable)",
      "The syllable 'kar' ends in the consonant 'r', making it a closed syllable by definition."),
  _q("Menene ake kira sautin da ake furtawa ta hanyar toshe iska sannan a saki shi kwatsam, kamar 'p', 'b', 'k', 'g'?",
      ["Baƙaƙe masu fashewa (plosives/stops)", "Wasula gajeru", "Baƙaƙe masu goga (fricatives)", "Karin sauti"], "Baƙaƙe masu fashewa (plosives/stops)",
      "Plosive (stop) consonants like p, b, k, g are produced by completely blocking airflow then releasing it abruptly."),
  _q("A ilimin karin sauti, menene ake kira kalmomi biyu da ke da sauti daya amma karin sauti daban, wanda ke haifar da ma'ana daban-daban?",
      ["Kalmomin da karin sauti ya bambanta ma'anarsu (tone-distinguished minimal pairs)", "Kalmomin aro", "Kalmomin jinsi", "Kalmomin adadi"], "Kalmomin da karin sauti ya bambanta ma'anarsu (tone-distinguished minimal pairs)",
      "These are minimal pairs distinguished purely by tone, illustrating tone's role as a meaning-differentiating feature in Hausa."),
  _q("Wane fanni ne ya fi mayar da hankali kan yadda ake tsara sautukan magana cikin tsari na kalmomi da jimloli?",
      ["Tsarin sauti (phonology)", "Al'ada (culture)", "Rubutaccen adabi", "Adabin baka"], "Tsarin sauti (phonology)",
      "Phonology is precisely the branch concerned with how speech sounds are organised and patterned within a language's words and sentences."),
  _q("Menene sunan tsarin da ake amfani da shi domin nazarin inda ake fitar da sauti a bakin magana, kamar hakori, harshe, ko lebe?",
      ["Wurin fitar sauti (place of articulation)", "Yanayin fitar sauti kawai", "Karin sauti", "Kirar kalma"], "Wurin fitar sauti (place of articulation)",
      "Place of articulation describes the specific location in the vocal tract — such as teeth, tongue, or lips — where a sound's airflow is constricted."),
];

final _kirarKalma = [
  _q("Menene ake kira sashin kalma da ke ba da ainihin ma'anar kalmar, kafin a kara wani kari?",
      ["Tushen kalma (root)", "Kari (affix)", "Karin sauti", "Sila"], "Tushen kalma (root)",
      "The root of a word carries its core lexical meaning, before any prefixes or suffixes are attached."),
  _q("A Hausa, kalmar 'malamai' an samo ta ta hanyar",
      ["Kara alamar jam'i ga tushen kalma 'malami'", "Rage wani baki daga tushen kalma", "Hada kalmomi biyu daban-daban gaba daya", "Sauya wasali kadai ba tare da wata alama ba"], "Kara alamar jam'i ga tushen kalma 'malami'",
      "'Malamai' is the plural of 'malami' formed by adding a pluralising suffix pattern to the singular root."),
  _q("Menene ake kira hada kalmomi biyu daban-daban domin samar da sabuwar kalma mai ma'ana, kamar 'gidan sarki'?",
      ["Hadaka (compounding)", "Rage kalma (clipping)", "Aro kalma (borrowing)", "Sila a bude"], "Hadaka (compounding)",
      "Compounding joins two independent words to form a new word or phrase with combined meaning, as in 'gidan sarki' (the chief's house/palace)."),
  _q("A ƙirar kalma, menene ake kira kalmomin da aka aro daga wani harshe, misali 'motoci' daga Turanci 'motor'?",
      ["Kalmomin aro (loan words)", "Kalmomin asali", "Kalmomin hadaka", "Kalmomin jam'i"], "Kalmomin aro (loan words)",
      "Loan words are terms borrowed from another language and adapted into Hausa, such as 'mota' (car) from English 'motor'."),
  _q("Wace hanya ce ake amfani da ita wajen sauya suna zuwa fi'ili ko akasin haka a Hausa?",
      ["Kara kari domin canza aji na kalma (derivation)", "Kawai canza karin sauti kadai", "Kawar da dukkan wasula", "Sauya kalma zuwa wani harshe daban"], "Kara kari domin canza aji na kalma (derivation)",
      "Derivational morphology involves adding affixes that can change a word's grammatical class, e.g. from noun to verb or vice versa."),
  _q("Menene ake kira kari da ake sawa a farkon kalma, kamar 'ma-' a cikin 'malami'?",
      ["Kari na gaba (prefix)", "Kari na baya (suffix)", "Kari na tsakiya (infix)", "Tushen kalma"], "Kari na gaba (prefix)",
      "A prefix is an affix attached to the beginning of a word, as opposed to a suffix which attaches at the end."),
  _q("Kalmar 'ɗalibai' jam'i ce ta wace kalma?",
      ["Ɗalibi", "Ɗalibar", "Ɗalibawa", "Ɗalibiya"], "Ɗalibi",
      "'Ɗalibai' (students) is the plural form of the singular noun 'ɗalibi' (student)."),
  _q("A Hausa, menene ake kira canza fi'ili domin nuna lokacin da aikin ya faru, kamar lokacin da ya wuce ko na yanzu?",
      ["Sauyin lokaci (tense marking)", "Hadaka", "Aro kalma", "Karin magana"], "Sauyin lokaci (tense marking)",
      "Tense marking on the verb (or through auxiliary particles in Hausa) indicates when an action occurred — past, present, or future."),
  _q("Wanne daga cikin wadannan misalai ne na kalmar hadaka (compound word) a Hausa?",
      ["Mai-gida", "Kujera", "Rubutu", "Kalma"], "Mai-gida",
      "'Mai-gida' (household head, literally 'owner of house') combines 'mai' (owner/possessor of) and 'gida' (house) into a compound word."),
  _q("Menene ake kira fannin nazarin yadda ake gina kalmomi daga sassa mafi karanci masu ma'ana?",
      ["Ƙirar kalma (morphology)", "Gidajen kalmomi (syntax)", "Tsarin sauti", "Al'ada"], "Ƙirar kalma (morphology)",
      "Morphology studies how words are built from smaller meaningful units such as roots, prefixes, and suffixes."),
];

final _gidajenKalmomi = [
  _q("A gidajen kalmomi (syntax) na Hausa, menene tsarin asali na jimla mai sauki?",
      ["Fa'ili + Fi'ili + Abin da aka yi wa aiki (Subject-Verb-Object)", "Fi'ili + Fa'ili + Abin da aka yi wa aiki", "Abin da aka yi wa aiki + Fa'ili + Fi'ili", "Babu wani tsari da aka kayyade"], "Fa'ili + Fi'ili + Abin da aka yi wa aiki (Subject-Verb-Object)",
      "Hausa basic sentence order typically follows Subject-Verb-Object (SVO), similar in structure to many analytic languages."),
  _q("A jimlar 'Musa ya karanta littafi', menene rawar 'Musa'?",
      ["Fa'ili (subject)", "Fi'ili (verb)", "Abin aiki (object)", "Sifa (adjective)"], "Fa'ili (subject)",
      "'Musa' is the subject (fa'ili) of the sentence, performing the action of reading."),
  _q("Wanne kalma ce fi'ili (verb) a cikin jimlar 'Yara suna wasa a filin wasa'?",
      ["Wasa", "Yara", "Filin", "Wasa a filin"], "Wasa",
      "'Wasa' (to play) is the action word (verb) in the sentence, describing what the children are doing."),
  _q("A gidajen kalmomi, menene ake kira kalmar da ke bayyana wani abu game da suna, kamar 'babba' a 'gida babba'?",
      ["Sifa (adjective)", "Fi'ili", "Karin magana", "Alamar tambaya"], "Sifa (adjective)",
      "An adjective (sifa) describes or qualifies a noun, such as 'babba' (big) describing 'gida' (house)."),
  _q("Wace jimla ce daidai a fannin tsarin nahawu?",
      ["Ali ya sayi mota jiya.", "Mota Ali jiya ya sayi.", "Jiya mota sayi ya Ali.", "Ya Ali jiya sayi mota."], "Ali ya sayi mota jiya.",
      "Only 'Ali ya sayi mota jiya' (Ali bought a car yesterday) follows correct standard Hausa word order; the others scramble the sentence structure."),
  _q("Menene ake kira kalmar da ke maye gurbin suna domin gujewa maimaitawa, misali 'shi' a maimakon 'Audu'?",
      ["Wakilin suna (pronoun)", "Sifa", "Fi'ili", "Kari"], "Wakilin suna (pronoun)",
      "A pronoun (wakilin suna) substitutes for a noun to avoid repetition, such as using 'shi' (he) instead of repeating a name."),
  _q("A jimlar 'Ta kawo ruwa saboda kishirwa ta kama ta', menene rawar 'saboda' a jimlar?",
      ["Yana hada jimlar biyu domin nuna dalili", "Yana nuna wurin da aikin ya faru", "Yana nuna sunan mutum", "Ba shi da wani aiki"], "Yana hada jimlar biyu domin nuna dalili",
      "'Saboda' (because) is a conjunction linking two clauses to show cause and effect/reason."),
  _q("Menene ake kira jimlar da take da fa'ili da fi'ili guda daya kacal, ba tare da wata karamar jimla a cikinta ba?",
      ["Jimla sauki (simple sentence)", "Jimla hadaka (compound sentence)", "Jimla rikitacciya (complex sentence)", "Babu amsa daidai"], "Jimla sauki (simple sentence)",
      "A simple sentence contains a single subject and a single verb (one independent clause), without additional clauses."),
  _q("Wace kalma ce ake amfani da ita domin nuna wuri a cikin jimlar 'Littafin yana kan tebur'?",
      ["Kan (a matsayin kalmar nuni ga wuri)", "Yana", "Littafin", "Tebur"], "Kan (a matsayin kalmar nuni ga wuri)",
      "'Kan' functions here as a locative/prepositional element indicating position — 'on top of' the table."),
  _q("A gidajen kalmomi na Hausa, menene ake kira canza tsarin jimla domin ta zama tambaya, misali 'Ya tafi kasuwa' zuwa 'Shin ya tafi kasuwa?'",
      ["Sauya jimla zuwa jimlar tambaya", "Sauya jimla zuwa jimlar umarni", "Sauya jimla zuwa jimlar mamaki", "Babu wani sauyi da ya faru"], "Sauya jimla zuwa jimlar tambaya",
      "Adding the interrogative marker 'shin' transforms a declarative sentence into a yes/no question."),
];

final _adabinBaka = [
  _q("Menene ma'anar karin magana 'Kowa ya ga dan uwansa da fara, ba ya cewa jajir'?",
      ["Kada ka yi wa wani abu izgili domin za a iya samun irinsa a kanka", "Kowa yana da hakkin dukiyar dan uwansa", "Bai kamata a taimaki dan uwa ba", "Kada ka amince da dan uwanka"], "Kada ka yi wa wani abu izgili domin za a iya samun irinsa a kanka",
      "This proverb warns against mocking others' misfortunes, since one may later find similar trouble affecting oneself or a relative."),
  _q("A al'adar Hausa, menene karin magana 'Hakuri maganin duniya' ke koyarwa?",
      ["Hakuri shine mafita ga matsalolin rayuwa", "Kada a yi hakuri kwata-kwata", "Duniya ba ta bukatar hakuri", "Hakuri yana kawo talauci"], "Hakuri shine mafita ga matsalolin rayuwa",
      "This widely known proverb teaches that patience is the key remedy for life's many challenges and hardships."),
  _q("Karin maganar 'Ruwan bagiwa ba ya kashe kishi' na koyar da",
      ["Cewa taimako marar gaskiya ba ya warware matsala da gaske", "Cewa ruwa mai yawa yana da amfani", "Cewa kishirwa ba ta warwarewa", "Cewa bagiwa dabba ce mai amfani"], "Cewa taimako marar gaskiya ba ya warware matsala da gaske",
      "This proverb, likening a mirage's water to false help, teaches that superficial or insincere assistance does not truly solve a problem."),
  _q("Wace irin adabin baka ce 'kirari', wanda ake amfani da shi wajen yabon mutum ko dabba?",
      ["Kalaman yabo ko siffanta wani abu ta hanyar kirari na musamman", "Labarin gargadi kawai", "Wakar bikin aure kadai", "Kissar tarihi kawai"], "Kalaman yabo ko siffanta wani abu ta hanyar kirari na musamman",
      "Kirari (praise epithets) are traditional laudatory or descriptive phrases used to honour and characterise a person, animal, or lineage."),
  _q("Menene 'tatsuniya' a adabin baka na Hausa?",
      ["Labarin kirkirarre wanda ake ba da shi domin nishadi da koyarwa, sau da yawa da dabbobi masu magana", "Rahoto na gaskiya game da tarihin kasa", "Wakar Islama kawai", "Sanarwar gwamnati"], "Labarin kirkirarre wanda ake ba da shi domin nishadi da koyarwa, sau da yawa da dabbobi masu magana",
      "A tatsuniya is a traditional Hausa folktale, often featuring talking animals, told both for entertainment and moral instruction."),
  _q("Menene babban dalilin ba da tatsuniya ga yara a al'adar Hausa da dare?",
      ["Domin koyar da su darasi na rayuwa da kuma nishadantar da su", "Domin su gaji su yi barci nan take", "Domin nuna karfin murya", "Babu wani dalili na musamman"], "Domin koyar da su darasi na rayuwa da kuma nishadantar da su",
      "Storytelling sessions at night traditionally served the dual purpose of entertaining children while imparting moral and social lessons."),
  _q("Wace irin waka ce 'wakar noma', wadda ake raira wa manoma yayin aiki a gona?",
      ["Wakar aiki (work song) da ke karfafa gwiwar manoma", "Wakar makoki kawai", "Wakar yabon sarki kadai", "Wakar addini kadai"], "Wakar aiki (work song) da ke karfafa gwiwar manoma",
      "Farming songs (wakar noma) are traditional work songs sung to encourage and energise farmers as they labour in the fields."),
  _q("Menene ake kira gajerun jimloli masu ban dariya ko wayo da ake amfani da su domin gwada hankali, kamar 'Me ke da kai amma ba shi da jiki?'",
      ["Kacici-kacici (riddles)", "Kirari", "Habaici", "Wasan kwaikwayo"], "Kacici-kacici (riddles)",
      "Riddles (kacici-kacici) are short witty questions used in Hausa oral tradition to test cleverness, often exchanged as a form of play."),
  _q("Menene 'habaici' a cikin adabin baka na Hausa?",
      ["Zambo ko sukar da ake yi wa wani a fakaice, ba tare da ambaton sunansa kai tsaye ba", "Yabon da ake yi wa sarki kai tsaye", "Labarin tarihi na gaskiya", "Wakar bikin suna kawai"], "Zambo ko sukar da ake yi wa wani a fakaice, ba tare da ambaton sunansa kai tsaye ba",
      "Habaici is an indirect form of criticism or satire, aimed at someone without directly naming them, often understood by context."),
  _q("Karin maganar 'Zaman lafiya ya fi zaman dowa' na koyar da mutane su",
      ["Ba wa zaman lafiya muhimmanci fiye da wani abu", "Su zauna a daji tare da dabbobi", "Su ki zama tare da wasu", "Su nemi arziki kadai"], "Ba wa zaman lafiya muhimmanci fiye da wani abu",
      "This proverb emphasises that peaceful coexistence is more valuable than wealth or comfort gained at the cost of conflict."),
  _q("Menene ake kira wakokin da ake rerawa a wuraren shagulgulan aure na gargajiya a al'adar Hausa?",
      ["Wakokin aure", "Wakokin yaki", "Wakokin makoki", "Wakokin addu'a kawai"], "Wakokin aure",
      "Wedding songs (wakokin aure) are traditional songs performed during marriage celebrations, expressing joy and blessing for the couple."),
  _q("A karin magana 'In ba ka gyara gida ba, gida zai gyara ka', menene babban darasi?",
      ["Kula da abin da yake naka ko ya mallake ka", "Kada ka taba gyara gida", "Gida ba shi da wata alaka da mutum", "Ka bar gida ya ruguje"], "Kula da abin da yake naka ko ya mallake ka",
      "This proverb teaches responsibility: if you fail to maintain what is yours, circumstances will eventually force hardship upon you."),
  _q("Menene ake kira wakokin yabon jarumai da suka nuna gwaninta a fagen daga a tsohuwar al'ada?",
      ["Wakokin yaki/jarumta", "Wakokin bukukuwan suna", "Wakokin noma", "Wakokin addini"], "Wakokin yaki/jarumta",
      "War/heroism songs celebrated the bravery and exploits of warriors, a notable genre within traditional Hausa oral poetry."),
  _q("Karin maganar 'Hannu daya ba ya daukar jinka' na nufin",
      ["Hadin kai yana da muhimmanci wajen kammala manyan ayyuka", "Mutum daya zai iya yin komai shi kadai", "Jinka ba shi da nauyi", "Kada mutane su taimaki juna"], "Hadin kai yana da muhimmanci wajen kammala manyan ayyuka",
      "This proverb ('one hand cannot carry a large calabash') stresses the importance of cooperation and unity in accomplishing big tasks."),
  _q("Menene 'take' a cikin adabin baka, wanda ake amfani da shi wajen gabatar da wani mawaƙi ko shahararren mutum?",
      ["Gajeriyar waka ta yabo da ake danganta wa mutum ko iyali", "Doguwar tatsuniya", "Sanarwar gwamnati", "Rubutacciyar wasika"], "Gajeriyar waka ta yabo da ake danganta wa mutum ko iyali",
      "A 'take' is a short praise chant or musical phrase specifically associated with an individual, family, or lineage in Hausa oral tradition."),
  _q("Karin maganar 'Kowane mutum ne magajin gyaɗa' na iya nufin",
      ["Kowa na iya samun rabo ko dama a wani abu na kowa", "Gyada ba ta da wani amfani", "Mutum daya ne kadai zai iya cin gyada", "Gyada tsada ce sosai"], "Kowa na iya samun rabo ko dama a wani abu na kowa",
      "This proverb suggests that opportunities or shared resources are open to everyone, not reserved for a select few."),
  _q("Menene manufar amfani da 'karin magana' a cikin zance na yau da kullum a al'adar Hausa?",
      ["Domin kara wa magana armashi da isar da sako a takaice cikin hikima", "Domin dagula fahimtar mai sauraro", "Domin nuna rashin ilimi", "Babu wata manufa ta musamman"], "Domin kara wa magana armashi da isar da sako a takaice cikin hikima",
      "Proverbs enrich everyday speech, conveying wisdom and meaning concisely and adding rhetorical flair to communication."),
  _q("A al'adar Hausa, wa ake dauka a matsayin mai adana da isar da adabin baka daga tsara zuwa tsara?",
      ["Marubuta da masu ba da labari na gargajiya, kamar tsofaffi da mawaka", "Injiniyoyi kawai", "Malaman fikihu kadai", "'Yan kasuwa kadai"], "Marubuta da masu ba da labari na gargajiya, kamar tsofaffi da mawaka",
      "Oral literature is traditionally preserved and transmitted across generations through storytellers, elders, and musicians/griots."),
  _q("Karin maganar 'Gara a ce an yi wani abu ba daidai ba, da a ce ba a yi kome ba' na karfafa",
      ["Muhimmancin yin kokari maimakon zaman kashe wando", "Rashin bukatar yin komai", "Cewa kuskure ba shi da illa", "Cewa a bar kokari gaba daya"], "Muhimmancin yin kokari maimakon zaman kashe wando",
      "This proverb encourages effort and action over idleness, suggesting it is better to try and possibly err than to do nothing at all."),
  _q("Menene ake kira raira waka da amsa waka a tsakanin jagora da 'yan amshi a wakokin gargajiya na Hausa?",
      ["Jagora da amshi (call and response)", "Wasan kwaikwayo kadai", "Karin magana kadai", "Kacici-kacici kadai"], "Jagora da amshi (call and response)",
      "The call-and-response structure, with a lead singer (jagora) and chorus (amshi), is a defining performance feature of traditional Hausa songs."),
];

final _rubutaccenAdabi = [
  _q("Menene ake kira rubutaccen adabi na Hausa da aka fara rubutawa da rubutun Ajami kafin zuwan boko?",
      ["Adabin Ajami", "Adabin boko", "Adabin baka kadai", "Adabin Turanci"], "Adabin Ajami",
      "Before the introduction of the Latin-based 'boko' script, Hausa written literature was recorded using the Arabic-based Ajami script."),
  _q("A tarihin adabin Hausa, wace irin gudunmawa ce marubuta irin su Abubakar Imam suka bayar?",
      ["Rubuta litattafai da suka kafa harsashin zube na zamani a Hausa", "Rubuta kundin tarihin Turai kawai", "Fassara Alkur'ani zuwa Turanci", "Kirkiro harshen Hausa daga farko"], "Rubuta litattafai da suka kafa harsashin zube na zamani a Hausa",
      "Abubakar Imam is widely recognised as a foundational figure in modern Hausa prose literature, notably through works like 'Ruwan Bagaja'."),
  _q("Menene ake kira nau'in adabi wanda aka rubuta shi bisa tsari na baiti da amsa-amo, kamar wakokin marubuta na zamani?",
      ["Waka (poetry)", "Zube (prose)", "Wasan kwaikwayo (drama)", "Kacici-kacici"], "Waka (poetry)",
      "Poetry (waka) in written Hausa literature is typically composed in structured verses with rhyme and metre, unlike prose."),
  _q("Wasan kwaikwayo (drama) a matsayin nau'in rubutaccen adabi na Hausa yana da mahimmanci wajen",
      ["Nuna rayuwar zamantakewa ta hanyar wasa da tattaunawa a kan dandali ko allo", "Bayar da labarin gaskiya na tarihi kadai", "Koyar da lissafi", "Rubuta kundin addini kadai"], "Nuna rayuwar zamantakewa ta hanyar wasa da tattaunawa a kan dandali ko allo",
      "Drama as a literary genre depicts social life through performed dialogue and action on stage or screen, distinct from prose narration."),
  _q("A rubutaccen adabin Hausa, menene babban bambanci tsakanin 'zube' da 'waka'?",
      ["Zube rubutu ne na yau da kullum ba tare da tsayayyen tsarin baiti ba, waka kuwa tana da tsari na baiti da amsa-amo", "Babu wani bambanci a tsakaninsu", "Zube ana rerawa ne kawai", "Waka ba ta da ma'ana"], "Zube rubutu ne na yau da kullum ba tare da tsayayyen tsarin baiti ba, waka kuwa tana da tsari na baiti da amsa-amo",
      "Prose (zube) is written in ordinary continuous sentences without a fixed verse structure, whereas poetry (waka) follows structured stanzas and rhyme."),
  _q("Wace muhimmiyar rawa ce mujallar 'Gaskiya Ta Fi Kwabo' ta taka a bunkasar adabin Hausa na zamani?",
      ["Ta ba da dama ga marubuta su buga labarai da rubuce-rubuce na Hausa a rubuce", "Ta hana rubuta Hausa gaba daya", "Ta koyar da harshen Faransanci", "Ba ta da wata alaka da adabi"], "Ta ba da dama ga marubuta su buga labarai da rubuce-rubuce na Hausa a rubuce",
      "Gaskiya Ta Fi Kwabo, a pioneering Hausa-language newspaper, provided an important early platform for published Hausa writing and literary development."),
  _q("A ra'ayin gama-gari, menene babban jigon da yawancin litattafan Hausa na farko-farko suka fi mayar da hankali a kai?",
      ["Ilmantarwa da fadakarwa game da zamantakewar al'umma", "Kimiyyar sararin samaniya kadai", "Fasahar kere-kere ta zamani kadai", "Tarihin kasashen waje kadai"], "Ilmantarwa da fadakarwa game da zamantakewar al'umma",
      "Early Hausa novels commonly centred on social education and moral instruction relevant to the community, reflecting their didactic purpose."),
  _q("Wanne fanni ne ake kira nazarin marubuta da ayyukansu a tarihin adabin Hausa?",
      ["Tarihin adabi (literary history)", "Tsarin sauti", "Ka'idojin rubutu", "Gidajen kalmomi"], "Tarihin adabi (literary history)",
      "Literary history is the study concerned with tracing writers, their works, and the development of a literary tradition over time."),
  _q("Menene ake kira nau'in labari mai tsawo, cike da hadaddiyar makirci da yawan haruffa, a rubutaccen adabin Hausa?",
      ["Littafi/Novel", "Kacici-kacici", "Kirari", "Waka gajera kadai"], "Littafi/Novel",
      "A novel is a long-form narrative work featuring complex plot and multiple characters, distinguished from shorter oral forms like riddles."),
  _q("Me ya sa nazarin rubutaccen adabin Hausa a matakin Post-UTME/JAMB ke bukatar sanin marubuta a matakin gama-gari maimakon dukkan cikakkun bayanan labarin kowane littafi?",
      ["Domin auna ilimin dalibi game da muhimman marubuta da gudummawarsu ba tare da bukatar haddace kowane karamin bayani ba", "Domin babu wani marubuci da aka sani a Hausa", "Domin littattafai ba su da amfani a jarabawa", "Domin a guji koyar da adabi gaba daya"], "Domin auna ilimin dalibi game da muhimman marubuta da gudummawarsu ba tare da bukatar haddace kowane karamin bayani ba",
      "General-level literary knowledge — recognising key authors and their significance — is typically what is assessed, rather than exhaustive plot memorisation."),
];

final _alada = [
  _q("Menene ake kira babban bikin da ake yi domin murnar kammala azumin Ramadan a al'adar Hausawa musulmi?",
      ["Sallah Karama (Idil Fitr)", "Bikin Gani", "Bikin Sharo", "Bikin Kalankuwa"], "Sallah Karama (Idil Fitr)",
      "Sallah Karama, corresponding to Eid al-Fitr, marks the end of the Ramadan fast and is celebrated widely among Hausa Muslims."),
  _q("A al'adar Hausa, menene ake kira gasar da matasa maza ke shiga domin nuna karfin jiki ta hanyar dukan juna da sanda?",
      ["Sharo", "Kokawa kadai", "Dambe kadai", "Wasan gargajiya na mata"], "Sharo",
      "Sharo is a traditional Fulani/Hausa-associated endurance contest in which young men are struck with canes to demonstrate bravery, often as a rite of passage."),
  _q("Wace irin dabi'a ake sa ran mace ta nuna a gargajiyar Hausa da ake kira 'kunya'?",
      ["Ladabi, tawali'u, da girmama sauran mutane", "Rashin ladabi da yawan magana", "Fadan bayyane da makwabta", "Nuna girman kai"], "Ladabi, tawali'u, da girmama sauran mutane",
      "'Kunya' in Hausa cultural context refers to modesty, humility, and respectful decorum expected in social conduct."),
  _q("Menene ake kira gyaran gargajiya na kayan ado na mata a al'adar Hausa, wanda ya kunshi zanen hannu da lele da lalle?",
      ["Kayan ado na gargajiya (kamar lalle)", "Kayan aikin gona", "Kayan yaki", "Kayan sana'ar kere-kere"], "Kayan ado na gargajiya (kamar lalle)",
      "Traditional adornments such as henna (lalle) designs are a well-known aspect of Hausa women's cultural beautification practices."),
  _q("A al'adar Hausa, menene rawar 'Sarki' a tsarin mulkin gargajiya?",
      ["Shugaban gargajiya da ke kula da al'amuran al'umma da tsare al'ada", "Malamin makaranta kadai", "Ma'aikacin banki", "Dan kasuwa kadai"], "Shugaban gargajiya da ke kula da al'amuran al'umma da tsare al'ada",
      "The Sarki (traditional ruler/emir) serves as a customary leader overseeing communal affairs and preserving cultural traditions."),
  _q("Menene ake kira sana'ar gargajiya ta kera kayan aiki da kayan ado daga karafa a al'adar Hausa?",
      ["Kira/Ƙirƙin ƙarfe (blacksmithing)", "Rini kadai", "Saka kadai", "Noma kadai"], "Kira/Ƙirƙin ƙarfe (blacksmithing)",
      "Blacksmithing is a longstanding traditional craft among the Hausa, producing tools, farming implements, and metal ornaments."),
  _q("Menene ake kira sana'ar gargajiya ta rina tufafi domin samar da launi, wadda birnin Kano ya shahara da ita?",
      ["Rini (dyeing)", "Kira", "Sassaka", "Kiwo"], "Rini (dyeing)",
      "Kano is historically famous for its indigo dye pits, a traditional craft of dyeing cloth used to produce distinctive coloured fabrics."),
  _q("A al'adar Hausa, menene manufar bikin suna da ake yi wa jariri kwana bakwai bayan haihuwa?",
      ["Ba jaririn suna a hukumance tare da yin addu'o'i", "Nuna wa jama'a arzikin iyaye kadai", "Bikin girbi ne", "Bikin aure ne"], "Ba jaririn suna a hukumance tare da yin addu'o'i",
      "The naming ceremony (suna), typically held seven days after birth, formally names the child and includes prayers and blessings."),
  _q("Menene ake kira sanannen abincin gargajiya na Hausa da aka fi sani da shi, wanda ake yi da hatsi kamar dawa ko gero?",
      ["Tuwo", "Suya kadai", "Kilishi kadai", "Fura da nono"], "Tuwo",
      "Tuwo, a thick porridge typically made from grains such as guinea corn or millet, is a staple traditional Hausa dish, often served with soup."),
  _q("A al'adar Hausa, menene babban dalilin gudanar da 'kalankuwa', wani biki na gargajiya bayan girbi?",
      ["Nuna godiya bayan an gama girbi tare da nishadantar da al'umma", "Fara noma sabon lokaci", "Yin makoki", "Fara sabon shekara ta Musulunci kadai"], "Nuna godiya bayan an gama girbi tare da nishadantar da al'umma",
      "Kalankuwa is a traditional post-harvest festival celebrating a successful farming season and giving thanks, while entertaining the community."),
  _q("Menene rawar da dattawa (elders) ke takawa a warware rikice-rikice a al'adar Hausa ta gargajiya?",
      ["Suna zama alkalai na gargajiya wajen sasanta sabani cikin hikima", "Ba su da wata rawa a warware rikici", "Su ne kadai ke da hakkin yin sana'a", "Suna kula da makarantu kadai"], "Suna zama alkalai na gargajiya wajen sasanta sabani cikin hikima",
      "Elders traditionally play a respected mediating role, using wisdom and social standing to resolve disputes within the community."),
  _q("Menene ake kira gargajiyar Hausawa ta gaisuwa da rungumar juna tsakanin tsofaffi da matasa domin nuna girmamawa?",
      ["Gaisuwa da ladabi (greeting etiquette)", "Rashin gaisuwa", "Fadar magana ba tare da gaisuwa ba", "Kin amincewa da girmamawa"], "Gaisuwa da ladabi (greeting etiquette)",
      "Elaborate, respectful greeting customs — differing by age and status — are a core feature of Hausa social etiquette."),
  _q("Menene ake kira kayan kide-kide na gargajiya na Hausa wanda ake amfani da fata domin samar da sauti, kuma ana amfani da shi wajen yabon sarki?",
      ["Tambari/Ganga (drum)", "Goge kadai", "Kuntigi kadai", "Algaita ba ta amfani da fata"], "Tambari/Ganga (drum)",
      "Traditional drums (such as tambari and ganga), made using stretched skins/hides, are commonly used in royal praise music and ceremonies."),
  _q("A al'adar Hausa, wace kalma ce ake amfani da ita domin nuna hadin kan iyali fadada wanda ya hada da kakanni, iyaye, da 'ya'ya?",
      ["Iyali/Dangi", "Kasuwa", "Majalisa", "Kungiya"], "Iyali/Dangi",
      "'Dangi' or 'iyali' refers to the extended family unit central to Hausa social organisation, including grandparents, parents, and children."),
  _q("Menene ake kira sana'ar gargajiya ta saka tufafi da kayan gida daga zaren auduga a al'adar Hausa?",
      ["Saka (weaving)", "Kira", "Noma kadai", "Kamun kifi kadai"], "Saka (weaving)",
      "Weaving (saka) using cotton thread to produce cloth and household items is a well-established traditional Hausa craft."),
  _q("Menene ake kira sana'ar gargajiya ta kira baƙin ƙarfe don yin kayan aiki a al'adar Hausa?",
      ["Kira (blacksmithing)", "Saƙa", "Rini", "Sassaka kawai"], "Kira (blacksmithing)",
      "Blacksmithing (kira) has traditionally been an important craft in Hausa society, producing farming tools and implements."),
  _q("A al'adar Hausa, menene ake kira sana'ar rini na gargajiya da ake yi domin canza launin tufafi?",
      ["Rini (dyeing)", "Kira", "Saƙa kawai", "Noma"], "Rini (dyeing)",
      "Traditional dyeing (rini), especially of indigo cloth, is a well-known craft associated with Hausa cities like Kano."),
  _q("Menene ake kira taron gargajiya na jama'a domin tattaunawa kan al'amuran al'umma a ƙarƙashin jagorancin sarki ko hakimi?",
      ["Majalisa/taro (council/assembly)", "Kasuwa", "Bikin aure", "Wasan kwaikwayo"], "Majalisa/taro (council/assembly)",
      "Traditional councils or assemblies (majalisa) convened under a chief or emir served as forums for community deliberation."),
];
