import "../quiz_question.dart";

const _subject = "Arabic";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// Obafemi Awolowo University (OAU) Post-UTME Arabic elective bank — 100
/// questions covering the five areas typically drawn on by Nigerian
/// Post-UTME/JAMB-style Arabic screening: Comprehension (المطالعة),
/// Translation (الترجمة), Grammar and Structure (النحو والصرف), Composition
/// (الإنشاء), and Arabic Literature (الأدب العربي). Literary-history
/// questions are kept at general/author-level (periods, honorifics,
/// well-known works) rather than fine-grained classical text analysis. This
/// is a general-purpose practice set, not an official OAU past-question
/// paper.
List<QuizQuestion> buildOauArabicQuestions() {
  return [
    ..._comprehension,
    ..._translation,
    ..._grammarAndStructure,
    ..._composition,
    ..._arabicLiterature,
  ];
}

const _passage =
    "سافرت ليلى إلى مدينة القاهرة لزيارة جدتها في العطلة الصيفية. استقلت الطائرة من لاغوس، ووصلت بعد رحلة "
    "طويلة. أعجبها جمال المدينة القديمة وأسواقها المزدحمة. زارت الأهرامات مع أبناء عمها، والتقطت صوراً كثيرة. "
    "في المساء، جلست مع جدتها تستمع إلى قصص عن الماضي وتتذوق الطعام المصري التقليدي. عادت ليلى إلى بلدها بعد "
    "أسبوعين، وهي تحمل ذكريات جميلة وهدايا لأسرتها.";

QuizQuestion _cq(String question, List<String> options, String correct, String explanation) {
  return _q("$_passage\n\n$question", options, correct, explanation);
}

final _comprehension = [
  _cq("لماذا سافرت ليلى إلى القاهرة؟",
      ["لزيارة جدتها في العطلة الصيفية", "للدراسة في جامعة هناك", "للعمل في شركة", "لحضور مؤتمر طبي"],
      "لزيارة جدتها في العطلة الصيفية",
      "The passage states Layla travelled 'لزيارة جدتها في العطلة الصيفية' (to visit her grandmother during the summer holiday)."),
  _cq("كيف سافرت ليلى إلى القاهرة؟",
      ["استقلت الطائرة", "سافرت بالسيارة", "ركبت القطار", "سارت على الأقدام"],
      "استقلت الطائرة",
      "The text says 'استقلت الطائرة من لاغوس' (she took the plane from Lagos), indicating her mode of travel."),
  _cq("من أين انطلقت رحلة ليلى؟",
      ["من لاغوس", "من أبوجا", "من كانو", "من إبادان"],
      "من لاغوس",
      "The passage specifies the flight departed 'من لاغوس' (from Lagos)."),
  _cq("ماذا أعجب ليلى في القاهرة؟",
      ["جمال المدينة القديمة وأسواقها المزدحمة", "الطقس البارد فقط", "قلة السكان", "غياب الأسواق"],
      "جمال المدينة القديمة وأسواقها المزدحمة",
      "The passage states 'أعجبها جمال المدينة القديمة وأسواقها المزدحمة' (she was impressed by the beauty of the old city and its crowded markets)."),
  _cq("مع من زارت ليلى الأهرامات؟",
      ["مع أبناء عمها", "وحدها", "مع معلمتها", "مع جيرانها"],
      "مع أبناء عمها",
      "The text says she visited the pyramids 'مع أبناء عمها' (with her cousins)."),
  _cq("ماذا فعلت ليلى أثناء زيارتها للأهرامات؟",
      ["التقطت صوراً كثيرة", "باعت هدايا", "كتبت رسالة", "نامت طوال اليوم"],
      "التقطت صوراً كثيرة",
      "The passage notes she 'التقطت صوراً كثيرة' (took many photos) during the pyramid visit."),
  _cq("ماذا فعلت ليلى مساءً مع جدتها؟",
      ["استمعت إلى قصص عن الماضي وتذوقت الطعام المصري", "ذهبت إلى السينما", "لعبت كرة القدم", "ذهبت إلى المدرسة"],
      "استمعت إلى قصص عن الماضي وتذوقت الطعام المصري",
      "In the evening she 'تستمع إلى قصص عن الماضي وتتذوق الطعام المصري التقليدي' (listened to stories of the past and tasted traditional Egyptian food)."),
  _cq("متى عادت ليلى إلى بلدها؟",
      ["بعد أسبوعين", "بعد يوم واحد", "بعد شهر", "بعد سنة"],
      "بعد أسبوعين",
      "The passage states she returned 'بعد أسبوعين' (after two weeks)."),
  _cq("ماذا كانت تحمل ليلى عند عودتها؟",
      ["ذكريات جميلة وهدايا لأسرتها", "لا شيء", "أموالاً كثيرة فقط", "كتباً مدرسية فقط"],
      "ذكريات جميلة وهدايا لأسرتها",
      "The text ends by noting she returned 'وهي تحمل ذكريات جميلة وهدايا لأسرتها' (carrying beautiful memories and gifts for her family)."),
  _cq("ما الفكرة العامة للنص؟",
      ["وصف رحلة صيفية ممتعة لزيارة الأقارب", "قصة عن حرب قديمة", "وصف مباراة رياضية", "حديث عن مشروع تجاري"],
      "وصف رحلة صيفية ممتعة لزيارة الأقارب",
      "The passage as a whole describes an enjoyable summer trip to visit relatives in Cairo, making this the general theme."),
  _cq("ما معنى كلمة 'المزدحمة' كما وردت في النص؟",
      ["المليئة بالناس", "الفارغة تماماً", "الهادئة جداً", "النظيفة"],
      "المليئة بالناس",
      "In context, 'المزدحمة' (crowded) describes markets full of people, i.e. 'المليئة بالناس'."),
  _cq("ماذا نستنتج عن علاقة ليلى بجدتها من النص؟",
      ["علاقة قوية ومحبة", "علاقة متوترة", "لا توجد علاقة بينهما", "علاقة عابرة فقط"],
      "علاقة قوية ومحبة",
      "Layla travelling to visit her grandmother and spending evenings listening to her stories suggests a close, affectionate relationship."),
];

final _translation = [
  _q("Turn to Arabic: 'The teacher explained the lesson clearly.'",
      ["المعلم شرح الدرس بوضوح", "الطالب كتب الواجب", "المعلمة قرأت القصة", "الأب أصلح السيارة"],
      "المعلم شرح الدرس بوضوح",
      "'The teacher explained the lesson clearly' is rendered as 'المعلم شرح الدرس بوضوح', using شرح (explained) and بوضوح (clearly)."),
  _q("Turn to Arabic: 'My brother works in a hospital.'",
      ["أخي يعمل في مستشفى", "أختي تدرس في الجامعة", "أخي يسكن في القرية", "صديقي يعمل في مصنع"],
      "أخي يعمل في مستشفى",
      "'My brother works in a hospital' becomes 'أخي يعمل في مستشفى', with أخي (my brother), يعمل (works), and مستشفى (hospital)."),
  _q("Turn to Arabic: 'The children are playing in the garden.'",
      ["الأطفال يلعبون في الحديقة", "الرجال يعملون في المزرعة", "البنات يقرأن في المكتبة", "الطلاب ينامون في الفصل"],
      "الأطفال يلعبون في الحديقة",
      "'The children are playing in the garden' translates as 'الأطفال يلعبون في الحديقة', using the plural verb يلعبون (they play) with الأطفال (the children)."),
  _q("Turn to Arabic: 'I bought two new books yesterday.'",
      ["اشتريتُ كتابين جديدين أمس", "بعتُ كتاباً قديماً اليوم", "قرأتُ ثلاثة كتب أمس", "كتبتُ رسالة أمس"],
      "اشتريتُ كتابين جديدين أمس",
      "'I bought two new books yesterday' is rendered as 'اشتريتُ كتابين جديدين أمس', using the dual form كتابين (two books) with أمس (yesterday)."),
  _q("Turn to Arabic: 'She will visit her uncle next month.'",
      ["ستزور عمها الشهر القادم", "زارت عمها الشهر الماضي", "تزور عمها كل شهر", "سيزور عمه غداً"],
      "ستزور عمها الشهر القادم",
      "'She will visit her uncle next month' becomes 'ستزور عمها الشهر القادم', using the future prefix 'سـ' with تزور (she visits)."),
  _q("Turn to Arabic: 'These students are diligent and honest.'",
      ["هؤلاء الطلاب مجتهدون وصادقون", "هذا الطالب كسول وكاذب", "هاتان الطالبتان مجتهدتان", "أولئك المعلمون كرماء"],
      "هؤلاء الطلاب مجتهدون وصادقون",
      "'These students are diligent and honest' translates as 'هؤلاء الطلاب مجتهدون وصادقون', using the plural demonstrative هؤلاء with the plural adjectives مجتهدون and صادقون."),
  _q("Turn to Arabic: 'Where is the nearest mosque?'",
      ["أين أقرب مسجد؟", "متى يفتح المسجد؟", "من بنى هذا المسجد؟", "كم مسجداً في المدينة؟"],
      "أين أقرب مسجد؟",
      "'Where is the nearest mosque?' is correctly rendered as 'أين أقرب مسجد؟', using the interrogative أين (where)."),
  _q("Turn to Arabic: 'We studied Arabic grammar for two hours.'",
      ["درسنا النحو العربي لمدة ساعتين", "درسنا الرياضيات لمدة ساعة", "درسوا التاريخ طوال اليوم", "درست العربية أمس فقط"],
      "درسنا النحو العربي لمدة ساعتين",
      "'We studied Arabic grammar for two hours' becomes 'درسنا النحو العربي لمدة ساعتين', using درسنا (we studied) and the dual ساعتين (two hours)."),
  _q("Turn to English: 'اشترى التاجر بضاعة جديدة من السوق.'",
      ["The merchant bought new goods from the market", "The farmer sold his crops at the market", "The teacher bought books from the shop", "The boy lost his money in the market"],
      "The merchant bought new goods from the market",
      "'اشترى التاجر بضاعة جديدة من السوق' translates as 'The merchant bought new goods from the market', with التاجر (the merchant) and بضاعة جديدة (new goods)."),
  _q("Turn to English: 'تفتح المكتبة أبوابها في الساعة الثامنة صباحاً.'",
      ["The library opens its doors at eight o'clock in the morning", "The library closes at eight in the evening", "The school opens at seven in the morning", "The market closes at eight at night"],
      "The library opens its doors at eight o'clock in the morning",
      "'تفتح المكتبة أبوابها في الساعة الثامنة صباحاً' translates as 'The library opens its doors at eight o'clock in the morning', using تفتح (opens) and صباحاً (in the morning)."),
  _q("Turn to English: 'يحرص الطلاب على حضور الدروس في وقتها.'",
      ["The students are keen to attend lessons on time", "The students often skip their lessons", "The teachers arrive late every day", "The students dislike attending school"],
      "The students are keen to attend lessons on time",
      "'يحرص الطلاب على حضور الدروس في وقتها' translates as 'The students are keen to attend lessons on time', with يحرص على meaning 'is keen on/careful about'."),
  _q("Turn to English: 'زارنا ضيوف كرام من مصر الأسبوع الماضي.'",
      ["Honoured guests from Egypt visited us last week", "We will visit Egypt next week", "Our neighbours travelled to Egypt yesterday", "No guests visited us this year"],
      "Honoured guests from Egypt visited us last week",
      "'زارنا ضيوف كرام من مصر الأسبوع الماضي' translates as 'Honoured guests from Egypt visited us last week', with ضيوف كرام meaning 'honoured/generous guests'."),
  _q("Turn to English: 'يجب على الطالب أن يحترم معلمه.'",
      ["The student must respect his teacher", "The teacher must obey the student", "The student refuses to attend class", "The teacher dislikes his students"],
      "The student must respect his teacher",
      "'يجب على الطالب أن يحترم معلمه' translates as 'The student must respect his teacher', using يجب على (it is obligatory upon) and يحترم (respects)."),
  _q("Turn to English: 'ارتفعت أسعار السلع في الأسواق مؤخراً.'",
      ["The prices of goods have recently risen in the markets", "The prices of goods have fallen sharply", "The markets have been closed recently", "Goods have disappeared from the markets"],
      "The prices of goods have recently risen in the markets",
      "'ارتفعت أسعار السلع في الأسواق مؤخراً' translates as 'The prices of goods have recently risen in the markets', with ارتفعت meaning 'rose/increased'."),
  _q("Turn to English: 'كتب الطالب اسمه على الورقة بخط جميل.'",
      ["The student wrote his name on the paper in beautiful handwriting", "The teacher erased the student's name", "The student tore up the paper", "The student forgot to write his name"],
      "The student wrote his name on the paper in beautiful handwriting",
      "'كتب الطالب اسمه على الورقة بخط جميل' translates as 'The student wrote his name on the paper in beautiful handwriting', with بخط جميل meaning 'in beautiful handwriting'."),
  _q("Turn to English: 'لا يستطيع الإنسان أن يعيش بمفرده تماماً.'",
      ["A human being cannot live entirely alone", "A human being prefers to live alone", "Animals cannot survive without humans", "Humans always live in large cities"],
      "A human being cannot live entirely alone",
      "'لا يستطيع الإنسان أن يعيش بمفرده تماماً' translates as 'A human being cannot live entirely alone', with لا يستطيع meaning 'cannot' and بمفرده تماماً meaning 'entirely alone'."),
];

final _grammarAndStructure = [
  _q("Which of the following is the standard Arabic grammatical term for a verb, a word denoting an action tied to a specific tense?",
      ["فعل", "اسم", "حرف", "ضمير"], "فعل",
      "A verb (فعل) denotes an action or event linked to a particular tense (past, present, or imperative), unlike اسم (noun) or حرف (particle)."),
  _q("A particle (حرف) in Arabic grammar is best described as a word that",
      ["has no independent meaning except in relation to other words, such as prepositions and conjunctions", "always names a person or object", "always denotes a completed action", "is always used as the subject of a sentence"],
      "has no independent meaning except in relation to other words, such as prepositions and conjunctions",
      "Particles (حروف) such as prepositions and conjunctions carry meaning only in relation to the words they connect, unlike independent nouns or verbs."),
  _q("The diminutive form (اسم التصغير) in Arabic, such as كُتَيِّب from كِتَاب, is typically used to indicate",
      ["smallness, endearment, or a lesser degree of something", "the plural of a noun", "the comparative degree of an adjective", "a completed past action"],
      "smallness, endearment, or a lesser degree of something",
      "The diminutive pattern (تصغير) modifies a noun's form to convey smallness, affection, or a lesser degree, as in كُتَيِّب (small book/booklet) from كِتَاب."),
  _q("The active participle (اسم الفاعل), such as كَاتِب (writer/writing) from كَتَبَ, denotes",
      ["the doer of an action", "the receiver of an action", "the tool used to perform an action", "the place where an action occurs"],
      "the doer of an action",
      "The active participle (اسم الفاعل) refers to the one performing an action, such as كَاتِب (one who writes), derived from the verb كَتَبَ."),
  _q("The passive participle (اسم المفعول), such as مَكْتُوب (written) from كَتَبَ, denotes",
      ["the receiver or object of an action", "the doer of an action", "the time of an action", "a comparative quality"],
      "the receiver or object of an action",
      "The passive participle (اسم المفعول) refers to that upon which an action is performed, such as مَكْتُوب (something written)."),
  _q("The verbal noun (المصدر), such as كِتَابَة (writing) from كَتَبَ, is best described as",
      ["a noun expressing the abstract action or meaning of a verb, without reference to tense", "a noun referring only to a physical object", "a form used exclusively for commands", "a plural noun form"],
      "a noun expressing the abstract action or meaning of a verb, without reference to tense",
      "The masdar (مصدر) captures the pure abstract meaning of a verb's action, such as كِتَابَة (writing), independent of any particular tense."),
  _q("The elative/comparative form (اسم التفضيل), such as أَكْبَر (bigger/biggest) from كَبِير, is generally used to express",
      ["a comparison or superlative degree of a quality", "a simple plural of an adjective", "a diminutive form of a noun", "a passive action"],
      "a comparison or superlative degree of a quality",
      "The elative pattern (أَفْعَل) expresses a comparative or superlative degree of a quality, as in أَكْبَر (bigger/biggest) from كَبِير (big)."),
  _q("The vocative particle يا in Arabic, as in 'يا أحمد', is used to",
      ["call or address someone directly", "negate a verb", "ask a question", "indicate possession"],
      "call or address someone directly",
      "يا is the standard vocative particle used to directly call or address a person, as in 'يا أحمد' (O Ahmad)."),
  _q("The exception particle إلا in a sentence such as 'حضر الطلاب إلا واحداً' functions to",
      ["exclude a specific item or person from a general statement", "emphasise the entire group without exception", "negate the whole sentence", "form a question about the group"],
      "exclude a specific item or person from a general statement",
      "إلا introduces an exception, excluding a specific person or item from an otherwise general statement, as in 'the students attended except one'."),
  _q("Which of the following is a common interrogative particle used to introduce a yes/no question in Arabic?",
      ["هل", "لن", "قد", "لو"], "هل",
      "هل is a standard particle placed at the start of a sentence to form a yes/no question in Arabic."),
  _q("The conjunction و ('and') in Arabic grammar is generally used to",
      ["link two words, phrases, or clauses of similar grammatical status", "negate the sentence that follows", "introduce a conditional clause", "mark the end of a sentence"],
      "link two words, phrases, or clauses of similar grammatical status",
      "و functions as a coordinating conjunction, joining words, phrases, or clauses of equivalent grammatical function."),
  _q("In the nominal sentence 'الكتابُ مفيدٌ' (The book is useful), the subject (مبتدأ) 'الكتابُ' takes which case ending?",
      ["Nominative (الرفع)", "Accusative (النصب)", "Genitive (الجر)", "Jussive (الجزم)"], "Nominative (الرفع)",
      "The subject (مبتدأ) of a nominal sentence is marked with the nominative case (رفع), as shown by the damma ending on الكتابُ."),
  _q("In the verbal sentence 'قرأ الطالبُ الكتابَ' (The student read the book), the doer 'الطالبُ' (subject/فاعل) takes which case ending?",
      ["Nominative (الرفع)", "Accusative (النصب)", "Genitive (الجر)", "Jussive (الجزم)"], "Nominative (الرفع)",
      "The doer of a verbal sentence (الفاعل) is always in the nominative case (رفع), regardless of the verb's tense."),
  _q("In the sentence 'قرأ الطالبُ الكتابَ', the word 'الكتابَ', functioning as the direct object (مفعول به), takes which case ending?",
      ["Accusative (النصب)", "Nominative (الرفع)", "Genitive (الجر)", "Jussive (الجزم)"], "Accusative (النصب)",
      "The direct object (مفعول به) of a transitive verb is marked with the accusative case (نصب), as shown by the fatha ending on الكتابَ."),
  _q("In an idafa (إضافة) construction such as 'مكتبةُ الجامعةِ' (the university's library), the second noun (المضاف إليه) always takes which case?",
      ["Genitive (الجر)", "Nominative (الرفع)", "Accusative (النصب)", "No fixed case is required"], "Genitive (الجر)",
      "The second noun in an idafa construction (المضاف إليه) is always in the genitive case (جر), regardless of the case of the first noun."),
  _q("The five nouns (الأسماء الخمسة), such as أخ (brother) and ذو (possessor of), take the long vowel و for the nominative case specifically when",
      ["they are attached to another noun in an idafa construction (other than the first-person singular pronoun)", "they stand alone without any idafa relationship", "they are made plural", "they are used in a question"],
      "they are attached to another noun in an idafa construction (other than the first-person singular pronoun)",
      "The special declension of the five nouns, using long vowels for case endings, applies specifically when they occur as the first term of an idafa construction, excluding the my/I possessive suffix."),
  _q("The particle ليس (laysa), similar in function to كان, is grammatically notable because it",
      ["negates a nominal sentence, keeping the subject nominative while making the predicate accusative", "is used only to form questions", "always requires a plural subject", "marks a verb as being in the past tense only"],
      "negates a nominal sentence, keeping the subject nominative while making the predicate accusative",
      "ليس negates a nominal (equational) sentence in the present, functioning like كان's sisters: the subject stays nominative while the predicate becomes accusative."),
  _q("Emphasis (توكيد) in Arabic grammar, using words such as نفس or عين, is generally used to",
      ["reinforce or stress the identity of a preceding noun", "negate the preceding statement", "introduce a new, unrelated topic", "form the plural of a preceding noun"],
      "reinforce or stress the identity of a preceding noun",
      "Emphatic words such as نفس/عين (self/very) are added after a noun to reinforce and stress its identity, such as 'جاء الرئيس نفسه' (the president himself came)."),
  _q("Apposition (البدل) in Arabic grammar refers to a noun that",
      ["follows another noun to further clarify or specify it, sharing the same grammatical case", "always negates the preceding noun", "is only used with verbs, never nouns", "always appears in the plural form"],
      "follows another noun to further clarify or specify it, sharing the same grammatical case",
      "A badal (بدل) is a noun placed after another noun to further identify or explain it, agreeing in case with the noun it follows."),
  _q("An adjective (نعت/صفة) in Arabic must agree with the noun it describes in",
      ["gender, number, case, and definiteness", "meaning only, with no grammatical agreement required", "tense alone", "person only, as with verbs"],
      "gender, number, case, and definiteness",
      "Arabic adjectives (نعت) must fully agree with the nouns they modify in gender, number, grammatical case, and definiteness."),
  _q("A simple comparative sentence in Arabic, such as 'محمد أطول من علي' (Muhammad is taller than Ali), typically uses the preposition",
      ["من (than)", "في (in)", "على (on)", "إلى (to)"], "من (than)",
      "من is the standard preposition used after an elative/comparative adjective to introduce the object of comparison, meaning 'than'."),
  _q("The interrogative particle كيف in Arabic is used to ask about",
      ["manner or condition (how)", "time (when)", "place (where)", "reason (why)"], "manner or condition (how)",
      "كيف is used to ask about the manner or condition of something, equivalent to 'how' in English."),
  _q("The interrogative particle متى in Arabic is used to ask about",
      ["time (when)", "manner (how)", "place (where)", "identity (who)"], "time (when)",
      "متى asks about time, equivalent to 'when' in English."),
  _q("The interrogative particle أين in Arabic is used to ask about",
      ["place (where)", "time (when)", "reason (why)", "quantity (how much)"], "place (where)",
      "أين asks about location, equivalent to 'where' in English."),
  _q("The interrogative particle لماذا in Arabic is used to ask about",
      ["reason or cause (why)", "place (where)", "manner (how)", "identity (who)"], "reason or cause (why)",
      "لماذا asks about reason or cause, equivalent to 'why' in English."),
  _q("The interrogative pronoun من in Arabic is used to ask about",
      ["a person's identity (who)", "an object or thing (what)", "a place (where)", "a quantity (how many)"], "a person's identity (who)",
      "من is used to ask about a person's identity, equivalent to 'who' in English."),
  _q("The interrogative pronoun ماذا in Arabic is used to ask about",
      ["a thing or object (what)", "a person's identity (who)", "a specific time (when)", "a specific place (where)"], "a thing or object (what)",
      "ماذا is used to ask about a thing or an action, equivalent to 'what' in English."),
  _q("In Arabic, the definite article ال is described as 'شمسية' (sun letter) when the following consonant",
      ["assimilates the ل sound, so it is not pronounced, e.g. الشمس", "is always pronounced clearly alongside the ل", "is dropped entirely from the word", "changes the noun into a verb"],
      "assimilates the ل sound, so it is not pronounced, e.g. الشمس",
      "With sun letters (حروف شمسية), the ل of ال assimilates into the following consonant, which is instead doubled in pronunciation, as in 'الشمس' pronounced 'ash-shams'."),
  _q("Hamzat al-wasl (همزة الوصل), unlike hamzat al-qat' (همزة القطع), is generally",
      ["pronounced only at the beginning of an utterance and dropped when preceded by another word", "always pronounced regardless of its position in a sentence", "never written in Arabic script", "used only in verbs of Form I"],
      "pronounced only at the beginning of an utterance and dropped when preceded by another word",
      "Hamzat al-wasl is a connecting hamza pronounced only when starting an utterance; when preceded by another word, it elides in continuous speech."),
  _q("Tanwin (التنوين), the doubled vowel marking seen at the end of many indefinite nouns, primarily serves to indicate",
      ["that a noun is indefinite (nakirah)", "that a noun is definite (ma'rifah)", "that a word is a verb", "that a sentence is a question"],
      "that a noun is indefinite (nakirah)",
      "Tanwin, the doubled short-vowel ending, marks a noun as indefinite (نكرة), distinguishing it from a definite noun, which typically lacks tanwin."),
  _q("The diacritical mark sukun (السكون), placed over a consonant, indicates that the consonant",
      ["is not followed by any vowel sound", "is doubled in pronunciation", "is followed by a long vowel", "marks the noun as plural"],
      "is not followed by any vowel sound",
      "Sukun (ْ) marks a consonant as having no following vowel, meaning it is pronounced without any accompanying short vowel."),
  _q("The shadda (الشدة) mark placed over a consonant in Arabic indicates that the consonant is",
      ["doubled or geminated in pronunciation", "silent and not pronounced", "always the final letter of a plural", "used only in loanwords"],
      "doubled or geminated in pronunciation",
      "Shadda (ّ) indicates that a consonant is doubled (geminated), effectively pronounced twice in succession."),
  _q("Most Arabic words are traditionally analysed as being built from a root of how many consonants, in the majority of cases?",
      ["Three (a triliteral root, الجذر الثلاثي)", "Five", "Two", "Seven"], "Three (a triliteral root, الجذر الثلاثي)",
      "The great majority of Arabic words derive from a triliteral root (جذر ثلاثي) of three consonants, from which various patterns and derived forms are built."),
  _q("The derived verb Form II (فَعَّل), formed by doubling the middle root letter, most commonly conveys which added meaning compared to Form I?",
      ["A causative meaning (making someone do something)", "A reciprocal meaning between two parties", "A passive meaning only", "A meaning of seeking or requesting"],
      "A causative meaning (making someone do something)",
      "Form II (فَعَّل), marked by doubling the middle root consonant, most commonly adds a causative sense, as in عَلَّم (to teach/cause to know) from عَلِمَ (to know)."),
  _q("The derived verb Form III (فَاعَل), formed by adding a long vowel after the first root letter, commonly conveys which meaning?",
      ["An action performed with or towards another party, often reciprocal effort", "A purely passive meaning", "A diminutive meaning", "A meaning restricted to commands only"],
      "An action performed with or towards another party, often reciprocal effort",
      "Form III (فَاعَل) typically conveys an action directed towards or shared with another party, often implying reciprocal effort, as in كَاتَب (to correspond with)."),
  _q("The derived verb Form X (اِسْتَفْعَل) commonly conveys which added meaning compared to the basic Form I verb?",
      ["Seeking or requesting the action or quality of the root", "A simple negation of the root meaning", "An exclusively plural subject", "A meaning restricted to the dual form"],
      "Seeking or requesting the action or quality of the root",
      "Form X (اِسْتَفْعَل) commonly adds a sense of seeking, requesting, or considering something to have the root's quality, as in اِسْتَغْفَرَ (to seek forgiveness)."),
  _q("Which of the following is an example of a broken plural following the أَفْعَال pattern?",
      ["أَقْلَام (pens, from قَلَم)", "مُعَلِّمُون (teachers)", "مُسْلِمَات (Muslim women)", "طَالِبَتَان (two female students)"], "أَقْلَام (pens, from قَلَم)",
      "أَقْلَام follows the common broken-plural pattern أَفْعَال, formed through an internal vowel change from the singular قَلَم, unlike the sound plurals and dual forms listed."),
  _q("A diptote noun (الممنوع من الصرف) in Arabic grammar is one that",
      ["does not take tanwin and uses only two case-vowel endings instead of the usual three", "always takes tanwin regardless of context", "is always a verb rather than a noun", "can only appear in the dual form"],
      "does not take tanwin and uses only two case-vowel endings instead of the usual three",
      "Diptote nouns (ممنوع من الصرف) do not accept tanwin and are marked with only a damma (nominative) or a fatha (accusative/genitive), unlike fully declinable (triptote) nouns."),
  _q("The typical, most common word order in a Standard Arabic verbal sentence is",
      ["Verb-Subject-Object (VSO)", "Subject-Verb-Object (SVO) exclusively, with VSO forbidden", "Object-Subject-Verb (OSV) exclusively", "There is no typical word order in Arabic"],
      "Verb-Subject-Object (VSO)", "Standard Arabic verbal sentences typically follow a Verb-Subject-Object (VSO) order, e.g. 'قرأ الطالبُ الكتابَ' (the student read the book), literally 'read the-student the-book'."),
  _q("In Arabic grammar, a sentence beginning with the object rather than the subject or verb, for emphasis, is an example of",
      ["a fronted/preposed complement used for stylistic emphasis (تقديم وتأخير)", "a grammatical error with no valid interpretation", "a feature found only in poetry, never in prose", "a construction unique to the imperative mood"],
      "a fronted/preposed complement used for stylistic emphasis (تقديم وتأخير)",
      "Fronting a sentence element such as the object before the verb or subject (تقديم وتأخير) is a recognised stylistic device in Arabic used to add emphasis."),
];

final _composition = [
  _q("In Arabic composition, which opening phrase is most appropriate for a formal letter addressed to an official or dignitary?",
      ["حضرة صاحب السعادة المحترم", "يا صاحبي العزيز", "أراك غداً إن شاء الله", "تحياتي الحارة يا صديقي"], "حضرة صاحب السعادة المحترم",
      "'حضرة صاحب السعادة المحترم' (Your respected excellency) is a formal, respectful opening suited to an official letter, unlike the informal alternatives."),
  _q("Which connective word is most appropriate for introducing a contrasting idea within an Arabic paragraph?",
      ["لكنّ (but/however)", "و (and)", "لأنّ (because)", "ثم (then)"], "لكنّ (but/however)",
      "لكنّ signals a contrast or contradiction between ideas, making it the appropriate connective for introducing opposing points."),
  _q("Which connective word is most appropriate for indicating a cause-and-effect relationship in an Arabic paragraph?",
      ["لأنّ (because)", "أو (or)", "لكنّ (but)", "بينما (while)"], "لأنّ (because)",
      "لأنّ introduces a reason or cause, appropriate for linking an effect to its explanation within a paragraph."),
  _q("When writing an essay in Arabic about the advantages and disadvantages of a topic, which structure is generally recommended?",
      ["An introduction, a balanced discussion of both sides, and a concluding evaluation", "A single long sentence with no paragraphs", "Only a list of advantages with no disadvantages mentioned", "A poem with no prose discussion at all"],
      "An introduction, a balanced discussion of both sides, and a concluding evaluation",
      "A well-structured advantages/disadvantages essay presents a clear introduction, a balanced treatment of both perspectives, and a concluding evaluation."),
  _q("Which of the following expressions would be most appropriate when apologising in Arabic composition or conversation?",
      ["أنا آسف جداً", "مبروك عليك", "بالتوفيق", "إلى اللقاء"], "أنا آسف جداً",
      "'أنا آسف جداً' (I am very sorry) is the standard expression used to apologise, unlike the congratulatory, well-wishing, or farewell phrases listed."),
  _q("In a formal Arabic report, which register of language is generally most appropriate?",
      ["Formal Standard Arabic (الفصحى), avoiding colloquial expressions", "Purely colloquial dialect throughout", "A mixture of English words with no Arabic", "Poetic classical verse only"],
      "Formal Standard Arabic (الفصحى), avoiding colloquial expressions",
      "Formal reports call for Modern Standard Arabic (الفصحى), which maintains a professional, widely understood register, avoiding regional colloquialisms."),
  _q("When composing a persuasive paragraph in Arabic, which technique is most effective for supporting the main argument?",
      ["Providing clear reasons and relevant examples", "Repeating the same sentence several times", "Avoiding any supporting evidence", "Writing only questions with no statements"],
      "Providing clear reasons and relevant examples",
      "Effective persuasive writing relies on clear supporting reasons and relevant examples to strengthen the main argument, rather than repetition or unsupported claims."),
  _q("Which of the following would be an appropriate transitional phrase to introduce a final point or conclusion in Arabic composition?",
      ["وأخيراً (and finally)", "في البداية (at the beginning)", "بالإضافة إلى ذلك (in addition to that)", "على الرغم من ذلك (despite that)"], "وأخيراً (and finally)",
      "'وأخيراً' (and finally) is a standard transitional phrase signalling the final point or conclusion of a composition."),
  _q("When writing a formal application letter in Arabic requesting admission or employment, it is most appropriate to",
      ["state the purpose clearly, provide relevant qualifications, and use a respectful, formal tone throughout", "use informal slang expressions to sound friendly", "avoid mentioning the purpose of the letter", "write in a mixture of Arabic and English without explanation"],
      "state the purpose clearly, provide relevant qualifications, and use a respectful, formal tone throughout",
      "A formal application letter should clearly state its purpose, present relevant qualifications, and maintain a respectful, formal tone appropriate to the context."),
  _q("Which of the following best represents an effective topic sentence to begin a descriptive paragraph about a rainy day in Arabic?",
      ["نزل المطر بغزارة صباح أمس، فتغيرت معالم المدينة", "اشترى أحمد كتاباً جديداً", "يحب الطلاب اللعب في فناء المدرسة", "سافر التاجر إلى بلد بعيد"],
      "نزل المطر بغزارة صباح أمس، فتغيرت معالم المدينة",
      "A strong topic sentence for a descriptive paragraph about rain directly introduces the scene, as in 'heavy rain fell yesterday morning, transforming the city's appearance', setting up the description that follows."),
  _q("In composing a formal Arabic email requesting information, which closing phrase would be most appropriate?",
      ["وتفضلوا بقبول فائق الاحترام والتقدير", "سلامي لجميع الأصدقاء", "أراك في الحفلة القادمة", "مع حبي الشديد"], "وتفضلوا بقبول فائق الاحترام والتقدير",
      "This formal closing, roughly meaning 'please accept my utmost respect and appreciation', is appropriate for a formal request email, unlike the casual alternatives."),
  _q("When summarising a longer Arabic passage in a shorter composition, a student should primarily aim to",
      ["capture the main ideas concisely in their own words, omitting minor details", "copy the original passage word for word", "add entirely new, unrelated information", "focus only on grammatical error correction"],
      "capture the main ideas concisely in their own words, omitting minor details",
      "Effective summarising involves concisely restating the main ideas in one's own words while leaving out minor supporting details, rather than copying text or introducing unrelated content."),
];

final _arabicLiterature = [
  _q("Imru' al-Qais, widely regarded as one of the foremost poets of the Pre-Islamic era, is especially celebrated for",
      ["his Mu'allaqa opening with the famous line 'قفا نبك', regarded as a model of classical Arabic ode", "his role as a companion of the Prophet Muhammad", "his compilation of Hadith literature", "his career as a modern Egyptian novelist"],
      "his Mu'allaqa opening with the famous line 'قفا نبك', regarded as a model of classical Arabic ode",
      "Imru' al-Qais is celebrated as a leading Pre-Islamic poet whose Mu'allaqa, opening with 'قفا نبك', is considered a foundational model of the classical Arabic qasida."),
  _q("Antarah ibn Shaddad, a notable Pre-Islamic poet, is particularly remembered for poetry combining themes of",
      ["chivalry, warfare, and love for his beloved Abla", "purely religious sermons", "modern political satire", "scientific observations of nature"],
      "chivalry, warfare, and love for his beloved Abla",
      "Antarah ibn Shaddad is remembered for poetry blending chivalric and martial themes with his celebrated love for Abla, becoming a legendary figure in Arabic literary tradition."),
  _q("Zuhayr ibn Abi Sulma, one of the poets of the Mu'allaqat, is often noted in Arabic literary history for",
      ["poetry emphasising wisdom, peace, and moral reflection", "leading military campaigns against Persia", "compiling the first Arabic dictionary", "writing exclusively in prose rather than verse"],
      "poetry emphasising wisdom, peace, and moral reflection",
      "Zuhayr ibn Abi Sulma is noted among the Mu'allaqat poets for verse reflecting on wisdom, the value of peace, and moral conduct, distinguishing his tone from more boastful contemporaries."),
  _q("Hassan ibn Thabit, a poet of the early Islamic period, is particularly known as",
      ["a poet closely associated with Prophet Muhammad, often called the 'poet of the Prophet'", "a Pre-Islamic vagabond poet (su'luk)", "a modern Lebanese novelist", "a compiler of pre-Islamic odes only"],
      "a poet closely associated with Prophet Muhammad, often called the 'poet of the Prophet'",
      "Hassan ibn Thabit is remembered for composing poetry in defence of Islam and the Prophet Muhammad, earning him the title of the 'poet of the Prophet'."),
  _q("Al-Farazdaq, an Umayyad-era poet, is chiefly remembered in Arabic literary history for",
      ["his poetic rivalry with Jarir, along with praise poetry (madih) for prominent patrons", "leading the compilation of the Qur'an", "founding a school of Islamic jurisprudence", "writing modern short stories"],
      "his poetic rivalry with Jarir, along with praise poetry (madih) for prominent patrons",
      "Al-Farazdaq is chiefly known for his long satirical rivalry with the poet Jarir, as well as praise poetry composed for Umayyad-era patrons."),
  _q("Al-Akhtal, one of the three great poets of the Umayyad period alongside Jarir and Al-Farazdaq, was notable for",
      ["composing panegyric poetry in praise of the Umayyad caliphs", "leading a Pre-Islamic tribal rebellion", "writing the earliest known Arabic grammar textbook", "translating Greek philosophy into Arabic"],
      "composing panegyric poetry in praise of the Umayyad caliphs",
      "Al-Akhtal was particularly known for panegyric (praise) poetry composed in honour of the Umayyad caliphs, complementing his role in the poetic rivalries of the era."),
  _q("Al-Mutanabbi, one of the most celebrated poets of the Abbasid period, is particularly renowned for",
      ["his eloquent, self-assured poetry often praising rulers and reflecting on ambition and pride", "his role as a Rightly Guided Caliph", "compiling the earliest collection of Hadith", "his career as a 20th-century journalist"],
      "his eloquent, self-assured poetry often praising rulers and reflecting on ambition and pride",
      "Al-Mutanabbi is widely regarded as one of the greatest Arabic poets, known for eloquent, confident verse praising patrons and reflecting on personal ambition and pride."),
  _q("Abu Nuwas, an Abbasid-era poet, is particularly known in Arabic literary history for",
      ["his innovative, often playful poetry, including verses on wine and everyday urban life", "his strict avoidance of any non-religious subject matter", "leading the Abbasid army into battle", "translating the Qur'an into Persian"],
      "his innovative, often playful poetry, including verses on wine and everyday urban life",
      "Abu Nuwas is known for innovative, often light-hearted Abbasid-era poetry, notably including khamriyyat (wine poetry) and depictions of urban life."),
  _q("Al-Jahiz, a prominent Abbasid intellectual, is particularly celebrated for his prose contributions to",
      ["essays and treatises covering topics such as zoology, rhetoric, and society, notably in 'Kitab al-Hayawan'", "epic pre-Islamic poetry", "modern Arabic cinema", "Sokoto-era West African scholarship"],
      "essays and treatises covering topics such as zoology, rhetoric, and society, notably in 'Kitab al-Hayawan'",
      "Al-Jahiz was a prolific Abbasid prose writer whose works, including 'Kitab al-Hayawan' (Book of Animals), covered zoology, rhetoric, and social observation."),
  _q("Ibn al-Muqaffa', an early Abbasid literary figure, is best known for his translation and adaptation of",
      ["'Kalila wa Dimna', a collection of moralistic animal fables originally from Persian/Indian sources", "the Mu'allaqat odes", "the Qur'an into Latin", "modern Egyptian newspaper articles"],
      "'Kalila wa Dimna', a collection of moralistic animal fables originally from Persian/Indian sources",
      "Ibn al-Muqaffa' is best remembered for his elegant Arabic rendering of 'Kalila wa Dimna', a collection of moralistic animal fables with Persian and Indian origins."),
  _q("Al-Hariri, a medieval Arabic literary figure, is particularly famous for his contribution to the literary genre known as",
      ["Maqamat, a form of rhymed prose narrative featuring a clever wandering protagonist", "modern free verse poetry", "Pre-Islamic oral tribal poetry", "West African Arabic scholarship"],
      "Maqamat, a form of rhymed prose narrative featuring a clever wandering protagonist",
      "Al-Hariri is celebrated for his Maqamat, a genre of rhymed, rhythmic prose narratives centred on a resourceful, roguish wandering protagonist."),
  _q("Taha Hussein, a major figure of modern Arabic literature, is particularly notable for",
      ["his influential autobiography 'Al-Ayyam' (The Days) and his contributions to literary criticism", "leading the Abbasid translation movement", "composing Pre-Islamic odes", "founding the Umayyad dynasty"],
      "his influential autobiography 'Al-Ayyam' (The Days) and his contributions to literary criticism",
      "Taha Hussein, a leading modern Egyptian intellectual, is best known for his autobiography 'Al-Ayyam' and for his influential work in modern Arabic literary criticism."),
  _q("Naguib Mahfouz, a leading modern Arabic novelist, is particularly notable for",
      ["his acclaimed novels depicting Egyptian society, including the 'Cairo Trilogy', and winning the Nobel Prize in Literature", "his role as a Pre-Islamic poet", "compiling the earliest Hadith collections", "leading a West African Islamic reform movement"],
      "his acclaimed novels depicting Egyptian society, including the 'Cairo Trilogy', and winning the Nobel Prize in Literature",
      "Naguib Mahfouz is renowned for his novels portraying Egyptian society, notably the 'Cairo Trilogy', and became the first Arabic-language writer to win the Nobel Prize in Literature."),
  _q("Gibran Khalil Gibran, a Lebanese-American literary figure, is particularly renowned for",
      ["his poetic prose work 'The Prophet', blending Arabic and English literary traditions", "his role as an Umayyad-era satirical poet", "compiling classical Arabic grammar rules", "his career as a Rightly Guided Caliph"],
      "his poetic prose work 'The Prophet', blending Arabic and English literary traditions",
      "Gibran Khalil Gibran is best known for 'The Prophet', a work of poetic prose that reflects his engagement with both Arabic and English literary traditions."),
  _q("Mahmoud Darwish, a prominent modern Arabic poet, is particularly known for poetry centred on themes of",
      ["Palestinian identity, exile, and homeland", "purely Pre-Islamic desert life", "medieval Islamic jurisprudence", "modern computer science"],
      "Palestinian identity, exile, and homeland",
      "Mahmoud Darwish is widely regarded as a national poet of Palestine, with his work centred on themes of identity, exile, and longing for homeland."),
  _q("Nizar Qabbani, a modern Syrian poet, is particularly celebrated for his poetry focused on",
      ["love, romance, and often bold social and political commentary", "strictly religious sermons with no personal themes", "Pre-Islamic tribal warfare exclusively", "translations of Greek philosophy"],
      "love, romance, and often bold social and political commentary",
      "Nizar Qabbani is celebrated for his lyrical poetry on love and romance, alongside bold, often provocative social and political commentary."),
  _q("Uthman dan Fodio, a key figure often studied within West African Arabic literary and scholarly tradition, is particularly known for",
      ["leading the Sokoto Jihad and producing extensive Arabic-language scholarly and religious writings", "composing Pre-Islamic odes in Mecca", "translating the Mu'allaqat into English", "founding a modern Egyptian publishing house"],
      "leading the Sokoto Jihad and producing extensive Arabic-language scholarly and religious writings",
      "Uthman dan Fodio led the Sokoto Jihad and produced a substantial body of Arabic scholarly and religious writings, making him a central figure in West African Islamic and Arabic literary tradition."),
  _q("Abdullahi dan Fodio, brother of Uthman dan Fodio and a scholar in the West African Arabic literary tradition, is particularly recognised for",
      ["his own body of Arabic scholarly works supporting the Sokoto Islamic reform movement", "leading Pre-Islamic tribal poetry gatherings", "authorship of the Maqamat genre", "his role as a modern Lebanese novelist"],
      "his own body of Arabic scholarly works supporting the Sokoto Islamic reform movement",
      "Abdullahi dan Fodio contributed his own significant body of Arabic scholarship supporting and documenting the Sokoto Islamic reform movement alongside his brother Uthman."),
  _q("The seven (or so) most celebrated pre-Islamic odes collectively known as the Mu'allaqat are traditionally associated with poets such as",
      ["Imru' al-Qais, Antarah ibn Shaddad, and Zuhayr ibn Abi Sulma, among others", "Ahmad Shawqi and Taha Hussein exclusively", "Al-Hariri and Ibn al-Muqaffa' exclusively", "Uthman dan Fodio and Abdullahi dan Fodio exclusively"],
      "Imru' al-Qais, Antarah ibn Shaddad, and Zuhayr ibn Abi Sulma, among others",
      "The Mu'allaqat are traditionally attributed to a group of celebrated Pre-Islamic poets including Imru' al-Qais, Antarah ibn Shaddad, and Zuhayr ibn Abi Sulma."),
  _q("The Nahda (النهضة), or Arabic literary and cultural revival beginning in the 19th century, is generally understood as a period marked by",
      ["renewed interest in classical Arabic heritage alongside engagement with modern European literary ideas", "the total disappearance of the Arabic language from literature", "an exclusive focus on Pre-Islamic poetic forms with no innovation", "the banning of prose writing in favor of poetry only"],
      "renewed interest in classical Arabic heritage alongside engagement with modern European literary ideas",
      "The Nahda was a period of Arabic literary and cultural revival that combined a renewed appreciation of classical Arabic heritage with meaningful engagement with modern European literary influences."),
];
