import "../quiz_question.dart";

const _subject = "Agricultural Science";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// Obafemi Awolowo University (OAU) Post-UTME Agricultural Science practice
/// bank — 100 medium-to-hard questions spanning the 7 core areas: General
/// Agriculture, Agricultural Ecology, Agricultural Engineering & Mechanics,
/// Soil Science, Agronomy, Animal Husbandry, and Agricultural Economics &
/// Extension. This is an independent practice set, not an official OAU past
/// question paper.
List<QuizQuestion> buildOauAgriculturalScienceQuestions() {
  return [
    ..._generalAgriculture,
    ..._agriculturalEcology,
    ..._agriculturalEngineering,
    ..._soilScience,
    ..._agronomy,
    ..._animalHusbandry,
    ..._agriculturalEconomicsExtension,
  ];
}

final _generalAgriculture = [
  _q("Which of the following most accurately distinguishes mixed farming from mixed cropping?",
      ["Mixed farming combines crop production with livestock rearing on the same farm, while mixed cropping grows two or more crops together",
       "Mixed farming grows only cereals while mixed cropping grows only legumes",
       "Mixed farming is practised only in the rainforest zone while mixed cropping is practised only in the savanna",
       "There is no real difference; the two terms mean exactly the same thing"],
      "Mixed farming combines crop production with livestock rearing on the same farm, while mixed cropping grows two or more crops together",
      "Mixed farming integrates crops and animals on one farm, whereas mixed cropping refers specifically to growing multiple crop species on the same piece of land simultaneously."),
  _q("Shifting cultivation, as traditionally practised, primarily relies on which mechanism to restore soil fertility?",
      ["A fallow period during which natural vegetation regenerates and organic matter accumulates", "Continuous application of synthetic fertiliser every season", "Deep ploughing to bring subsoil nutrients to the surface", "Irrigation with nutrient-rich river water"],
      "A fallow period during which natural vegetation regenerates and organic matter accumulates",
      "Shifting cultivation abandons a plot after a few cropping seasons, allowing the bush to regrow and replenish soil nutrients before it is farmed again."),
  _q("A major disadvantage of monocropping compared with crop rotation or mixed cropping is that monocropping tends to",
      ["deplete specific soil nutrients and encourage build-up of pests and diseases specific to that crop", "improve soil structure more than any other cropping system", "eliminate the need for weed control entirely", "automatically increase soil organic matter every season"],
      "deplete specific soil nutrients and encourage build-up of pests and diseases specific to that crop",
      "Growing the same crop repeatedly on the same land removes the same set of nutrients each season and allows crop-specific pests and diseases to persist and multiply."),
  _q("Agroforestry is best defined as a land-use system in which",
      ["woody perennial trees or shrubs are deliberately combined with crops and/or livestock on the same land", "only timber trees are planted for commercial logging", "crops are grown exclusively in greenhouses", "livestock are reared entirely indoors without access to pasture"],
      "woody perennial trees or shrubs are deliberately combined with crops and/or livestock on the same land",
      "Agroforestry integrates trees with arable crops or animals, providing benefits such as shade, windbreaks, soil improvement, and additional income."),
  _q("Which of the following is a primary role of the Federal Ministry of Agriculture in Nigeria's agricultural development?",
      ["Formulating national agricultural policy and coordinating programmes to boost food production", "Directly farming all land owned by private citizens", "Setting the retail price of every food item sold in local markets", "Manufacturing all farm machinery used in the country"],
      "Formulating national agricultural policy and coordinating programmes to boost food production",
      "Ministries of agriculture chiefly design policy, allocate resources, and coordinate national programmes rather than engage in direct farming themselves."),
  _q("A cooperative society benefits its farmer-members mainly by",
      ["pooling resources to obtain inputs, credit, and better market access at lower individual cost", "guaranteeing that crop prices will never fall", "eliminating the need for farmers to produce any crops themselves", "replacing government extension services entirely"],
      "pooling resources to obtain inputs, credit, and better market access at lower individual cost",
      "Cooperatives allow members to combine bargaining power for inputs, credit, and produce sales, achieving economies of scale unavailable to individual smallholders."),
  _q("Which factor is most limiting to increased agricultural productivity among smallholder farmers in many parts of Nigeria?",
      ["Limited access to improved inputs, credit, and modern technology", "Excessive availability of arable land", "Too much government subsidy on farm inputs", "Overabundance of skilled agricultural labour"],
      "Limited access to improved inputs, credit, and modern technology",
      "Smallholder productivity is commonly constrained by poor access to improved seeds, fertiliser, credit facilities, and mechanisation, keeping yields well below potential."),
  _q("The term 'plantation agriculture' refers to",
      ["large-scale cultivation of a single perennial cash crop, often for export", "small plots of mixed food crops grown for household consumption", "the rearing of poultry in battery cages", "the practice of growing crops only in greenhouses"],
      "large-scale cultivation of a single perennial cash crop, often for export",
      "Plantation agriculture involves extensive monoculture of crops such as oil palm, rubber, or cocoa, typically managed for commercial export rather than local subsistence."),
  _q("Which of these best explains why agriculture is described as the backbone of many developing economies?",
      ["It employs a large proportion of the workforce and underpins food security, raw material supply, and export earnings", "It is the only sector that generates any government revenue", "It requires no capital investment to operate successfully", "It has completely replaced industrialisation in most developing nations"],
      "It employs a large proportion of the workforce and underpins food security, raw material supply, and export earnings",
      "In many developing countries, agriculture remains the largest employer and a key source of food, industrial raw materials, and foreign exchange."),
  _q("Sustainable agriculture is best described as farming practised in a manner that",
      ["meets present food needs without compromising the ability of future generations to meet their own needs", "maximises short-term yield regardless of long-term soil degradation", "relies solely on chemical inputs to guarantee output", "avoids any form of technology or mechanisation"],
      "meets present food needs without compromising the ability of future generations to meet their own needs",
      "Sustainability balances current productivity with the conservation of soil, water, and biodiversity so that farming remains viable for future generations."),
  _q("Which of the following is an example of an agro-allied industry that depends directly on agricultural raw materials?",
      ["A textile mill that processes cotton lint into fabric", "A bank that offers only personal savings accounts", "A telecommunications company providing mobile network services", "A construction firm that builds residential apartments"],
      "A textile mill that processes cotton lint into fabric",
      "Agro-allied industries process farm produce; a textile mill using cotton lint as its raw material is a direct example of this linkage."),
  _q("A farm record showing the day-to-day income and expenditure of a farm business is best described as a",
      ["cash account/financial record", "soil survey map", "cropping calendar", "weather forecast bulletin"],
      "cash account/financial record",
      "A financial record tracks money received and spent, enabling the farmer to assess profitability, unlike a soil map, calendar, or weather bulletin."),
];

final _agriculturalEcology = [
  _q("An ecosystem is best defined as",
      ["a community of living organisms interacting with each other and their non-living environment", "a single species of plant growing in isolation", "the total land area used for crop production in a country", "a man-made structure for storing farm produce"],
      "a community of living organisms interacting with each other and their non-living environment",
      "An ecosystem encompasses both biotic (living) and abiotic (non-living) components and the interactions between them, such as a farm pond or a forest."),
  _q("In a farm food chain of grass to grasshopper to lizard to hawk, the hawk occupies which trophic level?",
      ["Tertiary consumer", "Primary producer", "Primary consumer", "Secondary consumer"],
      "Tertiary consumer",
      "Grass is the producer, the grasshopper is the primary consumer, the lizard is the secondary consumer, and the hawk, feeding on the lizard, is the tertiary consumer."),
  _q("Which of the following best explains the ecological importance of decomposers such as bacteria and fungi in a farm ecosystem?",
      ["They break down dead organic matter, releasing nutrients back into the soil for plant use", "They convert atmospheric nitrogen directly into protein for animal consumption", "They photosynthesise to produce food for the entire ecosystem", "They prevent any form of soil erosion from occurring"],
      "They break down dead organic matter, releasing nutrients back into the soil for plant use",
      "Decomposers recycle nutrients locked in dead plant and animal matter, making them available again to producers and maintaining soil fertility."),
  _q("Deforestation in the derived savanna zone of Nigeria has most directly contributed to",
      ["increased soil erosion and gradual desertification-like degradation", "a permanent increase in annual rainfall", "an automatic improvement in soil fertility", "a decrease in the average daily temperature"],
      "increased soil erosion and gradual desertification-like degradation",
      "Removing tree cover exposes soil to wind and water erosion and reduces moisture retention, accelerating land degradation in fragile transitional ecological zones."),
  _q("Which of the following is an abiotic component of a farm ecosystem?",
      ["Soil pH", "Earthworms", "Weeds", "Crop pests"],
      "Soil pH",
      "Soil pH is a chemical/physical property of the environment (non-living), while earthworms, weeds, and pests are living (biotic) components."),
  _q("Ecological succession on abandoned farmland typically begins with which group of colonising organisms?",
      ["Pioneer species such as grasses and other fast-growing herbaceous plants", "Mature climax forest trees", "Large grazing mammals", "Deep-rooted timber trees"],
      "Pioneer species such as grasses and other fast-growing herbaceous plants",
      "Succession starts with hardy pioneer species that can colonise bare or disturbed soil, gradually being replaced by shrubs and eventually forest as conditions improve."),
  _q("The carrying capacity of a grazing land refers to",
      ["the maximum number of livestock the land can support sustainably without degrading the pasture", "the total weight of farm machinery the soil can bear", "the volume of water a dam can hold", "the number of years land can be left fallow"],
      "the maximum number of livestock the land can support sustainably without degrading the pasture",
      "Carrying capacity is the stocking density a pasture can sustain long-term without overgrazing and subsequent degradation of the vegetation and soil."),
  _q("Overgrazing in the savanna zone leads mainly to",
      ["loss of vegetation cover, soil compaction, and increased erosion", "an increase in soil organic matter content", "improved water infiltration into the soil", "a rise in pasture productivity over time"],
      "loss of vegetation cover, soil compaction, and increased erosion",
      "Excessive grazing removes protective vegetation faster than it can regrow, exposing and compacting the soil and making it more vulnerable to erosion."),
  _q("Which climatic factor most directly limits crop production in the Sahel ecological zone of Nigeria?",
      ["Low and erratic rainfall", "Excessively high relative humidity", "Very low sunlight intensity", "Extremely acidic soil pH"],
      "Low and erratic rainfall",
      "The Sahel zone's short, unreliable rainy season is the chief constraint on crop choice and productivity, favouring only drought-tolerant crops like millet and sorghum."),
  _q("Symbiosis between rhizobium bacteria and leguminous plant roots is best classified as an example of",
      ["mutualism, since both organisms benefit from the association", "parasitism, since only the bacteria benefit", "predation, since the bacteria consume the plant", "commensalism, since only the plant benefits"],
      "mutualism, since both organisms benefit from the association",
      "Rhizobium bacteria fix atmospheric nitrogen for the plant's use, while the plant supplies the bacteria with carbohydrates, making it a mutually beneficial relationship."),
  _q("Which of the following best describes the effect of wind as an ecological factor on crop production?",
      ["Strong winds can cause lodging of crops and increase the rate of transpiration and soil erosion", "Wind has no measurable effect on any farming operation", "Wind only affects the colour of harvested produce", "Wind exclusively improves soil fertility"],
      "Strong winds can cause lodging of crops and increase the rate of transpiration and soil erosion",
      "High wind speeds can physically flatten tall crops (lodging), increase water loss through transpiration, and blow away loose topsoil."),
];

final _agriculturalEngineering = [
  _q("Which of the following farm tools is most appropriate for shelling maize on a small scale?",
      ["A maize sheller", "A mould-board plough", "A cutlass", "A wheelbarrow"],
      "A maize sheller",
      "A maize sheller is specifically designed to separate maize grains from the cob, unlike a plough (tillage), cutlass (cutting/clearing), or wheelbarrow (transport)."),
  _q("A knapsack sprayer is a farm implement primarily used for",
      ["applying liquid pesticides or herbicides to crops", "measuring the moisture content of harvested grain", "cutting down mature tree crops", "threshing cereal grains from their husks"],
      "applying liquid pesticides or herbicides to crops",
      "The knapsack sprayer, carried on the back, is designed to evenly distribute liquid agrochemicals such as pesticides or herbicides over a crop."),
  _q("Which of the following farm structures is designed mainly to protect stored grain from moisture, pests, and rodents?",
      ["A grain silo/crib", "A cattle crush", "An irrigation canal", "A farrowing pen"],
      "A grain silo/crib",
      "Silos and cribs are storage structures engineered to keep grain dry, well-ventilated, and protected from pests and rodents after harvest."),
  _q("The main advantage of using a disc plough over a mould-board plough on land with many roots and stones is that the disc plough",
      ["cuts through roots and obstructions more easily due to its rotating discs", "requires no tractor power to operate", "leaves the soil completely unturned", "is used exclusively for spraying chemicals"],
      "cuts through roots and obstructions more easily due to its rotating discs",
      "The rotating discs of a disc plough slice through roots, stones, and tough sod more effectively than the fixed mould-board, making it suited to newly cleared or trashy land."),
  _q("Planters (seed drills) are farm machines used mainly to",
      ["place seeds at a uniform depth and spacing during sowing", "harvest root and tuber crops", "spray fungicide on standing crops", "shell groundnuts after harvest"],
      "place seeds at a uniform depth and spacing during sowing",
      "Seed drills/planters mechanise sowing, ensuring consistent seed depth and spacing, which improves germination uniformity compared with broadcasting by hand."),
  _q("A cutlass and hoe are classified together as",
      ["simple hand tools", "primary tillage machinery", "irrigation equipment", "processing machinery"],
      "simple hand tools",
      "Both the cutlass and hoe are manually operated implements without engines, distinguishing them from powered machinery or complex engineered structures."),
  _q("Which unit of a tractor is responsible for transmitting engine power to attached implements such as a mower or thresher?",
      ["The power take-off (PTO) shaft", "The radiator", "The exhaust manifold", "The steering wheel"],
      "The power take-off (PTO) shaft",
      "The PTO shaft transfers rotational power from the tractor's engine to mounted or trailed implements, driving components such as a mower blade or thresher drum."),
  _q("A major safety precaution when operating a cutlass or any sharp farm tool is to",
      ["keep the blade sharp and always cut away from the body", "leave the blade permanently blunt to avoid injury", "operate it only at night", "avoid wearing any protective clothing while working"],
      "keep the blade sharp and always cut away from the body",
      "A sharp blade requires less force (reducing slip risk), and cutting motions directed away from the body minimise the chance of self-injury."),
  _q("Which of the following best explains why farm machinery should be stored under a shed when not in use?",
      ["To protect it from rain, sun, and rust, thereby extending its useful life", "To increase its fuel consumption when next used", "To make it heavier for better traction", "To prevent it from being serviced regularly"],
      "To protect it from rain, sun, and rust, thereby extending its useful life",
      "Exposure to weather accelerates corrosion and material degradation; sheltered storage reduces rust and wear, prolonging the equipment's service life."),
  _q("An animal-drawn ridger differs from a tractor-mounted ridger mainly in its",
      ["source of pulling power", "basic function of forming ridges", "requirement for a skilled operator", "use in crop production generally"],
      "source of pulling power",
      "Both perform the same ridging function, but one is pulled by draught animals (e.g., oxen) while the other is powered and pulled by a tractor."),
];

final _soilScience = [
  _q("Which soil separate has the smallest particle size and the greatest capacity to hold water and nutrients?",
      ["Clay", "Sand", "Silt", "Gravel"],
      "Clay",
      "Clay particles are the smallest of the mineral soil separates, giving clay soils a large surface area that strongly retains water and nutrient ions."),
  _q("Soil pH is a measure of the",
      ["degree of acidity or alkalinity of the soil", "amount of organic matter present in the soil", "proportion of sand particles in the soil", "depth of the water table below the soil surface"],
      "degree of acidity or alkalinity of the soil",
      "Soil pH quantifies hydrogen ion concentration, indicating whether a soil is acidic, neutral, or alkaline, which affects nutrient availability to plants."),
  _q("Most arable crops grow best within a soil pH range of approximately",
      ["6.0 to 7.0 (slightly acidic to neutral)", "2.0 to 3.0 (strongly acidic)", "9.0 to 10.0 (strongly alkaline)", "0.0 to 1.0 (extremely acidic)"],
      "6.0 to 7.0 (slightly acidic to neutral)",
      "Most nutrients are optimally available to plant roots within the slightly acidic to neutral pH range of about 6.0-7.0."),
  _q("Liming an acidic soil is carried out primarily to",
      ["raise the soil pH and reduce aluminium and manganese toxicity", "lower the soil pH further", "increase the sand content of the soil", "eliminate the need for any fertiliser application permanently"],
      "raise the soil pH and reduce aluminium and manganese toxicity",
      "Applying lime neutralises soil acidity, raising pH and reducing the solubility of toxic elements such as aluminium that harm plant roots in acidic soils."),
  _q("Which of the following soil erosion control methods is most effective on steep hillsides used for farming?",
      ["Terracing", "Broadcasting seeds without any tillage", "Deep monocropping", "Removing all vegetation cover"],
      "Terracing",
      "Terracing breaks a slope into a series of level steps, slowing water runoff and reducing soil erosion on hilly or mountainous farmland."),
  _q("Contour ploughing helps reduce soil erosion mainly by",
      ["creating furrows across the slope that slow down and trap surface water runoff", "increasing the speed at which rainwater flows downhill", "removing organic matter from the topsoil", "compacting the soil to prevent water infiltration entirely"],
      "creating furrows across the slope that slow down and trap surface water runoff",
      "Ploughing along the contour, rather than up and down a slope, creates ridges that intercept and slow runoff, reducing its erosive power."),
  _q("Leaching in the soil refers to the process by which",
      ["soluble nutrients are washed downward beyond the reach of plant roots by percolating water", "organic matter is converted into humus", "soil particles are blown away by strong wind", "nutrients are absorbed directly by plant roots"],
      "soluble nutrients are washed downward beyond the reach of plant roots by percolating water",
      "Leaching moves dissolved nutrients down through the soil profile with water, often making them unavailable to shallow-rooted plants and contributing to soil infertility."),
  _q("Soil fertility can be maintained or improved through all of the following practices EXCEPT",
      ["continuous monocropping of the same nutrient-demanding crop every season", "crop rotation with leguminous crops", "application of organic manure", "practising a bush fallow period"],
      "continuous monocropping of the same nutrient-demanding crop every season",
      "Continuous monocropping steadily depletes specific nutrients, whereas rotation, manuring, and fallowing all help restore or maintain soil fertility."),
  _q("The cation exchange capacity (CEC) of a soil is best described as its",
      ["ability to hold and exchange positively charged nutrient ions available to plants", "total weight per unit volume", "resistance to compaction by farm machinery", "capacity to transmit sound waves"],
      "ability to hold and exchange positively charged nutrient ions available to plants",
      "CEC measures how many cations (e.g., calcium, potassium, magnesium) a soil can retain on its charged particle surfaces and later release to plant roots."),
  _q("Which of the following soil organisms plays a major role in improving soil aeration and drainage through burrowing?",
      ["Earthworms", "Nematodes that attack roots", "Rust fungi", "Soil-borne viruses"],
      "Earthworms",
      "Earthworms burrow through soil, creating channels that improve aeration and drainage while also mixing and enriching the soil with castings."),
  _q("A soil that drains poorly and remains waterlogged for long periods is most likely to have a high proportion of",
      ["clay particles", "coarse sand particles", "gravel", "well-decomposed humus only"],
      "clay particles",
      "Clay particles are so small and tightly packed that they leave very small pore spaces, restricting water movement and causing waterlogging in clay-dominated soils."),
  _q("Green manuring involves",
      ["ploughing young, still-green leguminous or cover crops into the soil to improve fertility", "spraying green-coloured pesticide on crops", "painting farm structures green to reduce heat absorption", "harvesting crops while they are still unripe"],
      "ploughing young, still-green leguminous or cover crops into the soil to improve fertility",
      "Green manure crops are grown then incorporated into the soil while still green, adding organic matter and, if leguminous, fixing nitrogen."),
  _q("Soil erosion caused by the removal of topsoil in thin, fairly uniform layers across a slope is known as",
      ["sheet erosion", "gully erosion", "rill erosion", "wind erosion"],
      "sheet erosion",
      "Sheet erosion removes a relatively even layer of topsoil across a broad area, often the earliest and least visible stage of water erosion, before it develops into rills or gullies."),
];

final _agronomy = [
  _q("Crop rotation is defined as the practice of",
      ["growing different crops in a planned sequence on the same piece of land over successive seasons", "growing the same crop on the same land every season indefinitely", "planting several unrelated crops randomly without any plan", "rotating farm labourers between different farms"],
      "growing different crops in a planned sequence on the same piece of land over successive seasons",
      "Crop rotation deliberately alternates crops (often including a legume) across seasons to balance nutrient use, break pest cycles, and maintain soil fertility."),
  _q("Which of the following is the most important reason for including a legume in a crop rotation cycle?",
      ["Legumes fix atmospheric nitrogen, enriching the soil for the crop that follows", "Legumes require no water throughout their growth cycle", "Legumes are immune to all pests and diseases", "Legumes cannot be eaten by humans or animals"],
      "Legumes fix atmospheric nitrogen, enriching the soil for the crop that follows",
      "Nitrogen-fixing legumes, through their root nodule bacteria, add usable nitrogen to the soil, benefiting the next crop in the rotation."),
  _q("Seed dormancy refers to a condition in which",
      ["a viable seed fails to germinate even under favourable conditions until certain internal changes occur", "a seed has completely lost its ability to germinate", "a seed germinates immediately regardless of environmental conditions", "a seed is destroyed by pests before planting"],
      "a viable seed fails to germinate even under favourable conditions until certain internal changes occur",
      "Dormant seeds are alive and capable of germinating but are physiologically blocked from doing so until specific conditions (e.g., after-ripening) are met."),
  _q("Which of the following is a recommended method of breaking hard seed-coat dormancy before planting?",
      ["Scarification of the seed coat", "Storing the seed at extremely low humidity indefinitely", "Planting the seed immediately without any pre-treatment", "Exposing the seed to direct sunlight for one hour only"],
      "Scarification of the seed coat",
      "Scarification physically or chemically weakens a hard seed coat, allowing water and oxygen to penetrate and trigger germination."),
  _q("The primary purpose of thinning young crop seedlings is to",
      ["reduce competition for light, water, and nutrients among plants, allowing the remaining ones to grow better", "increase the total number of plants per unit area indefinitely", "eliminate the need for any weed control", "prevent seeds from germinating at all"],
      "reduce competition for light, water, and nutrients among plants, allowing the remaining ones to grow better",
      "Thinning removes excess, weaker seedlings so the remaining plants have adequate space and resources, improving overall crop performance."),
  _q("Which of the following weed control methods relies on the use of chemicals to kill unwanted plants?",
      ["Chemical (herbicide) control", "Mechanical control using a hoe", "Cultural control through crop rotation", "Biological control using natural predators only"],
      "Chemical (herbicide) control",
      "Herbicides are chemical substances specifically formulated to kill or suppress weeds, distinct from mechanical, cultural, or biological weed control approaches."),
  _q("A pre-emergence herbicide is applied",
      ["to the soil before the crop and weed seeds germinate", "only after the crop has fully matured and been harvested", "directly onto harvested grains in storage", "exclusively to livestock feed"],
      "to the soil before the crop and weed seeds germinate",
      "Pre-emergence herbicides form a chemical barrier in the soil that prevents germinating weed seeds from establishing, applied before seedlings emerge."),
  _q("Which of the following pests is most commonly associated with causing significant damage to stored grains such as maize and cowpea?",
      ["Weevils", "Tsetse flies", "Ticks", "Mosquitoes"],
      "Weevils",
      "Weevils are notorious storage pests that bore into and feed on grains such as maize and cowpea, causing substantial post-harvest losses."),
  _q("Crop rotation helps to reduce the incidence of soil-borne pests and diseases mainly because it",
      ["breaks the life cycle of pests and pathogens that depend on a specific host crop", "increases the population of a single pest species over time", "provides a continuous host for pathogens every season", "eliminates the need for any pest monitoring"],
      "breaks the life cycle of pests and pathogens that depend on a specific host crop",
      "Many pests and diseases are host-specific; rotating to a non-host crop deprives them of a suitable host, reducing their build-up in the soil."),
  _q("Which of the following best describes the term 'monoculture'?",
      ["The continuous cultivation of a single crop species on the same land over successive seasons", "The cultivation of several different crops together on the same plot", "The rearing of a single species of livestock alongside crops", "The practice of leaving farmland completely fallow every year"],
      "The continuous cultivation of a single crop species on the same land over successive seasons",
      "Monoculture involves repeatedly growing one crop type on the same land, which can increase yield uniformity but heightens pest, disease, and soil-nutrient risks."),
  _q("The main purpose of mulching around growing crops is to",
      ["conserve soil moisture and suppress weed growth", "increase the rate of soil erosion", "reduce the organic matter content of the soil", "prevent seed germination entirely"],
      "conserve soil moisture and suppress weed growth",
      "A mulch layer (organic or plastic) reduces evaporation from the soil surface and blocks light needed by weed seedlings, conserving moisture and limiting weed competition."),
  _q("Which stage of crop production involves cutting and gathering mature crops from the field?",
      ["Harvesting", "Land preparation", "Nursery establishment", "Transplanting"],
      "Harvesting",
      "Harvesting is the stage at which mature crops are cut, picked, or dug up from the field, following land preparation, planting, and crop husbandry stages."),
  _q("Vegetative propagation of crops such as cassava and sugarcane is carried out using",
      ["stem cuttings", "true seeds only", "spores", "grafted root nodules from unrelated species"],
      "stem cuttings",
      "Cassava and sugarcane are typically propagated asexually using stem cuttings, which grow into new plants genetically identical to the parent."),
  _q("Which of the following is an important reason for practising early planting at the onset of the rains in most parts of Nigeria?",
      ["It allows crops to make maximum use of the available rainfall period for growth and maturity", "It guarantees the complete absence of pests throughout the season", "It eliminates any need for subsequent weeding", "It reduces the total yield obtainable from the crop"],
      "It allows crops to make maximum use of the available rainfall period for growth and maturity",
      "Planting early ensures the crop's growth cycle aligns with the full length of the rainy season, maximising water availability for growth and yield."),
  _q("Which of these is a cultural method of pest control?",
      ["Timely planting and proper crop rotation to avoid peak pest periods", "Spraying a broad-spectrum synthetic insecticide", "Introducing a natural predator of the pest", "Applying a systemic fungicide"],
      "Timely planting and proper crop rotation to avoid peak pest periods",
      "Cultural pest control uses farming practices, such as adjusting planting dates or rotating crops, to reduce pest pressure without chemicals or introduced organisms."),
];

final _animalHusbandry = [
  _q("Which of the following breeds of cattle is best known for high milk yield and is commonly kept for dairy purposes?",
      ["Friesian", "White Fulani (Bunaji)", "N'Dama", "Sokoto Gudali"],
      "Friesian",
      "The Friesian (Holstein-Friesian) breed is internationally renowned for its exceptionally high milk yield, making it a preferred dairy breed, often crossed with local breeds in the tropics."),
  _q("Colostrum, the first milk produced by a mammal after giving birth, is important to the newborn mainly because it",
      ["provides antibodies that boost the young animal's immunity against disease", "contains no nutritional value at all", "is harmful and should be withheld from the young", "is used only for making cheese"],
      "provides antibodies that boost the young animal's immunity against disease",
      "Colostrum is rich in maternal antibodies that give newborn animals passive immunity during their first, most vulnerable days of life."),
  _q("Culling in livestock management refers to the",
      ["removal of unproductive, diseased, or genetically undesirable animals from the herd", "process of vaccinating all animals in a herd", "castration of young male animals", "process of feeding animals a balanced ration"],
      "removal of unproductive, diseased, or genetically undesirable animals from the herd",
      "Culling improves overall herd quality and productivity by systematically removing animals that are unproductive, sick, or of poor genetic merit."),
  _q("Which of the following poultry diseases is viral and highly contagious, often causing sudden high mortality in a flock?",
      ["Newcastle disease", "Coccidiosis", "Fowl mites infestation", "Rickets"],
      "Newcastle disease",
      "Newcastle disease is a highly contagious viral disease of poultry that can spread rapidly and cause severe mortality if the flock is unvaccinated."),
  _q("A balanced livestock ration is one that",
      ["supplies all the nutrients an animal needs in the correct proportions for its stage of production", "consists of a single feed ingredient fed exclusively", "contains only carbohydrates with no protein or minerals", "is given to the animal only once a week"],
      "supplies all the nutrients an animal needs in the correct proportions for its stage of production",
      "A balanced ration combines energy, protein, vitamins, and minerals in proportions appropriate to the animal's age, weight, and productive purpose (growth, milk, or egg production)."),
  _q("Castration of young male livestock is carried out mainly to",
      ["reduce aggressiveness and improve meat quality by controlling unwanted breeding", "increase the animal's fertility", "prevent the animal from ever gaining weight", "eliminate the need for vaccination"],
      "reduce aggressiveness and improve meat quality by controlling unwanted breeding",
      "Castrating males removes the testes, reducing aggressive behaviour and often improving carcass/meat quality while preventing indiscriminate breeding."),
  _q("Which of the following is an important sign of a healthy farm animal?",
      ["Bright, alert eyes with a shiny coat and normal appetite", "Dull, sunken eyes with a rough coat and loss of appetite", "Constant isolation from the rest of the herd or flock", "Persistent coughing and nasal discharge"],
      "Bright, alert eyes with a shiny coat and normal appetite",
      "Healthy animals typically show alertness, a glossy coat, normal feeding behaviour, and active engagement with their environment, unlike sick animals which show the opposite signs."),
  _q("The deep litter system of poultry housing involves",
      ["keeping birds on a floor covered with absorbent material such as wood shavings that is left to build up over time", "confining each bird individually in a small wire cage", "raising birds entirely on wire mesh floors with no litter", "keeping birds exclusively in open free-range pasture with no housing"],
      "keeping birds on a floor covered with absorbent material such as wood shavings that is left to build up over time",
      "In deep litter housing, birds are raised on a floor covered with materials like wood shavings or rice husks, which absorbs droppings and is periodically turned rather than removed daily."),
  _q("Which of the following is the main function of a brooder in poultry production?",
      ["To provide artificial warmth and a controlled environment for day-old chicks", "To store eggs before incubation", "To slaughter mature birds for sale", "To mix commercial feed for adult layers"],
      "To provide artificial warmth and a controlled environment for day-old chicks",
      "Brooders supply the heat that day-old chicks need since they cannot yet regulate their own body temperature effectively, protecting them during the critical early weeks."),
  _q("Artificial insemination in livestock breeding is mainly advantageous because it",
      ["allows genetically superior males to sire many offspring without natural mating and reduces disease transmission", "eliminates the need for any record-keeping on the farm", "guarantees that every offspring will be female", "removes the need to feed breeding females"],
      "allows genetically superior males to sire many offspring without natural mating and reduces disease transmission",
      "AI enables semen from a single high-merit sire to inseminate many females, spreading superior genetics widely while reducing risks associated with natural mating, such as disease spread and injury."),
  _q("Which class of feed ingredient is maize primarily classified as in livestock nutrition?",
      ["An energy (carbohydrate) feed", "A mineral supplement", "A vitamin premix", "A source of roughage only"],
      "An energy (carbohydrate) feed",
      "Maize is rich in starch/carbohydrate and is used mainly as an energy source in compounded livestock and poultry rations."),
  _q("Which of the following is a common ectoparasite that infests the skin and feathers of poultry?",
      ["Fowl lice", "Coccidia", "Newcastle virus", "Aflatoxin-producing mould"],
      "Fowl lice",
      "Fowl lice live on the skin and feathers of birds (external/ectoparasites), unlike coccidia, viruses, and moulds which act internally or via toxins rather than as skin parasites."),
  _q("Vaccination of livestock is carried out primarily to",
      ["stimulate the animal's immune system to develop resistance against specific diseases", "cure an animal that is already showing severe symptoms of illness", "increase the animal's daily feed intake", "improve the physical appearance of the animal's coat only"],
      "stimulate the animal's immune system to develop resistance against specific diseases",
      "Vaccines are preventive, priming the immune system to recognise and fight a specific pathogen before natural infection occurs, rather than treating existing illness."),
];

final _agriculturalEconomicsExtension = [
_q("Which of the following best defines the term 'demand' in agricultural marketing?",
      ["The quantity of a commodity that consumers are willing and able to buy at a given price and time", "The total quantity of a commodity produced by all farmers in a season", "The amount of a commodity that spoils before it reaches the market", "The number of farmers who cultivate a particular crop"],
      "The quantity of a commodity that consumers are willing and able to buy at a given price and time",
      "Demand in economics specifically refers to willingness and ability to purchase at a given price, not merely a desire or total production figures."),
_q("According to the law of supply, as the price of an agricultural commodity rises, the quantity supplied by producers tends to",
      ["increase, assuming other factors remain constant", "decrease, assuming other factors remain constant", "remain completely unchanged regardless of price", "fall to zero immediately"],
      "increase, assuming other factors remain constant",
      "The law of supply states a direct relationship between price and quantity supplied: higher prices generally motivate producers to supply more, ceteris paribus."),
_q("Which of the following is a major function of agricultural marketing?",
      ["Moving farm produce from the point of production to the final consumer efficiently", "Increasing the biological yield of crops directly", "Controlling the weather patterns affecting a farming season", "Determining the genetic composition of livestock breeds"],
      "Moving farm produce from the point of production to the final consumer efficiently",
      "Agricultural marketing covers all activities, assembling, storage, transport, processing, and distribution, that move produce from farm to consumer."),
_q("An increase in the price of an agricultural commodity while all other factors remain constant is most likely to cause quantity demanded to",
      ["fall, in line with the law of demand", "rise sharply regardless of consumer income", "remain exactly the same at all price levels", "become impossible to measure"],
      "fall, in line with the law of demand",
      "The law of demand states an inverse relationship between price and quantity demanded: as price rises, consumers generally buy less, other things being equal."),
_q("Which of the following is a major problem commonly associated with agricultural marketing in Nigeria?",
      ["Poor rural road networks and inadequate storage facilities leading to high post-harvest losses", "An oversupply of cold storage facilities in every village", "Excessive standardisation and grading of all produce", "Too many well-organised marketing cooperatives nationwide"],
      "Poor rural road networks and inadequate storage facilities leading to high post-harvest losses",
      "Bad roads delay produce reaching markets while inadequate storage accelerates spoilage, together contributing significantly to post-harvest losses in Nigerian agriculture."),
_q("The role of middlemen in agricultural marketing is best described as",
      ["linking producers to final consumers by performing functions such as buying, transporting, and distributing produce", "growing crops on behalf of farmers", "setting government agricultural policy", "conducting agricultural research on new crop varieties"],
      "linking producers to final consumers by performing functions such as buying, transporting, and distributing produce",
      "Middlemen (assemblers, wholesalers, retailers) perform essential marketing functions that bridge the gap between scattered farm producers and dispersed consumers."),
_q("Which of the following best describes 'farm budgeting'?",
      ["A financial plan estimating expected income and expenditure of a farm business over a period", "A record of the weather conditions on a farm throughout the year", "A map showing the boundaries of a farm", "A list of all livestock breeds kept on a farm"],
      "A financial plan estimating expected income and expenditure of a farm business over a period",
      "Farm budgeting projects anticipated costs and revenues, helping a farmer plan resource allocation and assess likely profitability before committing to production."),
_q("Which of the following is an example of a fixed cost in farm business management?",
      ["Depreciation on farm machinery", "Cost of seeds purchased for planting", "Cost of fertiliser applied each season", "Wages paid to casual labourers hired for harvesting"],
      "Depreciation on farm machinery",
      "Fixed costs do not vary with the level of output in the short run; machinery depreciation is incurred regardless of how much is produced, unlike seed, fertiliser, or seasonal labour costs."),
_q("Farm profit is calculated as",
      ["total revenue minus total cost of production", "total revenue plus total cost of production", "total cost of production divided by total revenue", "total quantity produced multiplied by the number of farm workers"],
      "total revenue minus total cost of production",
      "Profit is the surplus remaining after all production costs are subtracted from the total revenue generated from selling farm produce."),
_q("Which of the following best explains the term 'agricultural extension'?",
      ["An educational process of transferring useful research-based information to farmers to improve their practices", "The physical enlargement of a farmer's landholding", "A government tax levied on farm produce", "A type of farm insurance policy"],
      "An educational process of transferring useful research-based information to farmers to improve their practices",
      "Agricultural extension is fundamentally an informal education system that communicates research findings and improved techniques from scientists to farmers."),
_q("Which of the following is the most commonly used method by extension agents to reach many farmers at once with a new farming technique?",
      ["Method demonstration at farmer field days", "Individual farm visits to only one farmer per year", "Publishing research exclusively in international scientific journals", "Restricting information strictly to university students"],
      "Method demonstration at farmer field days",
      "Demonstrations at field days allow an extension agent to show a new technique practically to a large group of farmers simultaneously, encouraging wider adoption."),
_q("Which of the following best describes the role of the Agricultural Development Programme (ADP) in Nigeria?",
      ["Coordinating extension services and improved input distribution to boost farmer productivity at the state level", "Setting the exchange rate of the Nigerian currency", "Manufacturing all fertiliser used in the country", "Providing free land to every citizen who requests it"],
      "Coordinating extension services and improved input distribution to boost farmer productivity at the state level",
      "ADPs were established across Nigerian states primarily to deliver extension services, disseminate improved technology, and support farmers with access to inputs."),
_q("Which of the following is a key barrier to the adoption of improved agricultural technology by many rural farmers?",
      ["Limited access to credit and inadequate awareness of the new technology's benefits", "Excessive availability of low-interest agricultural loans", "Overexposure to too many extension agents per farmer", "Complete absence of any traditional farming knowledge"],
      "Limited access to credit and inadequate awareness of the new technology's benefits",
      "Farmers often cannot afford or are unaware of the advantages of new inputs or practices, which slows the adoption of otherwise beneficial agricultural innovations."),
_q("Which of the following best defines 'agricultural credit'?",
      ["Funds borrowed by a farmer to finance farm operations, to be repaid usually with interest", "Free farm inputs distributed without any repayment obligation", "A grading certificate issued for exported produce", "A government subsidy paid only to agricultural researchers"],
      "Funds borrowed by a farmer to finance farm operations, to be repaid usually with interest",
      "Agricultural credit refers to loans, obtained from banks, cooperatives, or other lenders, that farmers use to finance inputs, equipment, or expansion, and later repay."),
_q("Which of the following is a major benefit of forming a farmers' cooperative society for the marketing of produce?",
      ["Increased bargaining power leading to better prices for members' produce", "Automatic elimination of all transportation costs", "Guaranteed freedom from any form of price fluctuation", "Removal of the need for any record-keeping"],
      "Increased bargaining power leading to better prices for members' produce",
      "By selling collectively, cooperative members can negotiate more favourable prices than they could individually, strengthening their position in the market."),
_q("The concept of 'diminishing returns' in agricultural production describes a situation where",
      ["additional units of a variable input eventually produce smaller and smaller increases in output, other inputs held constant", "output continues to increase at a constant rate no matter how much input is added", "adding any input always causes total output to fall immediately", "output rises only when land area is reduced"],
      "additional units of a variable input eventually produce smaller and smaller increases in output, other inputs held constant",
      "The law of diminishing returns states that beyond a certain point, each extra unit of a variable input (e.g., fertiliser) yields progressively smaller output gains."),
_q("Which of the following farm records is used mainly to track the health treatments and productivity of individual livestock?",
      ["Livestock/herd register", "Rainfall record", "Farm map", "Soil survey report"],
      "Livestock/herd register",
      "A herd register logs details such as breed, health treatments, breeding history, and productivity for each animal, distinct from weather, mapping, or soil records."),
_q("Which of the following best describes 'value addition' in agricultural produce?",
      ["Processing raw farm produce into a more refined or convenient form to increase its market value", "Selling raw produce immediately after harvest without any processing", "Reducing the quantity of produce available for sale", "Storing produce indefinitely without any further use"],
      "Processing raw farm produce into a more refined or convenient form to increase its market value",
      "Value addition, such as milling grain into flour or processing cassava into garri, increases a product's usefulness and market price compared with selling it raw."),
_q("Which of the following best explains why storage facilities are important in agricultural marketing?",
      ["They help reduce post-harvest losses and allow produce to be sold when prices are more favourable", "They permanently prevent any produce from ever being sold", "They eliminate the need for transportation of produce to market", "They automatically increase the biological yield of the next planting season"],
      "They help reduce post-harvest losses and allow produce to be sold when prices are more favourable",
      "Proper storage protects harvested produce from spoilage and pests while giving farmers flexibility to sell later when market prices improve, rather than being forced to sell immediately."),
_q("Which of the following best describes 'land tenure' as it relates to agriculture?",
      ["The system of rules and rights governing the ownership, holding, and use of land", "The physical fertility level of a particular piece of farmland", "The chemical composition of the topsoil on a farm", "The type of crop that must be grown on a piece of land by law"],
      "The system of rules and rights governing the ownership, holding, and use of land",
      "Land tenure refers to the legal and customary arrangements determining who may own, inherit, lease, or use land, which strongly influences farming decisions and investment."),
_q("Communal land tenure, common in many traditional Nigerian communities, is best described as a system where",
      ["land is owned collectively by a community or family group and allocated to members for use", "each individual holds a government-issued freehold title to their own separate plot", "all farmland belongs exclusively to commercial banks", "land can only be used by foreign investors"],
      "land is owned collectively by a community or family group and allocated to members for use",
      "Under communal tenure, land ownership rests with the community or extended family, with individual members granted use rights rather than full private ownership."),
_q("Which of the following best explains the economic principle of 'opportunity cost' as applied to a farmer's decision to plant maize instead of yam on a plot of land?",
      ["The value of the next best alternative (yam) that is forgone by choosing to plant maize", "The total cost of fertiliser used for the maize crop only", "The market price of maize at harvest time", "The amount of labour required to plant maize"],
      "The value of the next best alternative (yam) that is forgone by choosing to plant maize",
      "Opportunity cost is the benefit of the best alternative given up when a choice is made; here, it is the value of the yam crop foregone by choosing to plant maize instead."),
_q("Which of the following best describes 'agricultural insurance'?",
      ["A scheme that compensates farmers for losses arising from risks such as drought, flood, pests, or disease", "A savings account used exclusively for personal, non-farm expenses", "A tax imposed on farmers who fail to meet production quotas", "A loan given only for the purchase of livestock feed"],
      "A scheme that compensates farmers for losses arising from risks such as drought, flood, pests, or disease",
      "Agricultural insurance protects farmers financially against unpredictable losses from natural disasters, pests, or diseases in exchange for periodic premium payments."),
_q("Grading of agricultural produce before sale is important mainly because it",
      ["classifies produce by quality, allowing fairer pricing and easier marketing", "increases the biological growth rate of the crop after harvest", "eliminates the need for any form of packaging", "reduces the nutritional value of the produce"],
      "classifies produce by quality, allowing fairer pricing and easier marketing",
      "Grading sorts produce into quality categories (e.g., by size or ripeness), enabling buyers to pay appropriate prices and simplifying transactions in the market."),
_q("Which of the following best illustrates 'specialisation' in agricultural production?",
      ["A farmer who focuses exclusively on poultry production rather than growing many different crops and animals", "A farmer who grows ten different crops and keeps five different livestock species on the same small plot", "A farmer who changes their main enterprise every single week", "A farmer who refuses to sell any of their produce"],
      "A farmer who focuses exclusively on poultry production rather than growing many different crops and animals",
      "Specialisation involves concentrating resources and effort on one enterprise (e.g., poultry) to gain efficiency and expertise, rather than spreading effort across many unrelated enterprises."),
_q("Which of the following best describes the function of the Nigerian Commodity Exchange in agricultural marketing?",
      ["Providing an organised platform for the trading of standardised agricultural commodities", "Directly cultivating crops on behalf of the government", "Setting the biological maturity period of every crop", "Replacing the need for farmers to harvest their own produce"],
      "Providing an organised platform for the trading of standardised agricultural commodities",
      "A commodity exchange creates a formal, regulated marketplace where standardised, graded agricultural products can be traded transparently between buyers and sellers."),
];
