import "../quiz_question.dart";

const _subject = "Yoruba";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// Obafemi Awolowo University (OAU) Post-UTME elective bank for Yoruba — 100
/// medium-to-hard questions pitched above the JAMB UTME level, covering Ede
/// (Fonoloji, Girama, Aroko/Ogbufo, Fahimta), Literesọ (oral literature,
/// weighted higher for its cultural depth, and written literature covered
/// only at general/author level), and Asa (beliefs, institutions/rites,
/// values/numerals). This is a general-purpose practice set, not an
/// official OAU past-question paper.
List<QuizQuestion> buildOauYorubaQuestions() {
  return [
    ..._fonoloji,
    ..._girama,
    ..._arokoAtiOgbufo,
    ..._fahimta,
    ..._literesoAlenu,
    ..._literesoKiko,
    ..._eroAtiIgbagbo,
    ..._institutionsAtiRites,
    ..._valuesAtiNumerals,
  ];
}

final _fonoloji = [
  _q("Kini a npe ilana ninu eyi ti ohun kọnsonanti kan ba yipada lati baamu pẹlu ohun ti n bọ leyin rẹ, gẹgẹ bi imu ti n di /m/ ṣaaju /b/ tabi /p/?",
      ["Idọgba ohun (assimilation)", "Isunki vaweli", "Iṣẹda oro", "Ọrọ àyálò"], "Idọgba ohun (assimilation)",
      "Assimilation (idọgba ohun) is the process by which a sound changes to become more similar to a neighbouring sound, as when a nasal becomes homorganic with the following consonant."),
  _q("Kini a npe ohun imu ti o le duro nikan gẹgẹ bi alusilo kan ninu ede Yoruba, bi ninu 'n lọ'?",
      ["Kọnsonanti alusilo (syllabic nasal)", "Diftọngi", "Ami ohun aarin", "Kọnsonanti didapọ"], "Kọnsonanti alusilo (syllabic nasal)",
      "A syllabic nasal is a nasal consonant, such as 'n' in 'n lọ' (is going), that functions as a full syllable on its own without an accompanying vowel."),
  _q("Ninu eto ohun Yoruba, kini a npe iṣẹlẹ ninu eyi ti ohun oke n dinku diẹ sii ju bi o ti ṣe deede nigba ti o ba tẹle ohun isale (downstep)?",
      ["Ẹsẹ ohun (downstep)", "Iparẹ oro", "Idapọ oro", "Ọrọ àyálò"], "Ẹsẹ ohun (downstep)",
      "Downstep is a tonal phenomenon in which a high tone is realised at a lower pitch than a preceding high tone, typically triggered by an intervening low tone, without being marked as a full low tone."),
  _q("Kini a npe apapọ afoniwasi meji ti a n pe gẹgẹ bi ohun kan laarin alusilo kan naa, bi ninu oro 'túulu'?",
      ["Diftọngi (diphthong)", "Kọnsonanti didapọ", "Ami ohun", "Isunki vaweli"], "Diftọngi (diphthong)",
      "A diphthong is a single syllabic sound formed by the combination of two adjacent vowel qualities pronounced within one syllable glide."),
  _q("Kọnsonanti melo ni a maa n ka si i ninu alfabeti Yoruba boṣewa, ti a ba ka awọn to didapọ (digraphs) gẹgẹ bi ẹyọkan?",
      ["Mejidinlogun (18)", "Meje (7)", "Metadinlogun (13)", "Meedogun (25)"], "Mejidinlogun (18)",
      "Standard Yoruba orthography is generally described as having eighteen consonant letters/sounds (including digraphs like gb, ṣ, and the nasal-marked letters), distinct from the seven oral vowels."),
  _q("Kini a npe ilana ninu eyi ti afoniwasi kan n ni ipa lori afoniwasi miran laarin oro kan naa lati je ki won baamu ni ipo bi ẹnu n ṣe si i (vowel harmony)?",
      ["Ibaramu afoniwasi (vowel harmony)", "Idọgba ohun", "Iparẹ oro", "Alusilo"], "Ibaramu afoniwasi (vowel harmony)",
      "Vowel harmony describes a pattern in which vowels within a word tend to share certain articulatory features, such as advanced or retracted tongue root, influencing how following vowels are pronounced."),
  _q("Kini a npe ohun /w/ ati /y/ ninu ede Yoruba, ti won n ṣiṣẹ bi afara laarin afoniwasi ati kọnsonanti?",
      ["Gigbe ohun (glides/semi-vowels)", "Kọnsonanti didena", "Afoniwasi imu", "Ami ohun isale"], "Gigbe ohun (glides/semi-vowels)",
      "Glides (semi-vowels) such as /w/ and /y/ share properties of both vowels and consonants, often functioning as a transitional sound between a consonant and a following vowel."),
  _q("Ninu ọrọ ' found ehingbe' (bi a se n pe oro Yoruba kan pẹlu ohun imu ṣaaju kọnsonanti bii /b/), kini idi ti /n/ fi n di /m/ ni ilana isọ oro?",
      ["Nitori idọgba ohun pẹlu ipo enu ti kọnsonanti to tele e", "Nitori a fẹ yi itumọ oro naa pada", "Nitori ami ohun n fẹ ki a ṣe bẹẹ", "Nitori ko si idi fonẹtiki kankan"], "Nitori idọgba ohun pẹlu ipo enu ti kọnsonanti to tele e",
      "A nasal typically assimilates to the place of articulation of a following consonant (e.g. becoming bilabial /m/ before a bilabial stop like /b/ or /p/), a purely phonetic conditioning, not a semantic one."),
  _q("Kini a npe atunkọ oro kan patapata tabi apakan rẹ lati fi han itumọ tuntun tabi lati fun un lokun, gẹgẹ bi 'wewe' lati 'wẹ'?",
      ["Atunsọ oro (reduplication)", "Isunki vaweli", "Iparẹ oro", "Idọgba ohun"], "Atunsọ oro (reduplication)",
      "Reduplication is a morphophonological process in which part or all of a root is repeated to form a new word, often intensifying meaning or forming derived nominal/adjectival forms."),
  _q("Ninu itupale ohun ti ede Yoruba, kini a npe ẹsẹ kan ti a n pe ni ohun ti n rọra gòkè lati ipo isale de ipo oke ninu alusilo kan naa (rising glide tone)?",
      ["Ohun ti n gòkè (rising/gliding tone)", "Ohun titọ (level tone)", "Iparẹ oro", "Kọnsonanti didena"], "Ohun ti n gòkè (rising/gliding tone)",
      "Beyond the three basic level tones, Yoruba also exhibits gliding (contour) tones, where the pitch rises or falls within a single syllable, often realised on certain vowel sequences."),
];

final _girama = [
  _q("Kini a npe ami ti a n lo ṣaaju oro-ise lati fi han pe iṣẹ kan n lọ lọwọ lọwọlọwọ, gẹgẹ bi 'ń' ninu 'Ó ń jẹun'?",
      ["Ami akoko lilọsiwaju (progressive aspect marker)", "Ami akoko ti o ti kọja", "Ami odi (negation marker)", "Ami ifiweranṣẹ (focus marker)"], "Ami akoko lilọsiwaju (progressive aspect marker)",
      "The marker 'ń' preceding a verb indicates the progressive aspect, showing that an action is currently ongoing, as in 'Ó ń jẹun' (He/she is eating)."),
  _q("Kini a npe oro ti a n lo lati fi kọ iṣe kan silẹ ninu gbolohun Yoruba, bi 'kò' ninu 'Kò lọ sí ọjà'?",
      ["Ami odi (negation marker)", "Ami akoko", "Oro-asopọ", "Oro-atokun"], "Ami odi (negation marker)",
      "'Kò' functions as a negation marker in Yoruba, placed before the verb to negate the action, as in 'Kò lọ sí ọjà' (He/she did not go to the market)."),
  _q("Kini a npe oro ti a n gbe siwaju gbolohun tabi apa kan gbolohun lati tẹnu mọ ọn, bi 'ni' ninu 'Adé ni ó lọ'?",
      ["Ami ifiweranṣẹ (focus marker)", "Ami odi", "Oro-nfiropo", "Oro-aponle"], "Ami ifiweranṣẹ (focus marker)",
      "'Ni' functions as a focus marker in Yoruba, drawing emphasis to the element it follows, as in 'Adé ni ó lọ' (It was Adé who went)."),
  _q("Kini a npe iru gbolohun ninu eyi ti oro-ise meji tabi ju bẹẹ lọ ba wa ni itẹlera lai ni oro-asopọ laarin won lati fi han iṣẹlẹ kan naa, bi 'Ó mu ọbẹ gé eran'?",
      ["Gbolohun oro-ise didapọ (serial verb construction)", "Gbolohun aṣẹ", "Gbolohun iyanu", "Gbolohun ibeere"], "Gbolohun oro-ise didapọ (serial verb construction)",
      "A serial verb construction strings together two or more verbs sharing a subject and describing a single connected event, without an intervening conjunction, a common feature of Yoruba syntax."),
  _q("Kini a npe ìṣe ti a n lo aṣokọwe 'a-' lati ṣe oro-oruko lati inu oro-ise, bi 'akọrin' lati 'kọrin'?",
      ["Iṣẹda oro pẹlu aṣokọwe (agentive prefixation)", "Idapọ oro", "Ọrọ àyálò", "Ami ohun"], "Iṣẹda oro pẹlu aṣokọwe (agentive prefixation)",
      "Prefixing 'a-' to a verb root is a common Yoruba word-formation strategy that derives an agentive noun, denoting the doer of the action, as in 'akọrin' (singer) from 'kọrin' (to sing)."),
  _q("Kini a npe gbolohun ti n so idi ti nkan kan fi le ṣẹlẹ ti nkan miran ba ti kọkọ ṣẹlẹ, bi 'Bí ó bá rọ̀jò, a kò ní lọ'?",
      ["Gbolohun ipo (conditional sentence)", "Gbolohun idapọ lasan", "Gbolohun aṣẹ", "Gbolohun rọrun"], "Gbolohun ipo (conditional sentence)",
      "A conditional sentence expresses that one event or state depends on another, typically introduced by 'bí' (if), as in 'Bí ó bá rọ̀jò, a kò ní lọ' (If it rains, we will not go)."),
  _q("Kini a npe oro-ise iranlọwọ ti a n fi kun oro-ise akọkọ lati fi han akoko tabi ipo, bi 'máa' ninu 'Yóò máa lọ'?",
      ["Oro-ise iranlọwọ (auxiliary verb)", "Oro-aponle", "Oro-atokun", "Oro-nfiropo"], "Oro-ise iranlọwọ (auxiliary verb)",
      "An auxiliary verb supports the main verb to express aspects such as habitual or future continuous action, as in 'máa' combined with a main verb."),
  _q("Kini a npe ẹka gbolohun ti n ṣàpèjúwe oro-oruko siwaju sii, ti a n bere pẹlu oro-nfiropo ibatan bi 'tí', bi ninu 'Ọkunrin tí ó wọ aṣọ pupa'?",
      ["Gbolohun ibatan (relative clause)", "Gbolohun aṣẹ", "Gbolohun ipo", "Gbolohun idapọ"], "Gbolohun ibatan (relative clause)",
      "A relative clause, introduced in Yoruba by 'tí', provides additional descriptive information about a preceding noun, as in 'Ọkunrin tí ó wọ aṣọ pupa' (The man who wore a red garment)."),
  _q("Kini a npe iṣẹ ti a n ṣe lati fi han pe iṣẹ kan ti n lọ lọwọ ni akoko to ti kọja, gẹgẹ bi 'ń' pẹlu 'ti' ninu 'Ó ti ń kọ ẹkọ'?",
      ["Akoko ti n lọ lọwọ ni ti kọja (past progressive)", "Akoko lọwọlọwọ lasan", "Akoko ọjọ iwaju", "Ami odi"], "Akoko ti n lọ lọwọ ni ti kọja (past progressive)",
      "Combining 'ti' with the progressive marker 'ń' before a verb conveys that an action was already ongoing at a past reference point, a past progressive construction."),
  _q("Kini a npe ọna ti a n fi ṣe afiwe iye tabi didara nkan meji ninu ede Yoruba, gẹgẹ bi lilo 'ju' ninu 'Ó ga ju ẹgbọn rẹ̀ lọ'?",
      ["Gbolohun afiwe (comparative construction)", "Gbolohun ipo", "Gbolohun ibatan", "Gbolohun aṣẹ"], "Gbolohun afiwe (comparative construction)",
      "Comparative constructions in Yoruba are commonly formed using 'ju...lọ', expressing that one entity exceeds another in a given quality, as in 'Ó ga ju ẹgbọn rẹ̀ lọ' (He/she is taller than his/her elder sibling)."),
  _q("Kini a npe oro ti a n lo lati ṣe apejuwe ohun tabi iṣe pẹlu ohun ti n fara wé bi nkan naa ti n dun tabi ri, bi 'gbagada' fun ohun ti n ṣubu wuwo?",
      ["Ideofoni (ideophone)", "Oro-aponle lasan", "Oro-atokun", "Oro-asopọ"], "Ideofoni (ideophone)",
      "Ideophones are vivid words that evoke sensory impressions such as sound, movement, or manner, widely used in Yoruba to add expressive, descriptive colour to speech."),
  _q("Kini a npe ẹya gbolohun ti a n lo lati fi han pe ẹnikan tabi nkan kan n gba iṣe kan laisi so ẹni ti n ṣe iṣe naa, iru si 'passive voice' ni Gẹẹsi?",
      ["Gbolohun airo-eni-ṣe (impersonal/passive-like construction)", "Gbolohun aṣẹ", "Gbolohun afiwe", "Gbolohun ipo"], "Gbolohun airo-eni-ṣe (impersonal/passive-like construction)",
      "Yoruba lacks a direct grammatical passive voice like English, but achieves a similar effect through impersonal constructions (often using 'a' as a generic subject) that background the agent of the action."),
];

final _arokoAtiOgbufo = [
  _q("Kini a npe iwe ti a n kọ ni ọna girama ti o ye, ti o ni akọle olugba, ọjọ, ati ọwọ olukọ ni ipari, ti a n fi ranṣẹ si ile-iṣẹ tabi oṣiṣẹ kan?",
      ["Iwe iṣẹ (formal/official letter)", "Iwe ẹbẹ si ọrẹ", "Aroko akọọlẹ", "Ewi asọtẹlẹ"], "Iwe iṣẹ (formal/official letter)",
      "A formal/official letter (iwe iṣẹ) follows a structured format with a formal register, addressed to an official recipient, and typically ends with the sender's signature and details."),
  _q("Kini iyato akọkọ laarin iwe si ọrẹ (informal letter) ati iwe iṣẹ (formal letter) ninu ede Yoruba?",
      ["Iwe si ọrẹ n lo ede alaraye ti ko le, iwe iṣẹ si n lo ede to muna ti o tẹle ilana girama pipe", "Ko si iyato kankan laarin awọn mejeeji", "Iwe si ọrẹ gun ju iwe iṣẹ lọ nigbagbogbo", "Iwe iṣẹ ko ni akọle rara"], "Iwe si ọrẹ n lo ede alaraye ti ko le, iwe iṣẹ si n lo ede to muna ti o tẹle ilana girama pipe",
      "An informal letter to a friend uses relaxed, familiar language, while a formal letter maintains a strict, polished register appropriate for official or professional correspondence."),
  _q("Kini a npe ọrọ ti a n ka niwaju ọpọlọpọ eniyan lati gbe ero kan ga tabi lati kilo fun won nipa nkan kan, gẹgẹ bi ọrọ ààrẹ kan?",
      ["Ọrọ ẹnu (public speech)", "Iwe ẹbẹ", "Aroko apejuwe", "Ewi ìfẹ́"], "Ọrọ ẹnu (public speech)",
      "A public speech (ọrọ ẹnu) is a spoken address delivered before an audience, typically aimed at informing, persuading, or motivating listeners on a given subject."),
  _q("Nigba ti a ba n tumọ owe Yoruba kan si Gẹẹsi, kini o le fa iṣoro julọ ti a ko ba ṣọra?",
      ["Isọnu ti itumọ jinlẹ ati aworan ti a fi n gbe ero owe naa jade", "Ọrọ owe naa yoo gun ju bi a ti fẹ lọ", "Ko si iṣoro kankan lati ṣe bẹẹ", "Ede Gẹẹsi ko ni oro fun ẹranko rara"], "Isọnu ti itumọ jinlẹ ati aworan ti a fi n gbe ero owe naa jade",
      "Idiomatic and culturally rich expressions such as proverbs are difficult to translate literally, since a word-for-word rendering often loses the figurative imagery and deeper cultural meaning."),
  _q("Kini a npe aroko ti o n fi awọn ero meji lodi si ara won ki a to yan eyi ti o dara ju, gẹgẹ bi 'Ilu ha dara ju abule lọ?'?",
      ["Aroko ijiyan/ifiwera (argumentative/comparative essay)", "Aroko apejuwe lasan", "Iwe ẹbẹ", "Ewi asọtẹlẹ"], "Aroko ijiyan/ifiwera (argumentative/comparative essay)",
      "An argumentative or comparative essay weighs two sides of an issue against each other before arriving at a reasoned conclusion, as suggested by a topic framed as a question of preference."),
  _q("Kini akọkọ ti a gbọdọ ṣe amojuto nigba ti a n ṣe akopo ìròyìn (report) ninu ede Yoruba lẹhin iṣẹlẹ kan?",
      ["Ki a fi ododo ati alaye to ye kun akopo naa laisi fi ero ara ẹni kun ọrọ naa", "Ki a fi ero ara ẹni ṣàkópọ̀ gbogbo alaye naa", "Ki a fo alaye pataki nipa iṣẹlẹ naa", "Ki a kọ ìròyìn naa ni ede miran ju Yoruba lọ"], "Ki a fi ododo ati alaye to ye kun akopo naa laisi fi ero ara ẹni kun ọrọ naa",
      "A good report should present facts and relevant details objectively, avoiding the intrusion of the writer's personal opinion into what should be a factual account."),
  _q("Kini a npe iru ijiroro ninu eyi ti ẹgbẹ meji n fi ero won lodi si ara won niwaju awọn onidajọ lati jere ariyanjiyan kan?",
      ["Àríyànjiyàn (debate)", "Ọrọ ìtùnú", "Iwe ẹbẹ", "Aroko apejuwe"], "Àríyànjiyàn (debate)",
      "A debate (àríyànjiyàn) is a structured contest in which opposing sides present arguments for and against a motion, judged on the strength and persuasiveness of their reasoning."),
  _q("Kini idi to ye ki a mọ ipele ìjìnlẹ̀ èdè (register) ti o yẹ ki a lo nigba ti a n kọ iwe tabi aroko ninu ede Yoruba?",
      ["Nitori ipele ede to yẹ da lori ẹni ti a n ba sọrọ ati idi ti a fi n kọ ọrọ naa", "Nitori gbogbo iru iwe ni ede kan naa ni a maa n lo", "Nitori ipele ede ko ni ipa lori bi a se n loye ọrọ naa", "Nitori Yoruba ko ni ipele ede oriṣiriṣi"], "Nitori ipele ede to yẹ da lori ẹni ti a n ba sọrọ ati idi ti a fi n kọ ọrọ naa",
      "Choosing the appropriate register matters because the level of formality suited to a piece of writing depends on the intended audience and purpose, whether an official letter or a casual note."),
];

final _fahimta = [
  _q("Kini iyato laarin kika-yára (skimming) ati kika-àyẹ̀wò (scanning) gẹgẹ bi ilana kika ninu idanwo Fahimta?",
      ["Skimming n wa akopo gbogbogbo ẹsẹ, scanning si n wa alaye kan pato ninu rẹ", "Won je ilana kan naa lai si iyato", "Scanning n gba akoko ju skimming lọ nigbagbogbo", "Skimming ni a n lo fun ẹsẹ ẹwi nikan"], "Skimming n wa akopo gbogbogbo ẹsẹ, scanning si n wa alaye kan pato ninu rẹ",
      "Skimming involves reading quickly to grasp the overall gist of a passage, while scanning involves searching rapidly for a specific piece of information within the text."),
  _q("Ti a ba pade oro ti a ko mọ itumọ rẹ ninu ẹsẹ Fahimta, kini ọna to dara julọ lati mọ itumọ rẹ nibẹ?",
      ["Lilo awọn ami inu gbolohun ti o yi oro naa ka (context clues)", "Fifo oro naa kọja patapata", "Yiyipada gbogbo ẹsẹ naa si ede miran", "Lilo itumọ akọkọ ti a ba ti gbọ ri lai wo bi o ṣe baamu"], "Lilo awọn ami inu gbolohun ti o yi oro naa ka (context clues)",
      "When encountering an unfamiliar word, examining the surrounding words and sentence context provides clues that help deduce the most likely intended meaning within that passage."),
  _q("Kini iyato laarin ibeere ti n beere fun koko-ọrọ akọkọ (main idea) ati ibeere ti n beere fun alaye atilẹyin (supporting detail)?",
      ["Ibeere koko-ọrọ akọkọ n beere fun ero gbogbogbo ẹsẹ, ibeere alaye atilẹyin si n beere fun ẹri kan pato ti n gbe koko-ọrọ naa lárugẹ", "Won je ibeere kan naa", "Alaye atilẹyin nikan ni a maa n beere ninu idanwo", "Koko-ọrọ akọkọ ko ṣe pataki ninu ẹsẹ kankan"], "Ibeere koko-ọrọ akọkọ n beere fun ero gbogbogbo ẹsẹ, ibeere alaye atilẹyin si n beere fun ẹri kan pato ti n gbe koko-ọrọ naa lárugẹ",
      "A main-idea question asks for the overall central point of a passage, while a supporting-detail question asks for specific facts or examples that reinforce that central point."),
  _q("Kini a n pe agbara lati mọ idi ti onkọwe fi kọ ẹsẹ kan, boya lati kọ ni, lati mu inu dun, tabi lati yi eniyan loju (author's purpose)?",
      ["Idi onkọwe (author's purpose)", "Ohun orin ẹsẹ (tone) nikan", "Akopo (summary)", "Ibeere amoro"], "Idi onkọwe (author's purpose)",
      "Identifying the author's purpose involves determining whether the writer's primary aim was to inform, entertain, persuade, or otherwise affect the reader, which shapes how a passage should be interpreted."),
  _q("Kini a npe ihuwasi tabi ero inu ọkan onkọwe si koko-ọrọ ti a le mọ lati inu awọn oro ati ara ti won lo ninu ẹsẹ kan (tone)?",
      ["Ohun orin ẹsẹ (tone)", "Idi onkọwe", "Akori", "Ibeere itumọ oro taara"], "Ohun orin ẹsẹ (tone)",
      "Tone refers to the author's attitude toward the subject matter, conveyed through word choice and style, and can be identified by analysing the diction and mood of the passage."),
  _q("Nigba ti a ba n ṣe akopo ẹsẹ kan, kini a gbọdọ yẹra fun ki akopo naa le dara?",
      ["Fifi alaye kekere ti ko ṣe pataki kun akopo naa dipo ki a dojukọ ohun to ṣe pataki julọ", "Lilo oro tiwa ni akopo naa dipo ki a daakọ ẹsẹ naa gangan", "Kika ẹsẹ naa ni kikun ki a to ṣe akopo", "Fifi ero wa nipa ẹsẹ naa han ni kedere"], "Fifi alaye kekere ti ko ṣe pataki kun akopo naa dipo ki a dojukọ ohun to ṣe pataki julọ",
      "A good summary should focus on the most essential points of the passage and avoid cluttering it with minor, non-essential details that dilute the central message."),
  _q("Kini a npe lilo ede ti ko ni itumọ taara, bi apejuwe tabi afiwe, ti onkọwe fi n gbe ero jinlẹ jade ninu ẹsẹ ẹwi?",
      ["Ede afiwe/aworan (figurative language/imagery)", "Ede taara lasan", "Ami ohun", "Ọrọ àyálò"], "Ede afiwe/aworan (figurative language/imagery)",
      "Figurative language and imagery use non-literal expressions such as comparisons and vivid description to evoke deeper meaning or sensory impressions, common in poetic passages."),
  _q("Ti akẹkọ kan ba n ka ẹsẹ pipẹ kan fun idanwo Fahimta ti akoko rẹ ko pẹ, kini ilana to dara julọ ki o le dahun ibeere daradara?",
      ["Ki o kọkọ ka ibeere naa ki o to ka ẹsẹ naa, ki o le mọ ohun to yẹ ki o wa fun", "Ki o kọ ẹsẹ tuntun dipo ẹsẹ ti a fun un", "Ki o fo gbogbo ẹsẹ naa ki o dahun lati inu amoro lasan", "Ki o ka ẹsẹ naa ni ẹẹkan lai wo ibeere rara"], "Ki o kọkọ ka ibeere naa ki o to ka ẹsẹ naa, ki o le mọ ohun to yẹ ki o wa fun",
      "Previewing the questions before reading the passage helps a student focus their reading on the specific information needed to answer accurately, an efficient strategy under time pressure."),
];

final _literesoAlenu = [
  _q("Kini a npe akojọpọ owe ti a n lo lati kọ awọn ọmọde iwa rere nipasẹ apeere ti a fi ẹranko ṣe, gẹgẹ bi itan Ijapa?",
      ["Alọ apamọ (didactic animal folktale)", "Ofo aabo", "Oriki-orile", "Ewi ìfẹ́"], "Alọ apamọ (didactic animal folktale)",
      "Animal folktales, often featuring the trickster tortoise Ijapa, are a form of oral narrative used to teach moral lessons to children through entertaining, symbolic stories."),
  _q("Kini ipa ti Ijapa (tortoise) n ṣe ojukokoro ninu ọpọlọpọ itan alọ apamọ Yoruba?",
      ["Ẹranko ọlọgbọn ẹrẹ (trickster) ti ojukokoro rẹ maa n mu u wọ wahala", "Ẹranko akikanju ti ko sise aṣiṣe rara", "Ẹranko ti n dari gbogbo awọn ẹranko miran ni alaafia", "Ẹranko ti ko fi ọgbọn han rara"], "Ẹranko ọlọgbọn ẹrẹ (trickster) ti ojukokoro rẹ maa n mu u wọ wahala",
      "Ijapa (the tortoise) is a classic trickster figure in Yoruba folktales, celebrated for cunning but whose greed or overconfidence frequently leads him into trouble, teaching cautionary lessons."),
  _q("Kini a npe iru orin oriki pataki ti a n ka fun ode tabi ọdẹ ni asa Yoruba, ti n yin igboya ati agbara won?",
      ["Ìjálá (hunters' chant)", "Rara Ìyàwó", "Ẹsẹ Ifá", "Ofo Ọsanyìn"], "Ìjálá (hunters' chant)",
      "Ìjálá is a distinctive genre of chanted oral poetry traditionally performed by and for hunters, praising courage, skill, and the deity Ogun associated with hunting and iron."),
  _q("Kini a npe iru orin ìyìn ti a n ka fun iyawo ni ọjọ igbeyawo ninu asa Yoruba?",
      ["Rárà Ìyàwó (bride's chant)", "Ìjálá", "Ẹsẹ Ifá", "Ekun Iyawo lasan laisi orin"], "Rárà Ìyàwó (bride's chant)",
      "Rárà Ìyàwó is a chanted praise performance for the bride during traditional Yoruba wedding ceremonies, celebrating her lineage, beauty, and the union taking place."),
  _q("Kini a npe ẹsẹ oríkì Ifá to gun ti awọn Babalawo n lo fun asọtẹlẹ, ti o ni ọpọlọpọ itan ati owe ninu rẹ?",
      ["Ẹsẹ Ifá (Ifa divination verses)", "Rárà Ìyàwó", "Oriki-orile", "Ewi ìfẹ́"], "Ẹsẹ Ifá (Ifa divination verses)",
      "Ẹsẹ Ifá are the extensive corpus of chanted verses used within Ifa divination, each associated with a specific Odù and containing narratives, proverbs, and moral instruction."),
  _q("Kini iyato laarin owe ati ọ̀rọ̀ àpọ́nlé (epithet) ninu Litereso Alenu Yoruba?",
      ["Owe je ọgbọn ti a le lo ni ipo pupọ, ọ̀rọ̀ àpọ́nlé si je oruko iyin ti a fi si ẹnikan tabi nkan pato", "Won je ohun kan naa patapata", "Ọ̀rọ̀ àpọ́nlé nikan ni a n lo ninu oriki", "Owe nikan ni a n lo ninu itan-itan"], "Owe je ọgbọn ti a le lo ni ipo pupọ, ọ̀rọ̀ àpọ́nlé si je oruko iyin ti a fi si ẹnikan tabi nkan pato",
      "A proverb is a general piece of transferable wisdom applicable across many situations, while an epithet is a specific descriptive praise-name attached to a particular person, deity, or thing."),
  _q("Kini a npe itan alaye gigun ti a n so ni ẹnu nipa idasile ilu, idile, tabi baba nla kan ninu asa Yoruba (legend)?",
      ["Ìtàn àtẹnudẹ́nu (legend)", "Alọ ọlọgbọn", "Ofo", "Owe kukuru"], "Ìtàn àtẹnudẹ́nu (legend)",
      "A legend (ìtàn àtẹnudẹ́nu) is a longer orally transmitted narrative recounting the founding of a town, lineage, or the exploits of an ancestral figure, passed down through generations."),
  _q("Kini idi to fa ki ọpọlọpọ owe Yoruba lo apeere ẹranko tabi iseda lati fi ọgbọn han, gẹgẹ bi 'Ọmọ ológìní kì í dàgbà ká má mọ pa eku'?",
      ["Nitori apeere ẹranko ati iseda n so ero jinlẹ di irorun lati ranti ati loye", "Nitori awọn Yoruba atijọ ko ni oye eniyan miran lati fi ṣe apeere", "Nitori ẹranko nikan ni owe Yoruba n so nipa rẹ", "Nitori a fẹ dojukọ imọ-ẹrọ ẹranko"], "Nitori apeere ẹranko ati iseda n so ero jinlẹ di irorun lati ranti ati loye",
      "Using vivid, familiar imagery from animals and nature makes abstract wisdom easier to remember, visualise, and pass down accurately through oral tradition."),
  _q("Kini a npe ilana ninu eyi ti a n lo ibeere ati idahun laarin akorin ati ẹgbẹ akọrin lati ṣe orin ibile Yoruba (call-and-response)?",
      ["Ipè-àti-ìdáhùn (call-and-response)", "Iṣẹda oro", "Isunki vaweli", "Ẹsẹ ohun"], "Ipè-àti-ìdáhùn (call-and-response)",
      "Call-and-response is a common performance structure in Yoruba oral music and chants, where a lead singer's phrase is answered by a chorus, reinforcing communal participation."),
  _q("Kini a npe orin ẹkún ti a n ka nigba isinku lati ṣàpèjúwe ibinujẹ ati lati yin ẹni ti o ku ninu asa Yoruba?",
      ["Ẹkún Àyájọ́/Ẹkún Ikú (dirge/funeral lament)", "Rárà Ìyàwó", "Ìjálá", "Ewi ìfẹ́"], "Ẹkún Àyájọ́/Ẹkún Ikú (dirge/funeral lament)",
      "A dirge (ẹkún ikú) is a mournful chant performed at funerals, expressing grief while also honouring and praising the life and achievements of the deceased."),
  _q("Ninu itan alọ apamọ, kini a maa n pe ẹkọ ti a n fẹ ki awọn ọmọdé rí kọ ni ipari itan naa?",
      ["Ẹkọ iwa (moral lesson)", "Akọle itan naa nikan", "Oruko akọrin naa", "Ọjọ ti a ti kọ itan naa"], "Ẹkọ iwa (moral lesson)",
      "Folktales are typically structured to conclude with an explicit or implicit moral lesson, the key teaching point the storyteller wants the audience, especially children, to internalise."),
  _q("Kini a npe oriki ti a n ki fun ilu tabi agbegbe kan pato lati fi han itan ati iyi ilu naa?",
      ["Oriki-ilu (town praise chant)", "Oriki-orile", "Rárà Ìyàwó", "Ẹsẹ Ifá"], "Oriki-ilu (town praise chant)",
      "Oriki-ilu are praise chants dedicated specifically to a town or community, celebrating its history, founders, and notable attributes distinct from lineage-based oriki-orile."),
  _q("Kini a npe alọ ti idahun rẹ n nilo agbọye ede meji tabi ilaluja oro (pun/wordplay) lati yanju?",
      ["Alọ arọ́ (wordplay riddle)", "Owe lasan", "Ofo iwosan", "Oriki-orile"], "Alọ arọ́ (wordplay riddle)",
      "Some Yoruba riddles rely specifically on double meanings, puns, or clever wordplay for their solution, testing not just logic but also linguistic dexterity."),
  _q("Kini idi ti Ìjálá fi ni ibatan pẹkipẹki pẹlu Ògún ninu asa Yoruba?",
      ["Nitori Ògún ni orisa awọn ọdẹ ati alagbede, ti Ìjálá n yin fun agbara ati akikanju", "Nitori Ògún ko ni ibatan kankan pẹlu ọdẹ", "Nitori Ìjálá je orin fun igbeyawo nikan", "Nitori Ògún je orisa omi"], "Nitori Ògún ni orisa awọn ọdẹ ati alagbede, ti Ìjálá n yin fun agbara ati akikanju",
      "Ògún, as the deity of iron, war, and hunting, is closely tied to hunters, and Ìjálá chants traditionally invoke and honour him alongside celebrating the hunters' own valour."),
  _q("Kini a npe itan ti a n so lati salaye idi ti nkan kan fi ri bi o ti ri ninu iseda, gẹgẹ bi idi ti ijapa fi ni ikarahun (etiological/origin tale)?",
      ["Ìtàn àlọ́ àyọrísí (origin/etiological tale)", "Owe kukuru", "Oriki-orile", "Ẹsẹ Ifá"], "Ìtàn àlọ́ àyọrísí (origin/etiological tale)",
      "Etiological (origin) tales are a folktale subtype that explain how or why a particular natural feature or animal characteristic came to be, blending entertainment with explanation."),
  _q("Kini agbekalẹ ti o wọpọ ni ibẹrẹ ọpọlọpọ itan alọ apamọ Yoruba lati fi han pe itan naa n bẹrẹ (opening formula)?",
      ["'Alo o!' pẹlu idahun 'Alo!'", "Ìkíni oríkì", "Ìpè fún àdúrà", "Ìkéde ìsìnkú"], "'Alo o!' pẹlu idahun 'Alo!'",
      "Yoruba folktale performances traditionally begin with a formulaic call from the narrator ('Alo o!') answered by the audience ('Alo!'), signalling the start of the storytelling session."),
  _q("Kini a npe oríkì ti a n ki fun orisa kan pato, gẹgẹ bi Ṣàngó tabi Ọya, ti n ṣàpèjúwe agbara ati iwa won?",
      ["Oríkì Òrìṣà (deity praise chant)", "Oriki-ilu", "Rárà Ìyàwó", "Ẹkún Ikú"], "Oríkì Òrìṣà (deity praise chant)",
      "Oríkì Òrìṣà are specialised praise chants dedicated to a specific deity, describing that deity's unique powers, attributes, and mythological exploits."),
  _q("Kini idi ti alọ (riddle) fi ka si ohun elo ẹkọ ti o wulo fun ọmọde ninu asa Yoruba, ju bi ere idaraya lasan?",
      ["O n ṣe idagbasoke agbara ero ero-jinlẹ ati oye ede laarin awọn ọmọde", "Ko ni anfani eyikeyi ju idaraya lọ", "O n kọ ọmọde ni iṣiro giga nikan", "O n kọ ọmọde ni ede ajeji nikan"], "O n ṣe idagbasoke agbara ero ero-jinlẹ ati oye ede laarin awọn ọmọde",
      "Beyond entertainment, riddles help sharpen children's reasoning, observation, and linguistic skills, functioning as an informal but effective educational tool in traditional society."),
  _q("Kini a npe orin tabi ẹsẹ ti a n ka lati fi ìfẹ́ ẹnikan han fun olólùfẹ́ rẹ ninu Litereso Alenu Yoruba?",
      ["Ewi ìfẹ́ (love chant/poem)", "Ẹkún Ikú", "Ìjálá", "Ẹsẹ Ifá"], "Ewi ìfẹ́ (love chant/poem)",
      "Love chants or poems (ewi ìfẹ́) form a distinct genre of Yoruba oral poetry, expressing romantic affection and admiration for a beloved."),
  _q("Kini a npe ihuwasi ti a maa n so mọ Ṣàngó ninu awọn oriki ti a n ki fun un, ti n ṣàfihàn agbara rẹ?",
      ["Ìbínú líle, agbára ãrá àti mọ̀nàmọ́ná", "Ẹ̀mí ìrẹ̀lẹ̀ àti ìdákẹ́jẹ́ẹ́", "Ìfẹ́ fún òkun àti odò nìkan", "Ìfẹ́ fún iṣẹ́-àgbẹ̀ nìkan"], "Ìbínú líle, agbára ãrá àti mọ̀nàmọ́ná",
      "Oríkì praising Ṣàngó typically emphasise his fierce temper and formidable power over thunder and lightning, hallmarks of his mythological character."),
  _q("Kini a npe iṣẹ́ akorin akọkọ ti n dari ijọ ni ijo Egúngún tabi ninu ijo ijálá, ti n bẹrẹ ọrọ akọkọ fun ẹgbẹ lati dahun?",
      ["Aṣáájú-orin/olùpè (lead chanter/caller)", "Onílù (drummer) nikan", "Olùgbọ́ lasan", "Babaláwo nikan"], "Aṣáájú-orin/olùpè (lead chanter/caller)",
      "In call-and-response performances such as Egúngún chants or Ìjálá, a lead chanter (aṣáájú-orin) initiates each line or phrase for the assembled group or chorus to respond to."),
  _q("Kini idi ti ọpọlọpọ owe Yoruba fi n gbe itumọ meji jade — itumọ gangan ati itumọ ìjìnlẹ̀ (literal and figurative)?",
      ["Nitori won n lo apeere gidi lati kọ́ni ẹkọ nipa ipo igbesi aye ti o gbooro ju itumọ gangan lọ", "Nitori a fẹ da eniyan loju ni gbogbo igba", "Nitori itumọ gangan nikan ni o ṣe pataki", "Nitori itumọ ìjìnlẹ̀ ko wulo rara"], "Nitori won n lo apeere gidi lati kọ́ni ẹkọ nipa ipo igbesi aye ti o gbooro ju itumọ gangan lọ",
      "Proverbs typically operate on two levels: a literal surface scenario and a broader figurative lesson about life, allowing a concrete image to teach an abstract truth."),
];

final _literesoKiko = [
  _q("Kini a n pe iṣẹ litereso ti a kọ ni ọna arọ (prose) gigun ti o ni itan pipe pẹlu ohun kikọ pupọ, gẹgẹ bi aramada Yoruba?",
      ["Aramada/Aroso (novel)", "Ewi kukuru", "Eré oníṣe (drama)", "Owe kan ṣoṣo"], "Aramada/Aroso (novel)",
      "A novel (aramada/aroso) is an extended prose narrative with a full plot and developed characters, one of the major genres within Yoruba written literature."),
  _q("Kini a n pe onkọwe olokiki ti a mọ julọ fun aramada 'Ògbójú Ọdẹ Nínú Igbó Irúnmalẹ̀' ninu litereso kiko Yoruba?",
      ["D.O. Fagunwa", "Akinwunmi Isola", "Adebayo Faleti", "Afolabi Olabimtan"], "D.O. Fagunwa",
      "D.O. Fagunwa is widely regarded as a foundational figure in written Yoruba literature, celebrated for pioneering fantastical adventure novels such as 'Ògbójú Ọdẹ Nínú Igbó Irúnmalẹ̀'."),
  _q("Kini a n pe eré ti a kọ sile lati ṣe lori itage, ti o ni ipin (acts) ati apá (scenes) ninu rẹ?",
      ["Eré oníṣe (drama/play)", "Aramada", "Ewi arọ", "Iwe akọọlẹ ara ẹni"], "Eré oníṣe (drama/play)",
      "A play (eré oníṣe) is a written literary work intended for stage performance, structured into acts and scenes, distinct from narrative prose like the novel."),
  _q("Kini a n pe onkọwe ti a mọ fun ọpọlọpọ eré ati fiimu Yoruba, ti a tun mọ si oṣere ati akewi olokiki (fun apẹẹrẹ eré bii 'Kúrunmí')?",
      ["Adebayo Faleti", "D.O. Fagunwa", "Wole Soyinka", "Chinua Achebe"], "Adebayo Faleti",
      "Adebayo Faleti was a prominent Yoruba writer, poet, actor, and broadcaster, well known for his contributions to Yoruba drama, including works such as 'Kúrunmí'."),
  _q("Kini a n pe ẹka ohun kikọ ninu itan tabi eré ti o duro takọtabo pẹlu ẹni akọni (protagonist), ti n mu wahala wa fun un?",
      ["Ọ̀tá/Akọ́tako (antagonist)", "Akọni (protagonist)", "Onítàn (narrator)", "Olùwòran (audience)"], "Ọ̀tá/Akọ́tako (antagonist)",
      "The antagonist is the character or force in direct opposition to the protagonist, driving conflict within the narrative or dramatic plot."),
  _q("Kini a n pe ibi ati akoko ti iṣẹlẹ inu itan tabi eré kan ti n ṣẹlẹ (setting)?",
      ["Ìṣẹ̀lẹ̀-ipò (setting)", "Akori (theme)", "Ohun kikọ (character)", "Ìtàn àyíká (plot summary)"], "Ìṣẹ̀lẹ̀-ipò (setting)",
      "Setting refers to the time and place in which the events of a literary work occur, an important element shaping the mood and context of the narrative."),
  _q("Kini a n pe ilana ti onkọwe fi n ṣàkóso bi itan kan ṣe n bẹrẹ, dagba, ati parí (plot structure)?",
      ["Ìdìtàn/ètò ìtàn (plot structure)", "Akori nikan", "Ohun kikọ nikan", "Ìṣẹ̀lẹ̀-ipò nikan"], "Ìdìtàn/ètò ìtàn (plot structure)",
      "Plot structure encompasses the organised sequence of events in a narrative, typically including exposition, rising action, climax, falling action, and resolution."),
  _q("Kini a n pe akoonu inu eré tabi itan kan ti o de ipele giga julọ ti ìforígbárí, ki o to bẹrẹ si yanju (climax)?",
      ["Ògbóńhìn ìtàn (climax)", "Ìṣáájú ìtàn (exposition)", "Ìparí ìtàn (resolution)", "Ìṣẹ̀lẹ̀-ipò"], "Ògbóńhìn ìtàn (climax)",
      "The climax is the turning point or peak of tension within a narrative or drama, the moment of greatest conflict before the story begins to move toward resolution."),
  _q("Kini a n pe ẹnikan ti n so itan naa fun awọn oluka tabi olugbọ, boya lati oju-iwoye 'emi' tabi 'oun' (narrator)?",
      ["Onítàn (narrator)", "Akọni", "Ọ̀tá", "Olùkọ̀wé alátẹ̀jáde (publisher)"], "Onítàn (narrator)",
      "The narrator is the voice that tells the story to the reader or audience, which may adopt a first-person ('emi') or third-person ('oun') point of view."),
  _q("Kini a n pe iṣẹ litereso kiko kukuru ti o ni ẹsẹ tí a to sọ ọna, ti n lo ede afiwe ati riru (rhythm) lati fi ero han, ti a kọ sile fun kika tabi kikorin?",
      ["Ewi kiko (written poem)", "Aramada", "Eré oníṣe", "Iwe iṣẹ"], "Ewi kiko (written poem)",
      "A written poem (ewi kiko) is a shorter literary composition structured with attention to language, imagery, and rhythm, distinct from prose narratives or drama."),
  _q("Ninu awọn iwe Yoruba ti a n gbaniyanju fun ẹkọ ni ile-iwe girama, kini idi ti a fi n ka Akinwunmi Isola gẹgẹ bi onkọwe pataki?",
      ["Nitori awọn eré ati aramada rẹ, gẹgẹ bi 'Efunsetan Aniwura', ṣàyẹ̀wò ìtàn àti àsà Yorùbá jinlẹ̀", "Nitori o kọ iwe imọ-ẹrọ kọmputa lasan", "Nitori ko kọ ohunkohun ninu ede Yoruba rara", "Nitori o je akewi Gẹẹsi nikan"], "Nitori awọn eré ati aramada rẹ, gẹgẹ bi 'Efunsetan Aniwura', ṣàyẹ̀wò ìtàn àti àsà Yorùbá jinlẹ̀",
      "Akinwunmi Isola is a significant Yoruba writer whose plays and novels, such as 'Efunṣetan Aníwúrà', are noted for their deep historical and cultural exploration of Yoruba society."),
  _q("Kini a n pe iṣẹ litereso kiko ti onkọwe fi n ṣàpèjúwe igbesi aye ara rẹ gan-an ninu iwe (autobiography)?",
      ["Ìtàn ayé ara-ẹni (autobiography)", "Aramada aroso", "Ewi ìfẹ́", "Eré àwàdà"], "Ìtàn ayé ara-ẹni (autobiography)",
      "An autobiography is a written literary account in which the author narrates events and experiences from their own real life, distinct from a fictional novel."),
];

final _eroAtiIgbagbo = [
  _q("Kini a npe igbagbọ ibile Yoruba pe eniyan le tun bi wa si aye leyin iku won, paapa gẹgẹ bi ọmọ inu idile kan naa (reincarnation)?",
      ["Àtúnwáyé (reincarnation)", "Àkúdàáyà", "Emèrè", "Ìpààrọ̀ orí"], "Àtúnwáyé (reincarnation)",
      "Àtúnwáyé is the traditional Yoruba belief that a deceased ancestor's spirit can return to be reborn, often within the same family lineage, distinct from other spirit phenomena like àkúdàáyà."),
  _q("Kini a n pe ẹya ara ọ̀rọ̀ àkóso ayé ẹmi ti a gbagbọ pe ẹnikan yan kadara ara rẹ ṣaaju ki o to wa si aye, ninu igbagbọ ibile Yoruba?",
      ["Orí (personal destiny/inner head)", "Egúngún", "Ògbóni", "Ajẹ́"], "Orí (personal destiny/inner head)",
      "Orí, in traditional Yoruba cosmology, is believed to be the spiritual essence chosen by an individual before birth that determines their destiny and fortune in life."),
  _q("Kini a n pe ẹgbẹ́ àṣírí (secret society) ibile Yoruba ti n ṣe idajọ ati atilẹyin fun oye ninu diẹ ninu awọn ilu Yoruba atijọ?",
      ["Ògbóni", "Egbẹ́ Ọdẹ", "Ẹgbẹ́ Àgbẹ̀", "Ẹgbẹ́ Aṣọ"], "Ògbóni",
      "The Ògbóni society is a traditional Yoruba secret institution historically involved in governance, judicial matters, and supporting the installation and accountability of traditional rulers."),
  _q("Kini a npe irubo tabi ijọsin ti awọn ọmọ ilu n ṣe fun awọn baba nla won ti won gbagbọ pe won pada wa si aye gẹgẹ bi ẹmi, pẹlu ijo eegun ninu asa Yoruba?",
      ["Ẹgbẹ́ Egúngún (ancestral masquerade cult)", "Ẹgbẹ́ Ọsanyìn", "Ẹgbẹ́ Ọdẹ", "Ẹgbẹ́ Agbe"], "Ẹgbẹ́ Egúngún (ancestral masquerade cult)",
      "The Egúngún masquerade cult centres on ancestral veneration, with masked performers believed to embody the spirits of departed ancestors returning to interact with the living community."),
  _q("Kini a npe igbagbọ ibile Yoruba nipa ọmọ ìbejì (twins), pe won ni agbara pataki ti o yatọ si awọn ọmọ miran?",
      ["Ìgbàgbọ́ nípa Ìbejì (twin veneration)", "Ìgbàgbọ́ nípa Ẹmèrè", "Ìgbàgbọ́ nípa Àkúdàáyà", "Ìgbàgbọ́ nípa Ọ̀run-àpáàdì"], "Ìgbàgbọ́ nípa Ìbejì (twin veneration)",
      "Yoruba tradition holds twins (ìbejì) in special spiritual regard, believed to possess unique powers and requiring particular rites and reverence, including the carving of ère ìbejì figures if a twin dies."),
  _q("Kini a n pe agbara ẹ̀mí burúkú ti a gbagbọ pe awọn obinrin kan (paapaa) ni, ti won le lo lati pa eniyan lara laisi lilo ohun elo gidi, ninu igbagbọ ibile Yoruba?",
      ["Àjẹ́ (witchcraft)", "Ifá", "Egúngún", "Ògbóni"], "Àjẹ́ (witchcraft)",
      "Àjẹ́ refers to the traditional Yoruba belief in witchcraft, a spiritual power believed to be wielded, often secretly, to cause harm to others without physical means."),
  _q("Kini a n pe orisa ti a gbagbọ pe o da eniyan ni apẹrẹ lati amọ̀ ni ile-iṣẹ ọrun, ki Olodumare to fi ẹmi sinu wọn?",
      ["Ọbàtálá (Òrìṣà-Ńlá)", "Ṣàngó", "Ògún", "Ẹ̀ṣù"], "Ọbàtálá (Òrìṣà-Ńlá)",
      "Ọbàtálá, also known as Òrìṣà-Ńlá, is traditionally credited in Yoruba belief with moulding the physical form of human beings from clay before Olódùmarè breathes life into them."),
  _q("Kini a n pe orisa omi tútù (odò) ti a gbagbọ pe o ni ibatan pẹkipẹki pẹlu iya ati abo ninu igbagbọ ibile Yoruba, yato si Ọ̀ṣun?",
      ["Yemọja", "Ṣàngó", "Ògún", "Ọya"], "Yemọja",
      "Yemọja is traditionally revered as a maternal river/ocean deity closely associated with motherhood and fertility, distinct from Ọ̀ṣun who is specifically linked to the Osun River."),
  _q("Kini ipa Ẹ̀ṣù n ṣe ninu igbagbọ ibile Yoruba, gẹgẹ bi a se n loye rẹ ninu ẹsin Ifá?",
      ["Onibarasọrọ ati alaṣẹ ẹnu-ọna laarin ọrun ati aye, ti n gbe ẹbọ dé ọ̀dọ̀ àwọn òrìṣà", "Orisa mọnamọna ati ãrá", "Orisa irin ati ogun", "Orisa odo lasan"], "Onibarasọrọ ati alaṣẹ ẹnu-ọna laarin ọrun ati aye, ti n gbe ẹbọ dé ọ̀dọ̀ àwọn òrìṣà",
      "Ẹ̀ṣù is understood in Ifá belief as a divine messenger and gatekeeper who mediates between the spirit world and humanity, delivering sacrifices to the other deities."),
  _q("Kini iyato akọkọ laarin igbagbọ nipa Emèrè ati Àkúdàáyà ninu asa Yoruba ibile?",
      ["Emèrè n tọka si ọmọ ti o ni asopọ pẹlu aiye ẹmi lati ibimọ, Àkúdàáyà si n tọka si ẹni ti o ti ku ti n farahan bi eniyan alaaye", "Won je ohun kan naa gan-an", "Àkúdàáyà nikan ni o ni ibatan pẹlu ọmọde", "Emèrè n tọka si orisa kan, kii ṣe eniyan"], "Emèrè n tọka si ọmọ ti o ni asopọ pẹlu aiye ẹmi lati ibimọ, Àkúdàáyà si n tọka si ẹni ti o ti ku ti n farahan bi eniyan alaaye",
      "Emèrè describes a child spiritually linked to the spirit world from birth, while àkúdàáyà refers to a deceased person believed to reappear and live again among the living, two distinct spirit-related concepts."),
  _q("Kini idi ti Ifá ṣe pataki to gẹgẹ bi ọ̀nà àsọtẹ́lẹ̀ ninu igbesi aye ojoojumọ awọn Yoruba ibile, ju bi ẹ̀sìn lasan?",
      ["O n ran awọn eniyan lọwọ lati mọ ipinnu ti o dara julọ ninu ọrọ igbesi aye, ilera, ati ayanmọ won", "Ko ni ipa kankan lori ipinnu ojoojumọ", "O n dojukọ iṣowo okeere nikan", "O n rọpo gbogbo iru oogun ibile"], "O n ran awọn eniyan lọwọ lati mọ ipinnu ti o dara julọ ninu ọrọ igbesi aye, ilera, ati ayanmọ won",
      "Beyond being a religious system, Ifá divination has traditionally served as a practical guide helping individuals make informed decisions about major life matters, health, and destiny."),
  _q("Kini a n pe ilana ti a gbagbọ pe o le yi ipa-ọna kadara buburu kan pada nipasẹ ẹbọ ati irubo ti Babalawo ba daba, ninu igbagbọ ibile Yoruba?",
      ["Ẹbọ ìrúbọ (sacrificial offering/ritual)", "Ìsọmọlórúkọ", "Ìgbéyàwó", "Ìsìnkú"], "Ẹbọ ìrúbọ (sacrificial offering/ritual)",
      "Making a prescribed sacrificial offering (ẹbọ) is a central practice in traditional Yoruba belief, understood as a means of averting misfortune or securing favourable outcomes as revealed through divination."),
];

final _institutionsAtiRites = [
  _q("Kini a n pe irubo ti a n ṣe ni ọjọ keje tabi ọjọ kẹsan lẹhin ibimọ ọmọ lati fun un ni oruko ninu asa Yoruba?",
      ["Ìsọmọlórúkọ (naming ceremony)", "Ìgbéyàwó", "Ìsìnkú", "Oye jije"], "Ìsọmọlórúkọ (naming ceremony)",
      "Ìsọmọlórúkọ is the traditional Yoruba naming ceremony, typically held about a week after a child's birth, during which the child is formally given names before family and community."),
  _q("Kini a n pe akojọ ohun ti a n lo ni ibile ninu irubo igbeyawo Yoruba, ti o ni obì, ọti, ati owó ninu rẹ, ti idile ọkọ n mu wa fun idile iyawo (bride price items)?",
      ["Owó orí/ẹrù ìyàwó (bride-price items)", "Ẹrù ìsìnkú", "Ẹrù ìsọmọlórúkọ", "Ẹrù oye"], "Owó orí/ẹrù ìyàwó (bride-price items)",
      "Traditional Yoruba marriage rites include the presentation of a customary list of items (bride-price items), such as kola nuts, drinks, and money, from the groom's family to the bride's family."),
  _q("Kini a n pe eto awujọ ibile ti n pin awọn ọmọkunrin sinu ẹgbẹ gẹgẹ bi ọjọ-ori won lati ṣe iṣẹ agbegbe pọ, gẹgẹ bi ẹgbẹ Ẹgbẹ́?",
      ["Ẹgbẹ́ ọjọ-ori (age-grade system)", "Ẹgbẹ́ Ògbóni nikan", "Ẹgbẹ́ Egúngún nikan", "Oye jije nikan"], "Ẹgbẹ́ ọjọ-ori (age-grade system)",
      "The age-grade system traditionally organised young men (and sometimes women) into cohorts by age, who performed communal labour and social duties together within the community."),
  _q("Kini a n pe ipo aṣaaju ti o wa labẹ Oba ninu ilana isakoso ibile diẹ ninu awọn ilu Yoruba, ti n dari agbegbe kekere kan?",
      ["Baálẹ̀ (village/quarter head)", "Babaláwo", "Onílù", "Aláṣọ"], "Baálẹ̀ (village/quarter head)",
      "A Baálẹ̀ is a traditional community or quarter head who administers a smaller settlement or section of a town, typically under the overall authority of the reigning Oba."),
  _q("Kini a n pe àjọyọ̀ ọdọọdún olokiki ni ilu Òsogbo ti n bọlá fun Òrìṣà Ọ̀ṣun, ti o n fa arinrin-ajo lati gbogbo agbaye wa?",
      ["Àjọyọ̀ Ọ̀ṣun Òsogbo (Osun-Osogbo Festival)", "Àjọyọ̀ Ọlọ́jọ́", "Àjọyọ̀ Ẹyọ", "Àjọyọ̀ Ògùn"], "Àjọyọ̀ Ọ̀ṣun Òsogbo (Osun-Osogbo Festival)",
      "The Osun-Osogbo Festival is a major annual traditional festival held in Osogbo honouring the river goddess Ọ̀ṣun, renowned internationally and recognised by UNESCO."),
  _q("Kini a n pe eto ninu eyi ti ọdọmọkunrin kan n gbe pẹlu ọga-iṣẹ kan fun ọpọlọpọ ọdun lati kọ́ iṣẹ ọwọ kan gẹgẹ bi alagbede tabi aṣọ híhun (apprenticeship)?",
      ["Ìkọ́ṣẹ́ (apprenticeship)", "Ìsọmọlórúkọ", "Oye jije", "Ìgbéyàwó"], "Ìkọ́ṣẹ́ (apprenticeship)",
      "Apprenticeship (ìkọ́ṣẹ́) is a traditional system in which a young person lives and trains under a skilled master craftsperson over an extended period to learn a trade."),
  _q("Kini a n pe eniyan ti iṣẹ rẹ ni lati kede iroyin pataki fun gbogbo ilu ni ibile, nigbagbogbo pẹlu ohun elo bi agogo tabi ilu?",
      ["Alágbóhùn-ṣọ́rọ̀/Adáàgbá (town crier)", "Baálẹ̀", "Babaláwo", "Aláṣọ"], "Alágbóhùn-ṣọ́rọ̀/Adáàgbá (town crier)",
      "A town crier traditionally served the important role of publicly announcing news, decrees, or events to the wider community, often using a bell or drum to gather attention."),
  _q("Kini idi to fi je ki Ẹgbẹ́ Ògbóni ṣe pataki ninu ìṣàkóso ìbílẹ̀ diẹ ninu awọn ilu Yoruba, ju bi ẹgbẹ́ àṣírí lasan?",
      ["Won maa n kopa ninu idajọ, imọran fun Oba, ati ìdánimọ̀ oye titun", "Won ko ni ipa kankan ninu isakoso ilu", "Won n dojukọ iṣowo ọjà nikan", "Won n dojukọ ere idaraya lasan"], "Won maa n kopa ninu idajọ, imọran fun Oba, ati ìdánimọ̀ oye titun",
      "Beyond secrecy, the Ògbóni society traditionally played a substantive governance role, involved in judicial matters, advising the Oba, and legitimising chieftaincy appointments in some Yoruba towns."),
];

final _valuesAtiNumerals = [
  _q("Bawo ni a se ka nọmba 'mẹẹdogun' (15) ninu ede Yoruba?",
      ["Mẹẹdógún", "Ogún", "Mẹẹdọgbọn", "Ẹẹdẹgbẹta"], "Mẹẹdógún",
      "'Mẹẹdógún' is the Yoruba word for fifteen, formed on the vigesimal base pattern (literally 'five short of twenty')."),
  _q("Bawo ni a se ka nọmba 'aadọta' (45) ninu ede Yoruba, ti a mọ pe eto kika Yoruba n lo idinku (subtraction) fun awọn nọmba kan?",
      ["Aadọta din márùn-ún", "Aadọta lé márùn-ún", "Ọgọ́ta", "Ogójì"], "Aadọta din márùn-ún",
      "The Yoruba numeral system often uses a subtractive pattern for certain numbers approaching a round base; 45 is expressed as 'aadọta din márùn-ún', literally 'fifty minus five'."),
  _q("Bawo ni a se ka nọmba 'ọgọ́rùn-ún méjì' (200) ninu ede Yoruba?",
      ["Igba", "Ọgọ́rùn-ún", "Irínwó", "Ẹgbẹ̀ta"], "Igba",
      "'Igba' is the distinct traditional Yoruba word for two hundred, illustrating how certain multiples in the vigesimal system have unique standalone names rather than simple compounding."),
  _q("Kini a n pe iye Omoluabi ti n fi otitọ ọrọ sisọ ati iwa han ni gbogbo ipo, laisi ẹ̀tàn?",
      ["Òtítọ́ (truthfulness/honesty)", "Ìwà ipá", "Ọ̀làjú lásán", "Ìjàmbá"], "Òtítọ́ (truthfulness/honesty)",
      "Truthfulness (òtítọ́) is one of the core values expected of an Ọmọlúàbí, emphasising honesty and integrity in speech and conduct."),
  _q("Kini a n pe ọ̀nà ìbọ̀wọ̀ ti a n fi n kí àgbà ọkùnrin nípa dídọ̀bálẹ̀ (prostrating) ninu asa Yoruba?",
      ["Ìdọ̀bálẹ̀ (prostration)", "Ìkúnlẹ̀ (kneeling)", "Ìkíni ọwọ́ (handshake)", "Ìtẹríba orí lásán"], "Ìdọ̀bálẹ̀ (prostration)",
      "Ìdọ̀bálẹ̀ (full prostration) is the traditional gesture of deep respect performed by males when greeting elders or superiors in Yoruba culture, distinct from the kneeling (ìkúnlẹ̀) typically performed by females."),
  _q("Kini a n pe ọ̀nà ìbọ̀wọ̀ ti a n fi n kí àgbà obìnrin nípa kíkúnlẹ̀ (kneeling) ninu asa Yoruba?",
      ["Ìkúnlẹ̀ (kneeling)", "Ìdọ̀bálẹ̀", "Ìjókòó lásán", "Ìdúró tì"], "Ìkúnlẹ̀ (kneeling)",
      "Ìkúnlẹ̀ (kneeling) is the customary gesture of respect traditionally performed by females when greeting elders in Yoruba society, paralleling the male gesture of prostration."),
  _q("Kini a n pe imọran to wa ninu owe Yoruba 'Ajọbí kìí burú kó tán' nipa iye ìdílé àti ìbáṣepọ̀ ẹ̀jẹ̀?",
      ["Ìdílé kìí já pátápátá bí ó ti wù kí ìṣòro tó pọ̀ tó láàrin àwọn ọmọ ìdílé", "Ìdílé kò ní ìtumọ̀ kankan mọ́ ní àkókò ìsọ̀de-òní", "Ẹ̀jẹ̀ ìbátan kò ṣe pàtàkì rárá", "Owe yìí ń sọ̀rọ̀ nípa iṣẹ́-àgbẹ̀ nìkan"], "Ìdílé kìí já pátápátá bí ó ti wù kí ìṣòro tó pọ̀ tó láàrin àwọn ọmọ ìdílé",
      "This proverb conveys the value that family bonds, however strained, are never entirely severed, reflecting the deep importance placed on kinship (ajọbí) in Yoruba society."),
  _q("Kini a n pe iye Omoluabi ti n fi ìtẹríba fún àwọn òfin àti ìlànà àwùjọ hàn, kì í ṣe ìṣọ̀tẹ̀ sí wọn?",
      ["Ìgbọràn (obedience/compliance to social order)", "Ìlara", "Ìtanjẹ", "Ìṣàkúsà"], "Ìgbọràn (obedience/compliance to social order)",
      "Obedience and respect for established social order (ìgbọràn) is regarded as an important Ọmọlúàbí trait, reflecting cooperation with communal norms and authority."),
];
