import "../quiz_question.dart";

const _subject = "Physics";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// Obafemi Awolowo University (OAU) Post-UTME Physics practice bank — 100
/// medium-to-hard, heavily calculation-based questions covering the 13 core
/// Post-UTME/UTME Physics topics: Measurements & Units, Scalars & Vectors,
/// Motion/Kinematics, Gravitational Field, Equilibrium of Forces,
/// Work/Energy/Power, Friction & Simple Machines, Properties of Matter,
/// Thermal Physics, Waves & Sound, Optics, Electricity & Magnetism, and
/// Modern Physics. This is a general practice set, not an official OAU past
/// paper; always confirm the exact format on OAU's own screening portal.
List<QuizQuestion> buildOauPhysicsQuestions() {
  return [
    ..._measurementsUnits,
    ..._scalarsVectors,
    ..._motion,
    ..._gravitationalField,
    ..._equilibriumForces,
    ..._workEnergyPower,
    ..._frictionSimpleMachines,
    ..._propertiesOfMatter,
    ..._thermalPhysics,
    ..._wavesSound,
    ..._optics,
    ..._electricityMagnetism,
    ..._modernPhysics,
  ];
}

final _measurementsUnits = [
  _q("A metre rule is used to measure the length of a wire and gives a reading of 24.65 cm. If the zero error of the rule is +0.05 cm, what is the corrected length?",
      ["24.60 cm", "24.70 cm", "24.65 cm", "24.55 cm"], "24.60 cm",
      "For a positive zero error, the correction is subtracted: 24.65 - 0.05 = 24.60 cm."),
  _q("The reading on a Vernier caliper has a main scale value of 3.2 cm and a Vernier scale coincidence at the 4th division (least count 0.01 cm). What is the total reading?",
      ["3.24 cm", "3.20 cm", "3.40 cm", "3.04 cm"], "3.24 cm",
      "Total reading = main scale + (Vernier division x least count) = 3.2 + (4 x 0.01) = 3.24 cm."),
  _q("A micrometer screw gauge has a pitch of 0.5 mm and 50 divisions on its thimble. What is its least count?",
      ["0.01 mm", "0.001 mm", "0.1 mm", "0.05 mm"], "0.01 mm",
      "Least count = pitch / number of divisions = 0.5/50 = 0.01 mm."),
  _q("The density of a metal block of mass 540 g and volume 60 cm3 is",
      ["9 g/cm3", "6 g/cm3", "0.11 g/cm3", "90 g/cm3"], "9 g/cm3",
      "Density = mass/volume = 540/60 = 9 g/cm3."),
  _q("Express 0.0007821 to 3 significant figures.",
      ["0.000782", "0.00078", "0.000780", "0.0008"], "0.000782",
      "Counting from the first non-zero digit, the first three significant figures are 7, 8, 2, rounding gives 0.000782."),
  _q("Which of the following is a base S.I. quantity?",
      ["Luminous intensity", "Force", "Pressure", "Energy"], "Luminous intensity",
      "Luminous intensity (candela) is one of the seven S.I. base quantities; force, pressure, and energy are all derived quantities."),
  _q("The dimension of pressure (force/area) is",
      ["ML-1T-2", "MLT-2", "ML2T-2", "ML-2T-1"], "ML-1T-2",
      "Pressure = force/area = (MLT-2)/L2 = ML-1T-2."),
  _q("A student records five readings of the period of a pendulum as 2.0 s, 2.1 s, 1.9 s, 2.0 s, and 2.0 s. What is the mean period?",
      ["2.0 s", "2.1 s", "1.9 s", "2.2 s"], "2.0 s",
      "Mean = (2.0+2.1+1.9+2.0+2.0)/5 = 10.0/5 = 2.0 s."),
  _q("Which combination of fundamental quantities gives the S.I. unit of energy?",
      ["kg m2 s-2", "kg m s-1", "kg m-1 s-2", "kg m2 s-1"], "kg m2 s-2",
      "Energy (joule) = force x distance = (kg m s-2)(m) = kg m2 s-2."),
  _q("Two lengths, 12.4 cm and 3.65 cm, are measured with instruments of different precision. Expressed to the correct number of significant figures, their sum is",
      ["16.1 cm", "16.05 cm", "16.0 cm", "16.05 cm"], "16.1 cm",
      "The least precise value (12.4 cm, 1 decimal place) limits the result, so the sum 16.05 cm is rounded to 16.1 cm."),
];

final _scalarsVectors = [
  _q("A boy walks 8 m east and then 6 m north. What is the magnitude of his resultant displacement?",
      ["10 m", "14 m", "2 m", "48 m"], "10 m",
      "Resultant = sqrt(8^2 + 6^2) = sqrt(64+36) = sqrt(100) = 10 m."),
  _q("Two forces of 6 N and 8 N act at right angles at a point. The angle the resultant makes with the 8 N force is",
      ["36.9 degrees", "53.1 degrees", "45 degrees", "60 degrees"], "36.9 degrees",
      "tan(theta) = opposite/adjacent = 6/8 = 0.75, so theta = arctan(0.75) = 36.9 degrees from the 8 N force."),
  _q("A force of 20 N acts at 60 degrees to the horizontal. Its vertical component is approximately",
      ["17.3 N", "10 N", "20 N", "11.5 N"], "17.3 N",
      "Vertical component = 20 sin 60 = 20 x 0.866 = 17.3 N."),
  _q("Which of the following is NOT a vector quantity?",
      ["Speed", "Momentum", "Weight", "Acceleration"], "Speed",
      "Speed has magnitude only; velocity (its vector counterpart) has direction. Momentum, weight, and acceleration are all vectors."),
  _q("Two equal forces of 10 N each act on a body such that the angle between them is 120 degrees. The magnitude of their resultant is",
      ["10 N", "20 N", "17.3 N", "5 N"], "10 N",
      "R = sqrt(P^2+Q^2+2PQcos(theta)) = sqrt(100+100+200cos120) = sqrt(200-100) = sqrt(100) = 10 N."),
  _q("A river flows at 3 m/s and a boat is steered directly across at 4 m/s relative to the water. The resultant speed of the boat relative to the bank is",
      ["5 m/s", "7 m/s", "1 m/s", "12 m/s"], "5 m/s",
      "Since the velocities are perpendicular, resultant = sqrt(3^2+4^2) = sqrt(25) = 5 m/s."),
  _q("Three coplanar forces of 5 N, 5 N, and 5 N act on a particle such that it remains in equilibrium. The angle between any two adjacent forces must be",
      ["120 degrees", "90 degrees", "180 degrees", "60 degrees"], "120 degrees",
      "Three equal forces keep a particle in equilibrium only when arranged symmetrically at 120 degrees to each other, forming a closed equilateral triangle of forces."),
  _q("A vector of magnitude 10 units is resolved into two perpendicular components. If one component is 6 units, the other component is",
      ["8 units", "4 units", "16 units", "60 units"], "8 units",
      "Using Pythagoras: other component = sqrt(10^2-6^2) = sqrt(100-36) = sqrt(64) = 8 units."),
];

final _motion = [
  _q("A car accelerates uniformly from 5 m/s to 25 m/s in 4 seconds. Its acceleration is",
      ["5 m/s2", "6.25 m/s2", "20 m/s2", "4 m/s2"], "5 m/s2",
      "a = (v-u)/t = (25-5)/4 = 20/4 = 5 m/s2."),
  _q("A stone is dropped from a height of 45 m. How long does it take to reach the ground? (g = 10 m/s2)",
      ["3 s", "4.5 s", "9 s", "2.1 s"], "3 s",
      "h = 0.5gt^2, so 45 = 0.5(10)t^2, t^2 = 9, t = 3 s."),
  _q("A ball is thrown vertically upward with a velocity of 30 m/s. What maximum height does it reach? (g = 10 m/s2)",
      ["45 m", "90 m", "30 m", "60 m"], "45 m",
      "Using v^2 = u^2 - 2gh with v=0: h = u^2/(2g) = 900/20 = 45 m."),
  _q("A car moving at 20 m/s decelerates uniformly at 4 m/s2. How long does it take to stop?",
      ["5 s", "80 s", "0.2 s", "16 s"], "5 s",
      "t = (v-u)/a = (0-20)/(-4) = 5 s."),
  _q("An object thrown horizontally from a cliff 20 m high with a speed of 15 m/s lands how far from the base of the cliff? (g = 10 m/s2)",
      ["30 m", "20 m", "15 m", "40 m"], "30 m",
      "Time to fall: t = sqrt(2h/g) = sqrt(40/10) = 2 s. Horizontal range = speed x t = 15 x 2 = 30 m."),
  _q("A body of mass 5 kg initially moving at 4 m/s is acted on by a force for 3 s, increasing its velocity to 10 m/s. The magnitude of the force is",
      ["10 N", "2 N", "30 N", "70 N"], "10 N",
      "a = (v-u)/t = (10-4)/3 = 2 m/s2. F = ma = 5 x 2 = 10 N."),
  _q("A bullet of mass 0.02 kg moving at 300 m/s embeds in a stationary block of mass 1.98 kg. What is the velocity of the block and bullet immediately after impact?",
      ["3 m/s", "6 m/s", "30 m/s", "1.5 m/s"], "3 m/s",
      "By conservation of momentum: (0.02)(300) = (2.0)v, so v = 6/2.0 = 3 m/s."),
  _q("A body moves in a circle of radius 2 m at a constant speed of 4 m/s. Its centripetal acceleration is",
      ["8 m/s2", "2 m/s2", "16 m/s2", "0.5 m/s2"], "8 m/s2",
      "a = v^2/r = 16/2 = 8 m/s2."),
  _q("A car of mass 1000 kg moving at 20 m/s is brought to rest by a constant braking force in 5 s. The braking force is",
      ["4000 N", "1000 N", "200 N", "20000 N"], "4000 N",
      "a = (0-20)/5 = -4 m/s2. F = ma = 1000 x 4 = 4000 N."),
  _q("Two objects of masses 3 kg and 2 kg moving towards each other at 4 m/s and 6 m/s respectively collide and stick together. Taking the 3 kg direction as positive, the velocity after collision is",
      ["0 m/s", "1 m/s", "2 m/s", "5 m/s"], "0 m/s",
      "Momentum: (3x4) + (2x-6) = 12-12 = 0. Combined mass = 5 kg, so v = 0/5 = 0 m/s."),
  _q("An object undergoes SHM with amplitude 0.2 m and angular frequency 5 rad/s. Its maximum velocity is",
      ["1.0 m/s", "0.2 m/s", "5.0 m/s", "0.04 m/s"], "1.0 m/s",
      "Maximum velocity in SHM = omega x amplitude = 5 x 0.2 = 1.0 m/s."),
  _q("A projectile is fired at 40 m/s at 30 degrees to the horizontal. Its time of flight is approximately (g = 10 m/s2)",
      ["4 s", "2 s", "8 s", "3.5 s"], "4 s",
      "Vertical component = 40 sin30 = 20 m/s. Time of flight = 2u_y/g = 40/10 = 4 s."),
];

final _gravitationalField = [
  _q("The gravitational force between two masses of 4 kg and 9 kg separated by 3 m is (G = 6.67 x 10^-11 Nm2/kg2)",
      ["2.67 x 10^-10 N", "8.0 x 10^-10 N", "2.4 x 10^-9 N", "1.2 x 10^-10 N"], "2.67 x 10^-10 N",
      "F = Gm1m2/r^2 = (6.67x10^-11 x 4 x 9)/9 = (2.4012x10^-9)/9 = 2.67x10^-10 N."),
  _q("A man weighs 700 N on Earth's surface. What would his mass be? (g = 10 m/s2)",
      ["70 kg", "700 kg", "7000 kg", "7 kg"], "70 kg",
      "m = W/g = 700/10 = 70 kg."),
  _q("At what height above the Earth's surface (radius R) does the value of g reduce to a quarter of its surface value?",
      ["R", "2R", "R/2", "4R"], "R",
      "g at height h is g_s(R/(R+h))^2. For g to be a quarter, (R/(R+h))^2 = 1/4, so R+h = 2R, giving h = R."),
  _q("An astronaut's mass is 80 kg on Earth. On the Moon, where gravitational field strength is about 1/6 that of Earth, his weight is approximately (g_Earth = 10 m/s2)",
      ["133 N", "800 N", "80 N", "480 N"], "133 N",
      "Weight on Moon = mass x g_moon = 80 x (10/6) = 133.3 N."),
  _q("A satellite orbits the Earth at a radius where its orbital period is 90 minutes. As the orbital radius increases, the orbital period",
      ["increases", "decreases", "stays constant", "becomes zero"], "increases",
      "By Kepler's third law, T^2 is proportional to r^3, so a larger orbital radius means a longer orbital period."),
  _q("The escape velocity from a planet of mass M and radius R is given by",
      ["sqrt(2GM/R)", "sqrt(GM/R)", "GM/R2", "sqrt(GM/R2)"], "sqrt(2GM/R)",
      "Escape velocity is derived by equating kinetic energy to gravitational potential energy: 0.5mv^2 = GMm/R, giving v = sqrt(2GM/R)."),
];

final _equilibriumForces = [
  _q("A uniform beam of length 4 m and weight 60 N is balanced on a pivot at its centre. A load of 40 N is placed 1 m from the pivot on one side. Where must a 20 N load be placed on the other side to balance the beam?",
      ["2 m from the pivot", "1 m from the pivot", "0.5 m from the pivot", "4 m from the pivot"], "2 m from the pivot",
      "Taking moments: 40 x 1 = 20 x d, so d = 40/20 = 2 m from the pivot."),
  _q("A uniform ladder of weight 200 N and length 5 m rests on a smooth wall and rough floor. If the ladder makes an angle of 60 degrees with the floor, which factor most affects whether it stays in equilibrium?",
      ["The frictional force at the floor", "The colour of the ladder", "The temperature of the room", "The material of the wall alone"], "The frictional force at the floor",
      "Since the wall is smooth (frictionless), only friction at the floor provides the horizontal force needed to prevent the ladder from slipping."),
  _q("A see-saw of length 6 m is pivoted at its centre. A child of weight 300 N sits 2 m from the pivot. Where should a 200 N child sit on the other side for balance?",
      ["3 m from the pivot", "2 m from the pivot", "4.5 m from the pivot", "1.5 m from the pivot"], "3 m from the pivot",
      "Clockwise moment = anticlockwise moment: 300 x 2 = 200 x d, so d = 600/200 = 3 m."),
  _q("Three forces of 10 N, 10 N, and 10 N act on a ring in equilibrium, forming a closed triangle when drawn to scale. This illustrates",
      ["the triangle law of forces", "the parallelogram law only", "Newton's third law", "the law of conservation of momentum"], "the triangle law of forces",
      "When three concurrent forces are in equilibrium, they can be represented in magnitude and direction by the three sides of a closed triangle, taken in order."),
  _q("A body of weight 100 N hangs from two strings inclined at 30 degrees and 60 degrees to the vertical support beam, meeting at a point. Which principle is used to find the tensions in the strings?",
      ["Lami's theorem or resolution of forces", "Conservation of energy", "Newton's law of gravitation", "Boyle's law"], "Lami's theorem or resolution of forces",
      "For three concurrent coplanar forces in equilibrium, Lami's theorem (or resolving forces into components) is used to determine unknown tensions."),
  _q("A metre rule is balanced at the 40 cm mark when a mass of 60 g is hung at the 10 cm mark. What is the mass of the metre rule, assumed to act at the 50 cm mark?",
      ["180 g", "60 g", "18 g", "72 g"], "180 g",
      "Taking moments about the 40 cm pivot: 60 g is 30 cm from the pivot, and the rule's weight (at 50 cm) is 10 cm from the pivot. So m x 10 = 60 x 30, giving m = 1800/10 = 180 g."),
];

final _workEnergyPower = [
  _q("A force of 15 N moves an object through a distance of 8 m in the direction of the force. The work done is",
      ["120 J", "1.875 J", "23 J", "7 J"], "120 J",
      "Work = force x distance = 15 x 8 = 120 J."),
  _q("A body of mass 2 kg moving at 6 m/s has kinetic energy of",
      ["36 J", "12 J", "72 J", "18 J"], "36 J",
      "K.E. = 0.5mv^2 = 0.5 x 2 x 36 = 36 J."),
  _q("An object of mass 5 kg is raised to a height of 4 m. Its gain in potential energy is (g = 10 m/s2)",
      ["200 J", "20 J", "50 J", "9.8 J"], "200 J",
      "P.E. = mgh = 5 x 10 x 4 = 200 J."),
  _q("A machine does 3000 J of work in 15 seconds. Its power output is",
      ["200 W", "45000 W", "20 W", "3015 W"], "200 W",
      "Power = work/time = 3000/15 = 200 W."),
  _q("A ball of mass 0.5 kg falls freely from a height of 20 m. Its speed just before hitting the ground is (g = 10 m/s2)",
      ["20 m/s", "10 m/s", "200 m/s", "14.1 m/s"], "20 m/s",
      "v^2 = 2gh = 2 x 10 x 20 = 400, so v = 20 m/s."),
  _q("A pump raises 200 kg of water through a height of 15 m every 10 seconds. Taking g = 10 m/s2, the power of the pump is",
      ["3000 W", "300 W", "30000 W", "2000 W"], "3000 W",
      "Power = mgh/t = (200 x 10 x 15)/10 = 30000/10 = 3000 W."),
  _q("A spring with force constant 200 N/m is compressed by 0.1 m. The elastic potential energy stored is",
      ["1 J", "20 J", "10 J", "2 J"], "1 J",
      "E = 0.5kx^2 = 0.5 x 200 x 0.01 = 1 J."),
  _q("An engine of power 5000 W is used to lift a load at a constant velocity of 2 m/s. The maximum load it can lift is (g = 10 m/s2)",
      ["250 kg", "1000 kg", "25 kg", "2500 kg"], "250 kg",
      "Power = Fv, so F = P/v = 5000/2 = 2500 N. Mass = F/g = 2500/10 = 250 kg."),
  _q("By the principle of conservation of energy, a pendulum bob released from a height of 0.45 m will have a speed at its lowest point of approximately (g = 10 m/s2)",
      ["3 m/s", "4.5 m/s", "9 m/s", "1.5 m/s"], "3 m/s",
      "mgh = 0.5mv^2, so v = sqrt(2gh) = sqrt(2x10x0.45) = sqrt(9) = 3 m/s."),
  _q("A crane lifts a 500 kg load through 10 m in 25 s. What is the power developed? (g = 10 m/s2)",
      ["2000 W", "200 W", "5000 W", "1250 W"], "2000 W",
      "Power = mgh/t = (500x10x10)/25 = 50000/25 = 2000 W."),
];

final _frictionSimpleMachines = [
  _q("A block of mass 10 kg rests on a horizontal surface with a coefficient of static friction of 0.4. The maximum frictional force before it starts to slide is (g = 10 m/s2)",
      ["40 N", "4 N", "100 N", "400 N"], "40 N",
      "Maximum friction = mu x Normal force = 0.4 x (10x10) = 0.4 x 100 = 40 N."),
  _q("A lever has a load of 300 N placed 0.5 m from the pivot and an effort applied 1.5 m from the pivot. The mechanical advantage of the lever is",
      ["3", "0.33", "1.5", "150"], "3",
      "For a lever, M.A. = load arm ratio inversely, but here M.A. = effort distance/load distance = 1.5/0.5 = 3."),
  _q("An inclined plane of length 10 m raises a load to a height of 2 m. Its velocity ratio is",
      ["5", "0.2", "20", "8"], "5",
      "Velocity ratio for an inclined plane = length/height = 10/2 = 5."),
  _q("A pulley system has a velocity ratio of 4. If an effort of 150 N raises a load of 500 N, the efficiency of the system is",
      ["83.3%", "100%", "12%", "37.5%"], "83.3%",
      "M.A. = load/effort = 500/150 = 3.33. Efficiency = (M.A./V.R.) x 100 = (3.33/4) x 100 = 83.3%."),
  _q("A block weighing 50 N is pulled at constant velocity along a rough horizontal surface by a horizontal force of 15 N. The coefficient of kinetic friction is",
      ["0.3", "3.33", "0.15", "0.5"], "0.3",
      "At constant velocity, applied force = friction force = 15 N. mu = friction/normal = 15/50 = 0.3."),
  _q("A screw jack has a pitch of 5 mm and a handle of length 35 cm. Its velocity ratio is approximately",
      ["440", "70", "1.75", "7"], "440",
      "V.R. = (2 x pi x handle length)/pitch = (2 x 3.142 x 350)/5 = 2199.1/5 = 439.8, approximately 440."),
  _q("In a wheel and axle system, the wheel has a radius of 20 cm and the axle has a radius of 4 cm. The velocity ratio is",
      ["5", "0.2", "16", "80"], "5",
      "V.R. = radius of wheel/radius of axle = 20/4 = 5."),
  _q("A block of mass 8 kg is on the verge of sliding down a rough incline set at 30 degrees to the horizontal. The coefficient of static friction between the block and the incline is approximately",
      ["0.577", "0.866", "0.5", "1.73"], "0.577",
      "At the point of sliding, mu = tan(theta) = tan30 = 0.577."),
];

final _propertiesOfMatter = [
  _q("A wire of original length 2 m and cross-sectional area 1 x 10^-6 m2 extends by 1 mm under a load of 100 N. Its Young's modulus is",
      ["2 x 10^11 Pa", "5 x 10^10 Pa", "2 x 10^8 Pa", "1 x 10^11 Pa"], "2 x 10^11 Pa",
      "E = (F/A)/(e/L) = (100/1e-6)/(0.001/2) = (1x10^8)/(5x10^-4) = 2x10^11 Pa."),
  _q("A spring extends by 4 cm when a load of 8 N is applied, obeying Hooke's law. What load would produce an extension of 10 cm?",
      ["20 N", "3.2 N", "10 N", "16 N"], "20 N",
      "k = F/e = 8/0.04 = 200 N/m. For e = 0.10 m, F = 200 x 0.10 = 20 N."),
  _q("A liquid of density 800 kg/m3 exerts a pressure at a depth of 5 m of (g = 10 m/s2)",
      ["40000 Pa", "4000 Pa", "8000 Pa", "400 Pa"], "40000 Pa",
      "Pressure = density x g x h = 800 x 10 x 5 = 40000 Pa."),
  _q("A solid object of volume 2 x 10^-4 m3 is fully submerged in water (density 1000 kg/m3). The upthrust on it is (g = 10 m/s2)",
      ["2 N", "0.2 N", "20 N", "200 N"], "2 N",
      "Upthrust = weight of displaced fluid = density x volume x g = 1000 x 2x10^-4 x 10 = 2 N."),
  _q("A hydraulic press has a small piston of area 5 cm2 and a large piston of area 100 cm2. An effort of 50 N on the small piston produces a load force of",
      ["1000 N", "2.5 N", "500 N", "100 N"], "1000 N",
      "Pressure is transmitted equally: F2 = F1 x (A2/A1) = 50 x (100/5) = 1000 N."),
  _q("A capillary tube of radius 0.5 mm is dipped in water. The rise of water due to surface tension is best explained by",
      ["adhesive forces between water and glass exceeding cohesive forces within water", "the high density of water", "atmospheric pressure alone", "the boiling point of water"], "adhesive forces between water and glass exceeding cohesive forces within water",
      "Capillary rise occurs because adhesion between the liquid and the tube wall exceeds cohesion within the liquid, pulling the liquid surface upward along the walls."),
  _q("An object weighs 50 N in air and 30 N when fully submerged in water. Its upthrust in water is",
      ["20 N", "80 N", "30 N", "50 N"], "20 N",
      "Upthrust = apparent loss in weight = weight in air - weight in water = 50 - 30 = 20 N."),
  _q("A gas occupies 400 cm3 at a pressure of 100 kPa. At constant temperature, if the pressure increases to 200 kPa, the new volume is",
      ["200 cm3", "800 cm3", "100 cm3", "400 cm3"], "200 cm3",
      "By Boyle's Law, P1V1 = P2V2: 100x400 = 200xV2, V2 = 40000/200 = 200 cm3."),
  _q("An elastic material is stretched beyond its elastic limit. Which statement is true?",
      ["It will not return to its original length after the load is removed", "It obeys Hooke's law throughout", "Its extension remains proportional to the applied force", "It behaves identically to before loading"], "It will not return to its original length after the load is removed",
      "Beyond the elastic limit, permanent (plastic) deformation occurs, so the material does not fully recover its original dimensions when unloaded."),
];

final _thermalPhysics = [
  _q("A mass of 2 kg of water is heated from 20 degC to 80 degC. If the specific heat capacity of water is 4200 J/kgK, the heat energy required is",
      ["504000 J", "168000 J", "252000 J", "84000 J"], "504000 J",
      "Q = mc(deltaT) = 2 x 4200 x (80-20) = 2 x 4200 x 60 = 504000 J."),
  _q("A gas at 27 degC is heated at constant pressure until its volume doubles. What is the new temperature in degrees Celsius?",
      ["327 degC", "54 degC", "300 degC", "600 degC"], "327 degC",
      "By Charles' Law, V1/T1 = V2/T2 in Kelvin: 300 K doubles to 600 K, which is 600-273 = 327 degC."),
  _q("The quantity of heat needed to melt 0.5 kg of ice at 0 degC (specific latent heat of fusion of ice = 336000 J/kg) is",
      ["168000 J", "336000 J", "672000 J", "84000 J"], "168000 J",
      "Q = mL = 0.5 x 336000 = 168000 J."),
  _q("A block of copper of mass 200 g absorbs 1800 J of heat, raising its temperature by 25 degC. The specific heat capacity of copper is",
      ["360 J/kgK", "0.36 J/kgK", "9000 J/kgK", "3.6 J/kgK"], "360 J/kgK",
      "c = Q/(m x deltaT) = 1800/(0.2 x 25) = 1800/5 = 360 J/kgK."),
  _q("A steel rod of length 2 m and linear expansivity 1.2 x 10^-5 /K is heated through 50 K. Its increase in length is",
      ["1.2 mm", "0.12 mm", "12 mm", "0.012 mm"], "1.2 mm",
      "Extension = L x alpha x deltaT = 2 x 1.2x10^-5 x 50 = 1.2x10^-3 m = 1.2 mm."),
  _q("On the Kelvin scale, absolute zero corresponds to",
      ["-273 degC", "0 degC", "100 degC", "-100 degC"], "-273 degC",
      "Absolute zero, the theoretical lowest possible temperature, is -273.15 degC (approximately -273 degC), equal to 0 K."),
  _q("A fixed mass of gas at constant volume has an initial pressure of 100 kPa at 300 K. When heated to 450 K, its new pressure is",
      ["150 kPa", "200 kPa", "100 kPa", "300 kPa"], "150 kPa",
      "By Pressure Law (constant volume), P1/T1 = P2/T2: P2 = 100 x (450/300) = 150 kPa."),
  _q("Heat transfer through a metal rod without bulk movement of the metal itself is called",
      ["conduction", "convection", "radiation", "insulation"], "conduction",
      "Conduction transfers heat energy via molecular/electron vibration and collision through a material, without the material itself flowing, unlike convection."),
  _q("A calorimeter of negligible heat capacity contains 0.3 kg of water at 20 degC. A 0.1 kg piece of metal at 100 degC is dropped in, and the final temperature is 25 degC. Taking specific heat capacity of water as 4200 J/kgK, the specific heat capacity of the metal is approximately",
      ["840 J/kgK", "420 J/kgK", "1260 J/kgK", "168 J/kgK"], "840 J/kgK",
      "Heat gained by water = 0.3x4200x5 = 6300 J = heat lost by metal = 0.1 x c x 75. So c = 6300/7.5 = 840 J/kgK."),
];

final _wavesSound = [
  _q("A wave has a frequency of 50 Hz and wavelength 4 m. Its speed is",
      ["200 m/s", "12.5 m/s", "54 m/s", "0.08 m/s"], "200 m/s",
      "Speed = frequency x wavelength = 50 x 4 = 200 m/s."),
  _q("A sound wave travels 340 m in 1 second in air. If its wavelength is 0.68 m, its frequency is",
      ["500 Hz", "231.2 Hz", "50 Hz", "5000 Hz"], "500 Hz",
      "f = v/wavelength = 340/0.68 = 500 Hz."),
  _q("An observer hears an echo from a cliff 3 seconds after producing a sound. If the speed of sound in air is 340 m/s, the distance to the cliff is",
      ["510 m", "1020 m", "255 m", "113.3 m"], "510 m",
      "Distance = (speed x time)/2 = (340 x 3)/2 = 1020/2 = 510 m."),
  _q("A stationary wave is formed on a string fixed at both ends, length 1.2 m, vibrating in its fundamental mode. The wavelength of the wave is",
      ["2.4 m", "1.2 m", "0.6 m", "4.8 m"], "2.4 m",
      "For the fundamental mode on a string fixed at both ends, wavelength = 2L = 2 x 1.2 = 2.4 m."),
  _q("A closed pipe of length 0.5 m resonates at its fundamental frequency. Taking the speed of sound as 340 m/s, this fundamental frequency is",
      ["170 Hz", "340 Hz", "680 Hz", "85 Hz"], "170 Hz",
      "For a closed pipe, fundamental wavelength = 4L = 2.0 m. f = v/wavelength = 340/2.0 = 170 Hz."),
  _q("Two sound waves of frequencies 256 Hz and 260 Hz are sounded together. The beat frequency heard is",
      ["4 Hz", "258 Hz", "516 Hz", "2 Hz"], "4 Hz",
      "Beat frequency = difference between the two frequencies = 260 - 256 = 4 Hz."),
  _q("The phenomenon in which the observed frequency of a sound changes due to relative motion between source and observer is called",
      ["the Doppler effect", "resonance", "diffraction", "interference"], "the Doppler effect",
      "The Doppler effect describes the apparent change in frequency of a wave due to relative motion between the source and the observer."),
  _q("A wave of period 0.02 s has a frequency of",
      ["50 Hz", "0.02 Hz", "20 Hz", "500 Hz"], "50 Hz",
      "f = 1/T = 1/0.02 = 50 Hz."),
  _q("Which property distinguishes transverse waves from longitudinal waves?",
      ["Particle vibration is perpendicular to the direction of wave travel", "They cannot travel through a vacuum", "They always travel faster", "They require a medium to propagate"], "Particle vibration is perpendicular to the direction of wave travel",
      "In transverse waves, particles oscillate perpendicular to the direction of energy propagation, unlike longitudinal waves where particles oscillate parallel to it."),
];

final _optics = [
  _q("An object is placed 30 cm from a converging lens of focal length 10 cm. Using 1/f = 1/v + 1/u, the image distance is",
      ["15 cm", "7.5 cm", "20 cm", "30 cm"], "15 cm",
      "1/v = 1/f - 1/u = 1/10 - 1/30 = (3-1)/30 = 2/30, so v = 15 cm."),
  _q("A concave mirror has a focal length of 20 cm. An object placed 60 cm from the mirror forms an image at",
      ["30 cm", "15 cm", "40 cm", "12 cm"], "30 cm",
      "1/v = 1/f - 1/u = 1/20 - 1/60 = (3-1)/60 = 2/60, so v = 30 cm."),
  _q("Light travels from air (refractive index 1) into glass (refractive index 1.5) at an angle of incidence of 30 degrees. Using Snell's law, the sine of the angle of refraction is approximately",
      ["0.333", "0.75", "0.5", "1.5"], "0.333",
      "n1 sin(i) = n2 sin(r): 1 x sin30 = 1.5 x sin(r), sin(r) = 0.5/1.5 = 0.333."),
  _q("The critical angle for a medium with refractive index 1.5 is approximately",
      ["41.8 degrees", "60 degrees", "48.2 degrees", "30 degrees"], "41.8 degrees",
      "sin(C) = 1/n = 1/1.5 = 0.667, so C = arcsin(0.667) = 41.8 degrees."),
  _q("A convex lens forms a real, inverted image twice the size of the object. If the object distance is 15 cm, the image distance is",
      ["30 cm", "7.5 cm", "45 cm", "60 cm"], "30 cm",
      "Magnification = v/u, so 2 = v/15, giving v = 30 cm."),
  _q("An object 5 cm tall is placed in front of a lens and forms an image 15 cm tall. The linear magnification produced is",
      ["3", "0.33", "10", "75"], "3",
      "Magnification = image height/object height = 15/5 = 3."),
  _q("A ray of light passing through a triangular glass prism is bent towards the base of the prism. This bending is due to",
      ["refraction at the two prism surfaces", "total internal reflection only", "diffraction of light", "polarization of light"], "refraction at the two prism surfaces",
      "As light enters and exits the prism's two inclined surfaces, it refracts at each surface, bending the overall ray path towards the base."),
  _q("The image formed in a plane mirror is",
      ["virtual, laterally inverted, and the same size as the object", "real and inverted", "virtual and magnified", "real and diminished"], "virtual, laterally inverted, and the same size as the object",
      "A plane mirror always produces a virtual, upright, laterally inverted image that is the same size as the object, located as far behind the mirror as the object is in front."),
  _q("A converging lens of focal length 25 cm is used as a magnifying glass. Its power in dioptres is",
      ["4 D", "0.25 D", "25 D", "2.5 D"], "4 D",
      "Power = 1/f(in metres) = 1/0.25 = 4 D."),
  _q("White light splitting into its component colours when passing through a prism is called",
      ["dispersion", "reflection", "polarization", "diffraction"], "dispersion",
      "Dispersion occurs because different wavelengths (colours) of light refract by different amounts in the prism, spreading white light into a spectrum."),
];

final _electricityMagnetism = [
_q("A current of 2 A flows through a resistor of 15 ohms for 10 seconds. The quantity of charge that flows is",
      ["20 C", "150 C", "0.75 C", "300 C"], "20 C",
      "Q = It = 2 x 10 = 20 C."),
_q("Three resistors of 2 ohms, 3 ohms, and 5 ohms are connected in series to a 20 V battery. The current flowing in the circuit is",
      ["2 A", "10 A", "4 A", "0.5 A"], "2 A",
      "Total resistance = 2+3+5 = 10 ohms. I = V/R = 20/10 = 2 A."),
_q("Two resistors of 4 ohms and 6 ohms are connected in parallel. Their combined resistance is",
      ["2.4 ohms", "10 ohms", "24 ohms", "1.5 ohms"], "2.4 ohms",
      "1/R = 1/4 + 1/6 = 3/12 + 2/12 = 5/12, so R = 12/5 = 2.4 ohms."),
];

final _modernPhysics = [

];
