import "../quiz_question.dart";

const _subject = "Commerce";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// Obafemi Awolowo University (OAU) Post-UTME Commerce practice bank — 100
/// medium-to-hard questions covering Introduction to Commerce, Occupations,
/// Business Units, Home & Foreign Trade, Trade Associations, Banking,
/// Insurance, Transport, Communication & Advertising, Warehousing,
/// Marketing, Legal Aspects of Business, and Business Management. This is a
/// general practice set aligned to typical Post-UTME screening standards,
/// not an official OAU past-question paper.
List<QuizQuestion> buildOauCommerceQuestions() {
  return [
    ..._introductionToCommerce,
    ..._occupations,
    ..._businessUnits,
    ..._homeForeignTrade,
    ..._tradeAssociations,
    ..._banking,
    ..._insurance,
    ..._transport,
    ..._communicationAdvertising,
    ..._warehousing,
    ..._marketing,
    ..._legalAspects,
    ..._businessManagement,
  ];
}

final _introductionToCommerce = [
  _q("A key distinguishing feature of commerce, as opposed to industry, is that commerce focuses on",
      ["the exchange and distribution of goods and services rather than their production", "the extraction of raw materials from nature", "the conversion of raw materials into finished products", "the storage of raw materials before processing"], "the exchange and distribution of goods and services rather than their production",
      "Commerce deals with buying, selling, and the aids to trade that move goods from producers to consumers, while industry deals with actual production."),
  _q("The 'aids to trade' are collectively necessary because they",
      ["remove the hindrances that stand between producers and consumers", "increase the cost of production without any benefit", "replace the need for trade entirely", "are only relevant to international transactions"], "remove the hindrances that stand between producers and consumers",
      "Aids to trade such as banking, insurance, transport, warehousing, and communication remove obstacles of place, time, risk, finance, and information that separate producers from consumers."),
  _q("Which pair correctly matches an obstacle to trade with the aid that removes it?",
      ["Obstacle of place — transport", "Obstacle of risk — warehousing", "Obstacle of time — banking", "Obstacle of finance — advertising"], "Obstacle of place — transport",
      "Transport removes the obstacle of place by physically moving goods from where they are produced to where they are demanded."),
  _q("Warehousing, as an aid to trade, primarily solves the obstacle of",
      ["time, by holding goods until they are needed", "place, by moving goods across distances", "risk, by insuring goods against loss", "finance, by lending money to traders"], "time, by holding goods until they are needed",
      "Warehousing bridges the gap between when goods are produced and when they are eventually demanded, thereby overcoming the obstacle of time."),
  _q("Insurance is classified as an aid to trade because it overcomes the obstacle of",
      ["risk, by spreading the financial burden of loss among many policyholders", "place, by transporting goods physically", "time, by storing goods for future sale", "communication, by conveying business information"], "risk, by spreading the financial burden of loss among many policyholders",
      "Insurance pools contributions from many policyholders to compensate the few who suffer losses, thus overcoming the obstacle of risk in trade."),
  _q("Which of these best describes 'home trade' within the scope of commerce?",
      ["Buying and selling of goods within the boundaries of one country", "Buying and selling of goods between two or more countries", "The movement of goods from a warehouse to a retail shop", "The exchange of services between banks only"], "Buying and selling of goods within the boundaries of one country",
      "Home (internal) trade refers to the exchange of goods and services carried out entirely within a country's borders, as opposed to foreign trade."),
  _q("The term 'commerce' is broader than the term 'trade' because commerce also includes",
      ["the aids to trade that facilitate the buying and selling of goods", "only the retailing of goods to final consumers", "only the wholesaling of goods to retailers", "the manufacturing of raw materials into finished goods"], "the aids to trade that facilitate the buying and selling of goods",
      "Trade is only one branch of commerce; commerce also embraces the aids to trade (banking, insurance, transport, warehousing, communication, advertising) that support trading activities."),
  _q("Which of the following best explains why commerce is considered essential to modern economic life?",
      ["It ensures goods and services produced in one place reach consumers wherever they are needed", "It eliminates the role of producers in the economy", "It guarantees that every business will make a profit", "It removes the need for government regulation of trade"], "It ensures goods and services produced in one place reach consumers wherever they are needed",
      "By linking production to consumption through trade and its aids, commerce ensures an efficient flow of goods and services to satisfy human wants."),
];

final _occupations = [
  _q("Which classification of occupations includes farming, mining, and fishing?",
      ["Extractive industrial occupations", "Commercial occupations", "Direct service occupations", "Constructive industrial occupations"], "Extractive industrial occupations",
      "Extractive occupations involve obtaining raw materials directly from nature, such as farming, mining, and fishing."),
  _q("Manufacturing occupations, such as textile weaving and furniture making, fall under which broad category?",
      ["Constructive/manufacturing industrial occupations", "Extractive industrial occupations", "Commercial occupations", "Service occupations"], "Constructive/manufacturing industrial occupations",
      "Constructive (manufacturing) occupations turn raw materials into finished or semi-finished goods, distinguishing them from extractive occupations that merely obtain raw materials."),
  _q("A stockbroker who buys and sells shares on behalf of clients is engaged in a",
      ["commercial occupation", "direct service occupation", "extractive occupation", "constructive occupation"], "commercial occupation",
      "Stockbroking is part of trade and its aids (finance-related services), placing it under commercial occupations."),
  _q("Which of the following is a direct service occupation?",
      ["Nursing", "Wholesaling", "Warehousing", "Insurance underwriting"], "Nursing",
      "Nursing renders a personal service directly to individuals, making it a direct (personal) service occupation rather than a commercial one."),
  _q("Why are commercial occupations considered indispensable to an economy?",
      ["They link producers to consumers through trade and supporting services", "They are the only occupations that generate government revenue", "They eliminate the need for industrial occupations", "They are restricted to import and export activities only"], "They link producers to consumers through trade and supporting services",
      "Commercial occupations, through trade and its aids, ensure that goods produced reach the final consumers who need them."),
  _q("A civil engineer who designs and constructs bridges belongs to which category of occupation?",
      ["Constructive industrial occupation", "Extractive industrial occupation", "Commercial occupation", "Direct service occupation"], "Constructive industrial occupation",
      "Construction work, which creates infrastructure from raw materials, is classified as a constructive (manufacturing/building) industrial occupation."),
];

final _businessUnits = [
  _q("A key disadvantage of the sole proprietorship as a form of business unit is that the owner has",
      ["unlimited liability for the debts of the business", "limited liability protecting personal assets", "shared control with numerous shareholders", "a perpetual legal existence separate from the owner"], "unlimited liability for the debts of the business",
      "In a sole proprietorship, the owner and the business are legally the same entity, so the owner's personal assets can be used to settle business debts."),
  _q("Which feature distinguishes a partnership from a sole proprietorship?",
      ["A partnership is owned by two or more persons who share capital, management, and profits", "A partnership must have at least seven members", "A partnership automatically has limited liability for all partners", "A partnership cannot be dissolved by the death of a partner"], "A partnership is owned by two or more persons who share capital, management, and profits",
      "Unlike a sole proprietorship owned by one person, a partnership involves two or more persons pooling resources and sharing responsibility for the business."),
  _q("In a limited partnership, a limited partner's liability for business debts is restricted to",
      ["the amount of capital they contributed to the business", "their entire personal wealth", "nothing at all, regardless of contribution", "double the amount of their capital contribution"], "the amount of capital they contributed to the business",
      "A limited partner risks only the capital invested and takes no part in management, unlike a general partner who has unlimited liability."),
  _q("A private limited liability company differs from a public limited liability company mainly because it",
      ["cannot offer its shares for sale to the general public", "must have at least fifty shareholders", "is required to list its shares on a stock exchange", "cannot have more than one director"], "cannot offer its shares for sale to the general public",
      "A private limited company restricts the transfer of its shares and cannot invite the public to subscribe for shares, unlike a public limited company."),
  _q("The document that governs the internal management and regulations of a registered company is called the",
      ["Articles of Association", "Memorandum of Association", "Certificate of Incorporation", "Prospectus"], "Articles of Association",
      "The Articles of Association set out the internal rules for running the company, such as directors' powers and shareholders' rights."),
  _q("The Memorandum of Association of a company mainly states",
      ["the company's relationship with the outside world, including its name, objectives, and registered address", "the internal rules governing meetings of directors", "the salaries to be paid to employees", "the list of customers the company intends to serve"], "the company's relationship with the outside world, including its name, objectives, and registered address",
      "The Memorandum of Association defines the company's external relations: its name, registered office, objectives, and capital, among other things."),
  _q("A cooperative society is best described as an organisation",
      ["formed voluntarily by members with common interests to pool resources for mutual benefit", "owned solely by the government for public welfare", "formed to maximise profit for a single wealthy investor", "that must always operate as a limited liability company"], "formed voluntarily by members with common interests to pool resources for mutual benefit",
      "Cooperative societies are voluntary associations where members combine resources to achieve shared economic benefits, such as better prices or access to credit."),
  _q("Which of the following is a major advantage of a public limited liability company over a sole proprietorship?",
      ["Ability to raise large amounts of capital by selling shares to the public", "Simplicity and low cost of formation", "Complete secrecy of financial affairs", "Freedom from government regulation"], "Ability to raise large amounts of capital by selling shares to the public",
      "A public company can raise substantial capital by inviting members of the public to buy its shares, something a sole proprietorship cannot do."),
  _q("A public corporation (state-owned enterprise) is typically established by",
      ["an Act of Parliament or government decree to provide essential services", "a group of private individuals seeking maximum profit", "a single wealthy entrepreneur without government involvement", "a cooperative society registered under company law"], "an Act of Parliament or government decree to provide essential services",
      "Public corporations are created by government legislation to run essential services (like electricity or rail transport) that may be unattractive to purely private capital."),
  _q("One key reason many small businesses choose to remain sole proprietorships rather than incorporate is",
      ["the ease and low cost of setting up and controlling the business", "the requirement to publish annual accounts publicly", "the automatic access to unlimited external capital", "the legal separation between owner and business"], "the ease and low cost of setting up and controlling the business",
      "Sole proprietorships are simple and inexpensive to establish, and the owner retains full control without the formalities required of registered companies."),
];

final _homeForeignTrade = [
  _q("Home trade is subdivided into",
      ["wholesale trade and retail trade", "import trade and export trade", "entrepot trade and bilateral trade", "visible trade and invisible trade"], "wholesale trade and retail trade",
      "Internal (home) trade consists of wholesale trade (buying in bulk for resale to retailers) and retail trade (selling in small quantities to final consumers)."),
  _q("The main function of a wholesaler in the chain of distribution is to",
      ["buy goods in bulk from producers and break them into smaller quantities for retailers", "manufacture goods for sale directly to consumers", "provide insurance cover for goods in transit", "regulate the foreign exchange rate of a country"], "buy goods in bulk from producers and break them into smaller quantities for retailers",
      "Wholesalers act as intermediaries who buy in bulk from producers and sell in smaller quantities to retailers, easing distribution for both producers and retailers."),
  _q("Which of the following best describes the wholesaler's function of 'breaking bulk'?",
      ["Breaking bulk into smaller units suitable for retailers", "Manufacturing finished goods from raw materials", "Regulating a nation's currency exchange rate", "Setting the exchange controls for imported goods"], "Breaking bulk into smaller units suitable for retailers",
      "One of the wholesaler's core functions is 'breaking bulk' — dividing large quantities purchased from producers into smaller lots suitable for retailers to buy."),
  _q("Retailing is best defined as the",
      ["sale of goods in small quantities directly to final consumers", "sale of goods in bulk to other traders for resale", "purchase of goods from foreign countries for local use", "movement of goods from one warehouse to another"], "sale of goods in small quantities directly to final consumers",
      "Retail trade is the last link in the chain of distribution, involving the sale of goods in small units directly to the final consumer."),
  _q("A department store is a type of retail outlet characterised by",
      ["selling a wide variety of goods organised into different departments under one roof", "selling only one type of product line, such as shoes", "operating exclusively through door-to-door sales agents", "selling goods only to other retailers, not final consumers"], "selling a wide variety of goods organised into different departments under one roof",
      "Department stores group a wide range of goods into separate departments (e.g., clothing, electronics, groceries) within a single large building."),
  _q("A supermarket differs from a small independent retail shop mainly through its",
      ["self-service system and sale of a wide range of goods at relatively low margins", "reliance on door-to-door selling", "focus on selling a single specialised product", "requirement that customers place orders by post"], "self-service system and sale of a wide range of goods at relatively low margins",
      "Supermarkets typically operate on a self-service basis, stock a wide variety of goods, and rely on high turnover with relatively low profit margins per item."),
  _q("Foreign trade refers to the exchange of goods and services",
      ["between two or more different countries", "between a producer and a wholesaler in the same country", "between a wholesaler and a retailer in the same country", "solely within the boundaries of one country"], "between two or more different countries",
      "Foreign (external) trade involves the buying and selling of goods and services across national boundaries, unlike home trade which is confined within one country."),
  _q("Foreign trade is divided into which three main categories?",
      ["Import trade, export trade, and entrepot trade", "Wholesale trade, retail trade, and barter trade", "Direct trade, indirect trade, and counter trade", "Visible trade, hidden trade, and invisible trade"], "Import trade, export trade, and entrepot trade",
      "External trade comprises import trade (bringing goods into a country), export trade (sending goods out), and entrepot trade (importing goods for re-export)."),
  _q("Entrepot trade occurs when a country",
      ["imports goods from one country and re-exports them, often after minor processing, to another country", "produces goods solely for its own domestic consumption", "bans the importation of all foreign goods", "exchanges goods directly for other goods without using money"], "imports goods from one country and re-exports them, often after minor processing, to another country",
      "Entrepot trade involves a country acting as a trading hub, importing goods and then re-exporting them to a third country, sometimes after processing or repackaging."),
  _q("A 'balance of trade' is said to be favourable when a country's",
      ["value of exports exceeds the value of its imports", "value of imports exceeds the value of its exports", "imports and exports are exactly equal in value", "currency has been devalued against foreign currencies"], "value of exports exceeds the value of its imports",
      "A favourable (surplus) balance of trade occurs when a country earns more from exports than it spends on imports."),
  _q("A tariff imposed on imported goods is primarily intended to",
      ["protect local industries by making imported goods more expensive than local substitutes", "encourage unrestricted importation of foreign goods", "eliminate all forms of foreign trade", "reduce the price of imported goods to consumers"], "protect local industries by making imported goods more expensive than local substitutes",
      "Import tariffs raise the price of foreign goods, making domestically produced goods more competitive and thereby protecting local industries."),
  _q("A quota, as a trade restriction, works by",
      ["limiting the physical quantity of a particular good that may be imported into a country", "imposing a tax on goods leaving the country", "banning a country from trading with any other nation", "fixing the exchange rate between two currencies"], "limiting the physical quantity of a particular good that may be imported into a country",
      "An import quota sets a maximum quantity of a specific good that can be brought into a country within a given period, restricting supply from abroad."),
  _q("A bill of lading used in foreign trade serves as",
      ["a document of title to goods being shipped, and evidence of a contract of carriage", "a certificate proving that goods are insured against fire only", "a licence permitting a company to operate locally", "a receipt for taxes paid on imported goods"], "a document of title to goods being shipped, and evidence of a contract of carriage",
      "A bill of lading is issued by a shipping company as a receipt for goods, evidence of the contract of carriage, and a document of title that can be transferred to another party."),
  _q("A letter of credit in foreign trade is mainly used to",
      ["assure an exporter of payment once specified conditions and documents are met", "insure goods against damage while at sea", "grant a company permission to export goods", "record the physical quantity of goods loaded onto a ship"], "assure an exporter of payment once specified conditions and documents are met",
      "A letter of credit, issued by the importer's bank, guarantees payment to the exporter once the exporter presents the agreed shipping documents, reducing payment risk in international trade."),
  _q("A 'certificate of origin' in foreign trade indicates",
      ["the country in which the goods being exported were manufactured or produced", "the insurance company covering the goods in transit", "the bank responsible for financing the shipment", "the final selling price of the goods in the importing country"], "the country in which the goods being exported were manufactured or produced",
      "A certificate of origin certifies the country where goods were produced or manufactured, which may affect tariffs or import eligibility."),
];

final _tradeAssociations = [
  _q("A Chamber of Commerce is primarily formed to",
      ["promote and protect the trading interests of its business members", "manufacture goods for sale to the general public", "provide direct government funding to individual traders", "regulate the political affairs of a country"], "promote and protect the trading interests of its business members",
      "Chambers of Commerce bring business people together to safeguard and advance shared commercial interests, such as lobbying government on trade policy."),
  _q("A trade union differs from a Chamber of Commerce in that a trade union primarily protects the interests of",
      ["employees/workers rather than business owners", "shareholders of public companies", "importers and exporters only", "consumers of manufactured goods"], "employees/workers rather than business owners",
      "Trade unions are formed by workers to negotiate better wages and working conditions, whereas Chambers of Commerce represent business owners and traders."),
  _q("A stock exchange functions mainly as a market for the",
      ["buying and selling of existing shares, bonds, and other securities", "buying and selling of perishable agricultural produce", "wholesale distribution of manufactured consumer goods", "exchange of foreign currency between individual travellers"], "buying and selling of existing shares, bonds, and other securities",
      "A stock exchange is an organised market where second-hand (already-issued) securities such as shares and bonds are traded between investors."),
  _q("A trade association, unlike a trade union, is typically formed by",
      ["business firms in the same industry to promote common commercial interests", "individual workers seeking higher wages", "government ministries to regulate imports", "consumers seeking to boycott certain products"], "business firms in the same industry to promote common commercial interests",
      "Trade associations bring together firms within the same trade or industry to pursue shared interests such as standard-setting, lobbying, and information sharing."),
  _q("One major function of a Chamber of Commerce is to",
      ["arbitrate in disputes between its members", "set the national minimum wage for all workers", "print and issue the national currency", "grant import licences on behalf of government"], "arbitrate in disputes between its members",
      "Chambers of Commerce often provide arbitration services to help settle commercial disputes between member businesses without resorting to costly litigation."),
];

final _banking = [
  _q("The primary function of a commercial bank is to",
      ["accept deposits from customers and lend money to borrowers", "print new currency notes for circulation", "set national fiscal policy for the government", "provide free insurance cover to all depositors"], "accept deposits from customers and lend money to borrowers",
      "Commercial banks act as financial intermediaries, mobilising deposits from savers and channelling them as loans to borrowers, earning interest in the process."),
  _q("A current account differs from a savings account mainly because a current account",
      ["allows unlimited withdrawals by cheque and usually earns no interest", "always earns a higher interest rate than a savings account", "cannot be operated by companies or businesses", "requires a minimum six-month notice before withdrawal"], "allows unlimited withdrawals by cheque and usually earns no interest",
      "Current accounts are designed for frequent transactions via cheque or transfer and typically do not attract interest, unlike savings accounts."),
  _q("A crossed cheque is one that",
      ["can only be paid into a bank account and not cashed directly over the counter", "has been cancelled and is no longer valid for payment", "guarantees payment regardless of the drawer's account balance", "can be cashed by anyone who presents it at any bank"], "can only be paid into a bank account and not cashed directly over the counter",
      "Crossing a cheque (drawing two parallel lines across it) restricts payment to being made through a bank account, adding a layer of security against fraud."),
  _q("A 'dishonoured cheque' is one that",
      ["a bank refuses to pay, often due to insufficient funds in the drawer's account", "has been crossed by the drawer for security", "has already been cashed and cancelled by the bank", "was issued by the Central Bank as legal tender"], "a bank refuses to pay, often due to insufficient funds in the drawer's account",
      "A cheque is dishonoured when the paying bank refuses to honour it, commonly because the drawer's account lacks sufficient funds."),
  _q("The Central Bank of a country performs which unique function not carried out by commercial banks?",
      ["Acting as the sole issuer of the country's legal tender currency", "Accepting savings deposits from the general public", "Granting personal loans to individual customers", "Operating retail banking branches nationwide for the public"], "Acting as the sole issuer of the country's legal tender currency",
      "Only the Central Bank has the legal authority to issue the nation's currency notes and coins; commercial banks cannot create legal tender."),
  _q("Which of the following best describes the Central Bank's role as 'lender of last resort'?",
      ["It provides emergency loans to commercial banks facing liquidity shortages when no other source is available", "It offers the lowest interest rates to ordinary individual borrowers", "It refuses to lend to any bank under any circumstances", "It only lends money to foreign governments"], "It provides emergency loans to commercial banks facing liquidity shortages when no other source is available",
      "As lender of last resort, the Central Bank supports commercial banks with emergency funds to prevent bank failures from destabilising the financial system."),
  _q("An overdraft facility allows a current account holder to",
      ["withdraw more money than is currently in their account, up to an agreed limit", "earn a fixed high interest rate on idle balances", "convert their savings account into a fixed deposit automatically", "receive free banking services for life"], "withdraw more money than is currently in their account, up to an agreed limit",
      "An overdraft is a short-term credit facility that lets an account holder withdraw beyond their balance up to a limit agreed with the bank."),
  _q("A fixed (time) deposit account is best suited for a customer who wants to",
      ["invest a lump sum for a set period at a higher rate of interest without frequent withdrawals", "make daily withdrawals using a chequebook", "receive an overdraft facility on demand", "operate a joint account with unlimited free transfers"], "invest a lump sum for a set period at a higher rate of interest without frequent withdrawals",
      "Fixed deposits lock a sum of money away for an agreed term in exchange for a higher interest rate than an ordinary savings account, discouraging frequent withdrawals."),
  _q("Which of these is a function of merchant banks that distinguishes them from typical commercial banks?",
      ["Providing corporate finance advice and underwriting new share issues for companies", "Operating a large network of retail branches for individual depositors", "Issuing the national currency", "Providing free chequebooks to individual savings customers"], "Providing corporate finance advice and underwriting new share issues for companies",
      "Merchant banks specialise in wholesale/corporate banking services such as underwriting securities, corporate finance, and advisory services, rather than mass retail banking."),
  _q("A standing order given to a bank instructs it to",
      ["make a fixed, regular payment from the customer's account to a specified party", "block a customer's account from any further transactions", "convert a customer's savings account into a current account", "issue a new debit card to the customer automatically"], "make a fixed, regular payment from the customer's account to a specified party",
      "A standing order is a customer's instruction to their bank to pay a fixed amount to a named party at regular intervals, such as monthly rent."),
  _q("Bank statements are important to a current account holder mainly because they",
      ["show a record of all transactions (deposits and withdrawals) on the account over a period", "guarantee automatic loan approval for the customer", "serve as legal tender for making payments", "replace the need for the customer to keep a chequebook"], "show a record of all transactions (deposits and withdrawals) on the account over a period",
      "A bank statement gives the account holder a periodic summary of all debits and credits, allowing them to reconcile their own records with the bank's."),
];

final _insurance = [
  _q("The fundamental principle behind insurance is",
      ["the sharing of risk among a large number of people who each pay a small premium", "the guarantee that no policyholder will ever suffer a loss", "the government's direct compensation for all business losses", "the elimination of risk from all commercial activities"], "the sharing of risk among a large number of people who each pay a small premium",
      "Insurance operates on the principle of risk-pooling: many people contribute small premiums into a common fund, from which the few who suffer losses are compensated."),
  _q("The principle of 'utmost good faith' in insurance requires that",
      ["the insured discloses all material facts relevant to the risk being insured", "the insurer sets premiums without informing the insured", "the insured need not disclose any information to the insurer", "only the insurer is bound to act honestly in the contract"], "the insured discloses all material facts relevant to the risk being insured",
      "Utmost good faith (uberrimae fidei) obliges both parties, especially the insured, to disclose all material facts that could affect the insurer's decision to grant cover or set the premium."),
  _q("The principle of 'indemnity' in insurance means that",
      ["the insured should be restored to the same financial position they were in before the loss, not better", "the insured can claim more than the actual value of the loss suffered", "premiums are paid only after a claim has been settled", "the insurer bears no obligation to pay any claim"], "the insured should be restored to the same financial position they were in before the loss, not better",
      "Indemnity ensures compensation merely restores the insured to their pre-loss financial position, preventing them from profiting from an insurance claim."),
  _q("'Insurable interest' refers to the requirement that",
      ["the insured must stand to suffer a genuine financial loss from the event insured against", "only the insurer benefits financially from the insurance contract", "any person may insure any property regardless of ownership", "insurance can only be taken out on human life, not property"], "the insured must stand to suffer a genuine financial loss from the event insured against",
      "Insurable interest requires a legally recognised financial relationship between the insured and the subject matter, ensuring insurance is not used for gambling on losses."),
  _q("'Subrogation' in insurance allows the insurer, after paying a claim, to",
      ["take over the insured's legal rights to recover the loss from a negligent third party", "cancel the policy without any prior notice", "refuse to pay any future claims from the same insured", "increase the premium retroactively for the settled claim"], "take over the insured's legal rights to recover the loss from a negligent third party",
      "Subrogation transfers the insured's right of recovery against a third party who caused the loss to the insurer, once the insurer has paid the claim."),
  _q("Life assurance differs from other forms of insurance mainly because",
      ["the event insured against (death) is certain to happen, only the timing is uncertain", "it never requires the payment of regular premiums", "it cannot be combined with any savings element", "claims can never be made by the policyholder's family"], "the event insured against (death) is certain to happen, only the timing is uncertain",
      "Unlike fire or motor insurance, where the insured event may never occur, death is certain; life assurance is thus a form of assurance rather than pure insurance against an uncertain event."),
  _q("A fidelity guarantee insurance policy protects an employer against",
      ["financial loss caused by the dishonesty or fraud of an employee", "damage to business premises caused by fire", "the death of a key member of staff", "loss of goods while being transported by sea"], "financial loss caused by the dishonesty or fraud of an employee",
      "Fidelity guarantee insurance compensates an employer for losses arising from an employee's dishonest acts, such as theft or embezzlement."),
  _q("Marine insurance primarily provides cover against risks associated with",
      ["the transportation of goods and vessels by sea", "damage to buildings caused by fire on land", "the death or disability of an individual", "the theft of goods from a retail shop"], "the transportation of goods and vessels by sea",
      "Marine insurance covers losses relating to ships, cargo, and freight arising from sea perils during a voyage."),
  _q("A 'cover note' issued by an insurer serves as",
      ["temporary evidence of insurance cover pending the issue of the full policy document", "final proof that a claim has been fully settled", "a receipt confirming cancellation of an insurance policy", "a legal document transferring ownership of insured property"], "temporary evidence of insurance cover pending the issue of the full policy document",
      "A cover note provides interim proof that insurance is in force while the formal policy document is being prepared."),
  _q("Under the principle of 'contribution' in insurance, when a loss is covered by more than one policy, each insurer",
      ["pays only its proportionate share of the total claim", "must pay the full claim amount independently to the insured", "is exempted entirely from paying any part of the claim", "can refuse to pay because multiple policies exist"], "pays only its proportionate share of the total claim",
      "Contribution prevents the insured from profiting by claiming the full amount from each of several insurers; instead, each insurer pays a proportionate share of the loss."),
];

final _transport = [
  _q("Which mode of transport is generally most suitable for moving bulky, low-value goods over long domestic distances at low cost?",
      ["Rail transport", "Air transport", "Pipeline transport for solid goods", "Courier/postal transport"], "Rail transport",
      "Railways are well suited for carrying heavy, bulky goods such as minerals and agricultural produce over long distances relatively cheaply, though they lack door-to-door flexibility."),
  _q("A major advantage of road transport over rail transport is that road transport offers",
      ["greater flexibility, including door-to-door delivery", "lower cost per tonne for very heavy bulk cargo over long distances", "the ability to cross oceans between continents", "immunity from traffic congestion and accidents"], "greater flexibility, including door-to-door delivery",
      "Road transport can reach virtually any location directly, offering door-to-door service that fixed rail lines cannot match."),
  _q("Air transport is most appropriate for goods that are",
      ["perishable, urgently needed, or of high value relative to their bulk", "extremely heavy and bulky with a low market value", "intended only for local, short-distance delivery", "hazardous liquids meant for pipeline transport"], "perishable, urgently needed, or of high value relative to their bulk",
      "Air transport, though costly, is fast and ideal for perishables, urgent shipments, and high-value low-bulk goods where speed outweighs the higher freight cost."),
  _q("Pipeline transport is most commonly used to move",
      ["liquids and gases such as crude oil, refined petroleum, and natural gas", "packaged consumer goods to retail stores", "passengers between cities", "bulky solid minerals such as iron ore"], "liquids and gases such as crude oil, refined petroleum, and natural gas",
      "Pipelines are specialised for continuously transporting liquids and gases, such as crude oil and natural gas, over long distances."),
  _q("A 'freight forwarder' in transport is an agent who",
      ["arranges the shipment and documentation of goods on behalf of exporters and importers", "personally owns and operates all the ships used in a trade route", "manufactures containers used for shipping goods", "sets government policy on international shipping routes"], "arranges the shipment and documentation of goods on behalf of exporters and importers",
      "A freight forwarder organises transportation, customs documentation, and related logistics for shippers, without necessarily owning the means of transport."),
  _q("Containerisation in shipping mainly benefits trade by",
      ["speeding up the loading, unloading, and handling of goods while reducing damage and pilferage", "eliminating the need for any form of insurance", "making air transport entirely unnecessary", "increasing the time goods spend in port"], "speeding up the loading, unloading, and handling of goods while reducing damage and pilferage",
      "Standardised containers allow for faster mechanised handling at ports, reduce cargo damage, and lower the risk of theft compared to loose cargo."),
  _q("Inland waterway transport (using rivers and canals) is particularly suited for",
      ["moving bulky, low-value goods cheaply where navigable waterways exist", "delivering urgent perishable goods across continents", "transporting passengers who require the fastest possible journey", "moving small parcels directly to individual homes"], "moving bulky, low-value goods cheaply where navigable waterways exist",
      "Where rivers and canals are navigable, waterway transport offers a cheap means of moving heavy, bulky cargo, though it is slower than road or rail."),
];

final _communicationAdvertising = [
  _q("Communication is regarded as an aid to trade because it",
      ["enables the exchange of business information between traders, producers, and consumers", "physically transports goods from producers to consumers", "provides financial compensation for losses in transit", "stores goods until they are demanded by the market"], "enables the exchange of business information between traders, producers, and consumers",
      "Effective communication allows business information, orders, and instructions to flow quickly between the parties involved in trade, supporting decision-making."),
  _q("Which of the following is classified as a means of written business communication?",
      ["A business letter", "A telephone conversation", "A radio jingle", "A face-to-face meeting"], "A business letter",
      "A business letter is a formal written record of communication, distinct from oral means such as telephone calls or face-to-face meetings."),
  _q("Advertising is best defined as",
      ["a paid, non-personal form of communication used to promote goods, services, or ideas", "the free distribution of goods to consumers as samples", "a legal document authorising the sale of a product", "the physical process of delivering goods to a retailer"], "a paid, non-personal form of communication used to promote goods, services, or ideas",
      "Advertising involves paying for space or time in media to present a persuasive, non-personal message about a product, service, or idea to a target audience."),
  _q("Informative advertising is primarily aimed at",
      ["creating awareness about a new product and its features", "persuading customers to switch from a well-known competing brand", "reminding loyal customers to keep repurchasing a familiar product", "discouraging the use of a rival's product through direct comparison"], "creating awareness about a new product and its features",
      "Informative advertising is typically used when a product is new, focusing on educating the market about its existence and features."),
  _q("Persuasive advertising is mainly used to",
      ["convince consumers to prefer a particular brand over competing alternatives", "provide purely technical specifications with no promotional tone", "inform the government about a company's tax obligations", "record a company's financial transactions for the year"], "convince consumers to prefer a particular brand over competing alternatives",
      "Persuasive advertising seeks to build preference and loyalty for a brand, often used in competitive markets to sway consumer choice."),
  _q("Which of the following best describes 'reminder advertising'?",
      ["Advertising aimed at keeping an already well-established product in the consumer's mind", "Advertising used only when a completely new product is launched", "Advertising that provides no brand name or product information", "Advertising restricted exclusively to government-owned media"], "Advertising aimed at keeping an already well-established product in the consumer's mind",
      "Reminder advertising is used for mature, well-known products to maintain consumer awareness and loyalty rather than to inform or persuade about something new."),
  _q("A major criticism often levelled against advertising is that it can",
      ["increase the final cost of goods to consumers by adding to marketing expenses", "always reduce the price of goods for consumers", "eliminate all forms of brand competition in a market", "make it impossible for new products to be introduced"], "increase the final cost of goods to consumers by adding to marketing expenses",
      "Advertising costs are often passed on to consumers through higher prices, which is one of the main criticisms raised against extensive advertising."),
];

final _warehousing = [
  _q("A bonded warehouse is one in which imported goods are stored",
      ["without payment of import duty until the goods are released for sale", "only after the full import duty has already been paid", "exclusively for goods manufactured within the country", "for a maximum period of twenty-four hours only"], "without payment of import duty until the goods are released for sale",
      "Goods kept in a bonded warehouse are held under customs supervision, and import duty is only paid when the goods are withdrawn for domestic sale or use."),
  _q("A private warehouse, as opposed to a public warehouse, is typically",
      ["owned and used exclusively by one particular firm for its own goods", "available for hire by any member of the public", "operated directly by the government for all traders", "used only for storing goods awaiting export documentation"], "owned and used exclusively by one particular firm for its own goods",
      "A private warehouse belongs to a single business and stores only that firm's own goods, unlike a public warehouse, which offers storage space to any trader for a fee."),
  _q("One key function of warehousing in the chain of distribution is to",
      ["hold goods in storage until they are needed, helping to stabilise supply and prices", "transport goods from the factory directly to the final consumer", "provide loans to producers for expanding their factories", "advertise a producer's goods to potential buyers"], "hold goods in storage until they are needed, helping to stabilise supply and prices",
      "By storing surplus goods when supply is high and releasing them when demand rises, warehousing helps smooth out fluctuations in market supply and price."),
  _q("Cold storage warehouses are specially designed to",
      ["preserve perishable goods such as fruits, vegetables, and meat at low temperatures", "store highly flammable liquids away from residential areas", "hold bonded goods awaiting payment of customs duty", "provide office space for a company's administrative staff"], "preserve perishable goods such as fruits, vegetables, and meat at low temperatures",
      "Cold storage facilities maintain low temperatures to slow spoilage, extending the shelf life of perishable commodities."),
];

final _marketing = [
  _q("Marketing is best defined as the process of",
      ["identifying, anticipating, and satisfying customer needs profitably", "manufacturing goods without any regard for consumer demand", "transporting raw materials from farms to factories", "recording a firm's financial transactions for tax purposes"], "identifying, anticipating, and satisfying customer needs profitably",
      "Marketing encompasses all activities involved in understanding what customers want and delivering it profitably, from product design through to sale."),
  _q("The 'marketing mix' traditionally consists of the four elements known as",
      ["Product, Price, Place, and Promotion", "Production, Personnel, Profit, and Planning", "Supply, Demand, Equilibrium, and Elasticity", "Import, Export, Tariff, and Quota"], "Product, Price, Place, and Promotion",
      "The classic '4Ps' of the marketing mix — Product, Price, Place, and Promotion — represent the key controllable variables a firm blends to reach its target market."),
  _q("Market segmentation refers to the practice of",
      ["dividing a broad market into smaller groups of consumers with similar needs or characteristics", "combining all consumers into a single undifferentiated target group", "restricting a product's sale to only one geographic region permanently", "eliminating competition by merging with rival firms"], "dividing a broad market into smaller groups of consumers with similar needs or characteristics",
      "Segmentation breaks a heterogeneous market into more homogeneous sub-groups (by age, income, location, etc.) so a firm can target its offerings more effectively."),
  _q("Market research is primarily carried out to",
      ["gather and analyse information about consumers and markets to guide business decisions", "physically distribute goods to wholesalers and retailers", "set the exact legal price at which all firms must sell a product", "replace the need for advertising a new product"], "gather and analyse information about consumers and markets to guide business decisions",
      "Market research systematically collects data on consumer preferences, competitors, and market trends to inform decisions on products, pricing, and promotion."),
  _q("A product's 'brand' mainly serves to",
      ["distinguish it from competitors' products in the minds of consumers", "determine the exact ingredients used in its manufacture", "fix the legal import duty payable on the product", "guarantee that the product will never require advertising"], "distinguish it from competitors' products in the minds of consumers",
      "Branding uses a name, symbol, or design to give a product a distinct identity, helping consumers recognise and prefer it over competing alternatives."),
  _q("Which stage of the product life cycle is typically characterised by rapidly rising sales and increasing competition?",
      ["Growth stage", "Introduction stage", "Decline stage", "Maturity stage's final phase before withdrawal"], "Growth stage",
      "During the growth stage, sales rise quickly as the product gains market acceptance, attracting new competitors into the market."),
  _q("Personal selling, as an element of promotion, is most valuable because it allows",
      ["direct, two-way interaction between a salesperson and a potential customer", "a message to reach millions of people simultaneously at minimal cost", "a firm to avoid any direct contact with its customers", "products to be sold without any need for pricing decisions"], "direct, two-way interaction between a salesperson and a potential customer",
      "Unlike mass advertising, personal selling involves direct, face-to-face communication that allows immediate feedback and tailored persuasion."),
  _q("Sales promotion techniques such as discounts, coupons, and free samples are mainly used to",
      ["stimulate a short-term increase in the sale of a product", "permanently replace the need for a sales force", "reduce the overall quality of a product to cut costs", "eliminate the need for market segmentation"], "stimulate a short-term increase in the sale of a product",
      "Sales promotions are short-term incentives designed to encourage an immediate boost in purchases, distinct from long-term brand-building advertising."),
];

final _legalAspects = [
  _q("For a business contract to be legally valid, it must generally include",
      ["offer, acceptance, consideration, and the intention to create legal relations", "only a verbal agreement between two friends", "the signature of a government official", "a guarantee that neither party can ever be sued"], "offer, acceptance, consideration, and the intention to create legal relations",
      "A valid contract typically requires a clear offer, an unqualified acceptance, consideration (something of value exchanged), and genuine intent to be legally bound."),
  _q("'Consideration' in contract law refers to",
      ["something of value given by each party to the other as part of the bargain", "the careful thought a person gives before signing any document", "a court's judgment awarded after a contractual dispute", "the government's approval required before any contract is signed"], "something of value given by each party to the other as part of the bargain",
      "Consideration is the price paid for a promise — each party to a contract must give or promise something of value in return for what they receive."),
  _q("A contract entered into by a minor (person under the age of legal majority) for non-necessary goods is generally",
      ["voidable at the option of the minor", "automatically binding on both parties without exception", "always enforceable against the minor's guardian", "treated exactly the same as a contract between two adults"], "voidable at the option of the minor",
      "Contracts made by minors for non-necessaries are generally voidable, meaning the minor may choose to affirm or repudiate the contract, protecting them from exploitation."),
  _q("A contract is said to be 'discharged by performance' when",
      ["both parties have fully carried out their obligations under the agreement", "one party dies before the contract can be completed", "a court declares the contract illegal from the outset", "the contract is cancelled by mutual agreement before it starts"], "both parties have fully carried out their obligations under the agreement",
      "Discharge by performance occurs when each party completes exactly what they promised to do under the contract, bringing it to a natural end."),
  _q("'Breach of contract' occurs when",
      ["one party fails, without lawful excuse, to fulfil their obligations under the agreement", "both parties mutually agree to end the contract early", "a contract is discharged through full performance by both sides", "a contract becomes impossible to perform due to a natural disaster"], "one party fails, without lawful excuse, to fulfil their obligations under the agreement",
      "A breach happens when a party fails to perform their contractual duties without a valid legal justification, entitling the other party to remedies such as damages."),
  _q("The Sale of Goods legislation implies that goods sold by description must",
      ["correspond with that description", "always be the cheapest available in the market", "be manufactured only within the buyer's home country", "be sold without any form of receipt or invoice"], "correspond with that description",
      "Under sale of goods principles, when goods are sold by description, there is an implied condition that the actual goods delivered will match that description."),
  _q("Under agency law, a 'principal' is the party who",
      ["authorises another person (the agent) to act on their behalf", "always personally negotiates and signs every business contract", "is legally barred from being represented by any other person", "can never be held liable for the acts of their agent"], "authorises another person (the agent) to act on their behalf",
      "In an agency relationship, the principal grants authority to an agent to act and make decisions on their behalf within agreed limits."),
];

final _businessManagement = [
_q("Which of the following is widely regarded as one of the primary functions of management?",
      ["Planning, organising, directing, and controlling", "Manufacturing, importing, exporting, and warehousing", "Advertising, branding, packaging, and pricing only", "Borrowing, lending, saving, and investing only"], "Planning, organising, directing, and controlling",
      "Classical management theory identifies planning, organising, directing (leading), and controlling as the core functions performed by managers."),
_q("'Planning', as a function of management, mainly involves",
      ["setting objectives and deciding in advance the course of action to achieve them", "physically supervising workers on the factory floor", "recording daily cash transactions in the account books", "distributing finished products to wholesalers and retailers"], "setting objectives and deciding in advance the course of action to achieve them",
      "Planning is the forward-looking management function of setting goals and determining the best strategies and actions to reach them."),
];
