import "../quiz_question.dart";

const _subject = "Christian Religious Studies";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// Obafemi Awolowo University (OAU) Post-UTME Christian Religious Studies
/// (CRS) elective bank — 100 medium-to-hard, original questions covering
/// Old Testament themes (Creation/Fall/Punishment, Authority of God,
/// Kingship in Israel, Divided Kingdom/Prophets, Exile and Return) and New
/// Testament themes (Life of Christ, Passion Week, Teachings of Jesus,
/// Early Church, Christian Virtues in Society). This is an independent
/// practice set, not an official OAU past-question paper; always confirm
/// the exact syllabus and format on OAU's own screening portal.
List<QuizQuestion> buildOauCrsQuestions() {
  return [
    ..._creationFallPunishment,
    ..._authorityOfGod,
    ..._kingshipInIsrael,
    ..._dividedKingdomProphets,
    ..._exileAndReturn,
    ..._lifeOfChrist,
    ..._passionWeek,
    ..._teachingsOfJesus,
    ..._earlyChurch,
    ..._christianVirtues,
  ];
}

final _creationFallPunishment = [
  _q("In the Genesis creation narrative, what was created on the fourth day?",
      ["The sun, moon, and stars", "Land animals and man", "Birds and sea creatures", "Light and darkness"], "The sun, moon, and stars",
      "Genesis 1:14-19 records that God made the greater and lesser lights, and the stars, on the fourth day to govern day and night."),
  _q("Which phrase best describes the theological significance of man being made 'in the image of God' in Genesis 1?",
      ["Man possesses a unique moral and spiritual likeness to God, distinct from other creatures", "Man is physically identical to God in form", "Man was created before every other living thing", "Man alone was formed from the dust of the ground"], "Man possesses a unique moral and spiritual likeness to God, distinct from other creatures",
      "The 'image of God' (imago Dei) points to humanity's unique capacity for reason, moral responsibility, and relationship with God, setting humans apart from the rest of creation."),
  _q("In the Garden of Eden, God placed man there primarily to",
      ["dress and keep the garden", "rule over the angels", "build an altar for sacrifice", "name the stars"], "dress and keep the garden",
      "Genesis 2:15 states God put the man in the Garden of Eden 'to dress it and to keep it', indicating humanity's stewardship role."),
  _q("The serpent's temptation of Eve in Genesis 3 was primarily built on",
      ["casting doubt on God's word and promising equality with God", "a direct threat of physical violence", "an offer of material wealth", "a promise of political power over Adam"], "casting doubt on God's word and promising equality with God",
      "The serpent questioned God's command ('Yea, hath God said...') and promised that eating the fruit would make Eve like God, knowing good and evil."),
  _q("Immediately after eating the forbidden fruit, Adam and Eve's first reaction was to",
      ["realise their nakedness and sew fig leaves to cover themselves", "confess openly to God without hesitation", "build an altar of repentance", "flee permanently from the garden before God spoke to them"], "realise their nakedness and sew fig leaves to cover themselves",
      "Genesis 3:7 records that their eyes were opened, they knew they were naked, and they sewed fig leaves together as makeshift coverings."),
  _q("When God confronted Adam about eating the forbidden fruit, Adam's response revealed",
      ["an attempt to shift blame onto Eve and, indirectly, onto God", "immediate and full repentance", "a refusal to answer at all", "an admission that the serpent had physically forced him"], "an attempt to shift blame onto Eve and, indirectly, onto God",
      "Adam replied that 'the woman whom thou gavest to be with me, she gave me of the tree', deflecting responsibility onto Eve and implicitly onto God's gift of her."),
  _q("As part of the curse pronounced on the serpent in Genesis 3, God declared that",
      ["it would crawl on its belly and eat dust, with enmity between its seed and the woman's seed", "it would be struck blind for its deception", "it would be cast into a pit of fire immediately", "it would lose the power of speech forever"], "it would crawl on its belly and eat dust, with enmity between its seed and the woman's seed",
      "Genesis 3:14-15 records the serpent's curse, including the protoevangelium ('he shall bruise thy head'), traditionally read as the first promise of redemption."),
  _q("The immediate practical consequence of Adam and Eve's expulsion from Eden included",
      ["being barred from the tree of life by cherubim with a flaming sword", "the immediate death of both of them that same day", "the loss of the ability to have children", "the destruction of the entire garden"], "being barred from the tree of life by cherubim with a flaming sword",
      "Genesis 3:24 describes God placing cherubim and a flaming sword at the east of Eden to guard the way to the tree of life after their expulsion."),
  _q("The story of Cain and Abel primarily illustrates the consequence of",
      ["jealousy and anger leading to the first murder", "the first act of idol worship", "disobedience to a direct command not to farm", "the origin of the Israelite priesthood"], "jealousy and anger leading to the first murder",
      "Cain's resentment over God's regard for Abel's offering, rather than his own, led him to murder his brother, introducing sin's escalating consequences after the Fall."),
  _q("God's punishment of Cain after he murdered Abel included",
      ["becoming a restless wanderer on the earth, though marked for protection", "immediate death by God's own hand", "being turned into a pillar of salt", "forty years of wandering in the wilderness"], "becoming a restless wanderer on the earth, though marked for protection",
      "Genesis 4:12-15 records that Cain was cursed to wander the earth, yet God placed a mark on him so that no one who found him would kill him."),
];

final _authorityOfGod = [
  _q("God's call of Abram in Genesis 12 to leave his country primarily demonstrated",
      ["God's sovereign authority to choose and direct individuals for His purposes", "Abram's own initiative in seeking a new god", "a punishment for Abram's past sins", "the beginning of the Israelite monarchy"], "God's sovereign authority to choose and direct individuals for His purposes",
      "God's unprompted call to Abram, promising to make him a great nation, shows divine initiative and authority in shaping salvation history."),
  _q("The covenant of circumcision given to Abraham in Genesis 17 served chiefly as",
      ["a physical sign of the covenant between God and Abraham's descendants", "a form of medical hygiene practice only", "a punishment for Ishmael's birth", "a requirement introduced only under Moses"], "a physical sign of the covenant between God and Abraham's descendants",
      "Genesis 17 establishes circumcision as the perpetual sign marking Abraham's household as party to God's covenant promise."),
  _q("God's command to Abraham to sacrifice Isaac on Mount Moriah is best understood as a test of",
      ["Abraham's faith and total obedience to God", "Isaac's willingness to die for his father", "the strength of Abraham's physical endurance", "Sarah's loyalty to her husband"], "Abraham's faith and total obedience to God",
      "God's instruction, later stayed by the provision of a ram, revealed and confirmed Abraham's unwavering trust and obedience to divine authority."),
  _q("Joshua's authority to lead Israel after Moses' death was chiefly established through",
      ["God's direct commissioning and the people's recognition of his leadership", "a popular election among the twelve tribes", "his marriage into the priestly line of Aaron", "his defeat of Pharaoh's army"], "God's direct commissioning and the people's recognition of his leadership",
      "God directly commanded Joshua to be strong and of good courage, assuring him of divine presence, and the people pledged obedience to him as they had to Moses."),
  _q("At the crossing of the Jordan River under Joshua, the priests bearing the Ark of the Covenant",
      ["stood in the riverbed while the waters were held back until all Israel had crossed", "were swept away by the flooding river", "remained on the western bank throughout the crossing", "carried the Ark across on a wooden bridge"], "stood in the riverbed while the waters were held back until all Israel had crossed",
      "Joshua 3 records that as the priests' feet touched the Jordan, the waters were cut off, and they stood firmly in the dry riverbed until the whole nation had passed over."),
  _q("The account of Achan's sin at Jericho in Joshua 7 illustrates the principle that",
      ["disobedience by one individual can bring judgement upon the wider community", "personal sin has no effect on communal fortune", "only leaders are held accountable for national sin", "wealth taken in battle always belongs to the victors"], "disobedience by one individual can bring judgement upon the wider community",
      "Achan's theft of devoted items from Jericho brought Israel's subsequent defeat at Ai, teaching that hidden sin can have communal consequences under God's covenant authority."),
  _q("Deborah's role among the judges of Israel is notable chiefly because she",
      ["served as both a prophetess and a judge who directed Barak into battle", "was the first woman ever mentioned in the Old Testament", "was appointed king over Israel", "led Israel out of Egyptian slavery"], "served as both a prophetess and a judge who directed Barak into battle",
      "Judges 4-5 present Deborah as a prophetess and judge whose counsel and presence emboldened Barak to lead Israel's forces against Sisera's army."),
  _q("Gideon's demand for a sign before leading Israel against Midian reflects",
      ["human hesitation seeking assurance of God's authority and presence", "outright rebellion against God's command", "a rejection of his calling as judge", "a request to be replaced by another leader"], "human hesitation seeking assurance of God's authority and presence",
      "Though eventually obedient, Gideon's repeated requests for confirming signs (the fleece) reveal a cautious faith seeking certainty of divine backing."),
  _q("The reduction of Gideon's army from 32,000 to 300 men before the battle with Midian was intended to",
      ["ensure that Israel would credit the victory to God's power rather than human strength", "save money on provisions for the campaign", "punish the fearful soldiers who were dismissed", "test the loyalty of Gideon's family"], "ensure that Israel would credit the victory to God's power rather than human strength",
      "God explicitly told Gideon the army was too large, 'lest Israel vaunt themselves...saying, Mine own hand hath saved me.'"),
  _q("Samson's Nazarite status, described in Judges 13, obligated him to avoid all of the following EXCEPT",
      ["offering sacrifices at the temple", "cutting his hair", "consuming wine or strong drink", "touching a dead body"], "offering sacrifices at the temple",
      "The Nazarite vow, given even before Samson's birth, required abstaining from wine, avoiding contact with the dead, and never cutting his hair; offering sacrifices was not among these specific restrictions."),
];

final _kingshipInIsrael = [
  _q("The Israelites' demand for a king in 1 Samuel 8 was primarily motivated by their desire to",
      ["be like other nations and have a visible, permanent leader", "restore worship of God at Shiloh", "replace the failing system of judges with priests", "unite the twelve tribes under Moses' descendants"], "be like other nations and have a visible, permanent leader",
      "1 Samuel 8:5 records the elders asking Samuel to 'make us a king to judge us like all the nations', a request God interpreted as a rejection of His own kingship over them."),
  _q("Samuel warned the Israelites that having a king would result in",
      ["heavy taxation, conscription, and loss of personal freedoms", "immediate peace and prosperity for all", "the abolition of the priesthood", "permanent exemption from military service"], "heavy taxation, conscription, and loss of personal freedoms",
      "1 Samuel 8:11-18 details Samuel's warning that a king would take their sons for war, their daughters for service, and a tenth of their produce and flocks."),
  _q("Saul's rejection as king was finally sealed after he",
      ["spared King Agag and the best Amalekite livestock against God's explicit instruction", "lost the battle against the Philistines at Gilboa", "married a foreign wife against God's law", "refused to be anointed by Samuel"], "spared King Agag and the best Amalekite livestock against God's explicit instruction",
      "1 Samuel 15 records Saul's incomplete obedience in the campaign against Amalek, after which Samuel declared that God had rejected him from being king."),
  _q("David's selection and anointing by Samuel in 1 Samuel 16 emphasised the principle that",
      ["God looks on the heart rather than outward appearance", "the eldest son always inherits leadership", "only warriors could be chosen as king", "kingship was determined strictly by tribal lineage"], "God looks on the heart rather than outward appearance",
      "When Samuel considered Jesse's elder sons, God told him, 'the Lord looketh on the heart', ultimately leading to the anointing of the youngest, David."),
  _q("Before becoming king, David demonstrated restraint toward Saul by",
      ["sparing Saul's life on two occasions despite having the opportunity to kill him", "publicly challenging Saul to single combat", "handing Saul over to the Philistines", "refusing to ever serve in Saul's court"], "sparing Saul's life on two occasions despite having the opportunity to kill him",
      "David spared Saul's life in the cave at En-gedi and again in the camp at Hachilah, respecting Saul as 'the Lord's anointed' despite Saul's pursuit of him."),
  _q("The Davidic covenant recorded in 2 Samuel 7 chiefly promised that",
      ["David's throne and dynasty would be established forever", "David would personally build the Temple", "David's descendants would rule only over Judah", "Israel would never again be threatened by enemies"], "David's throne and dynasty would be established forever",
      "God, through the prophet Nathan, promised David an everlasting dynasty, a promise later understood as pointing toward the Messiah."),
  _q("Solomon's request to God at Gibeon for 'an understanding heart' rather than riches or long life resulted in",
      ["God granting him wisdom along with unrequested riches and honour", "God rebuking him for asking too little", "God granting only wisdom, withholding all material blessing", "no response from God at that time"], "God granting him wisdom along with unrequested riches and honour",
      "1 Kings 3 records that because Solomon asked for discernment to judge the people, God gave him a wise heart, and also riches and honour he had not requested."),
  _q("The construction of Solomon's Temple in Jerusalem was significant chiefly because it",
      ["provided a permanent central place of worship, replacing the portable tabernacle", "was built entirely by Israelite slave labour", "was completed within one year of Solomon's reign", "was the first place sacrifices were ever offered to God"], "provided a permanent central place of worship, replacing the portable tabernacle",
      "The Temple fulfilled David's desire for a fixed dwelling place for the Ark of the Covenant and became the centre of Israelite worship."),
  _q("Which of the following contributed most directly to Solomon's spiritual decline in his later years?",
      ["His many foreign wives turning his heart toward idol worship", "His refusal to complete the building of the Temple", "His excessive military campaigns against Israel's neighbours", "His decision to move the capital away from Jerusalem"], "His many foreign wives turning his heart toward idol worship",
      "1 Kings 11 records that Solomon's foreign wives 'turned away his heart after other gods', leading him to build high places for their idols."),
  _q("Rehoboam's harsh response to the northern tribes' request for lighter labour, following his father Solomon's reign, directly led to",
      ["the division of the united kingdom into Israel and Judah", "a renewed covenant with all twelve tribes", "the immediate destruction of Jerusalem", "the appointment of Jeroboam as high priest"], "the division of the united kingdom into Israel and Judah",
      "1 Kings 12 records that Rehoboam's threat to increase, rather than lighten, the people's burdens caused the ten northern tribes to rebel under Jeroboam, splitting the kingdom."),
];

final _dividedKingdomProphets = [
  _q("Jeroboam, first king of the northern kingdom of Israel, is chiefly remembered for",
      ["setting up golden calves at Bethel and Dan to prevent the people worshipping in Jerusalem", "rebuilding the Temple in Jerusalem", "reuniting Israel and Judah under one throne", "defeating the Assyrian empire in battle"], "setting up golden calves at Bethel and Dan to prevent the people worshipping in Jerusalem",
      "Fearing his subjects would return their allegiance to Rehoboam if they worshipped in Jerusalem, Jeroboam instituted alternative worship centres with golden calves, a sin repeatedly referenced in later scripture."),
  _q("The contest between Elijah and the prophets of Baal on Mount Carmel was ultimately decided by",
      ["fire falling from heaven to consume Elijah's sacrifice after his prayer", "a vote among the assembled Israelites", "a wrestling match between Elijah and the chief prophet of Baal", "a sudden famine ending the contest"], "fire falling from heaven to consume Elijah's sacrifice after his prayer",
      "1 Kings 18 records that after the prophets of Baal failed to elicit any response, God answered Elijah's prayer by sending fire that consumed the sacrifice, water, and altar."),
  _q("After his victory on Mount Carmel, Elijah's flight into the wilderness and subsequent despair at Horeb reveal",
      ["that even faithful prophets can experience deep fear and discouragement", "that Elijah had lost his prophetic calling permanently", "that God abandoned Elijah after his failure", "that Elijah's victory was later proven false"], "that even faithful prophets can experience deep fear and discouragement",
      "Despite his dramatic triumph, Elijah fled from Jezebel's threat and even asked to die, showing his humanity; God responded with gentle provision and renewed commission rather than rebuke."),
  _q("Naboth's vineyard, seized by King Ahab through Jezebel's scheme, became a symbol of",
      ["royal abuse of power and injustice against ordinary citizens", "God's blessing on Ahab's reign", "the proper use of eminent domain by kings", "reconciliation between Ahab and the prophets"], "royal abuse of power and injustice against ordinary citizens",
      "1 Kings 21 recounts how Jezebel arranged false charges leading to Naboth's death so Ahab could seize his vineyard, prompting Elijah's prophetic condemnation of the royal household."),
  _q("The prophet Amos, though from Judah, directed most of his prophetic ministry against",
      ["the northern kingdom of Israel, particularly its social injustice", "the Assyrian empire directly", "the priests of Jerusalem alone", "the Egyptian Pharaoh"], "the northern kingdom of Israel, particularly its social injustice",
      "Amos, a shepherd from Tekoa in Judah, was sent to prophesy against Israel's exploitation of the poor and its hollow religious observance."),
  _q("Amos's famous declaration to 'let judgement run down as waters, and righteousness as a mighty stream' was primarily a call for",
      ["genuine social justice rather than empty ritual worship", "the immediate restoration of the monarchy", "an end to all sacrificial offerings", "reconciliation between Israel and Judah"], "genuine social justice rather than empty ritual worship",
      "Amos 5:24 rejects festivals and offerings offered without corresponding justice, insisting that true worship must be accompanied by righteous conduct."),
  _q("Hosea's marriage to Gomer functioned in his prophecy chiefly as",
      ["a living symbol of God's persistent love for an unfaithful Israel", "a warning against marrying outside one's tribe", "an example of ideal marital fidelity", "a political alliance arranged by King Jeroboam II"], "a living symbol of God's persistent love for an unfaithful Israel",
      "God commanded Hosea to marry Gomer, whose unfaithfulness mirrored Israel's spiritual adultery, while Hosea's continued love for her illustrated God's covenant faithfulness."),
  _q("Isaiah's vision of God's holiness in the Temple (Isaiah 6) led him to respond with",
      ["a confession of his own uncleanness before volunteering for God's mission", "immediate silence and refusal to speak", "a request to be excused from prophetic service", "an argument with God about the vision's meaning"], "a confession of his own uncleanness before volunteering for God's mission",
      "Overwhelmed by God's holiness, Isaiah cried 'Woe is me...I am a man of unclean lips', but after his cleansing by a seraph, he responded to God's call with 'Here am I; send me.'"),
  _q("Jeremiah's 'Temple Sermon' (Jeremiah 7) chiefly warned the people of Judah against",
      ["trusting in the mere presence of the Temple while continuing in injustice and idolatry", "abandoning the Temple altogether", "allowing foreigners to worship at the Temple", "rebuilding the Temple without royal permission"], "trusting in the mere presence of the Temple while continuing in injustice and idolatry",
      "Jeremiah rebuked the false confidence expressed in the repeated cry 'The temple of the Lord', warning that its presence would not protect a people persisting in sin."),
  _q("Jeremiah's use of the image of a potter and clay (Jeremiah 18) was meant to illustrate",
      ["God's sovereign authority to shape and reshape the destiny of nations", "the fragility of the Israelite economy", "the process of Temple construction", "the origin of pottery as a trade in Judah"], "God's sovereign authority to shape and reshape the destiny of nations",
      "As the potter reworks marred clay, Jeremiah taught that God retains the sovereign right to shape, judge, or restore a nation according to its response to Him."),
];

final _exileAndReturn = [
  _q("The Babylonian exile of Judah followed most immediately from",
      ["persistent idolatry and injustice despite repeated prophetic warnings", "a sudden, unprovoked invasion with no prior warning", "a peaceful treaty that was later broken by Babylon alone", "a natural disaster that destabilised the kingdom"], "persistent idolatry and injustice despite repeated prophetic warnings",
      "Prophets such as Jeremiah repeatedly warned Judah that continued unfaithfulness to the covenant would bring judgement, culminating in Babylon's conquest and the exile."),
  _q("Daniel and his companions' resolve not to defile themselves with the king's food in Babylon primarily demonstrated",
      ["faithfulness to God's law even while living under a foreign, pagan authority", "a rejection of all forms of secular education", "political rebellion against Nebuchadnezzar", "a permanent refusal to serve in the Babylonian court"], "faithfulness to God's law even while living under a foreign, pagan authority",
      "Daniel 1 records that Daniel purposed in his heart not to defile himself, choosing a diet consistent with his convictions while still serving faithfully within the Babylonian system."),
  _q("The account of Shadrach, Meshach, and Abednego in the fiery furnace primarily illustrates",
      ["unwavering faith and loyalty to God even under threat of death", "the failure of prayer to change one's circumstances", "the Babylonian king's tolerance of all religions", "the futility of refusing to worship idols"], "unwavering faith and loyalty to God even under threat of death",
      "Daniel 3 shows the three men refusing to bow to Nebuchadnezzar's golden image even at the risk of execution, and being miraculously preserved in the furnace."),
  _q("Daniel's experience in the lions' den (Daniel 6) resulted primarily from",
      ["a jealous plot by officials to trap him through his faithful practice of prayer", "his refusal to interpret the king's dream", "an accusation of theft from the royal treasury", "his failure to complete an assigned government task"], "a jealous plot by officials to trap him through his faithful practice of prayer",
      "Jealous officials persuaded King Darius to sign a decree banning prayer to anyone but the king, specifically to entrap Daniel because of his consistent devotion to God."),
  _q("The 'writing on the wall' interpreted by Daniel for King Belshazzar announced",
      ["the imminent end of Belshazzar's kingdom and its division", "a coming famine across Babylon", "the birth of a future deliverer", "a call for national repentance and forgiveness"], "the imminent end of Belshazzar's kingdom and its division",
      "Daniel 5 records that 'Mene, Mene, Tekel, Upharsin' foretold that Belshazzar's kingdom had been numbered, weighed, and found wanting, and would be given to the Medes and Persians."),
  _q("The decree of King Cyrus of Persia, recorded in Ezra 1, permitted the exiled Jews to",
      ["return to Jerusalem and rebuild the Temple of the Lord", "settle permanently within the Persian royal court", "retain exile status but with greater freedoms", "establish an independent kingdom under Persian protection"], "return to Jerusalem and rebuild the Temple of the Lord",
      "Cyrus's decree fulfilled earlier prophecy by authorising the Jewish exiles to return home and rebuild the house of the Lord in Jerusalem."),
  _q("The rebuilding of the Jerusalem Temple under Zerubbabel faced significant opposition mainly from",
      ["surrounding peoples who sought to discourage and delay the work", "a rival faction among the returning exiles themselves", "the Persian king, who later reversed his decree", "the prophets Haggai and Zechariah"], "surrounding peoples who sought to discourage and delay the work",
      "Ezra 4 records that adversaries of Judah and Benjamin worked to frustrate the rebuilding effort through discouragement, intimidation, and appeals to Persian authorities."),
  _q("Nehemiah's primary mission when he returned to Jerusalem was to",
      ["rebuild the broken walls of Jerusalem", "rebuild the Temple from its foundations", "reestablish the Davidic monarchy", "translate the Law into Aramaic"], "rebuild the broken walls of Jerusalem",
      "Nehemiah, cupbearer to King Artaxerxes, was moved by the report of Jerusalem's ruined walls and gained permission to return and lead their reconstruction."),
  _q("Nehemiah's response to opposition from Sanballat and Tobiah during the wall-building project was to",
      ["organise the workers to build with a weapon in one hand while remaining vigilant", "abandon the project until the opposition ceased", "seek Persian military intervention against them", "negotiate a compromise that halted construction"], "organise the workers to build with a weapon in one hand while remaining vigilant",
      "Nehemiah 4 describes the builders working with tools in one hand and weapons in the other, maintaining constant vigilance against the threats of their opponents."),
  _q("Ezra's public reading and exposition of the Law of Moses to the returned exiles (Nehemiah 8) resulted in",
      ["the people weeping in repentance and then celebrating with joy once they understood it", "widespread rejection of the Law by the assembly", "the exile of those who had intermarried with foreigners", "an immediate rebuilding of the Temple altar"], "the people weeping in repentance and then celebrating with joy once they understood it",
      "As the Levites helped the people understand the reading, they wept at their failure to keep the Law, but were then instructed to rejoice, since 'the joy of the Lord is your strength.'"),
];

final _lifeOfChrist = [
  _q("The angel Gabriel's announcement to Mary in Luke 1 is traditionally referred to as",
      ["the Annunciation", "the Magnificat", "the Transfiguration", "the Benediction"], "the Annunciation",
      "The angel's declaration that Mary would conceive and bear a son called Jesus is known in Christian tradition as the Annunciation."),
  _q("According to Luke's Gospel, Jesus was born in Bethlehem because",
      ["Joseph and Mary travelled there to register in a Roman census", "Nazareth had been destroyed by fire", "Herod ordered all pregnant women to relocate", "Bethlehem was Mary's ancestral hometown"], "Joseph and Mary travelled there to register in a Roman census",
      "Luke 2 records that a decree from Caesar Augustus required registration, and because Joseph was of the house of David, he travelled with Mary to Bethlehem, David's city."),
  _q("The visit of the Magi ('wise men') to the infant Jesus, recorded in Matthew 2, was prompted by",
      ["their observation of a star signifying the birth of a king", "a direct summons from King Herod", "an angelic appearance identical to the one given to the shepherds", "a prophecy they received from Jewish priests in their homeland"], "their observation of a star signifying the birth of a king",
      "Matthew 2:2 records the Magi's declaration that they had 'seen his star in the east' and had come to worship the newborn king."),
  _q("Herod's massacre of the male infants in Bethlehem was motivated chiefly by",
      ["fear of losing his throne to the newly announced 'King of the Jews'", "a religious ritual demanded by Roman authorities", "revenge against the shepherds who had spread news of Jesus' birth", "a response to a rebellion already underway in Bethlehem"], "fear of losing his throne to the newly announced 'King of the Jews'",
      "Matthew 2:16 describes Herod's murderous decree after realising the Magi had not returned to report the child's location, driven by insecurity over his own rule."),
  _q("John the Baptist's ministry in the wilderness is best summarised as one of",
      ["calling people to repentance in preparation for the coming Messiah", "establishing a new priesthood to rival the Temple", "leading an armed rebellion against Roman rule", "teaching exclusively within the Jerusalem synagogues"], "calling people to repentance in preparation for the coming Messiah",
      "John preached a baptism of repentance for the remission of sins, explicitly identifying himself as the one preparing 'the way of the Lord' before Jesus."),
  _q("At Jesus' baptism by John in the Jordan, the significance of the event was chiefly marked by",
      ["the Spirit descending like a dove and a voice affirming Him as God's beloved Son", "the parting of the Jordan River", "John's public refusal to baptise Jesus", "a great earthquake shaking the region"], "the Spirit descending like a dove and a voice affirming Him as God's beloved Son",
      "All three Synoptic Gospels record the Spirit's descent and the divine voice declaring, 'This is my beloved Son, in whom I am well pleased', affirming Jesus' identity and mission."),
  _q("In the wilderness temptation narratives, Jesus' consistent response to Satan's three temptations was to",
      ["quote Scripture to refute each temptation", "call down angels to drive Satan away", "remain completely silent throughout", "offer to compromise on one of the three temptations"], "quote Scripture to refute each temptation",
      "In each of the three temptations recorded in Matthew 4 and Luke 4, Jesus responded by citing Deuteronomy, demonstrating reliance on Scripture over self-interest."),
  _q("Jesus' first recorded miracle, turning water into wine at Cana, primarily served to",
      ["manifest His glory, leading His disciples to believe in Him", "provide food for a crowd of five thousand", "demonstrate His authority over illness", "fulfil a prophecy specifically about weddings"], "manifest His glory, leading His disciples to believe in Him",
      "John 2:11 states that this, the beginning of Jesus' miracles, 'manifested forth his glory; and his disciples believed on him.'"),
  _q("The calling of the first disciples by the Sea of Galilee, as recorded in the Synoptic Gospels, involved Jesus inviting fishermen to",
      ["leave their nets and become 'fishers of men'", "join Him only after completing formal rabbinic training", "pay a fee to become His followers", "wait until after His resurrection to follow Him"], "leave their nets and become 'fishers of men'",
      "Matthew 4:19 records Jesus calling Simon Peter and Andrew with the words, 'Follow me, and I will make you fishers of men', and they immediately left their nets."),
  _q("Jesus' transfiguration on the mountain, witnessed by Peter, James, and John, was significant chiefly because",
      ["His appearance was gloriously changed and He conversed with Moses and Elijah", "it marked the moment of His resurrection", "it occurred immediately before His arrest", "the crowd below also witnessed the event"], "His appearance was gloriously changed and He conversed with Moses and Elijah",
      "The transfiguration revealed Jesus' divine glory to the three disciples and connected His mission to the Law (Moses) and the Prophets (Elijah), affirmed by the Father's voice."),
];

final _passionWeek = [
  _q("Jesus' entry into Jerusalem on what is now called Palm Sunday fulfilled a prophecy that the coming king would arrive",
      ["lowly, and riding upon a donkey", "in a chariot with a great army", "under cover of darkness, unseen by the crowd", "bearing weapons of war"], "lowly, and riding upon a donkey",
      "Matthew 21:5 cites Zechariah's prophecy of a king coming 'meek, and sitting upon an ass', fulfilled as the crowds welcomed Jesus with palm branches and shouts of 'Hosanna.'"),
  _q("Jesus' cleansing of the Temple during Passion Week was directed chiefly against",
      ["merchants and money-changers who had turned it into a 'den of thieves'", "the Roman soldiers stationed within the Temple courts", "the Pharisees teaching in the Temple", "the priests performing daily sacrifices"], "merchants and money-changers who had turned it into a 'den of thieves'",
      "Jesus overturned the tables of the money-changers and those selling doves, declaring that His Father's house of prayer had been made 'a den of thieves.'"),
  _q("At the Last Supper, Jesus' institution of what Christians now call the Lord's Supper (Communion) centred on",
      ["bread and wine representing His body and blood given for His followers", "a ceremonial washing of hands before the Passover meal", "the reading of the entire Torah", "an oath of loyalty sworn by all twelve disciples"], "bread and wine representing His body and blood given for His followers",
      "Jesus took bread and wine, identifying them with His body and blood 'given for you', instituting a practice of ongoing remembrance among His followers."),
  _q("Jesus washing the disciples' feet at the Last Supper (John 13) was primarily intended to",
      ["model humble service as an example for His disciples to follow", "fulfil a Passover ritual requirement", "demonstrate His authority over Peter specifically", "prepare the disciples physically for travel"], "model humble service as an example for His disciples to follow",
      "After washing their feet, Jesus told the disciples, 'I have given you an example, that ye should do as I have done to you', teaching humble service."),
  _q("In the Garden of Gethsemane, Jesus' prayer 'not my will, but thine, be done' primarily reflects",
      ["His full submission to the Father's will despite the anguish of the coming crucifixion", "His uncertainty about whether He was truly the Messiah", "a request to be spared from crucifixion permanently", "His decision to abandon His mission"], "His full submission to the Father's will despite the anguish of the coming crucifixion",
      "Luke 22:42 records Jesus' agonised yet submissive prayer, expressing genuine human anguish alongside total obedience to God's redemptive plan."),
  _q("Judas Iscariot's betrayal of Jesus was carried out through",
      ["identifying Jesus to the arresting party with a kiss, for thirty pieces of silver", "publicly denouncing Jesus before the Sanhedrin", "leading a mob to stone Jesus", "reporting Jesus directly to Pontius Pilate"], "identifying Jesus to the arresting party with a kiss, for thirty pieces of silver",
      "Matthew 26 records Judas agreeing to betray Jesus for thirty pieces of silver and identifying Him to the soldiers with a prearranged kiss."),
  _q("Peter's denial of Jesus during the trial before the high priest was ultimately followed by",
      ["bitter weeping upon realising he had fulfilled Jesus' prediction", "immediate arrest alongside Jesus", "a public confession before the Sanhedrin", "his permanent departure from the group of disciples"], "bitter weeping upon realising he had fulfilled Jesus' prediction",
      "After denying Jesus three times, Peter heard the cock crow, remembered Jesus' prediction, and 'went out, and wept bitterly.'"),
  _q("Pilate's decision to release Barabbas instead of Jesus resulted mainly from",
      ["pressure from the crowd, incited by the chief priests", "Pilate's personal conviction that Barabbas was innocent", "a legal requirement to release the more dangerous prisoner", "Herod's direct order to Pilate"], "pressure from the crowd, incited by the chief priests",
      "Despite finding no fault in Jesus, Pilate yielded to the crowd, stirred up by the chief priests, who demanded Barabbas's release and Jesus' crucifixion."),
  _q("The inscription placed above Jesus on the cross, 'THE KING OF THE JEWS', was significant chiefly because",
      ["it was intended by Pilate as mockery, yet ironically proclaimed a profound truth", "it was written by the Jewish religious leaders themselves", "it was removed before the crucifixion began", "it referred to Barabbas rather than Jesus"], "it was intended by Pilate as mockery, yet ironically proclaimed a profound truth",
      "Though the chief priests objected to its wording, Pilate refused to alter the inscription, unwittingly affirming Jesus' true kingship even in mockery."),
  _q("The resurrection of Jesus on the third day is first discovered, according to the Gospel accounts, by",
      ["women, including Mary Magdalene, who came to the tomb", "the eleven remaining disciples together", "the Roman guards stationed at the tomb", "the high priest Caiaphas"], "women, including Mary Magdalene, who came to the tomb",
      "All four Gospels record that women, prominently Mary Magdalene, were the first to discover the empty tomb and receive news of the resurrection."),
];

final _teachingsOfJesus = [
  _q("In the Sermon on the Mount, the Beatitudes primarily describe",
      ["the character and blessedness of those who belong to God's kingdom", "a list of ritual obligations for Temple worship", "specific laws governing Sabbath observance", "instructions for the appointment of apostles"], "the character and blessedness of those who belong to God's kingdom",
      "Matthew 5:3-12 presents the Beatitudes as pronouncements of blessing on qualities such as humility, mercy, and purity of heart, describing kingdom values rather than legal rules."),
  _q("Jesus' teaching that His followers are 'the salt of the earth and the light of the world' primarily emphasises",
      ["the believer's positive, preserving, and illuminating influence in society", "the need to withdraw from worldly society entirely", "the superiority of Jewish believers over Gentiles", "a call to physical relocation to Jerusalem"], "the believer's positive, preserving, and illuminating influence in society",
      "Matthew 5:13-16 uses salt and light as metaphors for the believer's beneficial, visible impact on the surrounding world through godly living."),
  _q("In the parable of the Good Samaritan, Jesus' central teaching was that",
      ["true neighbourly love crosses social, ethnic, and religious boundaries", "priests and Levites are always the most compassionate people", "Samaritans were forbidden from helping Jews", "the injured man should have travelled with an armed escort"], "true neighbourly love crosses social, ethnic, and religious boundaries",
      "By making a despised Samaritan the hero who showed mercy, unlike the priest and Levite who passed by, Jesus redefined 'neighbour' to include anyone in need, regardless of ethnicity."),
  _q("The parable of the Prodigal Son primarily illustrates",
      ["God's readiness to forgive and joyfully welcome back the repentant sinner", "the importance of managing inherited wealth wisely", "the superiority of the elder son's obedience over the younger's rebellion", "the consequences of famine on agricultural societies"], "God's readiness to forgive and joyfully welcome back the repentant sinner",
      "Luke 15 depicts the father running to embrace his returning son and celebrating his return, portraying God's compassionate forgiveness toward repentant sinners."),
  _q("In the parable of the Sower, the seed that fell among thorns and was choked represents",
      ["those whose faith is stifled by the cares, riches, and pleasures of life", "those who never hear the word of God at all", "those who immediately reject the word with hostility", "those whose faith grows into a fruitful harvest"], "those whose faith is stifled by the cares, riches, and pleasures of life",
      "Luke 8:14 explains that the thorny ground represents hearers who are 'choked with cares and riches and pleasures of this life', bringing no fruit to maturity."),
  _q("Jesus' teaching in the parable of the Talents primarily emphasises",
      ["faithful and productive use of the gifts and resources God entrusts to us", "the importance of hoarding wealth for personal security", "equal distribution of resources regardless of ability", "the condemnation of all forms of trade and investment"], "faithful and productive use of the gifts and resources God entrusts to us",
      "Matthew 25:14-30 commends the servants who invested and multiplied their master's talents, while condemning the servant who buried his out of fear, teaching responsible stewardship."),
  _q("When Jesus taught His disciples the Lord's Prayer, the petition 'forgive us our debts, as we forgive our debtors' primarily teaches that",
      ["receiving God's forgiveness is linked to a willingness to forgive others", "debts should never be repaid among believers", "prayer should focus mainly on financial requests", "forgiveness is granted only after a formal confession ritual"], "receiving God's forgiveness is linked to a willingness to forgive others",
      "Matthew 6:14-15 reinforces this petition by warning that if we do not forgive others, our heavenly Father will not forgive our trespasses."),
  _q("Jesus' teaching 'You cannot serve God and mammon' (Matthew 6:24) warns primarily against",
      ["divided devotion, where love of wealth competes with wholehearted service to God", "the possession of any material wealth whatsoever", "working in commerce or trade", "paying taxes to earthly authorities"], "divided devotion, where love of wealth competes with wholehearted service to God",
      "Jesus taught that no one can wholly serve two masters, using 'mammon' (wealth) as an example of a rival claim on ultimate loyalty that competes with devotion to God."),
  _q("In His teaching on the greatest commandment, Jesus summarised the Law and the Prophets as",
      ["loving God with all one's heart, soul, and mind, and loving one's neighbour as oneself", "strict observance of the Sabbath above all else", "offering the correct sacrifices at the Temple", "obedience to the ten plagues narrative"], "loving God with all one's heart, soul, and mind, and loving one's neighbour as oneself",
      "Matthew 22:37-40 records Jesus identifying love for God and love for neighbour as the two commandments on which 'hang all the law and the prophets.'"),
  _q("Jesus' teaching on the new commandment in John 13:34, 'that ye love one another; as I have loved you', established love as",
      ["the distinguishing mark by which His disciples would be recognised", "a replacement for faith as the basis of salvation", "an obligation limited only to fellow disciples of the same background", "a temporary command relevant only until His crucifixion"], "the distinguishing mark by which His disciples would be recognised",
      "Jesus stated that 'by this shall all men know that ye are my disciples, if ye have love one to another', making sacrificial love the defining mark of His followers."),
];

final _earlyChurch = [
  _q("The events of Pentecost recorded in Acts 2 are chiefly significant because they mark",
      ["the coming of the Holy Spirit and the empowered birth of the Christian Church", "the first celebration of the Lord's Supper", "the appointment of the twelve apostles", "the conversion of the apostle Paul"], "the coming of the Holy Spirit and the empowered birth of the Christian Church",
      "Acts 2 describes the Holy Spirit's dramatic descent upon the disciples, enabling them to speak in other tongues and empowering Peter's bold sermon, traditionally seen as the Church's founding moment."),
  _q("Peter's sermon on the day of Pentecost primarily called his hearers to",
      ["repent and be baptised in the name of Jesus Christ for the remission of sins", "rebuild the Jerusalem Temple immediately", "return to strict observance of the Mosaic sacrificial system", "reject the authority of the Roman government openly"], "repent and be baptised in the name of Jesus Christ for the remission of sins",
      "Acts 2:38 records Peter's response to the convicted crowd: 'Repent, and be baptized every one of you in the name of Jesus Christ for the remission of sins.'"),
  _q("The early believers' practice described in Acts 2:44-45, of having 'all things common', primarily reflects",
      ["a voluntary, generous sharing of resources to meet the needs of the community", "a legally mandated abolition of all private property", "a temple requirement imposed by Jewish law", "a practice limited only to the twelve apostles"], "a voluntary, generous sharing of resources to meet the needs of the community",
      "The early church's communal sharing arose from voluntary generosity and fellowship, ensuring that no believer among them lacked necessities."),
  _q("The appointment of seven men, including Stephen, to oversee the daily distribution of food (Acts 6) primarily arose from",
      ["a complaint that Grecian widows were being neglected in the daily distribution", "a dispute over doctrine between Peter and Paul", "a shortage of funds within the church treasury", "opposition from the Sanhedrin to the apostles' preaching"], "a complaint that Grecian widows were being neglected in the daily distribution",
      "Acts 6:1 records murmuring among the Grecian Jews that their widows were overlooked, prompting the apostles to appoint seven men to manage this ministry so they could focus on prayer and preaching."),
  _q("Stephen, the first Christian martyr, was stoned to death primarily because",
      ["his bold testimony before the Sanhedrin provoked their fury, accusing him of blasphemy", "he refused to distribute food to Grecian widows", "he led a rebellion against Roman taxation", "he attempted to rebuild the Temple without authorisation"], "his bold testimony before the Sanhedrin provoked their fury, accusing him of blasphemy",
      "Acts 7 records Stephen's defence before the Sanhedrin, ending in a vision of Jesus at God's right hand, which so enraged his accusers that they dragged him out and stoned him."),
  _q("Saul's dramatic encounter with the risen Christ on the road to Damascus resulted in",
      ["his conversion from a persecutor of Christians to a leading apostle of the faith", "his immediate execution by Roman soldiers", "his permanent blindness with no restoration", "his rejection by all the apostles thereafter"], "his conversion from a persecutor of Christians to a leading apostle of the faith",
      "Acts 9 records Saul's blinding encounter with the risen Jesus, followed by his healing through Ananias and his transformation into a zealous apostle, later known as Paul."),
  _q("Peter's vision of the sheet containing unclean animals, prior to his visit to Cornelius (Acts 10), primarily taught him that",
      ["the gospel was not to be restricted to Jews alone, but extended to the Gentiles", "dietary laws remained permanently binding on all believers", "Cornelius should be rejected as a Roman soldier", "the apostles should avoid contact with non-Jews entirely"], "the gospel was not to be restricted to Jews alone, but extended to the Gentiles",
      "Peter's vision, followed by his visit to the Gentile centurion Cornelius, taught him that 'God is no respecter of persons', opening the way for Gentile inclusion in the Church."),
  _q("The Council of Jerusalem (Acts 15) was convened primarily to resolve the dispute over",
      ["whether Gentile converts needed to be circumcised and keep the Law of Moses", "the proper date for celebrating Passover", "who should succeed the apostle James as leader", "whether Paul should be permitted to travel to Rome"], "whether Gentile converts needed to be circumcised and keep the Law of Moses",
      "Acts 15 records the church leaders debating whether Gentile believers must be circumcised, ultimately deciding that salvation is by grace and not requiring full observance of the Mosaic law."),
  _q("Paul and Barnabas's missionary partnership eventually ended in separation primarily due to",
      ["a sharp disagreement over whether to take John Mark on a second journey", "a doctrinal dispute about the resurrection", "Barnabas's refusal to preach to Gentiles", "Paul's imprisonment in Rome"], "a sharp disagreement over whether to take John Mark on a second journey",
      "Acts 15:36-39 records that Paul and Barnabas had 'sharp contention' over John Mark, who had earlier departed from them, leading the two missionaries to separate and travel with different companions."),
  _q("Paul's conversion and calling are frequently cited as demonstrating that",
      ["God's grace can transform even the most zealous opponent of the gospel into its chief messenger", "only those raised within Judaism could become effective apostles", "persecution of the church always leads to its destruction", "apostleship required direct appointment by the eleven original disciples"], "God's grace can transform even the most zealous opponent of the gospel into its chief messenger",
      "Paul himself often referred to his dramatic transformation from persecutor to apostle as evidence of the exceeding grace and mercy of God."),
];

final _christianVirtues = [
  _q("According to Paul's list in Galatians 5:22-23, the 'fruit of the Spirit' includes all of the following EXCEPT",
      ["pride", "love", "patience", "gentleness"], "pride",
      "Galatians 5:22-23 lists love, joy, peace, longsuffering, gentleness, goodness, faith, meekness, and temperance as the fruit of the Spirit; pride is explicitly contrary to this list."),
  _q("Paul's teaching on love in 1 Corinthians 13 emphasises that love is",
      ["patient and kind, and does not seek its own interest above others", "primarily a feeling rather than an active choice", "less important than spiritual gifts such as prophecy", "only required between believers, not toward outsiders"], "patient and kind, and does not seek its own interest above others",
      "1 Corinthians 13:4-7 describes love as patient, kind, not self-seeking, and enduring, presenting it as superior to even the most impressive spiritual gifts without it."),
  _q("James' teaching that 'faith without works is dead' (James 2:26) primarily emphasises that",
      ["genuine faith should be demonstrated through practical, loving action", "good works alone are sufficient for salvation without faith", "faith and works are entirely unrelated concepts", "only wealthy believers are capable of good works"], "genuine faith should be demonstrated through practical, loving action",
      "James argues that authentic faith naturally produces visible good works, using the example of caring for the poor to show that professed faith without action is incomplete."),
  _q("Paul's instruction in Romans 12:2 to be 'not conformed to this world, but...transformed by the renewing of your mind' calls believers to",
      ["cultivate godly character that distinguishes them from surrounding worldly values", "withdraw completely from participation in society", "reject all forms of education and learning", "follow every cultural trend uncritically"], "cultivate godly character that distinguishes them from surrounding worldly values",
      "Paul urges believers toward inward transformation that produces discernment of God's will, standing in contrast to simply mirroring the values of the surrounding culture."),
  _q("The virtue of honesty in Christian teaching is grounded partly in the ninth commandment, which prohibits",
      ["bearing false witness against one's neighbour", "coveting a neighbour's possessions", "working on the Sabbath day", "the making of graven images"], "bearing false witness against one's neighbour",
      "Exodus 20:16 forbids false testimony, forming a foundational basis for the Christian virtue of truthfulness in speech and dealings with others."),
  _q("Paul's teaching on Christian conduct in the workplace, as in Colossians 3:23, encourages believers to",
      ["work heartily, as unto the Lord, and not merely to please human masters", "seek only the highest-paying jobs available", "avoid secular employment altogether", "work diligently only when directly supervised"], "work heartily, as unto the Lord, and not merely to please human masters",
      "Colossians 3:23 instructs believers, 'whatsoever ye do, do it heartily, as to the Lord, and not unto men', promoting integrity and diligence regardless of oversight."),
  _q("The Christian virtue of humility, as modelled by Christ in Philippians 2:5-8, is chiefly illustrated by His",
      ["willingness to take on the form of a servant and submit to death on a cross", "miraculous healing of the sick", "public debates with the religious leaders", "rejection of all human relationships"], "willingness to take on the form of a servant and submit to death on a cross",
      "Philippians 2 presents Christ's self-emptying and obedience even to death on the cross as the supreme model of humility for believers to imitate."),
  _q("Christian teaching on forgiveness, drawing on Jesus' parable of the unmerciful servant (Matthew 18), emphasises that believers should",
      ["forgive others as generously as they themselves have been forgiven by God", "forgive only those who formally apologise in writing", "withhold forgiveness until full restitution is made", "forgive family members only, not strangers"], "forgive others as generously as they themselves have been forgiven by God",
      "The parable warns that a servant forgiven a great debt but who refuses to forgive a smaller debt owed to him faces severe judgement, teaching that God's forgiveness should inspire ours."),
  _q("The Christian virtue of contentment, as Paul describes in Philippians 4:11-13, is chiefly rooted in",
      ["learning to trust God's sufficiency in every circumstance, whether abundance or need", "achieving financial independence through hard work alone", "avoiding all forms of ambition or goal-setting", "relying solely on the generosity of fellow believers"], "learning to trust God's sufficiency in every circumstance, whether abundance or need",
      "Paul testifies that he has 'learned, in whatsoever state I am, therewith to be content', attributing his endurance in all circumstances to strength found in Christ."),
  _q("Christian social responsibility, as reflected in passages such as Micah 6:8 and James 1:27, is often summarised as requiring believers to",
      ["do justly, love mercy, and care for the vulnerable, such as orphans and widows", "focus exclusively on personal spiritual disciplines", "avoid involvement in matters of justice or poverty", "leave all charitable responsibility to government institutions"], "do justly, love mercy, and care for the vulnerable, such as orphans and widows",
      "Micah 6:8 calls believers 'to do justly, and to love mercy', while James 1:27 defines pure religion partly as visiting orphans and widows in their affliction, framing social care as integral to genuine faith."),
];
