import "../quiz_question.dart";

const _subject = "Principles of Accounts";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// University of Ibadan (UI) Post-UTME elective bank — Principles of
/// Accounts. 100 original, heavily calculation-based questions covering the
/// standard UTME syllabus: Introduction to Accounting, Accounting
/// Concepts/Conventions, the Accounting Equation & Double Entry, Books of
/// Prime Entry, Trial Balance & Correction of Errors, Final Accounts of a
/// Sole Trader, Bank Reconciliation, Non-Profit Accounts, Partnership
/// Accounts, Company Accounts, Manufacturing Accounts, and Incomplete
/// Records.
List<QuizQuestion> buildUiAccountsQuestions() {
  return [
    ..._introductionToAccounting,
    ..._accountingConcepts,
    ..._accountingEquationDoubleEntry,
    ..._booksOfPrimeEntry,
    ..._trialBalanceCorrectionOfErrors,
    ..._finalAccountsSoleTrader,
    ..._bankReconciliation,
    ..._nonProfitAccounts,
    ..._partnershipAccounts,
    ..._companyAccounts,
    ..._manufacturingAccounts,
    ..._incompleteRecords,
  ];
}

final _introductionToAccounting = [
  _q("The branch of accounting concerned mainly with providing cost information for internal decision-making is",
      ["Cost accounting", "Financial accounting", "Public sector accounting", "Auditing"], "Cost accounting",
      "Cost accounting focuses on capturing and analysing costs of production to help management plan, control and make decisions."),
  _q("Which of these is NOT one of the traditional objectives of accounting?",
      ["Fixing the market price of a company's shares directly", "Ascertaining profit or loss", "Ascertaining the financial position of a business", "Providing information for decision-making"], "Fixing the market price of a company's shares directly",
      "Accounting supplies information that markets may use to value shares, but it does not itself fix share prices; that is left to the capital market."),
  _q("An auditor's main responsibility is to",
      ["Express an independent opinion on whether financial statements give a true and fair view", "Prepare the day-to-day ledger entries of a business", "Fix the salaries of company staff", "Sell the company's shares to the public"], "Express an independent opinion on whether financial statements give a true and fair view",
      "External auditors examine a company's financial statements and supporting records to give an independent, professional opinion on their fairness and accuracy."),
  _q("Which of the following best describes a 'transaction' in accounting?",
      ["An event that can be measured in monetary terms and affects the financial position of a business", "Any conversation between a buyer and a seller", "Only cash payments made by a business", "A decision taken by company management"], "An event that can be measured in monetary terms and affects the financial position of a business",
      "For an event to be recorded in accounting, it must be measurable in money and must change the assets, liabilities or capital of the business."),
  _q("Which of the following is an example of a tangible fixed asset?",
      ["Delivery van", "Goodwill", "Trademark", "Patent right"], "Delivery van",
      "A delivery van has physical substance and is used long-term in the business, making it a tangible fixed asset, unlike goodwill, trademarks and patents, which are intangible."),
  _q("A liquidity ratio that measures a business's ability to meet its short-term obligations using only cash, bank and marketable securities (excluding stock) is the",
      ["Acid test (quick) ratio", "Gross profit margin", "Return on capital employed", "Debtor collection period"], "Acid test (quick) ratio",
      "The acid test ratio deliberately excludes stock, the least liquid current asset, to give a stricter measure of a business's immediate ability to pay short-term debts than the current ratio."),
  _q("The main difference between a capital expenditure and a revenue expenditure is that capital expenditure",
      ["Provides benefit to the business over more than one accounting period", "Is always paid in cash immediately", "Is charged fully to the Trading Account", "Reduces the value of stock directly"], "Provides benefit to the business over more than one accounting period",
      "Capital expenditure buys or improves a long-term asset whose benefit extends beyond the current period, whereas revenue expenditure is consumed within the period it is incurred."),
];

final _accountingConcepts = [
  _q("Recording a proprietor's private house purchase in the business books would violate the",
      ["Business entity concept", "Going concern concept", "Money measurement concept", "Realisation concept"], "Business entity concept",
      "The business entity concept requires that only transactions of the business, not the personal transactions of the owner, be recorded in the business's books."),
  _q("Stating that only items expressible in monetary terms are recorded in the accounts reflects the",
      ["Money measurement concept", "Matching concept", "Dual aspect concept", "Prudence concept"], "Money measurement concept",
      "The money measurement concept limits accounting records to facts that can be expressed in monetary terms, excluding qualitative factors like staff morale."),
  _q("The matching (accruals) concept requires that",
      ["Expenses be matched against the revenue they helped to generate in the same period", "All expenses be recorded only when cash is paid", "Revenue be recorded only after all related expenses are settled in cash", "Assets be revalued to market price every year"], "Expenses be matched against the revenue they helped to generate in the same period",
      "The matching concept ensures that costs incurred in earning a period's revenue are charged against that same period's revenue, regardless of when cash changes hands."),
  _q("Under the realisation concept, revenue from a credit sale is recognised",
      ["When goods are transferred to the buyer and a legal obligation to pay arises, not when cash is eventually received", "Only when the cash is actually received from the customer", "When the goods are physically manufactured", "When the customer places the order, before delivery"], "When goods are transferred to the buyer and a legal obligation to pay arises, not when cash is eventually received",
      "Revenue is realised (recognised) once ownership passes and the buyer becomes legally obliged to pay, which for a credit sale is at the point of delivery, not at cash collection."),
  _q("Charging the full cost of a N5,000 stapler as an expense immediately, rather than depreciating it over several years, best illustrates the",
      ["Materiality concept", "Consistency concept", "Going concern concept", "Historical cost concept"], "Materiality concept",
      "Because the amount involved is too small to influence any user's decision, materiality justifies treating it as a straightforward expense rather than a depreciable asset."),
  _q("Valuing closing stock at the lower of cost and net realisable value is a direct application of the",
      ["Prudence concept", "Consistency concept", "Going concern concept", "Business entity concept"], "Prudence concept",
      "Prudence requires that assets like stock are not overstated, so stock is valued at whichever is lower between its cost and what it can actually be sold for."),
  _q("A trader values her closing stock at the lower of cost (N90,000) and net realisable value (N78,000). The value to be used in the accounts is",
      ["N78,000", "N90,000", "N84,000", "N168,000"], "N78,000",
      "The prudence concept requires stock to be valued at the lower of cost and net realisable value, so the N78,000 net realisable value is used since it is lower than the N90,000 cost."),
];

final _accountingEquationDoubleEntry = [
  _q("A business has capital of N450,000 and liabilities of N180,000. Total assets must be",
      ["N630,000", "N270,000", "N450,000", "N180,000"], "N630,000",
      "Assets = Capital + Liabilities = 450,000 + 180,000 = N630,000."),
  _q("At the start of the year a trader's assets were N900,000 and liabilities N250,000. Capital at the start of the year was",
      ["N650,000", "N1,150,000", "N250,000", "N900,000"], "N650,000",
      "Capital = Assets - Liabilities = 900,000 - 250,000 = N650,000."),
  _q("A trader's liabilities are N120,000, which is 30% of total assets. Total assets are",
      ["N400,000", "N360,000", "N156,000", "N40,000"], "N400,000",
      "If N120,000 is 30% of total assets, total assets = 120,000 / 0.30 = N400,000."),
  _q("If total assets are N700,000 and capital is N520,000, total liabilities are",
      ["N180,000", "N1,220,000", "N520,000", "N700,000"], "N180,000",
      "Liabilities = Assets - Capital = 700,000 - 520,000 = N180,000."),
  _q("When a business pays a creditor in cash, the correct double entry is to",
      ["Debit the creditor's account and credit the cash account", "Debit the cash account and credit the creditor's account", "Debit both the creditor's and cash accounts", "Credit both the creditor's and cash accounts"], "Debit the creditor's account and credit the cash account",
      "Paying a creditor reduces the liability, so the creditor's account is debited, while cash falls, so the cash account is credited."),
  _q("When the owner introduces additional cash into the business, the correct double entry is to",
      ["Debit the cash account and credit the capital account", "Debit the capital account and credit the cash account", "Debit both the cash and capital accounts", "Credit both the cash and capital accounts"], "Debit the cash account and credit the capital account",
      "Cash held by the business increases (debit), while the owner's claim on the business (capital) also increases, requiring a credit entry."),
  _q("A decrease in an asset account is normally recorded as a",
      ["Credit", "Debit", "Neither debit nor credit", "Both debit and credit at once"], "Credit",
      "Since assets increase on the debit side, they must decrease on the credit side under double-entry rules."),
  _q("Drawings taken by the owner in cash are recorded by",
      ["Debiting the drawings account and crediting the cash account", "Debiting the cash account and crediting the drawings account", "Debiting the capital account directly and crediting cash", "Crediting the drawings account and debiting the sales account"], "Debiting the drawings account and crediting the cash account",
      "Drawings represent cash taken out for personal use, increasing the drawings account (debit) while reducing cash (credit)."),
  _q("A business bought office furniture worth N60,000 on credit from ABC Furniture Ltd. The correct double entry is to",
      ["Debit furniture account and credit ABC Furniture Ltd account", "Debit ABC Furniture Ltd account and credit furniture account", "Debit cash account and credit furniture account", "Debit furniture account and credit cash account"], "Debit furniture account and credit ABC Furniture Ltd account",
      "The furniture asset increases (debit), and since it was bought on credit, a liability to the supplier is created (credit) rather than cash being affected."),
  _q("Which of the following correctly states the rule for expense and revenue accounts?",
      ["Expenses are debited when incurred; revenues are credited when earned", "Expenses are credited when incurred; revenues are debited when earned", "Both expenses and revenues are always debited", "Both expenses and revenues are always credited"], "Expenses are debited when incurred; revenues are credited when earned",
      "Expenses reduce profit and are recorded as debits, while revenues increase profit and are recorded as credits, in line with double-entry conventions."),
];

final _booksOfPrimeEntry = [
  _q("An invoice received from a supplier for goods bought on credit is first entered in the",
      ["Purchases Journal", "Sales Journal", "General Journal", "Petty Cash Book"], "Purchases Journal",
      "Invoices for credit purchases are recorded chronologically in the Purchases Journal before being posted to the individual supplier and purchases accounts."),
  _q("A credit note issued by a business to a customer who returned faulty goods is recorded in the",
      ["Returns Inwards Journal", "Returns Outwards Journal", "Sales Journal", "Purchases Journal"], "Returns Inwards Journal",
      "A credit note to a customer for returned goods reduces what the customer owes and is recorded in the Returns Inwards (Sales Returns) Journal."),
  _q("The entry to record the purchase of a delivery van on credit would normally be made in the",
      ["General Journal", "Purchases Journal", "Sales Journal", "Cash Book"], "General Journal",
      "Since the Purchases Journal is reserved for credit purchases of trading goods, the credit purchase of a fixed asset like a van is instead recorded via the General Journal."),
  _q("In a three-column cash book, discount allowed appears on the",
      ["Debit side, as a memorandum column alongside cash and bank receipts", "Credit side, alongside cash and bank payments", "Both the debit and credit sides equally", "Neither side, since it is posted only to the ledger"], "Debit side, as a memorandum column alongside cash and bank receipts",
      "Discount allowed to customers who pay early is entered in the discount column on the debit (receipts) side of the three-column cash book, alongside cash and bank receipts."),
  _q("A contra entry in a two-column (cash and bank) cash book arises when",
      ["Cash is withdrawn from the bank for office use, or cash is paid into the bank", "Goods are purchased on credit", "A customer returns goods for a refund", "A bad debt is written off"], "Cash is withdrawn from the bank for office use, or cash is paid into the bank",
      "A contra entry records a transaction that affects both the cash and bank columns of the same cash book, such as transferring money between cash in hand and the bank."),
  _q("The balance carried down on the debit side of a cash book represents",
      ["Cash or bank funds still held by the business at that date", "Total sales made during the period", "Amount owed to suppliers", "Amount owed by debtors"], "Cash or bank funds still held by the business at that date",
      "A debit balance carried down in the cash book shows the actual cash or bank balance remaining in the business's hands at the end of the period."),
  _q("Which book of prime entry would record the correction of an error discovered after the trial balance has been drawn up?",
      ["The General Journal", "The Sales Journal", "The Purchases Journal", "The Cash Book"], "The General Journal",
      "Correcting entries for errors are non-routine and are therefore recorded through the General Journal before being posted to the relevant ledger accounts."),
  _q("A trader who keeps a cash book will normally NOT need a separate",
      ["Cash account and bank account in the main ledger", "Sales journal for credit sales", "Purchases journal for credit purchases", "Debtors ledger"], "Cash account and bank account in the main ledger",
      "Because the cash book itself serves as both the book of prime entry and the ledger account for cash and bank, no separate cash or bank ledger account is required."),
];

final _trialBalanceCorrectionOfErrors = [
  _q("Goods bought for N15,000 were correctly entered in the Purchases account but wrongly posted as N15,000 to the credit side of the supplier's account instead of N15,000 credit as required, with the debit posted correctly. This is best described as",
      ["An error of complete reversal of entries", "An error of omission", "An error of principle", "A compensating error"], "An error of complete reversal of entries",
      "Both accounts used the correct amount, but the debit and credit sides were swapped between the two accounts, which is the defining feature of a complete reversal of entries."),
  _q("A trial balance shows total debits of N348,500 and total credits of N346,900. The difference of N1,600 should be",
      ["Placed on the credit side of a suspense account", "Placed on the debit side of a suspense account", "Ignored, since it is not material", "Added to the closing stock figure"], "Placed on the credit side of a suspense account",
      "Since debits exceed credits by N1,600, a credit balance of N1,600 is entered in the suspense account to make the trial balance balance."),
  _q("A cheque for N8,000 paid to a supplier was correctly entered in the cash book but was posted to the supplier's account as N800. On correction, the suspense account entry needed is",
      ["A debit of N7,200 to remove the difference caused by the understatement", "A credit of N7,200", "A debit of N8,800", "A credit of N800"], "A debit of N7,200 to remove the difference caused by the understatement",
      "The supplier's account was under-debited by 8,000 - 800 = N7,200; correcting this requires a further debit of N7,200 to the supplier's account, with the suspense account credited (7,200) being cleared by a matching debit as the correcting journal balances the suspense account back to zero, i.e. a N7,200 debit adjustment closes the discrepancy."),
  _q("Which of the following errors would cause the trial balance to disagree?",
      ["A sale of N4,000 posted correctly to the Sales account but omitted entirely from the debtor's account", "Recording a purchase of stationery as 'Purchases' instead of 'Stationery expense'", "Recording a transaction twice in both the correct debit and credit accounts", "Recording the correct figure but in the wrong customer's account"], "A sale of N4,000 posted correctly to the Sales account but omitted entirely from the debtor's account",
      "Since only one side of this transaction was posted, the trial balance totals would no longer be equal, unlike the other options, which are all two-sided errors that keep the trial balance balanced."),
  _q("Which statement about a trial balance is TRUE?",
      ["A trial balance that balances does not guarantee that the books are free of all errors", "A trial balance that balances proves that no errors exist anywhere in the ledger", "A trial balance is the same document as a Balance Sheet", "A trial balance always includes only asset and liability accounts"], "A trial balance that balances does not guarantee that the books are free of all errors",
      "Even when a trial balance balances, errors such as omission, commission, principle, original entry, complete reversal, or compensating errors may still be present undetected."),
  _q("Stationery purchased for N6,000 was debited to the Furniture account in error. This is an example of",
      ["An error of principle", "An error of commission", "An error of omission", "A compensating error"], "An error of principle",
      "Charging a revenue expense (stationery) to a fixed asset account breaches a fundamental accounting classification rule, making this an error of principle."),
  _q("Wages of N25,000 were correctly recorded in the cash book but posted to the Wages account as N2,500. If this is the only error, the suspense account should show a difference of",
      ["N22,500", "N25,000", "N2,500", "N27,500"], "N22,500",
      "The Wages account was understated by 25,000 - 2,500 = N22,500, so this amount must be posted as an additional entry to correct the account, matched against the suspense account."),
  _q("A machine bought for N200,000 was debited to the Purchases account instead of the Machinery account. Correcting this error will",
      ["Increase fixed assets and reduce purchases, but not affect the trial balance totals", "Cause the trial balance to disagree", "Have no effect on any financial statement", "Only affect the Balance Sheet, not the Profit and Loss Account"], "Increase fixed assets and reduce purchases, but not affect the trial balance totals",
      "Because both the original wrong entry and the correction involve a debit of equal amount, the trial balance itself stays balanced, but gross profit, net profit and fixed assets are all corrected by the reclassification."),
  _q("A trader's trial balance failed to balance, with total debits exceeding total credits by N3,400. Investigation showed that the sales account had been undercast (added up short) by N3,400. The correcting journal entry required is",
      ["Debit suspense account and credit sales account with N3,400", "Debit sales account and credit suspense account with N3,400", "Debit sales account and credit cash account with N3,400", "No correcting entry is required"], "Debit suspense account and credit sales account with N3,400",
      "An undercast (understated) sales account needs its credit balance increased by N3,400; the corresponding debit clears the suspense account that was opened to match the original trial balance shortfall."),
  _q("Which pair of errors, if both present together, would be classified as compensating errors?",
      ["The Sales account overcast by N2,000 and the Purchases account also overcast by N2,000", "A transaction posted to the wrong customer's account", "A transaction completely omitted from the books", "A capital expenditure treated as a revenue expense"], "The Sales account overcast by N2,000 and the Purchases account also overcast by N2,000",
      "Since an overcast (an excess credit) in Sales and an overcast (an excess debit) in Purchases are of equal and opposite value, they cancel out, letting the trial balance still balance despite both mistakes."),
];

final _finalAccountsSoleTrader = [
  _q("A trader has opening stock N30,000, purchases N150,000, purchases returns N5,000, carriage inwards N4,000, and closing stock N25,000. Cost of goods sold is",
      ["N154,000", "N159,000", "N150,000", "N164,000"], "N154,000",
      "Cost of Goods Sold = Opening stock + Purchases - Purchases returns + Carriage inwards - Closing stock = 30,000 + 150,000 - 5,000 + 4,000 - 25,000 = N154,000."),
  _q("Using the previous scenario, if sales for the period were N220,000, gross profit is",
      ["N66,000", "N70,000", "N60,000", "N76,000"], "N66,000",
      "Gross Profit = Sales - Cost of Goods Sold = 220,000 - 154,000 = N66,000."),
  _q("A business had sales of N400,000, sales returns of N20,000, and cost of goods sold of N300,000. Gross profit is",
      ["N80,000", "N100,000", "N120,000", "N60,000"], "N80,000",
      "Net sales = 400,000 - 20,000 = 380,000; Gross Profit = 380,000 - 300,000 = N80,000."),
  _q("A trader's gross profit is N90,000. Expenses for the period were: rent N15,000, salaries N28,000, and depreciation N7,000. Net profit is",
      ["N40,000", "N50,000", "N130,000", "N60,000"], "N40,000",
      "Total expenses = 15,000 + 28,000 + 7,000 = 50,000; Net Profit = 90,000 - 50,000 = N40,000."),
  _q("Rent paid during the year was N48,000, of which N8,000 relates to the following year. The amount to be charged as rent expense in the Profit and Loss Account for the current year is",
      ["N40,000", "N48,000", "N56,000", "N8,000"], "N40,000",
      "Since N8,000 was paid in advance for the next period, it is excluded from this year's expense: 48,000 - 8,000 = N40,000, with the N8,000 shown as a prepayment (current asset)."),
  _q("Salaries paid during the year were N120,000, and N15,000 was still owing at year end. The salaries expense to be charged in the Profit and Loss Account is",
      ["N135,000", "N120,000", "N105,000", "N15,000"], "N135,000",
      "Salaries incurred for the year = Amount paid + Amount still owing = 120,000 + 15,000 = N135,000, with the N15,000 also shown as a current liability (accrual)."),
  _q("A machine costing N240,000 has an estimated residual value of N40,000 and a useful life of 8 years. Its annual straight-line depreciation charge is",
      ["N25,000", "N30,000", "N20,000", "N35,000"], "N25,000",
      "Annual depreciation = (Cost - Residual value) / Useful life = (240,000 - 40,000) / 8 = 200,000 / 8 = N25,000."),
  _q("A vehicle costing N600,000 is depreciated at 20% per annum using the reducing balance method. Depreciation for the second year is",
      ["N96,000", "N120,000", "N480,000", "N24,000"], "N96,000",
      "Year 1 depreciation = 20% x 600,000 = 120,000, giving a net book value of 480,000; Year 2 depreciation = 20% x 480,000 = N96,000."),
  _q("A debtor's balance of N12,000 is considered irrecoverable and is written off. The correct entry is to",
      ["Debit Bad Debts account and credit the debtor's account", "Debit the debtor's account and credit Bad Debts account", "Debit Cash account and credit the debtor's account", "Debit Sales account and credit the debtor's account"], "Debit Bad Debts account and credit the debtor's account",
      "Writing off a bad debt records the loss as an expense (debit Bad Debts) and removes the amount from the debtor's account (credit), since it is no longer expected to be recovered."),
  _q("Total debtors at the year end are N250,000. A provision for doubtful debts of 4% is to be maintained. The amount of the provision is",
      ["N10,000", "N25,000", "N4,000", "N1,000"], "N10,000",
      "Provision for doubtful debts = 4% x 250,000 = N10,000."),
  _q("A business had an opening provision for doubtful debts of N6,000. Debtors at year end are N220,000, and a 5% provision is required. The change to be charged (or credited) to the Profit and Loss Account is",
      ["An additional charge of N5,000", "An additional charge of N11,000", "A credit (reduction) of N1,000", "An additional charge of N6,000"], "An additional charge of N5,000",
      "New provision required = 5% x 220,000 = 11,000; Increase needed = 11,000 - 6,000 (opening provision) = N5,000, charged as an additional expense."),
  _q("Which of the following would appear on the credit side of a Trading Account?",
      ["Sales and closing stock", "Purchases and carriage inwards", "Opening stock and purchases returns", "Carriage outwards and rent"], "Sales and closing stock",
      "The Trading Account credits sales revenue and closing stock (which reduces cost of goods sold), while purchases, opening stock and carriage inwards appear on the debit side."),
  _q("Carriage outwards is treated in the final accounts as",
      ["An expense in the Profit and Loss Account", "Part of the cost of goods sold in the Trading Account", "A deduction from sales", "A current asset in the Balance Sheet"], "An expense in the Profit and Loss Account",
      "Carriage outwards relates to delivering goods to customers after sale, a selling expense, and so is charged in the Profit and Loss Account rather than the Trading Account."),
  _q("In the Balance Sheet, a bank overdraft is normally classified as a",
      ["Current liability", "Current asset", "Fixed asset", "Long-term liability"], "Current liability",
      "A bank overdraft is money owed to the bank repayable on demand, making it a current liability rather than an asset."),
  _q("Which of the following is a current asset?",
      ["Stock of unsold goods", "Delivery van", "Goodwill", "Long-term bank loan"], "Stock of unsold goods",
      "Stock is expected to be sold and converted to cash within the normal trading cycle, making it a current asset, unlike the van (fixed asset), goodwill (intangible fixed asset) or loan (long-term liability)."),
  _q("Net working capital (net current assets) is calculated as",
      ["Current assets minus current liabilities", "Current assets plus current liabilities", "Fixed assets minus current liabilities", "Total assets minus total liabilities"], "Current assets minus current liabilities",
      "Working capital measures a business's short-term liquidity by comparing current assets against current liabilities."),
  _q("A business has current assets of N180,000 and current liabilities of N120,000. Its working capital is",
      ["N60,000", "N300,000", "N120,000", "N180,000"], "N60,000",
      "Working Capital = Current Assets - Current Liabilities = 180,000 - 120,000 = N60,000."),
];

final _bankReconciliation = [
  _q("A trader's cash book shows a debit balance of N45,000. Unpresented cheques total N12,000 and uncredited lodgements total N7,000. The balance as per the bank statement should be",
      ["N50,000", "N40,000", "N64,000", "N26,000"], "N50,000",
      "Bank statement balance = Cash book balance + Unpresented cheques - Uncredited lodgements = 45,000 + 12,000 - 7,000 = N50,000."),
  _q("A cash book shows a balance of N60,000. The bank statement shows a balance of N72,500, after allowing for unpresented cheques of N18,000 and uncredited lodgements of N9,500. Bank charges of N4,000 shown on the statement have not yet been entered in the cash book. The corrected cash book balance is",
      ["N56,000", "N64,000", "N60,000", "N54,000"], "N56,000",
      "Corrected cash book balance = 60,000 - 4,000 (bank charges not yet recorded) = N56,000."),
  _q("Which item found on a bank statement but not yet in the cash book would require the cash book balance to be increased?",
      ["Standing order income (interest earned) credited directly by the bank", "Bank charges deducted by the bank", "An unpresented cheque", "A dishonoured cheque"], "Standing order income (interest earned) credited directly by the bank",
      "Interest earned and credited directly to the account by the bank increases the true cash balance, so the cash book must be adjusted upward (debited) to match."),
  _q("A cheque of N9,000 received from a customer and banked was later dishonoured. In the cash book, this requires",
      ["A credit entry of N9,000 to reverse the earlier receipt", "A debit entry of N9,000", "No entry, since it was already recorded", "A credit entry of N18,000"], "A credit entry of N9,000 to reverse the earlier receipt",
      "A dishonoured cheque means the expected cash was never actually received, so the earlier debit entry recording its receipt must be reversed with a credit entry."),
  _q("A cash book showed a debit balance of N33,000 before adjustments. On comparison with the bank statement, a standing order payment of N5,000 and bank charges of N1,200 had not been entered in the cash book, while a direct credit transfer of N6,200 from a customer had also not been entered. The corrected cash book balance is",
      ["N33,000", "N38,000", "N27,800", "N45,400"], "N33,000",
      "Corrected balance = 33,000 - 5,000 - 1,200 + 6,200 = N33,000."),
  _q("Which of the following would NOT typically appear as a reconciling item in a bank reconciliation statement?",
      ["A cash sale recorded correctly in both the till and the cash book", "An unpresented cheque", "An uncredited lodgement", "Bank charges not yet recorded in the cash book"], "A cash sale recorded correctly in both the till and the cash book",
      "A correctly and identically recorded cash sale causes no discrepancy between the cash book and bank statement, so it is not a reconciling item."),
];

final _nonProfitAccounts = [
  _q("A club's Receipts and Payments Account showed subscriptions received of N180,000 during the year. Subscriptions owing at the start of the year were N15,000 and at the end were N22,000. Subscription income to be shown in the Income and Expenditure Account is",
      ["N187,000", "N173,000", "N195,000", "N165,000"], "N187,000",
      "Subscription income = Cash received + Closing arrears - Opening arrears = 180,000 + 22,000 - 15,000 = N187,000."),
  _q("A sports club had an opening Accumulated Fund of N320,000 and a closing Accumulated Fund of N410,000, after the year's surplus and a legacy of N30,000 credited directly to the fund. The surplus for the year, per the Income and Expenditure Account, was",
      ["N60,000", "N90,000", "N120,000", "N30,000"], "N60,000",
      "Change in Accumulated Fund = 410,000 - 320,000 = 90,000, of which 30,000 relates to the legacy credited directly, leaving a surplus of 90,000 - 30,000 = N60,000."),
  _q("A club's Receipts and Payments Account showed total receipts of N250,000 and total payments of N210,000 for the year. This means the club's",
      ["Cash and bank balance increased by N40,000 during the year", "Surplus for the year was exactly N40,000", "Accumulated Fund increased by exactly N40,000", "Net assets fell by N40,000"], "Cash and bank balance increased by N40,000 during the year",
      "The Receipts and Payments Account is a pure cash summary, so it only shows that cash/bank funds rose by 250,000 - 210,000 = N40,000; it does not by itself measure surplus, which requires accrual adjustments."),
  _q("A club bought sports equipment for N80,000 during the year, to be depreciated at 10% per annum. The depreciation charge for the year in the Income and Expenditure Account is",
      ["N8,000", "N80,000", "N72,000", "N800"], "N8,000",
      "Annual depreciation = 10% x 80,000 = N8,000, charged as an expense against the club's income for the year."),
  _q("The difference between the value of a club's bar sales and the cost of bar purchases consumed is shown in the Income and Expenditure Account as",
      ["A profit (or loss) on bar trading, similar to gross profit on a Trading Account", "Total subscription income", "An addition to the Accumulated Fund with no further explanation", "A current liability"], "A profit (or loss) on bar trading, similar to gross profit on a Trading Account",
      "Bar trading activities are effectively a small trading operation within the club, so a mini Trading Account is prepared, and the resulting profit or loss is transferred into the Income and Expenditure Account."),
  _q("Donations received by a non-profit organisation for a specific purpose, such as building a new hall, should be",
      ["Kept separate as a special fund until the purpose is fulfilled", "Treated as ordinary subscription income for the year", "Credited to the Income and Expenditure Account immediately as general income", "Ignored until the hall project is complete"], "Kept separate as a special fund until the purpose is fulfilled",
      "Restricted donations for a specific purpose are not general income and should be accounted for separately as a special fund until used for that stated purpose."),
];

final _partnershipAccounts = [
  _q("Partners Ade and Bola share profits equally. Net profit for the year was N400,000, after interest on capital of N30,000 to Ade and N20,000 to Bola had already been allowed. Ade's total share of profit (interest plus profit share) is",
      ["N205,000", "N200,000", "N230,000", "N175,000"], "N205,000",
      "Remaining profit after interest = 400,000 - 30,000 - 20,000 = 350,000, shared equally = 175,000 each; Ade's total = 175,000 + 30,000 (his interest) = N205,000."),
  _q("Partners Chidi and Deji share profits in the ratio 3:2. Net profit for appropriation was N250,000. Chidi's share is",
      ["N150,000", "N125,000", "N100,000", "N50,000"], "N150,000",
      "Total ratio parts = 3 + 2 = 5; Chidi's share = 3/5 x 250,000 = N150,000."),
  _q("A partner has a fixed capital of N500,000. Interest on capital is allowed at 8% per annum. The interest on capital for the year is",
      ["N40,000", "N4,000", "N50,000", "N400,000"], "N40,000",
      "Interest on capital = 8% x 500,000 = N40,000."),
  _q("A partner's drawings during the year averaged N60,000 outstanding, and interest on drawings is charged at 10% per annum. The interest on drawings to be added back to appropriable profit is",
      ["N6,000", "N600", "N60,000", "N54,000"], "N6,000",
      "Interest on drawings = 10% x 60,000 = N6,000."),
  _q("Partners Femi and Grace share profits equally. Their capitals are N300,000 and N200,000 respectively, and interest on capital is 5% per annum. Net profit for appropriation, before interest, is N150,000. Grace's total share (interest plus profit share) is",
      ["N77,500", "N67,500", "N75,000", "N10,000"], "N77,500",
      "Interest: Femi = 15,000, Grace = 10,000, total = 25,000; Remaining profit = 150,000 - 25,000 = 125,000, shared equally = 62,500 each; Grace's total = 62,500 + 10,000 = N77,500."),
  _q("On admission of a new partner, goodwill is valued at N90,000 and is not to remain in the books. If the old partners shared profits equally and the new partner brings in no goodwill personally, the existing two old partners' capital accounts should each be credited with",
      ["N45,000", "N90,000", "N30,000", "N22,500"], "N45,000",
      "Goodwill of N90,000 is shared between the two existing partners in their old profit-sharing ratio (equally), so each is credited with 90,000 / 2 = N45,000."),
  _q("A partnership's Appropriation Account would NOT normally include",
      ["Rent paid for the partnership's business premises", "Interest on partners' capital", "Partners' salaries", "Share of residual profit distributed to each partner"], "Rent paid for the partnership's business premises",
      "Rent is an ordinary trading expense deducted in arriving at net profit, before the Appropriation Account distributes that profit among the partners; it is not an appropriation item itself."),
  _q("At retirement, a partner's capital account balance is N180,000, current account balance is N25,000, and she is entitled to a further N40,000 as her share of goodwill. The total amount due to her is",
      ["N245,000", "N220,000", "N205,000", "N40,000"], "N245,000",
      "Total due = Capital account + Current account + Share of goodwill = 180,000 + 25,000 + 40,000 = N245,000."),
];

final _companyAccounts = [
  _q("A company issued 100,000 ordinary shares of N1 each at a price of N1.20 each. The total share premium received is",
      ["N20,000", "N100,000", "N120,000", "N1.20"], "N20,000",
      "Share premium per share = 1.20 - 1.00 = N0.20; Total premium = 100,000 x 0.20 = N20,000."),
  _q("A company has 200,000 ordinary shares of N1 each in issue and declares a dividend of 15 kobo per share. Total dividend payable is",
      ["N30,000", "N15,000", "N200,000", "N3,000"], "N30,000",
      "Total dividend = 200,000 shares x N0.15 = N30,000."),
  _q("A company issued N500,000 of 8% debentures. The annual interest payable on these debentures is",
      ["N40,000", "N4,000", "N8,000", "N500,000"], "N40,000",
      "Annual debenture interest = 8% x 500,000 = N40,000."),
  _q("In a company's Balance Sheet, called-up share capital not yet paid by shareholders is shown as",
      ["Calls in arrears, deducted from called-up capital", "A current liability", "A fixed asset", "Part of the reserves"], "Calls in arrears, deducted from called-up capital",
      "Amounts called up on shares but not yet received from shareholders are shown as calls in arrears, reducing the called-up share capital figure in the Balance Sheet."),
  _q("The Authorised Share Capital of a company refers to",
      ["The maximum amount of share capital the company is legally permitted to issue", "The amount of share capital that has actually been issued to shareholders", "The amount of share capital that has actually been paid for by shareholders", "The total value of the company's reserves"], "The maximum amount of share capital the company is legally permitted to issue",
      "Authorised (nominal) capital is the ceiling set out in the company's constitution on how much share capital it may issue; issued capital, which may be lower, is what has actually been allotted."),
  _q("Retained earnings (revenue reserves) represent",
      ["Accumulated profits kept in the business rather than distributed as dividends", "Money borrowed from debenture holders", "The nominal value of shares issued", "A fixed asset owned by the company"], "Accumulated profits kept in the business rather than distributed as dividends",
      "Retained earnings build up over time from profits that the company chooses to reinvest rather than pay out to shareholders as dividends."),
];

final _manufacturingAccounts = [
  _q("A manufacturer had direct materials consumed of N180,000, direct labour of N120,000, and direct expenses of N15,000. Prime cost is",
      ["N315,000", "N300,000", "N195,000", "N135,000"], "N315,000",
      "Prime Cost = Direct materials + Direct labour + Direct expenses = 180,000 + 120,000 + 15,000 = N315,000."),
  _q("Using the previous scenario, if factory overheads were N45,000, the total production cost is",
      ["N360,000", "N315,000", "N165,000", "N405,000"], "N360,000",
      "Total Production Cost = Prime Cost + Factory Overheads = 315,000 + 45,000 = N360,000."),
  _q("A manufacturer had opening stock of raw materials N25,000, purchases of raw materials N160,000, and closing stock of raw materials N30,000. Cost of raw materials consumed is",
      ["N155,000", "N185,000", "N135,000", "N215,000"], "N155,000",
      "Raw materials consumed = Opening stock + Purchases - Closing stock = 25,000 + 160,000 - 30,000 = N155,000."),
  _q("A manufacturer's total production cost was N400,000, opening work-in-progress N20,000, and closing work-in-progress N35,000. The cost of production of finished goods (transferred to the Trading Account) is",
      ["N385,000", "N415,000", "N455,000", "N400,000"], "N385,000",
      "Cost of Finished Goods = Total Production Cost + Opening WIP - Closing WIP = 400,000 + 20,000 - 35,000 = N385,000."),
  _q("Which of the following would be classified as a direct expense in a Manufacturing Account?",
      ["Royalties paid per unit produced under a licensing agreement", "Factory rent", "Depreciation of factory machinery", "Salary of the factory supervisor"], "Royalties paid per unit produced under a licensing agreement",
      "Royalties charged specifically per unit of output can be traced directly to production, making them a direct expense, unlike factory rent, depreciation and supervisory salaries, which are indirect overheads."),
  _q("If the cost of finished goods produced (N385,000) is less than what it would have cost to buy the same goods externally (N420,000), the difference of N35,000 is generally treated as",
      ["Manufacturing profit, credited to a Manufacturing Account and shown in the Profit and Loss Account", "An immediate cash receipt", "A reduction in factory overheads", "Ignored completely in the final accounts"], "Manufacturing profit, credited to a Manufacturing Account and shown in the Profit and Loss Account",
      "Some manufacturers transfer finished goods to the Trading Account at market value, recognising the notional saving as manufacturing profit, disclosed separately in the final accounts."),
];

final _incompleteRecords = [
  _q("A trader had opening capital of N250,000. During the year he introduced additional capital of N40,000 and made drawings of N35,000. Closing capital was N310,000. Profit for the year was",
      ["N55,000", "N60,000", "N15,000", "N95,000"], "N55,000",
      "Profit = (Closing Capital + Drawings) - (Opening Capital + Additional Capital) = (310,000 + 35,000) - (250,000 + 40,000) = 345,000 - 290,000 = N55,000."),
  _q("A trader's opening statement of affairs showed net assets of N180,000, and the closing statement of affairs showed net assets of N150,000. There were no drawings and no additional capital introduced during the year. The result for the year was",
      ["A net loss of N30,000", "A net profit of N30,000", "A net profit of N150,000", "No profit or loss"], "A net loss of N30,000",
      "Since closing capital (150,000) is lower than opening capital (180,000) with no drawings or new capital to explain the fall, the business made a loss of 180,000 - 150,000 = N30,000."),
  _q("A trader wants to estimate credit sales for the year using her total debtors account. Opening debtors were N45,000, closing debtors N60,000, and cash received from debtors during the year was N320,000, with no discounts or bad debts. Credit sales for the year were",
      ["N335,000", "N305,000", "N425,000", "N275,000"], "N335,000",
      "Using the Total Debtors Account: Credit sales = Cash received from debtors + Closing debtors - Opening debtors = 320,000 + 60,000 - 45,000 = N335,000."),
  _q("A trader's opening creditors were N28,000, closing creditors N33,000, and cash paid to suppliers during the year was N210,000, with no discounts received. Credit purchases for the year were",
      ["N215,000", "N205,000", "N238,000", "N182,000"], "N215,000",
      "Using the Total Creditors Account: Credit purchases = Cash paid to suppliers + Closing creditors - Opening creditors = 210,000 + 33,000 - 28,000 = N215,000."),
  _q("A trader's mark-up on cost is 25%. If cost of goods sold for the year was N320,000, sales for the year were",
      ["N400,000", "N480,000", "N256,000", "N345,000"], "N400,000",
      "Since mark-up is on cost, gross profit = 25% x 320,000 = 80,000; Sales = Cost of Goods Sold + Gross Profit = 320,000 + 80,000 = N400,000."),
  _q("A trader's gross profit margin on sales is 30%. If sales for the year were N500,000, cost of goods sold was",
      ["N350,000", "N150,000", "N385,000", "N400,000"], "N350,000",
      "Margin means gross profit is a percentage of sales: Gross Profit = 30% x 500,000 = 150,000; Cost of Goods Sold = Sales - Gross Profit = 500,000 - 150,000 = N350,000."),
  _q("A fire destroyed a trader's stock. Records show opening stock N40,000, purchases to date of the fire N260,000, and sales to date of the fire N360,000, with a consistent gross profit margin of 25% on sales. The estimated value of stock destroyed is",
      ["N30,000", "N70,000", "N130,000", "N90,000"], "N30,000",
      "Cost of Goods Sold = Sales x (1 - margin) = 360,000 x 0.75 = 270,000; Stock destroyed = Opening stock + Purchases - Cost of Goods Sold = 40,000 + 260,000 - 270,000 = N30,000."),
  _q("A sole trader keeping incomplete records determines her profit for the year mainly by",
      ["Comparing net assets (capital) at the start and end of the period, adjusted for drawings and capital introduced", "Preparing a full set of double-entry ledger accounts as usual", "Relying solely on her bank statement balance", "Asking her accountant to guess a reasonable figure"], "Comparing net assets (capital) at the start and end of the period, adjusted for drawings and capital introduced",
      "Without full double-entry records, the statement of affairs (net worth) method is the standard technique for deducing profit indirectly from the change in net assets."),
  _q("A trader's opening capital was N175,000. Closing net assets are calculated from a statement of affairs as N260,000. She introduced N15,000 of additional capital and withdrew goods for personal use costing N10,000 during the year (no other drawings). Profit for the year was",
      ["N80,000", "N70,000", "N90,000", "N60,000"], "N80,000",
      "Total drawings (including goods taken for personal use) = 10,000; Profit = (Closing Capital + Drawings) - (Opening Capital + Additional Capital) = (260,000 + 10,000) - (175,000 + 15,000) = 270,000 - 190,000 = N80,000."),
];
