import "../quiz_question.dart";

const _subject = "Agricultural Science";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// University of Ibadan (UI) Post-UTME elective bank — Agricultural Science.
/// 100 medium-to-hard questions spread across the seven core UTME topics:
/// General Agriculture, Agricultural Ecology, Agricultural Engineering &
/// Mechanics, Soil Science, Agronomy, Animal Husbandry, and Agricultural
/// Economics & Extension.
List<QuizQuestion> buildUiAgriculturalScienceQuestions() {
  return [
    ..._generalAgriculture,
    ..._agriculturalEcology,
    ..._agriculturalEngineering,
    ..._soilScience,
    ..._agronomy,
    ..._animalHusbandry,
    ..._agriculturalEconomicsExtension,
  ];
}

final _generalAgriculture = [
  _q("The primary aim of agricultural research institutes in Nigeria is to",
      ["develop improved varieties, breeds and techniques for farmers", "sell farm produce directly to the public", "regulate the price of agricultural land", "issue import licences for farm machinery"], "develop improved varieties, breeds and techniques for farmers",
      "Research institutes exist chiefly to generate improved crop varieties, animal breeds and farming techniques that extension services then pass on to farmers."),
  _q("Mixed farming, as a system of agriculture, involves the",
      ["combination of crop production and livestock rearing on the same farm", "cultivation of only one crop over a very large area", "rearing of a single livestock species exclusively", "practice of shifting from one piece of land to another yearly"], "combination of crop production and livestock rearing on the same farm",
      "Mixed farming integrates both crop and livestock enterprises on the same holding, allowing manure and crop residues to be exchanged between the two."),
  _q("Monoculture, as practised in large plantations, refers to the",
      ["continuous cultivation of a single crop on the same piece of land", "rotation of several crops on the same land each season", "rearing of many different animal species together", "practice of leaving land fallow for several years"], "continuous cultivation of a single crop on the same piece of land",
      "Monoculture is the repeated growing of one crop species on the same land, common on plantations such as oil palm or rubber estates."),
  _q("Shifting cultivation is a traditional farming practice mainly associated with",
      ["clearing a plot, farming it briefly, then abandoning it for a fallow period", "the continuous use of a fixed plot with heavy fertiliser application", "large mechanised farms in the savanna", "greenhouse production of vegetables"], "clearing a plot, farming it briefly, then abandoning it for a fallow period",
      "Under shifting cultivation, a farmer clears and cultivates a plot for a few seasons, then abandons it to fallow while soil fertility is restored naturally."),
  _q("Bush fallowing differs from shifting cultivation mainly in that, under bush fallowing, the",
      ["farmer's compound or homestead remains fixed while only the cultivated plot is rotated", "farmer abandons the homestead entirely and relocates with each new plot", "same crop must be grown every season without exception", "land is never allowed a resting period"], "farmer's compound or homestead remains fixed while only the cultivated plot is rotated",
      "In bush fallowing the farmstead stays put and only the farmed plots rotate through a fallow cycle, unlike shifting cultivation where the whole settlement may move."),
  _q("Which of the following is a major reason for the low productivity of traditional agriculture in Nigeria?",
      ["Continued reliance on rudimentary tools and outdated methods", "Excessive use of certified improved seeds", "Overuse of modern irrigation systems", "Widespread adoption of mechanised harvesters"], "Continued reliance on rudimentary tools and outdated methods",
      "Traditional farming in many parts of Nigeria still depends on simple hand tools and age-old practices, limiting the scale and efficiency of output."),
  _q("Which of these is classified as an arable crop?",
      ["Maize", "Oil palm", "Cocoa", "Rubber"], "Maize",
      "Arable crops are those grown from seed and harvested within a season, such as maize, unlike tree or perennial crops like oil palm, cocoa and rubber."),
  _q("A plantation crop is best described as one that is",
      ["a perennial crop grown on a large, continuous scale for commercial purposes", "harvested and replanted within a single farming season", "grown exclusively for home consumption", "cultivated only in greenhouses"], "a perennial crop grown on a large, continuous scale for commercial purposes",
      "Plantation crops such as rubber, oil palm and cocoa are perennial, long-term crops typically grown on a large commercial scale."),
  _q("The term 'agroforestry' refers to a land-use system that",
      ["combines the growing of trees with crops and/or livestock on the same land", "involves clearing all trees before any cultivation begins", "restricts land use strictly to forestry alone", "excludes livestock rearing from farmland entirely"], "combines the growing of trees with crops and/or livestock on the same land",
      "Agroforestry deliberately integrates trees with arable crops and sometimes livestock, providing complementary benefits such as shade, soil improvement and extra income."),
  _q("One major problem facing agricultural development in Nigeria is",
      ["poor rural infrastructure such as roads, which hampers movement of produce", "an oversupply of agricultural credit to farmers", "excessive government subsidy on farm inputs", "too many trained agricultural extension officers"], "poor rural infrastructure such as roads, which hampers movement of produce",
      "Poor rural roads and storage facilities make it difficult and costly to move farm produce from rural areas to markets, discouraging productivity."),
  _q("Land tenure, in the context of Nigerian agriculture, refers to the",
      ["system by which land is owned, held and transferred", "chemical composition of the topsoil", "seasonal pattern of rainfall distribution", "classification of crops by their growth habit"], "system by which land is owned, held and transferred",
      "Land tenure describes the rules and customs governing who owns land, how it is acquired, and how rights to it are passed on."),
  _q("Farm records are kept by a farm manager mainly to",
      ["provide accurate information for planning, decision-making and evaluating performance", "increase the physical size of the farm", "replace the need for farm labour", "eliminate all forms of farm risk"], "provide accurate information for planning, decision-making and evaluating performance",
      "Farm records document inputs, outputs, costs and returns, giving the manager the data needed to plan future operations and assess profitability."),
];

final _agriculturalEcology = [
  _q("An ecosystem, as studied in agricultural ecology, refers to the",
      ["interaction between living organisms and their non-living environment", "classification of soil types found in a region", "list of crops suited to a particular climate", "process of breeding new plant varieties"], "interaction between living organisms and their non-living environment",
      "An ecosystem is a functional unit comprising living organisms (biotic) interacting with each other and with non-living (abiotic) factors like soil, water and air."),
  _q("A food chain in an agro-ecosystem typically begins with",
      ["producers, such as green plants, which trap solar energy", "primary consumers, such as herbivores", "secondary consumers, such as carnivores", "decomposers, such as bacteria and fungi"], "producers, such as green plants, which trap solar energy",
      "Food chains start with producers (green plants) that convert solar energy into chemical energy through photosynthesis, forming the base of the chain."),
  _q("Decomposers in an agricultural ecosystem play the important role of",
      ["breaking down dead organic matter and releasing nutrients back into the soil", "trapping solar energy for use by plants", "preying directly on living herbivores", "fixing atmospheric nitrogen exclusively"], "breaking down dead organic matter and releasing nutrients back into the soil",
      "Decomposers such as bacteria and fungi break down dead plant and animal matter, recycling nutrients back into the soil for uptake by producers."),
  _q("A biotic factor affecting crop production in an ecosystem includes",
      ["pests, diseases and weeds competing with or attacking the crop", "the amount of rainfall received in a season", "the mineral composition of the soil", "the intensity of sunlight reaching the crop"], "pests, diseases and weeds competing with or attacking the crop",
      "Biotic factors are living components of the environment, such as pests, pathogens and weeds, that directly interact with and affect crops."),
  _q("Which of the following is an example of an abiotic factor in agricultural ecology?",
      ["Soil temperature", "Population of soil earthworms", "A parasitic weed such as Striga", "A herd of grazing cattle"], "Soil temperature",
      "Abiotic factors are non-living physical or chemical components of the environment, such as temperature, rainfall, and soil pH."),
  _q("Ecological succession refers to the",
      ["gradual, orderly change in the composition of a plant community over time", "sudden extinction of a single crop species", "annual rotation of crops on a single plot", "process of ploughing and harrowing farmland"], "gradual, orderly change in the composition of a plant community over time",
      "Ecological succession describes the progressive replacement of one plant community by another over time, eventually leading toward a stable climax community."),
  _q("The derived savanna vegetation zone of Nigeria arose mainly as a result of",
      ["repeated human activities such as farming and bush burning degrading forest into grassland", "a naturally occurring desert expansion", "permanent flooding of the rainforest belt", "volcanic activity destroying forest cover"], "repeated human activities such as farming and bush burning degrading forest into grassland",
      "Derived savanna is a secondary vegetation type that resulted from continuous clearing, farming and burning of what was originally rainforest."),
  _q("Symbiosis, as observed between rhizobium bacteria and leguminous plants, is best described as",
      ["a mutually beneficial relationship where both organisms gain from the association", "a relationship where one organism benefits and harms the other", "a competitive relationship for the same limited resource", "a relationship where one organism benefits with no effect on the other"], "a mutually beneficial relationship where both organisms gain from the association",
      "Rhizobium bacteria fix atmospheric nitrogen for the legume's use, while the legume supplies the bacteria with carbohydrates, making it a mutualistic symbiosis."),
  _q("Parasitism, as an ecological relationship affecting crops, describes a situation where one organism",
      ["lives on or in another organism and derives nourishment at the host's expense", "competes with another for the same food source without direct contact", "benefits from another without affecting it in any way", "cooperates with another for mutual survival benefit"], "lives on or in another organism and derives nourishment at the host's expense",
      "In parasitism, the parasite obtains nutrients from a host organism, usually causing harm to the host, as seen with pests like aphids on crop plants."),
  _q("Nitrogen fixation is the process by which",
      ["atmospheric nitrogen gas is converted into a form usable by plants", "nitrogen is lost from the soil through leaching", "plants release nitrogen gas back into the atmosphere", "soil nitrates are converted into nitrogen gas"], "atmospheric nitrogen gas is converted into a form usable by plants",
      "Nitrogen fixation, carried out by certain bacteria, converts inert atmospheric nitrogen gas into compounds such as ammonia that plants can absorb and use."),
  _q("Denitrification in the nitrogen cycle refers to the process by which",
      ["nitrates in the soil are converted back into atmospheric nitrogen gas", "atmospheric nitrogen is converted into ammonia by bacteria", "nitrites are converted into nitrates by nitrifying bacteria", "plants absorb nitrates directly from the soil"], "nitrates in the soil are converted back into atmospheric nitrogen gas",
      "Denitrification is carried out by denitrifying bacteria under low-oxygen (waterlogged) conditions, converting soil nitrates back into nitrogen gas, which is lost to the atmosphere."),
  _q("Wind, as an ecological factor, affects crop production mainly by",
      ["increasing the rate of transpiration and potentially causing lodging in tall crops", "directly increasing the nitrogen content of the soil", "determining the pH level of the soil", "controlling the length of the rainy season"], "increasing the rate of transpiration and potentially causing lodging in tall crops",
      "Strong winds raise the rate of water loss (transpiration) from leaves and can physically knock down or lodge tall-stemmed crops such as maize."),
];

final _agriculturalEngineering = [
  _q("A disc plough is generally preferred over a mouldboard plough for primary tillage on",
      ["hard, dry or stony soils, where it can cut through with less clogging", "very loose, sandy soils with no obstructions", "soils that require no inversion at all", "wetland rice fields exclusively"], "hard, dry or stony soils, where it can cut through with less clogging",
      "Disc ploughs are well suited to hard, dry, stony or root-infested soils because their rotating discs cut through obstructions with far less clogging than a mouldboard plough."),
  _q("A seed drill is a farm implement used mainly for",
      ["planting seeds at a uniform depth and spacing in rows", "harvesting mature cereal crops", "spraying herbicides on standing crops", "threshing grain after harvest"], "planting seeds at a uniform depth and spacing in rows",
      "A seed drill sows seeds mechanically at a controlled depth and even row spacing, improving on the unevenness of broadcasting by hand."),
  _q("A sprayer is a piece of farm equipment specifically designed to",
      ["apply liquid chemicals such as pesticides and herbicides to crops", "cut and gather mature grain crops", "till and pulverise the soil before planting", "measure the moisture content of harvested grain"], "apply liquid chemicals such as pesticides and herbicides to crops",
      "Sprayers are used to apply liquid agrochemicals, such as insecticides, fungicides and herbicides, evenly over crops or fields."),
  _q("The main purpose of a farm silo is to",
      ["store bulk feed or grain under conditions that limit spoilage", "till the soil before planting", "irrigate crops during the dry season", "harvest root and tuber crops"], "store bulk feed or grain under conditions that limit spoilage",
      "A silo is a storage structure designed to keep grain or silage in bulk while protecting it from moisture, pests and spoilage."),
  _q("A wheelbarrow used on the farm is best classified as a",
      ["simple hand tool for conveying farm materials over short distances", "primary tillage implement", "type of irrigation equipment", "mechanised harvesting machine"], "simple hand tool for conveying farm materials over short distances",
      "The wheelbarrow is a manually operated hand tool used to transport materials such as soil, manure or harvested produce over short distances."),
  _q("Which of the following safety practices is most important when operating a farm tractor?",
      ["Ensuring all guards are in place and avoiding loose clothing near moving parts", "Operating the tractor at maximum speed at all times", "Removing the safety guard to increase visibility", "Allowing untrained persons to operate the machine for practice"], "Ensuring all guards are in place and avoiding loose clothing near moving parts",
      "Keeping protective guards in place and avoiding loose clothing near power take-off shafts and other moving parts is essential to prevent serious tractor-related accidents."),
  _q("Land clearing, as a farm operation, involves the",
      ["removal of trees, stumps and vegetation to prepare land for cultivation", "application of fertiliser to growing crops", "harvesting of mature farm produce", "sorting and grading of farm produce"], "removal of trees, stumps and vegetation to prepare land for cultivation",
      "Land clearing is the initial operation of removing unwanted trees, shrubs, stumps and debris so that the land can subsequently be tilled and planted."),
  _q("Ridging, as a farm operation, is particularly beneficial for crops such as yam mainly because it",
      ["provides loose, well-aerated soil for good tuber development and improves drainage", "increases the nitrogen content of the topsoil directly", "eliminates the need for weeding throughout the season", "reduces the amount of sunlight reaching the crop"], "provides loose, well-aerated soil for good tuber development and improves drainage",
      "Ridges create a deep, loose, well-drained soil mass that allows tubers like yam to expand freely while also channelling away excess water."),
  _q("An animal-drawn implement such as an ox-plough is most suited to farmers who",
      ["cannot afford a tractor but require more power than manual hand tools provide", "operate very large mechanised commercial plantations", "farm exclusively in greenhouse conditions", "require precision planting of tree seedlings only"], "cannot afford a tractor but require more power than manual hand tools provide",
      "Animal traction, such as ox-drawn ploughs, offers small-scale farmers a level of power between manual hand tools and costly tractors."),
  _q("Which of the following is a key advantage of mechanised farming over the exclusive use of hand tools?",
      ["It allows a larger area of land to be cultivated within a shorter time", "It always eliminates the need for skilled labour entirely", "It guarantees higher soil fertility automatically", "It removes the need for any form of maintenance"], "It allows a larger area of land to be cultivated within a shorter time",
      "Mechanisation increases the speed and scale of farm operations, enabling more land to be worked in less time compared to manual labour alone."),
  _q("Threshing, as a post-harvest operation, refers to the",
      ["separation of grain from the straw or husk after harvesting", "cutting and gathering of a mature crop from the field", "drying of harvested produce under the sun", "storage of grain in airtight containers"], "separation of grain from the straw or husk after harvesting",
      "Threshing is the operation that separates the edible grain from the straw, stalks or husks after the crop has been reaped."),
  _q("The main function of a planter (mechanical planting machine) on a mechanised farm is to",
      ["place seeds at the correct depth and spacing in one continuous operation", "harvest and thresh grain crops simultaneously", "remove weeds from between crop rows", "apply irrigation water to the field"], "place seeds at the correct depth and spacing in one continuous operation",
      "A mechanical planter opens the furrow, drops the seed at a set spacing and depth, and covers it, all in a single continuous pass."),
];

final _soilScience = [
  _q("Soil is best defined as the",
      ["loose surface layer of the earth's crust that supports plant growth", "hard rock layer found deep beneath the earth's surface", "gaseous layer surrounding the earth", "body of water found in rivers and lakes"], "loose surface layer of the earth's crust that supports plant growth",
      "Soil is the thin, loose, weathered layer covering the earth's surface, formed from rock and organic material, capable of supporting plant life."),
  _q("Sandy soil is characterised mainly by",
      ["large particle size, good drainage, and low water-holding capacity", "very small particle size and high water-holding capacity", "a sticky texture when wet and poor drainage", "the highest nutrient-retention capacity among soil types"], "large particle size, good drainage, and low water-holding capacity",
      "Sandy soils have coarse, large particles with wide pore spaces, giving them excellent drainage but a poor ability to retain water and nutrients."),
  _q("Clay soil is generally less favourable for root crop production mainly because it",
      ["becomes compact and waterlogged, restricting root expansion and aeration", "drains water too quickly for roots to absorb", "contains too little organic matter to support any growth", "has particles too large for roots to penetrate"], "becomes compact and waterlogged, restricting root expansion and aeration",
      "Clay soils have very fine particles that pack tightly, holding excess water and limiting the aeration and expansion space that root and tuber crops need."),
  _q("Loam soil is generally considered the most suitable soil type for crop production because it",
      ["combines good drainage, aeration and water/nutrient retention", "consists almost entirely of large sand particles", "is composed purely of decomposed organic matter", "has no mineral particles present at all"], "combines good drainage, aeration and water/nutrient retention",
      "Loam is a balanced mixture of sand, silt and clay that provides good drainage and aeration while still retaining adequate moisture and nutrients."),
  _q("Soil texture refers to the",
      ["relative proportion of sand, silt and clay particles in the soil", "arrangement of soil particles into aggregates or crumbs", "acidity or alkalinity level of the soil", "amount of organic matter present in the soil"], "relative proportion of sand, silt and clay particles in the soil",
      "Soil texture is determined by the relative percentages of sand, silt and clay-sized mineral particles that make up the soil."),
  _q("Soil structure, as distinct from soil texture, refers to the",
      ["way individual soil particles are arranged or aggregated together", "proportion of sand, silt and clay in the soil", "depth of the topsoil layer", "chemical elements dissolved in the soil water"], "way individual soil particles are arranged or aggregated together",
      "Soil structure describes how individual soil particles clump or bind together into aggregates, which affects aeration, drainage and root penetration."),
  _q("Soil pH is a measure of the",
      ["degree of acidity or alkalinity of the soil", "amount of organic matter present in the soil", "moisture-holding capacity of the soil", "total mineral content of the soil"], "degree of acidity or alkalinity of the soil",
      "Soil pH indicates how acidic or alkaline the soil is on a scale, which strongly influences nutrient availability to plants."),
  _q("Most arable crops grow best within a soil pH range that is",
      ["slightly acidic to neutral, roughly 6.0 to 7.0", "extremely acidic, below 3.0", "extremely alkaline, above 9.0", "completely neutral at exactly 14.0"], "slightly acidic to neutral, roughly 6.0 to 7.0",
      "Most crop nutrients are most readily available to plants in a slightly acidic to neutral pH range, approximately 6.0 to 7.0."),
  _q("Liming is a soil management practice carried out mainly to",
      ["reduce soil acidity by raising the pH of acidic soils", "increase the sand content of the soil", "reduce the water-holding capacity of the soil", "eliminate all organic matter from the soil"], "reduce soil acidity by raising the pH of acidic soils",
      "Applying lime to acidic soils neutralises excess acidity, raising the pH to a range more favourable for nutrient availability and crop growth."),
  _q("Organic matter improves soil fertility mainly by",
      ["improving soil structure, water retention and supplying nutrients as it decomposes", "increasing the proportion of sand particles in the soil", "lowering the soil pH to extremely acidic levels", "reducing the population of beneficial soil microorganisms"], "improving soil structure, water retention and supplying nutrients as it decomposes",
      "Decomposing organic matter binds soil particles into stable aggregates, improves water-holding capacity, and releases nutrients as it breaks down."),
  _q("Humus refers to the",
      ["dark, well-decomposed organic material in the soil", "layer of solid rock beneath the soil profile", "mineral fraction of the soil derived from parent rock", "topmost living vegetation covering the soil"], "dark, well-decomposed organic material in the soil",
      "Humus is the stable, dark-coloured, well-decomposed organic material remaining after plant and animal residues have broken down."),
  _q("Cover cropping helps to control soil erosion mainly by",
      ["shielding the soil surface from the direct impact of rain and wind", "increasing the slope of the farmland", "removing all organic matter from the topsoil", "compacting the soil to prevent water infiltration"], "shielding the soil surface from the direct impact of rain and wind",
      "A cover crop's foliage intercepts raindrops and reduces wind speed at the soil surface, protecting the topsoil from being dislodged and washed or blown away."),
  _q("The three main components of a fertile agricultural soil profile, from top to bottom, are generally described as the",
      ["topsoil, subsoil and parent material", "sand, silt and clay layers", "humus, water and air layers", "root zone, stem zone and canopy zone"], "topsoil, subsoil and parent material",
      "A typical soil profile is divided into distinct horizons, broadly the nutrient-rich topsoil, the subsoil beneath it, and the parent material or bedrock below."),
  _q("Leaching, as a process affecting soil fertility, refers to the",
      ["downward movement and loss of soluble nutrients beyond the reach of plant roots", "upward movement of nutrients to the soil surface", "addition of fertiliser nutrients to the topsoil", "conversion of organic matter into humus"], "downward movement and loss of soluble nutrients beyond the reach of plant roots",
      "Leaching occurs when excess water percolating through the soil carries dissolved nutrients down past the root zone, making them unavailable to crops."),
  _q("Which of the following soil organisms is most beneficial in improving soil aeration and structure?",
      ["Earthworm", "Nematode pest", "Termite that attacks crop roots", "Fungal pathogen causing root rot"], "Earthworm",
      "Earthworms burrow through the soil, creating channels that improve aeration and drainage, while their casts enrich the soil with nutrients."),
];

final _agronomy = [
  _q("Crop rotation is a farming practice that involves",
      ["growing different crops in a planned sequence on the same land over successive seasons", "growing the same crop continuously on the same land every season", "planting several crops together at random on one plot", "abandoning farmland permanently after one season of use"], "growing different crops in a planned sequence on the same land over successive seasons",
      "Crop rotation deliberately alternates different crop types on the same plot across seasons to maintain soil fertility and disrupt pest and disease cycles."),
  _q("One major benefit of including a leguminous crop in a crop rotation programme is that it",
      ["helps restore soil nitrogen through its nitrogen-fixing root nodules", "depletes soil nitrogen faster than other crops", "requires no sunlight to grow successfully", "eliminates the need for any weeding"], "helps restore soil nitrogen through its nitrogen-fixing root nodules",
      "Legumes host nitrogen-fixing rhizobium bacteria in their root nodules, which convert atmospheric nitrogen into a form that enriches the soil for subsequent crops."),
  _q("Mixed cropping refers to the practice of",
      ["growing two or more crops simultaneously on the same piece of land", "growing a single crop species over a very large area", "leaving farmland completely fallow for a long period", "rotating a single crop with a fallow period only"], "growing two or more crops simultaneously on the same piece of land",
      "Mixed cropping involves cultivating more than one crop species together on the same plot at the same time, often to maximise land use and reduce risk."),
  _q("A major advantage of mixed cropping over monocropping is that it",
      ["reduces the overall risk of total crop failure and makes efficient use of land resources", "guarantees a higher yield of every individual crop grown", "eliminates competition between crops entirely", "requires no knowledge of individual crop requirements"], "reduces the overall risk of total crop failure and makes efficient use of land resources",
      "By growing several crops together, a farmer spreads risk since a pest, disease or price failure affecting one crop is unlikely to affect all the crops equally."),
  _q("Seed dormancy refers to a condition in which a viable seed",
      ["fails to germinate even under otherwise favourable conditions", "germinates immediately once planted", "loses its ability to germinate permanently", "is destroyed by pests before planting"], "fails to germinate even under otherwise favourable conditions",
      "A dormant seed is alive and capable of germinating but remains inactive under favourable conditions until an internal or external barrier to germination is removed."),
  _q("Which of the following is a recognised method of breaking seed dormancy before planting?",
      ["Scarification of the hard seed coat", "Continuous flooding of the seed for several months", "Storing the seed at extremely high temperatures indefinitely", "Coating the seed entirely in wax"], "Scarification of the hard seed coat",
      "Scarification, scratching or nicking a hard seed coat, allows water and oxygen to penetrate, breaking dormancy caused by impermeable seed coats."),
  _q("The correct planting depth for a seed is generally guided by the",
      ["size of the seed, with larger seeds typically planted deeper", "colour of the seed coat", "market price of the resulting produce", "distance of the farm from the nearest town"], "size of the seed, with larger seeds typically planted deeper",
      "As a general agronomic guideline, larger seeds with greater food reserves are planted deeper, while small seeds are planted shallowly, close to the surface."),
  _q("Mulching is a crop management practice that involves",
      ["covering the soil surface around plants with organic or other material", "digging deep trenches around each plant", "removing all vegetation cover from the soil surface", "burning plant residues on the field before planting"], "covering the soil surface around plants with organic or other material",
      "Mulching spreads a protective layer, often organic material like straw, over the soil surface around crops to conserve moisture and suppress weeds."),
  _q("One major benefit of mulching to a growing crop is that it",
      ["conserves soil moisture and suppresses weed growth", "increases the rate of soil erosion", "eliminates the need for any irrigation permanently", "reduces the organic matter content of the soil"], "conserves soil moisture and suppresses weed growth",
      "By covering bare soil, mulch reduces evaporation losses and blocks light needed by weed seeds to germinate, benefiting the main crop."),
  _q("Weeds are generally undesirable on farmland mainly because they",
      ["compete with crops for nutrients, water, light and space", "always improve the fertility of the soil", "attract beneficial pollinators exclusively", "increase the market value of the harvested crop"], "compete with crops for nutrients, water, light and space",
      "Weeds are unwanted plants that compete directly with cultivated crops for essential growth resources, often reducing crop yield if left unchecked."),
  _q("Which of the following is a chemical method of weed control?",
      ["Application of a selective herbicide", "Hand-pulling of weeds", "Hoeing between crop rows", "Crop rotation with a smothering cover crop"], "Application of a selective herbicide",
      "Herbicides are chemical substances applied specifically to kill or suppress weeds, distinguishing chemical control from manual or cultural methods."),
  _q("Crop pests differ from crop pathogens mainly in that pests are generally",
      ["visible organisms, such as insects and rodents, that directly damage the crop", "microscopic disease-causing organisms like bacteria, fungi and viruses", "beneficial organisms that always aid pollination", "chemicals applied to protect the crop"], "visible organisms, such as insects and rodents, that directly damage the crop",
      "Pests are typically larger, often visible organisms such as insects, rodents and birds, whereas pathogens are microscopic disease-causing agents like fungi, bacteria and viruses."),
  _q("Integrated Pest Management (IPM) is best described as an approach that",
      ["combines biological, cultural, chemical and other control methods for sustainable pest control", "relies exclusively on the heavy use of chemical pesticides", "eliminates all pest control practices from farming", "focuses only on the use of resistant crop varieties"], "combines biological, cultural, chemical and other control methods for sustainable pest control",
      "IPM integrates multiple complementary strategies, biological, cultural, mechanical and judicious chemical control, to manage pests sustainably and minimise resistance and environmental harm."),
  _q("Biological control of crop pests involves the use of",
      ["natural enemies, such as predators or parasites, to reduce pest populations", "synthetic chemical pesticides sprayed on the crop", "physical barriers like fences around the farm", "resistant crop varieties bred through hybridisation"], "natural enemies, such as predators or parasites, to reduce pest populations",
      "Biological control harnesses natural enemies of a pest, such as predatory insects or parasitic wasps, to keep pest populations in check without chemicals."),
  _q("Harvesting a crop before it reaches full maturity generally results in",
      ["reduced yield and poorer quality of the produce", "an automatic increase in the crop's market value", "improved storage life of the harvested produce", "higher nutrient content in the harvested produce"], "reduced yield and poorer quality of the produce",
      "Premature harvesting typically means the crop has not accumulated its full potential yield or quality, resulting in smaller, less developed produce."),
  _q("Curing, as applied to harvested tubers such as yam, is carried out mainly to",
      ["heal surface wounds and toughen the skin to reduce storage losses", "increase the moisture content of the tuber before storage", "artificially ripen the tuber for immediate consumption", "remove all starch content from the tuber"], "heal surface wounds and toughen the skin to reduce storage losses",
      "Curing allows harvested tubers to heal cuts and bruises and develop a tougher outer skin, which reduces rot and water loss during storage."),
  _q("Grading of harvested farm produce refers to the",
      ["sorting of produce into different categories based on quality, size or maturity", "process of drying produce under direct sunlight", "application of chemicals to preserve produce", "transportation of produce from the farm to the market"], "sorting of produce into different categories based on quality, size or maturity",
      "Grading separates farm produce into defined classes based on attributes such as size, quality or ripeness, which helps in pricing and marketing."),
];

final _animalHusbandry = [
  _q("Animal husbandry is best defined as the branch of agriculture concerned with the",
      ["breeding, feeding, housing and general management of farm animals", "cultivation and management of crops for human consumption", "study of soil formation and classification", "marketing and distribution of farm produce"], "breeding, feeding, housing and general management of farm animals",
      "Animal husbandry covers all aspects of raising livestock, including breeding, nutrition, housing, health and general management practices."),
  _q("Which of the following is classified as a monogastric farm animal?",
      ["Pig", "Cattle", "Sheep", "Goat"], "Pig",
      "The pig has a single-chambered stomach, classifying it as monogastric, unlike ruminants such as cattle, sheep and goats, which have a multi-chambered stomach."),
  _q("Ruminant animals, such as cattle and goats, are distinguished from monogastric animals by having",
      ["a four-chambered stomach adapted for digesting fibrous plant material", "a single-chambered stomach with limited fibre digestion ability", "no stomach at all in their digestive system", "a digestive system identical to that of poultry"], "a four-chambered stomach adapted for digesting fibrous plant material",
      "Ruminants possess a specialised four-compartment stomach (rumen, reticulum, omasum and abomasum) that allows efficient breakdown of fibrous, cellulose-rich feed."),
  _q("The rumen, the largest chamber of a ruminant's stomach, functions mainly as a",
      ["fermentation chamber where microorganisms break down fibrous feed", "site where milk is produced and stored", "chamber that filters blood before digestion", "structure used solely for water storage"], "fermentation chamber where microorganisms break down fibrous feed",
      "The rumen houses billions of microorganisms that ferment and break down cellulose and other fibrous plant materials the animal itself cannot digest directly."),
  _q("Colostrum, the first milk produced by a mammal after giving birth, is especially important to the newborn because it",
      ["provides antibodies that boost the newborn's immunity against disease", "contains no nutritional value whatsoever", "is harmful and should be withheld from the newborn", "is produced only in animals that do not suckle their young"], "provides antibodies that boost the newborn's immunity against disease",
      "Colostrum is rich in maternal antibodies that give the newborn passive immunity, protecting it from disease during its first vulnerable weeks of life."),
  _q("Culling, as a livestock management practice, refers to the",
      ["removal of unproductive or undesirable animals from the herd or flock", "process of feeding animals a balanced ration", "vaccination of animals against common diseases", "housing of animals in a well-ventilated structure"], "removal of unproductive or undesirable animals from the herd or flock",
      "Culling involves identifying and removing animals that are unproductive, diseased or otherwise undesirable, improving the overall quality and efficiency of the remaining herd or flock."),
  _q("Castration of male farm animals not intended for breeding is carried out mainly to",
      ["make the animals calmer and improve the quality of meat produced", "increase their fertility for breeding purposes", "prevent the animals from ever gaining weight", "eliminate the need for proper feeding"], "make the animals calmer and improve the quality of meat produced",
      "Castration removes the testes, reducing aggressive behaviour and often improving growth rate and meat quality in animals raised specifically for meat."),
  _q("Which of the following is an example of an intensive system of livestock management?",
      ["Battery cage system for layers", "Free-range system for poultry", "Nomadic pastoral system for cattle", "Ranching system for beef cattle"], "Battery cage system for layers",
      "The battery cage system confines birds closely in cages within a controlled structure, representing a highly intensive form of poultry management."),
  _q("Extensive livestock management, such as free-range grazing, is characterised mainly by",
      ["animals roaming over a large area to source most of their own feed", "animals being confined entirely within small cages", "complete control over every aspect of feeding and breeding", "the highest possible stocking density per unit area"], "animals roaming over a large area to source most of their own feed",
      "In extensive systems, animals graze freely over wide areas, obtaining most of their feed naturally, with comparatively little direct human control."),
  _q("Artificial insemination in livestock breeding involves the",
      ["introduction of collected semen into a female's reproductive tract by artificial means", "natural mating of a male and female of the same species", "surgical removal of reproductive organs from breeding stock", "cloning of an animal from a single somatic cell"], "introduction of collected semen into a female's reproductive tract by artificial means",
      "Artificial insemination allows semen collected from a superior male to be introduced into the female reproductive tract without natural mating, spreading desirable genetics widely."),
  _q("A major advantage of artificial insemination in livestock improvement is that it",
      ["allows the genes of a superior male to be used to breed many females widely", "eliminates the need for any record-keeping on the farm", "guarantees that every offspring produced will be female", "removes the need for proper animal nutrition entirely"], "allows the genes of a superior male to be used to breed many females widely",
      "Because semen from one outstanding male can be distributed to inseminate numerous females, artificial insemination rapidly spreads valuable genetic traits across a population."),
  _q("Which of the following nutrients is the primary source of energy in a typical livestock ration?",
      ["Carbohydrates", "Vitamins", "Minerals", "Water"], "Carbohydrates",
      "Carbohydrates, found abundantly in feeds such as maize and other cereals, serve as the main dietary source of energy for farm animals."),
  _q("Protein in a livestock ration is especially important mainly because it",
      ["supports growth, tissue repair and the building of body structures", "is the animal's primary source of immediate energy", "regulates the animal's body temperature directly", "prevents all forms of livestock disease automatically"], "supports growth, tissue repair and the building of body structures",
      "Proteins supply the amino acids needed for building and repairing muscle and other body tissues, making them essential for growth and productivity."),
  _q("A balanced ration for livestock is best described as a feed mixture that",
      ["supplies all required nutrients in the correct proportion and quantity for a given animal", "contains only a single feed ingredient", "consists entirely of water with no solid feed", "is composed purely of minerals with no energy source"], "supplies all required nutrients in the correct proportion and quantity for a given animal",
      "A balanced ration is carefully formulated to provide the right amounts and proportions of energy, protein, vitamins and minerals needed by a particular class of livestock."),
  _q("Foot-and-mouth disease is a major infectious disease that primarily affects",
      ["cloven-hoofed animals such as cattle, sheep, goats and pigs", "poultry exclusively", "fish in freshwater ponds only", "rabbits and other small mammals only"], "cloven-hoofed animals such as cattle, sheep, goats and pigs",
      "Foot-and-mouth disease is a highly contagious viral disease that specifically affects cloven-hoofed livestock, causing blisters on the mouth and feet."),
  _q("Newcastle disease is a major viral disease of significant economic importance in",
      ["poultry", "cattle", "pigs", "sheep"], "poultry",
      "Newcastle disease is a highly contagious and often fatal viral disease affecting domestic poultry, causing significant economic losses if not controlled through vaccination."),
  _q("Vaccination of livestock is carried out mainly to",
      ["stimulate the animal's immune system to develop resistance against specific diseases", "increase the animal's body weight directly", "improve the taste of meat produced by the animal", "eliminate the need for proper feeding and housing"], "stimulate the animal's immune system to develop resistance against specific diseases",
      "Vaccines expose an animal's immune system to a weakened or inactivated pathogen, prompting it to develop protective antibodies against future infection by that disease."),
  _q("Which of the following is an important factor to consider when selecting a site for livestock housing?",
      ["Good drainage and adequate ventilation of the site", "Proximity to a densely populated residential estate", "Absence of any access road to the site", "A site permanently prone to flooding"], "Good drainage and adequate ventilation of the site",
      "A well-drained, well-ventilated site helps keep livestock housing dry and free of excess moisture, reducing disease risk and improving animal comfort."),
  _q("Ectoparasites, such as ticks and mites, are external parasites of livestock that mainly cause harm by",
      ["feeding on blood or skin, leading to irritation, blood loss and disease transmission", "living entirely within the animal's digestive tract", "improving the animal's overall growth rate", "providing essential nutrients to the host animal"], "feeding on blood or skin, leading to irritation, blood loss and disease transmission",
      "Ectoparasites attach to the animal's skin, feeding on blood or tissue, which causes irritation, blood loss, reduced productivity, and can transmit disease-causing organisms."),
  _q("Weaning, in livestock management, refers to the",
      ["gradual withdrawal of a young animal from dependence on its mother's milk", "process of vaccinating a newborn animal", "castration of a young male animal", "process of selecting breeding stock for mating"], "gradual withdrawal of a young animal from dependence on its mother's milk",
      "Weaning is the transitional process of shifting a young animal's diet away from milk and onto solid feed, ending its dependence on the mother."),
  _q("Fish farming, or aquaculture, is best defined as the",
      ["deliberate rearing of fish and other aquatic organisms under controlled conditions", "harvesting of wild fish from natural rivers and oceans", "cultivation of crops on flooded farmland", "rearing of birds in an enclosed poultry house"], "deliberate rearing of fish and other aquatic organisms under controlled conditions",
      "Aquaculture involves the intentional breeding, stocking and management of fish and other aquatic species in ponds or tanks, distinct from capturing wild fish."),
  _q("A concrete or earthen fish pond used in aquaculture must have a reliable water supply mainly to",
      ["maintain suitable water quality and quantity for fish growth and survival", "increase the amount of feed the fish consume", "prevent the fish from ever reproducing", "eliminate the need to feed the fish at all"], "maintain suitable water quality and quantity for fish growth and survival",
      "A steady, adequate water supply is essential in a fish pond to sustain proper oxygen levels, temperature and overall water quality needed for healthy fish growth."),
];

final _agriculturalEconomicsExtension = [
_q("Agricultural economics is best described as the branch of agriculture concerned with the",
      ["application of economic principles to farm production, resource use and marketing decisions", "breeding and genetic improvement of farm animals", "classification and management of soil types", "study of pest and disease control on crops"], "application of economic principles to farm production, resource use and marketing decisions",
      "Agricultural economics applies core economic principles, such as scarcity, cost and efficient resource allocation, to decisions about farm production and marketing."),
_q("A farm budget is best described as a",
      ["plan estimating expected income and expenditure for a farm business over a period", "record of past weather patterns affecting a farm", "list of livestock breeds kept on a farm", "schedule of vaccination dates for farm animals"], "plan estimating expected income and expenditure for a farm business over a period",
      "A farm budget forecasts anticipated revenues and costs for a defined period, helping the farmer plan resource allocation and assess likely profitability."),
_q("Fixed costs in farm production are costs that",
      ["remain constant regardless of the level of output produced", "vary directly and proportionately with the level of output produced", "occur only once during the entire life of the farm business", "are incurred exclusively when produce is sold"], "remain constant regardless of the level of output produced",
      "Fixed costs, such as land rent or depreciation on buildings, must be paid whether output is high, low, or even zero, and do not change with production level."),
_q("Variable costs in farm production include expenses such as",
      ["cost of seeds, fertiliser and labour, which change with the level of output", "annual land rent, which stays the same regardless of output", "depreciation on permanent farm buildings", "insurance premiums paid once a year regardless of output"], "cost of seeds, fertiliser and labour, which change with the level of output",
      "Variable costs, such as seed, fertiliser and hired labour, rise or fall directly with the scale of production undertaken."),
_q("Farm profit is calculated as the",
      ["difference between total farm revenue and total farm costs", "sum of all fixed and variable costs incurred", "total quantity of produce harvested in a season", "total land area under cultivation on the farm"], "difference between total farm revenue and total farm costs",
      "Profit is the financial surplus remaining after all costs (fixed and variable) have been subtracted from the total revenue earned from the farm business."),
_q("The law of diminishing returns, as applied in agriculture, states that beyond a certain point",
      ["additional units of a variable input yield progressively smaller increases in output", "every additional unit of input always increases output by the same amount", "output continues to rise indefinitely as more input is added", "reducing an input always increases total output"], "additional units of a variable input yield progressively smaller increases in output",
      "The law of diminishing returns describes how, once an optimal input level is passed, each extra unit of a variable input adds progressively less to total output."),
_q("Demand for a farm product, in economic terms, refers to the",
      ["quantity of the product buyers are willing and able to purchase at a given price", "total quantity of the product available for sale in the market", "amount of the product that farmers wish to produce", "government-imposed price ceiling on the product"], "quantity of the product buyers are willing and able to purchase at a given price",
      "Demand specifically describes the quantity consumers are both willing and financially able to buy at a particular price, not merely a general desire for the good."),
_q("Supply of a farm product refers to the",
      ["quantity of the product that producers are willing and able to offer for sale at a given price", "quantity of the product consumers wish to purchase at a given price", "total land area used to cultivate the product", "amount of a product lost to pests during storage"], "quantity of the product that producers are willing and able to offer for sale at a given price",
      "Supply describes the quantity that sellers or producers are willing and able to bring to market for sale at a specified price."),
_q("Market equilibrium price is the price at which the",
      ["quantity demanded of a product equals the quantity supplied", "government fixes the price regardless of demand or supply", "quantity supplied is always greater than the quantity demanded", "quantity demanded is always greater than the quantity supplied"], "quantity demanded of a product equals the quantity supplied",
      "Equilibrium price occurs where the quantity buyers wish to purchase exactly matches the quantity sellers are willing to supply, clearing the market."),
_q("Agricultural marketing encompasses all the activities involved in",
      ["moving farm produce from the point of production to the final consumer", "growing crops from planting to harvest only", "breeding and selecting superior livestock", "controlling pests and diseases on the farm"], "moving farm produce from the point of production to the final consumer",
      "Agricultural marketing covers the entire chain of activities, assembling, grading, storage, transport and sale, that gets produce from farm to consumer."),
];
