import "../quiz_question.dart";

const _subject = "Biology";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// University of Ibadan (UI) Post-UTME elective Biology bank — 100
/// medium-to-hard, original questions written to Post-UTME/JAMB difficulty
/// and spread across the standard UTME Biology syllabus: Living
/// Organisms/Cell Biology, Form and Functions/Physiology, Reproduction,
/// Genetics and Heredity, Ecology and Environment, and Evolution. This is a
/// general practice set, not an official UI past-question paper.
List<QuizQuestion> buildUiBiologyQuestions() {
  return [
    ..._cellBiology,
    ..._formAndFunctions,
    ..._reproduction,
    ..._genetics,
    ..._ecology,
    ..._evolution,
  ];
}

final _cellBiology = [
  _q("Which of the following organelles is bounded by a double membrane and contains its own circular DNA?",
      ["Mitochondrion", "Ribosome", "Lysosome", "Golgi apparatus"], "Mitochondrion",
      "Mitochondria have an inner and outer membrane and possess their own circular DNA, supporting the endosymbiotic theory of their origin."),
  _q("The movement of water molecules from a region of high water potential to a region of low water potential through a selectively permeable membrane is called",
      ["osmosis", "diffusion", "active transport", "plasmolysis"], "osmosis",
      "Osmosis specifically describes the net movement of water across a selectively permeable membrane along a water-potential gradient."),
  _q("A plant cell placed in a hypertonic solution will most likely undergo",
      ["plasmolysis", "turgidity", "haemolysis", "cytolysis"], "plasmolysis",
      "In a hypertonic solution, water leaves the plant cell by osmosis, causing the protoplast to shrink away from the cell wall, a condition called plasmolysis."),
  _q("Which of the following best distinguishes a prokaryotic cell from a eukaryotic cell?",
      ["Absence of a membrane-bound nucleus", "Absence of a cell membrane", "Absence of cytoplasm", "Absence of ribosomes"], "Absence of a membrane-bound nucleus",
      "Prokaryotic cells lack a true, membrane-bound nucleus and other membrane-bound organelles, unlike eukaryotic cells."),
  _q("The organelle responsible for packaging and modifying proteins for secretion out of the cell is the",
      ["Golgi apparatus", "nucleolus", "peroxisome", "centriole"], "Golgi apparatus",
      "The Golgi apparatus modifies, sorts and packages proteins received from the rough endoplasmic reticulum into vesicles for secretion."),
  _q("Which process describes the net movement of molecules from a region of higher concentration to a region of lower concentration without the use of metabolic energy?",
      ["Diffusion", "Active transport", "Osmosis", "Pinocytosis"], "Diffusion",
      "Diffusion is a passive process driven by the concentration gradient and does not require ATP, unlike active transport."),
  _q("Enzymes are best described as",
      ["biological catalysts that are mostly proteins", "carbohydrates that store energy", "inorganic ions required in trace amounts", "lipids that form cell membranes"], "biological catalysts that are mostly proteins",
      "Enzymes are globular proteins that speed up biochemical reactions by lowering activation energy without being consumed."),
  _q("An increase in temperature beyond an enzyme's optimum generally causes its activity to",
      ["decrease sharply as the enzyme denatures", "increase indefinitely", "remain completely unchanged", "double for every 10 degree rise without limit"], "decrease sharply as the enzyme denatures",
      "Beyond the optimum temperature, the enzyme's tertiary structure is disrupted (denaturation), destroying the active site and sharply reducing activity."),
  _q("Which of the following is a monosaccharide?",
      ["Glucose", "Sucrose", "Starch", "Cellulose"], "Glucose",
      "Glucose is a simple sugar (monosaccharide), whereas sucrose is a disaccharide and starch and cellulose are polysaccharides."),
  _q("The basic building blocks of proteins are",
      ["amino acids", "fatty acids", "monosaccharides", "nucleotides"], "amino acids",
      "Proteins are polymers of amino acids linked together by peptide bonds."),
  _q("Mitosis results in the formation of",
      ["two daughter cells genetically identical to the parent cell", "four haploid daughter cells", "two daughter cells with half the chromosome number", "a single fused diploid cell"], "two daughter cells genetically identical to the parent cell",
      "Mitosis is a nuclear division producing two genetically identical diploid daughter cells, used for growth and repair."),
  _q("Which stage of mitosis is characterised by the alignment of chromosomes at the equatorial plate?",
      ["Metaphase", "Prophase", "Anaphase", "Telophase"], "Metaphase",
      "During metaphase, spindle fibres align chromosomes at the cell's equator in preparation for separation."),
  _q("The site of aerobic respiration in a eukaryotic cell is the",
      ["mitochondrion", "chloroplast", "nucleus", "ribosome"], "mitochondrion",
      "The mitochondrion houses the enzymes of the Krebs cycle and electron transport chain that generate ATP aerobically."),
  _q("Active transport differs from diffusion mainly because active transport",
      ["requires metabolic energy and can move substances against a concentration gradient", "never requires a carrier protein", "only occurs in plant cells", "always moves substances down a concentration gradient"], "requires metabolic energy and can move substances against a concentration gradient",
      "Active transport uses ATP to move substances from a region of lower to higher concentration, unlike passive diffusion."),
  _q("Which of the following organelles is responsible for intracellular digestion in animal cells?",
      ["Lysosome", "Ribosome", "Chloroplast", "Vacuole"], "Lysosome",
      "Lysosomes contain hydrolytic enzymes that break down worn-out organelles, food particles and foreign material within the cell."),
  _q("The fluid mosaic model describes the structure of the",
      ["cell membrane", "cell wall", "nucleus", "cytoplasm"], "cell membrane",
      "The fluid mosaic model describes the cell membrane as a dynamic bilayer of phospholipids with embedded, freely moving proteins."),
  _q("Which of the following is true of a red blood cell placed in distilled water?",
      ["It swells and may burst due to water entering by osmosis", "It shrinks due to water leaving by osmosis", "It remains completely unchanged", "It immediately divides by mitosis"], "It swells and may burst due to water entering by osmosis",
      "Distilled water is hypotonic to the cell contents, so water enters the red blood cell by osmosis, causing it to swell and potentially haemolyse."),
  _q("Meiosis is significant in sexually reproducing organisms mainly because it",
      ["halves the chromosome number and introduces genetic variation", "doubles the chromosome number in gametes", "produces cells identical to the parent cell", "occurs only in somatic tissues"], "halves the chromosome number and introduces genetic variation",
      "Meiosis produces haploid gametes and, through crossing over and independent assortment, generates genetic variation among offspring."),
  _q("Which pigment, found in chloroplasts, is primarily responsible for absorbing light energy for photosynthesis?",
      ["Chlorophyll", "Haemoglobin", "Melanin", "Carotene"], "Chlorophyll",
      "Chlorophyll absorbs light energy, mainly in the red and blue regions of the spectrum, driving the light-dependent reactions of photosynthesis."),
  _q("The cell wall of a typical plant cell is composed mainly of",
      ["cellulose", "chitin", "peptidoglycan", "keratin"], "cellulose",
      "Plant cell walls are composed mainly of cellulose, a structural polysaccharide that provides rigidity and support."),
  _q("Which of the following best describes osmotic pressure in relation to plant cells?",
      ["It is the pressure that must be applied to prevent net water entry into the cell", "It is the force exerted by the cell wall against the protoplast", "It is the pressure exerted by dissolved gases only", "It only occurs in dead plant cells"], "It is the pressure that must be applied to prevent net water entry into the cell",
      "Osmotic pressure is the pressure required to stop the net movement of water into a solution by osmosis."),
  _q("Which of the following statements about nucleic acids is correct?",
      ["DNA contains deoxyribose sugar while RNA contains ribose sugar", "DNA is single stranded while RNA is double stranded", "Both DNA and RNA contain thymine", "DNA is found only in the cytoplasm"], "DNA contains deoxyribose sugar while RNA contains ribose sugar",
      "DNA's sugar component is deoxyribose, while RNA contains ribose; DNA is typically double stranded and RNA single stranded."),
  _q("Which type of tissue in flowering plants is primarily responsible for the transport of water and mineral salts?",
      ["Xylem", "Phloem", "Epidermis", "Cambium"], "Xylem",
      "Xylem vessels and tracheids conduct water and dissolved mineral salts upward from the roots to the rest of the plant."),
];

final _formAndFunctions = [
  _q("In humans, the exchange of gases occurs across the walls of the",
      ["alveoli", "trachea", "bronchi", "larynx"], "alveoli",
      "Alveoli are thin-walled, richly capillarised air sacs that provide a large surface area for the diffusion of oxygen and carbon dioxide."),
  _q("Which blood vessel carries deoxygenated blood from the heart to the lungs?",
      ["Pulmonary artery", "Pulmonary vein", "Aorta", "Vena cava"], "Pulmonary artery",
      "The pulmonary artery is unusual among arteries in carrying deoxygenated blood, from the right ventricle to the lungs for oxygenation."),
  _q("The chamber of the human heart with the thickest muscular wall is the",
      ["left ventricle", "right ventricle", "left atrium", "right atrium"], "left ventricle",
      "The left ventricle must pump blood at high pressure around the entire body, so its wall is the thickest of the four chambers."),
  _q("Which enzyme, secreted in saliva, begins the digestion of starch in the mouth?",
      ["Salivary amylase", "Pepsin", "Trypsin", "Lipase"], "Salivary amylase",
      "Salivary amylase (ptyalin) hydrolyses starch into maltose, initiating carbohydrate digestion in the mouth."),
  _q("The organ primarily responsible for the deamination of excess amino acids in humans is the",
      ["liver", "kidney", "pancreas", "spleen"], "liver",
      "The liver deaminates excess amino acids, converting the amino group into urea, which is then excreted by the kidneys."),
  _q("The functional and structural unit of the kidney responsible for filtration is the",
      ["nephron", "ureter", "medulla", "cortex"], "nephron",
      "Each nephron consists of a glomerulus and renal tubule that together filter blood and process the filtrate into urine."),
  _q("Which of the following best describes the process of ultrafiltration in the kidney?",
      ["High pressure forces small molecules from the blood into the Bowman's capsule", "Water is reabsorbed into the blood at the loop of Henle only", "Urea is actively secreted into the glomerulus", "Glucose is filtered out and never reabsorbed"], "High pressure forces small molecules from the blood into the Bowman's capsule",
      "In the glomerulus, high hydrostatic pressure forces water and small solutes out of the blood into the Bowman's capsule, forming the glomerular filtrate."),
  _q("The main respiratory pigment found in human red blood cells is",
      ["haemoglobin", "chlorophyll", "myoglobin only", "melanin"], "haemoglobin",
      "Haemoglobin, an iron-containing protein in red blood cells, binds oxygen in the lungs and releases it to respiring tissues."),
  _q("Peristalsis in the alimentary canal refers to",
      ["wave-like muscular contractions that push food along the gut", "the chemical breakdown of food by enzymes", "the absorption of digested food into the blood", "the storage of bile in the gall bladder"], "wave-like muscular contractions that push food along the gut",
      "Peristalsis is the rhythmic, wave-like contraction and relaxation of gut muscles that propels food along the alimentary canal."),
  _q("Which hormone, secreted by the pancreas, lowers blood glucose level by promoting its uptake and storage as glycogen?",
      ["Insulin", "Glucagon", "Adrenaline", "Thyroxine"], "Insulin",
      "Insulin stimulates cells, particularly liver and muscle cells, to absorb glucose and convert it into glycogen, lowering blood glucose."),
  _q("The skeletal joint that allows movement in only one plane, as seen at the elbow, is a",
      ["hinge joint", "ball-and-socket joint", "pivot joint", "gliding joint"], "hinge joint",
      "A hinge joint, like the elbow and knee, permits movement in a single plane, similar to the motion of a door hinge."),
  _q("Which of the following is the correct pathway of a nerve impulse in a simple reflex arc?",
      ["Receptor, sensory neurone, relay neurone, motor neurone, effector", "Effector, motor neurone, relay neurone, sensory neurone, receptor", "Receptor, motor neurone, relay neurone, sensory neurone, effector", "Sensory neurone, receptor, effector, motor neurone"], "Receptor, sensory neurone, relay neurone, motor neurone, effector",
      "A typical reflex arc transmits impulses from a receptor through a sensory neurone, a relay neurone in the spinal cord, then a motor neurone to an effector."),
  _q("The part of the human brain primarily responsible for coordinating balance and muscular movement is the",
      ["cerebellum", "cerebrum", "medulla oblongata", "hypothalamus"], "cerebellum",
      "The cerebellum coordinates fine motor movement, posture and balance."),
  _q("Which structure in the leaf regulates the rate of transpiration by controlling the opening and closing of pores?",
      ["Guard cells", "Palisade cells", "Xylem vessels", "Root hair cells"], "Guard cells",
      "Guard cells surround the stomatal pore and change shape to open or close it, thereby regulating gaseous exchange and water loss."),
  _q("The process by which plants lose water vapour mainly through their stomata is known as",
      ["transpiration", "translocation", "guttation", "respiration"], "transpiration",
      "Transpiration is the loss of water vapour from aerial plant parts, chiefly through open stomata on leaves."),
  _q("Homeostasis in mammals refers to the",
      ["maintenance of a stable internal environment despite external changes", "continuous growth of body tissues", "process of producing offspring", "breakdown of glucose to release energy"], "maintenance of a stable internal environment despite external changes",
      "Homeostasis describes the physiological mechanisms that keep internal conditions such as temperature, pH and water balance relatively constant."),
  _q("Which of the following best describes the role of the loop of Henle in the nephron?",
      ["It creates a concentration gradient that enables water reabsorption and urine concentration", "It filters blood plasma into the Bowman's capsule", "It secretes hormones that regulate blood pressure", "It stores urine before it passes to the bladder"], "It creates a concentration gradient that enables water reabsorption and urine concentration",
      "The loop of Henle sets up an osmotic gradient in the medulla through the countercurrent multiplier mechanism, allowing the collecting duct to reabsorb water and concentrate urine."),
  _q("Vasoconstriction of skin blood vessels in response to cold conditions helps the body to",
      ["conserve heat by reducing blood flow near the skin surface", "increase heat loss through the skin", "lower the metabolic rate permanently", "increase sweat gland activity"], "conserve heat by reducing blood flow near the skin surface",
      "Vasoconstriction narrows skin capillaries, reducing blood flow to the surface and minimising heat loss to conserve body heat."),
  _q("The exchange surfaces of the lungs, gills and small intestine share which common structural feature that improves efficiency?",
      ["A large surface area relative to volume", "A thick, impermeable lining", "Very few blood capillaries", "An extremely low surface area"], "A large surface area relative to volume",
      "Efficient exchange surfaces are characterised by a large surface area, thin walls and good blood supply, which together speed diffusion."),
  _q("Which of the following gases diffuses out of the blood into the alveoli to be exhaled?",
      ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"], "Carbon dioxide",
      "Carbon dioxide, a waste product of respiration, diffuses from the blood, which has a higher concentration of it, into the alveolar air to be exhaled."),
  _q("The role of bile, produced by the liver, in digestion is mainly to",
      ["emulsify fats into smaller droplets for enzyme action", "digest proteins into amino acids", "digest starch into simple sugars", "neutralise excess alkalinity in the duodenum"], "emulsify fats into smaller droplets for enzyme action",
      "Bile emulsifies large fat globules into smaller droplets, increasing the surface area available for lipase to act on."),
  _q("Which structure in a woody plant stem is responsible for secondary growth in girth?",
      ["Vascular cambium", "Epidermis", "Pith", "Cortex"], "Vascular cambium",
      "The vascular cambium is a lateral meristem that produces new xylem and phloem cells, increasing the diameter of the stem."),
];

final _reproduction = [
  _q("In flowering plants, the transfer of pollen grains from the anther to the stigma of the same flower is called",
      ["self-pollination", "cross-pollination", "fertilisation", "germination"], "self-pollination",
      "Self-pollination occurs when pollen from the anther lands on the stigma of the same flower or another flower on the same plant."),
  _q("Which structure in the flower develops into the fruit after fertilisation?",
      ["Ovary", "Ovule", "Petal", "Stigma"], "Ovary",
      "After fertilisation, the ovary wall develops into the fruit wall (pericarp), while the ovules become seeds."),
  _q("Double fertilisation, a process unique to flowering plants, results in the formation of the",
      ["zygote and the endosperm", "pollen tube and the stigma", "petal and the sepal", "anther and the filament"], "zygote and the endosperm",
      "In double fertilisation, one male gamete fuses with the egg to form a diploid zygote, while the other fuses with the polar nuclei to form the triploid endosperm."),
  _q("In the human male reproductive system, sperm cells are produced in the",
      ["seminiferous tubules of the testes", "epididymis", "vas deferens", "prostate gland"], "seminiferous tubules of the testes",
      "Spermatogenesis, the production of sperm, occurs within the seminiferous tubules found in the testes."),
  _q("Fertilisation in humans normally occurs in the",
      ["oviduct (fallopian tube)", "uterus", "vagina", "ovary"], "oviduct (fallopian tube)",
      "The sperm typically meets and fertilises the ovum within the fallopian tube, after which the zygote travels to the uterus for implantation."),
  _q("Which hormone is primarily responsible for maintaining the uterine lining during early pregnancy?",
      ["Progesterone", "Oestrogen", "Follicle-stimulating hormone", "Luteinising hormone"], "Progesterone",
      "Progesterone, secreted first by the corpus luteum and later by the placenta, maintains the endometrium, supporting the pregnancy."),
  _q("Vegetative propagation in plants is a form of",
      ["asexual reproduction", "sexual reproduction", "cross-pollination", "external fertilisation"], "asexual reproduction",
      "Vegetative propagation produces new plants from vegetative parts such as stems, roots or leaves without the fusion of gametes, making it asexual."),
  _q("Which of the following is an adaptation of wind-pollinated flowers?",
      ["Small, dull petals and large amounts of light, powdery pollen", "Large, brightly coloured petals and scent", "Nectar guides and sticky pollen", "Enclosed anthers within the flower"], "Small, dull petals and large amounts of light, powdery pollen",
      "Wind-pollinated flowers typically have small, inconspicuous petals, feathery stigmas, and produce large quantities of light pollen suited for wind dispersal."),
  _q("In humans, the process by which a fertilised egg becomes embedded in the uterine wall is called",
      ["implantation", "ovulation", "menstruation", "gestation"], "implantation",
      "Implantation is the process by which the blastocyst attaches to and embeds itself into the endometrium of the uterus."),
  _q("Metamorphosis in insects such as the housefly, which passes through egg, larva, pupa and adult stages, is described as",
      ["complete metamorphosis", "incomplete metamorphosis", "direct development", "asexual development"], "complete metamorphosis",
      "Complete metamorphosis involves four distinct stages (egg, larva, pupa, adult), with the pupa undergoing a radical transformation, as seen in flies and butterflies."),
  _q("Which of the following best describes external fertilisation, as seen in most fish and amphibians?",
      ["Fusion of gametes occurs outside the body of the female, usually in water", "Fusion of gametes occurs inside the female's reproductive tract", "Only asexual budding occurs", "Fertilisation occurs within a shelled egg outside water"], "Fusion of gametes occurs outside the body of the female, usually in water",
      "In external fertilisation, males and females release gametes into the surrounding water, where fusion of sperm and egg occurs outside the body."),
  _q("The placenta in mammals primarily functions to",
      ["allow exchange of nutrients, gases and waste between mother and foetus", "produce milk for the newborn", "store the developing foetus permanently", "produce eggs for fertilisation"], "allow exchange of nutrients, gases and waste between mother and foetus",
      "The placenta is a specialised organ that allows diffusion of oxygen, nutrients and waste products between the maternal and foetal blood supplies without them mixing directly."),
  _q("Which of the following floral parts produces pollen grains?",
      ["Anther", "Stigma", "Ovary", "Style"], "Anther",
      "The anther, borne at the tip of the stamen filament, contains pollen sacs in which pollen grains (male gametophytes) are produced."),
  _q("In the menstrual cycle, ovulation is triggered mainly by a surge in",
      ["luteinising hormone", "progesterone", "oestrogen only", "follicle-stimulating hormone alone"], "luteinising hormone",
      "A sharp surge in luteinising hormone (LH) midway through the cycle triggers the rupture of the mature follicle and release of the egg."),
  _q("Which of these is an example of asexual reproduction in simple organisms?",
      ["Binary fission in Amoeba", "Cross-pollination in maize", "Copulation in earthworms", "Metamorphosis in frogs"], "Binary fission in Amoeba",
      "Binary fission, where a single parent cell divides into two identical daughter cells, is a common form of asexual reproduction in unicellular organisms like Amoeba."),
];

final _genetics = [
  _q("A cross between two heterozygous tall pea plants (Tt x Tt), where tallness is dominant, is expected to produce offspring in the phenotypic ratio",
      ["3 tall : 1 short", "1 tall : 1 short", "1 tall : 2 short : 1 tall", "9 tall : 7 short"], "3 tall : 1 short",
      "A monohybrid cross between two heterozygotes (Tt x Tt) produces a genotypic ratio of 1TT:2Tt:1tt, giving a phenotypic ratio of 3 dominant : 1 recessive."),
  _q("An individual with two different alleles for a particular gene, such as Aa, is said to be",
      ["heterozygous", "homozygous dominant", "homozygous recessive", "hemizygous"], "heterozygous",
      "An organism carrying two different alleles for a gene (one dominant, one recessive) is described as heterozygous for that trait."),
  _q("Which of the following is the physical, observable expression of an organism's genetic makeup?",
      ["Phenotype", "Genotype", "Allele", "Locus"], "Phenotype",
      "Phenotype refers to the observable characteristics of an organism, resulting from the interaction of its genotype with the environment."),
  _q("In humans, colour blindness is a sex-linked recessive trait carried on the X chromosome. A colour-blind man marries a woman who is homozygous normal. What proportion of their sons will be colour blind?",
      ["None, since sons receive their X chromosome from the mother", "All of the sons", "Half of the sons", "A quarter of the sons"], "None, since sons receive their X chromosome from the mother",
      "Sons inherit their single X chromosome from their mother; since she is homozygous normal, all sons will receive a normal allele and will not be colour blind."),
  _q("Gregor Mendel's Law of Segregation states that",
      ["the two alleles for a gene separate during gamete formation, so each gamete carries only one allele", "genes for different traits always assort independently of each other", "dominant alleles always mask recessive alleles completely in all cases", "offspring always resemble one parent exactly"], "the two alleles for a gene separate during gamete formation, so each gamete carries only one allele",
      "Mendel's Law of Segregation states that allele pairs separate during gamete formation, so each gamete receives only one allele from each pair."),
  _q("A change in the nucleotide sequence of DNA, which may alter an organism's phenotype, is called a",
      ["mutation", "translation", "transcription", "replication"], "mutation",
      "A mutation is any change in the base sequence of DNA, which can arise spontaneously or be induced by mutagens, sometimes altering the phenotype."),
  _q("Down syndrome in humans is caused by",
      ["the presence of an extra copy of chromosome 21", "a deletion of part of the X chromosome", "a point mutation in a single gene", "the loss of an entire autosome"], "the presence of an extra copy of chromosome 21",
      "Down syndrome results from trisomy 21, a chromosomal abnormality where an individual has three copies of chromosome 21 instead of two."),
  _q("In a dihybrid cross between two heterozygous individuals (AaBb x AaBb), assuming independent assortment, the expected phenotypic ratio of the offspring is",
      ["9:3:3:1", "3:1", "1:2:1", "1:1:1:1"], "9:3:3:1",
      "A dihybrid cross between two double heterozygotes produces four phenotype classes in the ratio 9:3:3:1 when the genes assort independently."),
  _q("The complete set of hereditary information carried by an organism is referred to as its",
      ["genome", "phenotype", "karyotype only", "proteome"], "genome",
      "The genome is the entire set of genetic material, including all genes, present in an organism."),
  _q("Which of the following best explains why identical (monozygotic) twins have the same genotype?",
      ["They develop from a single fertilised egg that splits into two embryos", "They develop from two separately fertilised eggs", "They share the same placenta but different genomes", "They result from the fusion of two sperm cells"], "They develop from a single fertilised egg that splits into two embryos",
      "Monozygotic twins arise when a single zygote splits early in development into two embryos, so both twins share identical genetic material."),
  _q("A test cross is performed by crossing an individual of unknown genotype with an individual that is",
      ["homozygous recessive for the trait", "homozygous dominant for the trait", "heterozygous for the trait", "of unknown genotype as well"], "homozygous recessive for the trait",
      "A test cross uses a homozygous recessive individual because the resulting offspring's phenotypes directly reveal whether the tested organism is homozygous or heterozygous dominant."),
  _q("Which of the following is an example of incomplete dominance?",
      ["A cross between red and white snapdragons producing pink offspring", "A cross between tall and short pea plants producing all tall offspring", "A cross producing offspring identical to only one parent", "A cross where the recessive trait is never expressed"], "A cross between red and white snapdragons producing pink offspring",
      "In incomplete dominance, the heterozygote shows an intermediate phenotype, as seen when red and white snapdragons produce pink-flowered offspring."),
  _q("The structural unit of a chromosome that carries the code for a specific protein or trait is called a",
      ["gene", "chromatid", "centromere", "nucleosome"], "gene",
      "A gene is a discrete segment of DNA on a chromosome that codes for a specific protein or functional RNA product, determining a trait."),
];

final _ecology = [
  _q("Within a food chain, organisms that manufacture their own food using sunlight are known as",
      ["producers", "primary consumers", "decomposers", "secondary consumers"], "producers",
      "Producers, mainly green plants and algae, are autotrophs that convert light energy into chemical energy through photosynthesis, forming the base of most food chains."),
  _q("The role of decomposers such as bacteria and fungi in an ecosystem is mainly to",
      ["break down dead organic matter and release nutrients back into the environment", "manufacture food using sunlight", "consume living producers directly", "convert atmospheric nitrogen into ammonia only"], "break down dead organic matter and release nutrients back into the environment",
      "Decomposers break down dead organisms and waste, releasing locked-up nutrients such as carbon and nitrogen compounds back into the ecosystem for reuse."),
  _q("In an ecological pyramid of numbers, energy is progressively lost between trophic levels mainly through",
      ["respiration and heat loss", "photosynthesis", "decomposition of producers only", "excretion of undigested food alone"], "respiration and heat loss",
      "At each trophic level, a large proportion of energy is lost as heat through respiration and other metabolic activities, explaining the pyramid shape of energy flow."),
  _q("A community of interacting organisms together with their non-living physical environment is called a(n)",
      ["ecosystem", "population", "habitat", "biome"], "ecosystem",
      "An ecosystem comprises the biotic community of organisms and the abiotic factors (soil, water, climate) with which they interact."),
  _q("Which of the following best defines a population in ecological terms?",
      ["A group of organisms of the same species living in a given area at the same time", "All the living and non-living things in an area", "A group of different species living together", "The physical area where an organism lives"], "A group of organisms of the same species living in a given area at the same time",
      "A population consists of individuals of one species occupying a particular area at a given time, capable of interbreeding."),
  _q("The process by which atmospheric nitrogen is converted into a form usable by plants, largely through the action of soil bacteria, is called",
      ["nitrogen fixation", "denitrification", "nitrification only", "ammonification only"], "nitrogen fixation",
      "Nitrogen fixation converts inert atmospheric nitrogen gas into ammonia or related compounds that plants can absorb and use, carried out by bacteria such as Rhizobium."),
  _q("Which relationship describes an association where one organism benefits and the other is unaffected?",
      ["Commensalism", "Mutualism", "Parasitism", "Competition"], "Commensalism",
      "In commensalism, one species benefits from the association while the other neither benefits nor is harmed."),
  _q("The relationship between a tapeworm and the human host it lives in is best described as",
      ["parasitism", "mutualism", "commensalism", "competition"], "parasitism",
      "A tapeworm benefits by obtaining nutrients from its host while harming the host, which is the defining feature of parasitism."),
  _q("Which of the following is an example of a biotic factor affecting an ecosystem?",
      ["Predation by carnivores", "Rainfall amount", "Soil pH", "Temperature"], "Predation by carnivores",
      "Biotic factors are living components of the environment, such as predation, competition and disease, as opposed to abiotic factors like rainfall and temperature."),
  _q("The continuous cycling of carbon between the atmosphere, living organisms and the environment mainly involves the processes of",
      ["photosynthesis and respiration", "nitrogen fixation and denitrification only", "transpiration and osmosis", "excretion and egestion"], "photosynthesis and respiration",
      "Photosynthesis removes carbon dioxide from the atmosphere to build organic compounds, while respiration and combustion return carbon dioxide to the atmosphere, driving the carbon cycle."),
  _q("Which of the following practices most directly contributes to soil erosion?",
      ["Deforestation and removal of vegetation cover", "Crop rotation", "Contour ploughing", "Afforestation"], "Deforestation and removal of vegetation cover",
      "Removing vegetation exposes the soil surface to wind and water, greatly increasing the rate of soil erosion, unlike practices such as afforestation that protect the soil."),
  _q("Two species that require the same limited resource, such as food or space, within a habitat are said to be in",
      ["competition", "mutualism", "commensalism", "parasitism"], "competition",
      "Competition occurs when two or more organisms or species vie for the same limited resource, potentially reducing the fitness of both."),
  _q("In a typical grassland food chain: grass, grasshopper, frog, snake, hawk; the snake occupies which trophic level?",
      ["Tertiary consumer", "Primary consumer", "Secondary consumer", "Producer"], "Tertiary consumer",
      "Counting grass as producer, grasshopper as primary consumer, frog as secondary consumer, the snake that eats the frog is the tertiary consumer."),
  _q("Which gas, released mainly from burning fossil fuels, is most closely associated with the enhanced greenhouse effect and global warming?",
      ["Carbon dioxide", "Nitrogen", "Oxygen", "Helium"], "Carbon dioxide",
      "Carbon dioxide is a major greenhouse gas whose atmospheric concentration has risen sharply due to fossil fuel combustion, contributing to global warming."),
  _q("An area's carrying capacity refers to",
      ["the maximum population size an environment can sustainably support", "the total number of species present", "the rate at which a population grows without limit", "the minimum number of predators needed"], "the maximum population size an environment can sustainably support",
      "Carrying capacity is the largest population size that a given environment can sustain indefinitely given its available resources."),
];

final _evolution = [
  _q("Charles Darwin's theory of evolution is primarily based on the mechanism of",
      ["natural selection", "use and disuse of organs", "inheritance of acquired characteristics", "special creation"], "natural selection",
      "Darwin proposed that organisms with favourable variations are more likely to survive and reproduce, passing those traits to offspring, a process called natural selection."),
  _q("Which scientist proposed the theory of inheritance of acquired characteristics, later shown to be largely incorrect?",
      ["Jean-Baptiste Lamarck", "Charles Darwin", "Gregor Mendel", "Alfred Wallace"], "Jean-Baptiste Lamarck",
      "Lamarck proposed that traits acquired during an organism's lifetime, such as a giraffe stretching its neck, could be passed to offspring, a theory not supported by modern genetics."),
  _q("Structures such as the forelimbs of a human, whale and bat, which have a similar basic bone structure but different functions, are described as",
      ["homologous structures", "analogous structures", "vestigial structures", "convergent structures"], "homologous structures",
      "Homologous structures share a common underlying structure inherited from a shared ancestor, even though they may serve different functions, providing evidence for evolution."),
  _q("Body structures that are reduced and no longer serve their original function, such as the human appendix, are termed",
      ["vestigial structures", "homologous structures", "analogous structures", "adaptive structures"], "vestigial structures",
      "Vestigial structures are remnants of organs that were functional in ancestral species but have become reduced or non-functional over evolutionary time."),
  _q("The peppered moth (Biston betularia) population shift from light to dark forms during the industrial revolution in England is a classic example of",
      ["natural selection in response to environmental change", "genetic drift alone", "artificial selection by breeders", "mutation with no adaptive advantage"], "natural selection in response to environmental change",
      "As pollution darkened tree bark, dark moths were better camouflaged from predators than light moths, so natural selection favoured the dark form, shifting the population's frequency."),
  _q("Which of the following provides direct evidence of evolutionary change preserved in rock strata?",
      ["Fossils", "Vestigial organs", "Homologous structures", "DNA hybridisation alone"], "Fossils",
      "Fossils are the preserved remains or traces of ancient organisms found in sedimentary rock layers, providing a direct historical record of evolutionary change over time."),
  _q("The process by which two unrelated species evolve similar structures independently due to similar environmental pressures is called",
      ["convergent evolution", "divergent evolution", "co-evolution", "adaptive radiation"], "convergent evolution",
      "Convergent evolution occurs when unrelated organisms independently evolve analogous structures, such as the wings of birds and insects, due to similar selective pressures."),
  _q("Analogous structures, such as the wings of a bird and the wings of a butterfly, are similar in function but",
      ["differ in evolutionary origin and basic structure", "share an identical evolutionary origin", "always have identical bone arrangements", "are found only in closely related species"], "differ in evolutionary origin and basic structure",
      "Analogous structures perform similar functions but evolved independently in unrelated lineages, so they differ in their underlying structure and evolutionary origin."),
  _q("According to modern evolutionary theory, new alleles that introduce genetic variation into a population primarily arise through",
      ["mutation", "natural selection directly", "the survival of the fittest alone", "loss of habitat"], "mutation",
      "Mutation is the ultimate source of new genetic variation, upon which natural selection and other evolutionary forces can then act."),
  _q("The formation of a new species from an ancestral population that becomes geographically isolated is known as",
      ["allopatric speciation", "sympatric speciation", "convergent speciation", "artificial speciation"], "allopatric speciation",
      "Allopatric speciation occurs when populations of a species are separated by a geographic barrier, evolve independently, and eventually become reproductively isolated as distinct species."),
  _q("Adaptive radiation, as seen in Darwin's finches on the Galapagos Islands, refers to",
      ["the diversification of a single ancestral species into many species occupying different niches", "the extinction of a species due to competition", "the merging of two species into one", "the mutation of a gene with no ecological effect"], "the diversification of a single ancestral species into many species occupying different niches",
      "Adaptive radiation describes the rapid evolution of many species from a single ancestor as they adapt to fill different available ecological niches, as seen in the varied beak shapes of Darwin's finches."),
  _q("Which of the following best describes 'survival of the fittest' as used in evolutionary biology?",
      ["Organisms best suited to their environment are more likely to survive and reproduce", "Only the physically strongest organisms in a population survive", "All organisms in a population have an equal chance of survival", "Fitness refers only to an organism's physical strength"], "Organisms best suited to their environment are more likely to survive and reproduce",
      "In evolutionary terms, 'fitness' refers to reproductive success; organisms whose traits are best suited to their environment tend to survive and pass on their genes more successfully."),
];
