import "../quiz_question.dart";

const _subject = "Igbo";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// University of Ibadan (UI) Post-UTME elective subject bank — Igbo.
/// 100 medium-to-hard questions spanning Ụdaasụsụ na Usoro (phonetics and
/// phonology), Njirimara na Mkpụrụokwu (orthography and vocabulary),
/// Ụtọasụsụ (grammar), Aghọtaazaa na Edemede (comprehension and essay),
/// Agụmagụ Ọnụ (oral literature — weighted higher: proverbs, folktales,
/// culture), Agụmagụ Edere Ede (written literature, kept at a general/
/// author level only), Omenala na Ewumewu (customs and institutions), and
/// Ihe Ngwa nke Ugbu a (current affairs). Content favours well-established
/// facts to keep accuracy risk low; questions and options are in Igbo,
/// with explanations in English.
List<QuizQuestion> buildUiIgboQuestions() {
  return [
    ..._udaasusuNaUsoro,
    ..._njirimaraNaMkpuruokwu,
    ..._utoasusu,
    ..._aghotaazaaNaEdemede,
    ..._agumaguOnu,
    ..._agumaguEdereEde,
    ..._omenalaNaEwumewu,
    ..._iheNgwaNkeUgbuA,
  ];
}

final _udaasusuNaUsoro = [
  _q("Kedu ụdaume so n'otu ndakọrịta ụdaume (vowel harmony set) na 'i'?",
      ["ị", "a", "o", "ọ"], "ị",
      "In Igbo vowel harmony, vowels group into two sets by tongue root position; 'i' pairs with 'ị' in usage patterns learners must distinguish."),
  _q("Olee ihe kpatara akara olu (tone marks) ji dị mkpa n'ederede Igbo?",
      ["N'ihi na olu dị iche iche nwere ike ime ka otu mkpụrụedemede pụta ihe abụọ ma ọ bụ karịa", "N'ihi na ha na-eme ka akwụkwọ dị mma ile anya naanị", "N'ihi na ha bụ mkpụrụedemede", "N'ihi na ha na-egosi ọnụọgụ"], "N'ihi na olu dị iche iche nwere ike ime ka otu mkpụrụedemede pụta ihe abụọ ma ọ bụ karịa",
      "Tone is contrastive in Igbo, meaning the same sequence of letters can carry different meanings depending on the tone pattern, which is why tone marks matter."),
  _q("Kedu okwu Igbo abụọ a na-esi n'olu ha mata ọdịiche n'ihe ha pụtara, ọ bụ ezie na e dere ha otu ụzọ n'edemede na-enweghị akara olu?",
      ["Akwụ (palm nut) na akwụ (bed)", "Ụlọ na aka", "Mmiri na anụ", "Egwu na ọzọ"], "Akwụ (palm nut) na akwụ (bed)",
      "'Akwụ' is a classic Igbo example of tonal minimal pairs, where identical spelling without tone marks can represent distinct words such as palm nut and bed, depending on tone."),
  _q("Kedu ụdị mgbochiume (consonant) a na-akpọ 'gb' n'ụtọasụsụ ụdaasụsụ Igbo?",
      ["Mgbochiume abụọ jikọrọ ọnụ (digraph) na-egosipụta otu ụda", "Ụdaume nkeji", "Akara olu", "Njikọ okwu"], "Mgbochiume abụọ jikọrọ ọnụ (digraph) na-egosipụta otu ụda",
      "'Gb', like 'gh', 'kp', 'nw' and 'ny', is a digraph in the Igbo alphabet — two letters representing a single distinct consonant sound."),
  _q("Kedu ihe a na-akpọ mgbanwe ụda mkpụrụokwu na-eme mgbe mkpụrụokwu abụọ zutere n'ọnụ n'ekwuwa okwu (elision/assimilation)?",
      ["Mmegharị ụda", "Nchịkọta okwu", "Akara nkwụsi", "Nnochi aha"], "Mmegharị ụda",
      "Assimilation and elision describe how adjoining sounds influence and sometimes merge with each other in fluent Igbo speech."),
  _q("Olu ole bụ isi ka ọ bara n'usoro olu Igbo, ewezuga olu agbadaba (downstep)?",
      ["Abụọ: olu elu na olu ala", "Naanị otu", "Anọ kpamkpam", "Iri"], "Abụọ: olu elu na olu ala",
      "Igbo tone is fundamentally binary: high and low, with downstep recognised as a derived variant of high tone rather than a fully separate basic tone."),
  _q("Kedu ihe a na-akpọ mgbochiume nsi-imi na-eguzo n'ọnọdụ ụdaume n'okwu dịka 'nne'?",
      ["Mgbochiume mkpụrụedemede (syllabic consonant)", "Ụdaume ochie", "Akara olu", "Mbuuzo"], "Mgbochiume mkpụrụedemede (syllabic consonant)",
      "Nasal consonants like 'n' and 'm' can serve as the nucleus of a syllable in Igbo, standing in for a vowel."),
  _q("N'asụsụ Igbo, olee otu e si ekwu okwu 'akwa' iji pụta 'cloth' karịa 'egg' ma e dee ya n'enweghị akara olu?",
      ["E ji olu (tone) dị iche iche kpọọ ya", "E ji ọnụọgụ mkpụrụedemede dị iche iche dee ya", "E ji mgbochiume dị iche iche dee ya", "Ọ dịghị ụzọ e si ama ọdịiche ha"], "E ji olu (tone) dị iche iche kpọọ ya",
      "'Akwa' is another commonly cited Igbo tonal minimal-pair word: identical spelling but distinct meanings (egg, cloth, cry, bridge) distinguished by tone alone."),
  _q("Kedu ihe a na-akpọ akụkụ ụdaasụsụ na-elebara anya n'otu e si esite n'ọnụ mmadụ mepụta ụda?",
      ["Ụdaasụsụ (phonetics)", "Ụtọasụsụ", "Agụmagụ", "Ọdịnala"], "Ụdaasụsụ (phonetics)",
      "Phonetics (ụdaasụsụ) is the branch of study focused on how speech sounds are physically produced, transmitted, and perceived."),
  _q("Kedu nkọwa kacha zie ezi maka mkpụrụedemede mmechi (closed syllable) n'asụsụ Igbo?",
      ["Mkpụrụedemede na-akwụsị na mgbochiume", "Mkpụrụedemede na-akwụsị na ụdaume mgbe niile", "Mkpụrụedemede na-enweghị mgbochiume ọ bụla", "Mkpụrụedemede nwere naanị akara olu"], "Mkpụrụedemede na-akwụsị na mgbochiume",
      "A closed syllable ends in a consonant sound, in contrast with the open (CV) syllable pattern that dominates ordinary Igbo words."),
  _q("Kedu ihe a na-akpọ usoro nyocha ụda okwu iji chọpụta ụda dị iche iche pụrụ iche n'otu asụsụ?",
      ["Usoro ụdaasụsụ (phonology)", "Ụtọasụsụ", "Njirimara mkpụrụokwu", "Agụmagụ ọnụ"], "Usoro ụdaasụsụ (phonology)",
      "Phonology is the systematic study of how sounds pattern and function meaningfully within a specific language, distinct from the physical study of sounds (phonetics)."),
  _q("Kedu ihe kpatara ọtụtụ okwu Igbo nwere naanị otu ma ọ bụ mkpụrụedemede abụọ n'ọtụtụ ọnọdụ?",
      ["N'ihi na Igbo bụ asụsụ nwere mkpụrụedemede CV dị mfe na-emeghachi onwe ya", "N'ihi na Igbo enweghị ụdaume", "N'ihi na Igbo enweghị mgbochiume", "N'ihi na ọ bụ asụsụ ọhụrụ"], "N'ihi na Igbo bụ asụsụ nwere mkpụrụedemede CV dị mfe na-emeghachi onwe ya",
      "The prevalence of simple, repeating CV syllable structures is a well-known structural feature contributing to the relatively short average word length in Igbo."),
];

final _njirimaraNaMkpuruokwu = [
  _q("Kedu usoro mkpụrụedemede a na-eji ede Igbo izugbe taa?",
      ["Usoro Onwu", "Usoro Ndịmele", "Usoro Latịn nke oge ochie", "Usoro Lepsius kpamkpam"], "Usoro Onwu",
      "The Onwu orthography, adopted officially in 1961, remains the standard writing system used for modern standard Igbo."),
  _q("Kedu ihe a na-akpọ okwu abụọ e jikọtara ọnụ iji mepụta otu okwu ọhụrụ nwere ihe ọ pụtara, dịka 'ụlọ' na 'akwụkwọ' bụ 'ụlọakwụkwọ'?",
      ["Mkpụrụokwu jikọrọ ọnụ (compound word)", "Mkpụrụokwu e ji (loan word)", "Mgbakwunye okwu", "Akara olu"], "Mkpụrụokwu jikọrọ ọnụ (compound word)",
      "'Ụlọakwụkwọ' (school) exemplifies Igbo compounding, where two independent words combine to form a new word with a distinct meaning."),
  _q("Kedu ihe a na-akpọ mkpụrụokwu ndị dịka 'sukuu', 'motọ', na 'kọmputa' e webatara n'asụsụ Igbo?",
      ["Mkpụrụokwu e ji (loan words)", "Mkpụrụokwu jikọrọ ọnụ", "Mgbakwunye ihu", "Akara nkwụsi"], "Mkpụrụokwu e ji (loan words)",
      "Words like 'sukuu' (school), 'motọ' (motor) and 'kọmputa' (computer) are loan words absorbed into Igbo, mostly from English, and adapted to Igbo sound patterns."),
  _q("Kedu mgbakwunye a na-etinye n'ihu mkpụrụokwu iji gbanwee ma ọ bụ kwado ihe ọ pụtara (prefix)?",
      ["Mgbakwunye ihu (prefix)", "Mgbakwunye azụ (suffix)", "Njikọ okwu", "Nnochi aha"], "Mgbakwunye ihu (prefix)",
      "A prefix (mgbakwunye ihu) is attached to the beginning of a root word, one of the two main affix positions in Igbo morphology alongside the suffix."),
  _q("Site n'okwu mgbagwoju 'ọzụzụ', kedu mkpụrụokwu (root) a na-esi eleta ya?",
      ["Zụ", "Ọzụ", "Zụzụ", "Ụzụ"], "Zụ",
      "The verb root '-zụ-' (to train/rear) underlies derived and reduplicated forms such as 'ọzụzụ' (training/rearing) in Igbo morphology."),
  _q("Kedu ihe a na-akpọ okwu ọdịnaala dị iche na mpaghara Igbo dị iche iche na-akọwa otu ihe, dịka 'ji' na mpaghara ụfọdụ, ebe mpaghara ọzọ nwere aha ọzọ?",
      ["Mkpụrụokwu olumba (dialect word)", "Mkpụrụokwu e ji", "Mgbakwunye azụ", "Akara olu"], "Mkpụrụokwu olumba (dialect word)",
      "Igbo has many regional dialects, and dialect words reflect the natural variation in vocabulary used across different Igbo-speaking areas for the same concept."),
  _q("Olee ihe a na-eji akọwa 'mkpụrụokwu' n'ụzọ dị mfe n'asụsụ Igbo?",
      ["Otu mgbọrọgwụ okwu ma ọ bụ ngwakọta okwu nwere ihe ọ pụtara", "Naanị akara olu", "Naanị mkpụrụedemede otu", "Naanị njikọ okwu"], "Otu mgbọrọgwụ okwu ma ọ bụ ngwakọta okwu nwere ihe ọ pụtara",
      "A word (mkpụrụokwu) is a basic meaningful unit of language, whether a single root or a combination of morphemes."),
  _q("Kedu isi ihe kpatara e ji ahazi okwu Igbo n'akwụkwọ ọkọwa okwu (dictionary) n'usoro mkpụrụedemede?",
      ["Ka o mee ka ịchọta okwu dị mfe na ngwa ngwa", "Ka a hapụ akara olu niile", "Ka okwu niile dịrị otu ogologo", "Ka a kwụsị iji ụdaume"], "Ka o mee ka ịchọta okwu dị mfe na ngwa ngwa",
      "Alphabetical ordering in dictionaries makes it fast and predictable for users to locate any given word."),
  _q("Kedu ihe a na-akpọ okwu Igbo na-egosi otu ihe ma ọ bụ omume n'ụzọ dị nro, karịa nkọwa ozugbo (idiomatic expression)?",
      ["Akpaokwu (idiom)", "Ilu (proverb)", "Agwụgwa (riddle)", "Mbem"], "Akpaokwu (idiom)",
      "An idiom (akpaokwu) is a fixed expression whose figurative meaning differs from a literal, word-for-word reading, distinct from a proverb which usually carries a moral lesson."),
  _q("Kedu mkpụrụokwu a ga-eji dochie 'nnukwu' n'ahịrịokwu, ma ihe ọ pụtara ghara ịgbanwe nke ukwuu?",
      ["Ukwu", "Nta", "Ọma", "Ọjọọ"], "Ukwu",
      "'Ukwu' (as in 'ukwu ukwu' / large) functions as a near-synonym of 'nnukwu' (big/great) in describing size."),
  _q("Kedu ọdịiche dị n'etiti 'ilu' na 'akpaokwu' n'asụsụ Igbo?",
      ["Ilu na-ebukarị ozizi omume ma ọ bụ amamihe, ebe akpaokwu bụ naanị nkebiokwu nwere ihe ọ pụtara na-abụghị nke ozugbo", "Ha bụ otu ihe kpamkpam", "Akpaokwu bụ naanị maka ụmụaka", "Ilu adịghị enwe isi ihe"], "Ilu na-ebukarị ozizi omume ma ọ bụ amamihe, ebe akpaokwu bụ naanị nkebiokwu nwere ihe ọ pụtara na-abụghị nke ozugbo",
      "Proverbs (ilu) typically encode a moral lesson or wisdom, while idioms (akpaokwu) are fixed figurative phrases without necessarily carrying moral instruction."),
  _q("Kedu ihe a na-akpọ akwụkwọ e ji achọpụta ihe okwu Igbo pụtara na Bekee ma ọ bụ asụsụ ọzọ?",
      ["Akwụkwọ ọkọwa okwu (dictionary)", "Akwụkwọ akụkọ ifo", "Akwụkwọ ozi", "Akwụkwọ mbem"], "Akwụkwọ ọkọwa okwu (dictionary)",
      "A dictionary (akwụkwọ ọkọwa okwu) provides the meanings, and often translations, of words in a language."),
];

final _utoasusu = [
  _q("Kedu klaasị okwu (mkpọaha) so n'ime ndị a: 'nwoke', 'ụlọ', 'echiche'?",
      ["Ha niile bụ mkpọaha (nouns)", "Ha niile bụ ngwaa", "Ha niile bụ nkọwa", "Ha niile bụ njikọ okwu"], "Ha niile bụ mkpọaha (nouns)",
      "'Nwoke' (man), 'ụlọ' (house) and 'echiche' (thought/idea) are all nouns, naming a person, a place/thing, and an abstract idea respectively."),
  _q("N'ahịrịokwu 'Nwata ahụ na-agba ọsọ', kedu okwu bụ ngwaa (verb)?",
      ["Na-agba", "Nwata", "Ahụ", "Ọsọ"], "Na-agba",
      "'Na-agba' (is running) is the verb phrase expressing the ongoing action performed by the subject 'nwata ahụ'."),
  _q("Kedu klaasị okwu 'ọma' bụ n'ahịrịokwu 'nwanyị ọma ahụ bịara'?",
      ["Nkọwa (adjective)", "Ngwaa", "Nkwuwa", "Mbuuzo"], "Nkọwa (adjective)",
      "'Ọma' (good) describes the noun 'nwanyị' (woman), functioning as an adjective."),
  _q("Kedu ihe a na-akpọ okwu na-anọchi anya mkpọaha iji zere ịkwụghachi aha ahụ ugboro ugboro?",
      ["Nnochi aha (pronoun)", "Njikọ okwu", "Mbuuzo", "Nkwuwa"], "Nnochi aha (pronoun)",
      "A pronoun (nnochi aha), like 'ọ', 'ha', or 'anyị', substitutes for a noun to avoid repetition."),
  _q("N'ahịrịokwu 'O bikere n'elu oche', kedu klaasị okwu 'n'elu' bụ?",
      ["Mbuuzo (preposition)", "Ngwaa", "Njikọ okwu", "Nkọwa"], "Mbuuzo (preposition)",
      "'N'elu' (on top of) shows the spatial relationship between the subject and 'oche' (chair), making it a preposition."),
  _q("Kedu njikọ okwu a ga-eji jikọta ahịrịokwu abụọ ndị a: 'Ọ dara ụra ___ a kpọrọ ya oku'?",
      ["mana", "na", "ka", "ma ọ bụrụ"], "mana",
      "'Mana' (but) correctly links the contrasting clauses of falling asleep and being called, expressing contrast."),
  _q("Kedu ihe a na-akpọ ahịrịokwu na-ajụ ajụjụ, dịka 'Kedu ebe ị na-aga?'",
      ["Ahịrịokwu ajụjụ (interrogative sentence)", "Ahịrịokwu iwu", "Ahịrịokwu akụkọ", "Ahịrịokwu jikọrọ ọnụ"], "Ahịrịokwu ajụjụ (interrogative sentence)",
      "An interrogative sentence is used to ask a question, marked in Igbo by question words such as 'kedu' or a rising tone pattern."),
  _q("Kedu ụdị ahịrịokwu bụ 'Mechie ụzọ ahụ!'?",
      ["Ahịrịokwu iwu (imperative sentence)", "Ahịrịokwu ajụjụ", "Ahịrịokwu akụkọ", "Ahịrịokwu jikọrọ ọnụ"], "Ahịrịokwu iwu (imperative sentence)",
      "'Mechie ụzọ ahụ!' (Close the door!) issues a direct command, characteristic of an imperative sentence."),
  _q("N'ụtọasụsụ Igbo, kedu ọnọdụ mkpọaha na-anọ n'ahịrịokwu dị mfe dịka 'Chidi ___ akpụkpọụkwụ'?",
      ["Onye ọrụ (subject)", "Ihe a na-arụ ọrụ na ya (object)", "Njikọ okwu", "Mbuuzo"], "Onye ọrụ (subject)",
      "'Chidi' functions as the subject (onye ọrụ), the one performing the action, at the start of a typical Igbo SVO sentence."),
  _q("Kedu ihe a na-akpọ mgbanwe ngwaa iji gosipụta na omume ahụ emeela n'oge gara aga (past tense)?",
      ["Mgbanwe oge gara aga (past tense marking)", "Mgbanwe iwu", "Mgbanwe ajụjụ", "Mgbanwe nkọwa"], "Mgbanwe oge gara aga (past tense marking)",
      "Igbo verbs take tense/aspect markers to indicate when an action occurred, including markers used for completed past actions."),
  _q("Kedu ihe a na-akpọ nkebi ụtọasụsụ na-elebara anya n'usoro mkpụrụokwu si emepụta ọzọ (word formation)?",
      ["Nhazi okwu (morphology)", "Nhazi ahịrịokwu (syntax)", "Ụdaasụsụ", "Agụmagụ"], "Nhazi okwu (morphology)",
      "Morphology studies how words are formed and structured from smaller meaningful units such as roots and affixes."),
  _q("Kedu ihe a na-akpọ ahịrịokwu na-adaberekarị n'ahịrịokwu ọzọ iji zuo ezu (complex sentence)?",
      ["Ahịrịokwu mgbagwoju (complex sentence)", "Ahịrịokwu dị mfe", "Ahịrịokwu jikọrọ ọnụ", "Ahịrịokwu iwu"], "Ahịrịokwu mgbagwoju (complex sentence)",
      "A complex sentence contains a main clause and at least one dependent clause that relies on the main clause for full meaning."),
  _q("N'ahịrịokwu 'Ha na-eri nri', kedu okwu bụ ihe a na-arụ ọrụ na ya (object)?",
      ["Nri", "Ha", "Na-eri", "Ọ dịghị"], "Nri",
      "'Nri' (food) receives the action of eating, making it the object of the verb 'na-eri' (are eating)."),
  _q("Kedu ihe a na-akpọ mgbakwunye e tinyere n'azụ mkpụrụokwu iji gbanwee ọnọdụ ya (suffix)?",
      ["Mgbakwunye azụ (suffix)", "Mgbakwunye ihu (prefix)", "Njikọ okwu", "Nnochi aha"], "Mgbakwunye azụ (suffix)",
      "A suffix (mgbakwunye azụ) attaches to the end of a root word, one of the two principal affix positions in Igbo."),
];

final _aghotaazaaNaEdemede = [
  _q("N'ịgụta edemede iji ghọta ya (comprehension), gịnị bụ isi ihe a na-achọ n'aka onye na-agụ ya?",
      ["Ịghọta isi ozi na nkọwa dị n'edemede ma zaa ajụjụ ndị metụtara ya", "Ịgụ okwu niile n'isi", "Ịtụgharị ya gaa n'asụsụ ọzọ", "Ịmata naanị aha onye dere ya"], "Ịghọta isi ozi na nkọwa dị n'edemede ma zaa ajụjụ ndị metụtara ya",
      "The primary goal of comprehension practice is to understand a passage's content and details well enough to answer related questions accurately."),
  _q("Kedu ụdị edemede na-akọ ihe mere eme n'usoro (narrative essay)?",
      ["Edemede akụkọ (narrative essay)", "Edemede nkọwa", "Edemede ịrụ ụka", "Akwụkwọ ozi"], "Edemede akụkọ (narrative essay)",
      "A narrative essay recounts events in a sequence, typically with a beginning, middle, and end."),
  _q("Kedu ụdị edemede a na-eji akọwapụta onye, ebe, ma ọ bụ ihe n'ụzọ zuru ezu iji mee ka onye na-agụ ya hụ ya n'anya uche?",
      ["Edemede nkọwa (descriptive essay)", "Edemede akụkọ", "Edemede ịrụ ụka", "Akwụkwọ ozi"], "Edemede nkọwa (descriptive essay)",
      "A descriptive essay uses vivid detail to help the reader form a clear mental picture of a person, place, or thing."),
  _q("N'ide akwụkwọ ozi obere (informal letter) n'asụsụ Igbo, gịnị ka a na-ejikarị amalite ya?",
      ["Ekele na aha onye e degaara akwụkwọ ozi ahụ", "Naanị isi okwu", "Naanị akara olu", "Naanị mbibi ugwu"], "Ekele na aha onye e degaara akwụkwọ ozi ahụ",
      "Igbo letters conventionally open with a greeting and an address to the recipient before moving to the main message."),
  _q("Kedu nkà kacha mkpa maka ide edemede zuru oke n'asụsụ Igbo?",
      ["Nhazi echiche n'usoro doro anya na iji ụtọasụsụ ziri ezi", "Ide n'enweghị nhazi ọ bụla", "Iji naanị mkpụrụokwu Bekee", "Ide n'enweghị akara olu ọ bụla"], "Nhazi echiche n'usoro doro anya na iji ụtọasụsụ ziri ezi",
      "Good essay writing requires clear, logical organisation of ideas along with correct grammar."),
  _q("Mgbe a na-agụ otu edemede ọgụgụ isi, gịnị bụ ụzọ kacha mma iji chọpụta azịza ajụjụ ma ị na-echedoghị echiche?",
      ["Ịlaghachi azụ gụọ akụkụ metụtara ajụjụ ahụ ọzọ", "Ịchọpụta azịza site n'echiche onwe gị naanị", "Ịzipụ ajụjụ ahụ n'efu", "Ịzaghachi site na ntụle aha onwe gị"], "Ịlaghachi azụ gụọ akụkụ metụtara ajụjụ ahụ ọzọ",
      "Re-reading the relevant section of the passage before answering is the most reliable way to confirm the correct answer."),
  _q("Kedu ihe a na-akpọ nkọwa nkenke nke isi ihe dị n'otu edemede ogologo?",
      ["Nchịkọta (summary)", "Nnochi aha", "Akara olu", "Njikọ okwu"], "Nchịkọta (summary)",
      "A summary (nchịkọta) briefly captures the essential main points of a longer text without every minor detail."),
  _q("Kedu ụdị edemede na-egosipụta echiche onye na-ede ya ma jiri ihe akaebe kwado ya (argumentative essay)?",
      ["Edemede ịrụ ụka (argumentative essay)", "Edemede akụkọ", "Edemede nkọwa", "Akwụkwọ ozi"], "Edemede ịrụ ụka (argumentative essay)",
      "An argumentative essay presents and supports a clear position on an issue using logical reasoning and evidence."),
  _q("N'ide akwụkwọ ozi gọọmentị/azụmahịa (formal letter) n'Igbo, gịnị dị iche na akwụkwọ ozi obere?",
      ["Ọ na-achọkarị okwu na usoro nkwanye ùgwù karịa", "Ọ dịghị mkpa ekele ọ bụla", "Ọ naghị enwe onye a na-edegara ya", "Ọ na-adịkarị mkpụmkpụ karịa akwụkwọ ozi obere"], "Ọ na-achọkarị okwu na usoro nkwanye ùgwù karịa",
      "Formal letters typically demand more careful, respectful, and structured language compared to informal letters to friends or family."),
  _q("Kedu ihe kpatara a na-agba mbọ ịmụta ụtọasụsụ ziri ezi tupu e wee mụọ ide edemede n'asụsụ Igbo?",
      ["N'ihi na ụtọasụsụ ziri ezi na-eme ka echiche pụta ìhè nke ọma n'edemede", "N'ihi na ụtọasụsụ bụ naanị maka mgbako", "N'ihi na ọ dịghị mkpa n'ọmụmụ asụsụ", "N'ihi na akara olu adịghị emetụta ụtọasụsụ"], "N'ihi na ụtọasụsụ ziri ezi na-eme ka echiche pụta ìhè nke ọma n'edemede",
      "A solid grasp of grammar helps writers express ideas clearly and correctly in their essays."),
];

final _agumaguOnu = [
  _q("Kedu nkọwa kacha zie ezi maka Agụmagụ Ọnụ n'omenala Igbo?",
      ["Agụmagụ e si n'ọnụ na-agbasa site n'ọgbọ ruo n'ọgbọ, n'edeghị ede ya", "Agụmagụ e dere n'akwụkwọ kpọmkwem", "Agụmagụ e siri na mba ọzọ tụgharịa", "Ihe ọmụmụ mgbako naanị"], "Agụmagụ e si n'ọnụ na-agbasa site n'ọgbọ ruo n'ọgbọ, n'edeghị ede ya",
      "Oral literature (Agụmagụ Ọnụ) is transmitted verbally across generations rather than through writing."),
  _q("Kedu ihe a na-akpọ akụkọ ọdịnala na-akọwa mmalite ụwa ma ọ bụ ihe omimi banyere chi na mmụọ?",
      ["Nkọmịrịkọ (myth)", "Nkọkịrịkọ (legend)", "Mbem (chant)", "Agwụgwa (riddle)"], "Nkọmịrịkọ (myth)",
      "Myths (nkọmịrịkọ) explain the origins of the world or supernatural phenomena in Igbo oral tradition."),
  _q("Kedu ihe a na-akpọ akụkọ ọdịnala metụtara ndị dị ike ma ọ bụ ihe omume mere n'oge gara aga, nke ndị mmadụ na-ekwenyekarị na e nwere eziokwu dị na ya?",
      ["Nkọkịrịkọ (legend)", "Nkọmịrịkọ (myth)", "Mbem", "Agwụgwa"], "Nkọkịrịkọ (legend)",
      "Legends (nkọkịrịkọ) recount notable figures or events believed to hold a kernel of historical truth."),
  _q("Kedu ihe a na-akpọ akụkọ ifo na-abụkarị maka anụmanụ dị iche iche na-ekwu okwu dịka mmadụ (dịka Mbekwu na Odum)?",
      ["Akụkọ ifo (folktale)", "Nkọmịrịkọ", "Mbem", "Egwu ọdịnala"], "Akụkọ ifo (folktale)",
      "Igbo folktales (akụkọ ifo) frequently feature anthropomorphised animal characters such as the tortoise (Mbekwu/Mbe) and lion (Odum), teaching moral lessons through their adventures."),
  _q("N'akụkọ ifo Igbo, kedu anụmanụ a maara nke ọma dịka onye aghụghọ na onye amamihe (trickster) n'akụkọ ọtụtụ?",
      ["Mbekwu (mbe/tortoise)", "Agụ (leopard)", "Enyi (elephant)", "Ọkụkọ (fowl)"], "Mbekwu (mbe/tortoise)",
      "The tortoise (mbekwu/mbe) is the archetypal trickster figure in Igbo folktales, known for cunning and cleverness that often gets it into and out of trouble."),
  _q("Kedu ihe a na-akpọ ajụjụ nwere ọkịkọ nke a na-eji egwuri egwu iji nwalee amamihe na uche ọsọ ọsọ?",
      ["Agwụgwa (riddle)", "Mbem", "Nkọmịrịkọ", "Egwu ọdịnala"], "Agwụgwa (riddle)",
      "Riddles (agwụgwa) are a traditional guessing game designed to test cleverness and quick thinking."),
  _q("Kedu ihe a na-akpọ abụ ọdịnala nke a na-abụkarị n'oge mmemme, ọrụ ubi, ma ọ bụ n'egwuregwu ụmụaka?",
      ["Egwu ọdịnala (traditional song)", "Nkọmịrịkọ", "Nkọkịrịkọ", "Ụtọasụsụ"], "Egwu ọdịnala (traditional song)",
      "Traditional songs (egwu ọdịnala) accompany festivals, communal work, and children's play in Igbo culture."),
  _q("Kedu ihe a na-akpọ okwu amamihe dị mkpụmkpụ ndị okenye na-ejikarị akụziri ụmụ ntị (ilu)?",
      ["Ilu (proverb)", "Akụkọ ifo", "Agwụgwa", "Mbem"], "Ilu (proverb)",
      "Proverbs (ilu) are short, wise sayings elders use to teach and pass on values and wisdom."),
  _q("N'ilu Igbo a ma ama, 'Ọ bụrụ na anyanwụ apụọ, ọ ga-acha nkịta ọcha ọcha' na-akọwapụta gịnị?",
      ["Eziokwu ga-apụta ìhè n'agbanyeghị mgbe ọ ga-adị", "Nkịta na-acha ọcha n'ihi anyanwụ", "Ọ dịghị isi ihe ọ pụtara", "Nkịta niile bụ ọcha"], "Eziokwu ga-apụta ìhè n'agbanyeghị mgbe ọ ga-adị",
      "This proverb-style saying is a common way Igbo proverbs use natural imagery to teach that truth or reality eventually becomes clear, regardless of delay."),
  _q("Kedu isi ọrụ ilu (proverbs) na-arụ n'ikwu okwu n'ọdịnala Igbo?",
      ["Ọ na-eme ka okwu doo anya, mee ka ọ dị ike, wee gosipụta amamihe onye na-ekwu okwu", "Ọ bụ naanị maka ntụrụndụ ụmụaka", "Ọ na-egbochi ekwuru okwu", "Ọ dịghị ọrụ ọ na-arụ"], "Ọ na-eme ka okwu doo anya, mee ka ọ dị ike, wee gosipụta amamihe onye na-ekwu okwu",
      "Proverbs enrich speech, add persuasive weight, and demonstrate the speaker's wisdom and command of the culture."),
  _q("Kedu oge a na-akpọkarị agwụgwa (riddles) n'omenala Igbo ochie?",
      ["N'abalị, mgbe ọrụ ehihie gwụsịrị", "Naanị n'ehihie n'oge ọrụ ubi", "Naanị n'oge ememme ọlụlụ di na nwunye", "Naanị n'oge mbido afọ ọhụrụ"], "N'abalị, mgbe ọrụ ehihie gwụsịrị",
      "Riddle-telling sessions traditionally happened at night, providing entertainment and mental exercise after the day's work."),
  _q("Kedu ọrụ ndị okenye (elders) na-arụkarị n'ịgbasa agụmagụ ọnụ n'obodo Igbo?",
      ["Ha na-akọrọ ụmụaka na ndị na-eto eto akụkọ ifo, ilu, na amamihe ọdịnala", "Ha anaghị etinye aka n'agụmagụ ọnụ ma ọ bụla", "Ha na-elekwasị anya naanị n'azụmahịa", "Ha na-akọwakarị naanị akụkọ mba ofesi"], "Ha na-akọrọ ụmụaka na ndị na-eto eto akụkọ ifo, ilu, na amamihe ọdịnala",
      "Elders serve as the traditional custodians and transmitters of oral literature, passing folktales, proverbs, and wisdom to younger generations."),
  _q("Kedu ụdị egwu ọdịnala Igbo a na-eji anabata ndị ọbịa ma ọ bụ mee ememme dị iche iche, jiri ọdụdụ egwu na ihe egwu ọdịnala?",
      ["Egwu na Ọdụdụ Ọdịnala (traditional music and dance)", "Nkọmịrịkọ naanị", "Agwụgwa naanị", "Nnochi aha"], "Egwu na Ọdụdụ Ọdịnala (traditional music and dance)",
      "Traditional music and dance are central to welcoming guests and celebrating festivals in Igbo communities."),
  _q("Gịnị bụ isi ọdịiche dị n'etiti nkọmịrịkọ (myth) na nkọkịrịkọ (legend)?",
      ["Nkọmịrịkọ na-emetụta ihe omimi na chi, ebe nkọkịrịkọ na-emetụtakarị ndị mmadụ ma ọ bụ ihe omume dị n'akụkọ ihe mere eme", "Ha abụọ bụ otu ihe", "Nkọkịrịkọ bụ naanị maka egwu ntụrụndụ", "Nkọmịrịkọ bụ naanị maka abụ"], "Nkọmịrịkọ na-emetụta ihe omimi na chi, ebe nkọkịrịkọ na-emetụtakarị ndị mmadụ ma ọ bụ ihe omume dị n'akụkọ ihe mere eme",
      "Myths deal with supernatural or divine explanations, while legends focus more on human figures or events with a claimed historical basis."),
  _q("Kedu ihe ga-eme ma ọ bụrụ na a ghara ịchekwa agụmagụ ọnụ site n'ọgbọ ruo n'ọgbọ?",
      ["A ga-efu ọtụtụ ọdịnala na amamihe ndị dị mkpa nke ọdịnala ahụ", "Ọ dịghị ihe ga-emeru omenala ahụ", "A ga-enwe agụmagụ ọnụ karịa mbụ", "Ọdịnala ahụ ga-adịgide na-enweghị mgbanwe ọ bụla"], "A ga-efu ọtụtụ ọdịnala na amamihe ndị dị mkpa nke ọdịnala ahụ",
      "Without deliberate transmission across generations, much valuable oral tradition and cultural wisdom risks being permanently lost."),
  _q("Kedu ihe a na-akpọ mkpịsị akụkọ ifo na-emesịkarị egosi omume ọjọọ ka a taa ya ahụhụ, ebe omume ọma ka a kwụghachi ụgwọ ọma?",
      ["Nkuzi omume (moral lesson)", "Isi ihe abụ", "Njikọ okwu", "Akara olu"], "Nkuzi omume (moral lesson)",
      "Igbo folktales typically end with a clear moral lesson, rewarding good behaviour and punishing bad conduct."),
  _q("Kedu ụdị nkà a na-achọkarị n'aka onye na-akọ akụkọ ifo n'ihu ọha (oral performer) ka akụkọ ya na-atọ ndị na-ege ntị ụtọ?",
      ["Ikike iji olu na omume ahụ mee ka akụkọ ahụ dị mma ma dọrọ mmasị", "Ikike ide akwụkwọ ozi", "Ikike gụọ akwụkwọ dị elu", "Ikike ịkpọ egwu ọ bụla na-enweghị olu"], "Ikike iji olu na omume ahụ mee ka akụkọ ahụ dị mma ma dọrọ mmasị",
      "Skilled oral performers use vocal expression, gesture, and audience interaction (often call-and-response) to make storytelling engaging."),
  _q("Kedu ọrụ egwu ubi (farm/work songs) na-arụ n'omenala Igbo?",
      ["Ọ na-akwalite ume ndị ọrụ ma na-eme ka ọrụ ọha dịrị mma", "Ọ na-akụzi mgbako naanị", "Ọ metụtara mgbanwe ihu igwe naanị", "Ọ metụtara ndụmọdụ azụmahịa naanị"], "Ọ na-akwalite ume ndị ọrụ ma na-eme ka ọrụ ọha dịrị mma",
      "Farm work songs energise labourers and help coordinate communal effort, making shared work more efficient and enjoyable."),
  _q("Kedu ihe a na-akpọ nkatakọtọ (chorus/refrain) a na-eji na-azaghachi n'egwu ọdịnala ma ọ bụ n'akụkọ ifo?",
      ["Ọsọ okwu (call and response)", "Nnochi aha", "Mbuuzo", "Akara nkwụsi"], "Ọsọ okwu (call and response)",
      "Call-and-response is a defining performance feature of Igbo oral tradition, where a leader's line is answered by a group's refrain."),
  _q("Kedu ihe kpatara e ji akpọ agwụgwa (riddles) 'egwuregwu okwu' n'asụsụ Bekee?",
      ["N'ihi na ọ bụ egwuregwu na-eji okwu chọpụta amamihe onye na-aza ya", "N'ihi na ọ bụ naanị maka ndị ọka", "N'ihi na e ji ya achọ ego", "N'ihi na a naghị eji ya eme ihe ọ bụla"], "N'ihi na ọ bụ egwuregwu na-eji okwu chọpụta amamihe onye na-aza ya",
      "Riddles are essentially a verbal 'word game' testing cleverness through language rather than physical skill."),
];

final _agumaguEdereEde = [
  _q("Kedu ihe a na-akpọ agụmagụ e dere n'akwụkwọ, dị ka akụkọ, egwuregwu, na abụ e dere ede?",
      ["Agụmagụ Edere Ede (written literature)", "Agụmagụ Ọnụ (oral literature)", "Nkọmịrịkọ naanị", "Agwụgwa naanị"], "Agụmagụ Edere Ede (written literature)",
      "Written literature (Agụmagụ Edere Ede) refers to literary works recorded in text form, distinct from orally transmitted traditions."),
  _q("Kedu onye e ji ama dịka otu n'ime ndị mbụ dere akwụkwọ akụkọ Igbo a maara nke ọma, dịka 'Omenụkọ'?",
      ["Pita Nwana", "Chinụa Achebe", "Cyprian Ekwensi", "Wole Soyinka"], "Pita Nwana",
      "Pita Nwana is widely credited as the author of 'Omenụkọ', one of the earliest and most influential Igbo-language novels."),
  _q("Kedu ụdị agụmagụ edere ede a na-akpọ nke a na-eme dịka egwuregwu ihu ọha, nwere ndị ọrụnnọgbu na-ekwu okwu (drama)?",
      ["Egwuregwu (drama)", "Uri (poetry)", "Akụkọ (prose/novel)", "Akwụkwọ ozi"], "Egwuregwu (drama)",
      "Drama (egwuregwu) is a literary genre written to be performed, featuring characters speaking dialogue, distinct from prose and poetry."),
  _q("N'agụmagụ edere ede, kedu ihe a na-akpọ isi ozi ma ọ bụ echiche bụ isi nke onye edemede na-achọ ịkọwa n'ime akwụkwọ ya?",
      ["Isi ihe (theme)", "Nkọmịrịkọ", "Agwụgwa", "Njirimara mkpụrụokwu"], "Isi ihe (theme)",
      "The theme (isi ihe) is the central underlying message or idea an author conveys through a literary work."),
  _q("Kedu ihe a na-akpọ ndị mmadụ dị iche iche na-eme ihe n'ime otu akụkọ ma ọ bụ egwuregwu?",
      ["Ndị ọrụnnọgbu n'akụkọ (characters)", "Isi ihe", "Ọdịnala", "Akara olu"], "Ndị ọrụnnọgbu n'akụkọ (characters)",
      "Characters are the individuals who participate in and drive the events of a narrative or dramatic work."),
  _q("Kedu ihe a na-akpọ akụkọ e dere ede n'akwụkwọ ogologo nwere isi ihe na ndị ọrụnnọgbu zuru oke (novel)?",
      ["Akụkọ ogologo (novel)", "Mbem (chant)", "Agwụgwa", "Ilu"], "Akụkọ ogologo (novel)",
      "A novel (akụkọ ogologo) is an extended fictional prose narrative with developed characters and plot."),
  _q("Kedu ọrụ JAMB/Ule ule si etinye n'usoro mmụta banyere agụmagụ edere ede Igbo?",
      ["Ọ na-ahọpụta akwụkwọ akụkọ, egwuregwu, na abụ ụfọdụ ka ụmụ akwụkwọ mụọ maka ule", "Ọ naghị enwe ihe ọ bụla metụtara agụmagụ edere ede", "Ọ na-ekwu naanị maka mgbako", "Ọ na-elebara anya naanị na akụkọ mba ọzọ"], "Ọ na-ahọpụta akwụkwọ akụkọ, egwuregwu, na abụ ụfọdụ ka ụmụ akwụkwọ mụọ maka ule",
      "Examination bodies prescribe specific Igbo prose, drama, and poetry texts that candidates are expected to study."),
  _q("Kedu nkà dị mkpa maka nyocha (analysis) nke otu akụkọ ma ọ bụ egwuregwu e dere ede n'asụsụ Igbo?",
      ["Ikike ịchọpụta isi ihe, ndị ọrụnnọgbu, na ọnọdụ akụkọ ahụ", "Ikike ịgụ akwụkwọ ngwa ngwa n'enweghị nghọta", "Ikike ide uri naanị", "Ikike ịkpọ akwụkwọ ozi"], "Ikike ịchọpụta isi ihe, ndị ọrụnnọgbu, na ọnọdụ akụkọ ahụ",
      "Effective literary analysis requires identifying a text's theme, characters, and setting for deeper understanding."),
  _q("Gịnị bụ isi ọdịiche dị n'etiti agụmagụ ọnụ na agụmagụ edere ede?",
      ["Agụmagụ ọnụ ka a na-agbasa site n'ọnụ, ebe agụmagụ edere ede ka a na-edekọ n'akwụkwọ", "Ọ dịghị ọdịiche dị n'etiti ha", "Agụmagụ edere ede bụ naanị maka mmemme ọlụlụ di na nwunye", "Agụmagụ ọnụ na-emetụta naanị mgbako"], "Agụmagụ ọnụ ka a na-agbasa site n'ọnụ, ebe agụmagụ edere ede ka a na-edekọ n'akwụkwọ",
      "The core distinction lies in mode of preservation: oral literature is passed down verbally while written literature is recorded in text."),
  _q("Kedu ụdị agụmagụ edere ede a na-eji ahịrịokwu dị nro na akara ụda mee ka echiche pụta ìhè n'ụzọ dị mma (poetry)?",
      ["Uri (poetry)", "Akụkọ ogologo", "Egwuregwu", "Akwụkwọ ozi"], "Uri (poetry)",
      "Poetry (uri) uses carefully crafted, often rhythmic language to express ideas and emotions in a compact, artistic form."),
];

final _omenalaNaEwumewu = [
  _q("Kedu ihe a na-akpọ usoro alụmdi na nwunye n'ọdịnala Igbo, nke gụnyere ịkwụ ụgwọ ọlụlụ?",
      ["Alụmdi na nwunye ọdịnala (traditional marriage institution)", "Ịgụ aha", "Ibi ugwu", "Echichi"], "Alụmdi na nwunye ọdịnala (traditional marriage institution)",
      "Traditional Igbo marriage (alụmdi na nwunye) involves formal family negotiations, including the payment of bride price (ịkwụ ụgwọ ọlụlụ)."),
  _q("Kedu ihe a na-akpọ mmemme e ji enye nwa ọhụrụ aha ya n'ọdịnala Igbo?",
      ["Ịgụ aha (naming ceremony)", "Ibi ugwu", "Alụmdi na nwunye", "Echichi"], "Ịgụ aha (naming ceremony)",
      "The naming ceremony (ịgụ aha) formally gives a newborn their name, usually accompanied by prayers and celebration."),
  _q("Kedu ihe a na-akpọ ọchịchị ọdịnala Igbo nke a na-ahọpụta ndị okenye ma ọ bụ eze n'obodo iji chịa obodo dịka omenala si dị?",
      ["Ọchịchị Ala/Ọha na Eze (traditional council/monarchy system)", "Ọchịchị nde ọzọ naanị", "Ọchịchị ndị ọka mmụta naanị", "Ọ dịghị ọchịchị ọdịnala"], "Ọchịchị Ala/Ọha na Eze (traditional council/monarchy system)",
      "Many Igbo communities are traditionally governed by a council of elders (Ọha na Eze) or a traditional ruler, depending on local custom."),
  _q("Kedu ihe a na-akpọ akwa mgba nwoke ma ọ bụ nwaanyị na-eyi n'oge emume ọdịnala dị mkpa dịka mmanwụ?",
      ["Uwe ọdịnala/akwa omenala (traditional attire)", "Uwe ndị ọrụ ụlọ ọrụ", "Uwe ndị sistọ", "Uwe akwụkwọ"], "Uwe ọdịnala/akwa omenala (traditional attire)",
      "Traditional attire (akwa omenala) is worn during significant cultural events such as masquerade festivals and title-taking ceremonies."),
  _q("Kedu ihe a na-akpọ mmemme nzuzo dị mkpa n'omenala Igbo ebe mmadụ na-eyiri uwe ma na-anọchite anya mmụọ ndị nna nna ha (dịka na ememme Ahịajiọkụ ma ọ bụ ememme mkpọmasị)?",
      ["Mmụọ/mmanwụ (masquerade)", "Ọzọ", "Ịgụ aha", "Echichi"], "Mmụọ/mmanwụ (masquerade)",
      "The masquerade (mmụọ/mmanwụ) tradition, in which performers embody ancestral or spiritual figures, is a central feature of many Igbo festivals."),
  _q("Kedu ihe a na-akpọ ememme owuwe ihe ubi a na-eme kwa afọ n'ọtụtụ obodo Igbo iji kelee ihe ubi ọhụrụ, dịka ji?",
      ["Ememme Iri Ji (New Yam Festival)", "Ememme mmiri ozuzo", "Ememme ọlụlụ di", "Ememme ịgba mba"], "Ememme Iri Ji (New Yam Festival)",
      "The New Yam Festival (Iri Ji/Iwa Ji) is an annual harvest celebration held across many Igbo communities to mark the yam harvest with thanksgiving."),
  _q("Kedu ihe a na-akpọ nsọpụrụ ndị Igbo na-enye chi ha, mmụọ ha, na ndị nna nna ha nwụrụ anwụ n'omenala ochie?",
      ["Nsọpụrụ ndịichie na chi (ancestral and spiritual reverence)", "Nsọpụrụ ndị ọzọ naanị", "Nsọpụrụ ndị ọka mmụta naanị", "Ọ dịghị nsọpụrụ ọ bụla dị"], "Nsọpụrụ ndịichie na chi (ancestral and spiritual reverence)",
      "Traditional Igbo religion and culture place great importance on honouring ancestors (ndịichie) and spiritual/deity figures (chi/arụsị)."),
  _q("Kedu ihe a na-akpọ omenala mbụ e ji anabata onye ọbịa n'ụlọ Igbo, dịka ịnye ya mmiri ma ọ bụ ọjị?",
      ["Nnabata ọbịa (hospitality customs)", "Ịgụ aha", "Echichi", "Alụmdi na nwunye"], "Nnabata ọbịa (hospitality customs)",
      "Igbo hospitality customs, such as offering water or kola nut (ọjị) to guests, reflect deeply held cultural values of welcome and respect."),
  _q("Kedu ihe a na-akpọ ọji (kola nut) na-anọchi anya ya n'omenala Igbo mgbe a na-agọ ya n'ihu ọbịa?",
      ["Nnabata, udo, na nkwanye ùgwù", "Ọ bụ naanị nri", "Ọ bụ naanị ihe ahịa", "Ọ dịghị isi ihe ọ na-anọchi anya ya"], "Nnabata, udo, na nkwanye ùgwù",
      "The breaking and sharing of kola nut (ọjị) symbolises welcome, peace, and mutual respect in Igbo tradition, and is often accompanied by prayers."),
  _q("Kedu ihe a na-akpọ usoro ọzọ (title-taking) n'omenala Igbo?",
      ["Usoro e si enweta ọkwa ùgwù n'obodo site n'ịgba mbọ na ịrụ ọrụ maka ọha", "Usoro alụmdi na nwunye naanị", "Usoro ime ọmụmụ naanị", "Usoro ịkọ akụkọ ifo naanị"], "Usoro e si enweta ọkwa ùgwù n'obodo site n'ịgba mbọ na ịrụ ọrụ maka ọha",
      "Title-taking (ịgba ọzọ or similar systems) is a traditional process by which a person earns social status and honour within the community."),
  _q("Kedu ihe a na-akpọ ihe onwunwe ala e ji egosi na ala bụ ihe kacha dị mkpa n'omenala Igbo, karịsịa n'ọrụ ubi?",
      ["Ala bụ chi/nne ala (Earth deity/land reverence)", "Mmiri bụ chi kachasị elu", "Anyanwụ bụ naanị chi a na-akpọku", "Ọ dịghị nsọpụrụ e nyere ala"], "Ala bụ chi/nne ala (Earth deity/land reverence)",
      "Ala (the Earth deity) holds a central place in traditional Igbo cosmology, especially given the community's strong dependence on farming and land."),
  _q("Kedu ihe a na-akpọ ọmarịcha ihe owuwu ụlọ ọdịnala Igbo bụ isi ebe emume obodo na-ebe (dịka mmemme mmadụ ọha)?",
      ["Ilo/ama obodo (village square)", "Ụlọikpe naanị", "Ụlọ ọrụ mmiri", "Ụlọ ahịa"], "Ilo/ama obodo (village square)",
      "The village square (ilo/ama) traditionally serves as the community's central gathering place for festivals, meetings, and important events."),
  _q("Kedu ihe a na-akpọ omenala ịkwa ozu na Igbo, nke gụnyere ememme e ji akwanyere onye nwụrụ anwụ ùgwù?",
      ["Ikwa ozu (burial/funeral rites)", "Ịgụ aha", "Alụmdi na nwunye", "Ememme Iri Ji"], "Ikwa ozu (burial/funeral rites)",
      "Burial and funeral rites (ikwa ozu) are elaborate traditional ceremonies performed to honour the deceased and mark their transition to ancestorhood."),
  _q("Kedu isi mkpa mmadụ ji akpọ aha ụmụ ya n'ọdịnala Igbo dịka 'Chukwuemeka' ma ọ bụ 'Ngozi'?",
      ["Aha ndị a na-egosipụtakarị ekele, ekpere, ma ọ bụ echiche banyere Chineke ma ọ bụ ihe gbasara ọmụmụ nwa", "Aha ndị a na-ahọpụta na-enweghị ihe ọ pụtara", "Aha niile a na-esi n'asụsụ Bekee", "Aha niile na-egosi ọrụ mmadụ na-arụ"], "Aha ndị a na-egosipụtakarị ekele, ekpere, ma ọ bụ echiche banyere Chineke ma ọ bụ ihe gbasara ọmụmụ nwa",
      "Igbo personal names are often meaningful, frequently expressing gratitude, prayer, or circumstances surrounding a child's birth, as with 'Chukwuemeka' (God has done well) or 'Ngozi' (blessing)."),
];

final _iheNgwaNkeUgbuA = [
  _q("Kedu nzukọ na-elekọta ọganihu na mgbasa asụsụ Igbo n'ọzụzụ akwụkwọ na mgbasa ozi n'oge a?",
      ["Society for Promoting Igbo Language and Culture (SPILC)", "NUC naanị", "WAEC naanị", "NNPC"], "Society for Promoting Igbo Language and Culture (SPILC)",
      "SPILC is a recognised body actively working to promote and preserve the Igbo language and culture in contemporary Nigeria."),
  _q("Kedu ihe UNESCO kwuru maka ọdịdị asụsụ Igbo n'ọtụtụ nyocha e mere na mmalite narị afọ 21?",
      ["E nwere nchegbu banyere mbelata ọmụmụ ya n'ụlọ, na-eme ka ndị nkụzi na ndị mmụta chọọ ịgbasi ya mbọ", "Ọ kwuru na Igbo bụ asụsụ kachasị ọtụtụ ndị na-asụ ya n'ụwa", "Ọ kwuru na Igbo enweghị nsogbu ọ bụla", "Ọ kwuru na Igbo bụ asụsụ ọhụrụ na Naịjirịa"], "E nwere nchegbu banyere mbelata ọmụmụ ya n'ụlọ, na-eme ka ndị nkụzi na ndị mmụta chọọ ịgbasi ya mbọ",
      "Concerns about declining intergenerational transmission of Igbo at home have prompted renewed advocacy for its promotion in schools and media."),
  _q("Kedu teknụzụ ndị a na-eji taa nyere aka gbasaa mmụta na iji asụsụ Igbo, dịka ngwa mkpanaka na weebụsaịtị?",
      ["Ngwa mọbaịl na weebụsaịtị mmụta asụsụ Igbo", "Igwe ndozi ụgbọ ala naanị", "Igwe ọrụ ubi kpọmkwem", "Ọ dịghị teknụzụ a na-eji"], "Ngwa mọbaịl na weebụsaịtị mmụta asụsụ Igbo",
      "Mobile apps and websites are increasingly used to teach and promote the Igbo language among younger and diaspora learners."),
  _q("Kedu ụdị mgbasa ozi (media) na-enyekarị aka ịgbasa asụsụ Igbo n'ụlọ ọrụ redio na telivishọn n'oge a?",
      ["Mmemme redio na telivishọn e ji Igbo mee (Igbo-language broadcasts)", "Naanị akwụkwọ akụkọ Bekee", "Naanị mgbasa ozi asụsụ ọzọ", "Ọ dịghị mgbasa ozi Igbo dị"], "Mmemme redio na telivishọn e ji Igbo mee (Igbo-language broadcasts)",
      "A number of Nigerian radio and television stations continue to run dedicated Igbo-language programming, helping sustain everyday use of the language."),
  _q("Kedu isi nsogbu ndị ọka mmụta asụsụ na-ekwukarị maka mbelata iji asụsụ Igbo n'ebe ụmụaka nọ na obodo ukwu?",
      ["Ọtụtụ nne na nna na-ejikarị Bekee na ụmụ ha na-ekwurịta okwu n'ụlọ", "Ọ dịghị asụsụ Bekee dị na Naịjirịa", "Ndị mmụta Igbo abaghị ọtụtụ", "Ọ dịghị nsogbu ọ bụla dị"], "Ọtụtụ nne na nna na-ejikarị Bekee na ụmụ ha na-ekwurịta okwu n'ụlọ",
      "Linguists commonly cite the growing preference for English in urban home communication as a key driver behind declining Igbo fluency among children."),
  _q("Kedu ihe ndị ọrụ akwụkwọ na-eme iji kwalite mmụta asụsụ Igbo n'ime ụlọ akwụkwọ Naịjirịa n'oge a?",
      ["Itinye asụsụ Igbo dịka otu asụsụ a na-akụziri ụmụ akwụkwọ na ndị ọzọ dịka ndị so na jamb elective", "Iwepụ Igbo n'usoro mmụta kpamkpam", "Iji naanị Bekee kụziere ihe niile", "Ịkwụsị ule Igbo n'ụlọ akwụkwọ"], "Itinye asụsụ Igbo dịka otu asụsụ a na-akụziri ụmụ akwụkwọ na ndị ọzọ dịka ndị so na jamb elective",
      "Igbo continues to be taught as a subject in Nigerian schools and is offered as an elective subject in examinations such as JAMB and Post-UTME screenings."),
  _q("Kedu ọrụ ndị na-ede n'ederede dijitalụ (dịka Facebook na WhatsApp) na-arụ n'ịgbasa asụsụ Igbo n'oge a?",
      ["Ha na-enyere aka ka ndị na-asụ Igbo dee ma kparịtaa ụka n'asụsụ ahụ n'ịntanetị", "Ha na-egbochi mmasị mmadụ n'Igbo", "Ha adịghị enye ohere ọ bụla iji Igbo", "Ha bụ naanị maka ndị na-asụ Bekee"], "Ha na-enyere aka ka ndị na-asụ Igbo dee ma kparịtaa ụka n'asụsụ ahụ n'ịntanetị",
      "Social media platforms have become an important informal space for writing and using Igbo in everyday digital communication."),
  _q("Kedu ihe a na-akpọ mmemme ememme ọdịnala Igbo a na-eme kwa afọ, nke na-adọtakarị ndị njem si mba ofesi bịa hụ omenala Igbo?",
      ["Ememme Iri Ji na ememme ọdịnala ndị ọzọ (annual cultural festivals)", "Ememme Krismas naanị", "Ememme Sallah naanị", "Ọ dịghị ememme ọdịnala Igbo dị"], "Ememme Iri Ji na ememme ọdịnala ndị ọzọ (annual cultural festivals)",
      "Annual cultural festivals such as the New Yam Festival remain prominent, drawing both local participants and visitors interested in Igbo heritage."),
];
