import "../quiz_question.dart";

QuizQuestion _q(String subject, String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

const _englishSubject = "English Language";
const _mathsSubject = "Mathematics";
const _gkSubject = "General Knowledge";

QuizQuestion _eq(String text, List<String> options, String correct, String explanation) =>
    _q(_englishSubject, text, options, correct, explanation);

QuizQuestion _mq(String text, List<String> options, String correct, String explanation) =>
    _q(_mathsSubject, text, options, correct, explanation);

QuizQuestion _gq(String text, List<String> options, String correct, String explanation) =>
    _q(_gkSubject, text, options, correct, explanation);

/// University of Ibadan (UI) Post-UTME practice bank — 100+ questions
/// covering the three areas most Nigerian Post-UTME screening exams draw
/// on: English Language, Mathematics, and General Knowledge (including
/// current affairs, with a good number themed around UI and Oyo State).
/// This is a general-purpose practice set, not an official UI past-question
/// paper; always confirm the exact format and syllabus on UI's own
/// screening portal for the current session.
List<QuizQuestion> buildUiPostUtmeQuestions() {
  return [
    ..._englishLanguage,
    ..._mathematics,
    ..._generalKnowledge,
  ];
}

/// Individual-subject accessors used by the Post-UTME subject picker, which
/// lets a student choose specific subjects rather than sit the full mixed
/// bank above.
List<QuizQuestion> buildUiEnglishLanguageQuestions() => List.of(_englishLanguage);
List<QuizQuestion> buildUiMathematicsQuestions() => List.of(_mathematics);
List<QuizQuestion> buildUiGeneralKnowledgeQuestions() => List.of(_generalKnowledge);

const _passage =
    "Across rural Nigeria, smallholder farmers have traditionally depended on itinerant extension officers for "
    "advice on planting seasons, pest control and fertiliser use, but the ratio of officers to farmers has long "
    "been too low to meet demand. In recent years, several agri-tech start-ups have begun delivering this same "
    "advice through simple text messages and voice calls sent directly to farmers' mobile phones, bypassing the "
    "need for a physical visit. Advocates say this approach is far cheaper to scale and can reach farmers in the "
    "most remote communities, provided they own even a basic handset. Critics, however, point out that such "
    "services still assume a level of network coverage and literacy that many rural households lack, and that "
    "generic advice sent to thousands of farmers at once cannot account for the specific soil conditions of an "
    "individual plot. Even so, pilot programmes across several states have reported modest gains in crop yields, "
    "suggesting the model holds real promise if refined further.";

QuizQuestion _ucq(String question, List<String> options, String correct, String explanation) =>
    _eq("$_passage\n\n$question", options, correct, explanation);

const _passage2 =
    "In the last decade, several Nigerian tertiary institutions have begun experimenting with solar-powered "
    "mini-grids to supplement the erratic supply from the national electricity grid. Unlike large centralised "
    "power stations, these mini-grids generate electricity close to where it is consumed, typically serving a "
    "single hostel block, laboratory complex or lecture theatre. Proponents argue that the approach sidesteps "
    "the enormous cost and years-long delay of extending national transmission lines to poorly served campuses, "
    "while also reducing the diesel fumes that once hung over generator-powered halls of residence. Sceptics "
    "counter that the upfront cost of solar panels and batteries remains high, that panels can lose a significant "
    "share of their efficiency within a decade if poorly maintained, and that a mini-grid serving one faculty "
    "does nothing to solve the electricity problems of neighbouring departments left off the scheme. Nonetheless, "
    "students in the pilot hostels report far fewer nights spent in the dark, and administrators say the "
    "investment already pays for itself within a few years through reduced diesel purchases.";

QuizQuestion _ucq2(String question, List<String> options, String correct, String explanation) =>
    _eq("$_passage2\n\n$question", options, correct, explanation);

const _passage3 =
    "Librarians across Nigerian secondary schools have grown increasingly worried about what many describe as a "
    "declining culture of sustained reading among teenagers, even as literacy rates on paper continue to rise. "
    "The concern is not that students cannot read, but that fewer of them choose to read anything longer than a "
    "social media caption once given the choice. Some educators blame the smartphone directly, arguing that its "
    "endless stream of short videos has shortened attention spans to the point where a ten-page short story now "
    "feels like an ordeal. Others push back against this narrative, noting that teenagers today consume enormous "
    "quantities of text daily through messaging and online forums, and suggesting that the real issue is a "
    "mismatch between assigned classroom texts and what young readers actually find engaging. A handful of "
    "schools have experimented with allowing students to choose their own novels for a weekly reading period, "
    "and report a modest but noticeable uptick in enthusiasm, if not yet in the reading of assigned literature.";

QuizQuestion _ucq3(String question, List<String> options, String correct, String explanation) =>
    _eq("$_passage3\n\n$question", options, correct, explanation);

final _englishLanguage = [
  _ucq("According to the passage, why have farmers traditionally relied on extension officers?",
      ["For advice on planting seasons, pest control and fertiliser use", "To obtain free mobile phones", "To secure loans for farm equipment", "To register for government subsidies"], "For advice on planting seasons, pest control and fertiliser use",
      "The passage states farmers 'depended on itinerant extension officers for advice on planting seasons, pest control and fertiliser use.'"),
  _ucq("What new approach does the passage describe as delivering the same advice as extension officers?",
      ["Text messages and voice calls sent to farmers' mobile phones", "Free television broadcasts in every village", "Door-to-door visits by government ministers", "Printed newsletters mailed to every farmhouse"], "Text messages and voice calls sent to farmers' mobile phones",
      "The passage says agri-tech start-ups deliver advice 'through simple text messages and voice calls sent directly to farmers' mobile phones.'"),
  _ucq("What do advocates of this mobile-based approach argue, according to the passage?",
      ["It is cheaper to scale and can reach the most remote communities", "It completely replaces the need for any government agricultural policy", "It guarantees every farmer a bumper harvest", "It eliminates the need for farmers to own a phone at all"], "It is cheaper to scale and can reach the most remote communities",
      "The passage notes advocates say the approach 'is far cheaper to scale and can reach farmers in the most remote communities.'"),
  _ucq("What concern do critics raise about the mobile-based advisory services, according to the passage?",
      ["Generic advice cannot account for the specific soil conditions of an individual plot", "The services are far more expensive than physical visits", "The advice given is always factually incorrect", "Extension officers have completely stopped visiting farmers"], "Generic advice cannot account for the specific soil conditions of an individual plot",
      "The passage states critics point out that 'generic advice sent to thousands of farmers at once cannot account for the specific soil conditions of an individual plot.'"),
  _ucq("What have pilot programmes across several states reportedly shown, according to the passage's conclusion?",
      ["Modest gains in crop yields, suggesting the model holds promise", "A complete collapse of agricultural output", "That farmers prefer to abandon phones entirely", "That extension officers are no longer needed anywhere"], "Modest gains in crop yields, suggesting the model holds promise",
      "The passage concludes that 'pilot programmes across several states have reported modest gains in crop yields, suggesting the model holds real promise if refined further.'"),
  _ucq("What is the closest meaning of the word 'itinerant' as used in the passage?",
      ["Travelling from place to place", "Permanently based in one office", "Highly paid", "Newly recruited"], "Travelling from place to place",
      "'Itinerant' describes someone who travels from place to place, fitting the description of extension officers who visit farmers rather than staying in one location."),
  _eq("Choose the option that best completes the sentence: 'The panel of judges ___ yet to reach a final decision.'",
      ["is", "are", "were", "have"], "is",
      "'The panel', treated as a single collective body, is grammatically singular here, taking the singular verb 'is'."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The new manager's approach was refreshingly PRAGMATIC.'",
      ["Practical", "Idealistic", "Chaotic", "Secretive"], "Practical",
      "'Pragmatic' means dealing with things sensibly and realistically, making 'practical' the closest synonym."),
  _eq("Choose the option opposite in meaning to the underlined word: 'The two leaders reached a remarkably CORDIAL agreement.'",
      ["Hostile", "Friendly", "Warm", "Genuine"], "Hostile",
      "'Cordial' means warm and friendly; its opposite is 'hostile', meaning unfriendly or antagonistic."),
  _eq("Choose the correctly spelt word.",
      ["Bureaucracy", "Beaurocracy", "Burreaucracy", "Bureaucrasy"], "Bureaucracy",
      "'Bureaucracy' is correctly spelt with 'eau' after 'bur' and 'cracy' at the end; the other options misspell the word."),
  _eq("Choose the option that best completes the sentence: 'If she ___ earlier, she would not have missed the flight.'",
      ["had left", "left", "leaves", "will leave"], "had left",
      "This is a third conditional describing an unreal past scenario, requiring the past perfect tense: 'if she had left earlier.'"),
  _eq("Choose the correct preposition to complete the sentence: 'The results were consistent ___ our earlier predictions.'",
      ["with", "to", "from", "for"], "with",
      "'Consistent with' is the standard and widely accepted preposition pairing in formal English usage."),
  _eq("Identify the part of speech of the underlined word: 'The QUICKLY assembled team impressed the judges.'",
      ["Adverb", "Adjective", "Noun", "Conjunction"], "Adverb",
      "'Quickly' modifies the verb form 'assembled', describing how the assembling was done, making it an adverb."),
  _eq("Choose the option that is the correct plural form of 'criterion'.",
      ["Criteria", "Criterions", "Criteriums", "Criterias"], "Criteria",
      "'Criterion', derived from Greek, forms its plural irregularly as 'criteria'."),
  _eq("Choose the option nearest in meaning to the idiom: 'When sales collapsed, the company decided to CUT ITS LOSSES.'",
      ["Stop an unprofitable activity before it gets worse", "Invest even more money immediately", "Celebrate an unexpected profit", "Announce a company-wide bonus"], "Stop an unprofitable activity before it gets worse",
      "'Cut one's losses' is an idiom meaning to stop doing something that is not working before the situation worsens further."),
  _eq("Choose the option that correctly completes the sentence: 'Economics ___ a compulsory subject in that faculty.'",
      ["is", "are", "were", "have been"], "is",
      "Although 'economics' ends in 's', it is treated as a singular subject when referring to the academic discipline, requiring the singular verb 'is'."),
  _eq("Choose the word that best completes the sentence: 'Her ___ handling of the crisis earned her wide praise.'",
      ["adept", "adopted", "adapted", "adequate"], "adept",
      "'Adept' means highly skilled, fitting the context of praiseworthy handling of a crisis."),
  _eq("Choose the correctly punctuated sentence.",
      ["The delegation included: Amina, Tunde, and Chidi.", "The delegation included Amina, Tunde, and Chidi", "The delegation included, Amina Tunde and Chidi.", "The delegation included; Amina, Tunde, and Chidi."], "The delegation included: Amina, Tunde, and Chidi.",
      "A colon is correctly used here to introduce a list following a complete independent clause, and the sentence properly ends with a full stop."),
  _eq("Choose the option that best completes the sentence: 'The information ___ accurate, despite the confusion it caused.'",
      ["was", "were", "have been", "having been"], "was",
      "'Information' is an uncountable noun that takes a singular verb, so 'was accurate' is correct."),
  _eq("Identify the figure of speech used: 'The wind whispered secrets through the trees.'",
      ["Personification", "Simile", "Onomatopoeia", "Hyperbole"], "Personification",
      "Giving the wind the human ability to 'whisper' is an example of personification, where non-human things are given human qualities."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The lecture hall fell into a SOMBRE silence after the announcement.'",
      ["Gloomy and serious", "Cheerful and lively", "Loud and chaotic", "Brief and casual"], "Gloomy and serious",
      "'Sombre' describes a dark, gloomy or serious mood, fitting the silence following a heavy announcement."),
  _eq("Choose the correct form of the verb: 'Each of the candidates ___ presented their proposal.'",
      ["has", "have", "were", "are"], "has",
      "'Each' is grammatically singular, so it takes the singular verb 'has', regardless of the plural noun ('candidates') that follows."),
  _eq("Choose the option that best completes the sentence: 'This is the laboratory ___ equipment was recently upgraded.'",
      ["whose", "who's", "which is", "that is"], "whose",
      "'Whose' is the possessive relative pronoun correctly used to link 'the laboratory' to 'its equipment.'"),
  _eq("Choose the word opposite in meaning to the underlined word: 'The committee's decision was entirely UNANIMOUS.'",
      ["Divided", "Agreed", "Collective", "Joint"], "Divided",
      "'Unanimous' means everyone in full agreement; its direct opposite is 'divided', meaning split in opinion."),
  _eq("Choose the correct option to complete the sentence: 'The scheme is designed not only to train youths ___ also to employ them.'",
      ["but", "and", "so", "or"], "but",
      "The correlative pairing 'not only...but also' is the standard grammatical construction used to link two related points."),
  _eq("Identify the correctly spelt word.",
      ["Occurrence", "Occurence", "Ocurrence", "Occurrance"], "Occurrence",
      "'Occurrence' is correctly spelt with double 'c' and double 'r'; the other options are misspellings."),
  _eq("Choose the option that best completes the sentence: 'It was they who ___ chosen to represent the class.'",
      ["were", "was", "is being", "have been"], "were",
      "The subject 'they' requires the plural past tense verb 'were' for grammatical agreement."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The auditor gave a very METICULOUS report of the accounts.'",
      ["Extremely careful and thorough", "Vague and careless", "Brief and superficial", "Late and incomplete"], "Extremely careful and thorough",
      "'Meticulous' means showing great attention to detail and being very careful, making 'extremely careful and thorough' the best synonym."),
  _eq("Choose the correct option: 'This scholarship is meant for you and ___.'",
      ["me", "I", "myself", "mine"], "me",
      "After a preposition ('for'), the objective case pronoun 'me' is correct, not the subjective 'I'."),
  _eq("Choose the option that correctly completes the sentence: 'The number of applicants ___ increased sharply this year.'",
      ["has", "have", "were", "are"], "has",
      "'The number of' takes a singular verb, unlike 'a number of', which takes a plural verb."),
  _eq("Choose the option that best expresses the meaning of the sentence: 'He decided to turn over a new leaf after the warning.'",
      ["He resolved to start behaving in a better way", "He literally flipped a page in a book", "He resigned from his job immediately", "He refused to accept the warning"], "He resolved to start behaving in a better way",
      "'Turn over a new leaf' is an idiom meaning to make a fresh, positive start in one's behaviour, not to be taken literally."),
  _eq("Choose the word that is nearest in meaning to the underlined word: 'The abandoned building was in a state of complete DERELICTION.'",
      ["Disrepair or abandonment", "Excellent preservation", "Modern renovation", "Recent construction"], "Disrepair or abandonment",
      "'Dereliction' refers to a state of abandonment or ruin, typically due to neglect."),
  _eq("Choose the correct sentence.",
      ["Every one of the girls has her own textbook.", "Every one of the girls have their own textbook.", "Every one of the girls has they own textbook.", "Every one of the girls have her own textbook."], "Every one of the girls has her own textbook.",
      "'Every one' is grammatically singular, so it correctly takes the singular verb 'has' and the singular possessive 'her' in traditional formal usage."),

  // --- Vocabulary: synonyms ---
  _eq("Choose the option nearest in meaning to the underlined word: 'The philanthropist was known for his BENEVOLENT donations to local schools.'",
      ["Kind and generous", "Cruel and selfish", "Secretive and shy", "Arrogant and boastful"], "Kind and generous",
      "'Benevolent' means well-meaning and kindly, making 'kind and generous' the closest synonym."),
  _eq("Choose the option nearest in meaning to the underlined word: 'She gave a CANDID account of what happened during the meeting.'",
      ["Honest and straightforward", "Deceptive and evasive", "Lengthy and boring", "Formal and rehearsed"], "Honest and straightforward",
      "'Candid' means truthful and straightforward, especially about something unwelcome."),
  _eq("Choose the option nearest in meaning to the underlined word: 'Despite years of research, a cure for the disease remained ELUSIVE.'",
      ["Difficult to find or achieve", "Easily obtainable", "Widely known", "Financially cheap"], "Difficult to find or achieve",
      "'Elusive' describes something that is hard to find, achieve or remember."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The professor's LUCID explanation cleared up all our doubts.'",
      ["Clear and easy to understand", "Confusing and vague", "Extremely lengthy", "Written in a foreign language"], "Clear and easy to understand",
      "'Lucid' means expressed clearly and easy to understand."),
  _eq("Choose the option nearest in meaning to the underlined word: 'Her TENACIOUS pursuit of the goal eventually paid off.'",
      ["Persistent and determined", "Careless and lazy", "Timid and fearful", "Indifferent and detached"], "Persistent and determined",
      "'Tenacious' describes someone who holds firmly to a purpose, i.e. persistent and determined."),
  _eq("Choose the option nearest in meaning to the underlined word: 'Growing up poor taught him to be FRUGAL with money.'",
      ["Careful and economical", "Wasteful and extravagant", "Generous to a fault", "Reckless with spending"], "Careful and economical",
      "'Frugal' means sparing or economical with money or resources."),
  _eq("Choose the option nearest in meaning to the underlined word: 'Everyone enjoyed working with the AMIABLE new supervisor.'",
      ["Friendly and pleasant", "Rude and hostile", "Distant and cold", "Nervous and anxious"], "Friendly and pleasant",
      "'Amiable' means having a friendly and pleasant manner."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The political situation in the region remained VOLATILE.'",
      ["Likely to change suddenly and unpredictably", "Calm and completely stable", "Well documented in history", "Popular among tourists"], "Likely to change suddenly and unpredictably",
      "'Volatile' describes a situation liable to change rapidly and unpredictably, especially for the worse."),
  _eq("Choose the option nearest in meaning to the underlined word: 'Experts confirmed that the painting was AUTHENTIC.'",
      ["Genuine", "Fake", "Damaged", "Expensive"], "Genuine",
      "'Authentic' means of undisputed origin, i.e. genuine."),
  _eq("Choose the option nearest in meaning to the underlined word: 'He was RETICENT about discussing his childhood.'",
      ["Reluctant to speak about something", "Eager to reveal everything", "Loud and boastful", "Confused about the facts"], "Reluctant to speak about something",
      "'Reticent' means not revealing one's thoughts or feelings readily; reluctant to speak."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The witness gave a PLAUSIBLE explanation for the delay.'",
      ["Believable and reasonable", "Absurd and unlikely", "Extremely rehearsed", "Written down beforehand"], "Believable and reasonable",
      "'Plausible' means seeming reasonable or probable, i.e. believable."),
  _eq("Choose the option nearest in meaning to the underlined word: 'Climbing the mountain proved to be an ARDUOUS task.'",
      ["Difficult and requiring great effort", "Simple and effortless", "Short and quick", "Enjoyable and relaxing"], "Difficult and requiring great effort",
      "'Arduous' means involving hard, strenuous effort."),
  _eq("Choose the option nearest in meaning to the underlined word: 'She spoke with such CANDOUR that no one doubted her sincerity.'",
      ["Openness and honesty", "Secrecy and deceit", "Anger and hostility", "Confusion and hesitation"], "Openness and honesty",
      "'Candour' means the quality of being open and honest."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The OBSTINATE child refused to change his mind.'",
      ["Stubborn and unyielding", "Flexible and agreeable", "Shy and timid", "Cheerful and playful"], "Stubborn and unyielding",
      "'Obstinate' means stubbornly refusing to change one's opinion or course of action."),
  _eq("Choose the option nearest in meaning to the underlined word: 'It would be PRUDENT to save some money for emergencies.'",
      ["Wise and sensible", "Careless and foolish", "Expensive and wasteful", "Illegal and risky"], "Wise and sensible",
      "'Prudent' means acting with or showing care and thought for the future, i.e. wise and sensible."),

  // --- Vocabulary: antonyms ---
  _eq("Choose the option opposite in meaning to the underlined word: 'Food was ABUNDANT during the harvest season.'",
      ["Scarce", "Plentiful", "Fresh", "Cheap"], "Scarce",
      "'Abundant' means existing in large quantities; its opposite is 'scarce', meaning insufficient or rare."),
  _eq("Choose the option opposite in meaning to the underlined word: 'The organisation's dealings were completely TRANSPARENT.'",
      ["Secretive", "Open", "Honest", "Clear"], "Secretive",
      "'Transparent' means open and easy to see through; its opposite is 'secretive', meaning inclined to hide information."),
  _eq("Choose the option opposite in meaning to the underlined word: 'The old policy was RIGID and allowed no exceptions.'",
      ["Flexible", "Strict", "Firm", "Unbending"], "Flexible",
      "'Rigid' means unable to bend or change; its opposite is 'flexible', meaning able to adapt easily."),
  _eq("Choose the option opposite in meaning to the underlined word: 'Attendance at the seminar was entirely VOLUNTARY.'",
      ["Compulsory", "Optional", "Free", "Willing"], "Compulsory",
      "'Voluntary' means done by choice; its opposite is 'compulsory', meaning required by rule or law."),
  _eq("Choose the option opposite in meaning to the underlined word: 'The village was TRANQUIL before the festival began.'",
      ["Chaotic", "Peaceful", "Quiet", "Calm"], "Chaotic",
      "'Tranquil' means calm and peaceful; its opposite is 'chaotic', meaning in a state of complete disorder."),
  _eq("Choose the option opposite in meaning to the underlined word: 'The old man was known to be GENEROUS to strangers.'",
      ["Stingy", "Kind", "Charitable", "Warm"], "Stingy",
      "'Generous' means willing to give freely; its opposite is 'stingy', meaning unwilling to spend or share."),
  _eq("Choose the option opposite in meaning to the underlined word: 'The museum housed several ANCIENT artefacts.'",
      ["Modern", "Old", "Historic", "Rare"], "Modern",
      "'Ancient' means belonging to the very distant past; its opposite is 'modern', meaning relating to the present or recent times."),
  _eq("Choose the option opposite in meaning to the underlined word: 'His performance was clearly SUPERIOR to the others.'",
      ["Inferior", "Excellent", "Better", "Advanced"], "Inferior",
      "'Superior' means higher in quality or rank; its opposite is 'inferior', meaning lower in quality or rank."),
  _eq("Choose the option opposite in meaning to the underlined word: 'The company plans to EXPAND its operations next year.'",
      ["Contract", "Grow", "Increase", "Extend"], "Contract",
      "'Expand' means to become or make larger; its opposite is 'contract', meaning to become smaller."),
  _eq("Choose the option opposite in meaning to the underlined word: 'Despite the setbacks, she remained OPTIMISTIC.'",
      ["Pessimistic", "Hopeful", "Positive", "Cheerful"], "Pessimistic",
      "'Optimistic' means hopeful about the future; its opposite is 'pessimistic', meaning expecting the worst."),
  _eq("Choose the option opposite in meaning to the underlined word: 'The staff were offered only a PERMANENT contract.'",
      ["Temporary", "Lasting", "Fixed", "Stable"], "Temporary",
      "'Permanent' means lasting indefinitely; its opposite is 'temporary', meaning lasting for only a limited time."),
  _eq("Choose the option opposite in meaning to the underlined word: 'The lawyer submitted a VOLUMINOUS report to the court.'",
      ["Compact", "Bulky", "Lengthy", "Extensive"], "Compact",
      "'Voluminous' means occupying a large amount of space; its opposite is 'compact', meaning small and neatly arranged."),
  _eq("Choose the option opposite in meaning to the underlined word: 'She was a DILIGENT student who never missed a class.'",
      ["Lazy", "Hardworking", "Careful", "Attentive"], "Lazy",
      "'Diligent' means showing care and effort in one's work; its opposite is 'lazy', meaning unwilling to work or exert effort."),
  _eq("Choose the option opposite in meaning to the underlined word: 'Clean water was SCARCE in that region.'",
      ["Abundant", "Rare", "Limited", "Insufficient"], "Abundant",
      "'Scarce' means insufficient for the demand; its opposite is 'abundant', meaning existing in large quantities."),
  _eq("Choose the option opposite in meaning to the underlined word: 'The champion remained HUMBLE despite his success.'",
      ["Arrogant", "Modest", "Simple", "Unassuming"], "Arrogant",
      "'Humble' means having a modest view of one's own importance; its opposite is 'arrogant', meaning having an exaggerated sense of one's own importance."),

  // --- Grammar and sentence completion ---
  _eq("Choose the option that best completes the sentence: 'Neither the manager nor the staff ___ aware of the change.'",
      ["were", "was", "is", "has"], "were",
      "With 'neither...nor', the verb agrees with the nearer subject; since 'staff' (nearer subject) is plural in sense here, 'were' is used."),
  _eq("Choose the option that best completes the sentence: 'By the time we arrived, the meeting ___ already started.'",
      ["had", "has", "have", "was"], "had",
      "The past perfect 'had started' is needed to show an action completed before another past action (our arrival)."),
  _eq("Choose the option that best completes the sentence: 'She is one of the students who ___ always punctual.'",
      ["are", "is", "was", "has been"], "are",
      "'Who' refers back to 'students' (plural), so the verb must agree in the plural: 'are'."),
  _eq("Choose the option that best completes the sentence: 'Hardly ___ the show begun when the lights went out.'",
      ["had", "has", "did", "was"], "had",
      "'Hardly...when' requires the past perfect tense for the first clause: 'had begun'."),
  _eq("Choose the option that best completes the sentence: 'I would rather you ___ here than travel in this weather.'",
      ["stayed", "stay", "stays", "will stay"], "stayed",
      "'Would rather' followed by a different subject takes a past subjunctive form, hence 'stayed'."),
  _eq("Choose the option that best completes the sentence: 'The teacher, along with her students, ___ preparing for the exhibition.'",
      ["is", "are", "were", "have"], "is",
      "Phrases introduced by 'along with' do not change the number of the main subject; since 'the teacher' is singular, the verb is 'is'."),
  _eq("Choose the option that best completes the sentence: '___ you finished the assignment, you may submit it.'",
      ["Once", "Unless", "Whereas", "Although"], "Once",
      "'Once' correctly conveys the meaning 'as soon as', fitting the logical sequence of the sentence."),
  _eq("Choose the option that best completes the sentence: 'He is too weak ___ carry the load alone.'",
      ["to", "for", "that", "so"], "to",
      "The construction 'too + adjective + to + verb' is the standard structure, as in 'too weak to carry'."),
  _eq("Choose the option that best completes the sentence: 'The report needs ___ before submission.'",
      ["proofreading", "proofread", "to proofreading", "proofreads"], "proofreading",
      "After 'needs', a gerund ('proofreading') is used to express that the report requires this action to be done to it."),
  _eq("Choose the option that best completes the sentence: 'No sooner had she sat down ___ the phone rang.'",
      ["than", "when", "then", "that"], "than",
      "'No sooner...than' is a fixed correlative construction used to describe two closely following events."),
  _eq("Choose the option that best completes the sentence: 'Scarcely had the plane landed ___ the passengers began to applaud.'",
      ["when", "than", "then", "that"], "when",
      "'Scarcely...when' is the correct fixed correlative pairing, unlike 'no sooner...than'."),
  _eq("Choose the option that best completes the sentence: '___ hard he tried, he could not solve the puzzle.'",
      ["However", "Whatever", "Whenever", "Wherever"], "However",
      "'However hard' is the correct concessive construction meaning 'no matter how hard'."),
  _eq("Choose the option that best completes the sentence: 'The committee members disagreed on ___ approach to take.'",
      ["which", "who", "whom", "whose own"], "which",
      "'Which' correctly introduces the noun 'approach' as a determiner asking about a choice among options."),
  _eq("Choose the option that best completes the sentence: 'She insisted that he ___ present at the ceremony.'",
      ["be", "is", "was", "being"], "be",
      "After verbs like 'insisted that', the subjunctive form 'be' is used regardless of the subject."),
  _eq("Choose the option that best completes the sentence: 'The twins look so alike that even their parents sometimes ___ them.'",
      ["confuse", "confuses", "confusing", "to confuse"], "confuse",
      "The subject 'parents' is plural, so the base form 'confuse' is the correct present-tense verb."),
  _eq("Choose the option that best completes the sentence: '___ of the two candidates has the required experience.'",
      ["Neither", "Both", "All", "Few"], "Neither",
      "'Neither... has' is used with exactly two items when referring to them jointly in the negative, taking a singular verb."),
  _eq("Choose the option that best completes the sentence: 'The committee has finalised ___ recommendations.'",
      ["its", "their", "it's", "his"], "its",
      "'Committee' is treated as a singular collective noun here, so the singular possessive 'its' is correct."),
  _eq("Choose the option that best completes the sentence: 'This is the same book ___ I lost last year.'",
      ["that", "who", "whom", "whose"], "that",
      "'That' is the correct relative pronoun to refer back to the object 'book'."),
  _eq("Choose the option that best completes the sentence: 'The workers went on strike, ___ halted production for a week.'",
      ["which", "who", "whom", "what"], "which",
      "'Which' correctly introduces a non-restrictive clause referring back to the whole preceding action (the strike)."),
  _eq("Choose the option that best completes the sentence: 'Not until the results were announced ___ she relax.'",
      ["did", "she did", "would", "had"], "did",
      "'Not until' at the start of a sentence triggers subject-verb inversion, requiring 'did she relax'."),

  // --- Figures of speech ---
  _eq("Identify the figure of speech used: 'The classroom was as silent as a graveyard during the test.'",
      ["Simile", "Metaphor", "Personification", "Hyperbole"], "Simile",
      "The comparison uses 'as...as' to directly liken two unlike things, which is the defining feature of a simile."),
  _eq("Identify the figure of speech used: 'Time is a thief that steals our youth.'",
      ["Metaphor", "Simile", "Onomatopoeia", "Alliteration"], "Metaphor",
      "Time is directly described as being 'a thief' without using 'like' or 'as', which is characteristic of a metaphor."),
  _eq("Identify the figure of speech used: 'I have told you a million times to clean your room.'",
      ["Hyperbole", "Understatement", "Simile", "Metaphor"], "Hyperbole",
      "The exaggerated claim of 'a million times' is used for emphasis rather than literal truth, making it a hyperbole."),
  _eq("Identify the figure of speech used: 'The bees buzzed lazily among the flowers.'",
      ["Onomatopoeia", "Personification", "Metaphor", "Simile"], "Onomatopoeia",
      "'Buzzed' imitates the actual sound made by bees, which is the defining feature of onomatopoeia."),
  _eq("Identify the figure of speech used: 'Peter Piper picked a peck of pickled pepper.'",
      ["Alliteration", "Assonance", "Onomatopoeia", "Rhyme"], "Alliteration",
      "The repetition of the initial 'p' sound across several words is a classic example of alliteration."),
  _eq("Identify the figure of speech used: 'The fire station burned down.'",
      ["Irony", "Metaphor", "Simile", "Personification"], "Irony",
      "It is ironic that a fire station, meant to fight fires, would itself burn down, creating an unexpected contradiction."),
  _eq("Identify the figure of speech used: 'It's just a small scratch,' he said, though the car was completely wrecked.",
      ["Understatement", "Hyperbole", "Personification", "Metaphor"], "Understatement",
      "Describing a completely wrecked car as 'just a small scratch' deliberately downplays the severity, which is an understatement."),
  _eq("Identify the figure of speech used: 'The stars danced playfully in the moonless sky.'",
      ["Personification", "Simile", "Metaphor", "Onomatopoeia"], "Personification",
      "Giving the stars the human ability to 'dance playfully' attributes human action to a non-human thing, which is personification."),

  // --- Idioms and proverbs ---
  _eq("Choose the option nearest in meaning to the idiom: 'He decided to BITE THE BULLET and confront his boss about the issue.'",
      ["Face a difficult situation with courage", "Avoid a difficult situation entirely", "Celebrate an unexpected success", "Complain loudly to everyone"], "Face a difficult situation with courage",
      "'Bite the bullet' means to bravely endure a painful or difficult situation that is unavoidable."),
  _eq("What does the proverb 'A stitch in time saves nine' mean?",
      ["Dealing with a problem early prevents it from becoming worse", "It is better to work slowly than quickly", "Nine problems are worse than one", "Sewing is more important than other skills"], "Dealing with a problem early prevents it from becoming worse",
      "This proverb teaches that prompt action on a small problem prevents it from growing into a much bigger one."),
  _eq("What does the proverb 'Don't count your chickens before they hatch' mean?",
      ["Do not assume something will happen before it actually does", "Always count your possessions carefully", "Chickens are more valuable than they appear", "Wait until night to make plans"], "Do not assume something will happen before it actually does",
      "This proverb warns against making plans based on events that have not yet happened."),
  _eq("Choose the option nearest in meaning to the idiom: 'She let the cat out of the bag during the party.'",
      ["She revealed a secret accidentally", "She brought a pet to the party", "She left the party early", "She played a prank on someone"], "She revealed a secret accidentally",
      "'Let the cat out of the bag' means to accidentally reveal a secret."),
  _eq("What does the proverb 'Every cloud has a silver lining' mean?",
      ["Even difficult situations have some positive aspect", "Clouds are always followed by rain", "Silver is more valuable than gold", "Bad situations never improve"], "Even difficult situations have some positive aspect",
      "This proverb teaches that even the worst situations contain some hopeful or positive element."),
  _eq("Choose the option nearest in meaning to the idiom: 'He was clearly BURNING THE MIDNIGHT OIL before the exams.'",
      ["Studying or working late into the night", "Wasting fuel unnecessarily", "Sleeping through an important event", "Ignoring his responsibilities completely"], "Studying or working late into the night",
      "'Burning the midnight oil' means working or studying late into the night."),
  _eq("What does the proverb 'Actions speak louder than words' mean?",
      ["What a person does matters more than what they say", "Loud speaking is more persuasive than quiet speaking", "Words are more important than actions", "Silence is the best form of communication"], "What a person does matters more than what they say",
      "This proverb emphasises that a person's deeds reveal their true character more than their statements do."),
  _eq("Choose the option nearest in meaning to the idiom: 'The negotiations finally reached a point where both sides had to BURY THE HATCHET.'",
      ["Agree to end a conflict and make peace", "Start a new war", "Hide evidence of wrongdoing", "Bury physical objects underground"], "Agree to end a conflict and make peace",
      "'Bury the hatchet' means to end a conflict and become friendly again."),

  // --- Oral English: phonetics, stress and rhyme ---
  _eq("Which of the following words has the same vowel sound as the underlined letters in 'BOOK'?",
      ["Look", "Boot", "Boat", "Bore"], "Look",
      "'Book' is pronounced with the short vowel sound /u/ as in 'look'; 'boot', 'boat' and 'bore' all use different vowel sounds."),
  _eq("Which of the following words carries the primary stress on the FIRST syllable?",
      ["PHOtograph", "phoTOgraphy", "photoGRAPHic", "phoTOgrapher"], "PHOtograph",
      "'Photograph' is stressed on the first syllable (PHO-to-graph), while related forms shift the stress to later syllables."),
  _eq("Which of the following words does NOT rhyme with 'FLOOR'?",
      ["FLOUR", "MORE", "DOOR", "POUR"], "FLOUR",
      "'Floor', 'more', 'door' and 'pour' all end with the same vowel sound; 'flour' has a different vowel sound and does not rhyme with them."),
  _eq("Which of the following words has a SILENT consonant?",
      ["Honest", "Hostel", "Hover", "Habit"], "Honest",
      "'Honest' has a silent 'h' at the beginning, unlike 'hostel', 'hover' and 'habit', where the 'h' is pronounced."),
  _eq("In which of the following words is the underlined letters 'ch' pronounced differently from the others?",
      ["Machine", "Chair", "Church", "Chicken"], "Machine",
      "In 'machine', 'ch' is pronounced /sh/, while in 'chair', 'church' and 'chicken' it is pronounced /ch/ as in 'church'."),
  _eq("Which of the following words carries the primary stress on the SECOND syllable?",
      ["Begin", "Open", "Table", "Window"], "Begin",
      "'Begin' is stressed on its second syllable (be-GIN), while 'open', 'table' and 'window' are stressed on their first syllable."),
  _eq("Which of the following words rhymes with 'THROUGH'?",
      ["Blue", "Though", "Tough", "Plough"], "Blue",
      "'Through' and 'blue' share the same long vowel sound /oo/; 'though', 'tough' and 'plough' are pronounced differently."),
  _eq("Which of the following words has a different stress pattern from the other three?",
      ["Import (noun)", "Export (noun)", "Object (noun)", "Present (verb)"], "Present (verb)",
      "The nouns 'import', 'export' and 'object' are stressed on the first syllable, while the verb 'present' shifts its stress to the second syllable."),
  _eq("Which of the following words contains a diphthong in its pronunciation?",
      ["Coin", "Pin", "Tin", "Sin"], "Coin",
      "'Coin' contains the diphthong /oi/, a glide between two vowel sounds, unlike 'pin', 'tin' and 'sin', which have a single short vowel sound."),
  _eq("Which of the following words is pronounced with a long vowel sound, unlike the others?",
      ["Sheep", "Ship", "Sit", "Bit"], "Sheep",
      "'Sheep' is pronounced with the long vowel sound /ee/, while 'ship', 'sit' and 'bit' all use the short vowel sound /i/."),

  // --- Spelling ---
  _eq("Which of the following is the correctly spelled word?",
      ["Necessary", "Neccessary", "Necesary", "Neccesary"], "Necessary",
      "'Necessary' is correctly spelt with one 'c' and two 's'; the other options are misspellings."),
  _eq("Select the correctly spelled word from the options below.",
      ["Embarrass", "Embarass", "Embarras", "Emmbarrass"], "Embarrass",
      "'Embarrass' is correctly spelt with double 'r' and double 's'; the other options are misspellings."),
  _eq("Pick out the word that is spelt correctly.",
      ["Maintenance", "Maintainance", "Maintenence", "Maintainence"], "Maintenance",
      "'Maintenance' is correctly spelt with 'ten' rather than 'tain' before the final 'ance'; the other options are misspellings."),
  _eq("Which option shows the correct spelling of the word?",
      ["Rhythm", "Rythm", "Rhythem", "Rhythim"], "Rhythm",
      "'Rhythm' is correctly spelt with 'rh' at the start and no vowel between 'th' and 'm'; the other options are misspellings."),
  _eq("Choose the word spelt without any error.",
      ["Questionnaire", "Questionaire", "Questionnairre", "Quiestionnaire"], "Questionnaire",
      "'Questionnaire' is correctly spelt with double 'n' before 'aire'; the other options are misspellings."),
  _eq("Identify the option that is free of spelling errors.",
      ["Pronunciation", "Pronounciation", "Pronunciasion", "Pronaunciation"], "Pronunciation",
      "'Pronunciation' is correctly spelt without the 'o' found in 'pronounce'; the other options are common misspellings."),

  // --- Punctuation ---
  _eq("Which of the following sentences uses a comma correctly after an introductory clause?",
      ["Although it rained, the match continued.", "Although it rained the match, continued.", "Although, it rained the match continued.", "Although it rained the match continued"], "Although it rained, the match continued.",
      "A comma should follow an introductory subordinate clause before the main clause begins, as in 'Although it rained, the match continued.'"),
  _eq("Which of the following sentences correctly punctuates the non-restrictive clause describing the students?",
      ["The students, who studied hard, passed the exam.", "The students who studied hard, passed the exam.", "The students, who studied hard passed the exam.", "The students who, studied hard passed the exam."], "The students, who studied hard, passed the exam.",
      "A non-restrictive relative clause must be enclosed by a pair of commas, one before and one after the clause."),
  _eq("Which of the following sentences correctly uses an apostrophe to show that the toys belong to the children?",
      ["The children's toys were scattered on the floor.", "The childrens' toys were scattered on the floor.", "The childrens toys were scattered on the floor.", "The children toys' were scattered on the floor."], "The children's toys were scattered on the floor.",
      "'Children' is already plural without an 's', so the possessive is formed by adding apostrophe-s: 'children's'."),
  _eq("Which of the following sentences correctly uses a colon to introduce a list of three items?",
      ["We need three items: rice, beans and garri.", "We need three items, rice, beans and garri.", "We need three items; rice, beans and garri.", "We need three items rice, beans and garri."], "We need three items: rice, beans and garri.",
      "A colon is the correct punctuation mark to introduce a list following a complete independent clause."),
  _eq("Which of the following sentences correctly punctuates the reported statement about the report?",
      ["The manager said that the report was ready.", "The manager said, that the report was ready.", "The manager said that, the report was ready.", "The manager said that the report, was ready."], "The manager said that the report was ready.",
      "In reported speech introduced by 'that', no comma is needed before or within the reported clause."),

  // --- Reading comprehension: solar mini-grids passage ---
  _ucq2("According to the passage, how do solar-powered mini-grids differ from large centralised power stations?",
      ["They generate electricity close to where it is consumed", "They require longer transmission lines than centralised stations", "They are exclusively used for street lighting", "They are managed directly by the national grid operator"], "They generate electricity close to where it is consumed",
      "The passage states that mini-grids 'generate electricity close to where it is consumed', unlike large centralised stations."),
  _ucq2("What cost-related advantage do proponents claim for mini-grids, according to the passage?",
      ["They avoid the enormous cost and delay of extending national transmission lines", "They are completely free to install", "They eliminate the need for any batteries", "They are funded entirely by student tuition fees"], "They avoid the enormous cost and delay of extending national transmission lines",
      "The passage says proponents argue the approach 'sidesteps the enormous cost and years-long delay of extending national transmission lines'."),
  _ucq2("What environmental benefit does the passage attribute to solar mini-grids?",
      ["Reducing the diesel fumes that once hung over generator-powered halls of residence", "Eliminating all forms of air travel on campus", "Ending the use of electricity entirely", "Preventing all forms of noise pollution"], "Reducing the diesel fumes that once hung over generator-powered halls of residence",
      "The passage notes the approach helps in 'reducing the diesel fumes that once hung over generator-powered halls of residence'."),
  _ucq2("What concern do sceptics raise about the upfront cost and maintenance of solar mini-grids?",
      ["Panels can lose a significant share of their efficiency within a decade if poorly maintained", "Solar panels never lose efficiency under any conditions", "The government fully subsidises all maintenance costs", "Mini-grids require no batteries at all"], "Panels can lose a significant share of their efficiency within a decade if poorly maintained",
      "The passage states sceptics counter that 'panels can lose a significant share of their efficiency within a decade if poorly maintained'."),
  _ucq2("What limitation of mini-grids do sceptics point out regarding neighbouring departments?",
      ["A mini-grid serving one faculty does nothing to solve the electricity problems of neighbouring departments left off the scheme", "Mini-grids automatically supply the entire campus at once", "Neighbouring departments receive priority access over the pilot hostels", "Mini-grids have been banned in departments outside the pilot"], "A mini-grid serving one faculty does nothing to solve the electricity problems of neighbouring departments left off the scheme",
      "The passage says a mini-grid 'serving one faculty does nothing to solve the electricity problems of neighbouring departments left off the scheme'."),
  _ucq2("What do administrators say about the financial payback of the investment, according to the passage?",
      ["The investment already pays for itself within a few years through reduced diesel purchases", "The investment will never be recovered", "The investment is recovered only after several decades", "The investment costs are borne entirely by donor countries"], "The investment already pays for itself within a few years through reduced diesel purchases",
      "The passage concludes that administrators say 'the investment already pays for itself within a few years through reduced diesel purchases'."),
  _ucq2("What is the closest meaning of the word 'sidesteps' as used in the passage?",
      ["Avoids", "Confronts directly", "Increases", "Publicises"], "Avoids",
      "'Sidesteps' means to avoid dealing with something directly, fitting the context of avoiding cost and delay."),

  // --- Reading comprehension: declining reading culture passage ---
  _ucq3("According to the passage, what specifically worries librarians about teenagers' reading habits?",
      ["A declining culture of sustained reading, even though literacy rates are rising", "A total inability among teenagers to read at all", "An excessive amount of time spent on assigned classroom texts", "A sharp decline in the number of libraries nationwide"], "A declining culture of sustained reading, even though literacy rates are rising",
      "The passage states librarians worry about 'a declining culture of sustained reading among teenagers, even as literacy rates on paper continue to rise'."),
  _ucq3("What do some educators blame for the perceived decline in reading, according to the passage?",
      ["The smartphone and its endless stream of short videos", "The rising cost of printed novels", "A shortage of trained librarians", "The introduction of new examination formats"], "The smartphone and its endless stream of short videos",
      "The passage says some educators 'blame the smartphone directly, arguing that its endless stream of short videos has shortened attention spans'."),
  _ucq3("How do others in the passage push back against the smartphone-blaming narrative?",
      ["They note teenagers consume enormous quantities of text daily through messaging and online forums", "They argue teenagers no longer own smartphones", "They claim reading levels have collapsed entirely", "They insist libraries should be closed"], "They note teenagers consume enormous quantities of text daily through messaging and online forums",
      "The passage notes others push back by 'noting that teenagers today consume enormous quantities of text daily through messaging and online forums'."),
  _ucq3("What alternative explanation is suggested for the reading concern, according to the passage?",
      ["A mismatch between assigned classroom texts and what young readers actually find engaging", "A complete absence of libraries in schools", "A ban on all forms of reading in schools", "An oversupply of engaging assigned literature"], "A mismatch between assigned classroom texts and what young readers actually find engaging",
      "The passage suggests 'the real issue is a mismatch between assigned classroom texts and what young readers actually find engaging'."),
  _ucq3("What did schools that let students choose their own novels report, according to the passage?",
      ["A modest but noticeable uptick in enthusiasm", "A dramatic collapse in student interest", "No change whatsoever in reading habits", "An outright rejection of the reading period by students"], "A modest but noticeable uptick in enthusiasm",
      "The passage states such schools 'report a modest but noticeable uptick in enthusiasm, if not yet in the reading of assigned literature'."),
  _ucq3("What is the closest meaning of the word 'ordeal' as used in the passage?",
      ["A difficult and unpleasant experience", "A pleasant and relaxing pastime", "A brief and effortless task", "A rewarding financial opportunity"], "A difficult and unpleasant experience",
      "'Ordeal' refers to a painful or difficult experience, fitting the description of a short story feeling burdensome to read."),
];

final _mathematics = [
  _mq("Simplify: 4(x + 3) - 2(x - 5)",
      ["2x + 22", "2x + 2", "6x + 2", "2x - 2"], "2x + 22",
      "4(x+3) - 2(x-5) = 4x + 12 - 2x + 10 = 2x + 22."),
  _mq("Solve for x: 5x - 7 = 18",
      ["x = 5", "x = 25", "x = 2.2", "x = 3.6"], "x = 5",
      "5x - 7 = 18, so 5x = 25, giving x = 5."),
  _mq("What is the value of 3^4?",
      ["81", "12", "34", "64"], "81",
      "3^4 = 3x3x3x3 = 81."),
  _mq("Simplify: (2/3) - (1/6)",
      ["1/2", "1/3", "3/6", "1/9"], "1/2",
      "Using a common denominator of 6: (2/3 = 4/6) - (1/6) = 3/6 = 1/2."),
  _mq("Find x if 6x + 3 = 3x + 21",
      ["x = 6", "x = 3", "x = 8", "x = 18"], "x = 6",
      "6x + 3 = 3x + 21, so 3x = 18, giving x = 6."),
  _mq("What is 15% of 480?",
      ["72", "48", "64", "120"], "72",
      "15% of 480 = 0.15 x 480 = 72."),
  _mq("The average of 8 numbers is 12. What is their sum?",
      ["96", "12", "20", "84"], "96",
      "Sum = average x count = 12 x 8 = 96."),
  _mq("Solve: x^2 - 25 = 0",
      ["x = 5 or x = -5", "x = 25 or x = -25", "x = 5 only", "x = -25 only"], "x = 5 or x = -5",
      "x^2 = 25, so x = sqrt(25) = +-5, giving x = 5 or x = -5."),
  _mq("If the ratio of black to white marbles is 3:7 and there are 9 black marbles, how many white marbles are there?",
      ["21", "18", "24", "63"], "21",
      "3 parts = 9, so 1 part = 3. White marbles = 7 parts = 7 x 3 = 21."),
  _mq("What is the perimeter of a rectangle with length 12cm and width 5cm?",
      ["34cm", "60cm", "17cm", "24cm"], "34cm",
      "Perimeter of a rectangle = 2(length + width) = 2(12+5) = 2 x 17 = 34cm."),
  _mq("What is the area of a circle with radius 7cm? (Use pi = 22/7)",
      ["154 cm^2", "44 cm^2", "49 cm^2", "22 cm^2"], "154 cm^2",
      "Area = pi r^2 = (22/7) x 7 x 7 = 22 x 7 = 154 cm^2."),
  _mq("Simplify: 2^3 x 2^4",
      ["2^7 = 128", "2^12", "4^7", "2^1 = 2"], "2^7 = 128",
      "When multiplying powers with the same base, add the exponents: 2^3 x 2^4 = 2^7 = 128."),
  _mq("What is the value of the square root of 196?",
      ["14", "13", "98", "49"], "14",
      "The square root of 196 is 14, since 14 x 14 = 196."),
  _mq("A motorist travels 120km in 4 hours. What is their average speed?",
      ["30 km/h", "480 km/h", "40 km/h", "24 km/h"], "30 km/h",
      "Average speed = distance/time = 120/4 = 30 km/h."),
  _mq("Solve for x: (x/5) - 2 = 3",
      ["x = 25", "x = 5", "x = 10", "x = 1"], "x = 25",
      "(x/5) = 5, so x = 25."),
  _mq("What is the sum of the interior angles of a heptagon (7 sides)?",
      ["900 degrees", "720 degrees", "540 degrees", "1080 degrees"], "900 degrees",
      "The sum of interior angles of a polygon = (n-2) x 180, so for a heptagon (n=7): (7-2) x 180 = 900 degrees."),
  _mq("What is the sum of the interior angles of an octagon (8 sides)?",
      ["1080 degrees", "900 degrees", "720 degrees", "1260 degrees"], "1080 degrees",
      "Using (n-2) x 180 for an octagon (n=8): (8-2) x 180 = 1080 degrees."),
  _mq("Factorise: x^2 - 9x + 20",
      ["(x - 4)(x - 5)", "(x + 4)(x + 5)", "(x - 2)(x - 10)", "(x + 20)(x - 1)"], "(x - 4)(x - 5)",
      "We need two numbers that multiply to 20 and add to -9: -4 and -5. So x^2-9x+20 = (x-4)(x-5)."),
  _mq("What is 0.75 expressed as a fraction in its lowest terms?",
      ["3/4", "75/100", "7/10", "2/3"], "3/4",
      "0.75 = 75/100, which simplifies to 3/4 when divided by 25."),
  _mq("If a = 4 and b = -2, find the value of a^2 - b^2",
      ["12", "20", "16", "8"], "12",
      "a^2 - b^2 = 16 - 4 = 12."),
  _mq("What is the median of the data set: 2, 7, 9, 13, 18?",
      ["9", "7", "13", "9.8"], "9",
      "With 5 values arranged in order (2,7,9,13,18), the median is the middle value: 9."),
  _mq("What is the mode of the data set: 4, 6, 6, 7, 9, 6, 10?",
      ["6", "7", "9", "10"], "6",
      "The mode is the most frequently occurring value; 6 appears three times, more than any other value."),
  _mq("Convert 3/8 to a percentage.",
      ["37.5%", "38%", "3.8%", "83%"], "37.5%",
      "3/8 = 0.375, which as a percentage is 37.5%."),
  _mq("What is the LCM (Lowest Common Multiple) of 9 and 12?",
      ["36", "108", "21", "3"], "36",
      "Multiples of 9: 9,18,27,36...; multiples of 12: 12,24,36...; the smallest common multiple is 36."),
  _mq("What is the HCF (Highest Common Factor) of 24 and 36?",
      ["12", "6", "72", "4"], "12",
      "The factors of 24 are 1,2,3,4,6,8,12,24; factors of 36 are 1,2,3,4,6,9,12,18,36; the highest common factor is 12."),
  _mq("If 2x + 3y = 18 and x = 3, find the value of y.",
      ["4", "6", "8", "2"], "4",
      "Substituting x=3: 2(3) + 3y = 18, so 6 + 3y = 18, giving 3y = 12, so y = 4."),
  _mq("A trader sells an item for N9,000 after a 25% discount on the original price. What was the original price?",
      ["N12,000", "N11,250", "N7,200", "N9,900"], "N12,000",
      "If N9,000 represents 75% of the original price, then original price = 9,000/0.75 = N12,000."),
  _mq("What is the next number in the sequence: 4, 12, 36, 108, ___?",
      ["324", "216", "432", "144"], "324",
      "Each term is multiplied by 3 to get the next term: 108 x 3 = 324."),
  _mq("Simplify: (5a^3b) x (3ab^2)",
      ["15a^4b^3", "8a^4b^3", "15a^3b^2", "8a^3b^2"], "15a^4b^3",
      "Multiplying coefficients: 5x3=15. Multiplying a terms: a^3 x a = a^4. Multiplying b terms: b x b^2 = b^3. Result: 15a^4b^3."),
  _mq("What is the value of x in the equation: 3(x - 2) = 2(x + 4)",
      ["x = 14", "x = 4", "x = 2", "x = 10"], "x = 14",
      "3x - 6 = 2x + 8, so 3x - 2x = 8 + 6, giving x = 14."),
  _mq("A rectangular plot has an area of 200 square metres and a width of 8 metres. What is its length?",
      ["25 metres", "8 metres", "20 metres", "16 metres"], "25 metres",
      "Length = Area/Width = 200/8 = 25 metres."),
  _mq("What is the probability of picking a blue ball from a bag containing 5 blue and 7 red balls?",
      ["5/12", "1/5", "7/12", "1/7"], "5/12",
      "Total balls = 5 + 7 = 12. Probability of blue = 5/12."),
  _mq("Express 3.6 x 10^3 as an ordinary number.",
      ["3,600", "360", "36,000", "0.0036"], "3,600",
      "3.6 x 10^3 = 3.6 x 1000 = 3,600."),
  _mq("What is the value of the square root of 144 plus the square root of 81?",
      ["21", "18", "225", "13"], "21",
      "Square root of 144 is 12 and square root of 81 is 9, so 12 + 9 = 21."),

  // --- Indices, logarithms and number bases ---
  _mq("Simplify: 5^3 ÷ 5",
      ["25", "5", "125", "15"], "25",
      "5^3 ÷ 5^1 = 5^(3-1) = 5^2 = 25."),
  _mq("Evaluate: 2^-3",
      ["1/8", "-8", "8", "-1/8"], "1/8",
      "A negative exponent gives a reciprocal: 2^-3 = 1/2^3 = 1/8."),
  _mq("Simplify: x^5 ÷ x^2",
      ["x^3", "x^7", "x^2.5", "x^10"], "x^3",
      "When dividing powers with the same base, subtract the exponents: x^5 ÷ x^2 = x^(5-2) = x^3."),
  _mq("Evaluate: 9^(1/2)",
      ["3", "4.5", "18", "81"], "3",
      "A power of 1/2 represents a square root: 9^(1/2) = sqrt(9) = 3."),
  _mq("Evaluate: 27^(1/3)",
      ["3", "9", "3^3", "1/3"], "3",
      "A power of 1/3 represents a cube root: 27^(1/3) = cube root of 27 = 3, since 3x3x3 = 27."),
  _mq("Simplify: (2^3)^2",
      ["64", "32", "16", "512"], "64",
      "When raising a power to a power, multiply the exponents: (2^3)^2 = 2^6 = 64."),
  _mq("If log base 10 of 100 = x, find x.",
      ["2", "10", "100", "1"], "2",
      "Since 10^2 = 100, log base 10 of 100 = 2."),
  _mq("Evaluate: log base 2 of 8",
      ["3", "4", "2", "8"], "3",
      "Since 2^3 = 8, log base 2 of 8 = 3."),
  _mq("Convert 1011 (base 2) to base 10.",
      ["11", "13", "9", "10"], "11",
      "1011(2) = (1x8) + (0x4) + (1x2) + (1x1) = 8 + 0 + 2 + 1 = 11."),
  _mq("Convert 25 (base 10) to base 2.",
      ["11001", "11010", "10101", "11101"], "11001",
      "25 = 16 + 8 + 0 + 0 + 1, so in binary this is 11001, since 16(1)+8(1)+4(0)+2(0)+1(1) = 25."),
  _mq("Convert 23 (base 5) to base 10.",
      ["13", "10", "15", "23"], "13",
      "23(5) = (2x5) + (3x1) = 10 + 3 = 13."),
  _mq("Simplify: 3^2 x 3^-1",
      ["3", "9", "1/3", "27"], "3",
      "When multiplying powers with the same base, add the exponents: 3^2 x 3^-1 = 3^(2-1) = 3^1 = 3."),
  _mq("Evaluate: log10 1000 - log10 10",
      ["2", "3", "100", "1"], "2",
      "log10 1000 = 3 and log10 10 = 1, so 3 - 1 = 2."),
  _mq("Evaluate: 16^(3/4)",
      ["8", "12", "64", "4"], "8",
      "16^(1/4) = 2 (since 2^4 = 16), so 16^(3/4) = 2^3 = 8."),
  _mq("Simplify: (2^5 ÷ 2^2) x 2",
      ["16", "8", "32", "64"], "16",
      "2^5 ÷ 2^2 = 2^3 = 8, then 8 x 2 = 16."),

  // --- Algebra: simplification, factorisation and equations ---
  _mq("Simplify: 3x + 5x - 2x",
      ["6x", "8x", "10x", "4x"], "6x",
      "Adding and subtracting like terms: 3x + 5x - 2x = 6x."),
  _mq("Solve for x: 7x - 4 = 3x + 16",
      ["x = 5", "x = 4", "x = 20", "x = 6"], "x = 5",
      "7x - 4 = 3x + 16, so 7x - 3x = 16 + 4, giving 4x = 20, so x = 5."),
  _mq("Expand: (x + 3)(x - 3)",
      ["x^2 - 9", "x^2 + 9", "x^2 - 6x - 9", "x^2 + 6x - 9"], "x^2 - 9",
      "This is a difference of two squares: (x+3)(x-3) = x^2 - 9."),
  _mq("Factorise: x^2 - 16",
      ["(x - 4)(x + 4)", "(x - 8)(x + 2)", "(x - 16)(x + 1)", "(x - 2)(x + 8)"], "(x - 4)(x + 4)",
      "x^2 - 16 is a difference of two squares, since 16 = 4^2, giving (x-4)(x+4)."),
  _mq("Factorise: 2x^2 + 5x - 3",
      ["(2x - 1)(x + 3)", "(2x + 1)(x - 3)", "(x - 1)(2x + 3)", "(2x - 3)(x + 1)"], "(2x - 1)(x + 3)",
      "Splitting the middle term: 2x^2 + 6x - x - 3 = 2x(x+3) - 1(x+3) = (2x-1)(x+3)."),
  _mq("Solve: x^2 - 7x + 12 = 0",
      ["x = 3 or x = 4", "x = -3 or x = -4", "x = 3 or x = -4", "x = 12 or x = 1"], "x = 3 or x = 4",
      "We need two numbers that multiply to 12 and add to -7: -3 and -4. So (x-3)(x-4) = 0, giving x = 3 or x = 4."),
  _mq("Simplify: (3x^2y)(4xy^3)",
      ["12x^3y^4", "7x^3y^4", "12x^2y^3", "12x^3y^3"], "12x^3y^4",
      "Multiplying coefficients: 3x4=12. Multiplying x terms: x^2 x x = x^3. Multiplying y terms: y x y^3 = y^4. Result: 12x^3y^4."),
  _mq("If x + y = 10 and x - y = 4, find the value of x.",
      ["7", "3", "6", "14"], "7",
      "Adding the two equations: 2x = 14, so x = 7."),
  _mq("Make r the subject of the formula A = pi r^2",
      ["r = sqrt(A/pi)", "r = A/pi", "r = sqrt(A) x pi", "r = A^2/pi"], "r = sqrt(A/pi)",
      "Dividing both sides by pi gives r^2 = A/pi, then taking the square root gives r = sqrt(A/pi)."),
  _mq("Simplify: (x^2 - 4)/(x - 2), for x not equal to 2",
      ["x + 2", "x - 2", "x^2 - 2", "2x - 4"], "x + 2",
      "x^2 - 4 factorises to (x-2)(x+2), so dividing by (x-2) leaves x + 2."),
  _mq("Solve the inequality: 3x - 5 > 10",
      ["x > 5", "x < 5", "x > 15", "x > 5/3"], "x > 5",
      "3x - 5 > 10, so 3x > 15, giving x > 5."),
  _mq("Solve: 2(3x - 1) = 4(x + 2)",
      ["x = 5", "x = 3", "x = 10", "x = 2"], "x = 5",
      "6x - 2 = 4x + 8, so 6x - 4x = 8 + 2, giving 2x = 10, so x = 5."),
  _mq("Simplify: (a+b)^2 - (a-b)^2",
      ["4ab", "2ab", "a^2+b^2", "0"], "4ab",
      "(a+b)^2 = a^2+2ab+b^2 and (a-b)^2 = a^2-2ab+b^2; subtracting gives 4ab."),
  _mq("Solve for x: x/3 + x/4 = 7",
      ["x = 12", "x = 7", "x = 84", "x = 21"], "x = 12",
      "Using a common denominator of 12: 4x/12 + 3x/12 = 7, so 7x = 84, giving x = 12."),
  _mq("Factorise completely: 6x^2 - 24",
      ["6(x - 2)(x + 2)", "6(x - 4)(x + 4)", "3(x-2)(x+4)", "(6x-2)(x+2)"], "6(x - 2)(x + 2)",
      "Taking out the common factor 6 first gives 6(x^2-4), which factorises further to 6(x-2)(x+2)."),
  _mq("If f(x) = 2x^2 - 3x + 1, find f(2).",
      ["3", "5", "8", "11"], "3",
      "f(2) = 2(2)^2 - 3(2) + 1 = 8 - 6 + 1 = 3."),
  _mq("Solve: 4(x - 2) - 3(x - 1) = 0",
      ["x = 5", "x = -5", "x = 11", "x = 1"], "x = 5",
      "4x - 8 - 3x + 3 = 0, so x - 5 = 0, giving x = 5."),
  _mq("Simplify: 2(x - 3) + 3(2x + 1)",
      ["8x - 3", "8x + 3", "5x - 3", "8x - 9"], "8x - 3",
      "2(x-3) = 2x - 6, and 3(2x+1) = 6x + 3; adding gives 8x - 3."),
  _mq("Solve for x: (2x+1)/3 = 5",
      ["x = 7", "x = 8", "x = 14", "x = 5"], "x = 7",
      "Multiplying both sides by 3: 2x + 1 = 15, so 2x = 14, giving x = 7."),
  _mq("If 3x - 2y = 12 and y = 3, find the value of x.",
      ["6", "4", "18", "2"], "6",
      "Substituting y=3: 3x - 6 = 12, so 3x = 18, giving x = 6."),

  // --- Sequences and series ---
  _mq("Find the 10th term of the arithmetic progression: 3, 7, 11, 15, ...",
      ["39", "43", "35", "40"], "39",
      "First term a=3, common difference d=4. The nth term is a+(n-1)d, so the 10th term is 3 + 9(4) = 3 + 36 = 39."),
  _mq("Find the sum of the first 10 terms of the arithmetic progression: 2, 5, 8, ...",
      ["155", "150", "160", "145"], "155",
      "a=2, d=3, n=10. Sum = (n/2)(2a+(n-1)d) = 5(4+27) = 5(31) = 155."),
  _mq("Find the common ratio of the geometric progression: 5, 15, 45, 135, ...",
      ["3", "5", "10", "15"], "3",
      "Each term is obtained by multiplying the previous term by 3, since 15/5 = 45/15 = 135/45 = 3."),
  _mq("Find the 6th term of the geometric progression: 2, 6, 18, ...",
      ["486", "162", "1458", "243"], "486",
      "a=2, r=3. The 6th term is a x r^5 = 2 x 3^5 = 2 x 243 = 486."),
  _mq("Find the sum to infinity of the geometric progression: 8, 4, 2, 1, ...",
      ["16", "8", "12", "24"], "16",
      "a=8, r=1/2. Sum to infinity = a/(1-r) = 8/(1-0.5) = 8/0.5 = 16."),
  _mq("Find the nth term of the arithmetic progression with first term 5 and common difference 3.",
      ["3n + 2", "3n + 5", "5n + 3", "3n - 2"], "3n + 2",
      "The nth term is a+(n-1)d = 5+(n-1)3 = 5+3n-3 = 3n+2."),
  _mq("The first term of an arithmetic progression is 4 and the 5th term is 20. Find the common difference.",
      ["4", "5", "16", "3"], "4",
      "T5 = a+4d, so 4+4d=20, giving 4d=16, so d=4."),
  _mq("Find the sum of the first 15 natural numbers (1 to 15).",
      ["120", "105", "225", "110"], "120",
      "Sum = n(n+1)/2 = 15(16)/2 = 240/2 = 120."),
  _mq("Find the 4th term of the sequence given by Tn = 2n^2 - 1.",
      ["31", "15", "32", "17"], "31",
      "T4 = 2(4)^2 - 1 = 2(16) - 1 = 32 - 1 = 31."),
  _mq("In a geometric progression, a = 3 and r = 2, find the sum of the first 5 terms.",
      ["93", "96", "48", "31"], "93",
      "Sum = a(r^n - 1)/(r - 1) = 3(2^5 - 1)/(2-1) = 3(31)/1 = 93."),

  // --- Mensuration ---
  _mq("Find the area of a triangle with base 10cm and height 6cm.",
      ["30 cm^2", "60 cm^2", "16 cm^2", "34 cm^2"], "30 cm^2",
      "Area of a triangle = (1/2) x base x height = (1/2) x 10 x 6 = 30 cm^2."),
  _mq("Find the circumference of a circle of radius 14cm. (Use pi = 22/7)",
      ["88 cm", "44 cm", "308 cm", "176 cm"], "88 cm",
      "Circumference = 2 pi r = 2 x (22/7) x 14 = 2 x 44 = 88 cm."),
  _mq("Find the volume of a cuboid with length 5cm, width 4cm and height 3cm.",
      ["60 cm^3", "12 cm^3", "47 cm^3", "120 cm^3"], "60 cm^3",
      "Volume of a cuboid = length x width x height = 5 x 4 x 3 = 60 cm^3."),
  _mq("Find the area of a trapezium with parallel sides 8cm and 12cm, and height 5cm.",
      ["50 cm^2", "100 cm^2", "40 cm^2", "60 cm^2"], "50 cm^2",
      "Area of a trapezium = (1/2)(sum of parallel sides) x height = (1/2)(8+12) x 5 = (1/2)(20)(5) = 50 cm^2."),
  _mq("Find the volume of a cylinder with radius 7cm and height 10cm. (Use pi = 22/7)",
      ["1540 cm^3", "770 cm^3", "440 cm^3", "3080 cm^3"], "1540 cm^3",
      "Volume = pi r^2 h = (22/7) x 7^2 x 10 = (22/7) x 49 x 10 = 22 x 7 x 10 = 1540 cm^3."),
  _mq("Find the surface area of a cube of side 4cm.",
      ["96 cm^2", "64 cm^2", "24 cm^2", "48 cm^2"], "96 cm^2",
      "Surface area of a cube = 6 x side^2 = 6 x 16 = 96 cm^2."),
  _mq("Find the area of a square whose diagonal is 10cm.",
      ["50 cm^2", "100 cm^2", "25 cm^2", "70.7 cm^2"], "50 cm^2",
      "Area of a square in terms of its diagonal d is d^2/2 = 100/2 = 50 cm^2."),
  _mq("Find the perimeter of a square field of area 81 square metres.",
      ["36 m", "81 m", "18 m", "9 m"], "36 m",
      "Side = sqrt(81) = 9 m. Perimeter = 4 x side = 4 x 9 = 36 m."),
  _mq("A rectangular tank has length 6m, width 4m and height 2m. Find its volume.",
      ["48 m^3", "24 m^3", "12 m^3", "44 m^3"], "48 m^3",
      "Volume = length x width x height = 6 x 4 x 2 = 48 m^3."),
  _mq("Find the area of a circle of diameter 21cm. (Use pi = 22/7)",
      ["346.5 cm^2", "693 cm^2", "173.25 cm^2", "441 cm^2"], "346.5 cm^2",
      "Radius = 10.5cm. Area = pi r^2 = (22/7) x 10.5 x 10.5 = 346.5 cm^2."),
  _mq("Find the volume of a cone with radius 3cm and height 7cm. (Use pi = 22/7)",
      ["66 cm^3", "198 cm^3", "22 cm^3", "132 cm^3"], "66 cm^3",
      "Volume = (1/3) pi r^2 h = (1/3) x (22/7) x 9 x 7 = (1/3) x 22 x 9 = 66 cm^3."),
  _mq("Find the total surface area of a cylinder with radius 7cm and height 3cm. (Use pi = 22/7)",
      ["440 cm^2", "220 cm^2", "132 cm^2", "308 cm^2"], "440 cm^2",
      "Total surface area = 2 pi r(h+r) = 2 x (22/7) x 7 x (3+7) = 2 x 22 x 10 = 440 cm^2."),
  _mq("A right triangle has legs 6cm and 8cm. Find the length of the hypotenuse.",
      ["10 cm", "14 cm", "48 cm", "7 cm"], "10 cm",
      "By Pythagoras' theorem, hypotenuse = sqrt(6^2+8^2) = sqrt(36+64) = sqrt(100) = 10 cm."),
  _mq("Find the area of a parallelogram with base 9cm and height 5cm.",
      ["45 cm^2", "14 cm^2", "22.5 cm^2", "90 cm^2"], "45 cm^2",
      "Area of a parallelogram = base x height = 9 x 5 = 45 cm^2."),
  _mq("Find the length of an arc of a circle of radius 21cm subtending an angle of 60 degrees at the centre. (Use pi = 22/7)",
      ["22 cm", "44 cm", "11 cm", "132 cm"], "22 cm",
      "Arc length = (angle/360) x 2 pi r = (60/360) x 2 x (22/7) x 21 = (1/6) x 132 = 22 cm."),

  // --- Geometry ---
  _mq("Two angles on a straight line are x and 3x. Find the value of x.",
      ["45", "60", "30", "90"], "45",
      "Angles on a straight line sum to 180 degrees, so x + 3x = 180, giving 4x = 180, so x = 45."),
  _mq("Two angles are complementary. If one angle is 35 degrees, find the other.",
      ["55°", "65°", "145°", "35°"], "55°",
      "Complementary angles sum to 90 degrees, so the other angle is 90 - 35 = 55 degrees."),
  _mq("Two angles are supplementary. If one angle is 110 degrees, find the other.",
      ["70°", "80°", "110°", "250°"], "70°",
      "Supplementary angles sum to 180 degrees, so the other angle is 180 - 110 = 70 degrees."),
  _mq("In a triangle, two of the angles are 50 degrees and 60 degrees. Find the third angle.",
      ["70°", "60°", "80°", "50°"], "70°",
      "The angles of a triangle sum to 180 degrees, so the third angle is 180 - 50 - 60 = 70 degrees."),
  _mq("Find the sum of the interior angles of a pentagon (5 sides).",
      ["540°", "360°", "720°", "450°"], "540°",
      "Sum of interior angles = (n-2) x 180. For a pentagon (n=5): (5-2) x 180 = 540°."),
  _mq("Each exterior angle of a regular polygon is 40 degrees. Find the number of sides.",
      ["9", "8", "10", "40"], "9",
      "The number of sides = 360/exterior angle = 360/40 = 9."),
  _mq("Find the size of each interior angle of a regular hexagon.",
      ["120°", "108°", "135°", "60°"], "120°",
      "Sum of interior angles = (6-2) x 180 = 720°. Each angle = 720/6 = 120°."),
  _mq("In triangle ABC, AB = AC and angle B = 70 degrees. Find angle A.",
      ["40°", "70°", "55°", "110°"], "40°",
      "Since AB=AC, the base angles B and C are equal, so angle C = 70°. Angle A = 180 - 70 - 70 = 40°."),
  _mq("In a triangle, the angles are x, 2x and 3x. Find the value of x.",
      ["30°", "60°", "90°", "45°"], "30°",
      "The angles sum to 180 degrees: x + 2x + 3x = 180, so 6x = 180, giving x = 30°."),
  _mq("Two parallel lines are cut by a transversal. If one co-interior angle is 65 degrees, find the other.",
      ["115°", "65°", "25°", "180°"], "115°",
      "Co-interior (allied) angles between parallel lines sum to 180 degrees, so the other angle is 180 - 65 = 115°."),

  // --- Trigonometry ---
  _mq("Find the value of sin 30°.",
      ["0.5", "0.866", "1", "0"], "0.5",
      "sin 30° is a standard trigonometric value equal to 0.5."),
  _mq("Find the value of cos 60°.",
      ["0.5", "0.866", "1", "0"], "0.5",
      "cos 60° is a standard trigonometric value equal to 0.5."),
  _mq("Find the value of tan 45°.",
      ["1", "0", "0.5", "undefined"], "1",
      "tan 45° is a standard trigonometric value equal to 1, since sin 45° equals cos 45°."),
  _mq("In a right triangle, the side opposite an angle is 3cm and the hypotenuse is 5cm. Find sin of the angle.",
      ["0.6", "0.8", "1.67", "0.75"], "0.6",
      "sin(theta) = opposite/hypotenuse = 3/5 = 0.6."),
  _mq("In a right triangle, the side adjacent to an angle is 4cm and the hypotenuse is 5cm. Find cos of the angle.",
      ["0.8", "0.6", "1.25", "0.75"], "0.8",
      "cos(theta) = adjacent/hypotenuse = 4/5 = 0.8."),
  _mq("If tan(theta) = 3/4, find sin(theta), using a right triangle with sides 3, 4 and 5.",
      ["0.6", "0.75", "0.8", "1.33"], "0.6",
      "With opposite=3, adjacent=4, the hypotenuse is 5 (3-4-5 triangle), so sin(theta) = 3/5 = 0.6."),
  _mq("Find the value of sin^2 30° + cos^2 30°.",
      ["1", "0", "0.5", "2"], "1",
      "By the trigonometric identity sin^2(theta) + cos^2(theta) = 1 for any angle theta."),
  _mq("Find the angle theta, where 0° < theta < 90°, if sin(theta) = 0.5.",
      ["30°", "45°", "60°", "90°"], "30°",
      "Since sin 30° = 0.5, theta = 30°."),
  _mq("A ladder leans against a wall making an angle of 60 degrees with the ground. If the foot of the ladder is 3m from the wall, find the length of the ladder. (cos 60° = 0.5)",
      ["6 m", "3 m", "1.5 m", "9 m"], "6 m",
      "cos(60°) = adjacent/hypotenuse, so hypotenuse = 3/0.5 = 6m, giving the ladder length as 6m."),
  _mq("Find the value of cos 0°.",
      ["1", "0", "0.5", "undefined"], "1",
      "cos 0° is a standard trigonometric value equal to 1."),

  // --- Statistics and probability ---
  _mq("Find the mean of the data set: 3, 5, 7, 9, 11.",
      ["7", "6", "9", "35"], "7",
      "Mean = sum of values/number of values = 35/5 = 7."),
  _mq("Find the range of the data set: 12, 18, 7, 25, 9.",
      ["18", "25", "7", "13"], "18",
      "Range = highest value - lowest value = 25 - 7 = 18."),
  _mq("A die is rolled once. Find the probability of getting a number greater than 4.",
      ["1/3", "1/2", "2/3", "1/6"], "1/3",
      "Numbers greater than 4 on a die are 5 and 6, so probability = 2/6 = 1/3."),
  _mq("Two coins are tossed together. Find the probability of getting exactly one head.",
      ["1/2", "1/4", "3/4", "1/3"], "1/2",
      "The possible outcomes are HH, HT, TH, TT. Exactly one head occurs in HT and TH, giving probability 2/4 = 1/2."),
  _mq("Find the mean of the first 6 positive even numbers: 2, 4, 6, 8, 10, 12.",
      ["7", "6", "8", "42"], "7",
      "Sum = 2+4+6+8+10+12 = 42. Mean = 42/6 = 7."),
  _mq("A bag contains 4 red balls and 6 blue balls. Find the probability that a ball picked at random is red.",
      ["2/5", "3/5", "1/5", "4/5"], "2/5",
      "Total balls = 10. Probability of red = 4/10 = 2/5."),
  _mq("Find the mode of the data set: 3, 5, 5, 7, 9, 5, 11.",
      ["5", "7", "9", "3"], "5",
      "The mode is the most frequently occurring value; 5 appears three times, more than any other value."),
  _mq("From a standard pack of 52 playing cards, one card is drawn at random. Find the probability that it is a king.",
      ["1/13", "1/4", "1/52", "4/13"], "1/13",
      "There are 4 kings in a pack of 52 cards, so probability = 4/52 = 1/13."),
  _mq("Find the median of the data set: 5, 11, 2, 8, 14, 3.",
      ["6.5", "8", "5", "6"], "6.5",
      "Arranged in order: 2, 3, 5, 8, 11, 14. With 6 values, the median is the average of the 3rd and 4th: (5+8)/2 = 6.5."),
  _mq("A basket has 3 green, 5 yellow and 2 orange fruits. Find the probability of picking a yellow fruit at random.",
      ["1/2", "1/5", "3/10", "1/10"], "1/2",
      "Total fruits = 10. Probability of yellow = 5/10 = 1/2."),

  // --- Word problems: percentages, ratio and rates ---
  _mq("A trader buys goods for N5,000 and sells them for N6,500. Find the percentage profit.",
      ["30%", "25%", "35%", "20%"], "30%",
      "Profit = 6,500 - 5,000 = 1,500. Percentage profit = (1,500/5,000) x 100 = 30%."),
  _mq("A man's salary is increased from N40,000 to N46,000. Find the percentage increase.",
      ["15%", "10%", "12%", "20%"], "15%",
      "Increase = 46,000 - 40,000 = 6,000. Percentage increase = (6,000/40,000) x 100 = 15%."),
  _mq("Divide N15,000 between two people in the ratio 2:3. Find the smaller share.",
      ["N6,000", "N9,000", "N5,000", "N7,500"], "N6,000",
      "Total parts = 2+3 = 5. Each part = 15,000/5 = 3,000. Smaller share = 2 x 3,000 = N6,000."),
  _mq("A car travels 210km in 3 hours. Find its average speed in km/h.",
      ["70 km/h", "63 km/h", "630 km/h", "207 km/h"], "70 km/h",
      "Average speed = distance/time = 210/3 = 70 km/h."),
  _mq("A sum of N24,000 is shared among three boys in the ratio 1:2:3. Find the largest share.",
      ["N12,000", "N8,000", "N4,000", "N16,000"], "N12,000",
      "Total parts = 1+2+3 = 6. Each part = 24,000/6 = 4,000. Largest share = 3 x 4,000 = N12,000."),
  _mq("The price of an item after a 20% increase is N960. Find the original price.",
      ["N800", "N768", "N1,152", "N900"], "N800",
      "If N960 represents 120% of the original price, original price = 960/1.2 = N800."),
  _mq("A cyclist covers 45km in 1.5 hours. Find the speed.",
      ["30 km/h", "67.5 km/h", "43.5 km/h", "15 km/h"], "30 km/h",
      "Speed = distance/time = 45/1.5 = 30 km/h."),
  _mq("In an exam, a student scored 56 out of 80. Find the percentage score.",
      ["70%", "56%", "80%", "65%"], "70%",
      "Percentage = (56/80) x 100 = 70%."),
  _mq("A shop reduces the price of a shirt from N2,500 to N2,000. Find the percentage discount.",
      ["20%", "25%", "15%", "10%"], "20%",
      "Discount = 2,500 - 2,000 = 500. Percentage discount = (500/2,500) x 100 = 20%."),
  _mq("Three workers, each working at the same rate, can complete a job together in 12 days. How long would it take one worker alone to complete the same job?",
      ["36 days", "4 days", "12 days", "24 days"], "36 days",
      "Working together, their combined rate is 3 times a single worker's rate, so one worker alone takes 3 x 12 = 36 days."),
];

final _generalKnowledge = [
  _gq("The University of Ibadan (UI) is located in which state?",
      ["Oyo State", "Osun State", "Ogun State", "Ondo State"], "Oyo State",
      "The University of Ibadan is located in Ibadan, the capital city of Oyo State."),
  _gq("In what year was the University of Ibadan founded, initially as University College Ibadan?",
      ["1948", "1962", "1975", "1953"], "1948",
      "The University College Ibadan (UCI) was established in 1948, making UI the first degree-awarding institution in Nigeria."),
  _gq("At its founding, University College Ibadan operated under a special academic relationship with which foreign university?",
      ["University of London", "University of Oxford", "University of Cambridge", "University of Edinburgh"], "University of London",
      "UCI operated as a college in special relationship with the University of London, with its degrees initially awarded by that university before UI gained full university status."),
  _gq("In what year did University College Ibadan become a fully independent university able to award its own degrees?",
      ["1962", "1948", "1970", "1976"], "1962",
      "The University of Ibadan attained full university status in 1962, ending its earlier affiliation with the University of London."),
  _gq("By what popular nickname is the University of Ibadan widely known among Nigerian universities?",
      ["First and the Best", "Centre of Excellence", "Great Ife", "Citadel of Learning"], "First and the Best",
      "The University of Ibadan, as Nigeria's oldest university, is popularly nicknamed 'First and the Best'."),
  _gq("Who is generally recognised as the first Nigerian Vice-Chancellor of the University of Ibadan?",
      ["Kenneth Dike", "Wole Soyinka", "Chinua Achebe", "Ade Ajayi"], "Kenneth Dike",
      "Kenneth Onwuka Dike became the first Nigerian Vice-Chancellor of the University of Ibadan, serving in that role in the 1960s."),
  _gq("Which of these celebrated writers studied at University College Ibadan in its early years?",
      ["Wole Soyinka and Chinua Achebe", "Nelson Mandela and Kwame Nkrumah", "Kofi Annan and Desmond Tutu", "Leopold Senghor and Julius Nyerere"], "Wole Soyinka and Chinua Achebe",
      "Both Wole Soyinka and Chinua Achebe were among the early students of University College Ibadan before it became a fully independent university."),
  _gq("Wole Soyinka, an alumnus of University College Ibadan, became the first African to win which major international prize?",
      ["The Nobel Prize in Literature", "The Nobel Peace Prize", "The Pulitzer Prize", "The Man Booker Prize"], "The Nobel Prize in Literature",
      "Wole Soyinka won the Nobel Prize in Literature in 1986, becoming the first African laureate in that category."),
  _gq("The teaching hospital affiliated with the University of Ibadan's College of Medicine, and the first of its kind in Nigeria, is known as?",
      ["University College Hospital (UCH)", "National Hospital Abuja", "Lagos University Teaching Hospital (LUTH)", "Federal Medical Centre"], "University College Hospital (UCH)",
      "University College Hospital (UCH) Ibadan, established in 1957, was Nigeria's first teaching hospital and remains affiliated with the University of Ibadan."),
  _gq("Ibadan, the city that hosts the University of Ibadan, is often described in relation to other West African cities as?",
      ["One of the largest indigenous cities in West Africa", "The smallest city in West Africa", "A city with no historical significance", "A recently founded modern city"], "One of the largest indigenous cities in West Africa",
      "Ibadan is widely described as one of the largest indigenous (pre-colonial, locally founded) cities in West Africa, with a long history predating British colonial rule."),
  _gq("Oyo State, where the University of Ibadan is situated, is officially given which nickname on its state emblem?",
      ["Pacesetter State", "Coal City State", "Food Basket of the Nation", "Centre of Excellence"], "Pacesetter State",
      "Oyo State carries the official nickname 'Pacesetter State', reflecting its historical prominence as part of the former Western Region."),
  _gq("Ibadan's older residential districts are sometimes described by which distinctive visual feature of their rooftops?",
      ["Brown, rusted corrugated iron roofs", "Bright blue thatched roofs", "White marble roofs", "Green solar-panelled roofs"], "Brown, rusted corrugated iron roofs",
      "Older parts of Ibadan are known for a dense spread of rusted, brown corrugated-iron roofing, a familiar sight when viewing the city from its hills."),
  _gq("Oyo State takes its name from which historic pre-colonial Yoruba empire?",
      ["The Old Oyo Empire", "The Benin Empire", "The Sokoto Caliphate", "The Kanem-Bornu Empire"], "The Old Oyo Empire",
      "Oyo State derives its name from the Old Oyo Empire, one of the most powerful pre-colonial Yoruba states in West Africa."),
  _gq("What is the traditional title of the paramount ruler of the Oyo Empire and its successor, the town of Oyo?",
      ["The Alaafin of Oyo", "The Oba of Benin", "The Emir of Oyo", "The Ooni of Oyo"], "The Alaafin of Oyo",
      "The Alaafin of Oyo is the traditional royal title for the ruler of Oyo, historically the head of the powerful Oyo Empire."),
  _gq("The body responsible for accrediting academic programmes in Nigerian universities, including the University of Ibadan, is the?",
      ["National Universities Commission (NUC)", "Joint Admissions and Matriculation Board (JAMB)", "West African Examinations Council (WAEC)", "National Examinations Council (NECO)"], "National Universities Commission (NUC)",
      "The NUC is the regulatory body responsible for approving and accrediting academic programmes offered by Nigerian universities, ensuring they meet minimum quality standards."),
  _gq("Which arm of government in Nigeria is primarily responsible for making laws?",
      ["The Legislature", "The Judiciary", "The Executive", "The Civil Service"], "The Legislature",
      "The Legislature (the National Assembly at federal level) is the arm of government responsible for making laws, distinct from the law-enforcing Executive and law-interpreting Judiciary."),
  _gq("What is the term for the Nigerian legislative chamber whose members represent an entire state, alongside the House of Representatives?",
      ["The Senate", "The House of Assembly", "The Federal Council", "The National Council"], "The Senate",
      "The Senate, together with the House of Representatives, forms Nigeria's bicameral National Assembly, with each state represented by three senators."),
  _gq("Which of the following countries shares a land border with Nigeria?",
      ["Cameroon", "Ghana", "South Africa", "Kenya"], "Cameroon",
      "Nigeria shares land borders with Cameroon, Niger, Chad, and Benin Republic; Ghana, South Africa, and Kenya are not bordering countries."),
  _gq("What is the longest river in Africa?",
      ["The Nile", "The Niger", "The Congo", "The Zambezi"], "The Nile",
      "The Nile, flowing through north-eastern Africa, is the longest river on the continent."),
  _gq("Which of the following best describes the primary function of the Independent National Electoral Commission (INEC)?",
      ["Organising and supervising elections in Nigeria", "Regulating the Nigerian banking sector", "Enforcing traffic laws nationwide", "Managing Nigeria's foreign embassies"], "Organising and supervising elections in Nigeria",
      "INEC is Nigeria's independent body responsible for organising, conducting, and supervising elections at the federal and state levels."),
  _gq("Which cash crop was historically the dominant export of the old Western Region, which included present-day Oyo State?",
      ["Cocoa", "Groundnut", "Cotton", "Rubber"], "Cocoa",
      "Cocoa was the dominant cash crop and export earner of the old Western Region of Nigeria, which included the area now forming Oyo State."),
  _gq("What is the chemical symbol for oxygen?",
      ["O", "Ox", "O2", "Og"], "O",
      "Oxygen's chemical symbol is simply 'O', as assigned on the periodic table of elements."),
  _gq("Which planet is known as the 'Red Planet'?",
      ["Mars", "Venus", "Jupiter", "Saturn"], "Mars",
      "Mars is nicknamed the 'Red Planet' because of the iron oxide (rust) prevalent on its surface, which gives it a reddish appearance."),
  _gq("Which of the following is Cameroon's national football team commonly nicknamed?",
      ["The Indomitable Lions", "The Black Stars", "The Super Eagles", "The Elephants"], "The Indomitable Lions",
      "Cameroon's senior men's national football team is popularly known as the Indomitable Lions, distinct from Nigeria's Super Eagles and Ghana's Black Stars."),
  _gq("Which international body is primarily responsible for global public health coordination?",
      ["The World Health Organization (WHO)", "The World Trade Organization (WTO)", "The United Nations (UN)", "The International Monetary Fund (IMF)"], "The World Health Organization (WHO)",
      "The WHO is the United Nations agency specifically responsible for coordinating international public health matters."),
  _gq("What is the term for a system of government headed by an elected president who is both head of state and head of government?",
      ["Presidential system", "Parliamentary system", "Constitutional monarchy", "Theocracy"], "Presidential system",
      "In a presidential system, the president serves as both head of state and head of government, as is the case in Nigeria's current constitution."),
  _gq("Which of the following best describes the primary function of the Nigerian Customs Service?",
      ["Regulating and collecting duties on goods entering or leaving the country", "Making laws for the federation", "Interpreting the Nigerian constitution", "Managing the country's monetary policy"], "Regulating and collecting duties on goods entering or leaving the country",
      "The Nigerian Customs Service is responsible for regulating the movement of goods across Nigeria's borders and collecting the associated duties and tariffs."),
  _gq("Which of the following is an example of a non-communicable disease?",
      ["Hypertension", "Tuberculosis", "Cholera", "Measles"], "Hypertension",
      "Hypertension (high blood pressure) is a non-communicable condition, unlike tuberculosis, cholera, and measles, which are infectious diseases."),
  _gq("What is the largest country in the world by land area?",
      ["Russia", "Canada", "China", "United States"], "Russia",
      "Russia, spanning parts of both Europe and Asia, is the largest country in the world by total land area."),
  _gq("Who is generally credited with leading the Sokoto Jihad in the early 19th century, later founding the Sokoto Caliphate?",
      ["Uthman Dan Fodio", "Ahmadu Bello", "Usman Aliyu", "Muhammadu Bello"], "Uthman Dan Fodio",
      "Uthman Dan Fodio led the Sokoto Jihad in the early 19th century, a religious and political reform movement that resulted in the founding of the Sokoto Caliphate."),
  _gq("Which of the following best describes the primary role of the judiciary in a democracy?",
      ["Interpreting laws and administering justice", "Making laws for the country", "Implementing government policy exclusively", "Auditing government accounts exclusively"], "Interpreting laws and administering justice",
      "The judiciary interprets the law and administers justice, resolving disputes and checking the powers of the other arms of government."),
  _gq("Which vitamin deficiency is most commonly associated with the disease rickets?",
      ["Vitamin D", "Vitamin C", "Vitamin A", "Vitamin B12"], "Vitamin D",
      "Rickets, a condition causing weak or soft bones in children, is most commonly associated with a deficiency of Vitamin D."),
  _gq("What is the term for the total value of goods and services produced by a country's citizens and businesses, regardless of location?",
      ["Gross National Product (GNP)", "Gross Domestic Product (GDP)", "Net Domestic Income", "Balance of Trade"], "Gross National Product (GNP)",
      "GNP measures output produced by a country's nationals and businesses wherever they are located, unlike GDP which measures output within the country's borders."),
  _gq("What does the abbreviation 'NYSC' stand for in the Nigerian context?",
      ["National Youth Service Corps", "National Youth Skills Council", "Nigerian Youth Service Commission", "National Young Scholars Corps"], "National Youth Service Corps",
      "NYSC is the scheme requiring Nigerian graduates under a certain age to serve the nation for one year, often in a state other than their own."),
  _gq("What is the term for a persistent, sustained rise in the general price level of goods and services in an economy?",
      ["Inflation", "Deflation", "Recession", "Depression"], "Inflation",
      "Inflation describes an ongoing, generalised increase in prices across an economy, reducing the purchasing power of money over time."),
  _gq("Which of the following best describes the primary aim of the Economic Community of West African States (ECOWAS)?",
      ["Promoting economic integration and cooperation among West African countries", "Restricting all trade between West African nations", "Coordinating global internet governance", "Managing international postal services"], "Promoting economic integration and cooperation among West African countries",
      "ECOWAS is a regional political and economic union of West African states aimed at promoting economic integration, free movement, and cooperation among member countries."),
  _gq("What is the term for a government budget in which planned revenue exceeds planned expenditure?",
      ["Surplus budget", "Deficit budget", "Balanced budget", "Zero budget"], "Surplus budget",
      "A surplus budget occurs when a government's expected revenue exceeds its planned spending, the opposite of a deficit budget."),
  _gq("Which of the following is a key function of the Central Bank of Nigeria (CBN) relating to monetary policy?",
      ["Regulating interest rates and the money supply", "Setting the retail price of consumer goods", "Managing Nigeria's road transport infrastructure", "Running the national postal service"], "Regulating interest rates and the money supply",
      "One of the CBN's core functions is formulating and implementing monetary policy, including regulating interest rates and controlling the money supply."),
];
