import "dart:math";

import "../quiz_question.dart";
import "post_utme_common_bank.dart";

QuizQuestion _q(String subject, String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

const _englishSubject = "English Language";
const _mathsSubject = "Mathematics";
const _gkSubject = "General Knowledge";

QuizQuestion _eq(String text, List<String> options, String correct, String explanation) =>
    _q(_englishSubject, text, options, correct, explanation);

QuizQuestion _mq(String text, List<String> options, String correct, String explanation) =>
    _q(_mathsSubject, text, options, correct, explanation);

QuizQuestion _gq(String text, List<String> options, String correct, String explanation) =>
    _q(_gkSubject, text, options, correct, explanation);

const _questionsPerSubject = 10;

List<QuizQuestion> _sample(List<QuizQuestion> pool, int count) {
  final shuffled = List.of(pool)..shuffle(Random());
  return shuffled.take(count).toList();
}

/// University of Lagos (UNILAG) Post-UTME practice bank — 95 questions
/// covering the three areas most Nigerian Post-UTME screening exams draw
/// on: English Language, Mathematics, and General Knowledge (including
/// current affairs). This is a general-purpose practice set, not an
/// official UNILAG past-question paper; always confirm the exact format
/// and syllabus on UNILAG's own screening portal for the current session.
///
/// Each attempt samples 10 questions per subject (30 total, matching the
/// standard Post-UTME practice-test format used across the app) rather than
/// dumping the whole bank into one sitting. The sample pool for each
/// subject combines this school's own questions with the larger shared
/// pool in `post_utme_common_bank.dart` (100 per subject, shared with
/// UNILORIN) for more variety across repeat attempts.
List<QuizQuestion> buildUnilagPostUtmeQuestions() {
  return [
    ..._sample([..._englishLanguage, ...sharedEnglishLanguage], _questionsPerSubject),
    ..._sample([..._mathematics, ...sharedMathematics], _questionsPerSubject),
    ..._sample([..._generalKnowledge, ...sharedGeneralKnowledge], _questionsPerSubject),
  ];
}

const _passage =
    "Traffic congestion has become one of the most visible challenges facing Lagos, a city whose population "
    "has grown far faster than its road network. Commuters routinely spend hours travelling distances that "
    "should take minutes, and the resulting stress and lost productivity carry a real economic cost. In "
    "response, the state government has invested in mass transit options, including a light rail system and "
    "an expanded fleet of high-capacity buses, aiming to reduce the number of private vehicles on the road. "
    "Critics argue that these measures, while welcome, cannot succeed unless they are matched by stricter "
    "enforcement of traffic regulations and continued investment in road infrastructure.";

QuizQuestion _ecq(String question, List<String> options, String correct, String explanation) =>
    _eq("$_passage\n\n$question", options, correct, explanation);

final _englishLanguage = [
  _ecq("According to the passage, why has traffic congestion become a major challenge in Lagos?",
      ["The population has grown faster than the road network", "The state government has banned private cars", "There are no buses operating in the city", "Commuters prefer to walk rather than drive"], "The population has grown faster than the road network",
      "The passage states congestion arises because 'a city whose population has grown far faster than its road network', directly identifying the cause."),
  _ecq("What has the Lagos State government invested in to address the problem, according to the passage?",
      ["A light rail system and an expanded bus fleet", "New private car dealerships", "Reduced fuel prices for commuters", "Free parking spaces across the city"], "A light rail system and an expanded bus fleet",
      "The passage specifically mentions investment in 'a light rail system and an expanded fleet of high-capacity buses' as the government's response."),
  _ecq("What do critics argue is necessary for the government's measures to succeed?",
      ["Stricter enforcement of traffic regulations and continued road investment", "Complete removal of all forms of public transport", "An increase in the number of private vehicles", "Elimination of all traffic regulations"], "Stricter enforcement of traffic regulations and continued road investment",
      "The passage notes critics believe the measures 'cannot succeed unless they are matched by stricter enforcement of traffic regulations and continued investment in road infrastructure.'"),
  _ecq("What is the main economic consequence of traffic congestion mentioned in the passage?",
      ["Lost productivity", "Increased vehicle sales", "Higher government revenue", "Reduced population growth"], "Lost productivity",
      "The passage explicitly mentions 'the resulting stress and lost productivity carry a real economic cost' as a direct consequence of congestion."),
  _ecq("Which word in the passage is closest in meaning to 'visible' as used in the first sentence?",
      ["Apparent", "Hidden", "Minor", "Temporary"], "Apparent",
      "In context, 'visible' describes a challenge that is obvious or apparent to observers, making 'apparent' the closest synonym among the options."),
  _ecq("What is the overall tone of the passage?",
      ["Analytical and balanced, presenting both government action and criticism", "Purely celebratory, with no criticism at all", "Entirely dismissive of any government effort", "Comedic and light-hearted"], "Analytical and balanced, presenting both government action and criticism",
      "The passage presents the problem, the government's response, and critics' reservations in a measured, analytical tone, rather than being purely celebratory or dismissive."),
  _eq("Choose the option that best completes the sentence: 'Neither the students nor the teacher ___ aware of the schedule change.'",
      ["was", "were", "have been", "are"], "was",
      "With 'neither...nor', the verb agrees with the subject closer to it ('the teacher', singular), so the singular verb 'was' is correct."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The manager's decision was final and IRREVOCABLE.'",
      ["Unchangeable", "Temporary", "Debatable", "Uncertain"], "Unchangeable",
      "'Irrevocable' means unable to be changed or reversed, making 'unchangeable' the closest synonym."),
  _eq("Choose the option opposite in meaning to the underlined word: 'The old bridge was considered extremely STURDY.'",
      ["Fragile", "Solid", "Durable", "Reliable"], "Fragile",
      "'Sturdy' means strong and well-built; its opposite is 'fragile', meaning easily broken or damaged."),
  _eq("Choose the correctly spelt word.",
      ["Necessary", "Neccessary", "Necesary", "Neccesarry"], "Necessary",
      "'Necessary' is the correct spelling, with one 'c' and two 's's; the other options misspell the word."),
  _eq("Choose the option that best completes the sentence: 'By the time we arrived, the meeting ___ already ___.'",
      ["had; started", "has; started", "have; start", "will; start"], "had; started",
      "This describes an action completed before another past action, requiring the past perfect tense: 'had already started'."),
  _eq("Choose the correct preposition to complete the sentence: 'She is quite good ___ solving mathematical problems.'",
      ["at", "in", "for", "with"], "at",
      "'Good at' is the standard idiomatic preposition used to describe proficiency in a skill or activity."),
  _eq("Identify the part of speech of the underlined word: 'She spoke SOFTLY to the frightened child.'",
      ["Adverb", "Adjective", "Noun", "Verb"], "Adverb",
      "'Softly' modifies the verb 'spoke', describing how the action was performed, making it an adverb."),
  _eq("Choose the option that is the correct plural form of 'analysis'.",
      ["Analyses", "Analysises", "Analysis's", "Analysi"], "Analyses",
      "'Analysis', derived from Greek, forms its plural irregularly as 'analyses', not by simply adding 's'."),
  _eq("Choose the option that best completes the sentence: 'If I ___ more time, I would have finished the project.'",
      ["had had", "have had", "have", "having"], "had had",
      "This is a third conditional sentence describing an unreal past situation, requiring the past perfect: 'If I had had more time...'"),
  _eq("Choose the option nearest in meaning to the idiom: 'The company decided to CUT CORNERS to save money.'",
      ["Do something in the cheapest or easiest way, often sacrificing quality", "Expand the business rapidly", "Hire more experienced staff", "Increase product prices significantly"], "Do something in the cheapest or easiest way, often sacrificing quality",
      "'Cut corners' is an idiom meaning to do something in a way that saves time or money, often at the expense of quality or thoroughness."),
  _eq("Choose the option that correctly completes the sentence: 'Each of the students ___ required to submit an assignment.'",
      ["is", "are", "were", "have been"], "is",
      "'Each' is treated as singular in formal English, so it takes the singular verb 'is', regardless of the plural noun that follows it."),
  _eq("Choose the word that best completes the sentence: 'The lawyer presented a very ___ argument that convinced the jury.'",
      ["cogent", "cogitate", "cognitive", "cognizant"], "cogent",
      "'Cogent' means clear, logical, and convincing, fitting the description of a persuasive argument; the other options are not correct adjectives in this context."),
  _eq("Choose the correctly punctuated sentence.",
      ["\"Are you coming with us?\" she asked.", "\"Are you coming with us\" she asked?", "Are you coming with us, she asked.", "\"Are you coming with us,\" she asked?"], "\"Are you coming with us?\" she asked.",
      "The question mark belongs inside the closing quotation marks since the quoted material itself is a question, and the sentence correctly ends with a full stop after 'she asked'."),
  _eq("Choose the option that best completes the sentence: 'The committee ___ yet to reach a decision.'",
      ["has", "have", "having", "had have"], "has",
      "'Committee', when treated as a single unit (the more common usage), takes a singular verb 'has'."),
  _eq("Identify the figure of speech used: 'The stars danced playfully in the moonlit sky.'",
      ["Personification", "Simile", "Onomatopoeia", "Hyperbole"], "Personification",
      "Attributing the human action of 'dancing' to stars is an example of personification, giving human qualities to non-human things."),
  _eq("Choose the option nearest in meaning to the underlined word: 'The negotiations reached an AMICABLE settlement.'",
      ["Friendly", "Hostile", "Chaotic", "Delayed"], "Friendly",
      "'Amicable' means characterised by friendliness and absence of discord, making 'friendly' the best synonym."),
  _eq("Choose the correct form of the verb: 'The number of applicants ___ increased significantly this year.'",
      ["has", "have", "were", "are"], "has",
      "'The number of' takes a singular verb because 'number' (not 'applicants') is the grammatical subject, giving 'has increased'."),
  _eq("Choose the option that best completes the sentence: 'He is the man ___ car was stolen last week.'",
      ["whose", "who's", "who", "which"], "whose",
      "'Whose' is the possessive relative pronoun used to show ownership, correctly linking 'the man' to 'his car'."),
  _eq("Choose the word opposite in meaning to the underlined word: 'The new policy was met with widespread APPROVAL.'",
      ["Disapproval", "Support", "Endorsement", "Acceptance"], "Disapproval",
      "'Approval' means agreement or acceptance; its direct opposite is 'disapproval'."),
  _eq("Choose the correct option to complete the sentence: 'Not only did she win the competition, ___ she also broke the record.'",
      ["but", "and", "so", "or"], "but",
      "The correlative construction 'not only...but also' is a standard grammatical pairing used to emphasise two connected points."),
  _eq("Identify the correctly spelt word.",
      ["Occurrence", "Occurence", "Ocurrence", "Occurrance"], "Occurrence",
      "'Occurrence' is correctly spelt with double 'c' and double 'r'; the other options contain spelling errors."),
  _eq("Choose the option that best completes the sentence: 'She is one of the students who ___ always punctual.'",
      ["are", "is", "was", "has been"], "are",
      "In this construction, 'who' refers back to 'students' (plural), so the verb agrees in the plural: 'who are always punctual'."),
  _eq("Choose the option nearest in meaning to the underlined word: 'His explanation was rather AMBIGUOUS.'",
      ["Unclear", "Precise", "Detailed", "Convincing"], "Unclear",
      "'Ambiguous' means open to more than one interpretation or unclear in meaning, making 'unclear' the best synonym."),
  _eq("Choose the correct option: 'Between you and ___, I think the plan will fail.'",
      ["me", "I", "myself", "mine"], "me",
      "After a preposition ('between'), the objective case pronoun 'me' is grammatically correct, not the subjective 'I'."),
  _eq("Choose the option that correctly completes the sentence: 'The teacher, along with her students, ___ preparing for the event.'",
      ["is", "are", "were", "have"], "is",
      "The subject of the sentence is 'the teacher' (singular); the phrase 'along with her students' is a parenthetical addition that does not change the verb's number, so 'is' is correct."),
  _eq("Choose the option that best expresses the meaning of the sentence: 'It is raining cats and dogs outside.'",
      ["It is raining very heavily", "Cats and dogs are falling from the sky", "It is raining lightly", "It has stopped raining"], "It is raining very heavily",
      "'Raining cats and dogs' is an idiomatic expression meaning it is raining very heavily, not to be taken literally."),
  _eq("Choose the word that is nearest in meaning to the underlined word: 'The politician's speech was full of PLATITUDES.'",
      ["Overused, unoriginal remarks", "Deeply original ideas", "Factual statistics", "Strong scientific evidence"], "Overused, unoriginal remarks",
      "'Platitudes' refers to trite, overused remarks that lack originality or depth, often used in a critical sense."),
  _eq("Choose the correct sentence.",
      ["Everyone must bring their own identification card.", "Everyone must bring his identification card only.", "Everyone must bring they identification card.", "Everyone must brought their identification card."], "Everyone must bring their own identification card.",
      "'Everyone' is grammatically singular but is now widely and correctly paired with 'their' as a gender-neutral pronoun in standard modern English usage."),
];

final _mathematics = [
  _mq("Simplify: 3(2x - 5) + 4(x + 3)",
      ["10x - 3", "10x + 3", "6x - 5", "6x + 3"], "10x - 3",
      "3(2x-5) + 4(x+3) = 6x - 15 + 4x + 12 = 10x - 3."),
  _mq("Solve for x: 2x + 7 = 19",
      ["x = 6", "x = 5", "x = 13", "x = 26"], "x = 6",
      "2x + 7 = 19, so 2x = 12, giving x = 6."),
  _mq("What is the value of 3^4?",
      ["81", "12", "64", "27"], "81",
      "3^4 = 3 x 3 x 3 x 3 = 81."),
  _mq("Simplify: (2/3) + (1/4)",
      ["11/12", "3/7", "2/12", "9/12"], "11/12",
      "Using a common denominator of 12: (2/3 = 8/12) + (1/4 = 3/12) = 11/12."),
  _mq("Find the value of x if 5x - 3 = 2x + 12",
      ["x = 5", "x = 3", "x = 9", "x = 15"], "x = 5",
      "5x - 3 = 2x + 12, so 3x = 15, giving x = 5."),
  _mq("What is 15% of 240?",
      ["36", "24", "40", "48"], "36",
      "15% of 240 = 0.15 x 240 = 36."),
  _mq("The average of 5 numbers is 20. What is their sum?",
      ["100", "20", "25", "80"], "100",
      "Sum = average x count = 20 x 5 = 100."),
  _mq("Solve: x^2 - 9 = 0",
      ["x = 3 or x = -3", "x = 9 or x = -9", "x = 3 only", "x = -9 only"], "x = 3 or x = -3",
      "x^2 = 9, so x = sqrt(9) = +-3, giving x = 3 or x = -3."),
  _mq("If the ratio of boys to girls in a class is 3:4 and there are 21 boys, how many girls are there?",
      ["28", "24", "18", "35"], "28",
      "3 parts = 21, so 1 part = 7. Girls = 4 parts = 4 x 7 = 28."),
  _mq("What is the perimeter of a rectangle with length 12cm and width 5cm?",
      ["34cm", "60cm", "17cm", "30cm"], "34cm",
      "Perimeter = 2(length + width) = 2(12+5) = 2(17) = 34cm."),
  _mq("What is the area of a circle with radius 7cm? (Use pi = 22/7)",
      ["154 cm^2", "44 cm^2", "22 cm^2", "308 cm^2"], "154 cm^2",
      "Area = pi r^2 = (22/7) x 7 x 7 = 22 x 7 = 154 cm^2."),
  _mq("Simplify: 2^3 x 2^4",
      ["2^7 = 128", "2^12 = 4096", "2^1 = 2", "4^7"], "2^7 = 128",
      "When multiplying powers with the same base, add the exponents: 2^3 x 2^4 = 2^(3+4) = 2^7 = 128."),
  _mq("What is the value of the square root of 144?",
      ["12", "14", "72", "24"], "12",
      "The square root of 144 is 12, since 12 x 12 = 144."),
  _mq("A car travels 240km in 4 hours. What is its average speed?",
      ["60 km/h", "40 km/h", "80 km/h", "50 km/h"], "60 km/h",
      "Average speed = distance/time = 240/4 = 60 km/h."),
  _mq("Solve for x: (x/3) + 2 = 7",
      ["x = 15", "x = 27", "x = 5", "x = 21"], "x = 15",
      "(x/3) = 5, so x = 15."),
  _mq("What is the sum of the interior angles of a triangle?",
      ["180 degrees", "360 degrees", "90 degrees", "270 degrees"], "180 degrees",
      "The interior angles of any triangle always sum to 180 degrees."),
  _mq("What is the sum of the interior angles of a quadrilateral?",
      ["360 degrees", "180 degrees", "90 degrees", "540 degrees"], "360 degrees",
      "The interior angles of any quadrilateral (four-sided polygon) always sum to 360 degrees."),
  _mq("Factorise: x^2 + 5x + 6",
      ["(x + 2)(x + 3)", "(x + 1)(x + 6)", "(x - 2)(x - 3)", "(x + 6)(x - 1)"], "(x + 2)(x + 3)",
      "We need two numbers that multiply to 6 and add to 5: 2 and 3. So x^2+5x+6 = (x+2)(x+3)."),
  _mq("What is 0.75 expressed as a fraction in its lowest terms?",
      ["3/4", "7/5", "75/10", "1/4"], "3/4",
      "0.75 = 75/100, which simplifies to 3/4 when divided by 25."),
  _mq("If a = 4 and b = -2, find the value of a^2 - b^2",
      ["12", "20", "4", "8"], "12",
      "a^2 - b^2 = 16 - 4 = 12."),
  _mq("What is the median of the data set: 3, 7, 9, 12, 15?",
      ["9", "7", "12", "46/5 = 9.2"], "9",
      "With 5 values arranged in order (3,7,9,12,15), the median is the middle value: 9."),
  _mq("What is the mode of the data set: 2, 4, 4, 5, 7, 4, 8?",
      ["4", "5", "7", "8"], "4",
      "The mode is the most frequently occurring value; 4 appears three times, more than any other value."),
  _mq("Convert 3/8 to a percentage.",
      ["37.5%", "38%", "3.8%", "83.3%"], "37.5%",
      "3/8 = 0.375, which as a percentage is 37.5%."),
  _mq("What is the LCM (Lowest Common Multiple) of 4 and 6?",
      ["12", "24", "10", "2"], "12",
      "Multiples of 4: 4,8,12...; multiples of 6: 6,12,18...; the smallest common multiple is 12."),
  _mq("What is the HCF (Highest Common Factor) of 18 and 24?",
      ["6", "3", "12", "72"], "6",
      "The factors of 18 are 1,2,3,6,9,18; factors of 24 are 1,2,3,4,6,8,12,24; the highest common factor is 6."),
  _mq("If 2x + 3y = 12 and x = 3, find the value of y.",
      ["2", "3", "4", "6"], "2",
      "Substituting x=3: 2(3) + 3y = 12, so 6 + 3y = 12, giving 3y = 6, so y = 2."),
  _mq("A shop sells an item for N4,500 after a 10% discount on the original price. What was the original price?",
      ["N5,000", "N4,950", "N4,050", "N5,500"], "N5,000",
      "If N4,500 represents 90% of the original price, then original price = 4,500/0.9 = N5,000."),
  _mq("What is the next number in the sequence: 2, 6, 18, 54, ___?",
      ["162", "108", "216", "72"], "162",
      "Each term is multiplied by 3 to get the next term: 54 x 3 = 162."),
  _mq("Simplify: (5x^2y) x (3xy^2)",
      ["15x^3y^3", "8x^3y^3", "15x^2y^2", "8x^2y^2"], "15x^3y^3",
      "Multiplying coefficients: 5x3=15. Multiplying x terms: x^2 x x = x^3. Multiplying y terms: y x y^2 = y^3. Result: 15x^3y^3."),
  _mq("What is the value of x in the equation: 3(x - 2) = 2(x + 1)",
      ["x = 8", "x = 4", "x = 6", "x = 2"], "x = 8",
      "3x - 6 = 2x + 2, so 3x - 2x = 2 + 6, giving x = 8."),
  _mq("A rectangular field has an area of 96 square metres and a length of 12 metres. What is its width?",
      ["8 metres", "10 metres", "12 metres", "6 metres"], "8 metres",
      "Width = Area/Length = 96/12 = 8 metres."),
  _mq("What is the probability of rolling a 4 on a fair six-sided die?",
      ["1/6", "1/4", "1/3", "1/2"], "1/6",
      "A fair six-sided die has 6 equally likely outcomes, so the probability of any specific number (like 4) is 1/6."),
  _mq("Express 2.5 x 10^3 as an ordinary number.",
      ["2,500", "250", "25,000", "0.0025"], "2,500",
      "2.5 x 10^3 = 2.5 x 1000 = 2,500."),
];

final _generalKnowledge = [
  _gq("What is the capital city of Nigeria?",
      ["Abuja", "Lagos", "Kano", "Port Harcourt"], "Abuja",
      "Abuja has been Nigeria's official federal capital since 1991, when it replaced Lagos as the seat of government."),
  _gq("The University of Lagos (UNILAG) is located in which state?",
      ["Lagos State", "Ogun State", "Oyo State", "Rivers State"], "Lagos State",
      "UNILAG, established in 1962, is situated in Lagos State, specifically in the Akoka area of Yaba, Lagos."),
  _gq("Which body is responsible for conducting the Unified Tertiary Matriculation Examination (UTME) in Nigeria?",
      ["Joint Admissions and Matriculation Board (JAMB)", "West African Examinations Council (WAEC)", "National Examinations Council (NECO)", "National Universities Commission (NUC)"], "Joint Admissions and Matriculation Board (JAMB)",
      "JAMB is the body responsible for conducting the UTME, the standardised entrance examination for Nigerian tertiary institutions."),
  _gq("Which of the following is the currency used in Nigeria?",
      ["Naira", "Cedi", "Franc", "Rand"], "Naira",
      "The Naira (NGN) is Nigeria's official currency, distinct from the Ghanaian Cedi, the West/Central African Franc, and the South African Rand."),
  _gq("How many states does Nigeria currently have, in addition to the Federal Capital Territory?",
      ["36 states", "30 states", "40 states", "33 states"], "36 states",
      "Nigeria is currently divided into 36 states, plus the Federal Capital Territory (Abuja), following the last state creation exercise in 1996."),
  _gq("Which river is generally regarded as the longest river in Nigeria?",
      ["River Niger", "River Benue", "River Ogun", "River Cross"], "River Niger",
      "The River Niger is the longest river in Nigeria and one of the major rivers of West Africa, giving the country its name."),
  _gq("Which organisation is headquartered in Addis Ababa, Ethiopia, and promotes unity among African states?",
      ["African Union (AU)", "United Nations (UN)", "ECOWAS", "World Health Organization (WHO)"], "African Union (AU)",
      "The African Union, headquartered in Addis Ababa, Ethiopia, works to promote political and economic integration and unity among African nations."),
  _gq("What does the acronym 'ECOWAS' stand for?",
      ["Economic Community of West African States", "European Community of West African States", "Economic Cooperation of West African States", "East and Central West African States"], "Economic Community of West African States",
      "ECOWAS stands for the Economic Community of West African States, a regional group promoting economic integration among West African countries, including Nigeria."),
  _gq("Which Nigerian city is widely regarded as the country's main commercial and financial hub?",
      ["Lagos", "Abuja", "Kano", "Enugu"], "Lagos",
      "Despite Abuja being the federal capital, Lagos remains Nigeria's largest city and its primary commercial, financial, and industrial centre."),
  _gq("Nigeria gained independence from British colonial rule in which year?",
      ["1960", "1963", "1957", "1970"], "1960",
      "Nigeria gained independence from Britain on 1 October 1960, though it did not become a republic until 1963."),
  _gq("Which of the following is the largest continent by land area?",
      ["Asia", "Africa", "North America", "Europe"], "Asia",
      "Asia is the largest continent by land area, followed by Africa as the second largest."),
  _gq("Which gas do humans primarily exhale as a waste product of respiration?",
      ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"], "Carbon dioxide",
      "During respiration, the human body takes in oxygen and releases carbon dioxide as a metabolic waste product."),
  _gq("What is the chemical symbol for water?",
      ["H2O", "CO2", "O2", "NaCl"], "H2O",
      "Water is chemically composed of two hydrogen atoms and one oxygen atom, giving it the formula H2O."),
  _gq("Which planet in our solar system is known as the 'Red Planet'?",
      ["Mars", "Venus", "Jupiter", "Saturn"], "Mars",
      "Mars is commonly called the 'Red Planet' due to iron oxide (rust) on its surface, giving it a reddish appearance."),
  _gq("The Sahara, the world's largest hot desert, is located primarily on which continent?",
      ["Africa", "Asia", "Australia", "South America"], "Africa",
      "The Sahara Desert spans much of North Africa, making it the world's largest hot desert, located on the African continent."),
  _gq("Which of the following is Nigeria's national football team commonly nicknamed?",
      ["The Super Eagles", "The Black Stars", "The Indomitable Lions", "The Bafana Bafana"], "The Super Eagles",
      "Nigeria's senior men's national football team is popularly known as the Super Eagles, distinct from Ghana's Black Stars, Cameroon's Indomitable Lions, and South Africa's Bafana Bafana."),
  _gq("Which international organisation is primarily responsible for maintaining global peace and security?",
      ["The United Nations (UN)", "The World Bank", "The International Monetary Fund (IMF)", "The World Trade Organization (WTO)"], "The United Nations (UN)",
      "The United Nations was established after World War II with the primary mission of maintaining international peace and security among nations."),
  _gq("What is the term for the system of government in which power is divided between a central authority and constituent states, as practised in Nigeria?",
      ["Federalism", "Unitarism", "Monarchy", "Confederalism"], "Federalism",
      "Nigeria operates a federal system of government, constitutionally dividing powers between the federal government and the 36 state governments."),
  _gq("Which of the following best describes the primary function of the Central Bank of Nigeria (CBN)?",
      ["Regulating the money supply and overseeing the banking sector", "Collecting personal income tax directly from citizens", "Running the national postal service", "Managing the country's road transport network"], "Regulating the money supply and overseeing the banking sector",
      "The CBN is Nigeria's apex monetary authority, responsible for regulating the money supply, setting monetary policy, and supervising the banking sector."),
  _gq("Which of the following is an example of a non-communicable disease?",
      ["Hypertension", "Malaria", "Cholera", "Tuberculosis"], "Hypertension",
      "Hypertension (high blood pressure) is a non-communicable disease, unlike malaria, cholera, and tuberculosis, which are all communicable (infectious) diseases."),
  _gq("What is the largest ocean in the world?",
      ["The Pacific Ocean", "The Atlantic Ocean", "The Indian Ocean", "The Arctic Ocean"], "The Pacific Ocean",
      "The Pacific Ocean is the largest and deepest of the world's oceans, covering more area than all the Earth's land combined."),
  _gq("Who is generally credited as the first military Head of State of Nigeria, following the January 1966 coup?",
      ["General Johnson Aguiyi-Ironsi", "General Yakubu Gowon", "General Murtala Mohammed", "General Ibrahim Babangida"], "General Johnson Aguiyi-Ironsi",
      "General Johnson Aguiyi-Ironsi became Nigeria's first military Head of State following the coup of January 1966, before being succeeded later that year by General Yakubu Gowon."),
  _gq("Which of the following best describes the primary role of the National Assembly in Nigeria?",
      ["Making laws for the federation", "Enforcing laws through the police", "Interpreting the constitution exclusively", "Managing the country's foreign embassies"], "Making laws for the federation",
      "The National Assembly, comprising the Senate and House of Representatives, is Nigeria's federal legislative body, primarily responsible for making laws."),
  _gq("Which vitamin is primarily obtained by the human body through exposure to sunlight?",
      ["Vitamin D", "Vitamin A", "Vitamin C", "Vitamin B12"], "Vitamin D",
      "Vitamin D is unique among vitamins in that the human body can synthesise it in the skin through exposure to sunlight."),
  _gq("What is the term for the buying and selling of goods and services between different countries?",
      ["International trade", "Domestic trade", "Barter trade", "Retail trade"], "International trade",
      "International trade specifically refers to the exchange of goods and services across national borders, distinct from domestic or local trade within one country."),
  _gq("Which Nigerian writer won the Nobel Prize in Literature in 1986?",
      ["Wole Soyinka", "Chinua Achebe", "Chimamanda Ngozi Adichie", "Ben Okri"], "Wole Soyinka",
      "Wole Soyinka became the first African to win the Nobel Prize in Literature, awarded in 1986, in recognition of his significant literary contributions."),
  _gq("What does the abbreviation 'NYSC' stand for in the Nigerian context?",
      ["National Youth Service Corps", "National Youth Sports Council", "Nigerian Youth Skills Centre", "National Yearly Statistics Commission"], "National Youth Service Corps",
      "NYSC (National Youth Service Corps) is a mandatory one-year national service programme for Nigerian graduates, established in 1973."),
  _gq("What is the term for a persistent, sustained rise in the general price level of goods and services in an economy?",
      ["Inflation", "Deflation", "Recession", "Depression"], "Inflation",
      "Inflation describes an ongoing, generalised increase in prices across an economy, reducing the purchasing power of money over time."),
  _gq("Which of the following is a key function of the legislature in a democratic system of government?",
      ["Law-making", "Law enforcement", "Judicial interpretation exclusively", "Military command"], "Law-making",
      "The legislature's core constitutional function in a democracy is to make (enact) laws, distinct from the executive's role in enforcement and the judiciary's role in interpretation."),
  _gq("Which of the following best describes the primary aim of the Sustainable Development Goals (SDGs), adopted by United Nations member states?",
      ["Addressing global challenges such as poverty, inequality, and climate change by a set target year", "Regulating international trade tariffs exclusively", "Managing global internet infrastructure", "Coordinating international sports competitions"], "Addressing global challenges such as poverty, inequality, and climate change by a set target year",
      "The SDGs are a set of 17 global goals adopted by UN member states in 2015, aiming to address major challenges including poverty, inequality, and climate change by 2030."),
  _gq("Which of the following is Nigeria's main source of foreign exchange earnings?",
      ["Crude oil (petroleum) exports", "Cocoa exports", "Textile exports", "Tourism"], "Crude oil (petroleum) exports",
      "Crude oil exports have historically been, and remain, Nigeria's dominant source of foreign exchange earnings, despite ongoing efforts toward economic diversification."),
  _gq("What is the term for a general election in which citizens directly vote to elect their representatives?",
      ["Direct election", "Indirect election", "Appointment", "Coronation"], "Direct election",
      "A direct election is one in which voters cast their ballots directly for the candidates or representatives they wish to elect, as opposed to an indirect election through intermediaries."),
  _gq("Which of the following international agencies is primarily focused on global public health matters?",
      ["World Health Organization (WHO)", "World Trade Organization (WTO)", "International Monetary Fund (IMF)", "United Nations Educational, Scientific and Cultural Organization (UNESCO)"], "World Health Organization (WHO)",
      "The WHO is the specialised United Nations agency responsible for coordinating international public health efforts and providing global health leadership and guidance."),
];
