import "../quiz_question.dart";

const _subject = "Geography";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// WAEC Geography question bank covering the full syllabus: Practical &
/// Physical Geography, Climatology/Biogeography/Oceanography, and Regional
/// & Economic Geography (with emphasis on West Africa/Nigeria).
List<QuizQuestion> buildWaecGeographyQuestions() {
  return [
    ..._practicalAndPhysicalGeography,
    ..._climatologyBiogeographyAndOceanography,
    ..._regionalAndEconomicGeography,
  ];
}

final _practicalAndPhysicalGeography = [
  _q("On a topographical map, the scale expressed as '1 centimetre represents 1 kilometre' is an example of a",
      ["statement scale", "representative fraction", "linear (graphical) scale", "vertical scale"], "statement scale",
      "A statement scale expresses the map-to-ground relationship in words, unlike a representative fraction which uses a ratio."),
  _q("A scale expressed as a ratio, such as 1:50,000, with no units attached, is called a",
      ["representative fraction (R.F.)", "statement scale", "linear scale", "vertical exaggeration scale"], "representative fraction (R.F.)",
      "A representative fraction shows the ratio between map distance and ground distance, applicable regardless of the unit of measurement used."),
  _q("A scale drawn as a line divided into units to allow direct measurement of distances on a map is called a",
      ["linear (graphical) scale", "statement scale", "representative fraction", "contour scale"], "linear (graphical) scale",
      "A linear scale is a drawn bar marked with distance units, allowing map users to measure ground distances directly using a ruler or divider."),
  _q("If a map has a scale of 1:50,000, a distance of 4 centimetres on the map represents an actual ground distance of",
      ["2 kilometres", "4 kilometres", "20 kilometres", "200 kilometres"], "2 kilometres",
      "4 cm x 50,000 = 200,000 cm = 2,000 metres = 2 kilometres on the ground."),
  _q("The direction of a point on a map, measured clockwise from north and expressed in degrees, is called its",
      ["bearing", "scale", "contour interval", "gradient"], "bearing",
      "Bearing gives the precise direction to a point, measured in degrees clockwise from north (0°/360°)."),
  _q("The imaginary lines on a topographical map joining points of equal height above sea level are called",
      ["contour lines", "grid lines", "graticules", "isohyets"], "contour lines",
      "Contour lines represent equal elevation, allowing the shape and steepness of the land to be visualised on a flat map."),
  _q("Where contour lines are drawn very close together on a map, the land they represent is",
      ["steep", "gentle", "flat", "at sea level only"], "steep",
      "Closely spaced contour lines indicate rapid changes in elevation over a short horizontal distance, representing steep slopes."),
  _q("Where contour lines are widely spaced apart on a map, the land they represent is",
      ["gentle (gradual) in slope", "very steep", "a vertical cliff", "underwater"], "gentle (gradual) in slope",
      "Widely spaced contours indicate a gradual change in elevation, representing gently sloping terrain."),
  _q("A steep, near-vertical rock face, often found at a coastline or valley edge, is best identified on a map by",
      ["closely packed contour lines forming a near-continuous line", "widely spaced, evenly distributed contour lines", "the complete absence of contour lines", "concentric circles far apart from each other"], "closely packed contour lines forming a near-continuous line",
      "A cliff is shown where contour lines converge tightly, sometimes merging, indicating an almost vertical change in elevation."),
  _q("A long, narrow depression, usually containing a river, and bounded by higher land on either side, is called a",
      ["valley", "ridge", "col", "spur"], "valley",
      "A valley is a low-lying stretch of land between hills or mountains, typically formed by river erosion."),
  _q("A narrow strip of high land projecting outward from a mountain or hill, often between two valleys, is called a",
      ["spur", "col", "valley", "plain"], "spur",
      "A spur is a projecting ridge of higher ground extending from a main upland area, often separating two valleys."),
  _q("An extensive area of flat or gently undulating low-lying land is called a",
      ["plain", "plateau", "col", "cliff"], "plain",
      "A plain is a large area of relatively flat land at low elevation, often suited to agriculture and settlement."),
  _q("An extensive, relatively flat area of land raised significantly above sea level, often with steep sides, is called a",
      ["plateau", "plain", "valley", "col"], "plateau",
      "A plateau is an elevated flatland, distinguished from a plain mainly by its higher elevation and often steep-sided edges."),
  _q("A diagram showing the shape of the land surface along a straight line drawn across a map is called a",
      ["cross-section", "contour map", "sketch map", "choropleth map"], "cross-section",
      "A cross-section is constructed by plotting the elevations along a chosen line to reveal the profile of the terrain."),
  _q("On a topographical map, settlements that cluster closely together around a central point, such as a market or road junction, are described as having a",
      ["nucleated settlement pattern", "linear settlement pattern", "dispersed settlement pattern", "radial pattern only"], "nucleated settlement pattern",
      "Nucleated settlements are tightly clustered around a focal point, unlike dispersed settlements which are spread out."),
  _q("The shape and size of the Earth is best described as",
      ["a slightly flattened sphere (oblate spheroid)", "a perfect sphere with no flattening", "a flat disc", "an irregular cube"], "a slightly flattened sphere (oblate spheroid)",
      "The Earth bulges slightly at the equator and is flattened at the poles due to its rotation, making it an oblate spheroid rather than a perfect sphere."),
  _q("The spinning of the Earth on its own axis, completing one full turn approximately every 24 hours, is called",
      ["rotation", "revolution", "precession", "declination"], "rotation",
      "Rotation is the Earth's spin on its axis, which causes the daily cycle of day and night."),
  _q("The movement of the Earth around the Sun, taking approximately 365¼ days to complete one cycle, is called",
      ["revolution", "rotation", "precession", "inclination"], "revolution",
      "Revolution refers to the Earth's annual orbit around the Sun, which, combined with axial tilt, produces the seasons."),
  _q("The alternation of day and night is directly caused by the Earth's",
      ["rotation on its axis", "revolution around the Sun", "tilt of 23.5 degrees alone", "distance from the Moon"], "rotation on its axis",
      "As the Earth rotates, different parts face the Sun (daytime) or away from it (nighttime), producing the day-night cycle."),
  _q("The changing seasons experienced at different times of the year are mainly caused by the",
      ["tilt of the Earth's axis combined with its revolution around the Sun", "Earth's rotation on its axis alone", "changing distance between the Earth and the Moon", "changing speed of the Earth's rotation"], "tilt of the Earth's axis combined with its revolution around the Sun",
      "As the tilted Earth orbits the Sun, different hemispheres receive varying intensities of sunlight at different times of year, producing seasons."),
  _q("The outermost, thin, solid layer of the Earth on which we live is called the",
      ["crust (lithosphere)", "mantle (mesosphere)", "core (barysphere)", "atmosphere"], "crust (lithosphere)",
      "The crust, part of the lithosphere, is the Earth's outermost solid layer, relatively thin compared to the layers beneath it."),
  _q("The thick layer of the Earth found between the crust and the core, composed of hot, semi-solid rock, is called the",
      ["mantle (mesosphere)", "crust", "core", "stratosphere"], "mantle (mesosphere)",
      "The mantle lies beneath the crust and above the core, consisting of dense, hot rock that can flow slowly over long periods."),
  _q("The innermost layer of the Earth, believed to consist mainly of iron and nickel, is called the",
      ["core (barysphere)", "crust", "mantle", "troposphere"], "core (barysphere)",
      "The core, at the centre of the Earth, is composed largely of iron and nickel and is divided into a solid inner core and liquid outer core."),
  _q("Rocks formed from the cooling and solidification of molten magma or lava are called",
      ["igneous rocks", "sedimentary rocks", "metamorphic rocks", "organic rocks"], "igneous rocks",
      "Igneous rocks form directly from the cooling of magma (below ground) or lava (on the surface)."),
  _q("Rocks formed from the compaction and cementation of layers of sediment over long periods are called",
      ["sedimentary rocks", "igneous rocks", "metamorphic rocks", "volcanic rocks"], "sedimentary rocks",
      "Sedimentary rocks form as layers of eroded material accumulate and are compressed and cemented together over time."),
  _q("Rocks that have been changed in structure or mineral composition by intense heat and/or pressure are called",
      ["metamorphic rocks", "igneous rocks", "sedimentary rocks", "extrusive rocks"], "metamorphic rocks",
      "Metamorphic rocks form when existing rocks are transformed by heat, pressure, or chemically active fluids, without fully melting."),
  _q("The bending or buckling of rock layers due to compressional earth movements is called",
      ["folding", "faulting", "weathering", "erosion"], "folding",
      "Folding occurs when horizontal compressional forces cause rock layers to bend, often producing mountain ranges."),
  _q("A fracture in the Earth's crust along which rock masses have moved relative to one another is called a",
      ["fault", "fold", "dyke", "sill"], "fault",
      "Faulting occurs when rock strata break and shift along a fracture line, often associated with earthquakes."),
  _q("Sudden, violent shaking of the ground caused by the release of energy along a fault line is called",
      ["an earthquake", "a volcano", "a landslide", "a tsunami directly"], "an earthquake",
      "Earthquakes result from the sudden release of built-up stress along faults, generating seismic waves that shake the ground."),
  _q("A sheet of igneous rock intruded parallel to existing rock layers underground is called a",
      ["sill", "dyke", "caldera", "crater"], "sill",
      "A sill is a horizontal (or near-horizontal) intrusion of magma that solidifies between existing rock layers."),
  _q("A large, basin-shaped depression formed after a volcanic eruption or the collapse of a volcano's summit is called a",
      ["caldera", "crater", "sill", "dyke"], "caldera",
      "A caldera is a broad depression resulting from the collapse of land following a major eruption or emptying of a magma chamber."),
  _q("The breakdown of rocks in situ through the mechanical action of temperature changes, frost, or plant roots, without chemical change, is called",
      ["physical (mechanical) weathering", "chemical weathering", "biological weathering only", "mass wasting"], "physical (mechanical) weathering",
      "Physical weathering breaks rock into smaller fragments through mechanical processes, without altering its chemical composition."),
  _q("The breakdown or decomposition of rocks through chemical reactions such as oxidation and carbonation is called",
      ["chemical weathering", "physical weathering", "mass wasting", "erosion"], "chemical weathering",
      "Chemical weathering alters the mineral composition of rocks through reactions with water, oxygen, and carbon dioxide."),
  _q("A rapid, sudden downward movement of a large mass of rock and soil down a slope is called a",
      ["landslide", "soil creep", "weathering", "deposition"], "landslide",
      "Landslides involve the fast, often catastrophic, movement of large volumes of material downslope, usually triggered by heavy rain or instability."),
  _q("The stage of a river's course characterised by rapid vertical erosion, waterfalls, and V-shaped valleys is called the",
      ["youthful (upper) stage", "mature (middle) stage", "old age (lower) stage", "estuarine stage"], "youthful (upper) stage",
      "In its upper (youthful) course, a river actively cuts downward, producing steep-sided V-shaped valleys and features like waterfalls and rapids."),
  _q("A loop-shaped lake formed when a meander is cut off from the main river channel is called an",
      ["oxbow lake", "estuary", "delta", "gorge"], "oxbow lake",
      "An oxbow lake forms when a river meander is bypassed and cut off, leaving a crescent-shaped body of standing water."),
  _q("A landform created at a river's mouth where sediment is deposited as the river enters a sea or lake is called a",
      ["delta", "gorge", "oxbow lake", "waterfall"], "delta",
      "A delta forms as a river loses velocity upon entering a larger body of water, depositing its sediment load in a fan-like or triangular shape."),
  _q("Landforms produced when waves erode a coastline, such as cliffs and wave-cut platforms, result mainly from",
      ["coastal (marine) erosion", "wind erosion", "river erosion", "glacial erosion"], "coastal (marine) erosion",
      "Coastal erosion, driven by wave action, sculpts features such as cliffs, wave-cut platforms, caves, and arches along shorelines."),
  _q("Landforms such as sand dunes and yardangs, common in arid regions, are shaped mainly by",
      ["wind erosion and deposition", "river erosion", "glacial deposition", "volcanic activity"], "wind erosion and deposition",
      "In deserts, wind is a dominant agent of erosion and deposition, sculpting features like sand dunes through the movement of loose sediment."),
];

final _climatologyBiogeographyAndOceanography = [
  _q("The degree of hotness or coldness of the atmosphere, measured using a thermometer, is called",
      ["temperature", "pressure", "humidity", "precipitation"], "temperature",
      "Temperature measures the heat energy in the air and is a fundamental element of weather and climate."),
  _q("The force exerted by the weight of the atmosphere on the Earth's surface, measured using a barometer, is called",
      ["atmospheric pressure", "temperature", "humidity", "wind speed"], "atmospheric pressure",
      "Atmospheric pressure reflects the weight of the air above a given point, and its variations drive wind patterns."),
  _q("The horizontal movement of air from areas of high pressure to areas of low pressure is called",
      ["wind", "humidity", "precipitation", "insolation"], "wind",
      "Wind results from pressure differences in the atmosphere, with air flowing from high-pressure to low-pressure zones."),
  _q("The amount of water vapour present in the air is called",
      ["humidity", "temperature", "pressure", "insolation"], "humidity",
      "Humidity measures the moisture content of the air, which influences cloud formation and the likelihood of precipitation."),
  _q("Water falling from the atmosphere to the Earth's surface in forms such as rain, snow, and hail is called",
      ["precipitation", "humidity", "condensation", "evaporation"], "precipitation",
      "Precipitation includes all forms of moisture that fall from clouds to the ground, driven by condensation processes in the atmosphere."),
  _q("The weather instrument used to measure atmospheric temperature is the",
      ["thermometer", "barometer", "anemometer", "rain gauge"], "thermometer",
      "A thermometer measures the temperature of the air, typically housed in a shaded, ventilated enclosure called a Stevenson screen."),
  _q("The weather instrument used to measure atmospheric pressure is the",
      ["barometer", "thermometer", "anemometer", "hygrometer"], "barometer",
      "A barometer measures the pressure exerted by the atmosphere, helping to forecast changes in weather."),
  _q("The weather instrument used to measure wind speed is the",
      ["anemometer", "barometer", "rain gauge", "wind vane"], "anemometer",
      "An anemometer measures the speed of the wind, typically using rotating cups exposed to the airflow."),
  _q("The instrument used to indicate wind direction is the",
      ["wind vane", "anemometer", "barometer", "hygrometer"], "wind vane",
      "A wind vane points in the direction from which the wind is blowing, showing wind direction rather than speed."),
  _q("The instrument used to measure the amount of rainfall received at a location is the",
      ["rain gauge", "barometer", "anemometer", "thermometer"], "rain gauge",
      "A rain gauge collects and measures the depth of rainfall over a set period at a particular location."),
  _q("The instrument used to measure atmospheric humidity is the",
      ["hygrometer", "barometer", "anemometer", "rain gauge"], "hygrometer",
      "A hygrometer measures the amount of water vapour (relative humidity) present in the air."),
  _q("Weather instruments are typically placed in a white, louvred box mounted on a stand, known as a",
      ["Stevenson screen", "rain gauge stand", "wind sock", "weather balloon"], "Stevenson screen",
      "A Stevenson screen shields instruments like thermometers from direct sunlight and precipitation while allowing free air circulation for accurate readings."),
  _q("The hot, wet climate found near the equator, with high year-round temperatures and rainfall, is called the",
      ["equatorial (tropical rainforest) climate", "hot desert climate", "Mediterranean climate", "cool temperate climate"], "equatorial (tropical rainforest) climate",
      "The equatorial climate is characterised by consistently high temperatures and abundant rainfall throughout the year, supporting dense rainforest vegetation."),
  _q("The hot, dry climate typically found in regions such as the Sahara, with very low and unreliable rainfall, is called the",
      ["hot desert climate", "equatorial climate", "temperate maritime climate", "tundra climate"], "hot desert climate",
      "Hot desert climates experience extremely low rainfall and large diurnal temperature ranges, supporting sparse desert vegetation."),
  _q("A climatic zone experiencing moderate temperatures and rainfall spread across four distinct seasons is called a",
      ["temperate climate", "tropical climate", "polar climate", "equatorial climate"], "temperate climate",
      "Temperate climates, found in the mid-latitudes, typically feature four seasons with moderate variations in temperature and precipitation."),
  _q("A very cold climatic zone found near the poles, with extremely low temperatures and minimal precipitation, is called a",
      ["polar (cold) climate", "temperate climate", "tropical climate", "equatorial climate"], "polar (cold) climate",
      "Polar climates are characterised by long, extremely cold winters and short, cool summers, with vegetation limited mainly to mosses and lichens."),
  _q("The dense forest vegetation found in areas of the equatorial climate, characterised by tall trees and multiple canopy layers, is called",
      ["tropical rainforest", "savanna grassland", "desert vegetation", "tundra vegetation"], "tropical rainforest",
      "Tropical rainforests thrive under the high rainfall and temperatures of equatorial regions, producing dense, multi-layered vegetation."),
  _q("The vegetation zone characterised by grassland interspersed with scattered trees, common across much of West Africa between the forest and desert, is called",
      ["savanna", "tropical rainforest", "tundra", "temperate grassland"], "savanna",
      "The savanna is a transitional vegetation belt of grasses and scattered trees, adapted to a climate with distinct wet and dry seasons."),
  _q("The vegetation type typical of hot desert regions, adapted to survive with very little water, includes plants such as",
      ["cacti and other drought-resistant (xerophytic) plants", "tall broadleaf rainforest trees", "dense coniferous forest", "mangrove swamp vegetation"], "cacti and other drought-resistant (xerophytic) plants",
      "Desert vegetation consists mainly of xerophytes, plants specially adapted with features like thick stems and reduced leaves to conserve water."),
  _q("The vegetation zone found in polar and sub-polar regions, consisting mainly of mosses, lichens, and low shrubs due to permanently frozen subsoil, is called the",
      ["tundra", "savanna", "tropical rainforest", "desert"], "tundra",
      "Tundra vegetation is limited by extreme cold and permafrost, supporting only low-growing plants adapted to short growing seasons."),
  _q("A key factor influencing the distribution of vegetation across the world is",
      ["climate, especially temperature and rainfall patterns", "the colour of the local soil alone", "the number of rivers in a country", "the size of a country's population"], "climate, especially temperature and rainfall patterns",
      "Climate, particularly rainfall and temperature, is the primary control on which types of vegetation can grow in a given region."),
  _q("The distinct layers of soil, visible when a vertical cut is made into the ground, are collectively called the",
      ["soil profile", "soil erosion pattern", "soil texture chart", "soil horizon map"], "soil profile",
      "A soil profile shows the sequence of layers (horizons) that make up the soil, from the surface down to the parent rock."),
  _q("The uppermost, most fertile layer of soil, rich in organic matter (humus), is called",
      ["topsoil", "subsoil", "parent rock", "bedrock"], "topsoil",
      "Topsoil is the fertile surface layer where most plant roots and organic decomposition occur, making it critical for agriculture."),
  _q("The removal of the fertile topsoil layer by the action of wind or water is called",
      ["soil erosion", "soil profile formation", "soil fertility", "soil conservation"], "soil erosion",
      "Soil erosion strips away valuable topsoil, reducing agricultural productivity and often caused by deforestation, overgrazing, or poor farming practices."),
  _q("A common method used to reduce soil erosion on farmland with sloping terrain is",
      ["terracing and contour ploughing", "complete deforestation of the area", "removal of all vegetation cover", "increasing the slope's steepness"], "terracing and contour ploughing",
      "Terracing and contour ploughing slow the flow of water down slopes, reducing the erosive power of surface runoff on farmland."),
  _q("The general shape and features of the floor of the ocean, including ridges, trenches, and plains, is referred to as",
      ["ocean floor configuration (bathymetry)", "the continental interior", "the water cycle", "the coastal plain"], "ocean floor configuration (bathymetry)",
      "Ocean floor configuration describes the relief of the seabed, including features such as mid-ocean ridges, abyssal plains, and deep trenches."),
  _q("Large-scale, persistent movements of ocean water in a fairly constant direction are called",
      ["ocean currents", "tides", "waves", "tsunamis"], "ocean currents",
      "Ocean currents are continuous, directed movements of seawater, driven by factors such as wind, temperature, and salinity differences."),
  _q("Ocean currents that carry warm water from tropical regions toward higher latitudes are called",
      ["warm currents", "cold currents", "tidal currents", "longshore currents"], "warm currents",
      "Warm currents originate near the equator and move warm water polewards, often raising coastal temperatures along their path."),
  _q("Ocean currents that carry cold water from polar regions toward the tropics are called",
      ["cold currents", "warm currents", "tidal currents", "rip currents"], "cold currents",
      "Cold currents flow from higher latitudes toward the equator, often cooling coastal climates and contributing to desert formation nearby."),
  _q("The Benguela Current, a cold ocean current flowing along the south-western coast of Africa, has the effect of",
      ["reducing rainfall and contributing to desert conditions along the adjacent coast", "increasing rainfall and creating tropical rainforest along the coast", "raising coastal temperatures significantly", "causing frequent volcanic eruptions along the coast"], "reducing rainfall and contributing to desert conditions along the adjacent coast",
      "Cold currents like the Benguela cool and stabilise the air above them, suppressing rainfall and helping to create arid coastal conditions, as seen near the Namib Desert."),
];

final _regionalAndEconomicGeography = [
  _q("The uneven distribution of the world's population, with dense clusters in some regions and sparse settlement in others, is best explained mainly by differences in",
      ["climate, relief, soil fertility, and economic opportunities", "the length of a country's coastline alone", "the number of rivers with no other factor", "the exact shape of a country's borders"], "climate, relief, soil fertility, and economic opportunities",
      "Population distribution is shaped by a combination of physical factors (climate, relief, soils) and human/economic factors (job opportunities, infrastructure)."),
  _q("Regions with harsh climates, poor soils, or rugged relief, such as deserts and high mountains, typically have",
      ["low population density", "very high population density", "the highest population density in the world", "a population density equal to fertile plains"], "low population density",
      "Areas with challenging physical conditions for farming and settlement generally support fewer people, resulting in sparse population density."),
  _q("Fertile river valleys and plains, such as the Nile Valley, typically have",
      ["high population density", "very low population density", "no permanent settlements", "population density similar to deserts"], "high population density",
      "Fertile lowland areas with reliable water supply support intensive agriculture, attracting dense human settlement."),
  _q("The movement of people from rural areas to urban centres in search of better economic opportunities is called",
      ["rural-urban migration (rural-urban drift)", "urban-rural migration", "international migration only", "seasonal migration only"], "rural-urban migration (rural-urban drift)",
      "Rural-urban migration describes the widespread movement of people from the countryside to cities and towns, often driven by the search for jobs and services."),
  _q("A major factor commonly pushing people to migrate from rural to urban areas in West Africa is",
      ["limited job opportunities and poor social amenities in rural areas", "an oversupply of social amenities in rural areas", "abundant well-paid rural employment", "the total absence of any cities to migrate to"], "limited job opportunities and poor social amenities in rural areas",
      "Rural areas often lack sufficient employment, healthcare, and educational facilities, pushing residents toward cities in search of a better life."),
  _q("Settlements whose main economic activities are farming, fishing, and other primary occupations are generally classified as",
      ["rural settlements", "urban settlements", "industrial settlements only", "port settlements only"], "rural settlements",
      "Rural settlements are typically characterised by low population density and reliance on primary economic activities such as agriculture."),
  _q("Settlements characterised by high population density, and dominated by commerce, industry, and administrative functions, are generally classified as",
      ["urban settlements", "rural settlements", "nomadic settlements", "pastoral settlements"], "urban settlements",
      "Urban settlements (towns and cities) are marked by dense populations and a concentration of secondary and tertiary economic activities."),
  _q("The type of shifting agriculture in which farmers clear and cultivate land for a few years before moving on to allow the land to regenerate is called",
      ["shifting cultivation", "sedentary farming", "commercial plantation agriculture", "pastoral nomadism"], "shifting cultivation",
      "Shifting cultivation involves rotating farmland use, clearing new plots as older ones lose fertility, common in traditional tropical farming systems."),
  _q("Farming carried out permanently on the same piece of land, often supported by fertilisers to maintain soil fertility, is called",
      ["sedentary farming", "shifting cultivation", "pastoral nomadism", "transhumance"], "sedentary farming",
      "Sedentary farming involves continuous cultivation of a fixed plot of land, relying on soil management techniques rather than relocating."),
  _q("Large-scale, organised farming of a single cash crop, such as rubber or oil palm, mainly for export, is called",
      ["commercial plantation agriculture", "subsistence farming", "shifting cultivation", "pastoral nomadism"], "commercial plantation agriculture",
      "Plantation agriculture involves large, often monoculture farms producing cash crops for sale, typically requiring significant capital investment."),
  _q("A system of livestock rearing in which herders move their animals from place to place in search of pasture and water is called",
      ["pastoral nomadism", "sedentary farming", "commercial plantation agriculture", "shifting cultivation"], "pastoral nomadism",
      "Pastoral nomadism is common in semi-arid regions where herders must constantly relocate their livestock to find adequate grazing and water."),
  _q("The exploitation of trees from natural or planted forests for timber and other wood products is called",
      ["lumbering", "pastoralism", "shifting cultivation", "commercial farming"], "lumbering",
      "Lumbering involves the felling, processing, and marketing of timber, an important economic activity in forested regions of West Africa."),
  _q("A major problem associated with lumbering in West Africa is",
      ["deforestation and loss of biodiversity from overexploitation", "an oversupply of timber with no market demand", "the complete absence of forest resources in the region", "excessive government restriction preventing any logging"], "deforestation and loss of biodiversity from overexploitation",
      "Unsustainable logging practices in West Africa have contributed to significant deforestation, threatening biodiversity and forest-dependent livelihoods."),
  _q("A key measure used to conserve forest resources exploited through lumbering is",
      ["reforestation (replanting trees) and controlled/selective logging", "clearing all forests for farmland immediately", "banning all use of timber products permanently", "increasing uncontrolled logging activity"], "reforestation (replanting trees) and controlled/selective logging",
      "Sustainable forestry practices, such as replanting trees and limiting harvest rates, help conserve forest resources for future use."),
  _q("Nigeria's most economically significant mineral resource, extracted mainly from the Niger Delta region, is",
      ["crude oil (petroleum)", "coal", "iron ore", "gold"], "crude oil (petroleum)",
      "Crude oil, concentrated in the Niger Delta, is Nigeria's most valuable mineral resource and dominant export earner."),
  _q("A major coal mining town historically associated with Nigeria's coal industry is",
      ["Enugu", "Jos", "Kano", "Sokoto"], "Enugu",
      "Enugu became a major centre of Nigeria's coal mining industry, which was historically significant before the rise of petroleum."),
  _q("A prominent location for tin mining on the Jos Plateau in Nigeria is closely associated with the town of",
      ["Jos", "Enugu", "Warri", "Sokoto"], "Jos",
      "The Jos Plateau has long been associated with Nigeria's tin mining industry, alongside associated columbite deposits."),
  _q("Iron ore deposits significant to Nigeria's steel industry are notably found around",
      ["Itakpe", "Enugu", "Jos", "Sokoto"], "Itakpe",
      "Itakpe in Kogi State hosts major iron ore deposits, feeding Nigeria's steel production efforts, including the Ajaokuta Steel Complex."),
  _q("Bauxite, an ore used mainly in the production of aluminium, is significant in some West African countries, most notably",
      ["Guinea", "Niger", "Chad", "Senegal"], "Guinea",
      "Guinea holds some of the world's largest bauxite reserves, making it a major global supplier of this aluminium ore."),
  _q("Gold mining has long been economically significant in parts of West Africa, particularly in",
      ["Ghana", "Chad", "Niger", "Cape Verde"], "Ghana",
      "Ghana, historically known as the 'Gold Coast', has a long tradition of gold mining that remains economically important today."),
  _q("The location of industries close to their sources of raw materials, markets, or labour supply is influenced mainly by",
      ["industrial location factors such as proximity to raw materials, markets, transport, and power supply", "the colour of a country's flag", "the number of political parties in a country", "the length of a country's history"], "industrial location factors such as proximity to raw materials, markets, transport, and power supply",
      "Industries typically locate where costs are minimised and access to inputs, markets, and infrastructure is most favourable."),
  _q("A major challenge facing manufacturing industries in many developing West African countries is",
      ["inadequate infrastructure, such as unreliable power supply and poor transport networks", "an oversupply of skilled labour with no jobs available", "excessive and cheap electricity supply", "too much government investment in industry"], "inadequate infrastructure, such as unreliable power supply and poor transport networks",
      "Poor infrastructure, especially unreliable electricity and transport, significantly raises production costs and limits industrial growth in the region."),
  _q("The mode of transport generally considered most flexible for door-to-door movement of goods and people over short to medium distances is",
      ["road transport", "rail transport", "water transport", "air transport"], "road transport",
      "Road transport offers the greatest flexibility, reaching destinations that other transport modes, such as rail or water, cannot access directly."),
  _q("The mode of transport generally most economical for moving heavy, bulky goods over long distances within a country is",
      ["rail transport", "air transport", "road transport for very long hauls", "pipeline transport for solid goods"], "rail transport",
      "Rail transport can move large volumes of heavy freight efficiently over long overland distances, often more cheaply than road transport."),
  _q("The mode of transport most suitable for moving goods and passengers between countries separated by large bodies of water is",
      ["water (sea) transport", "road transport", "rail transport", "pipeline transport"], "water (sea) transport",
      "Sea transport remains the dominant means of moving bulky goods internationally, especially between countries separated by oceans."),
  _q("West Africa's physical setting is generally characterised by",
      ["a mix of coastal plains, plateaus, and river basins such as the Niger and Senegal basins", "a landscape consisting entirely of high fold mountains", "a continuous ice sheet covering the entire region", "the complete absence of any river systems"], "a mix of coastal plains, plateaus, and river basins such as the Niger and Senegal basins",
      "West Africa's relief includes coastal lowlands, extensive plateaus, and major river systems like the Niger, shaping its human and economic geography."),
  _q("The River Niger, one of West Africa's most important rivers, generally flows through countries including",
      ["Guinea, Mali, Niger, and Nigeria", "Kenya, Tanzania, and Uganda only", "Egypt and Sudan only", "South Africa and Namibia only"], "Guinea, Mali, Niger, and Nigeria",
      "The Niger River originates in Guinea and flows through Mali, Niger, and Nigeria before emptying into the Gulf of Guinea via its delta."),
  _q("A major environmental challenge facing the Sahel region on the edge of the Sahara Desert is",
      ["desertification, caused by overgrazing, deforestation, and low rainfall", "excessive year-round rainfall causing constant flooding", "an overabundance of forest cover with no farmland", "permanent snow cover across the region"], "desertification, caused by overgrazing, deforestation, and low rainfall",
      "The Sahel faces desertification as unsustainable land use combines with low and unreliable rainfall, gradually turning productive land into desert."),
  _q("A significant environmental problem in the Niger Delta region of Nigeria, linked to petroleum extraction, is",
      ["oil pollution affecting land, water, and local livelihoods", "excessive cold temperatures damaging crops", "a complete absence of any industrial activity", "widespread desertification of the delta"], "oil pollution affecting land, water, and local livelihoods",
      "Oil spills and gas flaring associated with petroleum extraction in the Niger Delta have caused significant environmental damage, harming farming and fishing livelihoods."),
  _q("Regional cooperation among West African states, particularly through bodies such as ECOWAS, is aimed mainly at",
      ["promoting economic integration, free trade, and regional stability", "restricting all trade and movement between member countries", "eliminating the need for any national governments", "encouraging countries to withdraw from all international cooperation"], "promoting economic integration, free trade, and regional stability",
      "Regional bodies like ECOWAS seek to foster cooperation on trade, security, and development among West African nations."),
  _q("Coastal flooding is an increasing environmental challenge for many West African cities mainly because of",
      ["a combination of rising sea levels, heavy rainfall, and poor urban drainage systems", "a permanent decrease in regional rainfall", "the complete absence of any coastline in the region", "excessive snowfall along the coast"], "a combination of rising sea levels, heavy rainfall, and poor urban drainage systems",
      "Coastal West African cities face growing flood risk due to a mix of climatic factors, such as heavy rains and rising seas, combined with inadequate drainage infrastructure."),
];
