import "../quiz_question.dart";

const _subject = "Home Management";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// WAEC Home Management question bank covering the full syllabus:
/// Management Principles & Family Resources, Consumer Education & Housing,
/// and Family Life, Health & Hospitality.
List<QuizQuestion> buildWaecHomeManagementQuestions() {
  return [
    ..._managementPrinciplesAndFamilyResources,
    ..._consumerEducationAndHousing,
    ..._familyLifeHealthAndHospitality,
  ];
}

final _managementPrinciplesAndFamilyResources = [
  _q("The step in the home management process that involves deciding in advance what needs to be done to achieve a family goal is called",
      ["planning", "organising", "controlling", "evaluating"], "planning",
      "Planning is the initial step in the management process, involving deciding in advance what actions are needed to achieve a desired goal."),
  _q("The step in the home management process that involves arranging resources and assigning tasks to carry out a plan is called",
      ["organising", "planning", "controlling", "evaluating"], "organising",
      "Organising arranges the necessary resources, people, and tasks in a logical structure needed to carry out a plan effectively."),
  _q("The step in the home management process that involves actually carrying out planned tasks is called",
      ["executing (implementing)", "planning", "controlling", "evaluating"], "executing (implementing)",
      "Executing (implementing) is the stage where the planned and organised activities are actually put into action."),
  _q("The step in the home management process that involves monitoring activities and adjusting them as needed to stay on track is called",
      ["controlling", "planning", "organising", "evaluating"], "controlling",
      "Controlling involves monitoring ongoing activities against the original plan, making adjustments as needed to keep things on track."),
  _q("The step in the home management process that involves assessing whether a goal was successfully achieved, and identifying lessons for future planning, is called",
      ["evaluating", "planning", "organising", "controlling"], "evaluating",
      "Evaluating reviews the outcome of a completed task or goal, assessing success and identifying lessons to improve future planning and execution."),
  _q("Family resources that include time, energy, skills, intelligence, and attitude are classified as",
      ["human resources", "material resources", "financial resources only", "community resources only"], "human resources",
      "Human resources encompass the personal attributes and capacities individuals bring to managing the home, such as time, energy, skills, and attitude."),
  _q("Family resources that include money, property, and communal facilities are classified as",
      ["material resources", "human resources", "time resources only", "attitude resources only"], "material resources",
      "Material resources include tangible assets such as money, property, equipment, and community facilities available to a family."),
  _q("Time management in the home is important mainly because time is a resource that",
      ["cannot be stored, replaced, or recovered once it has passed", "can always be purchased in unlimited quantities", "is identical in value for every task, regardless of priority", "has no effect on the achievement of family goals"], "cannot be stored, replaced, or recovered once it has passed",
      "Time is a uniquely limited resource that, once passed, cannot be stored or recovered, making its careful management essential to achieving family goals."),
  _q("A technique used to reduce unnecessary effort and time spent on household tasks, often by rearranging tools or combining steps, is called",
      ["work simplification", "fatigue management only", "ergonomics only", "financial planning"], "work simplification",
      "Work simplification involves analysing and streamlining household tasks to reduce wasted time, effort, and motion."),
  _q("The study of designing tasks, tools, and environments to fit the physical capabilities of the person doing the work is called",
      ["ergonomics", "work simplification only", "fatigue management only", "budgeting"], "ergonomics",
      "Ergonomics focuses on designing tasks and equipment to suit the physical needs and capabilities of the person performing them, reducing strain and injury risk."),
  _q("Managing the onset of tiredness during household tasks, such as through proper posture and scheduled breaks, is called",
      ["fatigue management", "work simplification only", "ergonomics only", "budgeting"], "fatigue management",
      "Fatigue management involves strategies such as proper posture, task rotation, and scheduled rest breaks to reduce and manage tiredness during work."),
  _q("A schedule that allocates time appropriately across work, rest, and leisure activities throughout the day is called a",
      ["balanced daily work schedule", "family budget", "consumer report", "house plan"], "balanced daily work schedule",
      "A balanced daily work schedule allocates appropriate time to work, rest, and leisure, helping to prevent overwork and burnout."),
  _q("Family income received directly in the form of wages, salaries, or business profits is classified as",
      ["direct income", "indirect income", "gross income only", "net income only"], "direct income",
      "Direct income refers to money received directly, such as wages and salaries, as opposed to indirect income received in other forms, such as benefits."),
  _q("Family income received in forms other than direct money payments, such as free housing or subsidised meals, is classified as",
      ["indirect income", "direct income", "gross income only", "net income only"], "indirect income",
      "Indirect income includes non-cash benefits, such as free accommodation or subsidised services, that contribute to a family's overall economic wellbeing."),
  _q("A family's total income before any deductions, such as taxes, are made is called its",
      ["gross income", "net income", "indirect income only", "disposable income only"], "gross income",
      "Gross income represents total earnings before any deductions, such as taxes or other withholdings, are subtracted."),
  _q("A family's income remaining after all necessary deductions, such as taxes, have been subtracted is called its",
      ["net income", "gross income", "indirect income only", "direct income only"], "net income",
      "Net income is the amount remaining after deductions like taxes have been subtracted from gross income, representing what is actually available for spending or saving."),
  _q("A financial plan that outlines expected income and planned expenditure over a specific period is called a",
      ["budget", "ledger", "consumer report", "house plan"], "budget",
      "A budget is a financial plan estimating expected income and allocating planned expenditure over a given period, helping guide spending decisions."),
  _q("A record used to systematically track and record a family's actual income and expenses over time is called an",
      ["accounting ledger", "advertisement", "house plan", "care label"], "accounting ledger",
      "An accounting ledger provides an organised record of actual income and expenditure, helping families monitor their finances against their budget."),
  _q("Setting aside a portion of income for future use, rather than spending it immediately, is called",
      ["saving", "budgeting only", "consumer advocacy", "work simplification"], "saving",
      "Saving involves deliberately setting aside income for future needs or goals, rather than spending it all immediately."),
  _q("Putting money into an asset, such as property or shares, with the expectation of future financial growth is called",
      ["investment", "saving only", "budgeting only", "direct income"], "investment",
      "Investment involves committing money to an asset with the goal of generating future returns or growth, distinct from simple saving."),
  _q("A common channel used by families to save money regularly while earning modest interest is a",
      ["savings account with a bank", "unregistered informal lending scheme with no records", "spending all income immediately with no savings plan", "keeping all cash uninvested at home indefinitely"], "savings account with a bank",
      "A bank savings account provides a secure channel for regularly setting aside money while earning some interest over time."),
  _q("A traditional cooperative savings arrangement in which members contribute a fixed amount regularly, with each member taking turns to receive the collected sum, is often called a",
      ["thrift and savings (esusu/ajo) scheme", "government bond only", "corporate share issue only", "insurance policy only"], "thrift and savings (esusu/ajo) scheme",
      "Traditional thrift and savings schemes (such as esusu or ajo) allow members to pool regular contributions, with each member taking turns to receive the accumulated sum."),
  _q("A key benefit of preparing a written family budget is that it helps",
      ["prevent overspending by planning expenditure against expected income", "guarantee unlimited spending regardless of income", "eliminate the need to track any expenses", "replace the need for any family income at all"], "prevent overspending by planning expenditure against expected income",
      "A written budget helps families plan spending realistically against expected income, reducing the risk of overspending."),
  _q("A family's fixed expenses, such as rent or loan repayments, are best described as costs that",
      ["remain the same each period, regardless of changes in usage or consumption", "vary significantly from month to month with usage", "occur only once in a family's lifetime", "are entirely optional and can be skipped freely"], "remain the same each period, regardless of changes in usage or consumption",
      "Fixed expenses, such as rent or loan repayments, remain constant each period, unlike variable expenses which fluctuate with usage or consumption."),
  _q("A family's variable expenses, such as food or utility bills, are best described as costs that",
      ["can fluctuate from period to period depending on usage or need", "remain exactly the same amount every single period", "never need to be included in a budget", "are always higher than fixed expenses in every family"], "can fluctuate from period to period depending on usage or need",
      "Variable expenses change from period to period based on actual usage or need, unlike fixed expenses which remain constant."),
  _q("A key step in effective time management for household tasks is to",
      ["prioritise tasks according to their urgency and importance", "complete tasks in a completely random order", "avoid any form of planning or scheduling", "always complete the least important tasks first"], "prioritise tasks according to their urgency and importance",
      "Effective time management involves prioritising tasks based on their urgency and importance, ensuring critical tasks are completed first."),
  _q("Delegating household tasks among family members is a management technique used mainly to",
      ["share the workload and develop responsibility among family members", "concentrate all tasks on a single family member exclusively", "eliminate the need for any task completion at all", "create unnecessary conflict within the family"], "share the workload and develop responsibility among family members",
      "Delegating tasks distributes the household workload more evenly and helps develop a sense of responsibility among family members."),
  _q("A family's intelligence and skills, considered part of its human resources, can be developed through",
      ["education, training, and practical experience", "complete inactivity and avoidance of new challenges", "ignoring opportunities for learning entirely", "relying solely on inherited traits with no further development"], "education, training, and practical experience",
      "Human resources such as intelligence and skills can be actively developed and enhanced through education, training, and practical experience over time."),
  _q("A positive attitude toward household responsibilities is considered a valuable human resource mainly because it",
      ["improves motivation and the overall efficiency of completing tasks", "has no effect on how tasks are completed", "only matters for tasks performed outside the home", "guarantees financial success regardless of effort"], "improves motivation and the overall efficiency of completing tasks",
      "A positive attitude improves motivation and can significantly enhance the efficiency and quality of how household tasks are carried out."),
  _q("Community facilities, such as public libraries, health centres, and recreational parks, are considered part of a family's",
      ["material resources", "human resources only", "direct income only", "indirect income only"], "material resources",
      "Community facilities represent material resources that a family can access and use to support its overall wellbeing, alongside personally owned property."),
  _q("An accounting ledger used in home management typically records",
      ["dates, descriptions, and amounts of income and expenditure", "only the family's long-term investment goals", "personal opinions about spending habits, with no figures", "advertisements viewed by family members"], "dates, descriptions, and amounts of income and expenditure",
      "A home accounting ledger systematically records the dates, descriptions, and amounts of both income received and expenses incurred."),
  _q("A key reason for regularly reviewing and evaluating a family's budget is to",
      ["identify areas of overspending and adjust future financial plans accordingly", "avoid any changes to spending habits, regardless of outcomes", "eliminate the need for future budgeting entirely", "guarantee that no adjustments will ever be needed"], "identify areas of overspending and adjust future financial plans accordingly",
      "Regularly reviewing a budget helps identify overspending or shortfalls, allowing families to make informed adjustments to future financial plans."),
  _q("Effective family financial planning generally considers both",
      ["short-term needs and long-term goals, such as education or retirement savings", "only short-term needs, with no consideration of the future", "only long-term goals, with no attention to immediate needs", "neither short-term nor long-term financial considerations"], "short-term needs and long-term goals, such as education or retirement savings",
      "Sound financial planning balances immediate short-term needs with longer-term goals, such as saving for children's education or retirement."),
];

final _consumerEducationAndHousing = [
  _q("Wise purchasing behaviour generally involves consumers",
      ["comparing prices, quality, and value before making a purchase decision", "buying the first available item regardless of price or quality", "ignoring product labels and advertisements entirely", "purchasing based purely on advertising claims without verification"], "comparing prices, quality, and value before making a purchase decision",
      "Wise purchasing involves carefully comparing available options for price, quality, and overall value before committing to a purchase."),
  _q("Consumer protection agencies exist mainly to",
      ["safeguard buyers from exploitation, unsafe products, and unfair trade practices", "increase the profit margins of manufacturers exclusively", "eliminate competition between different businesses", "prevent consumers from making any purchases at all"], "safeguard buyers from exploitation, unsafe products, and unfair trade practices",
      "Consumer protection agencies exist to protect buyers from exploitation, unsafe goods, and unfair or deceptive trade practices."),
  _q("The Nigerian regulatory agency primarily responsible for the safety and quality of food and drugs is",
      ["NAFDAC", "SON", "CBN", "INEC"], "NAFDAC",
      "NAFDAC (National Agency for Food and Drug Administration and Control) regulates the safety and quality of food, drugs, and related products in Nigeria."),
  _q("The Nigerian regulatory agency primarily responsible for setting and enforcing general product quality standards is",
      ["SON (Standards Organisation of Nigeria)", "NAFDAC", "CBN", "INEC"], "SON (Standards Organisation of Nigeria)",
      "SON develops and enforces quality standards for products manufactured or sold in Nigeria, helping protect consumers from substandard goods."),
  _q("Reading and understanding product labels before purchase helps consumers mainly to",
      ["make informed decisions about ingredients, quality, and safety", "ignore all information about the product entirely", "avoid comparing products with one another", "increase the price paid for the product"], "make informed decisions about ingredients, quality, and safety",
      "Product labels provide important information about ingredients, usage instructions, and safety, helping consumers make informed purchasing decisions."),
  _q("Advertisements should generally be evaluated by consumers with a degree of",
      ["critical judgement, verifying claims rather than accepting them uncritically", "complete, unquestioning trust in every claim made", "total disregard, without ever considering the product advertised", "indifference to the accuracy of any information presented"], "critical judgement, verifying claims rather than accepting them uncritically",
      "Wise consumers approach advertisements critically, verifying claims through independent research rather than accepting marketing statements at face value."),
  _q("A key factor to consider when choosing a house to live in is its",
      ["location, structural condition, and cost relative to the family's budget", "colour of the exterior paint alone", "the number of neighbouring houses only", "the brand of the front door alone"], "location, structural condition, and cost relative to the family's budget",
      "Key considerations in choosing a house include its location (proximity to work, schools, amenities), structural soundness, and affordability."),
  _q("A house plan is best described as a",
      ["scaled drawing showing the layout of rooms and spaces within a building", "list of building materials used only", "record of the house's purchase price only", "schedule of house maintenance tasks only"], "scaled drawing showing the layout of rooms and spaces within a building",
      "A house plan is a scaled architectural drawing illustrating the arrangement and dimensions of rooms and spaces within a building."),
  _q("A key principle of interior design concerned with how furniture, walls, and open spaces are arranged within a room is called",
      ["space allocation", "colour selection only", "lighting only", "ventilation only"], "space allocation",
      "Space allocation considers how furniture and open areas are arranged within a room to optimise function, flow, and comfort."),
  _q("A key principle of interior design concerned with choosing hues that create a desired mood or complement a room's function is called",
      ["colour selection", "space allocation only", "furniture arrangement only", "ventilation only"], "colour selection",
      "Colour selection involves choosing hues that create a desired atmosphere and complement the intended use of a room."),
  _q("A key principle of interior design concerned with positioning furniture to balance function, traffic flow, and appearance is called",
      ["furniture arrangement", "space allocation only", "colour selection only", "lighting only"], "furniture arrangement",
      "Furniture arrangement considers how pieces are positioned to support the room's function, allow comfortable movement, and create visual balance."),
  _q("A key principle of interior design concerned with the natural or artificial illumination provided within a room is called",
      ["lighting", "ventilation only", "space allocation only", "colour selection only"], "lighting",
      "Lighting design considers both natural and artificial illumination sources, affecting a room's mood, function, and visual comfort."),
  _q("A key principle of interior design concerned with the movement of fresh air through a room, important for comfort and health, is called",
      ["ventilation", "lighting only", "colour selection only", "furniture arrangement only"], "ventilation",
      "Ventilation ensures adequate fresh air circulation within a room, important for both comfort and healthy indoor air quality."),
  _q("Items such as curtains, cushions, and rugs, used to add comfort and decorative appeal to a room, are collectively known as",
      ["soft furnishings", "hard furnishings only", "structural fittings only", "ironmongery"], "soft furnishings",
      "Soft furnishings, such as curtains, cushions, and rugs, add comfort, texture, and decorative appeal to interior spaces."),
  _q("Before purchasing a refrigerator, an important consideration is its",
      ["energy efficiency and storage capacity relative to family needs", "exterior colour alone, regardless of function", "brand name alone, regardless of features", "weight alone, regardless of capacity"], "energy efficiency and storage capacity relative to family needs",
      "Energy efficiency and appropriate storage capacity are key practical considerations when selecting a refrigerator suited to a family's needs."),
  _q("A key safety practice when using a gas cooker at home is to",
      ["regularly check for gas leaks and ensure proper ventilation", "ignore the smell of gas, assuming it is not dangerous", "store the cooker in an unventilated, sealed room", "leave the gas supply valve permanently open when not cooking"], "regularly check for gas leaks and ensure proper ventilation",
      "Regularly checking for leaks and maintaining good ventilation are essential safety practices for households using gas cookers."),
  _q("A key maintenance practice for extending the life of a washing machine is to",
      ["avoid overloading it and follow the manufacturer's care instructions", "always overload it to save time on multiple loads", "ignore all manufacturer guidelines", "leave it permanently connected to water even when not in use, with no supervision"], "avoid overloading it and follow the manufacturer's care instructions",
      "Avoiding overloading and following manufacturer guidelines helps extend the working life and performance of a washing machine."),
  _q("Small kitchen utensils, such as knives and graters, should generally be",
      ["cleaned, dried, and stored safely after each use", "left wet and unwashed after use", "stored loosely mixed together with no organisation", "left exposed to moisture indefinitely"], "cleaned, dried, and stored safely after each use",
      "Proper cleaning, drying, and safe storage of small kitchen utensils after use helps maintain hygiene and prevent accidents or damage."),
  _q("A major factor influencing the overall cost of building or purchasing a house is",
      ["its location and the quality of materials used in construction", "the number of family members who will visit occasionally", "the colour of the surrounding neighbourhood's houses", "the season in which the family plans to move in"], "its location and the quality of materials used in construction",
      "Location and the quality of construction materials are major factors influencing the overall cost of a house."),
  _q("Understanding a product's warranty before purchase helps a consumer mainly by",
      ["clarifying what repairs or replacements are covered if the product fails", "guaranteeing the product will never develop any fault", "eliminating the need to keep the purchase receipt", "reducing the actual purchase price of the item"], "clarifying what repairs or replacements are covered if the product fails",
      "A warranty specifies what repairs, replacements, or remedies are available if a product develops a fault, helping consumers understand their protections before a fault occurs."),
  _q("One of the basic rights of a consumer is the right to",
      ["safety, ensuring products purchased do not pose unreasonable harm", "purchase any product regardless of its safety record", "receive false or misleading information from sellers", "be denied any information about a product before purchase"], "safety, ensuring products purchased do not pose unreasonable harm",
      "The right to safety is a fundamental consumer right, protecting buyers from products that could cause unreasonable harm."),
  _q("One of the basic rights of a consumer is the right to",
      ["be informed, receiving accurate information needed to make a wise purchasing decision", "be deliberately misled by sellers regarding product quality", "be denied any choice among available products", "be charged prices with no relation to product value"], "be informed, receiving accurate information needed to make a wise purchasing decision",
      "The right to be informed ensures consumers receive accurate, adequate information to make well-considered purchasing decisions."),
  _q("One of the basic responsibilities of a consumer is to",
      ["use products safely and according to the manufacturer's instructions", "ignore all safety instructions provided with a product", "avoid ever reporting faulty or unsafe products", "deliberately misuse products without any consequence"], "use products safely and according to the manufacturer's instructions",
      "Consumers share responsibility for using products safely and correctly, following manufacturer instructions to avoid harm or misuse."),
  _q("A key reason to keep receipts after making a purchase is to",
      ["provide proof of purchase for warranty claims, returns, or exchanges", "prevent any future returns or exchanges from being processed", "increase the price of the item retroactively", "eliminate the need for any consumer protection at all"], "provide proof of purchase for warranty claims, returns, or exchanges",
      "Keeping receipts provides essential proof of purchase, often required to process warranty claims, returns, or exchanges."),
  _q("Comparing unit prices (cost per standard quantity) when shopping helps consumers to",
      ["identify the most economical option among different package sizes or brands", "always choose the most expensive option available", "ignore price differences between similar products", "avoid comparing any products before purchase"], "identify the most economical option among different package sizes or brands",
      "Comparing unit prices allows consumers to accurately identify the most economical choice, even when comparing different package sizes or brands."),
  _q("A key factor to consider regarding a house's location is its",
      ["proximity to essential amenities such as schools, markets, and healthcare facilities", "distance from all forms of transportation", "isolation from any form of community or infrastructure", "complete lack of access to water or electricity"], "proximity to essential amenities such as schools, markets, and healthcare facilities",
      "A house's proximity to essential amenities like schools, markets, and healthcare significantly affects its convenience and suitability for a family."),
  _q("Before purchasing land or a house, verifying legal ownership documents is important mainly to",
      ["avoid disputes over rightful ownership in the future", "increase the total cost of the transaction unnecessarily", "eliminate the need for any future documentation", "guarantee immediate resale value regardless of condition"], "avoid disputes over rightful ownership in the future",
      "Verifying legal ownership documents before purchase helps prevent future disputes over rightful ownership of the property."),
  _q("A house's structural integrity refers mainly to",
      ["the soundness and safety of its physical construction", "the colour scheme used for interior decoration", "the number of visitors it typically receives", "the style of furniture placed within it"], "the soundness and safety of its physical construction",
      "Structural integrity concerns the physical soundness and safety of a building's construction, a critical factor when choosing a house."),
  _q("Natural lighting in a room, provided through windows, is generally preferred where possible mainly because it",
      ["reduces reliance on artificial lighting and can improve mood and wellbeing", "always increases household electricity costs", "has no effect on the room's atmosphere", "eliminates the need for any ventilation"], "reduces reliance on artificial lighting and can improve mood and wellbeing",
      "Natural lighting reduces the need for artificial light sources and can positively affect mood and general wellbeing within a home."),
  _q("Selecting furniture appropriate to the size of a room is important mainly to",
      ["avoid overcrowding and maintain comfortable movement within the space", "ensure the room is always completely empty", "guarantee that furniture never matches the room's colour scheme", "eliminate the need for any furniture arrangement planning"], "avoid overcrowding and maintain comfortable movement within the space",
      "Appropriately sized furniture prevents overcrowding, maintaining comfortable movement and a balanced appearance within a room."),
  _q("A well-designed kitchen layout in a home should ideally",
      ["support an efficient workflow between storage, preparation, and cooking areas", "combine sleeping and cooking areas into a single undivided space", "eliminate the need for any storage space", "position all equipment far from any workflow logic"], "support an efficient workflow between storage, preparation, and cooking areas",
      "An effective kitchen layout, similar to the culinary work triangle principle, supports smooth movement and workflow between storage, preparation, and cooking areas."),
  _q("Before purchasing a gas cooker for the home, an important safety consideration is",
      ["verifying that it meets recognised safety standards and has functioning safety features", "ignoring any certification or safety standard entirely", "choosing the cheapest option regardless of safety features", "assuming all cookers are equally safe regardless of brand"], "verifying that it meets recognised safety standards and has functioning safety features",
      "Verifying that a gas cooker meets recognised safety standards helps ensure safer operation and reduces the risk of accidents in the home."),
  _q("Regular servicing and cleaning of major household appliances, such as refrigerators and cookers, helps to",
      ["extend their working lifespan and maintain efficient performance", "shorten their working lifespan intentionally", "increase the risk of malfunction over time", "eliminate the need for any future maintenance"], "extend their working lifespan and maintain efficient performance",
      "Regular servicing and cleaning helps extend the working lifespan of household appliances and keeps them operating efficiently."),
];

final _familyLifeHealthAndHospitality = [
  _q("A family structure consisting of parents and their children living together, without other relatives, is called a",
      ["nuclear family", "extended family", "blended family", "single-parent family only"], "nuclear family",
      "A nuclear family consists of parents and their children living as a single household unit, distinct from extended family arrangements."),
  _q("A family structure that includes parents, children, and other relatives such as grandparents, uncles, or aunts living together or closely connected, is called an",
      ["extended family", "nuclear family", "blended family", "single-parent family only"], "extended family",
      "An extended family includes additional relatives beyond parents and children, such as grandparents or other relatives, often living together or maintaining close ties."),
  _q("A family structure formed when parents with children from previous relationships combine to form a new family unit is called a",
      ["blended family", "nuclear family", "extended family only", "single-parent family only"], "blended family",
      "A blended family forms when parents, each potentially bringing children from previous relationships, unite to create a new combined family unit."),
  _q("Within a household, the role of providing financial support, guidance, and protection is traditionally associated with",
      ["parents (or guardians) as heads of the household", "young children exclusively", "distant relatives with no household ties", "no one in particular, as roles are never defined"], "parents (or guardians) as heads of the household",
      "Parents or guardians traditionally hold primary responsibility for providing financial support, guidance, and protection within a household, though roles can vary by family."),
  _q("Proper disposal of solid waste in the home, such as regular refuse collection and appropriate bins, is important mainly to",
      ["prevent the spread of disease and maintain a clean, healthy environment", "increase the accumulation of waste around the home", "attract pests and rodents intentionally", "have no effect on household health at all"], "prevent the spread of disease and maintain a clean, healthy environment",
      "Proper solid waste disposal prevents the buildup of refuse that can attract pests and spread disease, supporting a clean, healthy home environment."),
  _q("Proper disposal of liquid waste, such as through appropriate drainage systems, is important mainly to",
      ["prevent contamination of water sources and reduce breeding grounds for disease vectors", "increase the risk of water contamination intentionally", "have no impact on public health", "eliminate the need for any water supply system"], "prevent contamination of water sources and reduce breeding grounds for disease vectors",
      "Proper liquid waste disposal prevents contamination of clean water sources and reduces breeding grounds for disease-carrying insects like mosquitoes."),
  _q("Access to a clean, safe water supply within the home is essential mainly for",
      ["drinking, cooking, and hygiene, preventing waterborne diseases", "decorative purposes only", "increasing household expenses unnecessarily", "no significant health-related purpose"], "drinking, cooking, and hygiene, preventing waterborne diseases",
      "Clean water is essential for safe drinking, cooking, and hygiene practices, directly helping to prevent waterborne diseases within the household."),
  _q("Effective pest and rodent control in the home is important mainly to",
      ["prevent damage to property and reduce the risk of disease transmission", "encourage the growth of pest populations", "increase food contamination risks intentionally", "have no bearing on household health or safety"], "prevent damage to property and reduce the risk of disease transmission",
      "Pests and rodents can damage property and carry diseases, making effective control measures important for maintaining a safe, healthy home."),
  _q("Basic home first-aid nursing skills, such as treating minor cuts and burns, are important mainly to",
      ["provide immediate care for minor injuries before further medical attention, if needed", "replace the need for professional medical care in all situations", "worsen minor injuries intentionally", "have no practical benefit within the household"], "provide immediate care for minor injuries before further medical attention, if needed",
      "Basic first-aid skills allow household members to provide immediate, appropriate care for minor injuries, and to stabilise more serious situations before professional help arrives."),
  _q("Planning a hospitality event, such as a family celebration, generally involves considering",
      ["the guest list, menu, venue, and budget in advance", "no advance preparation of any kind", "inviting guests without any consideration of numbers or space", "ignoring the preferences and needs of guests entirely"], "the guest list, menu, venue, and budget in advance",
      "Effective event planning considers key factors such as the guest list, menu, venue, and budget well in advance of the occasion."),
  _q("A formal table setting typically includes",
      ["a defined arrangement of cutlery, glassware, and dishware according to the courses to be served", "no defined arrangement at all", "only a single plate with no other place settings", "identical arrangements regardless of the meal being served"], "a defined arrangement of cutlery, glassware, and dishware according to the courses to be served",
      "Formal table settings follow established conventions for arranging cutlery, glassware, and dishware, often varying according to the specific courses to be served."),
  _q("An informal table setting, compared to a formal one, is generally",
      ["simpler and more relaxed, with fewer pieces of cutlery and less rigid arrangement", "more elaborate and rigidly structured than a formal setting", "identical in every respect to a formal table setting", "used exclusively for large, ceremonial banquets"], "simpler and more relaxed, with fewer pieces of cutlery and less rigid arrangement",
      "Informal table settings are generally simpler and more relaxed than formal settings, using fewer utensils and less rigid arrangement."),
  _q("Good serving etiquette when hosting guests generally includes",
      ["serving food from the left and clearing plates from the right, or following consistent local convention", "serving food in a completely random and inconsistent manner", "ignoring guests' dietary preferences entirely", "serving the host before any guests, in every situation"], "serving food from the left and clearing plates from the right, or following consistent local convention",
      "Traditional Western serving etiquette generally follows serving from the left and clearing from the right, though the key principle is consistent, considerate practice."),
  _q("Good social manners during a shared meal generally include",
      ["polite conversation, appropriate table manners, and consideration for other guests", "ignoring other guests entirely throughout the meal", "speaking with a full mouth as a sign of enjoyment", "leaving the table abruptly without any acknowledgement"], "polite conversation, appropriate table manners, and consideration for other guests",
      "Good social manners at a shared meal include polite conversation, proper table manners, and general consideration and courtesy toward other guests."),
  _q("A key consideration when planning the menu for a hospitality event is",
      ["the dietary preferences, restrictions, and number of guests attending", "ignoring guests' preferences entirely", "preparing only foods the host personally dislikes", "selecting a menu with no regard for the number of attendees"], "the dietary preferences, restrictions, and number of guests attending",
      "Effective menu planning takes into account guests' dietary preferences, restrictions, and the total number of people attending the event."),
  _q("A key advantage of the nuclear family structure is that it",
      ["allows for closer, more direct supervision of children by their immediate parents", "always includes numerous extended relatives living together", "guarantees greater financial resources than any other family type", "eliminates the need for any parental responsibility"], "allows for closer, more direct supervision of children by their immediate parents",
      "The nuclear family structure often allows for closer, more direct parental supervision and attention, given its smaller, more immediate household unit."),
  _q("A key advantage of the extended family structure is that it",
      ["provides additional support, such as childcare and shared resources, from wider family members", "always eliminates the need for any parental responsibility", "guarantees there will be no family conflict of any kind", "excludes grandparents and other relatives from any involvement"], "provides additional support, such as childcare and shared resources, from wider family members",
      "Extended family structures often provide valuable additional support, such as shared childcare responsibilities and pooled resources among relatives."),
  _q("Within a household, the role of children generally includes",
      ["assisting with age-appropriate chores and respecting household rules", "having no responsibilities of any kind within the home", "making all major financial decisions for the family", "being solely responsible for the family's income"], "assisting with age-appropriate chores and respecting household rules",
      "Children typically contribute to household life through age-appropriate chores and by respecting the rules and structure set within the family."),
  _q("Good sanitation practices in the home include",
      ["regular cleaning, proper waste disposal, and maintaining clean water sources", "allowing waste to accumulate indefinitely", "avoiding any form of regular cleaning", "contaminating water sources intentionally"], "regular cleaning, proper waste disposal, and maintaining clean water sources",
      "Good sanitation combines regular cleaning, proper waste disposal, and protection of clean water sources to maintain a healthy home environment."),
  _q("A soakaway pit, used in some home sanitation systems, functions mainly to",
      ["allow wastewater to gradually disperse and filter into the surrounding soil", "store clean drinking water for household use", "generate electricity for the home", "act as the primary cooking area of the home"], "allow wastewater to gradually disperse and filter into the surrounding soil",
      "A soakaway pit allows treated wastewater to disperse gradually into the surrounding soil, a common feature of some home sanitation systems."),
  _q("A basic home first-aid kit should generally include items such as",
      ["antiseptic, bandages, and adhesive plasters", "only sharp tools with no protective supplies", "expired medications only", "no supplies at all, relying solely on professional help"], "antiseptic, bandages, and adhesive plasters",
      "A well-stocked basic first-aid kit typically includes antiseptic, bandages, and adhesive plasters, among other essential supplies for treating minor injuries."),
  _q("When treating a minor cut at home, the first step generally recommended is to",
      ["clean the wound and stop any bleeding using gentle pressure", "ignore the wound completely without any treatment", "apply an unclean cloth directly to the wound", "avoid any form of first aid regardless of severity"], "clean the wound and stop any bleeding using gentle pressure",
      "For a minor cut, the recommended first step is to clean the wound and apply gentle pressure to control any bleeding, before further care such as bandaging."),
  _q("A well-planned family celebration, such as a birthday or naming ceremony, typically requires advance consideration of",
      ["the budget, guest list, venue, and required materials", "no planning at all, relying entirely on spontaneous decisions", "excluding any consideration of cost", "ignoring the preferences of family members entirely"], "the budget, guest list, venue, and required materials",
      "Successful family celebrations require advance planning across several areas, including budget, guest list, venue, and materials needed."),
  _q("Proper etiquette when receiving guests in the home generally includes",
      ["greeting them warmly and ensuring their comfort", "ignoring guests upon their arrival", "leaving guests unattended throughout their visit", "showing open hostility toward invited guests"], "greeting them warmly and ensuring their comfort",
      "Good hospitality etiquette begins with a warm greeting and continues with attentiveness to guests' comfort throughout their visit."),
  _q("A napkin at a formal table setting is generally placed",
      ["to the left of the forks, or on the centre of the plate", "underneath the tablecloth, out of sight", "directly on the floor beside the chair", "inside a closed drawer during the meal"], "to the left of the forks, or on the centre of the plate",
      "In formal table settings, the napkin is conventionally placed either to the left of the forks or folded on the centre of the plate."),
  _q("At a formal dinner, cutlery is generally used",
      ["from the outside in, working toward the plate as each course is served", "from the plate outward, in reverse of the conventional order", "in any random order, with no defined sequence", "using only one utensil throughout the entire meal"], "from the outside in, working toward the plate as each course is served",
      "Formal dining etiquette conventionally uses cutlery from the outside in, with each utensil corresponding to a specific course as the meal progresses."),
  _q("A key aspect of good hospitality when serving guests with dietary restrictions is to",
      ["ask about their needs in advance and accommodate them where possible", "ignore any dietary restrictions entirely", "serve only foods that conflict with their known restrictions", "assume all guests share identical dietary preferences"], "ask about their needs in advance and accommodate them where possible",
      "Good hospitality involves proactively asking about guests' dietary needs in advance and accommodating them wherever reasonably possible."),
  _q("The primary function of the family as a social unit includes",
      ["providing emotional support, socialisation, and care for its members", "isolating its members from all social interaction", "eliminating any responsibility for child development", "providing no economic or emotional function whatsoever"], "providing emotional support, socialisation, and care for its members",
      "Families serve fundamental social functions, including providing emotional support, socialisation, and care for their members throughout life."),
  _q("Regular health check-ups for family members are important mainly to",
      ["detect potential health issues early and maintain overall wellbeing", "increase household expenses without any real benefit", "replace the need for good sanitation practices", "have no bearing on a family's overall wellbeing"], "detect potential health issues early and maintain overall wellbeing",
      "Regular health check-ups help detect potential health issues early, supporting the overall health and wellbeing of family members."),
  _q("Adequate home ventilation contributes to family health mainly by",
      ["reducing the buildup of indoor pollutants and improving air quality", "increasing indoor pollutant levels intentionally", "eliminating the need for any fresh air circulation", "having no effect on indoor air quality"], "reducing the buildup of indoor pollutants and improving air quality",
      "Good ventilation reduces the buildup of indoor pollutants and stale air, contributing to better indoor air quality and family health."),
  _q("A well-organised host, when planning a hospitality event, should ideally prepare a",
      ["checklist of tasks and a realistic timeline leading up to the event", "single, vague idea with no concrete details", "plan finalised only after the event has already begun", "list of tasks with no consideration of time constraints"], "checklist of tasks and a realistic timeline leading up to the event",
      "Effective event planning benefits from a clear checklist of tasks and a realistic timeline, ensuring all preparations are completed in good time."),
  _q("Understanding basic social manners, such as saying 'please' and 'thank you', contributes to",
      ["positive social relationships and mutual respect among family and guests", "unnecessary formality with no real social benefit", "increased conflict between family members and guests", "no meaningful effect on social relationships"], "positive social relationships and mutual respect among family and guests",
      "Basic social manners, such as courteous expressions, help build positive relationships and demonstrate mutual respect among family members and guests."),
  _q("The way household chores are distributed among family members can significantly affect",
      ["family harmony and each member's sense of shared responsibility", "only the physical appearance of the home, with no other effects", "nothing of significance within the family dynamic", "only the family's financial situation, with no social impact"], "family harmony and each member's sense of shared responsibility",
      "How chores are distributed can meaningfully affect family harmony and how responsible each member feels for the household's overall functioning."),
  _q("A family's approach to conflict resolution significantly affects",
      ["the overall emotional wellbeing and stability of the household", "only the physical cleanliness of the home", "nothing related to household functioning", "only the family's financial planning process"], "the overall emotional wellbeing and stability of the household",
      "How a family resolves conflict has a significant impact on the emotional wellbeing and overall stability of the household."),
];
