import "../quiz_question.dart";

const _subject = "Basic Electronics";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// WAEC Basic Electronics question bank covering the full syllabus:
/// Semiconductor Physics & Passive Components, Active Devices & Power
/// Supplies (diodes, rectification, BJTs), and Communication Systems,
/// Electronic Tools & Digital Logic.
List<QuizQuestion> buildWaecBasicElectronicsQuestions() {
  return [
    ..._semiconductorPhysicsAndPassiveComponents,
    ..._activeDevicesAndPowerSupplies,
    ..._communicationDigitalLogicAndTools,
  ];
}

final _semiconductorPhysicsAndPassiveComponents = [
  _q("A pure semiconductor material, containing no deliberately added impurities, is called an",
      ["intrinsic semiconductor", "extrinsic semiconductor", "P-type semiconductor only", "N-type semiconductor only"], "intrinsic semiconductor",
      "An intrinsic semiconductor is in its pure form, without deliberately introduced impurities that would alter its conductive properties."),
  _q("A semiconductor material that has been deliberately doped with impurities to alter its electrical properties is called an",
      ["extrinsic semiconductor", "intrinsic semiconductor", "pure semiconductor only", "insulator"], "extrinsic semiconductor",
      "Extrinsic semiconductors are intentionally doped with impurity atoms to modify their conductivity, forming either P-type or N-type material."),
  _q("The process of intentionally adding impurity atoms to a pure semiconductor to modify its electrical properties is called",
      ["doping", "annealing", "rectification", "biasing"], "doping",
      "Doping introduces controlled amounts of impurity atoms into a semiconductor crystal, creating either P-type or N-type material."),
  _q("Semiconductor material doped with trivalent impurity atoms, such as boron, creating an excess of 'holes' (positive charge carriers), is called",
      ["P-type material", "N-type material", "intrinsic material", "insulating material"], "P-type material",
      "P-type semiconductor material is created by doping with trivalent atoms (like boron), producing an excess of positive charge carriers called holes."),
  _q("Semiconductor material doped with pentavalent impurity atoms, such as phosphorus, creating an excess of free electrons, is called",
      ["N-type material", "P-type material", "intrinsic material", "insulating material"], "N-type material",
      "N-type semiconductor material is created by doping with pentavalent atoms (like phosphorus), producing an excess of free electrons as charge carriers."),
  _q("The junction formed where P-type and N-type semiconductor materials meet within a single crystal is called the",
      ["P-N junction", "depletion layer only", "barrier potential only", "forward bias region only"], "P-N junction",
      "The P-N junction is the boundary region where P-type and N-type materials meet, forming the basis of diodes and other semiconductor devices."),
  _q("The narrow region around a P-N junction that becomes depleted of free charge carriers is called the",
      ["depletion layer", "barrier potential", "P-N junction itself", "forward bias voltage"], "depletion layer",
      "The depletion layer is the region around the junction where charge carriers have diffused across and recombined, leaving it depleted of free carriers."),
  _q("The small voltage that naturally develops across a P-N junction, opposing further diffusion of charge carriers, is called the",
      ["barrier potential", "depletion layer", "forward bias", "reverse bias"], "barrier potential",
      "The barrier potential is the built-in voltage across the depletion layer that must be overcome for significant current to flow through the junction."),
  _q("Applying a voltage to a P-N junction in a way that reduces the barrier potential and allows current to flow easily is called",
      ["forward biasing", "reverse biasing", "zero biasing", "self biasing"], "forward biasing",
      "Forward biasing connects the voltage source so as to reduce the barrier potential, allowing current to flow readily through the junction."),
  _q("Applying a voltage to a P-N junction in a way that increases the barrier potential and prevents significant current flow is called",
      ["reverse biasing", "forward biasing", "zero biasing", "self biasing"], "reverse biasing",
      "Reverse biasing connects the voltage source so as to widen the depletion layer and increase the barrier, blocking significant current flow except a small leakage current."),
  _q("A resistor manufactured from a mixture of carbon granules and a binding material, one of the most common and inexpensive types, is called a",
      ["carbon composition resistor", "wire-wound resistor", "film resistor", "potentiometer"], "carbon composition resistor",
      "Carbon composition resistors are made from a compressed mixture of carbon and binder, offering a simple and inexpensive fixed resistance."),
  _q("A resistor manufactured by depositing a thin resistive layer, such as carbon or metal, onto an insulating substrate, offering improved precision, is called a",
      ["film resistor", "carbon composition resistor", "wire-wound resistor", "rheostat"], "film resistor",
      "Film resistors deposit a thin resistive film onto a substrate, generally offering better precision and stability than carbon composition types."),
  _q("A resistor manufactured by winding resistance wire around an insulating core, often used where higher power ratings are needed, is called a",
      ["wire-wound resistor", "carbon composition resistor", "film resistor", "potentiometer"], "wire-wound resistor",
      "Wire-wound resistors use a coiled resistance wire, allowing them to handle higher power dissipation than typical carbon or film resistors."),
  _q("A variable resistor with three terminals, commonly used to adjust voltage levels such as volume controls, is called a",
      ["potentiometer", "rheostat", "fixed resistor", "capacitor"], "potentiometer",
      "A potentiometer has three terminals and is typically used to create an adjustable voltage divider, such as in volume controls."),
  _q("A variable resistor with two terminals, commonly used to control current in a circuit, is called a",
      ["rheostat", "potentiometer", "fixed resistor", "capacitor"], "rheostat",
      "A rheostat typically uses two terminals to vary resistance and directly control current flow in a circuit."),
  _q("The standardised system using coloured bands to indicate the resistance value and tolerance of a fixed resistor is called",
      ["resistor colour coding", "capacitor labelling", "wire gauge marking", "diode polarity marking"], "resistor colour coding",
      "Resistor colour coding uses a standardised sequence of coloured bands to indicate a resistor's value, tolerance, and sometimes temperature coefficient."),
  _q("A capacitor constructed using a polarised design, generally offering high capacitance in a compact size, is called an",
      ["electrolytic capacitor", "ceramic capacitor", "mica capacitor", "variable capacitor"], "electrolytic capacitor",
      "Electrolytic capacitors are polarised and can offer relatively high capacitance values in a compact package, but must be connected with correct polarity."),
  _q("A capacitor constructed using a ceramic material as its dielectric, commonly small and non-polarised, is called a",
      ["ceramic capacitor", "electrolytic capacitor", "mica capacitor only", "variable capacitor"], "ceramic capacitor",
      "Ceramic capacitors use a ceramic dielectric and are typically small, non-polarised, and widely used for general-purpose applications."),
  _q("The capacitance of a capacitor is defined by the formula",
      ["C = Q/V (charge divided by voltage)", "C = V/Q (voltage divided by charge)", "C = QV (charge multiplied by voltage)", "C = Q + V (charge plus voltage)"], "C = Q/V (charge divided by voltage)",
      "Capacitance (C) is defined as the ratio of stored charge (Q) to the voltage (V) across the capacitor's plates."),
  _q("When capacitors are connected in parallel, the total capacitance is",
      ["the sum of all individual capacitances", "the reciprocal of the sum of reciprocals of individual capacitances", "always equal to the smallest individual capacitance", "always equal to zero"], "the sum of all individual capacitances",
      "Capacitors in parallel simply add their capacitance values together, unlike resistors in parallel."),
  _q("When capacitors are connected in series, the total capacitance is calculated using the",
      ["reciprocal sum formula (1/C total = 1/C1 + 1/C2 + ...)", "direct sum of the individual capacitances", "product of the individual capacitances directly", "average of the individual capacitances"], "reciprocal sum formula (1/C total = 1/C1 + 1/C2 + ...)",
      "Series-connected capacitors combine using the reciprocal sum formula, analogous to how resistors combine in parallel."),
  _q("A component made from a coil of wire, used to store energy in a magnetic field when current flows through it, is called an",
      ["inductor", "capacitor", "resistor", "diode"], "inductor",
      "An inductor stores energy in a magnetic field generated by current flowing through its coiled winding."),
  _q("An inductor wound around a non-magnetic core, such as plastic or cardboard, is called an",
      ["air-core inductor", "iron-core inductor", "ceramic-core inductor", "variable inductor only"], "air-core inductor",
      "Air-core inductors are wound with no magnetic core material, typically used for lower-inductance, higher-frequency applications."),
  _q("An inductor wound around a magnetic material, such as laminated iron, generally providing a higher inductance for a given coil size, is called an",
      ["iron-core inductor", "air-core inductor", "ceramic-core inductor only", "resistive inductor"], "iron-core inductor",
      "Iron-core inductors use a magnetic core material to concentrate the magnetic field, achieving greater inductance than an equivalent air-core design."),
  _q("The opposition an inductor presents to alternating current, which increases with frequency, is called its",
      ["inductive reactance (XL)", "capacitive reactance", "resistance", "conductance"], "inductive reactance (XL)",
      "Inductive reactance (XL = 2*pi*f*L) increases with both frequency and inductance, representing the AC opposition presented by an inductor."),
  _q("The opposition a capacitor presents to alternating current, which decreases as frequency increases, is called its",
      ["capacitive reactance (XC)", "inductive reactance", "resistance", "conductance"], "capacitive reactance (XC)",
      "Capacitive reactance decreases as frequency increases, the opposite behaviour to inductive reactance, reflecting how capacitors respond to AC signals."),
  _q("A capacitor made using thin mica sheets as the dielectric material, valued for stability and precision at higher frequencies, is called a",
      ["mica capacitor", "electrolytic capacitor", "ceramic capacitor only", "wire-wound capacitor"], "mica capacitor",
      "Mica capacitors use thin mica sheets as a dielectric, offering good stability and precision, often used in high-frequency and precision applications."),
  _q("A capacitor whose capacitance value can be adjusted, commonly used for tuning circuits such as radio receivers, is called a",
      ["variable capacitor", "electrolytic capacitor", "ceramic capacitor only", "mica capacitor only"], "variable capacitor",
      "Variable capacitors allow the capacitance value to be adjusted mechanically, commonly used for tuning applications such as radio receivers."),
  _q("The first colour band on a resistor, read from the end closest to it, generally represents the",
      ["first significant digit of the resistance value", "resistor's tolerance only", "resistor's power rating only", "temperature coefficient only"], "first significant digit of the resistance value",
      "The first colour band on a standard resistor indicates the first significant digit of its resistance value, following the standard colour code sequence."),
  _q("The final colour band on many resistors, often gold or silver, typically indicates the",
      ["tolerance of the resistance value", "first significant digit", "second significant digit", "power rating in watts"], "tolerance of the resistance value",
      "The final band on a resistor typically indicates its tolerance, showing the permissible variation from its nominal stated value (e.g., gold for ±5%)."),
  _q("Energy stored in a charged capacitor is held in the form of an",
      ["electric field between its plates", "magnetic field around its leads", "electric current flowing continuously", "electromagnetic wave radiating outward"], "electric field between its plates",
      "A capacitor stores energy in the electric field established between its two conductive plates, separated by the dielectric material."),
  _q("Energy stored in a current-carrying inductor is held in the form of a",
      ["magnetic field around its coil", "electric field between its terminals", "electric current flowing indefinitely with no source", "chemical reaction within its winding"], "magnetic field around its coil",
      "An inductor stores energy in the magnetic field generated by current flowing through its coiled winding."),
  _q("Doping a semiconductor with a pentavalent element such as phosphorus adds extra electrons because phosphorus has",
      ["five valence electrons, one more than needed for the four covalent bonds in the crystal lattice", "three valence electrons, one fewer than needed for the crystal lattice", "exactly four valence electrons, matching silicon precisely", "no valence electrons at all"], "five valence electrons, one more than needed for the four covalent bonds in the crystal lattice",
      "Phosphorus has five valence electrons; four form covalent bonds within the silicon lattice, leaving one extra electron free to conduct."),
  _q("Doping a semiconductor with a trivalent element such as boron creates 'holes' because boron has",
      ["three valence electrons, one fewer than needed to complete the four covalent bonds in the crystal lattice", "five valence electrons, one more than needed for the crystal lattice", "exactly four valence electrons, matching silicon precisely", "no valence electrons at all"], "three valence electrons, one fewer than needed to complete the four covalent bonds in the crystal lattice",
      "Boron has only three valence electrons, leaving one covalent bond incomplete within the silicon lattice, creating a 'hole' that can accept an electron."),
];

final _activeDevicesAndPowerSupplies = [
  _q("A basic semiconductor device that allows current to flow easily in one direction but blocks it in the other is called a",
      ["diode", "resistor", "capacitor", "inductor"], "diode",
      "A diode is a two-terminal semiconductor device that conducts current readily in one direction (forward biased) but blocks it in the reverse direction."),
  _q("A diode primarily designed to handle small signal currents, commonly used in radio and communication circuits, is called a",
      ["signal diode", "power rectifier diode", "Zener diode", "photodiode"], "signal diode",
      "Signal diodes are optimised for handling small currents at typically higher frequencies, common in radio and communication circuit applications."),
  _q("A diode designed to handle larger currents, commonly used to convert AC to DC in power supply circuits, is called a",
      ["power rectifier diode", "signal diode", "Zener diode", "LED"], "power rectifier diode",
      "Power rectifier diodes are built to handle higher currents, making them suitable for converting AC to DC in power supply circuits."),
  _q("A diode specifically designed to operate in reverse breakdown, maintaining a stable voltage across it, commonly used for voltage regulation, is called a",
      ["Zener diode", "signal diode", "power rectifier diode", "photodiode"], "Zener diode",
      "Zener diodes are designed to operate safely in reverse breakdown, maintaining a stable output voltage, widely used in voltage regulator circuits."),
  _q("A diode that emits visible (or invisible) light when forward biased is called a",
      ["Light Emitting Diode (LED)", "photodiode", "Zener diode", "signal diode"], "Light Emitting Diode (LED)",
      "An LED emits light when forward biased, converting electrical energy into light energy, widely used as indicators and in displays."),
  _q("A diode whose reverse current increases significantly when exposed to light, used in light-sensing applications, is called a",
      ["photodiode", "LED", "Zener diode", "signal diode"], "photodiode",
      "A photodiode's reverse current is sensitive to light intensity, making it useful for light-sensing and detection applications."),
  _q("The rectification process using only one diode (or one half of the input waveform) to convert AC to a pulsating DC output is called",
      ["half-wave rectification", "full-wave rectification", "bridge rectification only", "shunt regulation"], "half-wave rectification",
      "Half-wave rectification uses a single diode to conduct only during one half of the AC cycle, producing a pulsating output with significant gaps."),
  _q("The rectification process that converts both halves of the AC input waveform into a smoother pulsating DC output is called",
      ["full-wave rectification", "half-wave rectification", "shunt regulation", "clamping"], "full-wave rectification",
      "Full-wave rectification utilises both halves of the AC cycle, producing a pulsating DC output with fewer gaps than half-wave rectification."),
  _q("A full-wave rectifier design using a transformer with a centre-tapped secondary winding and two diodes is called a",
      ["centre-tapped full-wave rectifier", "bridge rectifier", "half-wave rectifier", "voltage doubler"], "centre-tapped full-wave rectifier",
      "The centre-tapped design uses a transformer's centre tap along with two diodes to achieve full-wave rectification."),
  _q("A full-wave rectifier design using four diodes arranged in a diamond configuration, without requiring a centre-tapped transformer, is called a",
      ["bridge rectifier", "centre-tapped rectifier", "half-wave rectifier", "voltage doubler"], "bridge rectifier",
      "The bridge rectifier uses four diodes arranged to achieve full-wave rectification without needing a centre-tapped transformer."),
  _q("A filter circuit using a single capacitor connected across the rectifier's output to smooth the pulsating DC is called a",
      ["capacitor input filter", "LC filter only", "RC filter only", "choke filter alone"], "capacitor input filter",
      "A capacitor input filter smooths the rectifier's pulsating output by charging during peaks and discharging during troughs, reducing ripple."),
  _q("A filter circuit using both an inductor and a capacitor together to more effectively smooth a rectifier's output is called an",
      ["LC filter", "capacitor input filter alone", "resistive filter only", "Zener filter"], "LC filter",
      "An LC filter combines an inductor (choke) and a capacitor to more effectively smooth the pulsating rectified output, further reducing ripple."),
  _q("The measure of the remaining AC variation present in a filtered DC output is called the",
      ["ripple factor", "power factor", "barrier potential", "current gain"], "ripple factor",
      "The ripple factor quantifies the amount of residual AC variation remaining in a supposedly smooth DC output after filtering."),
  _q("A voltage regulation circuit using a Zener diode connected in parallel with the load to maintain a stable output voltage is called a",
      ["Zener shunt regulator", "series regulator only", "bridge rectifier", "half-wave rectifier"], "Zener shunt regulator",
      "A Zener shunt regulator places the Zener diode in parallel with the load, maintaining a stable voltage across it despite variations in supply or load current."),
  _q("A bipolar junction transistor formed with a layer of P-type material sandwiched between two layers of N-type material is called an",
      ["NPN transistor", "PNP transistor", "N-type diode", "P-type diode"], "NPN transistor",
      "An NPN transistor has a thin P-type base region sandwiched between N-type emitter and collector regions."),
  _q("A bipolar junction transistor formed with a layer of N-type material sandwiched between two layers of P-type material is called a",
      ["PNP transistor", "NPN transistor", "N-type diode", "P-type diode"], "PNP transistor",
      "A PNP transistor has a thin N-type base region sandwiched between P-type emitter and collector regions."),
  _q("The operating mode of a transistor in which both junctions are reverse biased, and the transistor conducts essentially no current, is called the",
      ["cut-off region", "active region", "saturation region", "breakdown region"], "cut-off region",
      "In cut-off, both transistor junctions are reverse biased, and the transistor behaves like an open switch, conducting almost no current."),
  _q("The operating mode of a transistor in which the emitter-base junction is forward biased and the collector-base junction is reverse biased, allowing proportional amplification, is called the",
      ["active region", "cut-off region", "saturation region", "breakdown region"], "active region",
      "In the active region, a transistor amplifies current proportionally, making it the operating mode used for linear amplification."),
  _q("The operating mode of a transistor in which both junctions are forward biased, and the transistor conducts maximum current, behaving like a closed switch, is called the",
      ["saturation region", "cut-off region", "active region", "breakdown region"], "saturation region",
      "In saturation, both junctions are forward biased, and the transistor conducts maximum current, effectively acting as a closed switch."),
  _q("A transistor configuration in which the base terminal is common to both the input and output circuits is called the",
      ["Common Base (CB) configuration", "Common Emitter (CE) configuration", "Common Collector (CC) configuration", "Common Ground configuration"], "Common Base (CB) configuration",
      "In the Common Base configuration, the base terminal is shared between input and output circuits, offering high voltage gain but low current gain."),
  _q("A transistor configuration in which the emitter terminal is common to both the input and output circuits, and is the most widely used configuration for amplification, is called the",
      ["Common Emitter (CE) configuration", "Common Base (CB) configuration", "Common Collector (CC) configuration", "Common Ground configuration"], "Common Emitter (CE) configuration",
      "The Common Emitter configuration, with the emitter shared between input and output, is the most commonly used transistor amplifier configuration."),
  _q("A transistor configuration in which the collector terminal is common to both the input and output circuits, often used as a buffer with high current gain, is called the",
      ["Common Collector (CC) configuration", "Common Base (CB) configuration", "Common Emitter (CE) configuration", "Common Ground configuration"], "Common Collector (CC) configuration",
      "The Common Collector configuration (emitter follower) shares the collector terminal between input and output, offering high current gain and low output impedance, useful as a buffer."),
  _q("The transistor current gain term 'alpha' (alpha) represents the ratio of",
      ["collector current to emitter current", "base current to collector current", "emitter current to base current", "collector current to base current"], "collector current to emitter current",
      "Alpha (a common-base current gain) represents the ratio of collector current to emitter current, always slightly less than one."),
  _q("The transistor current gain term 'beta' (beta) represents the ratio of",
      ["collector current to base current", "emitter current to collector current", "base current to emitter current", "collector current to emitter current"], "collector current to base current",
      "Beta (a common-emitter current gain) represents the ratio of collector current to base current, and is related to alpha through the formula beta = alpha/(1-alpha)."),
  _q("When a transistor is used as an electronic switch, it typically operates between the",
      ["cut-off and saturation regions", "active region only, avoiding both extremes", "breakdown region exclusively", "reverse active region only"], "cut-off and saturation regions",
      "As a switch, a transistor is driven between cut-off (fully off) and saturation (fully on), rather than operating in its linear active region."),
  _q("A key characteristic of a Zener diode used in a voltage regulator circuit is its",
      ["stable, nearly constant reverse breakdown voltage over a range of currents", "inability to conduct in either direction", "very high forward voltage drop compared to ordinary diodes", "requirement to always be forward biased for regulation to occur"], "stable, nearly constant reverse breakdown voltage over a range of currents",
      "Zener diodes maintain a relatively constant voltage across their terminals once in reverse breakdown, making them ideal for voltage regulation over a range of currents."),
  _q("The forward voltage drop across a typical silicon signal diode, once conducting, is approximately",
      ["0.7 volts", "0.3 volts", "5 volts", "12 volts"], "0.7 volts",
      "A typical silicon diode has an approximate forward voltage drop of 0.7 volts once it begins conducting significantly."),
  _q("The forward voltage drop across a typical germanium diode, once conducting, is approximately",
      ["0.3 volts", "0.7 volts", "5 volts", "12 volts"], "0.3 volts",
      "Germanium diodes typically have a lower forward voltage drop, around 0.3 volts, compared to silicon diodes at approximately 0.7 volts."),
  _q("A key advantage of full-wave rectification over half-wave rectification is that it",
      ["produces a smoother output with less ripple, using both halves of the AC cycle", "uses fewer diodes in every configuration", "eliminates the need for any filtering capacitor", "cannot be used with a bridge configuration at all"], "produces a smoother output with less ripple, using both halves of the AC cycle",
      "By utilising both halves of the AC waveform, full-wave rectification produces a smoother, more consistent output with reduced ripple compared to half-wave rectification."),
  _q("An important precaution when installing an electrolytic capacitor in a circuit is to",
      ["observe the correct polarity, as reversing it can cause the capacitor to fail or explode", "ignore polarity markings entirely, since they never matter", "always connect it in reverse to the marked polarity", "avoid using it in any DC circuit"], "observe the correct polarity, as reversing it can cause the capacitor to fail or explode",
      "Electrolytic capacitors are polarised and can fail dramatically (including venting or exploding) if connected with reversed polarity."),
  _q("In a transistor amplifier, the emitter, base, and collector terminals are analogous in function to which parts of a water tap system controlling flow?",
      ["the base acts like a small control valve, while the collector-emitter path carries the larger controlled flow", "all three terminals perform an identical function with no distinction", "only the collector terminal has any functional role", "only the emitter terminal has any functional role"], "the base acts like a small control valve, while the collector-emitter path carries the larger controlled flow",
      "A helpful analogy: a small current at the base terminal controls a much larger current flowing through the collector-emitter path, similar to a valve controlling a larger flow."),
  _q("A key parameter to consider when selecting a rectifier diode for a power supply is its",
      ["maximum reverse voltage rating and maximum forward current rating", "colour and physical size only", "operating frequency in radio circuits only", "logic gate compatibility"], "maximum reverse voltage rating and maximum forward current rating",
      "Rectifier diode selection depends on ensuring the diode's maximum reverse voltage and forward current ratings safely exceed the circuit's actual operating conditions."),
  _q("Reverse breakdown in an ordinary (non-Zener) diode, if it occurs, generally",
      ["risks permanently damaging the diode, unlike the controlled breakdown of a Zener diode", "is a normal, safe, and desired mode of operation", "has no effect on the diode's performance", "only occurs when the diode is forward biased"], "risks permanently damaging the diode, unlike the controlled breakdown of a Zener diode",
      "Unlike Zener diodes, which are specifically designed to safely operate in reverse breakdown, ordinary diodes can be permanently damaged if driven into reverse breakdown."),
  _q("LEDs require a current-limiting resistor in most circuits mainly to",
      ["prevent excessive current from damaging the LED", "increase the LED's brightness far beyond its rated maximum", "reverse the polarity of the LED automatically", "convert AC current into DC current"], "prevent excessive current from damaging the LED",
      "A current-limiting resistor protects an LED from drawing excessive current, which could otherwise quickly damage or destroy it."),
];

final _communicationDigitalLogicAndTools = [
  _q("A single-stage transistor amplifier using the Common Emitter configuration is widely used mainly because it provides",
      ["both current and voltage gain, making it suitable for general-purpose amplification", "voltage gain only, with no current gain", "current gain only, with no voltage gain", "no gain of any kind, used purely for buffering"], "both current and voltage gain, making it suitable for general-purpose amplification",
      "The Common Emitter amplifier configuration is popular because it provides significant gain in both current and voltage, unlike the other two configurations."),
  _q("In a transistor amplifier circuit, the network of resistors used to establish the correct DC operating point before an AC signal is applied is called the",
      ["biasing network", "coupling network", "bypass network", "filter network"], "biasing network",
      "A biasing network sets up the correct DC voltages and currents needed for the transistor to operate correctly in its active region before amplifying an AC signal."),
  _q("A capacitor used to connect the AC signal between amplifier stages while blocking DC voltage from passing through is called a",
      ["coupling capacitor", "bypass capacitor", "filter capacitor only", "tuning capacitor only"], "coupling capacitor",
      "A coupling capacitor allows AC signals to pass between stages while blocking the DC bias voltages of each stage from interfering with one another."),
  _q("A capacitor placed across an emitter resistor to prevent AC signal loss (gain reduction) due to that resistor is called a",
      ["bypass capacitor", "coupling capacitor", "filter capacitor only", "tuning capacitor only"], "bypass capacitor",
      "A bypass capacitor provides a low-impedance AC path around the emitter resistor, preventing it from reducing the amplifier's overall AC gain."),
  _q("A curve showing how an amplifier's gain varies across different signal frequencies is called its",
      ["frequency response curve", "biasing curve", "characteristic curve of a diode", "truth table"], "frequency response curve",
      "The frequency response curve illustrates how an amplifier's gain changes as the input signal frequency varies, important for assessing its suitability for different applications."),
  _q("A circuit that generates a continuous, repetitive waveform, such as a sine wave, without an external AC input signal, is called an",
      ["oscillator", "amplifier only", "rectifier only", "filter only"], "oscillator",
      "An oscillator generates its own repetitive output waveform, using feedback and amplification, without requiring an external AC input signal."),
  _q("The condition that must be satisfied for a circuit to sustain continuous oscillation, involving the loop gain and phase shift, is called the",
      ["Barkhausen criterion", "Kirchhoff's Law", "Ohm's Law", "Faraday's Law"], "Barkhausen criterion",
      "The Barkhausen criterion states that sustained oscillation requires a loop gain of at least one and a total phase shift of zero (or a multiple of 360 degrees) around the feedback loop."),
  _q("An oscillator circuit that uses an inductor and capacitor together to determine its oscillation frequency is called an",
      ["LC (resonant tank) oscillator", "RC oscillator only", "crystal oscillator only", "digital oscillator only"], "LC (resonant tank) oscillator",
      "LC oscillators use the resonant properties of an inductor-capacitor combination (tank circuit) to establish and maintain their oscillation frequency."),
  _q("The number system that uses ten digits (0 through 9) is called the",
      ["decimal system", "binary system", "hexadecimal system", "octal system"], "decimal system",
      "The decimal system, used in everyday counting, is based on ten digits (0-9)."),
  _q("The number system that uses only two digits (0 and 1), forming the fundamental basis of digital electronics, is called the",
      ["binary system", "decimal system", "hexadecimal system", "octal system"], "binary system",
      "The binary system uses only two digits (0 and 1), directly corresponding to the on/off states used within digital electronic circuits."),
  _q("The number system that uses sixteen symbols (0-9 and A-F), often used as a compact way to represent binary values, is called the",
      ["hexadecimal system", "decimal system", "binary system", "octal system"], "hexadecimal system",
      "The hexadecimal system uses sixteen symbols, providing a more compact representation of binary data commonly used in computing and digital electronics."),
  _q("The branch of mathematics dealing with logical operations on true/false (binary) values, foundational to digital logic design, is called",
      ["Boolean algebra", "calculus", "trigonometry", "vector algebra"], "Boolean algebra",
      "Boolean algebra provides the mathematical framework for describing and simplifying logical operations, forming the basis of digital logic circuit design."),
  _q("A logic gate that produces a true (1) output only when all of its inputs are true (1) is called an",
      ["AND gate", "OR gate", "NOT gate", "NAND gate"], "AND gate",
      "An AND gate outputs true only when every one of its inputs is true; otherwise its output is false."),
  _q("A logic gate that produces a true (1) output when at least one of its inputs is true (1) is called an",
      ["OR gate", "AND gate", "NOT gate", "NOR gate"], "OR gate",
      "An OR gate outputs true if at least one of its inputs is true, and false only when all inputs are false."),
  _q("A logic gate with a single input that inverts (reverses) the logical state of that input is called a",
      ["NOT gate (inverter)", "AND gate", "OR gate", "XOR gate"], "NOT gate (inverter)",
      "A NOT gate (inverter) simply reverses its single input: a true input produces a false output, and vice versa."),
  _q("A logic gate that produces the inverse output of an AND gate, being false only when all inputs are true, is called a",
      ["NAND gate", "NOR gate", "AND gate", "XOR gate"], "NAND gate",
      "A NAND gate is the logical inverse of an AND gate, producing a false output only when all its inputs are true."),
  _q("A logic gate that produces the inverse output of an OR gate, being true only when all inputs are false, is called a",
      ["NOR gate", "NAND gate", "OR gate", "XNOR gate"], "NOR gate",
      "A NOR gate is the logical inverse of an OR gate, producing a true output only when every input is false."),
  _q("A logic gate that produces a true output only when its inputs are different from each other is called an",
      ["XOR (exclusive OR) gate", "XNOR gate", "AND gate", "OR gate"], "XOR (exclusive OR) gate",
      "An XOR gate outputs true only when its inputs differ (one true, one false), and false when the inputs are the same."),
  _q("A logic gate that produces a true output only when its inputs are the same as each other is called an",
      ["XNOR gate", "XOR gate", "NAND gate", "NOR gate"], "XNOR gate",
      "An XNOR gate is the inverse of an XOR gate, outputting true when its inputs match (both true or both false)."),
  _q("An instrument used to visually display and monitor how a voltage waveform changes over time is called a",
      ["Cathode Ray Oscilloscope (CRO)", "multimeter only", "wattmeter only", "signal generator only"], "Cathode Ray Oscilloscope (CRO)",
      "A CRO displays voltage waveforms visually on a screen, allowing engineers and technicians to observe how a signal changes over time."),
  _q("A chemical substance applied during soldering to clean the metal surfaces and improve the flow and adhesion of solder is called",
      ["flux", "solder wire alone", "PCB substrate", "desoldering braid"], "flux",
      "Flux cleans oxidation from metal surfaces and improves the wetting and flow of solder, producing a stronger, more reliable joint."),
  _q("A tool used to remove excess solder from a joint, often to correct mistakes or replace a faulty component, is called a",
      ["desoldering pump (solder sucker)", "soldering iron alone", "flux applicator", "wire stripper only"], "desoldering pump (solder sucker)",
      "A desoldering pump quickly draws away melted solder from a joint, allowing components to be removed or corrections made."),
  _q("A flat board with conductive copper tracks, used to mechanically support and electrically connect electronic components, is called a",
      ["printed circuit board (PCB)", "breadboard only", "heat sink", "capacitor bank"], "printed circuit board (PCB)",
      "A PCB provides both mechanical support and electrical connections for components, using etched copper tracks instead of loose wiring."),
  _q("A systematic process of identifying and resolving faults on an electronic circuit board is generally called",
      ["troubleshooting", "doping", "biasing", "rectification"], "troubleshooting",
      "Troubleshooting involves methodically testing and inspecting a circuit board to identify and correct faults preventing correct operation."),
  _q("The decimal number 5 is represented in binary as",
      ["101", "110", "100", "111"], "101",
      "Decimal 5 equals binary 101, since 1x4 + 0x2 + 1x1 = 5."),
  _q("The decimal number 10 is represented in binary as",
      ["1010", "1001", "1100", "1000"], "1010",
      "Decimal 10 equals binary 1010, since 1x8 + 0x4 + 1x2 + 0x1 = 10."),
  _q("A table listing all possible input combinations of a logic circuit alongside their corresponding outputs is called a",
      ["truth table", "frequency response curve", "characteristic curve", "biasing table"], "truth table",
      "A truth table systematically lists every possible input combination for a logic circuit and the resulting output for each, essential for digital logic design."),
  _q("The Boolean expression for an AND gate with inputs A and B is typically written as",
      ["A . B (A AND B)", "A + B (A OR B)", "A' (NOT A)", "A XOR B"], "A . B (A AND B)",
      "The AND operation is conventionally represented using a dot (or simple juxtaposition) between the input variables, such as A.B."),
  _q("The Boolean expression for an OR gate with inputs A and B is typically written as",
      ["A + B (A OR B)", "A . B (A AND B)", "A' (NOT A)", "A XOR B"], "A + B (A OR B)",
      "The OR operation is conventionally represented using a plus sign between the input variables, such as A+B."),
  _q("The main function of a CRO's time base control is to",
      ["adjust the horizontal sweep speed, controlling how the waveform is displayed over time", "adjust only the vertical amplitude of the displayed waveform", "change the frequency of the signal being measured", "convert AC signals into DC signals"], "adjust the horizontal sweep speed, controlling how the waveform is displayed over time",
      "The time base control adjusts how quickly the CRO's electron beam sweeps horizontally, determining how the waveform is stretched or compressed over time on the display."),
  _q("Before soldering a joint, it is generally recommended to first ensure that the surfaces to be joined are",
      ["clean and free from dirt, oxidation, or grease", "already coated with a thick layer of old solder", "left wet with water", "coated in a non-conductive varnish"], "clean and free from dirt, oxidation, or grease",
      "Clean surfaces, free from dirt, oxidation, or grease, are essential for solder to properly wet and bond to the metal, forming a reliable joint."),
  _q("A cold solder joint, resulting from insufficient heat during soldering, typically appears",
      ["dull, grainy, and may be mechanically or electrically unreliable", "shiny, smooth, and perfectly reliable", "identical in every way to a properly soldered joint", "only a cosmetic issue with no effect on reliability"], "dull, grainy, and may be mechanically or electrically unreliable",
      "A cold solder joint, caused by insufficient heating, typically looks dull and grainy rather than shiny and smooth, and can be mechanically weak or electrically intermittent."),
];
