import "../quiz_question.dart";

const _subject = "Government";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// WAEC Government question bank covering the full syllabus: Elements of
/// Government, Structures & Process of Government, Political Systems &
/// Governance, Pre-Colonial & Colonial Political Systems (West Africa), and
/// Post-Independence Constitutional Development & Foreign Policy.
List<QuizQuestion> buildWaecGovernmentQuestions() {
  return [
    ..._elementsOfGovernment,
    ..._structuresAndProcessOfGovernment,
    ..._politicalSystemsAndGovernance,
    ..._preColonialAndColonialPoliticalSystems,
    ..._postIndependenceConstitutionalDevelopmentAndForeignPolicy,
  ];
}

final _elementsOfGovernment = [
  _q("Government can be best defined as",
      ["the machinery or agency through which the will of the state is formulated, expressed, and realised", "a group of people living together in a defined territory", "an association formed purely for economic gain", "a body responsible only for collecting taxes"], "the machinery or agency through which the will of the state is formulated, expressed, and realised",
      "Government is the institution through which the state exercises authority, makes laws, and carries out its policies."),
  _q("The ability to influence or control the behaviour of others, with or without their consent, is called",
      ["power", "authority", "legitimacy", "sovereignty"], "power",
      "Power is the raw capacity to make others act in a certain way, which may or may not be recognised as rightful."),
  _q("The right or recognised power to command, enforce laws, and exact obedience is called",
      ["authority", "power", "anarchy", "society"], "authority",
      "Authority is power that is recognised as legitimate, typically backed by law, tradition, or consent of the governed."),
  _q("The acceptance by the people that a government's exercise of power is right and proper is called",
      ["legitimacy", "sovereignty", "power", "nationalism"], "legitimacy",
      "Legitimacy refers to the popular acceptance of a government's authority as rightful, whether based on law, tradition, or consent."),
  _q("The supreme, final, and unlimited power of a state to make and enforce laws within its territory, free from external control, is called",
      ["sovereignty", "authority", "legitimacy", "power"], "sovereignty",
      "Sovereignty is the highest authority a state possesses, both internally over its citizens and externally in relation to other states."),
  _q("The aspect of sovereignty concerned with a state's supreme authority over all persons and groups within its territory is called",
      ["internal sovereignty", "external sovereignty", "popular sovereignty", "legal sovereignty"], "internal sovereignty",
      "Internal sovereignty means the state has the highest authority over all individuals, groups, and institutions within its own borders."),
  _q("The aspect of sovereignty concerned with a state's independence and freedom from control by other states is called",
      ["external sovereignty", "internal sovereignty", "popular sovereignty", "legal sovereignty"], "external sovereignty",
      "External sovereignty refers to a state's recognition as independent and free from the political control of any other state."),
  _q("A politically organised community, permanently occupying a defined territory, with an independent government, is called a",
      ["state", "nation", "society", "tribe"], "state",
      "A state is a legal and political entity with a defined territory, population, government, and sovereignty."),
  _q("A group of people sharing common history, culture, language, or ancestry, and a sense of unity, regardless of political boundaries, is called a",
      ["nation", "state", "society", "government"], "nation",
      "A nation is defined by shared cultural or historical identity, which may or may not correspond to the boundaries of a single state."),
  _q("A broad group of people living together, interacting, and sharing a common way of life is called a",
      ["society", "state", "nation", "government"], "society",
      "Society refers generally to people living together in an organised community, sharing customs and institutions."),
  _q("Which of the following is a basic characteristic of government?",
      ["It possesses the authority to make and enforce binding laws", "It exists only in democratic states", "It is always formed by a single political party", "It cannot levy taxes on citizens"], "It possesses the authority to make and enforce binding laws",
      "A defining feature of government, in any political system, is its authority to make, interpret, and enforce laws binding on the population."),
  _q("An economic and political ideology advocating that the means of production should be owned and controlled by the state for the benefit of all is called",
      ["socialism", "capitalism", "feudalism", "communalism"], "socialism",
      "Socialism holds that resources and production should be collectively or state-owned to reduce inequality and serve the common good."),
  _q("An economic system based on private ownership of the means of production, free markets, and the pursuit of individual profit is called",
      ["capitalism", "socialism", "communism", "feudalism"], "capitalism",
      "Capitalism emphasises private property, free enterprise, and market competition, with minimal state control of the economy."),
  _q("An extreme, authoritarian, ultra-nationalist ideology emphasising the supremacy of the state and often a single dictatorial leader is called",
      ["fascism", "communism", "socialism", "welfarism"], "fascism",
      "Fascism is a far-right, authoritarian ideology marked by dictatorial power, extreme nationalism, and suppression of opposition."),
  _q("An ideology advocating a classless society in which all property is communally owned and wealth is distributed according to need is called",
      ["communism", "capitalism", "fascism", "feudalism"], "communism",
      "Communism aims for a classless, stateless society where the means of production are owned in common and goods are shared according to need."),
  _q("A traditional African social and economic system based on collective ownership of land and resources by the community is called",
      ["communalism", "feudalism", "capitalism", "fascism"], "communalism",
      "Communalism reflects the traditional African practice where land and key resources belong to the community as a whole, not individuals."),
  _q("A social and economic system, historically found in medieval Europe, based on land tenure in exchange for service or loyalty to a lord is called",
      ["feudalism", "communalism", "capitalism", "socialism"], "feudalism",
      "Feudalism structured society around lords granting land (fiefs) to vassals in return for military or other service, with peasants working the land."),
  _q("A state that combines a market economy with extensive government provision of social services such as healthcare, education, and social security is called a",
      ["welfare state", "police state", "unitary state", "confederal state"], "welfare state",
      "A welfare state ensures citizens' basic well-being through government-funded social programmes, alongside a market-based economy."),
  _q("Rights considered basic and inherent to every human being, such as the right to life, liberty, and freedom of expression, are called",
      ["fundamental human rights", "civic rights only", "property rights only", "political party rights"], "fundamental human rights",
      "Fundamental human rights are entitlements assumed to belong to every person by virtue of being human, often guaranteed in a constitution."),
  _q("The principle that no one, including the government, is above the law, and that all citizens are equal before the law, is called the",
      ["rule of law", "separation of powers", "federalism", "checks and balances"], "rule of law",
      "The rule of law ensures that laws apply equally to everyone, government actions are bound by law, and no one is above legal accountability."),
];

final _structuresAndProcessOfGovernment = [
  _q("The organ of government responsible for making laws is the",
      ["legislature", "executive", "judiciary", "civil service"], "legislature",
      "The legislature (e.g., parliament or national assembly) is primarily responsible for debating and enacting laws."),
  _q("A legislature made up of only one chamber or house is called",
      ["unicameral", "bicameral", "tricameral", "presidential"], "unicameral",
      "A unicameral legislature has a single legislative chamber, unlike a bicameral legislature which has two."),
  _q("A legislature made up of two separate chambers or houses, such as a senate and a house of representatives, is called",
      ["bicameral", "unicameral", "tricameral", "parliamentary"], "bicameral",
      "A bicameral legislature divides law-making power between two chambers, often to allow for more deliberation and representation."),
  _q("The organ of government responsible for implementing and enforcing laws is the",
      ["executive", "legislature", "judiciary", "electorate"], "executive",
      "The executive carries out the day-to-day administration of government and enforces laws passed by the legislature."),
  _q("Elected officials, such as the president and ministers, who form the political leadership of the executive, are collectively called the",
      ["political executive", "permanent (civil service) executive", "judiciary", "legislature"], "political executive",
      "The political executive consists of elected or appointed officeholders who set policy direction, distinct from career civil servants."),
  _q("Career officials who serve the government on a permanent, non-partisan basis regardless of which party is in power form the",
      ["permanent executive (civil service)", "political executive", "judiciary", "legislature"], "permanent executive (civil service)",
      "The permanent executive (civil service) provides continuity and administrative expertise, serving successive governments impartially."),
  _q("The organ of government responsible for interpreting laws and administering justice is the",
      ["judiciary", "executive", "legislature", "electorate"], "judiciary",
      "The judiciary interprets and applies the law, resolving disputes and ensuring justice is administered fairly."),
  _q("The power of the courts to examine and invalidate laws or executive actions that conflict with the constitution is called",
      ["judicial review", "judicial independence", "rule of law", "separation of powers"], "judicial review",
      "Judicial review allows courts to strike down legislation or government actions found to be unconstitutional."),
  _q("The principle that the judiciary should be free from interference by the executive or legislature in performing its duties is called",
      ["judicial independence", "judicial review", "rule of law", "separation of powers"], "judicial independence",
      "Judicial independence protects judges from political pressure, ensuring impartial administration of justice."),
  _q("The theory that the three organs of government (legislature, executive, and judiciary) should be distinct and exercise separate functions is called the doctrine of",
      ["separation of powers", "checks and balances", "rule of law", "federalism"], "separation of powers",
      "The separation of powers theory, associated with Montesquieu, argues that dividing government functions among three organs prevents the concentration and abuse of power."),
  _q("The philosopher most closely associated with developing the theory of separation of powers is",
      ["Montesquieu", "John Locke", "Thomas Hobbes", "Jean-Jacques Rousseau"], "Montesquieu",
      "Montesquieu, in his work 'The Spirit of the Laws', systematically developed the theory advocating separate legislative, executive, and judicial powers."),
  _q("The system of mutual restraints in which each organ of government can limit the powers of the others is called",
      ["checks and balances", "separation of powers", "rule of law", "sovereignty"], "checks and balances",
      "Checks and balances allow each arm of government to monitor and restrain the actions of the others, preventing abuse of power."),
  _q("Under a presidential system of government, the separation of powers is generally applied",
      ["strictly, with the executive and legislature elected separately and independently", "loosely, with the executive drawn entirely from the legislature", "not at all, since one person controls all three organs", "only to the judiciary and not the other organs"], "strictly, with the executive and legislature elected separately and independently",
      "In a presidential system, the executive (president) is elected separately from the legislature, reflecting a stricter separation of powers."),
  _q("Under a parliamentary system of government, executive power is generally",
      ["fused with the legislature, as the executive is drawn from and answerable to parliament", "completely separate from the legislature", "held by an unelected hereditary monarch alone", "shared equally among three independent branches"], "fused with the legislature, as the executive is drawn from and answerable to parliament",
      "In a parliamentary system, the prime minister and cabinet are typically drawn from the legislature and remain accountable to it, reflecting a fusion of powers."),
  _q("A constitution that is contained in a single formal document, deliberately drafted and adopted, is called a",
      ["written constitution", "unwritten constitution", "flexible constitution", "monarchical constitution"], "written constitution",
      "A written constitution is codified in one authoritative document, such as most modern national constitutions."),
  _q("A constitution based mainly on customs, conventions, judicial decisions, and various historical documents, rather than a single formal text, is called an",
      ["unwritten constitution", "written constitution", "rigid constitution", "republican constitution"], "unwritten constitution",
      "An unwritten constitution, such as that of the United Kingdom, derives from a combination of statutes, common law, and long-standing conventions."),
  _q("A constitution that can be easily amended through the ordinary law-making process is called a",
      ["flexible constitution", "rigid constitution", "written constitution", "monarchical constitution"], "flexible constitution",
      "A flexible constitution can be changed by the same simple procedure used for passing ordinary legislation."),
  _q("A constitution that can only be amended through a special, more difficult procedure than ordinary law-making is called a",
      ["rigid constitution", "flexible constitution", "unwritten constitution", "republican constitution"], "rigid constitution",
      "A rigid constitution requires special procedures, such as a supermajority vote or referendum, to be amended, making changes more difficult."),
  _q("A constitution under which the head of state is a hereditary monarch is called a",
      ["monarchical constitution", "republican constitution", "federal constitution", "unitary constitution"], "monarchical constitution",
      "A monarchical constitution establishes a hereditary ruler (king, queen, or emir) as the head of state, whether ceremonial or with real power."),
  _q("A constitution under which the head of state is an elected person rather than a hereditary monarch is called a",
      ["republican constitution", "monarchical constitution", "federal constitution", "unitary constitution"], "republican constitution",
      "A republican constitution establishes that the head of state derives their position through election rather than heredity."),
  _q("The process by which a bill passed by the legislature is formally signed and given legal effect by the head of state is called",
      ["assent (royal assent/presidential assent)", "first reading", "committee stage", "prorogation"], "assent (royal assent/presidential assent)",
      "Assent is the final formal approval by the head of state that turns a passed bill into a law."),
  _q("The stage of the legislative process in which a bill is formally introduced and its title read out, without debate, is called the",
      ["first reading", "second reading", "committee stage", "third reading"], "first reading",
      "The first reading is a purely formal introduction of a bill, with no debate on its content at that stage."),
  _q("The stage of the legislative process in which the general principles of a bill are debated is called the",
      ["second reading", "first reading", "committee stage", "report stage"], "second reading",
      "The second reading is when members debate the overall merits and principles of a bill before it moves to detailed scrutiny."),
  _q("The stage of the legislative process in which a bill is examined clause by clause, often by a smaller group of legislators, is called the",
      ["committee stage", "first reading", "second reading", "third reading"], "committee stage",
      "At the committee stage, a bill is scrutinised in detail, clause by clause, and amendments may be proposed."),
  _q("The final stage of the legislative process in a chamber, where the bill (as amended) is voted on in its complete form, is called the",
      ["third reading", "first reading", "committee stage", "royal assent"], "third reading",
      "The third reading is the final vote on the bill as a whole, after all amendments from earlier stages have been incorporated."),
];

final _politicalSystemsAndGovernance = [
  _q("A system of government in which all governmental powers are concentrated in a single, central authority is called a",
      ["unitary system", "federal system", "confederal system", "presidential system"], "unitary system",
      "In a unitary system, the central government holds supreme authority, and any local governments exist only by its delegation."),
  _q("A system of government in which powers are constitutionally divided between a central authority and constituent regional units (such as states or provinces) is called a",
      ["federal system", "unitary system", "confederal system", "parliamentary system"], "federal system",
      "In a federal system, both the central and regional (state/provincial) governments have constitutionally guaranteed powers over their own areas of jurisdiction."),
  _q("A loose association of independent, sovereign states that agree to cooperate on limited matters while retaining their individual sovereignty is called a",
      ["confederal system (confederation)", "federal system", "unitary system", "republican system"], "confederal system (confederation)",
      "A confederation is a weaker union than a federation, in which member states remain sovereign and can typically withdraw from the arrangement."),
  _q("One advantage of a federal system of government is that it",
      ["allows regions with diverse interests to manage their own local affairs while remaining united", "eliminates the need for a written constitution", "concentrates all power in one central authority", "makes constitutional amendment very easy"], "allows regions with diverse interests to manage their own local affairs while remaining united",
      "Federalism accommodates diversity by letting constituent units handle local matters, while a central government manages issues of common concern."),
  _q("One disadvantage of a federal system of government is that it",
      ["can be expensive to run, due to the duplication of government institutions at different levels", "always leads to a single, all-powerful central government", "makes it impossible for regions to have their own laws", "eliminates the need for a legislature altogether"], "can be expensive to run, due to the duplication of government institutions at different levels",
      "Maintaining separate governmental structures at the federal and state/regional levels can be costly and lead to duplication of effort."),
  _q("A form of government in which the head of state and head of government are combined in one person, elected separately from the legislature, is the",
      ["presidential system", "parliamentary system", "confederal system", "monarchical system"], "presidential system",
      "In a presidential system, the president serves as both head of state and head of government, and is elected independently of the legislature."),
  _q("A form of government in which the head of government (usually a prime minister) is drawn from and remains accountable to the legislature is the",
      ["parliamentary system", "presidential system", "unitary system", "federal system"], "parliamentary system",
      "A parliamentary system fuses executive and legislative power, with the prime minister and cabinet accountable to parliament, which can remove them via a vote of no confidence."),
  _q("A form of government in which absolute power is held by a single ruler or small group, without free elections or constitutional limits, is called a",
      ["dictatorship", "democracy", "federation", "confederation"], "dictatorship",
      "A dictatorship concentrates unchecked power in a single ruler or small clique, typically suppressing political opposition and civil liberties."),
  _q("A government that comes to power and rules through the armed forces, often after overthrowing a civilian government, is called a",
      ["military government", "civilian government", "parliamentary government", "confederal government"], "military government",
      "Military rule occurs when armed forces personnel seize and exercise governmental power, typically suspending the constitution."),
  _q("An organised group of people who share similar political views and seek to win elections and control government is called a",
      ["political party", "pressure group", "electorate", "civil service"], "political party",
      "Political parties organise around shared ideologies or interests, contesting elections to gain and exercise governmental power."),
  _q("A political party system in which only one party is legally allowed to exist and contest elections is called a",
      ["one-party system", "two-party system", "multi-party system", "no-party system"], "one-party system",
      "In a one-party system, a single party monopolises political power and no legal opposition parties are permitted."),
  _q("A political party system in which two major parties dominate politics and realistically compete for power, as seen in the United States, is called a",
      ["two-party system", "one-party system", "multi-party system", "no-party system"], "two-party system",
      "A two-party system features two dominant parties that alternate in and out of government, though minor parties may also exist."),
  _q("A political party system in which several parties compete for power, often resulting in coalition governments, is called a",
      ["multi-party system", "one-party system", "two-party system", "no-party system"], "multi-party system",
      "A multi-party system allows numerous parties to contest elections and gain representation, often requiring coalitions to form a government."),
  _q("The legal right of a citizen to vote in public elections is called",
      ["franchise (suffrage)", "sovereignty", "legitimacy", "citizenship"], "franchise (suffrage)",
      "Franchise, also called suffrage, is the constitutionally granted right to participate in elections by voting."),
  _q("An electoral system in which the candidate with the most votes in a constituency wins, even without an absolute majority, is called",
      ["plurality (first-past-the-post) system", "proportional representation", "the electoral college system", "indirect election"], "plurality (first-past-the-post) system",
      "First-past-the-post declares the candidate with the highest number of votes the winner, regardless of whether they secured over 50% of votes cast."),
  _q("An electoral system in which seats in the legislature are allocated to parties in proportion to the total votes each party receives is called",
      ["proportional representation", "first-past-the-post", "indirect election", "plurality system"], "proportional representation",
      "Proportional representation aims to match a party's share of legislative seats closely to its overall share of the popular vote."),
  _q("A body established to independently organise, conduct, and supervise elections, free from control by the ruling party, is called an",
      ["independent electoral commission", "political party", "civil service commission", "public corporation"], "independent electoral commission",
      "An independent electoral commission (such as INEC in Nigeria) is designed to conduct elections impartially, without interference from the party in power."),
  _q("A body of permanent, professional, non-political officials who assist the government in implementing policies and administering the state is called the",
      ["civil service", "political party", "electorate", "judiciary"], "civil service",
      "The civil service consists of career officials who serve the government of the day impartially, providing administrative continuity."),
  _q("A key characteristic of the civil service is that its members are expected to be",
      ["politically neutral and impartial in carrying out their duties", "elected directly by the people", "members of the ruling political party only", "responsible for making laws"], "politically neutral and impartial in carrying out their duties",
      "Civil servants are expected to serve any government in power impartially, without favouring a particular political party."),
  _q("Autonomous bodies set up by government to manage specific commercial or public services, such as electricity or water supply, are called",
      ["public corporations", "political parties", "civil service departments", "pressure groups"], "public corporations",
      "Public corporations are established to run specific essential services on behalf of the state, often on a semi-commercial basis."),
  _q("One reason governments establish public corporations is to",
      ["provide essential services that may not be profitable enough to attract private investment", "guarantee maximum profit for private shareholders", "eliminate the need for taxation entirely", "replace the legislature in law-making"], "provide essential services that may not be profitable enough to attract private investment",
      "Public corporations often run essential services (like utilities) that require heavy investment or serve the public interest, which private firms may be unwilling to provide."),
  _q("The level of government closest to the people, responsible for local matters such as markets, primary healthcare, and refuse disposal, is called",
      ["local government", "central government", "regional government", "state government"], "local government",
      "Local government administers grassroots affairs and services directly relevant to the immediate community."),
  _q("One major source of finance for local governments is",
      ["statutory allocations from the central or state government", "foreign direct investment only", "profits from international trade only", "loans from foreign governments only"], "statutory allocations from the central or state government",
      "Local governments commonly rely on allocations from higher tiers of government, in addition to internally generated revenue such as local rates and levies."),
  _q("A major problem often affecting the autonomy of local governments is",
      ["excessive control and interference by state or central governments", "too much independent revenue with no oversight", "an absence of any central government structure", "the complete lack of any local government elections"], "excessive control and interference by state or central governments",
      "Local government autonomy is often undermined when higher levels of government exert excessive financial or administrative control over local affairs."),
  _q("A group that seeks to influence government policy in its favour without itself seeking to win elections or hold governmental power is called a",
      ["pressure group (interest group)", "political party", "electoral commission", "public corporation"], "pressure group (interest group)",
      "Unlike political parties, pressure groups aim to influence policy on specific issues but do not contest elections to govern directly."),
];

final _preColonialAndColonialPoliticalSystems = [
  _q("The centralised Hausa-Fulani political system, headed by an Emir with defined administrative structures, is generally described as the",
      ["Emirate system", "Alafin system", "segmentary (acephalous) system", "confederal system"], "Emirate system",
      "The Hausa-Fulani Emirate system was a highly centralised traditional government headed by an Emir, supported by a hierarchy of officials."),
  _q("In the traditional Hausa-Fulani Emirate system, supreme political and religious authority within an emirate rested with the",
      ["Emir", "Sarkin Fada", "Waziri", "Madawaki"], "Emir",
      "The Emir was the paramount ruler of an emirate, combining political leadership with significant religious authority under Islamic law."),
  _q("The traditional Yoruba political system, headed by the Alaafin of Oyo and supported by the Oyo Mesi council, is best described as a",
      ["constitutional monarchy", "purely acephalous system", "military dictatorship", "confederal republic"], "constitutional monarchy",
      "The Alaafin's power was checked by the Oyo Mesi (a council of chiefs), making the traditional Yoruba system a form of constitutional monarchy rather than absolute rule."),
  _q("In traditional Oyo Yoruba government, the council of chiefs that could check the Alaafin's power and, in extreme cases, compel him to abdicate was known as the",
      ["Oyo Mesi", "Ogboni cult", "Emirate council", "Warrant Chief system"], "Oyo Mesi",
      "The Oyo Mesi was a powerful council of kingmakers and chiefs that acted as a check on the Alaafin's authority, including the power to demand his abdication."),
  _q("The traditional Igbo political system, generally lacking centralised kingship and instead based on village autonomy, is best described as",
      ["segmentary (acephalous/decentralised)", "an absolute monarchy", "an Emirate system", "a colonial creation"], "segmentary (acephalous/decentralised)",
      "Most traditional Igbo communities were organised as autonomous villages or groups of villages without an overarching centralised king, hence 'acephalous' (headless)."),
  _q("In the traditional Igbo political system, decisions were typically made through",
      ["a general assembly of adult males, councils of elders, and age-grades", "a single hereditary king with absolute power", "an appointed colonial district officer", "a written constitution drafted by chiefs"], "a general assembly of adult males, councils of elders, and age-grades",
      "Governance among the Igbo was largely democratic and decentralised, relying on assemblies, elders, age-grades, and title societies rather than a single ruler."),
  _q("The British system of colonial administration that governed African colonies through existing traditional rulers and institutions is called",
      ["Indirect Rule", "Direct Rule", "Assimilation", "Association"], "Indirect Rule",
      "Under Indirect Rule, the British used traditional chiefs and institutions as agents of colonial administration, rather than replacing them entirely."),
  _q("Indirect Rule was introduced by the British partly because it was",
      ["cheaper and required fewer British administrative personnel", "more expensive than direct colonial administration", "designed to abolish all traditional institutions immediately", "only applicable in areas without traditional rulers"], "cheaper and required fewer British administrative personnel",
      "Indirect Rule reduced the cost and manpower needs of colonial administration by relying on existing local rulers to enforce British policies."),
  _q("Indirect Rule was applied most successfully in Northern Nigeria mainly because",
      ["the existing centralised Emirate system provided a ready-made structure of traditional authority", "there were no traditional rulers in the North at all", "the region had no history of centralised government", "the British preferred direct rule everywhere in Nigeria"], "the existing centralised Emirate system provided a ready-made structure of traditional authority",
      "The centralised Hausa-Fulani Emirate system offered a hierarchy of rulers the British could work through, making Indirect Rule easier to apply there."),
  _q("A major difficulty in applying Indirect Rule among the Igbo was that",
      ["their acephalous system lacked a centralised chief through whom the British could rule", "the Igbo had a strongly centralised monarchy similar to Oyo", "the British had no interest in administering Igbo areas", "Igbo communities had no council of elders at all"], "their acephalous system lacked a centralised chief through whom the British could rule",
      "Since Igbo communities lacked centralised kingship, the British controversially imposed artificial 'Warrant Chiefs', which caused resentment and unrest."),
  _q("The French colonial policy that aimed to turn Africans into French citizens by adopting French culture, language, and values is called",
      ["Assimilation", "Association", "Indirect Rule", "Trusteeship"], "Assimilation",
      "Assimilation aimed to culturally transform Africans into French citizens, granting full French rights to those who adopted French civilisation."),
  _q("The later French colonial policy that recognised African differences and cooperated with local institutions while still maintaining French control is called",
      ["Association", "Assimilation", "Indirect Rule", "Direct Rule"], "Association",
      "Association replaced Assimilation as French policy, acknowledging African cultural distinctiveness while retaining ultimate French authority."),
  _q("A key difference between British and French colonial administration was that the British generally practised",
      ["Indirect Rule through existing chiefs, while the French practised more centralised, direct administration", "direct rule everywhere, while the French relied entirely on traditional chiefs", "no administration at all, while the French built full colonial governments", "federalism, while the French practised confederation"], "Indirect Rule through existing chiefs, while the French practised more centralised, direct administration",
      "British colonial policy favoured governing through traditional rulers, whereas French colonial policy was more centralised and directly administered from Paris."),
  _q("A major factor that fuelled the rise of nationalism in colonial West Africa was",
      ["the discriminatory treatment of educated Africans by colonial administrations", "the complete absence of colonial taxation", "the total lack of Western education in the colonies", "the immediate grant of independence upon colonisation"], "the discriminatory treatment of educated Africans by colonial administrations",
      "Educated Africans who faced racial discrimination and exclusion from top positions became key drivers of nationalist agitation for self-rule."),
  _q("Which of the following was a common method used by early West African nationalists to press for independence?",
      ["Formation of political parties, newspapers, and constitutional agitation", "Immediate armed rebellion in every colony without exception", "Total boycott of all Western education", "Refusal to engage with colonial authorities in any way"], "Formation of political parties, newspapers, and constitutional agitation",
      "Nationalists commonly organised political parties, used the press to mobilise opinion, and pursued constitutional means to demand self-government."),
];

final _postIndependenceConstitutionalDevelopmentAndForeignPolicy = [
  _q("The Nigerian constitution that first introduced a form of regionalism, dividing the country into provinces with legislative councils, was the",
      ["Clifford Constitution of 1922", "Richards Constitution of 1946", "Macpherson Constitution of 1951", "Lyttelton Constitution of 1954"], "Clifford Constitution of 1922",
      "The Clifford Constitution of 1922 introduced the elective principle in Nigeria and established a legislative council with limited African representation."),
  _q("The Nigerian constitution credited with formally introducing regionalism by dividing the country into the Northern, Western, and Eastern regions was the",
      ["Richards Constitution of 1946", "Clifford Constitution of 1922", "Macpherson Constitution of 1951", "Independence Constitution of 1960"], "Richards Constitution of 1946",
      "The Richards Constitution of 1946 divided Nigeria into three regions, each with its own legislative council, laying the groundwork for later federalism."),
  _q("The Nigerian constitution that introduced greater regional autonomy and increased Nigerian participation in the central legislature was the",
      ["Macpherson Constitution of 1951", "Richards Constitution of 1946", "Clifford Constitution of 1922", "Lyttelton Constitution of 1954"], "Macpherson Constitution of 1951",
      "The Macpherson Constitution of 1951 expanded regional self-government and increased African representation in central government institutions."),
  _q("The Nigerian constitution that established a full federal system of government with regions enjoying self-government was the",
      ["Lyttelton Constitution of 1954", "Macpherson Constitution of 1951", "Richards Constitution of 1946", "Clifford Constitution of 1922"], "Lyttelton Constitution of 1954",
      "The Lyttelton Constitution of 1954 firmly established federalism in Nigeria, granting the regions considerable self-governing powers."),
  _q("Nigeria attained political independence from British colonial rule in the year",
      ["1960", "1963", "1979", "1999"], "1960",
      "Nigeria became an independent nation on 1 October 1960, though it remained a monarchy under the British crown for a few more years."),
  _q("Nigeria became a full republic, replacing the British monarch as head of state with a Nigerian president, in the year",
      ["1963", "1960", "1979", "1999"], "1963",
      "The 1963 Republican Constitution made Nigeria a republic, with an indigenous president as head of state instead of the British monarch."),
  _q("The Nigerian constitution that introduced the American-style presidential system of government, replacing the parliamentary system, was the",
      ["1979 Constitution", "1963 Constitution", "1960 Constitution", "1989 Constitution"], "1979 Constitution",
      "The 1979 Constitution shifted Nigeria from the parliamentary (Westminster) system to a presidential system modelled on that of the United States."),
  _q("The most recent constitution currently in operation in Nigeria, which came into effect at the return to civilian rule, is the",
      ["1999 Constitution", "1979 Constitution", "1989 Constitution", "1963 Constitution"], "1999 Constitution",
      "The 1999 Constitution ushered in the current Fourth Republic and remains Nigeria's operative constitution, though it has since been amended."),
  _q("A country's foreign policy is best described as",
      ["the set of principles and strategies guiding its relations with other states and international bodies", "the internal rules governing its civil service", "the process by which its local governments are financed", "the method used to select its judiciary"], "the set of principles and strategies guiding its relations with other states and international bodies",
      "Foreign policy encompasses a state's objectives, principles, and actions in its dealings with other nations and international organisations."),
  _q("A key principle commonly guiding Nigeria's foreign policy is",
      ["Africa as the centrepiece of its foreign relations", "complete isolation from all other African countries", "permanent alliance with a single foreign superpower only", "total avoidance of international organisations"], "Africa as the centrepiece of its foreign relations",
      "Nigeria has traditionally emphasised African unity, decolonisation, and continental cooperation as central to its foreign policy."),
  _q("The international organisation established after the Second World War to maintain global peace and security among member nations is the",
      ["United Nations Organization (UNO)", "African Union (AU)", "Commonwealth of Nations", "Economic Community of West African States (ECOWAS)"], "United Nations Organization (UNO)",
      "The UNO was formed in 1945 to promote international peace, security, and cooperation among sovereign states worldwide."),
  _q("The organ of the United Nations with primary responsibility for the maintenance of international peace and security is the",
      ["Security Council", "General Assembly", "Economic and Social Council", "International Court of Justice"], "Security Council",
      "The UN Security Council, with its permanent and non-permanent members, holds primary responsibility for addressing threats to peace and authorising interventions."),
  _q("The continental organisation that succeeded the Organisation of African Unity (OAU) in 2002, aimed at promoting African unity and development, is the",
      ["African Union (AU)", "United Nations Organization (UNO)", "Commonwealth of Nations", "ECOWAS"], "African Union (AU)",
      "The African Union replaced the OAU in 2002, with a broader mandate covering political and economic integration across the continent."),
  _q("The regional organisation established in 1975 to promote economic integration and cooperation among West African states is the",
      ["Economic Community of West African States (ECOWAS)", "African Union (AU)", "United Nations Organization (UNO)", "Commonwealth of Nations"], "Economic Community of West African States (ECOWAS)",
      "ECOWAS was founded in 1975 to foster economic cooperation, free movement of goods and people, and regional stability in West Africa."),
  _q("The voluntary association of mostly former British colonies and dependencies, cooperating on trade, democracy, and development, is called the",
      ["Commonwealth of Nations", "African Union", "United Nations Organization", "ECOWAS"], "Commonwealth of Nations",
      "The Commonwealth of Nations links the United Kingdom and many of its former colonies in a voluntary association promoting shared values and cooperation."),
];
