import "../quiz_question.dart";

const _subject = "Clothing and Textiles";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// WAEC Clothing and Textiles question bank covering the full syllabus:
/// Textile Science & Fabrics, Sewing Equipment & Garment Construction, and
/// Pattern Draft, Fashion & Care of Clothing.
List<QuizQuestion> buildWaecClothingAndTextilesQuestions() {
  return [
    ..._textileScienceAndFabrics,
    ..._sewingEquipmentAndGarmentConstruction,
    ..._patternDraftFashionAndCareOfClothing,
  ];
}

final _textileScienceAndFabrics = [
  _q("Fibres obtained from plant sources, such as cotton and flax, are classified as",
      ["natural vegetable fibres", "natural animal fibres", "regenerated fibres", "true synthetic fibres"], "natural vegetable fibres",
      "Vegetable fibres, such as cotton and flax, are natural fibres derived directly from plants."),
  _q("Fibres obtained from animal sources, such as wool and silk, are classified as",
      ["natural animal fibres", "natural vegetable fibres", "regenerated fibres", "true synthetic fibres"], "natural animal fibres",
      "Animal fibres, such as wool (from sheep) and silk (from silkworms), are natural fibres derived from animal sources."),
  _q("Cotton fibre is obtained from the",
      ["seed pod (boll) of the cotton plant", "stem of the flax plant", "fleece of a sheep", "cocoon of the silkworm"], "seed pod (boll) of the cotton plant",
      "Cotton fibre is harvested from the seed pod (boll) of the cotton plant, one of the most widely used natural vegetable fibres."),
  _q("Flax fibre, used to produce linen fabric, is obtained from the",
      ["stem of the flax plant", "seed pod of the cotton plant", "fleece of a sheep", "cocoon of the silkworm"], "stem of the flax plant",
      "Flax fibre is extracted from the stem of the flax plant, and is processed to produce linen fabric."),
  _q("Wool fibre is obtained from the",
      ["fleece of sheep (and some other animals)", "seed pod of the cotton plant", "stem of the flax plant", "cocoon of the silkworm"], "fleece of sheep (and some other animals)",
      "Wool is a natural animal fibre obtained from the fleece of sheep, and sometimes other animals like goats (mohair, cashmere)."),
  _q("Silk fibre is obtained from the",
      ["cocoon of the silkworm", "fleece of sheep", "seed pod of the cotton plant", "stem of the flax plant"], "cocoon of the silkworm",
      "Silk is a natural animal fibre produced from the cocoon spun by the silkworm."),
  _q("Fibres manufactured by chemically processing natural cellulose, such as wood pulp, into a new fibre form are classified as",
      ["regenerated fibres", "true synthetic fibres", "natural vegetable fibres", "natural animal fibres"], "regenerated fibres",
      "Regenerated fibres, such as rayon and acetate, are manufactured from naturally occurring cellulose that has been chemically processed into fibre form."),
  _q("Rayon is an example of a",
      ["regenerated fibre", "true synthetic fibre", "natural vegetable fibre", "natural animal fibre"], "regenerated fibre",
      "Rayon is manufactured from cellulose (derived from wood pulp or similar sources), classifying it as a regenerated fibre rather than a truly synthetic one."),
  _q("Fibres manufactured entirely from chemical polymers, without using naturally occurring cellulose as a base, are classified as",
      ["true synthetic fibres", "regenerated fibres", "natural vegetable fibres", "natural animal fibres"], "true synthetic fibres",
      "True synthetic fibres, such as nylon and polyester, are manufactured entirely from chemical polymers rather than processed natural materials."),
  _q("Nylon, polyester, and acrylic are all examples of",
      ["true synthetic fibres", "regenerated fibres", "natural vegetable fibres", "natural animal fibres"], "true synthetic fibres",
      "Nylon, polyester, and acrylic are manufactured entirely from synthetic chemical polymers, classifying them as true synthetic fibres."),
  _q("Examining a fibre under a microscope to observe its structure is one method used for",
      ["fibre identification", "fabric weaving", "pattern drafting", "garment fitting"], "fibre identification",
      "Microscopic examination reveals a fibre's distinctive structural features, helping to identify the type of fibre present in a fabric."),
  _q("A test that identifies fibre type by observing how a small sample reacts when exposed to a flame, including the smell and residue produced, is called a",
      ["burning test", "chemical test", "tensile strength test", "moisture absorbency test"], "burning test",
      "The burning test identifies fibres based on characteristics such as how they burn, the smell produced, and the type of ash or residue left behind."),
  _q("When burned, natural cellulose fibres such as cotton typically produce a smell similar to",
      ["burning paper", "burning hair or feathers", "burning plastic", "no smell at all"], "burning paper",
      "Cotton and other cellulose fibres typically burn with a smell resembling burning paper, distinguishing them from protein-based fibres like wool."),
  _q("When burned, protein-based fibres such as wool or silk typically produce a smell similar to",
      ["burning hair or feathers", "burning paper", "burning plastic", "no smell at all"], "burning hair or feathers",
      "Wool and silk, being protein-based fibres, typically produce a smell resembling burning hair or feathers when tested by burning."),
  _q("The ability of a fabric to withstand pulling force without breaking is called its",
      ["tensile strength", "moisture absorbency", "flammability", "elasticity only"], "tensile strength",
      "Tensile strength measures a fabric's resistance to breaking under pulling (tension) forces, an important property for durability."),
  _q("The ability of a fabric to take up and hold moisture is called its",
      ["moisture absorbency", "tensile strength", "flammability", "colour fastness only"], "moisture absorbency",
      "Moisture absorbency describes how readily a fabric takes up and holds moisture, affecting comfort, especially in warm climates."),
  _q("A continuous, very long strand of fibre, such as that produced naturally by a silkworm, is used to make",
      ["filament yarn", "staple yarn", "regenerated fibre only", "true synthetic fibre only"], "filament yarn",
      "Filament yarns are made from continuous, long fibre strands, such as those naturally produced by silk, or manufactured synthetically."),
  _q("A yarn made by twisting together many short fibre lengths, such as those from cotton or wool, is called",
      ["staple yarn", "filament yarn", "regenerated yarn only", "synthetic yarn only"], "staple yarn",
      "Staple yarns are spun from many short fibre lengths twisted together, typical of natural fibres like cotton and wool."),
  _q("The lengthwise yarns held under tension on a loom, through which the crosswise yarns are woven, are called the",
      ["warp", "weft", "selvedge only", "pile only"], "warp",
      "The warp consists of the lengthwise yarns fixed to the loom, forming the foundation through which the weft yarns are interlaced."),
  _q("The crosswise yarns woven over and under the warp yarns on a loom to create fabric are called the",
      ["weft", "warp", "selvedge only", "pile only"], "weft",
      "The weft yarns are woven crosswise, over and under the warp yarns, to construct woven fabric."),
  _q("The simplest weave pattern, in which the weft yarn passes alternately over and under each warp yarn, is called the",
      ["plain weave", "twill weave", "satin weave", "pile weave"], "plain weave",
      "Plain weave is the most basic weaving pattern, with the weft simply alternating over and under each warp yarn in a regular sequence."),
  _q("A fabric construction method that interlocks a series of connected loops of yarn, rather than weaving crossed threads, is called",
      ["knitting", "weaving", "felting", "bonding"], "knitting",
      "Knitting constructs fabric by interlocking loops of yarn, giving knitted fabrics their characteristic stretch, unlike woven fabrics."),
  _q("A fabric construction method that matts and compresses fibres together using heat, moisture, and pressure, without weaving or knitting, is called",
      ["felting", "knitting", "weaving", "bonding only"], "felting",
      "Felting compresses and matts fibres (traditionally wool) together using heat, moisture, and pressure, producing fabric without weaving or knitting."),
  _q("A fabric construction method that joins fibres together using an adhesive or heat-fusing process, common in non-woven fabrics, is called",
      ["bonding", "weaving", "knitting", "felting only"], "bonding",
      "Bonding joins fibres together using adhesives or heat fusion, a technique commonly used to produce non-woven fabrics."),
  _q("A chemical test used to help identify fibre type by observing how a sample reacts when exposed to acids or alkalis is called a",
      ["chemical test", "burning test only", "tensile strength test only", "moisture absorbency test only"], "chemical test",
      "Chemical tests expose fibre samples to reagents such as acids or alkalis, observing reactions like dissolving or discolouration to help identify fibre type."),
  _q("Cotton fabric is generally known for its",
      ["good moisture absorbency and comfort in warm climates", "complete resistance to creasing", "very low moisture absorbency", "inability to be dyed any colour"], "good moisture absorbency and comfort in warm climates",
      "Cotton is valued for its good moisture absorbency, making it comfortable to wear, particularly in warm climates."),
  _q("Silk fabric is generally known for its",
      ["natural sheen (lustre) and smooth, luxurious feel", "extremely rough, coarse texture", "complete lack of any lustre", "inability to be woven into fabric"], "natural sheen (lustre) and smooth, luxurious feel",
      "Silk is prized for its natural lustre and smooth, luxurious feel, making it a highly valued fabric for fine garments."),
  _q("Wool fabric is generally known for its",
      ["good warmth retention, making it suitable for colder climates", "poor warmth retention compared to cotton", "complete resistance to felting", "unsuitability for any type of garment"], "good warmth retention, making it suitable for colder climates",
      "Wool is valued for its excellent warmth retention properties, making it particularly suitable for garments worn in colder climates."),
  _q("Polyester fabric is generally known for its",
      ["durability, wrinkle resistance, and quick-drying properties", "extremely poor durability compared to natural fibres", "complete inability to resist wrinkles", "very slow drying time compared to cotton"], "durability, wrinkle resistance, and quick-drying properties",
      "Polyester, a true synthetic fibre, is valued for its durability, resistance to wrinkling, and quick-drying properties."),
  _q("A blended fabric, combining two or more different fibre types (such as cotton and polyester), is created mainly to",
      ["combine the desirable properties of each fibre type in a single fabric", "eliminate all properties of both fibre types", "increase production cost with no functional benefit", "make fibre identification always impossible"], "combine the desirable properties of each fibre type in a single fabric",
      "Blended fabrics combine different fibres to bring together their most desirable properties, such as cotton's comfort with polyester's durability."),
  _q("The narrow, tightly woven edge running along both lengthwise sides of a woven fabric, which prevents fraying, is called the",
      ["selvedge", "warp only", "weft only", "pile only"], "selvedge",
      "The selvedge is the fabric's finished, self-edged border along its length, preventing the edges from fraying."),
  _q("A twill weave, in contrast to a plain weave, is generally identified by its",
      ["distinctive diagonal rib pattern on the fabric's surface", "completely flat surface with no visible pattern", "identical structure to a plain weave in every respect", "inability to be used for any type of garment"], "distinctive diagonal rib pattern on the fabric's surface",
      "Twill weave produces a distinctive diagonal rib pattern on the fabric surface, differing from the simple, flat criss-cross appearance of a plain weave."),
  _q("Knitted fabrics, compared to woven fabrics, generally offer greater",
      ["stretch and flexibility, due to their looped construction", "rigidity, with no stretch whatsoever", "similarity to felted fabric in construction method", "resistance to any form of stretching"], "stretch and flexibility, due to their looped construction",
      "The interlocking loop structure of knitted fabrics gives them greater inherent stretch and flexibility compared to the fixed criss-cross structure of woven fabrics."),
];

final _sewingEquipmentAndGarmentConstruction = [
  _q("The part of a sewing machine that holds and drives the needle up and down is called the",
      ["needle bar", "bobbin case", "presser foot", "hand wheel"], "needle bar",
      "The needle bar holds the needle and moves it up and down as the machine operates, forming stitches through the fabric."),
  _q("The small case holding the bottom thread supply on a sewing machine, interlocking with the top thread to form a stitch, is called the",
      ["bobbin case", "needle bar", "presser foot", "tension disc"], "bobbin case",
      "The bobbin case holds the lower thread supply, which interlocks with the needle's upper thread beneath the fabric to form a stitch."),
  _q("The part of a sewing machine that holds the fabric flat against the feed dogs during stitching is called the",
      ["presser foot", "needle bar", "bobbin case", "hand wheel"], "presser foot",
      "The presser foot holds the fabric firmly in place against the feed dogs, ensuring even, controlled movement of fabric during stitching."),
  _q("The mechanism on a sewing machine that controls how tightly the thread is drawn, affecting stitch quality, is called the",
      ["tension control (discs)", "presser foot only", "bobbin winder only", "hand wheel only"], "tension control (discs)",
      "Tension control discs regulate how much resistance is applied to the thread as it passes through, directly affecting the quality and balance of each stitch."),
  _q("Thread breaking frequently while sewing is often caused by",
      ["incorrect tension settings or a poorly threaded machine", "a perfectly balanced tension setting", "using thread of the correct weight for the fabric", "no issue at all with the machine's settings"], "incorrect tension settings or a poorly threaded machine",
      "Frequent thread breakage is commonly caused by incorrect tension settings or improper threading of the machine."),
  _q("Skipped stitches while sewing are often caused by",
      ["a bent, blunt, or incorrectly inserted needle", "using a brand new, correctly inserted needle", "correctly balanced thread tension", "properly maintained machine timing"], "a bent, blunt, or incorrectly inserted needle",
      "Skipped stitches are commonly caused by problems with the needle, such as it being bent, blunt, or not properly inserted into the machine."),
  _q("Puckered seams while sewing are often caused by",
      ["excessively tight thread tension for the fabric being used", "correctly balanced tension appropriate to the fabric", "using a properly sharpened needle", "properly matched thread and fabric weight"], "excessively tight thread tension for the fabric being used",
      "Puckered seams often result from thread tension set too tightly for the fabric being sewn, causing the fabric to gather unevenly along the seam."),
  _q("A tool used to measure body dimensions and fabric lengths, typically flexible enough to follow body curves, is called a",
      ["tape measure", "tailor's chalk", "pinking shears", "seam ripper"], "tape measure",
      "A flexible tape measure is essential for accurately measuring body dimensions and fabric lengths, including curved areas."),
  _q("A marking tool used to draw temporary guide lines directly onto fabric, easily removable afterward, is called",
      ["tailor's chalk", "tape measure", "pinking shears", "thimble"], "tailor's chalk",
      "Tailor's chalk marks fabric temporarily, allowing guide lines for cutting or stitching that can later be brushed or washed away."),
  _q("A cutting tool with straight blades used for cutting fabric cleanly along marked lines is called",
      ["shears", "pinking shears", "a seam ripper", "a thimble"], "shears",
      "Shears have straight-edged blades designed for making clean, accurate cuts through fabric."),
  _q("A cutting tool with zigzag-edged blades, used to cut fabric edges in a way that reduces fraying, is called",
      ["pinking shears", "ordinary shears", "a seam ripper", "a thimble"], "pinking shears",
      "Pinking shears cut fabric with a zigzag edge, which helps to reduce fraying along raw, unfinished fabric edges."),
  _q("A small tool used to unpick unwanted stitches from a seam is called a",
      ["seam ripper", "thimble", "tape measure", "tailor's chalk"], "seam ripper",
      "A seam ripper is specifically designed to carefully cut and remove unwanted stitches from a seam."),
  _q("A small protective cap worn on the finger to push a needle through fabric safely during hand sewing is called a",
      ["thimble", "seam ripper", "tape measure", "pinking shears"], "thimble",
      "A thimble protects the finger while pushing a needle through fabric, particularly useful for thicker or tougher materials."),
  _q("Temporary stitches used to hold fabric pieces together before permanent stitching, easily removed afterward, are called",
      ["tacking (basting) stitches", "backstitches", "hemming stitches", "running stitches only"], "tacking (basting) stitches",
      "Tacking (basting) stitches temporarily hold fabric layers in place before final, permanent stitching, and are removed once no longer needed."),
  _q("A basic hand stitch made by passing the needle in and out of the fabric in a simple, even, straight line is called a",
      ["running stitch", "backstitch", "hemming stitch", "tacking stitch only"], "running stitch",
      "A running stitch is a simple, straightforward hand stitch, formed by evenly passing the needle in and out of the fabric."),
  _q("A strong hand stitch formed by taking the needle back over the previous stitch before moving forward, commonly used for durability, is called a",
      ["backstitch", "running stitch", "hemming stitch", "tacking stitch"], "backstitch",
      "A backstitch is a strong, durable hand stitch created by looping back over the previous stitch, providing greater strength than a simple running stitch."),
  _q("A stitch specifically used to secure a folded fabric edge (hem) in place, often nearly invisible from the right side, is called a",
      ["hemming stitch", "backstitch", "running stitch", "tacking stitch"], "hemming stitch",
      "A hemming stitch secures a folded fabric edge discreetly, ideally remaining nearly invisible on the garment's right side."),
  _q("A simple seam formed by placing two fabric pieces right sides together and stitching along the seam allowance, then pressing it open or to one side, is called an",
      ["open (plain) seam", "enclosed (French) seam", "flat-felled seam", "bound seam"], "open (plain) seam",
      "An open (plain) seam is the most basic seam type, sewn with fabric right sides together and the seam allowance pressed open or to one side."),
  _q("A seam that fully encloses the raw edges within a second row of stitching, giving a clean finish on both sides, is called a",
      ["French seam", "open (plain) seam", "hemming stitch", "tacking stitch"], "French seam",
      "A French seam encloses the fabric's raw edges completely, achieved by stitching twice, giving a neat, self-finished appearance on both sides."),
  _q("A flat, enclosed seam commonly used in more durable garments like jeans, formed by folding one seam allowance over the other and stitching it down, is called a",
      ["machine-felled (flat-felled) seam", "French seam only", "open seam only", "bound seam"], "machine-felled (flat-felled) seam",
      "A machine-felled (flat-felled) seam encloses raw edges within a flat, durable finish, commonly seen in sturdy garments such as jeans."),
  _q("Small folds of fabric drawn together by a line of stitching, used to control fullness in a soft, gathered manner, are called",
      ["gathers", "pleats", "darts", "tucks"], "gathers",
      "Gathers create soft, evenly distributed fullness in fabric, typically formed by pulling stitching threads to draw the fabric together."),
  _q("A fold of fabric pressed and stitched in place to control fullness, folded in a single direction, is called a",
      ["knife pleat", "box pleat", "inverted pleat", "dart"], "knife pleat",
      "A knife pleat is a single fold of fabric pressed uniformly in one direction, commonly used to control fullness in skirts and garments."),
  _q("A pleat formed by two folds turning away from each other, creating a flat panel in the centre, is called a",
      ["box pleat", "knife pleat", "inverted pleat", "dart"], "box pleat",
      "A box pleat is formed by two folds facing outward in opposite directions, creating a flat panel of fabric in the centre."),
  _q("A pleat formed by two folds turning toward each other, creating a flat panel that appears as the reverse of a box pleat, is called an",
      ["inverted pleat", "knife pleat", "box pleat", "dart"], "inverted pleat",
      "An inverted pleat is essentially a box pleat viewed from the reverse side, with the folds turning inward rather than outward."),
  _q("A stitched, tapered fold used to shape flat fabric to fit the contours of the body, such as at the bust or waist, is called a",
      ["dart", "pleat", "gather", "tuck"], "dart",
      "Darts are tapered folds sewn into flat fabric to create shape, allowing garments to fit the body's natural contours."),
  _q("A small, stitched fold of fabric, similar to a pleat but generally narrower and used more for decorative or minor fullness control, is called a",
      ["tuck", "dart", "gather", "box pleat"], "tuck",
      "Tucks are small, stitched folds, narrower than typical pleats, often used decoratively or to control minor amounts of fullness."),
  _q("A garment opening finished with a continuous strip of fabric, commonly used for openings like sleeve cuffs, is called a",
      ["continuous strip opening (placket)", "faced opening", "zipper opening only", "bound buttonhole only"], "continuous strip opening (placket)",
      "A continuous strip opening (placket) uses a folded strip of fabric to neatly finish an opening, commonly seen at sleeve cuffs."),
  _q("A garment opening finished by attaching a separate, shaped piece of fabric to neaten the raw edges is called a",
      ["faced opening", "continuous strip opening", "zipper opening only", "bound buttonhole only"], "faced opening",
      "A faced opening uses a separate shaped fabric piece (facing) stitched to the garment to neatly finish the raw edges of an opening."),
  _q("A mechanical fastener with interlocking teeth, drawn together or apart by a sliding tab, is called a",
      ["zipper", "button", "hook and eye", "press stud"], "zipper",
      "A zipper uses interlocking teeth and a sliding tab to quickly open and close a garment opening."),
  _q("A fastener consisting of a small disc sewn onto fabric, secured through a corresponding buttonhole, is called a",
      ["button", "zipper", "hook and eye", "press stud"], "button",
      "A button is secured through a matching buttonhole, one of the most common and traditional garment fastening methods."),
  _q("A small metal fastener consisting of a hook and a corresponding loop (eye), often used at waistbands or necklines, is called a",
      ["hook and eye", "zipper", "button", "press stud"], "hook and eye",
      "A hook and eye fastener uses a small metal hook that catches a corresponding loop (eye), commonly used at waistbands or necklines."),
  _q("A small, two-part snap fastener that clicks together when pressed, commonly used on lighter garments, is called a",
      ["press stud (snap fastener)", "zipper", "button", "hook and eye"], "press stud (snap fastener)",
      "A press stud (snap fastener) consists of two interlocking parts that click together when pressed, commonly used on lighter fabrics and garments."),
  _q("A piece of fabric attached to the inside of a garment opening or edge to neaten and strengthen it, without being visible from the outside, is called a",
      ["facing", "binding", "collar", "cuff"], "facing",
      "A facing is stitched to the inside of an edge or opening to neaten and reinforce it, remaining hidden from the outside of the garment."),
  _q("A strip of fabric or bias tape used to enclose and finish a raw fabric edge, often visible on the outside of the garment, is called a",
      ["binding", "facing", "collar", "cuff"], "binding",
      "Binding encloses a raw fabric edge using a strip of fabric or bias tape, often visible and sometimes used decoratively on the garment's exterior."),
];

final _patternDraftFashionAndCareOfClothing = [
  _q("Taking accurate body measurements, such as bust, waist, and hip, is an essential first step in",
      ["pattern drafting and garment fitting", "fabric weaving only", "fibre identification only", "laundry care only"], "pattern drafting and garment fitting",
      "Accurate body measurements form the essential foundation for drafting patterns and ensuring a well-fitting garment."),
  _q("A pre-printed pattern, purchased ready-made in standard sizes for home sewing, is called a",
      ["commercial (flat) pattern", "basic block pattern", "toile only", "muslin only"], "commercial (flat) pattern",
      "Commercial flat patterns are pre-printed, standard-sized patterns purchased for home use, offering a convenient alternative to drafting from scratch."),
  _q("A basic, fitted pattern shape without design details, used as a foundation for developing other pattern styles, is called a",
      ["basic block (sloper)", "commercial pattern", "toile only", "facing only"], "basic block (sloper)",
      "A basic block (sloper) is a simple, closely fitted foundation pattern, from which more elaborate designs can be developed by adding style features."),
  _q("A basic pattern block covering the upper body torso area is called the",
      ["bodice block", "skirt block", "sleeve block", "trouser block"], "bodice block",
      "The bodice block is the foundational pattern piece for the upper body (torso), used as a base for designing various tops and dresses."),
  _q("A basic pattern block covering the lower body from the waist down to a chosen hem length is called the",
      ["skirt block", "bodice block", "sleeve block", "collar block"], "skirt block",
      "The skirt block is the foundational pattern piece covering the body from the waist downward, used as a base for various skirt designs."),
  _q("A basic pattern block specifically shaping the arm covering of a garment is called the",
      ["sleeve block", "bodice block", "skirt block", "collar block"], "sleeve block",
      "The sleeve block is the foundational pattern piece shaping the arm covering, used as a base for designing different sleeve styles."),
  _q("Adjusting a pattern to better suit an individual's specific body measurements or fit preferences is called",
      ["pattern alteration", "fabric bonding", "fibre identification", "hemming"], "pattern alteration",
      "Pattern alteration modifies a standard or basic pattern to better match an individual's specific body measurements and fit needs."),
  _q("The design principle concerned with the visual direction created by seams, darts, or trims on a garment is called",
      ["line", "form", "colour", "texture"], "line",
      "Line refers to the visual direction created within a garment's design, such as through seams, darts, or decorative trim, influencing its overall silhouette."),
  _q("The design principle concerned with the overall three-dimensional shape and structure of a garment on the body is called",
      ["form", "line", "colour", "texture"], "form",
      "Form describes the overall three-dimensional shape a garment takes on the body, influenced by its cut and construction."),
  _q("The design principle concerned with the hue and shade choices used in a garment's fabric or trim is called",
      ["colour", "line", "form", "texture"], "colour",
      "Colour, as a design principle, considers the hues and shades selected for a garment, influencing mood and visual impact."),
  _q("The design principle concerned with the surface quality and feel of a garment's fabric, such as smooth or rough, is called",
      ["texture", "line", "form", "colour"], "texture",
      "Texture describes the surface quality and tactile feel of a fabric, contributing to a garment's overall visual and physical character."),
  _q("When selecting a garment for a formal occasion, an important consideration is",
      ["choosing styles and fabrics appropriate to the formality of the event", "wearing whatever is most casual regardless of the occasion", "ignoring the nature of the event entirely", "selecting only garments unsuitable for the weather"], "choosing styles and fabrics appropriate to the formality of the event",
      "Selecting appropriate garments for an occasion involves matching the style and fabric formality to the nature of the event."),
  _q("When selecting garments suited to a person's body silhouette, the general goal is to",
      ["choose styles that flatter and balance the individual's body shape", "ignore body shape entirely when selecting clothing", "always choose the tightest possible fit regardless of shape", "select only one universal style suitable for every body shape"], "choose styles that flatter and balance the individual's body shape",
      "Thoughtful garment selection considers an individual's body silhouette, choosing styles that flatter and create a balanced, harmonious appearance."),
  _q("Wardrobe planning that considers a person's financial allocation mainly aims to",
      ["select versatile, cost-effective garments that meet the individual's needs within budget", "encourage unlimited spending regardless of financial means", "ignore cost considerations entirely when planning a wardrobe", "select only the most expensive garments available"], "select versatile, cost-effective garments that meet the individual's needs within budget",
      "Budget-conscious wardrobe planning focuses on selecting versatile, cost-effective garments that meet needs while remaining within financial means."),
  _q("Traditional soap, used in laundry work, is generally made through a chemical reaction between fat/oil and",
      ["an alkali (such as caustic soda)", "an acid (such as vinegar)", "a synthetic polymer", "a bleach compound"], "an alkali (such as caustic soda)",
      "Traditional soap is produced through saponification, a chemical reaction between fats/oils and an alkali such as caustic soda."),
  _q("Synthetic detergents, compared to traditional soap, generally offer an advantage in",
      ["performing effectively even in hard water, without forming scum", "being made entirely from natural fats and oils only", "requiring no chemical processing whatsoever", "being completely ineffective at removing dirt"], "performing effectively even in hard water, without forming scum",
      "Synthetic detergents were developed partly to overcome soap's tendency to form scum in hard water, performing more effectively under such conditions."),
  _q("The laundry step that involves separating garments by colour, fabric type, or soil level before washing is called",
      ["sorting", "soaking", "starching", "pressing"], "sorting",
      "Sorting separates garments by colour, fabric type, or soiling level before washing, helping to prevent colour bleeding and fabric damage."),
  _q("The laundry step that involves submerging heavily soiled garments in water (often with detergent) before the main wash is called",
      ["soaking", "sorting", "starching", "pressing"], "soaking",
      "Soaking pre-treats heavily soiled garments by submerging them in water, often with detergent, loosening stains before the main wash cycle."),
  _q("The laundry step that applies a stiffening agent to certain fabrics, such as cotton, to give them added body and crispness, is called",
      ["starching", "soaking", "sorting", "rinsing"], "starching",
      "Starching applies a stiffening agent to fabric, giving items like cotton shirts added body and a crisp finish."),
  _q("The laundry step that uses heat and pressure to smooth out wrinkles from freshly washed and dried garments is called",
      ["pressing (ironing)", "sorting", "soaking", "starching"], "pressing (ironing)",
      "Pressing (ironing) uses heat and pressure to smooth out wrinkles, giving laundered garments a neat, finished appearance."),
  _q("Removing a stain using an appropriate chemical reagent generally requires first identifying the",
      ["type of stain, since different stains require different treatment methods", "brand of the garment, regardless of the stain type", "size of the garment only, with no regard for the stain", "colour of the garment only, ignoring the stain's nature"], "type of stain, since different stains require different treatment methods",
      "Effective stain removal depends on correctly identifying the type of stain, since different stains (e.g., oil-based vs. protein-based) require different treatment approaches."),
  _q("International textile care symbols, found on garment labels, are designed to",
      ["provide standardised washing and care instructions understood across different countries and languages", "replace the need for any washing instructions at all", "only apply within a single specific country", "indicate the price of the garment"], "provide standardised washing and care instructions understood across different countries and languages",
      "Standardised international care symbols provide universally understood washing and care guidance, regardless of the language spoken by the garment's owner."),
  _q("A care label symbol showing a triangle typically relates to instructions regarding",
      ["bleaching", "ironing temperature", "washing temperature", "dry cleaning"], "bleaching",
      "The triangle symbol on care labels conventionally relates to bleaching instructions, indicating whether and how a garment may be safely bleached."),
  _q("A care label symbol showing a circle typically relates to instructions regarding",
      ["dry cleaning", "washing temperature", "ironing temperature", "bleaching"], "dry cleaning",
      "The circle symbol on care labels conventionally indicates dry cleaning instructions, including whether the garment is suitable for this process."),
  _q("A care label symbol showing an iron shape typically relates to instructions regarding",
      ["ironing temperature", "washing temperature", "bleaching", "dry cleaning"], "ironing temperature",
      "The iron-shaped symbol on care labels conventionally indicates the appropriate ironing temperature and any precautions for the fabric."),
  _q("A care label symbol showing a tub or basin shape typically relates to instructions regarding",
      ["washing temperature and method", "ironing temperature only", "bleaching only", "dry cleaning only"], "washing temperature and method",
      "The tub (washtub) symbol on care labels conventionally indicates appropriate washing temperature and method for the garment."),
  _q("A toile (muslin) is typically made during garment construction mainly to",
      ["test the fit and design of a pattern using cheap fabric before cutting the final garment fabric", "serve as the final, finished garment itself", "replace the need for any pattern at all", "permanently line the inside of a finished garment"], "test the fit and design of a pattern using cheap fabric before cutting the final garment fabric",
      "A toile (test garment, often made in muslin) allows a designer to check fit and design details using inexpensive fabric before committing to the final, often costlier, fabric."),
  _q("When drafting a basic bodice block, key body measurements typically required include the",
      ["bust, waist, and back width measurements", "shoe size and hat size only", "hair length and eye colour", "measurements unrelated to the upper body at all"], "bust, waist, and back width measurements",
      "Drafting an accurate bodice block requires key upper body measurements, such as bust, waist, and back width."),
  _q("Wardrobe planning that considers weather conditions mainly involves",
      ["selecting fabrics and styles suited to temperature and climate", "ignoring climate entirely when selecting garments", "choosing only garments suited to a single season, regardless of location", "selecting fabric based solely on colour, with no regard for climate"], "selecting fabrics and styles suited to temperature and climate",
      "Sensible wardrobe planning accounts for climate and weather, selecting appropriate fabric weights and styles for the prevailing conditions."),
  _q("Age-appropriate clothing selection generally considers factors such as",
      ["comfort, practicality, and suitability for the wearer's stage of life", "ignoring the wearer's age and needs entirely", "selecting identical styles for every age group without exception", "choosing only the most impractical designs available"], "comfort, practicality, and suitability for the wearer's stage of life",
      "Age-appropriate clothing selection balances comfort, practicality, and suitability, reflecting the specific needs of the wearer's stage of life."),
  _q("Bleach should generally be used on fabrics only after checking the",
      ["care label, to confirm the fabric can safely tolerate bleach", "garment's price tag, with no regard for fabric type", "season in which the garment was purchased", "size label, with no regard for fabric composition"], "care label, to confirm the fabric can safely tolerate bleach",
      "Checking the care label before using bleach helps confirm whether a fabric can safely tolerate this strong chemical treatment, avoiding damage or discolouration."),
  _q("Protein-based stains, such as blood or egg, are generally best treated initially using",
      ["cold water, since hot water can set the stain by cooking the protein", "boiling hot water, to dissolve the stain quickly", "direct ironing before any other treatment", "no water of any kind, using only dry heat"], "cold water, since hot water can set the stain by cooking the protein",
      "Protein-based stains should generally be treated with cold water first, as hot water can cause the protein to coagulate and set the stain more firmly into the fabric."),
  _q("Oil-based stains are generally best treated using",
      ["a suitable grease-cutting agent, such as dish soap, before laundering", "cold water alone, with no other treatment", "starch applied directly to the stain", "ignoring the stain entirely, since it will fade naturally"], "a suitable grease-cutting agent, such as dish soap, before laundering",
      "Oil-based stains typically respond best to grease-cutting agents, such as dish soap, applied before the garment is laundered."),
];
