import "../quiz_question.dart";

const _subject = "Economics";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// WAEC Economics question bank covering the full syllabus: Elements of
/// Economic Analysis, Microeconomics (Demand, Supply & Price
/// Determination), Production/Cost/Market Structures, Macroeconomics
/// (National Income & Financial Systems), and Public Finance/International
/// Trade/Development.
List<QuizQuestion> buildWaecEconomicsQuestions() {
  return [
    ..._elementsOfEconomicAnalysis,
    ..._microeconomicsDemandSupplyPrice,
    ..._productionCostMarketStructures,
    ..._macroeconomicsNationalIncomeAndFinance,
    ..._publicFinanceTradeAndDevelopment,
  ];
}

final _elementsOfEconomicAnalysis = [
  _q("Economics is best defined as the study of",
      ["how people and society choose to use scarce resources to satisfy unlimited wants", "how governments print money", "how companies advertise their products", "how banks lend money to customers"], "how people and society choose to use scarce resources to satisfy unlimited wants",
      "Economics studies the allocation of limited (scarce) resources to meet the unlimited wants of individuals and society."),
  _q("The economic problem arises fundamentally because",
      ["human wants are unlimited while resources to satisfy them are limited", "governments refuse to print enough money", "prices of goods are always too high", "banks refuse to give out loans"], "human wants are unlimited while resources to satisfy them are limited",
      "Scarcity — the gap between limited resources and unlimited wants — is the basic economic problem faced by every society."),
  _q("The act of selecting one alternative out of several competing uses for a scarce resource is called",
      ["choice", "scarcity", "opportunity cost", "scale of preference"], "choice",
      "Because resources are scarce, individuals and societies must make a choice about how to allocate them among competing uses."),
  _q("The value of the next best alternative forgone when a choice is made is called",
      ["opportunity cost", "scarcity", "scale of preference", "choice"], "opportunity cost",
      "Opportunity cost measures what is given up (the best alternative) when one option is chosen over another."),
  _q("An arrangement of a consumer's wants in order of importance, from the most pressing to the least pressing, is called a",
      ["scale of preference", "opportunity cost", "demand schedule", "supply schedule"], "scale of preference",
      "A scale of preference ranks wants by urgency, helping an individual decide which wants to satisfy first given limited resources."),
  _q("An economic system in which resources are owned and allocated mainly by private individuals through the market is called",
      ["capitalism (free market/free enterprise economy)", "socialism (command economy)", "a mixed economy", "a traditional economy"], "capitalism (free market/free enterprise economy)",
      "In a capitalist (free market) economy, private individuals and firms own resources, and prices set by market forces guide allocation decisions."),
  _q("An economic system in which resources are owned and allocated mainly by the state or government is called",
      ["socialism (command/planned economy)", "capitalism", "a mixed economy", "a traditional economy"], "socialism (command/planned economy)",
      "Under socialism, the government owns key resources and directs production and distribution through central planning rather than market forces."),
  _q("An economic system that combines features of both private enterprise and government control/ownership of resources is called a",
      ["mixed economy", "capitalist economy", "socialist economy", "traditional economy"], "mixed economy",
      "A mixed economy allows both private and public ownership, blending market forces with government intervention."),
  _q("An economic system in which production and distribution are guided mainly by customs and inherited practices, with little role for markets or central planning, is called a",
      ["traditional economy", "capitalist economy", "socialist economy", "mixed economy"], "traditional economy",
      "Traditional economies rely on custom, heritage, and long-established practices to decide what, how, and for whom to produce."),
  _q("One advantage of a free market (capitalist) economy is that it",
      ["encourages efficiency and innovation through competition", "guarantees equal distribution of income to all citizens", "eliminates unemployment completely", "removes the need for prices altogether"], "encourages efficiency and innovation through competition",
      "Competition among private firms in a free market economy tends to drive efficiency, innovation, and consumer choice."),
  _q("One disadvantage of a socialist (command) economy is that it",
      ["may reduce individual incentive and innovation due to lack of private ownership", "always leads to hyperinflation", "cannot provide any public goods", "relies entirely on foreign aid"], "may reduce individual incentive and innovation due to lack of private ownership",
      "Without private ownership and profit incentives, individuals and firms in a command economy may have less motivation to innovate or work efficiently."),
  _q("The branch of economic reasoning that starts from general principles and applies them to specific situations is called",
      ["deductive reasoning", "inductive reasoning", "positive economics", "normative economics"], "deductive reasoning",
      "Deductive reasoning moves from general economic theories/laws to explain or predict specific outcomes."),
  _q("The branch of economic reasoning that starts from specific observations and builds up general theories or conclusions is called",
      ["inductive reasoning", "deductive reasoning", "normative economics", "positive economics"], "inductive reasoning",
      "Inductive reasoning derives general economic principles from patterns observed in specific real-world data."),
  _q("An economic statement that describes 'what is' and can be tested against facts is called",
      ["positive economics", "normative economics", "deductive economics", "welfare economics"], "positive economics",
      "Positive economics deals with objective, factual statements that can be verified or refuted by evidence."),
  _q("An economic statement that expresses an opinion about 'what ought to be' is called",
      ["normative economics", "positive economics", "deductive economics", "inductive economics"], "normative economics",
      "Normative economics involves value judgments about what economic policy or outcomes should be, rather than objective facts."),
];

final _microeconomicsDemandSupplyPrice = [
  _q("The law of demand states that, all things being equal,",
      ["as the price of a good falls, the quantity demanded rises, and vice versa", "as the price of a good rises, the quantity demanded also rises", "quantity demanded is unrelated to price", "demand always equals supply at every price"], "as the price of a good falls, the quantity demanded rises, and vice versa",
      "The law of demand describes an inverse relationship between price and quantity demanded, holding other factors constant."),
  _q("A table showing the various quantities of a commodity that consumers are willing and able to buy at different prices is called a",
      ["demand schedule", "supply schedule", "scale of preference", "price index"], "demand schedule",
      "A demand schedule tabulates the relationship between price levels and the corresponding quantity demanded."),
  _q("A graphical representation showing the relationship between the price of a good and the quantity demanded is called the",
      ["demand curve", "supply curve", "production possibility curve", "Lorenz curve"], "demand curve",
      "The demand curve plots price against quantity demanded, typically sloping downward due to the law of demand."),
  _q("A movement along a demand curve, caused only by a change in the price of the good itself, is called a",
      ["change in quantity demanded", "change in demand", "change in supply", "shift in the supply curve"], "change in quantity demanded",
      "A change in quantity demanded refers strictly to movement along the same demand curve due to a price change of that good."),
  _q("An entire shift of the demand curve, caused by factors other than the price of the good itself (such as income or tastes), is called a",
      ["change in demand", "change in quantity demanded", "change in quantity supplied", "movement along the demand curve"], "change in demand",
      "A change in demand shifts the whole curve, reflecting changes in factors like income, tastes, or the price of related goods."),
  _q("The responsiveness of quantity demanded to a change in the price of a good is called",
      ["price elasticity of demand", "income elasticity of demand", "cross elasticity of demand", "elasticity of supply"], "price elasticity of demand",
      "Price elasticity of demand measures how much quantity demanded changes in response to a change in a good's own price."),
  _q("Price elasticity of demand is calculated as",
      ["percentage change in quantity demanded divided by percentage change in price", "percentage change in price divided by percentage change in quantity demanded", "change in total revenue divided by change in price", "change in supply divided by change in demand"], "percentage change in quantity demanded divided by percentage change in price",
      "This formula measures the sensitivity of quantity demanded to price changes, expressed as a ratio of percentage changes."),
  _q("If a small change in price leads to a proportionately larger change in quantity demanded, demand is said to be",
      ["elastic", "inelastic", "unitary elastic", "perfectly inelastic"], "elastic",
      "Elastic demand means quantity demanded is highly responsive to price changes, with the percentage change in quantity exceeding the percentage change in price."),
  _q("If a change in price leads to a proportionately smaller change in quantity demanded, demand is said to be",
      ["inelastic", "elastic", "unitary elastic", "perfectly elastic"], "inelastic",
      "Inelastic demand means quantity demanded responds only slightly to price changes, common for necessities with few substitutes."),
  _q("The responsiveness of quantity demanded to a change in consumers' income is called",
      ["income elasticity of demand", "price elasticity of demand", "cross elasticity of demand", "elasticity of supply"], "income elasticity of demand",
      "Income elasticity of demand measures how quantity demanded changes as consumer income rises or falls."),
  _q("For a normal good, income elasticity of demand is",
      ["positive, since demand rises as income rises", "negative, since demand falls as income rises", "always exactly zero", "always greater than one"], "positive, since demand rises as income rises",
      "Normal goods have positive income elasticity because demand for them increases as consumers' incomes increase."),
  _q("For an inferior good, income elasticity of demand is",
      ["negative, since demand falls as income rises", "positive, since demand rises as income rises", "always exactly one", "always undefined"], "negative, since demand falls as income rises",
      "Inferior goods have negative income elasticity because consumers buy less of them as their incomes rise, switching to better alternatives."),
  _q("The responsiveness of the quantity demanded of one good to a change in the price of another good is called",
      ["cross elasticity of demand", "income elasticity of demand", "price elasticity of demand", "elasticity of supply"], "cross elasticity of demand",
      "Cross elasticity of demand measures how the quantity demanded of one good changes when the price of a related good changes."),
  _q("For two goods that are complements (such as bread and butter), cross elasticity of demand is",
      ["negative", "positive", "zero", "infinite"], "negative",
      "Complementary goods have negative cross elasticity: a rise in the price of one reduces demand for the other, since they are used together."),
  _q("The law of supply states that, all things being equal,",
      ["as the price of a good rises, the quantity supplied also rises, and vice versa", "as the price of a good rises, the quantity supplied falls", "supply is unrelated to price", "supply always equals demand"], "as the price of a good rises, the quantity supplied also rises, and vice versa",
      "The law of supply describes a direct (positive) relationship between price and quantity supplied, holding other factors constant."),
  _q("A table showing the various quantities of a commodity that producers are willing to sell at different prices is called a",
      ["supply schedule", "demand schedule", "scale of preference", "price index"], "supply schedule",
      "A supply schedule tabulates the relationship between price levels and the corresponding quantity supplied."),
  _q("An entire shift of the supply curve, caused by factors other than price (such as production costs or technology), is called a",
      ["change in supply", "change in quantity supplied", "change in quantity demanded", "movement along the supply curve"], "change in supply",
      "A change in supply shifts the whole curve, reflecting factors like input costs, technology, or the number of producers in the market."),
  _q("The responsiveness of quantity supplied to a change in the price of a good is called",
      ["price elasticity of supply", "price elasticity of demand", "income elasticity of demand", "cross elasticity of demand"], "price elasticity of supply",
      "Price elasticity of supply measures how quantity supplied responds to changes in the good's own price."),
  _q("The point at which the quantity demanded of a good exactly equals the quantity supplied is called",
      ["equilibrium", "surplus", "shortage", "elasticity"], "equilibrium",
      "Market equilibrium occurs where the demand and supply curves intersect, determining the equilibrium price and quantity."),
  _q("A situation where the quantity demanded exceeds the quantity supplied at a given price is called a",
      ["shortage (excess demand)", "surplus (excess supply)", "equilibrium", "glut"], "shortage (excess demand)",
      "A shortage occurs when consumers wish to buy more than producers supply at the prevailing price, pushing price up toward equilibrium."),
  _q("A legally imposed price above which a commodity may not be sold, aimed at protecting producers, is called a",
      ["minimum price (price floor)", "maximum price (price ceiling)", "market equilibrium price", "subsidised price"], "minimum price (price floor)",
      "A price floor (minimum price) is set above the equilibrium price to guarantee producers a certain return, often creating a persistent surplus."),
  _q("A legally imposed price above which a commodity may not be sold, aimed at protecting consumers, is called a",
      ["maximum price (price ceiling)", "minimum price (price floor)", "market equilibrium price", "free market price"], "maximum price (price ceiling)",
      "A price ceiling (maximum price) is set below the equilibrium price to keep essential goods affordable, but it often creates a shortage."),
];

final _productionCostMarketStructures = [
  _q("The four traditional factors of production are",
      ["land, labour, capital, and entrepreneur", "land, money, banks, and government", "labour, tax, trade, and profit", "capital, interest, wages, and rent"], "land, labour, capital, and entrepreneur",
      "Economics identifies land, labour, capital, and entrepreneurship as the basic resources combined to produce goods and services."),
  _q("The reward paid to the factor of production 'land' is called",
      ["rent", "wages", "interest", "profit"], "rent",
      "Rent is the payment made for the use of land and other natural resources."),
  _q("The reward paid to the factor of production 'labour' is called",
      ["wages (or salary)", "rent", "interest", "profit"], "wages (or salary)",
      "Wages (or salaries) are payments made to workers for their labour services."),
  _q("The reward paid to the factor of production 'capital' is called",
      ["interest", "rent", "wages", "profit"], "interest",
      "Interest is the payment made for the use of capital, such as money borrowed or invested."),
  _q("The reward paid to the factor of production 'entrepreneur' is called",
      ["profit", "rent", "wages", "interest"], "profit",
      "Profit is the reward an entrepreneur earns for organising other factors of production and bearing business risk."),
  _q("The law of diminishing returns states that as more units of a variable factor are added to a fixed factor,",
      ["output will eventually increase at a decreasing rate", "output will always increase at a constant rate", "output will always fall immediately", "total cost will always fall"], "output will eventually increase at a decreasing rate",
      "The law of diminishing returns applies in the short run, where adding more of a variable input to fixed inputs eventually yields smaller and smaller additions to output."),
  _q("Breaking down a production process into separate, specialised tasks performed by different workers is called",
      ["division of labour", "diminishing returns", "economies of scale", "opportunity cost"], "division of labour",
      "Division of labour splits work into specialised tasks, which can raise efficiency and productivity."),
  _q("One advantage of division of labour is that it",
      ["increases efficiency and output through specialisation", "eliminates the need for factors of production", "guarantees full employment in an economy", "removes all forms of unemployment"], "increases efficiency and output through specialisation",
      "By allowing workers to focus on tasks they are skilled at, division of labour tends to raise overall productivity."),
  _q("Costs that do not change with the level of output in the short run, such as rent, are called",
      ["fixed costs", "variable costs", "marginal costs", "total costs"], "fixed costs",
      "Fixed costs remain constant regardless of how much (or little) is produced in the short run."),
  _q("Costs that change directly with the level of output, such as raw materials, are called",
      ["variable costs", "fixed costs", "average fixed costs", "sunk costs"], "variable costs",
      "Variable costs rise and fall with the quantity of output produced, unlike fixed costs."),
  _q("Total cost is calculated as",
      ["fixed costs plus variable costs", "fixed costs minus variable costs", "total revenue minus total cost", "average cost times price"], "fixed costs plus variable costs",
      "Total cost combines both the constant fixed costs and the output-dependent variable costs of production."),
  _q("The cost of producing one additional unit of output is called",
      ["marginal cost", "average cost", "fixed cost", "total cost"], "marginal cost",
      "Marginal cost measures the extra cost incurred from producing one more unit of a good."),
  _q("Total cost divided by the quantity of output produced gives the",
      ["average cost", "marginal cost", "fixed cost", "total revenue"], "average cost",
      "Average (total) cost is the cost per unit of output, found by dividing total cost by quantity produced."),
  _q("The total amount of money a firm receives from selling its output is called",
      ["total revenue", "total cost", "marginal cost", "average cost"], "total revenue",
      "Total revenue equals the price per unit multiplied by the quantity of units sold."),
  _q("The additional revenue earned from selling one more unit of output is called",
      ["marginal revenue", "average revenue", "total revenue", "marginal cost"], "marginal revenue",
      "Marginal revenue measures the change in total revenue resulting from selling one extra unit."),
  _q("A market structure in which there are many buyers and sellers, homogeneous products, and free entry and exit is called",
      ["perfect competition", "monopoly", "oligopoly", "monopolistic competition"], "perfect competition",
      "Perfect competition is characterised by many small firms selling identical products, with no single firm able to influence market price."),
  _q("Under perfect competition, an individual firm is described as a",
      ["price taker", "price maker", "price controller", "price fixer"], "price taker",
      "Since firms in perfect competition are small relative to the market and sell identical goods, they must accept the market-determined price."),
  _q("A market structure in which a single firm is the sole supplier of a good or service, with no close substitutes, is called a",
      ["monopoly", "perfect competition", "oligopoly", "monopolistic competition"], "monopoly",
      "A monopoly exists when one firm dominates the entire market for a product with no close substitutes available."),
  _q("A market structure with many firms selling similar but slightly differentiated products is called",
      ["monopolistic competition", "perfect competition", "monopoly", "oligopoly"], "monopolistic competition",
      "Monopolistic competition features many sellers offering differentiated products (through branding, quality, etc.), giving each some pricing power."),
  _q("A market structure dominated by a small number of large firms, often interdependent in their pricing and output decisions, is called",
      ["oligopoly", "monopoly", "perfect competition", "monopolistic competition"], "oligopoly",
      "In an oligopoly, a few large firms dominate the market, and each firm's decisions significantly affect and are affected by its rivals."),
];

final _macroeconomicsNationalIncomeAndFinance = [
  _q("The total monetary value of all final goods and services produced within a country's borders in a given period is called",
      ["Gross Domestic Product (GDP)", "Gross National Product (GNP)", "Net National Product (NNP)", "Personal Income"], "Gross Domestic Product (GDP)",
      "GDP measures output produced within a country's geographical boundaries, regardless of who owns the resources used."),
  _q("The total monetary value of goods and services produced by a country's nationals, both at home and abroad, is called",
      ["Gross National Product (GNP)", "Gross Domestic Product (GDP)", "Net Domestic Product (NDP)", "Disposable Income"], "Gross National Product (GNP)",
      "GNP measures output produced by a country's citizens and businesses regardless of location, unlike GDP which is location-based."),
  _q("GNP minus depreciation (capital consumption allowance) gives the",
      ["Net National Product (NNP)", "Gross Domestic Product (GDP)", "Personal Income", "Disposable Income"], "Net National Product (NNP)",
      "NNP adjusts GNP for the wear and tear (depreciation) of capital equipment used in production during the period."),
  _q("The income actually received by individuals before personal taxes are deducted is called",
      ["Personal Income", "Disposable Income", "National Income", "Gross Domestic Product"], "Personal Income",
      "Personal income is the total income received by households from all sources, before personal income tax is deducted."),
  _q("Personal Income minus personal income taxes gives",
      ["Disposable Income", "Gross National Product", "Net National Product", "National Income"], "Disposable Income",
      "Disposable income is what individuals actually have available to spend or save after taxes have been deducted."),
  _q("The method of measuring national income by adding up all incomes earned by factors of production is called the",
      ["income method", "expenditure method", "output (product) method", "value-added method"], "income method",
      "The income approach sums wages, rent, interest, and profit earned by all factors of production in the economy."),
  _q("The method of measuring national income by adding up all spending on final goods and services is called the",
      ["expenditure method", "income method", "output method", "value-added method"], "expenditure method",
      "The expenditure approach sums consumption, investment, government spending, and net exports to measure national income."),
  _q("The method of measuring national income by adding up the value of output produced by all sectors of the economy is called the",
      ["output (product) method", "income method", "expenditure method", "circular flow method"], "output (product) method",
      "The output approach totals the value added by each industry or sector to avoid double-counting intermediate goods."),
  _q("Counting the value of a good more than once at different stages of production when measuring national income is called the problem of",
      ["double counting", "depreciation", "inflation", "deflation"], "double counting",
      "Double counting inflates national income figures by including the value of intermediate goods multiple times; using value-added avoids this."),
  _q("Money can be best described as",
      ["anything generally acceptable as a medium of exchange", "any object used only for decoration", "a good that cannot be exchanged for other goods", "an asset that always loses its value over time"], "anything generally acceptable as a medium of exchange",
      "Money serves as a widely accepted medium of exchange, facilitating trade without requiring a double coincidence of wants."),
  _q("The function of money that allows it to be used to buy goods and services directly is called",
      ["medium of exchange", "store of value", "unit of account", "standard for deferred payment"], "medium of exchange",
      "As a medium of exchange, money is accepted in transactions for goods and services, replacing the need for barter."),
  _q("The function of money that allows prices of different goods to be compared using a common measure is called",
      ["unit of account (measure of value)", "medium of exchange", "store of value", "standard for deferred payment"], "unit of account (measure of value)",
      "As a unit of account, money provides a common standard for expressing and comparing the value of different goods and services."),
  _q("The function of money that allows wealth to be saved and used at a later date is called",
      ["store of value", "medium of exchange", "unit of account", "legal tender"], "store of value",
      "Money serves as a store of value, allowing purchasing power to be preserved over time (though inflation can erode this)."),
  _q("The desire to hold money for day-to-day transactions such as buying food and paying bills is called the",
      ["transactionary motive for holding money", "precautionary motive for holding money", "speculative motive for holding money", "store of value motive"], "transactionary motive for holding money",
      "The transactionary motive reflects the need to hold cash to cover routine, everyday spending."),
  _q("The desire to hold money to meet unforeseen or emergency expenses is called the",
      ["precautionary motive for holding money", "transactionary motive for holding money", "speculative motive for holding money", "unit of account motive"], "precautionary motive for holding money",
      "The precautionary motive reflects holding extra cash as a buffer against unexpected needs or emergencies."),
  _q("The desire to hold money in order to take advantage of expected future changes in interest rates or asset prices is called the",
      ["speculative motive for holding money", "transactionary motive for holding money", "precautionary motive for holding money", "store of value motive"], "speculative motive for holding money",
      "The speculative motive involves holding money to invest later when conditions (such as interest rates or prices) become more favourable."),
  _q("A bank that accepts deposits from the public and grants short- to medium-term loans is called a",
      ["commercial bank", "central bank", "development bank", "merchant bank"], "commercial bank",
      "Commercial banks are the primary retail banks that handle deposits, withdrawals, and lending for individuals and businesses."),
  _q("The bank responsible for issuing a country's currency and controlling the overall money supply is the",
      ["central bank", "commercial bank", "merchant bank", "development bank"], "central bank",
      "The central bank has the sole authority to issue legal tender currency and implement monetary policy for the whole economy."),
  _q("Central bank actions aimed at controlling the money supply and interest rates to influence the economy are called",
      ["monetary policy", "fiscal policy", "trade policy", "incomes policy"], "monetary policy",
      "Monetary policy involves tools like interest rates and open market operations, used by the central bank to manage money supply and economic activity."),
  _q("A persistent, sustained rise in the general price level of goods and services in an economy is called",
      ["inflation", "deflation", "disinflation", "stagnation"], "inflation",
      "Inflation reduces the purchasing power of money as prices rise generally across the economy over time."),
  _q("Inflation caused by too much money chasing too few goods, i.e., excess aggregate demand, is called",
      ["demand-pull inflation", "cost-push inflation", "structural inflation", "imported inflation"], "demand-pull inflation",
      "Demand-pull inflation arises when total demand in the economy outstrips the available supply of goods and services, driving prices up."),
  _q("Inflation caused by rising production costs, such as wages or raw material prices, being passed on to consumers is called",
      ["cost-push inflation", "demand-pull inflation", "hyperinflation", "deflation"], "cost-push inflation",
      "Cost-push inflation occurs when increased costs of production lead firms to raise prices to maintain profit margins."),
];

final _publicFinanceTradeAndDevelopment = [
  _q("Government revenue collected directly from individuals and businesses, such as personal income tax and company tax, is called",
      ["direct tax", "indirect tax", "value-added tax on imports only", "subsidy"], "direct tax",
      "Direct taxes are levied directly on the income or wealth of individuals and firms and cannot easily be shifted to another party."),
  _q("Government revenue collected on goods and services, such as excise duty and import duty, is called",
      ["indirect tax", "direct tax", "personal income tax", "company tax"], "indirect tax",
      "Indirect taxes are levied on goods and services and can often be passed on, at least in part, from sellers to buyers through prices."),
  _q("The economic principle stating that a tax should be proportional to a taxpayer's ability to pay is the canon of",
      ["equity (ability to pay)", "certainty", "convenience", "economy"], "equity (ability to pay)",
      "The canon of equity requires that taxes be fair, generally taking more from those with a greater capacity to pay."),
  _q("The economic principle stating that the amount, time, and manner of tax payment should be clear to the taxpayer is the canon of",
      ["certainty", "equity", "convenience", "economy"], "certainty",
      "The canon of certainty requires that taxpayers know exactly how much tax to pay, when, and how, without arbitrary changes."),
  _q("The economic principle stating that taxes should be collected in a manner and at a time convenient to the taxpayer is the canon of",
      ["convenience", "certainty", "equity", "economy"], "convenience",
      "The canon of convenience ensures the method and timing of tax collection are easy and suitable for the taxpayer, such as deducting tax at source."),
  _q("The economic principle stating that the cost of collecting a tax should be low relative to the revenue it generates is the canon of",
      ["economy", "equity", "certainty", "convenience"], "economy",
      "The canon of economy requires that the administrative cost of collecting a tax should not be excessive compared to the revenue raised."),
  _q("A budget in which planned government expenditure exceeds planned government revenue is called a",
      ["deficit budget", "surplus budget", "balanced budget", "zero budget"], "deficit budget",
      "A deficit budget occurs when a government plans to spend more than it expects to collect in revenue, requiring borrowing to cover the gap."),
  _q("A budget in which planned government revenue exceeds planned government expenditure is called a",
      ["surplus budget", "deficit budget", "balanced budget", "supplementary budget"], "surplus budget",
      "A surplus budget occurs when a government expects to collect more revenue than it plans to spend."),
  _q("A budget in which planned government revenue exactly equals planned government expenditure is called a",
      ["balanced budget", "deficit budget", "surplus budget", "zero-based budget"], "balanced budget",
      "A balanced budget occurs when total planned revenue equals total planned expenditure, with neither a surplus nor a deficit."),
  _q("The theory stating that a country should specialise in producing goods it can make relatively more efficiently than others, and trade for the rest, is called the theory of",
      ["comparative cost (comparative advantage)", "absolute advantage only", "protectionism", "balance of payments"], "comparative cost (comparative advantage)",
      "The theory of comparative advantage shows that countries gain from trade by specialising in goods they produce at a relatively lower opportunity cost."),
  _q("The ratio of the prices a country receives for its exports to the prices it pays for its imports is called the",
      ["terms of trade", "balance of trade", "balance of payments", "exchange rate"], "terms of trade",
      "Terms of trade compare export prices to import prices, indicating how much a country can import for a given quantity of exports."),
  _q("Government policy of restricting imports through tariffs, quotas, or other barriers to shield domestic industries from foreign competition is called",
      ["protectionism", "free trade", "entrepot trade", "specialisation"], "protectionism",
      "Protectionism uses trade barriers to protect local producers from cheaper or more competitive foreign goods."),
  _q("A policy that allows goods and services to move between countries without tariffs, quotas, or other restrictions is called",
      ["free trade", "protectionism", "autarky", "exchange control"], "free trade",
      "Free trade removes barriers to international trade, allowing goods and services to be exchanged based purely on market forces."),
  _q("A deliberate reduction in the official value of a country's currency in terms of other currencies is called",
      ["devaluation", "revaluation", "appreciation", "deflation"], "devaluation",
      "Devaluation lowers a currency's official exchange rate, typically to make exports cheaper and imports more expensive."),
  _q("A deliberate increase in the official value of a country's currency in terms of other currencies is called",
      ["revaluation", "devaluation", "depreciation", "inflation"], "revaluation",
      "Revaluation raises a currency's official exchange rate, typically making exports more expensive and imports cheaper."),
  _q("Economic growth is best defined as",
      ["a sustained increase in a country's real output (real GDP) over time", "a rise in the general price level", "a fall in the unemployment rate only", "an increase in a country's population only"], "a sustained increase in a country's real output (real GDP) over time",
      "Economic growth measures the expansion of an economy's productive capacity and output over a sustained period."),
  _q("Economic development is a broader concept than economic growth because it also includes",
      ["improvements in living standards, health, education, and general welfare", "only the increase in a country's GDP", "only the increase in a country's population", "only the value of a country's exports"], "improvements in living standards, health, education, and general welfare",
      "Economic development covers qualitative improvements in well-being (health, education, equality) beyond just growth in output."),
  _q("A common characteristic of most developing countries is",
      ["heavy dependence on the export of primary (agricultural or mineral) products", "very high levels of industrialisation", "very high per capita income", "very low population growth rates"], "heavy dependence on the export of primary (agricultural or mineral) products",
      "Many developing economies rely significantly on exporting raw agricultural or mineral commodities rather than finished manufactured goods."),
  _q("The regional body established mainly to promote economic integration and free movement of goods and people among West African states is",
      ["the Economic Community of West African States (ECOWAS)", "the African Union (AU)", "the World Trade Organization (WTO)", "the International Monetary Fund (IMF)"], "the Economic Community of West African States (ECOWAS)",
      "ECOWAS was established to promote economic cooperation, free trade, and integration among West African countries."),
  _q("The international financial institution that primarily provides short-term financial assistance to countries facing balance of payments problems is the",
      ["International Monetary Fund (IMF)", "World Bank", "World Trade Organization (WTO)", "African Development Bank (AfDB)"], "International Monetary Fund (IMF)",
      "The IMF offers financial support and policy advice to member countries experiencing balance of payments difficulties."),
  _q("The international financial institution that primarily provides long-term loans for development and reconstruction projects is the",
      ["World Bank", "International Monetary Fund (IMF)", "World Trade Organization (WTO)", "Central Bank"], "World Bank",
      "The World Bank funds long-term development projects such as infrastructure, education, and health, unlike the IMF's shorter-term focus."),
];
