import "../quiz_question.dart";

const _subject = "Physics";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// WAEC Physics — Mechanics & Properties of Matter & Thermal Physics.
/// Covers: Units/Dimensions, Kinematics, Dynamics, Circular Motion & SHM,
/// Statics, Work/Energy/Power/Machines, Elasticity, Hydrostatics,
/// Hydrodynamics, Temperature Measurement, Thermal Expansion, Gas Laws,
/// Quantity of Heat, and Heat Transfer.
List<QuizQuestion> buildWaecPhysicsMechanicsQuestions() {
  return [
    ..._unitsDimensions,
    ..._kinematics,
    ..._dynamics,
    ..._circularMotionShm,
    ..._statics,
    ..._workEnergyPowerMachines,
    ..._elasticity,
    ..._hydrostatics,
    ..._hydrodynamics,
    ..._temperatureMeasurement,
    ..._thermalExpansion,
    ..._gasLaws,
    ..._quantityOfHeat,
    ..._heatTransfer,
  ];
}

final _unitsDimensions = [
  _q("Which of the following is a fundamental (base) physical quantity?",
      ["Mass", "Force", "Velocity", "Pressure"], "Mass",
      "Mass, length, time, electric current, temperature, luminous intensity and amount of substance are the seven fundamental (base) quantities; force, velocity and pressure are all derived from these."),
  _q("Which of the following is a derived physical quantity?",
      ["Force", "Time", "Length", "Mass"], "Force",
      "Force is derived from the base quantities mass, length and time (F = ma, with dimensions MLT-2), unlike time, length and mass, which are themselves base quantities."),
  _q("The S.I. base unit of mass is the",
      ["kilogram", "gram", "newton", "pound"], "kilogram",
      "The kilogram (kg) is the S.I. base unit of mass; the newton is a derived unit of force, while the gram and pound are non-S.I. or subunit measures."),
  _q("The dimension of velocity is",
      ["LT-1", "LT-2", "MLT-1", "L2T-1"], "LT-1",
      "Velocity = distance/time, so its dimension is L (length) divided by T (time), giving LT-1."),
  _q("The dimension of force (F = ma) is",
      ["MLT-2", "MLT-1", "ML2T-2", "ML-1T-2"], "MLT-2",
      "Force = mass x acceleration. Acceleration has dimension LT-2, so force has dimension M x LT-2 = MLT-2."),
  _q("The dimension of pressure (force per unit area) is",
      ["ML-1T-2", "MLT-2", "ML2T-2", "ML-3"], "ML-1T-2",
      "Pressure = force/area = MLT-2 / L2 = ML-1T-2, since area has dimension L2."),
  _q("Dimensional analysis is mainly used to",
      ["check the homogeneity (consistency) of a physical equation", "measure the exact numerical value of a physical quantity", "determine the direction of a vector quantity", "calculate the efficiency of a machine"], "check the homogeneity (consistency) of a physical equation",
      "Dimensional analysis verifies that the dimensions on both sides of an equation match, confirming the equation is dimensionally consistent, though it cannot supply dimensionless numerical constants."),
  _q("Which pair of physical quantities has the same dimensions?",
      ["Work and Energy", "Force and Pressure", "Power and Force", "Velocity and Acceleration"], "Work and Energy",
      "Work and energy are both measured in joules and share the dimension ML2T-2, since energy is simply the capacity to do work; the other pairs have different dimensions."),
];

final _kinematics = [
  _q("Rectilinear motion refers to the motion of a body",
      ["along a straight line path", "along a circular path", "that repeats itself periodically", "that has zero velocity at all times"], "along a straight line path",
      "Rectilinear motion is motion confined to a straight line, as opposed to circular or curved (projectile) motion."),
  _q("In the equation of motion v = u + at, the symbol 'a' represents the",
      ["uniform acceleration of the body", "initial velocity of the body", "final velocity of the body", "total distance covered"], "uniform acceleration of the body",
      "In v = u + at, u is initial velocity, v is final velocity, t is time, and a is the constant (uniform) acceleration."),
  _q("A body starts with a velocity of 4 m/s and accelerates uniformly at 3 m/s2 for 6 s. What is its final velocity?",
      ["22 m/s", "18 m/s", "24 m/s", "7 m/s"], "22 m/s",
      "Using v = u + at: v = 4 + (3 x 6) = 4 + 18 = 22 m/s."),
  _q("A body with initial velocity 5 m/s accelerates uniformly at 2 m/s2 for 4 s. Using s = ut + 1/2 at^2, what distance does it cover?",
      ["36 m", "20 m", "16 m", "40 m"], "36 m",
      "s = ut + 1/2at^2 = (5 x 4) + 0.5(2)(4^2) = 20 + 0.5(2)(16) = 20 + 16 = 36 m."),
  _q("An object is dropped from rest and falls a vertical distance of 20 m. Using v^2 = u^2 + 2as and g = 10 m/s2, what is its velocity just before hitting the ground?",
      ["20 m/s", "10 m/s", "40 m/s", "200 m/s"], "20 m/s",
      "v^2 = u^2 + 2as = 0 + 2(10)(20) = 400, so v = sqrt(400) = 20 m/s."),
  _q("A stone dropped from rest takes 4 s to hit the ground. Using s = 1/2 gt^2 and g = 10 m/s2, from what height was it dropped?",
      ["80 m", "40 m", "20 m", "160 m"], "80 m",
      "s = 1/2 gt^2 = 0.5 x 10 x 4^2 = 0.5 x 10 x 16 = 80 m."),
  _q("A ball is thrown vertically upward with an initial velocity of 20 m/s. Using g = 10 m/s2, how long does it take to reach its maximum height?",
      ["2 s", "4 s", "1 s", "20 s"], "2 s",
      "At maximum height, final vertical velocity is zero, so t = u/g = 20/10 = 2 s."),
  _q("A ball is thrown vertically upward with an initial velocity of 20 m/s. Using g = 10 m/s2, what maximum height does it reach?",
      ["20 m", "40 m", "10 m", "200 m"], "20 m",
      "Maximum height h = u^2/(2g) = 20^2/(2 x 10) = 400/20 = 20 m."),
  _q("A projectile is launched with a velocity of 20 m/s at 30 degrees to the horizontal. Using g = 10 m/s2, what is its time of flight? (sin 30 degrees = 0.5)",
      ["2 s", "1 s", "4 s", "0.5 s"], "2 s",
      "Time of flight T = 2u sin(theta)/g = 2(20)(0.5)/10 = 20/10 = 2 s."),
  _q("For the same projectile (u = 20 m/s, angle = 30 degrees, g = 10 m/s2), what is the maximum height reached? (sin 30 degrees = 0.5)",
      ["5 m", "10 m", "20 m", "2.5 m"], "5 m",
      "Maximum height H = u^2 sin^2(theta)/(2g) = 400 x (0.5)^2 / 20 = 400 x 0.25 / 20 = 100/20 = 5 m."),
  _q("For the same projectile (u = 20 m/s, angle = 30 degrees, g = 10 m/s2), what is its horizontal range R = u^2 sin(2 theta)/g? (sin 60 degrees is approximately 0.87)",
      ["approximately 34.6 m", "20 m", "40 m", "5 m"], "approximately 34.6 m",
      "R = u^2 sin(2theta)/g = 400 x sin(60 degrees) / 10 = 400 x 0.866 / 10 = 346.4/10 = 34.6 m."),
  _q("During projectile motion (ignoring air resistance), the horizontal component of the velocity",
      ["remains constant throughout the flight", "increases steadily due to gravity", "decreases steadily due to gravity", "becomes zero at maximum height"], "remains constant throughout the flight",
      "Since gravity acts only vertically, there is no horizontal acceleration, so the horizontal velocity component stays constant throughout the projectile's flight."),
];

final _dynamics = [
  _q("Inertia is best described as the property of a body that makes it",
      ["resist any change in its state of rest or uniform motion", "always move in a circular path", "attract other bodies gravitationally", "lose energy continuously while moving"], "resist any change in its state of rest or uniform motion",
      "Inertia is the natural tendency of matter to remain in its existing state of rest or uniform motion unless acted upon by an external force, and is the basis of Newton's First Law."),
  _q("Newton's First Law of Motion states that a body remains at rest or in uniform motion in a straight line unless",
      ["an external unbalanced force acts on it", "it is placed in a vacuum", "its mass changes", "it is released from a height"], "an external unbalanced force acts on it",
      "This is the law of inertia: a net external force is required to change a body's velocity (speed or direction)."),
  _q("Newton's Second Law of Motion is expressed mathematically as",
      ["F = ma", "F = mv", "F = m/a", "F = m + a"], "F = ma",
      "Newton's Second Law states that the net force on a body equals the rate of change of momentum, which for constant mass reduces to F = ma."),
  _q("A resultant force of 20 N is applied to a mass of 5 kg. What acceleration is produced?",
      ["4 m/s2", "100 m/s2", "0.25 m/s2", "15 m/s2"], "4 m/s2",
      "Using F = ma: a = F/m = 20/5 = 4 m/s2."),
  _q("Newton's Third Law of Motion states that",
      ["for every action there is an equal and opposite reaction", "force is directly proportional to acceleration", "momentum is always conserved", "a body at rest has no inertia"], "for every action there is an equal and opposite reaction",
      "Newton's Third Law describes the mutual, paired nature of forces: any force exerted by one body on a second is matched by an equal and opposite force from the second on the first."),
  _q("Linear momentum of a body is defined as the product of its",
      ["mass and velocity", "mass and acceleration", "weight and time", "force and distance"], "mass and velocity",
      "Momentum p = mv, a vector quantity pointing in the same direction as the body's velocity."),
  _q("A body of mass 3 kg moves with a velocity of 4 m/s. What is its momentum?",
      ["12 kg m/s", "7 kg m/s", "1.33 kg m/s", "24 kg m/s"], "12 kg m/s",
      "Momentum = mass x velocity = 3 x 4 = 12 kg m/s."),
  _q("Impulse delivered to a body is defined as the",
      ["product of the force applied and the time for which it acts, equal to the change in momentum", "product of mass and velocity only", "rate of change of force", "product of force and distance moved"], "product of the force applied and the time for which it acts, equal to the change in momentum",
      "Impulse = F x t = change in momentum (mv - mu), linking the force-time effect of an impact to the resulting momentum change."),
  _q("The Law of Conservation of Linear Momentum states that in the absence of external forces, the total momentum of a system of colliding bodies",
      ["remains constant before and after collision", "always increases after collision", "always decreases after collision", "becomes zero after collision"], "remains constant before and after collision",
      "Provided no external (unbalanced) force acts on the system, total momentum before a collision equals total momentum after, whether the collision is elastic or inelastic."),
  _q("A 2 kg trolley moving at 6 m/s collides with a stationary 4 kg trolley and they stick together. What is their common velocity after collision?",
      ["2 m/s", "3 m/s", "1.5 m/s", "4 m/s"], "2 m/s",
      "By conservation of momentum: total momentum before = 2(6) + 4(0) = 12 kg m/s. Combined mass = 6 kg, so common velocity = 12/6 = 2 m/s."),
  _q("A collision in which both kinetic energy and momentum are conserved is called",
      ["a perfectly elastic collision", "a perfectly inelastic collision", "a partially elastic collision", "an oblique collision"], "a perfectly elastic collision",
      "In a perfectly elastic collision, the bodies bounce apart such that both total momentum and total kinetic energy are unchanged; in inelastic collisions, kinetic energy is not conserved (some is lost as heat/sound/deformation)."),
  _q("The coefficient of static friction between two surfaces is the ratio of the",
      ["limiting frictional force to the normal reaction between the surfaces", "normal reaction to the limiting frictional force", "applied force to the weight of the object", "weight of the object to the area of contact"], "limiting frictional force to the normal reaction between the surfaces",
      "Coefficient of friction (mu) = limiting friction (F) / normal reaction (R). If the normal reaction is 50 N and the limiting friction is 20 N, mu = 20/50 = 0.4."),
];

final _circularMotionShm = [
  _q("The centripetal force acting on a body moving in a circular path is given by the formula",
      ["F = mv^2/r", "F = mv/r", "F = mr/v", "F = mv^2 r"], "F = mv^2/r",
      "Centripetal force is the net force directed towards the centre of the circular path, required to keep the body moving in that path, given by F = mv^2/r."),
  _q("A 2 kg object moves in a circle of radius 5 m at a speed of 10 m/s. What centripetal force acts on it?",
      ["40 N", "20 N", "4 N", "100 N"], "40 N",
      "F = mv^2/r = 2 x 10^2 / 5 = 2 x 100/5 = 200/5 = 40 N."),
  _q("An object moves in a circle of radius 0.5 m with a linear speed of 2 m/s. What is its angular velocity (omega = v/r)?",
      ["4 rad/s", "1 rad/s", "0.25 rad/s", "2.5 rad/s"], "4 rad/s",
      "Angular velocity omega = v/r = 2/0.5 = 4 rad/s."),
  _q("Roads are banked at bends mainly to",
      ["provide part of the centripetal force needed, reducing reliance on friction alone", "reduce the speed of vehicles automatically", "increase the frictional force between tyres and road", "make the road surface smoother"], "provide part of the centripetal force needed, reducing reliance on friction alone",
      "Banking tilts the road so that a component of the normal reaction contributes to the centripetal force, allowing vehicles to safely negotiate bends at higher speeds with less dependence on friction."),
  _q("The period of a simple pendulum is given by the formula",
      ["T = 2(pi) sqrt(l/g)", "T = 2(pi) sqrt(g/l)", "T = 2(pi) l/g", "T = (pi) sqrt(lg)"], "T = 2(pi) sqrt(l/g)",
      "For small oscillations, the period of a simple pendulum depends only on its length (l) and the acceleration due to gravity (g), given by T = 2(pi) sqrt(l/g)."),
  _q("A simple pendulum has a length of 1 m. Using g = 10 m/s2, what is its period? (pi is approximately 3.14)",
      ["approximately 2.0 s", "approximately 1.0 s", "approximately 0.5 s", "approximately 4.0 s"], "approximately 2.0 s",
      "T = 2(pi) sqrt(l/g) = 2(3.14) sqrt(1/10) = 6.28 x 0.316 = approximately 1.99 s, i.e. about 2.0 s."),
  _q("The period of oscillation of a mass on a spring is given by the formula",
      ["T = 2(pi) sqrt(m/k)", "T = 2(pi) sqrt(k/m)", "T = 2(pi) mk", "T = 2(pi) sqrt(mk)"], "T = 2(pi) sqrt(m/k)",
      "For a mass m attached to a spring of force constant k undergoing SHM, the period is T = 2(pi) sqrt(m/k)."),
  _q("A mass of 0.5 kg is attached to a spring of force constant 50 N/m. What is the period of oscillation? (pi is approximately 3.14)",
      ["approximately 0.63 s", "approximately 1.26 s", "approximately 0.10 s", "approximately 6.3 s"], "approximately 0.63 s",
      "T = 2(pi) sqrt(m/k) = 2(3.14) sqrt(0.5/50) = 6.28 x sqrt(0.01) = 6.28 x 0.1 = 0.628 s, approximately 0.63 s."),
  _q("In Simple Harmonic Motion, the frequency (f) is related to the period (T) by",
      ["f = 1/T", "f = T", "f = 2T", "f = T^2"], "f = 1/T",
      "Frequency is the number of complete oscillations per second, the reciprocal of the period: f = 1/T."),
  _q("In Simple Harmonic Motion, at the extreme positions of oscillation, the body's velocity and acceleration are respectively",
      ["zero and maximum", "maximum and zero", "both zero", "both maximum"], "zero and maximum",
      "At the extreme (turning) points, the body is momentarily at rest (velocity = 0), while the restoring force, and hence acceleration, is at its greatest magnitude, directed back towards equilibrium."),
];

final _statics = [
  _q("Two forces of 6 N and 8 N act at right angles to each other on a body. What is the magnitude of their resultant?",
      ["10 N", "14 N", "2 N", "48 N"], "10 N",
      "For perpendicular forces, resultant = sqrt(6^2 + 8^2) = sqrt(36 + 64) = sqrt(100) = 10 N."),
  _q("The equilibrant of a system of forces is a single force that is",
      ["equal in magnitude but opposite in direction to the resultant", "equal in magnitude and direction to the resultant", "always twice the magnitude of the resultant", "always perpendicular to the resultant"], "equal in magnitude but opposite in direction to the resultant",
      "The equilibrant exactly balances the resultant of a set of forces, being equal in size but acting in the opposite direction, so that the body remains in equilibrium."),
  _q("The moment of a force about a point is defined as the product of the",
      ["force and the perpendicular distance from the point to the line of action of the force", "force and the mass of the object", "force and its velocity", "distance and time taken to apply the force"], "force and the perpendicular distance from the point to the line of action of the force",
      "Moment (torque) = force x perpendicular distance from the pivot to the line of action of the force, measuring the turning effect of the force."),
  _q("A force of 10 N acts at a perpendicular distance of 0.5 m from a pivot. What moment does it produce?",
      ["5 Nm", "10.5 Nm", "0.05 Nm", "20 Nm"], "5 Nm",
      "Moment = force x perpendicular distance = 10 x 0.5 = 5 Nm."),
  _q("A couple consists of",
      ["two equal, opposite, parallel forces whose lines of action do not coincide, producing rotation only", "two equal forces acting along the same line, producing no rotation", "a single force acting at the centre of gravity", "two unequal forces acting in the same direction"], "two equal, opposite, parallel forces whose lines of action do not coincide, producing rotation only",
      "A couple has zero resultant force (since the forces are equal and opposite) but produces a net turning moment because the forces act along different, parallel lines."),
  _q("A uniform rod is pivoted at its centre. A weight of 5 N hangs at 20 cm from the pivot on one side. What weight must hang at 30 cm from the pivot on the other side to balance the rod?",
      ["3.33 N", "7.5 N", "5 N", "1.5 N"], "3.33 N",
      "By the Principle of Moments: clockwise moment = anticlockwise moment. 5 x 20 = W x 30, so W = 100/30 = 3.33 N."),
  _q("The Principle of Moments states that when a body is in rotational equilibrium, the",
      ["sum of clockwise moments about any point equals the sum of anticlockwise moments about that point", "net force acting on the body must be greater than zero", "resultant of all forces must act through the centre of gravity only", "body must be moving at constant velocity"], "sum of clockwise moments about any point equals the sum of anticlockwise moments about that point",
      "This is the condition for rotational (moment) equilibrium: the turning effects in each direction about any chosen pivot must balance exactly."),
  _q("A rigid body is in complete equilibrium under coplanar forces when",
      ["the resultant force is zero and the resultant moment about any point is zero", "only the resultant force is zero", "only the resultant moment is zero", "all the forces are equal in magnitude"], "the resultant force is zero and the resultant moment about any point is zero",
      "Complete equilibrium requires both translational equilibrium (zero net force, so no acceleration) and rotational equilibrium (zero net moment, so no angular acceleration)."),
  _q("The centre of gravity of a body is the point through which",
      ["the entire weight of the body may be considered to act", "the body always rotates when spun", "no external forces can act", "the body's total mass becomes concentrated to zero"], "the entire weight of the body may be considered to act",
      "The centre of gravity is the single point at which the resultant of the weights of all the particles making up the body can be considered to act."),
  _q("A body is in neutral equilibrium if, when slightly displaced, it",
      ["stays in its new position without moving further or returning", "returns to its original position", "moves further away and topples over", "oscillates back and forth indefinitely"], "stays in its new position without moving further or returning",
      "In neutral equilibrium (e.g. a ball resting on a flat horizontal surface), the height of the centre of gravity does not change on displacement, so the body simply remains in its new position."),
];

final _workEnergyPowerMachines = [
  _q("Work done by a force is given by the formula",
      ["W = Fs cos(theta)", "W = Fs sin(theta)", "W = F/s", "W = Fs^2"], "W = Fs cos(theta)",
      "Work done W = Fs cos(theta), where F is the force, s is the displacement, and theta is the angle between the force and the direction of displacement."),
  _q("A force of 20 N moves an object 5 m in a direction making 60 degrees with the force. How much work is done? (cos 60 degrees = 0.5)",
      ["50 J", "100 J", "10 J", "86.6 J"], "50 J",
      "W = Fs cos(theta) = 20 x 5 x cos(60 degrees) = 100 x 0.5 = 50 J."),
  _q("A body of mass 4 kg moves with a velocity of 5 m/s. What is its kinetic energy?",
      ["50 J", "100 J", "20 J", "10 J"], "50 J",
      "KE = 1/2 mv^2 = 0.5 x 4 x 5^2 = 0.5 x 4 x 25 = 50 J."),
  _q("A body of mass 2 kg is raised to a height of 10 m. Using g = 10 m/s2, what is its gravitational potential energy?",
      ["200 J", "20 J", "100 J", "2000 J"], "200 J",
      "PE = mgh = 2 x 10 x 10 = 200 J."),
  _q("The Principle of Conservation of Mechanical Energy states that in the absence of friction and other resistive forces,",
      ["the sum of kinetic and potential energy of a system remains constant", "kinetic energy is always equal to potential energy", "potential energy is always converted entirely to heat", "total energy always increases as a body falls"], "the sum of kinetic and potential energy of a system remains constant",
      "Where only gravity does work (no friction or air resistance), the total mechanical energy (KE + PE) of a system remains constant, though it may change form as the body moves."),
  _q("An object falls freely from rest through a height of 20 m. Using g = 10 m/s2 and energy conservation, what is its velocity just before hitting the ground?",
      ["20 m/s", "200 m/s", "10 m/s", "40 m/s"], "20 m/s",
      "Loss in PE = gain in KE: mgh = 1/2 mv^2, so v = sqrt(2gh) = sqrt(2 x 10 x 20) = sqrt(400) = 20 m/s."),
  _q("A machine does 600 J of work in 20 seconds. What is its power output?",
      ["30 W", "12000 W", "3 W", "600 W"], "30 W",
      "Power = Work/time = 600/20 = 30 W."),
  _q("A pulley system is used to lift a load of 150 N with an effort of 30 N. What is its mechanical advantage?",
      ["5", "0.2", "180", "120"], "5",
      "Mechanical advantage (MA) = load/effort = 150/30 = 5."),
  _q("An inclined plane 10 m long is used to raise a load to a height of 2 m. What is its velocity ratio?",
      ["5", "0.2", "20", "12"], "5",
      "Velocity ratio (VR) = distance moved by effort/distance moved by load = length of incline/height = 10/2 = 5."),
  _q("A machine has a mechanical advantage of 4 and a velocity ratio of 5. What is its efficiency?",
      ["80%", "125%", "20%", "1.25%"], "80%",
      "Efficiency = (MA/VR) x 100% = (4/5) x 100% = 80%."),
  _q("In a hydraulic press, the small piston has an area of 5 cm^2 and the large piston has an area of 50 cm^2. If an effort is applied on the small piston to lift a load on the large piston, what is the velocity ratio (ratio of areas)?",
      ["10", "0.1", "45", "250"], "10",
      "Since pressure is transmitted equally (Pascal's principle), the force (and velocity) ratio equals the ratio of the piston areas: VR = A(large)/A(small) = 50/5 = 10."),
  _q("A gear system has a driver gear with 20 teeth engaged with a driven gear with 60 teeth. What is the velocity ratio of the system?",
      ["3", "0.33", "1200", "40"], "3",
      "Velocity ratio of gears = number of teeth on driven gear/number of teeth on driver gear = 60/20 = 3."),
];

final _elasticity = [
  _q("Hooke's Law states that within the elastic limit, the extension produced in a spring is",
      ["directly proportional to the applied force", "inversely proportional to the applied force", "independent of the applied force", "proportional to the square of the applied force"], "directly proportional to the applied force",
      "Hooke's Law: F = ke, so the extension (or compression) e is directly proportional to the applied force F, provided the elastic limit is not exceeded."),
  _q("A spring extends by 4 cm when a load of 20 N is applied. What is its spring constant?",
      ["5 N/cm", "0.2 N/cm", "80 N/cm", "16 N/cm"], "5 N/cm",
      "Spring constant k = F/e = 20 N / 4 cm = 5 N/cm."),
  _q("Tensile stress in a material under a stretching force is defined as the",
      ["force applied per unit cross-sectional area", "extension produced per unit original length", "force applied per unit extension", "extension produced per unit cross-sectional area"], "force applied per unit cross-sectional area",
      "Tensile stress = F/A, the applied force divided by the cross-sectional area over which it acts, measured in pascals (N/m^2)."),
  _q("Tensile strain in a stretched wire is defined as the",
      ["extension produced per unit original length", "force applied per unit cross-sectional area", "force applied per unit extension", "original length per unit extension"], "extension produced per unit original length",
      "Tensile strain = extension/original length (e/L), a dimensionless ratio describing the fractional deformation of the material."),
  _q("A wire of original length 1 m and cross-sectional area 2 x 10^-6 m^2 stretches by 0.5 x 10^-3 m under a force of 100 N. What is its Young's modulus?",
      ["1 x 10^11 Pa", "1 x 10^8 Pa", "2 x 10^4 Pa", "5 x 10^-7 Pa"], "1 x 10^11 Pa",
      "Stress = F/A = 100/(2 x 10^-6) = 5 x 10^7 Pa. Strain = e/L = (0.5 x 10^-3)/1 = 5 x 10^-4. Young's modulus = stress/strain = (5 x 10^7)/(5 x 10^-4) = 1 x 10^11 Pa."),
  _q("The energy stored in a spring stretched by an extension x under a force F (within the elastic limit) is given by",
      ["1/2 Fx", "Fx", "1/2 F/x", "Fx^2"], "1/2 Fx",
      "The elastic potential energy stored equals the area under the force-extension graph, a triangle, giving energy = 1/2 Fx (equivalently 1/2 kx^2)."),
  _q("A spring stretches by 4 cm (0.04 m) under a force of 20 N. How much elastic potential energy is stored in it?",
      ["0.4 J", "0.8 J", "4 J", "0.04 J"], "0.4 J",
      "Energy stored = 1/2 Fx = 0.5 x 20 x 0.04 = 0.4 J."),
  _q("The elastic limit of a material is the point beyond which the material",
      ["no longer returns to its original shape and size when the deforming force is removed", "obeys Hooke's Law perfectly", "begins to obey Hooke's Law", "cannot be stretched any further under any force"], "no longer returns to its original shape and size when the deforming force is removed",
      "Beyond the elastic limit, a material undergoes permanent (plastic) deformation and does not fully recover its original dimensions once the force is removed."),
];

final _hydrostatics = [
  _q("Density of a substance is defined as its",
      ["mass per unit volume", "weight per unit volume", "mass per unit area", "volume per unit mass"], "mass per unit volume",
      "Density (rho) = mass/volume, typically measured in kg/m^3 or g/cm^3."),
  _q("A body has a mass of 500 g and a volume of 200 cm^3. What is its density?",
      ["2500 kg/m3", "2.5 kg/m3", "0.4 kg/m3", "400 kg/m3"], "2500 kg/m3",
      "Convert to S.I. units: mass = 0.5 kg, volume = 200 cm^3 = 2 x 10^-4 m^3. Density = 0.5/(2 x 10^-4) = 2500 kg/m3."),
  _q("The relative density of a substance is defined as the ratio of the",
      ["density of the substance to the density of water", "mass of the substance to its volume", "weight of the substance to its mass", "density of water to the density of the substance"], "density of the substance to the density of water",
      "Relative density (specific gravity) = density of substance / density of water, a dimensionless number since both densities are in the same units."),
  _q("An object weighs 50 N in air and 30 N when fully submerged in water. What is its relative density, using the apparent loss of weight method?",
      ["2.5", "1.5", "0.6", "20"], "2.5",
      "Relative density = weight in air / (weight in air - weight in water) = 50/(50-30) = 50/20 = 2.5."),
  _q("The pressure exerted at a depth h in a liquid of density (rho) is given by",
      ["P = h(rho)g", "P = h/(rho)g", "P = h(rho)/g", "P = hg/(rho)"], "P = h(rho)g",
      "Liquid pressure at depth h is P = h(rho)g, depending on the depth, the liquid's density, and the acceleration due to gravity, but not on the shape of the container."),
  _q("What pressure is exerted at a depth of 2 m in water of density 1000 kg/m3? (g = 10 m/s2)",
      ["20000 Pa", "2000 Pa", "200 Pa", "5000 Pa"], "20000 Pa",
      "P = h(rho)g = 2 x 1000 x 10 = 20000 Pa (20 kPa)."),
  _q("Pascal's Principle states that pressure applied to an enclosed fluid is",
      ["transmitted equally in all directions throughout the fluid", "transmitted only in the direction of the applied force", "reduced as it spreads through the fluid", "converted entirely into heat energy"], "transmitted equally in all directions throughout the fluid",
      "Pascal's Principle underlies hydraulic machines: pressure applied anywhere to a confined, incompressible fluid is transmitted undiminished to every part of the fluid and the walls of its container."),
  _q("A body of volume 0.002 m^3 is fully submerged in water of density 1000 kg/m3 (g = 10 m/s2). What upthrust acts on it, according to Archimedes' Principle?",
      ["20 N", "2 N", "200 N", "0.02 N"], "20 N",
      "Archimedes' Principle: upthrust = weight of fluid displaced = (rho)Vg = 1000 x 0.002 x 10 = 20 N."),
];

final _hydrodynamics = [
  _q("Surface tension is the property of a liquid surface that makes it behave like a",
      ["stretched elastic membrane, tending to minimise its surface area", "rigid solid sheet that cannot be deformed", "gas with no cohesive forces between molecules", "perfectly frictionless surface"], "stretched elastic membrane, tending to minimise its surface area",
      "Surface tension arises from cohesive forces between liquid molecules at the surface, causing the surface to act like a stretched elastic skin that resists an increase in area."),
  _q("The rise of a liquid in a narrow capillary tube is",
      ["inversely proportional to the radius of the tube", "directly proportional to the radius of the tube", "independent of the radius of the tube", "independent of the surface tension of the liquid"], "inversely proportional to the radius of the tube",
      "From h = 2T cos(theta)/(r(rho)g), the capillary rise h is inversely proportional to the tube's radius r, so narrower tubes produce a greater rise."),
  _q("A liquid of surface tension 0.07 N/m rises in a capillary tube of radius 0.0005 m. Given (rho) = 1000 kg/m3, g = 10 m/s2, and the liquid wets the tube completely (cos theta = 1), what is the height of rise?",
      ["0.028 m", "0.28 m", "0.0028 m", "2.8 m"], "0.028 m",
      "h = 2T cos(theta)/(r(rho)g) = (2 x 0.07 x 1)/(0.0005 x 1000 x 10) = 0.14/5 = 0.028 m (2.8 cm)."),
  _q("Liquid drops tend to form a spherical shape mainly because",
      ["surface tension acts to minimise the surface area for a given volume, and a sphere has the least surface area for its volume", "gravity pulls all liquids into spherical shapes", "spherical shapes have the greatest surface area for a given volume", "liquids have no viscosity"], "surface tension acts to minimise the surface area for a given volume, and a sphere has the least surface area for its volume",
      "Since surface tension tends to shrink the surface to the smallest possible area, and a sphere encloses a given volume with the least surface area of any shape, small drops become spherical."),
  _q("According to Newton's law of viscous flow, the viscous force between adjacent layers of a fluid depends on the",
      ["velocity gradient between the layers, the area of contact, and the fluid's coefficient of viscosity", "temperature of the fluid alone", "colour of the fluid", "atmospheric pressure alone"], "velocity gradient between the layers, the area of contact, and the fluid's coefficient of viscosity",
      "Newton's law of viscous flow gives the viscous (drag) force as proportional to the coefficient of viscosity, the contact area, and the velocity gradient (rate of change of velocity) between adjacent fluid layers."),
  _q("Terminal velocity is the constant maximum velocity attained by a body falling through a fluid when",
      ["the net force on it becomes zero, as the upward drag and upthrust balance its weight", "the body stops accelerating due to running out of gravitational pull", "the fluid becomes completely frictionless", "the body's mass increases to infinity"], "the net force on it becomes zero, as the upward drag and upthrust balance its weight",
      "As speed increases, viscous drag increases until, together with the upthrust, it exactly balances the body's weight; from that point the body falls at a constant (terminal) velocity with zero acceleration."),
  _q("Stokes' Law gives the viscous drag force on a small sphere moving through a fluid as being proportional to the",
      ["coefficient of viscosity of the fluid, the radius of the sphere, and its velocity", "square of the radius of the sphere only", "density of the sphere only", "cross-sectional area of the sphere only, independent of velocity"], "coefficient of viscosity of the fluid, the radius of the sphere, and its velocity",
      "Stokes' Law states F = 6(pi)(eta)rv, where (eta) is the fluid's coefficient of viscosity, r is the sphere's radius, and v is its velocity through the fluid."),
  _q("A small steel ball falling through a viscous liquid eventually moves at a constant velocity. This occurs because",
      ["the increasing viscous drag has grown to balance the ball's weight minus the upthrust on it", "the ball has stopped experiencing gravity", "the liquid's viscosity has dropped to zero", "the ball's weight has increased to match the drag force"], "the increasing viscous drag has grown to balance the ball's weight minus the upthrust on it",
      "As the ball speeds up, viscous drag (which increases with speed) grows until, combined with the upthrust, it equals the ball's weight, giving zero net force and hence constant (terminal) velocity."),
];

final _temperatureMeasurement = [
  _q("A thermometric property is a physical property that",
      ["varies continuously and uniformly with temperature, and can be measured", "remains constant regardless of temperature", "only changes at the boiling point of a substance", "cannot be measured accurately"], "varies continuously and uniformly with temperature, and can be measured",
      "Thermometers rely on thermometric properties, such as the length of a mercury column or the resistance of a wire, which change measurably and consistently with temperature."),
  _q("The lower and upper fixed points used in calibrating a mercury-in-glass thermometer are respectively the",
      ["ice point (0 degC) and steam point (100 degC)", "boiling point of mercury and freezing point of water", "room temperature and body temperature", "absolute zero and the steam point"], "ice point (0 degC) and steam point (100 degC)",
      "The ice point (melting point of pure ice at standard pressure, 0 degC) and steam point (boiling point of water at standard pressure, 100 degC) are the standard fixed points on the Celsius scale."),
  _q("What is 25 degrees Celsius expressed in Kelvin?",
      ["298 K", "273 K", "25 K", "248 K"], "298 K",
      "K = degC + 273, so 25 degC = 25 + 273 = 298 K."),
  _q("What is 350 K expressed in degrees Celsius?",
      ["77 degC", "623 degC", "350 degC", "77 K"], "77 degC",
      "degC = K - 273, so 350 K = 350 - 273 = 77 degC."),
  _q("What is 40 degrees Celsius expressed in degrees Fahrenheit, using F = (9/5)C + 32?",
      ["104 degF", "72 degF", "40 degF", "212 degF"], "104 degF",
      "F = (9/5)(40) + 32 = 72 + 32 = 104 degF."),
  _q("A clinical thermometer is designed with a narrow range (around 35 to 42 degC) and a constriction near the bulb mainly to",
      ["allow accurate measurement of body temperature and prevent the mercury from receding before it is read", "measure very high industrial temperatures", "measure extremely low temperatures accurately", "eliminate the need for calibration"], "allow accurate measurement of body temperature and prevent the mercury from receding before it is read",
      "The narrow range gives fine precision around body temperature, while the constriction stops the mercury thread from flowing back into the bulb immediately after removal, allowing the reading to be taken afterward."),
];

final _thermalExpansion = [
  _q("The linear expansivity of a solid is defined as the",
      ["increase in length per unit original length per degree rise in temperature", "total increase in length regardless of original length", "increase in volume per unit original volume per degree rise in temperature", "increase in area per unit original area per degree rise in temperature"], "increase in length per unit original length per degree rise in temperature",
      "Linear expansivity (alpha) = increase in length / (original length x temperature rise), describing how much a material's length changes per degree per unit length."),
  _q("A metal rod of length 2 m has a linear expansivity of 12 x 10^-6 /K. What is its increase in length when heated through 50 K?",
      ["1.2 x 10^-3 m", "1.2 x 10^-2 m", "1.2 x 10^-4 m", "12 x 10^-6 m"], "1.2 x 10^-3 m",
      "Expansion = L x alpha x (temperature rise) = 2 x (12 x 10^-6) x 50 = 1200 x 10^-6 = 1.2 x 10^-3 m."),
  _q("For a given material, the area (superficial) expansivity is approximately",
      ["twice the linear expansivity", "three times the linear expansivity", "equal to the linear expansivity", "half the linear expansivity"], "twice the linear expansivity",
      "Since area involves two dimensions, the area expansivity (beta) is approximately 2(alpha), where alpha is the linear expansivity."),
  _q("For a given material, the volume (cubic) expansivity is approximately",
      ["three times the linear expansivity", "twice the linear expansivity", "equal to the linear expansivity", "four times the linear expansivity"], "three times the linear expansivity",
      "Since volume involves three dimensions, the cubic (volume) expansivity (gamma) is approximately 3(alpha), where alpha is the linear expansivity."),
  _q("The anomalous expansion of water refers to the fact that water",
      ["contracts when heated from 0 degC to 4 degC, and expands above 4 degC, with maximum density at 4 degC", "expands continuously as it is heated from 0 degC upwards", "contracts continuously as it is heated from 0 degC upwards", "has the same density at all temperatures"], "contracts when heated from 0 degC to 4 degC, and expands above 4 degC, with maximum density at 4 degC",
      "Unlike most substances, water shows unusual (anomalous) behaviour: as it is warmed from 0 degC, it first contracts until 4 degC (its point of maximum density), then expands normally above 4 degC."),
  _q("The anomalous expansion of water is significant in nature because it",
      ["causes ice to float and allows ponds to freeze from the top, letting aquatic life survive underneath", "causes all water bodies to freeze completely solid in cold weather", "prevents any ice from ever forming on water surfaces", "makes water boil at a lower temperature at high altitude"], "causes ice to float and allows ponds to freeze from the top, letting aquatic life survive underneath",
      "Because water at 4 degC is denser than ice or colder water, ice forms and floats at the surface, insulating the water below and allowing aquatic organisms to survive through winter."),
];

final _gasLaws = [
  _q("The ideal (general) gas equation relating pressure, volume, and temperature of a fixed mass of gas is",
      ["PV = nRT", "P + V = nRT", "PV = nR/T", "P/V = nRT"], "PV = nRT",
      "The ideal gas equation PV = nRT combines Boyle's, Charles's, and the Pressure Law, relating pressure (P), volume (V), number of moles (n), the molar gas constant (R), and absolute temperature (T)."),
  _q("A fixed mass of gas at constant temperature has a pressure of 100 kPa and volume of 2 m^3. If the volume is reduced to 0.5 m^3, what is the new pressure (Boyle's Law)?",
      ["400 kPa", "25 kPa", "200 kPa", "50 kPa"], "400 kPa",
      "By Boyle's Law, P1V1 = P2V2: P2 = P1V1/V2 = (100 x 2)/0.5 = 200/0.5 = 400 kPa."),
  _q("A fixed mass of gas at constant pressure occupies 2 litres at 300 K. What volume will it occupy at 600 K (Charles's Law)?",
      ["4 litres", "1 litre", "2 litres", "6 litres"], "4 litres",
      "By Charles's Law, V1/T1 = V2/T2: V2 = V1T2/T1 = (2 x 600)/300 = 1200/300 = 4 litres."),
  _q("A fixed mass of gas has pressure 100 kPa, volume 3 litres and temperature 250 K. It is changed to pressure 150 kPa and temperature 300 K. What is its new volume?",
      ["2.4 litres", "3.6 litres", "1.5 litres", "4.5 litres"], "2.4 litres",
      "Using the general gas equation P1V1/T1 = P2V2/T2: V2 = (P1V1T2)/(T1P2) = (100 x 3 x 300)/(250 x 150) = 90000/37500 = 2.4 litres."),
  _q("According to the kinetic theory of gases, the pressure exerted by a gas on the walls of its container is due to",
      ["the continuous collisions of rapidly and randomly moving gas molecules with the walls", "the weight of the gas molecules pressing down on the walls", "chemical reactions between gas molecules and the container", "the gas molecules being permanently attached to the walls"], "the continuous collisions of rapidly and randomly moving gas molecules with the walls",
      "Kinetic theory explains gas pressure as the cumulative effect of a huge number of molecules in random motion continually colliding with and rebounding off the container's walls."),
  _q("According to the kinetic theory of gases, at absolute zero (0 K, or -273 degC), the gas molecules would have",
      ["minimum (theoretically zero) kinetic energy", "maximum kinetic energy", "the same kinetic energy as at room temperature", "infinite kinetic energy"], "minimum (theoretically zero) kinetic energy",
      "Absolute zero is the theoretical temperature at which the random translational kinetic energy of gas molecules would fall to a minimum (ideally zero), which is why 0 K represents the lowest possible temperature."),
];

final _quantityOfHeat = [
  _q("The heat capacity of a body is defined as the quantity of heat needed to raise the temperature of",
      ["the whole body by one degree (Celsius or Kelvin)", "a unit mass of the body by one degree", "the body to its melting point", "a unit volume of the body by ten degrees"], "the whole body by one degree (Celsius or Kelvin)",
      "Heat capacity (C) applies to a specific object as a whole, unlike specific heat capacity, which is defined per unit mass of a substance."),
  _q("Specific heat capacity of a substance is defined as the quantity of heat required to raise the temperature of",
      ["a unit mass of the substance by one degree (Celsius or Kelvin)", "the whole substance by any amount", "one mole of the substance to its boiling point", "a unit volume of the substance by one degree"], "a unit mass of the substance by one degree (Celsius or Kelvin)",
      "Specific heat capacity (c) is defined by Q = mc(delta)theta, representing the heat needed per unit mass per degree temperature change."),
  _q("How much heat is required to raise the temperature of 0.5 kg of water by 20 degC? (Specific heat capacity of water = 4200 J/kgK)",
      ["42000 J", "4200 J", "21000 J", "8400 J"], "42000 J",
      "Q = mc(delta)theta = 0.5 x 4200 x 20 = 42000 J."),
  _q("The method of mixtures used in calorimetry is based on the principle that, assuming no heat is lost to the surroundings,",
      ["heat lost by the hotter body equals heat gained by the colder body", "heat lost always exceeds heat gained", "heat gained always exceeds heat lost", "the final temperature always equals the average of the initial temperatures regardless of mass"], "heat lost by the hotter body equals heat gained by the colder body",
      "In an ideal (insulated) mixing process, energy conservation demands that all the heat given out by the hotter substance as it cools is absorbed by the colder substance as it warms, until they reach a common final temperature."),
  _q("200 g of water at 80 degC is mixed with 300 g of water at 20 degC. Assuming no heat loss, what is the final temperature of the mixture?",
      ["44 degC", "50 degC", "40 degC", "60 degC"], "44 degC",
      "Heat lost by hot water = heat gained by cold water: 0.2(80 - Tf) = 0.3(Tf - 20). This gives 16 - 0.2Tf = 0.3Tf - 6, so 22 = 0.5Tf, and Tf = 44 degC."),
  _q("The latent heat of fusion of a substance is the quantity of heat required to change it from",
      ["solid to liquid at constant temperature", "liquid to gas at constant temperature", "solid directly to gas", "one temperature to another without changing state"], "solid to liquid at constant temperature",
      "Latent heat of fusion is absorbed during melting (solid to liquid) at the melting point, without any accompanying change in temperature, since the energy overcomes intermolecular bonds rather than raising kinetic energy."),
  _q("How much heat is needed to melt 0.1 kg of ice at 0 degC, given the specific latent heat of fusion of ice is 336000 J/kg?",
      ["33600 J", "3360 J", "336000 J", "3600 J"], "33600 J",
      "Q = mL = 0.1 x 336000 = 33600 J."),
  _q("The latent heat of vaporisation of a substance differs from its latent heat of fusion in that it is the heat required to change the substance from",
      ["liquid to gas (vapour) at constant temperature, rather than solid to liquid", "solid to liquid at constant temperature, rather than liquid to gas", "gas to solid directly", "one solid phase to another solid phase"], "liquid to gas (vapour) at constant temperature, rather than solid to liquid",
      "Latent heat of vaporisation is absorbed as a liquid changes to vapour at its boiling point at constant temperature, while latent heat of fusion applies to the solid-to-liquid change at the melting point."),
];

final _heatTransfer = [
  _q("Conduction is the mode of heat transfer in which heat travels through a material mainly by",
      ["direct molecular/particle vibration and collision, without bulk movement of the material", "the bulk movement of heated particles from one place to another", "electromagnetic waves requiring no medium", "the evaporation of the material"], "direct molecular/particle vibration and collision, without bulk movement of the material",
      "In conduction, heat energy passes from particle to particle through vibration and collision (and, in metals, free electron movement), without any overall movement of the material itself, and is most effective in solids."),
  _q("Convection is the mode of heat transfer that occurs mainly in liquids and gases, through",
      ["the actual bulk movement of the heated fluid particles", "direct particle-to-particle collision without movement", "electromagnetic radiation", "the conduction of heat along a solid rod"], "the actual bulk movement of the heated fluid particles",
      "Convection relies on heated fluid becoming less dense, rising, and being replaced by cooler, denser fluid, setting up convection currents that carry thermal energy through the bulk movement of the fluid."),
  _q("A sea breeze, which blows from the sea towards the land during the day, occurs because",
      ["land heats up faster than the sea, so warm air over land rises and cooler air from the sea flows in to replace it", "the sea heats up faster than the land during the day", "the wind always blows towards the sea during the day", "there is no temperature difference between land and sea during the day"], "land heats up faster than the sea, so warm air over land rises and cooler air from the sea flows in to replace it",
      "Land has a lower specific heat capacity than water, so it warms faster in sunlight; the warmed air above it rises, and cooler air from over the sea moves in to take its place, creating a sea breeze."),
  _q("A land breeze, which blows from the land towards the sea at night, occurs because",
      ["land cools faster than the sea at night, so air over the sea remains warmer and rises, drawing cooler air from the land", "the land remains warmer than the sea throughout the night", "the sea cools faster than the land at night", "convection currents cease completely at night"], "land cools faster than the sea at night, so air over the sea remains warmer and rises, drawing cooler air from the land",
      "At night the land loses heat faster than the sea (again due to its lower specific heat capacity), so the relatively warmer air over the sea rises and cooler air flows from the land to replace it, creating a land breeze."),
  _q("Radiation, as a mode of heat transfer, differs from conduction and convection in that it",
      ["can travel through a vacuum without requiring any material medium", "requires direct contact between particles of a medium", "only occurs in solids", "always requires the bulk movement of a fluid"], "can travel through a vacuum without requiring any material medium",
      "Radiation transfers heat via electromagnetic waves, which can travel through empty space, unlike conduction and convection, which both require a material medium."),
  _q("According to Prevost's theory of heat exchange, a black body is one that",
      ["is a perfect absorber and a perfect emitter of thermal radiation, and all bodies continuously emit and absorb radiation depending on temperature", "reflects all incident thermal radiation and absorbs none", "only absorbs radiation but never emits it", "only emits radiation when it is heated above its own temperature by an external source"], "is a perfect absorber and a perfect emitter of thermal radiation, and all bodies continuously emit and absorb radiation depending on temperature",
      "Prevost's theory states that all bodies constantly emit and absorb thermal radiation regardless of their surroundings' temperature; a black body is the idealised perfect absorber and emitter, with net heat exchange depending on the temperature difference between bodies."),
];
