import "../quiz_question.dart";

const _subject = "Hausa";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// WAEC Hausa question bank covering the full syllabus: A'a da Sauti
/// (Phonology), Tsarin Kalmomi da Nahawu (Morphology/Syntax/Translation),
/// Tsarin Rubutu (Composition & Comprehension), Al'ada da Zamantakewa
/// (Culture & Customs), and Adabin Hausa (Literature). Weighted toward
/// well-established phonology, grammar-category, culture, and
/// literary-history facts rather than fine-grained native-speaker
/// judgement calls.
List<QuizQuestion> buildWaecHausaQuestions() {
  return [
    ..._aaDaSauti,
    ..._nahawuDaTsarinKalma,
    ..._tsarinRubutu,
    ..._aladaDaZamantakewa,
    ..._adabinHausa,
  ];
}

final _aaDaSauti = [
  _q("Menene ake nufi da 'bakake' (consonants) a fannin ilimin sauti na Hausa?",
      ["Sautukan da ake fadarwa ta hanyar toshe ko taƙaita iska a wani sashe na baki", "Sautukan da ke fitowa ba tare da toshewar iska ba", "Alamomin rubutu kawai", "Karin waƙa"], "Sautukan da ake fadarwa ta hanyar toshe ko taƙaita iska a wani sashe na baki",
      "Consonants (bakake) are speech sounds produced by obstructing or restricting the airflow at some point in the vocal tract, unlike vowels which flow freely."),
  _q("Menene ake nufi da 'wasali' (vowels) a fannin ilimin sauti na Hausa?",
      ["Sautukan da ake fadarwa ba tare da toshewar iska ba a baki", "Sautukan da ake toshe iska gaba daya", "Haruffan da ake amfani da su domin rubutun lambobi", "Alamar tambaya a jimla"], "Sautukan da ake fadarwa ba tare da toshewar iska ba a baki",
      "Vowels (wasali) are speech sounds produced with a free, unobstructed flow of air through the vocal tract, unlike consonants."),
  _q("A Hausa, wasula na iya zama gajeru ko",
      ["dogaye", "kaifi", "lankwasa", "tagwaye kadai"], "dogaye",
      "Hausa vowels are distinguished by length, being either short (gajeru) or long (dogaye), a distinction that can change a word's meaning."),
  _q("Menene ake kira hadewar haruffa biyu domin wakiltar sauti daya, kamar 'sh' ko 'ky', a Hausa?",
      ["Tagwayen bakake (digraphs)", "Wasali dogo", "Karin sauti", "Gaba mai rufi"], "Tagwayen bakake (digraphs)",
      "Digraphs (tagwayen bakake) are combinations of two letters, such as 'sh', 'ts', 'gy', 'ky', and 'kw', used to represent single distinct sounds in Hausa."),
  _q("Menene ake kira sauyin sautin murya wanda ke nuna bambanci a ma'anar kalmomi iri daya a rubuce, a Hausa?",
      ["Karin sauti (tone)", "Wasali", "Bakake", "Gaɓa"], "Karin sauti (tone)",
      "Tone (karin sauti) is the pitch pattern of a syllable, and in Hausa it can distinguish between words that are otherwise spelled identically."),
  _q("Wadanne irin karin sauti ne ake samu a Hausa?",
      ["Sama (high), kasa (low), da fadowa (falling)", "Sama kadai", "Kasa kadai", "Fadowa kadai"], "Sama (high), kasa (low), da fadowa (falling)",
      "Hausa tone system generally recognises three tonal categories: high, low, and falling tones, which can change word meaning."),
  _q("Menene ake kira daidaituwar wasula a cikin kalma guda, inda wasu wasula ke shafar yadda ake furta wasu, a Hausa?",
      ["Cakuɗar wasali (vowel harmony)", "Karin sauti", "Tagwayen bakake", "Gaɓa mai rufi"], "Cakuɗar wasali (vowel harmony)",
      "Vowel harmony (cakuɗar wasali) refers to a phonological pattern where certain vowels within a word influence or agree with each other in quality."),
  _q("Menene ake kira sashin sauti wanda ke dauke da wasali guda daya ko fiye, wanda shine tubalin da ake gina kalmomi da su?",
      ["Gaɓa (syllable)", "Bakin murya", "Karin waƙa", "Alamar rubutu"], "Gaɓa (syllable)",
      "A syllable (gaɓa) is a unit of sound built around a vowel, serving as the fundamental building block of spoken words."),
  _q("Gaɓa mai buɗewa (open syllable) a Hausa yakan kare da",
      ["wasali", "baƙi biyu a jere", "alamar tambaya", "sirara (apostrophe)"], "wasali",
      "An open syllable (buɗaddiya) ends in a vowel sound, unlike a closed syllable which ends in a consonant."),
  _q("Gaɓa mai rufewa (closed syllable) a Hausa yakan kare da",
      ["baƙi (consonant)", "wasali kadai", "karin sauti kadai", "sirara"], "baƙi (consonant)",
      "A closed syllable (rufakkiya) ends in a consonant sound, in contrast to an open syllable which ends in a vowel."),
  _q("Wane baƙi ne ke wakiltar sautin da ake fadarwa ta hanyar toshe iska sannan a saki shi kwatsam da karfi na musamman (implosive), kamar 'ɓ'?",
      ["Ɓ (hooked b)", "S", "M", "R"], "Ɓ (hooked b)",
      "The hooked letter Ɓ represents an implosive consonant sound, distinct in articulation from the plain (unhooked) B."),
  _q("Wane baƙi ne ke wakiltar sautin implosive/ejective da aka rubuta da lankwasa a karkashinsa, kamar 'ɗ'?",
      ["Ɗ (hooked d)", "T", "N", "L"], "Ɗ (hooked d)",
      "The hooked letter Ɗ represents a distinct implosive consonant sound, separate from the plain D used elsewhere in the alphabet."),
  _q("Wane baƙi ne ke wakiltar sautin ejective da aka rubuta da lankwasa, kamar 'ƙ'?",
      ["Ƙ (hooked k)", "K (plain)", "G", "H"], "Ƙ (hooked k)",
      "The hooked letter Ƙ represents an ejective consonant sound, distinct from the plain K in standard Hausa orthography."),
  _q("Menene ake kira sautin da ake fadarwa ta hanyar goge sassan baki tare, kamar 's' da 'z'?",
      ["Sautin gogewa (fricative)", "Sautin toshewa (plosive)", "Sautin hanci (nasal)", "Wasali"], "Sautin gogewa (fricative)",
      "Fricative sounds are produced by forcing air through a narrow channel, creating friction, as with sounds like 's' and 'z'."),
  _q("Menene ake kira sautin da ake fadarwa ta hanci, kamar 'm' da 'n'?",
      ["Sautin hanci (nasal)", "Sautin gogewa", "Sautin toshewa", "Wasali dogo"], "Sautin hanci (nasal)",
      "Nasal sounds, such as 'm' and 'n', are produced with air passing through the nose rather than solely through the mouth."),
  _q("A ilimin sauti, ana amfani da menene domin nazarin yadda ake fadar sauti ta bakin dan'adam?",
      ["Ilimin fonetik/fonoloji (phonetics/phonology)", "Ilimin lissafi", "Ilimin siyasa", "Ilimin tattalin arziki"], "Ilimin fonetik/fonoloji (phonetics/phonology)",
      "Phonetics and phonology are the branches of linguistics dedicated to studying how speech sounds are produced, transmitted, and structured within a language."),
  _q("Wasali dogo a rubutun Hausa ana nuna shi ta hanyar",
      ["ninka wasalin, misali 'aa' ko amfani da alamar dogewa", "amfani da baƙi biyu a jere kawai", "amfani da alamar tambaya", "rage wasalin gaba daya"], "ninka wasalin, misali 'aa' ko amfani da alamar dogewa",
      "Long vowels in Hausa are typically indicated by doubling the vowel letter or using a length mark, distinguishing them from short vowels."),
  _q("Bambancin da ke tsakanin 'kudi' (money) da 'kudī' (a fadowar karin sauti misali) na iya nunawa ta hanyar",
      ["karin sauti (tone)", "yawan haruffa kawai", "launin rubutu", "girman rubutu"], "karin sauti (tone)",
      "In Hausa, tone differences alone can distinguish words that otherwise share the same consonant and vowel sequence."),
  _q("Menene ake kira nazarin yadda ake hada sautuka domin samar da kalmomi masu ma'ana a wani harshe?",
      ["Fonoloji (Phonology)", "Nahawu (Grammar/Syntax)", "Adabi (Literature)", "Tarihi (History)"], "Fonoloji (Phonology)",
      "Phonology is specifically concerned with the sound system of a language, including how sounds combine to form meaningful units."),
  _q("Wane bangare ne na ilimin sauti ke nazarin yadda ake fadar sautuka ta jiki (articulatory features)?",
      ["Fonetik (Phonetics)", "Nahawu", "Adabi", "Tarihi"], "Fonetik (Phonetics)",
      "Phonetics studies the physical production and articulation of speech sounds, complementing phonology's focus on sound patterns and systems."),
];

final _nahawuDaTsarinKalma = [
  _q("Wane azuzuwan kalma ne ke suna wa mutum, wuri, ko abu, a Hausa?",
      ["Suna (Noun)", "Aikatau (Verb)", "Sifa (Adjective)", "Bami (Preposition)"], "Suna (Noun)",
      "A noun (suna) is the part of speech used to name a person, place, thing, or idea."),
  _q("Wane azuzuwan kalma ne ke maye gurbin suna a cikin jimla, kamar 'shi', 'ita', 'su'?",
      ["Wakilin suna (Pronoun)", "Suna", "Aikatau", "Gami"], "Wakilin suna (Pronoun)",
      "A pronoun (wakilin suna) stands in place of a noun, such as 'he/him' (shi), 'she/her' (ita), or 'they/them' (su)."),
  _q("Wane azuzuwan kalma ne ke nuna aiki ko yanayi a jimla, kamar 'tafi', 'ci', 'zauna'?",
      ["Aikatau (Verb)", "Suna", "Sifa", "Bami"], "Aikatau (Verb)",
      "A verb (aikatau) expresses an action, occurrence, or state, forming the core of the predicate in a sentence."),
  _q("Wane azuzuwan kalma ne ke bayyana siffar suna, kamar 'mai kyau', 'baki', 'babba'?",
      ["Sifa (Adjective)", "Suna", "Aikatau", "Gami"], "Sifa (Adjective)",
      "An adjective (sifa) describes or modifies a noun, giving more information about its quality or characteristics."),
  _q("Wane azuzuwan kalma ne ke hada suna ko wakilin suna zuwa wani sashe na jimla, kamar 'a', 'da', 'kan'?",
      ["Bami (Preposition)", "Gami", "Aikatau", "Sifa"], "Bami (Preposition)",
      "A preposition (bami) links a noun or pronoun to another part of the sentence, showing relationships such as location, direction, or time."),
  _q("Wane azuzuwan kalma ne ke hada kalmomi ko jimloli biyu tare, kamar 'da', 'amma', 'ko'?",
      ["Gami (Conjunction)", "Bami", "Suna", "Aikatau"], "Gami (Conjunction)",
      "A conjunction (gami) joins words, phrases, or clauses together, such as 'and' (da), 'but' (amma), or 'or' (ko)."),
  _q("A Hausa, jinsin suna (gender) yakan kasu zuwa",
      ["namiji da mace", "tilas da jam'i kawai", "sama da kasa", "gajere da dogo"], "namiji da mace",
      "In Hausa grammar, noun gender is generally classified as masculine (namiji) or feminine (mace)."),
  _q("A Hausa, adadin suna (number) yakan kasu zuwa",
      ["tilas (singular) da jam'i (plural)", "namiji da mace kawai", "sama da kasa", "gajere da dogo"], "tilas (singular) da jam'i (plural)",
      "Number in Hausa nouns is classified as singular (tilas), referring to one, or plural (jam'i), referring to more than one."),
  _q("Menene ake nufi da 'shashen lokaci' (tense/aspect) na aikatau a Hausa?",
      ["Yadda ake nuna lokacin da aikin ya faru, ko na yau da kullum ne, ko na baya, ko na gaba", "Sunan wani wuri", "Sifar wani abu", "Alamar tambaya kawai"], "Yadda ake nuna lokacin da aikin ya faru, ko na yau da kullum ne, ko na baya, ko na gaba",
      "Tense/aspect marking on Hausa verbs indicates the timing and nature of an action, such as whether it is completed, ongoing, habitual, or yet to occur."),
  _q("Wace jimla ce ake kira 'sauƙaƙƙiyar jimla' (simple sentence) a Hausa?",
      ["Jimlar da ke da ma'ana daya kacal, mai fannin suna da aikatau guda daya", "Jimlar da ke da fannoni biyu ko fiye hade tare", "Jimlar da ba ta da ma'ana", "Jimlar da ke da tambaya kawai"], "Jimlar da ke da ma'ana daya kacal, mai fannin suna da aikatau guda daya",
      "A simple sentence (sauƙaƙƙiyar jimla) expresses a single complete thought, typically containing one subject and one main verb."),
  _q("Wace jimla ce ake kira 'sarƙaƙƙiyar jimla' (complex sentence) a Hausa?",
      ["Jimlar da ke da fannoni biyu ko fiye da suka hade don kammala ma'ana daya", "Jimlar da ke da kalma guda daya kacal", "Jimlar da ba ta da fi'ili", "Jimlar tambaya ce kawai"], "Jimlar da ke da fannoni biyu ko fiye da suka hade don kammala ma'ana daya",
      "A complex sentence (sarƙaƙƙiyar jimla) combines two or more clauses, often joined by a conjunction, to express a more elaborate idea."),
  _q("Menene ake kira aikin nazarin sassan jimla, kamar suna, aikatau, da sifa, domin fahimtar tsarinta?",
      ["Ja jimloli (Parsing)", "Fassara", "Rubuta waka", "Aunar fahimta"], "Ja jimloli (Parsing)",
      "Parsing (ja jimloli) involves breaking down a sentence into its grammatical components to analyse its structure and function."),
  _q("Menene manufar 'fassarar magana' (translation) tsakanin Hausa da Turanci a fannin karatun harshe?",
      ["Mayar da ma'anar jimla daga harshe daya zuwa wani, tare da adana ma'ana da kalmomin salo (karin magana)", "Rubuta jimla iri daya sau biyu a harshe guda", "Canza sautin murya kawai", "Kirga yawan haruffa a jimla"], "Mayar da ma'anar jimla daga harshe daya zuwa wani, tare da adana ma'ana da kalmomin salo (karin magana)",
      "Translation requires conveying the accurate meaning of a passage from one language to another, while preserving idiomatic expressions and context."),
  _q("Wane bangare ne na nahawu ke nazarin yadda ake gina kalmomi daga tushensu da karin kalmomi (morphemes)?",
      ["Ilimin ƙirar kalma (Morphology)", "Ilimin jimla (Syntax)", "Ilimin sauti (Phonology)", "Ilimin adabi (Literature)"], "Ilimin ƙirar kalma (Morphology)",
      "Morphology is the branch of grammar concerned with the internal structure of words, including roots, prefixes, and suffixes."),
  _q("Wane bangare ne na nahawu ke nazarin yadda ake tsara kalmomi domin gina jimloli masu ma'ana?",
      ["Ilimin jimla (Syntax)", "Ilimin ƙirar kalma", "Ilimin sauti", "Ilimin al'ada"], "Ilimin jimla (Syntax)",
      "Syntax is the branch of grammar dealing with sentence structure, including how words are arranged to form grammatically correct sentences."),
  _q("A jimlar Hausa, wane bangare ne ke bayyana wanda/menene jimlar take magana a kai (misali 'Musa')?",
      ["Fannin suna (Subject)", "Fannin aikatau kadai", "Fannin sifa", "Fannin bami"], "Fannin suna (Subject)",
      "The subject of a sentence identifies who or what the sentence is primarily about."),
  _q("A jimlar Hausa, wane bangare ne ke bayyana abinda ake fada game da suna/fannin suna?",
      ["Fannin fadi (Predicate)", "Fannin suna kadai", "Bami kadai", "Gami kadai"], "Fannin fadi (Predicate)",
      "The predicate provides information about the subject, typically including the verb and any related objects or complements."),
  _q("Menene ake kira karin magana da ake amfani da su domin isar da sako ta hanyar kwatanci ko dabara, wanda galibi ba za a iya fassara su kalma-da-kalma ba?",
      ["Karin magana (idioms/proverb-like expressions)", "Sunayen mutane kadai", "Alamomin rubutu", "Sifofi na yau da kullum"], "Karin magana (idioms/proverb-like expressions)",
      "Karin magana refers to idiomatic or figurative expressions whose meaning often cannot be understood from a literal, word-for-word translation."),
  _q("Wace kalma ce ta fi dacewa a matsayin 'aikatau' (verb) daga cikin wadannan?",
      ["Karanta", "Littafi", "Fari", "Da"], "Karanta",
      "'Karanta' (to read) expresses an action, making it a verb, unlike 'littafi' (book, a noun), 'fari' (white, an adjective), or 'da' (and/with, a conjunction/preposition)."),
  _q("Wace kalma ce ta fi dacewa a matsayin 'suna' (noun) daga cikin wadannan?",
      ["Makaranta", "Tafi", "Babba", "Ko"], "Makaranta",
      "'Makaranta' (school) names a place, making it a noun, unlike 'tafi' (go, a verb), 'babba' (big, an adjective), or 'ko' (or, a conjunction)."),
  _q("A tsarin jinsi na Hausa, kalmar 'yarinya' tana wakiltar jinsin",
      ["mace (feminine)", "namiji (masculine)", "jam'i kawai", "tilas kawai"], "mace (feminine)",
      "'Yarinya' (girl) refers to a female, placing it within the feminine gender category in Hausa noun classification."),
  _q("A tsarin adadi na Hausa, kalmar 'yara' (jam'i na 'yaro') tana nuna",
      ["jam'i (plural)", "tilas (singular)", "namiji kawai", "mace kawai"], "jam'i (plural)",
      "'Yara' is the plural form of 'yaro' (child/boy), indicating more than one, unlike the singular 'tilas' form."),
  _q("Menene ake kira kalmar da ke nuna inda ake ko lokacin da wani abu ya faru, misali 'nan', 'can', 'yau'?",
      ["Bami/madogara na wuri ko lokaci (adverbial-type words)", "Aikatau kadai", "Sifa kadai", "Gami kadai"], "Bami/madogara na wuri ko lokaci (adverbial-type words)",
      "Words indicating place or time, such as 'nan' (here), 'can' (there), or 'yau' (today), function to locate an action in space or time within a sentence."),
  _q("Menene ake kira karin kalma da ake dorawa a gaban tushen kalma domin canza ma'anarta, a fannin kirar kalma?",
      ["Kari na gaba (prefix)", "Kari na baya (suffix) kawai", "Tushen kalma kadai", "Gami kadai"], "Kari na gaba (prefix)",
      "A prefix is a morpheme attached to the beginning of a word's root, modifying or extending its meaning."),
  _q("Menene ake kira karin kalma da ake dorawa a bayan tushen kalma domin canza ma'anarta ko aikinta a jimla?",
      ["Kari na baya (suffix)", "Kari na gaba kawai", "Tushen kalma kadai", "Bami kadai"], "Kari na baya (suffix)",
      "A suffix is a morpheme attached to the end of a word's root, often changing its grammatical function or meaning."),
];

final _tsarinRubutu = [
  _q("Wace irin rubutu ake kira 'insha'i' a fannin rubutun Hausa?",
      ["Rubutun kirkire-kirkire, kamar wasika, muhawara, labari, ko bayani", "Nazarin harshe kadai", "Waka kadai", "Tarihin al'umma kadai"], "Rubutun kirkire-kirkire, kamar wasika, muhawara, labari, ko bayani",
      "Insha'i refers to creative or composition writing, encompassing letters, argumentative essays, narratives, and descriptive pieces."),
  _q("Wace irin wasika ce ake kira 'wasikar aiki' (formal letter)?",
      ["Wasikar da ake rubutawa zuwa ga hukuma ko wata sana'a, cikin tsari na yau da kullum", "Wasikar da ake rubutawa ga aboki na kusa cikin salon zumunci", "Wasikar da ba ta da adireshi", "Wasikar da ba a rubuta ta ba"], "Wasikar da ake rubutawa zuwa ga hukuma ko wata sana'a, cikin tsari na yau da kullum",
      "A formal letter (wasikar aiki) is written to an official, institution, or business, following a structured, professional format."),
  _q("Wace irin wasika ce ake kira wasika ta zumunci (informal letter)?",
      ["Wasikar da ake rubutawa ga aboki ko dan uwa cikin salon sada zumunci", "Wasikar aiki zuwa hukuma", "Rahoton kudi", "Takardar shaida"], "Wasikar da ake rubutawa ga aboki ko dan uwa cikin salon sada zumunci",
      "An informal letter is written to a friend or family member in a warm, familiar tone, distinct from the professional style of a formal letter."),
  _q("Menene ake kira rubutun da ake gabatar da hujjoji domin kare wani ra'ayi, wanda galibi ake kira 'muhawara'?",
      ["Rubutun muhawara (argumentative essay)", "Rubutun labari (narrative essay)", "Rubutun bayani kadai", "Wasika kadai"], "Rubutun muhawara (argumentative essay)",
      "An argumentative essay (muhawara) presents reasoned arguments to support or oppose a particular viewpoint on a topic."),
  _q("Menene ake kira rubutun da ke ba da labarin abin da ya faru, tare da tsari na farko, tsakiya, da karshe?",
      ["Rubutun labari (narrative essay)", "Rubutun muhawara", "Wasika kadai", "Bayanin kalmomi kadai"], "Rubutun labari (narrative essay)",
      "A narrative essay (labari) tells a story of events, typically organised with a beginning, middle, and end."),
  _q("Menene ake kira rubutun da ke bayyana wani abu, wuri, ko mutum ta hanyar amfani da cikakkun bayanai masu ban sha'awa?",
      ["Rubutun bayani (descriptive essay)", "Rubutun muhawara", "Wasika kadai", "Fassara kadai"], "Rubutun bayani (descriptive essay)",
      "A descriptive essay (bayani) uses vivid, detailed language to portray a person, place, or object clearly to the reader."),
  _q("Yawan kalmomin da ake bukata a mafi karanci wajen rubutun insha'i na WAEC shine kusan",
      ["kalmomi 300 ko sama da haka", "kalmomi 10 zuwa 20", "kalmomi 1000 ko sama da haka", "kalmomi 5 kacal"], "kalmomi 300 ko sama da haka",
      "WAEC composition essays are typically expected to be at least around 300 words to adequately develop the topic."),
  _q("A rubutun Hausa, ka'idojin rubutu (ka'idojin rubutun Hausa) sun hada da",
      ["daidaiton haruffa, rabon kalmomi, da alamomin rubutu", "kalar takarda kadai", "girman hannun rubutu kadai", "farashin littafi"], "daidaiton haruffa, rabon kalmomi, da alamomin rubutu",
      "Standard Hausa orthography rules cover correct letter usage, proper word division, and appropriate punctuation."),
  _q("Menene ake kira aikin fahimtar rubutu domin cire manyan bayanai daga wani sashe na labari?",
      ["Auna fahimta (comprehension)", "Ja jimloli", "Fassara", "Karin magana"], "Auna fahimta (comprehension)",
      "Comprehension (auna fahimta) involves reading a passage carefully to extract main points, ideas, and important details."),
  _q("A auna fahimta, menene ake nufi da 'ma'anar kalmomi bisa yanayin magana' (contextual vocabulary)?",
      ["Fahimtar ma'anar kalma bisa yadda aka yi amfani da ita a cikin jimla ko sakin layi", "Fassara kalma zuwa Turanci kai tsaye kawai", "Kirga adadin haruffan kalma", "Nemo kalmar a kamus kawai ba tare da la'akari da rubutun ba"], "Fahimtar ma'anar kalma bisa yadda aka yi amfani da ita a cikin jimla ko sakin layi",
      "Contextual vocabulary understanding requires interpreting a word's meaning based on how it is used within its surrounding sentence or passage, rather than a fixed dictionary definition alone."),
  _q("Menene ake kira amfani da kalmomi ko jimloli masu ma'ana wadda ba ta zahiri ba, don kwatanci ko ban mamaki, a cikin rubutu?",
      ["Amfani da alamomin magana (figurative usage)", "Amfani da lambobi kadai", "Amfani da suna kadai", "Rashin amfani da alamomin rubutu"], "Amfani da alamomin magana (figurative usage)",
      "Figurative usage involves using words or expressions beyond their literal meaning, often for comparison, emphasis, or artistic effect."),
  _q("Menene mataki na farko da ya kamata dalibi ya dauka kafin ya fara rubuta insha'i?",
      ["Tsara tunani da fahimtar batun da za a rubuta a kai", "Rubuta kai tsaye ba tare da tsari ba", "Mantawa da batun gaba daya", "Kwafi rubutun wani dalibi"], "Tsara tunani da fahimtar batun da za a rubuta a kai",
      "Before writing an essay, it is advisable to plan and organise one's thoughts, ensuring a clear understanding of the topic and structure to be followed."),
  _q("A rubuta wasikar aiki, menene ya kamata a rubuta a farkon wasikar, kafin sunan mai karba?",
      ["Adireshin marubuci da ranar da aka rubuta wasikar", "Sa hannun mai karba kadai", "Karshen wasikar", "Taken littafi"], "Adireshin marubuci da ranar da aka rubuta wasikar",
      "A formal letter conventionally begins with the sender's address and the date, before proceeding to the recipient's details and the letter's body."),
  _q("A rubutun labari, menene ake kira sashen da ke kawo karshen labarin, inda ake warware matsalar da aka gabatar?",
      ["Kammalawa (conclusion/resolution)", "Gabatarwa (introduction) kadai", "Jigo kadai", "Take kadai"], "Kammalawa (conclusion/resolution)",
      "The conclusion (kammalawa) of a narrative resolves the central conflict or situation established earlier in the story."),
  _q("A rubutun muhawara, menene ya kamata marubuci ya yi domin karfafa ra'ayinsa?",
      ["Bayar da dalilai da misalai masu goyon bayan ra'ayinsa", "Kaucewa fadin kowane dalili", "Rubuta jimloli marasa alaka da batun", "Yin watsi da duk wata shaida"], "Bayar da dalilai da misalai masu goyon bayan ra'ayinsa",
      "An effective argumentative essay presents clear reasons and relevant examples to support and strengthen the writer's position on a topic."),
  _q("Menene ake kira nazarin da ake yi domin gano manufar marubuci a cikin wani rubutu?",
      ["Nazarin manufar marubuci (author's intention)", "Kirga haruffa", "Auna girman takarda", "Nazarin launin rubutu"], "Nazarin manufar marubuci (author's intention)",
      "Analysing the author's intention involves considering the purpose behind the text and the message the writer aims to convey."),
  _q("A auna fahimta, menene ake nufi da 'taken labari' (title/main idea)?",
      ["Babbar manufa ko batun da rubutun ya fi mayar da hankali a kai", "Adadin kalmomin da ke cikin rubutun", "Sunan marubuci kadai", "Ranar da aka buga littafin"], "Babbar manufa ko batun da rubutun ya fi mayar da hankali a kai",
      "The main idea or theme of a passage represents its central focus, the primary point the text seeks to communicate to the reader."),
  _q("Menene ya kamata dalibi ya yi bayan kammala rubuta insha'i, kafin ya mika shi?",
      ["Sake dubawa domin gyara kurakuran nahawu da rubutu", "Mika shi nan take ba tare da bitar sa ba", "Share duk abinda aka rubuta", "Kwafi rubutun wani dalibi"], "Sake dubawa domin gyara kurakuran nahawu da rubutu",
      "Reviewing one's work before submission helps identify and correct grammatical errors, spelling mistakes, and improve overall clarity."),
  _q("A wasikar zumunci, wace kalma ce ta fi dacewa a matsayin gaisuwar bude wasika ga aboki?",
      ["Sannu da zuwa/Yaya kake, aboki na?", "Mun karbi wasikarku a ofis", "Da fatan za a amsa mana nan da nan", "Sanarwa ga jama'a"], "Sannu da zuwa/Yaya kake, aboki na?",
      "Informal letters to friends typically open with warm, familiar greetings, distinct from the formal openings used in official correspondence."),
  _q("Menene ake kira jerin kalmomin da ke bayyana yadda abubuwa suka faru bisa tsari, misali 'da farko', 'sannan', 'a karshe'?",
      ["Kalmomin hadewa (transitional/connecting words)", "Sifofi kadai", "Sunayen mutane kadai", "Alamomin tambaya kadai"], "Kalmomin hadewa (transitional/connecting words)",
      "Connecting words like 'da farko' (first), 'sannan' (then), and 'a karshe' (finally) help organise ideas in a clear, logical sequence within a composition."),
];

final _aladaDaZamantakewa = [
  _q("Menene ake kira bikin da ake yi domin bayar da suna ga jariri a al'adar Hausawa?",
      ["Suna (naming ceremony)", "Aure", "Jana'iza", "Sallah"], "Suna (naming ceremony)",
      "The naming ceremony (suna) is a traditional Hausa rite performed to formally give a name to a newborn baby, typically on the seventh day."),
  _q("A al'adar Hausawa, menene 'aure' ke nunawa?",
      ["Tsarin neman aure da bikin aure tsakanin namiji da mace", "Bikin bayar da suna ga jariri", "Bikin jana'iza", "Wani wasa na gargajiya"], "Tsarin neman aure da bikin aure tsakanin namiji da mace",
      "Aure refers to the traditional Hausa marriage process, including courtship customs and the wedding ceremony itself."),
  _q("A al'adar Hausawa, 'jana'iza' na nufin",
      ["Al'adun da ake bi wajen jibin da binne matacce", "Bikin suna", "Bikin aure", "Wasan gargajiya"], "Al'adun da ake bi wajen jibin da binne matacce",
      "Jana'iza refers to the traditional customs surrounding death, mourning, and burial in Hausa society."),
  _q("Wace sana'a ce ake kira 'kira' a al'adar gargajiyar Hausawa?",
      ["Sana'ar kera karafa (blacksmithing)", "Sana'ar saka tufafi", "Sana'ar noma", "Sana'ar jima fata"], "Sana'ar kera karafa (blacksmithing)",
      "Kira refers to the traditional occupation of blacksmithing, working and shaping metal into tools and implements."),
  _q("Wace sana'a ce ake kira 'saka' a al'adar gargajiyar Hausawa?",
      ["Sana'ar saka tufafi ko zane (weaving)", "Sana'ar kera karafa", "Sana'ar noma", "Sana'ar sarauta"], "Sana'ar saka tufafi ko zane (weaving)",
      "Saka refers to the traditional craft of weaving cloth or fabric, an important occupation in Hausa society."),
  _q("Wace sana'a ce ake kira 'jima' a al'adar gargajiyar Hausawa?",
      ["Sana'ar sarrafa fata (tanning/leatherwork)", "Sana'ar kera karafa", "Sana'ar saka tufafi", "Sana'ar noma"], "Sana'ar sarrafa fata (tanning/leatherwork)",
      "Jima refers to the traditional craft of tanning and processing leather from animal hides."),
  _q("Wace sana'a ce ake kira 'noma' a al'adar gargajiyar Hausawa?",
      ["Sana'ar aikin gona (farming)", "Sana'ar kera karafa", "Sana'ar sarrafa fata", "Sana'ar sarauta"], "Sana'ar aikin gona (farming)",
      "Noma refers to farming, one of the most fundamental and widespread traditional occupations in Hausa society."),
  _q("A tsarin gudanarwar gargajiyar Hausawa, wane matsayi ne ke jagorantar wata masarauta (emirate)?",
      ["Sarki/Emir", "Waziri kadai", "Madaki kadai", "Talaka"], "Sarki/Emir",
      "The Sarki (Emir) is the paramount traditional ruler at the head of a Hausa emirate's political and administrative structure."),
  _q("Wane wasa ne na gargajiya wanda ake yi da ƙarfin hannu, tsakanin mayaka biyu, kama da dambe?",
      ["Dambe (traditional boxing)", "Kokawa (wrestling) kadai", "Sharo", "Hawan kaho"], "Dambe (traditional boxing)",
      "Dambe is a traditional Hausa combat sport similar to boxing, involving fighters using their fists."),
  _q("Wane wasa ne na gargajiya wanda ake yi ta hanyar kokawa da juna har daya ya fadi kasa?",
      ["Kokawa (wrestling)", "Dambe", "Sharo", "Bukukuwan sallah"], "Kokawa (wrestling)",
      "Kokawa is a traditional wrestling sport where opponents grapple until one is thrown to the ground."),
  _q("Wane bikin gargajiya ne ake yi domin nuna kwarjini da jarumtaka ta hanyar musanya dukan sanda tsakanin samari?",
      ["Sharo/Shadi", "Kokawa", "Bikin suna", "Bikin aure"], "Sharo/Shadi",
      "Sharo (or Shadi) is a traditional Fulani/Hausa endurance ritual in which young men are whipped to demonstrate courage and manliness."),
  _q("Wane biki ne ake kira 'hawan kaho' a al'adar gargajiyar Hausawa?",
      ["Bikin gargajiya na sarauta da ake yi da kayan kade-kade na musamman", "Bikin bayar da suna", "Bikin aure", "Wasan kokawa kawai"], "Bikin gargajiya na sarauta da ake yi da kayan kade-kade na musamman",
      "Hawan kaho refers to a traditional ceremonial event, often associated with royal celebrations and accompanied by distinctive horn instruments and drumming."),
  _q("Wace bukukuwa ce ake yi bayan azumin watan Ramadan a al'adar Hausawa musulmi?",
      ["Bikin Sallah (Eid)", "Bikin Suna", "Bikin Kokawa", "Bikin Aure kadai"], "Bikin Sallah (Eid)",
      "Sallah festivals, marking the end of Ramadan (Eid al-Fitr) and the pilgrimage season (Eid al-Adha), are major religious and cultural celebrations among Hausa Muslims."),
  _q("Menene babban dalilin koyar da al'adun Hausawa a matsayin wani bangare na fannin karatun harshen Hausa?",
      ["Domin dalibai su fahimci al'adu da zamantakewar al'ummar Hausawa tare da harshensu", "Domin koyar da lissafi", "Domin koyar da wani harshe daban", "Domin dalibai su manta da al'adunsu"], "Domin dalibai su fahimci al'adu da zamantakewar al'ummar Hausawa tare da harshensu",
      "Studying culture alongside language helps students understand the social practices, customs, and worldview of the Hausa people, deepening their linguistic competence."),
  _q("Wane matsayi ne ke taimaka wa Sarki wajen shawarwari da gudanar da harkokin masarauta a tsarin sarautar gargajiya?",
      ["Fadawa (council of title-holders/advisers)", "Talakawa kadai", "Baki (foreigners) kadai", "Yara kanana kadai"], "Fadawa (council of title-holders/advisers)",
      "The Fadawa (palace title-holders and advisers) traditionally assist the Sarki in governance, decision-making, and administration of the emirate."),
  _q("A al'adar Hausawa, menene babban dalilin gudanar da bikin suna a rana ta bakwai bayan haihuwa?",
      ["Domin bayar wa jariri suna a hukumance a gaban dangi da al'umma", "Domin siyar da kayan gargajiya", "Domin fara koyar da jariri karatu", "Domin nishadantar da baki kadai ba tare da wata manufa ba"], "Domin bayar wa jariri suna a hukumance a gaban dangi da al'umma",
      "The seventh-day naming ceremony formally introduces the child's name to family and community, marking an important social and religious milestone."),
  _q("A tsarin neman aure na gargajiya, wane mataki ne ake yi kafin bikin aure, inda iyalan namiji ke gabatar da bukatarsu ga iyalan mace?",
      ["Zance/Neman hannu (courtship/marriage proposal)", "Bikin suna", "Jana'iza", "Sharo"], "Zance/Neman hannu (courtship/marriage proposal)",
      "Before the wedding itself, traditional courtship involves the groom's family formally presenting their intention to the bride's family, a key step in Hausa marriage customs."),
  _q("Menene babban rawar da sarakunan gargajiya (kamar Sarki/Emir) ke takawa a zamantakewar al'ummar Hausawa a yau?",
      ["Su na taimakawa wajen warware husuma da kula da al'adu, tare da hadin gwiwa da gwamnati", "Su ne kadai ke da ikon yin doka a kasa", "Ba su da wata rawa a yau", "Su ne kadai ke da ikon kula da tsaron kasa"], "Su na taimakawa wajen warware husuma da kula da al'adu, tare da hadin gwiwa da gwamnati",
      "Traditional rulers today largely assist in dispute resolution and cultural preservation, working alongside the modern government structure rather than holding sole legal authority."),
  _q("A al'adar gargajiyar Hausawa, menene ake kira lokacin da ake yin sujada da nuna biyayya ga babba, musamman iyaye?",
      ["Ibada/Biyayya ga iyaye (respect and deference to elders)", "Sharo kadai", "Kokawa kadai", "Dambe kadai"], "Ibada/Biyayya ga iyaye (respect and deference to elders)",
      "Showing deep respect and deference toward elders, especially parents, is a deeply embedded value in Hausa culture and social conduct."),
  _q("Menene babban dalilin gudanar da bukukuwan gargajiya, kamar hawan kaho da sharo, a al'ummar Hausawa?",
      ["Domin nuna hadin kai, jarumtaka, da kiyaye al'adun gargajiya", "Domin neman kudi kawai", "Domin kaucewa ayyukan noma", "Domin gwada karfin gwamnati kawai"], "Domin nuna hadin kai, jarumtaka, da kiyaye al'adun gargajiya",
      "Traditional festivals and rites serve to demonstrate communal unity, bravery, and the preservation of cultural heritage across generations."),
];

final _adabinHausa = [
  _q("Menene ake kira adabin da ake gadarwa ta baki daga tsara zuwa tsara, kamar tatsuniya da karin magana?",
      ["Adabin baka (oral literature)", "Rubutaccen adabi", "Nahawu", "Fonoloji"], "Adabin baka (oral literature)",
      "Oral literature (adabin baka) refers to traditional literary forms passed down verbally through generations, without being originally written down."),
  _q("Menene ake kira labaran gargajiya masu dauke da darasi ko nishadi, wadanda galibi ake bayarwa da dare?",
      ["Tatsuniya (folktale)", "Karin magana", "Kacici-kacici", "Waka"], "Tatsuniya (folktale)",
      "Tatsuniya refers to traditional folktales, often told at night, that entertain while conveying moral lessons."),
  _q("Menene ake kira wakokin baka na tarihi ko na bukukuwa a al'adar Hausawa?",
      ["Wakokin baka (oral poetry)", "Tatsuniya", "Kacici-kacici", "Rubutaccen labari"], "Wakokin baka (oral poetry)",
      "Oral poetry (wakokin baka) includes historical and ceremonial verse traditionally performed aloud rather than written."),
  _q("Menene ake kira gajerun jimloli masu dauke da hikima da darasi, wadanda ake amfani da su domin isar da sako a takaice?",
      ["Karin magana (proverbs)", "Tatsuniya", "Kacici-kacici", "Wakokin baka"], "Karin magana (proverbs)",
      "Proverbs (karin magana) are short, wise sayings used to convey deep meaning or moral lessons in a concise, memorable form."),
  _q("Menene ake kira wasannin baka masu kunshe da tambayoyi masu wuyar warwarewa, wadanda ake yi domin nishadi ko horar da hankali?",
      ["Kacici-kacici (riddles)", "Karin magana", "Tatsuniya", "Waka"], "Kacici-kacici (riddles)",
      "Riddles (kacici-kacici) are traditional oral games involving puzzling questions, often used to entertain and sharpen the mind."),
  _q("Menene ake kira adabin da aka rubuta a takarda, kamar litattafai da wasannin kwaikwayo?",
      ["Rubutaccen adabi (written literature)", "Adabin baka", "Fonoloji", "Nahawu"], "Rubutaccen adabi (written literature)",
      "Written literature (rubutaccen adabi) refers to literary works recorded in written form, such as novels and plays, unlike orally transmitted literature."),
  _q("Menene ake kira littafi mai dauke da labari mai tsawo, cikin rubutacciyar sigar zube?",
      ["Zubaccen rubutu/Littafin labari (novel)", "Wasan kwaikwayo", "Rubutacciyar waka", "Kacici-kacici"], "Zubaccen rubutu/Littafin labari (novel)",
      "A novel (zubaccen rubutu) is an extended prose narrative, one of the major forms of written Hausa literature studied in schools."),
  _q("Menene ake kira rubutun da aka tsara domin yin wasan kwaikwayo a kan dandali ko fim?",
      ["Wasan kwaikwayo (play/drama script)", "Waka", "Karin magana", "Kacici-kacici"], "Wasan kwaikwayo (play/drama script)",
      "A play (wasan kwaikwayo) is a written script intended for dramatic performance on stage or screen."),
  _q("Menene ake kira tarin wakoki masu rubutacciyar sigar, sabanin wakokin baka?",
      ["Rubutacciyar waka (written/modern poetry anthology)", "Tatsuniya", "Kacici-kacici", "Adabin baka gaba daya"], "Rubutacciyar waka (written/modern poetry anthology)",
      "Rubutacciyar waka refers to modern written poetry, composed and recorded in text form, distinct from orally performed traditional poetry."),
  _q("Wace dabara ake amfani da ita wajen nazarin littafin adabi domin fahimtar jigo, hali, da salon marubuci?",
      ["Nazarin adabi (literary analysis/criticism)", "Fassara kadai", "Auna fahimta kadai", "Ja jimloli kadai"], "Nazarin adabi (literary analysis/criticism)",
      "Literary analysis involves closely examining a text's themes, characters, and the author's stylistic choices to deepen understanding of the work."),
  _q("A nazarin adabi, menene ake kira babbar manufa ko sako da marubuci ke isarwa a cikin littafi?",
      ["Jigo (theme)", "Salo kadai", "Hali kadai", "Take kadai"], "Jigo (theme)",
      "The theme (jigo) of a literary work is the central message or idea that the author conveys throughout the text."),
  _q("A nazarin adabi, menene ake kira yanayin mutumin da ke cikin labari, tare da halayensa da rawar da yake takawa?",
      ["Hali/Jarumi (character)", "Jigo kadai", "Salo kadai", "Wuri kadai"], "Hali/Jarumi (character)",
      "A character (hali/jarumi) is a person portrayed within a literary work, defined by their traits, actions, and role in the story."),
  _q("A nazarin adabi, menene ake kira wurin da ko lokacin da al'amuran labari suka faru?",
      ["Wuri da zamani (setting)", "Jigo kadai", "Hali kadai", "Salo kadai"], "Wuri da zamani (setting)",
      "Setting refers to the time and place in which a story's events unfold, shaping the context of the characters' experiences."),
  _q("A nazarin adabi, menene ake kira salon musamman da marubuci ke amfani da shi wajen zabar kalmomi da tsara jimloli?",
      ["Salo (style)", "Jigo kadai", "Hali kadai", "Wuri kadai"], "Salo (style)",
      "Style (salo) refers to an author's distinctive manner of using language, word choice, and sentence construction throughout their work."),
  _q("Wace irin adabi ce ake kira 'wakokin Islama' wadanda ke dauke da darussan addini a al'adar Hausawa?",
      ["Wakokin addini (religious/Islamic poetry)", "Tatsuniya kadai", "Kacici-kacici kadai", "Rubutaccen labari kadai"], "Wakokin addini (religious/Islamic poetry)",
      "Religious poetry, often composed by Islamic scholars, conveys moral and spiritual teachings and forms an important part of Hausa literary tradition."),
];
