import "../quiz_question.dart";

const _subject = "Arabic";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// WAEC Arabic question bank covering the full syllabus: Al-Qawa'id
/// (Grammar and Morphology), Al-Balaghah (Rhetoric) and Literature,
/// Translation and Vocabulary Expansion, and Composition and Oral
/// Assessment. Weighted toward well-established grammar concepts rather
/// than fine-grained classical text analysis, to keep content accurate
/// regardless of the specific cycle's prescribed literary texts.
List<QuizQuestion> buildWaecArabicQuestions() {
  return [
    ..._grammarAndMorphology,
    ..._rhetoricAndLiterature,
    ..._translationAndVocabulary,
    ..._compositionAndOral,
  ];
}

final _grammarAndMorphology = [
  _q("The three main parts of speech (أقسام الكلام) in Arabic grammar are",
      ["الاسم (noun), الفعل (verb), and الحرف (particle)", "الفاعل، المفعول، والخبر", "الماضي، المضارع، والأمر", "المرفوع، المنصوب، والمجرور"], "الاسم (noun), الفعل (verb), and الحرف (particle)",
      "Classical Arabic grammar divides all words into three fundamental categories: Al-Ism (noun), Al-Fi'l (verb), and Al-Harf (particle)."),
  _q("الاسم (Al-Ism) in Arabic grammar refers to a word that",
      ["names a person, place, thing, or idea", "expresses an action occurring in time", "connects other words together, such as a preposition", "expresses a command"], "names a person, place, thing, or idea",
      "Al-Ism (noun) is a word used to name people, places, objects, or concepts, distinct from verbs and particles."),
  _q("الفعل (Al-Fi'l) in Arabic grammar refers to a word that",
      ["expresses an action or occurrence, tied to a specific tense", "only names an object or a place", "only functions as a connecting particle", "is always a proper noun"], "expresses an action or occurrence, tied to a specific tense",
      "Al-Fi'l (verb) expresses an action, state, or occurrence, and is inflected according to tense: past, present/future, or imperative."),
  _q("الحرف (Al-Harf) in Arabic grammar refers to a word that",
      ["has no independent meaning on its own but connects or modifies other words", "always refers to a specific noun", "is always conjugated like a verb", "must always appear at the end of a sentence"], "has no independent meaning on its own but connects or modifies other words",
      "Al-Harf (particle) lacks independent meaning by itself and instead serves a grammatical function, such as prepositions and conjunctions."),
  _q("A noun that refers to a specific, particular, and already known entity, such as a proper name, is called",
      ["معرفة (Ma'rifah, definite)", "نكرة (Nakirah, indefinite)", "فعل ماض (past tense verb)", "حرف جر (preposition)"], "معرفة (Ma'rifah, definite)",
      "Ma'rifah refers to definite nouns, which point to a specific, identifiable entity, such as proper names or nouns with the definite article 'ال'."),
  _q("A noun that refers to a general, unspecified entity, rather than a particular known one, is called",
      ["نكرة (Nakirah, indefinite)", "معرفة (Ma'rifah, definite)", "فعل مضارع (present tense verb)", "حرف عطف (conjunction)"], "نكرة (Nakirah, indefinite)",
      "Nakirah refers to indefinite nouns, which refer generally to any member of a category, without specifying a particular one."),
  _q("In Arabic, a noun referring to a male person or a grammatically masculine object is classified as",
      ["مذكر (Mudhakar, masculine)", "مؤنث (Mu'anath, feminine)", "مثنى (Muthanna, dual)", "جمع (Jam', plural)"], "مذكر (Mudhakar, masculine)",
      "Mudhakar refers to the masculine gender classification applied to nouns in Arabic grammar."),
  _q("In Arabic, a noun referring to a female person, or a noun that is grammatically feminine (often ending in ة), is classified as",
      ["مؤنث (Mu'anath, feminine)", "مذكر (Mudhakar, masculine)", "مفرد (Mufrad, singular)", "جمع (Jam', plural)"], "مؤنث (Mu'anath, feminine)",
      "Mu'anath refers to the feminine gender classification, commonly (though not exclusively) marked by the ة (taa marbutah) ending."),
  _q("A noun referring to a single entity is classified in Arabic grammar as",
      ["مفرد (Mufrad, singular)", "مثنى (Muthanna, dual)", "جمع (Jam', plural)", "معرفة (Ma'rifah, definite)"], "مفرد (Mufrad, singular)",
      "Mufrad refers to the singular form of a noun, indicating exactly one of the entity described."),
  _q("A noun referring to exactly two entities, formed with a special dual ending, is classified in Arabic grammar as",
      ["مثنى (Muthanna, dual)", "مفرد (Mufrad, singular)", "جمع (Jam', plural)", "نكرة (Nakirah, indefinite)"], "مثنى (Muthanna, dual)",
      "Muthanna is the dual form, used specifically when referring to exactly two of something, marked by distinctive dual endings."),
  _q("A plural formed by adding a regular ending to the singular noun, without altering its internal structure, is called",
      ["جمع سالم (Sound Plural)", "جمع تكسير (Broken Plural)", "مثنى (Muthanna, dual)", "مفرد (Mufrad, singular)"], "جمع سالم (Sound Plural)",
      "Jam' Salim (sound plural) is formed by adding a regular suffix to the singular noun without changing its internal letter pattern."),
  _q("A plural formed by internally restructuring the singular noun's pattern, rather than simply adding a suffix, is called",
      ["جمع تكسير (Broken Plural)", "جمع سالم (Sound Plural)", "مثنى (Muthanna, dual)", "معرفة (Ma'rifah, definite)"], "جمع تكسير (Broken Plural)",
      "Jam' Taksir (broken plural) involves an internal change to the noun's structure, unlike the sound plural which simply adds a regular suffix."),
  _q("الإعراب (Al-I'rab) in Arabic grammar refers to",
      ["the system of declension showing a word's grammatical case through its ending", "the classification of nouns as masculine or feminine", "the process of forming the plural of a noun", "the rules governing correct Qur'anic recitation"], "the system of declension showing a word's grammatical case through its ending",
      "Al-I'rab is the Arabic case system, in which a word's ending changes to indicate its grammatical role, such as subject or object."),
  _q("The case marking a noun functioning as the subject of a sentence is called",
      ["مرفوع (Marfoo', Nominative)", "منصوب (Mansoob, Accusative)", "مجرور (Majroor, Genitive)", "مجزوم (Majzoom, Jussive)"], "مرفوع (Marfoo', Nominative)",
      "Marfoo' (nominative case) marks a noun functioning as the subject of a sentence, typically indicated by a dammah ending."),
  _q("The case marking a noun functioning as a direct object of a verb is called",
      ["منصوب (Mansoob, Accusative)", "مرفوع (Marfoo', Nominative)", "مجرور (Majroor, Genitive)", "جمع (Jam', Plural)"], "منصوب (Mansoob, Accusative)",
      "Mansoob (accusative case) marks a noun functioning as the direct object of a verb, typically indicated by a fathah ending."),
  _q("The case marking a noun that follows a preposition or forms part of a possessive construction is called",
      ["مجرور (Majroor, Genitive)", "مرفوع (Marfoo', Nominative)", "منصوب (Mansoob, Accusative)", "مثنى (Muthanna, Dual)"], "مجرور (Majroor, Genitive)",
      "Majroor (genitive case) marks a noun following a preposition (حرف جر) or as the second part of an Idafah construction, typically ending in kasrah."),
  _q("A nominal sentence (الجملة الاسمية) is a sentence that",
      ["begins with a noun and consists of a subject (مبتدأ) and predicate (خبر)", "always begins with a verb", "contains only a preposition", "has no subject at all"], "begins with a noun and consists of a subject (مبتدأ) and predicate (خبر)",
      "A nominal sentence begins with a noun, structured around a Mubtada' (subject/topic) and a Khabar (predicate/comment about the subject)."),
  _q("In a nominal sentence, المبتدأ (Al-Mubtada') refers to",
      ["the subject or topic that the sentence is about", "the verb of the sentence", "the object of the verb", "a preposition linking two nouns"], "the subject or topic that the sentence is about",
      "Al-Mubtada' is the subject or topic of a nominal sentence, about which the Khabar (predicate) provides information."),
  _q("In a nominal sentence, الخبر (Al-Khabar) refers to",
      ["the predicate that gives information about the subject (مبتدأ)", "the subject of the sentence", "the object of a transitive verb", "the tense marker of a verb"], "the predicate that gives information about the subject (مبتدأ)",
      "Al-Khabar is the predicate of a nominal sentence, providing descriptive or informative content about the Mubtada' (subject)."),
  _q("A verbal sentence (الجملة الفعلية) is a sentence that",
      ["begins with a verb, typically followed by the subject (فاعل) and, where applicable, an object (مفعول به)", "always begins with a noun in the nominative case", "consists only of a preposition and a noun", "never includes a subject"], "begins with a verb, typically followed by the subject (فاعل) and, where applicable, an object (مفعول به)",
      "A verbal sentence is structured beginning with the verb (Fi'l), followed by its subject (Fa'il), and an object (Maf'ool Bihi) if the verb is transitive."),
  _q("In a verbal sentence, الفاعل (Al-Fa'il) refers to",
      ["the doer of the action expressed by the verb", "the object that receives the action", "the predicate of a nominal sentence", "a preposition connecting two clauses"], "the doer of the action expressed by the verb",
      "Al-Fa'il is the grammatical subject that performs the action of the verb in a verbal sentence."),
  _q("In a verbal sentence, المفعول به (Al-Maf'ool Bihi) refers to",
      ["the direct object that receives the action of the verb", "the doer of the action", "the subject of a nominal sentence", "a demonstrative pronoun"], "the direct object that receives the action of the verb",
      "Al-Maf'ool Bihi is the direct object, receiving the action performed by the Fa'il (subject) through the verb."),
  _q("كان وأخواتها (Kana and her sisters) are a group of verbs that, when entering a nominal sentence, generally cause",
      ["the subject (اسمها) to remain marfoo' while the predicate (خبرها) becomes mansoob", "both the subject and predicate to become majroor", "the sentence to lose its subject entirely", "the predicate to become the new subject"], "the subject (اسمها) to remain marfoo' while the predicate (خبرها) becomes mansoob",
      "Kana and its sister verbs (such as Kana, Asbaha, Sara) affect a nominal sentence by keeping the subject (Ismuha) nominative while changing the predicate (Khabaruha) to accusative."),
  _q("إن وأخواتها (Inna and her sisters) are a group of particles that, when entering a nominal sentence, generally cause",
      ["the subject (اسمها) to become mansoob while the predicate (خبرها) remains marfoo'", "both the subject and predicate to become marfoo'", "the sentence to become a verbal sentence", "the verb to change from past to present tense"], "the subject (اسمها) to become mansoob while the predicate (خبرها) remains marfoo'",
      "Inna and its sister particles (such as Inna, Anna, Laakinna) affect a nominal sentence by changing the subject (Ismuha) to accusative while the predicate (Khabaruha) remains nominative."),
  _q("The past tense form of an Arabic verb is called",
      ["الفعل الماضي (Al-Fi'l Al-Madi)", "الفعل المضارع (Al-Fi'l Al-Mudari')", "فعل الأمر (Fi'l Al-Amr)", "الاسم المفرد (Al-Ism Al-Mufrad)"], "الفعل الماضي (Al-Fi'l Al-Madi)",
      "Al-Fi'l Al-Madi refers to the past tense form of an Arabic verb, indicating a completed action."),
  _q("The present/future tense form of an Arabic verb is called",
      ["الفعل المضارع (Al-Fi'l Al-Mudari')", "الفعل الماضي (Al-Fi'l Al-Madi)", "فعل الأمر (Fi'l Al-Amr)", "الاسم الموصول (Al-Ism Al-Mawsool)"], "الفعل المضارع (Al-Fi'l Al-Mudari')",
      "Al-Fi'l Al-Mudari' expresses an action occurring in the present or future, and it is the only Arabic verb form affected by Al-I'rab (declension)."),
  _q("The imperative (command) form of an Arabic verb is called",
      ["فعل الأمر (Fi'l Al-Amr)", "الفعل الماضي (Al-Fi'l Al-Madi)", "الفعل المضارع (Al-Fi'l Al-Mudari')", "الاسم الموصول (Al-Ism Al-Mawsool)"], "فعل الأمر (Fi'l Al-Amr)",
      "Fi'l Al-Amr is the imperative verb form used to give commands or instructions directly to a second person."),
  _q("A verb whose root letters are all sound consonants, free of weak letters (و، ي، أ), is classified as",
      ["الفعل الصحيح (Al-Fi'l Al-Saheeh, sound verb)", "الفعل المعتل (Al-Fi'l Al-Mu'tal, weak verb)", "فعل الأمر (Fi'l Al-Amr)", "الاسم المشتق (derived noun)"], "الفعل الصحيح (Al-Fi'l Al-Saheeh, sound verb)",
      "Al-Fi'l Al-Saheeh (sound verb) has root letters entirely free from the weak letters waw, ya, or hamzah, following regular conjugation patterns."),
  _q("A verb containing one or more weak letters (و، ي، أ) in its root, often causing irregular conjugation patterns, is classified as",
      ["الفعل المعتل (Al-Fi'l Al-Mu'tal, weak verb)", "الفعل الصحيح (Al-Fi'l Al-Saheeh, sound verb)", "فعل الأمر (Fi'l Al-Amr)", "الاسم الجامد (rigid noun)"], "الفعل المعتل (Al-Fi'l Al-Mu'tal, weak verb)",
      "Al-Fi'l Al-Mu'tal (weak verb) contains one or more of the weak letters waw, ya, or hamzah in its root, often resulting in irregular conjugation."),
  _q("Pronoun suffixes attached directly to a verb, such as in 'كتبته' (he wrote it), are called",
      ["الضمائر المتصلة (attached/suffixed pronouns)", "الضمائر المنفصلة (independent pronouns)", "أسماء الإشارة (demonstrative nouns)", "حروف الجر (prepositions)"], "الضمائر المتصلة (attached/suffixed pronouns)",
      "Attached (suffixed) pronouns are joined directly onto a verb, noun, or preposition, representing the object or possessor, as opposed to standing independently."),
  _q("Words such as 'إلى' (to), 'من' (from), and 'على' (on) are classified in Arabic grammar as",
      ["حروف الجر (Huroof Al-Jarr, prepositions)", "الأسماء الموصولة (relative pronouns)", "أسماء الإشارة (demonstrative pronouns)", "أفعال الأمر (imperative verbs)"], "حروف الجر (Huroof Al-Jarr, prepositions)",
      "Huroof Al-Jarr are prepositions that govern a following noun in the genitive (majroor) case, expressing relationships such as direction, source, or location."),
  _q("Words such as 'الذي' (who/which, masculine) and 'التي' (who/which, feminine) are classified as",
      ["الأسماء الموصولة (Al-Asma' Al-Mawsoolah, relative pronouns)", "حروف الجر (prepositions)", "أسماء الإشارة (demonstrative pronouns)", "ضمائر منفصلة (independent pronouns)"], "الأسماء الموصولة (Al-Asma' Al-Mawsoolah, relative pronouns)",
      "Al-Asma' Al-Mawsoolah are relative pronouns used to introduce a relative clause, connecting it to the noun it describes."),
  _q("Words such as 'هذا' (this, masculine) and 'هذه' (this, feminine) are classified as",
      ["أسماء الإشارة (Asma' Al-Isharah, demonstrative nouns)", "الأسماء الموصولة (relative pronouns)", "حروف الجر (prepositions)", "ضمائر متصلة (attached pronouns)"], "أسماء الإشارة (Asma' Al-Isharah, demonstrative nouns)",
      "Asma' Al-Isharah are demonstrative nouns used to point out or indicate a specific person or object, such as 'this' or 'that'."),
  _q("A possessive construction linking two nouns, such as 'كتاب الطالب' (the student's book), is called",
      ["الإضافة (Al-Idafah, construct phrase)", "الجملة الفعلية (verbal sentence)", "حروف العطف (conjunctions)", "أسماء الإشارة (demonstrative nouns)"], "الإضافة (Al-Idafah, construct phrase)",
      "Al-Idafah is the construct (possessive) phrase structure in Arabic, linking two nouns where the second noun (in the genitive case) shows possession or specification of the first."),
  _q("In an Idafah (construct phrase) such as 'باب البيت' (the door of the house), the first noun 'باب' is called",
      ["المضاف (Al-Mudaf)", "المضاف إليه (Al-Mudaf Ilayhi)", "الفاعل (Al-Fa'il)", "الخبر (Al-Khabar)"], "المضاف (Al-Mudaf)",
      "Al-Mudaf is the first noun in a construct phrase, which is defined or specified by the second noun (Al-Mudaf Ilayhi)."),
  _q("In an Idafah (construct phrase) such as 'باب البيت' (the door of the house), the second noun 'البيت' is called",
      ["المضاف إليه (Al-Mudaf Ilayhi)", "المضاف (Al-Mudaf)", "الفاعل (Al-Fa'il)", "المبتدأ (Al-Mubtada')"], "المضاف إليه (Al-Mudaf Ilayhi)",
      "Al-Mudaf Ilayhi is the second noun in a construct phrase, always in the genitive case, specifying or possessing the first noun (Al-Mudaf)."),
  _q("The first noun (المضاف) in an Idafah construction never takes",
      ["the definite article 'ال' or tanween at the same time as being defined by the second noun", "any case ending at all", "a genitive-case second noun", "a possessive meaning"], "the definite article 'ال' or tanween at the same time as being defined by the second noun",
      "A defining feature of Al-Mudaf is that it cannot carry the definite article 'ال' or tanween itself, since its definiteness comes from the following Mudaf Ilayhi."),
  _q("Tanween (التنوين), the doubling of a final short vowel sound in Arabic, generally indicates that a noun is",
      ["indefinite (نكرة)", "definite (معرفة)", "a verb in the past tense", "a demonstrative pronoun"], "indefinite (نكرة)",
      "Tanween, the extra 'n' sound added to a noun's case ending, marks a noun as indefinite (Nakirah), unlike definite nouns which do not take tanween."),
  _q("A verb conjugated for the subject pronoun 'أنتم' (you, masculine plural) in the past tense typically ends with the suffix",
      ["ـتم", "ـتِ", "ـنا", "ـوا"], "ـتم",
      "The past tense suffix 'ـتم' is attached to verbs for the second person masculine plural subject 'أنتم'."),
  _q("A verb conjugated for the subject pronoun 'هم' (they, masculine plural) in the past tense typically ends with the suffix",
      ["ـوا", "ـتم", "ـتِ", "ـنا"], "ـوا",
      "The past tense suffix 'ـوا' is attached to verbs for the third person masculine plural subject 'هم'."),
  _q("In the present tense (المضارع), verbs conjugated for 'أنا' (I) typically begin with the prefix",
      ["أ", "ت", "ي", "ن"], "أ",
      "Present tense verbs for the first person singular 'أنا' begin with the prefix hamzah (أ), as in 'أكتب' (I write)."),
  _q("In the present tense (المضارع), verbs conjugated for 'نحن' (we) typically begin with the prefix",
      ["ن", "أ", "ي", "ت"], "ن",
      "Present tense verbs for the first person plural 'نحن' begin with the prefix noon (ن), as in 'نكتب' (we write)."),
  _q("In the present tense (المضارع), verbs conjugated for 'هو' (he) typically begin with the prefix",
      ["ي", "ت", "أ", "ن"], "ي",
      "Present tense verbs for the third person masculine singular 'هو' begin with the prefix ya (ي), as in 'يكتب' (he writes)."),
  _q("The negation particle 'لم' used before a present tense verb typically changes its meaning to",
      ["a negated past tense action (did not)", "a negated future action only", "an affirmative command", "a question about the future"], "a negated past tense action (did not)",
      "'لم' negates a present tense verb but shifts its meaning to the past, as in 'لم يذهب' (he did not go), and requires the jussive mood."),
  _q("The negation particle 'لن' used before a present tense verb typically expresses",
      ["a negated future action (will not)", "a negated past action", "an affirmative present action", "a command"], "a negated future action (will not)",
      "'لن' negates a present tense verb to express a future negation, as in 'لن يذهب' (he will not go), and places the verb in the accusative (mansoob) mood."),
];

final _rhetoricAndLiterature = [
  _q("البلاغة (Al-Balaghah) in Arabic studies refers broadly to",
      ["the art and science of eloquent, effective expression in the Arabic language", "the memorisation of Qur'anic verses only", "the study of Arabic verb conjugation patterns", "the rules governing Arabic noun declension"], "the art and science of eloquent, effective expression in the Arabic language",
      "Al-Balaghah is the discipline concerned with rhetorical eloquence, studying how language can be used effectively and beautifully to convey meaning."),
  _q("البيان (Al-Bayan), a major branch of Al-Balaghah, is primarily concerned with",
      ["figurative expression, including simile (تشبيه) and metaphor", "grammatical case endings", "the rules of Qur'anic recitation (tajwid)", "verb conjugation patterns"], "figurative expression, including simile (تشبيه) and metaphor",
      "Al-Bayan focuses on figurative and imaginative expression, including devices such as simile (Tashbih) and metaphor, to convey vivid meaning."),
  _q("تشبيه (Tashbih), a key device studied under Al-Bayan, refers to",
      ["a simile, comparing one thing to another using a comparative particle", "a direct metaphor with no comparative particle", "an antithesis contrasting opposite ideas", "a purely grammatical case marking"], "a simile, comparing one thing to another using a comparative particle",
      "Tashbih is the Arabic equivalent of a simile, explicitly comparing two things using a comparative particle such as 'كـ' (like) or 'مثل' (similar to)."),
  _q("البديع (Al-Badi'), another branch of Al-Balaghah, is primarily concerned with",
      ["ornamental and stylistic embellishments in language, such as antithesis", "the rules of Arabic noun declension", "verb tense formation", "the pronunciation of Qur'anic letters"], "ornamental and stylistic embellishments in language, such as antithesis",
      "Al-Badi' studies the decorative and stylistic features that enhance the beauty and impact of Arabic expression, including devices like antithesis."),
  _q("التقابل أو الطباق (Taqabul/Tibaaq), a device studied under Al-Badi', refers to",
      ["antithesis, bringing together two opposite or contrasting words or ideas", "a direct simile using 'كـ' (like)", "a metaphor with no comparative word", "a grammatical rule for verb conjugation"], "antithesis, bringing together two opposite or contrasting words or ideas",
      "Tibaaq (antithesis) involves pairing contrasting or opposite terms within a sentence for rhetorical and stylistic effect."),
  _q("When studying a prescribed Arabic literary text, analysing the central theme mainly involves",
      ["identifying the main idea or message the author conveys throughout the text", "counting the number of words in the text", "memorising the text without understanding its meaning", "ignoring the cultural context of the text entirely"], "identifying the main idea or message the author conveys throughout the text",
      "Thematic analysis of a literary text requires identifying and understanding the central ideas or messages the author intends to communicate."),
  _q("Understanding the cultural context of a prescribed Arabic text is important because it helps readers to",
      ["appreciate the historical and social background influencing the author's ideas", "ignore the meaning of the text entirely", "translate every word literally without interpretation", "avoid any analysis of the author's intentions"], "appreciate the historical and social background influencing the author's ideas",
      "Cultural context provides insight into the historical and social circumstances that shaped an author's perspective and the meaning of their work."),
  _q("Analysing an author's intention in a literary text involves considering",
      ["why the author wrote the text and what message or effect they intended to achieve", "only the number of paragraphs in the text", "the exact publication date with no regard to content", "the price of the book in which the text appears"], "why the author wrote the text and what message or effect they intended to achieve",
      "Understanding authorial intention requires considering the purpose behind a text and the effect the author sought to have on readers."),
  _q("Classical Arabic poetry is traditionally distinguished from prose mainly by its",
      ["structured metre (وزن) and rhyme (قافية)", "complete absence of any grammatical rules", "exclusive use of the imperative verb form", "total lack of thematic content"], "structured metre (وزن) and rhyme (قافية)",
      "Classical Arabic poetry follows structured patterns of metre (Wazn) and rhyme (Qafiyah), distinguishing it clearly from prose."),
  _q("Islamic Arabic literature commonly draws its themes from",
      ["religious devotion, morality, and Qur'anic or Prophetic teachings", "topics entirely unrelated to Islamic values", "modern secular philosophy exclusively", "European literary traditions exclusively"], "religious devotion, morality, and Qur'anic or Prophetic teachings",
      "Islamic Arabic literature frequently draws inspiration from religious devotion, moral instruction, and themes rooted in Qur'anic and Prophetic teaching."),
  _q("الاستعارة (Al-Isti'arah), a figure of speech closely related to Tashbih, refers to",
      ["a metaphor, in which one thing is described as another without using a comparative particle", "a simile that always uses 'كـ' (like)", "a purely grammatical case ending", "an antithesis contrasting two opposites"], "a metaphor, in which one thing is described as another without using a comparative particle",
      "Al-Isti'arah (metaphor) drops the comparative particle used in simile, directly describing one thing as if it were another for stronger rhetorical effect."),
  _q("A prescribed classical Arabic poem is generally studied for its",
      ["metre, rhyme scheme, themes, and the poet's stylistic choices", "grammatical case endings alone, without regard to meaning", "spelling and handwriting quality only", "the poet's date of birth alone"], "metre, rhyme scheme, themes, and the poet's stylistic choices",
      "Classical poetry analysis typically covers formal features like metre and rhyme, alongside thematic content and the poet's distinctive stylistic techniques."),
  _q("When comparing two Arabic literary texts, students are often asked to identify",
      ["similarities and differences in theme, style, or context between the two works", "only the number of pages in each text", "the exact publisher of each book", "which text was printed first, with no regard to content"], "similarities and differences in theme, style, or context between the two works",
      "Comparative literary analysis involves examining shared and contrasting elements of theme, style, and context across two or more works."),
  _q("السجع (As-Saj'), a rhetorical device found in some classical Arabic prose, refers to",
      ["rhymed prose, where sentence endings share a similar rhyming sound", "a purely grammatical rule for verb conjugation", "a type of Qur'anic recitation rule", "a form of noun declension"], "rhymed prose, where sentence endings share a similar rhyming sound",
      "As-Saj' is a stylistic device in classical Arabic prose where consecutive phrases or sentences end with rhyming sounds, adding rhythmic beauty to the text."),
  _q("الجناس (Al-Jinas), a stylistic device studied under Al-Badi', refers to",
      ["paronomasia, the use of two words that sound alike but differ in meaning", "a simile using the comparative particle 'كـ'", "a purely grammatical case ending", "an indirect implied meaning (kinayah)"], "paronomasia, the use of two words that sound alike but differ in meaning",
      "Al-Jinas involves placing similar-sounding but differently-meaning words close together in a sentence, creating a pleasing wordplay effect."),
];

final _translationAndVocabulary = [
  _q("الكناية (Al-Kinayah), another figure of speech in Al-Bayan, refers to",
      ["an indirect expression implying a meaning without stating it explicitly", "a direct statement with no implied meaning at all", "a purely grammatical rule for pluralising nouns", "a rule governing verb tense formation"], "an indirect expression implying a meaning without stating it explicitly",
      "Al-Kinayah is a form of indirect expression (metonymy/circumlocution) that implies a meaning without directly stating it, adding subtlety to the language."),
  _q("Translate to English: 'الكتاب على الطاولة.'",
      ["The book is on the table.", "The table is under the book.", "The student reads the book.", "The teacher is in the classroom."], "The book is on the table.",
      "This simple nominal sentence states the location of the book, translating directly to 'The book is on the table.'"),
  _q("Translate to English: 'ذهب الولد إلى المدرسة.'",
      ["The boy went to school.", "The boy is going to the market.", "The girl went to the school.", "The boy came from school."], "The boy went to school.",
      "'ذهب' (went, past tense) with 'الولد' (the boy) and 'إلى المدرسة' (to the school) translates as 'The boy went to school.'"),
  _q("Translate to Arabic: 'The teacher is in the classroom.'",
      ["المعلم في الفصل.", "الطالب في المدرسة.", "الكتاب على الطاولة.", "الولد في البيت."], "المعلم في الفصل.",
      "'المعلم' (the teacher), 'في' (in), and 'الفصل' (the classroom) together accurately translate 'The teacher is in the classroom.'"),
  _q("Translate to Arabic: 'She wrote a letter to her friend.'",
      ["كتبت رسالة إلى صديقتها.", "قرأت كتابًا في المكتبة.", "ذهبت إلى السوق أمس.", "أكلت الطعام في البيت."], "كتبت رسالة إلى صديقتها.",
      "'كتبت' (she wrote), 'رسالة' (a letter), and 'إلى صديقتها' (to her friend) accurately render 'She wrote a letter to her friend.'"),
  _q("When translating an Arabic passage into English, maintaining tense consistency means that",
      ["past tense verbs in Arabic should generally be translated using past tense verbs in English", "all Arabic verbs must be translated into the English present tense only", "tense in the original text can be ignored freely", "Arabic verbs should always become English nouns"], "past tense verbs in Arabic should generally be translated using past tense verbs in English",
      "Accurate translation requires preserving the tense of the original text, so past tense Arabic verbs should generally be rendered in past tense English."),
  _q("A key challenge when translating idiomatic Arabic expressions is that",
      ["a literal, word-for-word translation may fail to capture the intended meaning", "idioms always translate directly and literally with no loss of meaning", "idiomatic expressions do not exist in Arabic", "idioms are irrelevant to accurate translation"], "a literal, word-for-word translation may fail to capture the intended meaning",
      "Idiomatic expressions often carry meaning beyond their literal words, so translators must convey the intended sense rather than translating word-for-word."),
  _q("The Arabic word 'مكتب' most closely translates to English as",
      ["office/desk", "school", "hospital", "market"], "office/desk",
      "'مكتب' (maktab) refers to an office or a desk, a common vocabulary word relating to administrative or work settings."),
  _q("The Arabic word 'تجارة' most closely translates to English as",
      ["trade/commerce", "travel", "sport", "agriculture"], "trade/commerce",
      "'تجارة' (tijarah) refers to trade or commerce, relevant vocabulary in administrative and business-related registers."),
  _q("The Arabic word 'سفر' most closely translates to English as",
      ["travel/journey", "trade", "cleanliness", "worship"], "travel/journey",
      "'سفر' (safar) refers to travel or a journey, common vocabulary in registers relating to travel and transportation."),
  _q("The Arabic word 'رياضة' most closely translates to English as",
      ["sport/exercise", "trade", "agriculture", "administration"], "sport/exercise",
      "'رياضة' (riyadah) refers to sport or physical exercise, a common vocabulary term in discussions of health and leisure."),
  _q("The Arabic word 'بيت' most closely translates to English as",
      ["house/home", "office", "market", "hospital"], "house/home",
      "'بيت' (bayt) refers to a house or home, a fundamental domestic vocabulary term."),
  _q("The Arabic word 'سوق' most closely translates to English as",
      ["market", "school", "office", "hospital"], "market",
      "'سوق' (souq) refers to a market, a term relevant to vocabulary about trade and shopping."),
  _q("The Arabic phrase 'الشؤون الإدارية' relates most closely to the English concept of",
      ["administrative affairs", "sporting events", "agricultural produce", "travel arrangements"], "administrative affairs",
      "'الشؤون الإدارية' translates to 'administrative affairs', relevant vocabulary in registers concerning government and organisational matters."),
  _q("Translate to English: 'الأخبار الحالية مهمة جدًا.'",
      ["Current affairs (news) are very important.", "The old books are on the shelf.", "The weather today is very cold.", "The market is closed today."], "Current affairs (news) are very important.",
      "'الأخبار الحالية' (current news/affairs) and 'مهمة جدًا' (very important) together render 'Current affairs are very important.'"),
  _q("Translate to Arabic: 'The farmer works hard in the field.'",
      ["يعمل الفلاح بجد في الحقل.", "يذهب الطالب إلى المكتبة.", "تطبخ الأم الطعام في البيت.", "يسافر التاجر إلى المدينة."], "يعمل الفلاح بجد في الحقل.",
      "'يعمل' (works), 'الفلاح' (the farmer), 'بجد' (hard/diligently), and 'في الحقل' (in the field) together render 'The farmer works hard in the field.'"),
  _q("The Arabic word 'زراعة' most closely translates to English as",
      ["agriculture/farming", "trade", "sport", "travel"], "agriculture/farming",
      "'زراعة' (zira'ah) refers to agriculture or farming, relevant vocabulary for topics on rural life and food production."),
  _q("The Arabic word 'نظافة' most closely translates to English as",
      ["cleanliness", "trade", "travel", "sport"], "cleanliness",
      "'نظافة' (nazafah) refers to cleanliness, a term relevant to both everyday hygiene and religious purification contexts."),
  _q("Translate to English: 'يحب الطلاب القراءة في المكتبة.'",
      ["The students love reading in the library.", "The teachers work in the office.", "The children play in the garden.", "The farmers sell vegetables in the market."], "The students love reading in the library.",
      "'يحب الطلاب القراءة' (the students love reading) and 'في المكتبة' (in the library) together render 'The students love reading in the library.'"),
  _q("When translating a formal Arabic administrative document into English, it is especially important to preserve",
      ["precise and formal register, avoiding overly casual phrasing", "a casual, conversational tone throughout", "only the general idea, ignoring specific details", "the exact Arabic word order regardless of English grammar"], "precise and formal register, avoiding overly casual phrasing",
      "Administrative and official documents require a formal register in translation, ensuring accuracy and professionalism are preserved in the target language."),
];

final _compositionAndOral = [
  _q("A well-written short Arabic essay (الإنشاء) should generally include",
      ["a clear introduction, a well-developed body, and a concise conclusion", "only a list of unrelated vocabulary words", "no punctuation or structure at all", "a single sentence with no elaboration"], "a clear introduction, a well-developed body, and a concise conclusion",
      "Effective Arabic composition, like essay writing in other languages, benefits from a clear structure: introduction, body, and conclusion."),
  _q("The recommended word count for a short WAEC Arabic composition or formal correspondence is typically around",
      ["120 to 150 words", "10 to 20 words", "1000 to 1500 words", "3000 words"], "120 to 150 words",
      "WAEC Arabic compositions and formal correspondence are generally expected to fall within a range of about 120 to 150 words."),
  _q("Correct Arabic spelling (الإملاء) is particularly important in composition because it",
      ["ensures the intended meaning of words is clearly and accurately conveyed", "has no impact on how a text is understood", "is only relevant in spoken Arabic, not written Arabic", "can be freely ignored without consequence"], "ensures the intended meaning of words is clearly and accurately conveyed",
      "Correct spelling is essential in Arabic composition, as similar-looking words can carry very different meanings depending on precise letter usage."),
  _q("Guided creative writing exercises in Arabic often ask students to",
      ["describe a personal experience or a familiar topic using appropriate vocabulary and structure", "translate an entire novel from English to Arabic", "recite the Qur'an without any writing component", "analyse advanced classical poetry exclusively"], "describe a personal experience or a familiar topic using appropriate vocabulary and structure",
      "Guided writing tasks typically ask students to write about familiar topics, such as personal experiences, applying appropriate vocabulary and sentence structures."),
  _q("Al-Huroof Al-Shamsiyyah (الحروف الشمسية), the 'sun letters', affect the pronunciation of the definite article 'ال' by causing",
      ["the 'ل' of 'ال' to be assimilated (silent) while the following consonant is doubled in pronunciation", "the 'ل' of 'ال' to always be pronounced clearly", "the entire word to become plural", "the noun to change gender"], "the 'ل' of 'ال' to be assimilated (silent) while the following consonant is doubled in pronunciation",
      "Before sun letters, the lam (ل) of the definite article 'ال' is not pronounced; instead, the following consonant is emphasised (doubled) in pronunciation, as in 'الشمس' (ash-shams)."),
  _q("Al-Huroof Al-Qamariyyah (الحروف القمرية), the 'moon letters', affect the pronunciation of the definite article 'ال' by causing",
      ["the 'ل' of 'ال' to be clearly pronounced as written", "the 'ل' of 'ال' to be silent", "the noun to lose its definite meaning entirely", "the following letter to be doubled in pronunciation"], "the 'ل' of 'ال' to be clearly pronounced as written",
      "Before moon letters, the lam (ل) of the definite article 'ال' is pronounced clearly and distinctly, as in 'القمر' (al-qamar)."),
  _q("During the Arabic oral examination, correct vocalization of Arabic phonemes, such as differentiating 'ح' from 'ه', is important because",
      ["these letters represent distinct sounds that can change a word's meaning if mispronounced", "all Arabic letters are pronounced identically regardless of context", "pronunciation has no effect on spoken comprehension", "only written Arabic requires accuracy, not spoken Arabic"], "these letters represent distinct sounds that can change a word's meaning if mispronounced",
      "Arabic has several letters with subtly different pronunciations (such as ح and ه) that must be correctly articulated, as confusing them can change a word's meaning."),
  _q("A key skill assessed during the Arabic oral examination's listening component is the ability to",
      ["understand and respond appropriately to spoken Arabic questions or passages", "write a long essay without any spoken interaction", "translate written English text into French", "memorise grammar rules without any application"], "understand and respond appropriately to spoken Arabic questions or passages",
      "The listening component of the oral exam assesses a candidate's ability to comprehend spoken Arabic and respond appropriately and promptly."),
  _q("Swift textual comprehension during an Arabic listening assessment mainly requires candidates to",
      ["quickly grasp the meaning of spoken Arabic without needing extended time to process", "translate every word into English before responding", "ignore the context of the passage entirely", "rely solely on memorised phrases with no comprehension"], "quickly grasp the meaning of spoken Arabic without needing extended time to process",
      "Swift comprehension involves processing and understanding spoken Arabic promptly, allowing the candidate to respond accurately within the assessment's time constraints."),
  _q("A formal Arabic letter, such as a job application, typically begins with an appropriate greeting followed by",
      ["a clear statement of the letter's purpose", "an unrelated personal anecdote", "a list of unrelated vocabulary words", "a poem with no connection to the letter's purpose"], "a clear statement of the letter's purpose",
      "Formal correspondence should clearly state its purpose early on, following an appropriate greeting, to ensure the reader immediately understands the letter's intent."),
  _q("The Arabic greeting 'السلام عليكم' used at the start of a letter or conversation means",
      ["peace be upon you", "goodbye, see you later", "thank you very much", "congratulations on your success"], "peace be upon you",
      "'السلام عليكم' is a traditional Islamic greeting meaning 'peace be upon you', commonly used to open both spoken and written communication."),
  _q("A common closing phrase used at the end of a formal Arabic letter is",
      ["مع خالص التحية والتقدير (with sincere greetings and appreciation)", "إلى اللقاء فقط (just goodbye, with no further phrase)", "لا شيء، الرسالة تنتهي فجأة (nothing, the letter ends abruptly)", "وداعا للأبد (farewell forever)"], "مع خالص التحية والتقدير (with sincere greetings and appreciation)",
      "Formal Arabic letters typically close with a respectful and appreciative phrase, similar in tone to formal closings in other languages."),
  _q("When writing a short composition describing a personal experience, using time expressions such as 'في الصباح' (in the morning) helps to",
      ["clearly situate events within a specific time frame for the reader", "confuse the reader about when events occurred", "replace the need for any verbs in the sentence", "avoid describing any actions at all"], "clearly situate events within a specific time frame for the reader",
      "Time expressions help anchor a narrative in a clear temporal sequence, making the composition easier for the reader to follow."),
  _q("Legible and correct Arabic handwriting (خط واضح) is emphasised in composition assessment mainly because it",
      ["ensures the examiner can accurately read and evaluate the student's work", "has no bearing on how a script is graded", "is only relevant for calligraphy competitions", "replaces the need for correct grammar"], "ensures the examiner can accurately read and evaluate the student's work",
      "Clear handwriting ensures that an examiner can accurately read and properly assess the content, grammar, and structure of a student's written work."),
  _q("In the oral assessment, a candidate asked to describe their daily routine would appropriately use verbs conjugated in the",
      ["present tense (المضارع), to describe habitual actions", "past tense exclusively, even for daily habits", "imperative mood exclusively", "future tense exclusively, ignoring the present"], "present tense (المضارع), to describe habitual actions",
      "Describing a daily routine, which involves habitual or repeated actions, is most naturally expressed using the present tense (Al-Mudari')."),
  _q("A candidate demonstrating good oral fluency in Arabic would typically",
      ["speak with minimal hesitation, using appropriate vocabulary and correct grammar", "pause frequently and struggle to complete sentences", "rely entirely on single-word answers", "avoid answering the examiner's questions directly"], "speak with minimal hesitation, using appropriate vocabulary and correct grammar",
      "Fluency is demonstrated through smooth, confident speech with minimal hesitation, alongside accurate vocabulary and grammar use."),
  _q("During a roleplay exercise in the Arabic oral exam, such as ordering food at a restaurant, candidates are mainly assessed on their ability to",
      ["use appropriate vocabulary and phrases relevant to the given situation", "recite a memorised poem unrelated to the scenario", "write a formal letter instead of speaking", "translate the scenario into English"], "use appropriate vocabulary and phrases relevant to the given situation",
      "Roleplay exercises assess practical communication skills, requiring candidates to use vocabulary and expressions appropriate to a specific everyday scenario."),
  _q("A written Arabic composition describing 'a memorable day' (يوم لا يُنسى) would most naturally use verbs primarily conjugated in the",
      ["past tense (الماضي), since the events being described already occurred", "imperative mood exclusively", "present tense exclusively, ignoring the past", "future tense exclusively"], "past tense (الماضي), since the events being described already occurred",
      "Recounting a memorable day describes completed past events, making the past tense (Al-Madi) the most natural and appropriate choice for the narrative."),
  _q("When preparing for the oral component of the Arabic exam, a useful strategy is to",
      ["practise speaking about common everyday topics, such as family, school, and hobbies", "avoid speaking Arabic aloud until the day of the exam", "focus solely on memorising written grammar rules with no speaking practice", "ignore listening practice entirely"], "practise speaking about common everyday topics, such as family, school, and hobbies",
      "Regular practice discussing familiar, everyday topics helps build the vocabulary and confidence needed to perform well in the oral examination."),
  _q("A key difference between formal and informal Arabic composition styles is that formal writing generally",
      ["uses more elevated vocabulary and complete grammatical structures, avoiding colloquial expressions", "relies heavily on regional dialect and slang", "ignores grammatical accuracy entirely", "is always shorter than informal writing"], "uses more elevated vocabulary and complete grammatical structures, avoiding colloquial expressions",
      "Formal Arabic composition favours Modern Standard Arabic vocabulary and complete grammatical structures, avoiding the colloquial expressions common in informal speech."),
];
