import "../quiz_question.dart";

const _subject = "Building Construction";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// WAEC Building Construction question bank covering the full syllabus:
/// Site Operations & Building Materials, Substructure Work, and
/// Superstructure Work (walls, floors, scaffolding/formwork, stairs, roofs,
/// openings, and finishes/services).
List<QuizQuestion> buildWaecBuildingConstructionQuestions() {
  return [
    ..._siteOperationsAndBuildingMaterials,
    ..._substructureWork,
    ..._superstructureWork,
  ];
}

final _siteOperationsAndBuildingMaterials = [
  _q("The site operation involving the formal transfer of a construction site from the client/consultant to the contractor is called",
      ["handing over", "hoarding", "setting out", "excavation"], "handing over",
      "Handing over marks the formal transfer of the site and relevant documentation to the contractor before construction work begins."),
  _q("The site operation involving the removal of trees, bushes, and debris to prepare land for construction is called",
      ["site clearing", "site levelling", "setting out", "hoarding"], "site clearing",
      "Site clearing removes vegetation, trees, and debris to prepare a clear, workable area before construction begins."),
  _q("The site operation involving the adjustment of ground surfaces to a required uniform gradient is called",
      ["levelling", "clearing", "hoarding", "setting out"], "levelling",
      "Levelling adjusts the ground to the required elevation and gradient in preparation for building works."),
  _q("The temporary protective fencing or boarding erected around a construction site to restrict public access is called",
      ["hoarding", "setting out", "levelling", "excavation"], "hoarding",
      "Hoarding is a temporary barrier erected around a site to prevent unauthorised access and protect the public from construction hazards."),
  _q("The process of transferring the exact position and dimensions of a proposed building from the drawing onto the actual ground is called",
      ["setting out", "hoarding", "levelling", "handing over"], "setting out",
      "Setting out translates the building's design dimensions and position from the drawings onto the physical site, guiding excavation and construction."),
  _q("Temporary boards fixed at the corners of a building site, used to hold reference lines (profiles) during setting out, are called",
      ["profile boards", "hoarding boards", "formwork boards", "scaffold boards"], "profile boards",
      "Profile boards, positioned beyond the excavation area, hold string lines marking the building's exact corners and wall positions."),
  _q("The construction method using a 3:4:5 ratio of side lengths to accurately establish a 90-degree right angle on site is called the",
      ["3:4:5 triangulation method", "diagonal checking method", "profile boarding method", "hoarding method"], "3:4:5 triangulation method",
      "The 3:4:5 method uses the Pythagorean relationship (3² + 4² = 5²) to construct an accurate right angle using simple measuring tape and pegs."),
  _q("Checking that the diagonals of a rectangular building layout are equal in length is done primarily to confirm",
      ["that the building's corners are square (at right angles)", "the total area of the building", "the depth of the foundation", "the type of soil present on site"], "that the building's corners are square (at right angles)",
      "Equal diagonal measurements in a rectangular layout confirm that all four corners are true right angles, verifying the layout's squareness."),
  _q("The process of digging a narrow, elongated excavation to receive a strip foundation is called",
      ["trench excavation", "site levelling", "hoarding", "setting out"], "trench excavation",
      "Trench excavation creates the narrow channel needed to accommodate a strip foundation beneath a building's walls."),
  _q("Temporary timber supports used to prevent the collapse of trench walls during excavation, especially in loose soil, are called",
      ["timbering (shoring)", "profile boards", "hoarding", "formwork"], "timbering (shoring)",
      "Timbering (shoring) supports the sides of an excavation to prevent collapse, particularly critical in loose or unstable soil conditions."),
  _q("In firm, stable soils, the amount of timbering required to support a trench is generally",
      ["less than in loose or unstable soils", "the same as in loose soils regardless of stability", "greater than in loose soils", "completely unnecessary in all cases"], "less than in loose or unstable soils",
      "Firm, cohesive soils are more self-supporting, generally requiring less extensive timbering compared to loose, unstable, or sandy soils."),
  _q("The binding building material produced by heating limestone and clay, then grinding the resulting clinker into a fine powder, is called",
      ["cement", "sand", "gravel", "aggregate"], "cement",
      "Cement is manufactured by heating limestone and clay to form clinker, which is then finely ground, and acts as the binding agent in concrete and mortar."),
  _q("A concrete mix ratio of 1:2:4 typically refers to the proportions of",
      ["cement, sand, and coarse aggregate", "cement, water, and sand only", "sand, gravel, and water only", "cement, gravel, and steel reinforcement"], "cement, sand, and coarse aggregate",
      "A 1:2:4 mix ratio specifies one part cement, two parts sand (fine aggregate), and four parts coarse aggregate by volume."),
  _q("The test used to assess the workability (consistency) of freshly mixed concrete before it sets is called the",
      ["slump test", "compression test", "tensile test", "moisture test"], "slump test",
      "The slump test measures how much a sample of fresh concrete settles under its own weight, indicating its workability for placement."),
  _q("Building blocks manufactured from a mixture of cement, sand, and aggregate, cast and cured to a standard size, are called",
      ["concrete blocks", "bricks", "timber blocks", "glass blocks"], "concrete blocks",
      "Concrete blocks are manufactured from a cement-sand-aggregate mixture, cast into standard shapes and cured before use in construction."),
  _q("Building units manufactured from moulded and fired clay, traditionally used for wall construction, are called",
      ["bricks", "concrete blocks", "timber", "aggregate"], "bricks",
      "Bricks are made from clay, shaped and fired at high temperatures to produce durable units for building construction."),
  _q("Metals such as iron and steel, which contain iron as their main constituent, are classified as",
      ["ferrous metals", "non-ferrous metals", "aggregates", "bituminous products"], "ferrous metals",
      "Ferrous metals contain iron as a primary constituent, distinguishing them from non-ferrous metals like aluminium and copper."),
  _q("Metals such as aluminium, copper, and zinc, which do not contain iron as their main constituent, are classified as",
      ["non-ferrous metals", "ferrous metals", "aggregates", "bituminous products"], "non-ferrous metals",
      "Non-ferrous metals lack iron as a primary constituent, generally offering advantages such as corrosion resistance compared to ferrous metals."),
  _q("Waterproofing products such as bitumen and asphalt, used to protect building elements from moisture penetration, are classified as",
      ["bituminous products", "ferrous metals", "aggregates", "plastics"], "bituminous products",
      "Bituminous products, derived from petroleum, provide effective waterproofing for roofs, foundations, and other building elements."),
  _q("Sand and gravel used as filler materials in concrete, providing bulk and strength, are collectively known as",
      ["aggregates", "cement", "bituminous products", "ferrous metals"], "aggregates",
      "Aggregates (sand and gravel/crushed stone) form the bulk of concrete, with cement acting as the binding agent holding them together."),
  _q("Synthetic materials, such as PVC pipes and plastic sheeting, increasingly used in modern construction for their durability and low cost, are classified as",
      ["plastics", "ferrous metals", "aggregates", "bituminous products only"], "plastics",
      "Plastics are widely used in modern construction for applications such as piping, insulation, and sheeting, valued for durability and cost-effectiveness."),
  _q("A concrete mix ratio of 1:3:6 is generally used for applications requiring",
      ["lower strength, such as mass concrete or blinding layers", "the highest possible structural strength, such as suspended beams", "waterproofing membranes only", "decorative surface finishes only"], "lower strength, such as mass concrete or blinding layers",
      "A leaner 1:3:6 mix, with less cement relative to aggregate, is typically used for lower-strength applications such as blinding layers or mass concrete fill."),
  _q("Glass used in building construction, such as for windows, is valued mainly for its",
      ["transparency, allowing natural light into a building", "high compressive strength for structural columns", "ability to bind aggregate together", "use as a waterproofing membrane"], "transparency, allowing natural light into a building",
      "Glass is primarily valued in construction for its transparency, allowing daylight to enter a building while providing weather protection."),
  _q("Timber used in building construction requires proper seasoning (drying) mainly to",
      ["reduce its moisture content and minimise shrinkage or warping after installation", "increase its weight for structural stability", "change its natural colour permanently", "eliminate the need for any further treatment against pests"], "reduce its moisture content and minimise shrinkage or warping after installation",
      "Seasoning timber reduces its moisture content before use, minimising the risk of shrinkage, warping, or splitting once installed in a building."),
];

final _substructureWork = [
  _q("The part of a building structure below ground level, transferring the building's load safely to the supporting soil, is called the",
      ["foundation (substructure)", "superstructure", "roof", "scaffold"], "foundation (substructure)",
      "The foundation (substructure) transfers the entire load of a building safely into the ground, and its design depends on soil bearing capacity."),
  _q("The maximum load per unit area that a soil can safely support without excessive settlement or failure is called its",
      ["bearing capacity", "moisture content", "slump value", "compaction ratio"], "bearing capacity",
      "Soil bearing capacity determines how much load the ground can safely carry, directly influencing foundation design and depth."),
  _q("A continuous foundation running beneath load-bearing walls, typically used for simple building structures, is called a",
      ["strip foundation", "pad (isolated) footing", "raft foundation", "pile foundation"], "strip foundation",
      "Strip foundations run continuously beneath load-bearing walls, distributing the wall's load evenly along its length into the ground."),
  _q("A foundation consisting of individual, separate concrete bases supporting isolated columns is called a",
      ["pad (isolated) footing", "strip foundation", "raft foundation", "pile foundation"], "pad (isolated) footing",
      "Pad (isolated) footings support individual columns separately, rather than running continuously as with strip foundations."),
  _q("A foundation consisting of a single continuous concrete slab covering the entire building area, used especially on weak or variable soils, is called a",
      ["raft (mat) foundation", "strip foundation", "pad footing", "pile foundation"], "raft (mat) foundation",
      "A raft (mat) foundation spreads the building's total load over a large continuous slab, useful on weak or variable soil conditions."),
  _q("A foundation using long columns driven or bored deep into the ground to reach stable, load-bearing strata, is called a",
      ["pile foundation", "strip foundation", "pad footing", "raft foundation"], "pile foundation",
      "Pile foundations transfer building loads deep into the ground to reach strong, stable soil or rock layers, especially useful where surface soils are weak."),
  _q("Broken stones or rubble laid and compacted as a base layer beneath a ground floor slab is called",
      ["hardcore", "sand blinding", "damp-proof membrane", "oversite concrete"], "hardcore",
      "Hardcore consists of compacted broken stone or rubble, providing a stable, well-drained base layer beneath a floor slab."),
  _q("A thin layer of fine sand spread over hardcore to fill surface voids before laying a damp-proof membrane is called",
      ["sand blinding", "hardcore", "oversite concrete", "damp-proof course"], "sand blinding",
      "Sand blinding fills the surface irregularities of a hardcore layer, providing a smoother base for the damp-proof membrane above."),
  _q("A waterproof sheet material laid beneath a ground floor slab to prevent rising moisture from the ground is called a",
      ["damp-proof membrane (DPM)", "sand blinding layer", "hardcore layer", "oversite concrete"], "damp-proof membrane (DPM)",
      "The damp-proof membrane (DPM) is a waterproof layer that prevents ground moisture from rising into the floor slab and building interior."),
  _q("The concrete layer cast directly on top of the hardcore, sand blinding, and damp-proof membrane to form the ground floor base is called the",
      ["oversite concrete bed", "raft foundation", "pad footing", "strip foundation"], "oversite concrete bed",
      "The oversite concrete bed forms the solid ground floor base, cast over the prepared hardcore, sand blinding, and damp-proof membrane layers."),
  _q("A key factor considered when selecting the appropriate foundation type for a building is the",
      ["soil bearing capacity and ground conditions at the site", "colour of the building's exterior finish", "type of roof covering to be used", "number of paint coats to be applied"], "soil bearing capacity and ground conditions at the site",
      "Foundation selection depends heavily on the site's soil conditions and bearing capacity, ensuring the chosen foundation can safely support the building's loads."),
  _q("Pile foundations are generally preferred over shallow foundations when",
      ["the soil near the surface has poor bearing capacity, requiring loads to be transferred to deeper, stronger strata", "the surface soil already has excellent bearing capacity", "the building is very light and single-storey", "cost is the only consideration, regardless of soil conditions"], "the soil near the surface has poor bearing capacity, requiring loads to be transferred to deeper, stronger strata",
      "Piles are chosen when surface soils cannot adequately support a building's loads, allowing the load to be transferred down to deeper, more stable soil or rock layers."),
  _q("The width of a strip foundation is primarily determined by",
      ["the load of the wall above and the bearing capacity of the supporting soil", "the colour of the finished wall", "the type of roof to be constructed", "the number of windows in the building"], "the load of the wall above and the bearing capacity of the supporting soil",
      "Strip foundation width is calculated to ensure the load from the wall above is spread over a sufficient area of ground, based on the soil's bearing capacity."),
  _q("Before casting the oversite concrete bed, it is important to first ensure that the hardcore layer is",
      ["well compacted and blinded with sand to provide an even surface", "left loose and uncompacted", "removed entirely before concreting", "installed after the concrete has already been cast"], "well compacted and blinded with sand to provide an even surface",
      "Proper compaction and sand blinding of the hardcore layer provides a stable, even base, preventing settlement issues beneath the finished floor slab."),
  _q("A raft foundation is often chosen over a strip or pad foundation mainly to",
      ["spread the building's load over a wide area on weak or variable soil conditions", "reduce the overall cost of excavation in all soil types", "eliminate the need for a damp-proof membrane", "increase the depth of excavation required unnecessarily"], "spread the building's load over a wide area on weak or variable soil conditions",
      "Raft foundations distribute a building's total load across a large continuous area, making them particularly suitable for weak or inconsistent soil conditions."),
];

final _superstructureWork = [
  _q("A wall designed to carry and transfer structural loads from the roof and floors down to the foundation is called a",
      ["load-bearing wall", "non-load-bearing (partition) wall", "cavity wall only", "retaining wall only"], "load-bearing wall",
      "Load-bearing walls support and transfer structural loads from above down through the wall to the foundation."),
  _q("A wall used only to divide internal spaces, without carrying any structural load from the building above, is called a",
      ["non-load-bearing (partition) wall", "load-bearing wall", "retaining wall", "curtain wall"], "non-load-bearing (partition) wall",
      "Non-load-bearing (partition) walls simply divide interior spaces and do not support structural loads from the building above."),
  _q("A common brickwork bond in which each brick is laid so that only its shorter end (header) is not visible, showing mostly the long face (stretcher), is called the",
      ["stretcher bond", "English bond", "Flemish bond", "header bond"], "stretcher bond",
      "Stretcher bond shows the long face (stretcher) of each brick in every course, one of the simplest and most common bonding patterns."),
  _q("A brickwork bond alternating complete courses of headers and complete courses of stretchers is called the",
      ["English bond", "stretcher bond", "Flemish bond", "header bond only"], "English bond",
      "English bond alternates whole courses of headers with whole courses of stretchers, producing a strong, traditional bonding pattern."),
  _q("A brickwork bond alternating headers and stretchers within each individual course is called the",
      ["Flemish bond", "English bond", "stretcher bond", "header bond only"], "Flemish bond",
      "Flemish bond alternates headers and stretchers within the same course, producing a distinctive decorative pattern while maintaining structural strength."),
  _q("A structural member placed above a door or window opening to support the wall load above it is called a",
      ["lintel", "arch", "column", "damp-proof course"], "lintel",
      "A lintel spans across an opening, such as a door or window, transferring the load of the wall above safely to the sides."),
  _q("A curved structural member spanning an opening, transferring load through compression along its curve, is called an",
      ["arch", "lintel", "column", "truss"], "arch",
      "An arch spans an opening using a curved shape, transferring loads through compression down to its supporting piers."),
  _q("A vertical structural member that transfers loads from beams or slabs down to the foundation is called a",
      ["column", "lintel", "arch", "purlin"], "column",
      "Columns are vertical members that carry loads from beams, slabs, or roofs, transferring them down to the foundation."),
  _q("A continuous impervious layer built into a wall at plinth level, preventing rising dampness from entering the wall above ground, is called the",
      ["damp-proof course (DPC)", "damp-proof membrane", "hardcore layer", "sand blinding layer"], "damp-proof course (DPC)",
      "The damp-proof course (DPC) is installed within the wall at plinth level to block rising ground moisture from penetrating higher into the structure."),
  _q("A floor constructed using timber joists supporting floorboards, common in some residential upper floors, is called a",
      ["timber floor", "solid concrete slab floor", "hollow pot (ribbed) floor", "raft floor"], "timber floor",
      "Timber floors use joists to support floorboards, a lightweight construction method commonly used for upper floors in residential buildings."),
  _q("A floor constructed as a continuous cast reinforced concrete slab, without hollow blocks or ribs, is called a",
      ["solid concrete slab floor", "timber floor", "hollow pot (ribbed) floor", "raft floor only"], "solid concrete slab floor",
      "A solid concrete slab floor is cast as one continuous reinforced concrete section, without internal voids."),
  _q("A reinforced concrete floor incorporating hollow blocks (pots) between concrete ribs to reduce weight and material use is called a",
      ["hollow pot (ribbed) floor", "solid concrete slab floor", "timber floor", "raft floor"], "hollow pot (ribbed) floor",
      "Hollow pot (ribbed) floors incorporate lightweight hollow blocks between structural concrete ribs, reducing the overall weight and material cost of the floor."),
  _q("A hard-wearing floor finish made from marble or granite chips set in cement or resin and polished smooth is called",
      ["terrazzo", "screeding", "tiling", "plastering"], "terrazzo",
      "Terrazzo is a durable, decorative flooring finish made from marble or granite chips set in a binder and polished to a smooth surface."),
  _q("A thin layer of mortar applied over a concrete floor to provide a smooth, level surface for further finishing is called",
      ["screeding", "terrazzo", "tiling", "plastering"], "screeding",
      "Screeding applies a thin, level mortar layer over a concrete floor base, preparing it for the final floor finish."),
  _q("A temporary structure erected around a building to provide access and support for workers and materials during construction is called",
      ["scaffolding", "formwork", "hoarding", "hardcore"], "scaffolding",
      "Scaffolding provides safe temporary access and working platforms for construction workers at various heights around a building."),
  _q("Scaffolding erected independently of the building, supported entirely by its own vertical and horizontal members without relying on the wall, is called",
      ["independent scaffolding", "putlog scaffolding", "formwork", "hoarding"], "independent scaffolding",
      "Independent scaffolding stands entirely on its own structural framework, without needing support from the building under construction."),
  _q("Scaffolding partly supported by inserting horizontal tubes (putlogs) directly into the joints of the building's wall as it is constructed is called",
      ["putlog scaffolding", "independent scaffolding", "formwork", "hoarding"], "putlog scaffolding",
      "Putlog scaffolding relies partly on the building itself for support, with putlog tubes resting in specially left joints within the rising wall."),
  _q("The vertical tubes in a scaffold structure that transfer load down to the ground are called",
      ["standards", "ledgers", "transoms", "putlogs only"], "standards",
      "Standards are the vertical scaffold tubes that bear the overall load and transfer it safely down to the ground."),
  _q("The horizontal tubes in a scaffold structure that connect the standards together, running parallel to the building, are called",
      ["ledgers", "standards", "transoms", "putlogs only"], "ledgers",
      "Ledgers are horizontal scaffold tubes connecting standards together, running parallel to the face of the building."),
  _q("The horizontal tubes in a scaffold structure that span across the ledgers, supporting the scaffold boards, are called",
      ["transoms", "ledgers", "standards", "putlogs only"], "transoms",
      "Transoms span across the ledgers at right angles, providing the direct support for the scaffold's working boards."),
  _q("A temporary mould constructed to hold wet concrete in place until it gains sufficient strength to be self-supporting is called",
      ["formwork (shuttering)", "scaffolding", "hoarding", "hardcore"], "formwork (shuttering)",
      "Formwork (shuttering) temporarily contains and shapes wet concrete for elements such as columns, beams, and slabs until the concrete cures."),
  _q("In stair terminology, the horizontal surface of a step on which a person places their foot is called the",
      ["tread", "riser", "going", "nosing"], "tread",
      "The tread is the horizontal top surface of a stair step, providing the walking surface for each step."),
  _q("In stair terminology, the vertical surface between two consecutive treads is called the",
      ["riser", "tread", "going", "pitch"], "riser",
      "The riser is the vertical face of a stair step, connecting one tread to the next."),
  _q("In stair terminology, the horizontal distance measured from the face of one riser to the face of the next is called the",
      ["going", "tread", "riser", "nosing"], "going",
      "The going measures the horizontal distance between successive risers, an important dimension in stair design."),
  _q("In stair terminology, the small projecting edge of a tread that overhangs the riser below is called the",
      ["nosing", "going", "riser", "pitch"], "nosing",
      "The nosing is the projecting front edge of a tread, extending slightly over the riser beneath it, often to improve grip and appearance."),
  _q("In stair terminology, the angle of inclination of a staircase relative to the horizontal is called the",
      ["pitch", "going", "riser", "headroom"], "pitch",
      "The pitch describes the angle at which a staircase is inclined, an important consideration for comfort and safety of use."),
  _q("In stair terminology, the vertical clearance distance between a stair tread and the ceiling or structure above it is called the",
      ["headroom", "pitch", "going", "nosing"], "headroom",
      "Headroom is the vertical clearance above a stair, ensuring users have adequate space to walk without striking their head."),
  _q("A roof design with a single sloping surface, often built against an existing wall, is called a",
      ["lean-to roof", "gable roof", "hip roof", "mansard roof"], "lean-to roof",
      "A lean-to roof has a single sloping surface, typically leaning against an existing higher wall or structure."),
  _q("A roof design with two sloping surfaces meeting at a ridge, with triangular vertical wall sections (gables) at each end, is called a",
      ["gable roof", "lean-to roof", "hip roof", "flat roof"], "gable roof",
      "A gable roof has two sloping sides meeting at a central ridge, with the triangular gable ends visible at either side."),
  _q("A roof design with sloping surfaces on all four sides, meeting at a ridge, without vertical gable ends, is called a",
      ["hip roof", "gable roof", "lean-to roof", "flat roof"], "hip roof",
      "A hip roof slopes on all four sides, converging at a central ridge, without the vertical triangular gable ends seen in gable roofs."),
  _q("A roof design combining two different slopes on each side, with the lower slope steeper than the upper, is called a",
      ["mansard roof", "gable roof", "hip roof", "lean-to roof"], "mansard roof",
      "A mansard roof has two distinct slopes on each side, with a steeper lower slope and a shallower upper slope, often maximising usable attic space."),
  _q("The horizontal timber member fixed along the top of a wall, providing a level base to which the roof structure is fixed, is called the",
      ["wall plate", "purlin", "king post", "common rafter"], "wall plate",
      "The wall plate is a horizontal timber fixed along the top of a wall, distributing the roof's load evenly and providing an anchor point for rafters."),
  _q("The sloping timber members running from the wall plate to the ridge, forming the main structural framework of a pitched roof, are called",
      ["common rafters", "purlins", "wall plates", "king posts"], "common rafters",
      "Common rafters are the sloping structural members running from the wall plate up to the ridge, forming the roof's basic skeleton."),
  _q("A horizontal timber member providing intermediate support to rafters along their length, reducing the span they must cover unsupported, is called a",
      ["purlin", "common rafter", "wall plate", "king post"], "purlin",
      "Purlins run horizontally across rafters, providing intermediate support that reduces the unsupported span of the rafters."),
  _q("The central vertical member in a traditional timber roof truss, supporting the ridge and transferring load down to the tie beam, is called the",
      ["king post", "purlin", "wall plate", "common rafter"], "king post",
      "The king post is the central vertical member of a traditional roof truss, connecting the ridge to the tie beam and helping to carry the roof's load."),
  _q("A prefabricated triangulated framework used to support a roof's structure over a wide span is called a",
      ["truss", "wall plate", "purlin", "king post alone"], "truss",
      "A truss is a triangulated framework, often prefabricated, designed to efficiently support a roof over a wide span."),
  _q("A common lightweight roof covering material made from corrugated metal or fibre-cement sheets is called",
      ["corrugated roofing sheets", "roof tiles", "roofing felt", "terrazzo"], "corrugated roofing sheets",
      "Corrugated sheets, made from metal or fibre-cement, are a widely used, lightweight, and cost-effective roof covering material."),
  _q("A door constructed with solid or raised sections framed within stiles and rails, often used for a traditional decorative appearance, is called a",
      ["panel door", "flush door", "louvre door", "sliding door"], "panel door",
      "Panel doors feature raised or recessed panels set within a surrounding timber frame, giving a traditional decorative appearance."),
  _q("A door with a smooth, flat surface on both sides, typically constructed from a hollow or solid core covered by plywood or hardboard, is called a",
      ["flush door", "panel door", "louvre door", "ledged and braced door"], "flush door",
      "Flush doors have a completely flat, smooth surface, constructed by covering a solid or hollow core with a plywood or hardboard skin."),
  _q("A simple, traditional door constructed from vertical boards held together by horizontal ledges and diagonal braces is called a",
      ["ledged and braced door", "flush door", "panel door", "louvre door"], "ledged and braced door",
      "Ledged and braced doors are made from vertical boards fixed to horizontal ledges and diagonal braces, a simple, sturdy traditional construction."),
  _q("A window with one or more hinged sashes that open outward or inward like a door is called a",
      ["casement window", "sliding window", "louvre window", "pivoting window"], "casement window",
      "Casement windows have hinged sashes that swing open, similar to a door, providing good ventilation control."),
  _q("A window with sashes that move horizontally past each other within a frame, rather than swinging open, is called a",
      ["sliding window", "casement window", "louvre window", "pivoting window"], "sliding window",
      "Sliding windows open by moving one sash horizontally along a track, rather than swinging outward or inward."),
  _q("A window made up of angled, overlapping glass or metal slats that can be adjusted to control airflow is called a",
      ["louvre window", "casement window", "sliding window", "pivoting window"], "louvre window",
      "Louvre windows consist of adjustable, overlapping slats that can be tilted to control ventilation while providing some weather protection."),
  _q("Hardware fittings such as hinges, locks, and door handles, used on doors and windows, are collectively known as",
      ["ironmongery", "formwork", "scaffolding", "aggregate"], "ironmongery",
      "Ironmongery refers to the metal fittings and hardware, such as hinges, locks, and handles, used on doors and windows."),
  _q("The application of a smooth, protective, and decorative coating of mortar to internal wall surfaces is called",
      ["plastering", "rendering", "screeding", "terrazzo finishing"], "plastering",
      "Plastering applies a smooth mortar finish to internal wall surfaces, providing a suitable base for decoration and additional protection."),
  _q("The application of a protective and decorative coating of mortar to external wall surfaces is called",
      ["rendering", "plastering", "screeding", "terrazzo finishing"], "rendering",
      "Rendering applies a protective mortar coating to external wall surfaces, improving weather resistance and appearance."),
  _q("A drainage system specifically designed to collect and dispose of rainwater from roofs and paved surfaces is called the",
      ["surface water drainage system", "soil water drainage system", "septic system", "soakaway pit alone"], "surface water drainage system",
      "Surface water drainage systems collect and dispose of rainwater runoff from roofs, driveways, and other paved surfaces."),
  _q("A drainage system specifically designed to carry wastewater from toilets and similar sanitary fittings is called the",
      ["soil water drainage system", "surface water drainage system", "septic system alone", "soakaway pit alone"], "soil water drainage system",
      "Soil water drainage systems carry foul wastewater from toilets and similar fittings away from the building for treatment or disposal."),
  _q("An underground tank system that treats sewage on-site where a connection to a public sewer is unavailable is called a",
      ["septic tank system", "soakaway pit alone", "surface water drain alone", "damp-proof membrane"], "septic tank system",
      "A septic tank system treats and partially breaks down sewage on-site, commonly used where mains sewer connections are unavailable."),
  _q("An underground pit filled with rubble or gravel, allowing treated wastewater or surface water to gradually soak into the surrounding ground, is called a",
      ["soakaway pit", "septic tank", "damp-proof course", "hardcore bed"], "soakaway pit",
      "A soakaway pit allows water to disperse gradually into the surrounding soil, commonly used alongside septic systems or for surface water disposal."),
  _q("The protective tubes or channels installed within walls and floors to route electrical wiring safely through a building are called",
      ["electrical conduits", "plumbing pipes", "damp-proof membranes", "formwork panels"], "electrical conduits",
      "Electrical conduits protect and route wiring safely through the walls, floors, and ceilings of a building."),
  _q("The main purpose of installing a damp-proof course (DPC) at plinth level in a wall is to",
      ["prevent rising ground moisture from penetrating the wall above ground level", "increase the compressive strength of the wall", "reduce the overall weight of the building", "improve the wall's fire resistance rating"], "prevent rising ground moisture from penetrating the wall above ground level",
      "The DPC forms a continuous impervious barrier within the wall at plinth level, specifically blocking rising damp from travelling further up the structure."),
  _q("A cavity wall, consisting of two separate wall leaves with an air gap between them, is primarily constructed to",
      ["improve resistance to moisture penetration and thermal insulation", "reduce the overall foundation depth required", "eliminate the need for a damp-proof course entirely", "simplify the roof structure above"], "improve resistance to moisture penetration and thermal insulation",
      "Cavity walls use an air gap between two wall leaves to help prevent moisture penetration to the inner leaf and improve thermal insulation."),
  _q("A key advantage of reinforced concrete floors over timber floors is their",
      ["greater fire resistance and durability", "significantly lighter weight", "lower material cost in every situation", "faster construction time in every situation"], "greater fire resistance and durability",
      "Reinforced concrete floors generally offer superior fire resistance and long-term durability compared to timber floor construction."),
  _q("The primary purpose of formwork in reinforced concrete construction is to",
      ["contain and shape the wet concrete until it has gained sufficient strength", "reinforce the concrete against tension forces", "waterproof the finished concrete surface", "provide the finished decorative surface texture in every case"], "contain and shape the wet concrete until it has gained sufficient strength",
      "Formwork temporarily holds and shapes wet concrete during casting and early curing, until the concrete is strong enough to support itself."),
  _q("A key safety consideration when designing a staircase is ensuring consistent",
      ["tread and riser dimensions throughout the flight, to avoid trip hazards", "colour scheme matching the surrounding walls", "material cost regardless of dimensions", "decorative pattern on the underside of the stair"], "tread and riser dimensions throughout the flight, to avoid trip hazards",
      "Uneven tread or riser dimensions within a single staircase flight create serious trip hazards, so consistency is a key safety requirement in stair design."),
  _q("The primary function of a roof truss in building construction is to",
      ["support the roof covering and transfer its load safely to the supporting walls", "provide the internal partition walls of the building", "form the building's foundation", "serve as the primary damp-proofing layer"], "support the roof covering and transfer its load safely to the supporting walls",
      "Roof trusses form the structural skeleton that carries the roof covering's load and transfers it safely down to the supporting walls."),
  _q("A flat roof design, as opposed to a pitched roof, requires particular attention to",
      ["effective waterproofing and drainage to prevent water ponding", "the installation of a ridge board", "the construction of gable ends", "the use of common rafters exclusively"], "effective waterproofing and drainage to prevent water ponding",
      "Because flat roofs lack the natural water run-off of a pitched design, they require especially careful waterproofing and drainage design to avoid ponding and leaks."),
  _q("Ledged and braced doors are generally considered less suitable for external use in exposed conditions mainly because they",
      ["can be prone to warping and sagging over time without a rigid perimeter frame", "are more expensive to manufacture than panel doors", "cannot be fitted with any locks or hinges", "are always made only from metal"], "can be prone to warping and sagging over time without a rigid perimeter frame",
      "Without a rigid perimeter frame like a panel door, ledged and braced doors can be more prone to warping or sagging over time, particularly under weather exposure."),
  _q("Effective site drainage design for a building plot is important mainly to",
      ["prevent water accumulation that could damage the foundation or superstructure", "increase the overall cost of construction unnecessarily", "eliminate the need for a damp-proof course", "replace the need for a proper foundation design"], "prevent water accumulation that could damage the foundation or superstructure",
      "Well-planned site drainage prevents water from accumulating around a building, protecting both the foundation and the superstructure from moisture-related damage."),
  _q("The choice between a gable roof and a hip roof for a building often depends partly on",
      ["the desired architectural appearance and the building's exposure to wind", "the type of foundation used beneath the building", "the colour of the internal wall paint", "the depth of the damp-proof course installed"], "the desired architectural appearance and the building's exposure to wind",
      "Roof type selection is influenced by both aesthetic preference and practical factors such as wind exposure, since hip roofs can offer better wind resistance than gable roofs."),
];
