import "../quiz_question.dart";

const _subject = "Physics";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// WAEC Physics — Waves & Fields cluster, covering:
/// Waves (wave motion, wave phenomena, geometric optics, sound), Electricity,
/// Magnetism and Fields (electrostatics, current electricity, magnetism,
/// electromagnetism), and Modern Physics and Technology (atomic structure,
/// radioactivity, electronics).
List<QuizQuestion> buildWaecPhysicsFieldsQuestions() {
  return [
    ..._waveMotion,
    ..._wavePhenomena,
    ..._mirrors,
    ..._refraction,
    ..._lenses,
    ..._soundWaves,
    ..._electrostatics,
    ..._currentElectricity,
    ..._magnetism,
    ..._electromagnetism,
    ..._atomicStructure,
    ..._radioactivity,
    ..._electronics,
  ];
}

final _waveMotion = [
  _q("In a transverse wave, the particles of the medium vibrate",
      ["perpendicular to the direction of propagation of the wave", "parallel to the direction of propagation of the wave", "in circles around a fixed point", "only at the source of the wave"], "perpendicular to the direction of propagation of the wave",
      "A transverse wave (e.g. a water wave or light wave) has particles oscillating at right angles to the direction the wave energy travels, producing crests and troughs."),
  _q("In a longitudinal wave, the particles of the medium vibrate",
      ["parallel to the direction of propagation, producing compressions and rarefactions", "perpendicular to the direction of propagation", "in a fixed circular path", "only when the wave is reflected"], "parallel to the direction of propagation, producing compressions and rarefactions",
      "Longitudinal waves, such as sound, have particles oscillating back and forth along the same line as the wave travels, creating regions of compression and rarefaction."),
  _q("The amplitude of a wave is defined as its",
      ["maximum displacement from the equilibrium (rest) position", "distance between two successive crests", "number of complete oscillations per second", "time taken for one complete oscillation"], "maximum displacement from the equilibrium (rest) position",
      "Amplitude measures how far a particle moves from its rest position at the peak of its oscillation, and it determines the energy (and, for sound, the loudness) of the wave."),
  _q("The period of a wave is defined as the",
      ["time taken to complete one full oscillation (cycle)", "distance travelled by the wave in one second", "number of oscillations per second", "maximum displacement of a particle from rest"], "time taken to complete one full oscillation (cycle)",
      "Period (T) is the time for one complete cycle of the wave; it is the reciprocal of frequency, T = 1/f."),
  _q("The frequency of a wave is defined as the",
      ["number of complete oscillations (cycles) produced per second", "distance between two successive crests", "time taken for one complete oscillation", "maximum displacement from equilibrium"], "number of complete oscillations (cycles) produced per second",
      "Frequency (f), measured in hertz (Hz), counts how many complete wave cycles pass a point per second; it is related to period by f = 1/T."),
  _q("A wave of frequency 250 Hz has a wavelength of 1.4 m. What is its speed?",
      ["350 m/s", "178.6 m/s", "251.4 m/s", "0.0056 m/s"], "350 m/s",
      "Using v = f x wavelength: v = 250 x 1.4 = 350 m/s."),
  _q("A sound wave travels at 340 m/s and has a frequency of 170 Hz. What is its wavelength?",
      ["2 m", "0.5 m", "340 m", "170 m"], "2 m",
      "Wavelength = v/f = 340/170 = 2 m."),
  _q("A progressive (travelling) wave differs from a stationary (standing) wave mainly in that a progressive wave",
      ["transfers energy from one point to another as it travels through the medium", "has fixed nodes and antinodes that do not move", "cannot be reflected", "only exists in electromagnetic media"], "transfers energy from one point to another as it travels through the medium",
      "A progressive wave carries energy away from its source, with every particle eventually repeating the same motion at a time delay; a stationary wave, formed by two identical waves travelling in opposite directions, has fixed points (nodes) of zero displacement and does not transfer net energy."),
  _q("In a stationary wave, the distance between two adjacent nodes is",
      ["half a wavelength", "one full wavelength", "a quarter of a wavelength", "twice the wavelength"], "half a wavelength",
      "Stationary waves have nodes (points of no displacement) spaced at intervals of half a wavelength, with antinodes (points of maximum displacement) midway between them."),
  _q("A wave completes one oscillation every 0.02 s. What is its frequency?",
      ["50 Hz", "0.02 Hz", "20 Hz", "500 Hz"], "50 Hz",
      "Frequency f = 1/T = 1/0.02 = 50 Hz."),
];

final _wavePhenomena = [
  _q("Reflection of a wave occurs when the wave",
      ["bounces back into the original medium after striking a surface or boundary", "changes direction while passing into a new medium", "bends around an obstacle in its path", "combines with another wave to change amplitude"], "bounces back into the original medium after striking a surface or boundary",
      "Reflection describes a wave being turned back at a boundary, remaining in the same medium, with the angle of incidence equal to the angle of reflection."),
  _q("Refraction of a wave occurs when the wave",
      ["changes speed and direction as it passes from one medium into another", "is absorbed completely by the new medium", "spreads out after passing through a narrow gap", "combines with a similar wave to produce a stronger wave"], "changes speed and direction as it passes from one medium into another",
      "Refraction is the bending of a wave due to a change in its speed as it crosses a boundary between media of different densities (or optical properties)."),
  _q("Diffraction of a wave is the",
      ["spreading of a wave as it passes through a narrow gap or around an obstacle", "bouncing back of a wave from a surface", "bending of a wave as it changes medium", "combination of two waves to produce a new wave pattern"], "spreading of a wave as it passes through a narrow gap or around an obstacle",
      "Diffraction becomes most noticeable when the size of the gap or obstacle is comparable to the wavelength of the wave, causing it to spread into the region behind the obstacle."),
  _q("Interference of waves occurs when",
      ["two coherent waves overlap (superpose) to produce a resultant wave of different amplitude", "a wave changes speed on entering a new medium", "a wave is completely absorbed by a barrier", "a wave reflects off a rigid surface"], "two coherent waves overlap (superpose) to produce a resultant wave of different amplitude",
      "Interference results from the superposition principle: when two coherent waves overlap, their displacements add algebraically, producing points of reinforcement or cancellation."),
  _q("Constructive interference occurs at points where the path difference between two coherent waves is",
      ["a whole number of wavelengths (0, wavelength, 2 x wavelength, ...)", "an odd number of half wavelengths", "exactly a quarter of a wavelength", "always zero regardless of the waves"], "a whole number of wavelengths (0, wavelength, 2 x wavelength, ...)",
      "When the path difference equals a whole number of wavelengths, the waves arrive in phase and reinforce each other, producing maximum amplitude (constructive interference)."),
  _q("Destructive interference occurs at points where the path difference between two coherent waves is",
      ["an odd number of half wavelengths", "a whole number of wavelengths", "zero", "twice the wavelength"], "an odd number of half wavelengths",
      "When the path difference is an odd multiple of half a wavelength, the two waves arrive out of phase and cancel each other, producing minimum (or zero) amplitude."),
  _q("Polarization is a phenomenon that can occur only in",
      ["transverse waves, since longitudinal waves have no perpendicular vibration to restrict", "longitudinal waves only", "both transverse and longitudinal waves equally", "sound waves travelling in air"], "transverse waves, since longitudinal waves have no perpendicular vibration to restrict",
      "Polarization restricts the vibration of a transverse wave to a single plane; because longitudinal waves like sound vibrate only along the direction of travel, they cannot be polarized."),
  _q("Young's double-slit experiment, which produces a pattern of bright and dark fringes, is important because it demonstrates",
      ["the wave nature of light through interference", "that light travels faster in denser media", "that light cannot be diffracted", "the particle nature of light only"], "the wave nature of light through interference",
      "The alternating bright (constructive) and dark (destructive) fringes observed can only be explained if light behaves as a wave capable of interference."),
  _q("A diffraction grating produces a spectrum of colours from white light mainly by",
      ["diffracting and interfering light from many closely spaced slits, which reinforces different wavelengths at different angles", "reflecting light off a single polished mirror", "absorbing all wavelengths except one", "refracting light through a single thick lens"], "diffracting and interfering light from many closely spaced slits, which reinforces different wavelengths at different angles",
      "A diffraction grating has many equally spaced slits; light diffracted from each slit interferes constructively at angles that depend on wavelength, separating white light into a spectrum."),
];

final _mirrors = [
  _q("The mirror formula relating object distance (u), image distance (v), and focal length (f) is",
      ["1/f = 1/u + 1/v", "f = u + v", "1/f = u x v", "f = u/v"], "1/f = 1/u + 1/v",
      "The mirror formula 1/f = 1/u + 1/v relates the focal length of a spherical mirror to the object and image distances measured from the pole of the mirror."),
  _q("The linear magnification produced by a mirror is given by",
      ["m = v/u = image height / object height", "m = u/v only", "m = f/u only", "m = u + v"], "m = v/u = image height / object height",
      "Magnification compares how much larger or smaller the image is than the object, and can be found either from the ratio of image to object distance or image to object height."),
  _q("For a concave mirror, the focal length is related to the radius of curvature R by",
      ["f = R/2", "f = 2R", "f = R", "f = R/4"], "f = R/2",
      "The focal point of a spherical mirror lies midway between the pole and the centre of curvature, so f = R/2."),
  _q("An object is placed 30 cm from a concave mirror, forming a real image 60 cm from the mirror. What is the focal length of the mirror?",
      ["20 cm", "45 cm", "90 cm", "30 cm"], "20 cm",
      "Using 1/f = 1/u + 1/v = 1/30 + 1/60 = 2/60 + 1/60 = 3/60 = 1/20, so f = 20 cm."),
  _q("A convex mirror always produces an image that is",
      ["virtual, upright, and diminished, regardless of the object's position", "real and inverted when the object is far away", "magnified when the object is close to the mirror", "the same size as the object at all distances"], "virtual, upright, and diminished, regardless of the object's position",
      "Because a convex mirror diverges reflected rays, it always forms a virtual, upright, smaller image, which is why it is used in vehicle side mirrors for a wider field of view."),
  _q("A real image, as opposed to a virtual image, is one that",
      ["is formed by the actual convergence of light rays and can be captured on a screen", "cannot be projected onto a screen", "always appears upright", "is always the same size as the object"], "is formed by the actual convergence of light rays and can be captured on a screen",
      "Real images result from light rays actually meeting at a point, so they can be focused onto a screen, unlike virtual images which are formed by the apparent divergence of rays."),
  _q("A concave mirror produces a real image magnified 3 times when an object is placed 20 cm in front of it. What is the focal length of the mirror?",
      ["15 cm", "20 cm", "60 cm", "45 cm"], "15 cm",
      "Magnification m = v/u = 3, so v = 3 x 20 = 60 cm. Then 1/f = 1/u + 1/v = 1/20 + 1/60 = 3/60 + 1/60 = 4/60 = 1/15, giving f = 15 cm."),
  _q("When an object is placed exactly at the centre of curvature of a concave mirror, the image formed is",
      ["real, inverted, and the same size as the object, also at the centre of curvature", "virtual and upright", "magnified and behind the mirror", "at infinity"], "real, inverted, and the same size as the object, also at the centre of curvature",
      "At the centre of curvature (u = R = 2f), a concave mirror forms a real, inverted image of the same size, coinciding with the object's position at the centre of curvature."),
  _q("When an object is placed between the pole and the focal point of a concave mirror, the image formed is",
      ["virtual, upright, and magnified, appearing behind the mirror", "real, inverted, and diminished", "real and the same size as the object", "always at the focal point"], "virtual, upright, and magnified, appearing behind the mirror",
      "For u < f, the reflected rays diverge and appear to come from behind the mirror, producing a virtual, upright, and magnified image, as used in shaving/make-up mirrors."),
];

final _refraction = [
  _q("Snell's Law of refraction states that",
      ["n1 sin(theta1) = n2 sin(theta2), for light passing between two media", "n1 + theta1 = n2 + theta2", "the angle of incidence always equals the angle of refraction", "refraction only occurs when light is reflected"], "n1 sin(theta1) = n2 sin(theta2), for light passing between two media",
      "Snell's Law relates the refractive indices of two media to the sines of the angles of incidence and refraction, and follows from the change in wave speed at the boundary."),
  _q("The refractive index of a medium can be defined as the ratio of the",
      ["speed of light in a vacuum to the speed of light in the medium", "speed of light in the medium to the speed of light in a vacuum", "angle of incidence to the angle of reflection", "real depth to the refractive index"], "speed of light in a vacuum to the speed of light in the medium",
      "Refractive index n = c/v, where c is the speed of light in a vacuum and v is its (reduced) speed in the medium; denser media have higher refractive indices."),
  _q("A ray of light strikes a glass surface (refractive index 1.5) at an angle of incidence of 30 degrees. What is the angle of refraction?",
      ["about 19.5 degrees", "45 degrees", "30 degrees", "60 degrees"], "about 19.5 degrees",
      "By Snell's Law, sin(r) = sin(i)/n = sin(30)/1.5 = 0.5/1.5 = 0.333, so r = sin^-1(0.333) is about 19.5 degrees."),
  _q("A material has a refractive index of 1.5. What is its critical angle for light travelling from the material into air?",
      ["about 41.8 degrees", "48.2 degrees", "60 degrees", "33.7 degrees"], "about 41.8 degrees",
      "The critical angle C satisfies sin(C) = 1/n = 1/1.5 = 0.667, so C = sin^-1(0.667), which is about 41.8 degrees."),
  _q("Total internal reflection can occur only when light travels",
      ["from a denser (optically) medium into a less dense medium, at an angle greater than the critical angle", "from a less dense medium into a denser medium", "through a vacuum", "at an angle smaller than the critical angle"], "from a denser (optically) medium into a less dense medium, at an angle greater than the critical angle",
      "Total internal reflection requires light travelling towards a less optically dense medium and striking the boundary at an angle of incidence exceeding the critical angle, so that no light is transmitted and all is reflected."),
  _q("In a triangular prism, minimum deviation of a light ray occurs when",
      ["the ray passes symmetrically through the prism, with the angle of incidence equal to the angle of emergence", "the angle of incidence is 90 degrees", "the ray is totally internally reflected inside the prism", "the prism is made of a material with refractive index 1"], "the ray passes symmetrically through the prism, with the angle of incidence equal to the angle of emergence",
      "The condition for minimum deviation in a prism is that the light ray traverses the prism symmetrically, making the angle of incidence equal to the angle of emergence."),
  _q("The refractive index of a liquid can be found using the formula",
      ["n = real depth / apparent depth", "n = apparent depth / real depth", "n = real depth x apparent depth", "n = real depth + apparent depth"], "n = real depth / apparent depth",
      "Because refraction makes an object submerged in a denser medium appear closer to the surface (its apparent depth) than it really is, the refractive index equals real depth divided by apparent depth."),
  _q("A swimming pool appears to be 2.25 m deep when its actual (real) depth is 3 m. What is the refractive index of the water?",
      ["1.33", "0.75", "1.5", "2.25"], "1.33",
      "Refractive index n = real depth/apparent depth = 3/2.25 = 1.33."),
  _q("Optical fibres transmit light signals over long distances mainly by relying on the principle of",
      ["total internal reflection at the boundary between the fibre's core and cladding", "simple reflection off an external mirror", "diffraction through a narrow slit", "polarization of the light signal"], "total internal reflection at the boundary between the fibre's core and cladding",
      "Optical fibres are designed so light striking the core-cladding boundary always exceeds the critical angle, undergoing repeated total internal reflection and travelling long distances with little loss."),
];

final _lenses = [
  _q("The thin lens formula relating object distance (u), image distance (v), and focal length (f) is",
      ["1/f = 1/u + 1/v", "f = u + v", "1/f = u x v", "f = uv"], "1/f = 1/u + 1/v",
      "For a thin lens, the same numerical relationship as the mirror formula applies: 1/f = 1/u + 1/v, using appropriate sign conventions for real objects and images."),
  _q("The power of a lens is defined as",
      ["the reciprocal of its focal length in metres, measured in dioptres", "the product of its focal length and its magnification", "the square of its focal length", "always equal to 1 for a converging lens"], "the reciprocal of its focal length in metres, measured in dioptres",
      "Lens power P = 1/f (with f in metres) is measured in dioptres (D); a converging lens has positive power, and a diverging lens has negative power."),
  _q("A converging lens has a focal length of 0.5 m. What is its power?",
      ["2 D", "0.5 D", "5 D", "20 D"], "2 D",
      "Power P = 1/f = 1/0.5 = 2 dioptres."),
  _q("An object is placed 30 cm from a converging lens of focal length 20 cm. Where is the image formed?",
      ["60 cm from the lens", "12 cm from the lens", "50 cm from the lens", "10 cm from the lens"], "60 cm from the lens",
      "Using 1/f = 1/u + 1/v: 1/v = 1/f - 1/u = 1/20 - 1/30 = 3/60 - 2/60 = 1/60, so v = 60 cm."),
  _q("In a camera, the lens forms an image on the film or sensor that is",
      ["real, inverted, and diminished", "virtual, upright, and magnified", "real, upright, and the same size as the object", "virtual and inverted"], "real, inverted, and diminished",
      "A camera lens converges light from a distant object to form a real, inverted, and usually smaller image on the light-sensitive film or sensor."),
  _q("Myopia (short-sightedness) occurs because the eye lens focuses images",
      ["in front of the retina, and is corrected with a diverging (concave) lens", "behind the retina, and is corrected with a diverging lens", "in front of the retina, and is corrected with a converging (convex) lens", "exactly on the retina at all times"], "in front of the retina, and is corrected with a diverging (concave) lens",
      "In myopia, the eyeball is too long or the lens too powerful, focusing distant images in front of the retina; a diverging lens spreads the rays out before they enter the eye so the image falls on the retina."),
  _q("Hypermetropia (long-sightedness) occurs because the eye lens focuses images",
      ["behind the retina, and is corrected with a converging (convex) lens", "in front of the retina, and is corrected with a converging lens", "behind the retina, and is corrected with a diverging lens", "exactly on the retina at all times"], "behind the retina, and is corrected with a converging (convex) lens",
      "In hypermetropia, the eyeball is too short or the lens too weak, so near images form behind the retina; a converging lens adds extra convergence so the image falls correctly on the retina."),
  _q("Presbyopia is an eye defect that occurs mainly due to",
      ["age-related loss of the eye lens's ability to accommodate (change shape)", "the eyeball being too long", "the eyeball being too short", "a permanent opacity of the cornea"], "age-related loss of the eye lens's ability to accommodate (change shape)",
      "Presbyopia develops with age as the lens becomes less elastic and the ciliary muscles weaken, reducing the eye's ability to focus on nearby objects; it is often corrected with bifocal lenses."),
  _q("A compound microscope achieves much greater magnification than a simple microscope because it",
      ["uses two converging lenses (an objective and an eyepiece), each contributing to the overall magnification", "uses a single very powerful converging lens", "uses a concave mirror in place of a lens", "relies only on diffraction of light"], "uses two converging lenses (an objective and an eyepiece), each contributing to the overall magnification",
      "The objective lens forms a real, magnified image of the object, which the eyepiece lens then further magnifies as a simple magnifier, multiplying the two magnifications together."),
];

final _soundWaves = [
  _q("Sound is produced by",
      ["a vibrating object that sets up compressions and rarefactions in the surrounding medium", "the reflection of light off a surface", "the flow of electric current through a conductor", "any stationary object placed in air"], "a vibrating object that sets up compressions and rarefactions in the surrounding medium",
      "Sound originates from mechanical vibrations of a source, which disturb the surrounding medium and produce alternating regions of compression and rarefaction that travel outward as a longitudinal wave."),
  _q("Sound generally travels fastest in",
      ["solids, because their particles are most closely packed, allowing rapid transmission of vibrations", "gases, because their particles move freely", "liquids, because they are denser than gases", "a vacuum, since there is no resistance"], "solids, because their particles are most closely packed, allowing rapid transmission of vibrations",
      "The speed of sound depends on how quickly vibrations pass between particles; the close packing and strong intermolecular forces in solids allow sound to travel fastest there, slower in liquids, and slowest in gases. Sound cannot travel at all through a vacuum."),
  _q("The pitch, loudness, and quality (timbre) of a musical note are determined respectively by its",
      ["frequency, amplitude, and waveform (overtones present)", "amplitude, frequency, and speed", "wavelength, speed, and frequency", "speed, wavelength, and amplitude"], "frequency, amplitude, and waveform (overtones present)",
      "Pitch depends on frequency, loudness depends on amplitude, and quality (which lets us distinguish instruments playing the same note) depends on the mixture of overtones present in the waveform."),
  _q("Overtones are",
      ["higher-frequency components (harmonics) that accompany the fundamental frequency and give a sound its distinctive quality", "the fundamental frequency of a note alone", "sounds that are too high-pitched to be heard by humans", "echoes produced by reflection of sound"], "higher-frequency components (harmonics) that accompany the fundamental frequency and give a sound its distinctive quality",
      "Overtones are additional frequencies (multiples of the fundamental) produced along with the fundamental note; their relative strengths give different instruments their characteristic timbre even when playing the same pitch."),
  _q("The fundamental frequency of a closed (one end closed) pipe of length L, with speed of sound v, is given by",
      ["f = v / 4L", "f = v / 2L", "f = 2v / L", "f = v / L"], "f = v / 4L",
      "A closed pipe supports a node at the closed end and an antinode at the open end, so the fundamental corresponds to a quarter wavelength fitting the pipe length, giving f = v/4L."),
  _q("The fundamental frequency of an open (both ends open) pipe of length L, with speed of sound v, is given by",
      ["f = v / 2L", "f = v / 4L", "f = 4v / L", "f = v / L"], "f = v / 2L",
      "An open pipe has antinodes at both ends, so the fundamental corresponds to half a wavelength fitting the pipe length, giving f = v/2L."),
  _q("A closed pipe of length 0.5 m resonates with sound of speed 340 m/s. What is its fundamental frequency?",
      ["170 Hz", "340 Hz", "85 Hz", "680 Hz"], "170 Hz",
      "For a closed pipe, f = v/4L = 340/(4 x 0.5) = 340/2 = 170 Hz."),
  _q("An open pipe of length 0.85 m resonates with sound of speed 340 m/s. What is its fundamental frequency?",
      ["200 Hz", "100 Hz", "400 Hz", "170 Hz"], "200 Hz",
      "For an open pipe, f = v/2L = 340/(2 x 0.85) = 340/1.7 = 200 Hz."),
  _q("Beats are heard when two sound waves of slightly different frequencies overlap, producing a",
      ["periodic rise and fall in loudness at a beat frequency equal to the difference of the two frequencies", "single steady tone equal to the sum of the two frequencies", "complete cancellation of both sounds permanently", "constant loudness with no variation"], "periodic rise and fall in loudness at a beat frequency equal to the difference of the two frequencies",
      "Beats arise from alternating constructive and destructive interference between two nearly equal frequencies, producing a throbbing loudness variation at a rate equal to |f1 - f2|."),
  _q("Two tuning forks of frequency 256 Hz and 260 Hz are sounded together. What beat frequency is heard?",
      ["4 Hz", "516 Hz", "256 Hz", "260 Hz"], "4 Hz",
      "Beat frequency = |f1 - f2| = |260 - 256| = 4 Hz."),
];

final _electrostatics = [
  _q("Conductors differ from insulators in that conductors",
      ["allow free (delocalised) charges to move easily through them", "completely block the movement of all charges", "cannot be charged by induction", "only allow heat, not charge, to move through them"], "allow free (delocalised) charges to move easily through them",
      "Conductors, such as metals, have free electrons that can move readily under an applied electric field, while insulators hold their electrons tightly, preventing charge flow."),
  _q("A gold-leaf electroscope is mainly used to",
      ["detect the presence of electric charge and determine its sign", "measure electric current directly", "generate an electromotive force", "measure the resistance of a conductor"], "detect the presence of electric charge and determine its sign",
      "The gold-leaf electroscope detects charge because the leaf and the stem repel each other when both carry the same charge, causing the leaf to diverge; its sign can be tested by seeing whether divergence increases or decreases with a known charge brought near."),
  _q("Coulomb's Law for the force between two point charges is expressed as",
      ["F = kq1q2/r^2", "F = kq1q2/r", "F = k(q1+q2)/r^2", "F = kq1q2 x r^2"], "F = kq1q2/r^2",
      "Coulomb's Law states that the electrostatic force between two point charges is directly proportional to the product of the charges and inversely proportional to the square of the distance separating them."),
  _q("Two point charges of 2 x 10^-6 C each are placed 0.3 m apart (k = 9 x 10^9 Nm^2/C^2). What is the force between them?",
      ["0.4 N", "4 N", "0.04 N", "3.6 N"], "0.4 N",
      "F = kq1q2/r^2 = (9 x 10^9 x 2x10^-6 x 2x10^-6)/(0.3)^2 = (9x10^9 x 4x10^-12)/0.09 = 0.036/0.09 = 0.4 N."),
  _q("Electric field intensity at a point is defined as the",
      ["force per unit positive charge placed at that point", "work done per unit charge moved between two points", "charge stored per unit potential difference", "product of charge and distance from the source"], "force per unit positive charge placed at that point",
      "Electric field intensity, E = F/q, describes the force that would be experienced by a unit positive test charge placed at a given point in the field."),
  _q("Electric potential at a point is defined as the",
      ["work done in bringing a unit positive charge from infinity to that point", "force acting on a unit charge at that point", "total charge stored at that point", "rate of flow of charge at that point"], "work done in bringing a unit positive charge from infinity to that point",
      "Electric potential, V = W/q, measures the work done per unit charge in moving a small positive test charge from infinity (zero potential) to the point in question."),
  _q("The capacitance of a capacitor is defined by the formula",
      ["C = Q/V", "C = V/Q", "C = QV", "C = Q + V"], "C = Q/V",
      "Capacitance is the ratio of the charge stored on a capacitor's plates to the potential difference across them, C = Q/V, measured in farads."),
  _q("A capacitor stores a charge of 6 x 10^-4 C when a potential difference of 3 V is applied across it. What is its capacitance?",
      ["2 x 10^-4 F", "3 x 10^-4 F", "1.8 x 10^-3 F", "6 x 10^-4 F"], "2 x 10^-4 F",
      "Capacitance C = Q/V = (6 x 10^-4)/3 = 2 x 10^-4 F."),
  _q("For a parallel-plate capacitor, its capacitance increases when the",
      ["plate area increases or the separation between the plates decreases", "plate area decreases or the separation increases", "plates are moved further apart, regardless of area", "dielectric between the plates is removed"], "plate area increases or the separation between the plates decreases",
      "Capacitance C = (epsilon0 x epsilonR x A)/d, so it increases with larger plate area A or smaller plate separation d, or with a dielectric of higher permittivity."),
  _q("A 4 microfarad capacitor is charged to a potential difference of 100 V. How much energy is stored in it?",
      ["0.02 J", "0.04 J", "0.2 J", "4 J"], "0.02 J",
      "Energy stored E = 0.5CV^2 = 0.5 x 4x10^-6 x (100)^2 = 0.5 x 4x10^-6 x 10000 = 0.5 x 0.04 = 0.02 J."),
  _q("When capacitors are connected in series, the total (equivalent) capacitance is found from",
      ["1/Ctotal = 1/C1 + 1/C2 + ...", "Ctotal = C1 + C2 + ...", "Ctotal = C1 x C2", "Ctotal = C1 - C2"], "1/Ctotal = 1/C1 + 1/C2 + ...",
      "Series capacitors combine like parallel resistors: the reciprocals of the individual capacitances add, giving a total capacitance smaller than any individual capacitor, while in parallel, capacitances simply add directly."),
];

final _currentElectricity = [
  _q("The e.m.f of a cell differs from its terminal potential difference because the e.m.f. is the",
      ["total energy per unit charge supplied by the source, including the drop across its internal resistance", "voltage measured only when no current flows in an external circuit is possible", "same as the terminal voltage under all conditions", "current supplied by the cell per second"], "total energy per unit charge supplied by the source, including the drop across its internal resistance",
      "The e.m.f. represents the total electrical energy supplied per unit charge by the source, part of which is used up driving current through the cell's own internal resistance, leaving a smaller terminal potential difference when current flows."),
  _q("A cell of e.m.f. 12 V and internal resistance 0.5 ohms delivers a current of 2 A. What is the terminal potential difference?",
      ["11 V", "13 V", "12 V", "10 V"], "11 V",
      "Terminal p.d. = E - Ir = 12 - (2 x 0.5) = 12 - 1 = 11 V."),
  _q("A potential difference of 24 V is applied across a resistor of resistance 6 ohms. What current flows through it?",
      ["4 A", "144 A", "0.25 A", "18 A"], "4 A",
      "By Ohm's Law, I = V/R = 24/6 = 4 A."),
  _q("The resistivity of a material is given by the formula",
      ["rho = RA/L", "rho = RL/A", "rho = R/AL", "rho = RAL"], "rho = RA/L",
      "Resistivity relates a conductor's resistance to its geometry: rho = RA/L, where A is the cross-sectional area and L is the length, a property intrinsic to the material."),
  _q("A wire of length 1 m and cross-sectional area 1 x 10^-6 m^2 has a resistance of 2 ohms. What is the resistivity of the wire material?",
      ["2 x 10^-6 ohm-metres", "2 x 10^6 ohm-metres", "0.5 x 10^-6 ohm-metres", "2 ohm-metres"], "2 x 10^-6 ohm-metres",
      "Resistivity = RA/L = (2 x 1x10^-6)/1 = 2 x 10^-6 ohm-metres."),
  _q("Three resistors of 2 ohms, 3 ohms, and 5 ohms are connected in series. What is the total resistance?",
      ["10 ohms", "0.37 ohms", "30 ohms", "2.7 ohms"], "10 ohms",
      "In series, resistances add directly: Rtotal = 2 + 3 + 5 = 10 ohms."),
  _q("A 20 V supply is connected across three resistors of 2, 3, and 5 ohms in series. What current flows in the circuit?",
      ["2 A", "10 A", "0.5 A", "200 A"], "2 A",
      "Total resistance = 2+3+5 = 10 ohms, so current I = V/Rtotal = 20/10 = 2 A."),
  _q("The Wheatstone bridge circuit is used to",
      ["accurately measure an unknown resistance by achieving a null (zero) deflection balance condition", "measure current directly without any calculation", "generate an electromotive force", "store electric charge for later use"], "accurately measure an unknown resistance by achieving a null (zero) deflection balance condition",
      "A Wheatstone bridge balances four resistances (two known, one variable, one unknown) so that no current flows through a galvanometer bridging them, from which the unknown resistance can be calculated precisely."),
  _q("A potentiometer is used to measure the e.m.f. of a cell accurately because, at the balance point,",
      ["no current is drawn from the cell being measured", "maximum current flows through the cell", "the cell's internal resistance becomes zero", "the potentiometer wire is short-circuited"], "no current is drawn from the cell being measured",
      "At balance, the potentiometer's slide is positioned so no current flows through the galvanometer branch, meaning the cell being tested supplies no current, so its full e.m.f. (undiminished by internal resistance) is measured."),
  _q("A device draws a current of 5 A from a 220 V mains supply. What electrical power does it consume?",
      ["1100 W", "44 W", "225 W", "1320 W"], "1100 W",
      "Electrical power P = IV = 5 x 220 = 1100 W."),
  _q("A resistor of 10 ohms carries a current of 2 A. What power is dissipated in the resistor?",
      ["40 W", "20 W", "4 W", "200 W"], "40 W",
      "Power P = I^2R = (2)^2 x 10 = 4 x 10 = 40 W."),
];

final _magnetism = [
  _q("Ferromagnetic materials such as iron, cobalt, and nickel are",
      ["strongly attracted by a magnet and can themselves be magnetised", "repelled by all magnets", "unaffected by any magnetic field", "only attracted when heated above their melting point"], "strongly attracted by a magnet and can themselves be magnetised",
      "Ferromagnetic materials have domains that can align with an external magnetic field, allowing them to be strongly attracted to magnets and to retain magnetism themselves."),
  _q("The magnetic field lines around a bar magnet",
      ["emerge from the north pole and enter the south pole, forming closed loops", "emerge from the south pole only", "are always parallel straight lines with no curvature", "only exist inside the magnet itself"], "emerge from the north pole and enter the south pole, forming closed loops",
      "By convention, magnetic field lines are drawn leaving the north pole, curving round, and entering the south pole outside the magnet, continuing as closed loops through the magnet's interior."),
  _q("The magnetic field around a straight current-carrying conductor forms a pattern of",
      ["concentric circles centred on the wire, with direction given by the right-hand grip rule", "straight lines parallel to the wire", "closed loops similar to a bar magnet", "no field, since only coils produce magnetic fields"], "concentric circles centred on the wire, with direction given by the right-hand grip rule",
      "A current-carrying straight wire produces a magnetic field of concentric circular field lines around it; curling the right hand's fingers in the field direction with the thumb pointing along the current gives the right-hand grip rule."),
  _q("The magnetic field inside a current-carrying solenoid is",
      ["strong and fairly uniform, resembling the field of a bar magnet", "zero everywhere inside the coil", "strongest at the centre of each turn but zero along the axis", "identical outside and inside the solenoid"], "strong and fairly uniform, resembling the field of a bar magnet",
      "A solenoid's many turns produce a strong, nearly uniform magnetic field along its axis, similar in pattern to that of a bar magnet, which can be strengthened with a soft iron core."),
  _q("The angle of declination of the Earth's magnetic field is the angle between",
      ["geographic (true) north and magnetic north at a given location", "the horizontal and the resultant magnetic field direction", "the equator and the magnetic poles", "true north and the vertical"], "geographic (true) north and magnetic north at a given location",
      "Declination describes how far magnetic north (the direction a compass needle points) deviates from true geographic north at a particular location on Earth's surface."),
  _q("The angle of dip (inclination) of the Earth's magnetic field is the angle between",
      ["the resultant magnetic field direction and the horizontal plane at a location", "true north and magnetic north", "the vertical and the equator", "two magnetic poles of a bar magnet"], "the resultant magnetic field direction and the horizontal plane at a location",
      "The angle of dip measures how much the Earth's magnetic field tilts below (or above) the horizontal; it is 0 degrees at the magnetic equator and 90 degrees at the magnetic poles."),
  _q("A steel bar can be magnetised by which of the following methods?",
      ["Stroking with a magnet, placing it in a solenoid carrying direct current, or induction from another magnet", "Heating it far above its Curie temperature", "Dropping it repeatedly on a hard floor", "Leaving it in a region with no magnetic field"], "Stroking with a magnet, placing it in a solenoid carrying direct current, or induction from another magnet",
      "Magnetisation methods include single/double-touch stroking with a permanent magnet, the electrical method (placing the material in a solenoid carrying direct current), and induction by bringing it near a strong magnet."),
  _q("A magnet can be demagnetised by",
      ["heating it above its Curie temperature, hammering it, or applying a gradually decreasing alternating current", "stroking it repeatedly with another magnet in the same direction", "placing it inside a solenoid carrying a steady direct current", "cooling it to a very low temperature"], "heating it above its Curie temperature, hammering it, or applying a gradually decreasing alternating current",
      "Demagnetisation disrupts the alignment of magnetic domains, which can be achieved by heating past the Curie point, mechanical shock (hammering), or subjecting it to a decreasing alternating magnetic field."),
];

final _electromagnetism = [
  _q("The force on a current-carrying conductor in a magnetic field is given by",
      ["F = BIL sin(theta), where theta is the angle between the conductor and the field", "F = BIL, regardless of the angle between the conductor and the field", "F = B/IL", "F = BI + L"], "F = BIL sin(theta), where theta is the angle between the conductor and the field",
      "The force on a current-carrying conductor depends on the magnetic flux density B, current I, length L in the field, and the sine of the angle between the conductor and the field, being maximum when the conductor is perpendicular to the field."),
  _q("A straight conductor of length 0.2 m carries a current of 4 A perpendicular to a magnetic field of flux density 0.5 T. What force acts on the conductor?",
      ["0.4 N", "4 N", "0.04 N", "2 N"], "0.4 N",
      "Since the conductor is perpendicular to the field, sin(90) = 1, so F = BIL = 0.5 x 4 x 0.2 = 0.4 N."),
  _q("A moving-coil galvanometer works by using the",
      ["force experienced by a current-carrying coil placed in a magnetic field to produce a proportional deflection", "heating effect of a current passing through a resistor", "chemical effect of current in an electrolyte", "capacitive charging effect of a coil"], "force experienced by a current-carrying coil placed in a magnetic field to produce a proportional deflection",
      "In a moving-coil galvanometer, current through a coil in a radial magnetic field produces a torque proportional to the current, causing a pointer deflection that can be calibrated to read current."),
  _q("Faraday's Law of electromagnetic induction states that the induced e.m.f. in a circuit is",
      ["directly proportional to the rate of change of magnetic flux linking the circuit", "inversely proportional to the rate of change of magnetic flux", "independent of the rate of change of flux", "only produced when the flux is constant"], "directly proportional to the rate of change of magnetic flux linking the circuit",
      "Faraday's Law states that a changing magnetic flux through a circuit induces an e.m.f. proportional to how quickly the flux is changing, forming the basis of generators and transformers."),
  _q("Lenz's Law states that the direction of an induced current is always such that it",
      ["opposes the change in magnetic flux that produced it", "reinforces the change in magnetic flux that produced it", "has no definite direction", "flows only in direct current circuits"], "opposes the change in magnetic flux that produced it",
      "Lenz's Law is a consequence of the conservation of energy: the induced current creates its own magnetic field that opposes the original change in flux, requiring work to be done against this opposition."),
  _q("The root-mean-square (r.m.s.) value of an alternating current is related to its peak value by",
      ["rms value = peak value / square root of 2", "rms value = peak value x 2", "rms value = peak value", "rms value = peak value x square root of 2"], "rms value = peak value / square root of 2",
      "For a sinusoidal a.c. waveform, the r.m.s. value (equivalent d.c. value for the same power dissipation) equals the peak value divided by the square root of 2, approximately 0.707 times the peak."),
  _q("An alternating supply has a peak voltage of about 311 V. What is its approximate r.m.s. voltage?",
      ["220 V", "311 V", "440 V", "155 V"], "220 V",
      "rms voltage = peak voltage / sqrt(2) = 311/1.414, which is approximately 220 V, the standard mains r.m.s. voltage in many countries."),
  _q("A transformer's primary and secondary voltages are related to the number of turns on each coil by",
      ["Vp/Vs = Np/Ns", "Vp x Vs = Np x Ns", "Vp/Vs = Ns/Np only for step-down transformers", "Vp + Np = Vs + Ns"], "Vp/Vs = Np/Ns",
      "An ideal transformer's voltage ratio equals its turns ratio: Vp/Vs = Np/Ns, allowing the secondary voltage to be stepped up or down relative to the primary."),
  _q("A transformer has 100 turns on its primary coil and 500 turns on its secondary coil. If the primary voltage is 20 V, what is the secondary voltage?",
      ["100 V", "4 V", "20 V", "500 V"], "100 V",
      "Vs = Vp x (Ns/Np) = 20 x (500/100) = 20 x 5 = 100 V, since this is a step-up transformer (more secondary turns than primary)."),
  _q("In an a.c. circuit, the opposition to current flow due to a combination of resistance and reactance is called",
      ["impedance", "conductance", "capacitance", "permittivity"], "impedance",
      "Impedance combines the effects of ohmic resistance and reactance (from inductors and capacitors) into a single quantity that determines the total opposition to alternating current in a circuit."),
];

final _atomicStructure = [
  _q("Rutherford's alpha-particle scattering experiment led to the model of the atom in which",
      ["most of the atom's mass and all its positive charge are concentrated in a tiny, dense central nucleus", "the atom is a uniform sphere of positive charge with electrons embedded in it", "electrons orbit in continuously variable paths around a diffuse nucleus", "the atom has no internal structure at all"], "most of the atom's mass and all its positive charge are concentrated in a tiny, dense central nucleus",
      "The unexpected large-angle scattering of some alpha particles showed that atoms have a small, dense, positively charged nucleus, with the rest of the atom being mostly empty space, replacing the earlier 'plum pudding' model."),
  _q("In Bohr's model of the atom, electrons occupy",
      ["fixed, discrete energy levels (orbits), only gaining or losing energy when jumping between levels", "continuously variable orbits of any energy", "a single shared orbit around the nucleus", "orbits that continuously radiate energy and spiral into the nucleus"], "fixed, discrete energy levels (orbits), only gaining or losing energy when jumping between levels",
      "Bohr proposed that electrons can only exist in specific quantised energy levels, remaining stable in these orbits unless they absorb or emit a quantum of energy while transitioning between levels."),
  _q("The energy of a photon of electromagnetic radiation is given by the equation",
      ["E = hf, where h is Planck's constant and f is the frequency", "E = h/f", "E = mc, where m is mass and c is the speed of light", "E = f/h"], "E = hf, where h is Planck's constant and f is the frequency",
      "Planck's equation E = hf shows that the energy carried by a photon is directly proportional to the frequency of the radiation, with h as the constant of proportionality."),
  _q("A photon has a frequency of 5 x 10^14 Hz (h = 6.63 x 10^-34 Js). What is its energy?",
      ["3.315 x 10^-19 J", "3.315 x 10^-14 J", "6.63 x 10^-19 J", "1.33 x 10^-48 J"], "3.315 x 10^-19 J",
      "Energy E = hf = 6.63x10^-34 x 5x10^14 = 3.315 x 10^-19 J."),
  _q("Einstein's photoelectric equation is expressed as",
      ["hf = W0 + (1/2)mv(max)^2", "hf = W0 - (1/2)mv(max)^2", "hf = W0 x (1/2)mv(max)^2", "W0 = hf x (1/2)mv(max)^2"], "hf = W0 + (1/2)mv(max)^2",
      "Einstein explained the photoelectric effect by stating that the energy of an incident photon is used partly to overcome the metal's work function (W0) and the remainder becomes the maximum kinetic energy of the emitted electron."),
  _q("In a photoelectric experiment, a photon delivers 5 x 10^-19 J of energy to a metal of work function 2 x 10^-19 J. What is the maximum kinetic energy of the emitted electron?",
      ["3 x 10^-19 J", "7 x 10^-19 J", "2.5 x 10^-19 J", "1 x 10^-19 J"], "3 x 10^-19 J",
      "Maximum kinetic energy = hf - W0 = 5x10^-19 - 2x10^-19 = 3 x 10^-19 J."),
  _q("The threshold frequency in the photoelectric effect is the",
      ["minimum frequency of incident light below which no electrons are emitted, regardless of intensity", "maximum frequency of light a metal can absorb", "frequency at which the metal begins to melt", "frequency corresponding to the work function divided by intensity"], "minimum frequency of incident light below which no electrons are emitted, regardless of intensity",
      "Below the threshold frequency, individual photons do not carry enough energy to overcome the metal's work function, so no photoelectrons are emitted no matter how intense the light is."),
  _q("X-rays are produced when",
      ["fast-moving electrons are suddenly decelerated on striking a metal target in an evacuated tube", "slow-moving electrons are gradually accelerated in a magnetic field", "visible light is passed through a diffraction grating", "radioactive nuclei absorb neutrons"], "fast-moving electrons are suddenly decelerated on striking a metal target in an evacuated tube",
      "In an X-ray tube, electrons accelerated through a high voltage strike a metal (often tungsten) target; their sudden deceleration converts much of their kinetic energy into high-frequency electromagnetic radiation (X-rays)."),
  _q("The de Broglie wavelength of a moving particle is given by",
      ["lambda = h/(mv)", "lambda = h x mv", "lambda = mv/h", "lambda = h/m"], "lambda = h/(mv)",
      "De Broglie proposed that all moving particles have an associated wavelength given by lambda = h/p = h/(mv), linking a particle's momentum to a wave nature."),
  _q("An electron of mass 9.1 x 10^-31 kg moves at 2 x 10^6 m/s (h = 6.63 x 10^-34 Js). What is its de Broglie wavelength?",
      ["3.64 x 10^-10 m", "1.82 x 10^-24 m", "6.63 x 10^-34 m", "7.28 x 10^-10 m"], "3.64 x 10^-10 m",
      "Momentum = mv = 9.1x10^-31 x 2x10^6 = 1.82 x 10^-24 kg m/s. Wavelength = h/(mv) = 6.63x10^-34/1.82x10^-24 = 3.64 x 10^-10 m."),
];

final _radioactivity = [
  _q("An alpha particle is",
      ["a helium nucleus (2 protons and 2 neutrons) with a low penetrating power, stopped by a sheet of paper", "a high-speed electron with a moderate penetrating power", "a high-energy electromagnetic wave with the highest penetrating power", "an uncharged particle with no mass"], "a helium nucleus (2 protons and 2 neutrons) with a low penetrating power, stopped by a sheet of paper",
      "Alpha particles carry a charge of +2 and are relatively large and slow, so they are easily absorbed, being stopped by just a sheet of paper or a few centimetres of air."),
  _q("A beta particle is",
      ["a high-speed electron emitted from the nucleus, with moderate penetrating power stopped by a few millimetres of aluminium", "a helium nucleus with very low penetrating power", "an electromagnetic wave with the highest penetrating power", "identical to a proton"], "a high-speed electron emitted from the nucleus, with moderate penetrating power stopped by a few millimetres of aluminium",
      "Beta particles are fast electrons (or positrons) ejected from an unstable nucleus during beta decay; they penetrate further than alpha particles but are stopped by a few millimetres of aluminium."),
  _q("Gamma radiation consists of",
      ["high-energy, high-frequency electromagnetic waves with the greatest penetrating power among the three types of radioactive emission", "helium nuclei with the lowest penetrating power", "fast electrons with moderate penetrating power", "neutrons emitted from a nucleus"], "high-energy, high-frequency electromagnetic waves with the greatest penetrating power among the three types of radioactive emission",
      "Unlike alpha and beta particles, gamma rays are electromagnetic radiation with no mass or charge, and they require thick lead or concrete to significantly reduce their intensity."),
  _q("Radioactive decay follows the law",
      ["N = N0 e^(-lambda t), where lambda is the decay constant", "N = N0 + lambda t", "N = N0 x lambda x t", "N = N0 / (lambda + t)"], "N = N0 e^(-lambda t), where lambda is the decay constant",
      "The number of undecayed nuclei N remaining after time t follows an exponential decay law from an initial number N0, governed by the characteristic decay constant lambda of the isotope."),
  _q("The half-life of a radioactive substance is related to its decay constant by",
      ["T(half) = 0.693 / lambda", "T(half) = lambda / 0.693", "T(half) = 0.693 x lambda", "T(half) = 1 / (0.693 + lambda)"], "T(half) = 0.693 / lambda",
      "Half-life is the time for half the radioactive nuclei in a sample to decay, related to the decay constant lambda by T(half) = ln(2)/lambda, approximately 0.693/lambda."),
  _q("A radioactive isotope has a decay constant of 0.0866 per day. What is its half-life?",
      ["about 8 days", "about 4 days", "about 16 days", "about 0.0866 days"], "about 8 days",
      "Half-life = 0.693/lambda = 0.693/0.0866, which is approximately 8 days."),
  _q("A radioactive sample undergoes 3 half-lives. What fraction of the original radioactive nuclei remains?",
      ["1/8", "1/3", "1/6", "3/8"], "1/8",
      "After each half-life, the remaining fraction halves: after 1 half-life, 1/2 remains; after 2, 1/4 remains; after 3, 1/8 remains, following (1/2)^3 = 1/8."),
  _q("Nuclear fission is a process in which",
      ["a heavy nucleus splits into two lighter nuclei, releasing energy and usually more neutrons", "two light nuclei combine to form a heavier nucleus", "a nucleus emits only gamma radiation without changing its mass number", "electrons are removed from an atom's outer shell"], "a heavy nucleus splits into two lighter nuclei, releasing energy and usually more neutrons",
      "In nuclear fission, a heavy nucleus (such as uranium-235) captures a neutron and splits into two smaller nuclei, releasing a large amount of energy along with additional neutrons that can sustain a chain reaction, as used in nuclear reactors."),
  _q("Nuclear fusion is a process in which",
      ["light nuclei combine to form a heavier nucleus, releasing enormous energy", "a heavy nucleus splits into two lighter nuclei", "a nucleus captures an external electron", "radiation is absorbed without any nuclear change"], "light nuclei combine to form a heavier nucleus, releasing enormous energy",
      "Fusion combines light nuclei, such as isotopes of hydrogen, under extreme temperature and pressure to form a heavier nucleus, releasing far more energy per unit mass than fission; this process powers the Sun and other stars."),
  _q("The binding energy of a nucleus is defined as the",
      ["energy required to completely separate a nucleus into its individual protons and neutrons", "kinetic energy of the nucleus as it moves", "energy released when an electron is captured by the nucleus", "energy needed to ionise the outer electron shell only"], "energy required to completely separate a nucleus into its individual protons and neutrons",
      "Binding energy represents the energy that holds the nucleons together; it equals the energy that would need to be supplied to break the nucleus apart into separate, unbound protons and neutrons."),
  _q("The mass defect of a nucleus is the difference between",
      ["the sum of the masses of its individual nucleons and the actual mass of the nucleus", "the mass of the nucleus and the mass of the whole atom", "the number of protons and the number of neutrons", "the atomic number and the mass number"], "the sum of the masses of its individual nucleons and the actual mass of the nucleus",
      "The nucleus has slightly less mass than the sum of its separate constituent nucleons; this 'missing' mass, the mass defect, is converted to binding energy according to Einstein's equation E = mc^2."),
];

final _electronics = [
  _q("Thermionic emission refers to the",
      ["emission of electrons from a heated metal surface, as in a vacuum tube cathode", "emission of light from a heated filament", "absorption of electrons by a cooled metal surface", "flow of current through a p-n junction in reverse bias"], "emission of electrons from a heated metal surface, as in a vacuum tube cathode",
      "When a metal (the cathode) is heated sufficiently, some of its free electrons gain enough energy to escape the surface entirely, a process exploited in vacuum tubes and cathode ray devices."),
  _q("A diode's key characteristic is that it",
      ["conducts current readily in one direction (forward bias) and blocks it in the other (reverse bias)", "conducts current equally well in both directions", "blocks current in both directions at all times", "only conducts when connected to an alternating supply"], "conducts current readily in one direction (forward bias) and blocks it in the other (reverse bias)",
      "A diode's asymmetric conduction, allowing current to flow easily when forward biased but blocking it (aside from a tiny leakage current) when reverse biased, is the basis of its use in rectification."),
  _q("A p-type semiconductor is produced by doping a pure semiconductor with",
      ["a trivalent (acceptor) impurity, creating holes as the majority charge carriers", "a pentavalent (donor) impurity, creating free electrons as majority carriers", "another identical semiconductor atom", "a metal with very high conductivity"], "a trivalent (acceptor) impurity, creating holes as the majority charge carriers",
      "Adding a trivalent element such as boron introduces 'holes' (missing electrons) into the semiconductor's crystal structure, which act as the majority positive charge carriers in p-type material."),
  _q("An n-type semiconductor is produced by doping a pure semiconductor with",
      ["a pentavalent (donor) impurity, creating free electrons as the majority charge carriers", "a trivalent (acceptor) impurity, creating holes as majority carriers", "an inert gas to reduce conductivity", "pure silicon only, with no impurity"], "a pentavalent (donor) impurity, creating free electrons as the majority charge carriers",
      "Adding a pentavalent element such as phosphorus contributes extra free electrons to the semiconductor's crystal structure, making free electrons the majority negative charge carriers in n-type material."),
  _q("A p-n junction diode is formed by",
      ["joining a p-type and an n-type semiconductor, creating a depletion region that permits current flow mainly in one direction", "joining two identical n-type semiconductors together", "coating a metal plate with an insulating oxide layer", "heating a pure semiconductor to a very high temperature"], "joining a p-type and an n-type semiconductor, creating a depletion region that permits current flow mainly in one direction",
      "At the p-n junction, a depletion region forms where charge carriers have diffused and recombined; this region allows current to flow easily when forward biased but strongly resists current flow when reverse biased."),
  _q("Half-wave rectification uses a single diode to",
      ["allow current to flow during only one half of each a.c. input cycle, blocking the other half", "allow current to flow during both halves of each a.c. input cycle", "convert direct current into alternating current", "amplify the input a.c. signal without changing its frequency"], "allow current to flow during only one half of each a.c. input cycle, blocking the other half",
      "In half-wave rectification, the diode conducts only when it is forward biased, which occurs during one half of the a.c. cycle, producing a pulsating output at the same frequency as the input with the other half removed."),
  _q("Full-wave rectification, using two diodes or a four-diode bridge arrangement, produces a pulsating direct current output whose",
      ["ripple frequency is twice that of the a.c. input, giving a smoother output than half-wave rectification", "ripple frequency equals that of half-wave rectification", "output is a smooth, ripple-free direct current with no further filtering needed", "current flows only during alternate cycles, exactly as in half-wave rectification"], "ripple frequency is twice that of the a.c. input, giving a smoother output than half-wave rectification",
      "Because full-wave rectification makes use of both halves of the a.c. cycle (with polarity reversed appropriately during the negative half), the output pulses occur twice as often as in half-wave rectification, producing a smoother, more easily filtered direct current."),
  _q("A bridge rectifier achieves full-wave rectification using",
      ["four diodes arranged so that current always flows in the same direction through the load, without needing a centre-tapped transformer", "a single diode and a large capacitor only", "two diodes and a centre-tapped transformer only, with no other arrangement possible", "a transistor in place of all diodes"], "four diodes arranged so that current always flows in the same direction through the load, without needing a centre-tapped transformer",
      "The bridge rectifier arrangement uses four diodes so that, regardless of which half of the a.c. cycle is present, current is always directed the same way through the load, achieving full-wave rectification without requiring a centre-tapped transformer."),
];
