import "../quiz_question.dart";

const _subject = "Chemistry";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// WAEC Chemistry (Advanced) — 100+ questions covering the "advanced" half
/// of the WAEC syllabus: Energy Changes, Acids/Bases/Salts, Solubility &
/// Kinetics, Electrochemistry, Organic Chemistry, and Quantitative &
/// Qualitative Practical Analysis. Blends conceptual/definitional questions
/// with quantitative ones (titrations, pH, Faraday's law, empirical/water-
/// of-crystallisation calculations).
List<QuizQuestion> buildWaecChemistryAdvancedQuestions() {
  return [
    ..._energyChanges,
    ..._acidsBasesSalts,
    ..._solubilityKinetics,
    ..._electrochemistry,
    ..._organicChemistry,
    ..._quantitativeQualitativeAnalysis,
  ];
}

final _energyChanges = [
  _q("A reaction that releases heat energy to the surroundings is described as",
      ["exothermic", "endothermic", "isothermic", "adiabatic"], "exothermic",
      "Exothermic reactions have a negative enthalpy change (ΔH < 0) because the energy released forming new bonds exceeds the energy absorbed breaking old bonds."),
  _q("A reaction that absorbs heat energy from the surroundings is described as",
      ["endothermic", "exothermic", "isothermic", "catalytic"], "endothermic",
      "Endothermic reactions have a positive enthalpy change (ΔH > 0); more energy is absorbed to break bonds in the reactants than is released forming bonds in the products."),
  _q("The enthalpy change of combustion of a substance is defined as the heat change when",
      ["one mole of the substance is completely burnt in excess oxygen under standard conditions", "one mole of a compound is formed from its elements", "one mole of acid is neutralised by a base", "one gram of the substance dissolves in water"], "one mole of the substance is completely burnt in excess oxygen under standard conditions",
      "Enthalpy of combustion is always exothermic and is measured for exactly one mole of fuel/substance reacting completely with an excess supply of oxygen."),
  _q("The standard enthalpy change of neutralisation is the heat evolved when",
      ["one mole of water is formed from the reaction of an acid and a base in dilute solution", "one mole of salt crystallises from solution", "one mole of acid is completely dissociated", "one mole of base absorbs carbon dioxide"], "one mole of water is formed from the reaction of an acid and a base in dilute solution",
      "For any strong acid reacting with a strong base, the enthalpy of neutralisation is fairly constant (about -57 kJ/mol) because the reaction is essentially H+(aq) + OH-(aq) -> H2O(l) in every case."),
  _q("The standard enthalpy change of formation of a compound is the heat change when",
      ["one mole of the compound is formed from its constituent elements in their standard states", "one mole of the compound decomposes into its elements", "one mole of the compound dissolves completely in water", "one mole of the compound is burnt in oxygen"], "one mole of the compound is formed from its constituent elements in their standard states",
      "Enthalpy of formation refers strictly to building one mole of compound directly from its elements, each in their standard physical state at 298 K and 1 atmosphere."),
  _q("On an energy profile diagram, the activation energy is represented by the",
      ["difference in energy between the reactants and the peak of the curve", "difference in energy between the reactants and the products", "area under the entire curve", "energy of the products alone"], "difference in energy between the reactants and the peak of the curve",
      "Activation energy is the extra energy needed to reach the unstable transition state (the highest point on the energy profile) before products can form."),
  _q("On the energy profile of an exothermic reaction, the products are shown",
      ["at a lower energy level than the reactants", "at a higher energy level than the reactants", "at exactly the same energy level as the reactants", "above the activation energy peak"], "at a lower energy level than the reactants",
      "Because exothermic reactions release net energy to the surroundings, the products end up at a lower energy level on the diagram than the starting reactants."),
  _q("Adding a catalyst to a reaction changes the energy profile diagram by",
      ["lowering the activation energy peak while the reactant and product energy levels stay the same", "lowering the energy level of the products", "raising the energy level of the reactants", "removing the activation energy peak completely"], "lowering the activation energy peak while the reactant and product energy levels stay the same",
      "A catalyst provides an alternative pathway with a lower activation energy hump, speeding up the reaction, but it does not change the overall enthalpy change (ΔH) between reactants and products."),
  _q("Compared with an uncatalysed reaction, a catalysed reaction proceeds faster mainly because",
      ["a greater fraction of colliding particles now possess energy equal to or above the (lowered) activation energy", "the reactant particles collide less frequently", "the temperature of the reaction mixture automatically rises", "the products become more stable"],
      "a greater fraction of colliding particles now possess energy equal to or above the (lowered) activation energy",
      "Lowering the activation energy means more of the particles' existing energy distribution already exceeds the new, smaller barrier, so successful collisions happen more often per second."),
  _q("50 g of water is heated from 25 degC to 65 degC by the heat released from burning a fuel. Calculate the heat absorbed by the water. (specific heat capacity of water = 4.2 J/g degC)",
      ["8.4 kJ", "4.2 kJ", "16.8 kJ", "2.1 kJ"], "8.4 kJ",
      "Heat absorbed, q = mc(delta)T = 50 x 4.2 x (65 - 25) = 50 x 4.2 x 40 = 8400 J = 8.4 kJ."),
  _q("For the reaction H2(g) + Cl2(g) -> 2HCl(g), given bond energies H-H = 436 kJ/mol, Cl-Cl = 242 kJ/mol, and H-Cl = 431 kJ/mol, calculate the enthalpy change of the reaction.",
      ["-184 kJ/mol", "+184 kJ/mol", "-678 kJ/mol", "+862 kJ/mol"], "-184 kJ/mol",
      "Energy to break bonds = (436 + 242) = 678 kJ/mol. Energy released forming bonds = 2 x 431 = 862 kJ/mol. Delta H = energy in - energy out = 678 - 862 = -184 kJ/mol (exothermic)."),
  _q("50 cm3 of 1.0 mol/dm3 HCl is mixed with 50 cm3 of 1.0 mol/dm3 NaOH in a calorimeter and the temperature rises by 6.3 degC. Calculate the molar enthalpy of neutralisation. (Assume the mixture has mass 100 g and specific heat capacity 4.2 J/g degC)",
      ["-52.9 kJ/mol", "-6.3 kJ/mol", "-2.65 kJ/mol", "-105.8 kJ/mol"], "-52.9 kJ/mol",
      "Heat evolved, q = mc(delta)T = 100 x 4.2 x 6.3 = 2646 J = 2.646 kJ. Moles of acid (= moles of water formed) = 0.050 dm3 x 1.0 mol/dm3 = 0.05 mol. Molar enthalpy = -2.646/0.05 = -52.9 kJ/mol."),
  _q("Which of the following processes is exothermic?",
      ["Combustion of methane in oxygen", "Photosynthesis in green plants", "Thermal decomposition of calcium trioxocarbonate(IV)", "Dissolving ammonium chloride crystals in water"], "Combustion of methane in oxygen",
      "Combustion always releases heat energy to the surroundings, whereas photosynthesis, thermal decomposition, and dissolving ammonium salts typically absorb heat (endothermic)."),
  _q("Bond breaking during a chemical reaction is always",
      ["endothermic, since energy must be supplied to separate bonded atoms", "exothermic, since energy is released when bonds break", "neither exothermic nor endothermic", "dependent only on the identity of the catalyst used"], "endothermic, since energy must be supplied to separate bonded atoms",
      "Breaking a chemical bond always requires an input of energy to overcome the attractive forces holding atoms together, making bond breaking inherently endothermic."),
  _q("Bond formation during a chemical reaction is always",
      ["exothermic, since energy is released as new, more stable bonds form", "endothermic, since energy must be absorbed", "neither exothermic nor endothermic", "only exothermic for ionic compounds"], "exothermic, since energy is released as new, more stable bonds form",
      "When new bonds form, the atoms move to a lower, more stable energy state, releasing energy to the surroundings, so bond formation is always exothermic."),
  _q("Which quantity is directly obtained from a calorimetry experiment measuring temperature rise?",
      ["The heat change (q) of the reaction", "The activation energy of the reaction", "The rate constant of the reaction", "The equilibrium constant of the reaction"], "The heat change (q) of the reaction",
      "Calorimetry uses the measured mass, specific heat capacity, and temperature change (q = mcΔT) of the surrounding solution to determine the heat evolved or absorbed by a reaction."),
  _q("The minimum energy that colliding particles must possess before a reaction can occur is called the",
      ["activation energy", "bond dissociation energy", "lattice energy", "ionisation energy"], "activation energy",
      "Activation energy is the energy barrier that must be overcome for reacting particles to be converted into products during an effective collision."),
  _q("A catalyst increases reaction rate without altering the overall enthalpy change because it",
      ["provides an alternative reaction pathway of lower activation energy for both the forward and reverse reactions", "increases the energy of the reactants permanently", "is consumed and regenerated at a different overall energy", "changes the identity of the products formed"], "provides an alternative reaction pathway of lower activation energy for both the forward and reverse reactions",
      "A catalyst lowers the activation energy barrier equally for the forward and reverse reactions, speeding up the approach to equilibrium, but the energy difference between reactants and products (ΔH) is unaffected."),
];

final _acidsBasesSalts = [
  _q("According to the Arrhenius definition, an acid is a substance that",
      ["produces hydrogen ions (H+) as the only positive ions when dissolved in water", "produces hydroxide ions (OH-) when dissolved in water", "accepts a pair of electrons in a reaction", "donates a lone pair of electrons in a reaction"], "produces hydrogen ions (H+) as the only positive ions when dissolved in water",
      "The Arrhenius theory defines an acid narrowly as a substance that ionises in aqueous solution to give H+ (H3O+) as the only cation."),
  _q("According to the Arrhenius definition, a base is a substance that",
      ["produces hydroxide ions (OH-) as the only negative ions when dissolved in water", "donates protons in any solvent", "accepts protons in any solvent", "accepts a pair of electrons"], "produces hydroxide ions (OH-) as the only negative ions when dissolved in water",
      "Arrhenius bases dissociate in water to release OH- ions as the only anion, e.g. NaOH -> Na+ + OH-."),
  _q("According to the Bronsted-Lowry theory, an acid is defined as a",
      ["proton (H+) donor", "proton (H+) acceptor", "substance that produces OH- in water only", "electron-pair acceptor only in aqueous solution"], "proton (H+) donor",
      "The Bronsted-Lowry theory broadens the acid definition beyond water: an acid is any species that can donate a proton to another species, even in non-aqueous solvents."),
  _q("According to the Bronsted-Lowry theory, a base is defined as a",
      ["proton (H+) acceptor", "proton (H+) donor", "substance that produces H+ in water only", "electron-pair donor only in aqueous solution"], "proton (H+) acceptor",
      "A Bronsted-Lowry base accepts a proton from an acid, for example NH3 accepting H+ to form NH4+, even though NH3 contains no hydroxide ions itself."),
  _q("According to the Lewis theory, an acid is defined as a species that",
      ["accepts a pair of electrons to form a new covalent bond", "donates a pair of electrons to form a new covalent bond", "donates a proton to a base", "produces H+ ions in aqueous solution"], "accepts a pair of electrons to form a new covalent bond",
      "The Lewis theory is the broadest definition: a Lewis acid is an electron-pair acceptor, which explains why species like BF3 and Al3+, which have no protons to donate, still behave as acids."),
  _q("According to the Lewis theory, a base is defined as a species that",
      ["donates a pair of electrons to form a new covalent bond", "accepts a pair of electrons to form a new covalent bond", "accepts a proton from an acid", "produces OH- ions in aqueous solution"], "donates a pair of electrons to form a new covalent bond",
      "A Lewis base has an available lone pair of electrons that it donates to form a coordinate (dative) bond with a Lewis acid, e.g. NH3 donating its lone pair to H+ or to BF3."),
  _q("What is the pH of a 0.001 mol/dm3 solution of hydrochloric acid, a strong monobasic acid that ionises completely?",
      ["3", "1", "11", "0.001"], "3",
      "For a strong monobasic acid, [H+] = concentration = 0.001 = 1 x 10^-3 mol/dm3. pH = -log[H+] = -log(1 x 10^-3) = 3."),
  _q("A solution has a pH of 10. What is its pOH, given that pH + pOH = 14 at 25 degC?",
      ["4", "10", "14", "24"], "4",
      "Since pH + pOH = pKw = 14 at 25 degC, pOH = 14 - pH = 14 - 10 = 4."),
  _q("A solution has a pH of 5. What is the hydrogen ion concentration, [H+], of the solution?",
      ["1 x 10^-5 mol/dm3", "1 x 10^-9 mol/dm3", "5 mol/dm3", "1 x 10^5 mol/dm3"], "1 x 10^-5 mol/dm3",
      "Since pH = -log[H+], [H+] = 10^-pH = 10^-5 = 1 x 10^-5 mol/dm3."),
  _q("What is the value of the ionic product of water, Kw, at 25 degC, and its corresponding pKw?",
      ["Kw = 1 x 10^-14 mol2/dm6, pKw = 14", "Kw = 1 x 10^-7 mol2/dm6, pKw = 7", "Kw = 1 x 10^-14 mol2/dm6, pKw = 7", "Kw = 1 mol2/dm6, pKw = 0"], "Kw = 1 x 10^-14 mol2/dm6, pKw = 14",
      "At 25 degC, pure water has [H+] = [OH-] = 1 x 10^-7 mol/dm3, so Kw = [H+][OH-] = 1 x 10^-14, and pKw = -log(Kw) = 14."),
  _q("When a reactive metal such as magnesium reacts with a dilute acid, the products formed are",
      ["a salt and hydrogen gas", "a salt and water only", "a salt, water, and carbon dioxide", "an oxide and water"], "a salt and hydrogen gas",
      "Metal + acid -> salt + hydrogen, e.g. Mg + 2HCl -> MgCl2 + H2, since the metal displaces the acidic hydrogen from the acid."),
  _q("When an acid reacts with a trioxocarbonate(IV) salt (a carbonate), the products formed are",
      ["a salt, water, and carbon dioxide gas", "a salt and hydrogen gas only", "a salt and oxygen gas", "an oxide and hydrogen"], "a salt, water, and carbon dioxide gas",
      "Acid + carbonate -> salt + water + carbon dioxide, e.g. CaCO3 + 2HCl -> CaCl2 + H2O + CO2, and the CO2 evolved turns limewater milky."),
  _q("Potassium aluminium sulphate, KAl(SO4)2.12H2O (alum), is a classic example of a",
      ["double salt", "normal salt", "complex salt", "basic salt"], "double salt",
      "A double salt is formed when two simple salts crystallise together from solution in fixed proportions, and in solution it ionises to give all the simple ions (K+, Al3+, SO4 2-) present in the separate salts."),
  _q("The tetraamminecopper(II) ion, [Cu(NH3)4]2+, is an example of a",
      ["complex ion, formed by coordinate bonding between a central metal ion and surrounding ligands", "double salt formed by simple ionic combination", "normal salt with no acidic hydrogen", "basic salt containing a hydroxide group"], "complex ion, formed by coordinate bonding between a central metal ion and surrounding ligands",
      "In a complex ion, ligands (here, NH3 molecules) donate lone pairs of electrons to form coordinate bonds with a central metal ion, and the complex ion retains its identity in solution, unlike a double salt."),
  _q("Basic lead(II) trioxocarbonate(IV), Pb(OH)2.2PbCO3, is classified as a",
      ["basic salt, since it contains hydroxide ions in addition to the acid radical", "acid salt, since it contains a replaceable hydrogen atom", "normal salt with no extra OH- or H+", "double salt of two different metals"], "basic salt, since it contains hydroxide ions in addition to the acid radical",
      "A basic salt is formed by incomplete replacement of the hydroxide ions of a base, so it still contains OH- groups combined with the acid radical, distinguishing it from a normal salt."),
  _q("Sodium salts of very reactive metals, such as sodium chloride, are best prepared in the laboratory as soluble salts by",
      ["direct titration of the acid against the alkali using an indicator, followed by evaporation and crystallisation", "adding excess metal to the acid and filtering off the excess", "double decomposition (precipitation) of two soluble salts", "heating the metal directly in the acid vapour"], "direct titration of the acid against the alkali using an indicator, followed by evaporation and crystallisation",
      "Because sodium is too reactive to be added directly to acid, its soluble salt is prepared by exact acid-alkali titration (using an indicator to find the volumes needed), then removing the indicator and crystallising the salt from the neutral solution."),
  _q("An insoluble salt such as lead(II) chloride is best prepared in the laboratory by",
      ["mixing solutions of two suitable soluble salts so that the insoluble salt precipitates out, then filtering", "reacting the metal directly with a dilute acid", "titrating the corresponding acid against an alkali", "heating the corresponding oxide strongly"], "mixing solutions of two suitable soluble salts so that the insoluble salt precipitates out, then filtering",
      "Insoluble salts are prepared by double decomposition (precipitation): mixing solutions containing the required cation and anion (e.g. lead(II) nitrate and sodium chloride) so the insoluble product precipitates immediately and can be filtered off."),
  _q("A substance that absorbs moisture from the air and eventually dissolves completely to form a solution is said to be",
      ["deliquescent", "efflorescent", "hygroscopic only", "anhydrous"], "deliquescent",
      "Deliquescent substances, such as anhydrous calcium chloride and sodium hydroxide, absorb so much atmospheric water vapour that they dissolve in it, forming an aqueous solution."),
  _q("A hydrated crystalline salt that loses some or all of its water of crystallisation to the atmosphere, forming a powdery surface, is said to be",
      ["efflorescent", "deliquescent", "hygroscopic", "volatile"], "efflorescent",
      "Efflorescent salts, such as sodium carbonate decahydrate (Na2CO3.10H2O), lose water of crystallisation on exposure to air, crumbling into a powder as they effloresce."),
  _q("A substance that absorbs moisture from the air but does not dissolve or turn into a solution is described as",
      ["hygroscopic", "deliquescent", "efflorescent", "volatile"], "hygroscopic",
      "Hygroscopic substances, such as silica gel and quicklime (CaO), take up atmospheric moisture and retain it, but they remain essentially solid rather than dissolving away."),
];

final _solubilityKinetics = [
  _q("A saturated solution is one that",
      ["contains the maximum amount of dissolved solute in equilibrium with undissolved solute at that temperature", "contains less solute than the solvent can possibly dissolve", "contains no dissolved solute at all", "always has more dissolved solute than a supersaturated solution"], "contains the maximum amount of dissolved solute in equilibrium with undissolved solute at that temperature",
      "In a saturated solution, the rate of solute dissolving equals the rate of solute recrystallising, so it holds the maximum possible dissolved amount at that temperature."),
  _q("An unsaturated solution is one that",
      ["can still dissolve more solute at the given temperature", "cannot dissolve any additional solute", "contains excess undissolved solute", "has crystals forming spontaneously"], "can still dissolve more solute at the given temperature",
      "An unsaturated solution has not yet reached its solubility limit, so more solute can still be dissolved in it at that temperature."),
  _q("A supersaturated solution is one that",
      ["contains more dissolved solute than the solution would normally hold at that temperature, and is often prepared by carefully cooling a saturated solution", "is simply a dilute solution", "cannot exist under any circumstances", "always has undissolved solute visibly present"], "contains more dissolved solute than the solution would normally hold at that temperature, and is often prepared by carefully cooling a saturated solution",
      "Supersaturated solutions are unstable; they are usually made by dissolving solute in hot solvent to saturation and then cooling slowly without disturbance, so excess solute remains dissolved."),
  _q("40 g of a salt dissolves in 100 g of water at 80 degC to form a saturated solution. If the solubility of the salt at 20 degC is 25 g per 100 g of water, what mass of salt crystallises out when the solution is cooled from 80 degC to 20 degC?",
      ["15 g", "25 g", "40 g", "65 g"], "15 g",
      "The solution originally holds 40 g dissolved in 100 g water. At 20 degC, only 25 g per 100 g water can remain dissolved, so the excess that crystallises out is 40 - 25 = 15 g."),
  _q("According to the solubility curve of most solid ionic solutes in water, solubility generally",
      ["increases as the temperature of the water increases", "decreases as the temperature of the water increases", "stays exactly constant regardless of temperature", "becomes zero above 50 degC"], "increases as the temperature of the water increases",
      "For most solids, dissolving is endothermic overall, so supplying more heat (raising temperature) helps break the solute lattice and allows more solute to dissolve."),
  _q("Unlike most solids, the solubility of gases in water generally",
      ["decreases as temperature increases", "increases as temperature increases", "is unaffected by temperature", "increases indefinitely with temperature"], "decreases as temperature increases",
      "Gas dissolving in a liquid is generally exothermic, so raising the temperature drives dissolved gas back out of solution, reducing solubility, which is why warm water holds less dissolved oxygen."),
  _q("Which of the following factors increases the rate of a chemical reaction?",
      ["Increasing the temperature of the reacting mixture", "Decreasing the concentration of the reactants", "Reducing the surface area of a solid reactant", "Removing the catalyst from the reaction mixture"], "Increasing the temperature of the reacting mixture",
      "Raising the temperature increases the average kinetic energy of particles, so more collisions occur per second and a greater proportion of them have energy at or above the activation energy."),
  _q("Increasing the concentration of a reactant in solution increases the rate of reaction mainly because it",
      ["increases the frequency of collisions between reacting particles per unit time", "increases the activation energy of the reaction", "decreases the average kinetic energy of the particles", "changes the identity of the products formed"], "increases the frequency of collisions between reacting particles per unit time",
      "A higher concentration means more particles are packed into the same volume, so collisions between reactant particles happen more frequently, speeding up the reaction."),
  _q("Powdered calcium trioxocarbonate(IV) reacts faster with dilute hydrochloric acid than an equal mass of the same substance in large lumps because powdering",
      ["increases the total surface area exposed to the acid, allowing more frequent collisions", "increases the activation energy of the reaction", "decreases the number of particles available to react", "converts the carbonate into a different compound"], "increases the total surface area exposed to the acid, allowing more frequent collisions",
      "Breaking a solid into smaller pieces exposes far more surface area to the acid, so many more particle collisions can occur at the exposed surface in a given time."),
  _q("A catalyst increases the rate of a reaction without being used up because it",
      ["provides an alternative pathway of lower activation energy and is regenerated at the end of the reaction", "permanently raises the average kinetic energy of the reacting particles", "increases the concentration of the reactants", "shifts the equilibrium position towards the products"], "provides an alternative pathway of lower activation energy and is regenerated at the end of the reaction",
      "Catalysts participate in intermediate steps of a reaction mechanism but are regenerated unchanged at the end, so a small quantity can catalyse a reaction indefinitely."),
  _q("According to collision theory, a chemical reaction occurs between two particles only when they",
      ["collide with sufficient energy (at least the activation energy) and with the correct orientation", "simply come close to one another, regardless of energy or orientation", "are both in the gaseous state", "have identical molecular masses"], "collide with sufficient energy (at least the activation energy) and with the correct orientation",
      "Not every collision leads to reaction; only 'effective' collisions, which have enough energy to overcome the activation barrier and the correct geometric orientation, result in a reaction."),
  _q("A reversible reaction is one in which",
      ["the products can react together to re-form the original reactants under suitable conditions", "the reaction can only proceed in the forward direction", "the reactants are completely converted to products with no reverse process possible", "a catalyst is always required for the reaction to occur at all"], "the products can react together to re-form the original reactants under suitable conditions",
      "In a reversible reaction, such as NH4Cl(s) <=> NH3(g) + HCl(g), the forward and reverse reactions can both occur, eventually reaching a dynamic equilibrium."),
  _q("According to Le Chatelier's Principle, if a system at equilibrium is subjected to an external change in conditions, the system responds by",
      ["shifting in the direction that tends to oppose or minimise the effect of that change", "always shifting completely towards the products", "remaining totally unaffected by the change", "always shifting completely towards the reactants"], "shifting in the direction that tends to oppose or minimise the effect of that change",
      "Le Chatelier's Principle predicts that the equilibrium position adjusts to counteract, as far as possible, any imposed change in concentration, pressure, or temperature."),
  _q("In the equilibrium 2SO2(g) + O2(g) <=> 2SO3(g) (the Contact Process), increasing the pressure on the system shifts the equilibrium",
      ["towards the products, since there are fewer gas moles (2) on that side than on the reactant side (3)", "towards the reactants, since there are fewer gas moles on that side", "in no particular direction, since pressure never affects gaseous equilibria", "completely towards the products regardless of temperature"], "towards the products, since there are fewer gas moles (2) on that side than on the reactant side (3)",
      "There are 3 moles of gas among the reactants (2SO2 + O2) but only 2 moles of gas among the products (2SO3); increasing pressure favours the side with fewer gas molecules, so equilibrium shifts towards SO3."),
  _q("The forward reaction 2SO2(g) + O2(g) <=> 2SO3(g) is exothermic. Increasing the temperature of this equilibrium mixture shifts the equilibrium",
      ["towards the reactants, since the system favours the endothermic (reverse) direction to absorb the extra heat", "towards the products, since heat always favours the forward reaction", "in no particular direction, since temperature does not affect this equilibrium", "completely towards the products, converting all the SO2"], "towards the reactants, since the system favours the endothermic (reverse) direction to absorb the extra heat",
      "By Le Chatelier's Principle, adding heat to an exothermic equilibrium favours the reverse (endothermic) reaction, so the equilibrium shifts back towards SO2 and O2, reducing the yield of SO3."),
  _q("Adding a catalyst to a reversible reaction at equilibrium",
      ["speeds up the rate at which equilibrium is reached but does not change the position of equilibrium", "shifts the equilibrium position towards the products", "shifts the equilibrium position towards the reactants", "has no effect on either the forward or reverse reaction rate"], "speeds up the rate at which equilibrium is reached but does not change the position of equilibrium",
      "A catalyst speeds up both the forward and reverse reactions equally, so equilibrium is reached faster, but the equilibrium concentrations (position) remain the same as without the catalyst."),
  _q("The rate of a chemical reaction is generally defined as the",
      ["change in concentration of a reactant or product per unit time", "total energy released by the reaction", "total mass of reactants used in the reaction", "time taken for the reaction to start"], "change in concentration of a reactant or product per unit time",
      "Reaction rate is quantified as how quickly the concentration of a chosen reactant decreases, or a chosen product increases, over a given time interval."),
];

final _electrochemistry = [
  _q("What is the oxidation number of manganese in the manganate(VII) ion, MnO4-?",
      ["+7", "+6", "+4", "+2"], "+7",
      "Let Mn = x. The overall charge is -1: x + 4(-2) = -1, so x - 8 = -1, giving x = +7."),
  _q("In the ion-electron (half-equation) method for balancing MnO4- + Fe2+ + H+ -> Mn2+ + Fe3+ + H2O, the reduction half-equation is",
      ["MnO4- + 8H+ + 5e- -> Mn2+ + 4H2O", "Fe2+ -> Fe3+ + e-", "MnO4- -> Mn2+ + 4O2-", "Fe3+ + e- -> Fe2+"], "MnO4- + 8H+ + 5e- -> Mn2+ + 4H2O",
      "Manganese goes from +7 in MnO4- to +2 in Mn2+, a gain of 5 electrons; balancing oxygen with water and hydrogen with H+ gives MnO4- + 8H+ + 5e- -> Mn2+ + 4H2O."),
  _q("Combining the half-equations MnO4- + 8H+ + 5e- -> Mn2+ + 4H2O and Fe2+ -> Fe3+ + e-, the overall balanced ionic equation for the reaction is",
      ["MnO4- + 8H+ + 5Fe2+ -> Mn2+ + 4H2O + 5Fe3+", "MnO4- + 2H+ + Fe2+ -> Mn2+ + H2O + Fe3+", "MnO4- + 8H+ + Fe2+ -> Mn2+ + 4H2O + Fe3+", "2MnO4- + 8H+ + 5Fe2+ -> 2Mn2+ + 4H2O + 5Fe3+"], "MnO4- + 8H+ + 5Fe2+ -> Mn2+ + 4H2O + 5Fe3+",
      "Since MnO4- gains 5 electrons but Fe2+ only loses 1 electron per ion, the iron half-equation must be multiplied by 5 so that electrons lost equal electrons gained, giving 5Fe2+ reacting with each MnO4-."),
  _q("An electrolyte is best described as a substance that",
      ["conducts electricity when molten or dissolved in water, undergoing chemical decomposition in the process", "conducts electricity in the solid state without any chemical change", "never conducts electricity in any physical state", "conducts electricity only when it is a pure solid metal"], "conducts electricity when molten or dissolved in water, undergoing chemical decomposition in the process",
      "Electrolytes are ionic compounds (or some covalent compounds that ionise) that conduct electric current when their ions are mobile, in the molten or aqueous state, with accompanying chemical decomposition at the electrodes."),
  _q("A non-electrolyte is a substance that",
      ["does not conduct electricity, whether in the molten state, dissolved in water, or as a pure liquid", "conducts electricity only when molten", "conducts electricity only when dissolved in water", "always conducts electricity in every physical state"], "does not conduct electricity, whether in the molten state, dissolved in water, or as a pure liquid",
      "Non-electrolytes, such as sugar solution or pure ethanol, lack freely moving ions and therefore cannot carry electric current in any state."),
  _q("In an electrolytic cell, unlike a simple voltaic (galvanic) cell, electrical energy from an external source is used to",
      ["drive a non-spontaneous chemical reaction (decomposition of the electrolyte)", "generate electrical energy from a spontaneous chemical reaction", "measure the pH of a solution", "prevent any chemical reaction from occurring"], "drive a non-spontaneous chemical reaction (decomposition of the electrolyte)",
      "An electrolytic cell consumes electrical energy supplied by an external battery or power source to force a normally non-spontaneous decomposition reaction to occur."),
  _q("In the electrolysis of concentrated brine (concentrated aqueous sodium chloride) using inert electrodes, the ion selectively discharged at the anode is",
      ["chloride, Cl-, because of its high concentration, despite hydroxide normally being preferentially discharged", "hydroxide, OH-, because it is always preferentially discharged over any other anion", "sodium, Na+, because it migrates to the anode", "hydrogen, H+, because it migrates to the anode"], "chloride, Cl-, because of its high concentration, despite hydroxide normally being preferentially discharged",
      "Selective discharge depends on ion concentration as well as position in the electrochemical series; in concentrated brine, the very high Cl- concentration allows it to be discharged in preference to OH- at the anode, producing chlorine gas."),
  _q("Faraday's First Law of Electrolysis states that the mass of a substance liberated or deposited at an electrode is directly proportional to",
      ["the quantity of electric charge that passes through the electrolyte", "the temperature of the electrolyte solution", "the surface area of the electrolytic cell", "the distance between the two electrodes"], "the quantity of electric charge that passes through the electrolyte",
      "Faraday's First Law can be written as m = zQ (or m = zIt), showing that mass deposited is directly proportional to the total charge (Q = It) passed."),
  _q("Faraday's Second Law of Electrolysis states that when the same quantity of electricity is passed through different electrolytes, the masses of the substances liberated at the electrodes are proportional to their",
      ["chemical equivalent weights", "atomic numbers", "densities", "melting points"], "chemical equivalent weights",
      "For a fixed charge passed, different substances are deposited or liberated in amounts proportional to their equivalent weight (molar mass divided by the number of electrons transferred per ion)."),
  _q("A current of 2 amperes is passed through molten lead(II) bromide for 965 seconds. Calculate the quantity of electric charge (Q) passed, using Q = It.",
      ["1930 C", "965 C", "482.5 C", "2895 C"], "1930 C",
      "Q = It = 2 A x 965 s = 1930 coulombs."),
  _q("A current of 5 A is passed through a solution of silver nitrate for 30 minutes to electroplate a spoon. Calculate the mass of silver deposited. (Ag = 108, 1 Faraday = 96500 C, Ag+ + e- -> Ag)",
      ["10.07 g", "5.4 g", "20.14 g", "1.87 g"], "10.07 g",
      "Time = 30 x 60 = 1800 s. Charge, Q = It = 5 x 1800 = 9000 C. Moles of electrons = 9000/96500 = 0.0933 mol. Since 1 mole of electrons deposits 1 mole of Ag, moles Ag = 0.0933 mol. Mass = 0.0933 x 108 = 10.07 g."),
  _q("A quantity of charge equal to 3 Faradays is passed through molten aluminium oxide. Calculate the mass of aluminium deposited at the cathode. (Al = 27, Al3+ + 3e- -> Al, 1 Faraday = 1 mole of electrons)",
      ["27 g", "81 g", "9 g", "54 g"], "27 g",
      "Al3+ requires 3 moles of electrons (3 Faradays) to deposit 1 mole of aluminium. Moles Al = 3 Faradays / 3 = 1 mole. Mass = 1 x 27 = 27 g."),
  _q("Electroplating an iron spoon with silver is carried out by making the spoon the",
      ["cathode in a solution of a silver salt, with a silver anode", "anode in a solution of a silver salt, with a silver cathode", "cathode in molten silver metal", "anode in molten silver metal"], "cathode in a solution of a silver salt, with a silver anode",
      "In electroplating, the object to be coated is always the cathode so that metal cations from solution are reduced and deposited onto its surface, while the anode (made of the plating metal) dissolves to replenish the ions."),
  _q("In the electrolytic purification (refining) of copper, impure copper is made the",
      ["anode, which dissolves, while pure copper is deposited at the cathode", "cathode, which dissolves, while pure copper is deposited at the anode", "anode and cathode simultaneously", "electrolyte itself, dissolved directly in water"], "anode, which dissolves, while pure copper is deposited at the cathode",
      "During purification, impure copper is the anode; it dissolves as Cu2+ ions enter solution (Cu -> Cu2+ + 2e-), while at the pure copper cathode, Cu2+ ions are reduced and deposited as pure copper (Cu2+ + 2e- -> Cu)."),
  _q("In the electrolytic purification of copper described above, the insoluble impurities (such as gold and silver) originally present in the impure anode",
      ["fall to the bottom of the cell as anode sludge (anode mud)", "are deposited together with the pure copper at the cathode", "dissolve completely into the electrolyte solution", "escape from the cell as a gas"], "fall to the bottom of the cell as anode sludge (anode mud)",
      "Precious metal impurities that are less reactive than copper do not dissolve into the electrolyte; they simply fall away from the disintegrating anode and collect as valuable anode sludge."),
  _q("When two different metal ions are present in an electrolyte, the ion that is preferentially discharged at the cathode is generally the one that is",
      ["lower in the electrochemical (reactivity) series", "higher in the electrochemical (reactivity) series", "present in the smallest concentration", "always the alkali metal ion"], "lower in the electrochemical (reactivity) series",
      "Less reactive metal ions (lower in the electrochemical series, such as Cu2+ compared with Na+) are more easily reduced and are therefore selectively discharged at the cathode first."),
  _q("Oxidation number is best defined as",
      ["the charge an atom would have if the compound were composed entirely of ions", "the actual physical charge measured on every atom in a compound", "the total number of electrons in an atom", "the number of covalent bonds an atom can form"], "the charge an atom would have if the compound were composed entirely of ions",
      "Oxidation number is a bookkeeping device, assigning a hypothetical ionic charge to each atom according to a set of rules, used to track electron transfer in redox reactions even within covalent compounds."),
  _q("In the electrolysis of dilute sulphuric acid using platinum electrodes, the volume ratio of gas collected at the cathode to gas collected at the anode is approximately",
      ["2:1 (hydrogen to oxygen)", "1:2 (hydrogen to oxygen)", "1:1", "4:1"], "2:1 (hydrogen to oxygen)",
      "Water is decomposed as 2H2O -> 2H2 + O2; hydrogen is liberated at the cathode and oxygen at the anode in a 2:1 volume ratio, consistent with the formula of water."),
];

final _organicChemistry = [
  _q("What is the IUPAC name of the straight-chain alkane with molecular formula C5H12?",
      ["Pentane", "Butane", "Hexane", "Propane"], "Pentane",
      "Alkanes are named with the prefix indicating the number of carbon atoms plus the suffix '-ane'; five carbons in a saturated chain gives 'pentane'."),
  _q("What is the IUPAC name of the alkene CH3-CH2-CH=CH2?",
      ["But-1-ene", "But-2-ene", "Propene", "Pentene"], "But-1-ene",
      "The longest chain has 4 carbons (a butene) and the double bond starts at carbon 1 (counting from the end nearest the double bond), so it is named but-1-ene."),
  _q("What is the IUPAC name of the simplest alkyne, with molecular formula C2H2?",
      ["Ethyne", "Ethene", "Ethane", "Methyne"], "Ethyne",
      "Alkynes contain at least one carbon-carbon triple bond and take the suffix '-yne'; the two-carbon member is ethyne (commonly called acetylene)."),
  _q("Which functional group is characteristic of the alkanols (alcohols)?",
      ["-OH (hydroxyl group)", "-COOH (carboxyl group)", "-COO- (ester linkage)", "-NH2 (amine group)"], "-OH (hydroxyl group)",
      "Alkanols are identified by a hydroxyl group, -OH, attached to a saturated carbon chain, as in ethanol, CH3CH2OH."),
  _q("Which functional group is characteristic of the alkanoic acids (carboxylic acids)?",
      ["-COOH (carboxyl group)", "-OH (hydroxyl group)", "-CHO (aldehyde group)", "-NH2 (amine group)"], "-COOH (carboxyl group)",
      "The carboxyl group, -COOH, gives alkanoic acids their characteristic weak acidity, as seen in ethanoic (acetic) acid, CH3COOH."),
  _q("Which functional group is characteristic of the alkanoates (esters)?",
      ["-COO- (ester linkage)", "-OH (hydroxyl group)", "-COOH (carboxyl group)", "-NH2 (amine group)"], "-COO- (ester linkage)",
      "Esters (alkanoates) contain the -COO- linkage formed when the -OH of a carboxylic acid condenses with the -OH of an alcohol, releasing water."),
  _q("Which functional group is characteristic of the amines?",
      ["-NH2 (amino group)", "-OH (hydroxyl group)", "-COOH (carboxyl group)", "-CHO (aldehyde group)"], "-NH2 (amino group)",
      "Amines contain an amino group, -NH2, derived formally from ammonia, and behave as weak bases because of the lone pair of electrons on the nitrogen atom."),
  _q("Amines behave as weak bases mainly because",
      ["the nitrogen atom has a lone pair of electrons that can accept a proton", "they contain a hydroxyl group that releases OH-", "they are strongly acidic in aqueous solution", "they contain no nitrogen atom"], "the nitrogen atom has a lone pair of electrons that can accept a proton",
      "The lone pair on the nitrogen of an amine can accept a proton (H+) from water or an acid, forming an alkylammonium ion, which is the basis of their weak basic character."),
  _q("Structural isomerism occurs when two or more compounds",
      ["have the same molecular formula but different structural arrangements of atoms", "have completely different molecular formulae", "are simply different physical states of the same compound", "have the same structural formula but different molecular masses"], "have the same molecular formula but different structural arrangements of atoms",
      "Structural isomers share an identical molecular formula (same numbers of each type of atom) but differ in how those atoms are bonded together or arranged."),
  _q("Butane, C4H10, has a straight-chain structural isomer and a branched-chain structural isomer. What is the IUPAC name of its branched-chain isomer?",
      ["2-methylpropane", "2-methylbutane", "Pentane", "Cyclobutane"], "2-methylpropane",
      "C4H10 exists as straight-chain butane and as its branched isomer, 2-methylpropane (also called isobutane), both sharing the molecular formula C4H10 but differing in carbon skeleton arrangement."),
  _q("Fractional distillation is used to separate crude oil into useful fractions such as petrol, kerosene, and diesel, based mainly on differences in",
      ["boiling point of the hydrocarbon components", "colour of the hydrocarbon components", "density of the hydrocarbon components only", "solubility of the hydrocarbon components in water"], "boiling point of the hydrocarbon components",
      "Crude oil is heated and passed up a fractionating column with a temperature gradient; each fraction condenses out at the height corresponding to its characteristic range of boiling points."),
  _q("Cracking of large hydrocarbon molecules from crude oil is carried out mainly to",
      ["convert less useful, high-boiling-point hydrocarbons into smaller, more useful alkanes and alkenes", "combine small hydrocarbon molecules into larger ones", "remove sulphur impurities from crude oil", "separate crude oil into its fractions by boiling point"], "convert less useful, high-boiling-point hydrocarbons into smaller, more useful alkanes and alkenes",
      "Cracking uses heat and/or a catalyst to break carbon-carbon bonds in large hydrocarbon molecules, producing a mixture of smaller, more commercially useful alkanes and alkenes."),
  _q("In addition polymerisation, such as the formation of poly(ethene) from ethene monomers, the reaction proceeds",
      ["by monomers joining across their carbon-carbon double bonds, with no small by-product molecule formed", "by monomers joining with the loss of a small molecule such as water at each linkage", "only between two different types of monomer", "only in the presence of a strong acid catalyst"], "by monomers joining across their carbon-carbon double bonds, with no small by-product molecule formed",
      "Addition polymerisation opens up the C=C double bonds of unsaturated monomers, allowing them to link directly together without releasing any by-product, unlike condensation polymerisation."),
  _q("In condensation polymerisation, such as the formation of a polyester (terylene) or nylon, the reaction proceeds",
      ["by monomers joining together with the elimination of a small molecule, typically water, at each linkage", "by monomers simply adding across carbon-carbon double bonds", "without any chemical reaction between the monomer units", "only using monomers that contain a carbon-carbon triple bond"], "by monomers joining together with the elimination of a small molecule, typically water, at each linkage",
      "Condensation polymerisation joins monomers bearing two reactive functional groups (such as -COOH and -OH, or -COOH and -NH2), releasing a small molecule (usually water) at every new linkage formed."),
  _q("Saponification is the process in which",
      ["an ester (fat or oil) is hydrolysed by a hot concentrated alkali to form soap (a sodium or potassium salt of a fatty acid) and glycerol", "an alkanol reacts with an alkanoic acid to form an ester and water", "an alkene reacts with hydrogen in the presence of a nickel catalyst", "a carbonate reacts with a dilute acid to release carbon dioxide"], "an ester (fat or oil) is hydrolysed by a hot concentrated alkali to form soap (a sodium or potassium salt of a fatty acid) and glycerol",
      "Saponification is alkaline hydrolysis of a triglyceride ester (fat/oil), breaking the ester linkages to yield soap (the fatty acid salt) and glycerol (propane-1,2,3-triol) as by-products."),
  _q("Esterification is the reaction between an alkanoic acid and an alkanol, catalysed by concentrated sulphuric acid, to produce",
      ["an ester and water", "a soap and glycerol", "an alkene and hydrogen", "a salt and carbon dioxide"], "an ester and water",
      "Esterification is a condensation reaction: alkanoic acid + alkanol -(conc. H2SO4)-> ester + water, e.g. ethanoic acid + ethanol -> ethyl ethanoate + water."),
  _q("What is the name of the ester formed from the reaction between ethanoic acid and ethanol?",
      ["Ethyl ethanoate", "Ethyl methanoate", "Methyl ethanoate", "Ethanoic ethanol"], "Ethyl ethanoate",
      "Ester names combine the alcohol-derived part (ethyl, from ethanol) with the acid-derived part (ethanoate, from ethanoic acid), giving ethyl ethanoate, CH3COOC2H5."),
];

final _quantitativeQualitativeAnalysis = [
  _q("Volumetric analysis is a quantitative technique that determines the concentration of a solution by",
      ["measuring the volume of a solution of known concentration that exactly reacts with a measured volume of the solution being analysed", "weighing the mass of a solid precipitate formed", "measuring the volume of gas evolved from a reaction", "measuring the electrical conductivity of the solution"], "measuring the volume of a solution of known concentration that exactly reacts with a measured volume of the solution being analysed",
      "Volumetric analysis (titration) uses a standard solution of known concentration added from a burette until the reaction with a measured volume of the unknown solution is exactly complete, as shown by an indicator."),
  _q("In a titration between a strong acid and a strong base, a suitable indicator would be",
      ["either methyl orange or phenolphthalein, since both change colour sharply within the steep pH range of the equivalence point", "only universal indicator, since it must show a numerical pH value", "only starch-iodide indicator", "no indicator is required at all"], "either methyl orange or phenolphthalein, since both change colour sharply within the steep pH range of the equivalence point",
      "A strong acid-strong base titration has a very steep pH jump near the equivalence point (roughly pH 4 to pH 10), so both methyl orange and phenolphthalein change colour sharply within that range."),
  _q("In a titration between a weak acid and a strong base, the most suitable indicator to use is",
      ["phenolphthalein, since the equivalence point occurs on the alkaline side of pH 7", "methyl orange, since the equivalence point occurs on the acidic side of pH 7", "litmus, since it changes colour gradually over a wide pH range", "starch, since it only detects iodine"], "phenolphthalein, since the equivalence point occurs on the alkaline side of pH 7",
      "For a weak acid-strong base titration, the salt formed is slightly alkaline at the equivalence point, so phenolphthalein (which changes colour in the alkaline pH range, about 8.2-10) is the appropriate indicator."),
  _q("In a titration between a strong acid and a weak base, the most suitable indicator to use is",
      ["methyl orange, since the equivalence point occurs on the acidic side of pH 7", "phenolphthalein, since the equivalence point occurs on the alkaline side of pH 7", "universal indicator, since only it can be used with weak bases", "no indicator can be used with a weak base"], "methyl orange, since the equivalence point occurs on the acidic side of pH 7",
      "With a strong acid and a weak base, the salt formed is slightly acidic at the equivalence point, so methyl orange (which changes colour in the acidic pH range, about 3.1-4.4) is the appropriate indicator."),
  _q("20 cm3 of a NaOH solution of unknown concentration exactly neutralises 25 cm3 of 0.05 mol/dm3 H2SO4. Calculate the concentration of the NaOH solution. (H2SO4 + 2NaOH -> Na2SO4 + 2H2O)",
      ["0.125 mol/dm3", "0.0625 mol/dm3", "0.25 mol/dm3", "0.05 mol/dm3"], "0.125 mol/dm3",
      "Moles of H2SO4 = 0.025 dm3 x 0.05 mol/dm3 = 0.00125 mol. Since the mole ratio of acid to base is 1:2, moles of NaOH = 2 x 0.00125 = 0.0025 mol. Concentration of NaOH = 0.0025 mol / 0.020 dm3 = 0.125 mol/dm3."),
  _q("4.6 g of a monobasic acid, HA, is dissolved in water and made up to 250 cm3 of solution. A 25 cm3 portion of this solution requires 20 cm3 of 0.25 mol/dm3 NaOH for complete neutralisation (HA + NaOH -> NaA + H2O). Calculate the molar mass of the acid.",
      ["92 g/mol", "46 g/mol", "184 g/mol", "23 g/mol"], "92 g/mol",
      "Moles NaOH used = 0.020 dm3 x 0.25 mol/dm3 = 0.005 mol = moles of acid in the 25 cm3 portion (1:1 ratio). Moles of acid in the full 250 cm3 = 0.005 x 10 = 0.05 mol. Molar mass = mass/moles = 4.6 g / 0.05 mol = 92 g/mol."),
  _q("2.86 g of hydrated sodium trioxocarbonate(IV), Na2CO3.xH2O, is dissolved and made up to 250 cm3 of solution. A 25 cm3 portion requires 20 cm3 of 0.1 mol/dm3 HCl for complete reaction (Na2CO3 + 2HCl -> 2NaCl + H2O + CO2). Calculate the value of x. (Na2CO3 = 106, H2O = 18)",
      ["10", "7", "5", "12"], "10",
      "Moles HCl in aliquot = 0.020 x 0.1 = 0.002 mol. Moles Na2CO3 in aliquot = 0.002/2 = 0.001 mol. Moles in the full 250 cm3 = 0.001 x 10 = 0.01 mol. Molar mass of hydrate = 2.86 g / 0.01 mol = 286 g/mol. Mass of water = 286 - 106 = 180 g, so x = 180/18 = 10, giving Na2CO3.10H2O."),
  _q("Adding sodium hydroxide solution dropwise, then in excess, to a solution containing Fe2+ ions produces",
      ["a green precipitate that is insoluble in excess NaOH", "a reddish-brown precipitate that is insoluble in excess NaOH", "a white precipitate that dissolves in excess NaOH", "no visible precipitate at all"], "a green precipitate that is insoluble in excess NaOH",
      "Fe2+ ions form a dirty green gelatinous precipitate of iron(II) hydroxide with NaOH, which does not dissolve even when excess NaOH is added."),
  _q("Adding sodium hydroxide solution to a solution containing Fe3+ ions produces",
      ["a reddish-brown precipitate that is insoluble in excess NaOH", "a green precipitate that is insoluble in excess NaOH", "a white precipitate that is soluble in excess NaOH", "a blue precipitate that is soluble in excess NaOH"], "a reddish-brown precipitate that is insoluble in excess NaOH",
      "Fe3+ ions give a reddish-brown gelatinous precipitate of iron(III) hydroxide with NaOH, which remains insoluble even in excess of the alkali."),
  _q("Adding sodium hydroxide solution to a solution containing Cu2+ ions produces",
      ["a pale blue gelatinous precipitate that is insoluble in excess NaOH", "a white precipitate that is soluble in excess NaOH", "a green precipitate that is soluble in excess NaOH", "no precipitate, only a colour change of the solution"], "a pale blue gelatinous precipitate that is insoluble in excess NaOH",
      "Cu2+ ions form a pale blue precipitate of copper(II) hydroxide with NaOH, which persists (does not redissolve) even when excess NaOH is added."),
  _q("Adding sodium hydroxide solution dropwise, then in excess, to a solution containing Zn2+ ions produces",
      ["a white precipitate that dissolves in excess NaOH to form a colourless solution", "a white precipitate that remains insoluble in excess NaOH", "a blue precipitate that is insoluble in excess NaOH", "a reddish-brown precipitate that is insoluble in excess NaOH"], "a white precipitate that dissolves in excess NaOH to form a colourless solution",
      "Zn2+ forms an amphoteric white precipitate, zinc hydroxide, which dissolves in excess NaOH to form a soluble, colourless zincate complex, distinguishing it from Ca2+ or Fe ions."),
  _q("Adding sodium hydroxide solution dropwise, then in excess, to a solution containing Al3+ ions produces",
      ["a white precipitate that dissolves in excess NaOH to form a colourless solution", "a white precipitate that remains insoluble in excess NaOH", "a green precipitate that is insoluble in excess NaOH", "a reddish-brown precipitate that is soluble in excess NaOH"], "a white precipitate that dissolves in excess NaOH to form a colourless solution",
      "Al3+ forms an amphoteric white precipitate, aluminium hydroxide, which redissolves in excess NaOH to give a colourless aluminate solution, just like Zn2+."),
  _q("Adding sodium hydroxide solution to a solution containing Ca2+ ions produces",
      ["a white precipitate that remains insoluble even in excess NaOH", "a white precipitate that dissolves readily in excess NaOH", "a blue precipitate that is insoluble in excess NaOH", "no precipitate is formed at all"], "a white precipitate that remains insoluble even in excess NaOH",
      "Ca2+ gives a white precipitate of calcium hydroxide with NaOH (though only slightly soluble overall), and unlike Zn2+ or Al3+, this precipitate does not dissolve in excess alkali."),
  _q("Adding sodium hydroxide solution and gently warming a solution containing NH4+ (ammonium) ions produces",
      ["no precipitate, but a pungent gas is released that turns moist red litmus paper blue", "a white precipitate that is insoluble in excess NaOH", "a green precipitate that dissolves on warming", "a reddish-brown precipitate that dissolves on warming"], "no precipitate, but a pungent gas is released that turns moist red litmus paper blue",
      "NH4+ ions do not form a precipitate with NaOH; instead, warming releases ammonia gas, identifiable by its pungent smell and its ability to turn moist red litmus paper blue."),
  _q("Adding aqueous ammonia dropwise, then in excess, to a solution containing Cu2+ ions produces",
      ["a pale blue precipitate that dissolves in excess ammonia to form a deep blue solution", "a pale blue precipitate that remains insoluble in excess ammonia", "a white precipitate that dissolves in excess ammonia", "a reddish-brown precipitate insoluble in excess ammonia"], "a pale blue precipitate that dissolves in excess ammonia to form a deep blue solution",
      "Cu2+ first forms a pale blue precipitate of copper(II) hydroxide with a little ammonia, which then dissolves in excess ammonia to form the characteristic deep blue tetraamminecopper(II) complex."),
  _q("Which observation confirms the presence of the trioxocarbonate(IV) ion, CO3 2-, in a solid sample?",
      ["Effervescence with dilute acid, producing a gas that turns limewater milky", "A white precipitate forms immediately on adding water", "A pungent gas that turns moist red litmus blue is released", "A brown ring forms when the solid is mixed with iron(II) sulphate and concentrated sulphuric acid"], "Effervescence with dilute acid, producing a gas that turns limewater milky",
      "Carbonates react with dilute acids to effervesce, releasing carbon dioxide gas, which is confirmed by its ability to turn freshly prepared limewater milky (a white precipitate of CaCO3)."),
  _q("Which test confirms the presence of the sulphate(VI) ion, SO4 2-, in solution?",
      ["Adding dilute hydrochloric acid followed by barium chloride solution gives a white precipitate that is insoluble in the acid", "Adding barium chloride gives a white precipitate that dissolves readily in dilute hydrochloric acid", "Adding silver nitrate gives a yellow precipitate", "Adding acidified potassium heptaoxodichromate(VI) decolourises it"], "Adding dilute hydrochloric acid followed by barium chloride solution gives a white precipitate that is insoluble in the acid",
      "Sulphate ions form a white precipitate of barium sulphate with barium chloride that, crucially, does not dissolve in dilute hydrochloric acid, distinguishing SO4 2- from SO3 2-."),
  _q("Which observation distinguishes the sulphate(IV) ion (sulphite, SO3 2-) from the sulphate(VI) ion (sulphate, SO4 2-) when barium chloride is added?",
      ["The sulphite gives a white precipitate that dissolves in dilute hydrochloric acid, while the sulphate's precipitate does not", "The sulphite gives no precipitate at all with barium chloride", "The sulphate gives a yellow precipitate while the sulphite gives a white one", "Both give precipitates that dissolve equally in dilute hydrochloric acid"], "The sulphite gives a white precipitate that dissolves in dilute hydrochloric acid, while the sulphate's precipitate does not",
      "Both ions form white barium precipitates, but barium sulphite (unlike barium sulphate) readily dissolves in dilute hydrochloric acid, releasing sulphur dioxide gas, providing the distinguishing test."),
  _q("Which test confirms the presence of the chloride ion, Cl-, in solution?",
      ["Adding dilute nitric acid followed by silver nitrate solution gives a white precipitate that dissolves in excess aqueous ammonia", "Adding barium chloride solution gives a white precipitate insoluble in dilute hydrochloric acid", "Adding acidified potassium heptaoxodichromate(VI) turns the solution green", "Adding iron(II) sulphate and concentrated sulphuric acid gives a brown ring"], "Adding dilute nitric acid followed by silver nitrate solution gives a white precipitate that dissolves in excess aqueous ammonia",
      "Chloride ions form a white precipitate of silver chloride with acidified silver nitrate solution, and this precipitate characteristically dissolves in excess aqueous ammonia, unlike silver bromide or silver iodide."),
  _q("The brown ring test, in which a solution containing iron(II) sulphate is carefully layered with concentrated sulphuric acid, is used to confirm the presence of which ion?",
      ["Trioxonitrate(V), NO3-", "Trioxocarbonate(IV), CO3 2-", "Sulphate(VI), SO4 2-", "Chloride, Cl-"], "Trioxonitrate(V), NO3-",
      "The brown ring test is a classic confirmatory test for the nitrate ion: a brown ring of an iron-nitroso complex forms at the interface where the concentrated acid layer meets the iron(II) sulphate solution."),
  _q("Which observation confirms the identity of hydrogen gas?",
      ["It burns with a squeaky pop sound when a lit splint is introduced", "It relights a glowing splint", "It turns limewater milky", "It bleaches moist blue litmus paper"], "It burns with a squeaky pop sound when a lit splint is introduced",
      "Hydrogen gas is confirmed by the distinctive 'pop' sound produced when it combusts rapidly with oxygen in air on contact with a lit splint."),
  _q("Which observation confirms the identity of oxygen gas?",
      ["It relights a glowing splint", "It extinguishes a glowing splint", "It turns moist red litmus paper blue", "It gives a brown ring with iron(II) sulphate"], "It relights a glowing splint",
      "Oxygen supports combustion vigorously, so introducing a glowing (not flaming) splint into a test tube of the gas causes the splint to burst back into flame."),
  _q("Which observation confirms the identity of carbon dioxide gas?",
      ["It turns freshly prepared limewater milky", "It relights a glowing splint", "It burns with a pop sound", "It turns moist red litmus paper blue"], "It turns freshly prepared limewater milky",
      "Carbon dioxide reacts with limewater (calcium hydroxide solution) to form an insoluble white precipitate of calcium trioxocarbonate(IV), turning the limewater milky/cloudy."),
  _q("Which set of observations confirms the identity of ammonia gas?",
      ["It has a pungent smell, turns moist red litmus paper blue, and produces dense white fumes with hydrogen chloride gas", "It is colourless, odourless, and relights a glowing splint", "It bleaches moist litmus paper and has a choking smell", "It gives a brown ring test with iron(II) sulphate"], "It has a pungent smell, turns moist red litmus paper blue, and produces dense white fumes with hydrogen chloride gas",
      "Ammonia is a pungent, alkaline gas; it turns moist red litmus blue, and reacts with hydrogen chloride gas/fumes to form dense white fumes of solid ammonium chloride."),
  _q("Which observation confirms the identity of chlorine gas?",
      ["It is a greenish-yellow gas with a pungent smell that bleaches moist litmus paper", "It is a colourless gas that relights a glowing splint", "It has a rotten-egg smell and turns lead ethanoate paper black", "It gives dense white fumes when mixed with ammonia gas near the gas jar mouth without any colour of its own"], "It is a greenish-yellow gas with a pungent smell that bleaches moist litmus paper",
      "Chlorine is a characteristic greenish-yellow, choking, pungent gas that first turns moist blue litmus paper red and then rapidly bleaches it white due to its strong oxidising action."),
  _q("Which observation confirms the identity of hydrogen chloride gas?",
      ["It produces dense white fumes when it meets ammonia gas, and turns moist blue litmus paper red", "It relights a glowing splint", "It turns limewater milky", "It has a rotten-egg smell"], "It produces dense white fumes when it meets ammonia gas, and turns moist blue litmus paper red",
      "Hydrogen chloride gas is acidic (turning moist blue litmus red) and reacts with ammonia vapour to produce dense white fumes of solid ammonium chloride, a classic identification test."),
  _q("Which observation confirms the identity of sulphur(IV) oxide (sulphur dioxide) gas?",
      ["It decolourises acidified potassium heptaoxodichromate(VI) solution, turning it from orange to green", "It relights a glowing splint", "It produces a squeaky pop with a lit splint", "It turns moist red litmus paper blue"], "It decolourises acidified potassium heptaoxodichromate(VI) solution, turning it from orange to green",
      "Sulphur dioxide is a reducing agent that decolourises acidified potassium heptaoxodichromate(VI) (dichromate) solution, changing its colour from orange to green, a standard confirmatory test."),
];
