import "../quiz_question.dart";

const _subject = "English Language";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// WAEC Oral English (Paper 3): vowels, consonants, rhymes, word stress,
/// emphatic stress/intonation, and phonetic symbols. Every answer is checked
/// against Received Pronunciation (RP), the accent WAEC's Oral English
/// syllabus references.
List<QuizQuestion> buildWaecEnglishOralQuestions() {
  return [
    ..._monophthongs,
    ..._diphthongs,
    ..._consonantSounds,
    ..._consonantClusters,
    ..._rhymes,
    ..._wordStress,
    ..._emphaticStressIntonation,
    ..._phoneticSymbols,
  ];
}

final _monophthongs = [
  _q("Which word has the same vowel sound as the one in 'SEAT'?",
      ["SIT", "SEE", "SET", "SAT"], "SEE", "'SEAT' and 'SEE' both contain the long vowel /iː/."),
  _q("Which word has the same vowel sound as the one in 'SIT'?",
      ["SEAT", "SET", "SIP", "SATE"], "SIP", "'SIT' and 'SIP' both contain the short vowel /ɪ/."),
  _q("Which word has the same vowel sound as the one in 'BED'?",
      ["BAD", "BEAD", "HEAD", "BUD"], "HEAD", "'BED' and 'HEAD' both contain the short vowel /e/."),
  _q("Which word has the same vowel sound as the one in 'CAT'?",
      ["CUT", "COT", "CAT", "COAT"], "CAT", "'CAT' contains the short vowel /æ/; the matching option must share this same open front vowel."),
  _q("Which word has the same vowel sound as the one in 'CUP'?",
      ["CAP", "COP", "LOVE", "COOP"], "LOVE", "'CUP' and 'LOVE' both contain the short vowel /ʌ/."),
  _q("Which word has the same vowel sound as the one in 'HOT'?",
      ["HAT", "HUT", "WASH", "HEAT"], "WASH", "'HOT' and 'WASH' both contain the short back vowel /ɒ/."),
  _q("Which word has the same vowel sound as the one in 'SAW'?",
      ["SOW", "DOOR", "SEW", "SUE"], "DOOR", "'SAW' and 'DOOR' both contain the long vowel /ɔː/."),
  _q("Which word has the same vowel sound as the one in 'BOOK'?",
      ["BOOT", "COULD", "BOAT", "BUCK"], "COULD", "'BOOK' and 'COULD' both contain the short vowel /ʊ/."),
  _q("Which word has the same vowel sound as the one in 'TOO'?",
      ["TOE", "SHOE", "TOP", "TOY"], "SHOE", "'TOO' and 'SHOE' both contain the long vowel /uː/."),
  _q("Which word has the same vowel sound as the one in 'BIRD'?",
      ["BEARD", "BOARD", "WORD", "BREAD"], "WORD", "'BIRD' and 'WORD' both contain the long central vowel /ɜː/."),
  _q("Which word has the same vowel sound as the one in 'ABOUT' (the underlined unstressed syllable)?",
      ["SOFA", "SOFT", "SAFE", "SOUP"], "SOFA", "Both unstressed syllables contain the neutral vowel schwa /ə/."),
  _q("Which word has the same vowel sound as the one in 'FEET'?",
      ["FIT", "FATE", "FLEE", "FED"], "FLEE", "'FEET' and 'FLEE' both contain the long vowel /iː/."),
  _q("Which word has the same vowel sound as the one in 'PIT'?",
      ["PEAT", "PET", "PICK", "PATE"], "PICK", "'PIT' and 'PICK' both contain the short vowel /ɪ/."),
  _q("Which word has the same vowel sound as the one in 'SAID'?",
      ["SAD", "BREAD", "SEED", "SIDE"], "BREAD", "'SAID' and 'BREAD' both contain the short vowel /e/, despite different spellings."),
  _q("Which word has the same vowel sound as the one in 'BLACK'?",
      ["BLOCK", "BLANK", "BLOKE", "BLEAK"], "BLANK", "'BLACK' and 'BLANK' both contain the short vowel /æ/."),
  _q("Which word has the same vowel sound as the one in 'BLOOD'?",
      ["BLOOM", "FLOOD", "BLOND", "BLOAT"], "FLOOD", "'BLOOD' and 'FLOOD' both contain the short vowel /ʌ/, despite the 'oo' spelling."),
  _q("Which word has the same vowel sound as the one in 'DOG'?",
      ["DOSE", "COT", "DOZE", "DOOM"], "COT", "'DOG' and 'COT' both contain the short back vowel /ɒ/."),
  _q("Which word has the same vowel sound as the one in 'WALK'?",
      ["WORK", "WALL", "WAKE", "WICK"], "WALL", "'WALK' and 'WALL' both contain the long vowel /ɔː/."),
  _q("Which word has the same vowel sound as the one in 'WOLF'?",
      ["WOLD", "FOOL", "PUT", "WORE"], "PUT", "'WOLF' and 'PUT' both contain the short vowel /ʊ/."),
  _q("Which word has the same vowel sound as the one in 'FOOD'?",
      ["FOOT", "FLUTE", "FLOOD", "FOLD"], "FLUTE", "'FOOD' and 'FLUTE' both contain the long vowel /uː/."),
];

final _diphthongs = [
  _q("Which word has the same vowel sound as the one in 'DAY'?",
      ["DYE", "THEY", "DEW", "DIE"], "THEY", "'DAY' and 'THEY' both contain the diphthong /eɪ/."),
  _q("Which word has the same vowel sound as the one in 'MY'?",
      ["MAY", "ME", "HIGH", "MOO"], "HIGH", "'MY' and 'HIGH' both contain the diphthong /aɪ/."),
  _q("Which word has the same vowel sound as the one in 'BOY'?",
      ["BUY", "BAY", "COIN", "BOO"], "COIN", "'BOY' and 'COIN' both contain the diphthong /ɔɪ/."),
  _q("Which word has the same vowel sound as the one in 'GO'?",
      ["GOT", "BOAT", "GOD", "GOOD"], "BOAT", "'GO' and 'BOAT' both contain the diphthong /əʊ/."),
  _q("Which word has the same vowel sound as the one in 'NOW'?",
      ["NEW", "NO", "COW", "KNOW"], "COW", "'NOW' and 'COW' both contain the diphthong /aʊ/."),
  _q("Which word has the same vowel sound as the one in 'HERE'?",
      ["HAIR", "BEER", "HARE", "HER"], "BEER", "'HERE' and 'BEER' both contain the diphthong /ɪə/."),
  _q("Which word has the same vowel sound as the one in 'HAIR'?",
      ["HERE", "BEAR", "HAR", "HEAR"], "BEAR", "'HAIR' and 'BEAR' both contain the diphthong /eə/."),
  _q("Which word has the same vowel sound as the one in 'POOR'?",
      ["POUR", "TOUR", "POOL", "PORE"], "TOUR", "'POOR' and 'TOUR' both contain the diphthong /ʊə/ in traditional RP."),
  _q("Which word has the same vowel sound as the one in 'WEIGHT'?",
      ["WHITE", "WAIT", "WET", "WOT"], "WAIT", "'WEIGHT' and 'WAIT' both contain the diphthong /eɪ/."),
  _q("Which word has the same vowel sound as the one in 'BUY'?",
      ["BAY", "BOY", "BYE", "BOO"], "BYE", "'BUY' and 'BYE' both contain the diphthong /aɪ/."),
  _q("Which word has the same vowel sound as the one in 'NOISE'?",
      ["NICE", "NOSE", "TOYS", "NEWS"], "TOYS", "'NOISE' and 'TOYS' both contain the diphthong /ɔɪ/."),
  _q("Which word has the same vowel sound as the one in 'HOME'?",
      ["HOT", "HOPE", "HOW", "HOOD"], "HOPE", "'HOME' and 'HOPE' both contain the diphthong /əʊ/."),
  _q("Which word has the same vowel sound as the one in 'HOUSE'?",
      ["HOSE", "HOWL", "HOT", "HOOF"], "HOWL", "'HOUSE' and 'HOWL' both contain the diphthong /aʊ/."),
  _q("Which word has the same vowel sound as the one in 'IDEA' (second syllable)?",
      ["BEER", "BEAR", "BUY", "BOY"], "BEER", "The second syllable of 'idea' and the word 'beer' both contain the diphthong /ɪə/."),
  _q("Which word has the same vowel sound as the one in 'CARE'?",
      ["CAR", "CHAIR", "CUR", "CORE"], "CHAIR", "'CARE' and 'CHAIR' both contain the diphthong /eə/."),
  _q("Which word has the same vowel sound as the one in 'SURE'?",
      ["SORE", "SHORE", "SEWER", "SIR"], "SEWER", "'SURE' and 'SEWER' both may contain the diphthong /ʊə/ in careful RP pronunciation."),
  _q("Which word has the same vowel sound as the one in 'PLAY'?",
      ["PLEA", "PRAY", "PLOY", "PLOD"], "PRAY", "'PLAY' and 'PRAY' both contain the diphthong /eɪ/."),
  _q("Which word has the same vowel sound as the one in 'TIME'?",
      ["TEAM", "TAME", "TRY", "TOM"], "TRY", "'TIME' and 'TRY' both contain the diphthong /aɪ/."),
  _q("Which word has the same vowel sound as the one in 'TOWN'?",
      ["TONE", "TOWEL", "TIN", "TOO"], "TOWEL", "'TOWN' and 'TOWEL' both contain the diphthong /aʊ/."),
  _q("Which word has the same vowel sound as the one in 'JOY'?",
      ["JAY", "JOIN", "JIVE", "JUTE"], "JOIN", "'JOY' and 'JOIN' both contain the diphthong /ɔɪ/."),
];

final _consonantSounds = [
  _q("Which word has the same initial consonant sound as the one in 'CHURCH'?",
      ["CHAIR", "CHEF", "CHAOS", "CHORD"], "CHAIR", "'CHURCH' and 'CHAIR' both begin with the consonant sound /tʃ/."),
  _q("Which word has the same initial consonant sound as the one in 'THIS'?",
      ["THIN", "THOSE", "THEATRE", "THIRD"], "THOSE", "'THIS' and 'THOSE' both begin with the voiced consonant /ð/."),
  _q("Which word has the same initial consonant sound as the one in 'THIN'?",
      ["THIS", "THAT", "THINK", "THEM"], "THINK", "'THIN' and 'THINK' both begin with the voiceless consonant /θ/."),
  _q("Which word has the same final consonant sound as the one in 'BAG'?",
      ["BACK", "BEG", "BEACH", "BATH"], "BEG", "'BAG' and 'BEG' both end with the voiced consonant /g/."),
  _q("Which word has the same final consonant sound as the one in 'CAT'?",
      ["CAB", "COAT", "CAGE", "CAN"], "COAT", "'CAT' and 'COAT' both end with the voiceless consonant /t/."),
  _q("Which word has the same initial consonant sound as the one in 'SHE'?",
      ["SEE", "SHOE", "CHEESE", "SIT"], "SHOE", "'SHE' and 'SHOE' both begin with the consonant sound /ʃ/."),
  _q("Which word has the same initial consonant sound as the one in 'JUDGE'?",
      ["GENERAL", "GOAT", "GIVE", "GHOST"], "GENERAL", "'JUDGE' and 'GENERAL' both begin with the consonant sound /dʒ/."),
  _q("Which word contains the consonant sound /ʒ/ as in 'MEASURE'?",
      ["MASH", "VISION", "MASHER", "MISER"], "VISION", "'Vision' contains the voiced consonant /ʒ/, the same sound as in 'measure'."),
  _q("Which word has the same initial consonant sound as the one in 'PHONE'?",
      ["POUND", "FUN", "VAN", "PEN"], "FUN", "'Phone' begins with the consonant sound /f/, same as in 'fun', despite the 'ph' spelling."),
  _q("Which word has the same initial consonant sound as the one in 'KNOW'?",
      ["KNEE", "NOW", "KNOT", "KIND"], "NOW", "'Know' begins with the consonant sound /n/ (the 'k' is silent), the same as in 'now'."),
  _q("Which word has the same initial consonant sound as the one in 'WRITE'?",
      ["WRONG", "RIGHT", "WHITE", "WHIP"], "RIGHT", "'Write' begins with /r/ (the 'w' is silent), the same as in 'right'."),
  _q("Which word contains a silent letter, unlike the others?",
      ["HONEST", "HAPPY", "HORSE", "HUNT"], "HONEST", "In 'honest', the initial 'h' is silent, unlike in the other words listed."),
  _q("Which word has the same final consonant sound as the one in 'LOVE'?",
      ["LEAF", "LIVE", "LOOSE", "LIFE"], "LIVE", "'Love' and 'live' both end with the voiced consonant /v/."),
  _q("Which word has the same final consonant sound as the one in 'RICH'?",
      ["RIDGE", "RISE", "REACH", "RING"], "REACH", "'Rich' and 'reach' both end with the voiceless consonant /tʃ/."),
  _q("Which word has the same initial consonant sound as the one in 'GENTLE'?",
      ["GATE", "GOLD", "JELLY", "GUEST"], "JELLY", "'Gentle' begins with the consonant sound /dʒ/, the same as in 'jelly'."),
  _q("Which word has the same final consonant sound as the one in 'BREATHE'?",
      ["BREATH", "BATHE", "BENCH", "BEACH"], "BATHE", "'Breathe' and 'bathe' both end with the voiced consonant /ð/."),
  _q("Which word has the same initial consonant sound as the one in 'CIRCUS'?",
      ["CAT", "SIT", "CUP", "COAT"], "SIT", "'Circus' begins with the consonant sound /s/ (soft 'c'), the same as in 'sit'."),
  _q("Which word has the same initial consonant sound as the one in 'CITY'?",
      ["CAT", "SIT", "COT", "CUT"], "SIT", "'City' begins with the consonant sound /s/ (soft 'c'), the same as in 'sit'."),
  _q("Which word has a voiceless 's' sound, like the one in 'BUS'?",
      ["ROSE", "CATS", "DOGS", "BAGS"], "CATS", "The 's' in 'cats' is pronounced /s/ (voiceless), following a voiceless consonant, like in 'bus'."),
  _q("Which word has a voiced 's' sound pronounced as /z/, like the one in 'ROSE'?",
      ["CATS", "HATS", "DOGS", "CUPS"], "DOGS", "The 's' in 'dogs' is pronounced /z/ (voiced), following a voiced consonant, like in 'rose'."),
  _q("Which word has the same initial consonant sound as the one in 'PSYCHOLOGY'?",
      ["PULL", "SIT", "SPY", "SHY"], "SIT", "In 'psychology', the initial 'p' is silent, so the word begins with /s/, same as 'sit'."),
  _q("Which word has the same final consonant sound as the one in 'JUDGE'?",
      ["JUICE", "BRIDGE", "JOKE", "JEEP"], "BRIDGE", "'Judge' and 'bridge' both end with the voiced consonant sound /dʒ/."),
  _q("Which word contains a consonant cluster with a silent letter?",
      ["CLIMB", "CLIMATE", "CLING", "CLASS"], "CLIMB", "In 'climb', the final 'b' is silent after the /m/ sound."),
  _q("Which word has the same initial consonant sound as the one in 'QUEEN'?",
      ["QUAY", "KETTLE", "QUICK", "CUE"], "QUICK", "'Queen' begins with the consonant sound /kw/, same as in 'quick'."),
  _q("Which word has the same final consonant sound as the one in 'SING'?",
      ["SIN", "SIGN", "SUNG", "SICK"], "SUNG", "'Sing' and 'sung' both end with the nasal consonant /ŋ/."),
];

final _consonantClusters = [
  _q("Which word begins with the same consonant cluster as 'STING'?",
      ["SING", "STOP", "SPIN", "SKIP"], "STOP", "'Sting' and 'stop' both begin with the consonant cluster /st/."),
  _q("Which word begins with the same consonant cluster as 'SCREAM'?",
      ["SPREAD", "STREAM", "SCRATCH", "SWEEP"], "SCRATCH", "'Scream' and 'scratch' both begin with the consonant cluster /skr/."),
  _q("Which word begins with the same consonant cluster as 'SPLASH'?",
      ["SPRAY", "SPLIT", "SCRAP", "STRAP"], "SPLIT", "'Splash' and 'split' both begin with the consonant cluster /spl/."),
  _q("Which word begins with the same consonant cluster as 'THROW'?",
      ["THREE", "TRUE", "SHOW", "TOW"], "THREE", "'Throw' and 'three' both begin with the consonant cluster /θr/."),
  _q("Which word begins with the same consonant cluster as 'BLACK'?",
      ["BRICK", "BLEND", "BRAVE", "BEAK"], "BLEND", "'Black' and 'blend' both begin with the consonant cluster /bl/."),
  _q("Which word begins with the same consonant cluster as 'DRIVE'?",
      ["DREAM", "DIVE", "DELVE", "DIRECT"], "DREAM", "'Drive' and 'dream' both begin with the consonant cluster /dr/."),
  _q("Which word begins with the same consonant cluster as 'FREE'?",
      ["FLEE", "FRY", "FRAME", "FUR"], "FRY", "'Free' and 'fry' both begin with the consonant cluster /fr/."),
  _q("Which word begins with the same consonant cluster as 'GLAD'?",
      ["GRAB", "GLOW", "GATE", "GROW"], "GLOW", "'Glad' and 'glow' both begin with the consonant cluster /gl/."),
  _q("Which word begins with the same consonant cluster as 'PLAN'?",
      ["PRAY", "PLOT", "PAN", "PACE"], "PLOT", "'Plan' and 'plot' both begin with the consonant cluster /pl/."),
  _q("Which word begins with the same consonant cluster as 'CRAB'?",
      ["CLAP", "CROWD", "COAT", "CUT"], "CROWD", "'Crab' and 'crowd' both begin with the consonant cluster /kr/."),
  _q("Which word begins with the same consonant cluster as 'SNAKE'?",
      ["SPARE", "SNAP", "SLIP", "STARE"], "SNAP", "'Snake' and 'snap' both begin with the consonant cluster /sn/."),
  _q("Which word begins with the same consonant cluster as 'SWEET'?",
      ["SPEED", "SWIM", "SKIP", "STEP"], "SWIM", "'Sweet' and 'swim' both begin with the consonant cluster /sw/."),
  _q("Which word begins with the same consonant cluster as 'SKIN'?",
      ["SPIN", "SKY", "STIR", "SIGN"], "SKY", "'Skin' and 'sky' both begin with the consonant cluster /sk/."),
  _q("Which word ends with the same consonant cluster as 'HELPED'?",
      ["HOPED", "STOPPED", "CLAPPED", "WALKED"], "STOPPED", "'Helped' and 'stopped' both end in a voiceless plosive cluster followed by /t/, since 'ed' is pronounced /t/ after voiceless consonants."),
  _q("Which word ends with the same consonant cluster as 'ASKED'?",
      ["LOOKED", "CLIMBED", "PLAYED", "MOVED"], "LOOKED", "'Asked' and 'looked' both end with the cluster /kt/, since the '-ed' is pronounced /t/ after the voiceless /k/."),
  _q("Which word begins with the same consonant cluster as 'TWIN'?",
      ["TRAIN", "TWIST", "TIN", "THIN"], "TWIST", "'Twin' and 'twist' both begin with the consonant cluster /tw/."),
];

final _rhymes = [
  _q("Which word rhymes with 'THROUGH'?",
      ["THOUGH", "TOUGH", "BLUE", "THROW"], "BLUE", "'Through' /θruː/ and 'blue' /bluː/ share the identical ending sound, making them rhymes."),
  _q("Which word rhymes with 'HEART'?",
      ["HEAT", "START", "HEARD", "HEIR"], "START", "'Heart' and 'start' rhyme, sharing the ending sound /ɑːt/."),
  _q("Which word rhymes with 'COUGH'?",
      ["THOUGH", "OFF", "COUCH", "COACH"], "OFF", "'Cough' /kɒf/ and 'off' /ɒf/ share the identical ending sound, making them rhymes."),
  _q("Which word rhymes with 'BEAR'?",
      ["BEER", "FEAR", "FAIR", "BAR"], "FAIR", "'Bear' and 'fair' rhyme, sharing the ending sound /eə/."),
  _q("Which word rhymes with 'KNIGHT'?",
      ["KNIT", "SIGHT", "KNEE", "NEAT"], "SIGHT", "'Knight' and 'sight' rhyme, sharing the ending sound /aɪt/."),
  _q("Which word rhymes with 'PLOUGH'?",
      ["THOUGH", "COW", "TOUGH", "SLOW"], "COW", "'Plough' /plaʊ/ and 'cow' /kaʊ/ share the identical ending sound, making them rhymes."),
  _q("Which word rhymes with 'BREAK'?",
      ["BREATH", "STEAK", "BEAK", "BLACK"], "STEAK", "'Break' and 'steak' rhyme, sharing the ending sound /eɪk/, despite different spelling patterns."),
  _q("Which word rhymes with 'GREAT'?",
      ["GREET", "EIGHT", "GRIT", "GRATE"], "EIGHT", "'Great' /greɪt/ and 'eight' /eɪt/ rhyme, sharing the ending sound /eɪt/."),
  _q("Which word rhymes with 'WOMB'?",
      ["COMB", "BOMB", "TOMB", "THUMB"], "TOMB", "'Womb' and 'tomb' rhyme, sharing the ending sound /uːm/."),
  _q("Which word rhymes with 'ROUGH'?",
      ["DOUGH", "THROUGH", "STUFF", "BOUGH"], "STUFF", "'Rough' /rʌf/ and 'stuff' /stʌf/ share the identical ending sound, making them rhymes."),
  _q("Which word rhymes with 'FLOUR'?",
      ["FLOOR", "POWER", "FOUR", "FLOW"], "POWER", "'Flour' and 'power' rhyme, sharing the ending sound /aʊə/."),
  _q("Which word rhymes with 'HEAR'?",
      ["HEART", "HAIR", "DEER", "HERE"], "DEER", "'Hear' and 'deer' rhyme, sharing the ending sound /ɪə/."),
  _q("Which word rhymes with 'SEW'?",
      ["FEW", "COW", "GO", "NOW"], "GO", "'Sew' /səʊ/ and 'go' /gəʊ/ share the identical ending sound, making them rhymes despite different spellings."),
  _q("Which word rhymes with 'BLOOD'?",
      ["FOOD", "MOOD", "FLOOD", "MOULD"], "FLOOD", "'Blood' and 'flood' rhyme, sharing the ending sound /ʌd/, despite the 'oo' spelling."),
  _q("Which word rhymes with 'SOUL'?",
      ["SOUP", "SOUND", "BOWL", "SCOWL"], "BOWL", "'Soul' /səʊl/ and 'bowl' /bəʊl/ share the identical ending sound, making them rhymes."),
  _q("Which word rhymes with 'ONE'?",
      ["GONE", "BONE", "SUN", "TONE"], "SUN", "'One' /wʌn/ and 'sun' /sʌn/ share the identical ending sound, making them rhymes despite different spellings."),
  _q("Which word rhymes with 'HOUR'?",
      ["HONOUR", "FLOWER", "HOVER", "HOARD"], "FLOWER", "'Hour' /aʊə/ and 'flower' /flaʊə/ share the identical ending sound, making them rhymes."),
  _q("Which word rhymes with 'GUIDE'?",
      ["GUILD", "SIDE", "GRID", "GOD"], "SIDE", "'Guide' and 'side' rhyme, sharing the ending sound /aɪd/."),
  _q("Which word rhymes with 'AISLE'?",
      ["ISLE", "AIL", "ASYLUM", "EASEL"], "ISLE", "'Aisle' /aɪl/ and 'isle' /aɪl/ are perfect homophones and therefore rhyme exactly."),
  _q("Which word rhymes with 'CHOIR'?",
      ["CHAIR", "FIRE", "CHEER", "CHOOSE"], "FIRE", "'Choir' /kwaɪə/ and 'fire' /faɪə/ share the identical ending sound, making them rhymes."),
  _q("Which word rhymes with 'SUEDE'?",
      ["SAID", "SPADE", "SUED", "SEED"], "SPADE", "'Suede' /sweɪd/ and 'spade' /speɪd/ share the identical ending sound, making them rhymes."),
  _q("Which word rhymes with 'PIECE'?",
      ["PEACE", "PRICE", "PACE", "PISS"], "PEACE", "'Piece' and 'peace' are homophones with identical pronunciation /piːs/, so they rhyme."),
  _q("Which word rhymes with 'MOOSE'?",
      ["MOSS", "GOOSE", "MOUSE", "LOSE"], "GOOSE", "'Moose' and 'goose' rhyme, sharing the ending sound /uːs/."),
  _q("Which word rhymes with 'NEIGH'?",
      ["NIGH", "SAY", "KEY", "KNEE"], "SAY", "'Neigh' /neɪ/ and 'say' /seɪ/ share the identical ending sound, making them rhymes."),
  _q("Which word rhymes with 'CHOOSE'?",
      ["LOSE", "LOOSE", "LOSS", "CHOSE"], "LOSE", "'Choose' /tʃuːz/ and 'lose' /luːz/ share the identical ending sound, making them rhymes."),
  _q("Which word rhymes with 'GAUGE'?",
      ["GAG", "GARAGE", "PAGE", "GAUZE"], "PAGE", "'Gauge' /geɪdʒ/ and 'page' /peɪdʒ/ share the identical ending sound, making them rhymes."),
  _q("Which word rhymes with 'YACHT'?",
      ["YARD", "HOT", "YOKE", "YAWN"], "HOT", "'Yacht' /jɒt/ and 'hot' /hɒt/ share the identical ending sound, making them rhymes despite different spellings."),
  _q("Which word rhymes with 'WEIGH'?",
      ["WAY", "WEIGHT", "WHY", "WELL"], "WAY", "'Weigh' /weɪ/ and 'way' /weɪ/ are homophones and therefore rhyme exactly."),
  _q("Which word rhymes with 'BROACH'?",
      ["BROOCH", "BRUSH", "BEACH", "BATCH"], "BROOCH", "'Broach' and 'brooch' are homophones with identical pronunciation /brəʊtʃ/, so they rhyme."),
  _q("Which word rhymes with 'FLEA'?",
      ["FLEE", "FLED", "FLY", "FLEW"], "FLEE", "'Flea' and 'flee' are homophones with identical pronunciation /fliː/, so they rhyme."),
];

final _wordStress = [
  _q("In the word 'PHOTOGRAPH', which syllable carries the primary stress?",
      ["First", "Second", "Third", "Fourth"], "First", "'PHOTOGRAPH' is stressed on the first syllable: PHO-to-graph."),
  _q("In the word 'PHOTOGRAPHY', which syllable carries the primary stress?",
      ["First", "Second", "Third", "Fourth"], "Second", "'PHOTOGRAPHY' shifts its stress to the second syllable: pho-TOG-ra-phy."),
  _q("In the word 'PHOTOGRAPHIC', which syllable carries the primary stress?",
      ["First", "Second", "Third", "Fourth"], "Third", "'PHOTOGRAPHIC' shifts its stress to the third syllable: pho-to-GRAPH-ic."),
  _q("Which word is stressed on the first syllable when used as a noun? 'The RECORD showed a clear improvement.'",
      ["RECORD (noun)", "recORD (verb)", "reCORD (verb)", "recorDED"], "RECORD (noun)", "As a noun, 'record' is stressed on the first syllable; as a verb, it shifts to the second syllable."),
  _q("Which syllable is stressed in the verb form of 'IMPORT' as in 'They import goods from abroad'?",
      ["First", "Second", "Both equally", "None"], "Second", "As a verb, 'import' is stressed on the second syllable: im-PORT; as a noun, it shifts to the first syllable."),
  _q("Which syllable carries the primary stress in the noun 'PRESENT' (a gift)?",
      ["First", "Second", "Both equally", "None"], "First", "As a noun meaning 'a gift', 'present' is stressed on the first syllable: PRE-sent."),
  _q("Which syllable carries the primary stress in the verb 'PRESENT' (to present a report)?",
      ["First", "Second", "Both equally", "None"], "Second", "As a verb, 'present' is stressed on the second syllable: pre-SENT."),
  _q("In the word 'NECESSARY', which syllable carries the primary stress?",
      ["First", "Second", "Third", "Fourth"], "First", "'NECESSARY' is stressed on the first syllable: NE-ces-sa-ry."),
  _q("In the word 'EXAMINATION', which syllable carries the primary stress?",
      ["First", "Second", "Third", "Fourth"], "Fourth", "'EXAMINATION' places its primary stress on the fourth syllable: ex-am-in-A-tion."),
  _q("In the word 'ADVERTISEMENT', which syllable carries the primary stress?",
      ["First", "Second", "Third", "Fourth"], "Third", "'ADVERTISEMENT' places its primary stress on the third syllable: ad-ver-TISE-ment."),
  _q("In the word 'CONTENT' (meaning satisfied), which syllable is stressed?",
      ["First", "Second", "Both equally", "None"], "Second", "As an adjective meaning 'satisfied', 'content' is stressed on the second syllable: con-TENT."),
  _q("In the word 'CONTENT' (meaning the material inside something), which syllable is stressed?",
      ["First", "Second", "Both equally", "None"], "First", "As a noun meaning 'the material inside something', 'content' is stressed on the first syllable: CON-tent."),
  _q("In the word 'DEMOCRACY', which syllable carries the primary stress?",
      ["First", "Second", "Third", "Fourth"], "Second", "'DEMOCRACY' is stressed on the second syllable: de-MOC-ra-cy."),
  _q("In the word 'ENGINEER', which syllable carries the primary stress?",
      ["First", "Second", "Third", "None"], "Third", "'ENGINEER' places its primary stress on the third syllable: en-gi-NEER."),
  _q("In the word 'UNDERSTAND', which syllable carries the primary stress?",
      ["First", "Second", "Third", "None"], "Third", "'UNDERSTAND' places its primary stress on the third syllable: un-der-STAND."),
  _q("In the word 'COMFORTABLE', which syllable carries the primary stress?",
      ["First", "Second", "Third", "Fourth"], "First", "'COMFORTABLE' is stressed on the first syllable: COM-for-ta-ble."),
  _q("In the word 'DEVELOPMENT', which syllable carries the primary stress?",
      ["First", "Second", "Third", "Fourth"], "Second", "'DEVELOPMENT' is stressed on the second syllable: de-VEL-op-ment."),
  _q("Which word is stressed differently as a noun and as a verb? Choose the correct pair.",
      ["OBJECT (noun) / obJECT (verb)", "OBJECT (noun) / OBJECT (verb)", "obJECT (noun) / OBJECT (verb)", "obJECT (noun) / obJECT (verb)"],
      "OBJECT (noun) / obJECT (verb)", "'Object' is stressed on the first syllable as a noun and on the second syllable as a verb."),
  _q("In the word 'CONDUCT' used as a noun (good conduct), which syllable is stressed?",
      ["First", "Second", "Both equally", "None"], "First", "As a noun, 'conduct' is stressed on the first syllable: CON-duct."),
  _q("In the word 'CONDUCT' used as a verb (to conduct an experiment), which syllable is stressed?",
      ["First", "Second", "Both equally", "None"], "Second", "As a verb, 'conduct' is stressed on the second syllable: con-DUCT."),
  _q("In the word 'ORGANISATION', which syllable carries the primary stress?",
      ["Second", "Third", "Fourth", "Fifth"], "Fourth", "'ORGANISATION' places its primary stress on the fourth syllable: or-gan-i-SA-tion."),
  _q("In the word 'CHARACTERISTIC', which syllable carries the primary stress?",
      ["Second", "Third", "Fourth", "Fifth"], "Fourth", "'CHARACTERISTIC' places its primary stress on the fourth syllable: char-ac-ter-IS-tic."),
  _q("In the word 'INFORMATION', which syllable carries the primary stress?",
      ["First", "Second", "Third", "Fourth"], "Third", "'INFORMATION' places its primary stress on the third syllable: in-for-MA-tion."),
  _q("In the word 'ECONOMIC', which syllable carries the primary stress?",
      ["First", "Second", "Third", "Fourth"], "Third", "'ECONOMIC' places its primary stress on the third syllable: ec-o-NOM-ic."),
  _q("In the word 'ECONOMY', which syllable carries the primary stress?",
      ["First", "Second", "Third", "Fourth"], "Second", "'ECONOMY' places its primary stress on the second syllable: e-CON-o-my."),
  _q("Which syllable is stressed in the verb 'INCREASE' as in 'Prices will increase next month'?",
      ["First", "Second", "Both equally", "None"], "Second", "As a verb, 'increase' is stressed on the second syllable: in-CREASE."),
  _q("Which syllable is stressed in the noun 'INCREASE' as in 'There was a sharp increase in prices'?",
      ["First", "Second", "Both equally", "None"], "First", "As a noun, 'increase' is stressed on the first syllable: IN-crease."),
  _q("In the word 'INTELLIGENT', which syllable carries the primary stress?",
      ["First", "Second", "Third", "Fourth"], "Third", "'INTELLIGENT' places its primary stress on the third syllable: in-tel-LI-gent."),
  _q("In the word 'POLITICIAN', which syllable carries the primary stress?",
      ["First", "Second", "Third", "Fourth"], "Third", "'POLITICIAN' places its primary stress on the third syllable: pol-i-TI-cian."),
  _q("In the word 'REFEREE', which syllable carries the primary stress?",
      ["First", "Second", "Third", "None"], "Third", "'REFEREE' places its primary stress on the final (third) syllable: ref-er-EE."),
  _q("In the word 'MAGAZINE', which syllable carries the primary stress?",
      ["First", "Second", "Third", "None"], "Third", "'MAGAZINE' places its primary stress on the third syllable: mag-a-ZINE, in RP pronunciation."),
  _q("In the word 'GUARANTEE', which syllable carries the primary stress?",
      ["First", "Second", "Third", "None"], "Third", "'GUARANTEE' places its primary stress on the final (third) syllable: gua-ran-TEE."),
  _q("In the word 'DIFFICULTY', which syllable carries the primary stress?",
      ["First", "Second", "Third", "Fourth"], "First", "'DIFFICULTY' is stressed on the first syllable: DIF-fi-cul-ty."),
  _q("In the word 'INTRODUCE', which syllable carries the primary stress?",
      ["First", "Second", "Third", "None"], "Third", "'INTRODUCE' places its primary stress on the final (third) syllable: in-tro-DUCE."),
  _q("Which syllable is stressed in the verb 'PROJECT' as in 'They will project the image on the wall'?",
      ["First", "Second", "Both equally", "None"], "Second", "As a verb, 'project' is stressed on the second syllable: pro-JECT."),
  _q("Which syllable is stressed in the noun 'PROJECT' as in 'She is working on a school project'?",
      ["First", "Second", "Both equally", "None"], "First", "As a noun, 'project' is stressed on the first syllable: PRO-ject."),
  _q("In the word 'TELEVISION', which syllable carries the primary stress?",
      ["First", "Second", "Third", "Fourth"], "First", "'TELEVISION' is stressed on the first syllable: TEL-e-vi-sion."),
  _q("In the word 'UNIVERSITY', which syllable carries the primary stress?",
      ["First", "Second", "Third", "Fourth"], "Third", "'UNIVERSITY' places its primary stress on the third syllable: u-ni-VER-si-ty."),
  _q("In the word 'GEOGRAPHY', which syllable carries the primary stress?",
      ["First", "Second", "Third", "Fourth"], "Second", "'GEOGRAPHY' places its primary stress on the second syllable: ge-OG-ra-phy."),
  _q("In the word 'BIOLOGY', which syllable carries the primary stress?",
      ["First", "Second", "Third", "Fourth"], "Second", "'BIOLOGY' places its primary stress on the second syllable: bi-OL-o-gy."),
];

final _emphaticStressIntonation = [
  _q("In the sentence 'I DID finish my homework', what does the emphatic stress on 'DID' suggest?",
      ["Contradiction of a previous claim that it was not done", "A question about the homework", "Confusion about the task", "A request for help"],
      "Contradiction of a previous claim that it was not done", "Emphatic stress on the auxiliary verb 'did' is used to strongly contradict a suggestion that the action was not completed."),
  _q("In the sentence 'SHE gave him the book, not her sister', which word carries the emphatic stress and why?",
      ["'SHE', to clarify who performed the action", "'gave', to clarify the action", "'book', to clarify the object", "'sister', to clarify the relationship"],
      "'SHE', to clarify who performed the action", "The emphatic stress on 'SHE' contrasts the subject with another possible person, 'her sister'."),
  _q("In the sentence 'I want the RED car, not the blue one', what is the function of stressing 'RED'?",
      ["To contrast it with another colour", "To ask a question", "To show surprise", "To express doubt"],
      "To contrast it with another colour", "Stressing 'RED' highlights the specific choice in contrast with the rejected alternative, 'blue'."),
  _q("Which intonation pattern is typically used for a yes/no question like 'Are you coming to the party?'",
      ["Rising intonation", "Falling intonation", "Flat intonation", "No intonation change"], "Rising intonation",
      "Yes/no questions in English typically end with rising intonation."),
  _q("Which intonation pattern is typically used for a wh-question like 'Where are you going?'",
      ["Falling intonation", "Rising intonation", "Flat intonation", "No intonation change"], "Falling intonation",
      "Wh-questions in English typically end with falling intonation."),
  _q("Which intonation pattern is used when reading a list, such as 'I bought apples, oranges, and bananas'?",
      ["Rising intonation on each item except the last, which falls", "Falling intonation on every item", "Flat intonation throughout", "Rising intonation only on the last item"],
      "Rising intonation on each item except the last, which falls",
      "In a list, each item before the last is said with rising intonation, and the final item falls to show completion."),
  _q("In the sentence 'You are going, AREN'T you?', what is the function of the tag question's rising intonation?",
      ["To seek confirmation", "To express anger", "To give a command", "To show sarcasm"], "To seek confirmation",
      "A rising intonation on a tag question shows the speaker is genuinely seeking confirmation."),
  _q("In the sentence 'You ARE joking, aren't you?' with a falling tone on the tag, what does this suggest?",
      ["The speaker is fairly certain of the answer", "The speaker is asking a genuine question", "The speaker is angry", "The speaker is confused"],
      "The speaker is fairly certain of the answer", "A falling tone on a tag question suggests the speaker already expects a particular answer and is simply confirming it."),
  _q("Which word would naturally receive emphatic stress in the sentence 'I said BLACK, not white'?",
      ["BLACK", "said", "I", "not"], "BLACK", "The word 'BLACK' is emphasised to correct a misunderstanding about the colour mentioned."),
  _q("In the sentence 'Can you REALLY not see it?', what does stressing 'REALLY' suggest?",
      ["Disbelief or surprise", "A polite request", "Agreement", "Indifference"], "Disbelief or surprise",
      "Stressing 'REALLY' conveys the speaker's disbelief or surprise at the other person's claim."),
  _q("Which sentence uses stress correctly to express contrast? 'I never said he was LAZY; I said he was TIRED.'",
      ["The words LAZY and TIRED are both emphasised to show contrast", "Only LAZY is emphasised", "Only TIRED is emphasised", "No word needs emphasis"],
      "The words LAZY and TIRED are both emphasised to show contrast", "Both contrasted words receive emphatic stress to highlight the difference between them."),
  _q("What does falling intonation typically indicate at the end of a statement, such as 'I am going home'?",
      ["Completion or certainty", "A question", "Uncertainty", "Surprise"], "Completion or certainty",
      "Falling intonation at the end of a declarative statement signals that the sentence is complete and the speaker is certain."),
  _q("What does rising intonation typically indicate when used at the end of a statement, such as 'You're coming?'",
      ["A question or uncertainty", "A command", "A completed thought", "Anger"], "A question or uncertainty",
      "Rising intonation on a statement can turn it into a question, expressing uncertainty or seeking confirmation."),
  _q("In the sentence 'I only borrowed TWO books, not five', what does stressing 'TWO' achieve?",
      ["It corrects a wrong number mentioned earlier", "It shows anger", "It asks a question", "It shows uncertainty"],
      "It corrects a wrong number mentioned earlier", "Stressing 'TWO' emphasises the correct number in contrast to the incorrect figure implied earlier."),
  _q("Which sentence correctly demonstrates the use of stress to distinguish meaning? 'She is a LIGHT-house keeper' versus 'She is a light HOUSE-keeper'.",
      ["The stress placement changes the meaning of the compound phrase", "Both sentences mean the same thing", "The stress placement has no effect", "The stress only affects pronunciation speed"],
      "The stress placement changes the meaning of the compound phrase", "Depending on where the stress falls, 'lighthouse keeper' and 'light housekeeper' convey different meanings."),
  _q("In the sentence 'I thought YOU were bringing the drinks', what does the stress on 'YOU' imply?",
      ["A misunderstanding about who was responsible", "A question about the drinks", "Anger at the drinks", "Confusion about the time"],
      "A misunderstanding about who was responsible", "Stressing 'YOU' emphasises the mistaken assumption about who was meant to bring the drinks."),
  _q("Which intonation is typically used at the end of a polite request such as 'Could you help me, please?'",
      ["Rising intonation", "Falling intonation", "Flat intonation", "No clear pattern"], "Rising intonation",
      "Polite requests, especially those phrased as questions, typically end with rising intonation."),
  _q("In the sentence 'He didn't say he WOULDN'T come', what is emphasised, and why?",
      ["WOULDN'T, to highlight the double negative meaning", "didn't, to show anger", "say, to show doubt", "come, to ask a question"],
      "WOULDN'T, to highlight the double negative meaning", "Stressing 'WOULDN'T' draws attention to the precise meaning of the double negative construction."),
  _q("Which sentence best demonstrates contrastive stress? 'I want TEA, not coffee.'",
      ["TEA is stressed to contrast with coffee", "coffee is stressed to contrast with tea", "want is stressed for emphasis", "No word needs stress"],
      "TEA is stressed to contrast with coffee", "Stressing 'TEA' highlights the contrast between the requested item and the rejected alternative."),
  _q("What is the typical intonation pattern for expressing surprise, as in 'You won the LOTTERY?!'",
      ["Rising intonation with strong emphasis", "Flat, unstressed tone", "Falling intonation only", "No intonation at all"], "Rising intonation with strong emphasis",
      "Expressions of surprise typically combine a sharp rise in intonation with strong emphatic stress."),
  _q("In the sentence 'Nobody TOLD me about the meeting', what does the stress on 'TOLD' suggest?",
      ["A complaint that information was withheld", "A question about the meeting", "Agreement with a plan", "Excitement about an event"],
      "A complaint that information was withheld", "Stressing 'TOLD' emphasises that the act of informing never happened, expressing a complaint."),
  _q("Which sentence correctly uses falling intonation to signal a command? 'Close the door.'",
      ["Falling intonation on a command shows firmness", "Rising intonation on a command shows firmness", "Commands never use intonation", "Commands use only flat intonation"],
      "Falling intonation on a command shows firmness", "Commands are typically spoken with falling intonation to convey authority and finality."),
  _q("What is the effect of stressing the word 'ALL' in the sentence 'Not ALL the students passed the exam'?",
      ["It clarifies that only some students passed", "It shows that every student passed", "It expresses excitement", "It asks a question"],
      "It clarifies that only some students passed", "Stressing 'ALL' in a negative sentence emphasises that the statement applies only to some, not the entire group."),
  _q("Which type of question typically uses rising-then-falling intonation, such as 'Do you want tea or coffee?'",
      ["An alternative question", "A yes/no question", "A wh-question", "A tag question"], "An alternative question",
      "Alternative questions offering a choice typically rise on the first option and fall on the last."),
  _q("In the sentence 'I can't believe he actually WON', what does the stress on 'WON' emphasise?",
      ["The surprising outcome of the event", "The identity of the winner", "The time of the event", "The location of the event"],
      "The surprising outcome of the event", "Stressing 'WON' highlights the unexpected result being expressed with disbelief."),
  _q("What does a fall-rise intonation pattern typically suggest in a sentence like 'It's not bad...'?",
      ["Reservation or an implied 'but'", "Complete agreement", "Strong anger", "A direct command"], "Reservation or an implied 'but'",
      "A fall-rise pattern often implies hesitation or an unspoken reservation, suggesting more could be said."),
  _q("Which sentence uses stress to correct a factual error? 'The capital of Nigeria is ABUJA, not Lagos.'",
      ["ABUJA is stressed to correct the misconception", "Lagos is stressed to confirm it", "capital is stressed for clarity", "Nigeria is stressed for emphasis"],
      "ABUJA is stressed to correct the misconception", "Stressing 'ABUJA' corrects the common misconception that Lagos is Nigeria's capital."),
  _q("What is the typical function of a rising tone at the end of the first item in a list?",
      ["To show the list is not yet finished", "To show the list is complete", "To ask a question", "To show anger"],
      "To show the list is not yet finished", "A rising tone on non-final list items signals to the listener that more items are coming."),
  _q("In the sentence 'She's not MY sister, she's my COUSIN', which words carry contrastive stress?",
      ["MY and COUSIN", "sister and cousin only", "She's and she's", "not and my"], "MY and COUSIN",
      "'MY' (implying a mistaken assumption of relation) and 'COUSIN' (the correction) both carry contrastive stress."),
  _q("What does a wide pitch range in intonation typically convey in spoken English?",
      ["Strong emotion or enthusiasm", "Boredom or disinterest", "Formality", "Uncertainty only"], "Strong emotion or enthusiasm",
      "A wide pitch range typically conveys strong emotion, excitement, or enthusiasm in speech."),
];

final _phoneticSymbols = [
  _q("Which word is correctly represented by the phonetic transcription /kæt/?",
      ["CUT", "CAT", "COAT", "KIT"], "CAT", "The symbol /æ/ represents the short front vowel in 'CAT', matching the transcription /kæt/."),
  _q("Which word is correctly represented by the phonetic transcription /ʃiːp/?",
      ["SHIP", "SHEEP", "SHOP", "CHEAP"], "SHEEP", "The symbol /iː/ represents the long vowel sound, and /ʃ/ represents 'sh', giving 'SHEEP'."),
  _q("Which word is correctly represented by the phonetic transcription /θɪŋk/?",
      ["THINK", "SINK", "THIN", "DRINK"], "THINK", "The symbol /θ/ represents the voiceless 'th' sound, and /ŋ/ represents the 'ng' sound, giving 'THINK'."),
  _q("Which word is correctly represented by the phonetic transcription /dʒʌmp/?",
      ["JUMP", "CHUMP", "PLUMP", "JAM"], "JUMP", "The symbol /dʒ/ represents the initial consonant sound, matching the word 'JUMP'."),
  _q("Which phonetic symbol represents the vowel sound in the word 'BIRD'?",
      ["/ɜː/", "/iː/", "/ɪ/", "/e/"], "/ɜː/", "The symbol /ɜː/ represents the long central vowel sound found in 'BIRD'."),
  _q("Which phonetic symbol represents the neutral, unstressed vowel sound known as schwa?",
      ["/ə/", "/e/", "/æ/", "/ʌ/"], "/ə/", "The symbol /ə/ represents schwa, the most common unstressed vowel sound in English."),
  _q("Which word is correctly represented by the phonetic transcription /breɪk/?",
      ["BLACK", "BREAK", "BRICK", "BEAK"], "BREAK", "The symbol /eɪ/ represents the diphthong sound, matching the word 'BREAK'."),
  _q("Which phonetic symbol represents the consonant sound at the end of the word 'SING'?",
      ["/ŋ/", "/n/", "/g/", "/m/"], "/ŋ/", "The symbol /ŋ/ represents the nasal consonant sound found at the end of 'SING'."),
  _q("Which word is correctly represented by the phonetic transcription /tʃeə/?",
      ["CHAIR", "CHEER", "CHARM", "SHARE"], "CHAIR", "The symbols /tʃ/ and /eə/ combine to represent the word 'CHAIR'."),
  _q("Which phonetic symbol represents the voiced 'th' sound as in 'THIS'?",
      ["/ð/", "/θ/", "/d/", "/z/"], "/ð/", "The symbol /ð/ represents the voiced 'th' sound found in words like 'THIS' and 'THAT'."),
  _q("Which phonetic symbol represents the voiceless 'th' sound as in 'THINK'?",
      ["/θ/", "/ð/", "/t/", "/s/"], "/θ/", "The symbol /θ/ represents the voiceless 'th' sound found in words like 'THINK' and 'THIN'."),
  _q("Which word is correctly represented by the phonetic transcription /naʊ/?",
      ["NEW", "NOW", "NO", "KNOW"], "NOW", "The symbol /aʊ/ represents the diphthong sound found in the word 'NOW'."),
  _q("Which phonetic symbol represents the sound 'sh' as in 'SHOE'?",
      ["/ʃ/", "/s/", "/tʃ/", "/ʒ/"], "/ʃ/", "The symbol /ʃ/ represents the consonant sound at the start of 'SHOE'."),
  _q("Which phonetic symbol represents the sound in the middle of the word 'MEASURE'?",
      ["/ʒ/", "/ʃ/", "/z/", "/dʒ/"], "/ʒ/", "The symbol /ʒ/ represents the voiced sound found in the middle of 'MEASURE'."),
  _q("Which word is correctly represented by the phonetic transcription /nɔɪz/?",
      ["NOSE", "NOISE", "NICE", "NEWS"], "NOISE", "The symbol /ɔɪ/ represents the diphthong sound found in the word 'NOISE'."),
  _q("Which phonetic symbol represents the consonant sound at the beginning of 'JUDGE'?",
      ["/dʒ/", "/ʒ/", "/g/", "/tʃ/"], "/dʒ/", "The symbol /dʒ/ represents the voiced affricate consonant found at the start of 'JUDGE'."),
  _q("Which word is correctly represented by the phonetic transcription /faɪə/?",
      ["FAIR", "FIRE", "FAR", "FEAR"], "FIRE", "The symbol /aɪə/ represents a diphthong-plus-schwa combination found in the word 'FIRE'."),
  _q("Which phonetic symbol represents the vowel sound in the word 'PUT'?",
      ["/ʊ/", "/uː/", "/ʌ/", "/ɒ/"], "/ʊ/", "The symbol /ʊ/ represents the short vowel sound found in 'PUT'."),
  _q("Which word is correctly represented by the phonetic transcription /streɪndʒ/?",
      ["STRANGE", "STRING", "STRAIGHT", "STRONG"], "STRANGE", "The transcription combines /str/, /eɪ/, and /ndʒ/ to represent the word 'STRANGE'."),
  _q("Which phonetic symbol represents the vowel sound in the word 'HOT'?",
      ["/ɒ/", "/ɔː/", "/ʌ/", "/ə/"], "/ɒ/", "The symbol /ɒ/ represents the short back vowel sound found in 'HOT'."),
];
