import "../quiz_question.dart";

const _subject = "Physical Education";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// WAEC Physical Education question bank covering the full syllabus:
/// Foundations of Physical Education & Sports, Athletics (Track and Field),
/// Ball Games & Gymnastics, and Sports Medicine/Organization &
/// Administration.
List<QuizQuestion> buildWaecPhysicalEducationQuestions() {
  return [
    ..._foundationsOfPhysicalEducationAndSports,
    ..._athleticsTrackAndFieldEvents,
    ..._ballGamesAndGymnastics,
    ..._sportsMedicineOrganizationAndAdministration,
  ];
}

final _foundationsOfPhysicalEducationAndSports = [
  _q("Ancient Greece is historically significant to the development of Physical Education mainly for its",
      ["establishment of the ancient Olympic Games and emphasis on physical training", "invention of modern basketball", "development of the modern marathon distance", "creation of the first modern gymnasium equipment"], "establishment of the ancient Olympic Games and emphasis on physical training",
      "Ancient Greece is historically significant for establishing the ancient Olympic Games and placing strong cultural emphasis on physical training and athleticism."),
  _q("The industrial era in Europe influenced the development of Physical Education partly through",
      ["growing concern for workers' physical fitness and the rise of organised school physical training", "the complete elimination of all physical activity from daily life", "the invention of the ancient Olympic Games", "the abolition of all organised sport"], "growing concern for workers' physical fitness and the rise of organised school physical training",
      "Industrial-era Europe saw growing concern for public health and fitness, contributing to the rise of organised physical training programmes in schools."),
  _q("The development of modern Nigerian sports history has been shaped significantly by",
      ["the growth of organised school sports, national competitions, and international participation", "a complete absence of any organised sporting activity", "the exclusive practice of ancient Greek sports", "isolation from all international sporting events"], "the growth of organised school sports, national competitions, and international participation",
      "Modern Nigerian sports history reflects the growth of organised school and national competitions, alongside increasing participation in international sporting events."),
  _q("The cognitive domain of Physical Education's developmental goals is primarily concerned with",
      ["knowledge and understanding of rules, strategies, and health concepts", "physical skill execution alone", "emotional and social development alone", "purely random, unstructured play"], "knowledge and understanding of rules, strategies, and health concepts",
      "The cognitive domain focuses on developing knowledge and understanding, such as learning rules, strategies, and health-related concepts."),
  _q("The affective domain of Physical Education's developmental goals is primarily concerned with",
      ["attitudes, values, sportsmanship, and social/emotional development", "physical skill execution alone", "purely factual knowledge of rules", "equipment specifications alone"], "attitudes, values, sportsmanship, and social/emotional development",
      "The affective domain addresses attitudes, values, and social-emotional development, including qualities like sportsmanship and teamwork."),
  _q("The psychomotor domain of Physical Education's developmental goals is primarily concerned with",
      ["the development of physical skills and movement abilities", "purely theoretical knowledge with no physical component", "attitudes and values alone, with no skill development", "administrative and organisational tasks alone"], "the development of physical skills and movement abilities",
      "The psychomotor domain focuses on developing physical skills and movement abilities through practice and physical activity."),
  _q("The health-related fitness component describing the heart and lungs' ability to supply oxygen during sustained physical activity is called",
      ["cardiovascular endurance", "muscular strength", "flexibility", "body composition"], "cardiovascular endurance",
      "Cardiovascular endurance measures the efficiency of the heart and lungs in supplying oxygen to muscles during sustained physical activity."),
  _q("The health-related fitness component describing the maximum force a muscle or muscle group can exert in a single effort is called",
      ["muscular strength", "cardiovascular endurance", "muscular endurance", "flexibility"], "muscular strength",
      "Muscular strength refers to the maximum force a muscle or muscle group can generate in a single maximal effort."),
  _q("The health-related fitness component describing a muscle's ability to perform repeated contractions over an extended period without fatigue is called",
      ["muscular endurance", "muscular strength", "cardiovascular endurance", "flexibility"], "muscular endurance",
      "Muscular endurance measures a muscle's ability to sustain repeated contractions over time without becoming fatigued."),
  _q("The health-related fitness component describing the range of motion available at a joint or group of joints is called",
      ["flexibility", "muscular strength", "cardiovascular endurance", "body composition"], "flexibility",
      "Flexibility refers to the range of motion possible at a joint, influenced by factors such as muscle and connective tissue elasticity."),
  _q("The health-related fitness component describing the relative proportion of fat, muscle, bone, and other tissues making up the body is called",
      ["body composition", "flexibility", "muscular endurance", "cardiovascular endurance"], "body composition",
      "Body composition describes the relative proportions of fat mass, muscle mass, bone, and other tissues that make up total body weight."),
  _q("The skill-related fitness component describing the ability to rapidly change body position or direction with control is called",
      ["agility", "balance", "coordination", "power"], "agility",
      "Agility refers to the ability to quickly and accurately change body direction or position while maintaining control."),
  _q("The skill-related fitness component describing the ability to maintain body equilibrium, whether stationary or moving, is called",
      ["balance", "agility", "coordination", "reaction time"], "balance",
      "Balance describes the ability to maintain the body's equilibrium, whether in a static position or while in motion."),
  _q("The skill-related fitness component describing the ability to use the senses together with body parts to perform smooth, accurate movements is called",
      ["coordination", "agility", "power", "speed"], "coordination",
      "Coordination involves integrating sensory information with motor skills to execute smooth, accurate, and well-timed movements."),
  _q("The skill-related fitness component describing the ability to exert maximum force in the shortest possible time is called",
      ["power", "agility", "balance", "reaction time"], "power",
      "Power combines strength and speed, describing the ability to exert maximum force in the shortest possible time."),
  _q("The skill-related fitness component describing the time elapsed between a stimulus and the beginning of a response to it is called",
      ["reaction time", "speed", "agility", "balance"], "reaction time",
      "Reaction time measures how quickly an individual responds to a given stimulus, an important factor in many competitive sports."),
  _q("The skill-related fitness component describing the ability to move the body (or part of it) from one point to another in the shortest possible time is called",
      ["speed", "reaction time", "coordination", "power"], "speed",
      "Speed refers to the ability to move quickly from one point to another, a key skill-related fitness component in many sports."),
  _q("A standard test used to assess cardiovascular endurance, requiring participants to run as far as possible within a set time, is the",
      ["Cooper 12-minute run test", "sit-and-reach test", "vertical jump test", "reaction time ruler drop test"], "Cooper 12-minute run test",
      "The Cooper 12-minute run test measures the maximum distance covered in twelve minutes, providing an estimate of cardiovascular endurance."),
  _q("A standard test used to assess flexibility, typically measuring how far a person can reach forward from a seated position, is the",
      ["sit-and-reach test", "Cooper 12-minute run test", "vertical jump test", "shuttle run test"], "sit-and-reach test",
      "The sit-and-reach test measures flexibility, particularly of the lower back and hamstrings, by assessing forward reach from a seated position."),
  _q("A standard test used to assess power in the legs, measuring the height a person can jump vertically from a standing position, is the",
      ["vertical jump test", "sit-and-reach test", "Cooper run test", "reaction time test"], "vertical jump test",
      "The vertical jump test measures leg power by assessing the maximum height a person can jump vertically from a standing start."),
];

final _athleticsTrackAndFieldEvents = [
  _q("The starting position used by sprinters, involving hands and feet positioned on the track with the aid of starting blocks, is called the",
      ["crouch start", "standing start", "flying start", "distance start"], "crouch start",
      "The crouch start, aided by starting blocks, allows sprinters to generate maximum explosive power at the beginning of a race."),
  _q("In sprinting, the phase immediately following the start, during which a runner builds up to maximum speed, is called",
      ["acceleration", "deceleration", "recovery", "the finish"], "acceleration",
      "Acceleration is the phase where a sprinter progressively builds speed from the start until reaching their maximum velocity."),
  _q("A technique used by sprinters at the finish line, leaning the torso forward to cross the line slightly sooner, is called the",
      ["lean (dip) finish", "crouch start", "acceleration phase", "recovery phase"], "lean (dip) finish",
      "The lean (or dip) finish involves leaning the torso forward at the finish line, helping a sprinter's torso cross marginally sooner in a close race."),
  _q("Races covering distances such as 800m and 1500m, requiring a balance of speed and endurance, are classified as",
      ["middle-distance events", "sprint events", "long-distance events", "relay events"], "middle-distance events",
      "Middle-distance events, such as the 800m and 1500m, require athletes to balance elements of both speed and endurance."),
  _q("Races covering longer distances, such as 5000m, 10000m, and the marathon, are classified as",
      ["long-distance events", "sprint events", "middle-distance events", "relay events"], "long-distance events",
      "Long-distance events, such as the 5000m, 10000m, and marathon, place heavy emphasis on sustained aerobic endurance."),
  _q("A track event in which athletes must clear a series of barriers while running is called",
      ["hurdling", "sprinting only", "long-distance running only", "relay racing only"], "hurdling",
      "Hurdling requires athletes to clear a series of fixed barriers at speed while maintaining running rhythm and technique."),
  _q("A track event in which a team of runners each complete a portion of the total distance, passing a baton between them, is called",
      ["relay racing", "hurdling", "middle-distance running", "long jump"], "relay racing",
      "Relay racing involves a team of athletes, each running a set distance (leg) and passing a baton to the next runner."),
  _q("In relay racing, a baton exchange in which the receiving runner watches the baton being passed into their hand is called a",
      ["visual baton exchange", "non-visual (blind) baton exchange", "standing exchange only", "crouch exchange only"], "visual baton exchange",
      "A visual baton exchange involves the receiving athlete watching the baton as it is passed, often used in shorter relays where precision is critical."),
  _q("In relay racing, a baton exchange in which the receiving runner does not look back, instead reaching back to receive the baton based on timing and practice, is called a",
      ["non-visual (blind) baton exchange", "visual baton exchange", "standing exchange only", "crouch exchange only"], "non-visual (blind) baton exchange",
      "A non-visual (blind) exchange relies on practised timing rather than sight, allowing the receiving runner to maintain forward speed and focus."),
  _q("A jumping technique in the long jump involving a cycling leg motion in the air to maintain balance before landing is called the",
      ["hitch-kick style", "sail style", "Fosbury flop", "Western roll"], "hitch-kick style",
      "The hitch-kick technique involves a cycling leg motion during flight, helping the long jumper maintain balance and extend their jump distance."),
  _q("A simpler long jump technique in which the jumper holds a fixed body position through the air before landing is called the",
      ["sail style", "hitch-kick style", "Fosbury flop", "Western roll"], "sail style",
      "The sail style is a simpler long jump technique in which the body maintains a relatively fixed position throughout the flight phase."),
  _q("A field event involving a hop, step, and jump performed in sequence to achieve maximum distance is called the",
      ["triple jump", "long jump", "high jump", "shot put"], "triple jump",
      "The triple jump requires an athlete to perform a hop, a step, and a jump in sequence, aiming for maximum combined distance."),
  _q("A high jump technique, now the dominant style, involving the athlete going over the bar backward and head-first is called the",
      ["Fosbury flop", "Western roll", "sail style", "hitch-kick style"], "Fosbury flop",
      "The Fosbury flop, now the standard technique in competitive high jump, involves clearing the bar backward and head-first."),
  _q("An older high jump technique in which the athlete rolls over the bar facing downward, largely replaced by the Fosbury flop, is called the",
      ["Western roll", "Fosbury flop", "sail style", "hitch-kick style"], "Western roll",
      "The Western roll was an earlier high jump technique, largely superseded by the more efficient Fosbury flop in competitive athletics."),
  _q("A shot put technique involving a linear, gliding movement across the throwing circle before release is called the",
      ["O'Brien glide", "rotational style", "hitch-kick style", "sail style"], "O'Brien glide",
      "The O'Brien glide technique uses a linear gliding movement across the circle to build momentum before the shot is released."),
  _q("A shot put technique involving a spinning, rotational movement across the throwing circle before release, similar in style to discus throwing, is called the",
      ["rotational style", "O'Brien glide", "hitch-kick style", "sail style"], "rotational style",
      "The rotational shot put technique uses a spinning motion across the circle to generate momentum, resembling the discus throwing technique."),
  _q("A field event involving throwing a heavy, flat, disc-shaped implement for maximum distance is called the",
      ["discus throw", "shot put", "javelin throw", "hammer throw"], "discus throw",
      "The discus throw requires an athlete to throw a flat, disc-shaped implement for maximum distance, using a rotational technique."),
  _q("A field event involving throwing a long, spear-like implement for maximum distance is called the",
      ["javelin throw", "discus throw", "shot put", "hammer throw"], "javelin throw",
      "The javelin throw requires an athlete to throw a long, spear-shaped implement, using a running approach to generate momentum before release."),
  _q("A field event involving throwing a heavy metal ball attached to a wire and handle, using a spinning technique for momentum, is called the",
      ["hammer throw", "javelin throw", "discus throw", "shot put"], "hammer throw",
      "The hammer throw involves spinning to generate momentum before releasing a heavy metal ball attached to a wire and handle."),
  _q("The official responsible for determining the order of finish in a track race is called the",
      ["track judge", "timekeeper", "starter", "wind gauge operator"], "track judge",
      "Track judges are responsible for observing and determining the correct order of finish among competing athletes."),
  _q("The official responsible for recording the exact time taken by each athlete to complete a race is called the",
      ["timekeeper", "track judge", "starter", "field referee"], "timekeeper",
      "Timekeepers use stopwatches or automated timing systems to accurately record each athlete's race completion time."),
  _q("The official responsible for signalling the beginning of a race, typically using a starting gun or similar device, is called the",
      ["starter", "timekeeper", "track judge", "wind gauge operator"], "starter",
      "The starter signals the official beginning of a race, ensuring a fair and synchronised start for all competing athletes."),
  _q("The official responsible for overseeing rules compliance and resolving disputes within field events is called the",
      ["field referee", "starter", "timekeeper", "track judge"], "field referee",
      "Field referees oversee rule compliance and resolve disputes specifically within field events, such as jumps and throws."),
  _q("The official responsible for measuring wind speed and direction during sprint and jump events, since excessive tailwinds can affect record validity, is called the",
      ["wind gauge operator", "starter", "timekeeper", "track judge"], "wind gauge operator",
      "The wind gauge operator measures wind conditions during relevant events, since excessive tailwind can invalidate a performance for record purposes."),
  _q("A standard outdoor athletics track is typically measured as",
      ["400 metres in one complete lap", "100 metres in one complete lap", "1000 metres in one complete lap", "200 metres in one complete lap"], "400 metres in one complete lap",
      "A standard outdoor athletics track measures 400 metres for one complete lap, the basis for many middle- and long-distance race distances."),
  _q("In a 4 x 100m relay race, each of the four team members runs a distance of",
      ["100 metres", "400 metres", "200 metres", "50 metres"], "100 metres",
      "In a 4 x 100m relay, each of the four runners on a team covers a distance of 100 metres before passing the baton."),
  _q("A common rule in relay racing requires the baton exchange to occur within a designated",
      ["takeover (changeover) zone", "starting block area only", "finish line area only", "field event circle"], "takeover (changeover) zone",
      "Relay racing rules require the baton to be passed within a specific marked takeover (changeover) zone on the track."),
  _q("In the long jump, a competitor's jump is measured from the take-off board to the",
      ["nearest mark made in the sand by any part of the body", "farthest mark made in the sand", "centre of the sand pit regardless of the landing", "start of the runway"], "nearest mark made in the sand by any part of the body",
      "Long jump distances are measured from the take-off board to the nearest mark left in the sand pit by any part of the athlete's body."),
  _q("In the high jump, a competitor is eliminated from further attempts at a given height after",
      ["three consecutive failed attempts at that height", "a single failed attempt only", "five consecutive failed attempts", "ten consecutive failed attempts"], "three consecutive failed attempts at that height",
      "In competitive high jump, an athlete is eliminated from further attempts at a given height after three consecutive failures."),
];

final _ballGamesAndGymnastics = [
  _q("A team sport played on a rectangular pitch, using a spherical ball, primarily kicked (with limited handling except by the goalkeeper), is called",
      ["football (soccer)", "basketball", "volleyball", "handball"], "football (soccer)",
      "Football (soccer) is played on a rectangular pitch, with players primarily using their feet to control and pass the ball, except for the goalkeeper."),
  _q("A team sport played on an indoor court, in which players score by shooting a ball through an elevated hoop, is called",
      ["basketball", "football", "volleyball", "handball"], "basketball",
      "Basketball involves shooting a ball through an elevated hoop to score points, typically played on an indoor court."),
  _q("A team sport played across a net, in which players strike the ball to keep it airborne and grounded only on the opponent's side, is called",
      ["volleyball", "basketball", "football", "handball"], "volleyball",
      "Volleyball requires teams to hit the ball over a net, aiming to ground it on the opponent's side while preventing it from touching their own."),
  _q("A team sport in which players use their hands to throw a ball into a goal, combining elements of basketball and football, is called",
      ["handball", "basketball", "football", "hockey"], "handball",
      "Handball combines elements of basketball and football, with players using their hands to pass and throw the ball into the opposing goal."),
  _q("A team sport played with curved sticks, in which players manoeuvre a small ball into the opposing team's goal, is called",
      ["hockey", "handball", "basketball", "volleyball"], "hockey",
      "Hockey is played using curved sticks to control and manoeuvre a small ball, with the aim of scoring in the opponent's goal."),
  _q("A racket sport played on a court divided by a net, using a ball that bounces, played as singles or doubles, is called",
      ["lawn tennis", "table tennis", "badminton", "cricket"], "lawn tennis",
      "Lawn tennis is played on a court divided by a net, with players using rackets to strike a bouncing ball, competing as singles or doubles."),
  _q("A racket sport played on a small table divided by a low net, using a lightweight ball, is called",
      ["table tennis", "lawn tennis", "badminton", "cricket"], "table tennis",
      "Table tennis is played on a small table divided by a low net, using paddles to strike a lightweight ball back and forth."),
  _q("A racket sport played with a lightweight, feathered projectile called a shuttlecock, hit over a net, is called",
      ["badminton", "table tennis", "lawn tennis", "cricket"], "badminton",
      "Badminton uses a lightweight shuttlecock, struck with rackets over a net, rather than a bouncing ball as in tennis or table tennis."),
  _q("A bat-and-ball sport played between two teams, involving bowling, batting, and fielding on a large oval-shaped field, is called",
      ["cricket", "lawn tennis", "table tennis", "badminton"], "cricket",
      "Cricket is a bat-and-ball sport involving bowling, batting, and fielding, played between two teams on a large field with a central pitch."),
  _q("A gymnastics activity performed on a padded floor area, involving skills such as rolls, cartwheels, and handstands, is generally classified as",
      ["floor activities (tumbling)", "apparatus activities", "vaulting", "pommel horse routines only"], "floor activities (tumbling)",
      "Floor activities (tumbling) are performed on a padded surface, involving skills such as rolls, cartwheels, and handstands, without additional apparatus."),
  _q("A basic gymnastics skill involving rolling forward along the floor, tucking the body to rotate smoothly, is called a",
      ["forward roll", "backward roll", "cartwheel", "handstand"], "forward roll",
      "A forward roll involves tucking the body and rolling smoothly forward along the floor, a foundational gymnastics skill."),
  _q("A basic gymnastics skill involving rolling backward along the floor, similar in technique to a forward roll but in reverse, is called a",
      ["backward roll", "forward roll", "cartwheel", "headstand"], "backward roll",
      "A backward roll mirrors the forward roll technique, but performed by rolling backward along the floor."),
  _q("A gymnastics skill in which the body rotates sideways, passing through a momentary handstand position with legs extended outward, is called a",
      ["cartwheel", "forward roll", "backward roll", "headstand"], "cartwheel",
      "A cartwheel involves a sideways rotation of the body, passing through a brief handstand-like position with the legs extended in a wide 'star' shape."),
  _q("A gymnastics skill in which the body is supported upside down by the hands alone, with the body extended vertically, is called a",
      ["handstand", "headstand", "cartwheel", "forward roll"], "handstand",
      "A handstand involves supporting the entire body upside down using only the hands, with the body extended vertically in balance."),
  _q("A gymnastics skill in which the body is supported upside down primarily by the head and hands together, is called a",
      ["headstand", "handstand", "cartwheel", "forward roll"], "headstand",
      "A headstand involves supporting the body upside down using the head and hands together as a stable tripod base."),
  _q("Gymnastics activities that involve using specific pieces of equipment, such as vaulting boxes and parallel bars, are generally classified as",
      ["apparatus activities", "floor activities (tumbling)", "track events", "field events"], "apparatus activities",
      "Apparatus activities involve gymnastics skills performed using specific equipment, distinguishing them from floor-only tumbling activities."),
  _q("A gymnastics apparatus event involving a run-up and jump over a raised, padded box-like structure is called",
      ["vaulting", "parallel bars", "balance beam", "pommel horse"], "vaulting",
      "Vaulting involves a running approach followed by a jump over a raised, padded vaulting box or table apparatus."),
  _q("A gymnastics apparatus consisting of two horizontal bars set at the same height, used for swinging and balancing skills, is called the",
      ["parallel bars", "balance beam", "pommel horse", "vaulting box"], "parallel bars",
      "Parallel bars consist of two horizontal bars at the same height, used by gymnasts to perform swinging, balancing, and strength-based skills."),
  _q("A gymnastics apparatus consisting of a narrow, elevated beam requiring balance and precision for various skills, is called the",
      ["balance beam", "parallel bars", "pommel horse", "vaulting box"], "balance beam",
      "The balance beam is a narrow, elevated apparatus requiring precise balance and control as gymnasts perform routines along its length."),
  _q("A gymnastics apparatus resembling a padded horse-like structure with handles, on which gymnasts perform circular and swinging leg movements, is called the",
      ["pommel horse", "balance beam", "parallel bars", "vaulting box"], "pommel horse",
      "The pommel horse is a padded apparatus with handles, on which gymnasts perform circular and swinging leg movements while supporting themselves with their hands."),
  _q("In football (soccer), the standard number of players on the field per team, including the goalkeeper, is",
      ["11", "10", "12", "9"], "11",
      "Football (soccer) is played with 11 players per team on the field, including the goalkeeper."),
  _q("In basketball, the standard number of players on the court per team at any one time is",
      ["5", "6", "7", "11"], "5",
      "Basketball is played with 5 players per team on the court at any given time."),
  _q("In volleyball, the standard number of players on the court per team at any one time is",
      ["6", "5", "7", "11"], "6",
      "Volleyball is typically played with 6 players per team on the court at any given time."),
  _q("In football (soccer), a player is penalised with an indirect or direct free kick, or in some cases a caution, for committing a",
      ["foul", "goal", "throw-in", "corner kick"], "foul",
      "A foul in football refers to an illegal action by a player, such as tripping or handling the ball, resulting in a free kick or other penalty for the opposing team."),
  _q("In basketball, the act of illegally moving with the ball without dribbling it is called",
      ["travelling", "a foul only", "a free throw", "a rebound"], "travelling",
      "Travelling is a basketball violation in which a player moves their pivot foot illegally while holding the ball without dribbling."),
  _q("In basketball, points scored from a successful shot taken from beyond the marked arc are worth",
      ["three points", "two points", "one point", "four points"], "three points",
      "A successful shot taken from beyond the three-point arc is worth three points in basketball, more than the standard two-point field goal."),
  _q("A key tactical skill in football (soccer) involves players creating and using open space through movement and",
      ["accurate passing between teammates", "standing completely still throughout the match", "ignoring teammates' positions entirely", "avoiding all forms of ball possession"], "accurate passing between teammates",
      "Effective football tactics rely on players moving to create space and using accurate passing to maintain possession and create scoring opportunities."),
  _q("In lawn tennis, a match is generally organised into games, which are grouped into",
      ["sets", "innings", "quarters", "periods"], "sets",
      "Tennis matches are structured into games, which are grouped into sets, with a player typically needing to win a set number of sets to win the match."),
];

final _sportsMedicineOrganizationAndAdministration = [
  _q("A sudden, complete break in the continuity of a bone is called a",
      ["fracture", "sprain", "strain", "dislocation"], "fracture",
      "A fracture describes a break in the continuity of a bone, ranging from a small crack to a complete break."),
  _q("An injury in which a bone is forced out of its normal position at a joint is called a",
      ["dislocation", "fracture", "sprain", "strain"], "dislocation",
      "A dislocation occurs when a bone is displaced from its normal position within a joint."),
  _q("An injury involving the stretching or tearing of a ligament, typically at a joint, is called a",
      ["sprain", "strain", "fracture", "dislocation"], "sprain",
      "A sprain involves the stretching or tearing of a ligament, the connective tissue linking bone to bone at a joint."),
  _q("An injury involving the stretching or tearing of a muscle or tendon is called a",
      ["strain", "sprain", "fracture", "dislocation"], "strain",
      "A strain involves the stretching or tearing of a muscle or tendon, distinct from a sprain which affects ligaments."),
  _q("A painful, involuntary contraction of a muscle, often occurring during or after strenuous exercise, is called a",
      ["muscle cramp", "sprain", "strain", "fracture"], "muscle cramp",
      "A muscle cramp is a sudden, painful, involuntary muscle contraction, often triggered by fatigue, dehydration, or strenuous activity."),
  _q("A head injury resulting from a blow or jolt, potentially causing temporary disruption of brain function, is called a",
      ["concussion", "fracture", "sprain", "strain"], "concussion",
      "A concussion is a traumatic brain injury caused by a blow or jolt to the head, potentially causing temporary disruption of normal brain function."),
  _q("In the RICE protocol for treating minor sports injuries, the 'R' stands for",
      ["Rest", "Recovery only", "Reduction", "Repetition"], "Rest",
      "The 'R' in the RICE protocol stands for Rest, allowing the injured area time to begin healing without further strain."),
  _q("In the RICE protocol for treating minor sports injuries, the 'I' stands for",
      ["Ice", "Immobilisation only", "Inflammation", "Injection"], "Ice",
      "The 'I' in RICE stands for Ice, applied to help reduce swelling and numb pain in the injured area."),
  _q("In the RICE protocol for treating minor sports injuries, the 'C' stands for",
      ["Compression", "Concussion", "Circulation only", "Cramping"], "Compression",
      "The 'C' in RICE stands for Compression, typically applied using a bandage to help control swelling in the injured area."),
  _q("In the RICE protocol for treating minor sports injuries, the 'E' stands for",
      ["Elevation", "Exercise", "Examination only", "Emergency"], "Elevation",
      "The 'E' in RICE stands for Elevation, raising the injured area above heart level where possible to help reduce swelling."),
  _q("Substances used by athletes to artificially enhance physical performance beyond natural ability are called",
      ["ergogenic aids", "sports medicine tools", "protective equipment", "rehabilitation devices"], "ergogenic aids",
      "Ergogenic aids refer to substances or methods used to enhance athletic performance, some of which are banned due to health risks or unfair advantage."),
  _q("Synthetic hormones used illegally by some athletes to increase muscle mass and strength are called",
      ["anabolic steroids", "vitamins", "electrolytes", "carbohydrate supplements only"], "anabolic steroids",
      "Anabolic steroids are synthetic hormones sometimes misused to artificially increase muscle mass and strength, banned in most competitive sports."),
  _q("A banned performance-enhancement method involving the manipulation of an athlete's blood to increase oxygen-carrying capacity is called",
      ["blood doping", "anabolic steroid use only", "vitamin supplementation", "electrolyte replacement"], "blood doping",
      "Blood doping manipulates an athlete's blood (such as through transfusions) to increase red blood cell count and oxygen-carrying capacity, a banned practice in competitive sport."),
  _q("The international body primarily responsible for setting and enforcing anti-doping rules and codes in sport is the",
      ["World Anti-Doping Agency (WADA)", "World Health Organization (WHO)", "International Olympic Committee alone", "Nigerian Olympic Committee alone"], "World Anti-Doping Agency (WADA)",
      "WADA (World Anti-Doping Agency) is the international body responsible for developing and enforcing anti-doping policies and codes across sports."),
  _q("A tournament format in which a team or player is eliminated after a single loss, continuing until one champion remains, is called",
      ["single-elimination (knockout) format", "league (round-robin) format", "double-elimination format only", "friendly format only"], "single-elimination (knockout) format",
      "In a single-elimination (knockout) format, a single loss removes a team or player from the competition, continuing until only one champion remains."),
  _q("A tournament format in which every team or player competes against every other participant, with final standings based on overall results, is called a",
      ["league (round-robin) format", "single-elimination format", "knockout format only", "exhibition format only"], "league (round-robin) format",
      "In a league (round-robin) format, every participant competes against every other participant, with rankings determined by overall performance across all matches."),
  _q("Maintaining sports facilities in good condition, including regular inspection and repair, is important mainly to",
      ["ensure participant safety and prolong the usable life of the facility", "increase the risk of injury to participants intentionally", "eliminate the need for any safety standards", "have no bearing on participant experience or safety"], "ensure participant safety and prolong the usable life of the facility",
      "Regular maintenance of sports facilities helps ensure participant safety and extends the usable life of the equipment and infrastructure."),
  _q("Public relations management in sports administration mainly involves",
      ["promoting a positive public image and managing communication with stakeholders", "avoiding all communication with the public or media", "discouraging community interest in sporting events", "eliminating the need for any organisational structure"], "promoting a positive public image and managing communication with stakeholders",
      "Public relations management in sports involves promoting a positive image and effectively managing communication with fans, sponsors, media, and other stakeholders."),
  _q("The Nigerian Olympic Committee is primarily responsible for",
      ["coordinating Nigeria's participation in the Olympic Games and related sports development", "regulating international trade agreements", "administering national healthcare policy", "managing Nigeria's educational curriculum"], "coordinating Nigeria's participation in the Olympic Games and related sports development",
      "The Nigerian Olympic Committee coordinates the country's participation in the Olympic Games and supports broader national sports development efforts."),
  _q("Effective sports administration generally requires attention to",
      ["organisation, planning, and coordination of events, facilities, and personnel", "ignoring all aspects of event planning and coordination", "avoiding any structured management of sporting activities", "eliminating the need for trained officials or personnel"], "organisation, planning, and coordination of events, facilities, and personnel",
      "Effective sports administration requires careful organisation, planning, and coordination across events, facilities, and personnel to ensure successful operations."),
  _q("Immediately after a suspected concussion, an athlete should generally be",
      ["removed from play and assessed by a qualified professional before returning", "immediately returned to full play with no assessment", "given performance-enhancing substances to continue playing", "ignored entirely, regardless of symptoms"], "removed from play and assessed by a qualified professional before returning",
      "An athlete suspected of concussion should be removed from play immediately and properly assessed by a qualified professional before any return to activity."),
  _q("The use of anabolic steroids by athletes carries health risks that can include",
      ["hormonal imbalances and cardiovascular problems", "guaranteed improvement in long-term health with no risks", "complete elimination of injury risk", "no effect on the body whatsoever"], "hormonal imbalances and cardiovascular problems",
      "Anabolic steroid misuse carries serious health risks, including hormonal imbalances, cardiovascular problems, and other long-term harm."),
  _q("A double-elimination tournament format differs from a single-elimination format mainly in that competitors",
      ["are eliminated only after two losses, rather than just one", "are eliminated immediately after their first loss, same as single-elimination", "never face elimination under any circumstances", "compete only once throughout the entire tournament"], "are eliminated only after two losses, rather than just one",
      "In a double-elimination format, a competitor must lose twice before being eliminated, offering a second chance not available in single-elimination formats."),
];
