import "../quiz_question.dart";

const _subject = "Chemistry";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// WAEC Chemistry — Introductory topics: Introduction to Chemistry, Structure
/// of the Atom, Standard Separation Techniques, Periodic Chemistry, Chemical
/// Bonds, Stoichiometry and Chemical Reactions, and States of Matter.
List<QuizQuestion> buildWaecChemistryIntroQuestions() {
  return [
    ..._introToChemistry,
    ..._structureOfAtom,
    ..._separationTechniques,
    ..._periodicChemistry,
    ..._chemicalBonds,
    ..._stoichiometry,
    ..._statesOfMatter,
  ];
}

final _introToChemistry = [
  _q("Which of the following is the SI unit of length?",
      ["Metre", "Gram", "Second", "Kelvin"], "Metre",
      "The metre (m) is the base SI unit for length; gram relates to mass, second to time, and kelvin to temperature."),
  _q("What is the SI unit of mass?",
      ["Kilogram", "Gram", "Litre", "Newton"], "Kilogram",
      "The kilogram (kg) is the base SI unit of mass, though the gram is often used for smaller-scale laboratory measurements."),
  _q("Which instrument is most suitable for measuring a small volume of liquid accurately, such as 25.0 cm3?",
      ["Pipette", "Beaker", "Bucket", "Metre rule"], "Pipette",
      "A pipette delivers a precise, fixed or measured volume of liquid, whereas a beaker only gives an approximate volume."),
  _q("The SI unit of temperature used in scientific calculations is the",
      ["Kelvin", "Celsius", "Fahrenheit", "Joule"], "Kelvin",
      "The kelvin (K) is the SI base unit of thermodynamic temperature; Celsius is a common but non-SI derived scale, and Fahrenheit is not used in SI."),
  _q("How many significant figures are in the measurement 0.00520 g?",
      ["3", "2", "5", "6"], "3",
      "Leading zeros are not significant, but the trailing zero after the decimal point is significant here, giving 5, 2, and 0 as the three significant figures."),
  _q("A student measures the length of a rod as 12.50 cm using a ruler with millimetre divisions. This value is best described as having",
      ["four significant figures", "two significant figures", "three significant figures", "one significant figure"], "four significant figures",
      "In 12.50, all non-zero digits (1, 2, 5) count, and the trailing zero after the decimal point is also significant, giving four significant figures in total."),
  _q("Which of these best defines a hypothesis in the scientific method?",
      ["A tentative explanation or educated guess proposed to explain an observation, to be tested further", "A statement proven true beyond all doubt", "A repeated experimental result", "A universally accepted natural law"], "A tentative explanation or educated guess proposed to explain an observation, to be tested further",
      "A hypothesis is a proposed, testable explanation for an observation; it must be confirmed or refuted through further experimentation before being accepted."),
  _q("In the scientific method, the process of using existing knowledge to draw a logical conclusion from data collected is called",
      ["inference", "observation", "hypothesis", "control"], "inference",
      "Inference is the reasoning step in which conclusions are drawn from observed data or experimental results, distinct from the raw act of observing."),
  _q("A scientific law differs from a scientific theory in that a law",
      ["describes what happens under given conditions without explaining why, based on repeated observations", "explains why a phenomenon occurs using a broad, well-tested framework", "is only a guess awaiting confirmation", "can never be revised"], "describes what happens under given conditions without explaining why, based on repeated observations",
      "A scientific law is a concise statement (often mathematical) describing a consistently observed pattern, while a theory provides the underlying explanation for why the pattern occurs."),
  _q("A well-substantiated explanation of some aspect of the natural world, supported by a large body of evidence and repeated experimentation, is called a",
      ["theory", "hypothesis", "observation", "guess"], "theory",
      "A scientific theory is a broad, thoroughly tested explanatory framework, unlike a hypothesis, which is a preliminary, still-to-be-tested proposal."),
  _q("Which of the following correctly orders the general steps of the scientific method?",
      ["Observation, hypothesis, experimentation, inference, theory/law", "Theory, hypothesis, observation, law", "Inference, law, hypothesis, observation", "Experimentation, theory, observation, hypothesis"], "Observation, hypothesis, experimentation, inference, theory/law",
      "The scientific method typically begins with observation of a phenomenon, followed by a hypothesis, testing through experimentation, drawing inferences, and eventually forming laws or theories if well supported."),
  _q("Which of the following is a derived, not a base, SI quantity?",
      ["Volume", "Length", "Mass", "Time"], "Volume",
      "Volume (e.g., m3) is derived by combining base quantities of length (length x length x length); length, mass, and time are themselves SI base quantities."),
  _q("A digital thermometer reads a liquid's temperature as 25.4 degC. This measurement has how many significant figures?",
      ["3", "2", "4", "1"], "3",
      "All non-zero digits are significant: 2, 5, and 4 give a total of three significant figures in 25.4."),
  _q("Which quantity is measured using a stopwatch in a laboratory experiment?",
      ["Time", "Mass", "Volume", "Temperature"], "Time",
      "A stopwatch measures elapsed time, typically in seconds or minutes, during timed reactions or physical processes."),
  _q("What is 0.000456 expressed correctly in standard (scientific) notation?",
      ["4.56 x 10^-4", "4.56 x 10^4", "45.6 x 10^-5", "456 x 10^-3"], "4.56 x 10^-4",
      "Moving the decimal point four places to the right to get 4.56 requires multiplying by 10^-4, since the original number is less than 1."),
  _q("An observation in the scientific method is best described as",
      ["information gathered directly through the senses or measuring instruments", "a conclusion drawn from reasoning alone", "an untested guess", "a universally accepted explanation"], "information gathered directly through the senses or measuring instruments",
      "Observation is the initial, direct gathering of data (qualitative or quantitative) using the senses or instruments, forming the basis for hypotheses."),
];

final _structureOfAtom = [
  _q("Which subatomic particle is found in the nucleus and carries a positive charge?",
      ["Proton", "Electron", "Neutron", "Positron"], "Proton",
      "Protons, located in the nucleus alongside neutrons, carry a single positive charge (+1), balancing the negative electrons in a neutral atom."),
  _q("The atomic number of an element represents the number of",
      ["protons in the nucleus of an atom", "neutrons in the nucleus", "protons plus neutrons", "electrons in the outermost shell only"], "protons in the nucleus of an atom",
      "Atomic number (Z) uniquely identifies an element by the number of protons in its nucleus; in a neutral atom, this also equals the number of electrons."),
  _q("The mass number of an atom is the sum of the number of",
      ["protons and neutrons in the nucleus", "protons and electrons", "neutrons and electrons", "protons only"], "protons and neutrons in the nucleus",
      "Mass number (A) accounts for the nucleons (protons and neutrons), since electrons contribute negligible mass to the atom."),
  _q("An atom of chlorine has 17 protons and 18 neutrons. What is its mass number?",
      ["35", "17", "18", "1"], "35",
      "Mass number = protons + neutrons = 17 + 18 = 35."),
  _q("Isotopes of the same element differ in their number of",
      ["neutrons", "protons", "electrons in a neutral atom", "atomic number"], "neutrons",
      "Isotopes share the same atomic number (protons) but have different mass numbers because they contain different numbers of neutrons."),
  _q("Chlorine has two isotopes, Cl-35 (75%) and Cl-37 (25%). What is its relative atomic mass?",
      ["35.5", "36", "35", "37"], "35.5",
      "Weighted average = (35 x 0.75) + (37 x 0.25) = 26.25 + 9.25 = 35.5."),
  _q("The relative atomic mass of an element is defined on a scale where the mass of one atom of",
      ["carbon-12 is taken as exactly 12 units", "hydrogen-1 is taken as exactly 1 unit", "oxygen-16 is taken as exactly 16 units", "carbon-14 is taken as exactly 14 units"], "carbon-12 is taken as exactly 12 units",
      "By international convention, the carbon-12 isotope is assigned a mass of exactly 12 units, and all other atomic masses are measured relative to this standard."),
  _q("Which of the following describes a physical change?",
      ["Melting of ice to form water", "Rusting of iron", "Burning of magnesium ribbon", "Souring of milk"], "Melting of ice to form water",
      "Melting is a physical change because it only alters the state of matter (solid to liquid) without forming a new substance; the process is also easily reversible."),
  _q("Which of the following describes a chemical change?",
      ["Burning of magnesium ribbon in air", "Evaporation of water", "Melting of wax", "Dissolving sugar in water"], "Burning of magnesium ribbon in air",
      "Burning magnesium produces a new substance, magnesium oxide, through a chemical reaction with oxygen, unlike purely physical processes such as melting or dissolving."),
  _q("What is the electronic configuration of potassium (atomic number 19)?",
      ["1s2 2s2 2p6 3s2 3p6 4s1", "1s2 2s2 2p6 3s2 3p7", "1s2 2s2 2p6 3s2 3p6 3d1", "1s2 2s2 2p6 3s2 3p6 4s2"], "1s2 2s2 2p6 3s2 3p6 4s1",
      "Potassium has 19 electrons; after filling 1s, 2s, 2p, 3s, and 3p (18 electrons), the 19th electron enters the 4s orbital rather than 3d, since 4s has slightly lower energy."),
  _q("The Aufbau Principle states that electrons occupy atomic orbitals",
      ["in order of increasing energy, filling the lowest-energy orbitals first", "in order of decreasing energy", "randomly, regardless of energy level", "only in the outermost shell first"], "in order of increasing energy, filling the lowest-energy orbitals first",
      "The Aufbau Principle (German for 'building up') states that electrons fill the lowest available energy orbitals before occupying higher-energy ones."),
  _q("The Pauli Exclusion Principle states that",
      ["no two electrons in the same atom can have the same set of four quantum numbers, so an orbital holds at most two electrons of opposite spin", "electrons always occupy separate orbitals within a subshell before pairing", "electrons fill orbitals in order of increasing energy", "an atom cannot have more than 8 electrons in its outer shell"], "no two electrons in the same atom can have the same set of four quantum numbers, so an orbital holds at most two electrons of opposite spin",
      "The Pauli Exclusion Principle limits each orbital to a maximum of two electrons, and those two electrons must have opposite spins."),
  _q("Hund's Rule states that when filling degenerate orbitals of the same subshell (e.g., the three 2p orbitals), electrons will",
      ["occupy separate orbitals singly, with parallel spins, before any orbital is doubly occupied", "immediately pair up in the lowest-numbered orbital", "occupy orbitals in a completely random order", "always remain unpaired regardless of the number of electrons"], "occupy separate orbitals singly, with parallel spins, before any orbital is doubly occupied",
      "Hund's Rule minimises electron-electron repulsion by placing one electron in each orbital of a subshell (with parallel spins) before any pairing occurs."),
  _q("What is the electronic configuration of calcium (atomic number 20)?",
      ["2, 8, 8, 2", "2, 8, 10", "2, 8, 8, 1, 1", "2, 8, 6, 4"], "2, 8, 8, 2",
      "Calcium has 20 electrons, filling shells as 2, 8, 8, and then 2 electrons in the fourth shell, following the standard shell-filling pattern (2, 8, 8, 2)."),
  _q("How many electrons can the 3d subshell hold at maximum, according to quantum mechanical rules?",
      ["10", "6", "2", "14"], "10",
      "The d subshell has 5 orbitals, and each orbital holds a maximum of 2 electrons (Pauli Exclusion Principle), giving a maximum of 5 x 2 = 10 electrons."),
  _q("An atom of an element X has 20 protons and 20 electrons but loses 2 electrons to form an ion. What is the charge on the resulting ion?",
      ["2+", "2-", "1+", "Neutral"], "2+",
      "Losing 2 negatively charged electrons from a neutral atom leaves 20 protons and only 18 electrons, giving a net charge of +2."),
];

final _separationTechniques = [
  _q("A mixture in which the components are uniformly distributed throughout, with no visible boundary between them, is called",
      ["a homogeneous mixture", "a heterogeneous mixture", "a compound", "an element"], "a homogeneous mixture",
      "Homogeneous mixtures (like a salt solution) have uniform composition and appearance throughout, unlike heterogeneous mixtures, which show distinct, unevenly distributed regions or phases."),
  _q("A mixture of sand and water, in which the two components remain visibly distinct, is an example of",
      ["a heterogeneous mixture", "a homogeneous mixture", "a solution", "a pure compound"], "a heterogeneous mixture",
      "Because sand does not dissolve in water, the mixture shows visibly separate phases and non-uniform composition, characteristic of a heterogeneous mixture."),
  _q("Which technique is used to separate a soluble solid from a solvent, recovering only the solvent by heating until it turns to vapour, which then escapes?",
      ["Evaporation", "Filtration", "Sublimation", "Decantation"], "Evaporation",
      "Evaporation drives off the volatile solvent as vapour, leaving the dissolved solid behind as a residue; unlike distillation, the vapour is not collected."),
  _q("Which technique separates an insoluble solid from a liquid using a porous medium, such as filter paper?",
      ["Filtration", "Evaporation", "Crystallization", "Fractional distillation"], "Filtration",
      "Filtration passes a mixture through a porous medium that retains larger, insoluble solid particles (residue) while allowing the liquid (filtrate) to pass through."),
  _q("Crystallization is used to obtain a pure solid from its saturated solution by",
      ["cooling the solution slowly so that pure crystals of the solute form and grow", "heating the solution until it is completely dry", "passing the solution through filter paper", "adding a magnet to attract the solute"], "cooling the solution slowly so that pure crystals of the solute form and grow",
      "Slow cooling of a hot saturated solution allows solute particles to arrange into a well-ordered, pure crystal lattice, often superior in purity to simple evaporation."),
  _q("Fractional distillation is particularly suited to separating",
      ["a mixture of miscible liquids with different but reasonably close boiling points", "an insoluble solid from a liquid", "two immiscible liquids of very different densities", "a mixture of two solids with different melting points"], "a mixture of miscible liquids with different but reasonably close boiling points",
      "A fractionating column provides repeated vaporisation-condensation cycles, allowing separation of miscible liquids whose boiling points are close together, such as in crude oil refining."),
  _q("Sublimation can be used to separate a mixture of ammonium chloride and sodium chloride because",
      ["ammonium chloride sublimes directly from solid to gas on heating, while sodium chloride does not", "sodium chloride sublimes but ammonium chloride does not", "both substances sublime at the same rate", "ammonium chloride is magnetic"], "ammonium chloride sublimes directly from solid to gas on heating, while sodium chloride does not",
      "On heating, ammonium chloride sublimes (solid directly to vapour) and can be recondensed elsewhere, leaving the non-subliming sodium chloride behind."),
  _q("Paper chromatography separates the components of a mixture, such as ink dyes, mainly based on differences in their",
      ["solubility and rate of movement through the stationary phase", "melting points", "densities", "magnetic properties"], "solubility and rate of movement through the stationary phase",
      "Components with different solubilities in the mobile phase and different affinities for the stationary phase (paper) travel at different rates, separating into distinct spots."),
  _q("Decantation is a simple technique used to separate",
      ["a liquid from a settled insoluble solid by carefully pouring off the liquid", "two miscible liquids with close boiling points", "a soluble solid dissolved in a liquid", "a gas mixture into its components"], "a liquid from a settled insoluble solid by carefully pouring off the liquid",
      "After a solid settles at the bottom of a container, the clear liquid above (supernatant) is carefully poured off, leaving the solid residue behind, without using filter paper."),
  _q("Precipitation as a separation technique typically involves",
      ["mixing two solutions so an insoluble solid forms, which is then filtered out", "heating a solution until only solid remains", "cooling a gas until it liquefies", "passing a mixture through chromatography paper"], "mixing two solutions so an insoluble solid forms, which is then filtered out",
      "When two soluble reactants combine to form an insoluble product (precipitate), the solid can then be separated from the remaining solution by filtration."),
  _q("Magnetic separation is a suitable technique for separating a mixture containing",
      ["iron filings and non-magnetic sand", "sugar and water", "iodine and sand", "salt and water"], "iron filings and non-magnetic sand",
      "Only mixtures containing a magnetic component, such as iron filings, can be separated using a magnet, which attracts the magnetic material away from the rest."),
  _q("Which of the following is the best test for the purity of a liquid substance?",
      ["A fixed, sharp boiling point at a given pressure", "Its colour", "Its smell", "Its density alone"], "A fixed, sharp boiling point at a given pressure",
      "A pure liquid boils sharply at one specific temperature (at a given pressure); the presence of impurities raises the boiling point and widens the boiling range."),
  _q("A mixture of two immiscible liquids, such as oil and water, is best separated using a",
      ["separating funnel", "fractionating column", "chromatography paper", "sublimation apparatus"], "separating funnel",
      "Immiscible liquids form distinct layers based on density, allowing the denser lower layer to be run off through the tap of a separating funnel."),
  _q("Which statement about mixtures is correct?",
      ["Mixtures can be separated by physical methods into their constituent components", "Mixtures always have a fixed, definite composition by mass", "Mixtures can only be separated by chemical reactions", "Mixtures cannot exist as solids"], "Mixtures can be separated by physical methods into their constituent components",
      "Unlike compounds, mixtures are not chemically bonded together, so their components retain their individual properties and can be separated by physical means, such as filtration or distillation."),
  _q("Which separation technique would best recover pure water from ink (a solution of dye in water)?",
      ["Simple distillation", "Filtration", "Magnetic separation", "Decantation"], "Simple distillation",
      "The dye is dissolved in water, so it cannot be filtered out; distillation vaporises the water, leaving the non-volatile dye behind, and the vapour is condensed to give pure water."),
  _q("A mixture of two solids, one of which is soluble in a particular solvent and one of which is not, can be separated using",
      ["dissolving in the solvent followed by filtration", "sublimation only", "a separating funnel only", "magnetic separation only"], "dissolving in the solvent followed by filtration",
      "Adding the solvent dissolves only the soluble solid; filtration then removes the undissolved insoluble solid, and evaporation of the filtrate recovers the dissolved solid."),
];

final _periodicChemistry = [
  _q("The modern periodic law states that the properties of elements are a periodic function of their",
      ["atomic number", "atomic mass", "number of neutrons", "melting point"], "atomic number",
      "Unlike Mendeleev's original law based on atomic mass, the modern periodic law arranges elements by increasing atomic number, correctly resolving earlier anomalies."),
  _q("Elements in the periodic table are arranged in horizontal rows called",
      ["periods", "groups", "series", "blocks"], "periods",
      "Horizontal rows are called periods, while vertical columns of elements with similar properties are called groups."),
  _q("Elements in the same group of the periodic table have similar chemical properties mainly because they have the same",
      ["number of electrons in their outermost (valence) shell", "atomic mass", "number of neutrons", "physical state at room temperature"], "number of electrons in their outermost (valence) shell",
      "Chemical reactivity depends heavily on valence electrons, and elements within a group share the same number of these, giving them similar chemical behaviour."),
  _q("Across a period from left to right, atomic radius generally",
      ["decreases, due to increasing nuclear charge pulling the electron cloud inward", "increases, due to additional electron shells", "remains constant", "increases, due to decreasing nuclear charge"], "decreases, due to increasing nuclear charge pulling the electron cloud inward",
      "Across a period, electrons are added to the same outer shell while protons increase, so the greater nuclear attraction pulls the electron cloud closer, shrinking atomic radius."),
  _q("Down a group of the periodic table, atomic radius generally",
      ["increases, due to the addition of extra electron shells", "decreases, due to increasing nuclear charge", "remains the same for all elements", "decreases, due to fewer electron shells"], "increases, due to the addition of extra electron shells",
      "Descending a group adds new electron shells further from the nucleus, increasing atomic radius despite the greater nuclear charge."),
  _q("Ionization energy generally increases across a period from left to right because",
      ["increasing nuclear charge holds outer electrons more tightly, making them harder to remove", "atomic radius increases across the period", "the number of electron shells increases", "shielding by inner electrons increases significantly"], "increasing nuclear charge holds outer electrons more tightly, making them harder to remove",
      "As nuclear charge increases across a period with no extra shielding shell added, outer electrons are held more strongly, requiring more energy to remove them."),
  _q("Which trend correctly describes electronegativity across a period from left to right?",
      ["It generally increases, as atoms attract bonding electrons more strongly", "It generally decreases", "It stays constant", "It becomes negative"], "It generally increases, as atoms attract bonding electrons more strongly",
      "Across a period, increasing nuclear charge and decreasing atomic radius result in a stronger pull on shared electron pairs, increasing electronegativity."),
  _q("Electron affinity refers to the energy change when",
      ["a gaseous atom gains an electron to form a negative ion", "a gaseous atom loses an electron to form a positive ion", "two atoms share a pair of electrons", "an atom loses a proton"], "a gaseous atom gains an electron to form a negative ion",
      "Electron affinity is the energy released (or absorbed) when an isolated gaseous atom accepts an extra electron to form an anion."),
  _q("Which of the following is a characteristic trend of the Group 7 elements (halogens) down the group?",
      ["Reactivity decreases down the group", "Reactivity increases down the group", "Atomic radius decreases down the group", "All halogens are gases at room temperature"], "Reactivity decreases down the group",
      "Down Group 7, increasing atomic radius and shielding make it harder for halogens to attract an extra electron, so their reactivity as oxidising agents decreases down the group."),
  _q("Which physical state describes chlorine, bromine, and iodine respectively at room temperature?",
      ["Gas, liquid, solid", "Solid, liquid, gas", "Gas, gas, liquid", "Liquid, solid, gas"], "Gas, liquid, solid",
      "Down Group 7, increasing molecular size and stronger van der Waals forces raise melting and boiling points: chlorine is a gas, bromine a liquid, and iodine a solid at room temperature."),
  _q("Across Period 3 (Na to Ar), the elements change in character from",
      ["metallic (Na, Mg, Al) through metalloid (Si) to non-metallic (P, S, Cl, Ar)", "non-metallic to metallic only", "purely metallic throughout", "purely non-metallic throughout"], "metallic (Na, Mg, Al) through metalloid (Si) to non-metallic (P, S, Cl, Ar)",
      "Period 3 begins with reactive metals (sodium, magnesium, aluminium), transitions through the metalloid silicon, and ends with non-metals (phosphorus, sulphur, chlorine) and the noble gas argon."),
  _q("Which Period 3 element has the highest melting point due to its giant covalent (macromolecular) structure?",
      ["Silicon", "Sodium", "Chlorine", "Argon"], "Silicon",
      "Silicon forms a giant covalent lattice with strong covalent bonds throughout, requiring far more energy to melt than the metallic sodium or simple molecular chlorine and argon."),
  _q("The first transition series (Scandium to Zinc) is characterised by the progressive filling of the",
      ["3d subshell", "3p subshell", "4p subshell", "2p subshell"], "3d subshell",
      "Transition metals in the first series are defined by electrons progressively filling the 3d subshell after the 4s subshell is occupied."),
  _q("Which of the following is a characteristic property of transition metals, unlike most main group metals?",
      ["They commonly show variable oxidation states", "They only ever form colourless compounds", "They cannot act as catalysts", "They have only one possible oxidation state"], "They commonly show variable oxidation states",
      "Transition metals such as iron and manganese readily exist in multiple oxidation states (e.g., Fe2+ and Fe3+) because their 3d and 4s electrons have similar energies."),
  _q("Many transition metal compounds are coloured because",
      ["d-orbital electrons absorb specific wavelengths of visible light during electronic transitions", "they contain only s and p electrons", "they are always insoluble in water", "their ions have no charge"], "d-orbital electrons absorb specific wavelengths of visible light during electronic transitions",
      "Partially filled d-orbitals allow electrons to be excited between split d-orbital energy levels by absorbing certain wavelengths of visible light, giving transition metal compounds their characteristic colours."),
  _q("Transition metals and their compounds are widely used industrially mainly because of their",
      ["catalytic activity in many important industrial reactions", "complete chemical inertness", "total lack of variable oxidation states", "inability to form complex ions"], "catalytic activity in many important industrial reactions",
      "Transition metals like iron (Haber process) and nickel (hydrogenation) are effective catalysts due to their variable oxidation states and ability to form intermediate complexes."),
  _q("A complex ion is best described as",
      ["a central metal ion surrounded by a number of ligands bonded through coordinate (dative) bonds", "a simple ionic compound formed by electron transfer", "a covalent molecule with no central metal atom", "an isotope of a transition metal"], "a central metal ion surrounded by a number of ligands bonded through coordinate (dative) bonds",
      "Complex ions consist of a central metal ion (often a transition metal) coordinately bonded to surrounding ligands, such as water or ammonia molecules, which donate electron pairs."),
];

final _chemicalBonds = [
  _q("An electrovalent (ionic) bond is formed by",
      ["complete transfer of electrons from a metal atom to a non-metal atom", "equal sharing of electrons between two non-metal atoms", "the donation of both electrons in a pair by a single atom", "a sea of delocalised electrons around metal ions"], "complete transfer of electrons from a metal atom to a non-metal atom",
      "In ionic bonding, electrons transfer completely from a metal (forming a cation) to a non-metal (forming an anion), and the resulting ions are held by strong electrostatic attraction."),
  _q("A single covalent bond is formed when two atoms",
      ["share one pair of electrons between them", "share two pairs of electrons", "share three pairs of electrons", "transfer one electron completely"], "share one pair of electrons between them",
      "A single covalent bond consists of one shared pair of electrons, one electron contributed by each bonding atom, as seen in H-H or Cl-Cl."),
  _q("A double covalent bond, as found in the oxygen molecule O2, involves the sharing of",
      ["two pairs of electrons between the two atoms", "one pair of electrons", "three pairs of electrons", "four pairs of electrons"], "two pairs of electrons between the two atoms",
      "A double bond consists of two shared electron pairs, making it shorter and stronger than a single bond, as in O=O."),
  _q("A triple covalent bond, as found in the nitrogen molecule N2, involves the sharing of",
      ["three pairs of electrons between the two atoms", "one pair of electrons", "two pairs of electrons", "four pairs of electrons"], "three pairs of electrons between the two atoms",
      "The nitrogen molecule shares three electron pairs, forming a very strong triple bond that accounts for nitrogen gas's characteristic unreactivity at room temperature."),
  _q("A coordinate (dative) covalent bond differs from an ordinary covalent bond in that",
      ["both electrons of the shared pair are donated by only one of the bonding atoms", "no electrons are shared between the atoms", "electrons are completely transferred from one atom to the other", "it can only form between two identical atoms"], "both electrons of the shared pair are donated by only one of the bonding atoms",
      "In coordinate bonding, one atom alone (the donor, which has a lone pair) supplies both electrons for the shared pair, unlike ordinary covalent bonds where each atom contributes one electron."),
  _q("The formation of the ammonium ion, NH4+, from ammonia and a hydrogen ion involves",
      ["a coordinate bond, as the lone pair on nitrogen is donated to the incoming H+ ion", "an ionic bond only", "a metallic bond", "a triple covalent bond"], "a coordinate bond, as the lone pair on nitrogen is donated to the incoming H+ ion",
      "The nitrogen atom in ammonia has a lone pair, which it donates entirely to the empty orbital of the H+ ion, forming a coordinate (dative) bond in NH4+."),
  _q("The formation of the hydroxonium (oxonium) ion, H3O+, from water and a hydrogen ion also involves",
      ["a coordinate bond, formed from a lone pair on the oxygen atom of water", "only ionic bonding", "a metallic bond", "no bond at all, just a loose association"], "a coordinate bond, formed from a lone pair on the oxygen atom of water",
      "Water's oxygen atom donates one of its lone pairs to the incoming H+ ion, forming a coordinate bond and producing the hydroxonium ion, H3O+."),
  _q("Metallic bonding can be described as",
      ["a lattice of positive metal ions held together by a 'sea' of delocalised (mobile) electrons", "the transfer of electrons between two metal atoms", "the sharing of one pair of electrons between two metal atoms", "hydrogen bonding between adjacent metal atoms"], "a lattice of positive metal ions held together by a 'sea' of delocalised (mobile) electrons",
      "In metals, valence electrons are delocalised and free to move throughout the lattice of positive ion cores, explaining metals' electrical conductivity and malleability."),
  _q("Which of the following is an example of an intermolecular force, rather than a bond within a molecule?",
      ["Van der Waals forces between molecules", "A covalent bond between two hydrogen atoms", "An ionic bond in sodium chloride", "A metallic bond in copper"], "Van der Waals forces between molecules",
      "Van der Waals forces are weak, temporary attractions between separate molecules, distinct from the strong intramolecular covalent, ionic, or metallic bonds holding atoms together within a molecule or lattice."),
  _q("Dipole-dipole forces of attraction occur between molecules that",
      ["are polar, having a permanent separation of positive and negative charge", "are completely non-polar", "have no electrons at all", "only exist in the gaseous state"], "are polar, having a permanent separation of positive and negative charge",
      "Polar molecules possess a permanent dipole (uneven charge distribution), and the positive end of one molecule attracts the negative end of a neighbouring molecule."),
  _q("Hydrogen bonding is best described as",
      ["a relatively strong intermolecular attraction between a hydrogen atom bonded to a highly electronegative atom (N, O, F) and a lone pair on another such atom nearby", "an ordinary covalent bond found only in the hydrogen molecule", "an ionic bond involving a free hydrogen ion", "a type of metallic bond"], "a relatively strong intermolecular attraction between a hydrogen atom bonded to a highly electronegative atom (N, O, F) and a lone pair on another such atom nearby",
      "Hydrogen bonds arise when hydrogen covalently bonded to N, O, or F is strongly attracted to a lone pair on a nearby electronegative atom, a stronger intermolecular force than ordinary van der Waals attractions."),
  _q("Water has an unusually high boiling point compared to other similarly sized molecules mainly because of",
      ["extensive hydrogen bonding between water molecules", "strong metallic bonding between molecules", "weak van der Waals forces only", "the absence of any intermolecular forces"], "extensive hydrogen bonding between water molecules",
      "Each water molecule can form multiple hydrogen bonds with neighbouring molecules, requiring significantly more energy to separate them and vaporise the liquid than would otherwise be expected."),
  _q("Which type of bond is present in common table salt, sodium chloride (NaCl)?",
      ["Ionic (electrovalent) bond", "Covalent bond", "Coordinate bond", "Metallic bond"], "Ionic (electrovalent) bond",
      "Sodium (a metal) transfers an electron to chlorine (a non-metal), forming Na+ and Cl- ions held together by strong electrostatic (ionic) attraction in a crystal lattice."),
  _q("Which of the following best explains why noble gases like argon exist as monatomic gases with very weak intermolecular forces?",
      ["They have only weak, instantaneous van der Waals forces between their atoms, and no permanent dipole", "They form strong covalent bonds between atoms", "They readily form ionic lattices", "They possess strong hydrogen bonding"], "They have only weak, instantaneous van der Waals forces between their atoms, and no permanent dipole",
      "Noble gas atoms have complete outer shells and do not bond chemically with each other; only weak, temporary van der Waals forces exist between their atoms, giving them low boiling points."),
  _q("The overlap of atomic orbitals to share electron density between two non-metal atoms describes",
      ["covalent bonding", "ionic bonding", "metallic bonding", "hydrogen bonding only"], "covalent bonding",
      "Covalent bonding involves the overlap of atomic orbitals from two atoms (usually non-metals), allowing shared electron density to hold the atoms together."),
];

final _stoichiometry = [
  _q("A chemical equation is said to be balanced when",
      ["the number of atoms of each element is equal on both sides of the equation", "the number of molecules is equal on both sides", "only the number of moles of gas is equal on both sides", "the total mass of reactants is greater than that of products"], "the number of atoms of each element is equal on both sides of the equation",
      "Balancing obeys the Law of Conservation of Mass: since atoms are neither created nor destroyed in a chemical reaction, each element must appear in equal amounts on both sides."),
  _q("The empirical formula of a compound shows",
      ["the simplest whole-number ratio of atoms of each element present", "the actual number of atoms of each element in one molecule", "only the total number of atoms present", "the physical state of the compound"], "the simplest whole-number ratio of atoms of each element present",
      "Unlike the molecular formula, which gives the actual number of atoms in a molecule, the empirical formula only expresses the smallest whole-number ratio of the elements."),
  _q("A compound has the empirical formula CH2O and a relative molecular mass of 180. What is its molecular formula? (C = 12, H = 1, O = 16)",
      ["C6H12O6", "C3H6O3", "C2H4O2", "CH2O"], "C6H12O6",
      "Empirical formula mass = 12 + 2(1) + 16 = 30. Multiplying factor = 180/30 = 6, so the molecular formula is (CH2O) x 6 = C6H12O6."),
  _q("The Law of Conservation of Mass states that",
      ["mass is neither created nor destroyed in a chemical reaction, so the total mass of reactants equals the total mass of products", "the mass of a compound depends only on the mass of one of its elements", "reacting masses are always in a 1:1 ratio", "mass increases during every chemical reaction"], "mass is neither created nor destroyed in a chemical reaction, so the total mass of reactants equals the total mass of products",
      "This fundamental law, verified experimentally by Lavoisier, underlies the balancing of chemical equations, since matter is simply rearranged, not created or destroyed."),
  _q("The Law of Definite Proportions states that",
      ["a pure chemical compound always contains the same elements combined in a fixed ratio by mass, regardless of its source", "the volume of a gas is proportional to its number of moles", "elements combine in variable, unpredictable ratios", "reacting masses depend on temperature"], "a pure chemical compound always contains the same elements combined in a fixed ratio by mass, regardless of its source",
      "Also called Proust's Law, this states that any given pure compound (e.g., water, H2O) always has the same fixed mass ratio of its constituent elements."),
  _q("Carbon forms two oxides, CO and CO2. For a fixed mass of carbon, the masses of oxygen combining with it in CO2 and CO are in the ratio",
      ["2:1, illustrating the Law of Multiple Proportions", "1:1, illustrating the Law of Definite Proportions", "3:1", "4:1"], "2:1, illustrating the Law of Multiple Proportions",
      "For a fixed mass of carbon, CO2 contains twice as much combined oxygen as CO, and this simple whole-number ratio (2:1) illustrates the Law of Multiple Proportions."),
  _q("Gay-Lussac's Law of combining volumes states that",
      ["gases react in simple whole-number ratios by volume, under the same conditions of temperature and pressure", "gases react in a fixed ratio by mass only", "the volume of a gas is inversely proportional to pressure", "equal masses of any two gases occupy equal volumes"], "gases react in simple whole-number ratios by volume, under the same conditions of temperature and pressure",
      "Gay-Lussac observed that when gases react, the volumes of reactants and gaseous products (at the same temperature and pressure) are always in simple whole-number ratios."),
  _q("One mole of any substance contains how many elementary particles (atoms, molecules, or ions)?",
      ["6.02 x 10^23 (Avogadro's number)", "22.4 x 10^23", "1.0 x 10^23", "3.01 x 10^23"], "6.02 x 10^23 (Avogadro's number)",
      "Avogadro's number, approximately 6.02 x 10^23, defines the number of particles in exactly one mole of any substance."),
  _q("What is the molar mass of Na2CO3? (Na = 23, C = 12, O = 16)",
      ["106 g/mol", "84 g/mol", "90 g/mol", "62 g/mol"], "106 g/mol",
      "Na2CO3 molar mass = (2 x 23) + 12 + (3 x 16) = 46 + 12 + 48 = 106 g/mol."),
  _q("How many moles are present in 22 g of CO2? (C = 12, O = 16)",
      ["0.5 mole", "1.0 mole", "0.25 mole", "2.0 moles"], "0.5 mole",
      "Molar mass of CO2 = 12 + (2 x 16) = 44 g/mol. Moles = mass/molar mass = 22/44 = 0.5 mole."),
  _q("What volume does 0.25 mole of a gas occupy at standard temperature and pressure (s.t.p.), given molar volume = 22.4 dm3?",
      ["5.6 dm3", "22.4 dm3", "11.2 dm3", "2.24 dm3"], "5.6 dm3",
      "Volume = number of moles x molar volume = 0.25 x 22.4 = 5.6 dm3."),
  _q("How many moles of hydrogen atoms are present in 2 moles of H2SO4?",
      ["4 moles", "2 moles", "1 mole", "8 moles"], "4 moles",
      "Each molecule of H2SO4 contains 2 hydrogen atoms, so 2 moles of H2SO4 contain 2 x 2 = 4 moles of hydrogen atoms."),
  _q("What is the concentration, in g/dm3, of a solution containing 20 g of solute dissolved to make 2 dm3 of solution?",
      ["10 g/dm3", "40 g/dm3", "20 g/dm3", "5 g/dm3"], "10 g/dm3",
      "Concentration (g/dm3) = mass of solute (g) / volume of solution (dm3) = 20/2 = 10 g/dm3."),
  _q("What is the concentration, in mol/dm3, of a solution formed by dissolving 0.5 mole of NaOH to make 250 cm3 of solution?",
      ["2.0 mol/dm3", "0.5 mol/dm3", "0.125 mol/dm3", "1.0 mol/dm3"], "2.0 mol/dm3",
      "Convert 250 cm3 to dm3: 250/1000 = 0.25 dm3. Concentration = moles/volume = 0.5/0.25 = 2.0 mol/dm3."),
  _q("Using the dilution formula C1V1 = C2V2, what volume of water must be added to 100 cm3 of a 2.0 mol/dm3 solution to dilute it to 0.5 mol/dm3?",
      ["300 cm3 of water (final volume 400 cm3)", "100 cm3 of water", "200 cm3 of water", "50 cm3 of water"], "300 cm3 of water (final volume 400 cm3)",
      "C1V1 = C2V2: 2.0 x 100 = 0.5 x V2, so V2 = 200/0.5 = 400 cm3 total final volume. Water added = 400 - 100 = 300 cm3."),
  _q("What mass of sodium hydroxide (NaOH) is needed to prepare 500 cm3 of a 0.2 mol/dm3 solution? (Na = 23, O = 16, H = 1)",
      ["4 g", "8 g", "2 g", "40 g"], "4 g",
      "Moles required = concentration x volume = 0.2 x 0.5 = 0.1 mole. Molar mass of NaOH = 23 + 16 + 1 = 40 g/mol. Mass = 0.1 x 40 = 4 g."),
  _q("A 500 cm3 solution of HCl is prepared by diluting 50 cm3 of a 4.0 mol/dm3 stock solution with water. What is the concentration of the diluted solution?",
      ["0.4 mol/dm3", "4.0 mol/dm3", "0.04 mol/dm3", "40 mol/dm3"], "0.4 mol/dm3",
      "Using C1V1 = C2V2: 4.0 x 50 = C2 x 500, so C2 = 200/500 = 0.4 mol/dm3."),
  _q("What is the empirical formula of a compound containing 40% carbon, 6.7% hydrogen, and 53.3% oxygen by mass? (C = 12, H = 1, O = 16)",
      ["CH2O", "C2H4O2", "CHO", "C2H6O"], "CH2O",
      "Moles: C = 40/12 = 3.33, H = 6.7/1 = 6.7, O = 53.3/16 = 3.33. Dividing each by the smallest value (3.33) gives a ratio of C:H:O = 1:2:1, so the empirical formula is CH2O."),
];

final _statesOfMatter = [
  _q("According to the kinetic theory of matter, particles in a solid",
      ["vibrate about fixed positions in a regular, closely packed lattice", "move randomly and freely at high speed", "have no forces of attraction between them", "are far apart with negligible attraction"], "vibrate about fixed positions in a regular, closely packed lattice",
      "In solids, strong intermolecular forces hold particles in fixed positions within an ordered lattice; the particles can only vibrate in place, not move freely."),
  _q("Melting, according to kinetic theory, occurs when particles in a solid",
      ["gain enough energy to overcome some of the forces holding them in fixed positions, allowing them to move past one another", "lose all their kinetic energy completely", "become completely stationary", "gain no additional energy at all"], "gain enough energy to overcome some of the forces holding them in fixed positions, allowing them to move past one another",
      "As a solid is heated, particles vibrate more vigorously until they gain enough energy to break free of their fixed lattice positions and slide past each other, becoming a liquid."),
  _q("Evaporation differs from boiling in that evaporation",
      ["occurs at the surface of a liquid at any temperature below the boiling point", "occurs only at the liquid's boiling point", "occurs throughout the whole liquid, not just the surface", "always requires the liquid to be heated to 100 degC"], "occurs at the surface of a liquid at any temperature below the boiling point",
      "Evaporation is a surface phenomenon in which the most energetic particles escape into the gas phase at temperatures below the boiling point, unlike boiling, which occurs throughout the liquid at a fixed temperature."),
  _q("Boiling occurs when",
      ["the vapour pressure of a liquid equals the surrounding atmospheric pressure, so bubbles of vapour form throughout the liquid", "particles only escape from the surface of a liquid", "a liquid is cooled below its freezing point", "a gas is compressed into a liquid"], "the vapour pressure of a liquid equals the surrounding atmospheric pressure, so bubbles of vapour form throughout the liquid",
      "Unlike evaporation, boiling happens at one specific temperature where the liquid's vapour pressure matches the external pressure, allowing bubbles of vapour to form within the bulk liquid."),
  _q("Sublimation is the process by which a substance changes directly from",
      ["solid to gas (or gas to solid) without passing through the liquid state", "liquid to gas only", "solid to liquid only", "gas to liquid only"], "solid to gas (or gas to solid) without passing through the liquid state",
      "Substances like iodine and solid carbon dioxide (dry ice) sublime directly between the solid and gaseous states, bypassing the liquid phase entirely under normal conditions."),
  _q("Boyle's Law states that, at constant temperature, the volume of a fixed mass of gas is",
      ["inversely proportional to its pressure", "directly proportional to its pressure", "directly proportional to its absolute temperature", "unaffected by pressure changes"], "inversely proportional to its pressure",
      "Boyle's Law: P1V1 = P2V2 at constant temperature, meaning that as pressure on a gas increases, its volume decreases proportionally."),
  _q("A gas occupies 600 cm3 at a pressure of 100 kPa. What is its new volume if the pressure increases to 200 kPa at constant temperature?",
      ["300 cm3", "600 cm3", "1200 cm3", "150 cm3"], "300 cm3",
      "By Boyle's Law, P1V1 = P2V2: 100 x 600 = 200 x V2, so V2 = 60000/200 = 300 cm3."),
  _q("Charles's Law states that, at constant pressure, the volume of a fixed mass of gas is",
      ["directly proportional to its absolute temperature", "inversely proportional to its absolute temperature", "directly proportional to its pressure", "independent of temperature"], "directly proportional to its absolute temperature",
      "Charles's Law: V1/T1 = V2/T2 at constant pressure, so gas volume increases proportionally with absolute (Kelvin) temperature."),
  _q("A gas has a volume of 300 cm3 at 27 degC. What volume will it occupy at 127 degC, assuming pressure remains constant?",
      ["400 cm3", "300 cm3", "200 cm3", "350 cm3"], "400 cm3",
      "Convert to Kelvin: 27 degC = 300 K, 127 degC = 400 K. By Charles's Law, V1/T1 = V2/T2: 300/300 = V2/400, so V2 = 400 cm3."),
  _q("The general gas equation combines Boyle's and Charles's Laws as",
      ["P1V1/T1 = P2V2/T2", "P1V1 = P2V2 only", "V1/T1 = V2/T2 only", "P1/T1 = P2/T2 only"], "P1V1/T1 = P2V2/T2",
      "The general (combined) gas equation merges the pressure-volume and volume-temperature relationships into a single expression relating all three variables for a fixed mass of gas."),
  _q("A gas occupies 400 cm3 at 100 kPa and 300 K. What volume will it occupy at 200 kPa and 450 K?",
      ["300 cm3", "400 cm3", "600 cm3", "200 cm3"], "300 cm3",
      "Using P1V1/T1 = P2V2/T2: (100 x 400)/300 = (200 x V2)/450. So 40000/300 = 200V2/450, giving 133.33 = 200V2/450, so V2 = 133.33 x 450/200 = 300 cm3."),
  _q("Dalton's Law of Partial Pressures states that the total pressure exerted by a mixture of non-reacting gases equals",
      ["the sum of the partial pressures each gas would exert alone in the same container", "the average of the individual partial pressures", "the partial pressure of the lightest gas only", "the product of all the partial pressures"], "the sum of the partial pressures each gas would exert alone in the same container",
      "Dalton's Law states that in a mixture of gases that do not react chemically, the total pressure is simply the sum of each gas's individual (partial) pressure."),
  _q("A container holds a mixture of two gases with partial pressures of 30 kPa and 50 kPa. What is the total pressure in the container?",
      ["80 kPa", "20 kPa", "1500 kPa", "40 kPa"], "80 kPa",
      "By Dalton's Law, total pressure = sum of partial pressures = 30 + 50 = 80 kPa."),
  _q("Graham's Law of diffusion states that the rate of diffusion of a gas is",
      ["inversely proportional to the square root of its molar mass (or density)", "directly proportional to its molar mass", "independent of its molar mass", "directly proportional to the square root of its molar mass"], "inversely proportional to the square root of its molar mass (or density)",
      "Graham's Law shows that lighter gases diffuse faster than heavier ones, since diffusion rate is inversely proportional to the square root of molar mass."),
  _q("Using Graham's Law, if hydrogen (M = 2) and carbon dioxide (M = 44) diffuse under the same conditions, hydrogen diffuses approximately how many times faster?",
      ["4.7 times faster", "22 times faster", "2 times faster", "44 times faster"], "4.7 times faster",
      "Rate ratio = sqrt(M_CO2/M_H2) = sqrt(44/2) = sqrt(22) = 4.69, approximately 4.7 times faster for hydrogen."),
  _q("A crystalline solid differs from an amorphous solid in that a crystalline solid has",
      ["a regular, orderly, repeating arrangement of particles and a sharp melting point", "no definite geometric structure and melts over a range of temperatures", "particles that move freely past one another", "no definite shape at all"], "a regular, orderly, repeating arrangement of particles and a sharp melting point",
      "Crystalline solids (like sodium chloride) have a highly ordered lattice structure and melt sharply, whereas amorphous solids (like glass) lack long-range order and soften gradually over a range of temperatures."),
  _q("Diamond and graphite are both allotropes of carbon, but diamond is extremely hard while graphite is soft and slippery mainly because",
      ["diamond has a rigid three-dimensional tetrahedral network of covalent bonds, while graphite has weakly bonded layers that can slide over one another", "graphite has stronger covalent bonds than diamond", "diamond contains free-moving delocalised electrons throughout its structure", "graphite is not a form of carbon at all"], "diamond has a rigid three-dimensional tetrahedral network of covalent bonds, while graphite has weakly bonded layers that can slide over one another",
      "In diamond, each carbon atom forms four strong covalent bonds in a rigid 3D lattice, giving great hardness; in graphite, carbon atoms form flat hexagonal layers with only weak van der Waals forces between layers, allowing them to slide, making graphite soft."),
  _q("Graphite conducts electricity, unlike diamond, because graphite",
      ["has one delocalised electron per carbon atom that is free to move within its layered structure", "has no covalent bonds at all", "is a giant ionic lattice", "has a tetrahedral bonding arrangement like diamond"], "has one delocalised electron per carbon atom that is free to move within its layered structure",
      "Each carbon atom in graphite is only bonded to three others, leaving one electron delocalised within the layers, allowing it to conduct electricity, unlike diamond, where all four electrons are used in localised covalent bonds."),
];
