import "../quiz_question.dart";

const _subject = "Foods and Nutrition";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// WAEC Foods and Nutrition question bank covering the full syllabus:
/// Nutrition Science & Dietary Planning, Food Science/Commodities &
/// Preservation, and Kitchen Operations & Culinary Methods.
List<QuizQuestion> buildWaecFoodsAndNutritionQuestions() {
  return [
    ..._nutritionScienceAndDietaryPlanning,
    ..._foodScienceCommoditiesAndPreservation,
    ..._kitchenOperationsAndCulinaryMethods,
  ];
}

final _nutritionScienceAndDietaryPlanning = [
  _q("The nutrient class made up of carbon, hydrogen, and oxygen, serving as the body's primary and quickest source of energy, is",
      ["carbohydrates", "proteins", "fats", "vitamins"], "carbohydrates",
      "Carbohydrates, composed of carbon, hydrogen, and oxygen, are the body's main and most readily available source of energy."),
  _q("The nutrient class primarily responsible for growth, repair, and maintenance of body tissues is",
      ["proteins", "carbohydrates", "fats", "water"], "proteins",
      "Proteins provide the amino acids essential for building, repairing, and maintaining body tissues, including muscles and organs."),
  _q("The nutrient class that provides the most concentrated source of energy per gram, and also supplies essential fatty acids, is",
      ["fats and lipids", "carbohydrates", "proteins", "minerals"], "fats and lipids",
      "Fats and lipids provide over twice the energy per gram compared to carbohydrates or proteins, and also supply essential fatty acids."),
  _q("A deficiency disease caused by insufficient dietary protein, especially common in children, characterised by swelling (oedema) and stunted growth, is called",
      ["kwashiorkor", "scurvy", "rickets", "beriberi"], "kwashiorkor",
      "Kwashiorkor results from severe protein deficiency, often marked by oedema (swelling), a distended belly, and growth impairment, primarily in children."),
  _q("A deficiency disease caused by insufficient vitamin C, characterised by bleeding gums and poor wound healing, is called",
      ["scurvy", "kwashiorkor", "rickets", "beriberi"], "scurvy",
      "Scurvy results from prolonged vitamin C deficiency, causing symptoms such as bleeding gums, joint pain, and poor wound healing."),
  _q("A deficiency disease caused by insufficient vitamin D (or calcium), leading to soft, weak, and deformed bones in children, is called",
      ["rickets", "scurvy", "kwashiorkor", "beriberi"], "rickets",
      "Rickets results from vitamin D deficiency, impairing calcium absorption and leading to soft, weak bones in growing children."),
  _q("A deficiency disease caused by insufficient vitamin B1 (thiamine), affecting the nervous system and heart, is called",
      ["beriberi", "scurvy", "rickets", "kwashiorkor"], "beriberi",
      "Beriberi results from thiamine (vitamin B1) deficiency, affecting the nervous and cardiovascular systems."),
  _q("Vitamins that dissolve in water and are generally not stored in significant amounts in the body, requiring regular dietary intake, include",
      ["vitamin C and the B-complex vitamins", "vitamin A and vitamin D", "vitamin E and vitamin K", "all vitamins equally"], "vitamin C and the B-complex vitamins",
      "Water-soluble vitamins, such as vitamin C and the B-complex group, are not significantly stored in the body and must be consumed regularly."),
  _q("Vitamins that dissolve in fat and can be stored in the body's fatty tissues for longer periods include",
      ["vitamins A, D, E, and K", "vitamin C and B1 only", "vitamin B12 and folate only", "all vitamins equally"], "vitamins A, D, E, and K",
      "Fat-soluble vitamins (A, D, E, K) can be stored in the body's fat tissues, unlike water-soluble vitamins which require more regular intake."),
  _q("Minerals required by the body in relatively large amounts, such as calcium and phosphorus, are classified as",
      ["macro (major) minerals", "trace elements", "water-soluble vitamins", "fat-soluble vitamins"], "macro (major) minerals",
      "Macro (major) minerals, including calcium, phosphorus, and sodium, are needed by the body in comparatively larger amounts."),
  _q("Minerals required by the body only in very small amounts, such as iron and zinc, are classified as",
      ["trace elements (micro minerals)", "macro minerals", "water-soluble vitamins", "fat-soluble vitamins"], "trace elements (micro minerals)",
      "Trace elements (micro minerals), such as iron, zinc, and iodine, are essential but required only in small quantities."),
  _q("Water is considered an essential nutrient mainly because it",
      ["regulates body temperature, transports nutrients, and supports many metabolic processes", "provides significant dietary energy (calories)", "builds muscle tissue directly", "is only needed by the very young"], "regulates body temperature, transports nutrients, and supports many metabolic processes",
      "Water plays vital roles in temperature regulation, nutrient transport, waste removal, and many essential metabolic processes, despite providing no calories itself."),
  _q("The breakdown of food through physical actions such as chewing and the churning of the stomach is called",
      ["mechanical digestion", "chemical digestion", "absorption", "metabolism"], "mechanical digestion",
      "Mechanical digestion physically breaks food into smaller pieces through actions like chewing and stomach churning, increasing surface area for chemical digestion."),
  _q("The breakdown of food through the action of enzymes and digestive juices into simpler chemical substances is called",
      ["chemical digestion", "mechanical digestion", "absorption", "excretion"], "chemical digestion",
      "Chemical digestion uses enzymes and other digestive secretions to break complex food molecules down into simpler, absorbable substances."),
  _q("Enzymes that break down starches (carbohydrates) into simpler sugars are called",
      ["amylases", "proteases", "lipases", "vitamins"], "amylases",
      "Amylases are digestive enzymes that specifically break down starches into simpler sugar molecules."),
  _q("Enzymes that break down proteins into smaller peptides and amino acids are called",
      ["proteases", "amylases", "lipases", "minerals"], "proteases",
      "Proteases are digestive enzymes that break down proteins into smaller peptide chains and individual amino acids."),
  _q("Enzymes that break down fats into fatty acids and glycerol are called",
      ["lipases", "amylases", "proteases", "carbohydrases only"], "lipases",
      "Lipases are digestive enzymes specifically responsible for breaking down fats into fatty acids and glycerol."),
  _q("The process by which digested nutrients pass through the wall of the small intestine into the bloodstream is called",
      ["absorption", "digestion", "excretion", "respiration"], "absorption",
      "Absorption is the process by which broken-down nutrients move across the intestinal wall into the bloodstream for distribution throughout the body."),
  _q("The sum of all chemical processes occurring within the body to maintain life, including building up and breaking down substances, is called",
      ["metabolism", "digestion", "absorption", "excretion"], "metabolism",
      "Metabolism encompasses all the chemical reactions occurring within the body, including both the breakdown (catabolism) and building up (anabolism) of substances."),
  _q("A dietary plan for infants generally emphasises",
      ["easily digestible, nutrient-dense foods appropriate to their developmental stage", "large portions of tough, fibrous, hard-to-chew foods", "highly spiced adult meals from birth", "complete avoidance of any dietary fat"], "easily digestible, nutrient-dense foods appropriate to their developmental stage",
      "Infant diets prioritise easily digestible, nutrient-dense foods suited to their developing digestive systems, gradually introducing solids appropriate to age."),
  _q("A dietary plan for adolescents generally requires",
      ["increased energy, protein, and mineral intake to support rapid growth and development", "significantly reduced calorie and nutrient intake compared to younger children", "complete avoidance of all dairy products", "identical nutrient requirements to elderly individuals"], "increased energy, protein, and mineral intake to support rapid growth and development",
      "Adolescents undergoing rapid growth generally require increased energy, protein, and mineral intake compared to younger children."),
  _q("A dietary plan for pregnant and lactating women generally requires increased intake of",
      ["protein, iron, calcium, and folic acid to support foetal/infant development and maternal health", "only carbohydrates, with no other nutrient adjustments", "significantly reduced overall calorie intake", "no dietary changes at all compared to before pregnancy"], "protein, iron, calcium, and folic acid to support foetal/infant development and maternal health",
      "Pregnant and lactating women require increased protein, iron, calcium, and folic acid to support foetal or infant development and their own health."),
  _q("A dietary plan for manual workers engaged in heavy physical labour generally requires",
      ["higher energy (calorie) intake to match increased physical exertion", "significantly reduced energy intake compared to sedentary individuals", "complete avoidance of carbohydrates", "identical nutrient needs to infants"], "higher energy (calorie) intake to match increased physical exertion",
      "Manual workers performing heavy physical labour require higher energy intake to replace the calories expended through their strenuous work."),
  _q("A dietary plan for the elderly generally emphasises",
      ["nutrient-dense, easily digestible foods, often with reduced calorie needs due to lower activity levels", "very high calorie, high-fat foods regardless of activity level", "complete avoidance of protein entirely", "identical dietary needs to adolescents"], "nutrient-dense, easily digestible foods, often with reduced calorie needs due to lower activity levels",
      "Elderly individuals often need nutrient-dense, easily digestible foods, with calorie needs generally reduced due to lower activity levels and metabolism."),
  _q("A therapeutic diet for a person with diabetes generally focuses on",
      ["controlling carbohydrate intake and choosing foods with a lower impact on blood sugar levels", "maximising sugar and refined carbohydrate intake", "eliminating all forms of dietary fibre", "eating only raw meat"], "controlling carbohydrate intake and choosing foods with a lower impact on blood sugar levels",
      "Diabetic diets typically focus on managing carbohydrate intake and choosing foods that have a more moderate effect on blood glucose levels."),
  _q("A therapeutic diet for a person with hypertension (high blood pressure) generally focuses on",
      ["reducing salt (sodium) intake", "maximising salt intake for flavour", "eliminating all vegetables from the diet", "consuming only fried foods"], "reducing salt (sodium) intake",
      "Hypertension management typically involves reducing dietary sodium (salt) intake, which can help control blood pressure levels."),
  _q("A diet planned for a convalescent (someone recovering from illness) generally emphasises",
      ["easily digestible, nutrient-rich foods to support recovery", "very heavy, hard-to-digest meals", "complete fasting until fully recovered", "identical requirements to a healthy manual labourer"], "easily digestible, nutrient-rich foods to support recovery",
      "Convalescent diets typically favour easily digestible, nutrient-rich foods that support the body's recovery process without overburdening a weakened digestive system."),
  _q("A balanced diet is best described as one that",
      ["provides all essential nutrients in the correct proportions needed for good health", "consists of a single food type eaten repeatedly", "contains only carbohydrates and no other nutrients", "excludes all fats and oils entirely"], "provides all essential nutrients in the correct proportions needed for good health",
      "A balanced diet supplies all essential nutrients (carbohydrates, proteins, fats, vitamins, minerals, water) in appropriate proportions to maintain good health."),
  _q("Proteins are made up of smaller building-block units called",
      ["amino acids", "fatty acids", "monosaccharides", "glycerol molecules"], "amino acids",
      "Proteins are composed of chains of amino acids, which the body links together in specific sequences to build various proteins."),
  _q("An amino acid that the body cannot synthesise itself and must therefore obtain from the diet is called an",
      ["essential amino acid", "non-essential amino acid", "essential fatty acid only", "essential vitamin only"], "essential amino acid",
      "Essential amino acids cannot be produced by the body and must be obtained through dietary protein sources."),
  _q("Fats and oils are composed of fatty acids combined with a molecule of",
      ["glycerol", "glucose", "amino acid", "starch"], "glycerol",
      "Fats and oils (triglycerides) are formed from three fatty acid chains attached to a single glycerol molecule."),
  _q("Carbohydrates are broadly classified into simple sugars and more complex forms known as",
      ["starches (polysaccharides)", "amino acids", "fatty acids", "minerals"], "starches (polysaccharides)",
      "Complex carbohydrates, or polysaccharides such as starch, are made of many linked sugar units, unlike simple sugars (monosaccharides and disaccharides)."),
  _q("The mineral most closely associated with building and maintaining strong bones and teeth is",
      ["calcium", "iron", "iodine", "zinc"], "calcium",
      "Calcium is essential for building and maintaining strong bones and teeth, alongside supporting other bodily functions like muscle contraction."),
  _q("The mineral most closely associated with the formation of haemoglobin in red blood cells is",
      ["iron", "calcium", "iodine", "zinc"], "iron",
      "Iron is a key component of haemoglobin, the protein in red blood cells responsible for transporting oxygen throughout the body."),
  _q("The mineral essential for normal thyroid gland function, with deficiency leading to goitre, is",
      ["iodine", "calcium", "iron", "zinc"], "iodine",
      "Iodine is essential for the thyroid gland's production of hormones; deficiency can result in an enlarged thyroid gland, known as goitre."),
];

final _foodScienceCommoditiesAndPreservation = [
  _q("Grain foods such as rice, maize, and wheat, which are important sources of carbohydrate, are classified as",
      ["cereals", "legumes", "roots and tubers", "flesh foods"], "cereals",
      "Cereals are grain crops, such as rice, maize, and wheat, providing significant amounts of dietary carbohydrate."),
  _q("Plant foods such as beans, peas, and lentils, notable for their relatively high protein content among plant foods, are classified as",
      ["legumes", "cereals", "roots and tubers", "flesh foods"], "legumes",
      "Legumes, including beans, peas, and lentils, are valued as plant sources of protein alongside carbohydrates."),
  _q("Starchy plant foods such as yam, cassava, and potato, which grow underground, are classified as",
      ["roots and tubers", "cereals", "legumes", "dairy products"], "roots and tubers",
      "Roots and tubers are underground starchy plant foods, including yam, cassava, and potato, primarily valued for their carbohydrate content."),
  _q("Meat, poultry, and fish, all valued primarily for their protein content, are collectively classified as",
      ["flesh foods", "dairy products", "cereals", "legumes"], "flesh foods",
      "Flesh foods, including meat, poultry, and fish, are animal-derived foods valued mainly for their high-quality protein content."),
  _q("Foods derived from milk, such as cheese, yoghurt, and butter, are classified as",
      ["dairy products", "flesh foods", "cereals", "legumes"], "dairy products",
      "Dairy products are derived from milk and are valued especially for their protein and calcium content."),
  _q("When selecting fresh fish for purchase, a key indicator of freshness is",
      ["bright, clear eyes and firm flesh that springs back when pressed", "dull, sunken eyes and soft, mushy flesh", "a strong ammonia-like odour", "discoloured, slimy skin"], "bright, clear eyes and firm flesh that springs back when pressed",
      "Fresh fish typically has bright, clear eyes and firm flesh, distinguishing it from stale fish, which shows dull eyes and soft, unresponsive flesh."),
  _q("Cereals should generally be stored in conditions that are",
      ["cool, dry, and well-ventilated to prevent mould growth and pest infestation", "warm and humid to encourage faster ripening", "completely airtight with high moisture content", "exposed to direct sunlight and rain"], "cool, dry, and well-ventilated to prevent mould growth and pest infestation",
      "Proper cereal storage in cool, dry, ventilated conditions helps prevent mould growth, insect infestation, and spoilage."),
  _q("The microorganisms most commonly responsible for causing food spoilage include",
      ["bacteria, yeasts, and moulds", "vitamins and minerals", "enzymes only, with no living organisms involved", "amino acids only"], "bacteria, yeasts, and moulds",
      "Bacteria, yeasts, and moulds are the primary microorganisms responsible for the spoilage and decomposition of food."),
  _q("Naturally occurring enzymes present within food can contribute to spoilage mainly by",
      ["continuing to break down the food's tissues and nutrients even after harvesting or slaughter", "actively killing harmful microorganisms present in the food", "preserving the food indefinitely without any other intervention", "having no effect on food quality over time"], "continuing to break down the food's tissues and nutrients even after harvesting or slaughter",
      "Enzymes naturally present in food continue their breakdown activity after harvesting or slaughter, contributing to spoilage if not controlled through preservation methods."),
  _q("A food preservation method that removes moisture from food to inhibit microbial growth is called",
      ["dehydration (drying)", "refrigeration", "canning", "smoking only"], "dehydration (drying)",
      "Dehydration removes the moisture microorganisms need to grow, extending the shelf life of the preserved food."),
  _q("A food preservation method that slows microbial growth and enzyme activity by storing food at low, above-freezing temperatures is called",
      ["refrigeration", "dehydration", "canning", "sterilization only"], "refrigeration",
      "Refrigeration slows (but does not stop) microbial growth and enzyme activity by keeping food at low, above-freezing temperatures."),
  _q("A food preservation method that stops microbial growth almost entirely by storing food at temperatures well below freezing is called",
      ["freezing", "refrigeration only", "pasteurization", "canning only"], "freezing",
      "Freezing preserves food by lowering its temperature well below the freezing point, effectively halting most microbial growth and slowing enzyme activity."),
  _q("A food preservation method that seals food in airtight containers and applies heat to destroy microorganisms is called",
      ["canning", "dehydration", "refrigeration", "chemical preservation only"], "canning",
      "Canning combines heat treatment with airtight sealing, destroying microorganisms and preventing recontamination for extended shelf life."),
  _q("A heat treatment process that destroys most harmful microorganisms in a liquid, such as milk, without fully sterilising it, is called",
      ["pasteurization", "sterilization", "canning only", "dehydration"], "pasteurization",
      "Pasteurization uses controlled heating to destroy most harmful microorganisms while preserving more of the food's quality than full sterilisation."),
  _q("A heat treatment process that destroys virtually all microorganisms, including their spores, is called",
      ["sterilization", "pasteurization", "refrigeration only", "dehydration"], "sterilization",
      "Sterilization uses higher heat and longer exposure than pasteurization to destroy nearly all microorganisms, including resistant spores."),
  _q("A food preservation method using substances such as salt, sugar, or specific chemical additives to inhibit microbial growth is called",
      ["chemical preservation", "canning only", "refrigeration only", "sterilization only"], "chemical preservation",
      "Chemical preservation uses substances like salt, sugar, vinegar, or approved additives to create conditions unfavourable for microbial growth."),
  _q("A traditional food preservation method that exposes food to smoke, both drying it and depositing preservative compounds, is called",
      ["smoking", "canning", "refrigeration", "sterilization only"], "smoking",
      "Smoking preserves food through a combination of drying and depositing antimicrobial compounds from the smoke onto the food's surface."),
  _q("The protein found in wheat flour that gives dough its elastic, stretchy structure, essential for bread making, is called",
      ["gluten", "starch", "cellulose", "casein"], "gluten",
      "Gluten, formed when wheat flour is mixed with water, provides the elastic structure that traps gas bubbles and gives bread its characteristic texture."),
  _q("A raising method that incorporates air into a mixture through vigorous physical action, such as whisking egg whites, is classified as",
      ["mechanical raising", "chemical raising", "biological raising", "no raising at all"], "mechanical raising",
      "Mechanical raising methods, such as whisking or creaming, incorporate air physically into a mixture, which expands during cooking to provide lift."),
  _q("A raising method that uses substances such as baking powder or bicarbonate of soda, which release gas through a chemical reaction, is classified as",
      ["chemical raising", "mechanical raising", "biological raising", "no raising at all"], "chemical raising",
      "Chemical raising agents, like baking powder and bicarbonate of soda, release carbon dioxide gas through chemical reactions, causing mixtures to rise."),
  _q("A raising method that relies on living yeast fermenting sugars and producing carbon dioxide gas is classified as",
      ["biological raising", "mechanical raising", "chemical raising", "no raising at all"], "biological raising",
      "Biological raising uses living yeast, which ferments sugars in the dough and produces carbon dioxide gas, causing the dough to rise."),
  _q("Fresh fruits and vegetables should generally be stored in conditions that",
      ["maintain appropriate cool temperatures and humidity to slow ripening and decay", "maximise warmth and dryness to speed up ripening", "involve tightly sealed, airless containers for all types", "expose them to continuous direct sunlight"], "maintain appropriate cool temperatures and humidity to slow ripening and decay",
      "Most fresh fruits and vegetables keep best in cool, appropriately humid conditions that slow the natural processes of ripening and decay."),
  _q("Fats and oils used in cooking should generally be stored away from",
      ["light, heat, and air, which can cause them to become rancid", "cool, dark conditions, which help preserve them", "airtight containers, which best preserve freshness", "moderate room temperature storage"], "light, heat, and air, which can cause them to become rancid",
      "Exposure to light, heat, and air accelerates the oxidation of fats and oils, causing them to become rancid; proper storage minimises this exposure."),
  _q("A common structural feature of cereal grains is their outer protective layer, known as the",
      ["bran", "endosperm only", "germ only", "husk removed entirely before any processing"], "bran",
      "The bran is the tough outer protective layer of a cereal grain, rich in fibre, surrounding the starchy endosperm and nutrient-rich germ."),
  _q("The nutrient-rich inner part of a cereal grain, often removed during refined milling, is called the",
      ["germ", "bran only", "endosperm only", "husk"], "germ",
      "The germ is the nutrient-dense embryo of the grain, often removed along with the bran during the refining process, reducing the nutritional value of refined grains."),
  _q("A major reason meat, poultry, and fish require careful, prompt refrigeration after purchase is that they are",
      ["highly perishable and susceptible to rapid microbial spoilage", "naturally resistant to all microbial spoilage", "the only foods that never require refrigeration", "unaffected by temperature under any circumstances"], "highly perishable and susceptible to rapid microbial spoilage",
      "Flesh foods are highly perishable, providing an ideal environment for microbial growth, making prompt and proper refrigeration essential to prevent spoilage."),
  _q("The main purpose of blanching vegetables briefly in boiling water before freezing them is to",
      ["destroy enzymes that would otherwise continue to degrade quality during frozen storage", "fully cook the vegetables before freezing", "add extra moisture content to the vegetables", "remove all nutrients before freezing"], "destroy enzymes that would otherwise continue to degrade quality during frozen storage",
      "Blanching briefly destroys enzymes that would otherwise continue breaking down the vegetable's quality, colour, and texture during frozen storage."),
  _q("A key sign that canned food may be unsafe to eat, indicating possible bacterial contamination, is",
      ["a bulging or swollen can lid", "a can that is cool to the touch", "a can with a clear, undamaged label", "a can stored in a cool, dry cupboard"], "a bulging or swollen can lid",
      "A bulging or swollen can lid can indicate gas production from bacterial contamination inside, signalling that the contents may be unsafe to consume."),
  _q("Wheat flour used for bread-making generally requires a",
      ["higher gluten (protein) content, to provide the necessary elastic structure", "lower gluten content than flour used for delicate cakes", "complete absence of gluten", "identical properties to cornflour"], "higher gluten (protein) content, to provide the necessary elastic structure",
      "Bread-making flour ('strong' flour) has a higher gluten content, providing the elastic structure needed to trap gas and support a well-risen loaf."),
  _q("Cake flour generally has a",
      ["lower gluten (protein) content than bread flour, producing a softer, more tender texture", "higher gluten content than bread flour", "identical gluten content to bread flour", "no starch content at all"], "lower gluten (protein) content than bread flour, producing a softer, more tender texture",
      "Cake ('soft') flour has a lower gluten content than bread flour, helping to produce the lighter, more tender texture desired in cakes."),
];

final _kitchenOperationsAndCulinaryMethods = [
  _q("An efficient kitchen layout generally organises work into distinct zones for",
      ["storage, preparation, and cooking, to allow a smooth workflow", "a single combined zone with no logical separation", "cooking only, with storage and preparation done elsewhere entirely", "decoration purposes only, with no practical function"], "storage, preparation, and cooking, to allow a smooth workflow",
      "A well-planned kitchen separates storage, preparation, and cooking zones, supporting an efficient, logical workflow from raw ingredients to finished dishes."),
  _q("A key kitchen safety practice to prevent burns and scalds is to",
      ["turn pot handles inward and use dry oven gloves when handling hot items", "leave pot handles extending outward over the edge of the cooker", "handle hot pans with wet cloths", "ignore the use of any protective equipment"], "turn pot handles inward and use dry oven gloves when handling hot items",
      "Turning pot handles inward reduces the risk of accidental knocks, while dry oven gloves protect hands from burns when handling hot cookware."),
  _q("A key kitchen safety practice to prevent slips and falls is to",
      ["clean up spills immediately and keep floors dry", "leave spilled liquids on the floor until the end of the day", "encourage running within the kitchen area", "keep the kitchen floor cluttered with equipment"], "clean up spills immediately and keep floors dry",
      "Promptly cleaning spills and keeping floors dry significantly reduces the risk of slips and falls in a busy kitchen environment."),
  _q("Good kitchen hygiene practices generally include",
      ["regular handwashing and keeping food preparation surfaces clean", "handling raw and cooked foods with the same unwashed utensils", "storing raw meat above ready-to-eat foods in the refrigerator", "ignoring expiry dates on perishable items"], "regular handwashing and keeping food preparation surfaces clean",
      "Regular handwashing and clean preparation surfaces are fundamental hygiene practices that help prevent cross-contamination and foodborne illness."),
  _q("A cooking method that involves cooking food fully submerged in liquid at a rolling temperature of 100°C is called",
      ["boiling", "steaming", "roasting", "grilling"], "boiling",
      "Boiling cooks food fully immersed in liquid heated to its boiling point (100°C at sea level)."),
  _q("A cooking method that involves slow cooking food in a small amount of liquid over a long period, tenderising tougher cuts, is called",
      ["stewing", "boiling", "roasting", "grilling"], "stewing",
      "Stewing slowly cooks food in a smaller amount of liquid over an extended time, effectively tenderising tougher ingredients."),
  _q("A cooking method that involves gently cooking food in liquid kept just below boiling point, often used for delicate items like eggs or fish, is called",
      ["poaching", "boiling", "roasting", "frying"], "poaching",
      "Poaching uses gently simmering liquid kept below boiling point, suitable for delicate foods that would break apart under a rolling boil."),
  _q("A cooking method that involves cooking food using the vapour produced by boiling water, without direct contact with the liquid, is called",
      ["steaming", "boiling", "poaching", "grilling"], "steaming",
      "Steaming cooks food using hot water vapour, keeping it out of direct contact with the boiling liquid itself."),
  _q("A dry cooking method that cooks food using hot, dry air within an enclosed oven is called",
      ["baking", "boiling", "steaming", "stewing"], "baking",
      "Baking uses hot, dry air circulating within an enclosed oven to cook food, commonly used for bread, cakes, and pastries."),
  _q("A dry cooking method traditionally used to cook larger cuts of meat using hot, dry air, often with added fat for basting, is called",
      ["roasting", "boiling", "poaching", "steaming"], "roasting",
      "Roasting cooks larger food items, especially meat, using dry heat, often basted with fat to keep the surface from drying out excessively."),
  _q("A dry cooking method that cooks food quickly using direct, intense heat from above or below, such as a grill element, is called",
      ["grilling", "boiling", "steaming", "poaching"], "grilling",
      "Grilling exposes food to intense, direct radiant heat, cooking it quickly while often producing a characteristic charred or browned surface."),
  _q("A cooking method that fully immerses food in hot oil or fat, often producing a crisp exterior, is called",
      ["deep frying", "shallow frying", "stir frying", "steaming"], "deep frying",
      "Deep frying fully submerges food in hot oil, cooking it quickly while producing a crisp, browned exterior."),
  _q("A cooking method that cooks food in a small, shallow amount of oil or fat in a pan is called",
      ["shallow frying", "deep frying", "stir frying", "steaming"], "shallow frying",
      "Shallow frying uses only a small amount of oil in a pan, cooking food primarily on one surface at a time before turning."),
  _q("A cooking method that quickly cooks small pieces of food over high heat while constantly moving them in a small amount of oil, typically in a wok, is called",
      ["stir frying", "deep frying", "shallow frying", "boiling"], "stir frying",
      "Stir frying rapidly cooks small, evenly cut pieces of food over high heat, using constant movement and minimal oil, typically in a wok."),
  _q("A key advantage of moist cooking methods such as stewing is that they",
      ["can effectively tenderise tougher cuts of meat over a longer cooking time", "always cook food faster than dry methods", "require no liquid of any kind", "prevent any loss of water-soluble nutrients"], "can effectively tenderise tougher cuts of meat over a longer cooking time",
      "Moist methods like stewing use prolonged gentle cooking in liquid to break down connective tissue, effectively tenderising tougher cuts of meat."),
  _q("A key disadvantage of boiling vegetables for an extended time is that it can",
      ["cause significant loss of water-soluble vitamins into the cooking liquid", "increase the vitamin content of the vegetables", "make the vegetables firmer and crunchier", "have no effect on the nutrient content at all"], "cause significant loss of water-soluble vitamins into the cooking liquid",
      "Prolonged boiling can leach water-soluble vitamins, such as vitamin C and some B vitamins, out of vegetables and into the surrounding cooking liquid."),
  _q("A pastry made by rubbing fat into flour to form a short, crumbly texture, commonly used for pie cases and tarts, is called",
      ["shortcrust pastry", "flaky pastry", "choux pastry", "puff pastry only"], "shortcrust pastry",
      "Shortcrust pastry is made by rubbing fat into flour, producing a short, crumbly texture ideal for pie and tart bases."),
  _q("A pastry made by folding layers of fat and dough together repeatedly, producing a light, flaky, layered texture, is called",
      ["flaky pastry", "shortcrust pastry", "choux pastry", "batter only"], "flaky pastry",
      "Flaky pastry is created through repeated folding of fat within the dough, producing distinct light, flaky layers when baked."),
  _q("A pastry made by cooking flour and fat together in liquid before beating in eggs, producing a light, hollow structure used for items like éclairs, is called",
      ["choux pastry", "shortcrust pastry", "flaky pastry", "puff pastry"], "choux pastry",
      "Choux pastry involves cooking a flour-fat-liquid mixture before beating in eggs, producing a light, airy dough that puffs into hollow shapes like éclairs and profiteroles."),
  _q("A cake-making method in which fat is worked into flour before other ingredients are added, commonly used for plain cakes, is called the",
      ["rubbed-in method", "creamed method", "whisked method", "melted method"], "rubbed-in method",
      "The rubbed-in method combines fat and flour by rubbing them together, similar to shortcrust pastry, commonly used for simpler, plainer cakes."),
  _q("A cake-making method in which fat and sugar are beaten together until light and fluffy before other ingredients are added, commonly used for richer cakes, is called the",
      ["creamed method", "rubbed-in method", "whisked method", "melted method"], "creamed method",
      "The creamed method beats fat and sugar together to incorporate air, producing a light texture suited to richer cake recipes."),
  _q("A cake-making method that relies mainly on whisking eggs and sugar together to incorporate air, often producing a light sponge with little or no fat, is called the",
      ["whisked method", "rubbed-in method", "creamed method", "melted method"], "whisked method",
      "The whisked method incorporates air primarily through vigorously beating eggs and sugar, producing a light sponge texture, often with minimal or no added fat."),
  _q("A cake-making method in which fat, sugar, and liquid ingredients are melted together before being combined with dry ingredients, commonly used for gingerbread, is called the",
      ["melted method", "rubbed-in method", "creamed method", "whisked method"], "melted method",
      "The melted method combines melted fat, sugar, and liquid with dry ingredients, commonly used for dense cakes like gingerbread."),
  _q("A sauce made from a base of butter and flour (roux) cooked with milk, without browning the roux, is called a",
      ["white sauce", "brown sauce", "emulsified sauce", "tomato sauce only"], "white sauce",
      "A white sauce (béchamel) is made from a roux of butter and flour cooked briefly without browning, then combined with milk."),
  _q("A sauce made from a roux that has been cooked until browned, typically combined with stock, is called a",
      ["brown sauce", "white sauce", "emulsified sauce", "custard sauce"], "brown sauce",
      "A brown sauce uses a roux cooked to a darker colour before liquid (often stock) is added, giving it a deeper flavour and colour than a white sauce."),
  _q("A sauce formed by combining two normally unmixable liquids, such as oil and vinegar, into a stable mixture, is called an",
      ["emulsified sauce", "white sauce", "brown sauce", "clear sauce"], "emulsified sauce",
      "Emulsified sauces, such as mayonnaise, combine typically unmixable liquids (like oil and vinegar) into a stable blended mixture, often using an emulsifying agent like egg yolk."),
  _q("A thick liquid dish, typically made by simmering meat, vegetables, or other ingredients in stock, is generally called a",
      ["soup", "sauce only", "stew only", "pastry"], "soup",
      "Soups are liquid-based dishes made by simmering various ingredients, such as meat, vegetables, or grains, in a flavourful stock or broth."),
  _q("A soup that has been passed through a sieve or blended to produce a smooth, thickened consistency is called a",
      ["puréed (cream) soup", "clear soup only", "consommé only", "broth only"], "puréed (cream) soup",
      "Puréed (cream) soups are blended or sieved to achieve a smooth, thick texture, unlike clear soups which retain a thin, transparent consistency."),
  _q("A clear, well-flavoured soup made by carefully clarifying a rich stock is called a",
      ["consommé", "cream soup", "purée soup", "thick chowder"], "consommé",
      "Consommé is a clear soup produced by carefully clarifying a rich stock, typically using egg whites to remove impurities, resulting in a crystal-clear liquid."),
  _q("Traditional local dishes taught in a Foods and Nutrition curriculum are important mainly because they",
      ["reflect cultural food heritage while applying learned nutritional and culinary principles", "have no connection to nutritional science at all", "are always less nutritious than foreign dishes", "require no cooking skill to prepare"], "reflect cultural food heritage while applying learned nutritional and culinary principles",
      "Studying traditional local dishes connects cultural heritage with practical application of nutrition science and culinary techniques learned in the course."),
  _q("When planning a kitchen work triangle (the relationship between the sink, cooker, and refrigerator), the main goal is to",
      ["minimise unnecessary movement between these key work areas", "maximise the distance between all three areas", "place all three appliances in exactly the same spot", "eliminate the need for a refrigerator in the kitchen"], "minimise unnecessary movement between these key work areas",
      "An efficient kitchen work triangle arrangement minimises the distance and movement needed between the sink, cooker, and refrigerator, improving workflow efficiency."),
  _q("Adequate ventilation in a kitchen is important mainly to",
      ["remove excess heat, steam, and cooking odours", "increase humidity levels unnecessarily", "prevent any air circulation at all", "eliminate the need for proper food storage"], "remove excess heat, steam, and cooking odours",
      "Good kitchen ventilation removes excess heat, steam, and odours generated during cooking, improving comfort and air quality."),
  _q("A key precaution when using a gas cooker in the kitchen is to",
      ["ensure proper ventilation and check for gas leaks regularly", "block all ventilation to conserve heat", "ignore any smell of gas, assuming it is harmless", "store flammable materials directly beside the cooker"], "ensure proper ventilation and check for gas leaks regularly",
      "Gas cookers require good ventilation and regular leak checks as essential safety precautions to prevent the buildup of hazardous gas."),
  _q("A basic knife safety practice in the kitchen is to",
      ["always cut away from the body and keep knives sharp for safer, more controlled cuts", "always cut toward the body for better visibility", "store knives loosely in a drawer with other utensils", "use only extremely blunt knives for all cutting tasks"], "always cut away from the body and keep knives sharp for safer, more controlled cuts",
      "Cutting away from the body and using well-sharpened knives (which require less force and are less likely to slip) are basic, essential knife safety practices."),
  _q("Cross-contamination in the kitchen is best prevented by",
      ["using separate chopping boards and utensils for raw meat and ready-to-eat foods", "using the same chopping board for all food types without washing it", "storing raw meat directly next to cooked food in the refrigerator", "washing hands only at the start of meal preparation"], "using separate chopping boards and utensils for raw meat and ready-to-eat foods",
      "Using separate chopping boards and utensils for raw meat and ready-to-eat foods, along with regular handwashing, are key measures to prevent cross-contamination."),
];
