import "../quiz_question.dart";

const _subject = "Yoruba";

QuizQuestion _q(String text, List<String> options, String correct, String explanation) {
  return QuizQuestion(
    subject: _subject,
    text: text,
    options: options,
    correctIndex: options.indexOf(correct),
    explanation: explanation,
  );
}

/// WAEC Yoruba question bank covering the full syllabus: Ètò Ìró àti Gírámà
/// (Phonology & Grammar/Morphology/Translation), Àrokò àti Àkàgbóòye
/// (Composition & Comprehension), and Àṣà, Ìṣe, àti Lítírẹ́ṣọ̀ (Culture,
/// Traditions & Literature). Weighted toward well-established phonology,
/// grammar-category, culture, and literary-history facts rather than
/// fine-grained native-speaker judgement calls.
List<QuizQuestion> buildWaecYorubaQuestions() {
  return [
    ..._iroEdePhonology,
    ..._giramaAtiIsedaOro,
    ..._arokoAtiAkagboye,
    ..._asaIseAtiLiteresho,
  ];
}

final _iroEdePhonology = [
  _q("Kí ni orúkọ tí à ń pè àwọn ìró tí a ń pè láìsí ìdènà afẹ́fẹ́ nínú ẹnu, gẹ́gẹ́ bí 'a', 'e', 'i'?",
      ["Fáwẹ́lì (Vowels)", "Kọ́nṣónántì", "Àmì Ohùn", "Mọ́fíìmù"], "Fáwẹ́lì (Vowels)",
      "Vowels (fáwẹ́lì) are speech sounds produced without any obstruction to the airflow, unlike consonants."),
  _q("Kí ni orúkọ tí à ń pè àwọn ìró tí a ń dá pẹ̀lú ìdènà afẹ́fẹ́ ní apá kan ẹnu, gẹ́gẹ́ bí 'b', 'k', 'd'?",
      ["Kọ́nṣónántì (Consonants)", "Fáwẹ́lì", "Àmì Ohùn", "Ìró Àárín"], "Kọ́nṣónántì (Consonants)",
      "Consonants (kọ́nṣónántì) are produced by obstructing the airflow at some point in the vocal tract, distinguishing them from vowels."),
  _q("Fáwẹ́lì Yorùbá tí a ń pè pẹ̀lú afẹ́fẹ́ tí ń jáde láti imú ni a ń pè ní",
      ["Àfofún (nasal vowels)", "Àránmú (oral vowels)", "Kọ́nṣónántì", "Àmì Ohùn"], "Àfofún (nasal vowels)",
      "Nasal vowels (àfofún) are produced with airflow passing through the nose, distinct from oral vowels (àránmú) which use only the mouth."),
  _q("Fáwẹ́lì Yorùbá tí a ń pè pẹ̀lú afẹ́fẹ́ tí ń jáde láti ẹnu nìkan ni a ń pè ní",
      ["Àránmú (oral vowels)", "Àfofún (nasal vowels)", "Kọ́nṣónántì", "Ìró Àárín"], "Àránmú (oral vowels)",
      "Oral vowels (àránmú) are produced with air passing only through the mouth, as opposed to nasal vowels which involve nasal airflow."),
  _q("Kí ni orúkọ tí à ń pè ètò lẹ́tà tí a ń fi kọ èdè Yorùbá?",
      ["Àkópọ̀ lẹ́tà (Yoruba alphabet/orthography)", "Àmì Ohùn nìkan", "Mọ́fíìmù", "Gbólóhùn"], "Àkópọ̀ lẹ́tà (Yoruba alphabet/orthography)",
      "Àkópọ̀ lẹ́tà refers to the standard Yoruba alphabet and orthographic system used to write the language."),
  _q("Kí ni à ń pè ìṣẹ̀lẹ̀ nínú èdè Yorùbá níbi tí a ti ń yọ fáwẹ́lì kan kúrò nígbà tí ọ̀rọ̀ méjì bá pàdé, láti mú ọ̀rọ̀ sunwọ̀n?",
      ["Ìsúnkì fàwẹ́lì (vowel elision)", "Ìyọpọ̀ Fáwẹ́lì", "Àmì Ohùn", "Ìpín-ọ̀rọ̀"], "Ìsúnkì fàwẹ́lì (vowel elision)",
      "Vowel elision (ìsúnkì fàwẹ́lì) occurs when a vowel is dropped where two words meet, smoothing the pronunciation of connected speech."),
  _q("Kí ni à ń pè ìṣẹ̀lẹ̀ tí ó ń mú kí fáwẹ́lì kan yí padà láti bá fáwẹ́lì tó wà nítòsí rẹ̀ mu, ní èdè Yorùbá?",
      ["Ìyọpọ̀ Fáwẹ́lì (vowel assimilation)", "Ìsúnkì fàwẹ́lì", "Àmì Ohùn", "Ìpín-ọ̀rọ̀"], "Ìyọpọ̀ Fáwẹ́lì (vowel assimilation)",
      "Vowel assimilation (ìyọpọ̀ fáwẹ́lì) occurs when a vowel changes to become more similar to a neighbouring vowel, aiding smoother pronunciation."),
  _q("Èdè Yorùbá ní irú àmì ohùn mélòó?",
      ["Mẹ́ta: Òkè, Àárín, àti Ìsàlẹ̀ (three: High, Mid, and Low)", "Ọ̀kan ṣoṣo", "Mẹ́rin", "Márùn-ún"], "Mẹ́ta: Òkè, Àárín, àti Ìsàlẹ̀ (three: High, Mid, and Low)",
      "Yoruba has three tone levels: high (òkè), mid (àárín, typically unmarked in writing), and low (ìsàlẹ̀), each capable of distinguishing word meaning."),
  _q("Àmì wo ni a máa ń lò láti fi hàn pé ọ̀rọ̀ kan ní ohùn òkè ní èdè Yorùbá?",
      ["Àmì àdìdùn (acute accent, ´)", "Àmì ìsàlẹ̀ (grave accent, `)", "Kò sí àmì rárá", "Àmì ìbéèrè"], "Àmì àdìdùn (acute accent, ´)",
      "A high tone in written Yoruba is typically marked with an acute accent (´) placed above the relevant vowel."),
  _q("Àmì wo ni a máa ń lò láti fi hàn pé ọ̀rọ̀ kan ní ohùn ìsàlẹ̀ ní èdè Yorùbá?",
      ["Àmì ìsàlẹ̀ (grave accent, `)", "Àmì àdìdùn (acute accent)", "Kò sí àmì rárá", "Àmì ìbéèrè"], "Àmì ìsàlẹ̀ (grave accent, `)",
      "A low tone in written Yoruba is typically marked with a grave accent (`) placed above the relevant vowel."),
  _q("Ohùn Àárín (mid tone) ní èdè Yorùbá, ní ọ̀pọ̀ ìgbà, ni a máa ń kọ",
      ["láìsí àmì kankan (unmarked)", "pẹ̀lú àmì àdìdùn", "pẹ̀lú àmì ìsàlẹ̀", "pẹ̀lú àmì ìbéèrè"], "láìsí àmì kankan (unmarked)",
      "The mid tone in Yoruba is conventionally left unmarked in writing, distinguishing it from the marked high and low tones."),
  _q("Kí nìdí tí àmì ohùn (tone marking) fi ṣe pàtàkì gan-an nínú kíkọ èdè Yorùbá?",
      ["Nítorí ọ̀rọ̀ kan náà lè ní ìtumọ̀ tó yàtọ̀ pátápátá tí ohùn rẹ̀ bá yàtọ̀", "Nítorí kò ní ipa kankan lórí ìtumọ̀ ọ̀rọ̀", "Nítorí àwọn olùkọ́ nìkan ló ń lò ó", "Nítorí kò sí ìyàtọ̀ láàrin ohùn"], "Nítorí ọ̀rọ̀ kan náà lè ní ìtumọ̀ tó yàtọ̀ pátápátá tí ohùn rẹ̀ bá yàtọ̀",
      "Since Yoruba is a tonal language, the same sequence of letters can carry entirely different meanings depending on the tone applied, making accurate tone marking essential."),
  _q("Kí ni ìpín kan tó kéré jùlọ nínú ọ̀rọ̀ tó ní fáwẹ́lì nínú, tí í ṣe ìpìlẹ̀ fún kíkọ ọ̀rọ̀?",
      ["Ìpín-ọ̀rọ̀/Syllable", "Mọ́fíìmù", "Gbólóhùn", "Àmì Ohùn"], "Ìpín-ọ̀rọ̀/Syllable",
      "A syllable (ìpín-ọ̀rọ̀) is the basic phonetic unit built around a vowel, forming the foundational building block of spoken words."),
  _q("Ẹ̀ka ìmọ̀ èdè wo ni ó ń kẹ́kọ̀ọ́ nípa ètò ìró àti ohùn nínú èdè kan?",
      ["Fonọ́lọ́jì (Phonology)", "Gírámà (Grammar/Syntax)", "Lítírẹ́ṣọ̀ (Literature)", "Ìtàn (History)"], "Fonọ́lọ́jì (Phonology)",
      "Phonology is the branch of linguistics dedicated to studying the sound system of a language, including vowels, consonants, and tone patterns."),
  _q("Ẹ̀ka ìmọ̀ èdè wo ni ó ń kẹ́kọ̀ọ́ nípa bí a ṣe ń pe ìró pẹ̀lú ẹ̀yà ara ìpè (articulatory features)?",
      ["Fonẹ́tíìkì (Phonetics)", "Fonọ́lọ́jì nìkan", "Ìṣẹ̀dá Ọ̀rọ̀", "Ìtúpalẹ̀"], "Fonẹ́tíìkì (Phonetics)",
      "Phonetics studies the physical articulation of speech sounds, complementing phonology's focus on the sound patterns and system of a language."),
  _q("Kọ́nṣónántì méjì tí a ń pè papọ̀ ní àkókò kan náà, gẹ́gẹ́ bí 'gb' àti 'kp', ni a ń pè ní",
      ["Kọ́nṣónántì onífúnpọ̀ (labial-velar consonants)", "Fáwẹ́lì onífúnpọ̀", "Àmì Ohùn onífúnpọ̀", "Ìpín-ọ̀rọ̀ onífúnpọ̀"], "Kọ́nṣónántì onífúnpọ̀ (labial-velar consonants)",
      "Labial-velar consonants like 'gb' and 'kp' are produced with a simultaneous double articulation, a distinctive feature of Yoruba phonology."),
  _q("Kí ni à ń pè ìpín-ọ̀rọ̀ tí ó parí pẹ̀lú fáwẹ́lì, ní èdè Yorùbá?",
      ["Ìpín-ọ̀rọ̀ tí ó ṣí sílẹ̀ (open syllable)", "Ìpín-ọ̀rọ̀ tí ó tì (closed syllable)", "Àmì Ohùn", "Mọ́fíìmù"], "Ìpín-ọ̀rọ̀ tí ó ṣí sílẹ̀ (open syllable)",
      "An open syllable ends in a vowel sound, a very common syllable structure in Yoruba words."),
  _q("Kí ni à ń pè ohun tí ó ń ṣẹlẹ̀ nígbà tí ọ̀rọ̀ méjì bá pàdé tí wọ́n sì di ọ̀rọ̀ kan ṣoṣo nínú ọ̀rọ̀ sísọ àti kíkọ?",
      ["Àkópọ̀-ọ̀rọ̀ (word/phrase contraction)", "Àmì Ohùn nìkan", "Ìpín-ọ̀rọ̀ nìkan", "Mọ́fíìmù nìkan"], "Àkópọ̀-ọ̀rọ̀ (word/phrase contraction)",
      "Contraction in Yoruba often occurs when two words merge into one form during speech, closely related to processes like vowel elision."),
  _q("Ìyàtọ̀ láàrin ohùn Òkè àti Ìsàlẹ̀ nínú ọ̀rọ̀ kan náà lè yí ìtumọ̀ ọ̀rọ̀ padà pátápátá. Èyí fi hàn pé Yorùbá jẹ́",
      ["èdè oníohùn (a tonal language)", "èdè tí kò ní ohùn rárá", "èdè tí kò ní gírámà", "èdè tí a kò lè kọ sílẹ̀"], "èdè oníohùn (a tonal language)",
      "Because tone alone can distinguish meaning, Yoruba is classified as a tonal language, where pitch is a core part of word meaning."),
  _q("Kí ni à ń pè ìwádìí nípa bí ohùn (tone) ṣe ń ṣiṣẹ́ nínú ìṣètò ìró èdè kan?",
      ["Ìmọ̀ Ohùn (tonology)", "Ìmọ̀ Ìtàn", "Ìmọ̀ Lítírẹ́ṣọ̀", "Ìmọ̀ Ìṣirò"], "Ìmọ̀ Ohùn (tonology)",
      "Tonology, a specialised branch of phonology, focuses on how pitch patterns (tones) function to convey meaning within a tonal language."),
  _q("Nínú ọ̀rọ̀ Yorùbá, ìró kọ́nṣónántì méjì tí a ń pè pẹ̀lú fífọwọ́kan ètè méjèèjì ni a ń pè ní",
      ["Kọ́nṣónántì onílètè (bilabial consonants)", "Kọ́nṣónántì onífun", "Fáwẹ́lì onífun", "Àmì Ohùn Àárín"], "Kọ́nṣónántì onílètè (bilabial consonants)",
      "Bilabial consonants, such as 'b', 'p', and 'm', are produced using both lips, a common consonant category in Yoruba."),
  _q("Kí nìdí tí ìmọ̀ ìpín-ọ̀rọ̀ (syllable structure) fi ṣe pàtàkì nínú kíkọ́ ọ̀mọ̀wé láti ka èdè Yorùbá dáadáa?",
      ["Nítorí ó ń ràn wá lọ́wọ́ láti mọ bí a ṣe ń pín ọ̀rọ̀ sí ẹ̀ka kéékèèké fún kíkà tí ó tọ́", "Nítorí kò ní ìwúlò kankan", "Nítorí ó jẹ mọ́ ìtàn Yorùbá nìkan", "Nítorí ó jẹ mọ́ orin nìkan"], "Nítorí ó ń ràn wá lọ́wọ́ láti mọ bí a ṣe ń pín ọ̀rọ̀ sí ẹ̀ka kéékèèké fún kíkà tí ó tọ́",
      "Understanding syllable structure helps learners correctly break down and pronounce words, supporting accurate reading and speech."),
  _q("Kí ni à ń pè ọ̀nà tí a ń gbà ṣàyẹ̀wò ipò ahọ́n nínú ẹnu nígbà tí a bá ń pe fáwẹ́lì kan pàtó?",
      ["Ìtúpalẹ̀ ipò ahọ́n (tongue position analysis)", "Ìtúpalẹ̀ àkọsílẹ̀ ìtàn", "Ìtúpalẹ̀ lítírẹ́ṣọ̀", "Ìtúpalẹ̀ gírámà nìkan"], "Ìtúpalẹ̀ ipò ahọ́n (tongue position analysis)",
      "Analysing tongue position during vowel articulation helps distinguish different vowel qualities within a language's phonological system."),
  _q("Kí ni ìdí tí àkópọ̀ lẹ́tà (orthography) fi ṣe pàtàkì nínú kíkọ èdè Yorùbá lónìí?",
      ["Kí a lè ní ìṣọ̀kan ní bí a ṣe ń kọ àti kíka èdè náà láàrin gbogbo àwọn tí ń lò ó", "Kí a lè yí èdè náà padà pátápátá", "Kí a lè dá kọ́nṣónántì tuntun sílẹ̀ láìsí ìlànà", "Kí a lè yẹra fún kíkọ èdè náà pátápátá"], "Kí a lè ní ìṣọ̀kan ní bí a ṣe ń kọ àti kíka èdè náà láàrin gbogbo àwọn tí ń lò ó",
      "A standardised orthography ensures consistency in how the language is written and read across all its users, aiding clear communication and education."),
  _q("Kí ni à ń pè ìró tí a ń pè pẹ̀lú fífi ahọ́n kan ẹ̀yìn ẹnu, gẹ́gẹ́ bí 'k', 'g', 'ng'?",
      ["Kọ́nṣónántì ẹ̀yìn-ọ̀fun (velar consonants)", "Kọ́nṣónántì onílètè", "Fáwẹ́lì onífun", "Àmì Ohùn Àárín"], "Kọ́nṣónántì ẹ̀yìn-ọ̀fun (velar consonants)",
      "Velar consonants, such as 'k', 'g', and 'ng', are articulated with the back of the tongue raised toward the soft palate (velum)."),
];

final _giramaAtiIsedaOro = [
  _q("Ọ̀rọ̀ tí ó ń dárúkọ ènìyàn, ibi, tàbí ohun kan ni a ń pè ní",
      ["Ọ̀rọ̀-Orúkọ (Noun)", "Ọ̀rọ̀-Ìṣe", "Ọ̀rọ̀-Àpèjúwe", "Ọ̀rọ̀-Atọ́kùn"], "Ọ̀rọ̀-Orúkọ (Noun)",
      "A noun (ọ̀rọ̀-orúkọ) is the part of speech used to name a person, place, or thing."),
  _q("Ọ̀rọ̀ tí ó ń rọ́pò orúkọ nínú gbólóhùn, bí í ṣe 'òun', 'wọ́n', 'àwa'?",
      ["Ọ̀rọ̀-Arọpò-Orúkọ (Pronoun)", "Ọ̀rọ̀-Orúkọ", "Ọ̀rọ̀-Ìṣe", "Ọ̀rọ̀-Atọ́kùn"], "Ọ̀rọ̀-Arọpò-Orúkọ (Pronoun)",
      "A pronoun (ọ̀rọ̀-arọpò-orúkọ) stands in place of a noun, such as 'he/she/it' (òun), 'they' (wọ́n), or 'we' (àwa)."),
  _q("Ọ̀rọ̀ tí ó ń fi hàn ìṣe tàbí ipò kan nínú gbólóhùn, bí í ṣe 'lọ', 'jẹ', 'jókòó'?",
      ["Ọ̀rọ̀-Ìṣe (Verb)", "Ọ̀rọ̀-Orúkọ", "Ọ̀rọ̀-Àpèjúwe", "Ọ̀rọ̀-Atọ́kùn"], "Ọ̀rọ̀-Ìṣe (Verb)",
      "A verb (ọ̀rọ̀-ìṣe) expresses an action or state, forming the core of the predicate in a Yoruba sentence."),
  _q("Ọ̀rọ̀ tí ó ń ṣàpèjúwe orúkọ kan, bí í ṣe 'dára', 'dúdú', 'ńlá'?",
      ["Ọ̀rọ̀-Àpèjúwe (Adjective)", "Ọ̀rọ̀-Orúkọ", "Ọ̀rọ̀-Ìṣe", "Ọ̀rọ̀-Atọ́kùn"], "Ọ̀rọ̀-Àpèjúwe (Adjective)",
      "An adjective (ọ̀rọ̀-àpèjúwe) describes or modifies a noun, providing more information about its quality."),
  _q("Ọ̀rọ̀ tí ó ń so orúkọ tàbí arọ́pò-orúkọ pọ̀ mọ́ apá gbólóhùn mìíràn, bí í ṣe 'ní', 'lórí', 'sí'?",
      ["Ọ̀rọ̀-Atọ́kùn (Preposition)", "Ọ̀rọ̀-Ìṣe", "Ọ̀rọ̀-Orúkọ", "Ọ̀rọ̀-Àpèjúwe"], "Ọ̀rọ̀-Atọ́kùn (Preposition)",
      "A preposition (ọ̀rọ̀-atọ́kùn) links a noun or pronoun to another part of the sentence, indicating relationships such as location or direction."),
  _q("Kí ni à ń pè ọ̀nà tí a ń gbà kọ́ ọ̀rọ̀ tuntun nípa fífi ìbẹ̀rẹ̀ kún ìpìlẹ̀ ọ̀rọ̀ kan, ní èdè Yorùbá?",
      ["Àfòmọ́-ìbẹ̀rẹ̀ (Prefixation)", "Àpòpò-ọ̀rọ̀", "Ìsúnkì fàwẹ́lì", "Ìyọpọ̀ Fáwẹ́lì"], "Àfòmọ́-ìbẹ̀rẹ̀ (Prefixation)",
      "Prefixation (àfòmọ́-ìbẹ̀rẹ̀) is a word-formation process in Yoruba where a prefix is attached to a root, often creating a noun from a verb."),
  _q("Kí ni à ń pè ọ̀nà tí a ń gbà tún ọ̀rọ̀ ṣe lẹ́ẹ̀mejì tàbí jù bẹ́ẹ̀ lọ láti fi kún ìtumọ̀ rẹ̀, ní èdè Yorùbá?",
      ["Àpòpò-ọ̀rọ̀ (Reduplication)", "Àfòmọ́-ìbẹ̀rẹ̀", "Ìsúnkì fàwẹ́lì", "Ìyọpọ̀ Fáwẹ́lì"], "Àpòpò-ọ̀rọ̀ (Reduplication)",
      "Reduplication (àpòpò-ọ̀rọ̀) involves repeating a word or part of it, a common word-formation process used to intensify or extend meaning in Yoruba."),
  _q("Kí ni gbólóhùn tí a ń pè ní 'gbólóhùn oníbọ̀' (complex sentence)?",
      ["Gbólóhùn tí ó ní ìpín méjì tàbí jù bẹ́ẹ̀ lọ tí wọ́n so pọ̀ láti fi hàn èrò kan tó pé", "Gbólóhùn tí ó ní ọ̀rọ̀ kan ṣoṣo", "Gbólóhùn tí kò ní ọ̀rọ̀-ìṣe", "Gbólóhùn ìbéèrè nìkan"], "Gbólóhùn tí ó ní ìpín méjì tàbí jù bẹ́ẹ̀ lọ tí wọ́n so pọ̀ láti fi hàn èrò kan tó pé",
      "A complex sentence (gbólóhùn oníbọ̀) combines two or more clauses, often joined by a conjunction or subordinator, to express a fuller, more elaborate idea."),
  _q("Kí ni gbólóhùn tí a ń pè ní 'gbólóhùn alákòópọ̀' (compound sentence)?",
      ["Gbólóhùn tí ó ní gbólóhùn olómìnira méjì tí a fi ọ̀rọ̀ atapọ̀ so pọ̀", "Gbólóhùn tí ó ní ọ̀rọ̀ kan ṣoṣo", "Gbólóhùn tí kò ní kókó-ọ̀rọ̀", "Gbólóhùn ìbéèrè nìkan"], "Gbólóhùn tí ó ní gbólóhùn olómìnira méjì tí a fi ọ̀rọ̀ atapọ̀ so pọ̀",
      "A compound sentence (gbólóhùn alákòópọ̀) joins two independent clauses together, typically using a conjunction such as 'àti' (and) or 'ṣùgbọ́n' (but)."),
  _q("Nínú ìtúpalẹ̀ gbólóhùn, kí ni à ń pè apá tí ó ń fi hàn ẹni tàbí ohun tí gbólóhùn ń sọ̀rọ̀ nípa rẹ̀?",
      ["Kókó-ọ̀rọ̀ (Subject)", "Àsọtúnsọ (Predicate) nìkan", "Ọ̀rọ̀-Atọ́kùn nìkan", "Ọ̀rọ̀-Àpèjúwe nìkan"], "Kókó-ọ̀rọ̀ (Subject)",
      "The subject (kókó-ọ̀rọ̀) identifies who or what the sentence is primarily about, typically performing the action of the verb."),
  _q("Nínú ìtúpalẹ̀ gbólóhùn, kí ni à ń pè apá tí ó ń fún wa ní ìsọfúnni nípa kókó-ọ̀rọ̀?",
      ["Àsọtúnsọ (Predicate)", "Kókó-ọ̀rọ̀ nìkan", "Ọ̀rọ̀-Atọ́kùn nìkan", "Mọ́fíìmù nìkan"], "Àsọtúnsọ (Predicate)",
      "The predicate (àsọtúnsọ) provides information about the subject, typically including the verb and any related objects or complements."),
  _q("Kí ni ìdí ìtúmọ̀ (translation) fi ṣe pàtàkì láàrin èdè Gẹ̀ẹ́sì àti Yorùbá?",
      ["Kí a lè fi ìtumọ̀ ọ̀rọ̀ hàn ní èdè mìíràn láìyẹ̀ nínú ìtumọ̀ àti àṣà náà", "Kí a lè fi ọ̀rọ̀ kan náà kọ ní èdè kan náà lẹ́ẹ̀mejì", "Kí a lè yí ohùn ọ̀rọ̀ padà nìkan", "Kí a lè yẹra fún kíkọ gbólóhùn"], "Kí a lè fi ìtumọ̀ ọ̀rọ̀ hàn ní èdè mìíràn láìyẹ̀ nínú ìtumọ̀ àti àṣà náà",
      "Translation aims to accurately convey the meaning of a passage from one language to another, while preserving both meaning and cultural nuance."),
  _q("Ẹ̀ka gírámà wo ni ó ń kẹ́kọ̀ọ́ nípa ìgbékalẹ̀ inú ọ̀rọ̀, gẹ́gẹ́ bí ìpìlẹ̀ àti àfikún rẹ̀?",
      ["Ìṣẹ̀dá Ọ̀rọ̀ (Morphology)", "Ìgbékalẹ̀ Gbólóhùn (Syntax)", "Fonọ́lọ́jì", "Lítírẹ́ṣọ̀"], "Ìṣẹ̀dá Ọ̀rọ̀ (Morphology)",
      "Morphology studies the internal structure of words, including how roots, prefixes, and reduplication combine to form new words."),
  _q("Ẹ̀ka gírámà wo ni ó ń kẹ́kọ̀ọ́ nípa bí a ṣe ń to àwọn ọ̀rọ̀ jọ láti kọ́ gbólóhùn tó ní ìtumọ̀?",
      ["Ìgbékalẹ̀ Gbólóhùn (Syntax)", "Ìṣẹ̀dá Ọ̀rọ̀", "Fonọ́lọ́jì", "Lítírẹ́ṣọ̀"], "Ìgbékalẹ̀ Gbólóhùn (Syntax)",
      "Syntax examines how words are arranged and combined to form grammatically correct and meaningful sentences."),
  _q("Ọ̀rọ̀ tí ó ń so ọ̀rọ̀ méjì tàbí gbólóhùn méjì pọ̀, bí í ṣe 'àti', 'ṣùgbọ́n', 'tàbí'?",
      ["Ọ̀rọ̀-Atapọ̀ (Conjunction)", "Ọ̀rọ̀-Atọ́kùn", "Ọ̀rọ̀-Orúkọ", "Ọ̀rọ̀-Ìṣe"], "Ọ̀rọ̀-Atapọ̀ (Conjunction)",
      "A conjunction (ọ̀rọ̀-atapọ̀) joins words, phrases, or clauses together, such as 'and' (àti), 'but' (ṣùgbọ́n), or 'or' (tàbí)."),
  _q("Nínú gbólóhùn Yorùbá, kí ni orúkọ tí a ń fún ẹni tí ó ń gba ìṣe ọ̀rọ̀-ìṣe, tí kì í ṣe kókó-ọ̀rọ̀?",
      ["Àbájáde/Ohun-ìṣe (Object)", "Kókó-ọ̀rọ̀ nìkan", "Ọ̀rọ̀-Atọ́kùn nìkan", "Ọ̀rọ̀-Àpèjúwe nìkan"], "Àbájáde/Ohun-ìṣe (Object)",
      "The object of a sentence receives the action of the verb, distinct from the subject, which performs the action."),
  _q("Kí ni à ń pè gbólóhùn tí a ń fi béèrè ìbéèrè, bí í ṣe 'Ṣé o lọ sí ilé-ìwé?'",
      ["Gbólóhùn Ìbéèrè (interrogative sentence)", "Gbólóhùn Àṣẹ nìkan", "Gbólóhùn Oníbọ̀ nìkan", "Gbólóhùn Alákòópọ̀ nìkan"], "Gbólóhùn Ìbéèrè (interrogative sentence)",
      "An interrogative sentence is used to ask a question, distinct from declarative, imperative, or exclamatory sentence types."),
  _q("Kí ni à ń pè gbólóhùn tí a ń fi pàṣẹ tàbí kọ́ni, bí í ṣe 'Lọ sí ilé-ìwé!'?",
      ["Gbólóhùn Àṣẹ (imperative sentence)", "Gbólóhùn Ìbéèrè", "Gbólóhùn Oníbọ̀ nìkan", "Gbólóhùn Alákòópọ̀ nìkan"], "Gbólóhùn Àṣẹ (imperative sentence)",
      "An imperative sentence gives a command or instruction, such as telling someone to go to school."),
  _q("Ọ̀rọ̀-àpèjúwe tí ó ń fi ìṣàkóso ẹnìkan hàn, bí í ṣe 'mi', 'rẹ', 'wọn' nínú 'ilé mi', ni a ń pè ní",
      ["Ọ̀rọ̀-Àpèjúwe Ìṣàkóso (possessive determiner)", "Ọ̀rọ̀-Ìṣe", "Ọ̀rọ̀-Atọ́kùn", "Ọ̀rọ̀-Atapọ̀"], "Ọ̀rọ̀-Àpèjúwe Ìṣàkóso (possessive determiner)",
      "Possessive determiners like 'mi' (my), 'rẹ' (your), or 'wọn' (their) show ownership or association with the noun they modify, such as 'ilé mi' (my house)."),
  _q("Kí ni à ń pè ìfiwéra tí a ń ṣe láàrin nǹkan méjì nípa lílo ọ̀rọ̀ bí í ṣe 'ju... lọ' ní èdè Yorùbá?",
      ["Ìfiwéra (comparative construction)", "Ìsúnkì fàwẹ́lì", "Ìpín-ọ̀rọ̀", "Àmì Ohùn"], "Ìfiwéra (comparative construction)",
      "Comparative constructions, such as those using 'ju...lọ' (more than), allow speakers to compare the qualities of two things in Yoruba."),
  _q("Kí ni à ń pè ìdìpọ̀ ọ̀rọ̀ tí ó ń fi ìní ọ̀rọ̀ kan hàn lórí òmíràn, bí í ṣe 'ilé bàbá mi'?",
      ["Gbólóhùn Ìní (possessive/genitive construction)", "Gbólóhùn Ìbéèrè", "Gbólóhùn Àṣẹ", "Gbólóhùn Alákòópọ̀"], "Gbólóhùn Ìní (possessive/genitive construction)",
      "A possessive (genitive) construction, such as 'ilé bàbá mi' (my father's house), shows a relationship of ownership between two nouns."),
  _q("Nínú ìtúpalẹ̀ gbólóhùn, kí ni à ń pè ìpín gbólóhùn kan sí àwọn ẹ̀yà rẹ̀ láti ṣàyẹ̀wò ìgbékalẹ̀ rẹ̀?",
      ["Ìtúpalẹ̀ Gbólóhùn (sentence parsing)", "Ìtúmọ̀ ọ̀rọ̀ nìkan", "Fonọ́lọ́jì nìkan", "Lítírẹ́ṣọ̀ nìkan"], "Ìtúpalẹ̀ Gbólóhùn (sentence parsing)",
      "Sentence parsing involves breaking a sentence into its grammatical components to analyse its structure and function."),
  _q("Kí ni à ń pè ọ̀rọ̀ tí a fi ń ṣàpèjúwe ìye tàbí iye nǹkan, bí í ṣe 'mẹ́ta', 'púpọ̀', 'díẹ̀'?",
      ["Ọ̀rọ̀ Onípò/Iye (quantifiers/numerals)", "Ọ̀rọ̀-Atọ́kùn", "Ọ̀rọ̀-Atapọ̀", "Ọ̀rọ̀-Orúkọ nìkan"], "Ọ̀rọ̀ Onípò/Iye (quantifiers/numerals)",
      "Quantifiers and numerals, such as 'mẹ́ta' (three), 'púpọ̀' (many), or 'díẹ̀' (a few), express quantity or amount in relation to a noun."),
  _q("Kí ni ìlànà gbogbogbòò tí a ń tẹ̀lé nígbà tí a bá ń kọ́ ọ̀rọ̀-orúkọ láti inú ọ̀rọ̀-ìṣe nípa àfòmọ́-ìbẹ̀rẹ̀?",
      ["Fífi fáwẹ́lì kún ìbẹ̀rẹ̀ ọ̀rọ̀-ìṣe náà, bí í ṣe 'kọ́' di 'ìkọ́'", "Yíyọ gbogbo fáwẹ́lì kúrò", "Yíyí ọ̀rọ̀-ìṣe padà sí kọ́nṣónántì nìkan", "Kíkọ ọ̀rọ̀-ìṣe náà ní ìdàkejì rẹ̀"], "Fífi fáwẹ́lì kún ìbẹ̀rẹ̀ ọ̀rọ̀-ìṣe náà, bí í ṣe 'kọ́' di 'ìkọ́'",
      "A common Yoruba word-formation pattern involves adding a vowel prefix to a verb root to derive a related noun, such as 'kọ́' (to build) becoming 'ìkọ́' (building/construction)."),
  _q("Ọ̀rọ̀-ìṣe tí ó ń fi hàn pé ìṣe kan ṣẹlẹ̀ ní àkókò tí ó ti kọjá ni a ń pè ní ọ̀rọ̀-ìṣe onígbà",
      ["Àkókò Ìṣẹ̀ṣe (past tense)", "Àkókò Ìsinsìnyí nìkan", "Àkókò Ọjọ́ Iwájú nìkan", "Àṣẹ nìkan"], "Àkókò Ìṣẹ̀ṣe (past tense)",
      "Past tense verb forms indicate that an action has already occurred, marked in Yoruba typically through auxiliary markers or context."),
];

final _arokoAtiAkagboye = [
  _q("Kí ni à ń pè lẹ́tà tí a fi ń kọ sí ilé-iṣẹ́ tàbí ẹnì kan tí a kò mọ̀ dáadáa, ní ọ̀nà oníṣẹ́ẹ́?",
      ["Lẹ́tà Kíkọ oníṣẹ́ẹ́ (formal letter)", "Lẹ́tà Kíkọ àjọṣepọ̀ (informal letter)", "Àbáye", "Ìtàn"], "Lẹ́tà Kíkọ oníṣẹ́ẹ́ (formal letter)",
      "A formal letter is written to an institution or person one does not know well, following a professional, structured format."),
  _q("Kí ni à ń pè lẹ́tà tí a fi ń kọ sí ọ̀rẹ́ tàbí ẹbí, ní ọ̀nà ìbáṣepọ̀?",
      ["Lẹ́tà Kíkọ àjọṣepọ̀ (informal letter)", "Lẹ́tà Kíkọ oníṣẹ́ẹ́", "Àbáye", "Ìtàn"], "Lẹ́tà Kíkọ àjọṣepọ̀ (informal letter)",
      "An informal letter is written to a friend or family member in a warm, familiar tone, distinct from the professional style of a formal letter."),
  _q("Kí ni à ń pè àpilẹ̀kọ tí ó ń jíyàn fún tàbí lòdì sí kókó kan pẹ̀lú ìdí tó fẹsẹ̀múlẹ̀?",
      ["Àbáye/Àjírò (argumentative essay)", "Ìròyìn", "Ìtàn", "Lẹ́tà Kíkọ"], "Àbáye/Àjírò (argumentative essay)",
      "An argumentative essay (àbáye/àjírò) presents reasoned arguments to support or oppose a particular viewpoint on a topic."),
  _q("Kí ni à ń pè àpilẹ̀kọ tí ó ń ṣàlàyé ìṣẹ̀lẹ̀ kan tí ó ṣẹlẹ̀ gan-an, ní ọ̀nà ìròyìn?",
      ["Ìròyìn (news/report writing)", "Àbáye", "Ìtàn", "Lẹ́tà Kíkọ"], "Ìròyìn (news/report writing)",
      "News report writing (ìròyìn) describes real events in a factual, structured manner, typical of journalistic composition."),
  _q("Kí ni à ń pè àpilẹ̀kọ tí ó ń sọ ìtàn ìṣẹ̀lẹ̀ kan, pẹ̀lú ìbẹ̀rẹ̀, àárín, àti òpin?",
      ["Ìtàn (narrative essay)", "Àbáye", "Ìròyìn", "Lẹ́tà Kíkọ"], "Ìtàn (narrative essay)",
      "A narrative essay (ìtàn) tells the story of events, typically organised with a beginning, middle, and end."),
  _q("Iye ọ̀rọ̀ tí a ń retí nínú àrokò WAEC ní èdè Yorùbá jẹ́ kò kéré ní",
      ["ọ̀rọ̀ 300", "ọ̀rọ̀ 10 sí 20", "ọ̀rọ̀ 1000", "ọ̀rọ̀ 5"], "ọ̀rọ̀ 300",
      "WAEC Yoruba compositions are typically expected to contain a minimum of about 300 words to adequately develop the topic."),
  _q("Kí ni à ń pè kíkàwé tí a ṣe láti fa kókó pàtàkì jáde nínú àpilẹ̀kọ tí a kò tíì rí rí?",
      ["Àkàgbóòye (comprehension)", "Àrokò", "Ìtúpalẹ̀ ọ̀rọ̀", "Lítírẹ́ṣọ̀"], "Àkàgbóòye (comprehension)",
      "Comprehension (àkàgbóòye) involves carefully reading an unseen passage to extract main ideas and understand its deeper meaning."),
  _q("Nínú àkàgbóòye, kí ni à ń pè ìdámọ̀ àwọn kókó tí ó fara sin nínú àpilẹ̀kọ, tí kò fi hàn gbangba?",
      ["Ìtumọ̀ jíjìn/àṣírí ọ̀rọ̀ (implicit/deep-seated meaning)", "Kíkà ọ̀rọ̀ ní gbangba nìkan", "Kíka iye ọ̀rọ̀ nìkan", "Wíwo aṣọ ìwé nìkan"], "Ìtumọ̀ jíjìn/àṣírí ọ̀rọ̀ (implicit/deep-seated meaning)",
      "Identifying implicit meaning requires the reader to infer ideas that are suggested by a text but not directly and explicitly stated."),
  _q("Kí ni à ń pè ìdámọ̀ àwọn ọ̀rọ̀ àtijọ́ tàbí ìṣàkàwé ọ̀rọ̀ nínú àkàgbóòye?",
      ["Ìdámọ̀ ọ̀rọ̀ àkànlò-èdè (idiomatic/archaic phrasing identification)", "Ìka ẹsẹ̀ ìwé nìkan", "Kíka orúkọ òǹkọ̀wé nìkan", "Kíka ọjọ́ tí a tẹ ìwé jáde nìkan"], "Ìdámọ̀ ọ̀rọ̀ àkànlò-èdè (idiomatic/archaic phrasing identification)",
      "Identifying idiomatic or archaic phrasing helps the reader decode figurative or older expressions whose meaning may not be obvious from a literal reading."),
  _q("Kí ni ìṣísẹ̀ àkọ́kọ́ tí ó yẹ kí akẹ́kọ̀ọ́ gbé ṣáájú kí ó tó bẹ̀rẹ̀ sí kọ àrokò?",
      ["Ṣíṣe ìtòlẹ́sẹẹsẹ èrò àti ìjìnlẹ̀ òye kókó náà", "Kíkọ láìní ìtòlẹ́sẹẹsẹ kankan", "Gbígbàgbé kókó náà pátápátá", "Ríko iṣẹ́ akẹ́kọ̀ọ́ mìíràn"], "Ṣíṣe ìtòlẹ́sẹẹsẹ èrò àti ìjìnlẹ̀ òye kókó náà",
      "Before writing an essay, it is important to plan and organise one's thoughts, ensuring a clear understanding of the topic to produce a coherent composition."),
  _q("Nínú lẹ́tà oníṣẹ́ẹ́, kí ni ó yẹ kí a kọ ní ìbẹ̀rẹ̀ ìwé, ṣáájú orúkọ ẹni tí a ń kọ sí?",
      ["Àdírẹ́sì ẹni tí ó kọ ìwé àti ọjọ́ tí a kọ ìwé náà", "Ìparí ìwé náà", "Orúkọ ilé-ìwé nìkan", "Owó tí a ń ná"], "Àdírẹ́sì ẹni tí ó kọ ìwé àti ọjọ́ tí a kọ ìwé náà",
      "A formal letter conventionally begins with the sender's address and the date, before the recipient's details and the letter's body."),
  _q("Nínú ìtàn, kí ni à ń pè apá tí ó ń parí gbogbo ìṣẹ̀lẹ̀ tí ó ti ṣẹlẹ̀ nínú ìtàn náà?",
      ["Òpin (conclusion/resolution)", "Ìbẹ̀rẹ̀ nìkan", "Kókó-ọ̀rọ̀ nìkan", "Iye ọ̀rọ̀ nìkan"], "Òpin (conclusion/resolution)",
      "The conclusion (òpin) resolves the events and conflicts developed throughout the narrative, bringing the story to a satisfying end."),
  _q("Nínú àpilẹ̀kọ àbáye, kí ni ó yẹ kí òǹkọ̀wé ṣe láti fún ìdí rẹ̀ lókun?",
      ["Fífúnni ní ìdí àti àpẹẹrẹ tí ó ń fi ìdí èrò rẹ̀ múlẹ̀", "Yíyẹra fún fífúnni ní ìdí kankan", "Kíkọ gbólóhùn tí kò bára mu pẹ̀lú kókó náà", "Ìfojúfo àti ìwádìí èyíkéyìí"], "Fífúnni ní ìdí àti àpẹẹrẹ tí ó ń fi ìdí èrò rẹ̀ múlẹ̀",
      "An effective argumentative essay provides supporting evidence and relevant examples to reinforce the writer's position on a topic."),
  _q("Kí ni à ń pè ìtúpalẹ̀ tí a ń ṣe láti mọ ìdí tí òǹkọ̀wé fi kọ ìwé kan?",
      ["Ìtúpalẹ̀ Ète Òǹkọ̀wé (author's intention analysis)", "Ìka ẹsẹ̀ ìwé nìkan", "Kíka orúkọ ilé-ìwé nìkan", "Kíka iye ọ̀rọ̀ nìkan"], "Ìtúpalẹ̀ Ète Òǹkọ̀wé (author's intention analysis)",
      "Analysing the author's intention involves considering the purpose behind a text and the message the writer aims to convey."),
  _q("Nínú àkàgbóòye, kí ni à ń pè kókó pàtàkì tí ìwé kan gbé kalẹ̀?",
      ["Kókó-ọ̀rọ̀ àkọ́kọ́ (main idea/theme)", "Iye ọ̀rọ̀ nìkan", "Orúkọ òǹkọ̀wé nìkan", "Ọjọ́ tí a tẹ ìwé jáde nìkan"], "Kókó-ọ̀rọ̀ àkọ́kọ́ (main idea/theme)",
      "The main idea or theme of a passage represents its central focus, the primary point the text seeks to communicate to the reader."),
  _q("Kí ni ó yẹ akẹ́kọ̀ọ́ ṣe lẹ́yìn tí ó parí kíkọ àrokò rẹ̀, kí ó tó fi lé olùkọ́ lọ́wọ́?",
      ["Ṣíṣàyẹ̀wò rẹ̀ padà láti tọ́ àwọn àṣìṣe gírámà àti àkọtọ́ sí", "Fífi lé olùkọ́ lọ́wọ́ láìṣàyẹ̀wò padà", "Yíyọ ìpari àrokò náà kúrò", "Ríko iṣẹ́ akẹ́kọ̀ọ́ mìíràn"], "Ṣíṣàyẹ̀wò rẹ̀ padà láti tọ́ àwọn àṣìṣe gírámà àti àkọtọ́ sí",
      "Reviewing one's work before submission helps identify and correct grammatical errors and spelling mistakes, improving overall composition quality."),
  _q("Kí ni à ń pè àwọn ọ̀rọ̀ tí a ń lò láti so èrò pọ̀ ní ọ̀nà tí ó bára mu nínú àrokò, bí í ṣe 'ní àkọ́kọ́', 'lẹ́yìn náà', 'níkẹyìn'?",
      ["Ọ̀rọ̀ Aṣopọ̀-Èrò (transitional/connecting words)", "Ọ̀rọ̀-Àpèjúwe nìkan", "Ọ̀rọ̀-Orúkọ nìkan", "Ọ̀rọ̀-Atọ́kùn nìkan"], "Ọ̀rọ̀ Aṣopọ̀-Èrò (transitional/connecting words)",
      "Connecting words like 'ní àkọ́kọ́' (first), 'lẹ́yìn náà' (then), and 'níkẹyìn' (finally) help organise ideas logically within a composition."),
  _q("Nínú lẹ́tà àjọṣepọ̀, kí ni ìkíni tí ó bára mu jùlọ láti bẹ̀rẹ̀ ìwé sí ọ̀rẹ́?",
      ["Ìkíni onínú-adùn, bí í ṣe 'Ọ̀rẹ́ mi ọ̀wọ́n,'", "Àkọsílẹ̀ owó ilé-iṣẹ́", "Ìkéde ìjọba", "Ìwé àṣẹ ìjọba"], "Ìkíni onínú-adùn, bí í ṣe 'Ọ̀rẹ́ mi ọ̀wọ́n,'",
      "Informal letters to friends typically open with warm, familiar greetings, distinct from the formal openings used in official correspondence."),
  _q("Nínú àpilẹ̀kọ àpèjúwe, kí ni ó yẹ kí òǹkọ̀wé ṣe láti mú kí ohun tí ó ń ṣàpèjúwe hàn kedere sí òǹkàwé?",
      ["Lílo ọ̀rọ̀ tí ó ń fi hàn àwọ̀, ìró, àti bí ohun kan ti rí lára", "Lílo nọ́mbà nìkan láìní àlàyé", "Kíkọ orúkọ òǹkọ̀wé nìkan", "Yíyọ gbogbo àlàyé kúrò"], "Lílo ọ̀rọ̀ tí ó ń fi hàn àwọ̀, ìró, àti bí ohun kan ti rí lára",
      "Effective descriptive writing uses vivid sensory details, such as colours, sounds, and physical sensations, to bring a scene or subject to life for the reader."),
  _q("Nínú ìròyìn, kí ni ó yẹ kí òǹkọ̀wé rí i dájú pé ó jẹ́ nípa ìṣẹ̀lẹ̀ tí a ń ròyìn?",
      ["Òtítọ́ àti pé ó ṣẹlẹ̀ ní tòótọ́", "Àròsọ tí kò sí ní tòótọ́", "Èrò ìkọ̀kọ̀ òǹkọ̀wé nìkan", "Ìtàn àdáyébá láìsí ìṣẹ̀lẹ̀ gidi"], "Òtítọ́ àti pé ó ṣẹlẹ̀ ní tòótọ́",
      "News reports should be based on factual, verifiable events, distinguishing them from fictional narrative writing."),
];

final _asaIseAtiLiteresho = [
  _q("Kí ni à ń pè ààtò ìdálórúkọ ọmọ tuntun, ní àṣà Yorùbá?",
      ["Ìsọmọlórúkọ (naming ceremony)", "Ìgbéyàwó", "Ìsìnkú", "Ìbọ́wọ̀ fún Àgbà"], "Ìsọmọlórúkọ (naming ceremony)",
      "The naming ceremony (ìsọmọlórúkọ) is a traditional Yoruba rite performed to formally give a name to a newborn baby."),
  _q("Kí ni à ń pè ètò ìgbéyàwó ní àṣà Yorùbá, láti ìbéèrè títí dé ìgbéyàwó gan-an?",
      ["Ìgbéyàwó (marriage parameters/customs)", "Ìsọmọlórúkọ", "Ìsìnkú", "Ẹ̀sìn Ìbílẹ̀"], "Ìgbéyàwó (marriage parameters/customs)",
      "Ìgbéyàwó refers to the traditional Yoruba marriage process, including courtship customs and the wedding itself."),
  _q("Kí ni à ń pè ààtò ìdálẹ̀kú àti sísin òkú ní àṣà Yorùbá?",
      ["Ìsìnkú (funeral arrangements)", "Ìsọmọlórúkọ", "Ìgbéyàwó", "Ìbọ́wọ̀ fún Àgbà"], "Ìsìnkú (funeral arrangements)",
      "Ìsìnkú describes the traditional Yoruba customs surrounding death, mourning, and burial."),
  _q("Kí ni à ń pè ìbọ̀wọ̀ àti ìkíni tí a ń fi hàn sí àgbà ní àṣà Yorùbá?",
      ["Ìbọ́wọ̀ fún Àgbà (respect for elders)", "Ìgbéyàwó", "Ìsìnkú", "Ẹ̀sìn Ìbílẹ̀"], "Ìbọ́wọ̀ fún Àgbà (respect for elders)",
      "Ìbọ́wọ̀ fún àgbà reflects the deep cultural value placed on respecting and honouring elders, expressed through specific greetings and conduct."),
  _q("Kí ni ẹ̀sìn ìbílẹ̀ tí ó gbàgbọ́ nínú ọ̀pọ̀lọpọ̀ Òrìṣà àti ètò ìṣàyẹ̀wò Ifá?",
      ["Ẹ̀sìn Ìbílẹ̀ (traditional/Orisa religion)", "Ìgbéyàwó", "Ìsìnkú", "Ìsọmọlórúkọ"], "Ẹ̀sìn Ìbílẹ̀ (traditional/Orisa religion)",
      "Traditional Yoruba religion (ẹ̀sìn ìbílẹ̀) centres on the worship of various Orisa deities and consultation with the Ifa divination system."),
  _q("Nínú ètò ìṣèlú ìbílẹ̀ Yorùbá, kí ni orúkọ oyè tí ó ń tọ́ka sí ọba kan?",
      ["Oba", "Baálẹ̀ nìkan", "Ọlọ́pọ́n", "Ọ̀gá ìjọba nìkan"], "Oba",
      "Oba is the traditional title for a Yoruba king, the paramount ruler of a kingdom or town in the traditional political hierarchy."),
  _q("Nínú ètò ìṣèlú ìbílẹ̀ Yorùbá, kí ni orúkọ oyè tí ó ń tọ́ka sí olórí abúlé tàbí ìlú kékeré tí kìí ṣe ìjọba Oba?",
      ["Baálẹ̀", "Oba nìkan", "Ọ̀ṣọ́rọ̀", "Ògbóni nìkan"], "Baálẹ̀",
      "Baálẹ̀ refers to the head of a smaller settlement or community that does not hold full kingship status."),
  _q("Kí ni ìgbìmọ̀ àwọn ọlọ́lá ìlú tí ó ń ràn Oba lọ́wọ́ láti ṣàkóso ìlú, tí ó sì lè ṣàyẹ̀wò agbára rẹ̀?",
      ["Ọ̀yọ́mèsì", "Ògbóni nìkan", "Baálẹ̀ nìkan", "Ọlọ́pọ́n"], "Ọ̀yọ́mèsì",
      "The Ọ̀yọ́mèsì was a council of chiefs in the traditional Oyo Yoruba political system, holding significant power to check and, in extreme cases, remove the Alaafin."),
  _q("Kí ni ẹgbẹ́ àṣírí tí ó ní ipa pàtàkì nínú ìṣèlú àti ìdájọ́ ìbílẹ̀ láàrin àwọn ìlú Yorùbá kan?",
      ["Ògbóni", "Ọ̀yọ́mèsì nìkan", "Baálẹ̀ nìkan", "Ẹgbẹ́ ọdẹ nìkan"], "Ògbóni",
      "The Ogboni society is a traditional secretive fraternity that historically played a significant judicial and political role in some Yoruba communities."),
  _q("Kí ni orúkọ sáà-níṣẹ́ ìbílẹ̀ tí ó ń kàn iṣẹ́ agbéṣin irin, gẹ́gẹ́ bí ọ̀nà ìgbẹ́mìí àwọn Yorùbá?",
      ["Alágbède (blacksmithing)", "Àgbẹ̀", "Adárosùn", "Ọlọ́pọ́n"], "Alágbède (blacksmithing)",
      "Alágbède refers to the traditional occupation of blacksmithing, a valued craft in Yoruba society."),
  _q("Kí ni orúkọ sáà-níṣẹ́ ìbílẹ̀ tí ó ń kàn iṣẹ́ àgbẹ̀, ọ̀kan lára àwọn iṣẹ́ ìpìlẹ̀ ìbílẹ̀ Yorùbá?",
      ["Àgbẹ̀ (farming)", "Alágbède", "Adárosùn", "Ẹ̀sìn Ìbílẹ̀"], "Àgbẹ̀ (farming)",
      "Àgbẹ̀ refers to farming, one of the most fundamental traditional occupations among the Yoruba people."),
  _q("Kí ni orúkọ sáà-níṣẹ́ ìbílẹ̀ tí ó ń kàn iṣẹ́ ìrọ aṣọ, gẹ́gẹ́ bí ọ̀nà iṣẹ́ ọwọ́ Yorùbá?",
      ["Adárosùn (dyeing)", "Àgbẹ̀", "Alágbède", "Ọlọ́pọ́n"], "Adárosùn (dyeing)",
      "Adárosùn refers to the traditional craft of fabric dyeing, notably associated with indigo (aro) dyeing in Yoruba culture."),
  _q("Kí ni eré ìdárayá ìbílẹ̀ tí a ń fi ìjà ara-ẹni ṣe láàrin ọ̀dọ́mọkùnrin méjì, títí tí ẹnìkan yóò fi ṣubú?",
      ["Ìjakadi (wrestling)", "Ayò", "Ẹ̀sìn Ìbílẹ̀", "Ìsìnkú"], "Ìjakadi (wrestling)",
      "Ìjakadi is a traditional wrestling sport where opponents grapple until one is thrown down, a popular form of Yoruba traditional entertainment."),
  _q("Kí ni eré ìbílẹ̀ tí a ń fi àwọn ìjì kéékèèké àti ihò ṣeré, tí a mọ̀ sí eré ọpọ́n?",
      ["Ayò (ayò ọlọ́pọ́n)", "Ìjakadi", "Adárosùn", "Alágbède"], "Ayò (ayò ọlọ́pọ́n)",
      "Ayò ọlọ́pọ́n is a traditional Yoruba board game played with seeds moved between carved pits, a popular form of intellectual entertainment."),
  _q("Kí ni à ń pè ọ̀rọ̀ kúkúrú tí ó kún fún ọgbọ́n, tí a ń lò láti fi hàn ẹ̀kọ́ ìwà rere ní ọ̀nà kúkúrú?",
      ["Òwe (proverbs)", "Àpèjúwe/Àpóló", "Àwòko/Àlọ́", "Ewì Alẹ́nu"], "Òwe (proverbs)",
      "Proverbs (òwe) are short, wisdom-laden sayings used to convey deep meaning or moral lessons concisely in Yoruba speech."),
  _q("Kí ni à ń pè lílo ọ̀rọ̀ tàbí àpèjúwe tí kì í ṣe ìtumọ̀ tààrà, láti fi ṣàpèjúwe ohun kan ní ọ̀nà arékérekè?",
      ["Àpèjúwe/Àpóló (figures of speech)", "Òwe nìkan", "Àwòko/Àlọ́ nìkan", "Ewì Alẹ́nu nìkan"], "Àpèjúwe/Àpóló (figures of speech)",
      "Figures of speech (àpèjúwe/àpóló) use language creatively, beyond its literal meaning, often for comparison or emphasis."),
  _q("Kí ni à ń pè eré ìbéèrè arọ́wọ́tó tí ó ń jẹ́ kí àwọn èèyàn wá ìdáhùn rẹ̀, ní àṣà Yorùbá?",
      ["Àwòko/Àlọ́ (riddles)", "Òwe", "Àpèjúwe", "Ewì Alẹ́nu"], "Àwòko/Àlọ́ (riddles)",
      "Riddles (àwòko/àlọ́) are traditional oral puzzles designed for entertainment and to sharpen listeners' wit."),
  _q("Kí ni à ń pè oríkì tàbí ewì tí a ń kọ láti ẹnu, gẹ́gẹ́ bí Ìjálá tàbí Ekun Iyawo, láìsí kíkọ sílẹ̀ ní àkọ́kọ́?",
      ["Ewì Alẹ́nu (oral/chanted performance poetry)", "Lítírẹ́ṣọ̀ Olórí-Ìwé", "Òwe nìkan", "Àwòko nìkan"], "Ewì Alẹ́nu (oral/chanted performance poetry)",
      "Chanted oral poetry, such as Ijala (hunters' chants) and Ekun Iyawo (bridal lament), forms a rich tradition of performed verse within Yoruba oral literature."),
  _q("Kí ni à ń pè ìwé tí a kọ sílẹ̀ ní ìrísí ìtàn àròsọ, eré ìtàgé, tàbí ewì tí a kọ sílẹ̀, ní èdè Yorùbá?",
      ["Lítírẹ́ṣọ̀ Olórí-Ìwé (written literature)", "Ewì Alẹ́nu", "Òwe", "Àwòko"], "Lítírẹ́ṣọ̀ Olórí-Ìwé (written literature)",
      "Written literature (lítírẹ́ṣọ̀ olórí-ìwé) refers to literary works recorded in text form, such as novels, plays, and written poetry anthologies."),
  _q("Nínú ìtúpalẹ̀ lítírẹ́ṣọ̀, kí ni à ń pè kókó pàtàkì tí ìwé kan gbé kalẹ̀ láti ẹnu sí ẹnu?",
      ["Kókó-ọ̀rọ̀ (theme)", "Ẹni-kọ̀wé nìkan", "Ibi ìṣẹ̀lẹ̀ nìkan", "Àkọsílẹ̀ ọjọ́ nìkan"], "Kókó-ọ̀rọ̀ (theme)",
      "The theme of a literary work is the central message or idea that the author conveys throughout the text."),
  _q("Nínú ìtúpalẹ̀ lítírẹ́ṣọ̀, kí ni à ń pè ẹni tí ó wà nínú ìtàn, pẹ̀lú ìwà rẹ̀ àti ipa tí ó kó nínú ìtàn náà?",
      ["Ẹni-kọ̀wé/Ẹni-nínú-ìtàn (character)", "Kókó-ọ̀rọ̀ nìkan", "Ibi ìṣẹ̀lẹ̀ nìkan", "Ìlànà nìkan"], "Ẹni-kọ̀wé/Ẹni-nínú-ìtàn (character)",
      "A character is a person portrayed within a literary work, defined by their traits, actions, and role in the story."),
  _q("Nínú ìtúpalẹ̀ lítírẹ́ṣọ̀, kí ni à ń pè ibi àti àkókò tí ìṣẹ̀lẹ̀ inú ìtàn kan wáyé?",
      ["Ibi ìṣẹ̀lẹ̀ (setting)", "Kókó-ọ̀rọ̀ nìkan", "Ẹni-nínú-ìtàn nìkan", "Ìlànà nìkan"], "Ibi ìṣẹ̀lẹ̀ (setting)",
      "Setting refers to the time and place in which a story's events unfold."),
  _q("Kí ni à ń pè iṣẹ́ ìbílẹ̀ tí ó jẹ mọ́ ìtọ́jú ẹran-ọ̀sìn àti oko ní àṣà Yorùbá?",
      ["Ọ̀gbìn àti Ẹran ọ̀sìn (agriculture and animal husbandry)", "Alágbède nìkan", "Adárosùn nìkan", "Ẹ̀sìn Ìbílẹ̀ nìkan"], "Ọ̀gbìn àti Ẹran ọ̀sìn (agriculture and animal husbandry)",
      "Agriculture and animal husbandry have traditionally formed an important part of the Yoruba economy, alongside crafts like weaving and dyeing."),
  _q("Kí ni ètò ìjọba ìbílẹ̀ ti ìlú Yorùbá kan (bí Ọ̀yọ́) ń pè ìgbìmọ̀ tí ń ràn Oba lọ́wọ́ nínú ìdájọ́ àti ìṣèlú, tí ó yàtọ̀ sí Ọ̀yọ́mèsì?",
      ["Ògbóni (a parallel judicial/political council)", "Ọ̀yọ́mèsì nìkan", "Baálẹ̀ nìkan", "Ọlọ́pọ́n nìkan"], "Ògbóni (a parallel judicial/political council)",
      "Alongside the Ọ̀yọ́mèsì, the Ogboni society traditionally served an important, sometimes overlapping, judicial and political function in some Yoruba towns."),
  _q("Kí nìdí tí ìkẹ́kọ̀ọ́ àṣà (culture) fi ṣe pàtàkì gẹ́gẹ́ bí apá kan nínú ìkẹ́kọ̀ọ́ èdè Yorùbá?",
      ["Kí àwọn akẹ́kọ̀ọ́ lè lóye ìṣe àti ìrònú àwọn ará Yorùbá pọ̀ mọ́ èdè wọn", "Kí àwọn akẹ́kọ̀ọ́ lè kọ ìṣirò", "Kí àwọn akẹ́kọ̀ọ́ lè kọ èdè mìíràn tí kò jẹ mọ́ Yorùbá", "Kí àwọn akẹ́kọ̀ọ́ lè gbàgbé àṣà ìbílẹ̀ wọn"], "Kí àwọn akẹ́kọ̀ọ́ lè lóye ìṣe àti ìrònú àwọn ará Yorùbá pọ̀ mọ́ èdè wọn",
      "Studying culture alongside language helps students understand the social practices and worldview of the Yoruba people, deepening their linguistic competence."),
  _q("Kí ni à ń pè ìtàn àròsọ tí a ń kọ láti ẹnu sí ẹnu, tí ó jẹ́ kún fún ẹ̀kọ́ ìwà rere ní àṣà Yorùbá?",
      ["Àlọ́ Àpagbè (folktales)", "Òwe nìkan", "Àwòko nìkan", "Ewì Alẹ́nu nìkan"], "Àlọ́ Àpagbè (folktales)",
      "Folktales are traditional oral stories, often conveying moral lessons, passed down through generations among the Yoruba."),
  _q("Kí ni à ń pè ìlànà tí a ń tẹ̀lé láti ṣàyẹ̀wò ìwé lítírẹ́ṣọ̀ kan fún kókó-ọ̀rọ̀ àti ọgbọ́n inú rẹ̀?",
      ["Ìtúpalẹ̀ Lítírẹ́ṣọ̀ (literary analysis/criticism)", "Ìtúmọ̀ ọ̀rọ̀ nìkan", "Àkàgbóòye nìkan", "Fonọ́lọ́jì nìkan"], "Ìtúpalẹ̀ Lítírẹ́ṣọ̀ (literary analysis/criticism)",
      "Literary analysis involves closely examining a text's themes, characters, and structure to deepen understanding of the author's work."),
  _q("Kí ni ipa tí àwọn baba ńlá (ancestors) kó nínú ìgbàgbọ́ ẹ̀sìn ìbílẹ̀ Yorùbá?",
      ["A gbà pé wọ́n ń bójútó ìdílé wọn láti ayé mìíràn, a sì ń bọ̀wọ̀ fún wọn", "Wọn kò ní ipa kankan nínú ìgbàgbọ́ ìbílẹ̀", "Wọ́n jẹ́ ọ̀tá àwọn Òrìṣà", "A kò rántí wọn rárá"], "A gbà pé wọ́n ń bójútó ìdílé wọn láti ayé mìíràn, a sì ń bọ̀wọ̀ fún wọn",
      "Ancestral reverence forms an important part of traditional Yoruba belief, with ancestors regarded as continuing to watch over and guide their families."),
  _q("Kí ni à ń pè oríkì tí a ń kọ fún ọmọ ọba tàbí ìdílé pàtàkì kan, gẹ́gẹ́ bí ara oríkì ìbílẹ̀ Yorùbá?",
      ["Oríkì (praise poetry)", "Òwe nìkan", "Àwòko nìkan", "Ìtàn àròsọ nìkan"], "Oríkì (praise poetry)",
      "Oríkì (praise poetry) celebrates the qualities, lineage, and achievements of an individual or family, a significant form of Yoruba oral literature."),
  _q("Kí ni à ń pè ìpìlẹ̀ ìṣàkóso ìbílẹ̀ Yorùbá tí ó gbé ọ̀wọ̀ àti ipò lélẹ̀ gẹ́gẹ́ bí a ti ń jogún oyè láti ìran dé ìran?",
      ["Ìṣàkóso oyè àbínibí (hereditary chieftaincy structure)", "Ìjọba tiwantiwa lóde òní nìkan", "Ìjọba ológun nìkan", "Àìsí ìjọba rárá"], "Ìṣàkóso oyè àbínibí (hereditary chieftaincy structure)",
      "Traditional Yoruba political structures are often built around hereditary chieftaincy, with royal titles and positions passed down through specific lineages."),
];
