// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNNZqKZovbJZOB-u6-UlkNDwqgLG6b9sI',
    appId: '1:734285493928:web:ef4dd3fa2f41a1fa38749d',
    messagingSenderId: '734285493928',
    projectId: 'exam-prep-ng',
    authDomain: 'exam-prep-ng.firebaseapp.com',
    storageBucket: 'exam-prep-ng.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcW02I86HdaPwPfbSIyCTOpp0cE0xaTGY',
    appId: '1:734285493928:android:fe940beec1a9baa038749d',
    messagingSenderId: '734285493928',
    projectId: 'exam-prep-ng',
    storageBucket: 'exam-prep-ng.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd9r9K4qTNMou4UrhYQFt7pvLj6qCYHVE',
    appId: '1:734285493928:ios:2ce70288e6d643d338749d',
    messagingSenderId: '734285493928',
    projectId: 'exam-prep-ng',
    storageBucket: 'exam-prep-ng.firebasestorage.app',
    iosBundleId: 'com.example.examPrep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd9r9K4qTNMou4UrhYQFt7pvLj6qCYHVE',
    appId: '1:734285493928:ios:2ce70288e6d643d338749d',
    messagingSenderId: '734285493928',
    projectId: 'exam-prep-ng',
    storageBucket: 'exam-prep-ng.firebasestorage.app',
    iosBundleId: 'com.example.examPrep',
  );
}
